### ISSUE TITLE
Punchlist of effects caused by upgrades

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#10]
**Task:** Draft punchlist of what will be broken following upgrades

**Acceptance Criteria:**
- Publicly available document in the Github wiki: https://github.com/fecgov/fecfile-online/wiki
- In that document, we should outline known issues that require further remediation following technology upgrades for, at least:
  - Angular
  - Django
  - Postgres
- Create new issues for remaining items in the github repo: https://github.com/fecgov/fecfile-online/issues
 

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by alexander-lin** [comment]
For Sprint Review: Al will review status based on document.

**Comment by albertcrowley** [comment]
I have created a wiki page here: https://github.com/fecgov/fecfile-online/wiki/Repository-Upgrade-Punchlist

**Comment by WiseQA** [comment]
Closed Ticket - complete.
