### ISSUE TITLE
1 - Allow user to enter Loan Received from Individual on Schedule C - Step 1

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1000]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Loan Received from Individual”** transaction on Schedule C of a Form 3X report so that I can accurately report on my committee's transactions.

NOTE: This transaction will also create a "Loan Received from Individual" transaction on Schedule A

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a Loans and Debts
**Then** I can enter a transaction with the type “Loan Received from Individual"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Lender Information
-	**LENDER LOOKUP**
Dropdown: Individual, Organization, Committee 
**Note** Default to Individual
 
---
_if LENDER TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if LENDER TYPE = Committee_
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

---
_if LENDER TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Loan Information 
#
-	**ORIGINAL AMOUNT** (AMT-12, Required)
-	**PAYMENT TO DATE** (AMT-12, Required) (Should be $0 and read-only)
-	**BALANCE OUTSTANDING** (AMT-12, Required) (Should be same as Original Amount and read-only)
-	**MEMO ITEM** (Optional)

# Terms 
#
-	**DATE INCURRED** (Required)**
-	**DUE DATE** (BLANK and read-only, implementation deferred until #1156)
-	**INTEREST RATE** (BLANK and read-only, implementation deferred until #1156)
-	**SECURED** (Checkbox, Required)

# Additional information 
#
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Cancel
- Add C2 – Loan Guarantor (See #1012)
- Save **(When this is Saved, a 'Loan Received from Individual' transaction is created on Schedule A - see #1002)**
- Edit

Note: this cannot be saved without #1002.

 QA Note
- Payment to Date and Balance Outstanding will be uneditable, and auto-calculation implementation deferred until #1103.
- Note that Loan Due Date and Loan Interest Rate fields will _not_ be implemented with this ticket, and will be implemented with #1156.
- Button to "Add Loan Guarantor" will be a dead link until implementation of #1012.

 Dev Note 

- Note that Loan Due Date and Loan Interest Rate fields will _not_ be implemented with this ticket, and will be implemented with #1156.
- Button to "Add Loan Guarantor" will be a dead link until implementation of #1012.
- Payment to Date and Balance Outstanding will be uneditable, and auto-calculation implementation deferred until #1103.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1H1zZmpkhUrKqe25OShtQrgbH1TrhIOSxvI1ZOM-Fw9Y/edit#gid=0)  **Please note this is a consolidated specification.** 
- [x] 

 UX Updates
**Changes  per Jonella**

- [x] **Update text under page title to** 
- Saving a loan received from individual will automatically create a related receipt.
 <br>      
- [x] **Update text top accordion to**
- ENTER DATA: Enter lender, loan, and terms information for a loan received from individual
<br>
- [x] **Change Amount (Original) to Original Amount in the Loan information section**
<br>
- [x] **Change prompt text above second accordion section**
- The information in this loan will automatically create a related receipt. Review the receipt;  enter a 
purpose of receipt or note/memo text; or continue without reviewing and “Save transactions.” 
<br>
- [x] **Update text bottom accordion to**
- AUTO-POPULATED: Review information and enter purpose of description or note/memo text

 Wireframe
![1000 - Loan Received From Individual - UPDATED.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/64c04b30-bcfb-4488-bc8b-e8612146776d)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand
I'm attaching the wire here to review. Once approved I will move up by ACs

 ![1000 - Loan Received From Individual - 2 – 1.png]
(https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f262b460-1c96-4ec3-885e-078035f6fc7d)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Updated wire
![1000 - Loan Received From Individual - 2 – 1.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/03948084-dba1-4f1f-b572-5e9286c705be)

**Comment by mjtravers** [comment]
Sending back to In Progress to update text changes on form.

**Comment by MitchellTCG** [comment]
@mjtravers 
please review updates in the UX updates section under the ACs

**Comment by mjtravers** [comment]
Requested UX updates made. Moving ticket back to CR.

**Comment by toddlees** [comment]
Finished with CR moving to QA with step 2 & 3

**Comment by WiseQA** [comment]
QA review verified when selecting "Add Loans and Debts" then select "Loans" dropdown, then select Loan Received from Individual transaction page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/057b798a-167c-41b7-8a30-5c0aecf0db9a)

Lender type is defaulted to Individual.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9a36771e-5b6a-4512-9375-0970f79a7215)

Verified Loan Received from Individual is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e14f8bcc-e1a4-4f34-b4d8-3b6600b324a9)

Verified "Original Amount" is a required field.  "Payment to Date" is $0.00 and read-only.  "Balance Outstanding" is read-only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/58117c1f-8aae-426c-a5fa-fe6aad8af87e)

Verified when entering dollar amount for "Original Amount"  the "Balance Outstanding" field is updated with the same amount.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/97204725-7474-4d2d-b45c-49ed90ee8efa)

Verified Memo Item (Optional) with help text icon is displayed.  (Note:  The word (Optional) has been missing in Schedule A and B tickets - updated in Schedule C)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/08f25c35-fca7-485b-a4a6-a4c27e0f6603)

### Below Reasons Sending Back to In-progress ### 

Per review with @mjtravers the Just Checking popup is not valid for this ticket and will be disabled.  Ticket #1177 address the date rules for Schedule C.   The Just Checking popup once transaction is saved redisplays on the transaction page when opening and you have to select "Close" to proceed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/43ce5093-0e28-49ee-9ea3-2e6f002514b8)

@mjtravers @MitchellTCG need clarification if the + and - symbols need added to this transaction page as denoted in wireframe.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0e879463-b3e0-446c-8106-977cce0f8266)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/124eb400-6147-4434-91a1-2fef6ae73684)

**Change Lender Type to Lender Lookup (AC has been updated to reflect correct naming)**

@mjtravers returned to In-Progress for the "Just Checking" disable.

**Comment by MitchellTCG** [comment]
The look and feel of the accordion is not part of this ticket. Ignore the + and -.

**Comment by MitchellTCG** [comment]
Change Lender type to Lender Lookup

**Comment by mjtravers** [comment]
The "Just Checking..." pop up has been disabled and the LENDER TYPE label updated to LENDER LOOKUP. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review retested when selecting "Add Loans and Debts" then select "Loans" dropdown, then select Loan Received from Individual transaction page is displayed.

Verified Just Checking popup has been disabled.    

Verified LENDER TYPE labeled changed to LENDER LOOKUP

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8c069b55-83b7-4431-8b96-eb0182716025)

Once "Saved" verified "Loan Received from Individual" is displayed under the Loans and Debts Transactions.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/256d2814-40d6-4d4f-ae0f-cb1026541171)

QA Review Completed.   Moved to Stage Ready.
