### ISSUE TITLE
1 - System to auto-generate Loan Received from Individual on Schedule A  (STEP 2)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1002]
Business Reason 
 

As a Committee Administrator, I will be able to view a **”Loan Received from Individual”** transaction on Schedule A while creating the associated Schedule C Loan on a Form 3X report so that I can know what receipt will be saved.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing a **”Loan Received from Individual”** transaction on Schedule C
**Then** I will be able to view the auto-generated **”Loan Received from Individual”** receipt that will be saved when I save the Schedule C Loan with the following information: 

---

 Contact 
#
Dropdown: Individual, Organization, Committee
**Note** auto-generated from associated LOAN_RECEIVED_FROM_INDIVIDUAL
 
---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required, auto-generated from associated LOAN_RECEIVED_FROM_INDIVIDUAL)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required, auto-generated from associated LOAN_RECEIVED_FROM_INDIVIDUAL)

---
_if CONTACT TYPE = Individual_ 

-	**LAST NAME** (Required, auto-generated from associated LOAN_RECEIVED_FROM_INDIVIDUAL)
-	**FIRST NAME** (Required, auto-generated from associated LOAN_RECEIVED_FROM_INDIVIDUAL)
-	**MIDDLE NAME** (Optional, auto-generated from associated LOAN_RECEIVED_FROM_INDIVIDUAL)
-	**PREFIX** (Optional, auto-generated from associated LOAN_RECEIVED_FROM_INDIVIDUAL)
-	**SUFFIX** (Optional, auto-generated from associated LOAN_RECEIVED_FROM_INDIVIDUAL)

# Address 
#
-	**STREET ADDRESS** (Required, auto-generated from associated LOAN_RECEIVED_FROM_INDIVIDUAL)
-	**APARTMENT, SUITE, ETC.** (Optional, auto-generated from associated LOAN_RECEIVED_FROM_INDIVIDUAL)
-	**CITY** (Required, auto-generated from associated LOAN_RECEIVED_FROM_INDIVIDUAL)
-	**STATE/PROVINCE** (Required, auto-generated from associated LOAN_RECEIVED_FROM_INDIVIDUAL)
-	**ZIP/POSTAL CODE** (Required, auto-generated from associated LOAN_RECEIVED_FROM_INDIVIDUAL)

# Receipt information 
#
-	**DATE** (Required, auto-generated from associated LOAN_RECEIVED_FROM_INDIVIDUAL)
-	**MEMO ITEM** (Optional, auto-generated from associated LOAN_RECEIVED_FROM_INDIVIDUAL)
-	**AMOUNT** (Required, can be negative, auto-generated from associated LOAN_RECEIVED_FROM_INDIVIDUAL)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (CONTACT) 
-- within Aggregation Group of "GENERAL"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF RECEIPT** (Optional)
-	**NOTE OR MEMO TEXT** (Optional)

**Then** I will be able to:
- Cancel
- Save

**And** both transactions will be itemized upon saving and saved with their own line items on the *.fec file:
- Loan Received from Individual (Schedule C) will be saved as SC/10
- Loan Received from Individual (Schedule A) will be saved as SA13.
 
**And** the user can access the SC loan and the SA transaction by clicking on them in the "Loans and Debts" and "Receipts" transaction tables, respectively.

 QA Note
- The only editable fields are Purpose of Receipt and Note/Memo Text. Everything else is auto-generated from the SC parent loan.

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=841846951)  

 WIREFRAME 
![1002 - Loan Received From Individual - 2.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/05e53045-aa1a-49c8-8678-dea885113fbf)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand
I'm attaching the wire here to review. Once approved I will move up by ACs

![1002 - Loan Received From Individual - 2.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/646f7fc5-90e7-4ff9-beb9-9b379d127c51)

**Comment by mjtravers** [comment]
Sending back to In Progress to update text changes on form.

**Comment by mjtravers** [comment]
Requested UX updates made. Moving ticket back to CR.

**Comment by toddlees** [comment]
Finished with CR moving to QA with step 1 & 3

**Comment by WiseQA** [comment]
On-hold until ticket 1000 updated.

**Comment by WiseQA** [comment]
QA review the MEMO ITEM label is incorrect.     Change to MEMO ITEM (OPTIONAL) (then help text icon).   Acceptance Criteria to be updated to match Wireframe showing correct label name.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0bde2a00-9f18-4038-8260-c9f8f0acb0cd)

@mjtravers @MitchellTCG returning to In-Progress for this fix.

**Comment by mjtravers** [comment]
The (OPTIONAL) suffix to the MEMO ITEM checkbox label will be fixed in ticket #1119. Sending #1002 back to QA.

**Comment by WiseQA** [comment]
QA review when selecting the auto populated Loan Received from Individual (Schedule A) from the transactions table:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a18cbec7-5f3d-4ad0-8362-d442b1e25c8b)

The Transactions page displayed show the name as "Loan Received from Individual"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c7709bb9-757e-43d7-a3ee-f91c024de836)

The name should be "Receipt" as denoted in Wireframe.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cc567059-6d9a-40ed-a8e5-e8052ee0ceed)

@mjtravers @MitchellTCG returning to In-Progress for transaction name change on Schedule A Loan Received from Individual transaction.

**Comment by mjtravers** [comment]
Fix made to rename "Loan Received from Individual" to "Receipt". Passes CR. Back in QA.

**Comment by WiseQA** [comment]
QA review retested.  Pre-requisite a "Loan Received from Individual" transaction is created and displayed in the Transactions table under the Loans and Debts.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/42d1ffdc-4d50-4341-897d-391769b7e560)

Verify "Loan Received from Individual" transaction is auto populated and displayed in the Transactions table under Receipts.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/022515ce-3bd1-4dfd-a9cc-93de3eab572f)

Select the "Loan Received from Individual" transaction from Receipts.   Verify "Receipt" transaction has been auto populated and field are read-only.   (Note:  Verified fields were populated correctly from the Loan transaction)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/eb8d9b75-da27-46bf-8e4c-da43a2538678)

QA Review Completed.   Moved to Stage Ready.
