### ISSUE TITLE
3 - System to auto-generate Loan Received From Bank on Schedule A (STEP 3)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1005]
Business Reason 
 

As a Committee Administrator, I will be able to view a **”Loan Received from Bank”** transaction on Schedule A while creating the associated Schedule C Loan on a Form 3X report so that I can know what receipt will be saved.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing a **”Loan from Bank”** transaction on Schedule C
**Then** I will be able to view the auto-generated **”Loan Received from Bank”** receipt that will be saved when I save the Schedule C Loan with the following information: 

---

 Contact 
#
-	**CONTACT TYPE**
-Organization Only, auto-generated from associated LOAN_RECEIVED_FROM_BANK
-	**ORGANIZATION NAME** (Required, auto-generated from associated LOAN_RECEIVED_FROM_BANK)

# Address 
#
-	**STREET ADDRESS** (Required, auto-generated from associated LOAN_RECEIVED_FROM_BANK)
-	**APARTMENT, SUITE, ETC.** (Optional, auto-generated from associated LOAN_RECEIVED_FROM_BANK)
-	**CITY** (Required, auto-generated from associated LOAN_RECEIVED_FROM_BANK)
-	**STATE/PROVINCE** (Required, auto-generated from associated LOAN_RECEIVED_FROM_BANK)
-	**ZIP/POSTAL CODE** (Required, auto-generated from associated LOAN_RECEIVED_FROM_BANK)

# Expenditure Information 
#
-	**DATE** (Required, auto-generated from associated LOAN_RECEIVED_FROM_BANK)
-	**MEMO ITEM** (Optional, auto-generated from associated LOAN_RECEIVED_FROM_BANK))
-	**AMOUNT** (Required, auto-generated from associated LOAN_RECEIVED_FROM_BANK)
-	AGGREGATE (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (CONTACT) 
-- within Aggregation Group of "GENERAL"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF RECEIPT** (Optional)
-	**NOTE OR MEMO TEXT** (Optional)

**Then** I will be able to:
- Cancel
- Save transactions

**And** both transactions will be itemized upon saving and saved with their own line items on the *.fec file:
- Loan Received from Bank (Schedule C) will be saved as SC/10 and available to view/edit from Loans and Debts transaction section.
- Loan Agreement (C1) will be saved as SC1/10
- Loan Received from Bank (Schedule A) will be saved as SA13 and available to view/edit from Receipts transaction section.

 QA Note
- Note that the Purpose of Receipt and the Note or Memo Text fields are editable.

 Dev Note 

- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1471552815)  

 Wireframe
![1005 - Loan Received From Bank on Schedule A.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7f3453a8-5587-41eb-aebf-8ea37dc7cf08)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
lets review tomorrow
![1005 - Loan Received from Bank.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/838dab82-b3d6-41a9-9b98-2c3b6e872054)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Here is an updated version
![1005 - Loan Received From Bank on Schedule A.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/5e325de2-243a-43ab-bf3e-e871b915cd4a)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG wire approved.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the Loan Received from Bank (schedule A) receipt is auto-populated and displayed in the Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6ba899ca-bd6e-406c-aff2-61663287de89)

Verified Purpose of Receipt and Note or Memo Text fields are (Optional) editable and savable.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b3b8ed25-c899-4696-b520-d23bb139b4fe)

**Comment by WiseQA** [comment]
QA retested the Loan Received from Bank (schedule A) receipt is auto-populated and displayed in the Transactions table.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc01TIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7eefd8af198ce5067bdbce5463275b2300ba092f/image.png)

Verified label changed from Receipt to Loan Receipt per wireframe: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1VTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cc5aa164627d6094e17374f9533313e6355f48cb/image.png)

Verified text in text boxes were corrected per wireframe:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1lTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ef5ff3df4e4360513c35d1ad69508b8f714fc556/image.png)

QA Review Completed.   Moved to Stage Ready.
