### ISSUE TITLE
Defect - Manage reports page +Create a new report button is not working when selecting "X" to close out of Select form type popup window

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1008]
This defect is being written for when on Manage Reports page after selecting + Create a new report button the X out of popup window cannot select the + Create a new report button again.

1\. Select Reports from the dashboard

  2\. Manage reports page is displayed

  3\. Select + Create a new report button

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1f882f1b-bcfb-4a4a-a18a-529b65cf9249](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1f882f1b-bcfb-4a4a-a18a-529b65cf9249))

4\. Popup window "Select form type" is displayed

  5\. Select the "X" in the upper right hand corner to close the popup window

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c00fe393-61bd-4c54-bb53-1b0deea2440f](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c00fe393-61bd-4c54-bb53-1b0deea2440f))

6\. Manage reports page is redisplayed

  7\. Select + Create a new report button again, the button is dead, and will not redisplay the "Select form type" popup menu

Verified this error with @Elaine-Krauss-TCG and pointed at 2 points for fix.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-810](https://fecgov.atlassian.net/browse/FECFILE-810)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by MitchellTCG** [comment]
@mjtravers 
please change the Manage reports font to 32px Gandhi-bold

**Comment by mjtravers** [comment]
CSS style updated for Manage reports text. Passes CR and deployed to DEV. Ready for QA.

**Comment by WiseQA** [comment]
1.  Select Reports from the dashboard
2.  Manage reports page is displayed
3.  Select + Create a new report button

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f6f02ad6-1221-43ad-bc10-4aba254290fe)

4.  Popup window "Select form type" is displayed
5.  Select the "X" in the upper right hand corner to close the popup window

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c00fe393-61bd-4c54-bb53-1b0deea2440f)

6.  Manage reports page is redisplayed
7.  Select + Create a new report button again, the button is activated and the Popup window "Select form type" is displayed

Defect passes QA review.   Moved to Stage Ready.
