### ISSUE TITLE
3 - Allow user to create C1 - Loan Agreement for Loan Received from Bank (STEP 2)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1011]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Loan Agreement”** transaction sub-transaction under **”Loan Received From Bank”** on Schedule C of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a **Loan Received From Bank** transaction on an open report
**Then** I will be required to enter the following transaction:

---

 Lender 
#
-	**ORGANIZATION NAME** (Required, auto-generated from LOAN_RECEIVED_FROM_BANK)

# Address 
#
-	**STREET ADDRESS** (Required, auto-generated from LOAN_RECEIVED_FROM_BANK)
-	**APARTMENT, SUITE, ETC.** (Optional, auto-generated from LOAN_RECEIVED_FROM_BANK)
-	**CITY** (Required, auto-generated from LOAN_RECEIVED_FROM_BANK)
-	**STATE/PROVINCE** (Required, auto-generated from LOAN_RECEIVED_FROM_BANK)
-	**ZIP/POSTAL CODE** (Required, auto-generated from LOAN_RECEIVED_FROM_BANK)

# Loan Information 
#
-	**ORIGINAL AMOUNT** (Required, auto-generated from LOAN_RECEIVED_FROM_BANK)
-	**DATE INCURRED** (Required, auto-generated from LOAN_RECEIVED_FROM_BANK)
-	**DUE DATE** (Required, auto-generated from LOAN_RECEIVED_FROM_BANK)
-	**INTEREST RATE %** (Required, auto-generated from LOAN_RECEIVED_FROM_BANK)

- **LOAN RESTRUCTURED** (YN Checkbox, Required)
- **DATE OF ORIGINAL LOAN** (Required if Loan Restructured = Y)
- **CREDIT AMOUNT THIS DRAW** (AMT-12, Optional)
- **TOTAL BALANCE** (Required if CREDIT AMOUNT THIS DRAW is populated)
- **OTHERS LIABLE** (YN Checkbox, Required)

# Collateral 
#
-	**COLLATERAL** (YN Checkbox, Required)
-	**COLLATERAL DESCRIPTION** (A/N-100, Required if COLLATERAL = Y)
-	**COLLATERAL AMOUNT** (AMT-12, Required if COLLATERAL = Y)
-	**PERFECTED INTEREST** (YN Checkbox, Optional)

# Future Income 
#
-	**FUTURE INCOME** (YN Checkbox, Required)
-	**DESCRIPTION** (A/N-100, required if FUTURE INCOME =Y )
-	**ESTIMATED VALUE** (AMT-12, required if FUTURE INCOME =Y )
-	**DEPOSITORY ACCOUNT ESTABLISHED** (Date, required if FUTURE INCOME =Y)
-	**LOCATION OF ACCOUNT** (Org only, NEEDS LOOKUP, required if FUTURE INCOME =Y)
-	**STREET  1** (required if FUTURE INCOME =Y)
-	**STREET  2** (optional if FUTURE INCOME =Y)
-	**CITY** (required if FUTURE INCOME =Y)
-	**STATE** (required if FUTURE INCOME =Y)
-	**ZIP** (required if FUTURE INCOME =Y)

#  Basis of Loan 
#
-	**DESCRIPTION** (A/N-100, Optional)

#  Committee Treasurer 
#

**and** the user will be allowed to enter the following:
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

-	**DATE SIGNED** (Required)

# Authorized Representative 
#
**and** the user will be allowed to enter the following:
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)
- **TITLE** (Required)
-	**DATE SIGNED** (Required)

---
**Then** I will be able to:
- Cancel
- Edit
- Save transactions (must be saved with #1003 and #1005)

**and** when the associated SC loan is saved, then the Loan Agreement will be saved with the Form Type SC1/10.

 QA Note
- There are NO LOOKUPS for Treasurer or Authorized Representative.

 Dev Note 

- ToolTip for "Location of Account" is _inactive_ for this ticket, but icon should be present.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1H1zZmpkhUrKqe25OShtQrgbH1TrhIOSxvI1ZOM-Fw9Y/edit#gid=661269970)
- [x] There are NO LOOKUPS for Treasurer or Authorized Representative.
- [x] Disable the "Just checking ..." memo code date pop-up by adding this line to the transaction type: override doMemoCodeDateCheck = false;
  

 Wireframes

# Main Wireframe
![1011 - Loan Received from Bank – Loan Agreement.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/c9124823-3680-46bb-b236-13264136631c)

# Terms
![1011 Terms.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/2128be5f-7bba-4dbf-a9ff-b30304b6871f)

# Terms / Credit Draw
![1011 Terms – Credit Amount this Draw.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/487679e6-b0bd-4a91-8613-eaf47375bd6e)

# Other Liable
![1011 Others liable.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/94ec7eab-4f09-45ae-b073-5a6d9474099c)

# Other Liable (Error All radio errors will look like this)
![1011 Others liable – Error.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/56595132-455a-4c0a-9ecb-8684a41d7fbd)

# Collateral
![1011 Collateral.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/c643bd8b-7910-47ed-8a49-b63d97253d67)

# Future income
![1011 Future income.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/bf2a7fd4-2d6e-4ce3-b1d6-87a748cb33f4)

# Future income / Location of account
![1011 Future income – Location of account.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/9b245981-d1d1-42ba-a5f0-5761c35cdaad)

# Future income / Location of account - TOOLTIP
![1011 Future income – Toolitp.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a5e03e64-bd93-4a8a-a2b8-81b1d7c79ad3)

# Committee Treasurer
![Screenshot 2023-07-24 at 2.09.22 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7419a247-b3a3-4c4b-995a-6c6138386f6a)

# Authorized Representative
![Screenshot 2023-07-24 at 2.08.17 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/e9c391c2-5db2-4f19-8f1c-94b71b6c64d7)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Let review this in the afternoon. 
![1011 - Loan Received from Bank.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/211f1a8b-5cca-4794-aa16-7cd234f65ecc)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Please review. I made the updates from 66 and posted the wires here.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by toddlees** [comment]
Loan restructured should be required and credit should be optional.  
Patch will be put on stage to update the labels.  restructured will no longer have (OPTIONAL) and credit will have (OPTIONAL)
>LOAN RESTRUCTURED (YN Checkbox, Required)
>CREDIT AMOUNT THIS DRAW (AMT-12, Optional)

![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/2b2429ee-f0ea-497f-9d6b-e0c0b1f0b677)

**Comment by toddlees** [comment]
above has been addressed:
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/a1b99e78-e4b7-414e-804e-907701a973de)

**Comment by WiseQA** [comment]
QA review verified (Optional) been removed from "Has loan been restructured?"

**NOTE COMMENT BELOW OBE AS LABEL NAMES CONFIRMED 8/16/2023 AND DOCUMENTED BELOW IN COMMENT.**
Verified Date Originally Incurred becomes a required field if Yes is selected.    (NOTE:  AC has text as =
DATE OF ORIGINAL LOAN (Required if Loan Restructured = Y).  However, text for this field is "DATE ORIGINALLY INCURRED" (see wireframe).   Tested using this name. @AureliaKhorsand @GreggMoreland FYI if you want to change AC - thanks

**Comment by WiseQA** [comment]
QA review verified radio buttons are displayed as designed per wireframe.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/397d4882-e509-426a-b959-9d64eb6c0c9c)

Verified when selecting "Yes" radio button under "Others liable" the following text is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/00592d70-c54e-4743-b540-ece665da68c5)

Verified when selecting "Yes" radio button under "Collateral" the following required text boxes are displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0fd0e988-0641-4bc2-ab7f-ef4c335a43c6)

Verified when selecting "Yes" radio button under "Future Income" the following required text boxes are displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8eff4f5b-7ede-48de-882d-48079cd39eb0)

(NOTE: Retested contact window popups functionality is working correctly)

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers "Location of Account" does have the tooltip.  But when I bypass this section then try to save doesn't show me "This is a required field".   Add "This is a required field" upon save.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b70b8243-d301-47c3-b15c-d82e46b9f5f2)

@MitchellTCG @mjtravers added this fix to ticket #1164 after verifying with Todd the same code is being used for this field as what is being developed in #1164.  Will retest this once #1164 is pushed through.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
FYI (for the demo)
BA's Please be aware of the known issue above that will be resolved in ticket #1164 in Sprint 30.

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG @AureliaKhorsand during a side discussion (QA not involved), the following decisions were made from the BA's (Note:  Wireframe needs updated to reflect changes)

Per @mjtravers - Ok, all set on STAGE. Per Aurelia's instructions, the labels were changed to match the acceptance criteria: DATE OF ORIGINAL LOAN and TOTAL BALANCE.   Wireframe verbiage not to be used.
The (OPTIONAL) was added to the CREDIT AMOUNT THIS DRAW

**Comment by WiseQA** [comment]
QA verified the following changes were made on the Loan Agreement per above statement.  (Wireframe needs updated to reflect these changes)

1.  Changed label from DATE ORIGINALLY INCURRED to DATE OF ORIGINAL LOAN
2.  Changed label from TOTAL OUTSTANDING BALANCE to TOTAL BALANCE
3.  Changed label from CREDIT AMOUNT THIS DRAW to CREDIT AMOUNT THIS DRAW (OPTIONAL)

**Comment by WiseQA** [comment]
QA review retested functionality of Loan Agreement for Loan Received from Bank (Step 2).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUlTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4c3de5cc70327f28a6beda56e8cbe31b8494b750/image.png)

Verified label changed from Loan agreement to Loan Agreement

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWtTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ededd5dbcbe69f59ff196c30e061cfc4de1ad7c4/image.png)

Verified text in text boxes were corrected per wireframe:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcklTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--15d3af87b44795991323e04ecb060b103b7c6c7a/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclFTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--55e3f06cb1b88802e35db970ca29a933ca3ce5ca/image.png)

Verified under Loans and Debts in the transactions table the Loan Received from Bank is saved and displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcm9TIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4cd0fb13e2ed5bbc4006fc604669d9d1f91c4a7e/image.png)

Retested contact popups verified functionality working as designed.   

QA Review Completed.   Moved to Stage Ready.
