### ISSUE TITLE
4 - Allow user to add Loan Guarantor information to Schedule C loan

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1012]
Business Reason

As a Committee Administrator, I will be able to enter one or many ***”Loan Guarantor”*** information associated with either a ***"Loan Received from Individual"****, **”Loan Received from Bank”****, or **”Loan by Committee”*** on Schedule C of a Form 3X report so that I can accurately report on my committee's transactions.

***NOTE:*** Although not a "transaction", per se, this _must_ be associated with a Schedule C loan like children are associated to parents.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

  ***And*** I am editing a ***"Loan Received from Individual"****, **”Loan Received from Bank”****, or **”Loan by Committee”*** transaction on an open report

  ***Then*** I will have the OPTION to enter the following information for one or many guarantors:

—

Guarantor 

  #

Contact 

  #

  (includes lookup for individual contact)

*   ***LAST NAME*** (Required)
*   ***FIRST NAME*** (Required)
*   ***MIDDLE NAME*** (Optional)
*   ***PREFIX*** (Optional)
*   ***SUFFIX*** (Optional)

1.  Address

       #

*   ***STREET ADDRESS*** (Required)
*   ***APARTMENT, SUITE, ETC.*** (Optional)
*   ***CITY*** (Required)
*   ***STATE/PROVINCE*** (Required)
*   ***ZIP/POSTAL CODE*** (Required)
*   ***EMPLOYER*** (Required if ***Amount*** > $200)
*   ***OCCUPATION*** (Required if ***Amount*** > $200)

1.  Guaranteed Financial Information

       #

*   ***AMOUNT*** (AMT-12, Required, can be negative)

***Then*** I will be able to:

*   Cancel
*   Save & add loan guarantor
*   Save transactions

***And*** upon saving the system will create a C2 specification with this information associated with the Schedule C loan

  If Transaction Type is LOAN_RECEIVED_FROM_INDIVIDUAL or LOAN_RECEIVED_FROM_BANK, then it will be saved on the *.fec file on SC2/10

If Transaction Type is LOAN_BY_COMMITTEE, then it will be saved on the .fec file on SC2/9

***And*** I can access the information through the loan transaction it is associated with

  ***And*** I can continue adding more Guarantors if needed.

Dev Note

*   [x] Update schema to match [Spec Updates spreadsheet tab here]( [https://docs.google.com/spreadsheets/d/1H1zZmpkhUrKqe25OShtQrgbH1TrhIOSxvI1ZOM-Fw9Y/edit#gid=2022815147](https://docs.google.com/spreadsheets/d/1H1zZmpkhUrKqe25OShtQrgbH1TrhIOSxvI1ZOM-Fw9Y/edit#gid=2022815147))

Wireframes

***Placement of "Add Loan Guarantor" button***

  ![1000 - Loan Received From Individual - UPDATED.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/88ce5b8b-8a57-4c84-ba37-20240162bc5f](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/88ce5b8b-8a57-4c84-ba37-20240162bc5f))

***Lookup Collapsed***

![1012 - Guarantor - collapsed - UPDATED – 3.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ba3e7923-f260-4acc-84b4-bc87a9abebe0](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ba3e7923-f260-4acc-84b4-bc87a9abebe0))

***When the button is clicked, form expands to show this***

  ![1012 - Guarantor – 1.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/94894812-32d2-4e95-b9b0-2d3f18f54d15](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/94894812-32d2-4e95-b9b0-2d3f18f54d15))

Prototype Video
[https://images.zenhubusercontent.com/306118986/2c93949a-f50d-4941-89ba-4d5eb942a0a1/1012___gaurantor_prototype.mp4](https://images.zenhubusercontent.com/306118986/2c93949a-f50d-4941-89ba-4d5eb942a0a1/1012___gaurantor_prototype.mp4)

### QA Notes ###
- Emp/Occ required is based on amount, since there is no aggregate.
- This is Individual only, and there is no Entity field.

### DEV Notes ###
null

### Design ###
null

[FECFILE-808](https://fecgov.atlassian.net/browse/FECFILE-808)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Here is a prototype video

I'll walk you through my thinking tomorrow

https://images.zenhubusercontent.com/306118986/b7cec48d-be43-4af2-8cfd-2380f2abf270/1012_guarantor.mp4

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
How about these?
![1000 - Loan Received From Individual - 2 – 1.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/53ede581-136b-447d-bc1d-dacf53115b1c)

![1000 - Loan Received From Individual - 2 – 6.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/dedae141-6f31-458f-9ed6-7c3daef66211)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Please review. I made the updates from 66 and posted the wires here.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg request at refinement meeting to make it clear to the users that this is an optional section.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG wire approved. Moving to ADQTR.

**Comment by Elaine-Krauss-TCG** [comment]
Used work from #1300 to verify that #1012 is working
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVJnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e17bf1d09dcea00743a1002eba544a531133aa8a/image.png)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mary-tcg @mjtravers there is no dropdown in the wireframe for "Save & add loan guarantor" is there suppose to be ?  (Note:  Developed with "Guarantors to loan source" in dropdown).   Keep or remove dropdown is the question.   Thanks

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWhzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--41b397c6e0bedd123295e933d714f2635bfad7c3/image.png)

@mjtravers change dropdown to button only

**Comment by mary-tcg** [comment]
Since there are no options to choose from, we designed it without the dropdown to reduce user effort. If devs think it needs a dropdown we can discuss

**Comment by WiseQA** [comment]
QA review verified dropdown was changed to "+ Save & add loan guarantor" button only.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWR5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--927a05a9a56292fd2ad981f64a623acf3e13fcd7/image.png)

**Comment by WiseQA** [comment]
QA review verified when selecting "+ Save & add loan guarantor" button the "Guarantors to loan source" page is displayed.  (Note:  "Loan Received from Individual", ”Loan Received from Bank”, and ”Loan by Committee” were all tested)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWx5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--50c06c39753fbea077fe69077b165ca9b86a3ed6/image.png)

Verified Guarantor Lookup is defaulted to Individual only for "Loan Received from Individual", ”Loan Received from Bank”, and ”Loan by Committee”

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkZ5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5eadbfb4d4bf0de761e42cd15a75714c3db2e457/image.png)

Verified upon LOOKUP and entering an Individual Guarantor the "Guarantors to loan source" page is populated.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmR5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--90f17298997d6a24aec0c68294bc621b279698a9/image.png)

Verified under "Guaranteed financial information" the Amount field is "This is a required field"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0J5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9c467b7cf6940c7f9789cc8d297802398fdfd103/image.png)

Verified if Amount is < $200.00 the EMPLOYER and OCCUPATION fields are not required.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb055IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d0aba4cd2071fbc924c5e3c32dd38ef8e4c5fae8/image.png)

Verified if Amount is > $200.00 the EMPLOYER and OCCUPATION fields are required fields.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2x5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e54a8a129c5fc86d3a96bd393611b6cb8d8454fd/image.png)

Verified more than one Guarantor can be added (see ticket #1300 for list)

Verified transactions are updated and saved in the Transactions table.

QA Review Completed.   Moved to Stage Ready.
