### ISSUE TITLE
Refresh of "Transactions in this report" page the left NAV bar disappears

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1027]
During testing when selecting refresh from the menu bar in STAGE the "Transactions in this report" page the left NAV bar disappears. (Note: Issue on both environment DEV and STAGE)

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d442b063-eef5-48a0-b2fd-6e0e8740bb28](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d442b063-eef5-48a0-b2fd-6e0e8740bb28))

Left NAV bar displayed before refreshing:

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a83ed780-7f53-4dfd-b0d4-d35b77f5d176](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a83ed780-7f53-4dfd-b0d4-d35b77f5d176))

Left NAV bar missing after refreshing:

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/77f5c54e-6f09-457b-b914-7ecfad4683df](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/77f5c54e-6f09-457b-b914-7ecfad4683df))

Per review with @MitchellTCG @mjtravers fix refresh for the "Transactions in this report" page on both DEV and STAGE. 2 point bug fix.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-804](https://fecgov.atlassian.net/browse/FECFILE-804)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified  when selecting refresh from the menu bar in DEV the "Transactions in this report" page the left NAV bar does not disappear. (Note: Will test on STAGE once pushed for Sprint 25)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5cab3f1d-5645-403f-bd3a-73888151ec22)

QA Review Completed.   Moved to Stage Ready.
