### ISSUE TITLE
5 - Allow user to create Loan Repayment Received on Schedule A

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1032]
Business Reason

As a Committee Administrator, I will be able to initiate a ***”Loan Repayment Received”*** on an existing Schedule C loan transaction on a Form 3X report so that I can accurately report on my committee's transactions.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

  ***When*** I have an existing Schedule C loan of ***"Loan by Committee"***

  ***Then*** I can click on "Receive Loan Repayment" to initiate a “Loan Repayment Received"

  ***Then*** I will be required to enter the following information (unless otherwise noted):

—

Contact 

  #

*   ***CONTACT TYPE*** (Required, includes LOOKUP) 
      *   Committee Only
*   ***COMMITTEE NAME*** (Required)

1.  Address

       #

*   ***STREET ADDRESS*** (Required)
*   ***APARTMENT, SUITE, ETC.*** (Optional)
*   ***CITY*** (Required)
*   ***STATE/PROVINCE*** (Required)

1.  Receipt information

       #

*   ***DATE RECEIVED*** (Required)
*   ***MEMO ITEM*** (Optional)
*   ***AMOUNT*** (Required, can be negative)
*   ***AGGREGATE*** (Required) 
      *   Amount Displayed will be the total of contributions that are: 
            *   From the person (ENTITY)
    *   within Aggregation Group of "LINE_14" 
            *   _from_ January 1 of report year _to_ the Contribution Date* of the transaction.
        *   *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

1.  Additional information

       #

*   ***PURPOSE OF RECEIPT*** (Required, System generated) 
      *   Text must read "Loan Repayment"
*   ***NOTE OR MEMO TEXT*** (Optional)

***Then*** I will be able to:

*   Cancel
*   Save

***And*** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SA14.

Dev Note

*   Schedule A transaction back reference ID will refer to the SC transaction. This will be needed for updating SC amounts.
*   [x] Update schema to match [Spec Updates spreadsheet tab here]( [https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1761463363](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1761463363))

Wireframes

1.  Transaction Page:
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWxaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47af142cdbbf3d7f3ad400dd2c2020f34f7fe616/1032%20-%20Allow%20user%20to%20create%20Loan%20Repayment%20Received%20on%20Schedule%20A.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWxaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47af142cdbbf3d7f3ad400dd2c2020f34f7fe616/1032%20-%20Allow%20user%20to%20create%20Loan%20Repayment%20Received%20on%20Schedule%20A.png))

1.  Transactions on this Report Page:
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0pGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fb21e77d97ebb7496953f21e8d2928cb112b99e8/1032%20-%20Transactions%20in%20this%20report.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0pGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fb21e77d97ebb7496953f21e8d2928cb112b99e8/1032%20-%20Transactions%20in%20this%20report.png))

### QA Notes ###
- Associated Schedule C  loan will always be "Loan by Committee"

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-800](https://fecgov.atlassian.net/browse/FECFILE-800)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
First crack
![1032 - Allow user to create Loan Repayment Received on Schedule A.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/55565bf4-bb04-4d0a-b7be-bdbb6d8e37e2)

**Comment by MitchellTCG** [comment]
![1032 - Allow user to create Loan Repayment Received on Schedule A.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/aaf8525a-f59e-4ba1-b67c-8213eb2bcc9c)

**Comment by MitchellTCG** [comment]
Wires updated

**Comment by toddlees** [comment]
Passes CR moving to QA

**Comment by WiseQA** [comment]
@toddlees change dropdown label from "Loan Repayment Received" to "Receive loan repayment"  and make sentence case per UX.

**Comment by toddlees** [comment]
Updated "Loan Repayment Received" to "Receive loan repayment"
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBck5GIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--efd6c4b657846374c0e27bb3a1f7b3610153e86d/image.png)

**Comment by WiseQA** [comment]
QA review verified Loan Repayment Received transaction is generated and saved as a Receipt in the Transactions table.

Verified Actions dropdown was changed to "Receive loan repayment" per Wireframe.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDFMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b71c340f6b177a2afb95cf8643d966b10781c351/image.png)

Verified Loan Repayment Received transactions page is displayed after select "Receive loan repayment" from the dropdown for Loan By Committee in the Loans and Debts area of the transaction table.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVJMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--05738b3d9bb3780a4c8dd53c1a7755754bddceec/image.png)

Verified Contact Type is Committee Only

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXBMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6d50ae41fb9118e5682a3f2d7e32e32f3e633308/image.png)

Verified (adhoc tested) Memo Item (Optional) is displayed correctly and the Sections are labeled correctly as sentence case in the transaction.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkJMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--99802fbdcf3de525f3cfeb49683ad3f77faf9ce4/image.png)

Verified Aggregate amount is generated.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkpMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--776912cc7a6ad272acc963fb0d6e0b6928ed1215/image.png)

Verified Amount can be a negative value.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb05MIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--274b022873e1274c4fdc06e95fbe2e80044362ae/image.png)

Verified Purpose of Receipt (System-Generated) text field contains "Loan Repayment"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblZMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--650a340657aabecd045ebb7d3183ac725481ef67/image.png)

Verified contact popup is displayed correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmxMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3f7c0155c6d6ba7acd2cef680e6a303b1a1461e2/image.png)

Verified Loan Repayment Received transaction is created and saved as a Receipt (Schedule A) in the Transactions table.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnBMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c681a7f9898ef754da8888ef0bd9c68ceb5d1fcf/image.png)

QA Review Completed.   Moved to Stage Ready.

**Comment by WiseQA** [comment]
@mjtravers @toddlees @alexander-lin @MitchellTCG moving back to QA review until the requirements, AC and Wireframes sorted out on this ticket per DEV findings.

**Comment by GreggMoreland** [comment]
AC is updated to indicate the Action to click

**Comment by mjtravers** [comment]
The current AC for this ticket is asking for an FEC ID for committee but there is no field in the spec available to store that information.

**Comment by GreggMoreland** [comment]
Wire and AC were updated to remove reference to the FEC ID, to match the spec

**Comment by WiseQA** [comment]
QA review retested (even though no changes from DEV).    Verified FEC ID was removed from AC (Gregg) and Wireframe (Mary) to match current spec.

QA Review Completed.   Moved to Stage Ready.
