### ISSUE TITLE
5 - Allow user to create Loan Repayment Made on Schedule B 

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1033]
Business Reason 
 

As a Committee Administrator, I will be able to initiate a **”Loan Repayment Made”** on an existing Schedule C loan transaction on a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**When** I open an existing Schedule C loan of "Loan Received from Individual" or "Loan Received from Bank"
**Then** I can initiate a “Loan Repayment Made"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
Dropdown: Individual, Organization, Committee
**Note** auto-generated from associated SC loan

_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required, auto-generated from associated SC loan)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)

---
_if CONTACT TYPE = Individual_ 
-	**LAST NAME** (Required, auto-generated from associated SC loan)
-	**FIRST NAME** (Required, auto-generated from associated SC loan)
-	**MIDDLE NAME** (Optional, auto-generated from associated SC loan)
-	**PREFIX** (Optional, auto-generated from associated SC loan)
-	**SUFFIX** (Optional, auto-generated from associated SC loan)

# Address 
#
-	**STREET ADDRESS** (Required, auto-generated from associated SC loan)
-	**APARTMENT, SUITE, ETC.** (Optional, auto-generated from associated SC loan)
-	**CITY** (Required, auto-generated from associated SC loan)
-	**STATE/PROVINCE** (Required, auto-generated from associated SC loan)

# Expenditure information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be negative)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, System generated)
-- Text must read "Loan Repayment"
-	**NOTE OR MEMO TEXT** (Optional)

**Then** I will be able to:
- Cancel
- Save

**And** anything auto-generated from the associated SC loan will be **read-only**
**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB26.
**And** the transaction will be saved as a Disbursement, and can be accessed as such.

 QA Note 

- Associated Schedule C loan will either be "Loan Received from Individual" or "Loan Received from Bank"
- Loan Repayment Made will be a Disbursement (Schedule B)

 Dev Note 

- Schedule B transaction back reference ID will refer to the Schedule C transaction. This will be needed for updating SC amounts.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1558500269)  

 Wireframe 

# Transaction
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclUyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cb524e4bc4628ebe5e8fe12051cc22dbad763748/1033%20-%20Loan%20Repayment%20Made%20on%20Schedule%20B.png)

# Transactions in this report
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDVGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--84dec9dc546a6b97e9eaf90db45cc5d6b9d66c94/1033%20-%20Transactions%20in%20this%20report%20-%204.png)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
First crack
![1033 - Loan Repayment Made on Schedule B.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/1e18c515-fbf1-446a-89ac-efdbdce6c13b)

**Comment by mary-tcg** [comment]
@AureliaKhorsand @GreggMoreland @MitchellTCG wire updated

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
wire added. I think there was something I was supposed to edit in the "transactions in this report"

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers @GreggMoreland verified UX design dropdown should read "Make loan repayment" not “Loan Repayment Made".   QA  will test using "Make loan repayment" terminology.

**Comment by WiseQA** [comment]
QA review verified both "Loan Received from Individual" and "Loan Received from Bank" actions dropdown list displays "Make loan repayment".  

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXByIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--23b0433c295a23828cc909f26eb517e4e0fd8423/image.png)

Verify "Loan Repayment Made" transaction page is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXRyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ea9acd92d21ec39e3af9a6a8eeda962b64dd6ace/image.png)

Verify under the "Expenditure information" section - Date; Memo Item (Optional) and Amount are displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTVyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e1be3007dd77ab01ad3ae92836890d62975119e9/image.png)

Verified "Loan Repayment Made" transactions is saved and listed in the Disbursements (Schedule B) list in the transaction table.   Verified the Transaction ID and Associated With references are correct.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclJyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--58daaa404cfe618bdb62dcddebd4e82d6e48e971/image.png)

Both Loan Received from Bank and Loan Received from Individual was tested.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnByIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--630f325c920f217f3873a9c9d4e67683d0dec0e9/image.png)

QA Review Completed.   Moved to Stage Ready.
