### ISSUE TITLE
System to propagate contact updates across committee account (including submitted reports)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1034]
Business Reason 
 

As a user, if I update contact information either within a transaction or Contact Management, that contact information will be updated in Contact management and any existing transaction on any report so that I don't have to update each one manually in order to report accurately.

 Acceptance Criteria 
 

**If** the user edits an existing contact in Contact Management 
**When** the user saves the contact,
**Then** any transaction with the same entity will show the updated contact information, regardless of report status.

---
**If** the user edits an existing contact within a transaction,
**When** the user saves the transaction,
**Then** any transaction with the same entity will show the updated contact information, regardless of report status
**And** the  contact in Contact Management will show the updated contact information.

 Wireframe 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3VNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f19c40f0785174c24ffcf277cb22aa7b141be28a/1034.png)

### QA Notes ### 
 
- [x] BA/Design Quality Checklist complete

### DEV Notes ### 
 
- The contact information should be updated regardless of if the contact is in a transaction as a contributor, payee, beneficiary, donor, conduit, etc...
- This is an expansion of functionality in #582. We no longer have the restriction of only looking forward. It should be updated everywhere, regardless of date and report status.

### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
UX/UI team: We need the popup message language for saving the contact to let the user know that the changes will appear everywhere except closed reports.

**Comment by AureliaKhorsand** [comment]
BA Note: Need answer on report status before we can point this one. (Ensure we cannot have a closed report between open ones).

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg can one of you update the wireframe here to say that it will affect "all transactions involving this contact"?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
update complete please review

**Comment by GreggMoreland** [comment]
@MitchellTCG @AureliaKhorsand I have reviewed this and I'm moving it to ADQTR

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@AureliaKhorsand @GreggMoreland @MitchellTCG @toddlees need clarification the AC states "user edits an existing contact in Contact Management", this means the Manage Contacts page correct ?   If Contact changed and saved the popup will be displayed.  

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXJUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--817498435f6238bc6b1b31ffb365132c6c15a230/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWJUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69e598f3c18d9fb6c489f9fdc1747c9d572d7220/image.png)

**Comment by GreggMoreland** [comment]
@WiseQA the function is Contact Management. The UI page to perform that function is Manage Contacts

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland @WiseQA @toddlees 
**Per Ryan** (11/14/2023 12:45p): 
"Propagating contacts across committee account" — It does not matter if the contact is updated in a transaction or from the "Manage contacts" page, **ALL** transactions related to that contact **WILL BE** updated.

@toddlees 
So the same pop up will appear when updating a contact on the "Manage contact" page and when updating a contact while saving a transaction .

Please let me know if I can provide any more clarity.

**Comment by WiseQA** [comment]
After clarification from Ryan sending back to In-Progress for fix that the same pop up will appear when updating a contact on the "Manage contact" page.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmJUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9334add87d67c103a803546a5e5c28bc9b478c16/image.png)

@MitchellTCG @mjtravers @toddlees - Thanks Mitchell !

**Comment by mjtravers** [comment]
CR turned up some issues with merging this branch with develop. Sending back to In Progress for resolution.

**Comment by mjtravers** [comment]
In CR, when creating a new contact in the contact manager, I'm getting "undefined, undefined" and a bunch of extra bullets in the pop-up:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelBwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e4e85213ea218b87a4244a8d42b378e3f93cd5d/image.png)

Can we skip showing the pop-up when creating a new contact? No pop-up appears when I saving with the "Save & Add More" button.

Sending back to In Progress.

**Comment by toddlees** [comment]
fixed

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review retested and verified popup appears when updating / editing an existing contact on the "Manage contact" page.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnI5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--28c88aaec16946e8fcb62cbfe785afa05ad53cee/image.png)

QA review retested when changing / editing an existing contact in a transaction the following popup appears correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0Q5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e911950e650aead38c3429c87e0bddad8e8082b9/image.png)

Verified when creating a new contact the popup window is not displayed per DEV comment above.

QA Review Completed.   Moved to Stage Ready.
