### ISSUE TITLE
System to match Tier 2/3 itemization with Tier 1 itemization, regardless of Tier 2/3 amounts

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1035]
***Task:*** Tier 2 and 3 transactions must match the itemization logic of the associated Tier 1 and Tier 2 transactions, respectively.

Acceptance Criteria

***Given*** I am a user creating a new Tier 2 or Tier 3 transaction

  ***Then*** the default itemization logic for that Tier 2 and Tier 3 transaction _must_ match the itemization logic of the associated Tier 1 transaction.

### QA Notes ###
- Test with any Receipt/Memo and/or Disbursement/memo combination where the itemization rule is set based on aggregate amount
- This is for _default_ itemization logic and does not account for force itemization or unitemization (see ticket #804)
- Example for Tier 1 with Tier 2: Partnership Receipt (Tier 1), Partnership Attribution (Tier 2) and
     Earmark Receipt (Tier 1), Earmark Memo (Tier 2)
- Example for testing Tier 2 and Tier 3: Joint Fundraising Transfer (Tier 1) with Partnership Receipt Joint Fundraising Transfer Memo (Tier 2) and Partnership Attribution Joint Fundraising Transfer Memo (Tier 3)

### DEV Notes ###
- ~~All existing transactions where itemization is set based on aggregate amount will need to be updated so that tier 2 and tier 3 default to what was set for Tier 1.~~
- Implementation should be updating the transaction manager to base itemization on the parent's itemization

### Design ###
null

 See full ticket and images here: [FECFILE-797](https://fecgov.atlassian.net/browse/FECFILE-797)

**Comment by AureliaKhorsand** [comment]
**BA updates needed:** itemization is not calculated upon saving a transaction. need to update to take into account that "when itemization is determined", what needs to happen, and also include force itemize/unitemize. Don't need to separate it out, but if we want to, can implement functionality now and the message to users later. 

BA/Design notes: may need to prevent user from force itemizing/unitemizing Tier 2 and Tier 3.

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers @AureliaKhorsand @GreggMoreland is the dropdown under actions the same list for this ticket as ticket #804 ?   Thanks

**Comment by GreggMoreland** [comment]
@WiseQA Correct, the same items as #804. Itemize, Unitemize, and Edit

**Comment by Elaine-Krauss-TCG** [comment]
The memo should be itemized as it has a negative amount, but instead it inherits its parent's itemization status.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjhVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e2b69c471a43aa4b844fe8e98dba7c38abae067f/image.png)

**Comment by mjtravers** [comment]
Needs code added to handle .fec file build. Moving back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified when a Tier 1 with Tier 2: Partnership Receipt (Tier 1), Partnership Attribution (Tier 2) Itemization which is not forced the itemization applies to the associated memo transactions when the itemization of the parent transaction is changed. Used Partnership Partnership Receipt (Tier 1), Partnership Attribution (Tier 2) for testing.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFpUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9c4bbfdded35f4f5b88481195c6b4458426ccc1d/image.png)

e2e testing to be updated.

QA Review Completed. Moved to Stage Ready.
