### ISSUE TITLE
DSP: System to calculate Loans Received (line 13) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1037]
Business Reason 
 

On the Detailed Summary Page, Line 13 should be a total of all transactions with form type SA13 _except_ for if the transaction has "Memo Code" checked. This ticket is for Column B only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 13 (column B) of Form 3X must:
--  consist of the total of all transactions with form type "SA13" **from January 1 of current year to the report coverage period end date**
-- NOT include any transactions with "Memo Code" checked
2. The numbers will update as needed until the report is submitted.

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

 QA NOTES
Transaction types included here:
- Loan Received From Individual
- Loan Received From Bank

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by Elaine-Krauss-TCG** [comment]
This run of the unit tests on CircleCI includes all 8 DSP line additions and their respective tickets.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakNYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bc82aa921caa837d82c57f9b0c6265630c404cad/image.png)

**Comment by WiseQA** [comment]
QA review verified "ALL LOANS RECEIVED" are calculated correctly in Line 13 - Column B. (Note: tested with Loan Received From Individual and Loan Received From Bank to verify calculation is correct)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanVYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e6b162cc814faafa0b613404a03acc70317d946f/image.png)

QA Review Completed. Moved to Stage Ready.
