### ISSUE TITLE
DSP: System to calculate Loan Repayments Made (Line 26) (Column A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1038]
Business Reason 
 

On the Detailed Summary Page, Line 26 should be a total of all transactions with form type SB26 _except_ for if the transaction has "Memo Code" checked. This ticket is for Column A only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 26 (column A) of Form 3X must:
--  consist of the total of all transactions with form type "SB26"  within the report period
-- NOT include any transactions with "Memo Code" checked

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
 Transactions included here:

- Loan Repayment Made
- NOTE for testing:   Loan Received from Individual and Loan Received from Bank > will create the Schedule B Loan Repayment Made
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by Elaine-Krauss-TCG** [comment]
This run of the unit tests on CircleCI includes all 8 DSP line additions and their respective tickets.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakNYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bc82aa921caa837d82c57f9b0c6265630c404cad/image.png)

**Comment by WiseQA** [comment]
QA review verified "LOANS REPAYMENTS MADE" are calculated correctly in Line 26 - Column A. (Note: tested with Loan Received from Individual and Loan Received from Bank > will create the Schedule B Loan Repayment Made to verify calculation is correct - without Memo Item checked)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGVYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--885728a5dab93ec241cc617bfa043b69a1178575/image.png)

QA Review Completed. Moved to Stage Ready.
