### ISSUE TITLE
3 - Summary Page and DSP: System to calculate Total Disbursements (Line 7 and Line 31) (Column A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1040]
Business Reason

On the Summary Page, Line 7 and Detailed Summary Page, Line 31 should be a total of all Disbursement transactions _except_ for if the transaction has "Memo Code" checked. This ticket is for Column A only.

Acceptance Criteria

1\. Detailed Summary Page Line 31 (column A) of Form 3X must:

  – consist of the sum of all transaction totals in the following report lines within the report period

*   Line 21.c Total Operating Expenditures (#1041)
*   Line 22 Transfers to Affiliated/Other Party Committees (#913)
*   Line 23 – Contributions to Federal Candidates/Committees and Other Political Committees (#915)
*   Line 24 Independent Expenditures (#1182)
*   Line 25 Coordinated Party Expenditures (SF25, set to zero in #1427)
*   Line 26 Loan Repayments Made (#1038)
*   Line 27 Loans Made (#1052)
*   Line 28.d Total Contribution Refunds (#917)
*   Line 29 other Disbursements (#919)
*   Line 30.c Total Federal Election Activity (#921) 
      *   NOT include any transactions with "Memo Code" checked

2\. Summary Page, Line 7 – DSP Line 31 should be copied to Line 7 (Column A)

DEV NOTES

  Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.]([https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf))

Dev Notes

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-792](https://fecgov.atlassian.net/browse/FECFILE-792)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Detailed Summary Page for Line 31 (Column A ONLY) is displaying correctly. (JULY 15 QUARTERLY REPORT (Q2) 04/01/2023 — 06/30/2023 for testing).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFVOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--588339e2233295b27841439f7206c27f5d11ab63/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFlOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9d24cccdc391ea6b936bf522b22c2da36990247/image.png)

QA review verified Summary Page for Line 7 (Column A ONLY) is displaying correctly. (JULY 15 QUARTERLY REPORT (Q2) 04/01/2023 — 06/30/2023 for testing).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG9OQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83ee911862613b41a8e3b73cf3e0562e02e786d3/image.png)

QA Review Completed.  Moved to Stage Ready.
