### ISSUE TITLE
3 - Summary Page and DSP: System to calculate Total Disbursements (Line 7 and Line 31) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1041]
Business Reason

On the Summary Page, Line 7 and Detailed Summary Page, Line 31 should be a total of all Disbursement transactions _except_ for if the transaction has "Memo Code" checked. This ticket is for Column B only.

Acceptance Criteria

1\. Detailed Summary Page Line 31 (column B) of Form 3X must:

  – consist of the sum of all transaction totals in the following report lines ***from January 1 of current year to the report coverage period end date***

*   Line 21.c Total Operating Expenditures (#1043)
*   Line 22 Transfers to Affiliated/Other Party Committees (#914)
*   Line 23 – Contributions to Federal Candidates/Committees and Other Political Committees (#916)
*   Line 24 Independent Expenditures (#1183)
*   Line 25 Coordinated Party Expenditures (SF25, set to zero in #1427)
*   Line 26 Loan Repayments Made (#1039)
*   Line 27 Loans Made (#1053)
*   Line 28.d Total Contribution Refunds (#918)
*   Line 29 other Disbursements (#920)
*   Line 30.c Total Federal Election Activity (#922)

– NOT include any transactions with "Memo Code" checked

2\. Summary Page, Line 7 – DSP Line 31 should be copied to Line 7 (Column B)

  3\. The numbers will update as needed until the report is submitted.

DEV NOTES

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
- [x] BA/Design Quality Checklist complete

 See full ticket and images here: [FECFILE-791](https://fecgov.atlassian.net/browse/FECFILE-791)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Detailed Summary Page for Line 31 (Column B ONLY) is displaying correctly. (JULY 15 QUARTERLY REPORT (Q2) 04/01/2023 — 06/30/2023 for testing).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUVOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3980cad50eb96ed294b2dbfb0f07d96b22bb956/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU1OQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac6d96aef79925fbbd825343b77563ee651f2654/image.png)

QA review verified Summary Page for Line 7 (Column B ONLY) is displaying correctly. (JULY 15 QUARTERLY REPORT (Q2) 04/01/2023 — 06/30/2023 for testing).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWdOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f5ad60374a80f0a5d28b537e8ca328e7a264bf5/image.png)

QA Review Completed.  Moved to Stage Ready.
