### ISSUE TITLE
2 - DSP: System to calculate Total Operating Expenditures (Line 21.c) (Column A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1042]
Business Reason 
 

On the Detailed Summary Page, Line 21.c should be a total of all lines 21.a.i, 21.a.ii, and 21.b_except_ for if the transaction has "Memo Code" checked. This ticket is for Column A only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 21.c (column A) of Form 3X must:
--  consist of the sum of all transaction totals in the following **Column A** report lines:
- Line 21.a.i Allocated Federal/Non-Federal Activity – Federal Share (From Schedule H4, set to zero in #1427)
- Line 21.a.ii Allocated Federal/Non-Federal Activity – Non-Federal Share (From Schedule H4, set to zero in #1427)
- Line 21.b – Other Federal Operating Expenditures (Line SB21b transactions) #911
-- NOT include any transactions with "Memo Code" checked

 DEV NOTES

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
- Lines 21.a.i and 21.a.ii will be set to zero initially in #1427
- Line 21.b was completed in #911

Line 21.b transactions:
- Operating Expenditure
- Credit Card Payment for Operating Expenditure
- Staff Reimbursement for Operating Expenditure
- Payment to Payroll for Operating Expenditure
- Void of Operating Expenditure
- National Party Headquarters Buildings Account Disbursement
- National Party Pres. Nominating Convention Account Disbursement
- Individual Refund - National Party Headquarters Buildings Account
- Other Committee Refund - National Party Headquarters Buildings Account
- Tribal Refund - National Party Headquarters Buildings Account
- Individual Refund - National Party Pres. Nominating Convention Account
- Other Committee Refund - National Party Pres. Nominating Convention Account
- Tribal Refund - National Party Pres. Nominating Convention Account
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Detailed Summary Page for Line 21.c (Column A ONLY) is displaying correctly. (Used JULY 15 QUARTERLY REPORT (Q2) 04/01/2023 — 06/30/2023 for testing) **(NOTE: Line 21.a.i and 21.a.ii is value of zero as these have not been developed to date.)**

Used the following transactions for testing listed in ticket #911:

- Operating Expenditure
- Credit Card Payment for Operating Expenditure
- Staff Reimbursement for Operating Expenditure
- Payment to Payroll for Operating Expenditure
- Void of Operating Expenditure

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0h3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb4f02d57f0028c57dd27bf83aff8c86ad47a7fe/image.png)

QA Review Completed.   Moved to Stage Ready.
