### ISSUE TITLE
DSP: System to calculate Net Contributions (Line 35) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1048]
Business Reason 
 

On the Detailed Summary Page, Line 35 should be calculated by subtracting the value in Line 34 (Column B) from the value in Line 33 (Column B). This ticket is for Column B only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 35 (Net Contributions) of Form 3X must:
--  consist of the value in Line 34 (Total Contribution Refunds) **subtracted from** the value in Line 33 (Total Contributions). Both values should be from Column B.

 DEV NOTES
-	This is a calculation. Line 33 (Column B) MINUS Line 34 (Column B)

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
 -	This is a calculation. Line 33 (Column B) MINUS Line 34 (Column B)
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified from acceptance criteria, Column B value in Line 34 (Total Contribution Refunds) subtracted from the value in Line 33 (Total Contributions) calculation displayed in Line 35 Net Contributions (Other Than Loans).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6dd68101-ff59-447d-85da-3186e3cb155a)

QA Review Completed.   Moved to Stage Ready.
