### ISSUE TITLE
Create Testing Accounts for Cloud.gov

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#105]
Set up accounts in cloud.gov for testing, for Shelly (QA/Testing), Mary (UX), Mitchell (Scrum), Aurelia (BA). (Not not sure who else would need testing access from the our team.)

Testing user role will be "Committee Account Administrator" as "access to everything" as decided in previous requirements meetings for OPT 1.

***Acceptance Criteria:***

*   [x] test accounts should work on stage server, DEV server and PROD server
*   [x] email, committee ID, password, and MFA code for each test account
*   [x] 4 accounts are needed and named: swise@tygart.com, mitchell.jarrett@tcg.com, aurelia.khorsand@tcg.com, and mary.honard@tcg.com
*   [x] All 4 accounts will be Committee Admin role so each will have its own Committee Account

***QA***

  New accounts

  (email, committee id)

  swise@tygart.com, C00277608

  mitchell.jarrett@tcg.com, C00277616

  aurelia.khorsand@tcg.com, C00277673

  mary.honard@tcg.com, C00277863

  See Matt for password and multi-factor code.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1305](https://fecgov.atlassian.net/browse/FECFILE-1305)

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/9/22:** Currently no way to do this in UI, so we have SQL statements from script from Roberto. This is a stopgap for just getting the test accounts in the system. Right now, authentication isn't leaving our system, so users don't need access to these emails just yet. Pointed at 3.

Note: The accounts that exist in UAT when we move to Stage in ticket [fecfile-web-api# 37](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-api/37) will still exist, and these four accounts will be added.

**Comment by WiseQA** [comment]
Capability of logging in to test account on cloud.gov passed.  Below Login credentials used was new test account set up for swise@tygart.com.

Verify login to DEV:
https://fecfile-web-app-dev.app.cloud.gov/
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8d71a0a3-0f68-4151-8fe5-ddb3649f6e8b)

Verify login to STAGE:
https://fecfile-web-app-stage.app.cloud.gov/
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a55509d5-9dc9-4f54-a664-85d21905fd5d)

Verify login to PROD:
https://fecfile-web-app-prod.app.cloud.gov/
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c194d635-bc8d-489e-80e1-4e3f79d4f9e3)

@mjtravers and @WiseQA verified other test accounts working.

**Comment by WiseQA** [comment]
Conversation with @mjtravers on tester access to PROD server.   @mjtravers will clarify what servers the test accounts should have access to..  Will update acceptance criteria once clarified.  Returned to Code Review.  (Note:  Ticket was written initially for Stage server access only which needed changed.)

**Comment by WiseQA** [comment]
QA Completed.   Capability of logging in to test accounts on cloud.gov passed (DEV, Stage, PROD) (see above screen shots).  

Acceptance criteria updated:   test accounts should work on stage server, DEV server and PROD server

QA review completed.  Moved to Stage Ready.
