### ISSUE TITLE
2 - System to auto-generate Loan Made on Schedule B 

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1051]
Business Reason 
 

As a Committee Administrator, I will be able to view a **”Loan Made”** transaction on Schedule B while creating the associated Schedule C "Loan by Committee" on a Form 3X report so that I can know what receipt will be saved.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing a **”Loan by Committee”** transaction on Schedule C
**Then** I will be able to view the auto-generated **”Loan Made”** disbursement that will be saved when I save the Schedule C Loan with the following information: 

---

 Contact 
#
- Committee Only
-	**COMMITTEE NAME** (Required, auto-generated from LOAN_BY_COMMITTEE)

# Address 
#
-	**STREET ADDRESS** (Required, auto-generated from LOAN_BY_COMMITTEE)
-	**APARTMENT, SUITE, ETC.**  (Optional, auto-generated from LOAN_BY_COMMITTEE)
-	**CITY**  (Required, auto-generated from LOAN_BY_COMMITTEE)
-	**STATE/PROVINCE**  (Required, auto-generated from LOAN_BY_COMMITTEE)
- **ZIP**  (Required, auto-generated from LOAN_BY_COMMITTEE)

# Expenditure Information 
#
-	**DATE**  (Required, auto-generated from LOAN_BY_COMMITTEE)
-	**MEMO ITEM**  (Optional, auto-generated from LOAN_BY_COMMITTEE)
-	**AMOUNT**  (Required, auto-generated from LOAN_BY_COMMITTEE)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Optional)
-	**NOTE OR MEMO TEXT** (Optional)

**Then** I will be able to:
- Cancel
- Edit
- Save transactions (cannot be saved without #1134).

**And** both transactions will be itemized upon saving and saved with their own line items on the *.fec file:
- Loan by Committee (Schedule C) will be saved as SC/9
- Loan Made (Schedule B) will be saved as SB27.

 QA Note 

**QA Note added:    >  ENTER DATA:  field auto populated text should be "loan by committee"**

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1285539153)  
- [x] Disable the "Just checking ..." memo code date pop-up by adding this line to the transaction type: override doMemoCodeDateCheck = false;

 Wireframe
![1051 - Loan Made on Schedule B.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/cbfd87af-6e55-479f-aa0c-144b375ff94b)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Please review wire

**Comment by AureliaKhorsand** [comment]
@MitchellTCG wire approved.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Updated

**Comment by AureliaKhorsand** [comment]
@MitchellTCG wire approved

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers (NOTE:  No changed needed from DEV, the verbiage is correct on DEV)

QA note added to acceptance criteria:

> ENTER DATA:  field auto populated text shows "loan by bank" shown in the Wireframe:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/411d2867-c88e-4a86-ba80-f738139c2ad8)

>  ENTER DATA:  field auto populated text should be "loan by committee":

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c0159364-0221-4184-9453-942a3c1f20f3)

**Comment by WiseQA** [comment]
QA review retested. Pre-requisite a "Loan By Committee" transaction is created and displayed in the Transactions table under the Loans and Debts.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/06c8784b-2bb6-4ead-bedb-a1f556867232)

Verify "Loan Made" transaction is auto populated and displayed in the Transactions table under Disbursements.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7c1730b4-204f-4b98-a0ab-21c198ab7097)

Select the "Loan Made" transaction from Disbursements. Verify transaction has been auto populated and fields are read-only. (Note: Verified fields were populated correctly from the Loan transaction)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/621b5342-be0e-48fd-9c7a-ed2e883bff46)

QA Review Completed. Moved to Stage Ready.
