### ISSUE TITLE
DSP: System to calculate Loans Made (Line 27) (Column A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1052]
Business Reason 
 

On the Detailed Summary Page, Line 27 should be a total of all transactions with form type SB27 _except_ for if the transaction has "Memo Code" checked. This ticket is for Column A only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 27 (column A) of Form 3X must:
--  consist of the total of all transactions with form type "SB27"  within the report period
-- NOT include any transactions with "Memo Code" checked

 DEV NOTES
- Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
 Transactions included here:

- Loan Made (transaction is autocreated when Loan by Committee is saved)
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXhoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1c4acf9cedb3ad86bbadd56abaf06ef9858491fd/image.png)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Loans Made are calculated correctly in Line 27 - Column A. (Note: tested with Memo Code selected not in total of Line 27)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakJpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6784752843b57ab79c83662ebbccef46bbba90f7/image.png)

QA Review Completed.   Moved to Stage Ready.
