### ISSUE TITLE
Allow user to specify Election Information in a transaction (updated)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1055]
Business Reason 
 

As a user, I will be able to select from a list of Election code values and include an Election Year for my schedule A transaction on Form 3X so that I can categorize my receipts for bookkeeping purposes.

 Acceptance Criteria 
 

**Given** the user is entering a transaction that requires Election Information (example: "Refund of Contribution to Other Political Committee", Schedule A). 
**Then** they will have the option to select one Election Code from the dropdown under "Election Information"
**And** the list will include the following in this order: 
- Primary (P)
- General (G)
- Convention (C)
- Runoff (R)
- Special (S)
- Recount (E)
- Other (O)

**And** they will be required to enter an Election Year value (YYYY format)
**And** If they select "Other" they will be required to enter a value in the Election Description text box (A/N 20) For all other selections, this field is optional.

**And** upon saving, the Election Code/Year field in the specification will be a concatenation of the Election Code (X) and Year (YYYY) as "XYYYY", with the code mapping as follows:
- Primary (P)
- General (G)
- Convention (C)
- Runoff (R)
- Special (S)
- Recount (E)
- Other (O)

 Wireframe 

![1055 - Election Information with “Other” option.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/14d0eaff-afce-403e-a379-84c2db62de1c)

### QA Notes ### 
 - Election code and Election Year are required. Election Description is only required if the Election Code is Other.
- Election Description should have "REQUIRED IF OTHER" in grey text next to the field name.
- Should be tested with "Refund of Contribution to Other Political Committee" (Schedule A)
### DEV Notes ### 
 - This will also affect the schemas.
- The single digit code and year is what is captured and saved for .fec file for the "Election Code/Year" field in the specification. 
Example: P2022 - if code is P (Primary) and year is 2022
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg can we have updated wires for this ticket, indicating that the Election Description field is "REQUIRED IF OTHER" or whatever language you want to use?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Wire added

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Election Type Other (O) has been added to the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6c5c1569-aecf-4e35-802e-bb45fa64dbcd)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7b9e2275-c84b-48cf-bbe8-c1432082b6cd)

Election Year is Required if selecting Other (O):

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7bb2c386-c221-460d-a584-ee0f40376b16)

Election Field (Required if Other):

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6c1f45ae-a18d-46c6-8994-84c4b891acb1)

QA Review Completed.  Moved to Stage Ready.
