### ISSUE TITLE
[UI] Create "Add Loans and Debts" page within a Report

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1056]
Business Reason

As a user, I will be able to access the "Add Loans and Debts" page in a reports so that I can select what transactions I want to create as needed.

 Acceptance Criteria

**Given** the user is in an open report,
**When** the users clicks "Add Loans and Debts" either from the "+ Add new transaction" button in the top right or on the left hand navigation menu,
**Then** they will see the Add Loans and Debts page, which (for now) will have the accordion dropdowns (one for Loans and one for Debts), and under Loans will be the following transactions as dead links:
- Loan Received from Individual 
- Loan Received from Bank

![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/dc977ee1-33fb-491c-b0d7-cf8458ba1ffa)

![1056 - Loans and debts Selector.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/6249f7b3-fb8c-4f4c-9810-ea5434c7f974)

Make "Add loans and Debts" active on both button (dropdown on right) and the left nav

### QA Notes ### 
 - Transactions will be "dead links" and greyed out for now.
### DEV Notes ### 
  WIREFRAME 
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG and @mary-tcg - These links need to be live, and we need to design the "Add Loans and Debts" page itself. Right now if will only have the ability to add a **Loan Received from Individual** and **Loan Received from Bank**.
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/6ab6e81e-8314-4474-873e-37c57a7f835a)
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/b2dbea91-2385-4c78-a05f-eab98060f44a)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg per my comment above from 5/9, this ticket needs the wire for the Loans and Debts page (with accordion dropdowns). ACs updated for more info if needed, please ask me if you have questions.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
I updated the ticket. let me know if you feel it is ready to go

**Comment by AureliaKhorsand** [comment]
@MitchellTCG all good except can you take out the bottom half of the first screenshot? The functionality for viewing the Loans and Debts is a different ticket and I don't want folks to be confused. Thanks!

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
I updated the wire does this look right?

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "ADD LOANS AND DEBTS" link is activated in the left NAV Bar.  Once selected the "Add loans and debts" page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/88902610-b4f2-45eb-8aa0-1f03f4aeecfe)

Verified under the "LOANS" dropdown the following are displayed:
Loans Received from Individual
Loans Received from Bank

Verified under the "DEBTS" dropdown currently nothing is displayed.

QA Review Completed.   Moved to Stage Ready.
