### ISSUE TITLE
1 - Allow user to view Loan and Debt transactions from Manage your Transactions (STEP 4)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1057]
Business Reason

As a user, I will be able to view and access existing Loan and Debt transactions on my report on the Manage your Transactions page.

 Acceptance Criteria

**Given** I am on the Manage Transactions page of a report
**Then** I will be able to see the transaction table for Loans and Debts, which will include the following information:

1. Line Number
2. Transaction
3. Name
4. Amount  _(For a Loan or Debt, this is the "Original Amt." field from when first reported)_
5. Balance _(Loan: Loan Balance, Debt: Amount at Close)_
6. Date _(Loan and Debt: Date Incurred)_
7. Transaction ID _(temporary)_
8. Associated With _(temporary)_

 Wireframe 

![1057 - Transactions in this report – Loan – 2.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/bf387808-bef8-49a8-a728-fe46b1c51907)

### QA Notes ### 
 - Text in italics is informational to indicate what data should pull into the field.
### DEV Notes ### 
 - Please note text in italics for what should pull into which column.
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Any ideas on what columns to show?

**Comment by AureliaKhorsand** [comment]
For now, let's do the following. We can get feedback from FEC/users at a later date.

1. **Line Number** _(with implementation of #828)_
2. **Transaction**
3. **Name** 
4. **Amount**  _(Loan: Original Amt.; Debt: Original Amt. (pulled from when debt was first reported))_
5. **Balance**  _(Loan: Closing; Debt: Closing)_
6. **Date**  _(Loan and Debt: Incurred)_
7. **Transaction ID**
8. **Associated With**
 
Text in italics is just additional information, such as what exactly should pull based on the transaction. Column headers are in bold.

**Comment by AureliaKhorsand** [comment]
Marked as "on hold" until we have answer on capitalization of line numbers, which may result in updated wires. However, otherwise this looks good.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
I talked with @JonellaCulmer this afternoon. Please touch base with her before asking Ryan for input. 

The design was based on the paper form. 
Example attached:
![Screenshot 2023-05-17 at 5.24.56 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d364abd6-c7c8-4154-b898-6215305c9ee4)

**Comment by AureliaKhorsand** [comment]
Note: We should push this through only when we have a Schedule C transaction to test against.

**Comment by toddlees** [comment]
Finished with CR moving to QA with step 1 & 2

**Comment by WiseQA** [comment]
QA review verified "Loans and Debts" are listed in the "Transactions in this report" table.  

Column headings for Loans and Debts verified in this order as denoted in the wireframe:   Line; Type; Name; Date Incurred; Amount; Transaction ID; Associated With; and Actions.  (Note AC had different order and names)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d0a8db07-3f6f-47a3-ae1e-598f6cb75bea)

Verified currently Loans can be saved to the Loans and Debts transactions table #1000

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0193503e-b2dd-4c45-a58e-06258195d55b)

QA Review Completed.   Moved to Stage Ready.
