### ISSUE TITLE
When selecting "Enter" from the keyboard when entering a Receipt or Disbursement Transaction form causes the Transaction to cancel

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1059]
During testing when entering a Receipt or Disbursement transaction form and press the "Enter" key on the keyboard, within the fields (e.g., Date Received, Checking Memo Item, Amount etc.), the Transaction is cancelled and not saved and returns to the "Mange your transactions" page (tested on both STAGE and DEV environments).

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/122358da-1e1b-4285-88d7-d260d05a9897](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/122358da-1e1b-4285-88d7-d260d05a9897))

Transaction cancelled and not displayed in the table.

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e1a3e148-e670-4e9b-9f79-01b5879f3b83](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e1a3e148-e670-4e9b-9f79-01b5879f3b83))

Per review with @MitchellTCG @mjtravers fix when pressing the "Enter" button on the keyboard, the transaction form does not cancel. 2 point bug fix.

***DEV NOTES***

  This issue is not occurring on the other forms. It may be that there is an HTML submit button defined in the HTML template.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-780](https://fecgov.atlassian.net/browse/FECFILE-780)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the following bug has been fixed.  When entering a Receipt or Disbursement then press "Enter on the keyboard, the transaction page remains active and in the same status.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9ed7f72f-3cb9-4b6e-a41c-e180cef0d9d2)

QA Review Completed.  Moved to Stage Ready.
