### ISSUE TITLE
When Modals are displayed can not select "enter" to close modal and background form still active

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1060]
During testing when entering a Receipt or Disbursement transaction form and "Just Checking" modal is displayed, you can not select enter to close modal and the background form is still active.  (tested on both STAGE and DEV environments).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/39982221-53ad-4fc1-b33f-08feae6b36fe)

Bug affects current Modals developed to include:  (Note:  Updated 17 May 2023 with current list for this bug)

new contact modal - Fixed with this bug ticket
delete contacts modal - working as designed modal not affected by this bug ticket
new report modal - Fixed with this bug ticket
just checking modal - Fixed with this bug ticket
create contact in transaction form modal- working as designed modal not affected by this bug ticket
restore deleted contacts modal - Fixed with this bug ticket

Per review with @MitchellTCG @mjtravers fix background form being active when modal is displayed.   5 point bug fix.

**DEV NOTES**
The focus is not getting set to the elements in the modal but staying in the background HTML form. Tab indexing may need to be adjusted. Exploring the PrimeNG API may be of value as this is a commonly used widget and it may have a solution already rolled into the API.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by dheitzer** [comment]
reached out to QA to demo as I cannot reproduce this for:

delete contacts modal
create contact in transaction form modal

**Comment by WiseQA** [comment]
@dheitzer when this bug was found we listed all the current modals in the ticket to check.   If the two you noted above are functioning correctly then we will note as such.   @toddlees provided the initial list for this ticket.   So suggest the following:

Modals developed to include:

new contact modal - Fixed with this bug ticket
**delete contacts modal - working as designed modal not affected by this bug ticket**
new report modal - Fixed with this bug ticket
just checking modal - Fixed with this bug ticket
**create contact in transaction form modal- working as designed modal not affected by this bug ticket**
restore deleted contacts modal

@dheitzer verify from the list QA provided above the ones marked for fixed with this bug are correct.   Adding @toddlees @mjtravers    Thanks !

**Comment by dheitzer** [comment]
@WiseQA yes this is correct.  I could not reproduce this in:

delete contacts modal
create contact in transaction form modal

thanks!

**Comment by toddlees** [comment]
@dheitzer @WiseQA My mistake, "delete contacts modal" was supposed to refer to the Restore Deleted Contacts modal.

I added "restore deleted contacts modal"  to shelly's list in the comment above per her request

**Comment by dheitzer** [comment]
as a technical note - if a `<p-dialog>` is directly after the element that opens it (New button in Contacts for example), tabbing will move directly to the modal.  Otherwise, when this is not feasible (when p-dialog needs to be after a table with actions for example), the `[autofocus]="true"` can be added to an input element inside the modal to make this functionality work.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA verified bug fix for both Receipt and Disbursement.  When Modal is displayed (e.g., Just Checking . . . ) the background form is inactive and if select "enter" from the keyboard the Modal closes.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f78fb84c-943b-4ae0-8df1-b200db84ed72)

QA review verified the following Modals bug fix was implemented.

new contact modal - Fixed with this bug ticket
delete contacts modal - working as designed modal not affected by this bug ticket
new report modal - Fixed with this bug ticket
just checking modal - Fixed with this bug ticket
create contact in transaction form modal- working as designed modal not affected by this bug ticket
restore deleted contacts modal - Fixed with this bug ticket

QA Review Completed.   Moved to Stage Ready.
