### ISSUE TITLE
Note or Memo Text (Optional) field not recognizing characters not allowed

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1061]
During testing when entering a non allowed character in NOTE OR MEMO TEXT (OPTIONAL) field for both Receipts and Disbursement the field does not display the error message "This field contains characters that are not allowed." Upon saving populates error message (tested on both STAGE and DEV environments).

Receipt:

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/774a80bf-2815-4003-9055-d46b1241fd56](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/774a80bf-2815-4003-9055-d46b1241fd56))

Disbursement:

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/82ea4055-ac16-4c5e-b1c0-01e87627a80b](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/82ea4055-ac16-4c5e-b1c0-01e87627a80b))

Error message when selecting "Save"

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5ee3d822-fa0f-4a47-a121-869a751f53d8](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5ee3d822-fa0f-4a47-a121-869a751f53d8))

Per review with @MitchellTCG @mjtravers fix characters not allowed in NOTE OR MEMO TEXT (OPTIONAL) field for both receipts and disbursements. 2 point bug fix.

***DEV NOTES***

  This bug is related to the mapping of the NOTE OR MEMO TEXT field to the MemoText object which has a separate validation schema from the transaction type schemas used to validate all the other form fields on the transaction input page.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-778](https://fecgov.atlassian.net/browse/FECFILE-778)

**Comment by Elaine-Krauss-TCG** [comment]
Memo text description fields now detect invalid characters
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/5b08ac7e-f1d6-484d-8d31-c2a5cf3a2914)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified bug fix - Note or Memo Text (Optional fired recognizes characters not allowed for both Receipt and Disbursement transactions.

**Receipt:**
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6891fe35-6067-4948-b71c-ac218d1ae64b)

**Disbursement:**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7510ef5e-9f4d-4068-a159-1a56bfd3bde0)

QA Review Completed.   Bug Fix Passed.  Moved to Stage Ready.
