### ISSUE TITLE
Allow user to redesignate a Tier 1 Schedule B transaction within current report

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1063]
Business Reason

As a user, I will be able to "Redesignate" a transaction within a current open report so that I can attribute part of the the disbursement amount to a different election.

Acceptance Criteria

***Given*** I am viewing a ***Tier 1*** Schedule B transaction ***on Line 23 or 30b*** on a report In-progress:

*   Contribution to Candidate
*   In-kind Contribution to Candidate
*   Void of Contribution to Candidate
*   100% Federal Election Activity Payment
*   Credit Card Payment for 100% Federal Election Activity
*   Staff Reimbursement for 100% Federal Election Activity
*   Payment to Payroll for 100% Federal Election Activity
*   Void of 100% Federal Election Activity
*   CONDUIT_EARMARK_OUT
*   PAC_CONDUIT_EARMARK_OUT

***When*** I initiate a ‘Redesignate’ function for that transaction

  ***Then*** I will be able to indicate the how much should be redesignated and to which election, as follows:

—

1.  Contact

       #

*   _(Contact will auto-pull from original disbursement)_

1.  Address

       #

*   _(Address will auto-pull from original disbursement)_

1.  Expenditure information

       #

*   ***REDESIGNATION DATE*** (Required)
*   ***MEMO ITEM*** (Required, automatically checked by the system and user cannot change it)
*   ***REDESIGNATION AMOUNT*** (Required, must be positive and cannot exceed amount of original disbursement)

1.  Committee/Candidate information

       #

*   Committee/Candidate values should match the original contribution

1.  ELECTION INFORMATION

       #

*   ***ELECTION CODE*** (Required)
*   ***ELECTION YEAR*** (Required)
*   ***ELECTION DESCRIPTION*** (Required if Election Code is Other)

1.  Additional information

       #

*   ***PURPOSE OF DISBURSEMENT*** (Required, system generated) 
      *   "Redesignation - Contribution from XX", where XX = Date of Original Transaction
*   ***NOTE OR MEMO TEXT*** (Optional)
*   ***CATEGORY CODE*** (values should match the original disbursement and be read-only)

—

***And*** the system will auto-generate a transaction showing amount and election _redesignated from_ with the following information:

1.  Contact

       #

*   _(Contact will auto-pull from original disbursement and user cannot edit it)_

1.  Address

       #

*   _(Address will auto-pull from original disbursement and user cannot edit it)_

1.  Expenditure information

       #

*   ***REDESIGNATION DATE*** (required, auto-generated from "Redesignation To" transaction)
*   ***MEMO ITEM*** (required, automatically checked by the system and user cannot change it)
*   ***REDESIGNATION AMOUNT*** (required, auto-generated from "Redesignation To" transaction and _made negative_)

1.  Committee/Candidate information

       #

*   Committee/Candidate values should match the original disbursement and user cannot edit it

1.  ELECTION INFORMATION

       #

*   Election Information values should match the original disbursement and user cannot edit it

1.  Additional information

       #

*   ***PURPOSE OF RECEIPT*** (Required, system generated) 
      *   "Redesignation - Contribution from XX", where XX = Date of Original Transaction
*   ***NOTE OR MEMO TEXT*** (Optional)
*   ***CATEGORY CODE*** (values should match the original disbursement and be read-only)

***Then*** I will be able to:

*   Cancel
*   Edit
*   Save transactions (users must save both at the same time)

***And*** upon saving:

*   both transactions will be saved as memo items with line numbers matching the original disbursement.
*   both will be associated to the original disbursement by their back reference IDs.
*   the original transaction will have ***PURPOSE OF DISBURSEMENT*** updated to (Required, system generated) 
      *   "See redesignation below."
*   on the backend, 
      *   Original transaction: REATTRIBUTION REDESIGNATION TAG set to REDESIGNATED
    *   First transaction above (Redesignated To): REATTRIBUTION REDESIGNATION TAG set to REDESIGNATION_TO
    *   Second transaction above (Redesignated From): REATTRIBUTION REDESIGNATION TAG set to REDESIGNATION_FROM

***And*** when the user opens a redesigated transaction, it will take them back to the "Redesignation From/To" entry form.

Dev Note

*   This functionality should ONLY be for Tier 1 (parent) Line 23 and 30b transactions.
*   This will be a **[specification overlay]([https://docs.google.com/spreadsheets/d/1AbYjbtwZNuB8Y1GHAXMwSzxJW41Pr_3J/edit#gid=1399838959)**](https://docs.google.com/spreadsheets/d/1AbYjbtwZNuB8Y1GHAXMwSzxJW41Pr_3J/edit#gid=1399838959)**), with specifications here replacing those on the original receipt. The remaining specifications will match the original.
*   Original transaction: REATTRIBUTION REDESIGNATION TAG set to REDESIGNATED
*   First transaction above (Redesignated To): REATTRIBUTION REDESIGNATION TAG set to REDESIGNATION_TO
*   Second transaction above (Redesignated From): REATTRIBUTION REDESIGNATION TAG set to REDESIGNATION_FROM

Wireframes

1.  Select Redesignation
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlIyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd20a9fa842908a77bbe44750606be55b35f13bf/1063%20-%20Kabob%20%E2%80%93%201.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlIyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd20a9fa842908a77bbe44750606be55b35f13bf/1063%20-%20Kabob%20%E2%80%93%201.png))

1.  Redesignation to
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3dWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83beacd648ed0e9435473df45e8abbe99a0c3e83/1063%20-%20Redesignation%20to.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3dWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83beacd648ed0e9435473df45e8abbe99a0c3e83/1063%20-%20Redesignation%20to.png))

1.  Redesignation from
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzBWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b8f3f5c6932149e9626b5ceffc75ef48b4f2e52/1063%20-%20Redesignation%20from.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzBWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b8f3f5c6932149e9626b5ceffc75ef48b4f2e52/1063%20-%20Redesignation%20from.png))

UX Tasks

*   [x] change "REDESIGNATION AMOUNT" to "REDESIGNATED AMOUNT"
*   [x] Update the Committee/candidate box to have First Name, Last Name, Middle , Prefix and Suffix. and replace on all mocks in 1063

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
- [x] BA/Design Quality Checklist complete
- This functionality should ONLY be for Tier 1 (parent) Line 23 and 30b transactions.

 See full ticket and images here: [FECFILE-777](https://fecgov.atlassian.net/browse/FECFILE-777)

**Comment by MitchellTCG** [comment]
@JonellaCulmer  & @mary-tcg 
Please review these wires for design considerations

THIS DESIGN IS NOT FINAL BECAUSE THE REQUIREMENTS ARE NOT FINAL
I will review after reqs are finalized

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg should it be "REDESIGNATED AMOUNT" instead of "REDESIGNATION AMOUNT", to match the conjugation on the Reattribution forms? Also, CANDIDATE NAME should be split out into First Name, Last Name, prefix, suffix, as usual.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
these month old edits are finally made

@GreggMoreland 
please review

**Comment by mjtravers** [comment]
Notes from CR: 

- The first transaction should auto-populate with information from the original disbursement and those form fields be read-only (or it looks that way from the wire frames but not mentioned in acceptance criteria).
- The subtitle text below "Redesignation" does not match the wire frame.
- The text after "ENTER DATA" does not match the wire frame.
- The PURPOSE OF DISBURSEMENT text in both transactions do not match the acceptance criteria.
- It looks from the wire frames that all the form fields for the second transaction should be read-only but the acceptance criteria only mention the CATEGORY CODE to be read-only. Will need to ask the BAs for clarification.

Sending to In Progress to address changes.

**Comment by GreggMoreland** [comment]
@mjtravers AC's were updated in second transaction to match the language that is in the similar reattribution ticket. The fields are read only, just as they were in the reattribution ticket.

**Comment by sasha-dresden** [comment]
Fixed these issues. I also added a check so that the Redesignation option will only appear for Schedule B's which have Elections. For example a "Contribution to a Candidate" transaction would have it as an option, but an "Operating Expenditure" transaction would not.

**Comment by toddlees** [comment]
@GreggMoreland can you confirm @sasha-dresden 's change above?

**Comment by mjtravers** [comment]
A few things noticed in CR:

For the "Redesignated To" section:
1. MEMO ITEM should be checked and read-only
2. In the Committee/Candidate info section: I'm seeing things like labels off shade and sometimes the STATE is editable:

Shading off:
<img width="641" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUxFQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6a9920a1004c2de84af840afc3591ebbf82649b/image.png" alt="image.png" />

State is editable:
<img width="641" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVRFQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8d9b8f87e330e2b3f4db0ceb84272664d27253d/image.png" alt="image.png" />

For "Redesignated From" section:
1. Does the order of the info blocks matter? The AC has expenditure info above the Committee/Candidate information and the election information. There is a way to change this in the double entry template.
2. PURPOSE OF DISBURSEMENT has “Rattribution to null” in the box. Should be: "Redesignation - Contribution from XX", where XX = Date of Original Transaction
3. NOTE OR MEMO TEXT should be editable

Sending back to In Progress

**Comment by AureliaKhorsand** [comment]
@sasha-dresden limiting this to only transactions with election information sounds right, but I need to check with FEC because they explicitly said it should be only open to all of Schedule B (though I don't see how you can redesignate something with no election fields). Stand by, asking this morning.

@mjtravers the order of the info blocks should match what the original transaction had the best we can. Typically it will show the Candidate/Committee information _after_ the Expenditure information.

**Comment by AureliaKhorsand** [comment]
@sasha-dresden ACs updated to specify only Line 23 and 30b transactions on Schedule B. Thank you for catching!

**Comment by sasha-dresden** [comment]
@mjtravers I fixed those edits you caught. Ready for code review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
**QA review tested using Login.gov and Test Committee ID C00100495 assigned to QA for testing.**  **(Tested using Contribution to Candidate disbursement transaction (Schedule B))   NOTE:  e2e testing to be updated to test all transactions**

___________________________________________________________________________________________________________________

Under the "Actions" dropdown select "Redesignate"

<img width="1246" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2IyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbc6e1cb8b389bdc394f2a39a910e527816451eb/image.png" alt="image.png" />

________________________________________________________________________________________________________________________

Verify contact and address information has been populated from transaction.

<img width="1353" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0QzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15b4535382cd439b949dfd64f56c839886769c59/image.png" alt="image.png" />

_______________________________________________________________________________________________________________________

@MitchellTCG @mjtravers @AureliaKhorsand the wireframes show the labels as:
Election Type > New Election Type
Election Year > New Election Year
Election Description > New Election Description

1.  Are the labels to be changed per wireframes and the word "New" added to labels for "Redesignation to"?

<img width="609" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUgzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--182e54b30c3e71c748be8f6ba6b59a2676aa255d/image.png" alt="image.png" />

____________________________________________________________________________________________________________________

Form currently showing the following (Redesignation to):

<img width="1078" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVQzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db8abf3a415f5c92e85f4e5135f822338886aa32/image.png" alt="image.png" />

**Comment by mjtravers** [comment]
Patch deployed that adds the "NEW" prefix to the election input labels for REDESIGNATED_TO transaction. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified "NEW" prefix was added to the election input labels for REDESIGNATED_TO transaction.

<img width="893" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN01CQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d146253c688116acdefd26b81d7c774e562f0d0/image.png" alt="image.png" />
_______________________________________________________________________________________________________________________
<img width="1239" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjhCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d1f4ad0034bb25334371b911246584ef9761e29/image.png" alt="image.png" />

Retested "Redesignation to" verified fields auto populating correctly and read only.

<img width="1199" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1FCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d26480faccff7c6add347f7d4d99a6778fa4756/image.png" alt="image.png" />

______________________________________________________________________________________________________________________

Retested "Redesignation from" verified fields auto populating correctly and read only.

<img width="842" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2NCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c26e6084bfa4dc1c9360edef7e44b505168cb54e/image.png" alt="image.png" />

_______________________________________________________________________________________________________________________

Verified PURPOSE OF DISBURSEMENT (SYSTEM-GENERATED) field is populated correctly.

<img width="467" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN29CQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5eaccd6102a1f49e408f62eb0a589db3733bbff/image.png" alt="image.png" />

_________________________________________________________________________________________________________

Verified orginial transaction, "Redesignated to" and "Redesignated from" transactions are displayed in the "Transactions in this report table"   Verified the "transaction IDs" and "associated with" 

<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3dCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--622e1041dfc0f6f02e3d2d7cf3477024a16bb418/image.png" alt="image.png" />

______________________________________________________________________________________________________________

QA Review Completed.    Moved to Stage Ready.
