### ISSUE TITLE
6 - System to pull outstanding loan transaction(s) forward when a new report is created

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1069]
Business Reason

As a user, I will be able to see any outstanding Schedule C loans pull forward onto any new report I create until that loan balance is $0 so that I can continue to report outstanding loans and associate repayments as needed.

Acceptance Criteria

***Given*** a user has Schedule C loan(s) on a previous report,

  ***When*** the user creates a new report in the future,

  ***Then*** the Schedule C Loan(s) will be pre-populated in the report along with any associated Guarantor information (C2s) if they meet the following conditions:

*   loan balance ***other than $0***
*   loan is _not_ marked as a memo item.

***And*** the transaction ID will be the same as the original.

—

***Given*** the following transactions have pulled forward,

  ***then*** the fields will not change rules regarding if they can be edited or not (i.e., if they were editable before, they are editable now):

*   Loan Received from Bank
*   Loan Received from Individual
*   Loan by Committee

Wireframe

  ![1069-System to pull outstanding loan forward.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7f41d071-a68e-418d-aa13-919fb16f691c](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7f41d071-a68e-418d-aa13-919fb16f691c))

### QA Notes ###
- Note that in order for the loan to not pull forward, it either must be marked as a memo item or have a balance of _exactly_ $0, not more or less.
- This will NOT include the auto-generated Schedule A or Schedule B transactions or the C1 (Loan Agreement) created when the user first saved these loans on the original report.
- The transaction ID must be the same as the original.

### DEV Notes ###
- "Date Incurred " will NO LONGER have the validation that it must be within report coverage dates. 
- The transaction ID must be the same as the original. 
- A new field will be added to the transaction table that will hold the UUID of the originating transaction for copied forward transactions. We can use this as a flag so the transaction type code knows the transaction is a pulled forward transaction

### Design ###
null

 See full ticket and images here: [FECFILE-774](https://fecgov.atlassian.net/browse/FECFILE-774)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Please review

**Comment by MitchellTCG** [comment]
@GreggMoreland 
This appears to only be a reference wire but all looks good. 
UX review complete

**Comment by GreggMoreland** [comment]
BA Review Complete

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified outstanding loans are pulled forward when a new report is created with future dates.  

1.  Created Monthly Report (February 20 Monthly Report (M2) - Report dates 01/01/2000 - 01/31/2000)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHZUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8eed9be918ae1cb3c47cb248459058e761d469d1/image.png)

2.  Verified Loans displayed in transactions table
3.  Verified Transaction IDs

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ3pUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0bd645d683f480b0b4f85946d3c8127c2804ae6c/image.png)

4.  Verified when creating new Monthly Report (March 20 Monthly Report (M3) - Report dates 02/01/2000 - 02/28/2000)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaC9UIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7a8d0d9d89dab417c5b624c71fb95cd1c09531d3/image.png)

5.  Verified Loans displayed in transactions table
6.  Verified Transaction IDs

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVBUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--03eedb8e04ed7d861c63fec07f791ff4f415146c/image.png)

QA Review Complete.  Moved to Stage Ready.
