### ISSUE TITLE
Allow user to create Committee contact using Lookup feature (Contact Management)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#107]
Business Reason 
 

As a Committee Administrator, I will be able to create a Committee contact associated with my committee using the Lookup feature to find a Committee already registered with FEC so that I can pull them into necessary transactions and reports as needed.

 Acceptance Criteria 
 

**When** I go to Contact Management
**And** add a new contact with the Type "Committee"
**Then** I will have the option to create a new contact using the FEC Lookup
**And if** I use the FEC Lookup, it will:

- Appear in the search dropdown under "Create a new contact from the list of registered Committees"
- highlight the matching text from the search box within the results
- highlight a selection grey if hovered over with the pointer
- be limited to **5** maximum _(Dev/QA note: for now, users need to type more to narrow it down. #542 will address when results are more than 10.)_

**And** when I select a contact from the FEC Lookup dropdown,
**Then** the contact entry screen will be populated with relevant info and I can continue editing the new contact.

# Wireframes 
#
![107 - Committee contact using Lookup feature 1.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8b5ec791-0f85-4426-a8a0-a3a52bfbbd1b)
![107 - Committee contact using Lookup feature 2.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/14243cb0-0a56-4587-947f-cef6f5d4929d)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/16/22:** Need to confirm the endpoint we are pulling from, and that it is the appropriate place to pull from. This determination is included in the scope of the ticket and pointing - we cannot assume that this is working at the transaction level. 

Because telephone number is not essential for reporting, if the API endpoint does not give us the phone number, we do not need to go out of our way to pull it in. The field can remain as blank. Pointed at 8.

**Comment by AureliaKhorsand** [comment]
Per Laura on Slack 2/16/22: It looks like the lookup is calling from the fecfile API database, which would mean we'd need some sort of ETL to get committee/candidate data in there. I think because committee info is updated daily, we should probably just be calling the FEC API. https://api.open.fec.gov/v1/committee/C00344234/?api_key=DEMO_KEY

https://api.open.fec.gov/developers/#/committee

**Comment by MitchellTCG** [comment]
Wireframes under UX Review.

**Comment by toddlees** [comment]
example of committee name on FEC not matching the validation rules defined in this ticket:

`LENOVO (UNITED STATES) INC. NON-PARTISAN CMTE FOR GOOD GOVT (LENOVOPAC)`
special characters `().-` present in name

**Comment by MitchellTCG** [comment]
wires

![Add_New_Contact_Committee_Lookup.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/cb625403-751d-4711-88db-5ff7d6d58d81)

![Add_New_Contact_Committee_Manual.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/5d89b02c-e8e8-4f94-9a9d-ed0d52054769)

https://images.zenhubusercontent.com/306118986/57a3cd9c-d254-414a-aebd-4ec0d7d864a9/add_new_contact_committee.mp4

**Comment by lbeaufort** [comment]
**4/6/22 Refinement Meeting**: 
Should be able to use https://api.open.fec.gov/developers/#/search/get_names_committees_ for search (example https://api.open.fec.gov/v1/names/committees/?api_key=DEMO_KEY&q=pelosi
) and 
https://api.open.fec.gov/developers/#/committee/get_committee__committee_id__history_ (example https://api.open.fec.gov/v1/committee/C00344234/history/?api_key=DEMO_KEY) for candidate info.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG at requirements session, discussed how we need a new template for this in Contact Management. Design team to confer at the weekly UX review for solutions.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @mary-tcg @JonellaCulmer 
Updated

**Comment by dheitzer** [comment]
want to confirm UI implementation before sending to CR.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @dheitzer @WiseQA 

Wireframes have been updated. Sorry for the confusion.
And thank you David for finding the inconsistency in my mock and bringing it to my attention.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified when adding a Committee contact the lookup field is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/81cd2b21-bda8-41ce-8ca2-ba5c2ab9a59d)

When entering text in search field the Committee's are displayed, verified when hoovering over selection becomes grey.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a5feec26-cc45-406e-b006-2c1d1c5e526f)

Verified when selecting contact the Committee ID and Name address (all required fields) are displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/09754d2f-a57b-460d-a3f5-3f39958e36bf)

Verify new Committee is saved and displayed in the Manage Contacts list.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1e0879f2-3efe-42ab-aa19-7060699a0ea4)

QA Review Completed.  Moved to Stage Ready.
