### ISSUE TITLE
Allow user to create Candidate contact using Lookup feature (Contact Management)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#108]
Business Reason

As a Committee Administrator, I will be able to create a Candidate contact associated with my committee using the Lookup feature to find a Candidate already registered with FEC so that I can pull them into necessary transactions and reports as needed.

Acceptance Criteria

***When*** I access Contact Management

  ***And*** add a new contact with the Type "Candidate"

  ***Then*** I will have the option to create a new contact using the FEC Lookup

  ***And if*** I use the FEC Lookup, it will:

*   highlight the matching text from the search box within the results
*   highlight a selection grey if hovered over with the pointer
*   be limited to ***5*** maximum _(Dev/QA note: for now, users need to type more to narrow it down. #542 will address when results are more than 10.)_

***And*** when I select a contact from the FEC Lookup dropdown,

  ***Then*** the contact entry screen will be populated with relevant info and I can continue editing the new contact.

1.  Wireframes

       #

       ![108 - Candidate contact using Lookup feature 1.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/567358fd-afc9-4965-8a4c-a7c8098fccbb](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/567358fd-afc9-4965-8a4c-a7c8098fccbb))

       ![108 - Candidate contact using Lookup feature 2.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a828812a-6c0f-4112-a28c-f549c0769630](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a828812a-6c0f-4112-a28c-f549c0769630))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1303](https://fecgov.atlassian.net/browse/FECFILE-1303)

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/16/22**: Back to AA, need to determine how to display names when candidate is running for multiple offices. 

Dev Note: Budget time for refactoring.

**Comment by AureliaKhorsand** [comment]
@mjtravers this is the front-end ticket for what we discussed during the 3/10 requirements meeting. It's ready for a related technical ticket - also please let me know if anything here needs to be updated. 

Requirements sessions notes [here](https://docs.google.com/document/d/1QP9K0yV2G9YJ5ZDhty9ialDbO73sBaAf33_XIgoclco/edit).

**Comment by MitchellTCG** [comment]
Wireframes under UX Review.

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 3/30/22**: Need to hash out the special characters allowed in contact fields before we can move this forward. For example, would we need to pull "parentheses" out if they aren't accepted here but come over from FEC?

BA Note: Update with requirement that the information from Lookup can be editable, and will not feed back to FEC.

**Comment by toddlees** [comment]
example of candidate name on FEC not matching the validation rules defined in this ticket:

`O'CONNOR, DANIEL JAY JR.`
special characters `'` present in name and `.` in suffix

**Comment by MitchellTCG** [comment]
wire
https://images.zenhubusercontent.com/306118986/ce3f2ad8-532c-47fc-a559-6efa3b0d00a6/add_new_contact_candidate.mp4

![Add_New_Contact_Candidate_Lookup.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f0aa4f77-c2fa-41e1-badb-5c9f09942f51)

![Add_New_Contact_Candidate_Manual.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/9c18eeb1-52be-4ca7-97b6-f2f8b23498e5)

**Comment by AureliaKhorsand** [comment]
**4/6/22 Refinement Meeting**: Removed Employer and Occupation since FEC will not be providing that data for a Candidate contact type.

**Comment by lbeaufort** [comment]
**4/6/22 Refinement Meeting**: 
Should be able to use https://api.open.fec.gov/developers/#/search/get_names_candidates_ for search (example https://api.open.fec.gov/v1/names/candidates/?api_key=DEMO_KEY&q=pelosi
) and 
https://api.open.fec.gov/developers/#/candidate/get_candidate__candidate_id__history_ (example https://api.open.fec.gov/v1/candidate/H8CA05035/history/?api_key=DEMO_KEY) for candidate info.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @mary-tcg @JonellaCulmer 
Updated

**Comment by dheitzer** [comment]
Initial implementation complete.  Reached out for clarification on how to proceed with open FEC candidate endpoint not returning separate names (first_name, last_name, suffix, prefix, etc).

**Comment by dheitzer** [comment]
Per discussion with Laura & Matt on 2/21/23, we decided to move forward with this ticket by doing a simple comma split on the "name" field coming back from the open FEC API and populating First Name/Last Name accordingly.  Laura opened an FEC ticket to address adding the other name fields (middle, prefix, suffix) to their candidate API.  Per Laura on 2/21:

[Here's the ticket for the openFEC work](https://github.com/fecgov/openFEC/issues/5347) - I ran it by 
@pat
 to make sure it looked ok and to make sure she's ok with putting in the PR.
Because we realized paper filed F2's won't have parsed data, my recommendation is now:

- start with parsing first and last name from candidate name using ", " as the delimiter

- :white_check_mark:  enter ticket in openFEC to add candidate_firstname etc

- (tentatively) Laura puts in a PR

- Once the work is complete, modify the FECFile logic to use parsed name fields (candidate_firstname etc) and fall back on parsing  name  ourselves only when the parsed fields are unavailable (IE, paper filers)


We will then address retrieving these additional name fields from the API in ticket TBD.

**Comment by dheitzer** [comment]
want to confirm UI changes before sending to CR.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @dheitzer @WiseQA 

Wireframes have been updated. Sorry for the confusion.
And thank you David for finding the inconsistency in my mock and bringing it to my attention.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified when adding a Candidate contact the lookup field is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/93db77f9-3159-4871-992d-f91e38bb3c1d)

When entering text in search field the Candidate's are displayed, verified when hoovering over selection becomes grey.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d0892c78-f6f6-4b29-b996-9f4c9cce1293)

Verified when selecting contact the Candidate ID and Last Name, First Name, address, candidate office, candidate state (all required fields) are displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ab4d7f38-ee6c-46d5-91fa-a178c9157d88)

Verify the new candidate is saved and displayed in the Manage Contacts List.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5178e791-6e24-4856-b75d-a45292f0dbbd)

QA Review Completed. Moved to Stage Ready.
