### ISSUE TITLE
Allow user to enter Independent Expenditure on Schedule E 

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1082]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Independent Expenditure"** transaction on Schedule E of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** go to Add a disbursement
**Then** I can enter a transaction with the type “Independent Expenditure" under the "Independent Expenditures" Accordion link  
**Then** I will be required to enter the following information (unless otherwise noted):

 Payee 
#
-	**LOOKUP**
Dropdown options: Organization, Individual
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure information 
#
-	**DISSEMINATION DATE** (At least one date is required. If one is entered, the other is optional)
-	**DISBURSEMENT DATE** (At least one date is required. If one is entered, the other is optional)
-- Note: If only one date is present, that date must be within the report coverage period. If both dates are present, the Date of Disbursement must be within the report coverage period.

-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be negative)
-	**CALENDAR YEAR-TO-DATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- For the selected ELECTION CODE/ELECTION YEAR and Candidate selected
--- within Aggregation Group of "INDEPENDENT_EXPENDITURE"
--- _from_ January 1 of report year _to_ the Disbursement Date of the transaction. 
--- (**IF** Disbursement Date is not entered, then use Dissemination Date of the transaction.)

# Candidate information 
#
-	**SUPPORT/OPPOSE CODE** (Required, values Support, Oppose)
**And** the user will be required to select a Candidate using the LOOKUP, and upon selection the following will be populated:
-	**CANDIDATE ID** (Required)
- 	**CANDIDATE  LAST NAME** (Required)
-	**CANDIDATE FIRST NAME** (Required)
-	**CANDIDATE MIDDLE NAME** (Optional)
-	**CANDIDATE PREFIX** (Optional)
-	**CANDIDATE SUFFIX** (Optional)
-	**CANDIDATE OFFICE** (Required)
-	**CANDIDATE STATE** (Required if (CANDIDATE OFFICE is 'House' or 'Senate') or If (CANDIDATE OFFICE  = President and the Election Code = P-Primary))
-	**CANDIDATE DISTRICT** (Required if CANDIDATE OFFICE is 'House')

# Election information
#
-	**ELECTION CODE** (Required)
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Other)

# Additional information 
#
-	**PURPOSE OF EXPENDITURE** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

#  Committee treasurer 
#
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

-	**DATE SIGNED** (Required)

---
**Then** I will be able to:
- Cancel
- Save 
- Edit

**And if** the ENTITY aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SE.

**If** the ENTITY aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 Dev Note 

- Front-end field for "treasurer" maps to "COMPLETING" name on specification spreadsheet
- Support and Oppose radio buttons are unselected upon initial load but a choice is required. Candidate lookup will then be displayed and available for the user.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/15hqrgTeto1hp7i_9-jd719kTM9UNjN6qUPq-xOlJOco/edit#gid=1786117945) **This is a consolidated specification**

 Wireframes 

# IE Form Candidate Info Collapsed
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWppIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a96291fd8c0af6516f6ba450dd82d0e2fb153734/1082%20-%20Allow%20user%20to%20enter%20Independent%20Expenditure%20on%20Schedule%20E%20%E2%80%93%205.png)

#  IE Form with Candidate Info Expanded
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa25oIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb89d91fef2d8ee5c011b97fc75ccb821bcee51a/1082%20-%20Allow%20user%20to%20enter%20Independent%20Expenditure%20on%20Schedule%20E.png)

#  Expenditure Info error
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3ZoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0b8b409bca49ef0044f90dc0428b4ec87db873b1/1082%20-%20Allow%20user%20to%20enter%20Independent%20Expenditure%20on%20Schedule%20E%20%E2%80%93%20ERROR%20%E2%80%93%201.png)

#  Candidate Info Errors
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXJpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1788339100f237480d713ac89d05e71aad82dc41/1082%20-%20Allow%20user%20to%20enter%20Independent%20Expenditure%20on%20Schedule%20E%20%E2%80%93%20ERROR.png)

 One Date Entered - Outside Report Range
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnoxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4d75ba6b0edc9d046f6350516cd2ecf169315bb1/Screenshot%202023-10-02%20at%208.53.15%20AM.png)

 Both Dates Entered - Disbursement Outside Report Range
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjMxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b85b6f763cbaca3403374b91270898f1c71644ec/Screenshot%202023-10-02%20at%208.55.02%20AM.png)

 After closing modal window
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUltQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0415ac96b9ade62edc3acdfd01ddfc66b418df2a/Screenshot%202023-10-11%20at%2010.17.52%20AM.png)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 - [x] BA/Design Quality Checklist complete
- ENTITY can be Organization or Individual but should default to Organization.
- **(NOTE: aggregate calculation is being done in #1386)** There are two aggregates calculated on the back end. There is the aggregate that populates "Calendar Y-T-D" on the front-end, and the ENTITY aggregate, which determines itemization. This aggregate is the total of transactions:
--- From the person (ENTITY) 
--- within Aggregation Group of "INDEPENDENT_EXPENDITURE"
--- _from_ January 1 of report year _to_ the Disbursement Date of the transaction. 
--- (**IF** Disbursement Date is not entered, then use Dissemination Date of the transaction.)

**Comment by mary-tcg** [comment]
@AureliaKhorsand @GreggMoreland @MitchellTCG wireframe added

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg can we show the Candidate information collapsed in a wire, then expanded in the other with the data filled in? Also, a wire showing the validation error if the Candidate information is not entered (should look the same as #1164). Same changes for #1117.

We also need the error message similar to #294 to apply for the dates. It's odd, because if one date is present, that error applies, but if both are present, it only applies to Disbursement date.

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Wires posted and UX review complete
please note that Support and Oppose radio buttons are unselected upon initial load but a choice is required

**Comment by MitchellTCG** [comment]
Wires are updated

**Comment by mjtravers** [comment]
@MitchellTCG @mary-tcg Can we change the MEMO ITEM error message when the date is out of range from "An answer is required." to "This is a required field."? This would keep the message consistent across transaction type entry forms.

@MitchellTCG ticket in QA bucket was there an answer to the above question ?

**Comment by mjtravers** [comment]
@WiseQA Until ticket #1386 is done, the CALENDAR YEAR-TO_DATE value will simply match the AMOUNT value.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then under "Independent Expenditures"  select 'Independent Expenditure" transaction page is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1VsQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--118456bcde3976458a9026a863fb8c06713a29d2/image.png)

Verified LOOKUP is defaulted to Organization.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2dsQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1ee8850db5c16a9d620f75919bb81cacf242cf6/image.png)

Verified entering Dissemination Date outside report coverage dates the "Just checking ... " popup window is displayed.  Memo Item becomes a required field.  

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ltQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b5c84752942b80df32227bb2e3d7d769d7066e1/image.png)

Verified entering Disbursement Date outside report coverage dates the "Just checking ... " popup window is displayed.  Memo Item becomes a required field.  

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3NtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a165a3531ea67bff34eff496fe480ecc56cf60e/image.png)

Verified error message displayed "At least ONE date field must be entered"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzBtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d194a4b7f94fd659eb95c102337f0c9496fe411e/image.png)

Verified Candidate information error message displayed "An answer is required"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWttQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4911e19cb14523d174f6067cdc764c55a9b1a8a/image.png)

Verified "This is required field" is populating correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTRtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65a67539938af1c7f4ed5d33838fa6125becf0c8/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeThtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4cf091d4550d10f19fe75dc5f3c86765a18ffda9/image.png)

Verified once selected "Support" and/or "Oppose" the LOOKUP for Candidate is displayed and error message displayed "Candidate information is required"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME1tQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4102ab69eb465badd333fcc8a615201edd6e1e0c/image.png)

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG per discussion ticket placed on hold to clarify the following;

1.  Which dates are populated in the Transactions table.  Disbursement Date field **has to be filled in to populate the table**. The Dissemination Date field **does NOT populate in the table**.

2.  Line number missing from table and ticket ?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelVuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--933bb905ef5c2999aff026cd79c9cdb64c9d6ed5/image.png)

**Comment by AureliaKhorsand** [comment]
@WiseQA great catches. 
1. For this ticket, do not worry about making sure the date shows here. BAs will talk to FEC about if they want dissemenation date to show or not if Disbursement date is not present, and that will be a separate ticket, since there are no requirements in this ticket for this column.
2. It should be Line 24, that may be a dev question.

**Comment by WiseQA** [comment]
QA review verified the transactions table to display date column as currently designed.  The Disbursement Date field will be populated in the date column of the transactions table **only** at this point.   (NOTE:  Future clarification with FEC to determine if the Dissemination Date field will populate in the date field if Disbursement date is NOT filled in in the transaction)   

Line number 24 has been added to the transactions table for the Independent Expenditure disbursement transaction.

**Comment by WiseQA** [comment]
QA review retested transaction and verified transactions action table is being updated correctly (by current design / requirement).   Line 24 verified added for Independent Expenditure disbursement transaction.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3NvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae432aff671af6b539376d3932bd4e5fc377bc98/image.png)

QA Review Completed.  Moved to Stage Ready.

**Comment by WiseQA** [comment]
Ticket placed on-hold as a DEFECT #1456 was found during Sprint 32 demo.   DEFECT #1456 PASSES.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEozQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf0fb8e73e27e097e7c514f51649240e53d5d394/image.png)

@MitchellTCG IE Transactions have been retested and validated as Passing for Sprint 32.  Removed on-hold and closed.
