### ISSUE TITLE
1 - Allow user to enter Debt Owed to Committee on Schedule D

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1091]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Debt Owed to Committee”** transaction on Schedule D of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a Loans and Debts
**Then** I can enter a transaction with the type “Debt Owed to Committee "
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Lendee 
#
-	**CONTACT TYPE**
Dropdown: Committee, Organization, Individual
**Note** Default to Committee
 
---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Debt or Obligation Information 
#
-	**BEGINNING BALANCE** (AMT-12, Required, system auto-calculated, set to $0.00 for initial implementation)
-	**INCURRED AMOUNT** (AMT-12, Required, can be negative)
-	**PAYMENT AMOUNT** (AMT-12, Required, system auto-calculated, set to $0.00 for initial implementation)
-	**BALANCE AT CLOSE** (AMT-12, Required, system auto-calculated, set to INCURRED AMOUNT for initial implementation)

# Additional information 
#
-	**PURPOSE OF DEBT OR OBLIGATION** (A/N-100, Required)

---
**Then** I will be able to:
- Cancel
- Save 
- Edit

**and** upon saving the debt will be itemized as a "SD9" and accessible in the Loans and Debts section of the transactions table.

 QA Note
- BEGINNING BALANCE and BALANCE AT CLOSE will have the auto-calculations implemented in #1195. 
- PAYMENT AMOUNT will have the auto-calculations implemented in #1212. 

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1ykulNJdRI6J_PwVWk80QzBaopHZKVaEkgEjDo7RHeKQ/edit#gid=1956508297) **Please note this is a consolidated specification.**  

 Wireframe
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFpyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d92d910e22de0c72aadb5bc78fa979f33be66d0d/1091%20-%20Allow%20user%20to%20enter%20Debt%20Owed%20to%20Committee.png)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Please review

@mary-tcg finished these on Friday and I forgot to review them

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg same as #1093, please set Payment Amount to $0 and read-only. Also, the text at the top should specify "Lendee", not "Lender" for this scenario.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Updated

**Comment by mjtravers** [comment]
@GreggMoreland There is an optional Memo Item checkbox in the acceptance criteria and wireframe but the Schedule D spec does not have a spot for it. Should the Memo Item be removed?

**Comment by mjtravers** [comment]
Passes CR. Ready for QA pending the decision about the table sorting for Loans & Debts not working.

**Comment by mjtravers** [comment]
On hold until we learn if memo code is part of the Schedule D spec

**Comment by mary-tcg** [comment]
Updated wire to reflect new requirement clarification (no memo item checkbox, no memo text)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA review verified when adding a "Debt Owed To Committee" transactions page is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXB5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dbae1c506b1b7d6d2ca6f5d5c63403df3999d547/image.png)

Verified Contact Type is defaulted to Committee.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXR5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9d2f6d9bae59e9931863b375011feaba96f5962d/image.png)

Verified "INCURRED AMOUNT" is a required field.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXh5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5c2d6a11fc4cc2aae7efdf6836f422158aa3011c/image.png)

Verified "PURPOSE OF DEBT OR OBLIGATION (REQUIRED) displays as required field if information not entered.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmh5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--17456de9409cb1c1b49f26bcd01cd1bbf3bfe64b/image.png)

Verified "Debit Owed To Committee" is saved and displayed under Loans and Debts in the transactions table.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc055IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5913cd72ef9454d3e086173de1d62c06940051c5/image.png)

QA Review Completed.   Moved to Stage Ready.
