### ISSUE TITLE
1 - Allow user to enter Debt Owed by Committee on Schedule D

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1093]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Debt Owed by Committee”** transaction on Schedule D of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a Loans and Debts
**Then** I can enter a transaction with the type “Debt Owed by Committee "
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Lender 
#
-	**CONTACT TYPE**
Dropdown: Organization, Committee, Individual
**Note** Default to Organization
 
---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Debt or Obligation Information 
#
-	**BEGINNING BALANCE** (AMT-12, Required, system auto-calculated, set to $0.00 for initial implementation)
-	**INCURRED AMOUNT** (AMT-12, Required, can be negative)
-	**PAYMENT AMOUNT** (AMT-12, Required, system auto-calculated, set to $0.00 for initial implementation)
-	**BALANCE AT CLOSE** (AMT-12, Required, system auto-calculated, set to INCURRED AMOUNT for initial implementation)

# Additional information 
#
-	**PURPOSE OF DEBT OR OBLIGATION** (A/N-100, Required)

---
**Then** I will be able to:
- Cancel
- Save 
- Edit

**and** upon saving the debt will be itemized as a "SD10" and accessible in the Loans and Debts section of the transactions table.

 QA Note
- BEGINNING BALANCE and BALANCE AT CLOSE will have the auto-calculations implemented in #1195. 
- PAYMENT AMOUNT will have the auto-calculations implemented in #1212. 

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1ykulNJdRI6J_PwVWk80QzBaopHZKVaEkgEjDo7RHeKQ/edit#gid=1956508297) **Please note this is a consolidated specification.**   

 Wireframe
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGxyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3731b3cf6ad48cd655b2502674976721819b30a1/1093%20-%20Allow%20user%20to%20enter%20Debt%20Owed%20by%20Committee.png)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Please review

@mary-tcg finished these on Friday and I forgot to review them

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg only change needed is Payment Amount should be set to $0 and read-only (this is a new requirement recently clarified). Thank you!

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Updated

**Comment by mjtravers** [comment]
Passes CR. Ready for QA pending the decision about the table sorting for Loans & Debts not working.

**Comment by mjtravers** [comment]
On hold until we learn if memo code is part of the Schedule D spec

**Comment by mary-tcg** [comment]
Updated wire to reflect new requirement clarification removing memo item and memo text from this transaction.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA review verified when adding a "Debt Owed By Committee" transactions page is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1Z5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7ca0d650486532ec7a2ce2a75239c49b6efb8d01/image.png)

Verified Contact Type is defaulted to Organization.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1p5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--db02b84bcfd26b450089e91e6fe9b7b926bd893c/image.png)

Verified "INCURRED AMOUNT" is a required field.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3R5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--56e356c741f127bbfd1b226eb8d42d24fa5a7c92/image.png)

Verified "PURPOSE OF DEBT OR OBLIGATION (REQUIRED) displays as required field if information not entered.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3h5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--304a80c3ea32374c1ce893ad952162faba364c01/image.png)

Verified "Debit Owed By Committee" is saved and displayed under Loans and Debts in the transactions table.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEp5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d29559e2bd59d618c5f3962b50e2a27a7335496d/image.png)

QA Review Completed. Moved to Stage Ready.
