### ISSUE TITLE
Update end-to-end tests to incorporate UI changes from sprint-25

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1098]
The workflow for the transaction entry screens has changed, mainly in the buttons. The end-to-end tests need to be updated to reflect these changes.

**DEV Notes**
Let's see if we can incorporate a tier 3 transaction in a test

**QA Notes**
Verification through a screenshot of the test output to screen
### QA Notes ### 
 **DEV Notes**
Let's see if we can incorporate a tier 3 transaction in a test

**QA Notes**
Verification through a screenshot of the test output to screen
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by dheitzer** [comment]
![image.png](https://images.zenhubusercontent.com/6298ce840c1c301e7c4a4151/2401ad1f-fee9-4863-a817-b3046ec23ffd)

![image.png](https://images.zenhubusercontent.com/6298ce840c1c301e7c4a4151/0f74d3c8-1903-43f5-a9e6-4291699fd63c)

![image.png](https://images.zenhubusercontent.com/6298ce840c1c301e7c4a4151/acb34405-7df7-4664-a8b5-2318aa402ab5)


My browser eventually gets a Chrome SIGTRAP error trying to run all transaction e2e tests together, however splitting them into 3 groups helps them finish (this seems to be a local browser issue).

**Comment by dheitzer** [comment]
Also note that Lighthouse had to be disabled since it is flagging a few accessibility concerns.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review completed as visual inspection to date on e2e testing. Reports will be future inspection with DEV.

QA Review Completed. Moved to Stage Ready.
