### ISSUE TITLE
Complete first run of CI Pipeline

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#11]
**Task:** First run of CI; Basic Circle CI pipeline connected to GitHub

**Sub-Tasks:**

1. Generate Python lint report in Circle CI
2. Generate Typescript link report in Circle CI
3. Run Python unit tests in Circle CI
4. Standup Postgres database in Circle CI
5. Connect CI database instance to Django API code

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by alexander-lin** [comment]
Pull request was in TCG repo for code review. Matt and Al to coordinate on review results.

**Comment by alexander-lin** [comment]
Notes: 1) Linters currently fail because of number of errors. 2) Python unit tests are failing because of lack of sample data in Circle CI pipeline.

**Comment by alexander-lin** [comment]
Once approved by Matt, Al will move this to FEC and put in a formal pull request there.

**Comment by alexander-lin** [comment]
Review plan: 1) Show Linting results in Circle CI, 2) For python, show the database connection passes (i.e. but unit tests fail because of lack of database)

**Comment by AureliaKhorsand** [comment]
@WiseQA did this get moved by accidents to the Epics pipeline? Or should this remain in Done or go back to QA review?

**Comment by WiseQA** [comment]
What are you referencing ?  A ticket ?   If so what ticket number ?  If
it's ticket 27 moved to done - see comments

**Comment by WiseQA** [comment]
Sorry just saw ticket #11 - this was suppose to get moved to done I thought
by discussion in our standup if I understood Matt correctly.
