### ISSUE TITLE
Allow user to save or save and add Contacts or cancel without saving

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#110]
Business Reason

As a Committee Administrator, I will be able to save new contacts so that I can keep my contact list up-to-date.

Acceptance Criteria

***If*** I am a Committee Administrator

  ***When*** I have created a new contact with all required fields

  ***Then*** I will be able to:

1\. save a new contact and return to the contact list ***or***,

  2\. save and add more contacts (which opens a new add contact page)***or***,

***And*** regardless if I have all required fields or not, I will be able to:

  1\. cancel without saving.

Dev Tasks:

  1\. refactor old code

  2\. unit tests

  3\. documentation

  4\. logging in the back-end

  5\. accessible in the UI

Testing:

  (Shelly will update) - Test Case / Test Script attached to show test status of ticket.

  Only test the button and make sure the actions noted in the CTA work.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1301](https://fecgov.atlassian.net/browse/FECFILE-1301)

**Comment by AureliaKhorsand** [comment]
![a1f4695a-47ce-4177-9d67-cef5b05abac5.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/c8540a0a-e84b-44b4-a615-a0d51f84ee9f)

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/16/22**: Holding off on pointing until later in Sprint 4 to determine how many endpoint models we will have for contact types, and if this ticket should or should not be split.

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/23/22:** Within the task to "refactor old code", this assumes that dev team will ensure the contacts are visible in the contact list screen (scope does not include design of the View Contacts page, which is covered in #75).

**Comment by WiseQA** [comment]
Per conversation with Matt / Mitchell current bug:
Contact Type “defaults” to Individual when Save and Add More.  Contact Type the field should default to blank.  Then select dropdown to choose which Contact Type you want to enter.

Returned to @mjtravers for bug fix.

**Comment by WiseQA** [comment]
Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/59d20642-7cf1-4c54-8ce8-55d7a0d2b512/download](https://app.zenhub.com/files/306118986/59d20642-7cf1-4c54-8ce8-55d7a0d2b512/download)

QA review completed.  Moved to Stage Ready.
