### ISSUE TITLE
Allow user to enter 24/48 Hour Report of Independent Expenditure (Form 24) 

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1102]
Business Reason 

As a Committee Administrator, I will be able to enter a ***”24/48 hour Report of Independent Expenditure"*** on Form 24 so that I can accurately report on my committee's transactions.

 Acceptance Criteria 

***Given*** I am a Committee Administrator 
 ***When*** I create a Form 24/48 Report of Independent Expenditure
 ***Then*** I will be required to enter the following information (unless otherwise noted):

*   ***REPORT TYPE***
     Dropdown options: 24,48

***And*** when I save, then I will be taken to the Manage Reports table showing this report.

 Dev Note 

*   [x] Update schema to match [Spec Updates spreadsheet tab here]( [https://docs.google.com/spreadsheets/d/1V-iOx4l6OzLrfIYRyK_iTzQz3Q1BCYj0/edit#gid=715507782](https://docs.google.com/spreadsheets/d/1V-iOx4l6OzLrfIYRyK_iTzQz3Q1BCYj0/edit#gid=715507782))

 Wireframes 

1.  Create a new report
     [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW9WQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1dfdbb7b467dd0c070fa594122154e904228e985/1102%20Create%20a%20new%20report.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW9WQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1dfdbb7b467dd0c070fa594122154e904228e985/1102%20Create%20a%20new%20report.png))

1.  Select form type
     [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc972ce05d05a2dc3b44c2e0f1a16ae018eed0ca/1102%20Create%20a%20new%20report%20-%20Select.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc972ce05d05a2dc3b44c2e0f1a16ae018eed0ca/1102%20Create%20a%20new%20report%20-%20Select.png))

1.  Form type selected
     [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTBWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2235a9618a3c94e115c6e8591bab5807a104ec63/1102%20Create%20a%20new%20report%20-%20Selected.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTBWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2235a9618a3c94e115c6e8591bab5807a104ec63/1102%20Create%20a%20new%20report%20-%20Selected.png))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
- [x] BA/Design Quality Checklist complete
- In #1499, saving the report will go to the Manage Transactions page, and the report actions will be disabled/empty until #1499.

[FECFILE-762](https://fecgov.atlassian.net/browse/FECFILE-762)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @GreggMoreland having a separate screen for the Amendment date seems odd to me - is that only going to appear on amended Form 24s? That would be out of scope for this iteration. Can we combine it with the modal that asks if it's a 24 or 48 hour report?

**Comment by Elaine-Krauss-TCG** [comment]
Form24's are able to be created and viewed in the reports table, but there's presently no indication to the user of whether or not the report type (24/48) actually saved.  I've included a screenshot below that demonstrates that the database does record the data.
<img width="728" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME9EQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9beb32446977464fedba6a2cba0ef6c2f61556e1/image.png" alt="image.png" />

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Form 24 (24/48) is selectable from the "Create a new report" list.

<img width="1316" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVdvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b873e9531a97a95d2ff80b3accbc24dac3abc30e/image.png" alt="image.png" />

Verified under "Form Type" Form 24: 24/48 HOUR NOTICE OF INDEPENDENT EXPENDITURE is selectable.

<img width="1305" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXFvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0553549718b0b4ff4360e2608d02e09e49484c7e/image.png" alt="image.png" />

Selected "Report Type" 24 hour button.   Verified Form 24 page is displayed.

<img width="1414" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek9vQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4eb2b6d54e70586d74a04e8ea41ff794651dd30d/image.png" alt="image.png" />

<img width="1369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejZvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebd43100ff2e096be50bf2a231f39e9a5efea984/image.png" alt="image.png" />

Verified Form 24 is saved in the "Manage reports" table.

<img width="1288" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeitvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e0c70e1613f444d79951d9d36a9289303038d69/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
