### ISSUE TITLE
Allow user to create and edit a Form 99

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1103]
Business Reason

As a Committee Administrator, I will be able to create a Form 99 on my committee account so that I can submit Miscellaneous Text to FEC as needed.

Acceptance Criteria

***Given*** the user is on the Reports page

  ***When*** I go to create a new report and create a Form 99

  ***then*** I will be required to enter the following information (unless otherwise noted):

*   ***COMMITTEE NAME*** (Required, System populated)

1.  Address

       #

*   ***STREET ADDRESS*** (Required, System populated)
*   ***APARTMENT, SUITE, ETC.*** (Optional, System populated)
*   ***CITY*** (Required, System populated)
*   ***STATE/PROVINCE*** (Required, System populated)
*   ***ZIP/POSTAL CODE*** (Required, System populated)

1.  Text Information

       #

*   ***TEXT CODE*** (Optional) 
      *   "Disavowal Response" (maps to 'MSI' on backend)
    *   "Filing Frequency Change Notice" (maps to 'MSM' on backend)
    *   "Miscellaneous Report to the FEC" (maps to 'MST' on backend)
*   ***TEXT MESSAGE*** (Required, A/N - 20,000) 
      *   ***NOTE: in addition to ASCII 32 – 126, this field will also accept line feed and carriage return***

—

  ***Then*** I will be able to:

*   Cancel
*   Save
*   Edit

***And*** when I save, then I will be taken to the Manage Report table

Dev Note

New form should be created in a new reports/f99 directory and leverage the existing shared/components/inputs components and also include the ngrx store of activeReport store variable.

The layout/sidebar/menu-report will need to be refactored into 2 sidebars, one for f3x and one for f99., and also update manage of sidebarState values in the ngrx store. The current menu-report can be the one for f3x. Let's put them in layout/sidebar/menus/f3x and layout/sidebar/menus/f99

*   [x] Update schema to match [Spec Updates spreadsheet tab here]( [https://docs.google.com/spreadsheets/d/1O2HKF5ND3YV0TYq87G0g4hKeX-VogoFXLLjORYElyQ4/edit#gid=1789273618](https://docs.google.com/spreadsheets/d/1O2HKF5ND3YV0TYq87G0g4hKeX-VogoFXLLjORYElyQ4/edit#gid=1789273618))
*   [x] Save resolves on the Manage reports page
*   [ ] Save and continue resolves on the Print preview page

Wireframes

1.  Creating Form 99
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFVhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d57bff044bdf5e9a201f76cd7555939a076bd494/1400%20-%20Form%2099%20-%20Creation.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFVhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d57bff044bdf5e9a201f76cd7555939a076bd494/1400%20-%20Form%2099%20-%20Creation.png))

1.  Text information dropdown
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGNhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65b2df78cc5252f2599fc64b85a68958c470a7d5/1400%20-%20Form%2099%20-%20Creation%20w%20dropdown.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGNhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65b2df78cc5252f2599fc64b85a68958c470a7d5/1400%20-%20Form%2099%20-%20Creation%20w%20dropdown.png))

1.  Editing Form 99
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUFTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64ab370c799c61e8fecd4a18b456dd0f37b84c07/1400%20-%20Form%2099.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUFTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64ab370c799c61e8fecd4a18b456dd0f37b84c07/1400%20-%20Form%2099.png))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
- [x] BA/Design Quality Checklist complete
- NOTE: The Form 99 "TEXT MESSAGE" field will accept ASCII 32 – 126 AND line breaks and carriage fields. This is the first (and so far only) time we accept line breaks and carriage returns in a text field in the app.
QA notes for testing (Wise)
- [x] Save resolves on the Manage reports page
- [x] Save and continue **(deactivated)** resolves on the Print preview page~~ (to be implemented in a future ticket) - Note removed Save and continue from options above.   
- [x] There is no Cancel button - test **Back** button

[FECFILE-761](https://fecgov.atlassian.net/browse/FECFILE-761)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
please review

I updated the dev notes:
- Save resolves on the Manage reports page
- Save and continue resolves on the Print preview page

**Comment by MitchellTCG** [comment]
I have a message for Ken to find any extra ASCII characters for the validator.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @Elaine-Krauss-TCG @WiseQA we received confirmation from Mahi/Ken that the TEXT MESSAGE field can also accept line feeds and carriage returns. ACs updated and a QA note added, let me know if you have questions.

**Comment by toddlees** [comment]
@GreggMoreland @Elaine-Krauss-TCG  I notice that the way the spreadsheet is written has the f99 text as a column, with a column seq.
.<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1Z0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2a990c3da6eaf375b1fb32e5e3dcb274f6b7278/image.png" alt="image.png" />

The text is separate from the f99 row in the .fec, so it doesn't have a column or a column sequence

**Comment by GreggMoreland** [comment]
@toddlees In the vendor file, it actually was listed with the 16 originally, but I've removed it now

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
Adding more than 20,000 characters in the TEXT MESSAGE field triggers the error message below the input box:
<img width="881" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEo1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--554957630284b408947b1d0cd9456355e58eb370/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
QA verified Form 99 form is selectable from the "Create a new Report" dropdown.

<img width="575" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlI5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0c69ca8b2fa4261faeb1bf0d202f6af261b5c63/image.png" alt="image.png" />

Verified following fields are system generated from Committee Name and Committee ID.

<img width="882" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmg5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f669e06c906b8de86dc7c3b4f780bd80c7a861a/image.png" alt="image.png" />

Verified TEXT CODE (OPTIONAL) dropdown contains contains the following selections:

<img width="454" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnA5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79de82da18fd09c8fb5dad246c62d4e43c0482c0/image.png" alt="image.png" />

Verified TEXT MESSAGE field is required field.  Verified line feed and hard return within text message.

<img width="817" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2g5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7af8b51afa2a5d51163aa3a6f4bb10ccb6c84317/image.png" alt="image.png" />

Verified with DEV 20,000 characters in the TEXT MESSAGE field triggers the error message (see above comment)

Verified Form 99 "Back" button and "Save" button are functional.   (Note:  "Save and continue" button is disabled for this ticket and nontestable)

<img width="794" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3Q5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2aedef777e3a716c513d90cf953873143c7a3c3a/image.png" alt="image.png" />

Verified Form 99 saved in the "Manage reports" table.   Verified "Form type" within the "Manage reports" table forms are sortable.

<img width="858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEI5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d0bbb3cf81fbc1a8cceba6a985c5813eee1a377/image.png" alt="image.png" />

QA Review Completed.  Moved to Stage Ready.
