### ISSUE TITLE
UI: Change disabled input text box component to READ-ONLY input box

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1105]
User story: As the FEC UX lead, I would like the disabled input text box to match the FEC Style and the wireframes

**Task 1:** Globally **_Update p-input text_**

*   [ ] Change “Color” from #5B616B to #212121

**Task 2:** On the “Account information” page **_Update p-disabled_**

*   [ ] Remove “Opacity: .65”

**Task 3:** Update text of radio buttons for selecting the type of report so that there is more contrast between the black for an enable radio button vs the gray of a disabled radio button.

### Design ###
Wireframe:

h3. Task 1 Current State

!Screenshot 2024-08-14 at 11.08.56 AM.png|width=2375,height=1866,alt="Screenshot 2024-08-14 at 11.08.56 AM.png"!

h3. Task 1 Ideal State

!Screenshot 2024-08-14 at 11.09.15 AM.png|width=2375,height=1866,alt="Screenshot 2024-08-14 at 11.09.15 AM.png"!

h3. Task 2 Current State

!Screenshot 2024-08-14 at 10.49.58 AM.png|width=2076,height=1788,alt="Screenshot 2024-08-14 at 10.49.58 AM.png"!

h3. Task 2 Ideal State

!Screenshot 2024-08-14 at 10.49.45 AM.png|width=2076,height=1788,alt="Screenshot 2024-08-14 at 10.49.45 AM.png"!

h3. 

 See full ticket and images here: [FECFILE-759](https://fecgov.atlassian.net/browse/FECFILE-759)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Please review when you have time

**Comment by AureliaKhorsand** [comment]
@MitchellTCG dev team requests clarification on which input boxes this applies to (dropdowns, date pickers, etc)

**Comment by WiseQA** [comment]
@MitchellTCG QA also needs clarification on disabled input text box and which ones are applicable for this change. - Thanks

**Comment by MitchellTCG** [comment]
@mjtravers @toddlees @sasha-dresden 
Can we also discuss this

**Comment by MitchellTCG** [comment]
@mary-tcg Pls locate all disable textboxes
