### ISSUE TITLE
Allow user to enter international contact information (Telephone Only)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#111]
Business Reason

As a Committee Administrator, I will be able to enter international specific information in contact metadata so that I can accurately record the address of the contact if they are located outside the United States.

Acceptance Criteria

***If*** I am a Committee Administrator

  ***When*** I am creating or editing a contact of any type

  ***Then*** I will be able to enter International data in the following fields:

*   COUNTRY/REGION (dropdown, required. Should default to United States)
*   STATE/PROVINCE (A/N-2, required. Should be a dropdown, _if Country is not US, defaults to Foreign Countries (ZZ on the back end)_)
*   ZIP (A/N-9, not required only if Country is NOT United States) [validate that optional appears if state chosen]
*   TELEPHONE (Country code and then N-10, not required)

### QA Notes ###
 
- Verify Telephone field will now have a dropdown for country code that defaults to United States.  
- Verify number input portion must be a digit of length 10 per validation rules.  
- Verify contact form should validate and be able to save.
- When an existing contact is edited, the country code dropdown should automatically select the one that was saved, and the digits entered should also automatically populate in this scenario.  
- Please validate countries and numbers against this Google Sheet: https://docs.google.com/spreadsheets/d/17YmnaZgqvFOUyv4-Qknd8ikHe8o9LoDb/edit#gid=870494971.   (Spot check between 5-10 numbers)

NOTE:   QA to test Telephone Dropdown Only in this ticket.  (See below comment for additional ticket being created for other International functionality)

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1300](https://fecgov.atlassian.net/browse/FECFILE-1300)

**Comment by AureliaKhorsand** [comment]
During the 2/10/22 requirements discussion, Paul found examples of committees with foreign addresses. We determined that we should accommodate international addresses for Committee and Candidate contacts just in case.

**Comment by MitchellTCG** [comment]
Wire done but needs to be signed off by UX and Devs

**Comment by AureliaKhorsand** [comment]
@MitchellTCG can you attach the wires to this ticket? They look good. Also, can you take a look at the ACs above and double check they verify with what you mocked up? I think they do but another pair of eyes won't hurt! Thanks!

**Comment by MitchellTCG** [comment]
here are the wireframes:
![b0a79552-3732-4597-82ab-1f32f0c4b2a8.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/3d9a7482-1f43-4ef8-a7c2-4a821623a153)

![dd7535ca-eeaf-40a8-9e03-6a5db28d15fa.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/99b0e3b2-452b-4173-8988-c575cdccc46b)

https://images.zenhubusercontent.com/306118986/587277e9-b046-47cc-a9fd-7a508409e796/international_number_v1.mp4

**Comment by AureliaKhorsand** [comment]
**4/21 Refinement Meeting:** BA to update the zip code requirements for foreign countries. If the country is not the US, it is not required. There will be a validator warning if there is no zip code, but FEC will address it on their end.

**Comment by WiseQA** [comment]
@dheitzer can you please provide the list or link the list of the telephone dropdown list that contains the International numbers list used to develop this ticket.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a1be44d5-6a00-41e6-bf08-dd2d670c8ff7)

Will need this to test against.

**Comment by dheitzer** [comment]
@WiseQA There's a demo of the library here that allows you to use the dropdown with the canonical list.  Can you use this to validate ours?

https://intl-tel-input.com/

**Comment by dheitzer** [comment]
![image](https://user-images.githubusercontent.com/104843885/187294301-22fae383-41b6-4839-a463-719816658319.png)

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers asking for list for international phone numbers, like we did the Country dropdown.   See demo list @dheitzer provided above, do we use this ?   Please advise.   Also, we need the QA notes added to this ticket.

**Comment by MitchellTCG** [comment]
I am officially approving the use of intl-tel-input  over the Stackblitz on in the original mocks

**Comment by WiseQA** [comment]
QA Review - drop down does work, however by Acceptance Criteria, the following do not change when Telephone is edit.  This is suppose to work correct ?  So if I edit a contact and change phone number to non US the State/Province and Zip should change automatically ?  if so this is not working

- STATE/PROVINCE (A/N-2, required. Should be a dropdown, if Country is not US, defaults to Foreign Countries (ZZ on the back end))

- ZIP (A/N-9, not required only if Country is NOT United States) [validate that optional appears if state chosen]

@mjtravers @toddlees Returned to In-Progress for fix.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/54234988-074a-4e10-b4c9-ceccd447dbed)

**Comment by toddlees** [comment]
@WiseQA @mjtravers You're right, those Acceptance Criteria are part of the ticket.  The Country they are describing is the "Country/Region" field above "Street Address" rather than the country in the phone input.  A contact in Spain can have a USA number (like Aurelia :p).  I believe the state/province dropdown does change to Foreign Countries if you pick a country/region other than USA.  Zip should also only show a required error if it's not filled in and the country/region selected is not USA

**Comment by WiseQA** [comment]
Country region only showing the following:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/37fc8875-d771-4d98-9916-b5978e71f9b1)

Verified dropdown working as designed as a place holder of 3 countries for testing purposes.

**Comment by WiseQA** [comment]
City showing a required field for foreign country selected as Mexico is this correct ?

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8c21e2fa-b860-46f9-8e77-66c093477f14)


Verified City is a required field when selecting a foreign country.

**Comment by toddlees** [comment]
Returning to QA.  Questions answered

**Comment by MitchellTCG** [comment]
Updating this ticket to just test the new international Phone number dropdown.

I will make a new ticket to deal with updating contact address functionality.

**Comment by WiseQA** [comment]
QA Review verified the International Telephone dropdown menu displays International telephone numbers, and are selectable from dropdown.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0f84a159-67f4-4ad7-9b37-4669f4af121b)

QA Review Completed.  Moved to Stage Ready
