### ISSUE TITLE
Create Angular model for Schedule C1

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1110]
Following the same pattern as was created for the Schedule A and Schedule B, create a Schedule C1 class to manage the data for a Schedule C1 record.

DEV Tasks:

*   [x] Create a SchC1Transaction class that extends the Transaction class
*   [x] Create a ScheduleC1TransactionGroups enum containing groupings for the "Add transacation" expand/collapse page
*   [x] Create a ScheduleC1TransactionsGroupsType type
*   [x] Create a ScheduleC1TransactionTypes enum containing the transaction unique identifiers
*   [x] Create a ScheduleC1TransactionTypeLabels LabelList containing the UI title for each transaction type
*   [x] Update the ScheduleTransaction, TransactionTypes, and TransactionGroupTypes type definitions in the transactions.model.ts file

### QA Notes ###

There will be a unit test that can be reviewed verifying the correctness of the Schedule C1 model code. A screenshot can be provided.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-757](https://fecgov.atlassian.net/browse/FECFILE-757)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
Unit test results for QA: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/2994/workflows/76523d30-baf1-4b44-a13e-0642521f4339/jobs/11170

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of code passing as denoted in app.circleci per DEV.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/83a2757e-e26c-4d29-ac88-daa6d62a4983)

QA Review Completed. Moved to Stage Ready,
