### ISSUE TITLE
Create Angular model for Schedule C2

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1111]
Following the same pattern as was created for the Schedule A and Schedule B, create a Schedule C2 class to manage the data for a Schedule C2 record.

DEV Tasks:

*   [x] Create a SchC2Transaction class that extends the Transaction class
*   [x] Create a ScheduleC2TransactionGroups enum containing groupings for the "Add transacation" expand/collapse page
*   [x] Create a ScheduleC2TransactionsGroupsType type
*   [x] Create a ScheduleC2TransactionTypes enum containing the transaction unique identifiers
*   [x] Create a ScheduleC2TransactionTypeLabels LabelList containing the UI title for each transaction type
*   [x] Update the ScheduleTransaction, TransactionTypes, and TransactionGroupTypes type definitions in the transactions.model.ts file

### QA Notes ###

There will be a unit test that can be reviewed verifying the correctness of the Schedule C2 model code. A screenshot can be provided.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-756](https://fecgov.atlassian.net/browse/FECFILE-756)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
Unit test results for QA: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/2994/workflows/76523d30-baf1-4b44-a13e-0642521f4339/jobs/11170

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of code passing as denoted in app.circleci per DEV.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/92c764e2-83b9-44b0-b5da-f9b3597daa0b)

QA Review Completed. Moved to Stage Ready,
