### ISSUE TITLE
Upgrade to Angular 16 from Angular 14

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1112]
The front end is currently using Angular 14. Angular 16 was recently released so we should upgrade via recommended upgrade path.

**DEV Notes**
https://angular.io/guide/update-to-version-16

**QA Notes**
Testing will entail passing of unit and end-to-end tests.
### QA Notes ### 
 **DEV Notes**
https://angular.io/guide/update-to-version-16

**QA Notes**
Testing will entail passing of unit and end-to-end tests.
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
For QA, link to automated test output for code changes: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/3096/workflows/a4e1eaec-fa20-49bc-9888-14b7672508b7/jobs/11520

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of code passing as denoted in app.circleci per DEV.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c6451a19-7a3c-4e5c-9cad-fc52139bf362)

QA Review Completed. Moved to Stage Ready,
