### ISSUE TITLE
Allow user to enter Independent Expenditure - Void on Schedule E

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1117]
Business Reason

As a Committee Administrator, I will be able to enter a ***”Independent Expenditure - Void"*** transaction on Schedule E of a Form 3X report so that I can accurately report on my committee's transactions.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

  ***Then*** go to Add a disbursement

  ***Then*** I can enter a transaction with the type “Independent Expenditure - Void" under the "Independent Expenditures" Accordion link 

  ***Then*** I will be required to enter the following information (unless otherwise noted):

Payee 

  #

*   ***LOOKUP***

       Dropdown options: Organization, Individual

       *Note - please default to Organization.

—
_if CONTACT TYPE = Organization_

*   ***ORGANIZATION NAME*** (Required)

—
_if CONTACT TYPE = Individual_

*   ***LAST NAME*** (Required)
*   ***FIRST NAME*** (Required)
*   ***MIDDLE NAME*** (Optional)
*   ***PREFIX*** (Optional)
*   ***SUFFIX*** (Optional)

1.  Address

       #

*   ***STREET ADDRESS*** (Required)
*   ***APARTMENT, SUITE, ETC.*** (Optional)
*   ***CITY*** (Required)
*   ***STATE/PROVINCE*** (Required)
*   ***ZIP/POSTAL CODE*** (Required)

1.  Expenditure information

       #

*   ***DISSEMINATION DATE*** (At least one date is required. If one is entered, the other is optional)
*   ***DISBURSEMENT DATE*** (At least one date is required. If one is entered, the other is optional)
*   ***DISBURSEMENT DATE*** (At least one date is required. If one is entered, the other is optional) 
      *   Note: If only one date is present, that date must be within the report coverage period. If both dates are present, the Date of Disbursement must be within the report coverage period.
*   ***MEMO ITEM*** (Optional)
*   ***AMOUNT*** (Required, must be negative)
*   ***CALENDAR YEAR-TO-DATE*** (Required) 
      *   Amount Displayed will be the total of contributions that are: 
            *   For the selected ELECTION CODE/ELECTION YEAR and Candidate selected
        *   within Aggregation Group of "INDEPENDENT_EXPENDITURE"
        *   _from_ January 1 of report year _to_ the Disbursement Date* of the transaction.
        *   (***IF*** Disbursement Date is not entered, then use Dissemination Date of the transaction-

1.  Candidate information

       #

*   ***SUPPORT/OPPOSE CODE*** (Required, values Support, Oppose)

       ***And*** the user will be required to select a Candidate using the LOOKUP, and upon selection the following will be populated:

*   ***CANDIDATE ID*** (Optional)
*   ***CANDIDATE LAST NAME*** (Required)
*   ***CANDIDATE FIRST NAME*** (Required)
*   ***CANDIDATE MIDDLE NAME*** (Optional)
*   ***CANDIDATE PREFIX*** (Optional)
*   ** CANDIDATE SUFFIX** (Optional)

*   ***CANDIDATE OFFICE*** (Required)
*   ***CANDIDATE STATE*** (Required if (CANDIDATE OFFICE is 'House' or 'Senate') or If (CANDIDATE OFFICE = President and the Election Code = P-Primary))
*   ***CANDIDATE DISTRICT*** (Required if CANDIDATE OFFICE is 'House')

1.  Election information

       #

*   ***ELECTION CODE*** (Required)
*   ***ELECTION YEAR*** (Required)
*   ***ELECTION DESCRIPTION*** (Required if Election Code is Other)

1.  Additional information

       #

*   ***PURPOSE OF EXPENDITURE*** (Required)

       ***Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."***
*   ***NOTE OR MEMO TEXT*** (Optional)
*   ***CATEGORY CODE*** (Optional)

1.  Committee treasurer

       #

*   ***LAST NAME*** (Required)
*   ***FIRST NAME*** (Required)
*   ***MIDDLE NAME*** (Optional)
*   ***PREFIX*** (Optional)
*   ***SUFFIX*** (Optional)

*   ***DATE SIGNED*** (Required)

—

  ***Then*** I will be able to:

*   Cancel
*   Save
*   Edit

***And if*** the Aggregate amount is >= $200.01, 

  ***Then*** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SE.

***If*** the Aggregate amount is [x] Update schema to match [Spec Updates spreadsheet tab here]( [https://docs.google.com/spreadsheets/d/15hqrgTeto1hp7i_9-jd719kTM9UNjN6qUPq-xOlJOco/edit#gid=1786117945](https://docs.google.com/spreadsheets/d/15hqrgTeto1hp7i_9-jd719kTM9UNjN6qUPq-xOlJOco/edit#gid=1786117945)) ***This is a consolidated specification***

Wireframes

1.  IE Void Inital load with Candidate info collapsed
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTdpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b3fd7cf50477a642ffb9380b09aa4dff65b37ae5/1117%20-%20Allow%20user%20to%20enter%20Independent%20Expenditure%20-%20Void%20on%20Schedule%20E%20%E2%80%93%202.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTdpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b3fd7cf50477a642ffb9380b09aa4dff65b37ae5/1117%20-%20Allow%20user%20to%20enter%20Independent%20Expenditure%20-%20Void%20on%20Schedule%20E%20%E2%80%93%202.png))

1.  IE Void Fully expanded
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDdoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7652de74576bb9ba431a50aec1eaa772736761a5/1117%20-%20Allow%20user%20to%20enter%20Independent%20Expenditure%20-%20Void%20on%20Schedule%20E%20%E2%80%93%201.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDdoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7652de74576bb9ba431a50aec1eaa772736761a5/1117%20-%20Allow%20user%20to%20enter%20Independent%20Expenditure%20-%20Void%20on%20Schedule%20E%20%E2%80%93%201.png))

1.  Expenditure info error
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbG5oIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c4dbeb27bb6e708875dc3d309aa991682fe308ee/1082%20-%20Allow%20user%20to%20enter%20Independent%20Expenditure%20on%20Schedule%20E%20%E2%80%93%20ERROR%20%E2%80%93%201.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbG5oIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c4dbeb27bb6e708875dc3d309aa991682fe308ee/1082%20-%20Allow%20user%20to%20enter%20Independent%20Expenditure%20on%20Schedule%20E%20%E2%80%93%20ERROR%20%E2%80%93%201.png))

1.  Candidate info error
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaS9pIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ded9e78314572bb8c29d88e421499e52eeb838ef/1082%20-%20Allow%20user%20to%20enter%20Independent%20Expenditure%20on%20Schedule%20E%20%E2%80%93%20ERROR.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaS9pIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ded9e78314572bb8c29d88e421499e52eeb838ef/1082%20-%20Allow%20user%20to%20enter%20Independent%20Expenditure%20on%20Schedule%20E%20%E2%80%93%20ERROR.png))

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnoxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4d75ba6b0edc9d046f6350516cd2ecf169315bb1/Screenshot%202023-10-02%20at%208.53.15%20AM.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnoxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4d75ba6b0edc9d046f6350516cd2ecf169315bb1/Screenshot%202023-10-02%20at%208.53.15%20AM.png))

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjMxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b85b6f763cbaca3403374b91270898f1c71644ec/Screenshot%202023-10-02%20at%208.55.02%20AM.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjMxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b85b6f763cbaca3403374b91270898f1c71644ec/Screenshot%202023-10-02%20at%208.55.02%20AM.png))

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVFtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7956609d250620e59f5cc2c7d03a6cf1c9cbac27/Screenshot%202023-10-11%20at%2010.17.52%20AM.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVFtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7956609d250620e59f5cc2c7d03a6cf1c9cbac27/Screenshot%202023-10-11%20at%2010.17.52%20AM.png))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
- [x] BA/Design Quality Checklist complete
- The only difference between this and #1082 is this has 'void' in the title and the amount must be negative
- ENTITY can be Organization, Individual, or Committee, but should default to Organization.
-  **(NOTE: aggregate calculation is being done in #1386)** There are two aggregates calculated on the back end. There is the aggregate that populates "Calendar Y-T-D" on the front-end, and the ENTITY aggregate, which determines itemization. This aggregate is the total of transactions:
--- From the person (ENTITY) 
--- within Aggregation Group of "INDEPENDENT_EXPENDITURE"
--- _from_ January 1 of report year _to_ the Disbursement Date of the transaction. 
--- (**IF** Disbursement Date is not entered, then use Dissemination Date of the transaction.)

 See full ticket and images here: [FECFILE-754](https://fecgov.atlassian.net/browse/FECFILE-754)

**Comment by mary-tcg** [comment]
@AureliaKhorsand @GreggMoreland @MitchellTCG wire added

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg can we show the Candidate information collapsed in a wire, then expanded in the other with the data filled in? Also, a wire showing the validation error if the Candidate information is not entered (should look the same as #1164). 

We also need the error message similar to #294 to apply for the dates. It's odd, because if one date is present, that error applies, but if both are present, it only applies to Disbursement date.

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Wires posted and UX review complete
please note that Support and Oppose radio buttons are unselected upon initial load but a choice is required

**Comment by MitchellTCG** [comment]
Wires are updated

**Comment by mjtravers** [comment]
@WiseQA Until ticket #1386 is done, the CALENDAR YEAR-TO_DATE value will simply match the AMOUNT value.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then under "Independent Expenditures" select 'Independent Expenditure - Void" transaction page is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1luQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c699e4c022a43ee757050c1d6c8b0da4b140434d/image.png)

Verified LOOKUP is defaulted to Organization.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2duQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b62e808ab92f2d29bad6ce5fbcd7940b7f3ed38/image.png)

Verified Independent Expenditure - Void transaction page is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3duQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5577a779e1bed438463ba402caec706ec963bf2f/image.png)

Verified Amount when entered is a negative number

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzRuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b45f674dec71accdf4266cbe48f8aa1cebbda279/image.png)

Verified Amount field and Calendar Year-To-Date fields are populated with amount.   Calendar Year-To-Date is read-only field.  (Note:   Actual functionality in ticket 1386)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzBuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73efa5a35b96554bffb56122ba97a6a09c103ccd/image.png)

Verified entering Dissemination Date outside report coverage dates the "Just checking ... " popup window is displayed.  Memo Item becomes a required field.  

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ltQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b5c84752942b80df32227bb2e3d7d769d7066e1/image.png)

Verified entering Disbursement Date outside report coverage dates the "Just checking ... " popup window is displayed.  Memo Item becomes a required field.  

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3NtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a165a3531ea67bff34eff496fe480ecc56cf60e/image.png)

Verified error message displayed "At least ONE date field must be entered"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzBtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d194a4b7f94fd659eb95c102337f0c9496fe411e/image.png)

Verified Candidate information error message displayed "An answer is required"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWttQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4911e19cb14523d174f6067cdc764c55a9b1a8a/image.png)

QA review verified the transactions table to display date column as currently designed. The Disbursement Date field will be populated in the date column of the transactions table only at this point. (NOTE: Future clarification with FEC to determine if the Dissemination Date field will populate in the date field if Disbursement date is NOT filled in in the transaction)

Line number 24 has been added to the transactions table for the Independent Expenditure - Void disbursement transaction.

**Comment by WiseQA** [comment]
QA review retested transaction and verified transactions action table is being updated correctly (by current design / requirement). Line 24 verified added for Independent Expenditure - Void disbursement transaction.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1lvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29d8f8671ad1c214adeed81784912428e24fb941/image.png)

QA Review Completed.   Moved to Stage Ready.

**Comment by WiseQA** [comment]
Ticket placed on-hold as a DEFECT #1456 was found during Sprint 32 demo.   DEFECT #1456 PASSES.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEozQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf0fb8e73e27e097e7c514f51649240e53d5d394/image.png)

@MitchellTCG IE Transactions have been retested and validated as Passing for Sprint 32.  Removed on-hold and closed.
