### ISSUE TITLE
Allow user to enter Multistate Independent Expenditure on Schedule E

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1118]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Multistate Independent Expenditure"** transaction on Schedule E of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** go to Add a disbursement
**Then** I can enter a transaction with the type “Multistate Independent Expenditure" under the "Independent Expenditures" Accordion link  
**Then** I will be required to enter the following information (unless otherwise noted):

 Payee 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure information 
#
-	**DISSEMINATION DATE** (At least one date is required. If one is entered, the other is optional)
-	**DISBURSEMENT DATE** ((At least one date is required. If one is entered, the other is optional)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be negative)
-	**CALENDAR YEAR-TO-DATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- For the selected ELECTION CODE/ELECTION YEAR and Candidate selected
--- within Aggregation Group of "INDEPENDENT_EXPENDITURE"
--- _from_ January 1 of report year _to_ the Disbursement Date* of the transaction. 
--- (**IF** Disbursement Date is not entered, then use Dissemination Date of the transaction- 
.

# Candidate information 
#
-	**SUPPORT/OPPOSE CODE** (Required, values Support, Oppose)
**And** the user will be required to select a Candidate using the LOOKUP, and upon selection the following will be populated:

-	**CANDIDATE ID** (Optional)
- 	**CANDIDATE  LAST NAME** (Required)
-	**CANDIDATE FIRST NAME** (Required)
-	**CANDIDATE MIDDLE NAME** (Optional)
-	**CANDIDATE PREFIX** (Optional)
-	**CANDIDATE SUFFIX** (Optional)

-	**CANDIDATE OFFICE** (Required to be President)
--Value can only be P - President
-	**CANDIDATE STATE** (Required If CANDIDATE OFFICE  = President and the Election Code = P-Primary)
-	**CANDIDATE DISTRICT** (This field is not applicable and will be grayed out)

# Election information 
#
-	**ELECTION CODE** **(Required to be PRIMARY)**
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Other)

# Additional information 
#
-	**PURPOSE OF EXPENDITURE** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Required)
--Text: "Multistate independent expenditure, publicly distributed or disseminated in the following states: XX", where XX is user entered text
-	**CATEGORY CODE** (Optional)

#  Committee treasurer 
#
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

-	**DATE SIGNED** (Required)

---
**Then** I will be able to:
- Cancel
- Save 
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SE.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 Dev Note 

- Front-end field for "treasurer" maps to "COMPLETING" name on specification spreadsheet
- - [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/15hqrgTeto1hp7i_9-jd719kTM9UNjN6qUPq-xOlJOco/edit#gid=2146252084)
- **This is the first time we have system-generated text in the Memo Text field.** It must read "Multistate independent expenditure, publicly distributed or disseminated in the following states: XX", where XX is user entered text
- [x] Beneath the label LOOKUP there will be the following text: Presidential candidates only"
- [x] the LOOKUPs will only look for presidential candidates (not House or Senate)
- [x] the Candidate Office will be read-only and say President in all places ASSOCIATED WITH THIS TICKET

 Wireframes 

# Full page at initial load
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNitNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--14c334d196ec2f99caeac2917ae6d197b8ea5b72/1118%20-%20Allow%20user%20to%20enter%20Multistate%20Independent%20Expenditure%20on%20Schedule%20E%20%E2%80%93%202.png)

# Candidate & Election Info @ initial load AND support/oppose error message when skipped
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0NNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c39cddedcfdafa8408d0724520e922ae8a53e4cb/1118%20Main.png)

# Lookup with "Presidential candidates only"
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0dNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc3bf66b92343c5b2d5575b172d7e4986630f2e2/1118%20Main%202.png)

#  Candidate Info required error
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0tNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53a983152dae5d8a25dbcb2f5239a7a0b041ac6b/1118%20Main%203.png)

# This lookup will only search for presidents 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN09NQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf82c1f3a25c31df840227d4a2dd943f217cdf4f/1118%20Main%204.png)

# Candidate office read-only 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1NNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68f1395588846a96eee08379ea0c25f488d093d9/1118%20Main%205.png)

# Add new contact modal: with "Presidential candidates only" text; lookup will only search for presidents; and Candidate office read-only
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1dNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6804179e16f1edac08571cf432f4694946e6374/1118%20Main%206.png)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 - [x] BA/Design Quality Checklist complete
- ENTITY can be Organization or Individual but should default to Organization.
- Note that this can ONLY be for Presidential Primary candidates (Candidate Office = P and Election Code = P)
- There are two aggregates calculated on the back end. There is the aggregate that populates "Calendar Y-T-D" on the front-end, and the ENTITY aggregate, which determines itemization. This aggregate is the total of transactions:
--- From the person (ENTITY) 
--- within Aggregation Group of "INDEPENDENT_EXPENDITURE"
--- _from_ January 1 of report year _to_ the Disbursement Date of the transaction. 
--- (**IF** Disbursement Date is not entered, then use Dissemination Date of the transaction.)
- **This is the first time we have system-generated text in the Memo Text field.** It must read "Multistate independent expenditure, publicly distributed or disseminated in the following states: XX", where XX is user entered text

**Comment by mary-tcg** [comment]
Wireframe posted in comments for review, is not final
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1pHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86b8a30ce66cdf5730c2f0cd93a93922d4dcd47f/1118%20-%20Allow%20user%20to%20enter%20Multistate%20Independent%20Expenditure%20on%20Schedule%20E.png)

**Comment by GreggMoreland** [comment]
@mary-tcg It looks good to me. Will there be some sort of guidance for the user to know to enter the states in the memo text?
@MitchellTCG @AureliaKhorsand

**Comment by MitchellTCG** [comment]
We can come up with language to place in a info tooltip.

**Comment by GreggMoreland** [comment]
@MitchellTCG @mary-tcg That sounds like a good solution

**Comment by MitchellTCG** [comment]
@GreggMoreland @AureliaKhorsand 
Mock posted in the top of ticket

**Comment by GreggMoreland** [comment]
@MitchellTCG Is this ready for BA Review?

**Comment by MitchellTCG** [comment]
Sorry about that. Yes it is.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then under "Independent Expenditures" select 'Multistate Independent Expenditure" transaction page is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWF1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7228506eb9a407257f5917fdec3429d23004b08/image.png)

Verified LOOKUP is defaulted to Organization.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW11QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec70562c1ab46508e5baddb996eef9078d0ffcf1/image.png)

Verified entering Disbursement Date outside report coverage dates the "Just checking ... " popup window is displayed. Memo Item becomes a required field.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzJ1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--352f228f428fd6ca4e3f1b04f917a7e6b35cad31/image.png)

Verified error message displayed "At least ONE date field must be entered"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG11QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67436e291ac5ea6aa68dfb773adb45591bd0d21d/image.png)

Verified Candidate information error message displayed "An answer is required"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODZ1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--159db9e26d27a169c6761de7138181a516abd5f0/image.png)

Verified Candidate information error displays if Candidate not filled in.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG12QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92df2d393d1a976128b8017655773333de46edb6/image.png)

Verified Candidate information LOOKUP is defaulted to Candidate and verbiage for LOOKUP  "Presidential candidates only".   Verified Election Type is defaulted to Primary (P)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0t1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05c1d1825257705eacbb62aa3f610abcdd55e09b/image.png)

Verified the LOOKUP only displays Presidential candidates

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEN2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ad05bb8af255e44bfc058c05917f52d31d7a434/image.png)

Verified NOTE OR MEMO TEXT (REQUIRED) field has the verbiage Multistate independent expenditure, publicly distributed or disseminated in the following states: "  and the error "This is a required field" is displayed upon saving.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGF2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1530c684209ff4b372358932125853ef73419a12/image.png)

Verified Multistate Independent Expenditure transaction is displayed in the Transactions table under Disbursements.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWV2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f426c5d50443f5dbcaec50c360407b4feda42656/image.png)

**Comment by WiseQA** [comment]
QA review found one hotfix during testing.   When selecting "Add a disbursement" then under "Independent Expenditures" select 'Multistate Independent Expenditure" the transaction page is displayed.   The LOOKUP should be Organization and /or Individual.    

Remove **"Presidential candidate only"** verbiage under LOOKUP

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekN2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b3d81ef4cda350268ba7d0140746a923aec725f/image.png)

@MitchellTCG @mjtravers making hotfix

**Comment by mjtravers** [comment]
An additional flag was put in the code so that the "Presidential candidates only" label only shows up where it should in the Candidate lookup in the lower part of the form. Patch pushed to DEV and STAGE and ready for QA.

**Comment by WiseQA** [comment]
QA review verified hotfix was implemented.  

Retested when selecting "Add a disbursement" then under "Independent Expenditures" select 'Multistate Independent Expenditure" the transaction page is displayed. The LOOKUP should be Organization and /or Individual.

Verified "Presidential candidate only" verbiage under LOOKUP was removed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFd3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60644eaf4905057e1411138433cf0f3c39b43320/image.png)

QA Review Completed.   Moved to Stage Ready.
