### ISSUE TITLE
Memo Item Checkbox the verbiage (Optional) is missing if date range is within the report period for Schedule A transactions

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1119]
During testing the Memo Item Checkbox verbiage ***(Optional)*** is missing when entering a Receipt (Schedule A) transaction form with a date range within the report period. (tested on both STAGE and DEV environments). Found in Sprint 25.

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/70c3e9f1-a806-48bc-b7d4-7f3143b614a5](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/70c3e9f1-a806-48bc-b7d4-7f3143b614a5))

Schedule A - That are optional upon initial load

*   [x] Individual Receipt
*   [x] Tribal Receipt
*   [ ] Partnership Receipt
*   [ ] In-Kind Receipt
*   [ ] Returned/Bounced Receipt
*   [ ] Earmark Receipt
*   [ ] Unregistered Receipt from Person
*   [ ] Unregistered Receipt from Person - Returned/Bounced Receipt
*   [x] Party Receipt
*   [x] Party In-Kind Receipt
*   [ ] Returned/Bounced Receipt
*   [ ] PAC Receipt
*   [ ] In-Kind Receipt
*   [ ] Earmark Receipt
*   [ ] PAC Returned/Bounced Receipt
*   [x] Transfer
*   [x] Joint Fundraising Transfer
*   [ ] In-Kind Transfer
*   [ ] In-Kind Transfer - Federal Election Activity
*   [ ] Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account
*   [ ] Joint Fundraising Transfer - National Party Pres. Nominating Convention Account
*   [ ] Joint Fundraising Transfer - National Party Headquarters Buildings Account
*   [x] Refund of Contribution to Federal Candidate
*   [x] Refund of Contribution to Other Political Committee
*   [ ] Refund of Contribution to Unregistered Committee
*   [x] Offset to Operating Expenditures
*   [x] Other Receipts
*   [ ] Individual Receipt - Non-contribution Account
*   [ ] Other Committee Receipt - Non-contribution Account
*   [ ] Business/Labor Organization Receipt - Non-contribution Account
*   [ ] Individual Recount Receipt
*   [ ] Party Recount Receipt
*   [ ] PAC Recount Receipt
*   [ ] Tribal Recount Receipt
*   [ ] Partnership Recount Account Receipt
*   [ ] Individual National Party Recount/Legal Proceedings Account
*   [ ] Party National Party Recount/Legal Proceedings Account
*   [ ] PAC National Party Recount/Legal Proceedings Account
*   [ ] Tribal National Party Recount/Legal Proceedings Account
*   [ ] Partnership National Party Recount/Legal Proceedings Account
*   [ ] Individual National Party Headquarters Buildings Account
*   [ ] Party National Party Headquarters Buildings Account
*   [ ] Partnership National Party Headquarters Buildings Account
*   [ ] Partnership National Party Pres. Nominating Convention Account
*   [ ] PAC National Party Headquarters Buildings Account
*   [ ] Tribal National Party Headquarters Buildings Account
*   [ ] Partnership National Party Headquarters Buildings Account
*   [ ] Individual National Party Pres. Nominating Convention Account
*   [ ] Party National Party Pres. Nominating Convention Account
*   [ ] PAC National Party Pres. Nominating Convention Account
*   [ ] Earmark Receipt for National Party Recount/Legal Proceedings Account
*   [ ] Earmark Receipt for National Party Pres. Nominating Convention Account
*   [ ] Earmark Receipt for National Party Headquarters Buildings Account
*   [ ] Loan Received from Individual (Receipt that is created from Schedule C Loan Received from Individual)

Dev Note

Per @MitchellTCG testing on the Schedule B transactions to be completed prior to QA review. Per discussion ticket pointed as 5.

Because this will impact all transactions, we can get rid of the dynamic label put in place to make some of them have "(Optional)"

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-752](https://fecgov.atlassian.net/browse/FECFILE-752)

**Comment by GreggMoreland** [comment]
@MitchellTCG Nothing was removed from the list, but items were added to Schedule A (Receipt from Loan Received from Individual) and all the In-kind Out transactions on Schedule B.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Memo Item Checkbox verbiage (Optional) is displayed when creating / entering a Receipt (Schedule A).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cf361d61-7a12-4b0f-9f79-22904ef91479)

QA tested 2 transactions from each accordion dropdown list as denoted in list above.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/de3ad286-eeb8-4f63-9da1-3107bb275e47)

QA Review Completed. Moved to Stage Ready.
