### ISSUE TITLE
7 - Allow user to provide new C1 - Loan Agreement for existing Schedule C Loan

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1122]
Business Reason

As a user, I will be able to initiate an updated Loan Agreement on a "Loan Received from Bank" so that I can report any required changes to FEC.

Acceptance Criteria

***Given***a Loan Received from Bank that has been _pulled forward_ onto a Form 3X report 

  ***When*** I select the action kebab menu, I will see the option "New loan agreement"

  ***And when*** I select the ***New loan agreement*** Action Item 

  ***Then*** I will be required to enter the following information, unless otherwise indicated:

Lender 

  #

*   ***LOOKUP***

       -Organization only
*   ***ORGANIZATION NAME*** (Required)

1.  Address

       #

*   ***STREET ADDRESS*** (Required)
*   ***APARTMENT, SUITE, ETC.*** (Optional)
*   ***CITY*** (Required)
*   ***STATE/PROVINCE*** (Required)
*   ***ZIP/POSTAL CODE*** (Required)

1.  Loan Information

       #

*   ***ORIGINAL AMOUNT*** (Required)
*   ***DATE INCURRED*** (Required)
*   ***DUE DATE*** (Required, either specific date or user defined text A/N-15)
*   ***INTEREST RATE %*** (Required, either specific percentage or user defined text A/N-15)

*   ***LOAN RESTRUCTURED*** (YN Checkbox, Required)
*   ***DATE OF ORIGINAL LOAN*** (Required if Loan Restructured = Y)
*   ***CREDIT AMOUNT THIS DRAW*** (AMT-12, Optional)
*   ***TOTAL BALANCE*** (Required if CREDIT AMOUNT THIS DRAW is populated)
*   ***OTHERS LIABLE*** (YN Checkbox, Required)

1.  Collateral

       #

*   ***COLLATERAL*** (YN Checkbox, Required)
*   ***COLLATERAL DESCRIPTION*** (A/N-100, Required if COLLATERAL = Y)
*   ***COLLATERAL AMOUNT*** (AMT-12, Required if COLLATERAL = Y)
*   ***PERFECTED INTEREST*** (YN Checkbox, Required)

1.  Future Income

       #

*   ***FUTURE INCOME*** (YN Checkbox, Required)
*   ***DESCRIPTION*** (A/N-100, required if FUTURE INCOME =Y )
*   ***ESTIMATED VALUE*** (AMT-12, required if FUTURE INCOME =Y )
*   ***DEPOSITORY ACCOUNT ESTABLISHED*** (Date, required if FUTURE INCOME =Y)
*   ***LOCATION OF ACCOUNT*** (Org only, NEEDS LOOKUP, required if FUTURE INCOME =Y)
*   ***STREET 1*** (required if FUTURE INCOME =Y)
*   ***STREET 2*** (optional if FUTURE INCOME =Y)
*   ***CITY*** (required if FUTURE INCOME =Y)
*   ***STATE*** (required if FUTURE INCOME =Y)
*   ***ZIP*** (required if FUTURE INCOME =Y)

1.  Basis of Loan

       #

*   ***DESCRIPTION*** (A/N-100, Optional)

1.  Committee Treasurer

       #

*   ***LAST NAME*** (Required)
*   ***FIRST NAME*** (Required)
*   ***MIDDLE NAME*** (Optional)
*   ***PREFIX*** (Optional)
*   ***SUFFIX*** (Optional)

*   ***DATE SIGNED*** (Required)

1.  Authorized Representative

       #

*   ***LAST NAME*** (Required)
*   ***FIRST NAME*** (Required)
*   ***MIDDLE NAME*** (Optional)
*   ***PREFIX*** (Optional)
*   ***SUFFIX*** (Optional)

*   ***DATE SIGNED*** (Required)

—

  ***Then*** I will be able to:

*   Cancel
*   Save
*   Edit

***And*** upon saving, the Loan Agreement will be saved with Form Type SC1/10,

  ***And*** I will no longer see "New loan agreement" as an action in the transaction action kebab menu, and I will see "Review loan agreement" instead (see use cases below), which upon selecting will allow me to review and edit the new loan agreement I just made.

Wireframes

1.  Use Case 1

*   User creates a ***Loan Received from Bank*** in a report (Ex. M3).
*   After creating the loan, loan agreement, Schedule A transaction and (if necessary) adding guarantors; the user returns to the ***Transactions in this report*** page.
*   When the user clicks on the action kebab for the recently created ***Loan Received from Bank*** they will see the following choices in the dropdown:
*   ***Edit***
*   ***Review loan agreement***
*   ***Make loan repayment***

1.  1.  Use Case 1 Dropdown choices
        [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmYrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--88f9098a6fa7787e34216977caa373841a585eff/1122%20-%20Loan%20repayment.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmYrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--88f9098a6fa7787e34216977caa373841a585eff/1122%20-%20Loan%20repayment.png))

1.  1.  Use Case 1 View after clicking "Review loan agreement"
        [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnorIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e6ccab3f9076d137e3f17528718f5f9c4c0c0560/Screenshot%202023-10-03%20at%203.13.33%20PM.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnorIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e6ccab3f9076d137e3f17528718f5f9c4c0c0560/Screenshot%202023-10-03%20at%203.13.33%20PM.png))

1.  Use Case 2

*   User create an M4 report causing a ***Loan Received from Bank*** to be auto-generated.
*   When the user clicks on the action kebab for the recently pulled-forward ***Loan Received from Bank*** they will see the following choices in the dropdown:
*   ***Edit***
*   ***New loan agreement***
*   ***Make loan repayment***

1.  1.  Use Case 2 Dropdown choices
        [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjMrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e136865f7af98808b495c5f9fda7447acd1ee181/1122%20-%20New%20Loan%20Agreement.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjMrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e136865f7af98808b495c5f9fda7447acd1ee181/1122%20-%20New%20Loan%20Agreement.png))

1.  Use Case 3

*   On an M4 or future report, the user creates a ***new loan agreement***.
*   After the ***new loan agreement*** is saved, the user will return to the ***Transactions in this report*** page
*   When the user clicks on the action kebab for the recently created ***NEW Loan agreement*** they will see the following choices in the dropdown:
*   ***Edit***
*   ***Review loan agreement***
*   ***Make loan repayment***

1.  1.  Use Case 3 Dropdown choices
        [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjcrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6b4c52a04ff02fc59bb2bf487b1201583e38633c/1122%20-%20Loan%20repayment.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjcrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6b4c52a04ff02fc59bb2bf487b1201583e38633c/1122%20-%20Loan%20repayment.png))

1.  1.  Use Case 3 View after clicking "Review loan agreement"
        [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1grIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--be7af58ecfd9a8e21eb8c5c805b58ad5b2994e79/Screenshot%202023-10-03%20at%203.18.32%20PM.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1grIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--be7af58ecfd9a8e21eb8c5c805b58ad5b2994e79/Screenshot%202023-10-03%20at%203.18.32%20PM.png))

### QA Notes ###
- None of the fields will be auto-populated. All fields will be blank when the 'transaction' is initially displayed.
- Also, test a new **Loan Received From Bank** transaction that is created in THIS report does **NOT** include "New loan agreement". It's only for pulled forward transactions.

### DEV Notes ###
- None of the other fields will be auto-populated. All other fields will be blank when the 'transaction' is initially displayed.

- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1H1zZmpkhUrKqe25OShtQrgbH1TrhIOSxvI1ZOM-Fw9Y/edit#gid=661269970)  
- The sub-headline 'Loan agreement' light grey should use the hex color of #AEB0B5

### Design ###
null

 See full ticket and images here: [FECFILE-749](https://fecgov.atlassian.net/browse/FECFILE-749)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
wires updated

**Comment by MitchellTCG** [comment]
@GreggMoreland 
The only new styling piece is a sub headline in lighter grey. The hex color of that grey is #AEB0B5
UX Review Complete

**Comment by GreggMoreland** [comment]
BA Review Complete

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg please update the wire to remove "Review loan agreement" option, since this is a pulled forward loan transaction.

**Comment by MitchellTCG** [comment]
Fixed wireframe

**Comment by AureliaKhorsand** [comment]
ACs have been updated to reflect the wires and use cases - added last line of ACs and altered the first few. Nothing on the form itself has changed.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the following use cases as denoted in Acceptance Criteria.

1.  Use Case 1 Dropdown choices

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzRuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5fd00148ad0277fd5b51f3f3c8bf23a317e78562/image.png)

2.  Use Case 1 View after clicking "Review loan agreement"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEluQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bfe11fa7c7302eabeca8672ee510d9148793da31/image.png)

3.  Use Case 2 Dropdown choices

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHNuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57b02561abc4096d4b1eb0d211c638688cad5bb4/image.png)

4.  Use Case 3 Dropdown choices

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWduQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--518fcb18872a979b0bddf4a0b2bd45a40c8e9609/image.png)

QA Review Completed.   Moved to Stage Ready.
