### ISSUE TITLE
UI: System to show status for Committee in site header

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1129]
Task: Include Committee status in the header

Under the Committee name and to the left of the committee type please the following:
- [x] Display a 16px diameter circle either Grey (if terminated) or Green (if active)
- [x] these are the three possible statuses
- Active
- Terminated
- Administratively Terminated
- [x] If active please display the reporting cycle to the right (Choices are: Quarterly and Monthly)
- [x] Lastly make sure this data is wired correctly to the database

# Examples 
#
![The Dashboard – 14.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/cabd2faf-58af-4ec2-bcd2-4779e8fbfe4f)

![The Dashboard – 15.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ea6f890b-8429-4865-884c-1b9dd45fd356)

![The Dashboard – 16.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d0b2ec78-2e25-490d-9347-0337445a6954)

![The Dashboard – 17.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/77af34e6-fcd2-4fb5-a4ea-ad5bc1e7c576)

![The Dashboard – 18.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8a7cf378-042e-4cba-99ce-e3c68735ccee)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@mjtravers 
Please review ACs. let me know if you need more.
I know this is already built by this ticket will track it

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified status is displayed under the committee name for the following status:  Active. 
Terminated, and  Administratively Terminated

QA Review Completed. Move to Stage Ready after Sprint 26 review 22 June 2023.
