### ISSUE TITLE
System to update form type (line number) when transaction is manually itemized/unitemized

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1133]
Business Reason

Unitemized Line 11A transactions must have Form Type of SA11AII, whereas itemized Line 11A transactions must have Form Type SA11AI.

Acceptance Criteria

***Given*** a Line 11 transaction that is _itemized_ (whether by default OR manually by the user)

  ***Then*** the Form Type will be SA11AI

  ***And*** the line number will show in the transactions table as 11(a)![](/images/icons/emoticons/information.png).

—

  ***Given*** a Line 11 transaction that is _unitemized_ (whether by default OR manually by the user)

  ***Then*** the Form Type will be SA11AII

  ***And*** the line number will show in the transactions table as 11(a)(ii).

### QA Notes ###
- Ensure that the correct line numbers show in the transactions table for the report
- Ticket to Allow user to manually itemize or unitemize a transaction was #591

Transactions included here:
- Individual Receipt
- Tribal Receipt
- Partnership Receipt
- In-Kind Receipt
- Return/Bounced Receipt
- Earmark Receipt
- Conduit Earmark
- Receipt from Unregistered Entity
- Receipt from Unregistered Entity - Return/Bounced Receipt

### DEV Notes ###
- Recommend "just-in-time" implementation
- Ticket to Allow user to manually itemize or unitemize a transaction was #591
- Ensure that the aggregates are still going to the correct place on the DSP
- Specifications have been updated to account for both options in Value references

### Design ###
null

 See full ticket and images here: [FECFILE-746](https://fecgov.atlassian.net/browse/FECFILE-746)

**Comment by AureliaKhorsand** [comment]
BA Note: Need to ask FEC if this applies to ALL Line 11 transactions.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review **"failed"** Line 11 transaction that is itemized is shown in the transactions table as 11(a)(i).  (Note this failed when the transaction is unitemized and you change it to itemized by changing the dollar amount in the transaction then save.)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4ffe1ba9-d4c3-4244-a3a9-5ca53c80085e)

QA review verified Line 11 transaction that is unitemized is shown in the transactions table as 11(a)(ii).  **(PASSED)**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ede4aa9a-c658-4c4f-87d5-2f044149cd8f)


**The dropdown button will need to be tested for both itemized and unitemized to verify this change also.**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/71e7fd85-b2f4-481b-ae06-6d0bb3132a62)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5c735b1b-19cf-45cc-9e75-02785736c458)

@MitchellTCG @toddlees @mjtravers returned to in-progress for fix.   Todd and I reviewed and this is not displaying correctly.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers @toddlees what was the fix ?   Wasn't documented in ticket ?  Patch ?   Please update
Thanks

**Comment by toddlees** [comment]
@WiseQA https://github.com/fecgov/fecfile-web-api/pull/487 was the patch to fix the issue when an unitemized SA11AII was changed to itemized.  Now it gets updated to SA11AI

**Comment by WiseQA** [comment]
QA Review retested and verified fix for Line 11 transaction that is itemized is shown in the transactions table as 11(a)(i).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d32d9118-ac8e-4c07-b186-43fb0251736d)

QA Review retested and verified fix for Line 11 transaction that is unitemized is shown in the transactions table as 11(a)(ii).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f9560ab3-663f-44ba-8435-b244052eb652)

Retested and verified when choosing the "Actions" dropdown when selecting Itemized and unitemized the line item is displayed correctly in the transactions table.

Both retest issues for this ticket have been validated and passed.

QA Review Completed.   Moved to Stage Ready.
