### ISSUE TITLE
2 - Allow user to enter Loan by Committee on Schedule C

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1134]
Business Reason

As a Committee Administrator, I will be able to enter a ***”Loan By Committee”*** transaction on Schedule C of a Form 3X report so that I can accurately report on my committee's transactions.

NOTE: This transaction will also create a "Loan Made" transaction on Schedule B. This transaction optionally might also include a ‘Child’ transaction to record one or more ‘Loan Guarantor’.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

  ***Then*** Add a Loans and Debts

  ***Then*** I can enter a transaction with the type “Loan By Committee"

  ***Then*** I will be required to enter the following information (unless otherwise noted):

—

Lendee 

  #

*   ***LENDEE TYPE***

       -Committee only
*   ***COMMITTEE NAME*** (Required)
*   ***COMMITTEE ID*** (Required)

—

1.  Address

       #

*   ***STREET ADDRESS*** (Required)
*   ***APARTMENT, SUITE, ETC.*** (Optional)
*   ***CITY*** (Required)
*   ***STATE/PROVINCE*** (Required)
*   ***ZIP/POSTAL CODE*** (Required)

1.  Loan Information

       #

*   ***AMOUNT (Original)*** (AMT-12, Required)
*   ***PAYMENT TO DATE*** (AMT-12, Required) (Should be $0 and read-only)
*   ***BALANCE OUTSTANDING*** (AMT-12, Required) (Should be same as Original Amount and read-only)
*   ***MEMO ITEM*** (Optional)

1.  Terms

       #

*   ***INCURRED DATE*** (Required)
*   ***DUE DATE*** (BLANK and read-only, implementation deferred until #1156)
*   ***INTEREST RATE*** (BLANK and read-only, implementation deferred until #1156)
*   ***SECURED*** (YN Checkbox, Required)

1.  Additional information

       #

*   ***NOTE OR MEMO TEXT*** (Optional)

—

  ***Then*** I will be able to:

*   Cancel
*   Save ***(When this is Saved, a 'Loan Made' transaction is created on Schedule B - See #1051)***
*   Add C2 – Loan Guarantor (will be a dead link until implementation of #1012)

QA Note

*   LENDEE TYPE should be LENDEE LOOKUP. (Acceptance Criteria and Wireframe both incorrect). Made note in QA notes to test LENDEE LOOKUP.
*   Verbiage is incorrect under the auto populated > AUTO-POPULATED text shows "...purpose of description...". Should read "....purpose of disbursement...". Change text from description to disbursement.

Dev Note

*   [x] Update schema to match [Spec Updates spreadsheet tab here]( [https://docs.google.com/spreadsheets/d/1H1zZmpkhUrKqe25OShtQrgbH1TrhIOSxvI1ZOM-Fw9Y/edit#gid=0](https://docs.google.com/spreadsheets/d/1H1zZmpkhUrKqe25OShtQrgbH1TrhIOSxvI1ZOM-Fw9Y/edit#gid=0)) ***Please note this is a consolidated specification.***
*   [x] Disable the "Just checking ..." memo code date pop-up by adding this line to the transaction type: override doMemoCodeDateCheck = false;

Wireframe

  ![1134 - Loan by Committee - v3.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/fb0b1752-2c03-4eb2-b9fd-2a2608dd772a](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/fb0b1752-2c03-4eb2-b9fd-2a2608dd772a))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-745](https://fecgov.atlassian.net/browse/FECFILE-745)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG wire approved.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Updated

**Comment by AureliaKhorsand** [comment]
@MitchellTCG wire approved

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
Per @MitchellTCG LENDEE TYPE should be LENDEE LOOKUP.  (Acceptance Criteria and Wireframe both incorrect).  Made note in QA notes to test LENDEE LOOKUP.

QA review verified Lendee > LENDEE LOOKUP

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6698dfe0-d423-4ef5-8a2d-fe10002d2986)

**Comment by WiseQA** [comment]
Per @MitchellTCG the verbiage is incorrect under the auto populated > AUTO-POPULATED text shows "...purpose of description...".   Should read "....purpose of disbursement...".    Change text from description to disbursement.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c63e7010-7ad5-4502-9a1d-ff411e7a5dd9)

QA note added to acceptance criteria.

@mjtravers changed needs to be made to DEV.

**Comment by mjtravers** [comment]
The text has been updated from "description" to "disbursement". Will deploy to DEV and then make the release branch for STAGE.

**Comment by WiseQA** [comment]
QA review verified verbiage updated from "description" to "disbursement"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8d058815-7fef-476f-829b-f4563a4f541b)

**Comment by WiseQA** [comment]
QA review verified when selecting "Add Loans and Debts" then select "Loans" dropdown, then select Loan By Committee transaction page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/74a4f369-e76e-4ffd-9a30-72e41b223b16)

Lendee Lookup is defaulted to Committee.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d5bbd118-217d-4c58-b08f-ddb60819339d)

Verified Loan By Committee is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6dba275b-9634-4e54-8475-68303f720d26)

Verified Date Incurred error message appears showing date must fall within .....

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/10cac89a-69b6-4d24-9e39-33801eb855b3)

Verified No/Yes radio buttons selectable for Is this loan secured?

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bef2ebf8-4f7d-4b37-990e-788f5b1b28ec)

Verified "Original Amount" is a required field. "Payment to Date" is $0.00 and read-only. "Balance Outstanding" is read-only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bcfddfda-2f43-42ab-8319-ede1478b6f96)

Verified when entering dollar amount for "Original Amount" the "Balance Outstanding" field is updated with the same amount.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a4d7b0e1-30e6-4a56-b2b8-4e9c63c12532)

Verified Memo Item (Optional) with help text icon is displayed. 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ad359a1d-e669-4bdf-8b8e-10dc3b5339b5)

Verified Confirm popup is displayed with correct verbiage -  "By saving this transaction, you're also creating a new committee contact for "Loan By Committee - Second Test"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/40363a49-93cf-4e27-a263-03593886cc99)

Verified Loan By Committee is displayed under the Loans and Debts Transactions.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/977ccd9f-fbe0-4b68-aa5e-8749e7c06f2d)

QA Review Completed. Moved to Stage Ready.
