### ISSUE TITLE
Remove Election Information from Refund of Contribution to Other Political Committee on Schedule A

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1142]
Business Reason

Task: Remove Election Information from Refund of Contribution to Other Political Committee transaction.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

  ***Then*** Add a receipt 

  ***Then*** Click(open) on the "Refunds" Accordion link 

  ***Then*** I can enter a transaction with the type "Refund of Contribution to Other Political Committee"

  ***Then*** Election Information section is not displayed

*   Update schema to Remove Election Code, Election Description [(Spec updates spreadsheet here)]([https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=2083397974](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=2083397974))

### QA Notes ###
 Dev Note 

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-743](https://fecgov.atlassian.net/browse/FECFILE-743)

**Comment by dheitzer** [comment]
Per discussion with @GreggMoreland and @AureliaKhorsand this transaction is moving to Group E and Group I is going away.

**Comment by dheitzer** [comment]
Ready for code review but holding back as requested due to being sprint 28.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "Election Information" has been removed and is not displayed for Refund of Contribution to Other Political Committee transaction.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/36b8450f-8d72-4825-8f02-084af6e07f82)

QA Review Completed.   Moved to Stage Ready.
