### ISSUE TITLE
When selecting the "In-kind" out transactions from the Disbursement table the Receipt page is displayed instead of the "Auto Populated Disbursement" page

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1144]
During testing when entering any "In-kind ..." transaction the "In-kind out . . ." transaction is AUTO-POPULATED: Review disbursement information." and displayed in the transactions table.

When select the "In-kind out . . . " transaction the "In-kind .." transactions page is displayed, instead of the "Read-Only" disbursement page.

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/259f30b5-de89-4a50-b753-466c6def30a1](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/259f30b5-de89-4a50-b753-466c6def30a1))

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/56896056-6b56-4deb-820b-06ba1f0cf4db](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/56896056-6b56-4deb-820b-06ba1f0cf4db))

@MitchellTCG Per review with @mjtravers fix selecting the disbursement the disbursement page is displayed. 3 point bug fix.

Note this change will apply to the following transactions.

This will apply to existing transactions, including:

In-kind Receipt/In-kind Out

  Party In-kind Receipt/Party In-kind Out

  PAC In-kind Receipt/PAC In-kind Out

  In-kind Transfer/In-kind Transfer Out

  In-kind Transfer - Federal Election Activity/In-kind Transfer - Federal Election Activity Out

Earmark Receipt/Earmark Memo

  PAC Earmark Receipt/PAC Earmark Memo

  Earmark Receipt for National Party Recount/Legal Proceedings Account (Contribution)/Earmark Memo

  Earmark Receipt for National Party Pres. Nominating Convention Account (Contribution)/Earmark Memo

  Earmark Receipt for National Party Headquarters Buildings Account (Contribution)/Earmark Memo

Future transaction:

  Conduit Earmark/Conduit Earmark Out

  PAC Conduit Earmark/PAC Conduit Earmark Out

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-741](https://fecgov.atlassian.net/browse/FECFILE-741)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting the "In-kind Out" transaction from the Disbursements in the "Transactions in this report" table the "In-kind Out" disbursement page is displayed not the Receipt page.  (Tested PAC In-kind Out, Party In-kind Out, Earmark Memo).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6b0bdf6b-15bf-4069-b7a8-0b0c1de349a4)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/17c8722c-4763-4f88-ba13-251b23b3dbba)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e76ac22f-8f3b-4e3a-b8fb-f6597db4cc1c)

QA Review Completed.  Moved to Stage Ready.
