### ISSUE TITLE
Update transaction names for Partnership Memo transactions to Partnership Attribution (or variations)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1147]
Per FEC feedback, any transaction reference to any 'Partnership Memo' (tier 2 or 3) transaction should now be 'Partnership Attribution'.

Acceptance Criteria

1\. Update Transaction entry form headers

*   [x] Rename “Partnership Memo" to “Partnership Attribution”
*   [x] Rename “Partnership Individual Joint Fundraising Transfer Memo to “Partnership Attribution Joint Fundraising Transfer Memo”
*   [x] Rename “Partnership Individual Recount/Legal Proceedings Account JF Transfer Memo to “Partnership Attribution Recount/Legal Proceedings Account JF Transfer Memo”
*   [x] Rename “Partnership Individual Pres. Nominating Convention Account JF Transfer Memo to “Partnership Attribution Pres. Nominating Convention Account JF Transfer Memo”
*   [x] Rename “Partnership Individual Headquarters Buildings Account JF Transfer Memo to “Partnership Attribution Headquarters Buildings Account JF Transfer Memo”
*   [x] Rename “Partnership Recount Account Receipt Memo to “Partnership Attribution Recount Account Receipt Memo”
*   [x] Rename “Partnership National Party Recount/Legal Proceedings Account Memo to “Partnership Attribution National Party Recount/Legal Proceedings Account Memo”
*   [x] Rename “Partnership National Party Headquarters Buildings Account Memo to “Partnership Attribution National Party Headquarters Buildings Account Memo”
*   [x] Rename “Partnership National Party Pres. Nominating Convention Account Memo to “Partnership Attribution National Party Pres. Nominating Convention Account Memo”

2\. Update dropdown names (using the above renamed values) in 'Save & Add Memo' for all Partnership Individual (tier 3) transactions. Rename “Partnership Individual” to “Partnership Attribution” on the dropdown for these transactions:

*   [x] Partnership Receipt
*   [x] Partnership Receipt Joint Fundraising Transfer Memo
*   [x] Partnership Attribution Joint Fundraising Transfer Memo
*   [x] Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo
*   [x] Partnership Attribution Recount/Legal Proceedings Account JF Transfer Memo
*   [x] Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo
*   [x] Partnership Attribution Pres. Nominating Convention Account JF Transfer Memo
*   [x] Partnership Receipt Headquarters Buildings Account JF Transfer Memo
*   [x] Partnership Attribution Headquarters Buildings Account JF Transfer Memo
*   [x] Partnership Recount Account Receipt
*   [x] Partnership National Party Recount/Legal Proceedings Account
*   [x] Partnership National Party Headquarters Buildings Account
*   [x] Partnership National Party Pres. Nominating Convention Account

### QA Notes ###
(Note: Information on transaction relationships available on the master sheet [here](https://docs.google.com/spreadsheets/d/1gdcvYQBFMeCGt-1NfVuaSTsB0sB-dl2N/edit#gid=1395788914). In the future, this will be where you should go for transaction lists since it is the source-of-truth.)

For testing, the tier 1, tier 2, (and if needed) tier 3 transactions in each sequence:
- [x] Partnership Receipt --> Partnership Attribution
- [x] Joint Fundraising Transfer --> Partnership Receipt Joint Fundraising Transfer Memo --> Partnership Attribution Joint Fundraising Transfer Memo
- [x] Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account --> Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo --> Partnership Attribution Recount/Legal Proceedings Account JF Transfer Memo
- [x] Joint Fundraising Transfer - National Party Pres. Nominating Convention Account --> Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo --> Partnership Attribution Pres. Nominating Convention Account JF Transfer Memo
- [x] Joint Fundraising Transfer - National Party Headquarters Buildings Account --> Partnership Receipt Headquarters Buildings Account JF Transfer Memo --> Partnership Attribution Headquarters Buildings Account JF Transfer Memo
- [x] Partnership Recount Account Receipt --> Partnership Attribution Recount Account Receipt Memo
- [x] Partnership National Party Recount/Legal Proceedings Account --> Partnership Attribution National Party Recount/Legal Proceedings Account Memo
- [x] Partnership National Party Headquarters Buildings Account --> Partnership Attribution National Party Headquarters Buildings Account Memo
- [x] Partnership National Party Pres. Nominating Convention Account --> Partnership Attribution National Party Pres. Nominating Convention Account Memo

### DEV Notes ###
1. Update Transaction type identifiers
- [x] PARTNERSHIP_MEMO must change to PARTNERSHIP_ATTRIBUTION
- [x] PARTNERSHIP_INDIVIDUAL_JF_TRANSFER_MEMO must change to PARTNERSHIP_ATTRIBUTION_JF_TRANSFER_MEMO
- [x] PARTNERSHIP_INDIVIDUAL_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO must change to PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO
- [x] PARTNERSHIP_INDIVIDUAL_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO must change to PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO
- [x] PARTNERSHIP_INDIVIDUAL_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO must change to PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO
- [x] PARTNERSHIP_RECOUNT_ACCOUNT_RECEIPT_MEMO must change to PARTNERSHIP_ATTRIBUTION_RECOUNT_ACCOUNT_RECEIPT_MEMO
- [x] PARTNERSHIP_NATIONAL_PARTY_RECOUNT_ACCOUNT_MEMO must change to PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_RECOUNT_ACCOUNT_MEMO
- [x] PARTNERSHIP_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT_MEMO must change to PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT_MEMO
- [x] PARTNERSHIP_NATIONAL_PARTY_CONVENTION_ACCOUNT_MEMO must change to PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_CONVENTION_ACCOUNT_MEMO

### Design ###
null

 See full ticket and images here: [FECFILE-739](https://fecgov.atlassian.net/browse/FECFILE-739)

**Comment by AureliaKhorsand** [comment]
Removed following since there is no transaction selection for these
1. Update Accordion dropdown names
- [ ] Rename “Partnership Memo" to “Partnership Attribution”
- [ ] Rename “Partnership Individual Joint Fundraising Transfer Memo to “Partnership Attribution Joint Fundraising Transfer Memo”
- [ ] Rename “Partnership Individual Recount/Legal Proceedings Account JF Transfer Memo to “Partnership Attribution Recount/Legal Proceedings Account JF Transfer Memo”
- [ ] Rename “Partnership Individual Pres. Nominating Convention Account JF Transfer Memo to “Partnership Attribution Pres. Nominating Convention Account JF Transfer Memo”
- [ ] Rename “Partnership Individual Headquarters Buildings Account JF Transfer Memo to “Partnership Attribution Headquarters Buildings Account JF Transfer Memo”
- [ ] Rename “Partnership Recount Account Receipt Memo to “Partnership Attribution Recount Account Receipt Memo”
- [ ] Rename “Partnership National Party Recount/Legal Proceedings Account Memo to “Partnership Attribution National Party Recount/Legal Proceedings Account Memo”
- [ ] Rename “Partnership National Party Headquarters Buildings Account Memo to “Partnership Attribution National Party Headquarters Buildings Account Memo”
- [ ] Rename “Partnership National Party Pres. Nominating Convention Account Memo to “Partnership Attribution National Party Pres. Nominating Convention Account Memo”

**Comment by GreggMoreland** [comment]
@WiseQA I added to QA notes the path for testing each one, listing Tier 1, Tier 2, and if needed, Tier 3. Let me know if I missed anything or if you'd like to see it displayed any differently.

**Comment by WiseQA** [comment]
@GreggMoreland perfect - as we get into testing when ticket comes down pipeline will let you know if any further information needed.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "Partnership Memo" transactions have been renamed to "Partnership Attribution" per list in QA notes.   Below are screenshots for a couple of transactions name changed.

Partnership Receipt --> Partnership Attribution  (PASSED)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c1117bda-7c44-4d71-bf8e-ec4c12fea1be)

Partnership Recount Account Receipt --> Partnership Attribution Recount Account Receipt Memo  (PASSED)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5cd6bc94-d70e-4a98-a850-0f9513e401a0)

**The following transactions during testing failed the naming change.   Under Transfers accordion the following need naming changed:**

Joint Fundraising Transfer --> Partnership Receipt Joint Fundraising Transfer Memo --> Partnership Attribution Joint Fundraising Transfer Memo  (FAILED)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3d164b65-cc9e-444d-92cf-0f5af7dc5b5d)

Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account --> Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo --> Partnership Attribution Recount/Legal Proceedings Account JF Transfer Memo (FAILED)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dcc3820c-8b55-4472-a50e-1e24d6c884b0)

Joint Fundraising Transfer - National Party Pres. Nominating Convention Account --> Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo --> Partnership Attribution Pres. Nominating Convention Account JF Transfer Memo (FAILED)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/56566f6e-81c6-4712-9712-aecee8decf80)

Joint Fundraising Transfer - National Party Headquarters Buildings Account --> Partnership Receipt Headquarters Buildings Account JF Transfer Memo --> Partnership Attribution Headquarters Buildings Account JF Transfer Memo (FAILED)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3f137403-39ff-439d-a91a-10575a540863)

Below following list QA review verified.   The unchecked boxes are names needing changed as denoted above with screenshots.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/384dc455-c092-409f-993f-9065a935c7b0)

@MitchellTCG @mjtravers returning to in-progress for naming fix.

**Comment by Elaine-Krauss-TCG** [comment]
Joint Fundraising Transfer --> Partnership Receipt Joint Fundraising Transfer Memo --> Partnership Attribution Joint Fundraising Transfer Memo is working as intended.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/e722f5bc-0f71-46e6-b9ab-0b8a8d5c834c)

I believe the raised concern comes from them not having the full transaction type identifiers listed in the Save & Add a Memo dropdown.  This is intended, and none of the four other potential children have "Joint Fundraising Transfer Memo" in their names.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/883677d5-c119-4d9f-97f0-b8984d8bd92d)

There was a problem in the Save & Add a Memo dropdown for the Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo: The shortname for one of the child transactions had not been updated from "Partnership Individual" to "Partnership Attribution."  This has been corrected.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/50cc058c-ff87-4ff0-960b-5a77348ee3b0)

The same issue was also identified and corrected in the Save & Add a Memo dropdown for the Partnership Receipt National Party Pres. Nominating Convention Account transaction as well, but not for Partnership Receipt National Party Headquarters Buildings Account...

**Comment by mjtravers** [comment]
"Partinership Individual" changed to "Partnership Attribution". Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review retested and verified "Partnership Individual" changed to "Partnership Attribution". 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ee791db4-ca59-4be6-a431-a4966dbba9a6)

Retested Partnership Attribution Recount/Legal Proceedings Account JF Transfer Memo displaying correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/315b8627-006e-4f6d-8c2e-63488e8ed5e6)

Retested the following transactions - all PASS

- [x] Joint Fundraising Transfer --> Partnership Receipt Joint Fundraising Transfer Memo --> Partnership Attribution Joint Fundraising Transfer Memo
- [x] Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account --> Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo --> Partnership Attribution Recount/Legal Proceedings Account JF Transfer Memo
- [x] Joint Fundraising Transfer - National Party Pres. Nominating Convention Account --> Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo --> Partnership Attribution Pres. Nominating Convention Account JF Transfer Memo
- [x] Joint Fundraising Transfer - National Party Headquarters Buildings Account --> Partnership Receipt Headquarters Buildings Account JF Transfer Memo --> Partnership Attribution Headquarters Buildings Account JF Transfer Memo

QA Review Completed.    Moved to Stage Ready.
