### ISSUE TITLE
Update system generated Purpose of Receipt and UI Information Description for Partnership Receipt transactions

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1148]
On review, FEC has requested text changes to the Purpose of Receipt information description and system generated text for Partnership - where "Partnership attributions do not require itemization" is mentioned, should be changed to "Partnership attributions do not meet itemization threshold"

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

 ***When*** I am entering or editing any of the following transactions:

*   Partnership Receipt
*   Partnership Receipt Joint Fundraising Transfer Memo (Joint Fundraising Transfer)
*   Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo (Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account)
*   Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo (Joint Fundraising Transfer - National Party Pres. Nominating Convention Account)
*   Partnership Receipt Headquarters Buildings Account JF Transfer Memo (Joint Fundraising Transfer - National Party Headquarters Buildings Account)
*   Partnership Recount Account Receipt
*   Partnership National Party Recount/Legal Proceedings Account
*   Partnership National Party Pres. Nominating Convention Account
*   Partnership National Party Headquarters Buildings Account

***Then*** Purpose of Receipt Information text will indicate:

> If a Partnership Receipt is saved without a Partnership Attribution, this will include the text "Partnership attributions do not meet itemization threshold." If a Partnership Attribution is added, this will include the text "See Partnership Attribution(s) below."

***And*** if a Partnership Attribution is not added to the Partnership Receipt, the Purpose of Receipt will include "Partnership attributions do not meet itemization threshold." in the system generated text.

### QA Notes ###
- Note that this help text will apply to ANY Partnership Receipt transaction. We are no longer having different help text for each partnership receipt transaction.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-738](https://fecgov.atlassian.net/browse/FECFILE-738)

**Comment by toddlees** [comment]
@AureliaKhorsand  @GreggMoreland  I'm seeing two distinct patterns with the information text between the memo (soon to be called attribution) transactions and the receipt transactions:

Partnership Receipt Joint Fundraising Transfer Memo
Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo
Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo
Partnership Receipt Headquarters Buildings Account JF Transfer Memo
> If transaction has no associated Partnership memos, reads "Pres. Nominating Convention Account JF Memo: XX (Partnership attributions do not require itemization)". Otherwise, reads "Pres. Nominating Convention Account JF Memo: XX (See Partnership Attribution(s) below)"

and 

Partnership Receipt
Partnership Recount Account Receipt
Partnership National Party Recount/Legal Proceedings Account
Partnership National Party Pres. Nominating Convention Account
Partnership National Party Headquarters Buildings Account
>If Partnership Receipt is saved without a Partnership Memo, this will read "Partnership attributions do not require itemization". If a Partnership Memo is added, it will read "See Partnership Attribution(s) below".

---

Propose changing reqs to something like:

**Then** Purpose of Receipt Information text for receipts (see distinction below) will indicate: 

> If Partnership Receipt is saved without a Partnership Attribution, this will read "Partnership attributions do not meet itemization threshold." If a Partnership Attribution is added, it will read "See Partnership Attribution(s) below."

**Then** Purpose of Receipt Information text for attributions (see distinction below) will indicate the following where ```JF Memo``` would read ```Pres. Nominating Convention Account JF Memo``` on a Partnership National Party Recount JF Transfer Memo and so on: 

> If transaction has no associated Partnership memos, reads "```JF Memo```: XX (Partnership attributions do not require itemization)". Otherwise, reads "```JF Memo```: XX (See Partnership Attribution(s) below)"

attribution transactions: 
Partnership Receipt Joint Fundraising Transfer Memo
Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo
Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo
Partnership Receipt Headquarters Buildings Account JF Transfer Memo

receipt transactions:
Partnership Receipt
Partnership Recount Account Receipt
Partnership National Party Recount/Legal Proceedings Account
Partnership National Party Pres. Nominating Convention Account
Partnership National Party Headquarters Buildings Account

**Comment by dheitzer** [comment]
This one is ready for CR but is SP28 so won't be moved.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the Purpose of Receipt system generated field verbiage has been updated from "Partnership attributions do not require itemization" changed to "Partnership attributions do not meet itemization threshold"  

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2f5ddc03-7cf3-4260-9341-45ccc3695f59)

The following transactions were verified (note this list came from ticket #1147 as the names have changed from the acceptance criteria above.    Below are the correct transactions tested:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/22a53ea7-5fd6-4057-9ff2-c7b1bbfdb6bd)

QA Review Completed.   Moved to Stage Ready.
