### ISSUE TITLE
System to prevent user from submitting a Form 3X report if a prior Form 3X report is open

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1154]
### Business Reason

As a Committee Administrator, I will not be able to submit a Form 3X report if a prior Form 3X report is still in "in-progress", so that I can accurately report on my committee's transactions.

### Acceptance Criteria

**Given** I am a Committee Administrator editing an open Form 3x report (with report status 'In progress')
**When** I have another Form 3X report with report status 'In progress' with an earlier timeframe
**When** I try to submit the current report
**Then** I should see an error message that prevents me from submitting this report if another one is open with report status of 'In progress'.

### QA Notes
- [ ] BA/Design Quality Checklist complete

**Comment by AureliaKhorsand** [comment]
Given the decision to allow for data to dynamically change in submitted reports (requirements session 10/19/23), this ticket is no longer needed. Closed as OBE.
