### ISSUE TITLE
Just checking... Pop Up window verbiage incorrect

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1155]
During testing when entering a Receipt or Disbursement transaction form and "Just Checking" modal is displayed, the text within the Pop Up is incorrect. (tested on both STAGE and DEV environments).

The Just checking. . . Pop Up highlighted text currently reads:

"If the data entered is correct, please check the Memo Item box to continue."

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/832fd30b-858e-4462-ada9-9a8fccc9f02c)

Change the Just checking. . . Pop Up highlighted text to read (reference wireframe in #294):

"If the data entered is correct, this transaction must be a Memo Item."

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/84600c62-0751-4c66-a0e4-afac486f0d71)

Per review with @mjtravers fix the verbiage and assign to @Elaine-Krauss-TCG .  1 point bug fix.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by toddlees** [comment]
passes CR moving to QA

**Comment by WiseQA** [comment]
QA review verified the Just checking. . . Pop Up text has been changed to read:

"If the data entered is correct, this transaction must be a Memo Item."

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c0a5beac-f3c3-4a88-99ef-cdabd7f89c7f)

QA Review Completed.  Moved to Stage Ready.
