### ISSUE TITLE
Allow user to enter Loan Due Date and Loan Interest Rate for Schedule C Loans

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1156]
Business Reason

As a user, I will be able to enter a Due Date and Interest Rate for my Schedule C Loan so that I can report my loan per FEC regulations. 

 Acceptance Criteria

**Given** one of the following transactions:
- Loan Received from Individual
- Loan Received from Bank
- Loan by Committee

**When** I am creating the transaction 
**Then** I will be able to enter the following

- Due Date
- Interest Rate

---
**When** I select 'Enter a specific date' on the Due Date dropdown
**Then** I will be able to select and enter a valid date in the Specific Date field 

---
**When** I select 'Enter a user defined value' on the Due Date dropdown
**Then** I will be able to enter a user defined text value in **Date Due** (A/N-15)

---
**When** I select 'Enter an exact percentage' on the Interest Rate dropdown
**Then** I will be able to select and enter an Exact Percentage value (xx.xxxxx format)

--
**When** I select 'Enter a user defined value' on the Interest Rate dropdown
**Then** I will be able to enter a user defined text value in **Interest Rate** (A/N-15)

 Prototype
https://images.zenhubusercontent.com/306118986/d5aa982d-0092-4fcc-be93-82c77f701440/1156___allow_user_to_enter_loan_due_date_and_loan_interest_proto.mp4

 Wireframes

# Due Date Options
![1156 - Allow user to enter Loan Due Date and Loan Interest Rate for Schedule C Loans – 01.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/b8fa3fa1-56ec-4b54-9e41-798f640e68cf)

# Specific Date
![1156 - Allow user to enter Loan Due Date and Loan Interest Rate for Schedule C Loans – 02.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/47515b5e-d042-445d-884b-8f59fd2ae76b)

# Due Date User Defined
![1156 - Allow user to enter Loan Due Date and Loan Interest Rate for Schedule C Loans – 03.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4ae9cc82-0d5f-413b-bf52-392573116e54)

# Interest Rate Options
![1156 - Allow user to enter Loan Due Date and Loan Interest Rate for Schedule C Loans – 04.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/bf7f8014-f0c9-4493-98c0-1f2c4689932d)

# Exact Percentage
![1156 - Allow user to enter Loan Due Date and Loan Interest Rate for Schedule C Loans – 05.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/fcca5614-7525-4752-87b2-fcbf38578b94)

# Interest Rate User Defined
![1156 - Allow user to enter Loan Due Date and Loan Interest Rate for Schedule C Loans – 06.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/05170ca5-ea5c-4e3f-b8e8-6fb1af37689c)

### QA Notes ### 
 - User defined values are limited to 15 characters per the specifications.
### DEV Notes ### 
 - For APR allow 5 digits after the decimal point 
- Show error messages under both
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @JonellaCulmer @mary-tcg 

Wireframe and Prototype attached approve. We can discuss tomorrow

**Comment by Elaine-Krauss-TCG** [comment]
Loan Received from Individual and Loan by Committee are both working great, but Loan Received from Bank needs more work as there are complications due to it's being a triple-transaction
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjAzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6e4c7efeaebdd7b8df8815b92130bc548f1a85fe/image.png)

**Comment by mjtravers** [comment]
When saving the transaction without selecting a DATE DUE or INTEREST RATE type, no "required field" error message is displayed below the select boxes so that I know why the form doesn't save. Also, does LOAN RECEIVED FROM BANK still need more work? It seems to be working for me. Sending back to In Progress for required field error message fix.

**Comment by Elaine-Krauss-TCG** [comment]
Required validators added to the two new inputs.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3RSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b346975a7a038a7ae35b94be08117a86a31424a0/image.png)

The LOAN RECEIVED FROM BANK issue with inheritance has been resolved.

**Comment by mjtravers** [comment]
Validators were added and ticket passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA review tested and verified the Date Incurred, Date Due and Interest Rate for the following loan transactions:  Loan Received from Individual; Loan Received from Bank; Loan by Committee.

Verified under Terms the "Date Incurred"; "Date Due" and "Interest Rate" display the associated required field message.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGhUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47887b50e1d7757b128e27b21f1ce456eac062b0/image.png)

Verified once selecting "Date Due" and "Interest Rate" the "Specific Date" and "Exact Percentage (%)" fields display the associated required field message.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU5UIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--22dee211a466fff797d781a2521d51536263f81c/image.png)

Verified when selecting Date Due field dropdown displays both "Enter a specific date" and "Enter a user defined value" is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDVUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9d28105c68dfdaf2f05e416440974869f32199af/image.png)

Verified when selecting the Interest Rate field dropdown displays both "Enter an exact percentage" and "Enter a user defined value" is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1ZUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7642970570e1cc5578bfd3c4261eb1e4670158d9/image.png)

Verified "Date Due (User Defined) and Exact Percentage (%) fields are displayed upon entering data.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazlUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b8459059ed5a2dac984eb543255e9ba1bd939892/image.png)

Verified transaction is save in the Transactions table.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWhUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9cfad5416d1c7c172aab0aa521ef8eb7e03760d6/image.png)

QA Review Completed.   Moved to Stage Ready.
