### ISSUE TITLE
6 - System to update Payment to Date and Balance Outstanding on SC loan when Loan Repayment Made or Received

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1157]
Business Reason
As a user, I should see my updated Payment to Date and Balance Outstanding on my SC Loan whenever I enter a **Loan Repayment Made** or **Loan Repayment Received** so that I can accurately report my loan to FEC.

 Acceptance Criteria

**Given** the user has a SC Loan (Loan Received from Individual or Loan Received from Bank)
**When** the user saves a "Loan Repayment Made" (Schedule B) on a Loan Received from Individual or Loan Received from Bank
**or** the user saves a "Loan Repayment Received" (Schedule A) on a Loan by Committee
**Then** the associated SC loan will reflect the updated Payment to Date and Balance Outstanding as follows:

- Amount entered in Loan Repayment Made/Loan Repayment Received will be _added_ to "Payment to Date" value
- Amount entered in Loan Repayment Made/Loan Repayment Received will be _subtracted_ from "Balance Outstanding" value

### QA Notes ### 
 - This will apply to "Loan Received from Individual", "Loan Received from Bank", and "Loan by Committee"
### DEV Notes ### 
  Wireframe
![Screenshot 2023-08-03 at 1.37.19 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d32a877d-2d6c-434c-a57c-10ec04803578)

### Design ### 
 null

**Comment by WiseQA** [comment]
@MitchellTCG you forgot one I changed it for you.   Thanks !

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Prerequisite Loan Repayment Made (Disbursement / Schedule B) transactions have been created for both Loan Received from Bank and Loan Received from Individual.

 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0pyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6a1f435919c65d24e5686931188e63992b73406a/image.png)

Entered two Loan Repayment Made (e.g., Loan Received from Bank) one for $50.00 and one for $5.00 for testing.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2xyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e60929cdd9e4084666fb6f3e671117a16a6fcd87/image.png)

Verified the "Loan  Received from Bank" transaction the "PAYMENT TO DATE" and "BALANCE OUTSTANDING" fields are populated with payment amounts and outstanding balance (accumulative)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdE5yIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f0877ac50e37fc0f1bf10e7bb83228a99e3ba700/image.png)

QA Review Completed.   Moved to Stage Ready.
