### ISSUE TITLE
Reports not loading in production environment

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#116]
**Description**
Reports aren't loading in production environment, but they are in the development environment. Console errors appear in production.

**Steps to reproduce:**

- Log in to https://fecfile-web-app-prod.app.cloud.gov/#/
- Click on a report in the left-hand menu
- Report doesn't load, shows console errors

**Screenshot**
<img width="967" alt="Screen Shot 2022-02-14 at 9 27 52 AM" src="https://user-images.githubusercontent.com/31420082/153900040-7c237946-6c36-4306-ae64-131b4e926ba4.png">

It looks like the angular build for prod in https://github.com/fecgov/fecfile-web-app/blob/6b81a90cd49439d489949b95217a291f68943757/front-end/angular.json#L36-L86 has the following extra settings, one/some of which are breaking some of the JS (TS?) functionality:
```
      "optimization": true,
      "outputHashing": "all",
      "sourceMap": false,
      "namedChunks": false,
      "aot": true,
      "extractLicenses": true,
      "vendorChunk": false,
      "buildOptimizer": true
```

Tested with https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/157/workflows/50a90755-8a75-4127-95a1-0850c708cb51/jobs/611

 Acceptance Criteria 
 

- [ ] Reports load in production environment

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
This ticket is OBE. Reports pages have been put in the backlog until they are to be worked on.
Closing ticket.
