### ISSUE TITLE
[UI] System to indicate missing required fields in "Committee/Candidate information" upon saving 

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1164]
Business Reason

As a user, I will be able to see if I have missed fields in the Committee/Candidate information section of relevant transactions so that I know what I need to add in order to save my transaction.

Acceptance Criteria

***Given*** a transaction with a "Committee/Candidate information" section,

  ***If*** the user does not enter all required fields within that section,

  ***Then*** upon saving, the system will indicate that those fields are required to save.

Wireframes

1.  Committee Autopopulated

       ![1164 - System to indicate missing required fields (first auotpop).png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d2a2fa89-1d2d-4192-a9f8-39c0bb15213f](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d2a2fa89-1d2d-4192-a9f8-39c0bb15213f))

1.  Both Required

       ![1164 - System to indicate missing required fields (both required).png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/63755034-18a8-40a3-a95b-0b4cbf92531e](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/63755034-18a8-40a3-a95b-0b4cbf92531e))

### QA Notes ###
Tickets with a "Committee/Candidate information" section:
- Refund of Contribution to Federal Candidate (Schedule A) 
- Contribution to Candidate (Schedule B)
- Void of Contribution to Candidate (Schedule B)
- In-kind Contribution to a Candidate (Schedule B)
- Conduit Earmark (Update by HMJ)
- PAC Conduit Earmark (Update by HMJ)
- Loan Agreement for Loan Received from Bank (SW) #1011

### DEV Notes ###
Can add the lookup's p-autocomplete to the form and validate on whether or not the candidate contact fields are shown or not.

### Design ###
null

 See full ticket and images here: [FECFILE-730](https://fecgov.atlassian.net/browse/FECFILE-730)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg right now there is _no_ indication these fields are required if the user tries to save. There is no in-line validation, red text, etc. (Note: This solution is separate from the holistic solution in #1165).

**Comment by MitchellTCG** [comment]
@toddlees 
Please review and add your thoughts to the dev notes, then forward to @AureliaKhorsand

**Comment by toddlees** [comment]
looks great!  notes added @AureliaKhorsand

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @toddlees do we need to include wires for if the Last Name, First name, etc is missing, or are those already implemented? Otherwise, this looks fine.

**Comment by AureliaKhorsand** [comment]
Wires approved.

**Comment by dheitzer** [comment]
need to clarify a UI update for the lookup in this ticket.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Committee/Candidate information > Candidate field is a required field upon saving transaction.  "Candidate information is required".    Tested Refund of Contribution to Federal Candidate (Schedule A)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0387b5dd-e88e-461b-87c0-eb89ba5b8428)

QA review verified Committee/Candidate information > Candidate field is a required field upon saving transaction.  "Candidate information is required".    Tested Contribution to Candidate (Schedule B)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5f83883b-d3b2-4d2f-97ce-b5c6ababc1ea)

The following will be tested and verified once #863 completed:

1.   Committee/Candidate information > Candidate field is a required field upon saving transaction.  "Candidate information is required".
2.  Committee/Candidate information > Committee field is a required field upon saving transaction.  "Committee information is required".

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4d448cf9-6717-40cf-8d83-43c1883d172f)

Ticket put on-hold until #863 completed.

**Comment by MitchellTCG** [comment]
Currently failing in both situations

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers @toddlees during testing of ticket #1011 the lookup for "Location of Account" is the same issue as this ticket.   Todd verified the same code for above noted fixes, is used for this fix also.   Adding "Organization" information missing in required field upon saving.   

@MitchellTCG verify the verbiage needing added is:  "Organization information is required" 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9cf8e400-810f-44a4-a66a-d4b2f17960cf)

**Comment by MitchellTCG** [comment]
"Organization information is required" is the correct verbiage

**Comment by toddlees** [comment]
passes CR moving to QA

**Comment by WiseQA** [comment]
QA review retested the following transactions and verified the  Committee/Candidate information "missing required fields" verbiage is displayed.

1.   Verified Committee/Candidate information > Candidate field is a required field upon saving transaction. "Candidate information is required". Tested Refund of Contribution to Federal Candidate (Schedule A)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHN2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--96dd5b5d63c9d9fe96b6ec11c8d3644bf10f160e/image.png)

2.  Verified Committee/Candidate information > Candidate field is a required field upon saving transaction. "Candidate information is required". Tested Contribution to Candidate (Schedule B)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaW92IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0fc7c5ef11648497a14d21ae6e0b1b1662c84cc0/image.png)

3.  Verified Committee/Candidate information > Both Committee and Candidate fields are required fields upon saving transaction. "Committee information is required" and "Candidate information is required". Tested In-kind Contribution to a Candidate (Schedule B)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTR2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9abfa0236d8b8c4d38e70e6c4de0af47fa013322/image.png)

4.    Verified Committee/Candidate information > Organization field is a required field upon saving transaction. "Organization information is required". Tested Loan Agreement for Loan Received from Bank.  (Note Future Income radio button must be "Yes")

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2N2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6d91c5675614adcb7f03ac6e2842fcbddb5ab262/image.png)

QA Review Completed.  Moved to Stage Ready.
