### ISSUE TITLE
3 - Allow user to report Repayment of Debt Owed to Committee (Schedule A)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1168]
Business Reason

As a Committee Administrator, I will be able to initiate and report a Repayment of an outstanding Debt Owed to Committee on a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria

**Given** I am a Committee Administrator editing an open Form 3X report
**When** I open the action kebab menu for an existing Schedule D "Debt Owed to Committee" on the transaction table
**And** I click on the "Report debt repayment" option
**Then** I will be able to initiate one of the following transactions that will link to the owed debt:

- Individual Receipt
- Tribal Receipt
- Partnership Receipt
- Partnership Attribution
- In-kind Receipt
- Returned/Bounced Receipt
- Party Receipt
- Party In-kind Receipt
- Party Returned/Bounced Receipt
- PAC Receipt
- PAC In-kind Receipt
- PAC Earmark Receipt
- PAC Conduit Earmark (Deposited)
- PAC Conduit Earmark (Undeposited)
- PAC Returned/Bounced Receipt
- Earmark Receipt
- Conduit Earmark (Deposited)
- Conduit Earmark (Undeposited)
- Receipt from Unregistered Entity
- Receipt from Unregistered Entity - Returned/Bounced Receipt
- Transfer
- Joint Fundraising Transfer
- In-kind Transfer
- In-kind Transfer - Federal Election Activity
- Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account
- Joint Fundraising Transfer - National Party Pres. Nominating Convention Account
- Joint Fundraising Transfer - National Party Headquarters Buildings Account
- Refund of Contribution to Federal Candidate
- Refund of Contribution to Other Political Committee
- Refund of Contribution to Unregistered Committee
- Offset to Operating Expenditures
- Other Receipts
- Individual Receipt - Non-contribution Account
- Other Committee Receipt - Non-contribution Account
- Business/Labor Organization Receipt - Non-contribution Account
- Individual Recount Receipt
- Party Recount Receipt
- PAC Recount Receipt
- Tribal Recount Receipt
- Partnership Recount Account Receipt
- Individual National Party Recount/Legal Proceedings Account
- Party National Party Recount/Legal Proceedings Account
- PAC National Party Recount/Legal Proceedings Account
- Tribal National Party Recount/Legal Proceedings Account
- Partnership National Party Recount/Legal Proceedings Account 
- Individual National Party Headquarters Buildings Account
- Party National Party Headquarters Buildings Account
- PAC National Party Headquarters Buildings Account
- Tribal National Party Headquarters Buildings Account
- Partnership National Party Headquarters Buildings Account
- Individual National Party Pres. Nominating Convention Account
- Party National Party Pres. Nominating Convention Account
- PAC National Party Pres. Nominating Convention Account
- Tribal National Party Pres. Nominating Convention Account
- Partnership National Party Pres. Nominating Convention Account
- Earmark Receipt for National Party Recount/Legal Proceedings Account (Contribution)
- Earmark Receipt for National Party Pres. Nominating Convention Account (Contribution)
- Earmark Receipt for National Party Headquarters Buildings Account (Contribution)

**And** When I select a transaction
**Then** A transaction screen will open for me to enter and save the details.

 Wireframe

# Wireframe with Report debt repayment button
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWlZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f76c8f60b4e8887a5266eb55e319bcd84666e16f/1168%20-%20Allow%20user%20to%20report%20Repayment%20of%20Debt%20Owed%20to%20Committee%20-%20Table.png)

# Transaction Selection
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXFZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e08a63e09ed5edfbe4794724fd19d1d9ce4d62a0/1213%20-%20Allow%20user%20to%20report%20Repayment%20of%20Debt%20Owed%20by%20Committee%20-%20Expanded.png)

# The type of report selected should have a tag stating it is a debt repayment on it
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaitZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bd1e85654674015056e5626e6b611af4e31c0868/1168%20-%20Allow%20user%20to%20report%20Repayment%20of%20Debt%20Owed%20to%20Committee%20-%20Individual%20Receipt.png)

# 1168 Prototype
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0NZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d18a405185ef9ab22b0f21efcf6bed3689af1cd5/1168%20-%20Allow%20user%20to%20report%20Repayment%20of%20Debt%20Owed%20to%20Committee%20-%20Proto.mp4)

### QA Notes ### 
 - The disbursement entry form should say "DEBT REPAYMENT" under the header per the wireframe.
- Users can still enter negatives if allowed on the debt repayment transaction, which would result in an _increased_ balance. (Confirmed with Ryan and Marlene 8/10/23)
- note that until #1124 is through, `Receipt from Unregistered Entity` will appear as `Unregistered Receipt from Person`
### DEV Notes ### 
 - Debt repayments are tied to the Schedule D debt with the back reference ID.
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@GreggMoreland 
Debts Owed by the Committee - SD10 - (possible debt repayments)  Lines 21, 21b, 22, 23, 24, 25, 28a, 28b, 28c, 29, 30a, 30b
Debts Owed to the Committee - SD9 - (possible debt repayments) Lines 11a, 11b, 11c, 12, 15, 16, 17, 18a

**Comment by GreggMoreland** [comment]
@AureliaKhorsand All the possible transactions for line numbers 11a, 11b, 11c, 12, 15, 16, 17 are listed here (18a is in Schedule H3)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
wires added

It's you call if this process need a debt repayment table. (feel free to add to a future ticket or remove all together)

**Comment by toddlees** [comment]
~~passes CR moving to QA~~
wrong ticket

**Comment by MitchellTCG** [comment]
@GreggMoreland 
UX review complete

**Comment by GreggMoreland** [comment]
@toddlees BA Review complete

**Comment by mjtravers** [comment]
From CR: Let's add the transaction ids to the transaction tables so we can track which repayments to to which debts. Sending back to In Progress

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review noticed wording is missing under "Report debt repayment"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXZGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--302b5e671f9f6197a451c2c9572b4bfa20c4ccb1/image.png)

@mjtravers @toddlees add verbiage below the "Report debt repayment" as denoted in wireframe.  (See below screenshot) of what needs to be there.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVhGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--18dcb3ded30a58d99bdc17a64b97ee31e8aabb83/image.png)

@toddlees update comments in ticket when fixed.

**Comment by toddlees** [comment]
Patch to add description under Report debt repayment title and add spacing: Merged

**Comment by WiseQA** [comment]
QA review verified when selecting the Actions dropdown for a Debt Owed to Committee "Report debt repayment" is displayed and selectable.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3ZNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5893915701fefc397f810513d1fc10f111fe18ac/image.png)

Verified Report debt repayment page is displayed with Accordion drops downs for Schedule A (Receipts)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzNNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4e63bc4fdf91af2d50fdebbb13b18169e1ffc4f9/image.png)

Verified verbiage below Report debt repayment was added per fix.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcERNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--67a1a9f5660a03e3dbe19b950c697abc71098fbf/image.png)

Select Receipt transaction from accordion dropdown (tested with Individual Receipt), verify "DEBT REPAYMENT" verbiage is below transaction name.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcExNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--82225ac9faf8c4f31a6ad638ae6c48ef6720c7c0/image.png)

Verified transaction is created and displayed in the transactions table under Receipts.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGZNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d311e0852c9245145889ecff4fea32ec3602b3f0/image.png)

QA Review Completed. Moved to Stage Ready.
