### ISSUE TITLE
2 - System to pull outstanding debt(s) forward when a new report is created

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1169]
Business Reason

As a user, I will be able to see any outstanding Schedule D debts pull forward onto any new report I create until that debt balance is $0 so that I can continue to report outstanding debts and associate repayments as needed.

 Acceptance Criteria

**Given** a user has Schedule D debt(s) on a previous report with a debt balance other than $0
**When** the user creates a new report in the future
**Then** the Schedule D debts(s) will be pre-populated in the report (the transaction ID will be the same as the original.)
**Except** if the Schedule D debt(s) is marked as a memo item - do _not_ pull it forward if that is the case.

---

**Given** the following transactions have pulled forward,
**then** the fields will not change rules regarding if they can be edited or not (i.e., if they were editable before, they are editable now):
- Debt Owed by Committee
- Debt Owed to Committee

---

**Given** the following transactions have pulled forward,

- Debt Owed by Committee
- Debt Owed to Committee

 **then** the Incurred Amount will reset to $0, and will be editable by the user.
 

### QA Notes ### 
 - Note that in order for the debt to not pull forward, it either must be marked as a memo item or have a balance of _exactly_ $0, not more or less.
- The transaction ID must be the same as the original.
### DEV Notes ### 
 - "Incurred Date" will NO LONGER have the validation that it must be within report coverage dates. 
- The transaction ID must be the same as the original. 
- A new field will be added to the transaction table that will hold the UUID of the originating transaction for copied forward transactions. We can use this as a flag so the transaction type code knows the transaction is a pulled forward transaction
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@GreggMoreland 
No UX Review needed

**Comment by GreggMoreland** [comment]
BA Review complete

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

QA NOTE: There is a code dependency on 1195 which is still In Progress. Each of 1195 and this ticket had a dependency on the other so it was decided to push this ticket forward with the understanding that, temporarily until 1195 is done, that ALL debts will be pulled forward, not just the ones that don't have a 0.00 balance. That feature should be tested after 1195 is in QA.

**Comment by mjtravers** [comment]
This ticket and ticket 1195 are interdependent. This ticket has passed CR and will move forward to QA with ticket 1195.

**Comment by mjtravers** [comment]
Moving to QA with 1195

**Comment by WiseQA** [comment]
QA review verified debts displayed in transactions table when new report created. Verified outstanding debts if any are displayed.  Verified Transaction IDs displaying correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcURaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--413df4107ee0aa9daf79de204b8e7ce328611715/image.png)

QA Review Completed.   Moved to Stage Ready.
