### ISSUE TITLE
1 - Summary Page: System to calculate Debts and Obligations owed TO the Committee (Line 9) (Column A Only)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1171]
Business Reason 
 

On the Summary Page, Line 9 should be a total of transactions with form type **SC/9** or **SD9**_except_ for if the transaction has "Memo Code" checked. This ticket is for Column A only.

 Acceptance Criteria 
 

1. Summary Page 9 (column A) of Form 3X must:
--  consist of the total of the balance amount on transactions with form type "**SC/9**"  and "**SD9**" within the report period using the following fields:

- On **SC/9**, the total should be calculated using LOAN BALANCE on the transaction
- On **SD9**, the total should be calculated using the BALANCE AT CLOSE on the transaction

-- NOT include any transactions with "Memo Code" checked

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
 
- [x] BA/Design Quality Checklist complete

Main transaction types included here:
Schedule C: Loan By Committee - LOAN BALANCE  
(QA NOTE:   Field used to test in named - BALANCE OUTSTANDING on transaction" (Wise)

Schedule D: 
Debts Owed To Committee - BALANCE AT CLOSE
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1pVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bdb7bbec6930faa99931f2455122b8900d6d9e22/image.png)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Summary Page for Line 9 (Column A ONLY) is displaying correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDVvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4d125d7279ebbd02deaf73b40154af45ba00e06/image.png)

QA Review Completed.   Moved to Stage Ready.

**Comment by MitchellTCG** [comment]
Final answer specs and code should read SC/10 & SD10

**Comment by WiseQA** [comment]
@GreggMoreland @MitchellTCG - Gregg just reverifying that the transactions tested for this DSP are only the two transactions:   Schedule C: Loan By Committee - LOAN BALANCE and Debts Owed To Committee - BALANCE AT CLOSE (Please confirm - thanks)

**Comment by GreggMoreland** [comment]
@WiseQA Yes, those are the two transactions which are reported on line 9

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
**(QA NOTE:   Field used to test in named - BALANCE OUTSTANDING on transaction" not Loan Balance)**

QA review verified the Summary Page for this report (used March 20 (M3) for testing) Line 9 (Column A) calculates the following transaction fields.

1.  Schedule C - Loan By Committee - OUTSTANDING BALANCE
2.  Schedule D - Debts Owed To Committee - BALANCE AT CLOSE
3.  Above 2 transactions total Line 9 (Column A)

Schedule C - Loan By Committee - OUTSTANDING BALANCE - used for calculation:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXZ2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82cdbc35370cca80a13d5ab55cf779cfabb3579d/image.png)

Schedule D - Debts Owed To Committee - BALANCE AT CLOSE - used for calculation

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS92QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--858a97f76decdf0c56100fa1916cb6bff529c974/image.png)

Summary Page calculated from Schedule C = $250.00 and Schedule D = $99.99 - Total Line 9 = $349.99

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0x2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d98ecb87ac9f34d8d919964477e6c9fef411f24d/image.png)

QA Review Completed.   Moved to Stage Ready.
