### ISSUE TITLE
1 - Summary Page: System to calculate Debts Owed BY the Committee (Line 10) (Column A Only)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1172]
Business Reason 
 

On the Summary Page, Line 9 should be a total of transactions with form type **SC/10** or **SD10** _except_ for if the transaction has "Memo Code" checked. This ticket is for Column A only.

 Acceptance Criteria 
 

1. Summary Page 9 (column A) of Form 3X must:
--  consist of the total of the balance amount of the transactions with form type "**SC/10**"  and "**SD10**" within the report period using the following:

- On **SC/10**, the total should be calculated using LOAN BALANCE on the transaction
- On **SD10**, the total should be calculated using the BALANCE AT CLOSE on the transaction
- 
-- NOT include any transactions with "Memo Code" checked

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
 
- [ ] BA/Design Quality Checklist complete

Main transaction types included here:
Schedule C: 
Loan Received from Individual - LOAN BALANCE
Loan Received from Bank - LOAN BALANCE
(QA NOTE:   Field used to test in named - BALANCE OUTSTANDING on transaction" (Wise)

Schedule D: 
Debts Owed By Committee - BALANCE AT CLOSE
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDVWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--054142ea155894bb0cbd8e2c5df98902964b17f8/image.png)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Summary Page for Line 10 (Column A ONLY) is displaying correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXRvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2924bbfd7cbab5ac9f6895dc3e0bd6a3dca5356f/image.png)

QA Review Completed. Moved to Stage Ready.

**Comment by MitchellTCG** [comment]
Final answer specs and code should read SC/10 & SD10

**Comment by WiseQA** [comment]
@GreggMoreland @MitchellTCG - Gregg just reverifying that the transactions tested for this DSP are only the three transactions:  Loan Received from Individual - LOAN BALANCE; Loan Received from Bank - LOAN BALANCE and Debts Owed By Committee - BALANCE AT CLOSE (Please confirm - thanks)

**Comment by GreggMoreland** [comment]
@WiseQA Yes, those are the only transactions which are reported on line 10

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
**(QA NOTE: Field used to test in named - BALANCE OUTSTANDING on transaction" not Loan Balance)**

QA review verified the Summary Page for this report (used March 20 (M3) for testing) Line 10 (Column A) calculates the following transaction fields.

1.  Schedule C - Loan Received from Individual - OUTSTANDING BALANCE
2.  Schedule C - Loan Received from Bank - OUTSTANDING BALANCE
3.  Schedule D - Debts Owed By Committee - BALANCE AT CLOSE
Above 3 transactions total Line 10 (Column A)

Schedule C - Loan Received from Individual - OUTSTANDING BALANCE - used for calculation:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2p2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5cdcec09904fa0ff0549c6dc785b20e27c30d155/image.png)

Schedule C - Loan Received from Bank - OUTSTANDING BALANCE - used for calculation:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzN2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1526990f216d2de5c0a7652482174fbe1ef4ca8b/image.png)

Schedule D - Debts Owed By Committee - BALANCE AT CLOSE - used for calculation:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0R2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--685d08eed41bc55e512ac38d7c73dc70b30d0550/image.png)

Summary Page calculated from Schedule C(s) = $10,300.00 and Schedule D = $50.00 - Total Line 10 = $10,350.00

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2Z2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5265dd8f5933929d704e63a394608313d347ca6a/image.png)

QA Review Completed.   Moved to Stage Ready.
