### ISSUE TITLE
1- Summary Page and DSP: System to calcuate Total Receipts (Line 6.c and Line 19) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1174]
Business Reason 
 

On the Summary Page, Line 6.c and Detailed Summary Page Line 19 should be a calculation of the sum of values from the following DSP line numbers: 11.d, 12, 13, 14, 15, 16, 17, and 18.c. This ticket is for Column B only.

 Acceptance Criteria 
 

1. Summary Page 6c and Detailed Summary Page Line 19 (column B) of Form 3X must:
--  consist of the total of transactions included in the following Detailed Summary Page values, **from January 1 of current year to the report coverage period end date**:
- 11.c Total Contributions (#808)
- 12 Transfers From Affiliated/Other Party Committees (#801)
- 13 All Loans Received (#1037)
- 14 Loan Payments Received (#1036)
- 15 Offsets to Operating Expenditures (#426)
- 16 Refund of contributions Made to Federal Candidates and Other Political Committees (#1020)
- 17 Other Federal Receipts (#809)
- 18.c Total Transfers (Future ticket will update after Schedule H3 and H5)

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
 
- [x] BA/Design Quality Checklist complete

- These two values are the sum of the values of all Receipts, listed above by line number.
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2hWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac728c7f58e0cf4975d5895c55c0d319d699e030/image.png)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Detailed Summary Page for Line 19 (Column B ONLY) is displaying correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTFvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0c306965f9c66e435b0bb2d59b20219138e3202/image.png)

Verified Summary Page for Line 6.c (Column B ONLY) is displaying correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTlvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6d1cb18a1e29fbd2dcc43a9a58e49e013348ff6/image.png)

QA Review Completed. Moved to Stage Ready.

**Comment by WiseQA** [comment]
Defect fix calculations in Summary Page and Detailed Summary pages 1173 and 1174 from 11.c to 11.d

11.c Total Contributions (#808) should have been 11.d #283 for both tickets,   Comment in tickets noted for incorrect list in AC.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3ZLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ac41d6aaea0419c839aff7c117a6ad89325e4d3/image.png)

Defect: 

https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/1516

@MitchellTCG @mjtravers Defect created (hotfix) #1516 for Sprint 33.   Defect (hotfix) pointed 2.
