### ISSUE TITLE
2 - DSP: System to calculate Total Federal Receipts (line 20) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1176]
Business Reason 
 

On the Detailed Summary Page Line 20 should be a calculation of the line 19 value minus the line 18c value. This ticket is for Column B only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 20 (column **B**) of Form 3X must:
--  consist of the the following calculation:
- Line 19 - Total Receipts (#1174) minus Line 18.c Total Transfers (set to zero in #1427) (Column B values only)

 DEV NOTES

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
 
- [x] BA/Design Quality Checklist complete

- These two values are subtracted from each other, line 18.c is subtracted from Line 19
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Detailed Summary Page for Line 20 (Column B ONLY) is displaying correctly. (Used JULY 15 QUARTERLY REPORT (Q2) 04/01/2023 — 06/30/2023 for testing) (NOTE: Line 18.c is value of zero as this has not been developed to date.)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkx3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--102bfc35a63b0efe065fe125049e46589d631290/image.png)

QA Review Completed. Moved to Stage Ready.
