### ISSUE TITLE
4 - System to warn user if Date Incurred is outside report coverage dates on Schedule C loans  [1 - STEP 3 of 4]

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1177]
Business Reason

As a user, I will be able to clearly see that putting a loan's Date Incurred out of the report coverages dates is not allowed, so that I can update the date appropriately and save the loan transaction.

 Acceptance Criteria

**Given** the user is creating or editing a Schedule C loan transaction including:
- Loan Received by Individual
- Loan by Committee

**When** the user puts a "Date Incurred" outside the report coverage dates
**Then** they will receive a message indicating that it is required for the Date Incurred to be within the report coverage dates
**and** they will be unable to save until they change the date to be within the report period coverage dates.

 Wireframe
![1177 - Date Incurred is outside report coverage.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0fd69643-bbd6-471a-af59-355beedc8486)

### QA Notes ### 
  DEV Notes
Here is the error message:
**This date must fall within the coverage dates of 03/01/2022 - 03/31/2022 for this report**
[Please dynamically add the coverage dates for the current report into the error message]

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG wire approved.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG need clarification on this ticket.    Are we doing the just checking popup ?  

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c7f009b8-d9dc-4928-a6fa-8b6856242185)

 AC only shows text below "Date Incurred" field.  Nothing denoted in acceptance criteria or wireframe about Just Checking popup ?

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/84c1bb58-20aa-483e-a187-88fd454af657)

If Just checking popup not valid here then the Memo Item checkbox "This is a required field" needs fixed.  "Dates must fall within coverage dates"


![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/893bfe5c-bd7f-45ec-a4af-f34a234ad7c2)

Awaiting clarification on display of Date incurred outside report coverage dates.

NOTE:   There is no Just checking popup as verified.

**Comment by mjtravers** [comment]
The flag to turn off the pop up was mistakenly removed. It has been restored. The patch has been deployed to DEV and is ready for QA.

**Comment by WiseQA** [comment]
QA review verified the popup for Just checking has been disabled.    

Verified date incurred outside report coverage error message is displayed below the Date Incurred field. Tested with Loan Received by Individual (Ticket #1000 and #1002)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/24d8c2b2-9125-40e3-9ded-e53ad78db91c)

QA Review Completed.   Moved to Stage Ready.

**Comment by MitchellTCG** [comment]
Moved back to ASA til Loan from Bank is completed. Then we pull back into the sprint.
