### ISSUE TITLE
7 - Allow user to see original C1 Loan Agreement on original report as read-only

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1178]
Business Reason

As a user, I will be able to view any C1 - Loan Agreements associated with Schedule C Loans on the original report so that I can review what was originally sent to FEC and know if I need to update it.

 Acceptance Criteria

**Given** a "Loan Received from Bank" has been created on a previous report (per #1069) and has been pulled forward onto a report the user is currently editing,
**When** the user selects the action "Review loan agreement" on the action menu for the transactions from the transactions table,
**Then** they will be taken to the associated Loan Agreement (read-only) on the **original report** it was disclosed on.

 Wireframe

# Transaction
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjAxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ef145bd9de726d18b5ddb312f33e053a8ee6783/1178%20-%20Loan%20Received%20from%20Bank%20%E2%80%93%20Loan%20Agreement%20%E2%80%93%20READ%20ONLY.png)

# Transaction in this Report Page
![1033 - Transactions in this report - 4 – 1.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/eea60cdd-987a-4466-a5e3-e635721f2551)

### QA Notes ### 
  DEV Notes
- This should point to the most recent C1 created by the user. 
- The user will be able to initiate a new C1 per #1122. That functionality is not included here.
- The sub-headline 'Loan agreement' light grey should use the hex color of #AEB0B5

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Please Review

![1178 - Loan Received from Bank – Loan Agreement – READ ONLY.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ad21beed-a2ba-4b29-830b-44f36e99961c)

**Comment by JonellaCulmer** [comment]
@MitchellTCG Assuming I have the process correct, here's a quick workshop on the language at the end:

Preference: 
"The information provided for this loan will automatically generate a related [Name of transaction] transaction." 

If we think we need more info:
"The information provided for this loan will automatically generate a related [Name of transaction] transaction. Continue by reviewing the information you provided and enter a purpose of receipt or note/memo text."

**Comment by MitchellTCG** [comment]
@JonellaCulmer 
The third accordion is optional. The user can review it or just skip it and save the transactions. That is the reason for the cumbersome language. We can workshop tomorrow.

**Comment by MitchellTCG** [comment]
@GreggMoreland 
The only new styling piece is a sub headline in lighter grey. The hex color of that grey is #AEB0B5
UX Review Complete

**Comment by GreggMoreland** [comment]
BA Review Complete

**Comment by dheitzer** [comment]
Changed to 5pt per discussion with Gregg and Matt regarding this C1 displaying in its own screen (as opposed to simply in the accordion)

**Comment by GreggMoreland** [comment]
Requirement question: If a prior report which had original loan is 'In Progress', will the Loan Agreement be read only on future reports or can it be edited?

**Comment by dheitzer** [comment]
@GreggMoreland @AureliaKhorsand tangentially, we might want to clarify this AC:

`This should point to the most recent C1 sent to FEC.`

**Comment by AureliaKhorsand** [comment]
Closing as OBE after discussion with Ryan on Slack on 9/28. Essentially, we gain very little value from implementing this link, as users typically don't go look at old loan agreements, and they can always find it on their own (in fact, this is what they're used to on FECfile Desktop). Implementing this would open a lot of questions about how the links work, how they get back to their current report, etc., so for now we don't want to do it.
