### ISSUE TITLE
Generate Dependency Report

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-web-app#118]
***User Story***

  As a QASP evaluator, I would like to have a dependency report for each repository.

***Acceptance Criteria***

*   [x] The report should include all packages used for that repository, the version number we are using, and the license for the package.
*   [x] Separate reports should be generated for the:
*   fecfile-web-app
*   fecfile-web-api
*   fecfile-validate
*   fecfile-image-generator repositories.

***QA***

  See the last comment below for links to the 4 license reports.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1298](https://fecgov.atlassian.net/browse/FECFILE-1298)

**Comment by MitchellTCG** [comment]
The report will be stored within Circle CI

**Comment by mjtravers** [comment]
Here are the 4 license reports, one for each repo:

[api-license-report.md](https://github.com/fecgov/fecfile-web-app/files/8142976/api-license-report.md)

[image-generator-license-report.md](https://github.com/fecgov/fecfile-web-app/files/8142978/image-generator-license-report.md)

[app-license-report.txt](https://github.com/fecgov/fecfile-web-app/files/8142985/app-license-report.txt)

[validate-license-report.md](https://github.com/fecgov/fecfile-web-app/files/8142986/validate-license-report.md)

**Comment by WiseQA** [comment]
Verified license report for each repo.  (Note:  below images are snipped shots for verification license report is generated and not a complete list.)

API License Report    api-license-report.md
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/36827d9c-1c9d-46a1-878e-423b7dfeb286)

Image Generator License Report    image-generator-license-report.md
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/445f8d6d-da6d-4187-8d1d-facc2c333a74)

App License Report    app-license-report.txt
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ca2a0db2-b13d-4bb3-a368-acdd8aa1379a)

Validate License Report    validate-license-report.md
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/82292ffe-17d0-455e-aa5f-ce8617913dee)

QA review completed.  Moved to Stage Ready.
