### ISSUE TITLE
1 - DSP: System to calculate Independent Expenditure (Line 24) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1183]
Business Reason 
 

On the Detailed Summary Page, Line 24 should be a total of transactions with form type SE _except_ for if the transaction has "Memo Code" checked. This ticket is for Column B only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 24 (column B) of Form 3X must:
--  consist of the total of transactions with form type "SE"  **from January 1 of current year to the report coverage period end date**
-- NOT include any transactions with "Memo Code" checked

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
 
- [x] BA/Design Quality Checklist complete

Main transaction types included here (Accessed by 'Add a Disbursment'):
- Independent Expenditure
- Multistate Independent Expenditure 
- Independent Expenditure Void
- Credit Card Payment for Independent Expenditure
- Staff Reimbursement for Independent Expenditure
- Payment to Payroll for Independent Expenditure
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@GreggMoreland @MitchellTCG what is being used to calculate the Line 24 Column B ?   The "Amount" field or the "Calendar Year-To-Date" field ?

**Comment by GreggMoreland** [comment]
@wiseQA the Amount field
Thanks Gregg just double verifying (I was second guessing)

**Comment by WiseQA** [comment]
QA review verified Detailed Summary Page for Line 24 (Column B ONLY) is displaying correctly. (Used APRIL 20 MONTHLY REPORT (M4) 03/01/2000 — 03/31/2000 for testing).   Added Independent Expenditure in amount of $75.00.   Calendar To-Year-Date updated correctly ($5969.00 + 75.00 = $6044.99).  (Note:  $5969.00 from #1182)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmJ3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a09f8f698b941132d2ef15e5d8ca8b7d510adf5e/image.png)

QA Review Completed. Moved to Stage Ready.
