### ISSUE TITLE
3 - Add 'Review loan agreement' to transaction action for Loan Received by Bank

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1186]
Business Reason

As a Committee Administrator,  I will be able to click on the 'Review loan agreement'  in the Action kebab next to my 'Loan Received by Bank' transactions  so that I can view the details of the current Loan Agreement for that Loan Transaction.

 Acceptance Criteria

**Given** I am a Committee Administrator editing an open Form 3X report
**When** I click on the Action kebab next to Loan Received by Bank transaction
**Then** I will have the option listed 'Review loan agreement'
**And** clicking on that option takes me to the Loan Agreement for that Schedule C Loan. 

### QA Notes ### 
 Note the "Edit" and "Save" was not tested in this ticket.
### DEV Notes ### 
  Wireframe
![1186 - Add ‘View loan agreement’ to transaction action for Loan Received by Bank.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/bab8674e-710d-4f88-9722-9eda8a3eb5c8)

### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Wire posted

**Comment by AureliaKhorsand** [comment]
Wire approved.

**Comment by mjtravers** [comment]
When opening the loan agreement, the second tab opens but the top of the screen starts at the address in put box. Can we anchor the opening to the accordion header or right below?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGROIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--13ea8a8c61af3946edea44f9d055cb7223bb8938/image.png)

@Elaine-Krauss-TCG @WiseQA  - Sending back to In Progress to see if this can be done easily. If not, let's talk to Shelly to see if it needs another ticket.

**Comment by mjtravers** [comment]
Scrolling issue occurs on all pages navigated to, it's just more pronounced in this case. If needed, issue can be addressed globally in a new ticket. Ticket passes CR, sending to QA.

**Comment by mjtravers** [comment]
While ad hoc testing, the Loan By Bank screen is not saving. Sending to In Progress to check out.

**Comment by mjtravers** [comment]
Loan By Bank problem sorted out when latest develop branch merged in. Passes CR. Sending to QA.

**Comment by mary-tcg** [comment]
Dropdown AC should say "Review loan agreement" to match UX design pattern rather than "View loan agreement".

Thanks Mary for clarifying the terminology per UX design.   @WiseQA

**Comment by WiseQA** [comment]
@GreggMoreland @MitchellTCG @mjtravers Gregg can you please fix AC to read "Review loan agreement".   UX verified the verbiage.

**Comment by GreggMoreland** [comment]
Ticket updated

**Comment by WiseQA** [comment]
QA review verified dropdown  was changed from "View loan agreement" to "Review loan agreement" to match UX design pattern.

**Comment by WiseQA** [comment]
QA review verified when selecting the "Actions" dropdown from "Loan  Received from Bank" transaction the "Review loan agreement" option is displayed and selectable.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEpyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5ec2197838f016f2f52ca08af363887a4e52a654/image.png)

Verify the "Loan Agreement" is displayed and can be reviewed.  This is the only requirement tested for this ticket per AC.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHRyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e69fb9d2ed9b48276f84bd9fa528c4534720ad23/image.png)

QA verified scrolling issue was fixed and Loan Agreement is displayed correctly.

QA Review Completed.   Moved to Stage Ready.
