### ISSUE TITLE
Auto-populate the Treasurer using Committee treasurer when creating C1 (Loan Agreement) transaction

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1187]
Business Reason

As a Committee Administrator, I will be able to see the Treasurer name from my Committee auto-populated when I create a new Loan Agreement (C1) so that I can create a new agreement correctly.

Acceptance Criteria

***Given*** I am a Committee Administrator creating a Loan Received from Bank

  ***When*** I click on the section to Add loan agreement

  ***Then*** the Treasurer Name fields will be pre-populated with the name of the Treasurer of my Committee. The following will be populated (but will remain editable):

*   ***LAST NAME*** (Required)
*   ***FIRST NAME*** (Required)
*   ***MIDDLE NAME*** (Optional)
*   ***PREFIX*** (Optional)
*   ***SUFFIX*** (Optional)

Wireframe

  ![Screenshot 2023-07-24 at 2.09.22 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0338ab2f-2e81-4593-9e78-46a4d5e65338](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0338ab2f-2e81-4593-9e78-46a4d5e65338))

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
Please validate the all committees on DEV and STAGE have COMPLETE treasurer info

### Design ###
null

 See full ticket and images here: [FECFILE-714](https://fecgov.atlassian.net/browse/FECFILE-714)

**Comment by MitchellTCG** [comment]
@GreggMoreland  Updated

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
**QA review tested using Login.gov and Test Committee ID C00100495 assigned to QA for testing.**

QA review verified when creating a Loan Agreement the "Committee Treasurer" auto-populated with correct treasurer information.  

____________________________________________________________________________________________________________________

<img width="1016" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzc5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb5763980f23a271ed2ac0312dd0bc72bf8b7d2f/image.png" alt="image.png" />

___________________________________________________________________________________________________________________

<img width="1263" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0Q5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a5e8aa50227c35ee8d888879efe782a1ed2badc/image.png" alt="image.png" />

____________________________________________________________________________________________________________________

QA and DEV review verified the required fields and optional fields all auto populate if information is available.

- LAST NAME (Required)
- FIRST NAME (Required)
- MIDDLE NAME (Optional)
- PREFIX (Optional)
- SUFFIX (Optional)
_________________________________________________________________________________________________________

Verified Committee Treasurer fields can be edited and Loan Agreement resaves.

<img width="1142" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ArQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04977bdefb3a238e847e9dd679ce6562c7c139c2/image.png" alt="image.png" />

______________________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
