### ISSUE TITLE
Allow user to enter Candidate Office/State/District info when creating Candidate Contact

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#119]
Business Reason 
 

As a Committee Administrator, I will be able to enter Candidate Office/State/District info when creating Candidate Contact so that I can track Candidate information as required for transactions.

 Acceptance Criteria 
 

**If** I am a Committee Administrator
**When** I access my committee's contact list and am adding a new "Candidate" contact
**Then**  I will be required to input the following:
- CANDIDATE OFFICE (Dropdown: House, Senate, Presidential. Required)
- CANDIDATE STATE (A/N-2, _should be a dropdown, and required if Office = House or Senate_)
- CANDIDATE DISTRICT (A/N-2, required if Office = House. _List should reflect State selected_)

**And** the dropdowns appear as documented in the below xls file (tab 3 Congressional Districts):
https://docs.google.com/spreadsheets/d/17YmnaZgqvFOUyv4-Qknd8ikHe8o9LoDb/edit#gid=1465207356

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
Wireframe

![Candidate.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/fa81e131-a7ee-4494-8572-ef08f7861ebf)

![Candidate Office– Required Fields.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/908a876e-342a-4c5b-9344-e49fc0c18689)

**Comment by AureliaKhorsand** [comment]
**3/16/22 Refinement Meeting:** Mitchell will confirm the dropdown lists with FEC, then load the lists to be validated to the ticket.

**Comment by MitchellTCG** [comment]
@mjtravers 
Please make sure the candidate state dropdown should consist of the states and territories in row 1 of the excel doc. 

The Foreign Countries option should not appear in either candidates dropdowns — Address nor Office.

**Comment by WiseQA** [comment]
Verified candidate office drop down for Presidential no Candidate State or Candidate District fields were displayed.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5c7fd835-12a5-464e-be36-851d3bfb1405)

Verified candidate office drop down for Senate ONLY Candidate State field is displayed.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d47538bb-1712-437a-a9eb-f748448639a4)

Verified candidate office drop down for House Candidate State and Candidate District fields are displayed.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/42139719-cd19-4ab2-a639-5c401194c95f)

Verified Candidate State and Candidate District fields (see Test Case/Test Script)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/79036791-e82a-4a57-82b9-331f5184b75d/download](https://app.zenhub.com/files/306118986/79036791-e82a-4a57-82b9-331f5184b75d/download)

QA review completed.  Moved to Stage Ready.
