### ISSUE TITLE
Remove transaction group code

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1193]
The management of the transaction types by assigning them to groups based on the fields needed has become difficult. The transaction group code needs to be removed and the management of the fields and contact type information for a transaction type moved into the transaction type model.

This ticket replaces #1149

Methods managed by the transaction type group models:

*   getFormProperties
*   getChildFormProperties
*   getContactTypeOptions
*   getChildContactTypeOptions
*   getFormProperties
*   getChildFormProperties
*   hasEmployerInput
*   childHasEmployerInput
*   hasCommitteeFecIdInput
*   hasElectionInformationInput
*   hasCandidateInformationInput
*   hasCandidateCommitteeInput
*   hasParentCandidateInformationInput
*   hasChildCandidateInformationInput
*   hasParentElectionInformationInput
*   hasChildElectionInformationInput
*   getParentTransactionTitle
*   getParentFooter
*   getChildTransactionSubTitle
*   getGroupDescription
*   getParentAccordionTitle
*   getParentAccordionSubTitle
*   getChildAccordionTitle
*   getChildAccordionSubTitle
*   getChildContactLabel
*   getAutoGeneratedChildFields

DEV Notes

*   The methods should be converted to properties unless a dynamic value needs to be generated
*   The parent/child versions of the methods do not need that distinction when migrated into the transaction type model
*   A sensible grouping of form fields can be made based on the Angular input components. These groupings should be easily overridable to allow finer control at the field level

QA Notes

*   Ticket passes if automated tests pass

### QA Notes ###
This ticket replaces #1149

Methods managed by the transaction type group models:
- getFormProperties
- getChildFormProperties
- getContactTypeOptions
- getChildContactTypeOptions
- getFormProperties
- getChildFormProperties
- hasEmployerInput
- childHasEmployerInput
- hasCommitteeFecIdInput
- hasElectionInformationInput
- hasCandidateInformationInput
- hasCandidateCommitteeInput
- hasParentCandidateInformationInput
- hasChildCandidateInformationInput
- hasParentElectionInformationInput
- hasChildElectionInformationInput
- getParentTransactionTitle
- getParentFooter
- getChildTransactionSubTitle
- getGroupDescription
- getParentAccordionTitle
- getParentAccordionSubTitle
- getChildAccordionTitle
- getChildAccordionSubTitle
- getChildContactLabel
- getAutoGeneratedChildFields

DEV Notes

- The methods should be converted to properties unless a dynamic value needs to be generated
- The parent/child versions of the methods do not need that distinction when migrated into the transaction type model
- A sensible grouping of form fields can be made based on the Angular input components. These groupings should be easily overridable to allow finer control at the field level

QA Notes
- Ticket passes if automated tests pass

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-712](https://fecgov.atlassian.net/browse/FECFILE-712)

**Comment by mjtravers** [comment]
For QA: Here are the automated test results:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/eb3aa3d3-8b19-481f-90b7-2187b88607a6)

The report can be found here: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/3356/workflows/3079ad84-eaf7-4bd2-89ea-5b6f29373d97/jobs/12276

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified visual inspection with DEV that from automated testing that this test passed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/34585c4b-17ca-4fcf-883f-3d29668abe43)

QA Review Completed. Moved to Stage Ready.
