### ISSUE TITLE
Update e2e tests to work up to Sprint 27 changes

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1194]
The e2e tests need to be updated to account for UI changes in Sprint 27

The tasks on this ticket include:

*   Adding the updates for UI changes
*   Fixing the inconsistent behavior in CircleCI
*   Make sure the report is available online through CircleCI for viewing

QA Notes
 Ticket passes with an available passing e2e test report

### QA Notes ###
The tasks on this ticket include:
- Adding the updates for UI changes
- Fixing the inconsistent behavior in CircleCI
- Make sure the report is available online through CircleCI for viewing

QA Notes
Ticket passes with an available passing e2e test report

### DEV Notes ###
null

### Design ###
null

[FECFILE-711](https://fecgov.atlassian.net/browse/FECFILE-711)

**Comment by Elaine-Krauss-TCG** [comment]
All existing tests are once again passing.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/5cce5461-6682-4df9-89c1-19c02d261484)

They actually passed on three back-to-back runs, which is a very good sign going forward.

**Comment by mjtravers** [comment]
In CR. I've merged this branch into develop. Let's see how the nightly run goes for a few days, if the report emails are going out, and how the report looks before sending this ticket to QA.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified with DEV on CircleCI the availability and viewing of a report for "Passed" and "Failed" current e2e tests running on a nightly basis.   Video running e2e tests visually shows where a possible "bug" is located in a transaction.   

(NOTE:   Email notifications being worked to report out on the nightly runs if "Failed" tests)

QA Review Completed.   Moved to Stage Ready.
