### ISSUE TITLE
4 - System to auto-calculate "Beginning Balance" and "Balance at Close" for Schedule D Debts

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1195]
Business Reason

As a user, I will see that the "Beginning Balance" and "Balance at Close" for my Schedule D Debts are auto-calculated for me so that I do not have to make the calculations myself, reducing the likelihood of user-error.

Acceptance Criteria

***Given*** a Schedule D debt, either:

1\. Debt Owed to Committee

 2\. Debt Owed by Committee

***Then*** the following fields will be auto-calculated by the system as follows:

*   ***BEGINNING BALANCE***: this will pull from the "Balance at Close" from the same Schedule D on the previous report. If this is the first reporting of the Schedule D loan, this will default to $0.
*   ***BALANCE AT CLOSE***: this will be [Beginning Balance + (Incurred amount - Payment amount)]

### QA Notes ###
- Incurred Amount and Payment Amounts are calculated from transactions _only_ within the current reporting period (see #1212 and #1269)
- NOTE:   These balances are both testable AFTER a new report has been created and the balances pulled to the new report.

### DEV Notes ###
 Debt or obligation information section
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/ea3eb44a-6bbb-47f7-80d3-8a0c158fb74e)

### Design ###
null

 See full ticket and images here: [FECFILE-710](https://fecgov.atlassian.net/browse/FECFILE-710)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
UX Review Complete

**Comment by GreggMoreland** [comment]
BA Review Complete

**Comment by mjtravers** [comment]
This ticket and ticket 1169 are interdependent. This ticket will move forward to QA with ticket 1169.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA with 1169

**Comment by WiseQA** [comment]
@GreggMoreland @AureliaKhorsand @MitchellTCG please update Acceptance Criteria from 

Given a Schedule D debt, either:
Loan Owed to Committee
Loan Owed by Committee

To:
Debt Owed to Committee
Debt Owed by Committee

Thanks -

**Comment by GreggMoreland** [comment]
@WiseQA Updated

**Comment by WiseQA** [comment]
QA review verified the **"Balance at Close"** for both Debt Owed to Committee and Debt Owed by Committee is calculating correctly prior to being pulled forward to another report.  (NOTE:  Created Monthly Report (February 20 Monthly Report (M2) - Report dates 01/01/2000 - 01/31/2000))

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBby9aIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47387ad009ae8bb958b7922aa79aa8460b8026f1/image.png)

Created new Monthly Report (March 20 Monthly Report (M3) - Report dates 02/01/2000 - 02/28/2000).   Verified **"Beginning Balance"** is calculated correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHZaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5c9dd97dcbcbda5f8e17a8f8a4dcdbc7a4f0db0f/image.png)

QA Review Completed.   Moved to Stage Ready.
