### ISSUE TITLE
2 - Allow user to submit an amended Form 3X report

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1197]
Business Reason

As a user, I will be able to submit an amended Form 3X report so that I can report any needed updates to FEC.

Acceptance Criteria

***Given*** the user has an amended report in 'In progress' status

  ***and*** they go to submit the report,

  ***and*** upon submission, the *.fec file will reflect the following:

*   the Form3X specification form type will read "F3XA"
*   the header record will now include ***Rpt ID*** (FEC filing ID of original report) and ***Rpt Number*** (sequential number of amendments.)

### QA Notes ###
- [x] BA/Design Quality Checklist complete
- The "Rpt Number" is blank on original reports, and starts with "1" for the first amendment, "2" for the second amendment, etc.

### DEV Notes ###
- Please note the header record requirements for an amended report, captured in the [specifications here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1335034634).
- Even if a report is a Termination report, the form type will be "F3XA". The report code will remain as "TER".
- **Need to determine what should be sent in Amendment ID in JSON file.**
- Screencap JSON file for QA purposes.

### Design ###
null

 See full ticket and images here: [FECFILE-708](https://fecgov.atlassian.net/browse/FECFILE-708)

**Comment by toddlees** [comment]
JSON sent to fec with "amendment_id":[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDh0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da29c9ac3b13cfce1acbed3d99a5117c597a5e7a/submission%20json.jpg)


.FEC with report id and version in header:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGt0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa710dcddac3029ba055b94dd4a190f1b3fbeda8/dot%20fec.jpg)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review with @toddlees Submission (efo filing) and amending an existing report, Amendment 1 saves and displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUl1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccc7722b85c8feb7f13c20171fd1ab69eac86b61/image.png)

Amendment 2 not submitting.

[Private Zenhub Image](
https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzB1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf018326a0de1e2dca613edf90d79fb241e578ba/image.png)

@MitchellTCG @mjtravers @toddlees returning to In-Progress for fix.

**Comment by WiseQA** [comment]
QA review getting submission failure instead of submission success.   Amendment 2 displaying but there wasn't an Amendment 1 completed.  

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3c3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a11e4de7b4a96d101f3a128ad67a08b7ad7ad25b/image.png)

@mjtravers @toddlees checking into submission failure and Amendment displaying.   Returned to In-Progress for resolution.

**Comment by WiseQA** [comment]
QA retested and the Submission Success working with first submission of report.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekk4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0fb9bc8673ac4fe0b4e375168ef23ab05db09b14/image.png)

Selected Amend and the status stays in-progress for Amendment 1.    (Cleared cache and cookies) still getting same thing.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem84QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2040937902f997bf2e2e8b9935371b1b958df8c2/image.png)

@mjtravers @toddlees just wanted to retest again before sending back to in-progress.

**Comment by WiseQA** [comment]
QA retested and the Submission Success working with first submission of report.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekk4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0fb9bc8673ac4fe0b4e375168ef23ab05db09b14/image.png)

Selected Amend and the status stays in-progress for Amendment 1.    (Cleared cache and cookies) still getting same thing.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem84QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2040937902f997bf2e2e8b9935371b1b958df8c2/image.png)

@mjtravers @toddlees just wanted to retest again before sending back to in-progress.

**Comment by WiseQA** [comment]
QA retested again.

Selected original report and Amend from the dropdown for April 15 (Q1) report.   Version updated with Amendment 1

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGs4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10858fd3985255eebda766c300e16969813b3d13/image.png)

Selected Amend from the dropdown for April 15 (Q1) Amendment 1 report.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHc4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a78fc250d2f334f694769d7d67066eacf66b815/image.png)

Version changed from Amendment 1 to Amendment 2

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVk4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e215ddb639f5b588b8c411790a59131e1688e622/image.png)

April 15 (Q1) Amendment 2 report "Submission Successful"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk04QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2c746cc48deae9f9092c6e6a1df0ff612414476/image.png)

(Note:   before testing this clear all cache and cookies.    Also login.gov times you out when preforming this test.   Therefore I logged in twice to get this ticket to pass correctly. )

@mjtravers @toddlees ticket is passing moved back to QA review and Stage Ready.

**Comment by WiseQA** [comment]
QA Review Completed.   Moved to Stage Ready.
