### ISSUE TITLE
3 - Allow user to provide backdoor code on an amended report

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1198]
Business Reason

As a user, I will be able to include a "Backdoor Code" with submission of my amended report so that I can successfully submit to FEC if I have amended or deleted greater than 50% of the activity, or have an incorrect date range.

 Acceptance Criteria

**Given** an amended report
**When** the user goes to submit the report
**Then** they will have the _option_ to enter a "Backdoor Code" (YES/NO)
**And** if they select "YES", they will be required to enter a backdoor code in order to save (max length A/N-16 per specifications).
**And** that backdoor code will be added to the end of the **amendment ID** on the JSON file sent to FEC along with the generated *.fec file but _not_ on the *.fec file itself. 

 Wireframes 

# Default state of "No":
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb25qIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--15f56b3cc0518988eb336090725eb458c32e20fe/1198%20Allow%20user%20to%20provide%20Back-Door%20Code%20on%20an%20amended%20report%20%E2%80%93%206.png)

# "No" with hovertext over the information icon:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3JqIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--782d1be45790b7ddd5d8ff62aa2abe6d891674c6/1198%20Allow%20user%20to%20provide%20Back-Door%20Code%20on%20an%20amended%20report%20%E2%80%93%208.png)

# State of "Yes":
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmh2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bc8b024a32e43475a8e36ff60701543529d682b/1198%20YES.png)

# Error - Required Field
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmx2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8daa8aa52895865b960608356254b03ba6cc9f44/1198%20ERROR%20-%20Required%20field.png)

# Error - More than 16 Characters
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnB2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9fb9d64570dc642134c2f60bb50031a8177d700e/1198%20ERROR%20-%20Over%2016%20Characters.png)

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
- For the JSON portion, this will be a visual inspection.
### DEV Notes ### 
 The tooltip text should read:
This is only needed if you have  amended or deleted **more than 50% of the activity** in the original report, or have **fixed an incorrect date range.**
### Design ### 
 null

**Comment by mary-tcg** [comment]
@GreggMoreland @AureliaKhorsand @MitchellTCG wires updated

**Comment by MitchellTCG** [comment]
@GreggMoreland @AureliaKhorsand 

Based on a conversation with @JonellaCulmer and @mary-tcg "Backdoor" should be one word.
Jonella referred to the Government Publishing Office. Since backdoor is an adjective of code, it needs to be one word not hyphenated.

I wanted to send this message before changing the ACs. We can discuss in the morning if y'all have visceral objections.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @GreggMoreland agreed on the change. I've updated the ACs, no objections here.

**Comment by MitchellTCG** [comment]
Making a wire for this field is required.

**Comment by MitchellTCG** [comment]
@GreggMoreland please review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers @dheitzer -  Per discussion today awaiting JSON screenshot to be added to ticket.  Per AC backdoor code will be added to the end of the amendment ID on the JSON file.   QA will verify the functionality of the backdoor code fields only in the front matter (no submission).

**Comment by dheitzer** [comment]
STAGE: amendment_id has the backdoor code appended (it is printed as xxxxx as not to in the logs)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzZwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4afc9e7468059cc5f62a1e27df8661bc8d87e393/image.png)

**Comment by dheitzer** [comment]
DEV: amendment_id has the backdoor code appended (it is printed as xxxxx as not to put in the logs)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHlwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff57728abbd66e0dc155df19e865ad6d2312febb/image.png)

**Comment by WiseQA** [comment]
Thanks David !  Looks like this meets AC on showing backdoor code will be added to the end of the amendment ID on the JSON file.

**Comment by WiseQA** [comment]
During QA review the Submit Report page in stage shows "Do you need to use a backdoor code? (Optional) with No / Yes radio buttons and nothing is defaulted.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2F1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee062139adfcaa357653664a5c6249c218d750a3/image.png)

Wireframes in AC shows "Do you need to use a backdoor code? (Optional) with No / Yes radio buttons and NO is defaulted.

@MitchellTCG waiting on clarification what is selected and not selected as default.

**Comment by WiseQA** [comment]
During QA review this ticket is written to where the  "Backdoor Code" to be displayed with submission of amended reports only.   The Backdoor code "Do you need to use a backdoor code? (Optional) with No / Yes radio buttons appears on the initial Submit page of a report.

1.   Report selected to submit is In-progress status

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzJ2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abef486723cd3b242484dc23a3721861d64bb4ce/image.png)

2.  Select Submit report - Submit page displayed with the verbiage "Do you need to use a backdoor code? (Optional) with No / Yes radio buttons 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0N2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5cbfd55454c5c60f6192d22eda63de24a64d2da/image.png)

3.  This should only be displayed for Amended reports after submission not the first time being submitted per BA. @AureliaKhorsand 

@MitchellTCG @mjtravers @dheitzer returning to In-progress for this fix and and awaiting decision on other question above.

**Comment by MitchellTCG** [comment]
@WiseQA 
Re: Backdoor code question
Neither radio button should be selected as a default.

@MitchellTCG thanks

**Comment by dheitzer** [comment]
pushed fix to CRs
https://github.com/fecgov/fecfile-web-app/pull/1500
https://github.com/fecgov/fecfile-web-app/pull/1501

**Comment by mjtravers** [comment]
Passed CR. Sending to QA. Fix is on both DEV and STAGE.

**Comment by WiseQA** [comment]
@dheitzer @mjtravers please document what fix was made from DEV to make sure QA is testing what your fix was pushed.   Thanks !

**Comment by mjtravers** [comment]
The bug fix: A flag was added to the code so the backdoor form input is only displayed when the report is an amendment.

**Comment by WiseQA** [comment]
QA review verified fix - Select Submit report - Submit page  the verbiage "Do you need to use a backdoor code? (Optional) with No / Yes radio buttons has been removed.   

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmUyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66e972efdd1dc61dcf0c9f4d737700c624df28e7/image.png)

This fix passes.

**Comment by WiseQA** [comment]
**QA testing was performed using the test efo filing account set up through login.gov.**

QA review verified on an amended report the option to select the Backdoor code "Do you need to use a backdoor code? (Optional) with No / Yes radio button (neither selected per UX)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNisyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d34fd6393a3344cf8a6a485507281de9ad8b067/image.png)

Verified "No" selected radio button and the hovertext over the information icon:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0syQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5fe6e2150dcf1cdf8a316172051761b88e0bb109/image.png)

Verified "Yes" selected radio button the BACKDOOR CODE field is displayed and the "This is a required field" error is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2EyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86d99e71ab36adedb3a5498b020b2381f41fd748/image.png)

Verified BACKDOOR CODE field error "This field cannot contain more than 16 alphanumeric characters"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3UyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8fe25536efe87cf5d51dcb240a899e55f925db9a/image.png)

Visual inspection of JSON file provided above by DEV
STAGE: amendment_id has the backdoor code appended (it is printed as xxxxx as not to in the logs)
DEV: amendment_id has the backdoor code appended (it is printed as xxxxx as not to put in the logs)

QA Review Completed.   Moved to Stage Ready.
