### ISSUE TITLE
System to require users to consent to security notice annually

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#120]
Business Reason

Per FEC Security team guidance, users will be required to consent to a security notice the first time they log in to FECFile Online, then annually after that. We should require all users to acknowledge the system use notification the first time they access the application. We should track this acknowledgement. Subsequent displays of the notification should happen at least yearly. We only need to keep a record of the most recent acknowledgement.

Acceptance Criteria

***When*** a newly provisioned user logs in to FECFile Online (first time login)

  ***And*** they have entered their user profile information (#92) and clicked "Continue"

  ***Then*** the system will display the following message:

  "insert PLACEHOLDER text here. We will updated with approved language closer to go-live"

***And*** they can either:

*   "Decline and exit" and be sent back to the Landing Page (PER ticket #1719), and the security notice will appear on the next login attempt or;
*   "Consent" _without_ the checkbox selected and continue to the dashboard (or Committee Account selection with #1654), whereupon they will see the security message on next login as well
*   "Consent" _with_ the checkbox selected and continue to the dashboard (or Committee Account selection with #1654), then they will not see the message again for 365 days.

—

***When*** an authorized user logs in to FECFile Online (they have logged in before)

  ***Then*** the system will display the following message:

  "insert PLACEHOLDER text here. We will updated with approved language closer to go-live"

***And*** they can either:

*   "Decline and exit" and be sent back to the Landing Page, and the security notice will appear on the next login attempt or;
*   "Consent" _without_ the checkbox selected and continue to the dashboard (or Committee Account selection with #1654), whereupon they will see the security message on next login as well
*   "Consent" _with_ the checkbox selected and continue to the dashboard (or Committee Account selection with #1654), then they will not see the message again for 365 days.

Dev Notes

1.  Here is the text you should use:

       #

       ***You are about to access the Federal Election Commission computer system.***

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

***By using this system, you consent to the terms set forth in this notice.***

*   Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.

*   Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.

*   Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea?

*   Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores.

*   Et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa.

1.  Please REMOVE THIS VALIDATION

       

Asset

  

svg for the logo:
[https://drive.google.com/file/d/1g-PrMwxXWZ5eiQWjdGYXPkXO0_it4eVJ/view?usp=drive_link](https://drive.google.com/file/d/1g-PrMwxXWZ5eiQWjdGYXPkXO0_it4eVJ/view?usp=drive_link)

### QA Notes ###
 

- [x] BA/QA checklist complete
- Will need to work with devs to test the AC for one year time limit
- Checkbox is OPTIONAL

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1296](https://fecgov.atlassian.net/browse/FECFILE-1296)

**Comment by AureliaKhorsand** [comment]
Ken reached out to Security team on 2/10/22, and they confirmed this is required at each log in. We need the current language from OGC.

**Comment by AureliaKhorsand** [comment]
2/24/22 Requirements Session: Paul mentioned that Wenchun Jiang (CISO) said we can change it to once a month, or once a quarter consent. Paul will follow-up with Christine on this.

Paul: if we think that this message is going to be in usability testing soon, we should probably have more updated language. When we get to the point of needing to develop, Policy should go through Ryan/Debbie and OGC contacts, and Security should go through Paul first (Christine's group in Admin Law)

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 6/1/22:** Shelly and Todd not present. Because this is in Angular code and not login.gov, we can point now.

Dev Notes: Angular Guard will be made, which will determine if the security notice will be shown or not.

**Comment by AureliaKhorsand** [comment]
**Tech Review 6/6/22:** QA approved 8 points, moving to ASA.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG ACs updated. How does the behavior of the checkbox work with the consent button? Should "Consent" be greyed out until the user selects the checkbox? Is there a validation error of any kind if they try to click consent without ticking the checkbox?

**Comment by mjtravers** [comment]
@Elaine-Krauss-TCG Works great. One small graphics change: The black FECFile text in the header is white in the wireframe. We need a copy of the seal-and-title.svg with white lettering from @MitchellTCG 
<img width="501" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW9uQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eab2220beb73e3e7d24319025ca43ed990fe3a87/image.png" alt="image.png" />

Sending back to In Progress

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by MitchellTCG** [comment]
This is the link:
https://drive.google.com/file/d/1g-PrMwxXWZ5eiQWjdGYXPkXO0_it4eVJ/view?usp=drive_link

**Comment by WiseQA** [comment]
QA testing using Login.gov on STAGE. 

From ticket #92 when selecting "Continue" verify Security Notification page is displayed.

<img width="1369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1E4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3a6664e2f423e3ff361c32ff7c6e2940da2587c/image.png" alt="image.png" />

______________________________________________________________________________________________

Verified when selecting "Decline and exit" return to landing page.

<img width="1277" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1U4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6186b6ed33bc139fd5463e4c4cb59d3fa4208070/image.png" alt="image.png" />

_______________________________________________________________________________________________

Select "Consent" verify "Select a committee account" page is displayed.

<img width="1292" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHc4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0edcddf05b271d2ac61902183c8d5e2d5111947/image.png" alt="image.png" />

Verify dashboard was removed and the word "Log Out" is diplayed.

<img width="1292" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDQ4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af665c3e3400a97b66ab0348ecd427061421b107/image.png" alt="image.png" />

__________________________________________________________________________________________

QA Review Completed.  Moved to Stage Ready.

**Comment by WiseQA** [comment]
@MitchellTCG awaiting clarification if after selecting "Decline and exit" is the user sent back to the Login Page or the  Landing Page.   Please let us know the decision - thanks !

**Comment by mjtravers** [comment]
On hold until log out process is fixed in #1721

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by MitchellTCG** [comment]
### QA verified the following: 

#### 1. 
When the yearly consent checkbox has been checked, the following screens are displayed in the following order on the next login: Landing Page, login.gov, 2-Factor Authentication, Get started now page, then Dashboard

<img width="238" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMStiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe8f4122023e3af20e476faa100e0e91d2aeb5ad/120%20-%20System%20to%20require%20users%20to%20consent%20to%20security%20notice%20annually.png" alt="120 - System to require users to consent to security notice annually.png" />


#### 2.  
365+ days after checking the checkbox on the Security Notification, the following screens are displayed in the following order on the next login: Landing Page, login.gov, 2-Factor Authentication, Security Notification, Get started now page, then Dashboard

<img width="200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmViQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07b639e53a7f5f12f8fc69d4d50bb682bf653b9d/120%20-%20System%20to%20require%20users%20to%20consent%20to%20security%20notice%20annually%202.png" alt="120 - System to require users to consent to security notice annually 2.png" />

### QA Review Completed. Moved to Stage Ready.
