### ISSUE TITLE
3 - Allow user to create C1 - Loan Agreement for Loan by Committee

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1205]
Business Reason

As a Committee Administrator, I will be able to enter a ***”Loan Agreement”*** transaction sub-transaction under ***”Loan by Committee”*** on Schedule C of a Form 3X report so that I can accurately report on my committee's transactions.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

  ***And*** I am editing an existing ***"Loan by Committee"*** transaction on an open report

  ***Then*** I will be required to enter the following transaction:

Lender 

  #

*   ***ORGANIZATION NAME*** (Required, with LOOKUP)

1.  Address

       #

*   ***STREET ADDRESS*** (Required)
*   ***APARTMENT, SUITE, ETC.*** (Optional)
*   ***CITY*** (Required)
*   ***STATE/PROVINCE*** (Required)
*   ***ZIP/POSTAL CODE*** (Required)

1.  Loan Information

       #

*   ***AMOUNT (Original)*** (Required, auto-generated from LOAN_BY_COMMITTEE)
*   ***LOAN INCURRED DATE*** (Required, auto-generated from LOAN_BY_COMMITTEE)
*   ***LOAN DUE DATE*** (Required, auto-generated from LOAN_BY_COMMITTEE)
*   ***LOAN INTEREST RATE %*** (Required, auto-generated from LOAN_BY_COMMITTEE)

*   ***LOAN RESTRUCTURED*** (YN Checkbox, Required)
*   ***DATE OF ORIGINAL LOAN*** (Required if Loan Restructured = Y)
*   ***CREDIT AMOUNT THIS DRAW*** (AMT-12, Optional)
*   ***TOTAL BALANCE*** (Required if CREDIT AMOUNT THIS DRAW is populated)
*   ***OTHERS LIABLE*** (YN Checkbox, Required)

1.  Collateral

       #

*   ***COLLATERAL*** (YN Checkbox, Required)
*   ***COLLATERAL DESCRIPTION*** (A/N-100, Required if COLLATERAL = Y)
*   ***COLLATERAL AMOUNT*** (AMT-12, Required if COLLATERAL = Y)
*   ***PERFECTED INTEREST*** (YN Checkbox, Optional)

1.  Future Income

       #

*   ***FUTURE INCOME*** (YN Checkbox, Required)
*   ***DESCRIPTION*** (A/N-100, required if FUTURE INCOME =Y )
*   ***ESTIMATED VALUE*** (AMT-12, required if FUTURE INCOME =Y )
*   ***DEPOSITORY ACCOUNT ESTABLISHED*** (Date, required if FUTURE INCOME =Y)
*   ***LOCATION OF ACCOUNT*** (Org only, NEEDS LOOKUP, required if FUTURE INCOME =Y)
*   ***STREET 1*** (required if FUTURE INCOME =Y)
*   ***STREET 2*** (optional if FUTURE INCOME =Y)
*   ***CITY*** (required if FUTURE INCOME =Y)
*   ***STATE*** (required if FUTURE INCOME =Y)
*   ***ZIP*** (required if FUTURE INCOME =Y)

1.  Basis of Loan

       #

*   ***DESCRIPTION*** (A/N-100, Optional)

1.  Committee Treasurer

       #

***and*** the user will be allowed to enter the following using a LOOKUP, and upon selection the following will be populated:

*   ***LAST NAME*** (Required)
*   ***FIRST NAME*** (Required)
*   ***MIDDLE NAME*** (Optional)
*   ***PREFIX*** (Optional)
*   ***SUFFIX*** (Optional)

*   ***DATE SIGNED*** (Required)

1.  Authorized Representative

       #

       ***And*** the user will be required to select an authorized representative using the LOOKUP, and upon selection the following will be populated:

*   ***LAST NAME*** (Required)
*   ***FIRST NAME*** (Required)
*   ***MIDDLE NAME*** (Optional)
*   ***PREFIX*** (Optional)
*   ***SUFFIX*** (Optional)
*   ***TITLE*** (Required)
*   ***DATE SIGNED*** (Required)

       —

       ***Then*** I will be able to:
*   Cancel
*   Save (must be saved with #1134)
*   Edit

### QA Notes ###
- Treasurer information should pull from the Committee Account (Form 1), but can be editable. If none available or if they want to change it, users must select/create a contact using the Lookup.

### DEV Notes ###
- Treasurer information should pull from the Committee Account (Form 1), but can be editable. If none available or if they want to change it, users must select/create a contact using the Lookup.
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1H1zZmpkhUrKqe25OShtQrgbH1TrhIOSxvI1ZOM-Fw9Y/edit#gid=661269970

### Design ###
null

 See full ticket and images here: [FECFILE-706](https://fecgov.atlassian.net/browse/FECFILE-706)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG here is the ticket for Loan Agreement for Loan by Committee. 
Waiting on response from Ryan to confirm manually entered fields.

**Comment by AureliaKhorsand** [comment]
Confirmed with Ryan on 6/30/23 via Slack that a C1 - Loan Agreement is _not_ required for a Loan by Committee.
