### ISSUE TITLE
4 - System to auto-calculate "Payment Amount" based on Debt Repayments

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1212]
Business Reason

As a user, I should see my updated Payment Amount in the SD Debt whenever I enter a transaction for Debt Repayment so that I can accurately report my debts to FEC.

 Acceptance Criteria

**Given** the user has a debt on schedule D:
- Debt Owed to the Committee
- Debt Owed By the Committee
 
**When** the user enters:
- a Debt Repayment on a Debt Owed to the Committee (Schedule A)
- a Debt Repayment on a Debt Owed By the Committee (Schedule B)

**Then** the transaction amount of that debt repayment will be _added_ to "Payment Amount" value in the associated Schedule D transaction **as long as that debt repayment was in the same reporting period.**

### QA Notes ### 
 - This will apply to "Debt Owed to the Committee” and “Debt Owed By the Committee”
- #1168 described the process and transactions for making a debt repayment owed to the committee
- #1213 described the process and transactions for making a debt repayment owed by the committee
### DEV Notes ### 
 - Debt repayments are tied to the Schedule D debt with the back reference ID.
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@GreggMoreland 
No UX Review needed

**Comment by GreggMoreland** [comment]
BA Review Complete

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Payment Amount is calculating correctly for Debt Owed by Committee and Debt Owed to Committee.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclhNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--70d1f0a00100efc95d4450110e9fbc72ce69a21d/image.png)

Note used Schedule A (Individual Receipt) for testing and Schedule B (Operating Expenditure) for testing.

QA Review Completed.   Moved to Stage Ready.
