### ISSUE TITLE
3 - Allow user to report Repayment of Debt Owed by Committee (Schedule B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1213]
Business Reason

As a Committee Administrator, I will be able to initiate and report a Repayment of an outstanding Debt Owed by Committee on a Form 3X report so that I can accurately report on my committee's transactions.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

  ***When*** I open the action kebab menu for an existing Schedule D "Debt Owed by Committee"

  ***And*** I click on the "Report debt repayment" option

  ***Then*** I will be able to initiate one of the following transactions that will link to the owed debt:

*   Operating Expenditure
*   Credit Card Payment for Operating Expenditure
*   Staff Reimbursement for Operating Expenditure
*   Payment to Payroll for Operating Expenditure
*   Transfers to Affiliates/Other Committees
*   Contribution to Candidate
*   In-kind Contribution to Candidate
*   Contribution to Other Committee
*   In-kind Contribution to Other Committee
*   Other Disbursements
*   Credit Card Payment for Other Disbursement
*   Staff Reimbursement for Other Disbursement
*   Payment to Payroll for Other Disbursement
*   Non-contribution Account Disbursement
*   Non-contribution Account Credit Card Payment
*   Non-contribution Account Staff Reimbursement
*   Non-contribution Account Payment to Payroll
*   Individual Refund - Non-contribution Account
*   Other Committee Refund - Non-contribution Account
*   Business/Labor Organization Refund - Non-contribution Account
*   Recount Account Disbursement
*   National Party Recount/Legal Proceedings Account Disbursement
*   National Party Headquarters Buildings Account Disbursement
*   National Party Pres. Nominating Convention Account Disbursement
*   Individual Refund - National Party Headquarters Buildings Account
*   Other Committee Refund - National Party Headquarters Buildings Account
*   Tribal Refund - National Party Headquarters Buildings Account
*   Individual Refund - National Party Pres. Nominating Convention Account
*   Other Committee Refund - National Party Pres. Nominating Convention Account
*   Tribal Refund - National Party Pres. Nominating Convention Account
*   Individual Refund - National Party Recount/Legal Proceedings Account
*   Other Committee Refund - National Party Recount/Legal Proceedings Account
*   Tribal Refund - National Party Recount/Legal Proceedings Account
*   Refund of Individual Contribution
*   Refund of Party Contribution
*   Refund of PAC Contribution
*   Refund of Unregistered Receipt from Person
*   100% Federal Election Activity Payment
*   Credit Card Payment for 100% Federal Election Activity
*   Staff Reimbursement for 100% Federal Election Activity
*   Payment to Payroll for 100% Federal Election Activity
*   Void of Operating Expenditure
*   Void of Contribution to Candidate
*   Void of Contribution to Other Committee
*   Void of Other Disbursement
*   Refund of Individual Contribution - Void
*   Refund of Party Contribution - Void
*   Refund of PAC Contribution - Void
*   Refund of Unregistered Receipt from Person - Void
*   Void of 100% Federal Election Activity

***And*** When I select a transaction

  ***Then*** A transaction screen will open for me to enter and save the details.

Wireframe

1.  Wireframe with Report debt repayment button
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTJZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--607d9aafb88f6e395af5dd608b0b45b832f8833b/1213%20-%20Allow%20user%20to%20report%20Repayment%20of%20Debt%20Owed%20by%20Committee%20-%20Table.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTJZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--607d9aafb88f6e395af5dd608b0b45b832f8833b/1213%20-%20Allow%20user%20to%20report%20Repayment%20of%20Debt%20Owed%20by%20Committee%20-%20Table.png))

1.  Transaction Selection
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbktZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--221162a9de958a824eab726c0632ea3596f7d355/1213%20-%20Allow%20user%20to%20report%20Repayment%20of%20Debt%20Owed%20by%20Committee%20-%20Expanded.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbktZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--221162a9de958a824eab726c0632ea3596f7d355/1213%20-%20Allow%20user%20to%20report%20Repayment%20of%20Debt%20Owed%20by%20Committee%20-%20Expanded.png))

1.  The type of report selected should have a tag stating it is a debt repayment on it
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbk9ZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3968f4780c75daf20d05e9a2695e45d295a02221/1213%20-%20Allow%20user%20to%20report%20Repayment%20of%20Debt%20Owed%20by%20Committee%20-%20Operating%20expenditure.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbk9ZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3968f4780c75daf20d05e9a2695e45d295a02221/1213%20-%20Allow%20user%20to%20report%20Repayment%20of%20Debt%20Owed%20by%20Committee%20-%20Operating%20expenditure.png))

1.  1168 Prototype
    [Private Zenhub Video]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2lZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--81912030ff56f6cbf82ff7f49e77574608d3b73a/1213%20-%20Allow%20user%20to%20report%20Repayment%20of%20Debt%20Owed%20by%20Committee%20-%20Proto.mp4](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2lZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--81912030ff56f6cbf82ff7f49e77574608d3b73a/1213%20-%20Allow%20user%20to%20report%20Repayment%20of%20Debt%20Owed%20by%20Committee%20-%20Proto.mp4))

### QA Notes ###
- The disbursement entry form should say "DEBT REPAYMENT" under the header per the wireframe.
- Users can still enter negatives if allowed on the debt repayment transaction, which would result in an _increased_ balance. (Confirmed with Ryan and Marlene 8/10/23)

### DEV Notes ###
- Debt repayments are tied to the Schedule D debt with the back reference ID.

### Design ###
null

 See full ticket and images here: [FECFILE-703](https://fecgov.atlassian.net/browse/FECFILE-703)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
wires added

It's you call if this process need a debt repayment table. (feel free to add to a future ticket or remove all together)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
UX Review complete

**Comment by GreggMoreland** [comment]
@toddlees BA Review complete

**Comment by mjtravers** [comment]
From CR: Let's add the transaction ids to the transaction tables so we can track which repayments to to which debts. Sending back to In Progress

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review noticed wording is missing under "Report debt repayment"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWZGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0f173734fc0580223bd7b8b56b711144492dd6e6/image.png)

@mjtravers @toddlees add verbiage below the "Report debt repayment" as denoted in wireframe.  (See below screenshot) of what needs to be there.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVhGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--18dcb3ded30a58d99bdc17a64b97ee31e8aabb83/image.png)

@toddlees update comments in ticket when fixed.

**Comment by toddlees** [comment]
Patch to add description under Report debt repayment title and add spacing: Merged

**Comment by WiseQA** [comment]
QA review verified when selecting the Actions dropdown for a Debt Owed by Committee "Report debt repayment" is displayed and selectable.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblBNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4916b625675ac5e19cc1a050e4eb084b4d943a6e/image.png)

Verified Report debt repayment page is displayed with Accordion drops downs for Schedule B (Disbursements)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbm5NIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bd43417d94cd629acb3637b9803109cfa1b951f4/image.png)

Verified verbiage below Report debt repayment was added per fix.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnJNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3b13bc1e4194efc13a229bc513cc1eb1e1d9646e/image.png)

Select Disbursement transaction from accordion dropdown (tested with Operating Expenditure), verify "DEBT REPAYMENT" verbiage is below transaction name.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0RNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4824625f9a05fee3ce3e5550675a5d35a3a8c394/image.png)

Verified transaction is created and displayed in the transactions table under Disbursments.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1BNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4a6103aac28ac01d51b7b3bebe945f991b200510/image.png)

QA Review Completed.   Moved to Stage Ready.
