### ISSUE TITLE
Update stack reference in manifest file for Cloud.gov

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1216]
Cloud.gov is depreciating the cflinuxfs3 stack to cflinuxfs4.

As a result we need to update our manifest files to reference cflinuxfs4 and verify the site still works with the upgrade.

**DEV NOTES**
See article: https://cloud.gov/2023/03/28/cflinuxfs3-deprecation/#timeline

**QA NOTES**
Passes if automated tests run without error

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
**Additional DEV notes:**
The nginx_buildpack provided by cloud.gov is deploying nginx 1.25.0 which is not able to validate our nginx.conf file causing it to fail. For now, we are pulling the nginx_build pack from github which is using nginx 1.25.1 which is able to use our nginx.conf file. We will convert to the Cloud.gov buildpack after they upgrade to nginx 1.25.1

Also, the command to update the Cloud.gov stack from cflinuxfs3 to cflinuxfs4 is:
`cf push MY-APP -s cflinuxfs4`

See here for details: https://cloud.gov/2023/05/16/cflinuxfs3-buildpack-deprecation/

**Comment by mjtravers** [comment]
**For QA:**
Passing automated tests: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/3274/workflows/36443daf-52d2-41dd-81be-253d43d6bfa0/jobs/12032

Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified visual inspection with DEV that from automated testing that this test passed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d3698e0b-97e1-40ee-9bfc-cc3de3e2248f)

QA Review Completed.   Moved to Stage Ready.
