### ISSUE TITLE
Make transaction component headers "Sentence case"

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1217]
Business Reason

As the FEC UX Stakeholder , I will like all transaction component Headers with two or more words to be "Sentence case." so the application more closely follows the typographical style of FEC.gov

Task

Make any two word or longer transaction component header Sentence case, .e.g. The first word is capitalized and ALL subsequent words start with a lower case letter.

  ***[This will impact components in Schedule A, B, and C]***

***Please update the following headers on Single and multi-transaction page, i.e. Earmark or In-kind:***

*   [x] Receipt information
*   [x] Expenditure information
*   [x] Election information
*   [x] Additional information
*   [x] Loan information
*   [x] Candidate/Committee information

Dev Notes

### QA Notes ###
 Wireframes
![Custom Size – 39.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/3e2b404d-d4f4-44ab-a4c9-3ec3615033fc)
![Custom Size – 40.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/af121cf9-bbdc-45e7-bd03-4f47568193e8)
![Custom Size – 41.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f3499be2-854f-4198-a034-19ae7b1f1bba)
![Custom Size – 42.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/3b7b2175-9205-4bc1-a483-0a146ad21e9d)
![Custom Size – 43.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4686e7cb-cb84-4379-8438-0806b3454f63)
![Custom Size – 44.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/2f418d6b-f33e-433c-956d-dadded68ecbe)
![Custom Size – 45.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/5b5cb06f-e9d6-4d4a-b8a5-e8bab27838ba)
![Custom Size – 46.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/9ea142ee-9ee2-4260-ba8a-f221788898ef)
![Custom Size – 47.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/34aeae4f-228d-451a-b932-3ca35db23fb0)
![Custom Size – 48.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/614561ce-e54c-4fe9-acbf-5ec945fc1020)
![Custom Size – 49.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/21ff36e6-fc66-492b-a137-e65ec4f35657)
![Custom Size – 50.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/96bc28f8-dd36-4371-ad3d-2f096bad7a7b)
![Custom Size – 52.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a9e0b108-9dee-474b-a784-65e55ad5afdf)
![Custom Size – 54.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d79a16f9-477c-483a-897d-39b044c6de16)
![Custom Size – 55.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/cf0ff010-b049-4f7d-bf18-85371d000b68)

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-701](https://fecgov.atlassian.net/browse/FECFILE-701)

**Comment by MitchellTCG** [comment]
@toddlees 
Please review this ticket and add any Dev Notes needed

thank you

**Comment by toddlees** [comment]
Very clear! no dev notes needed

**Comment by mjtravers** [comment]
Looks good

**Comment by toddlees** [comment]
@MitchellTCG The following headers are not implemented yet and could not be updated:
Debt or obligation information 
Others liable 
Future income 
Basis of loan 
Committee treasurer 
Authorized representative 
Guaranteed financial information

**Comment by toddlees** [comment]
@MitchellTCG 
updated report submission page 2 to be sentence case:
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/239d5f26-0166-464b-8b7e-142c441a7069)
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/a60c5413-487a-4d97-9751-fa6d367092d5)

**Comment by toddlees** [comment]
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/e256a5ae-ef9b-45d2-8a84-168ca8616812)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the following transaction component headers are "Sentence case".   The first word is capitalized and ALL subsequent words start with a lower case letter.

- [x] Receipt information
- [x] Expenditure information
- [x] Election information
- [x] Additional information
- [x] Loan information
- [x] Candidate/Committee information

QA Review Completed.   Moved to Stage Ready.
