### ISSUE TITLE
Create Angular model for Schedule D

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1218]
Following the same pattern as was created for the Schedule A and Schedule B, create a Schedule D class to manage the data for a Schedule D record.

DEV Tasks:

*   [x] Create a SchDTransaction class that extends the Transaction class
*   [x] Create a ScheduleDTransactionGroups enum containing groupings for the "Add transacation" expand/collapse page
*   [x] Create a ScheduleDTransactionsGroupsType type
*   [x] Create a ScheduleDTransactionTypes enum containing the transaction unique identifiers
*   [x] Create a ScheduleDTransactionTypeLabels LabelList containing the UI title for each transaction type
*   [x] Update the ScheduleTransaction, TransactionTypes, and TransactionGroupTypes type definitions in the transactions.model.ts file

### QA Notes ###

There will be a unit test that can be reviewed verifying the correctness of the Schedule D model code. A screenshot can be provided.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-700](https://fecgov.atlassian.net/browse/FECFILE-700)

**Comment by mjtravers** [comment]
Unit test report (https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/2179/workflows/140e9d62-11d0-479a-aceb-e5246045f81e/jobs/6933):
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/63f48861-0823-4d2e-9d84-04f4ff20d381)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of code passing as denoted in app.circleci per DEV.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/20f116d6-510d-4660-87d2-0d6921442e81)

QA Review Completed. Moved to Stage Ready,
