### ISSUE TITLE
Clicking on link to homepage shouldn't go to fec.gov

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#122]
### Business Reason ### 

As a FECFile user, I will be able to click on the homepage link so that I can go back to the home page. 

### Acceptance Criteria ### 

**If** I am a FECfile user,
**When** I click on the Federal Elections Commission logo/text
**Then** the system should return me to the FECfile Online Homepage within the same browser tab

**Dev Note:** More information on this design pattern here: https://www.nngroup.com/articles/homepage-links/ Currently, clicking on the link to homepage opens a new tab and goes to fec.gov.

<img width="657" alt="Screen Shot 2022-02-15 at 10 18 57 AM" src="https://user-images.githubusercontent.com/31420082/154093261-ea4a5e19-687f-4f40-b2f9-e2c942528af6.png">

**Comment by MitchellTCG** [comment]
I see this was assign and then deprioritize. 
@AureliaKhorsand Is this OBE

**Comment by AureliaKhorsand** [comment]
@MitchellTCG Not to my knowledge - I'm not sure why it was sent back. It should still get done at some point.

**Comment by Elaine-Krauss-TCG** [comment]
We no longer have any sort of link in the navbar that might fit this description.  I think this ticket is OBE?

**Comment by WiseQA** [comment]
@Elaine-Krauss-TCG agree with you this ticket should be OBE ?  @MitchellTCG

**Comment by AureliaKhorsand** [comment]
Marking as OBE since the left navigation redesign removed this link. We will look into the logo and homepage link at a later time.
