### ISSUE TITLE
Defect - Functionality is broken for - System to prevent user from having multiple reports of the same type within calendar year. 

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1221]
This defect is being written to where functionality is broken for: "The System to prevent user from having multiple reports of same type within calendar year". (Tested on both Stage and DEV environments.) This functionality was developed in Sprint 23 ticket #361 to where this functionality was working and passed.

[https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/361](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/361)

This defect was found in Sprint 28 during e2e testing.

Below are screenshots to show when selecting create a new report and existing report within same calendar year can be selected, added and saved.

Existing report:

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/312ccaba-8f03-4cc5-a83e-07cd0bd43a87](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/312ccaba-8f03-4cc5-a83e-07cd0bd43a87))

Created new report April 15 Quarterly Report (Q1) selectable and able to create and save same report and same calendar year.

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b2f94916-34cb-4ac3-8fc2-f43794f034cf](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b2f94916-34cb-4ac3-8fc2-f43794f034cf))

Per @MitchellTCG @mjtravers assigned to Sprint 28 pointed at 3 points for fix.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-699](https://fecgov.atlassian.net/browse/FECFILE-699)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Below when selecting create a new report and existing report within same calendar year cannot be selected, added and saved.

Existing Report:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c9aaa8ba-8142-4da2-bd07-4895fc2c7103)

Unable to select an existing report in the same calendar year.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a58d69e1-94f1-4358-89b2-8fdf34529124)

QA Review Completed.   Moved to Stage Ready.
