### ISSUE TITLE
Verbiage below the "Conduit Earmark Out" disbursement name needs to be removed.  

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1222]
During testing when entering a two-step for the conduit earmark receipt and creating a conduit earmark out disbursement, the verbiage below the "Conduit Earmark Out" transaction name needs to be removed.  

**"To update any errors found, return to the previous step to update the in-kind receipt."**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bd715d83-f3a7-4edd-a7c4-0da9b74a2810)

Reference ticket #745 Wireframe:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2005b6fc-8e4e-426c-a01b-42395c5e9584)

Bug found in Sprint 28.

@MitchellTCG @mjtravers remove verbiage below the Conduit Earmark Out disbursement name.  Bug fix pointed as a 1 point bug fix.  (NOTE:  Change is being done in ticket #1193 ticket, once it is completed both will be moved together)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified incorrect verbiage below the "Conduit Earmark Out" (Step Two) disbursement was removed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e124f47f-6786-43d4-82b7-987485fa4297)

QA Review Completed.  Moved to Stage Ready.
