### ISSUE TITLE
Allow user to force (un)itemize ONLY Tier 1 transactions

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1223]
Business Reason

As a user, I will be able to force itemize and unitemize only on Tier 1 transactions so that I can accurately report on my committee transactions.

Acceptance Criteria

***Given*** an existing ***Tier 1*** transaction in the Transactions table of a report

  ***When*** the user selects the action menu for that transaction,

  ***Then*** they will see an option to manually "itemize" or "unitemize" that transaction.

  ***And*** these options will NOT be available on any Tier 2 or Tier 3 transactions.

### QA Notes ###
- Functionality to manually itemize/unitemize completed in #591. This ticket is to ensure that these options _only_ appear for Tier 1 transactions from now on.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-697](https://fecgov.atlassian.net/browse/FECFILE-697)

**Comment by AureliaKhorsand** [comment]
@GreggMoreland please peer review and move to ADQTR when ready. Thanks!

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA question should loans / debts be itemized / unitemized?  Verified with @GreggMoreland @AureliaKhorsand that every tier 1 transaction should have the Itemize/Unitemize function, including loans (Schedule C).

**Comment by WiseQA** [comment]
QA review verified Tier 1 transactions for Receipts (Schedule A), Disbursements (Schedule B), Loans and Debts (Schedule C) Actions dropdown menu has the option to change transaction from Itemize > Unitemized and Unitemized > Itemize

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVZTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--38c3a8ea82403685cd070748f0ceeabc8b3cc87f/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWRTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9164cb8478d124bd5a9e34537bc4460088f415fe/image.png)

Transaction is updated displayed correctly in transaction table once Itemized and/or Unitemized is selected.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWxTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c7564d5d49f3a5182c5472d3bc6fd863077f7070/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXBTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--caeedc700dcefaae539bfd469f2a02ad1db5f06a/image.png)

Verified "Heads up!" popup window is displayed (reference ticket #804)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTlTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b917a212a80027f578376473b88bf88ba05cf650/image.png)

QA Review Completed.   Moved to Stage Ready.
