### ISSUE TITLE
Create Angular model for Schedule E

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1225]
Following the same pattern as was created for the Schedule A and Schedule B, create a Schedule E class to manage the data for a Schedule E record.

DEV Tasks:

*   Create a SchETransaction class that extends the Transaction class
*   Create a ScheduleETransactionGroups enum containing groupings for the "Add transacation" expand/collapse page
*   Create a ScheduleETransactionsGroupsType type
*   Create a ScheduleETransactionTypes enum containing the transaction unique identifiers
*   Create a ScheduleETransactionTypeLabels LabelList containing the UI title for each transaction type
*   Update the ScheduleTransaction, TransactionTypes, and TransactionGroupTypes type definitions in the transactions.model.ts file

### QA Notes ###

There will be a unit test that can be reviewed verifying the correctness of the Schedule E model code. A screenshot can be provided.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-696](https://fecgov.atlassian.net/browse/FECFILE-696)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

QA Notes: Automated test report can be viewed here: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/3448/workflows/45ce2ad6-7990-4115-81e0-b81143f706a2/jobs/12577
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/caf1bf9d-2300-4eb4-8b87-66de026ad072)

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of code passing as denoted in app.circleci per DEV.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ffe83db2-cde0-47fe-bd02-001ea108937c)

QA Review Completed. Moved to Stage Ready,
