### ISSUE TITLE
Allow user to report Repayment of Debt Owed by Committee with Schedule E transactions

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1230]
Business Reason

As a Committee Administrator, I will be able to initiate and report a Repayment of an outstanding Debt Owed by Committee on a Form 3X report so that I can accurately report on my committee's transactions.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

  ***When*** I open an existing Schedule D "Debt Owed by Committee"

  ***Then*** The following Line 24 transactions (form type SE) are added to the list of transactions that will link to the owed debt:

*   Independent Expenditure
*   Independent Expenditure - Void
*   Multistate Independent Expenditure
*   Credit Card Payment for Independent Expenditure
*   Staff Reimbursement for Independent Expenditure
*   Payment to Payroll for Independent Expenditure

### QA Notes ###
- [x] BA/Design Quality Checklist complete
- This will add to the list of transactions that were added in #1213

### DEV Notes ###
- This will add to the list of transactions that were added in #1213

### Design ###
null

 See full ticket and images here: [FECFILE-692](https://fecgov.atlassian.net/browse/FECFILE-692)

**Comment by mjtravers** [comment]
@dheitzer See PR for question about the naming of the identifier used for the annotation.
Sending ticket back to In Progress.

**Comment by mjtravers** [comment]
@GreggMoreland @dheitzer I see "Independent Expenditure -Void" in the list but not in the AC of the ticket. Should it be there?

<img width="326" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTBMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e81c7281841d8403934a19abd2618f4a57683297/image.png" alt="image.png" />


Sending back to In Progress

**Comment by GreggMoreland** [comment]
@mjtravers @dheitzer That was missed (and now updated) in AC.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
**QA review tested using Login.gov and Test Committee ID C00100495 assigned to QA for testing.** 

Create a "Debit Owed By Committee" for the Loans and Debts transactions.  Then from the "Actions" Kabob select "Report dept repayment"

<img width="1437" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG9RQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56e57a14bee3e89235661e8a7f20235ff14c2f29/image.png" alt="image.png" />

__________________________________________________________________________________________________________

Verified Report debt repayment page is displayed.

<img width="858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDhRQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4329854c6feac7d1aeac3aee18bcc891c9b31d69/image.png" alt="image.png" />

______________________________________________________________________________________________________________________

Select "Independent Expenditures" accordion dropdown.   Verify Schedule E transactions are displayed correctly.

<img width="787" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUlRQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4ba36597b9d77098e21955c86737acf51d3eecf/image.png" alt="image.png" />

_______________________________________________________________________________________________________________

QA Review Completed.  Verified Functionality of this Ticket.   Moved to Stage Ready.
