### ISSUE TITLE
Allow user to enter Credit Card Memo for Independent Expenditure on Schedule E

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1238]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Credit Card Memo for Independent Expenditure"** sub-transaction under **"Credit Card Payment for Independent Expenditure"** on Schedule E of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Credit Card Payment for Independent Expenditure transaction on an open report
**Then** I will have the option to enter the following sub-transaction:
- Credit Card Memo for Independent Expenditure
**And** I will be required to enter the following information (unless otherwise noted):

 Payee 
#
-	**LOOKUP**
Dropdown options: Organization, Individual
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure information 
#
-	**DISSEMINATION DATE** (At least one date is required. If one is entered, the other is optional)
-	**DISBURSEMENT DATE** (At least one date is required. If one is entered, the other is optional)
-	**MEMO ITEM** (Required)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**CALENDAR YEAR-TO-DATE** (Required, system generated)
-- Amount Displayed will be copied from the Tier 1 **"Credit Card Payment for Independent Expenditure"** transaction

# Candidate information 
#
-	**SUPPORT/OPPOSE CODE** (Required, values Support, Oppose)
**And** the user will be required to select a Candidate using the LOOKUP, and upon selection the following will be populated:

-	**CANDIDATE ID** (Optional)
- 	**CANDIDATE  LAST NAME** (Required)
-	**CANDIDATE FIRST NAME** (Required)
-	**CANDIDATE MIDDLE NAME** (Optional)
-	**CANDIDATE PREFIX** (Optional)
-	**CANDIDATE SUFFIX** (Optional)

-	**CANDIDATE OFFICE** (Required)
-	**CANDIDATE STATE** (Required if (CANDIDATE OFFICE is 'House' or 'Senate') or If (CANDIDATE OFFICE  = President and the Election Code = P-Primary))
-	**CANDIDATE DISTRICT** (Required if CANDIDATE OFFICE is 'House')

# Election information 
#
-	**ELECTION CODE** (Required)
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Other)

# Additional information 
#
-	**PURPOSE OF EXPENDITURE** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

#  Committee treasurer 
#
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

-	**DATE SIGNED** (Required)

---
**Then** I will be able to:
- Save & add memo (Memo Name: Credit Card Memo for Independent Expenditure)
- Cancel
- Save 

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SE.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 Dev Note 

- Front-end field for "treasurer" maps to "COMPLETING" name on specification spreadsheet
- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/15hqrgTeto1hp7i_9-jd719kTM9UNjN6qUPq-xOlJOco/edit#gid=575880970) **This is a consolidated specification**

 Wireframes 

Candidate section collapsed before selection
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaERvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--37f607191b903a48df3b89ee601b41305ec256c3/1238%20-%20Allow%20user%20to%20enter%20Credit%20Card%20Memo%20for%20Independent%20Expenditure%20on%20Schedule%20E%20%E2%80%93%202.png)

Candidate section expanded after selection
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWZoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4d4371292c0647726189f10ce27c73c284bf73f4/1238%20-%20Allow%20user%20to%20enter%20Credit%20Card%20Memo%20for%20Independent%20Expenditure%20on%20Schedule%20E%20%E2%80%93%201.png)

Memo button with dropdown
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGJpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--81d9cd9c3271e4ed0858ed9b5054e0a13a3cec8d/1238%20-%20Allow%20user%20to%20enter%20Credit%20Card%20Memo%20for%20Independent%20Expenditure%20on%20Schedule%20E%20%E2%80%93%20dropdown.png)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 - [x] BA/Design Quality Checklist complete
- The "Calendar Y-T-D" aggregate will be copied from the Tier 1 transaction and not calculated. The ENTITY aggregate, which determines itemization, is the total of transactions:
--- From the person (ENTITY) 
--- within Aggregation Group of "INDEPENDENT_EXPENDITURE"
--- _from_ January 1 of report year _to_ the Disbursement Date of the transaction. 
--- (**IF** Disbursement Date is not entered, then use Dissemination Date of the transaction.)

**Comment by mary-tcg** [comment]
@GreggMoreland @AureliaKhorsand @MitchellTCG wire uploaded

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Defect #1456 fixed.  On-hold removed.

**Comment by WiseQA** [comment]
Defect #1456 fixed. On-hold removed.

**Comment by WiseQA** [comment]
Prerequisite Credit Card Payment for Independent Expenditure (Disbursement) transactions created and saved.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU43QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--179c24f866d228425cfad516f728bd440271acfe/image.png)

**Comment by WiseQA** [comment]
QA review the dropdown for the Save and add memo has name of memo twice.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2w3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--415443b474e3005d04d271e9e8f58d3d40569748/image.png)

Should be one name only in dropdown (see wireframe)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3A3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d5969c0d5b8dec0374b4bb3841cb863719a6858/image.png)

@toddlees @MitchellTCG - Todd pushing patch to fix dropdown.

**Comment by toddlees** [comment]
patch do address above comment on dropdowns:
https://github.com/fecgov/fecfile-web-app/pull/1469

**Comment by WiseQA** [comment]
QA review verified fix for the dropdown for +Save & add memo has one memo transaction name only in dropdown (see wireframe) was fixed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTk4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c69658c0b52303ce781ee0fbdd03e433dbc5fdc/image.png)

**Comment by WiseQA** [comment]
Prerequisite Credit Card Payment for Independent Expenditure (Disbursement) transactions created and saved.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU43QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--179c24f866d228425cfad516f728bd440271acfe/image.png)

Select +Save & add memo dropdown and select memo.   

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMng4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ec73998caf763f78ce860ebcde02a3f84630d52/image.png)

Verify Credit Card Memo for Independent Expenditure page is displayed and defaulted to Organization.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjU4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9fdb374e680c31e6aa160fc9564520c07dd4867d/image.png)

Memo Item (awaiting clarification @MitchellTCG @GreggMoreland - AC / Wireframes are different ?

AC has memo item required - wireframe frames have checkbox - memo item (Optional).   Transaction has check box selected as default for memo item.

Below is what is displaying in Memo transactions, which assuming this is correct for Schedule E memo's?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGg4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3cf86005bfc9f162a356bf0dc95b2143f0dda5fb/image.png)

**Comment by GreggMoreland** [comment]
@MitchellTCG I missed it in my review, but since this is a memo transaction, then MEMO is required and not optional.

@WiseQA AC is correct here

**Comment by WiseQA** [comment]
QA review verified Memo Item checkbox is selected (as this is required field) per comments above.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzk4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fbcf5f769a12a643802b4c02e3070600bd223715/image.png)

Verified Credit Card Memo for Independent Expenditure is created and saved in the "Transactions in this report" under Disbursements 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd045QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--499381673ae6e681ad8a19ab59dc70ae73d8e67c/image.png)

QA Review Completed.   Moved to Stage Ready.
