### ISSUE TITLE
Allow user to enter Staff Reimbursement for Independent Expenditure on Schedule E

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1239]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Staff Reimbursement for Independent Expenditure"** transaction on Schedule E of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** go to Add a disbursement
**Then** I can enter a transaction with the type "Staff Reimbursement for Independent Expenditures" under the "Independent Expenditures" Accordion link  
**Then** I will be required to enter the following information (unless otherwise noted):

 Payee 
#
-	**LOOKUP**
-Individual

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure information 
#
-	**DISSEMINATION DATE** (At least one date is required. If one is entered, the other is optional)
-	**DISBURSEMENT DATE** (At least one date is required. If one is entered, the other is optional)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**CALENDAR YEAR-TO-DATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- For the selected ELECTION CODE/ELECTION YEAR and Candidate selected
--- within Aggregation Group of "INDEPENDENT_EXPENDITURE"
--- _from_ January 1 of report year _to_ the Disbursement Date* of the transaction. 
--- (**IF** Disbursement Date is not entered, then use Dissemination Date of the transaction- 

# Candidate information 
#
-	**SUPPORT/OPPOSE CODE** (Required, values Support, Oppose)
**And** the user will be required to select a Candidate using the LOOKUP, and upon selection the following will be populated:

-	**CANDIDATE ID** (Optional)
- 	**CANDIDATE  LAST NAME** (Required)
-	**CANDIDATE FIRST NAME** (Required)
-	**CANDIDATE MIDDLE NAME** (Optional)
-	**CANDIDATE PREFIX** (Optional)
-	**CANDIDATE SUFFIX** (Optional)

-	**CANDIDATE OFFICE** (Required)
-	**CANDIDATE STATE** (Required if (CANDIDATE OFFICE is 'House' or 'Senate') or If (CANDIDATE OFFICE  = President and the Election Code = P-Primary))
-	**CANDIDATE DISTRICT** (Required if CANDIDATE OFFICE is 'House')

# Election information 
#
-	**ELECTION CODE** (Required)
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Other)

# Additional information 
#
-	**PURPOSE OF EXPENDITURE** (Required, System Generated)
--Text must read: "Reimbursement: See Below"
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

#  Committee treasurer 
#
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

-	**DATE SIGNED** (Required)

---
**Then** I will be able to:
- Save & add memo (Memo Name: Staff Reimbursement Memo for Independent Expenditure)
- Cancel
- Save 
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SE.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 Dev Note 

- Front-end field for "treasurer" maps to "COMPLETING" name on specification spreadsheet
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/15hqrgTeto1hp7i_9-jd719kTM9UNjN6qUPq-xOlJOco/edit#gid=1786117945) **This is a consolidated specification**

 Wireframes 

Candidate section before selection
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEkwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a749f62ecec9dcfccdda7834028a95b7da3831d/1236%20-%20Allow%20user%20to%20enter%20Staff%20Reimbursement%20for%20Independent%20Expenditure%20on%20Schedule%20E%20%E2%80%93%202.png)

Candidate section after selection
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE0wQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ff5740ffc5da6a1c08cea04d24c5f99ea676f8c/Screenshot%202023-10-13%20at%2010.49.19%20AM.png)

Button with dropdown
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGZpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b74bca58a3d5191d0a41d1c6098d18bed84f5ab2/1239%20-%20Allow%20user%20to%20enter%20Staff%20Reimbursement%20for%20Independent%20Expenditure%20on%20Schedule%20E%20dropdown.png)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 - [x] BA/Design Quality Checklist complete
- There are two aggregates calculated on the back end. There is the aggregate that populates "Calendar Y-T-D" on the front-end, and the ENTITY aggregate, which determines itemization. This aggregate is the total of transactions:
--- From the person (ENTITY) 
--- within Aggregation Group of "INDEPENDENT_EXPENDITURE"
--- _from_ January 1 of report year _to_ the Disbursement Date of the transaction. 
--- (**IF** Disbursement Date is not entered, then use Dissemination Date of the transaction.)

**Comment by mary-tcg** [comment]
@GreggMoreland @AureliaKhorsand @MitchellTCG wire uploaded

**Comment by Elaine-Krauss-TCG** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjhUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e6a6ec2e5f797c3229dbafe7df9c68a784a35f6/image.png)

**Comment by Elaine-Krauss-TCG** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1VlQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f032e0ee67e691dd77e23402dd573b1f0afc1954/image.png)

**Comment by Elaine-Krauss-TCG** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1llQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93becc3b32fcdce0e257f0a40c13888189418ec6/image.png)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then under "Independent Expenditures" select "Staff Reimbursement for Independent Expenditure" transaction page is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUEwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a27a8e1a91f86d2e596333b5eda80ec51444f2b/image.png)

Verified LOOKUP is defaulted to Individual.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUUwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea76ed0dc6a2f2764c1a10cdb6adbb7cc1df0cf3/image.png)

Verified entering Dissemination Date outside report coverage dates the "Just checking ... " popup window is displayed. Memo Item becomes a required field.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2N6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe8ecf559f73915d5b6447eaf6fb2f9d55960860/image.png)

Verified entering Disbursement Date outside report coverage dates the "Just checking ... " popup window is displayed. Memo Item becomes a required field.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK296QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22f21faafadcb2c9cdbadde265cda2cfe2a989db/image.png)

Verified error message displayed "At least ONE date field must be entered"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3d6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--700b761f76417158322793b2f3a992fada4cffb7/image.png)

Verified Candidate information error message displayed "An answer is required"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1F6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1016e30f1c7d4f9c2b89a7153196cf68fcecc958/image.png)

Verified once selected "Support" and/or "Oppose" the LOOKUP for Candidate is displayed and error message displayed "Candidate information is required"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd28wQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab1181e58402a72a3b7bbe74c4e0b4fb303a9548/image.png)

Verified PURPOSE OF EXPENDITURE (SYSTEM-GENERATED) field populated with "Reimbursement:  See Below"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVUwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34c5eea399bb5357a85012e3e64b0e03768f0019/image.png)

Verified after selecting the +Save & add memo button the "Staff Reimbursement Memo For Independent Expenditure"  is displayed in the dropdown menu.   (NOTE:  Link a dead link in this ticket)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW8wQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2314d0434e55b2b19e09d310b2e5882a7af7838b/image.png)

QA review verified transaction is displayed in the transactions table.   The Disbursement Date field will be populated in the date column of the transactions table only at this point. (NOTE: Future clarification with FEC to determine if the Dissemination Date field will populate in the date field if Disbursement date is NOT filled in in the transaction)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXcwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94646fc5e99803f63e3a2cc2f6dd92d40123b8a5/image.png)

QA Review Completed.   Moved to Stage Ready.

**Comment by WiseQA** [comment]
Ticket placed on-hold as a DEFECT #1456 was found during Sprint 32 demo.   DEFECT #1456 PASSES.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEozQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf0fb8e73e27e097e7c514f51649240e53d5d394/image.png)

@MitchellTCG IE Transactions have been retested and validated as Passing for Sprint 32.  Removed on-hold and closed.
