### ISSUE TITLE
Allow user to enter Payroll Memo for Independent Expenditure on Schedule E

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1242]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Payroll Memo for Independent Expenditure"** sub-transaction under **"Payment to Payroll for Independent Expenditure"** on Schedule E of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Payment to Payroll for Independent Expenditure transaction on an open report
**Then** I will have the option to enter the following sub-transaction:
- Payroll Memo for Independent Expenditure
**And** I will be required to enter the following information (unless otherwise noted):

 Payee 
#
-	**LOOKUP**
Dropdown options: Organization, Individual
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure information 
#
-	**DISSEMINATION DATE** (At least one date is required. If one is entered, the other is optional)
-	**DISBURSEMENT DATE** (At least one date is required. If one is entered, the other is optional)
-	**MEMO ITEM** (Required)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**CALENDAR YEAR-TO-DATE** (Required, system generated)
-- Amount Displayed will be copied from the Tier 1 **"Payment to Payroll for Independent Expenditure"** transaction
.

# Candidate information 
#
-	**SUPPORT/OPPOSE CODE** (Required, values Support, Oppose)
**And** the user will be required to select a Candidate using the LOOKUP, and upon selection the following will be populated:

-	**CANDIDATE ID** (Optional)
- 	**CANDIDATE  LAST NAME** (Required)
-	**CANDIDATE FIRST NAME** (Required)
-	**CANDIDATE MIDDLE NAME** (Optional)
-	**CANDIDATE PREFIX** (Optional)
-	**CANDIDATE SUFFIX** (Optional)

-	**CANDIDATE OFFICE** (Required)
-	**CANDIDATE STATE** (Required if (CANDIDATE OFFICE is 'House' or 'Senate') or If (CANDIDATE OFFICE  = President and the Election Code = P-Primary))
-	**CANDIDATE DISTRICT** (Required if CANDIDATE OFFICE is 'House')

# Election information 
#
-	**ELECTION CODE** (Required)
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Other)

# Additional information 
#
-	**PURPOSE OF EXPENDITURE** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

#  Committee treasurer 
#
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

---
**Then** I will be able to:
- Save & add memo (Memo Name: Payroll Memo for Independent Expenditure)
- Cancel
- Save 

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SE.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 Dev Note 

- Front-end field for "treasurer" maps to "COMPLETING" name on specification spreadsheet
- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/15hqrgTeto1hp7i_9-jd719kTM9UNjN6qUPq-xOlJOco/edit#gid=575880970) **This is a consolidated specification**

 Wireframes 

Candidate section before selection
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaExvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e02f15de62a392a5059fd1f8fc12592f549c7a21/1242%20-%20Allow%20user%20to%20enter%20Payment%20to%20Payroll%20Memo%20for%20Independent%20Expenditure%20on%20Schedule%20E%20%E2%80%93%204.png)

Candidate section after selection
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXZoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e75b1ae54ba566ffdaf2ed4350bfa6dce2c1d4d8/1242%20-%20Allow%20user%20to%20enter%20Payment%20to%20Payroll%20Memo%20for%20Independent%20Expenditure%20on%20Schedule%20E%20%E2%80%93%203.png)

Memo button with dropdown
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHppIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--599769824fa08f97dda559def4fd0497c7832c9c/1242%20-%20Allow%20user%20to%20enter%20Payment%20to%20Payroll%20Memo%20for%20Independent%20Expenditure%20on%20Schedule%20E%20%E2%80%93%20dropdown.png)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 - [x] BA/Design Quality Checklist complete
- The "Calendar Y-T-D" aggregate will be copied from the Tier 1 transaction and not calculated. The ENTITY aggregate, which determines itemization, is the total of transactions:
--- From the person (ENTITY) 
--- within Aggregation Group of "INDEPENDENT_EXPENDITURE"
--- _from_ January 1 of report year _to_ the Disbursement Date of the transaction. 
--- (**IF** Disbursement Date is not entered, then use Dissemination Date of the transaction.)

**Comment by mary-tcg** [comment]
@GreggMoreland @AureliaKhorsand @MitchellTCG wire uploaded

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Defect #1456 fixed. On-hold removed.

**Comment by WiseQA** [comment]
QA review the dropdown for the Save and add memo has name of memo twice.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1Y3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a606de18c379e650b41250da36466b07170b1836/image.png)

Should be one name only in dropdown (see wireframe)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0o3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--855250f8ae450bcf6a43a192515bb0c030097c84/image.png)

@toddlees @MitchellTCG - Todd pushing patch to fix dropdown.

**Comment by toddlees** [comment]
patch do address above comment on dropdowns:
https://github.com/fecgov/fecfile-web-app/pull/1469

**Comment by WiseQA** [comment]
QA review verified fix for the dropdown for +Save & add memo has one memo transaction name only in dropdown (see wireframe) was fixed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlY4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15182cb32fdccf0631379fa7849a4bb2f173a1d1/image.png)

**Comment by WiseQA** [comment]
Memo Item (awaiting clarification @MitchellTCG @GreggMoreland - AC / Wireframes are different ?

AC has memo item required - wireframe frames have checkbox - memo item (Optional).   Transaction has check box selected as default for memo item.

Below is what is displaying in Memo transactions, which assuming this is correct for Schedule E memo's?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGg4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3cf86005bfc9f162a356bf0dc95b2143f0dda5fb/image.png)

**Comment by GreggMoreland** [comment]
@MitchellTCG I missed it in my review, but since this is a memo transaction, then MEMO is required and not optional.

@WiseQA AC is correct here

**Comment by WiseQA** [comment]
QA review verified Memo Item checkbox is selected (as this is required field) per comments above.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2Q5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3dcf3f6b9ff16b132202f570c680b0fdbe48ac68/image.png)

**Comment by WiseQA** [comment]
Prerequisite Payment to Payroll for Independent Expenditure (Disbursement) transactions created and saved.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGQ5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6526157c3c0f792a146fef669af2df0cf2334961/image.png)

Select +Save & add memo dropdown and select memo.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHQ5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b43e82426f93cf521454317f41dff7d12e0f7aa/image.png)

Verify Payroll Memo for Independent Expenditure page is displayed and defaulted to Organization.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDE5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c8ddbcc88771bea6e5c96741e6af43f2d960655/image.png)

Verified Payroll Memo for Independent Expenditure is created and saved in the "Transactions in this report" under Disbursements

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWw5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24d60a85b1f7ffecd1539c2d0871c1d3373da205/image.png)

QA Review Completed.   Moved to Stage Ready.
