### ISSUE TITLE
Memo Item Checkbox the verbiage (Optional) is missing if date range is within the report period for Schedule B transactions

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1251]
During testing the Memo Item Checkbox verbiage (Optional) is missing when entering a Disbursement (Schedule B) transaction form with a date range within the report period. (tested on both STAGE and DEV environments). Found in Sprint 25.

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/677ad2d6-865e-464c-b060-b6bb4e4c1e50](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/677ad2d6-865e-464c-b060-b6bb4e4c1e50))

Schedule B - That are optional upon initial load

*   [x] Operating Expenditure
*   [x] Credit Card Payment for Operating Expenditure
*   [ ] Staff Reimbursement for Operating Expenditure
*   [ ] Payment to Payroll for Operating Expenditure
*   [ ] Void of Operating Expenditure
*   [ ] Transfers to Affiliates/Other Committees
*   [x] Contribution to Candidate
*   [x] Contribution to Candidate (In-Kind)
*   [ ] Void of Contribution to Candidate
*   [ ] Contribution to Other Committee
*   [ ] Contribution to Other Committee (In-Kind)
*   [ ] Void of Contribution to Other Committee
*   [x] Other Disbursements
*   [x] Credit Card Payment for Other Disbursement
*   [ ] Staff Reimbursement for Other Disbursement
*   [ ] Payment to Payroll for Other Disbursement
*   [ ] Void of Other Disbursement
*   [ ] Non-contribution Account Disbursement
*   [ ] Non-contribution Account Credit Card Payment
*   [ ] Non-contribution Account Staff Reimbursement
*   [ ] Non-contribution Account Payment to Payroll
*   [ ] Individual Refund - Non-contribution Account
*   [ ] Other Committee Refund - Non-contribution Account
*   [ ] Business/Labor Organization Refund - Non-contribution Account
*   [ ] Recount Account Disbursement
*   [ ] National Party Recount/Legal Proceedings Account Disbursement
*   [ ] National Party Headquarters Buildings Account Disbursement
*   [ ] National Party Pres. Nominating Convention Account Disbursement
*   [ ] Individual Refund - National Party Headquarters Buildings Account
*   [ ] Other Committee Refund - National Party Headquarters Buildings Account
*   [ ] Tribal Refund - National Party Headquarters Buildings Account
*   [ ] Individual Refund - National Party Pres. Nominating Convention Account
*   [ ] Other Committee Refund - National Party Pres. Nominating Convention Account
*   [ ] Tribal Refund - National Party Pres. Nominating Convention Account
*   [ ] Individual Refund - National Party Recount/Legal Proceedings Account
*   [ ] Other Committee Refund - National Party Recount/Legal Proceedings Account
*   [ ] Tribal Refund - National Party Recount/Legal Proceedings Account
*   [x] Refund of Individual Contribution
*   [ ] Refund of Individual Contribution - Void
*   [x] Refund of Party Contribution
*   [ ] Refund of Party Contribution - Void
*   [ ] Refund of PAC Contribution
*   [ ] Refund of PAC Contribution - Void
*   [ ] Refund of Unregistered Receipt from Person
*   [ ] Refund of Unregistered Receipt from Person - Void
*   [x] 100% Federal Election Activity Payment
*   [x] Credit Card Payment for 100% Federal Election Activity
*   [ ] Staff Reimbursement for 100% Federal Election Activity
*   [ ] Payment to Payroll for 100% Federal Election Activity
*   [ ] Void of 100% Federal Election Activity
*   [ ] In-kind Out (should match whatever is on In-kind Receipt)
*   [ ] PAC In-kind Out (should match whatever is on PAC In-kind Receipt)
*   [ ] Party In-kind Out (should match whatever is on Party In-kind Receipt)
*   [ ] In-kind Transfer Out (should match whatever is on In-kind Transfer)
*   [ ] In-kind Transfer FEA Out (should match whatever is on In-kind Transfer - Federal Election Activity)

Dev Note

Per @MitchellTCG testing on the Schedule B transactions to be completed prior to QA review. Per discussion ticket pointed as 5.

Because this will impact all transactions, we can get rid of the dynamic label put in place to make some of them have "(Optional)"

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-679](https://fecgov.atlassian.net/browse/FECFILE-679)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Memo Item Checkbox verbiage (Optional) is displayed when creating / entering a Disbursement (Schedule B).    

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8ebe2d64-e1fc-48f2-91db-84a004b7beb7)

QA tested 2 transactions from each accordion dropdown list as denoted in list above.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/94dadf0c-721a-4eb3-a9ac-817845ccccea)

QA Review Completed.   Moved to Stage Ready.
