### ISSUE TITLE
UI Update: Fix Data table sorting icons

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1253]
Business Reason

  As the UX Stakeholder, I would like the Data Table sorting Icons to match FEC.gov to reinforce continuity with the main website and FEC ecosystem.

Tasks

*   [x] ***1\. Change not filtered icon***

       FROM:

       ![Screenshot 2023-07-18 at 2.24.33 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/b1c964ba-fd07-4b92-9b1c-9f2c1d7a0983](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/b1c964ba-fd07-4b92-9b1c-9f2c1d7a0983))

TO:

  ![i-dash.svg]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/bc2dcafa-969c-49a7-a427-258bf1cc5702](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/bc2dcafa-969c-49a7-a427-258bf1cc5702))

*   [x] ***2\. Change Ascending Icon (Sort top to bottom - A to Z)***

       FROM:

       ![Screenshot 2023-07-18 at 2.24.38 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/15c96184-c7ac-4c90-8591-31c0b6a4c90f](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/15c96184-c7ac-4c90-8591-31c0b6a4c90f))

TO:

  ![i-arrow-up-border.svg]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/49f5ce2b-70c3-4956-b7b8-47ee8e8628ce](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/49f5ce2b-70c3-4956-b7b8-47ee8e8628ce))

*   [x] ***3\. Change Descending Icon (Sort top to bottom - Z to A)***

       FROM:

       ![Screenshot 2023-07-18 at 2.24.47 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/047a4b36-8915-46a3-bd58-c757fa1b3bb1](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/047a4b36-8915-46a3-bd58-c757fa1b3bb1))

TO:

  ![i-arrow-down-border.svg]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/9f6d1443-ea5e-4aac-addb-115e712de9fc](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/9f6d1443-ea5e-4aac-addb-115e712de9fc))

Icons Attached
[https://app.zenhub.com/files/306118986/80a90363-9c1c-4f5e-b288-cd7bf7eda221/download](https://app.zenhub.com/files/306118986/80a90363-9c1c-4f5e-b288-cd7bf7eda221/download)([https://app.zenhub.com/files/306118986/80a90363-9c1c-4f5e-b288-cd7bf7eda221/download](https://app.zenhub.com/files/306118986/80a90363-9c1c-4f5e-b288-cd7bf7eda221/download))

New dash
[dash.svg.zip]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1grIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5cdf0724528a66c3d526205d25997111a657bc41/dash.svg.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1grIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5cdf0724528a66c3d526205d25997111a657bc41/dash.svg.zip))

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-678](https://fecgov.atlassian.net/browse/FECFILE-678)

**Comment by MitchellTCG** [comment]
@GreggMoreland
UX Review complete

**Comment by GreggMoreland** [comment]
BA Review complete

**Comment by MitchellTCG** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanYrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fda4b42be6c33133a5f693728bcc24bb00986160/dash.svg)

**Comment by MitchellTCG** [comment]
[dash.svg.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajcrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8bf72166dbc921e9a3edf28440b1b83c5b6540b5/dash.svg.zip)

**Comment by MitchellTCG** [comment]
testing 123

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEgrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--807f3b275535fb84ea1baa796e856ddda2bbb4ec/New-dash.svg)

**Comment by MitchellTCG** [comment]
new dash 2

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGIrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--458baae5969e8f4cabebea1ba8a7f119e10c08c7/New-dash2.svg)

**Comment by mjtravers** [comment]
The initial sort when tables on the MANAGE YOUR TRANSACTIONS page is opened is by transaction create date, so it is correct that all the columns have the "-" icon displayed.

Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Icons have been updated per UX design.  

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFFEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa606a5fe9f06bbec3ec3d604f6c73c2ea42436e/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a29331a1c8f15e5499b9762d13f3f940263e4c5d/image.png)

QA Review Completed.  Moved to Stage Ready.
