### ISSUE TITLE
UI Update: Snap footer to the bottom of the page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1255]
Business Reason

  PLEASE FIX

Task

*   [ ] Snap footer to the bottom of the page on BOTH pages with just a footer and pages with a footer and left nav

1.  IT SHOULD NOT LOOK LIKE THIS

       ![Screenshot 2023-07-18 at 3.19.37 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/3af61074-778c-4831-982a-cea7542834aa](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/3af61074-778c-4831-982a-cea7542834aa))

1.  SHOULD NOT LOOK LIKE THIS

1.  1.  Regular
        [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3VzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--30c3db612ae3c8327f14c92d74f37a6012cc4ad1/1255%20-%20UI%20Update%20-%20Snap%20footer%20to%20the%20bottom%20of%20the%20page%201.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3VzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--30c3db612ae3c8327f14c92d74f37a6012cc4ad1/1255%20-%20UI%20Update%20-%20Snap%20footer%20to%20the%20bottom%20of%20the%20page%201.png))

1.  1.  Stretched
        [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3lzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8c45d31735c272e5bdc60b9c8da7e0d51a806425/1255%20-%20UI%20Update%20-%20Snap%20footer%20to%20the%20bottom%20of%20the%20page%202.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3lzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8c45d31735c272e5bdc60b9c8da7e0d51a806425/1255%20-%20UI%20Update%20-%20Snap%20footer%20to%20the%20bottom%20of%20the%20page%202.png))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-676](https://fecgov.atlassian.net/browse/FECFILE-676)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
UX Review complete

**Comment by GreggMoreland** [comment]
BA Review complete

**Comment by andrew-bowers-tcg** [comment]
Moved footer to the bottom. Created a pull request

**Comment by MitchellTCG** [comment]
@WiseQA 
Wires added
@MitchellTCG Thank You !!

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review when selecting "Edit report" from the actions dropdown list - test FAILED

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1dzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fb8881cd6a468a24e5fb89d481955ad912d8593c/image.png)

The footer is overlaying the left Nav bar

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3lzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ed07df8957709c74e548573049de4a0cfe7abbf0/image.png)

@MitchellTCG returning to In-Progress for fix.

**Comment by WiseQA** [comment]
QA noted also the "Loans and Debts" part of the Transactions page is not displayable.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ090IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--333e82e7ff9e141da45ccab070c72657343e30c0/image.png)

**Comment by MitchellTCG** [comment]
@andrew-bowers-tcg @mjtravers 
I'm not sure it if this is a Z-index issue but data is catch behind the footer and the user can't scroll to it

@andrew-bowers-tcg 
please look at new wires

if there is a left nav the footer should be to the right of it

Ping me with you have a moment

**Comment by MitchellTCG** [comment]
@mjtravers 
Is rollingback the code and moving the ticket to Sprint Backlog.

@andrew-bowers-tcg 
Work on the radio button first

**Comment by mjtravers** [comment]
Code for this ticket has been rolled back out of the develop branch.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified footer fix was implement and is displaying correctly at the bottom of the page.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1l1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2796b26a8d2bf62d8f86787fd7498c84e94ac080/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2N1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--686680236dfb7976662cc2da4ab5fcf92ee1cfcc/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK291QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78dc411f804fe7bfc1f5d538bb24512a6de3e56e/image.png)

QA Review Completed.   Moved to Stage Ready.

**Comment by WiseQA** [comment]
During further testing it was found that when shrinking the screen the display changes and becomes stacked underneath the left NAV bar.    Fix stacking issue.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzgxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b084177601e945f5c6a1bbec272aadfbfd1faef3/image.png)

@MitchellTCG @andrew-bowers-tcg moved back to In-Progress for this fix.

**Comment by MitchellTCG** [comment]
@sasha-dresden , let's discuss this ticket sometime this morning.

**Comment by sasha-dresden** [comment]
How does this look?
<h4>No Sidebar</h4>
<h5>Content fits / No scrollbar </h5>
<img width="1556" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNng2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88d8bd43e5b4bba77f21cbbba710a14a01c1136f/Screenshot%20from%202023-12-20%2016-31-23.png" alt="Screenshot from 2023-12-20 16-31-23.png" />
<h5>Content does not fit / Scrollbar </h5>
<img width="1556" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjE2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2844d545ec4600adf88617180cc9898a48ff912e/Screenshot%20from%202023-12-20%2016-32-19.png" alt="Screenshot from 2023-12-20 16-32-19.png" />
<h4>With Sidebar</h4>
<h5>Content fits / No scrollbar </h5>
<img width="1556" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjk2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d4b7f1b400b97357b3904140c5a9b0326a60815/Screenshot%20from%202023-12-20%2016-32-48.png" alt="Screenshot from 2023-12-20 16-32-48.png" />
<h5>Content does not fit / Scrollbar </h5>
<img width="1556" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0I2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75bf2981a279262266037d8791b5c2239de82950/Screenshot%20from%202023-12-20%2016-33-06.png" alt="Screenshot from 2023-12-20 16-33-06.png" />

**Comment by mjtravers** [comment]
Noticed in CR that the left nav needs to stretch some more
<img width="800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU9qQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88b1c146ac9c37316662bcb93b8d52843f9c5bad/image.png" alt="image.png" />

Sending ticket back to In Progress

**Comment by sasha-dresden** [comment]
Ah, looks like there was a bit of an issue with the css when the height of the main content section exceeded both the the sidebar's height and the height of the viewport. Got that fixed and ready for code review.

**Comment by mjtravers** [comment]
There are some SonarCloud quality issues raised. I don't think this has come up before so it wasn't realized as a blocker like failing tests has been. To see these issues, check the list as seen below in the PR. In this case, there are 7 that can be looked at and corrected.
<img width="534" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVdrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b816ad0d3f76d4ada84b54de1379eae4f0ad3e2/image.png" alt="image.png" />

The list looks mostly like duplicate code or empty style blocks that can be removed:
<img width="771" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVNrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--711bb97451027564197cb50f75c0bc1af19a2e33/image.png" alt="image.png" />

Sending ticket back to In Progress

**Comment by sasha-dresden** [comment]
Oh thanks for catching that. I just saw the green checkmark and figured it was all good. Do you think we should have these sorts of things fail the sonar cloud check?
I cleaned up those css files.

**Comment by mjtravers** [comment]
@sasha-dresden SonarCloud has a threshhold setting on how many errors per group check that we could lower. Although, sometimes we have some SonarCloud findings that don't apply to what we're doing. In this case it was duplicates or empty style sheet declarations so we can attend to those.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the footer is snapped to the bottom of the page as designed.   Tested the links under "Enter A Transaction" (see screenshot below).   Footer displayed to the bottom of the page.   Left NAV was stretched to bottom of page with the footer.  (Note:  Minimized and maximized image on my computer and footer and left NAV displayed correctly)

<img width="1678" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMCt0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef559a5f42cd4b02e8c13b1b1fcba335b656e1eb/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
