### ISSUE TITLE
UI Update: Fix lookup box

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1258]
Business Reason
As the UX Principal, I would like the Lookup to look like the wireframe

 Task
1. Update the left side of the lookup

# Found here
![Screenshot 2023-07-18 at 3.51.23 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/bd90e302-bff9-4b20-ae72-159674aea078)
 
Update this code:
![Screenshot 2023-07-18 at 3.54.19 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4fc4d89f-95d4-4ada-b436-7160ac2df17c)
- [ ] Update border: from 2px to **3px**

Update this code:
![Screenshot 2023-07-18 at 3.53.57 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0fc1d518-936d-4904-8a07-a0a240e3b819)
- [ ] Update border-radius: from 4px to **4px 0 0 4px**

2. Update the lright side of the lookup

# Found here
![Screenshot 2023-07-18 at 3.51.50 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/96477e81-7c71-44ff-9486-d2bca0043102)

Update this code:
![Screenshot 2023-07-18 at 3.52.25 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/9afd2106-7074-47f6-8acb-bf08e36ec6a2)
- [ ] Update border-radius: from 4px to **0 4px 4px 0**
- [ ] Update border: from 2px to **3px**
- [ ] Add **margin-left: -3px**

 Wireframes

# CHANGE FROM
![Screenshot 2023-07-18 at 3.21.48 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/029a5eb5-2f49-444e-ac84-5d6aaced0356)

# CHANGE TO
![Screenshot 2023-07-18 at 3.50.05 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/df0f537e-b488-4f19-adc3-e4370883b646)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by toddlees** [comment]
https://primeng.org/inputgroup should solve the need of combining the two controls

**Comment by MitchellTCG** [comment]
OBE
