### ISSUE TITLE
Add lint check to CircleCI for web-app

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#126]
The linting process is already set up but just needs to be added as a step in CircleCI. The relevant files to get it running are:
- front-end/build-scripts/Dockerfile-lint
- front-end/build-scripts/lint.sh

**Acceptance Criteria**
- eslint is run in CircleCI and the results reported in the CircleCI commit report
- if it fails, then the deployment aborts

**QA Notes**
- The output of CircleCI showing that the lint process is running can be found [here](https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/308/workflows/6ff68702-f0ab-4642-9779-04a461f30607/jobs/1057)
### QA Notes ### 
 - front-end/build-scripts/Dockerfile-lint
- front-end/build-scripts/lint.sh

**Acceptance Criteria**
- eslint is run in CircleCI and the results reported in the CircleCI commit report
- if it fails, then the deployment aborts

**QA Notes**
- The output of CircleCI showing that the lint process is running can be found [here](https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/308/workflows/6ff68702-f0ab-4642-9779-04a461f30607/jobs/1057)
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
This ticket will just cover the set up of the lint check in CircleCI. There are currently 50 or so lint warning and error messages that will be cleaned up with the follow on ticket, #220

**Comment by mjtravers** [comment]
There have been 3 linting rule checks turned off temporarily until ticket #220 cleans up the remaining linting errors. The rule exceptions were added to the .eslintrc.json file and are:
- no-extra-boolean-cast
- @typescript-eslint/no-explicit-any
- @typescript-eslint/no-unused-vars

**Comment by WiseQA** [comment]
Verified unit test passed successfully as denoted in the Acceptance Criteria.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/861f3510-cfa0-46cc-92a4-2630b8fc8509)

QA review completed.  Moved to Stage Ready.
