### ISSUE TITLE
UI Update: Fix double line and instructive text on ALL In-kinds (total of five)

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1261]
Business Reason
As the UX Principal I would like the extra "hr" removed near the bottom of the first accordion section from the In-kind receipt and to change the text instructive text.

 Tasks
- [ ] Remove extra hr
- [ ] Change instructive text 
**FROM:**
_The information in this receipt will automatically populate a related transaction. Review the associated disbursement or click "Save both transactions" to record these transactions._
**TO:**
_The information in this receipt will automatically create a related disbursement. Review the disbursement or continue without reviewing and “Save both transactions”._

 Wireframes

# CURRENT
![Screenshot 2023-07-19 at 9.25.43 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/b160e212-f6e4-49ea-baee-41b1f41c74d8)
![Screenshot 2023-07-19 at 9.25.51 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/357706c9-a161-4f1b-9f82-7daeca58bfb1)

# Change to
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUtnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9fe3492e18294e8bbb14d94818815679fd794f7e/642%20-%20In-kind%20Receipt.png)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
I check all five in-kind types and this ticket appears to be completed.

@WiseQA 
can you please verify the following In-kinds have already been updated:

- In-kind Receipt
- Party In-kind Receipt
- PAC In-kind Receipt
- In-kind Transfer
- In-kind Transfer - Federal Election Activity

**Comment by WiseQA** [comment]
@MitchellTCG push to QA bucket please and will adhoc test and make sure all fixes have been made.   Assign to Sprint 31 ?

**Comment by WiseQA** [comment]
QA review verified the double line and instructive text has been corrected on the following transactions.

- In-kind Receipt
- Party In-kind Receipt
- PAC In-kind Receipt
- In-kind Transfer
- In-kind Transfer - Federal Election Activity

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdktvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7d6f003fd20c8b7b1b94b0622645a399851491f2/image.png)

QA Review Completed.  Moved to Stage Ready.
