### ISSUE TITLE
When Editing a Contact from Manage Contacts the Committee or Candidate ID complains of duplicate FEC ID

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1283]
During testing when editing an existing contact from the Mange Contacts table the Committee and/or Candidate ID complains the Committee / Candidate ID is to be unique. Found in Sprint 28.

1\. Open Contact from Contacts Table

  2\. Edit Street Name

  2\. Click accidentally in Committee ID field

  3\. Error Message appears as "FEC IDs must be unique"

  4\. Cannot save contact

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/040c52e0-e5db-4b49-9fb1-5cf95a08226c](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/040c52e0-e5db-4b49-9fb1-5cf95a08226c))

(NOTE: This bug is for both Committee and Candidate IDs in Manage Contacts)

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ed89c6b6-1b47-4dad-ba60-ee6453a2d02c](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ed89c6b6-1b47-4dad-ba60-ee6453a2d02c))

@MitchellTCG @mjtravers Bug fix pointed as a 3 point. Change to be verified within Schedule A / B transactions and contacts. Bug found in Sprint 28.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-655](https://fecgov.atlassian.net/browse/FECFILE-655)

**Comment by mjtravers** [comment]
I am seeing hard-coded references to contact_1 in the contact service and contact form component that gives me pause. As David is out, the best way forward is to wait for 1284 (which is streamlining the contact management code) to pass QA and then merge that code into the branch for this ticket and go from there. Currently, form controls are being passed through to sub-components to manage the error messaging which may be able to be made more efficient. Sending back to In Progress and marking this ticket dependent on 1284.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified and retested when editing an existing contact from the Mange Contacts table the Committee and/or Candidate ID is functioning correctly.

1.  Open Contact from Contacts Table
2.  Edit Street Name
3.  Save contact once editing - Committee ID / Candidate ID functioning correctly.
4.  Click accidentally in Candidate / Committee ID field
5.  No Error Message appears "FEC IDs must be unique"
6.  Select Save - contact updated and saved.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFVFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f6a5660b6e465b31749c0a3bbabd91077e6ba52f/image.png)

QA Review Completed.    Moved to Stage Ready.
