### ISSUE TITLE
Fix broken contact functionality

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1284]
During testing when creating second / third contact, the notifications for contacts is not displaying, functionality is broken. Upon editing the second contact changes, the contact information is not being saved to Manage Contacts. Bug found in Sprint 28.

Fix broken contact functionality for 1, 2 or 3 contacts. Verify notifications for each contact being saved or edited are populated correctly.

***Dev Notes***

  Fixing these bugs is achieved by:

*   Rewriting confirmation code to loop through configured contacts (was only running for contact_1)
*   Rewriting contact change detection and form  contact resolution code to be configured. Where it was blindly comparing/updating any form field that matched a contact field, now it relies on a configured relation between contact, contact fields and form fields.

@MitchellTCG @mjtravers per conversation assigned to Matt and pointed this bug fix as an 8.

***QA Notes: List of needed fixes:***

*   [x] When adding a transaction with 2 new contacts, the pop-up alerting the user that a the second contact will be created does not appear. CAN TEST WITH: Conduit Earmark Out
*   [x] When editing the contacts in a transaction with 2 existing contacts, the pop-up alerting the user what fields have changed for the first contact shows changes made in the second contact. CAN TEST WITH: Conduit Earmark Out
*   [x] When editing the contacts in a transaction with 2 existing contacts, the pop-up alerting the user what fields have changed for the second contact does not appear. CAN TEST WITH: Conduit Earmark Out
*   [x] When updating a candidate in a conduit earmark out transaction, the candidate updates are not getting saved to the record in the contact management screen. CAN TEST WITH: Conduit Earmark Out
*   [x] When creating a single transaction (an individual receipt for example), if you look up an existing contact, change a property of the contact (update the last name for example), and save, no confirmation popup will appear but the changes will take effect. CAN TEST WITH: Individual Receipt

### QA Notes ###
Fix broken contact functionality for 1, 2 or 3 contacts.  Verify notifications for each contact being saved or edited are populated correctly.

**Dev Notes**
Fixing these bugs is achieved by:
- Rewriting confirmation code to loop through configured contacts (was only running for contact_1)
- Rewriting contact change detection and form  contact resolution code to be configured.  Where it was blindly comparing/updating any form field that matched a contact field, now it relies on a configured relation between contact, contact fields and form fields.

@MitchellTCG @mjtravers per conversation assigned to Matt and pointed this bug fix as an 8.   

**QA Notes: List of needed fixes:**

- [x] When adding a transaction with 2 new contacts, the pop-up alerting the user that a the second contact will be created does not appear. CAN TEST WITH: Conduit Earmark Out
- [x] When editing the contacts in a transaction with 2 existing contacts, the pop-up alerting the user what fields have changed for the first contact shows changes made in the second contact.  CAN TEST WITH: Conduit Earmark Out
- [x] When editing the contacts in a transaction with 2 existing contacts, the pop-up alerting the user what fields have changed for the second contact does not appear.  CAN TEST WITH: Conduit Earmark Out
- [x] When updating a candidate in a conduit earmark out transaction, the candidate updates are not getting saved to the record in the contact management screen.  CAN TEST WITH: Conduit Earmark Out
- [x] When creating a single transaction (an individual receipt for example), if you look up an existing contact, change a property of the contact (update the last name for example), and save, no confirmation popup will appear but the changes will take effect.  CAN TEST WITH: Individual Receipt

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-654](https://fecgov.atlassian.net/browse/FECFILE-654)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Contact functionality has been fixed and tested below scenarios.   Defect **PASSED**

- [x] When adding a transaction with 2 new contacts, the pop-up alerting the user that a the second contact will be created does not appear. CAN TEST WITH: Conduit Earmark Out
- [x] When editing the contacts in a transaction with 2 existing contacts, the pop-up alerting the user what fields have changed for the first contact shows changes made in the second contact.  CAN TEST WITH: Conduit Earmark Out
- [x] When editing the contacts in a transaction with 2 existing contacts, the pop-up alerting the user what fields have changed for the second contact does not appear.  CAN TEST WITH: Conduit Earmark Out
- [x] When updating a candidate in a conduit earmark out transaction, the candidate updates are not getting saved to the record in the contact management screen.  CAN TEST WITH: Conduit Earmark Out
- [x] When creating a single transaction (an individual receipt for example), if you look up an existing contact, change a property of the contact (update the last name for example), and save, no confirmation popup will appear but the changes will take effect.  CAN TEST WITH: Individual Receipt

QA Review Completed.   Moved to Stage Ready.
