### ISSUE TITLE
Conduit Earmark Receipt / Conduit Earmark Out and PAC Conduit Earmark / PAC Conduit Earmark Out transactions the "This is a required field" error message populating incorrectly. 

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1286]
During testing there are two places the error message is displaying incorrectly. Found in Sprint 28.

NOTE: Fixes in this bug affect both Conduit Earmark Receipt / Conduit Earmark Out (Reference ticket [https://fecgov.atlassian.net/browse/FECFILE-979](https://fecgov.atlassian.net/browse/FECFILE-979 "smart-link") #643 and [https://fecgov.atlassian.net/browse/FECFILE-897](https://fecgov.atlassian.net/browse/FECFILE-897 "smart-link") #745 from Sprint 27) and PAC Conduit Earmark / PAC Conduit Earmark Out transactions (Reference ticket [https://fecgov.atlassian.net/browse/FECFILE-975](https://fecgov.atlassian.net/browse/FECFILE-975 "smart-link") #647 and [https://fecgov.atlassian.net/browse/FECFILE-895](https://fecgov.atlassian.net/browse/FECFILE-895 "smart-link") #747 from Sprint 27)

When creating a Conduit Earmark Receipt transaction, When selecting the "Deposited" button the "This is a required field" is populated. This is Not a Memo Item so the error message shouldn't be populating. (NOTE: Button fix is in future UI ticket)

[![](https://github.com/fecgov/fecfile-web-app/assets/110493670/b9427d99-13a9-42c0-ad22-c869f4fe6d09%5D(https://github.com/fecgov/fecfile-web-app/assets/110493670/b9427d99-13a9-42c0-ad22-c869f4fe6d0))](https://github.com/fecgov/fecfile-web-app/assets/110493670/b9427d99-13a9-42c0-ad22-c869f4fe6d09%5D(https://github.com/fecgov/fecfile-web-app/assets/110493670/b9427d99-13a9-42c0-ad22-c869f4fe6d0))

Selected Step Two entered information for "Conduit Earmark Out"

Date range is outside report period.

[![](https://github.com/fecgov/fecfile-web-app/assets/110493670/a2fb8f27-5510-437f-b84b-e9013ba3fc83%5D(https://github.com/fecgov/fecfile-web-app/assets/110493670/a2fb8f27-5510-437f-b84b-e9013ba3fc8))](https://github.com/fecgov/fecfile-web-app/assets/110493670/a2fb8f27-5510-437f-b84b-e9013ba3fc83%5D(https://github.com/fecgov/fecfile-web-app/assets/110493670/a2fb8f27-5510-437f-b84b-e9013ba3fc8))

Below the memo item should display "This is a required field" error message.

Cannot save transaction due to the "This is a required field" error.

@MitchellTCG @mjtravers bug fix to correct "This is required field" error message for Conduit Earmark Receipt / Conduit Earmark Out. Bug fix pointed as a 3 point.

Tasks

*   [x] Change error message below text: "This transaction must be undeposited because the date received is outside the coverage dates."

*   [x] and move error under date received

*   [x] Bold Memo Item and Not a Memo Item

*   [x] Make use this fix covers ALL Conduit Earmarks (Conduit Earmark & PAC Conduit Earmark)

*   [ ] Add validation to Conduit Earmark Out memo item field (if date outside report coverage date, can't be memo item). Memo item is still based on Conduit Earmark Receipt (parent) and cannot be edited in Conduit Earmark Out (child). This means that the user could try to make a deposited conduit earmark out, outside the coverage dates, but wont be able to save it unless they make the conduit earmark receipt (parent) undeposited or change the date of the conduit earmark out to within the report coverage dates.

Wireframe

[![](https://github.com/fecgov/fecfile-web-app/assets/110493670/41dcd645-03c5-4115-a20a-33e94169aebd%5D(https://github.com/fecgov/fecfile-web-app/assets/110493670/41dcd645-03c5-4115-a20a-33e94169aeb))](https://github.com/fecgov/fecfile-web-app/assets/110493670/41dcd645-03c5-4115-a20a-33e94169aebd%5D(https://github.com/fecgov/fecfile-web-app/assets/110493670/41dcd645-03c5-4115-a20a-33e94169aeb))

### QA Notes ###

 
  
 null

### DEV Notes ###

 
  
 null

### Design ###

 
  
 null

[FECFILE-653](https://fecgov.atlassian.net/browse/FECFILE-653)

 See full ticket and images here: [FECFILE-653](https://fecgov.atlassian.net/browse/FECFILE-653)

**Comment by WiseQA** [comment]
During additional review two additional fixes for this ticket.  (Reference ticket #643 from Sprint 27)

1.   Disable "Just checking" popup 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b7d37f0e-71ec-4550-b2e8-ae88ee29bbb3)

2.   Select Conduit Earmark Transaction, then select Step 2, Conduit Earmark Out page is displayed.  
-  Remove checkbox MEMO ITEM (OPTIONAL) (help icon)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5ceb28f0-58dd-44ed-a0ca-52df69165614)

-  Replace with same verbiage from Conduit Earmark Receipt page

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1e9fc394-61dd-4899-a595-d8eb4308c09d)

@MitchellTCG  @Elaine-Krauss-TCG  these fixes added to this bug ticket.   Changed ticket points from 3 to 5 as discussed.

**Comment by Elaine-Krauss-TCG** [comment]
Updated to match requirements.  I just need to polish things up and ship to CR.

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/0746ffb0-3c11-4afe-883f-2428f33f1045)

**Comment by MitchellTCG** [comment]
@Elaine-Krauss-TCG & @WiseQA 

Elaine can you move the error message closer to the date received input box than the toggle

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers @Elaine-Krauss-TCG per discussion added the PAC Conduit Earmark / PAC Conduit Earmark Out transactions to be fixed also, as this bug fixes are the same.    Referenced tickets from Sprint 27.

**Comment by toddlees** [comment]
moving to awaiting analysis to address scenario with Conduit Earmark Out that is outside of the current reporting period

**Comment by MitchellTCG** [comment]
Due to UX confusion the functionality of the ticket needs to be redesigned by the UX team and run by FEC before a new ticket is created. The new ticket(s) will be linked to this one for context and tracking purposes.

**Comment by MitchellTCG** [comment]
We will revisit this ticket after the redesign of Conduit Earmark is finished

**Comment by AureliaKhorsand** [comment]
@MitchellTCG has the redesign been completed? Can we move on this yet?

**Comment by AureliaKhorsand** [comment]
@MitchellTCG what is the status of this?

**Comment by AureliaKhorsand** [comment]
@MitchellTCG is this still needed?

**Comment by mary-tcg** [comment]
@MitchellTCG @AureliaKhorsand wire updated to correct placement of error message

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg what is the status of this? It has been on hold for a while and it is blocking #1153

**Comment by MitchellTCG** [comment]
@AureliaKhorsand, let's talk about this ticket tomorrow. I've talked with Shelley, and we believe it is OBE.
