### ISSUE TITLE
UX: Create FECfile Online Landing Page

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#129]
Business Reason

As an FEC report filer, I need a Landing Page to go to so I can Log into FECFile, Sign up for Login.gov or learn more information about the app and/or Login.gov

Acceptance Criteria

***Given*** someone comes to FECfile Online

 ***Then*** the log in/landing page will be as follows (see wireframe).

 ***And*** the following links will resolve as follows:

*   "Log into FECFile" Button & "Log in" Hyperlink will resolve to the login.gov sign in page (see wireframes below)
*   "Sign up with Login.gov" Button & "Sign up" Hyperlink will be dead links
*   "Learn more about Login.gov" Hyperlink will resolve to ***(need link)***
*   the footer links will resolve as they do once logged in (see #553)

Dev Notes

*   Add "SIGN UP" next to "LOG IN"
*   ***Please be very aware it is LOG IN !!! TWO WORDS***
*   Footer only has blue part. Not the light grey part that is on most pages.
*   Alt text for image "Example Dashboard for FECFile"

Wireframes

1.  New Landing Page

      

1.  "Log into FECFile" Button & "Log in" Hyperlink

1.  1.  On DEV this button will resolve to:

            

1.  1.  On Stage this button will resolve to:

            

1.  "Sign up with Login.gov" Button & "Sign up" Hyperlink

1.  1.  On DEV this button will resolve to:

            Dead link

1.  1.  On Stage this button will resolve to:

            Dead link

1.  "Learn more about Login.gov" Hyperlink

1.  1.  On Stage and Dev

            

HTML/CSS

 ***Headline:***

 this is an H1

 "Made for filers

 Built for productivity"

 Font-family: karla bold

 Font-size: 32px

Made for filers

 color: #212121

Built for productivity

 color: #164F85

***Body text:***

 "FECFile is a FREE Web-based software system that committees can use for electronic filing. and the Electronic Filing Office is available to answer filers’ questions about the system."

 Font-family: karla

 Font-size: 14px

 color: #212121

***Button***

 "Log into FECFile"

 background-color: #112e51;

 color: #ffffff

 border-radius: 4px;

 display: inline-block;

 font-family: karla,sans-serif;

 font-size: 14px

 line-height: 1;

 padding: 8px 20px;

 text-align: center;

 vertical-align: middle;

***Button***

 "Sign up with Login.gov"

 background-color: #367F90;

 color: #ffffff

 border-radius: 4px;

 display: inline-block;

 font-family: karla,sans-serif;

 font-size: 14px

 line-height: 1;

 padding: 8px 20px;

 text-align: center;

 vertical-align: middle;

***Hyperlink***

 "Learn more about Login.gov"

 font-family: karla bold;

 font-size: 14px

 color: #112e51;

 border-bottom: 1px dotted #112e51;

 cursor: pointer;

 text-decoration: none;

 transition: color .1s linear;

Asset

 (Note that none of these links are functional, this is just a static image)

 

### QA Notes ###
- Note that nothing is "clickable" in the asset image (dashboard example).

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1290](https://fecgov.atlassian.net/browse/FECFILE-1290)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Can we discuss this use case?

**Comment by AureliaKhorsand** [comment]
@MitchellTCG yes - this is a placeholder that needs BA work, and isn't ready for design review. If you want to discuss it before we flesh it out with requirements that's fine.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG can you provide the link for "learn more about login.gov"?

**Comment by mjtravers** [comment]
@Elaine-Krauss-TCG I'm seeing a scroll bar on the bottom and right of the content area of the page.
<img width="958" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWtMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a45a5e596d6b6c0929de1c74c60d7ca101f0a55/image.png" alt="image.png" />

Sending back to In Progress

**Comment by Elaine-Krauss-TCG** [comment]
This scrollbar appears on Google Chrome but not on Firefox where I was doing my development.  I'll look into it.

**Comment by Elaine-Krauss-TCG** [comment]
A small CSS change prevents the scrollbars from being always visible.  Pushing it back to CR.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified FECfile Landing page is displayed.   Sign Up has been added beside Log In.   Log In has been changed to two words.   "Log into FECFile" and "Sign up with Login.gov" buttons are dead links.

<img width="1421" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK29TQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--473a6403929f39afc741ac319b326b23c6b0a6cf/image.png" alt="image.png" />

___________________________________________________________________________________________________________

NOTE:  "Debug Login Form" is temporary on DEV to be used for testing.   Will not be displayed when pushed to STAGE and/or PROD

____________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
