### ISSUE TITLE
Allow user to create and edit Notification of Multicandidate Status (Form 1M)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1292]
Business Reason

As a Committee Administrator, I will be able to create a Notification of Multicandidate Status transaction on Form 1M so that I can submit Notification of Multicandidate Status as needed.

 Acceptance Criteria

**Given** the user is on the Reports page
**When** I go to create a new report and select Form 1M
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#

-	**COMMITTEE NAME** (Required, System populated)
-	**COMMITTEE TYPE** (Required) 
-- State Party (maps to X on the backend)
-- Other (maps to N on the backend)

# Address 
#
-	**STREET ADDRESS** (Required, System populated)
-	**APARTMENT, SUITE, ETC.** (Optional, System populated)
-	**CITY** (Required, System populated)
-	**STATE/PROVINCE** (Required, System populated)
-	**ZIP/POSTAL CODE** (Required, System populated)

**and** the user must indicate whether they will qualify by
- affiliation _or_
- qualification (this cannot be selected until #1555)

---

# Affiliation 
#

If the user has indicated they want to qualify through affiliation, they will be required to complete the following fields:

-	**AFFILIATED COMMITTEE NAME** (Required, LOOKUP)
-	**AFFILIATED COMMITTEE ID** (Required)
-	**AFFILIATED DATE** (Required)

---

**Then** I will be able to:
- Cancel
- Save 
- Save and continue
- Edit

**And** when I save, then I will be taken to the Manage Transactions table

 Wireframes

# Select a Form 1M
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHNNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ac92dcacecb5376dbd40316392d677c0eaf2a71/1292%20Select.png)

# Select a Form 1M - Selected
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG9NQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f18f5c1d707edd8e0924871fc33643097a609f9/1292%20Selected.png)

# Form 1M Initial Load
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVlOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--faf4a4b579339e447988c3749c54e3feff3efa2b/1292%20Initial%20Load.png)

# Form 1M Radio button errors
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWdOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--632c2da583d2023a48e859beb8e118f6d15342c4/1292%20Radio%20errors.png)

# Form 1M Affiliation collapsed
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXNOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7387b5f05a5dc26329f58e520d7a1b4dacc715ac/1292%20-%20Affiliation%20%E2%80%93%20collapsed.png)

# Form 1M Affiliation expanded
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXdOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65b64475cde35cc1cb8f29829ae6efb77555560d/1292%20-%20Affiliation%20Expanded.png)

# Form 1M Affiliation Errors
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTBOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a2b02a97f8cf9b050df83efbd65bd6e75b57c72/1292%20-%20Affiliation%20Expanded%20%E2%80%93%20error.png)

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
QA Notes for testing (Wise)
- [x] Save resolves on the Manage reports page
- [x] Save and continue resolves on the Print preview page
### DEV Notes ### 
 New form should be created in a new reports/f1m directory and leverage the existing shared/components/inputs components and also include the ngrx store of activeReport store variable.

The layout/sidebar/menu-report will need to be refactored into 2 sidebars, one for f3x and one for f1m., and also update manage of sidebarState values in the ngrx store. The current menu-report can be the one for f3x. Let's put them in layout/sidebar/menus/f3x and layout/sidebar/menus/f1m

- [ ] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1tpwh5DbSF4CVjszSy05W5QzKPkVK5e1gglCpPrL0wcM/edit#gid=642826310)
- [ ] Save resolves on the Manage reports page
- [ ] Save and continue resolves on the Print preview page
- Changes made to existing contacts will be saved to the committee contact selected.
-
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@JonellaCulmer @mary-tcg 
Please Review and comment

**Comment by MitchellTCG** [comment]
@GreggMoreland 
New wires added
please review

**Comment by GreggMoreland** [comment]
@MitchellTCG A State Party should be required to still enter the three dates for Qualification, even though the five candidates are optional.  FEC instructions here: https://www.fec.gov/help-candidates-and-committees/filing-political-party-reports/multicandidate-status/

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @GreggMoreland the 5 candidates should NEVER be optional. State party committees will only ever qualify by affiliation per Ryan. The instructions make it look confusing, but we need to build it out so that if they choose Qualification, all dates AND all 5 candidates are required. 

Do NOT make any of the requirements based on what they choose for Type of Committee - that's out of scope for us.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @GreggMoreland the 5 candidates should NEVER be optional. State party committees will only ever qualify by affiliation per Ryan. The instructions make it look confusing, but we need to build it out so that if they choose Qualification, all dates AND all 5 candidates are required. 

Do NOT make any of the requirements based on what they choose for Type of Committee - that's out of scope for us.

**Comment by MitchellTCG** [comment]
Got it. I’ll update the qualification state only wires.

**Comment by MitchellTCG** [comment]
Per @AureliaKhorsand comments:
I got rid of the qualification state only collapsed and expanded.

@AureliaKhorsand @GreggMoreland 
do the wires above look correct now?

**Comment by GreggMoreland** [comment]
@MitchellTCG wire for 'Form 1M Qualification - Other expanded' has State checked and Candidate fields marked as optional

**Comment by MitchellTCG** [comment]
OK, I am updating some more. @AureliaKhorsand @GreggMoreland 

**Can both of you validate this statement:
If the Committee is a "State party," you can ONLY affiliate
But if the committee is "Other," you can affiliate or qualify.**

**Comment by AureliaKhorsand** [comment]
@MitchellTCG that's most likely true, but please do not build out any logic based on that, it is **not in scope** right now. The type of committee they select should not shoehorn them into any one way.

**Comment by MitchellTCG** [comment]
I have updated the wires again. I have not updated the logic. can this be moved to ADTQR

**Comment by MitchellTCG** [comment]
nevermind it already is
thx

**Comment by WiseQA** [comment]
@MitchellTCG @GreggMoreland

QA question was "Is it Multicandidate or Multi-Candidate - hyphenated or not".   See below link @MitchellTCG provided.

https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/multicandidate-status/

@GreggMoreland can you please update ticket name and Business Reason in AC for correct consistency.   Thanks !

**Comment by JonellaCulmer** [comment]
@WiseQA Multicandidate. Not hyphenated.

**Comment by WiseQA** [comment]
@JonellaCulmer Thank You !

**Comment by mjtravers** [comment]
@MitchellTCG There are fields in the wireframes for EMAIL and WEBSITE. I don't see those fields in the acceptance criteria and there are no fields defined in the spec for the F1M for them. Do those fields need to be removed from the wireframes or does the acceptance criteria need to be updated?

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mjtravers not sure where the EMAIL and WEBSITE fields came from. They should _not_ be included, and the ACs are correct.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Form 1M can be created and edited.   (Note:  EMAIL and WEBSITE in wireframes not testable as they should not be included on the Form 1M).

Select FORM 1M: Notification of Multicandidate Status from the "Create a new report" dropdown menu.

<img width="1133" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW5IQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab1b688c9be3137c4807af82dc18f834c5dcf099/image.png" alt="image.png" />
_____________________________________________________________________________________________________________________________

FORM 1M is displayed.

<img width="1183" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0hIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be6684ea91da569050ae2580696c2200fbbc01d0/image.png" alt="image.png" />
___________________________________________________________________________________________________________________________

Verify Type of Committee is a required fields "An answer is required."

<img width="267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK25IQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--608502ba42d77ffdeb2c9fecb88c1535036d2706/image.png" alt="image.png" />

_____________________________________________________________________________________________________________________________
Verify Status By is a required fields "An answer is required."

<img width="338" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3pIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ef594b3da0b022814e1b36607ccf5540faac960/image.png" alt="image.png" />

_____________________________________________________________________________________________________________________________
Select Status By radio button "Affiliation" Committee Lookup is displayed as required field (NOTE"  Qualification being built out in ticket #1555.)

<img width="932" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2ZIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c33c6f5f6165ef25c0f9c678d232940287f94365/image.png" alt="image.png" />

<img width="1109" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2pIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b68fb60d0dd0aeb0231af7476c92b5fdd968e4c2/image.png" alt="image.png" />

___________________________________________________________________________________________________________________________
Select the "Save" button verify the Manage reports page is displayed.  Verify Form 1M has been saved and displayed in the Manage reports table.

<img width="1049" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzdIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40f4f94f26c298e88dd34cc6c21794e81ac013a9/image.png" alt="image.png" />

____________________________________________________________________________________________________________________________

Select "Save and continue" button verify "Print preview" page is displayed.

<img width="938" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0RJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ceafa360a7726689916ef5541e71e6e8a553998b/image.png" alt="image.png" />

___________________________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
