### ISSUE TITLE
System to direct user to fec.gov (Form 1) to edit Committee Account data

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#130]
Business Reason

As a Committee Administrator, I will see instructions on the Committee Account page telling me to access fec.gov and resubmit a Form 1 to update any Committee Account information so that I can edit the information as needed if it changes.

Acceptance Criteria

***Given*** a Committee Administrator is on the Committee Account page (Profile > Account)

  ***Then*** I will see instructions directing me to resubmit Form 1 through FEC if edits are needed 

  ***And*** a link to my committee's most recently submitted Form 1

  ***And*** each link will open a new tab when clicked.

### QA Notes ###

_Note: Remove numerous "Edit" buttons._

For example: “You can view your committee's most recent Form 1 here: (link to most recent F1 on fec.gov for that committee). You can update your committee’s official information disclosed on Form 1 here. (Link:  https://webforms.fec.gov/webforms/form1/index.htm ).”

Dev Notes: 

- For the most recent Form 1 for a committee, pull the "pdf_url" from the following API call FOR EXAMPLE [https://api.open.fec.gov/v1/filings/?api_key=DEMO_KEY&sort=-receipt_date&per_page=1&page=1&cycle=2022&committee_id=C00344234&form_type=F1](https://api.open.fec.gov/v1/filings/?api_key=DEMO_KEY&sort=-receipt_date&per_page=1&page=1&cycle=2022&committee_id=C00344234&form_type=F1) 
- (LB Note): This endpoint (/filings/) is updated nightly. In order to get the most up-to-date data, we should also include a query to the raw/efile endpoints. These endpoints don't have as good filters though, so we'll need to loop through some of it on our own. Start with https://api.open.fec.gov/v1/efile/filings/?api_key=DEMO_KEY&committee_id=C00344234 and then get the most recent filing where `form_type` starts with F1. We can probably wait until we move this to the API. We can't just use efiling endpoint because it's only 3-4 months of data
- Need to create three FEC API keys, and also have public API keys and rate limit them by IP.
- Need to rename the existing API key to private

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1289](https://fecgov.atlassian.net/browse/FECFILE-1289)

**Comment by AureliaKhorsand** [comment]
@lbeaufort @RyanLanz This is the story for making sure users have the link to their committee's most recent Form 1 as well as the webform to update the Form 1. Can you provide us the links and/or link logic to use?

**Comment by RyanLanz** [comment]
Aurelia:

Here are the links/explanation, although Laura can probably provide additional information for the most recent F1.

Webform Form 1: https://webforms.fec.gov/webforms/form1/index.htm
Most Recent Form 1: https://docquery.fec.gov/pdf/539/202110149467253539/202110149467253539.pdf - This link changes for each committee.  The numbers in the link are what we call an image number and they are unique for each filing.  My assumption is that we have an API that pulls the most recent Form 1, but Laura can probably provide greater insight on that than I can.  We display the most recent F1 on a committee's profile page (example: https://www.fec.gov/data/committee/C00001313/?tab=about-committee).

**Comment by MitchellTCG** [comment]
here is the wire

![Account - READ ONLY_v3.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ef498aaf-9e08-4466-9f76-337f55947ddc)

**Comment by MitchellTCG** [comment]
Wireframe finalized and added. removing UX/UI attention needed.

**Comment by AureliaKhorsand** [comment]
**Comments from 3/29/22 Sprint Planning:** 

Options for additional form 1 link:
- Docquery link AKA https://docquery.fec.gov/pdf/439/202201069474878439/202201069474878439.pdf
- Statements of organization section: https://www.fec.gov/data/committee/C00344234/?tab=filings#statements
- About this committee page: https://www.fec.gov/data/committee/C00344234/?tab=about-committee

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 3/30/22**: Because we are not yet pulling committee data into FECFile Online, to test, we will need to manually create a Committee Account with a real Committee ID for testing. See example from Ryan above.

**Comment by PaulClark2** [comment]
@lbeaufort  if memory serves me, the efiling endpoint only has the most recent four months of data. If a committee's most recent F1 is older than that, how do we provide a link to it? Do we need need a way to check both the efiling and processed data endpoints for the most recent F1. Do we need to consider changing how we "prune" the efiling endpoint?

**Comment by mjtravers** [comment]
Passes code review. Sending to QA.

**Comment by WiseQA** [comment]
Verified when selecting "Update committee info using Form 1" the following screen appears:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/713bfbf6-76d4-4957-a9fb-8645f196763b)

Verified when selecting "View full committee info from Form 1" the following pdf of the most recent F1 filing is displayed.  Example using committee (C00277608) link  https://docquery.fec.gov/pdf/220/12030992220/12030992220.pdf

QA review completed.  Moved to Stage Ready.
