### ISSUE TITLE
4 - Allow user to View Loan guarantors assigned to a loan

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1300]
Business Reason

As a Committee Administrator, I will be able to see a table of guarantors associated with a loan and see the details of a guarantor so that I can accurately see the details of my loans.

 Acceptance Criteria

**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a **"Loan Received from Individual"**, **”Loan Received from Bank”**, or **”Loan by Committee”** transaction on an open report
**Then** I will see a table that lists all the guarantors associated with my loan with the following columns:

- Name (includes a link to view the guarantor record)
- Guaranteed financial information amount
- Actions (Edit)

**And** when I click on one of the guarantors in the list, I will review the following information for the guarantor selected:

 Guarantor 
#
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)
-	**EMPLOYER** (Required if **Amount** > $200)
-	**OCCUPATION** (Required if **Amount**  > $200)

# Guaranteed Financial Information 
#
-	**AMOUNT** (AMT-12, Required, can be negative)

---
**And** when I click on the 'Edit' action next to one of the guarantors in the list, I will be able to view and update the above information for the guarantor selected
**Then** I will be able to:
- Cancel
- Save & add loan guarantor
- Save (goes back to transactions table)

 Wireframes

**Schedule C with Guarantor table**
![1000 - Loan Received From Individual - with Gaurantor table.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0f6e6617-75f2-4e2e-9412-85b2aed3908e)

**When Guarantor in table is clicked or Edit action next to a guarantor is clicked**
![1012 - Guarantor – 1.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/94894812-32d2-4e95-b9b0-2d3f18f54d15)

### QA Notes ### 
  DEV Notes

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg what will it look like when they open the guarantor? Is it a modal pop-up? Can we have a wireframe of that? Also, what are the actions in the action kebab?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
complete and in ASA

**Comment by Elaine-Krauss-TCG** [comment]
The table is in pretty great shape (mechanically).  It needs CSS and HTML work, but the functionality is just about where it needs to be.  Since #1012 is still underway, I'm testing with Joint Fundraising Transfers instead of Loans.

Pictured below are two tables, one showing all children and one showing only Individual JF Transfer Memos.  Once #1012 is done, it will take all of five minutes to tweak the knobs to ensure that each of the Loan transactions has a table displaying their Loan Guarantors.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa05WIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--acb2eb187d4dcb007ddc318a62da578efc2791a2/image.png)

**Comment by Elaine-Krauss-TCG** [comment]
Used work from #1300 to verify that #1012 is working
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVJnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e17bf1d09dcea00743a1002eba544a531133aa8a/image.png)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified once Guarantors are created can view.  (Note: "Loan Received from Individual", ”Loan Received from Bank”, and ”Loan by Committee” were all tested)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcE55IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f6ec24a6836ad72ddbe3511713eefd01ac6e0d4a/image.png)

(Note:   Table format and display will be updated in a future ticket per DEV)

QA Review Completed.   Moved to Stage Ready.
