### ISSUE TITLE
Loan Received from Individual Receipt (Step 2) Purpose of Receipt (Optional) and Note or Memo Text (Optional) fields are Read-Only where they should be editable and savable.

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1302]
During testing the Loan Received from Individual Receipt (Step 2) Purpose of Receipt (Optional) and Note or Memo Text (Optional) fields are Read-Only where they should be editable and savable.  Bug found in preparing for Sprint 28 demo of ticket #1002.  (Note:  Previous test showed this functionality working, as documented in ticket #1002.)

Steps to recreate bug.

1.  Create Loan Received from Individual.
2.  Select Auto-Populated (step 2) to create Loan Received from Individual Receipt.
3.  Purpose of Receipt (Optional) and Note or Memo Text (Optional) should be editable and savable.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f9f7d9ae-ef17-435c-97cd-1ff9d0413ff6)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8d11ab4d-2902-4db7-a063-e6ba38166b30)

**4.   Change Date Received > Date on Loan Received from Individual Receipt (Step 2)**
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2b01b5f6-3bab-427d-b355-9c3f7ab7d02c)

@MitchellTCG @mjtravers make Purpose of Receipt (Optional) and Note or Memo Text (Optional) editable and savable.  Currently displaying as read-only.   Bug fix pointed as a 2 pt. fix.

### QA Notes ### 
 null
### DEV Notes ### 
 **Note:   The **Note or Memo Text (Optional)** field on the **Loan Received from Individual** transaction page is linked to Step 2 (Receipt) and filling in Note or Memo Text (Optional) field.   This should not happen.**   

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/400a26f1-8c2b-482b-9422-9c432125511a)
### Design ### 
 null

**Comment by mjtravers** [comment]
The inheritedFields array that manages copying the values from the LOAN RECEIVED FROM INDIVIDUAL to the RECEIPT in STEP 2 was erroneously updated with a recent commit. That has been fixed. In addition the DATE RECEIVED for the receipt was changed to DATE.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified both bugs documented in this ticket are fixed and **PASSED**.

QA review verified Purpose of Receipt (Optional) and Note or Memo Text (Optional) are editable and savable after creating a "Loan Received from Individual Receipt (Step 2).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2b85fc80-c1cd-48da-932b-6dda8e077c80)

Verified second fix in bug  Date Received changed to Date on Loan Received from Individual Receipt (Step 2)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9993f235-9f6b-4ad5-9f6a-b079fdd6d3de)

QA Review Completed.   Moved to Stage Ready.
