### ISSUE TITLE
UI: Remove Contact Type dropdown carrot from Schedule B transactions with single entity selection

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1308]
Business Reason

As a user, I will be able to see only a single Contact Type entity without the appearance of a lookup dropdown for all Schedule B transactions which have only one entity type so that I can see there is no selection required.

Acceptance Criteria

***Given*** I am a user editing an open Form 3X report

  ***When*** I create one of the Schedule B (Disbursement) transactions with only one entity selection

  ***Then*** I will no longer see the lookup dropdown indicator on the Contact Type field

Wireframe

  ![1256-Wire.jpg]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/bb3c523e-b07e-4657-9394-c7b214c5dff0](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/bb3c523e-b07e-4657-9394-c7b214c5dff0))

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
Dropdown icon is dynamic and can be assigned in template 
```[dropdownIcon]="options.length > 1 ? 'pi pi-angle-down' : 'none'"```
Schedule B Transactions with a single contact type which will need to be changed:

- [ ] Credit Card Payment for Operating Expenditure
- [ ] Payment to Payroll for Operating Expenditure
- [ ] Credit Card Payment for Other Disbursement
- [ ] Payment to Payroll for Other Disbursement
- [ ] Staff Reimbursement for Operating Expenditure 
- [ ] Staff Reimbursements for Other Disbursements
- [ ] Transfers to Affiliates/Other Committees
- [ ] Contribution to Candidate
- [ ] Void of Contribution to Candidate
- [ ] Non-contribution Account Credit Card Payment 
- [ ] Non-contribution Account Payment to Payroll
- [ ] Non-contribution Account Staff Reimbursement
- [ ] Individual Refund - National Party Headquarters Buildings Account
- [ ] Individual Refund - National Party Pres. Nominating Convention Account 
- [ ] Individual Refund - National Party Recount/Legal Proceedings Account
- [ ] Tribal Refund - National Party Headquarters Buildings Account 
- [ ] Tribal Refund - National Party Pres. Nominating Convention Account 
- [ ] Tribal Refund - National Party Recount/Legal Proceedings Account
- [ ] Other Committee Refund - National Party Headquarters Buildings Account 
- [ ] Other Committee Refund - National Party Pres. Nominating Convention Account 
- [ ] Other Committee Refund - National Party Recount/Legal Proceedings Account
- [ ] Refund of Party Contribution 
- [ ] Refund of Party Contribution - Void 
- [ ] Refund of PAC Contribution 
- [ ] Refund of PAC Contribution – Void
- [ ] Refund of Unregistered Receipt from Person 
- [ ] Refund of Unregistered Receipt from Person – Void
- [ ] Credit Card Payment for 100% Federal Election Activity
- [ ] Payment to Payroll for 100% Federal Election Activity
- [ ] Staff Reimbursement for 100% Federal Election Activity
- [ ] In-Kind Out (from In-kind Receipt on Schedule A)
- [ ] PAC In-Kind Out (from PAC In-kind on Schedule A)
- [ ] Party In-Kind Out (from Party In-kind  on Schedule A)
- [ ] In-Kind Transfer Out (from In-kind Transfer on Schedule A)
- [ ] In-Kind Transfer FEA Out (from In-kind Transfer - Federal Election Activity on Schedule A)
- [ ] Conduit Earmark Out (from Conduit Earmark on Schedule A)
- [ ] PAC Conduit Earmark Out (from PAC Conduit Earmark on Schedule A)

### Design ###
null

[FECFILE-641](https://fecgov.atlassian.net/browse/FECFILE-641)

**Comment by WiseQA** [comment]
@GreggMoreland Thank You !

**Comment by mjtravers** [comment]
Add Schedule C1, Loans from Bank needs the carrot removed from the C1 record.

**Comment by toddlees** [comment]
No code change. moving to QA

**Comment by WiseQA** [comment]
QA review verified "carrot" was removed from the Schedule B transactions, transactions list above, for a single entity selection. Screenshot of Credit Card Payment for Operating Expenditure below showing "carrot" removed.

<img width="1201" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWpKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d868fc0eae165b828313327a5d9892a1fad8d39f/image.png" alt="image.png" />
__________________________________________________________________________________________

Verified Schedule C1, Loans from Bank "carrot" was removed per DEV comment above.

<img width="1187" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWZKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2086fb77165b2207e611de4deacf88d4bf114dc/image.png" alt="image.png" />
_________________________________________________________________________________________
QA Review Completed.   Moved to Stage Ready.
