### ISSUE TITLE
Primeng 16.1.0 upgrade breaks left navigation menu

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1311]
The jump from Primeng 16.0.2 to 16.1.0 starts showing the down caret icon in our left navigation. See image:

![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/55e56182-2ed0-4abb-983c-d3e7e99677ac)

The menu needs to be restore to its previous display with sizing and without the caret.

NOTE: The version of Primeng is being held at 16.0.2 until this ticket is completed.

### QA Notes ### 
 - Visual check
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
Local with the changes made:
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/43e7dbe1-0170-4cd9-b741-5fae7f6314b6)

DEV on PrimeNG 16.0.2
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/ab52628a-1a65-4d1b-9cd9-841af8f69f0c)

**Comment by Elaine-Krauss-TCG** [comment]
Scratch that, my fix for the chevrons in the sidebar *also* broke the chevrons in the date picker...

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified left navigation is displaying correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b813160e-0516-4c91-b744-ba0c1cf568c0)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a40ebfad-667a-4509-918a-f2978659d1d2)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7de52ce9-c5d9-4d39-84d0-ea19951a9e10)

QA Review Completed.  Moved to Stage Ready.
