### ISSUE TITLE
When submitting a first time report the user can submit without Cash On Hand

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1314]
During testing verified when submitting a first time report the user can submit without Cash On Hand (reference ticket #196 for original requirements). (Note: if you reference #196 scroll to the bottom of ticket for the updated wireframes as this ticket changed a lot.)

Steps to reproduce:

**1\. Create new report**

[![](https://github.com/fecgov/fecfile-web-app/assets/110493670/1cf11153-b80c-43d0-afd4-ebbd7eabf60d)](https://github.com/fecgov/fecfile-web-app/assets/110493670/1cf11153-b80c-43d0-afd4-ebbd7eabf60d)

**2\. Cash on hand page will display. Select the "Skip for now" button**

[![](https://github.com/fecgov/fecfile-web-app/assets/110493670/ded62252-86ce-4da1-aaf8-674b9a3b7c95)](https://github.com/fecgov/fecfile-web-app/assets/110493670/ded62252-86ce-4da1-aaf8-674b9a3b7c95)

**3\. Enter transactions (if needed). Select "Submit Report"**

[![](https://github.com/fecgov/fecfile-web-app/assets/110493670/8243cb39-a6c0-42ba-bc27-6ef763050427)](https://github.com/fecgov/fecfile-web-app/assets/110493670/8243cb39-a6c0-42ba-bc27-6ef763050427)

**4\. Warning popup "Are you sure?" is not displaying. User can submit a report without Cash On Hand**

[![](https://github.com/fecgov/fecfile-web-app/assets/110493670/d87d63df-7f5a-46b3-ab40-325c1644d3a1)](https://github.com/fecgov/fecfile-web-app/assets/110493670/d87d63df-7f5a-46b3-ab40-325c1644d3a1)

[![](https://github.com/fecgov/fecfile-web-app/assets/110493670/d1f0147d-b975-48dd-a03f-e5f13ab0723b)](https://github.com/fecgov/fecfile-web-app/assets/110493670/d1f0147d-b975-48dd-a03f-e5f13ab0723b)

@MitchellTCG @mjtravers defect to fix Cash On Hand is required before submission of first time report. Defect added to Sprint 30\. Defect 3pt fix. /

### QA Notes ###
 
 null

### DEV Notes ###
 
 null

### Design ###
 
 null

 See full ticket and images here: [FECFILE-639](https://fecgov.atlassian.net/browse/FECFILE-639)

**Comment by Elaine-Krauss-TCG** [comment]
The back-end will no longer allow the user to submit a report when no Cash on Hand Date has been provided for _any_  of their committee's reports.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcW9uIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--76a221c876b10c6c1e60d65c794acd6f279c2792/image.png)

Several questions and one error have arisen now that this has been implemented:

1. What are the exact requirements re: cash-on-hand for submission?  Do they need to do it for one report _ever_, or one per year, or something else?
2. How do we want to display the error to the user?  How do we want to phrase it?

And the error:
 - Cash-on-Hand cannot be added to already submitted reports, and it can't be added to reports of later dates.  If the earliest possible report has been erroneously submitted without Cash-on-Hand, the user is soft-locked.  They're unable to submit later reports and unable to rectify the situation without creating a new earliest report in which to save Cash-on-Hand.

**Comment by AureliaKhorsand** [comment]
During discussion at Sprint 29 planning Ryan indicated that this is actually ok for Form 3X. BAs need to do more analysis to determine how to move forward, or if we do. Moving back to AA.

**Comment by AureliaKhorsand** [comment]
Complete COH redesign first
