### ISSUE TITLE
System to prevent user from creating or amending a report if there is a report with 'Submission Pending' status

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1327]
Business Reason

As a Committee Administrator, I will not be able to create a new report or amend a previous report when there is a report with a Submission Pending status so that I can track my committee's transactions without any errors.

Acceptance Criteria

***Given*** I am a Committee Administrator

  ***When*** I click the function to create a new report

  ***And*** I have an earlier report that has a 'Submission Pending' Status

  ***Then*** I will receive a message that will prevent me from creating a new report until the previous submission is final.

—

  ***Given*** I am a Committee Administrator

  ***When*** I click the function to amend a report

  ***And*** I have an earlier report that has a 'Submission Pending' Status

  ***Then*** I will receive a message that will prevent me from amending a report until the previous submission is final.

### QA Notes ###
- [ ] BA/Design Quality Checklist complete

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-645](https://fecgov.atlassian.net/browse/FECFILE-645)

**Comment by AureliaKhorsand** [comment]
@toddlees @mjtravers is this something we want to recommend to FEC? This was originally created because data in reports was going to be "frozen" and we didn't want a report to end up failing with another report created after it. However, since data is going to remain fluid even in closed reports, is this relevant? What technical considerations are there for implementing this or not, if any?

**Comment by toddlees** [comment]
@AureliaKhorsand @GreggMoreland This doesn't seem like a need any longer if there is no freezing of data.  submitting a report will not cause any issues for new reports and vice versa

**Comment by AureliaKhorsand** [comment]
Sounds good. Closing this as OBE since we are no longer freezing report data.
