### ISSUE TITLE
UI: Replace all lookup labels with 'LOOKUP' on all transactions

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1329]
Business Reason

As a user, I will be able to see 'LOOKUP' instead of 'CONTACT LOOKUP', 'CONTACT TYPE', 'LENDER LOOKUP', 'LENDEE LOOKUP > LOOKUP' or anything else, before each transaction lookup so that I can see a consistent view with each lookup.

Acceptance Criteria

***Given*** I am a user

  ***When*** I create a new transaction of any type

  ***Then*** I will see the 'LOOKUP' header above the Lookup function on any transaction

Wireframe

  (This is an example wireframe of how the label should look on any given ticket)
[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmFlIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--58fcde40156e67775c95a3f036a2ab8601741632/Screenshot%202023-09-14%20at%2010.53.04%20AM.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmFlIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--58fcde40156e67775c95a3f036a2ab8601741632/Screenshot%202023-09-14%20at%2010.53.04%20AM.png))

### QA Notes ###
LOOKUP all CAPS (use checkbox list from DEV)

### DEV Notes ###
- [x] CONTACT LOOKUP > LOOKUP
- [x] CONTACT TYPE > LOOKUP
- [x] LENDER LOOKUP > LOOKUP
- [x] LENDEE LOOKUP > LOOKUP
- [x] ENTITY LOOKUP > LOOKUP
- [x] GUARANTOR LOOKUP  > LOOKUP

### Design ###
null

 See full ticket and images here: [FECFILE-1374](https://fecgov.atlassian.net/browse/FECFILE-1374)

**Comment by alexander-lin** [comment]
From Mitchell: "Make a ticket to change ALL lookups from contact type, lender lookup, or anything else to “LOOKUP.” Jonella has blessed this update. [This ticket is] 1329. 

[Until 1329 is done,] pass all tickets with whatever is currently coded on the page.

Please have the team point the ticket...and ensure it is in Sprint 31."

**Comment by alexander-lin** [comment]
Mary will create a quick wireframe for this ticket.

**Comment by GreggMoreland** [comment]
Updated title and business reason and added checklist of each variable I have found which need to be changed. Clarified that the label should be ALL CAPS to match all other field labels.

**Comment by mary-tcg** [comment]
Wire updated

**Comment by andrew-bowers-tcg** [comment]
Code complete and ready for review.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the lookup labels have been changed (a few screenshots shown for verification of change):

- [x] CONTACT LOOKUP > LOOKUP
- [x] CONTACT TYPE > LOOKUP
- [x] LENDER LOOKUP > LOOKUP
- [x] LENDEE LOOKUP > LOOKUP
- [x] ENTITY LOOKUP > LOOKUP
- [x] GUARANTOR LOOKUP  > LOOKUP

Screenshot of what was changed - CONTACT TYPE > LOOKUP to show change. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdk9vIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d4810409b98c171222726b55e36e22fc93426b76/image.png)

Screenshot of what was changed - LENDER LOOKUP > LOOKUP to show change. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlNvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4a3d9704e3cca80cce9cde5616e55a1e7e039f75/image.png)

Screenshot of what was changed - GUARANTOR LOOKUP > LOOKUP to show change. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdldvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c7a3b1719c97bd33f965cf7001360d07573caf02/image.png)

QA Review Completed.  Moved to Stage Ready.

**Comment by WiseQA** [comment]
@MitchellTCG as long as you are good with layout the LOOKUP passes QA testing
