### ISSUE TITLE
Allow user to review and edit ADDRESS and see MULTICANDIDATE STATUS: (Create Form 3X-Part 2)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#133]
Business Reason 
 

As a Committee Administrator, I will be able to review and edit your committee’s address and review your multi-candidate status

 Technical Notes 

- When saving this record, the FORM_TYPE field must have "F3XN" value in the new table record. See [F3X spec](https://fecgov.github.io/fecfile-validate/F3X_spec.html)

- Each time this screen is opened, a new pull from the FEC API endpoint needs to be made to display the most recent form information in case the user has submitted a FORM 1 and had it processed since the last time this info was refreshed for the committee account

 Acceptance Criteria 
 

# Path A 
#
**Given** I am a Committee Administrator or Backup Committee Administrator
**When** I have created a new Form3X report for my committee
**Then** User will decide if they need to update their address
IF **NO**...
**Then** the user will review their multicandidate status (only visual, can not be changed)
**And** I will be able save the report and see it from the report management page.

# Path B 
#
**Given** I am a Committee Administrator or Backup Committee Administrator
**When** I have created a new Form3X report for my committee
**Then** User will decide if they need to update their address
IF **YES**...
**Then** the user will see there current address of the committee in editable textbox
**And** have the ability to edit the address
**Then** the user will review their multicandidate status (only visual, can not be changed)
**And** I will be able save the report and see it from the report management page.

 Dev Notes 

-- Committee Type Q if qualified, Committee Type N if not qualified. 
-- https://api.open.fec.gov/developers/#/committee/get_committee__committee_id__ (see committee_type)

For Committee status:
_text:_
This committee has qualified as a multicandidate committee.
OR
This committee has not qualified as a multicandidate committee.
_link:_
Learn more about multicandidate committee status
[ https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/multicandidate-status/ ]

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
Note from PI 2 Planning: Per Ryan, election/non-election year determines what report types are selectable. Our app can default to the right one. Specifying helps users understand what they need to file. Don't HAVE to have them select election or non-election year - can default. But users need the option to select, however. If a committee is overdue on a report, would need to go back and select another one.

**Comment by MitchellTCG** [comment]
Mocks in fecfile-project-management#42
[mocks here](https://github.com/fecgov/fecfile-project-management/issues/42)

**Comment by MitchellTCG** [comment]
Here are the prototypes:

https://images.zenhubusercontent.com/306118986/8e43c54a-72fb-4312-b9f5-837ff91b35ed/fec_form_3x_memo.mp4


https://images.zenhubusercontent.com/306118986/88e8c282-2c42-423f-b655-c1e4a68d61a0/fec_form_3x_multi.mp4

**Comment by MitchellTCG** [comment]
Here are the wireframes:

![FEC Form 3X-Main.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0c58ffef-f82a-456c-97cc-4b4a90abb356)

![FEC Form 3X-Address.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/1ea9a6bf-f03f-45ea-ab25-3feb06cdd665)

**Comment by MitchellTCG** [comment]
Here are the wireframes:

![FEC Form 3X-Main.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0c58ffef-f82a-456c-97cc-4b4a90abb356)

![FEC Form 3X-Address.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/1ea9a6bf-f03f-45ea-ab25-3feb06cdd665)

![FEC Form 3X-Memo.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/171f8a56-7e13-4897-8705-0e1c6e285c9f)

**Comment by MitchellTCG** [comment]
For Committee status:

text:
This committee has qualified as a multicandidate committee.  

link:
Learn more about multicandidate committee status 
[ https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/multicandidate-status/ ]

**Comment by WiseQA** [comment]
Ticket fails - "NO" Radio button staying selected after "Save and Continue" broken.  Selecting "Save" is broken.   Per conversation with @mjtravers put back to In-Progress

**Comment by WiseQA** [comment]
Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/0a22ab3c-214f-4eae-9673-35a66b40dacb/download](https://app.zenhub.com/files/306118986/0a22ab3c-214f-4eae-9673-35a66b40dacb/download)

QA review completed.  Moved to Stage Ready.
