### ISSUE TITLE
When creating a new contact the "Required Field" text boxes are displaying in red upon New Contact page being displayed.

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1332]
During testing when creating a new contact the "Required Field" text boxes are displaying in red upon New Contact page being displayed. This bug was found when testing Contribution to Candidate (Schedule B) in Sprint 30.

This bug works the same way if you have an Individual transaction or tier transaction.

The steps below is what is being displayed if you are viewing the Contribution to Candidate transaction.

1\. Under Committee/Candidate information if the required field example "Candidate information is required"

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0F2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5bcb8dd36bb56c9de5049fb393ba29fca5a7e7d5/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0F2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5bcb8dd36bb56c9de5049fb393ba29fca5a7e7d5/image.png))

2\. Select "Create a new contact"

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2t2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ff7a87b59be24f5015ab80b5c3cd4f6de1bf54a3/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2t2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ff7a87b59be24f5015ab80b5c3cd4f6de1bf54a3/image.png))

3\. Create a new contact page is displayed and the required fields are highlighted in red, (This is the bug error)

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3N2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4f1017a5f0c082ef7bcdbfa8d8c16905f6f0dd60/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3N2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4f1017a5f0c082ef7bcdbfa8d8c16905f6f0dd60/image.png))

4\. If you select the "Save & continue" button the required fields are highlighted in red with the correct notification "This is a required field" is working correctly.

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcE12IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9059718ba1ca91994002a670e23743d0341eaf90/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcE12IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9059718ba1ca91994002a670e23743d0341eaf90/image.png))

@toddlees @mjtravers @MitchellTCG the bug is to fix the required fields highlighted in red on the contact page when creating a new contact for any transaction. Pointed bug at 3 pts.

Note: This also happens if you have an individual transaction with a contact already created on the transaction page then select "Create a new contact" the same bug appears.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-637](https://fecgov.atlassian.net/browse/FECFILE-637)

**Comment by WiseQA** [comment]
After discussion with DEV this Bug will take more effort.   Per consensus changed from 3 Pts. to 5 Pts.

**Comment by alexander-lin** [comment]
Given what we heard from Todd yesterday (i.e. some regression risk, more complex than the original 3 pointers), let's move this back into ASA and discuss as a team alongside other potential S31 priorities.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG per discussion moved ticket to In-Progress, needs to go through Unit Tests and Code Review on changes made.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review tested using Contribution to Candidate (Schedule B) transaction.  

1  Under Committee/Candidate information if the required field example "Candidate information is required"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGUxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4d816fba0955bec0c254faf48f02640efa4b7e24/image.png)

2.  Select "Create a new contact"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHkxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cf086e1d6e459ac79efc203688452eed4a13073b/image.png)

3.  Create a new contact page is displayed and the required fields bug has been fixed.  NO fields are highlighted in red,

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDYxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fdb96bbb3d66fc6de0600d148265c8848393aa14/image.png)

4.  Retested -  If you select the "Save & continue" button the required fields are highlighted in red with the correct notification "This is a required field" is working correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUsxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3b7da09a9d6a1a999bf71bfdeb8512e5081ee52f/image.png)

@mjtravers @MitchellTCG the "Search for contact" box is still highlighted in red.   There is NO required field error message required for this field.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkcxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--36fa205b00d43bf6c29acee86da055cbbda4fd03/image.png)

**Comment by WiseQA** [comment]
QA review rested the 4 QA steps above - all PASSED.

QA review the "Search for contact" box is NOT highlighted in red when other fields displaying "This is a required field". There is NO required field error message required for this field.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjI5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--52e970f60cc4f31cf01da5e6f9001e8920468be0/image.png)

QA Review Completed.   Moved to Stage Ready.
