### ISSUE TITLE
Create Angular model for Form 1M

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1334]
Following the same pattern as was created for the Form 24, create a Form 1M class to manage the data for a Form 1M record.

 DEV Tasks: 

- Create a f1MReport class that extends the Report class

### QA Notes ### 
 
There will be a unit test that can be reviewed verifying the correctness of the Form 1M model code. A screenshot can be provided.

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
Unit tests for QA: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/4110/workflows/c2473a91-d781-46dd-8f68-3d8aa1a6ac5e/jobs/14819
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnpVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--717630c630c24cbb6ba9c0c006f4c1661a4a291e/image.png)

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of Unit Test passing as denoted in app.circleci per DEV.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenJaQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f64f3adca506a9cf83426e23c4b7e58e45c80ec/image.png)

QA Review Completed. Moved to Stage Ready,
