### ISSUE TITLE
Allow user to submit Form 1M report 

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1337]
Business Reason

As a user, I will be able to submit a completed Form 1M report so that I can generate a *.fec file and send it to the FEC.

Acceptance Criteria

***Given*** the Form 1M report includes all required information

  ***Then*** there will be the pages "Confirm information" and "Submit report" under the SIGN & SUBMIT section of left-hand navigation

***and when*** a user is on the "Confirm information" page, they will enter the following information:

*   ***EMAIL #1*** (Required)
*   ***Email #2*** (OPTIONAL)

***And when*** a user is on the "Submit report" page, they will enter the following information:

1.  Treasurer Information 
      1.  UX Comment

             We will not change the general look and feel. No new grey box. we will add in illustration instead of old fan of 5 pages

1.  1.  Wireframes

Confirm info
[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGdOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37cf3f33214be862fa03921e260343dafbef39bd/1337%20Confirm%20info.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGdOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37cf3f33214be862fa03921e260343dafbef39bd/1337%20Confirm%20info.png))

Submit report
[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGtOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93778d439cc05641cf9c605627e3d1ab9db247b5/1337%20submit%20report.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGtOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93778d439cc05641cf9c605627e3d1ab9db247b5/1337%20submit%20report.png))

Are you sure?
[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHNOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59aae90d407d3decbf7e6a7c8b6e562d1f6c9f9d/1337%20submit%20report%20%E2%80%93%20Are%20you%20sure.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHNOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59aae90d407d3decbf7e6a7c8b6e562d1f6c9f9d/1337%20submit%20report%20%E2%80%93%20Are%20you%20sure.png))

1.  Congratulations
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVFjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2a73e0bd52d9459870d7a87dda29ba99a748029/1337%20Congratulations.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVFjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2a73e0bd52d9459870d7a87dda29ba99a748029/1337%20Congratulations.png))

1.  Processing
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVljQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d6a6927ca06823b88c44608c8006ff43137a89f/1337%20processing.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVljQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d6a6927ca06823b88c44608c8006ff43137a89f/1337%20processing.png))

### QA Notes ###
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

- **ELECTRONIC FILING PASSWORD** (Required)

**Then** they will be required to check the box with the following text before being able to submit:

> I certify that I have examined this Statement and to the best of my knowledge and belief it is true, correct, and complete. NOTE: Submission of false, erroneous, or incomplete information may subject the person signing this Statement to the penalties of 52 U.S.C. § 30109.

**And** when the user clicks "Submit", they will receive a confirmation popup with the following language: 

> Are you sure you want to submit this form electronically? Please note that you cannot undo this action. 

**And** when the user confirms submission
- the user will be redirected to the "Report status" page with an indication of submission.
- the following will be auto-populated within the *.fec:
--	**COMMITTEE NAME** (Required, System populated)
--	**STREET ADDRESS** (Required)
--	**APARTMENT, SUITE, ETC.** (Optional)
--	**CITY** (Required)
--	**STATE/PROVINCE** (Required)
--	**ZIP/POSTAL CODE** (Required)
-- **DATE SIGNED** (Required)

## QA Notes ##
- [x] BA/Design Quality Checklist complete

## DEV Notes ##

Let's refactor the submit-f3x-step1 (call it submit-confirm-info), submit-f3x-step2 (call it submit-report), and submit-f3x-status (call it submit-status) components into a new reports/shared directory. Each component will have it's own directory in the reports/shared directory.

- DATE SIGNED in the specification should work like it does on Form 3X, and populate when the user confirms submission.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-633](https://fecgov.atlassian.net/browse/FECFILE-633)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Please review

**Comment by MitchellTCG** [comment]
Report Status added
@GreggMoreland 
Please review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
When submitting, the fec file has a bad date format and is missing the date signed:
<img width="582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnZJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e79687c9aab9c9df9ddc22adb6a50789ab12b737/image.png" alt="image.png" />

The produced fec file is attached

___________________________________________________________________________________________________________________________
@mjtravers when selecting "Warnings" tab from fec file below is attached what warning is displayed:

<img width="1130" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWZJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db63ed7dcdc6160701ab7478a8ca711faa6db771/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG "Are you sure?" verbiage in popup is incorrect.   Change verbiage to below screenshot as denoted in above wireframe for Form 1M.

<img width="504" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2JJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fcd21c2218b880bdb986eb4b8c8f514472659671/image.png" alt="image.png" />

**Comment by MitchellTCG** [comment]
@mjtravers
Please change pop up to the text Shelly just just posted above.

**Comment by WiseQA** [comment]
QA verified popup Are you sure?" verbiage in popup was changed to below screenshot as denoted in above wireframe for Form 1M.

<img width="887" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHpKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e5c5c4be121ce53096fb26357352d8e9417b32d/image.png" alt="image.png" />

_____________________________________________________________________________________________________________________________
Issues with submission still being worked as stated above.   "When submitting, the fec file has a bad date format and is missing the date signed:"

**Comment by mjtravers** [comment]
The schema for the F1M fec file was updated to fix the error messages coming up in WebCheck. Also, the text to the submit pop-up was updated. Ready to retest on STAGE.

**Comment by WiseQA** [comment]
QA review verified Form 1M report "Submission success".

<img width="1206" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEhKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef0cfc1003a6b29b516da34320da6517afbbe5c6/image.png" alt="image.png" />

____________________________________________________________________________________________________________________________
Email received confirming filling and accepted 

<img width="871" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFBKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2d6c0e148f8e6daf23e80a1c13b6e29d9b8beb9/image.png" alt="image.png" />

_____________________________________________________________________________________________________________________________

Webcheck validation

<img width="1074" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGpKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5829a277cd271f290146e8f956873086ec602ac4/image.png" alt="image.png" />


_____________________________________________________________________________________________________________________________

Submission displayed correctly on the FEC Electronic Filings

<img width="1117" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFRKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f858dcb40d555ee074463c3878e77734b26ffac/image.png" alt="image.png" />
_____________________________________________________________________________________________________________________________

Verified Manage reports table updated showing Form 1M Successful Submission

<img width="1166" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG5KQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee283a6cdbc7371abb3d7471dc6f8b4fd355a84d/image.png" alt="image.png" />

_____________________________________________________________________________________________________________________________

QA Review Completed.    Moved to Stage Ready.
