### ISSUE TITLE
Allow user to create a Form 3X report  and specify report type (Form 3X Line 4)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#135]
Business Reason

As a Committee Administrator, I will be able to create a Form 3X report and specify the report type for Form 3X so that, along with coverage date, I will be able to save a Form 3X report record for my Committee Account.

Acceptance Criteria

***Given*** I am a Committee Administrator

  ***When*** I create a new Form 3X report

  ***Then*** I will be ***required*** to select a report type with the following logic:

*   If Committee has a MONTHLY Filing frequency: 
      *   And creates a report for an ELECTION YEAR: 
            *   M2 February 20 Monthly
        *   M3 March 20 Monthly
        *   M4 April 20 Monthly
        *   M5 May 20 Monthly
        *   M6 June 20 Monthly
        *   M7 July 20 Monthly
        *   M8 August 20 Monthly
        *   M9 September 20 Monthly
        *   M10 October 20 Monthly
        *   12G 12-Day Pre-General
        *   30G 30-Day Post-General
        *   YE Year End
        *   TER Termination
    *   And creates a report for a NON ELECTION YEAR: 
            *   M2 February 20 Monthly
        *   M3 March 20 Monthly
        *   M4 April 20 Monthly
        *   M5 May 20 Monthly
        *   M6 June 20 Monthly
        *   M7 July 20 Monthly
        *   M8 August 20 Monthly
        *   M9 September 20 Monthly
        *   M10 October 20 Monthly
        *   M11 November 20 Monthly
        *   M12 December 20 Monthly
        *   YE Year End
        *   TER Termination
*   If Committee has a QUARTERLY Filing frequency: 
      *   And creates a report for an ELECTION YEAR: 
            *   Q1 April Quarterly
        *   Q2 July Quarterly
        *   Q3 October Quarterly
        *   12G 12-Day Pre-General
        *   30G 30-Day Post-General
        *   YE Year End
        *   12P 12-Day Pre-Primary
        *   12R 12-Day Pre-Runoff
        *   12S 12-Day Pre-Special
        *   12C 12-Day Pre-Convention
        *   30R 30-Day Post-Run-Off
        *   30S 30-Day Post-Special
        *   TER Termination
    *   And creates a report for a NON ELECTION YEAR: 
            *   MY Mid-Year
        *   YE Year-End
        *   12P 12-Day Pre-Primary
        *   12R 12-Day Pre-Runoff
        *   12S 12-Day Pre-Special
        *   12C 12-Day Pre-Convention
        *   30R 30-Day Post-Run-Off
        *   30S 30-Day Post-Special
        *   TER Termination

it was 8 storypoints

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1286](https://fecgov.atlassian.net/browse/FECFILE-1286)

**Comment by MitchellTCG** [comment]
Here are 5 mocks related to this ticket

![Monthly report save.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/14437f63-dc4a-4886-93ed-57e5e98a2d02)

![Quarterly report save.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d87e33df-e087-4deb-88a4-4b4dc76c9ce9)

![12-Day Pre-Election Save.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/6ca64b11-4abd-4699-b29b-b0783d85432e)

![30-Day Post-Election Save.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/fdf173b7-ce68-4949-a550-f178bceec062)

![Termination Save.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8ae6d3b9-5412-401a-ab26-f21626180e64)

**Comment by MitchellTCG** [comment]
Most up-to-date wires:
![Monthly - Election Year.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a018beeb-8112-4dcd-abe6-ce4e89429568)

![Monthly - Non-election Year.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/03391a89-858a-42bf-90b9-b18244759d13)

![Quarterly - Election Year.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/2ffa03ec-4a10-4d3b-8946-f8e0b20b86b9)

![Quarterly - Non-election Year.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/98d1fe4d-6b73-4557-8baf-6707fc6b7d8a)

![Quarterly - Special Reports.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a3e23e8c-7ec0-4273-a913-96ab133dc38e)

![Quarterly - Election Year - 12 Day General.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/704bf866-7700-4bc0-a3d2-1396771eafb8)
