### ISSUE TITLE
 "Loan Received from Bank" transaction under "Actions" the "Review loan agreement" page is displaying incorrectly on DEV

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1365]
QA review verified when selecting the "Actions" dropdown from "Loan Received from Bank" transaction the "Review loan agreement" option is displayed and selectable and the "Loan Agreement" page is displayed as shown below.   (Tested on STAGE)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2FRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0a4596b9810f187824f231ebbb3c554322f5245d/image.png)

1.   The "Loan Agreement" page is displaying correctly on Stage (see above screen).
2.   When selecting the "Actions" dropdown from "Loan Received from Bank" transaction the "Review loan agreement" option on DEV the incorrect page is being displayed "Loan Repayment Made"
  
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3VRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7266c1da8a5d502fbec3f01b1f86aa88e25097dc/image.png)

3.   Note:   Working correctly on STAGE - broken on DEV after Sprint 30 deployment.
4.   Note:   Tested and passed in ticket #1186 (Sprint 30) see QA notes.

@mjtravers @Mitchell Jarrett fix page being displayed  "Review loan agreement" on DEV.  Created Bug for DEV assigned to In-Progress and pointed 3 pts.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by toddlees** [comment]
passes CR moving to QA

**Comment by WiseQA** [comment]
QA review verified the bug fix has been implemented for displaying the Loan Agreement page after selecting the "Actions" dropdown from "Loan Received from Bank" transaction then "Review loan agreement" option.   Tested bug fix on DEV only.  (Note:  STAGE was not broken or had this bug)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVdZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--be09685348089b34968c5eabc5bc1b017e8e5c50/image.png)

QA Review Completed.   Moved to Stage Ready.
