### ISSUE TITLE
Remove 'force itemize/unitemize' function from Schedule C and Schedule D transactions

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1366]
Business Reason

As a user, I should NOT be able to force itemize/unitemize Schedule C and Schedule D transaction so that I can accurately report on my committee transactions.

Acceptance Criteria

***Given*** an existing Schedule C or Schedule D transaction in the Loans and Debts Transactions table of a report

  ***When*** the user selects the action menu for that transaction,

  ***Then*** they will NOT see an option to manually "itemize" or "unitemize" that transaction.

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-627](https://fecgov.atlassian.net/browse/FECFILE-627)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified under the "Actions" dropdown menu "Itemize" and/or "Unitemize" option for Loans (Schedule C) and Debts (Schedule D) transactions have been removed.  

Dropdown for "Loan Received from Bank" (showing as example of dropdown)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlA4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--23405664bdae34e2b866a781ccd6abe2ff5c326c/image.png)

Dropdown for "Loan By Committee"  (showing as example of dropdown)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkg4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0563cd4ecd62daa35bdaa338ae60f10d5b99f91f/image.png)

Transactions tested:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXI4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--335bab3a09892974b7fc5b89f182bf704ddadeee/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXY4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--720f1f966975aaad36c271d343c32840e52702c4/image.png)

QA Review Completed.   Moved to Stage Ready.
