### ISSUE TITLE
Allow user to set and edit coverage dates for a report (Form 3X Line 5)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#137]
Business Reason

As a Committee Administrator, I will be able to set and edit the coverage dates for my Form 3X report so that, along with report type, I will be able to save a Form 3X report record to my Committee Account.

Acceptance Criteria

***Given*** I am a Committee Administrator that is creating a new Form 3X Report

  ***When*** I select any report type (Monthly, Quarterly, 12 day, 30 day, or Termination)

  ***Then*** I will be required to enter a starting and ending coverage date for that report

***THIS CRITERIA HAS BEEN REMOVED (Can Be Found in a New Ticket web-app #262)***

  ***And*** ~those dates MUST NOT overlap with any existing report coverage dates.~

Testing Note

Any Date can be put into the date picker (Future logic to come)

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1284](https://fecgov.atlassian.net/browse/FECFILE-1284)

**Comment by MitchellTCG** [comment]
Wires:
![Monthly - Coverage Dates.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/e0f20a90-83d7-483e-a026-1f47eff9fb37)

![Quarterly - Coverage dates.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/fe849b65-f1aa-4db2-bfcf-a5dbe17090a4)

![Quarterly - 12 Day Coverage Dates.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/75e887f0-395c-4e56-82f0-df8f4ee867b1)

**Comment by WiseQA** [comment]
Visual inspection of entering a coverage period date and changing the coverage period date as denoted in the Acceptance Criteria.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/24978acf-3e33-4017-a1ab-bf9bde5f2812)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/cf2ae138-0122-4657-9ebf-5862dafca94c/download](https://app.zenhub.com/files/306118986/cf2ae138-0122-4657-9ebf-5862dafca94c/download)

QA review completed.  Moved to Stage Ready.
