### ISSUE TITLE
The dropdown for reports action displays "Review report" should be "Edit report" for a report "In progress" and also causing "Add New Transactions Button" not to display

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1376]
During testing the dropdown for reports action when a report is "In progress" displays "Review report" should be "Edit report" . Since the status is "Review report" the "Add New Transactions Button" is missing. Found in Sprint 30 tested on both DEV and STAGE.

1\. Change action status from "Review report" to "Edit report" for reports in progress.

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdm1vIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f755c5ebd497e91692dc3f530686777a327fc1f0/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdm1vIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f755c5ebd497e91692dc3f530686777a327fc1f0/image.png))

2) Add new transaction button is missing from transactions page because it thinks the report is not in progress. Once step one of bug is corrected verify the "Add new transaction" button is displayed.

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnVvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--06a0a9b929f21f646d51bcca939deaa6042e8ece/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnVvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--06a0a9b929f21f646d51bcca939deaa6042e8ece/image.png))

@MitchellTCG @mjtravers the bug is pointed as 1 pt. and put "In-progress" for fix in Sprint 31 as discussed.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-624](https://fecgov.atlassian.net/browse/FECFILE-624)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
This ticket was changed from Bug to Defect as this broke functionality and could not create transaction due to action dropdown being incorrect.  (Tested on DEV will be pushed to STAGE Sprint 31)

1.  QA verified action status changed from "Review report" to "Edit report" for reports in progress.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdCtzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2c12d5379ff405dbcdc891b7b08caf4ff9f46407/image.png)

2.  QA review verified "+ Add new transaction" button is is displayed correctly.   Verified link working.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXFzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4cb10a1f68a0f2b1adf6531accf1e5e189f2def7/image.png)

QA Review Completed.   Moved to Stage Ready.
