### ISSUE TITLE
E2E test updates Sprint 31

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1379]
Add end-to-end tests for the following forms/features:

- [x] - 100% Federal Election Activity Payment under "ADD A DISBURSEMENT" -> "FED ELECTION ACTIVITY EXPENDITURES" [bug note: check for the correct candidate lookup label and value in the lookup select when editing an existing record]
- [x] - Loan by Committee
- [x] - Receive loan repayment (Loan by Committee)
- [x] - Add loan guarantors (Loan by Committee)
- [x] - Loan Received from Bank
- [x] - Add a Guarantor (Loan Received from Bank)
- [x] - Review loan agreement (Loan Received from Bank)
- [x] - Make loan repayment (Loan Received from Bank)
- [x] - Debt Owed By Committee
- [x] - Debt Owded To Committee

- 
DEV NOTES: When creating the test, review the acceptance criteria and include checks for custom (non-JSON) inline validation and any calculations created by the new transactions.

**Comment by mjtravers** [comment]
The 2 e2e tests in reports-f3x-debts.cy.ts and the 3 in reports-f3x-loans-committee.cy.ts work locally but not during the nightly run in CircleCI. Those 5 tests have been turned off in the develop branch and the fix will be addressed in #1424

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified e2e nightly run successfully passed.   (Screenshot from 10/21/2023 night run).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenBkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8f83ebbd08fa24e700d09c3cb85f8173f6b23a1/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejFkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11a2e59ae0f25735d64faf8e4e17677b12b6688d/image.png)

QA Review Completed.  Moved to Stage Ready.
