### ISSUE TITLE
Allow user to save their report progress and viewable in Reports Table

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#138]
**UX/UI considerations: How do we want to implement saving in reports? What auto-save functionality is recommend?**

 Business Reason 
 

As a Committee Administrator, I will be able to save a newly created Form 3x Report so that I can see the report in the Reports Table

 Acceptance Criteria 
 

**If** the Committee Administrator create a new Form 3x Report
**When** they click the save button
**Then** the newly created Report will appear in the Reports Page Table

 Testing Note 
 
**Save and continue** will take the user to Part 2 the Form 3X header form found in ticket (web-app #133)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
There will be a **Save** button and a **Save and continue** Button

![Custom Size – 37.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/9f81ad95-b9e8-4234-8bfe-fd8ffb2c179f)

**Comment by WiseQA** [comment]
Covering period "From" - "To" date picker not working for displaying in Reports table.   @mjtravers moved back to in-progress per our discussion.

**Comment by WiseQA** [comment]
Save and Save and Continue screen verifying Reports table was saved to and viewable.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6a966cc4-5731-4a8a-8b06-a8709dc83c05)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/0350d0d0-b88a-4f21-b68f-4b108e6e3d8a/download](https://app.zenhub.com/files/306118986/0350d0d0-b88a-4f21-b68f-4b108e6e3d8a/download)

QA review completed.  Moved to Stage Ready.
