### ISSUE TITLE
Create 'Independent Expenditures' grouping in the "Add a disbursement" selection screen

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1384]
**Note:** _These links/items will be inactive until we develop transactions, and they will become active as we go._
<br>

 Business Reason 
 

As a Committee Administrator within an existing Form 3X report, I will be able to see a list of available Independent Expenditure group under Disbursements so that in the future I can easily see and select what I need to enter.

 Acceptance Criteria 
 

**Given** I am editing an open Form 3X report
**Then** I can enter a Disbursement by clicking "Add a Disbursement" in the left-hand navigation menu,
**Then** I can see an INDEPENDENT EXPENDITURES grouping listed below the FEDERAL ELECTION ACTIVITY group, showing the following:

# Independent Expenditures 
#
- Independent Expenditure
- Void of Independent Expenditure
- Multistate Independent Expenditure
- Credit Card Payment for Independent Expenditure
- Staff Reimbursement for Independent Expenditure
- Payment to Payroll for Independent Expenditure
 

 Wireframe 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjNZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0fc6846f5cf92a1b20d6941c1c6ab3306bfc28b8/1384%20-%20Create%20%27Independent%20Expenditures%27%20grouping.png)

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete

**NOTE added by QA:  Per UX (see comment below) accordion dropdown to be Initial Caps like the other accordion dropdowns for consistency.   UX will create future ticket for updating accordion dropdowns to ALL CAPS if change is needed**
### DEV Notes ### 
 - Independent Expenditure: INDEPENDENT EXPENDITURE
- Void of Independent Expenditure: INDEPENDENT_EXPENDITURE_VOID
- Multistate Independent Expenditure: INDEPENDENT_EXPENDITURE_MULTISTATE
- Credit Card Payment for Independent Expenditure: INDEPENDENT_EXPENDITURE_CREDIT_CARD_PAYMENT
- Staff Reimbursement for Independent Expenditure: INDEPENDENT_EXPENDITURE_STAFF_REIMBURSEMENT
- Payment to Payroll for Independent Expenditure: INDEPENDENT_EXPENDITURE_PAYMENT_TO_PAYROLL
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand @GreggMoreland @MitchellTCG wire uploaded

**Comment by GreggMoreland** [comment]
@mary-tcg @AureliaKhorsand @MitchellTCG Wire looks good. Please confirm if the slight text change I made in AC will clear up the confusion.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
@MitchellTCG The wireframe has all caps for the list inside of the INDEPENDENT EXPENDITURES but this is not consistent with the other accordians. Can we get a confirmation for case in list?

**Comment by MitchellTCG** [comment]
Keep the accordion consistent to other pages. Please pass

**Comment by WiseQA** [comment]
QA review verified Accordion dropdown list is Initial Caps to be consistent with the other Accordion dropdown lists.  (Wireframe shows all CAPS tested as Initial CAPS per comment above)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFQ5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--35a70cd09527ba344a093a38fd2de3571f2d2710/image.png)

QA Review Completed.   Moved to Stage Ready.
