### ISSUE TITLE
System to  Calculate 'CALENDAR YEAR-TO-DATE' aggregate for Schedule E Tier 1 transactions

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1386]
Business Reason
The aggregate 'CALENDAR YEAR-TO-DATE' field must display the total contributions from the calendar year of the report _per election._ This is necessary to track contribution limits. This amount will be a _rolling total_. This will only apply to Tier 1 transacitons on Schedule E.

_Please note that this is not the same thing as the entity aggregate, which will be calculated to determine itemization on relevant transactions in Schedule E._

 Acceptance Criteria

**Given** I am a Committee Administrator editing an open Form 3X report
**Then** go to Add a disbursement
**Then** I can enter a transaction with the type “Independent Expenditure" under the "Independent Expenditures" Accordion link  
**And** the following will be automatically calculated by the system:

**CALENDAR YEAR-TO-DATE** field must meet the following criteria:

-- Amount Displayed will be the total of contributions that are:
--- For the selected ELECTION TYPE, ELECTION YEAR, CANDIDATE OFFICE, CANDIDATE STATE, and CANDIDATE DISTRICT
--- within Aggregation Group of "INDEPENDENT_EXPENDITURE"
--- _from_ January 1 of report year _to_ the Disbursement Date of the transaction. 
--- (**IF** Disbursement Date is not entered, then use Dissemination Date of the transaction.)

AND when saving a transaction, any subsequent transactions for the same ELECTION CODE, ELECTION YEAR, CANDIDATE OFFICE, CANDIDATE STATE, and CANDIDATE DISTRICT will update. (E.g., if a previous transaction receipt amount is _changed_, it will affect the future aggregations). 

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
- This field applies to Schedule E transactions on Line 24. 

Please verify this functionality is working in the following transactions:
-  [ ] Independent Expenditure
-  [ ] Credit Card Payment for Independent Expenditure
-  [ ] Staff Reimbursement for Independent Expenditure
-  [ ] Payment to Payroll for Independent Expenditure
-  [ ] Void of Independent Expenditure
### DEV Notes ### 
  Wireframe
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkxMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ede778a912451cc4fc842e6a19cc3a96d746bfb3/image.png)

### Design ### 
 null

**Comment by toddlees** [comment]
updated AC from 
>For the selected ELECTION CODE/ELECTION YEAR and Candidate selected

to
> For the selected ELECTION CODE, ELECTION YEAR, CANDIDATE OFFICE, CANDIDATE STATE, and CANDIDATE DISTRICT

meaning different candidates for the same election will be correctly grouped

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
After some initial testing, there are issues when aggregating with Presidential and also getting an api error pop up when switching office from Presidential to Senate because the state is not sent back to the /previous/election URL
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemxjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02f6234f3def849dfd8b02115198d4d443dfe656/image.png)

Sending ticket back to In Progress

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
Defect #1456 fixed.  On-hold removed.

**Comment by WiseQA** [comment]
QA review consisted of the calculation of the following fields in the IE transactions.  (Note:   Election Code = Election Type and Election Year however tested to the field names in the actual transaction)

 ELECTION TYPE, ELECTION YEAR, CANDIDATE OFFICE, CANDIDATE STATE, and CANDIDATE DISTRICT
--- within Aggregation Group of "INDEPENDENT_EXPENDITURE

**Comment by WiseQA** [comment]
@MitchellTCG @GreggMoreland @AureliaKhorsand please clarify are both the Schedule E IE transactions and the IE memo's included in the calculation of the "Calendar Year-To-Date" ? or is is just the IE transactions as listed under the QA Notes to be tested?


Please verify this functionality is working in the following transactions:
-  [ ] Independent Expenditure
-  [ ] Credit Card Payment for Independent Expenditure
-  [ ] Staff Reimbursement for Independent Expenditure
-  [ ] Payment to Payroll for Independent Expenditure
-  [ ] Void of Independent Expenditure

If memo's are included I will add to the list.   Thanks @GreggMoreland for the talk awaiting clarification.

Memo's List:
Payroll Memo for Independent Expenditure
Credit Card Memo for Independent Expenditure
Staff Reimbursement Memo for Independent Expenditure

**Comment by GreggMoreland** [comment]
@WiseQA I discussed this with Aurelia and confirmed that this only applies to the Tier 1 transactions. The Calendar YTD on the Tier 2 should be a copy of what is on the accompanying Tier 1, so Memos should just have a copy of what the tier 1 transaction has.

**Comment by WiseQA** [comment]
QA review verified the Calendar Year-To-Date aggregate for the following Schedule E transactions:

-  [x] Independent Expenditure
-  [x] Credit Card Payment for Independent Expenditure
-  [x] Staff Reimbursement for Independent Expenditure
-  [x] Payment to Payroll for Independent Expenditure
-  [x] Void of Independent Expenditure

Screenshot of Staff Reimbursement for Independent Expenditure displaying Calendar Year-To-Date aggregate 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2FCQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99f1d7828af7c1ab1caa897aa909216a771b1bd2/image.png)

QA Review Completed.   Moved to Stage Ready.
