### ISSUE TITLE
System should not allow Memo Item selection for Loan and Debt Repayment

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1391]
Business Reason

As a Committee Administrator, I will be unable to select the MEMO ITEM checkbox when creating a Loan or Debt repayment so that I can accuratley report on my committee's transactions.

 Acceptance Criteria

**Given** I am a Committee Administrator editing an open Form 3X report
**When** I have an existing Schedule C loan 
**And** I click on one of the following actions:
- Receive loan repayment
- Make loan repayment

**And** I initiate a transaction to enter the loan repayment
**Then** The Memo Item checkbox will be unavailable.

---

**Given** I am a Committee Administrator editing an open Form 3X report
**When** I open the action kebab menu for an existing Schedule D transaction
**And** I click on the "Report debt repayment" action
**And** I initiate a transaction to enter the contribution to apply to the debt
**Then** The Memo Item checkbox will be unavailable.

 Wireframe

# Main wire
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1pvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c641821905feec5636c452c19408826d53162e93/1391%20-%20Debt%20repayment.png)

# Wire with error message
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGlCQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ce3e120aae3b86d902a790a5d70ac501297eb22/1391%20-%20Debt%20repayment%20%E2%80%93%20error.png)

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
- The memo item checkbox will be removed from these transactions (currently displaying memo item checbox)
### DEV Notes ### 
 For this ticket, we can look at the isDebtRepayment flag that the transaction detail component uses to show/hide the "DEBT REPAYMENT" sub title to determine if the Memo Item checkbox should be displayed in the form.
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand @GreggMoreland @MitchellTCG wire updated to show removal of memo item checkbox option

**Comment by AureliaKhorsand** [comment]
@MitchellTCG need a specific error message if user tries to enter transaction outside report coverage dates. This should be prevented for these repayments.

**Comment by mary-tcg** [comment]
@AureliaKhorsand @GreggMoreland @MitchellTCG error wire updated

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when creating "Loan Repayment Made" the "Memo Item (checkbox)" has been removed.  (Note for testing selected date outside report date range.)  (QA note used report dated JULY 15 QUARTERLY REPORT (Q2) 04/01/2023 — 06/30/2023 for testing)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0RUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49b1ec34ee73fd4be6702aacc8cfe41ac8b4ea8c/image.png)

QA review verified when creating "Report debt repayment" then selected Individual Receipt (debt repayment) the "Memo Item (checkbox)" has been removed.  (Note for testing selected date outside report date range.)  (QA note used report dated JULY 15 QUARTERLY REPORT (Q2) 04/01/2023 — 06/30/2023 for testing)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEhUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5ba25887779d8221a76c08b5c3c041a154dc11e/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzdUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae87aaba3964ad1e4c88c1891122604ebd53a548/image.png)

QA Review Completed.  Moved to Stage Ready.
