### ISSUE TITLE
Fix bugs for 100% Federal Election Activity Payment and Void of 100% Federal Election Activity Payment disbursement transactions.

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1395]
QA review and team retested and verified there are bugs needing fixed for both the ***100% Federal Election Activity Payment and Void of 100% Federal Election Activity Payment*** disbursement transactions (Schedule B). (Tested on both DEV and STAGE) Found during testing in Sprint 31.

1\. Under Federal Election Activity Expenditures select the 100% Federal Election Activity Report.
 2\. Start creating a Transaction, under the "Committee/Candidate information" label add the words ***LOOKUP (Optional)*** ***(NOTE: First bug)***
 3\. Verify "Candidate" is displayed in the LOOKUP contact type. Save transaction. Reopen transaction created the "Committee/Candidate information" LOOKUP contact type changed from "Candidate" to "Organization". Should have stayed as "Candidate"***(NOTE: Second bug)***

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdExaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--da797342f699e15d5b5231d85b446b29dbfdde9c/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdExaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--da797342f699e15d5b5231d85b446b29dbfdde9c/image.png))

4\. Select "Create a new contact" the contact type "Candidate" page is displayed correctly.

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDdaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5173a4dc02f016c6d9d5103f6290712c1248b2d2/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDdaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5173a4dc02f016c6d9d5103f6290712c1248b2d2/image.png))

5\. Enter "Candidate Office" information select "Save & continue"

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUxaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4d75e15a2136156ef637ff8da73cfe1be747189d/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUxaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4d75e15a2136156ef637ff8da73cfe1be747189d/image.png))

6\. Reopen the transaction created. The "Candidate Office" is NOT saving. ***(NOTE: Third bug)***

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWpaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e8ca75dd5395fbeb34cb927bad965d7976455447/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWpaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e8ca75dd5395fbeb34cb927bad965d7976455447/image.png))

(NOTE: These bug fixes will also fix Void of 100% Federal Election Activity Payment transaction per DEV).

@MitchellTCG @mjtravers fix the 3 bugs denoted above for both transactions on DEV and push with Sprint 32 release. Assigned to Sprint Backlog and pointed 5 pts.

***DEV NOTES:*** Ensure that the bugs found are covered by the e2e tests, specifically the 100% Federal Election Activity Payment test being written in #1379

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-618](https://fecgov.atlassian.net/browse/FECFILE-618)

**Comment by andrew-bowers-tcg** [comment]
Ive made note of these bugs for 100% Fed Election payment e2e test and will update it accordingly

**Comment by mjtravers** [comment]
The 3 bug fixes were made:
1. Label for candidate lookup should have LOOKUP (OPTIONAL) label
2. The contact lookup select box for candidate was defaulting to wrong contact type when editing a transaction
3. The candidate office form inputs should not be displayed for 100% Federal Election Activity Payment and Void of 100% Federal Election Activity Payment transaction types

This ticket is sent to CR but on hold until #1379 is completed and checked that the e2e test for 100% Federal Election Activity Payment checks for the correct candidate lookup label and value in the lookup select.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA. Bug fix has been deployed to both DEV and STAGE.

**Comment by WiseQA** [comment]
QA review verified bug fixes tested and passed for both 100% Federal Election Activity Payment and Void of 100% Federal Election Activity Payment disbursement transactions (Schedule B).

1.  Verified label for candidate lookup is LOOKUP (OPTIONAL) label

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXpvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fd0c7695a2b5eb36cd76ed557e2a5f2c082a7560/image.png)

2.   Verified the contact lookup select box for candidate is defaulting to correct contact type when editing a transaction

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmZvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7fe388816df2017e1f8f2b7bf709adf15a1fa787/image.png)

3.   Verified "Candidate Office" information is saved and when reopening transaction the information has been saved in the transaction.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUxaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4d75e15a2136156ef637ff8da73cfe1be747189d/image.png)

4.   Verified 100% Federal Election Activity Payment transaction is saved and displayed in the transactions table.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczdvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7212128648708215294930ccc5e1a18e0e6b5d89/image.png)

QA review verified bug fixes passed.  Tested on both DEV and STAGE.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHpvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ef2f28510af37f4ad71bd922b87c229671e1c4d6/image.png)

QA Review Completed.  Moved to Stage Ready.
