### ISSUE TITLE
Upgrade Angular code to version 13

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-web-app#14]
fecfil-online/front-end is currently using Angular 11. This should be upgraded to version 12 and then 13 to maintain compliance with the QASP standard of being at most one major version behind the latest release.

**Acceptance Criteria**
- [x] The npm modules for Angular are version 13
- [x] The unit tests that passed before the upgrade also pass after the upgrade

**QA**
Verification that Angular version is 13 can be found in [this configuration file](https://github.com/fecgov/fecfile-web-app/blob/develop/front-end/package.json#L23-L30)
Passing unit tests can be found in this [CircleCI Report](https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/190/workflows/40153923-2d2d-42bc-8955-5aef6108e91d/jobs/718) under the "run unit tests" section.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by toddlees** [comment]
https://update.angular.io/?l=3&v=11.0-12.0 great resource for the upgrade

**Comment by AureliaKhorsand** [comment]
@mjtravers or @albertcrowley can we get ACs in here before it's in ADTR?

**Comment by albertcrowley** [comment]
This ticket is still in the Code Review lane in Zenhub.  Not sure if it is ready for QA as-is so I'm assigning it back to Matt update.

**Comment by WiseQA** [comment]
Verified Angular version 13 is in configuration file:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ee99ff3f-b0b1-4a08-8d48-3884859b4d49)

Verified unit test passed successfully as denoted in the Acceptance Criteria.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e7c36adc-3636-42b7-9bb4-c4edcef3cd3d)

QA review completed.  Moved to Stage Ready.
