### ISSUE TITLE
System to populate Committee info on new Form 3X report

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#140]
Business Reason 
 

The system will auto-populate Committee information on a Form 3X report so that the user does not have to manually enter information that rarely changes, reducing the chance for user error and enhancing the user experience.

 Technical Notes 

- Each time this screen is opened, a new pull from the FEC API endpoint needs to be made to display the most recent form information in case the user has submitted a FORM 1 and had it processed since the last time this info was refreshed for the committee account

 Acceptance Criteria 
 

**When** a Form 3X report gets created
**Then** the following will auto-populate and CAN NEVER be edited on the Form 3X report:
- Committee ID
- Committee Name 
- Multicandidate Status
-- Committee Type Q if qualified, Committee Type N if not qualified. 
-- https://api.open.fec.gov/developers/#/committee/get_committee__committee_id__ (see committee_type)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
Mocks in fecfile-project-management#42

**Comment by AureliaKhorsand** [comment]
Closed as duplicate. Requirements have been incorporated into #133.
