### ISSUE TITLE
Fix Defect: Show original incurred amount in "Amount" column and balance-at-close in "Balance" column

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1401]
During testing and team review the system is showing the current incurred amount in the "Amount" column and beginning balance in the "Balance" column. It should show the incurred amount of the original debt in the "Amount" column and the balance at close in the "Balance" column for "Loans and Debts" in the "Transactions in this report" table.

*   [x] Show the incurred amount from the original debt in the `Amount` column for Debts. (If the debt new, this will = the incurred amount. If it's carried over, it will = the incurred amount of that debt on the first report it appears on)
*   [x] Show the balance at close in the `Balance` column for Debts

Debts "Balance at Close" field in debts transactions. (here you can see the correct "Balance at Close" value.

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2J2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--30b04356490568367785f25e7616178ac42e9cc4/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2J2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--30b04356490568367785f25e7616178ac42e9cc4/image.png))

 (below you can see that the column is instead showing the "Beginning Balance" value of 0

 [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1R2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f39808fd0c9d13be1a92fff66b5ca9f5234bd8b6/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1R2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f39808fd0c9d13be1a92fff66b5ca9f5234bd8b6/image.png))

Debt Amount on table is showing the "Incurred Amount" of the **CURRENT** debt transaction

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzN3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5ed621e42532c812385d480fbad8d46824272abd/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzN3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5ed621e42532c812385d480fbad8d46824272abd/image.png))

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzd3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6668515a1ce96a45a1e391d636bc14caa97b7668/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzd3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6668515a1ce96a45a1e391d636bc14caa97b7668/image.png))

@MitchellTCG @mjtravers @toddlees per conversation assigned to Sprint 32 and put in Sprint Backlog and pointed this defect fix as 3pts.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-617](https://fecgov.atlassian.net/browse/FECFILE-617)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified incurred amount is displayed correctly in the "Amount" column and balance-at-close is displayed correctly in the "Balance" column.    Tested both Debt Owed to Committee and Debt Owed by Committee.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVFLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ffe2480f22b29f55fecffa458402ac1b01281f1/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWNLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f75532b45928a3701b8c55110da531564c070745/image.png)

Screenshot of multiple repayment transactions for both "debt" transactions.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkVLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6379db58c6116ce6481c182b889474c1ce0953a/image.png)

QA Review Completed.   Moved to Stage Ready.
