### ISSUE TITLE
System to pull new and updated debt transactions forward when existing future reports exist

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1406]
Business Reason

As a user, I will be able to see any NEW or UPDATED Schedule D debts pull forward onto any future 'In progress' report that has previously been created so that I can continue to report outstanding debts and associate repayments as needed.

Acceptance Criteria

***Given***a user has a new Schedule D debt or edits an existing Schedule D debt,

 ***When*** the user Saves that Debt transaction in the current report

 ***And*** an 'In progress' report exists with future coverage dates,

 ***Then*** the Schedule D debt will be pre-populated in the future report or updated accordingly

### QA Notes ###
- [x] BA/Design Quality Checklist complete
- This will follow the rules and requirements for #1169 for the transactions synced to the future report
- The transaction ID must be the same as the original.
- The debt transaction is synced forward on all future 'In Progress' reports and does not work backwards.
- Verify the incurred amount on the debts copied to future reports will be set to $0.00 and the debt will not be pulled forward if the balance at close is $0. (Wise added)

### DEV Notes ###
- "Incurred Date" will NO LONGER have the validation that it must be within report coverage dates. 
- The transaction ID must be the same as the original. 
- As mentioned in #1069, a new field was added to the transaction table that will hold the UUID of the originating transaction for copied forward transactions. We can use this as a flag so the transaction type code knows the transaction is a pulled forward transaction
- This will follow the rules and requirements for #1169 for the transactions synced to the future report
- The debt transaction is synced forward on all future 'In Progress' reports and does not work backwards.
- As noted in ticket #1169, the incurred amount on the debts copied to future reports will be set to $0.00 and the debt will not be pulled forward if the balance at close is $0.
- As noted in ticket #1195, the Beginning Balance on the future report is pulled from the 'Balance and Close' from the prior report.

### Design ###
null

 See full ticket and images here: [FECFILE-615](https://fecgov.atlassian.net/browse/FECFILE-615)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG need clarification on incurred amount being carried forward in future reports.

Comment added to DEV notes for current fix

As noted in ticket #1169, the **incurred amount** on the debts copied to future reports will be set to $0.00 and the debt will not be pulled forward if the **balance at close** is $0.

**Comment by mjtravers** [comment]
Fixes to incurred amount and balance at close pass CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Debt Owed by Committee and Debt Owed to Committee transactions are pulled forward to future reports.   There were 2 fixes as stated above.   Verified the incurred amount on the debts copied to future reports will be set to $0.00 and the debt will not be pulled forward if the balance at close is $0.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW1lQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbb57ed1aeaed31fc28ad54519d87ae31f617d1e/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTJlQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f4df9ab3bcc93115feba4fae2c54c96a619bf43/image.png)

QA Review Completed.   Moved to Stage Ready.
