### ISSUE TITLE
Remove "Review loan agreement" action from Loans pulled forward onto subsequent reports

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1407]
"Review loan agreement" should only appear as an action for a Loan Received by Bank on the report it was originally reported on.

Acceptance Criteria

***Given*** a Loan Received by Bank that has been pulled forward onto a report

  ***When*** the user opens the action kebab menu from the transactions table,

  ***Then*** they will NOT see "Review loan agreement" as an option.

### QA Notes ###
- "Review loan agreement" should only appear as an action for a Loan Received by Bank on the report it was originally reported on. 
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
 Wireframes
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblAzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ea53bab2743c5a23b54d0c1496369e85045b48eb/Screenshot%202023-10-02%20at%202.24.31%20PM.png)

### Design ###
null

 See full ticket and images here: [FECFILE-614](https://fecgov.atlassian.net/browse/FECFILE-614)

**Comment by MitchellTCG** [comment]
@GreggMoreland @AureliaKhorsand 

I believe yall need one of these two.
enjoy

**Comment by AureliaKhorsand** [comment]
Covered in use cases in #1122. Closing as OBE.
