### ISSUE TITLE
Investigate Java version warning from sonar

### ISSUE THREAD

**Issue by dheitzer** [fecgov/fecfile-web-app#1413]
Business Reason

We are currently getting an error indicating an old Java version in emails from sonarcloud during our circleci builds:

![image]([https://github.com/fecgov/fecfile-web-app/assets/104843885/2f88eb67-ee38-4998-8f69-f3b66d562a19](https://github.com/fecgov/fecfile-web-app/assets/104843885/2f88eb67-ee38-4998-8f69-f3b66d562a19))

### QA Notes ###
null

### DEV Notes ###
This is caused by running sonar-scanner in our Circle config.yml files.  The image for the docker container running this is **cimg/python:3.8-node** and uses Java 11, so it may not be possible to avoid this error, but may be worth looking into.

### Design ###
null

 See full ticket and images here: [FECFILE-612](https://fecgov.atlassian.net/browse/FECFILE-612)

**Comment by mjtravers** [comment]
This ticket is OBE. Closing.
