### ISSUE TITLE
Copy Purpose of Disbursement from original transaction to memo text when transaction is copied for Redesignation

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1415]
Business Reason

As a user, I will be able to see the text from the Purpose of Disbursement on the original transaction copied to the memo text of the new copied transaction when I reattribute a transaction so that I don't lose any information from the original transaction.

Acceptance Criteria

***Given*** a Purpose of Disbursement has been entered on a disbursement

  ***When*** the user redesignates that disbursement (whether it is from a previous report or within the current report)

  ***Then*** the original Purpose of Disbursement will be copied to the Memo Text field as follows:

*   "[Original purpose description: XX] YY" where:

       --XX is the original purpose description (anything in brackets is not editable) 
      *   and YY would be optional memo text (editable).

***And*** YY will be editable to the user (but _not_ the copied purpose description).

### QA Notes ###
- [ ] BA/Design Quality Checklist complete

### DEV Notes ###
null

### Design ###
null

[FECFILE-610](https://fecgov.atlassian.net/browse/FECFILE-610)

**Comment by mjtravers** [comment]
@AureliaKhorsand If the user already has existing memo text, should we prepend or append the Purpose of Disbursement?

**Comment by AureliaKhorsand** [comment]
@mjtravers updated ACs to clarify how it will be appended, and what is editable. Thanks for reviewing - good catch!

**Comment by mjtravers** [comment]
@Elaine-Krauss-TCG I have a couple of questions and comments in the PR. Ping me if you'd like to discuss.
Moving back to In Progress

**Comment by mjtravers** [comment]
@Elaine-Krauss-TCG I am getting an error in the api when saving. I noticed in the payload going out to the api that my purpose description wasn't in the text400 field. I don't think that would cause a save error though. Let's meet and test it together.
<img width="456" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzRMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1ae5f379ff74a3e541e5675af244dd78b6b1659/image.png" alt="image.png" />

Sending back to In Progress

**Comment by mjtravers** [comment]
Elaine helped me straighten out my local setup. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA copied list of transactions that need tested from ticket #1063.   These are the transactions that need tested for this ticket.

- Contribution to Candidate
- In-kind Contribution to Candidate
- Void of Contribution to Candidate
- Contribution to Other Committee
- In-kind Contribution to Other Committee
- Void of Contribution to Other Committee
- 100% Federal Election Activity Payment
- Credit Card Payment for 100% Federal Election Activity
- Staff Reimbursement for 100% Federal Election Activity
- Payment to Payroll for 100% Federal Election Activity
- Void of 100% Federal Election Activity

________________________________________________________________________________________________________________

When testing the "Contribution to Other Committee" does not have the option to "Redesignate".    

<img width="1323" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0llQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdf0d08bea1c286262e4eedf88f6b9ff305fdf81/image.png" alt="image.png" />

_______________________________________________________________________________________________________________

@MitchellTCG @mjtravers ticket as we discussed needs updated to reflect actual test.   Second is the list of transactions (listed above from ticket #1063) was tested that the "Redesignate" was an option from the kabob dropdown.   However, resting with this ticket "Redesignate" is not an option.  (All transactions listed above should have "Redesignate")

Returning to In-Progress for above fixes.

**Comment by mjtravers** [comment]
The test for whether a Schedule B transaction type can be redesignated is if the transaction type asks for election information. The "Contribution to Other Committee" doesn't have election info so is not redesignated. I looked at our models, and here are the Schedule B transaction types that I believe can be redesignated:

CONDUIT_EARMARK_OUT
CONTRIBUTION_TO_CANDIDATE
CONTRIBUTION_TO_CANDIDATE_VOID
FEDERAL_ELECTION_ACTIVITY_100PCT_PAYMENT
FEDERAL_ELECTION_ACTIVITY_CREDIT_CARD_PAYMENT
FEDERAL_ELECTION_ACTIVITY_PAYMENT_TO_PAYROLL
FEDERAL_ELECTION_ACTIVITY_STAFF_REIMBURSEMENT
FEDERAL_ELECTION_ACTIVITY_VOID
IN_KIND_CONTRIBUTION_TO_CANDIDATE
IN_KIND_TRANSFER_FEDERAL_ELECTION_ACTIVITY

**Comment by WiseQA** [comment]
Fixes in #1414 will per @mjtravers will also be implemented in this ticket.

**Comment by GreggMoreland** [comment]
@mjtravers @WiseQA - correct list is as follows:

CONDUIT_EARMARK_OUT
CONTRIBUTION_TO_CANDIDATE 
CONTRIBUTION_TO_CANDIDATE_VOID
FEDERAL_ELECTION_ACTIVITY_100PCT_PAYMENT
FEDERAL_ELECTION_ACTIVITY_CREDIT_CARD_PAYMENT
FEDERAL_ELECTION_ACTIVITY_PAYMENT_TO_PAYROLL
FEDERAL_ELECTION_ACTIVITY_STAFF_REIMBURSEMENT
FEDERAL_ELECTION_ACTIVITY_VOID
IN_KIND_CONTRIBUTION_TO_CANDIDATE
PAC_CONDUIT_EARMARK_OUT

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
During QA review the PURPOSE OF RECEIPT (OPTIONAL) text was copied from original transaction to NOTE OR MEMO TEXT (OPTIONAL) field once the "CONTRIBUTION_TO_CANDIDATE" transaction was reattributed. 

QA Review Completed.  Moved to Stage Ready.
