### ISSUE TITLE
System to prevent report coverage "From" date from being chronologically after the "To" date

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1417]
Business Reason

When setting report coverage dates, the "from date" cannot be chronologically after the "to date", as that would break report logic.

Acceptance Criteria

***Given*** I am creating a new report

  ***When*** I have entered a "From Date"

  ***Then*** I will be unable to save if I enter a "To Date" that comes before that "From Date".

  ***And*** if I try to save if that is the case, I will receive an error message as follows:

*   TO date must fall chronologically after FROM date

1.  Correct
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzRWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37cbeccf76dbc56168c85c8b3abc5aa36155e5d4/1417.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzRWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37cbeccf76dbc56168c85c8b3abc5aa36155e5d4/1417.png))

1.  Error
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0FXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68b03f13fb9bb59061c15d30ea7a126463d09f7c/1417%202.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0FXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68b03f13fb9bb59061c15d30ea7a126463d09f7c/1417%202.png))

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
 Wireframeas

### Design ###
null

 See full ticket and images here: [FECFILE-609](https://fecgov.atlassian.net/browse/FECFILE-609)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Please review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG @GreggMoreland noticed the BA/Design Quality Checklist complete checkbox is not checked.   Double verifying this ticket was reviewed by BAs.   Thanks !

**Comment by GreggMoreland** [comment]
@WiseQA I'm not sure how that got unchecked because it was checked at one time.

**Comment by WiseQA** [comment]
@GreggMoreland no problem just checking.   Thanks for verifying.

**Comment by WiseQA** [comment]
QA review verified Report coverage "From" date cannot be greater than "To" date.

<img width="1036" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFJOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--14964781e300f23d3d65aa8319d86c5bc5f4e411/image.png" alt="image.png" />

QA Review Completed.  Moved to Stage Ready.
