### ISSUE TITLE
Add e2e tests for Sprint 32

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1424]
Create e2e tests for:

- [x] Creating an Independent Expenditure - VOID transaction (https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/1117)
- [x] Create an amendment (https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/207)
- [x] Add a new loan agreement to existing Sched C Loan (https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/1122)
- [x] Fix issue with reports-f3x-debts.cy.ts and the 3 in reports-f3x-loans-committee.cy.ts not working on CircleCI. It appears an issue with cypress not able to get the entity search dropdown to work. (https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/3947/workflows/094ca84d-2418-4d8c-bfe3-d591f7948f23/jobs/14278)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by andrew-bowers-tcg** [comment]
I added some more rigorous checks to the ones that were failing to find the dropdown before it loaded. We'll see if it works on the nightly build I guess...

**Comment by mjtravers** [comment]
Passes CR and been merged into the develop branch. Let's see if the e2e tests pass tonight.
Here they are passing when run locally:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMml4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--090d052b3d5f6daec66c74751be3bc2139e31b26/image.png)

**Comment by mjtravers** [comment]
Tests are failing on CircleCI so ticket needs more work. It has been moved to sprint 34 and moved out of QA into In Progress.

**Comment by WiseQA** [comment]
Per @mjtravers moved this ticket back to In-Progress from QA review.   Nightly runs for e2e kept failing.   There is additional work that needs done to this ticket.

Removing on-hold status.

**Comment by mjtravers** [comment]
@toddlees Sending back to In Progress from CR with a couple of questions made in the PRs.

**Comment by toddlees** [comment]
addressed comments.  in pr

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA and DEV reviewed the e2e tests and verified currently they are running and passing correctly.

<img width="1044" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMklzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3a2db8c5dc858fd9e5c4985c837064360783b68/image.png" alt="image.png" />

<img width="1061" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk1zQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d98f4fd3c0a7d41a04ead11fa8f260aebe1376f/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
