### ISSUE TITLE
1 - DSP: System to set empty values for future schedules to zero

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1427]
Business Reason
On the Detailed Summary Page, undefined totals for future schedules will be set to zero in both Column A and Column B.

 Acceptance Criteria

**Given** I am a user 
**When** I view the Detailed Summary Report for a report
**Then** I will see the value of zero (0) in Column A and Column B for the following lines:
- [x] **18.a** Transfer from Non-Federal Account
- [x] **18.b** Transfer from Levin Account
- [x] **18.c** Total Transfers
- [x] **21.a.i** Operating Expenditures - Allocated Federal/Non-Federal Activity - Federal Share
- [x] **21.a.ii** Operating Expenditures - Allocated Federal/Non-Federal Activity - Non-Federal Share
- [x] **25** Coordinated Party Expenditures
- [x] **30.a.i** Federal Election Activity - Allocated FEA - Federal Share
- [x] **30.a.ii** Federal Election Activity - Allocated FEA - "Levin" Share

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
All DSP fields fall back to zero.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM081QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fbad0f1d228de007022be3eef5bdcdf9e1461e75/image.png)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the value of zero (0) in Column A and Column B for the following lines:

- [x] **18.a** Transfer from Non-Federal Account
- [x] **18.b** Transfer from Levin Account
- [x] **18.c** Total Transfers
- [x] **21.a.i** Operating Expenditures - Allocated Federal/Non-Federal Activity - Federal Share
- [x] **21.a.ii** Operating Expenditures - Allocated Federal/Non-Federal Activity - Non-Federal Share
- [x] **25** Coordinated Party Expenditures
- [x] **30.a.i** Federal Election Activity - Allocated FEA - Federal Share
- [x] **30.a.ii** Federal Election Activity - Allocated FEA - "Levin" Share

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWpOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2503e6ecb903232c22cabc5250321fb00abab82e/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW5OQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9abd3252c2f90083ab0399462ddb8a1ef118c190/image.png)

QA Review Completed. Moved to Stage Ready (after Sprint 33 review)
