### ISSUE TITLE
4 - DSP: System to calculate Total Federal Disbursements (Line 32) (Column A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1428]
Business Reason

On the Detailed Summary Page, Line 32 should be calculated by subtracting Line 21.a.ii and Line 30.a.ii from Line 31. This ticket is for Column A only.

 Acceptance Criteria

1. Detailed Summary Page Line 32 (column A) of Form 3X must:
--  consist of the the following calculation:
- Line 31 - Total Disbursements (#1041) **minus** (Line 21.a.ii Operating Expenditures - Allocated Federal/Non-Federal Activity - Non-Federal Share) (set to zero in #1427)  and **minus** (Line 30.a.ii Federal Election Activity - Allocated FEA - "Levin" Share) (set to zero in #1427) (Column A values only)

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
@GreggMoreland 

I'm guessing that the calculation in the AC above is a typo?  It says that Line 32 = (Line 32 - Line 21aii - Line 30aii) which is circular.  Given that you referenced ticket #1041 right next to "Line 32", I'm going to assume that you meant "Line 31" instead.

**Comment by GreggMoreland** [comment]
@Elaine-Krauss-TCG Yes, good catch. I had thought I had fixed that before. Thank you.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Detailed Summary Page for Line 32 (Column A ONLY) is displaying correctly. (Used MARCH 20 MONTHLY REPORT (M3) 02/01/2000 — 02/28/2000 for testing).  **(NOTE: Line 21.a.ii and 30.a.ii is value of zero as these have not been developed to date.)**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWNMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--404f9a6d2cdf86c6a7e555c38d3ebff26f518fd7/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWdMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6002c1823b039ef11c34f2b1ea7c419f62a955ef/image.png)

QA Review Completed.  Moved to Stage Ready.
