### ISSUE TITLE
4 - DSP: System to calculate Total Federal Disbursements (Line 32) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1429]
Business Reason

On the Detailed Summary Page, Line 32 should be calculated by subtracting Line 21.a.ii and Line 30.a.ii from Line 31. This ticket is for Column B only.

 Acceptance Criteria

1. Detailed Summary Page Line 32 (column B) of Form 3X must:
--  consist of the the following calculation:
- (Line 31 - Total Disbursements) (#1041) **minus** (Line 21.a.ii Operating Expenditures - Allocated Federal/Non-Federal Activity - Non-Federal Share) (set to zero in #1427)  and **minus** (Line 30.a.ii Federal Election Activity - Allocated FEA - "Levin" Share) (set to zero in #1427) (Column B values only)

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Detailed Summary Page for Line 32 (Column B ONLY) is displaying correctly. (MARCH 20 MONTHLY REPORT (M3) 02/01/2000 — 02/28/2000 for testing). **(NOTE: Line 21.a.ii and 30.a.ii is value of zero as these have not been developed to date.)**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEFMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3af33241beaf16ccfa7b5f1f9607d2471dc896bd/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMElMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3fe91b4e72e5c06921be39359a2dbc0ba0a226f/image.png)

QA Review Completed. Moved to Stage Ready.
