### ISSUE TITLE
2 - DSP: System to calculate Total Federal Election Activity (Line 30.c) (Column A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1430]
Business Reason 
 

On the Detailed Summary Page, Line 30.c should be a total of all lines 30.a.i, 30.a.ii, and 30.b_except_ for if the transaction has "Memo Code" checked.  This ticket is for Column A only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 30.c (column A) of Form 3X must:
--  consist of the sum of all transaction totals in the following Column A report lines:
- 30.a.i	Federal Election Activity - Allocated FEA - Federal Share (Set to zero in #1427)
- 30.a.ii	Federal Election Activity - Allocated FEA - "Levin" Share (Set to zero in #1427)
- 30.b	Federal Election Activity paid Entirely With Federal Funds (#921)
-- NOT include any transactions with "Memo Code" checked
3. The numbers will update as needed until the report is submitted.

 DEV NOTES

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Detailed Summary Page for Line 30.c (Column A ONLY) is displaying correctly. (Used JULY 15 QUARTERLY REPORT (Q2) 04/01/2023 — 06/30/2023 for testing)

Used the following transactions for testing listed in ticket #921:

- 100% Federal Election Activity Payment
- Credit Card Payment for 100% Federal Election Activity
- Staff Reimbursement for 100% Federal Election Activity
- Payment to Payroll for 100% Federal Election Activity
- Void of 100% Federal Election Activity

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1h3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c760dfeb01f8f1209efde45b9c709e8ec9aa755/image.png)

QA Review Completed. Moved to Stage Ready.
