### ISSUE TITLE
2 - DSP: System to calculate Total Federal Election Activity (Line 30.c) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1431]
Business Reason 
 

On the Detailed Summary Page, Line 30.c should be a total of all lines 30.a.i, 30.a.ii, and 30.b_except_ for if the transaction has "Memo Code" checked.  This ticket is for Column B only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 30.c (column B) of Form 3X must:
--  consist of the sum of all transaction totals in the following Column B report lines:
- 30.a.i	Federal Election Activity - Allocated FEA - Federal Share (Set to zero in #1427)
- 30.a.ii	Federal Election Activity - Allocated FEA - "Levin" Share (Set to zero in #1427)
- 30.b	Federal Election Activity paid Entirely With Federal Funds (#922)
-- NOT include any transactions with "Memo Code" checked
3. The numbers will update as needed until the report is submitted.

 DEV NOTES

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Detailed Summary Page for Line 30.c (Column B ONLY) is displaying correctly. (Used AUGUST 20 MONTHLY REPORT (M8) 07/01/2023 — 07/31/2023 for testing). Added 100% Federal Election Activity Payment in amount of $300.00. Calendar To-Year-Date updated correctly ($9001.00 + 300.00 = $9301.00). (Note: $9001.00 from #1430)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFB3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f483b33951c0fc0d32c75be005f20fc8774111b/image.png)

QA Review Completed. Moved to Stage Ready.
