### ISSUE TITLE
2- DSP: System to calculate Total Federal Operating Expenditures (Line 36) (Column A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1432]
Business Reason 
 

On the Detailed Summary Page, Line 36 should be a total of all lines 21.a.i and 21.b_except_ for if the transaction has "Memo Code" checked.  This ticket is for Column A only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 36 (column A) of Form 3X must:
--  consist of the sum of all transaction totals in the following Column A report lines:
- 21.a.i	Operating Expenditures - Allocated Federal/Non-Federal Activity - Federal Share (Set to zero in #1427)
- 21.b	Operating Expenditures - Other Federal Operating Expenditures (#911)
-- NOT include any transactions with "Memo Code" checked
3. The numbers will update as needed until the report is submitted.

 DEV NOTES

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Detailed Summary Page for Line 36 (Column A ONLY) is displaying correctly. (Used JULY 15 QUARTERLY REPORT (Q2) 04/01/2023 — 06/30/2023 for testing)

Used the following transactions for testing listed in ticket #911:

- Operating Expenditure
- Credit Card Payment for Operating Expenditure
- Staff Reimbursement for Operating Expenditure
- Payment to Payroll for Operating Expenditure
- Void of Operating Expenditure

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNC93QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6caa026d95c1ab221d0707900c0aae849140d4a/image.png)

QA Review Completed. Moved to Stage Ready.
