### ISSUE TITLE
2 - DSP: System to calculate Total Federal Operating Expenditures (Line 36) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1433]
Business Reason 
 

On the Detailed Summary Page, Line 36 should be a total of all lines 21.a.i and 21.b_except_ for if the transaction has "Memo Code" checked.  This ticket is for Column B only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 36 (column B) of Form 3X must:
--  consist of the sum of all transaction totals in the following Column B report lines:
- 21.a.i	Operating Expenditures - Allocated Federal/Non-Federal Activity - Federal Share (Set to zero in #1427)
- 21.b	Operating Expenditures - Other Federal Operating Expenditures (#912)
-- NOT include any transactions with "Memo Code" checked
3. The numbers will update as needed until the report is submitted.

 DEV NOTES

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Detailed Summary Page for Line 36 (Column B ONLY) is displaying correctly. (Used AUGUST 20 MONTHLY REPORT (M8) 07/01/2023 — 07/31/2023 for testing). 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUx3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce2402f33df9d2cd9a2174fa576396ea5ecddc76/image.png)

QA Review Completed. Moved to Stage Ready.
