### ISSUE TITLE
3 - DSP: System to calculate Net Operating Expenditures (Line 38) (Column A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1434]
Business Reason 
 

On the Detailed Summary Page, Line 38 should be a calculation of the Line 36 value minus the Line 37 value.  This ticket is for Column A only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 38 (column A) of Form 3X must:
--  consist of the following calculation:
- Line 36 - Total Federal Operating Expenditures (#1432) minus Line 37 - Offsets to Operating Expenditures (#287) (Column A values only)

3. The numbers will update as needed until the report is submitted.

 DEV NOTES

### QA Notes ### 
 -	These two values are subtracted from each other, line 37 is subtracted from line 36
- [x] BA/Design Quality Checklist complete
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Detailed Summary Page for Line 38 (Column A ONLY) is displaying correctly. (JULY 15 QUARTERLY REPORT (Q2) 04/01/2023 — 06/30/2023 for testing). 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWdNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b781472312603ae670e9bedcc1ddee0facdf9d0/image.png)

QA Review Completed.   Moved to Stage Ready.
