### ISSUE TITLE
3 - DSP: System to calculate Net Operating Expenditures (Line 38) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1435]
Business Reason 
 

On the Detailed Summary Page, Line 36 should be a calculation of the Line 36 value minus the Line 37 value.  This ticket is for Column B only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 38 (column B) of Form 3X must:
--  consist of the following calculation:
- Line 36 - Total Federal Operating Expenditures (#1433) minus Line 37 - Offsets to Operating Expenditures (#426) (Column B values only)

3. The numbers will update as needed until the report is submitted.

 DEV NOTES

### QA Notes ### 
 -	These two values are subtracted from each other, Line 37 is subtracted from Line 36
- [x] BA/Design Quality Checklist complete
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Detailed Summary Page for Line 38 (Column B ONLY) is displaying correctly. (JULY 15 QUARTERLY REPORT (Q2) 04/01/2023 — 06/30/2023 for testing).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUlNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a847f1d1ad02eed094dcc27b04b32359b24ebf2/image.png)

QA Review Completed.   Moved to Stage Ready.
