### ISSUE TITLE
5b - Summary Page: System to auto calculate Cash On Hand at Close of Reporting Period (Line 8) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1436]
Business Reason 
 
On the Summary Page, Line 8 should a calculation of line 6.d minus line 7 (This ticket is for Column B only)

 Acceptance Criteria 
 

1. Summary Page Line 8 (Cash On Hand at Close of Reporting Period) of Form 3x must:
-- consist of the following calculation:
- Line 6.d - Subtotal of Receipts and Cash on Hand (#1437) minus Line 7 Total Disbursements (#1040) (Column B values only)

 Dev Notes

### QA Notes ### 
 - This consists of a calculation, Line 6.d minus Line 7
- [x] BA/Design Quality Checklist complete
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
Completed in [this PR](https://github.com/fecgov/fecfile-web-api/pull/597) using the fallback-to-zero method

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Ticket #1521 - 5a - Summary Page: System to calculate Cash-on-Hand at Beginning of Report Period (Line 6.b) for first report was moved back to in-progress after DEV review.   Putting this ticket on-hold since this is a 5b COH ticket until #1521 is pushed to QA review.

**Comment by WiseQA** [comment]
QA review verified Summary Page Line 8 calculation of line 6.d minus line 7 (This ticket is for Column B only) per AC.

<img width="1003" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTFSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00c06f565ff1bb9dbcf71975d67ffb82edc3ef63/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
