### ISSUE TITLE
5b - Summary Page: System to auto calculate Subtotal (Line 6.d) (Column A and Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1437]
Business Reason 
 

On the Summary Page, 6.d, Column A should be a total of lines 6.b and 6.c. Column B should be a total of lines 6.a and 6.c.

 Acceptance Criteria 
 

1. Summary Page line 6.d (column A) of Form 3X must:
--  consist of the sum of the totals from Line 6.b and Line 6.c
2. Summary Page line 6.d (column B) of Form 3x must:
-- consist of the sum of the totals from Line 6.a and Line 6.c
3. The numbers will update as needed until the report is submitted

 DEV NOTES

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
Completed in [this PR](https://github.com/fecgov/fecfile-web-api/pull/597) using the fallback-to-zero method

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Ticket #1521 - 5a - Summary Page: System to calculate Cash-on-Hand at Beginning of Report Period (Line 6.b) for first report was moved back to in-progress after DEV review.   Putting this ticket on-hold since this is a 5b COH ticket until #1521 is pushed to QA review.

**Comment by WiseQA** [comment]
QA review verified from AC the following:

1.  Summary Page line 6.d (column A) of Form 3X must:
-- consist of the sum of the totals from Line 6.b and Line 6.c

<img width="987" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekpSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a28c22dfa554f14df3d7422d9c8094c3f1e5b2e5/image.png" alt="image.png" />

2.  Summary Page line 6.d (column B) of Form 3x must:
-- consist of the sum of the totals from Line 6.a and Line 6.c

<img width="964" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemRSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--312ee06317711d0ae08922f8c3c3bf242fa3f03b/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
