### ISSUE TITLE
Fix sorting of Line column in "Transactions in this report" table

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1438]
During QA testing and DEV review verified the Line column in the "Transactions in this report" table is not sorting correctly when selecting ascending / descending order.

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2swQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc04ea251878d7744fd284024245cd28e581384a/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2swQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc04ea251878d7744fd284024245cd28e581384a/image.png))

@MitchellTCG @mjtravers Fix Line sorting. Bug fix pointed as a 3 point bug fix and assigned to Sprint 33.

Dev Note

The sorting of the Line column is off because we store the form_type which can be something like "SE" or "SC/10" in the database but "24" or "10" on the screen so the data and label sorts don't match exactly. We need to move the label list into the backend as an annotation so it can be used for sorting and sent to the front-end to display in the table

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-596](https://fecgov.atlassian.net/browse/FECFILE-596)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the sorting of the Line column in "Transactions in this report" table has been fixed for Receipts, Disbursement and Loans and Debts.

Screenshot of Loans and Debts showing sorting correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEZuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9fdb0eb36c57ae7bbbd0447b5fc8e9105b883e8a/image.png)

QA Review Completed.   Moved to Stage Ready.
