### ISSUE TITLE
Allow user to edit an existing Candidate contact

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#144]
Business Reason 
 

As a Committee Administrator, I will be able to edit an existing Candidate contact so that I can maintain an accurate database of contacts as contact metadata such as addresses, employers, etc. change over time.

 Acceptance Criteria 
 

**If** I am a Committee Administrator
**When** I access my committee's contact list and select a Candidate type contact
**Then** I will be able to edit and save any of that contact's data **except Type**

 Dev Notes 
 
So, that a Contact name will appear on the Contact Page, find a way for the name to display in the  Contact Table:
 **First Name**  **Last Name**

Dev Tasks:
1. refactor old code
2. unit tests
3. documentation
4. logging in the back-end
5. accessible in the UI

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
Pointed at 3 based on 2/23/22 backlog refinement discussion. Based off pointing of #68.

**Comment by WiseQA** [comment]
Contacts screen selecting Candidate contact:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/818cdbba-07ea-4f70-abbb-a44cf0764972)

Successful - Contact Updated Popup Screen Shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f73c4322-e2d7-44eb-be33-a10ed303d86d)

Contacts screen showing Candidate edit name successful:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dec8a14d-7a59-42ae-a13b-f6a73d58c839)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/d57f3256-d38c-4117-bcc7-f2e2bab0b700/download](https://app.zenhub.com/files/306118986/d57f3256-d38c-4117-bcc7-f2e2bab0b700/download)

QA review completed.  Moved to Stage Ready.
