### ISSUE TITLE
Fix the ability to Save on the Confirm Information page

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1444]
During testing with QA and DEV the ability to Save on the Confirm information page is not working on both Stage and DEV. 

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGxMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a93b84c96def7059edd4f1a39521422c5850af3/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGxMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a93b84c96def7059edd4f1a39521422c5850af3/image.png))

Verified Summary Page Calendar Year-to-Date 

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnBMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b48b337a3ee003f5c8afd6f9247e99a57e1f29d/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnBMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b48b337a3ee003f5c8afd6f9247e99a57e1f29d/image.png))

(Note: This broke when pushing the Form 24) 

@MitchellTCG @mjtravers @toddlees fix ability to save. Hotfix in Sprint 32 pointed as 3.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-595](https://fecgov.atlassian.net/browse/FECFILE-595)

**Comment by toddlees** [comment]
associated pull request
https://github.com/fecgov/fecfile-web-api/pull/562

**Comment by WiseQA** [comment]
QA review verified and retested on both Stage and DEV the fix to have the ability to Save on the Confirm information page was fixed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVpMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1713b30cdc201899049614120b799679a706c8d8/image.png)

Verified once saved the Submit report page is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWhMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c22ce196afb45b7a985922ba3954182f6085096/image.png)

QA Review Completed.   Moved to Stage Ready.
