### ISSUE TITLE
Fix Cash on Hand (COH) menu item that is showing for all reports

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1446]
During QA and DEV testing the COH menu item showing for all reports.   The COH link is working properly for the report that it is supposed to show up on.   However, the link is disabled for the reports it should not be displayed for.  

**DEV NOTE:**  The problem is in the PrimeNG panel menu component we use. It is no longer implementing the "visible" attribute which is causing the "Cash on hand" to display permanently. See this line of code for the heart of the problem: https://github.com/fecgov/fecfile-web-app/blob/develop/front-end/src/app/layout/sidebar/menu-report/menu-report.component.ts#L49

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2hUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb0e1817947834a2b0fd9c1d96c480889282179c/image.png)

@MitchellTCG @mjtravers fix Cash on Hand (COH) menu item showing for all reports.  Bug assigned to Sprint 33 pointed as 3.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Cash on Hand (COH) menu item fix was implemented.

Cash on Hand displayed for first report submitted in NAV bar.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0pvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67d2be7abdd8881695cd89181b87b28271a80a3a/image.png)

Cash on Hand NOT displayed for all other reports in NAV bar.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd05vQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be1d5cff186241c8f63df53f7fd4797fd3156be3/image.png)

QA Review Completed.   Moved to Stage Ready.
