### ISSUE TITLE
System to populate "XX" in Purpose Descriptions with correct report code for reattributed/redesignated transactions

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1454]
Business Reason

As a user, if I have reattributed or redesignated a transaction from a previous report, then I will see the original report it was reported on in the purpose description of the copy of the original transaction.

Acceptance Criteria

***Given*** a reattributed or redesignated transaction from a previous report,

  ***When*** the user views the Purpose of Receipt or Purpose of Disbursement

  ***Then*** they will see "(Originally disclosed on XX). See  below." where XX is the report from the original report it was disclosed on. (Anything in parentheses is not editable).

  ***And*** the report name will display as it does in report creation, like the following:

*   APRIL 15 QUARTERLY REPORT (Q1)
*   JULY 15 QUARTERLY REPORT (Q2)
*   OCTOBER 15 QUARTERLY REPORT (Q3)
*   JANUARY 31 YEAR-END (YE)
*   TERMINATION REPORT (TER)
*   JULY 31 MID-YEAR REPORT (MY)
*   12-DAY PRE-GENERAL (12G)
*   12-DAY PRE-PRIMARY (12P)
*   12-DAY PRE-RUNOFF (12R)
*   12-DAY PRE-SPECIAL (12S)
*   12-DAY PRE-CONVENTION (12C)
*   30-DAY POST-GENERAL (30G)
*   30-DAY POST-RUNOFF (30R)
*   30-DAY POST-SPECIAL (30S)
*   FEBRUARY 20 MONTHLY REPORT (M2)
*   MARCH 20 MONTHLY REPORT (M3)
*   APRIL 20 MONTHLY REPORT (M4)
*   MAY 20 MONTHLY REPORT (M5)
*   JUNE 20 MONTHLY REPORT (M6)
*   JULY 20 MONTHLY REPORT (M7)
*   AUGUST 20 MONTHLY REPORT (M8)
*   SEPTEMBER 20 MONTHLY REPORT (M9)
*   OCTOBER 20 MONTHLY REPORT (M10)
*   NOVEMBER 20 MONTHLY REPORT (M11)
*   DECEMBER 20 MONTHLY REPORT (M12)

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
null

### Design ###
null

[FECFILE-592](https://fecgov.atlassian.net/browse/FECFILE-592)

**Comment by AureliaKhorsand** [comment]
@mjtravers @toddlees can someone on the dev team add the list of report code mappings to this ticket?

**Comment by toddlees** [comment]
Mapping used in report creation:
```
 Q1 => 'APRIL 15 QUARTERLY REPORT (Q1)'
 Q2 => 'JULY 15 QUARTERLY REPORT (Q2)'
 Q3 => 'OCTOBER 15 QUARTERLY REPORT(Q3)'
 YE => 'JANUARY 31 YEAR-END (YE)'
 TER => 'TERMINATION REPORT (TER)'
 MY => 'JULY 31 MID-YEAR REPORT (MY)'
 TwelveG => '12-DAY PRE-GENERAL (12G)'
 TwelveP => '12-DAY PRE-PRIMARY (12P)'
 TwelveR => '12-DAY PRE-RUNOFF (12R)'
 TwelveS => '12-DAY PRE-SPECIAL (12S)'
 TwelveC => '12-DAY PRE-CONVENTION (12C)'
 ThirtyG => '30-DAY POST-GENERAL (30G)'
 ThirtyR => '30-DAY POST-RUNOFF (30R)'
 ThirtyS => '30-DAY POST-SPECIAL (30S)'
 M2 => 'FEBRUARY 20 MONTHLY REPORT (M2)'
 M3 => 'MARCH 20 MONTHLY REPORT (M3)'
 M4 => 'APRIL 20 MONTHLY REPORT (M4)'
 M5 => 'MAY 20 MONTHLY REPORT (M5)'
 M6 => 'JUNE 20 MONTHLY REPORT (M6)'
 M7 => 'JULY 20 MONTHLY REPORT (M7)'
 M8 => 'AUGUST 20 MONTHLY REPORT (M8)'
 M9 => 'SEPTEMBER 20 MONTHLY REPORT (M9)'
 M10 => 'OCTOBER 20 MONTHLY REPORT (M10)'
 M11 => 'NOVEMBER 20 MONTHLY REPORT (M11)'
 M12 => 'DECEMBER 20 MONTHLY REPORT (M12)'
 ```
 mapping used on report table:
 ```
 Q1 => "APRIL 15 (Q1)"
Q2 => "JULY 15 (Q2)"
Q3 => "OCTOBER 15 (Q3)"
YE => "JANUARY 31 (YE)"
TER => "TERMINATION (TER)"
MY => "JULY 31 (MY)"
12G => "GENERAL (12G)"
12P => "PRIMARY (12P)"
12R => "RUNOFF (12R)"
12S => "SPECIAL (12S)"
12C => "CONVENTION (12C)"
30G => "GENERAL (30G)"
30R => "RUNOFF (30R)"
30S => "SPECIAL (30S)"
M2 => "FEBRUARY 20 (M2)"
M3 => "MARCH 30 (M3)"
M4 => "APRIL 20 (M4)"
M5 => "MAY 20 (M5)"
M6 => "JUNE 20 (M6)"
M7 => "JULY 20 (M7)"
M8 => "AUGUST 20 (M8)"
M9 => "SEPTEMBER 20 (M9)"
M10 => "OCTOBER 20 (M10)"
M11 => "NOVEMBER 20 (M11)"
M12 => "DECEMBER 20 (M12)"
 ```

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA verified PURPOSE OF RECEIPT and PURPOSE OF DISBURSEMENT  both display the originally disclosed on:  (Report date) 

<img width="759" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE04QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b96fd3aa6459f1ac58ccc390ad0084994fcb8aa3/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.

**Comment by WiseQA** [comment]
**QA retested using Login.gov on STAGE using QA test committee account.**

QA review reverified  PURPOSE OF RECEIPT and PURPOSE OF DISBURSEMENT both display the originally disclosed on: (Report date) 
_________________________________________________________________________________________________________________

**PURPOSE OF DISBURSEMENT**

Select below transaction:

<img width="1433" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFZPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e25ab499114d26965ae0f50adbb8121b4e2a22a/image.png" alt="image.png" />

___________________________________________________________________________________________________________

<img width="911" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGxPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c9ab8a4955fcbe6f63fb84cb86af37e0404c8b29/image.png" alt="image.png" />

_______________________________________________________________________________________________________________
<img width="862" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHBPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b09213b2c5151333d60d1ce2bf22b16776b31a45/image.png" alt="image.png" />

______________________________________________________________________________________

Verified same for PURPOSE OF RECEIPT

<img width="758" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHhPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e9cc525832687aaf92bf454bf2a2b974c4a0737/image.png" alt="image.png" />

_________________________________________________________________________________________________________

@MitchellTCG QA review retested and verified the above functionality is working.
