### ISSUE TITLE
System to require Candidate State if Candidate Office is Presidential and Election Type is Primary on all Schedule E transactions

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1456]
Business Reason

Defect found during Demo of Sprint 32.

As a user, I will be required to select a Candidate State when the Candidate Office is "Presidential" and Election Type is "Primary" so that I can create a Schedule E transaction

Acceptance Criteria

***Given*** I am a Committee Administrator

  ***When*** I am creating a transaction in the following list:

*   [x] Independent Expenditure
*   [x] Credit Card Payment for Independent Expenditure
*   [x] Staff Reimbursement for Independent Expenditure
*   [x] Payment to Payroll for Independent Expenditure
*   [x] Void of Independent Expenditure

***And*** I select a Candidate with a Candidate Office = Presidential

  ***And*** I select Election Type = ***Primary*** (P)

  ***Then*** The system will require that I enter a Candidate State.

### QA Notes ###
QA notes Test the following transactions for DEFECT fix (Wise)
-  [x] Independent Expenditure
-  [x] Credit Card Payment for Independent Expenditure
-  [x] Staff Reimbursement for Independent Expenditure
-  [x] Payment to Payroll for Independent Expenditure
-  [x] Void of Independent Expenditure

### DEV Notes ###
 Wireframe
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUppQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b05a92ff53ae8e00c2f191fc2954602cda3f006c/Screenshot%202023-10-23%20at%203.21.27%20PM.png)

### Design ###
null

 See full ticket and images here: [FECFILE-590](https://fecgov.atlassian.net/browse/FECFILE-590)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
A bug was discovered that the candidate state did not show it was a required field for presidential primaries unless the election year was completely filled out with a 4 digit date. This has been corrected and passed CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified bug fix in the DEFECT.  Election Year and Candidate State fields populating correctly and showing both fields "This is a required field" is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjEyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da3ef3a45c9214b25cd3a9bb4968aa581398d467/image.png)

**Comment by WiseQA** [comment]
QA review verified the original written defect that Candidate State is required when Candidate Office = Presidential and Election Type = Primary (P)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0YyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f156cc4a35fa35f66ed7523ddf6116497c682c2/image.png)

QA review verified the transactions listed under QA Notes (above) were retested for this initial defect and passed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXQyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c9f0d4e75e1531cc4df3849b29f1a79d39fdf9f/image.png)

**Comment by WiseQA** [comment]
During QA testing when "Election Type' is selected as "Other" and then you select "Save" the "Election Year" field displays "This is a required field".   The "Election Description" field should also display "This is a required field" if Election Type is selected as Other.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1oyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee055178d89a4007dc09d6ab4190edb9d8e454f8/image.png)

But once the Election Year is entered the Election Description field then becomes a required field

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0IyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a3022df99f5b829d37561a996e3334808e21a4c/image.png)


@MitchellTCG @mjtravers see above comment for fix.

**Comment by mjtravers** [comment]
The issue that was affecting the candidate state was also causing the required message for the election description to not show the message unless all 4 digits of the election year were input. This has been corrected.

**Comment by mjtravers** [comment]
Patch passes CR. Ready for QA on DEV.

**Comment by WiseQA** [comment]
QA review verified the bug fix implemented to fix the required message for the election description to show the message along with the Election Year.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1YzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd6c38eed044f9fd54636d892dee06145ff38dc7/image.png)

DEFECT and Bug fixes verified and PASSED.

(NOTE:   The IE transactions retested above to verify DEFECT fix clears the 5 IE that were put on-hold in Sprint 32 #1241, #1239, #1236, #1117, and #1082.  These transaction Schedule E tickets can be passed)

QA Review Completed.  Moved to Stage Ready.
