### ISSUE TITLE
Allow user to edit an existing Organization contact

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#146]
Business Reason 
 

As a Committee Administrator, I will be able to edit an existing Organization contact so that I can maintain an accurate database of contacts as contact metadata such as addresses, employers, etc. change over time.

 Acceptance Criteria 
 

**If** I am a Committee Administrator
**When** I access my committee's contact list and select an Organization type contact
**Then** I will be able to edit and save any of that contact's data **except Type**

Dev Tasks:
1. refactor old code
2. unit tests
3. documentation
4. logging in the back-end
5. accessible in the UI

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
Pointed at 3 based on 2/23/22 backlog refinement discussion. Based off pointing of #68.

**Comment by WiseQA** [comment]
Contacts screen selecting Organization contact:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/294e9795-d746-4e63-aa00-5ebe6c4a3905)

Successful - Contact Updated Popup Screen Shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/620eb206-e9d6-4309-b569-0401688d069f)

Contacts screen showing Organization edit name successful:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3f9cf4b7-3986-4497-b32f-2a73a95e9d70)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/746f246c-12d5-4f6b-b825-a51073615777/download](https://app.zenhub.com/files/306118986/746f246c-12d5-4f6b-b825-a51073615777/download)

QA review completed.  Moved to Stage Ready.
