### ISSUE TITLE
Tech work to allow a user to reattribute/redesignate a Tier 1 Schedule A and B transactions

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1461]
In order for a user to reattribute a Schedule A or redesignate a Schedule B transaction, the Reattribution/Redesignation Overlay Spec. will need to be implemented in the front-end.

[https://docs.google.com/spreadsheets/d/1AbYjbtwZNuB8Y1GHAXMwSzxJW41Pr_3J](https://docs.google.com/spreadsheets/d/1AbYjbtwZNuB8Y1GHAXMwSzxJW41Pr_3J)

***DEV NOTES***

  The overlay needs to know (1) if the reattributed/redesignated transaction is in current or previous report, (2) the amount of the reattributed/redesignated transaction, and (3) update the CPDs/EPDs of the reattributed/redesignated, reattributed/redesignated_from, and reattributed/redesignated_to transactions.

***Tasks:***

1\. Use a python script (see Matt for starter script) to add a non-required reattribution_redesignation_tag property to all Schedule A and Schedule B validation JSON schemas. It will be an enum with the values listed in the spreadsheet above. Before doing this, investigate the JSON Schema spec to see if we can pool new properties that are used by many transactions into a secondary file that is incorporated using the "$ref" property. (see: [https://json-schema.org/understanding-json-schema/structuring](https://json-schema.org/understanding-json-schema/structuring))

  2\. Add a reattribution_redesignation_tag to the Django schedule_a and schedule_b models.

  3\. Update Angular models for Schedule A and Schedule B to include the new reattribution_redesignation_tag property.

  4\. Implement a ReattRedesigUtils class in shared/utils/reatt-redesig.utils.ts to perform the necessary data transformations and validation on the transactions.

### QA Notes ###
- Unit test visual inspection

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-587](https://fecgov.atlassian.net/browse/FECFILE-587)

**Comment by mjtravers** [comment]
Unit test report for QA visual inspection:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/4045/workflows/4f88d636-b7e4-45ad-bc97-f3d746a369e8/jobs/14599

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzJpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--437916e5607becb55eea00d072712baf0be60cec/image.png)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of Unit Test with DEV.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGVvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2668a20b835d01283fb94c24098b2365c8d0310c/image.png)

QA Review Completed.   Moved to Stage Ready.
