### ISSUE TITLE
Update "Regular Filers" to "Registered Filers" in Add a Disbursement accordion dropdown

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1462]
Task: Update "Regular Filers" to "Registered Filers" in Add a Disbursement accordion dropdown

Acceptance Criteria

***Given*** the user is on the page to "Add a disbursement"

  ***Then*** the second accordion dropdown header will read "CONTRIBUTIONS?EXPENDITURES TO REGISTERED FILERS" instead of "regular" filers.

***Screenshot with _incorrect_ text***
[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTlwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56ad73f6d42a4ce9e4a4b043ab4af44aa3c54913/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTlwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56ad73f6d42a4ce9e4a4b043ab4af44aa3c54913/image.png))

### QA Notes ###
- [ ] BA/Design Quality Checklist complete

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-586](https://fecgov.atlassian.net/browse/FECFILE-586)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the accordion dropdown name was changed from CONTRIBUTIONS/EXPENDITURES TO REGULAR FILERS to CONTRIBUTIONS/EXPENDITURES TO REGISTERED FILERS

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUxOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da45f290f8d5a41b7cc58049beadecd26f44b114/image.png)

QA Review Completed. Moved to Stage Ready (after Sprint 33 review)
