### ISSUE TITLE
Allow user to see "dissemination date" on the transaction table for disbursements if "disbursement date" is not available 

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1463]
Business Reason

As a user, I will be able to see the dissemination date on the transactions table within a report for an Independent Expenditure that does not have a disbursement date so that I can still sort my transactions based on date.

Acceptance Criteria

***Given*** a Schedule E transaction that does _not_ have a disbursement date but does have a dissemination date

  ***When*** the user views the disbursements on the transactions table

  ***Then*** they will see the dissemination date populated in the "Date" column for that transaction.

—

***Given*** a Schedule E transaction that has both a disbursement date and a dissemination date,

  ***When*** the user views the disbursements on the transactions table

  ***Then*** they will see the disbursement date populated in the "Date" column for that transaction.

### QA Notes ###
- [x] BA/Design Quality Checklist complete
- [x] Note: Manage your transactions table only shows one DATE column.  (Wise comment)

### DEV Notes ###
The `date` field already behaves this way and is even used as the sort field in this column.  All we need to do is change
```
        
          {{ item[item.transactionType.templateMap.date] | fecDate }}
        
```
to 
```
        
          {{ item.date | fecDate }}
        
```

### Design ###
null

 See full ticket and images here: [FECFILE-585](https://fecgov.atlassian.net/browse/FECFILE-585)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified if "dissemination date" is entered and NOT the "disbursement date" then the "dissemination date" is displayed in the "Manage your transactions" table.  (Tested using Staff Reimbursement for Independent Expenditure) (QA note tested using March 20 Monthly Report (M3)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkhOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c2debc87a50463648ed3b310b533fbc89cba886/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlBOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b634f232aa3b7063efd3825e51458320f07e98bd/image.png)

QA Review Completed. Moved to Stage Ready (after Sprint 33 review)
