### ISSUE TITLE
Add Forms 1M, 24, and 99 to the Report selection 

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1466]
Business Reason

As a user, I will be able to see additional form types listed in the Form type selection so that I can create one of the form types.

 Acceptance Criteria

**Given** I'm a user
**When** I select 'Create a new report'
**Then** the 'Select form type' popup will include the following in the selection dropdown, which already includes Form 3x:
- **Form 1M:** Notification of Multicandidate Status
- Form 3X: Report of Receipts and Disbursements
- **Form 24:** 24/48-Hour Report of Independent Expenditure
- **Form 99:** Miscellaneous Report to FEC 

 Wireframe
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmFtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96ffa3140e3d3cc5fe794017c924ad7f5ef6e3ce/1466.png)

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
### DEV Notes ### 
 Each form selection will be displayed in the dropdown. BUT the "Start building report" button will be grayed out for the following selections:
- Form 1M
- Form 24
- Form 99
### Design ### 
 null

**Comment by MitchellTCG** [comment]
The design team opted to organize these reports alphanumerically to improve report findability in this first iteration.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
ready for review.

**Comment by GreggMoreland** [comment]
@MitchellTCG I agree with the alphanumeric order. However, wouldn't 24 come before 3X?

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg also the Form 24's official name is FORM 24 - 24 / 48 HOUR REPORT OF INDEPENDENT EXPENDITURE. If may be worth at least adding in the 48.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
I updated 24/48 and @JonellaCulmer  has cosigned on the order:
1M
3X
24
99

Ready for BA review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Form 1M; Form 24 and Form 99 have been added to the "Select form type" > "Choose Form" dropdown menu.

1.  Select "Create new report button"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGo5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd99b09a4c4b2473500ffba0b079b1ace2c22d8a/image.png)

2.  Verify "Select form type" > "Choose Form" popup is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDM5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--872c90a1883cfd681be86478438caffe63756fb4/image.png)

3.  Select the dropdown arrow and verify Form 1M; Form 3X; Form 24 and Form 99 are displayed in this order.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMC85QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ea85bd4f39a719cea9076710727a6ffaac86a59/image.png)

4.  Verified Form 1M; Form 24 and Form 99, once selected, the "Start building report" button is deactivated.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVg5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b59ef9378977dcf569ebd4653f1003741a00a82/image.png)

5.  Verified when selecting Form 3X the "Start building report" button is Activated.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWo5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--701b5b080109f256fcb1f117e787ebd1adf63dd1/image.png)

QA Review Completed.   Moved to Stage Ready.
