### ISSUE TITLE
Fix Independent Expenditure transactions when searching an existing contact and adding "Candidate' the "Candidate ID" becomes an unique field

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1471]
During QA and DEV testing when changing the ***Candidate information*** within an Independent Expenditure the "Candidate ID" becomes required field for existing Candidates.

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk9DQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4fff1f7f03fcca69e01b2107dd1e95500a31b73d/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk9DQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4fff1f7f03fcca69e01b2107dd1e95500a31b73d/image.png))

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmVDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d55f7111d955c47c537819b2ba4edd344aa08deb/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmVDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d55f7111d955c47c537819b2ba4edd344aa08deb/image.png))

@MitchellTCG @mjtravers fix "Candidate ID" field. Bug added to Sprint 33 pointed as 3.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-582](https://fecgov.atlassian.net/browse/FECFILE-582)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified when changing the Candidate information within an Independent Expenditure the "Candidate ID" doesn't become a required field for existing Candidates.   Bug fix passed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU9lQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ceae59726833212229a7ef0f0a6c1560fdb4f856/image.png)

QA Review Completed.  Moved to Stage Ready.
