### ISSUE TITLE
System to only show relevant Form 3X transactions for "PTY" Committee Type

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1472]
Business Reason

As a Committee Administrator, I will be able to only see, create, and update all Form 3X transactions that correspond to my committee type so that I can only create and update the transactions that apply to my committee type.

Acceptance Criteria

***If*** I am a Committee Administrator for a Party (PTY) committee type (Committee Type is included [HERE]([https://docs.google.com/spreadsheets/d/10fwbBXjS9C3N0Q2QqjWbyPpWF_ow4F59WdZbh0_osu4/edit#gid=1295372537](https://docs.google.com/spreadsheets/d/10fwbBXjS9C3N0Q2QqjWbyPpWF_ow4F59WdZbh0_osu4/edit#gid=1295372537)))

  ***When*** I see which transactions are available for me to add and update on a report

  ***Then*** I will see only the following transactions:

***Add a receipt***

  Contributions from Individuals/Persons:

*   [ ] Individual Receipt
*   [ ] Tribal Receipt
*   [ ] Partnership Receipt
*   [ ] In-kind Receipt
*   [ ] Returned/Bounced Receipt
*   [ ] Earmark Receipt
*   [ ] Conduit Earmark Receipt
*   [ ] Receipt from Unregistered Entity
*   [ ] Receipt from Unregistered Entity - Returned/Bounced Receipt

Contributions from registered filers:

*   [ ] Party Receipt
*   [ ] Party In-kind Receipt
*   [ ] Party Returned/Bounced Receipt
*   [ ] PAC Receipt
*   [ ] PAC In-kind Receipt
*   [ ] PAC Earmark Receipt
*   [ ] PAC Conduit Earmark
*   [ ] PAC Returned/Bounced Receipt

Transfers:

*   [ ] Transfer
*   [ ] Joint Fundraising Transfer
*   [ ] In-kind Transfer
*   [ ] In-kind Transfer - Federal Election Activity
*   [ ] Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account
*   [ ] Joint Fundraising Transfer - National Party Pres. Nominating Convention Account
*   [ ] Joint Fundraising Transfer - National Party Headquarters Buildings Account

Refunds:

*   [ ] Refund of Contribution to Federal Candidate
*   [ ] Refund of Contribution to Other Political Committee
*   [ ] Refund of Contribution to Unregistered Committee

Other:

*   [ ] Offset to Operating Expenditures
*   [ ] Other Receipts
*   [ ] Individual Recount Receipt
*   [ ] Party Recount Receipt
*   [ ] PAC Recount Receipt
*   [ ] Tribal Recount Receipt
*   [ ] Partnership Recount Account Receipt
*   [ ] Individual National Party Recount/Legal Proceedings Account
*   [ ] Party National Party Recount/Legal Proceedings Account
*   [ ] PAC National Party Recount/Legal Proceedings Account
*   [ ] Tribal National Party Recount/Legal Proceedings Account
*   [ ] Partnership National Party Recount/Legal Proceedings Account
*   [ ] Individual National Party Headquarters Buildings Account
*   [ ] Party National Party Headquarters Buildings Account
*   [ ] PAC National Party Headquarters Buildings Account
*   [ ] Tribal National Party Headquarters Buildings Account
*   [ ] Partnership National Party Headquarters Buildings Account
*   [ ] Individual National Party Pres. Nominating Convention Account
*   [ ] Party National Party Pres. Nominating Convention Account
*   [ ] PAC National Party Pres. Nominating Convention Account
*   [ ] Tribal National Party Pres. Nominating Convention Account
*   [ ] Partnership National Party Pres. Nominating Convention Account
*   [ ] Earmark Receipt for National Party Recount/Legal Proceedings Account (Contribution)
*   [ ] Earmark Receipt for National Party Pres. Nominating Convention Account (Contribution)
*   [ ] Earmark Receipt for National Party Headquarters Buildings Account (Contribution)

***Add a disbursement***

  Operating expenditures:

*   [ ] Operating Expenditure
*   [ ] Credit Card Payment for Operating Expenditure
*   [ ] Staff Reimbursement for Operating Expenditure
*   [ ] Payment to Payroll for Operating Expenditure
*   [ ] Void of Operating Expenditure

Contributions/expenditures to registered filers:

*   [ ] Transfers to Affiliates/Other Committees
*   [ ] Contribution to Candidate
*   [ ] Void of Contribution to Candidate
*   [ ] Contribution to Other Committee
*   [ ] Void of Contribution to Other Committee
*   [ ] In-kind Contribution to Candidate
*   [ ] In-kind Contribution to Other Committee

Other Expenditures:

*   [ ] Other Disbursements
*   [ ] Credit Card Payment for Other Disbursement
*   [ ] Staff Reimbursement for Other Disbursement
*   [ ] Payment to Payroll for Other Disbursement
*   [ ] Void of Other Disbursement
*   [ ] Recount Account Disbursement
*   [ ] National Party Recount/Legal Proceedings Account Disbursement
*   [ ] National Party Headquarters Buildings Account Disbursement
*   [ ] National Party Pres. Nominating Convention Account Disbursement
*   [ ] Individual Refund - National Party Headquarters Buildings Account
*   [ ] Other Committee Refund - National Party Headquarters Buildings Account
*   [ ] Tribal Refund - National Party Headquarters Buildings Account
*   [ ] Individual Refund - National Party Pres. Nominating Convention Account
*   [ ] Other Committee Refund - National Party Pres. Nominating Convention Account
*   [ ] Tribal Refund - National Party Pres. Nominating Convention Account
*   [ ] Individual Refund - National Party Recount/Legal Proceedings Account
*   [ ] Other Committee Refund - National Party Recount/Legal Proceedings Account
*   [ ] Tribal Refund - National Party Recount/Legal Proceedings Account

Refund:

*   [ ] Refund of Individual Contribution
*   [ ] Refund of Individual Contribution - Void
*   [ ] Refund of Party Contribution
*   [ ] Refund of Party Contribution - Void
*   [ ] Refund of PAC Contribution
*   [ ] Refund of PAC Contribution - Void
*   [ ] Refund of Unregistered Receipt from Person
*   [ ] Refund of Unregistered Receipt from Person - Void

Federal Election Activity Expenditures:

*   [ ] 100% Federal Election Activity Payment
*   [ ] Credit Card Payment for 100% Federal Election Activity
*   [ ] Staff Reimbursement for 100% Federal Election Activity
*   [ ] Payment to Payroll for 100% Federal Election Activity
*   [ ] Void of 100% Federal Election Activity

Independent Expenditures:

*   [ ] Independent Expenditure
*   [ ] Multistate Independent Expenditure
*   [ ] Credit Card Payment for Independent Expenditure
*   [ ] Staff Reimbursement for Independent Expenditure
*   [ ] Payment to Payroll for Independent Expenditure
*   [ ] Void of Independent Expenditure

***Add a loan or debt***

*   [ ] Loan Received from Individual
*   [ ] Loan Received from Bank
*   [ ] Loan by Committee
*   [ ] Debt Owed to Committee
*   [ ] Debt Owed by Committee

Dev Notes

*   Committee Type can be determined using the following: [https://docs.google.com/spreadsheets/d/10fwbBXjS9C3N0Q2QqjWbyPpWF_ow4F59WdZbh0_osu4/edit#gid=1295372537](https://docs.google.com/spreadsheets/d/10fwbBXjS9C3N0Q2QqjWbyPpWF_ow4F59WdZbh0_osu4/edit#gid=1295372537)

*   Schedule A and B PTY and PAC/PTY Transactions:
    [https://docs.google.com/spreadsheets/d/1PfDEfdMtUmiLIW1pOeA7_M4_lbwzs3Bb/edit?usp=drive_link&ouid=101369876548603687926&rtpof=true&sd=true](https://docs.google.com/spreadsheets/d/1PfDEfdMtUmiLIW1pOeA7_M4_lbwzs3Bb/edit?usp=drive_link&ouid=101369876548603687926&rtpof=true&sd=true)

       //

### QA Notes ###
- [x] BA/Design Quality Checklist complete
- Will need to test using a PTY committee type, such as a Non-qulified Joint Fundraiser Party (Committee Designation J and Committee Type X)

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-581](https://fecgov.atlassian.net/browse/FECFILE-581)

**Comment by AureliaKhorsand** [comment]
@GreggMoreland I'm thinking it would be helpful to condense the lists into one, so it's easy to go straight down the page and check them off when testing. Also, could you maybe add the transaction groupings like they appear in the app as well, and give some committee type options for testing like in #1472 ? Thanks!

**Comment by GreggMoreland** [comment]
@AureliaKhorsand Updated as requested

**Comment by sasha-dresden** [comment]
@AureliaKhorsand I just want to confirm the list for Disbursement Other Expenditures. The following aren't shown on the Acceptance Criteria, however, they appear like they are listed as visible for PTY committees according to the excel document.
National Party Headquarters Buildings Account Disbursement
National Party Pres. Nominating Convention Account Disbursement
Tribal Refund - National Party Headquarters Buildings Account
Tribal Refund - National Party Pres. Nominating Convention Account
Tribal Refund - National Party Recount/Legal Proceedings Account
Other Committee Refund - National Party Headquarters Buildings Account
Other Committee Refund - National Party Pres. Nominating Convention Account
Other Committee Refund - National Party Recount/Legal Proceedings Account

**Comment by GreggMoreland** [comment]
@sasha-dresden @AureliaKhorsand 

AC's updated and validated, spreasheet link updated with a new validated list.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA verified the following transactions show for PTY Committee (copied AC list to verify). (Note: Tested Individual Receipt, Party Receipt, Operating Expenditure, Contribution to Candidate transactions - verified transactions were created and saved)

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/723187ac-28b0-4bc3-ab95-79efb62856e6)

_____________________________________________________________________________________________________________________________

**Add a receipt**
Contributions from Individuals/Persons:
- [x] Individual Receipt
- [x] Tribal Receipt
- [x] Partnership Receipt
- [x] In-kind Receipt
- [x] Returned/Bounced Receipt
- [x] Earmark Receipt
- [x] Conduit Earmark Receipt
- [x] Receipt from Unregistered Entity
- [x] Receipt from Unregistered Entity - Returned/Bounced Receipt

Contributions from registered filers:
- [x] Party Receipt
- [x] Party In-kind Receipt
- [x] Party Returned/Bounced Receipt
- [x] PAC Receipt
- [x] PAC In-kind Receipt
- [x] PAC Earmark Receipt
- [x] PAC Conduit Earmark
- [x] PAC Returned/Bounced Receipt

Transfers:
- [x] Transfer
- [x] Joint Fundraising Transfer
- [x] In-kind Transfer
- [x] In-kind Transfer - Federal Election Activity
- [x] Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account
- [x] Joint Fundraising Transfer - National Party Pres. Nominating Convention Account
- [x] Joint Fundraising Transfer - National Party Headquarters Buildings Account

Refunds:
- [x] Refund of Contribution to Federal Candidate
- [x] Refund of Contribution to Other Political Committee
- [x] Refund of Contribution to Unregistered Committee

Other:
- [x] Offset to Operating Expenditures
- [x] Other Receipts
- [x] Individual Recount Receipt
- [x] Party Recount Receipt
- [x] PAC Recount Receipt
- [x] Tribal Recount Receipt
- [x] Partnership Recount Account Receipt
- [x] Individual National Party Recount/Legal Proceedings Account
- [x] Party National Party Recount/Legal Proceedings Account
- [x] PAC National Party Recount/Legal Proceedings Account
- [x] Tribal National Party Recount/Legal Proceedings Account
- [x] Partnership National Party Recount/Legal Proceedings Account 
- [x] Individual National Party Headquarters Buildings Account
- [x] Party National Party Headquarters Buildings Account
- [x] PAC National Party Headquarters Buildings Account
- [x] Tribal National Party Headquarters Buildings Account
- [x] Partnership National Party Headquarters Buildings Account
- [x] Individual National Party Pres. Nominating Convention Account
- [x] Party National Party Pres. Nominating Convention Account
- [x] PAC National Party Pres. Nominating Convention Account
- [x] Tribal National Party Pres. Nominating Convention Account
- [x] Partnership National Party Pres. Nominating Convention Account
- [x] Earmark Receipt for National Party Recount/Legal Proceedings Account (Contribution)
- [x] Earmark Receipt for National Party Pres. Nominating Convention Account (Contribution)
- [x] Earmark Receipt for National Party Headquarters Buildings Account (Contribution)

**Add a disbursement**
Operating expenditures:
- [x] Operating Expenditure
- [x] Credit Card Payment for Operating Expenditure
- [x] Staff Reimbursement for Operating Expenditure
- [x] Payment to Payroll for Operating Expenditure
- [x] Void of Operating Expenditure **(NOTE Name in list shows Operating Expenditure - Void)**

Contributions/expenditures to registered filers:
- [x] Transfers to Affiliates/Other Committees
- [x] Contribution to Candidate
- [x] Void of Contribution to Candidate
- [x] Contribution to Other Committee
- [x] Void of Contribution to Other Committee
- [x] In-kind Contribution to Candidate
- [x] In-kind Contribution to Other Committee

Other Expenditures:
- [x] Other Disbursements
- [x] Credit Card Payment for Other Disbursement
- [x] Staff Reimbursement for Other Disbursement
- [x] Payment to Payroll for Other Disbursement
- [x] Void of Other Disbursement
- [x] Recount Account Disbursement
- [x] National Party Recount/Legal Proceedings Account Disbursement
- [x] National Party Headquarters Buildings Account Disbursement
- [x] National Party Pres. Nominating Convention Account Disbursement
- [x] Individual Refund - National Party Headquarters Buildings Account
- [x] Other Committee Refund - National Party Headquarters Buildings Account
- [x] Tribal Refund - National Party Headquarters Buildings Account
- [x] Individual Refund - National Party Pres. Nominating Convention Account
- [x] Other Committee Refund - National Party Pres. Nominating Convention Account
- [x] Tribal Refund - National Party Pres. Nominating Convention Account
- [x] Individual Refund - National Party Recount/Legal Proceedings Account
- [x] Other Committee Refund - National Party Recount/Legal Proceedings Account
- [x] Tribal Refund - National Party Recount/Legal Proceedings Account


Refund:
- [x] Refund of Individual Contribution
- [x] Refund of Individual Contribution - Void
- [x] Refund of Party Contribution
- [x] Refund of Party Contribution - Void
- [x] Refund of PAC Contribution
- [x] Refund of PAC Contribution - Void
- [x] Refund of Unregistered Receipt from Person
- [x] Refund of Unregistered Receipt from Person - Void

Federal Election Activity Expenditures:
- [x] 100% Federal Election Activity Payment
- [x] Credit Card Payment for 100% Federal Election Activity
- [x] Staff Reimbursement for 100% Federal Election Activity
- [x] Payment to Payroll for 100% Federal Election Activity
- [x] Void of 100% Federal Election Activity

Independent Expenditures:
- [x] Independent Expenditure
- [x] Multistate Independent Expenditure
- [x] Credit Card Payment for Independent Expenditure
- [x] Staff Reimbursement for Independent Expenditure
- [x] Payment to Payroll for Independent Expenditure
- [x] Void of Independent Expenditure

**Add a loan or debt**
- [x] Loan Received from Individual
- [x] Loan Received from Bank
- [x] Loan by Committee
- [x] Debt Owed to Committee
- [x] Debt Owed by Committee

_______________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
