### ISSUE TITLE
System to show all Schedule E transactions for any Committee Type

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1473]
### Business Reason ### 

As a Committee Administrator, I will be able to see, create, and update all Schedule E transactions regardless of my committee type so that I can only create and update the transactions that apply to my committee type.

### Acceptance Criteria ### 

**If** I am a Committee Administrator for a PAC committee type or PTY committee type or PAC/PTY Committee Type (Committee Type is included [HERE](https://docs.google.com/spreadsheets/d/10fwbBXjS9C3N0Q2QqjWbyPpWF_ow4F59WdZbh0_osu4/edit#gid=1295372537))
**When** I see which Schedule E transactions are available for me to add and update on a report
**Then** I will see all of the PAC/PTY transactions listed in [here]( https://docs.google.com/spreadsheets/d/1JzELCLpZ8qy5vC0DgQ8OHqz3dnq_VsIV/edit#gid=564782748)

### QA Notes
- [ ] BA/Design Quality Checklist complete
-- All Schedule E transactions are available for both PAC and PTY committee types.

### Dev Notes
- Committee Type can be determined using the following: https://docs.google.com/spreadsheets/d/10fwbBXjS9C3N0Q2QqjWbyPpWF_ow4F59WdZbh0_osu4/edit#gid=1295372537
-- All Schedule E transactions are available for both PAC and PTY committee types.

**Comment by AureliaKhorsand** [comment]
Closed as OBE, covered in #404, #1472, and #1659.
