### ISSUE TITLE
Fix label under "Debt Owed by Committee" and "Debt Owed to Committee".   Remove "DEBT REPAYMENT" as this label shouldn't be displayed.

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1477]
During QA and DEV review the label under "Debt Owed by Committee" and "Debt Owed to Committee" should not be in this transaction as this is not a repayment. Remove "DEBT REPAYMENT" label under "Debt Owed by Committee" and "Debt Owed to Committee" transaction name.

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3lTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e533db67fdf2821b6b2cbd4897e27148a35bd53/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3lTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e533db67fdf2821b6b2cbd4897e27148a35bd53/image.png))

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE9TQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50af4abee5929577719b460011304902892111de/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE9TQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50af4abee5929577719b460011304902892111de/image.png))

@MitchellTCG @mjtravers assigned to Sprint 33, bug fix 1 pt and assigned to @mjtravers Bug found in Sprint 33 testing.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-577](https://fecgov.atlassian.net/browse/FECFILE-577)

**Comment by mjtravers** [comment]
There is a CR comment in the PR. Sending back to "In Progress".
https://github.com/fecgov/fecfile-web-app/pull/1512

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "DEBT REPAYMENT" label under "Debt Owed by Committee" and "Debt Owed to Committee" transaction name was removed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWpUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d4b9fb927c8024ac61e6580a2fe8477786664e6/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW5UQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5b83e483c9d73ad008bd44369d1ae32e99b247d/image.png)

QA Review Completed.   Moved to Stage Ready.
