### ISSUE TITLE
Allow user to amend a Form 24 report

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1488]
Business Reason 
 

As a user, I will be able to amend a submitted Form 24 report so that I can provide FEC with the correct information per regulations.

 Acceptance Criteria 
 

**Given** the user has a Form 24 report in 'Submission success' status,
**Then** they will have the option in the action menu to "Amend" 
**And** when they amend the report, then:
- the report will have a status of 'In progress'
- the report will have a version of "Amendment X", where "X" is the amendment number
- the report and transactions will be completely editable

---

**Given** I have amended a report
**When** I add new transactions,
**Then** they will appear following the same ordering logic on an original report (copied below)

1. Within a report, by **Schedule**
2. Within a schedule, by **Line Number**
3. Within line number, **by order transaction was created**
4. And child transactions be displayed directly after the parent in the order in which they were created **only if it is in the same schedule.** If the associated transaction is in a different schedule, it will be listed within that schedule following the rules above.

# Select Amend
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGdXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a512159f8f3933d2c1cf1d132ee7e683c8ff637/1102%20Amend.png)

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
- Functionality is the same as amending a Form 3X.
- There will be no option to auto-generate additional amendments when amending a Form 24.
### DEV Notes ### 
  Wireframes

### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg Does this mean they'd never have the option to edit the Original Amendment Date before submitting?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
As of right now, no. But we can tuck it somewhere in the submit workflow.

As a reference, a user can't currently update the coverage dates of a report.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG so to confirm, we are keeping the box for Original Amendment date here, and the user will be unable to change it before they submit?

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified a Form 24 "Submission successful" can be amended.  

<img width="1172" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUhKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50b1bc58bd04f513cc7fa1801b347faff918dba6/image.png" alt="image.png" />

_____________________________________________________________________________________________________________________________
Verify after selecting "Amend" the report version is changed to "Amendment 1"
<img width="1090" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUxKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b26325f1acb2272abe6fa024f55429a10cf872a6/image.png" alt="image.png" />
_____________________________________________________________________________________________________________________________
@mjtravers @MitchellTCG 

Incremental Amendment numbers will be verified and ad-hoc tested upon completion of ticket 1489 (Form 24 Submission of Amendments)   Current status only shows Amendment 1 until submission.  Ticket passes.
_____________________________________________________________________________________________________________________________
QA Review Completed.   Moved to Stage Ready.
