### ISSUE TITLE
Allow user to submit an amended Form 24 report

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1489]
Business Reason

As a user, I will be able to submit an amended Form 24 report so that I can report any needed updates to FEC.

Acceptance Criteria

***Given*** the user has an amended report in 'In progress' status

  ***and*** they go to submit the report,

  ***Then*** they will have the _option_ to enter a "Backdoor Code" (YES/NO)

  ***And*** if they select "YES", they will be required to enter a backdoor code in order to save (max length A/N-16 per specifications).

  ***and*** upon submission, the *.fec file will reflect the following:

*   the Form 24 specification form type will read "F24A"
*   the header record will now include ***Rpt ID*** (FEC filing ID of original report) and ***Rpt Number*** (sequential number of amendments.)
*   ORIGINAL AMENDMENT DATE will be the Date Submitted from the previous version of the report
*   ***and*** if backdoor code was submitted, that backdoor code will be added to the end of the ***amendment ID*** on the JSON file that is send to FEC along with the generated .fec file

1.  Confirm info
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVFXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f3c01a8ffb8f7f91ed3171d0cf0d8bd8dcee11d/1489%20-%20Confirm%20Info.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVFXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f3c01a8ffb8f7f91ed3171d0cf0d8bd8dcee11d/1489%20-%20Confirm%20Info.png))

1.  Backdoor question
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVVXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--315f2f3f92c2e5365c53bdc740f4ebb69bd44fc3/1338%20-%20Submit%20report%20Backdoor%20Question.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVVXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--315f2f3f92c2e5365c53bdc740f4ebb69bd44fc3/1338%20-%20Submit%20report%20Backdoor%20Question.png))

1.  Submit report backdoor
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWNXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4409f927f34e64953eb96661a0424c6552e5ce4/1338%20-%20Submit%20report%20Backdoor.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWNXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4409f927f34e64953eb96661a0424c6552e5ce4/1338%20-%20Submit%20report%20Backdoor.png))

### QA Notes ###
- [x] BA/Design Quality Checklist complete
- Only amended Form 24 reports will require an Original Amendment Date in the *.fec file. This will be the same as the Date Submitted from the previous version of the report.

### DEV Notes ###
 Wireframes

### Design ###
null

[FECFILE-572](https://fecgov.atlassian.net/browse/FECFILE-572)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
mocks added

**Comment by GreggMoreland** [comment]
@AureliaKhorsand The AC mentions Form 3X instructions for the .fec   What goes on the .fec for Form 24?

**Comment by AureliaKhorsand** [comment]
@GreggMoreland referenced the spec [here](https://docs.google.com/spreadsheets/d/1V-iOx4l6OzLrfIYRyK_iTzQz3Q1BCYj0/edit#gid=715507782). Updated the AC so that form type will read "F24A".

**Comment by Elaine-Krauss-TCG** [comment]
The issue with Original Amendment Date not being populated when submitting amended F24s has been addressed, and web check reports zero errors and no warnings that are unique to F24.

<img width="740" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekxQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24799accca034bb23f9e49f7ed0364cb3da35b14/image.png" alt="image.png" />

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
**QA review tested using Login.gov and Test Committee ID C00100495 assigned to QA for testing.**
______________________________________________________________________________________________________________________
Test Prerequisite Form 24 Submitted Successfully and displayed in Manage reports table.

<img width="1490" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzMyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d0afa7778a67e64db0de9a286a4c339e8d990f8/image.png" alt="image.png" />

_______________________________________________________________________________________________________________________
Under the "Actions" dropdown select "Amend" 

<img width="1504" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDMyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7821ac0c0f28b444b0fcf6012a8c1fb58929e165/image.png" alt="image.png" />

_________________________________________________________________________________________________________________________
Verify Manage reports table Form 24 "Version" is updated to "Amendment 1"

<img width="1285" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVQyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--235a3f2b0a63cec9fcaaba6f0622712830b20f93/image.png" alt="image.png" />

______________________________________________________________________________________________________________________
Under the "Actions" dropdown select "Edit report".   Make a change in report resave.

<img width="1337" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW4yQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c1a1a2d1d811bd1e80733808045013a2ef98455/image.png" alt="image.png" />

Select "Submit Report" from the Left NAV bar.  
________________________________________________________________________________________________________________________
Are you sure?  popup window is displayed.  Then select "Yes"

<img width="983" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTcyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e1590df92f75c2c9c52b814e4d3edb5ccfaa9547/image.png" alt="image.png" />

_________________________________________________________________________________________________________________________
Verify "Thank you for submitting your report" page is displayed.

<img width="1251" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkgyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--211fba5e015f4bd9f8e06dd2b258b028c40900db/image.png" alt="image.png" />

_____________________________________________________________________________________________________________________
Verify on the Manage reports page Form 24 Amendment 1 was Successfully submitted.

<img width="1275" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlAyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a972cc1417d4ba34925f53112df0b48dae81d7b/image.png" alt="image.png" />

__________________________________________________________________________________________________________________________
Repeated above steps and verified "Amendment 2" Successfully Submitted.

<img width="1203" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlQyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1bdcfe8f2f88c1a7a49099a24e00cd301e13548b/image.png" alt="image.png" />
_______________________________________________________________________________________________________________

Email received "FEC electronic filing results" Amendment Report received and accepted.

<img width="715" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0gyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d3458e2e967d3acfa14efc7b4e77b149c2959a2/image.png" alt="image.png" />
______________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
