### ISSUE TITLE
Update to Calendar YTD and entity aggregation on Tier 2 Schedule E transactions

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1491]
Business Reason

As a user, I will be able to see the Schedule E Tier 1 Calendar YTD aggregate on the Tier 2 transaction, and the Tier 2 transaction will be disaggregated although the entity aggregate is still calculated so that I can accurately report on transaction and entity aggregates.

Acceptance Criteria

***Given*** I am a user

  ***When*** I create any Tier 2 Schedule E transaction

*   Credit Card Memo for Independent Expenditure
*   Staff Reimbursement Memo for Independent Expenditure
*   Payment to Payroll Memo for Independent Expenditure

***Then*** the Calendar YTD for the Tier 2 transaction will display the value that is on the Tier 1 transaction,

  ***And*** the Tier 2 transaction will be disaggregated and marked as such (this is in regards to the per election office/sought aggregation)

### QA Notes ###
- [x] BA/Design Quality Checklist complete
 - There will be no per election/office sought aggregate calculated for the Tier 2, it's just a copy of the Tier 1.
**PLEASE NOTE:** This is separate from the entity aggregate calculated on the back end for itemization purposes. That will still be calculated.
- Any Tier 2 Schedule E transaction amount will NOT be included in the Calendar YTD aggregation.

### DEV Notes ###
- The entity aggregate must still be calculated for itemization purposes on the back end. That logic does not change.
- Any Tier 2 Schedule E transaction amount will NOT be included in the Calendar YTD aggregation.
- To implement, add a Q() statement to the Django query that calculates the calendar_ytd aggregation that excludes transactions that have a parent_id.

### Design ###
null

 See full ticket and images here: [FECFILE-571](https://fecgov.atlassian.net/browse/FECFILE-571)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "CALENDAR YEAR-TO-DATE" field in the Memo Transaction(s) (tier 2) for Schedule E Independent Expenditures is displaying what is "aggregated" in the Independent Transaction (s) (tier 1) "CALENDAR YEAR-TO-DATE" field content.  (Note: the amount field in the memo transaction(s) are not calculated in the "CALENDAR YEAR-TO-DATE" field).

The transactions **listed in the Acceptance Criteria** were used to test this functionality.

1.  Credit Card Memo for Independent Expenditure
2.  Staff Reimbursement Memo for Independent Expenditure
3.  Payment to Payroll Memo for Independent Expenditure
 ------------------------------------------------------------------------
1.  Below screenshot for Credit Card Payment for Independent Expenditure "CALENDAR YEAR-TO-DATE" is displaying correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi9uQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf611d4f43eac3428c85cd2fad16d297095bdb9a/image.png)

1.  Below screenshot for Credit Card Memo for Independent Expenditure "CALENDAR YEAR-TO-DATE" is displaying correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1huQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--faeed502ba965ea8d37d465648db6e45daa4e8fe/image.png)

2.  Below screenshot for Staff Reimbursement for Independent Expenditure "CALENDAR YEAR-TO-DATE" is displaying correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3JuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b8541cc2a58cd50b92624efeab314b32cf41a3f/image.png)

2.  Below screenshot for Staff Reimbursement Memo for Independent Expenditure "CALENDAR YEAR-TO-DATE" is displaying correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEhuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ed4950637c7643d88ac50054bbd0a3c42e08cae/image.png)

3.  Below screenshot for Payment to Payroll for Independent Expenditure "CALENDAR YEAR-TO-DATE" is displaying correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODduQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a398cb9a3922e842f0111107df8f21c33b2e2a4/image.png)

3.  Below screenshot for Payroll Memo for Independent Expenditure "CALENDAR YEAR-TO-DATE" is displaying correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW5uQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d0c9489ecf23fa22445015f0e2eff163f010b8f/image.png)

QA Review Completed.  Moved to Stage Ready.
