### ISSUE TITLE
Allow user to delete an existing guarantor on a Loan

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1492]
Business Reason

As a user, I will be able to delete a guarantor on a Schedule C loan so that I can update and report the guarantors associated with my loan.

 Acceptance Criteria

**Given** I have a Schedule C Loan with one or more guarantors
**When** I access the action kebab menu next to an existing Guarantor
**Then** I will have the ability to "delete" a guarantor
**And** when I click on Delete
**Then** that guarantor will be deleted.

 Wireframe
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmtWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b6af991e4a7444e2fc6a5395d31d800fe5ef0b80/1492%20-%20Allow%20user%20to%20delete%20an%20existing%20guarantor%20on%20a%20Loan.png)

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
### DEV Notes ### 
 - This is a soft delete
-
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Please review

**Comment by mjtravers** [comment]
One unit test needs to be fixed up. The last one in transaction-guarantors.compoentn.spec.ts. Sending back to In Progress.

**Comment by mjtravers** [comment]
During CR, I noticed the "Edit" action link on the guarantor list table is not working. It is working on the develop branch. Sending ticket back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified a Guarantor on a loan can be deleted.  (Note:  once deleted not retrievable)

Verified list of Guarantors is displayed (e.g., used Loan Received from Individual - Schedule C for testing)

<img width="1175" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2R6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7db46f07778ae875a4e18bf4058bbc7766cca731/image.png" alt="image.png" />

Select "Delete" from the "Actions" dropdown list for a particular Guarantor

<img width="1182" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2x6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c72f3f6dd1f606dd6b127064c13e25246e55ff6a/image.png" alt="image.png" />

Verify "Confirm" popup window is displayed.

<img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3R6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c6b3c23f892dea579849a045180ff5117aeba12/image.png" alt="image.png" />

If select "No" return to Guarantors.   If select "Yes" verify Guarantor is deleted from the list.

<img width="1169" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzl6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50e578c7d56485a0f237c4c30ebbc7b6fae07aa1/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
