### ISSUE TITLE
Set up CDN/custom domain for Angular web app, update app settings for new domain

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#1493]
Business Reason

As a technical requirement, we need a CDN in place for security/performance reasons As a user, I want to trust that I'm on a FEC system and the URL [https://fecfile-web-app-prod.app.cloud.gov/](https://fecfile-web-app-prod.app.cloud.gov/) isn't on the FEC domain.

In order for the lower environments, we should set this up in dev/stage as well. Something like:

*   dev.fecfile.fec.gov
*   stage.fecfile.fec.gov
*   fecfile.fec.gov

See also [https://github.com/fecgov/fecfile-web-api/issues/780](https://github.com/fecgov/fecfile-web-api/issues/780)

### QA Notes ###

 
 - [ ] BA/Design Quality Checklist complete

### DEV Notes ###

 
 - Use AWS Route 53 to set up DNS records - FEC DNS is a little wonky so it will need to be an apex domain. So it might make the most sense to make fecfile.fec.gov an apex and do subdomains for dev.fecfile.fec.gov, stage.fecfile.fec.gov.
- If there is a difference between the app and api domains (currently, they are fecfile-web-api-stage.app.cloud.gov and fecfile-web-app-stage.app.cloud.gov for example), then the FFAPI_COOKIE_DOMAIN environment variable will need to be set to a value that includes both (currently, it is set to .app.cloud.gov for example) so that the client can access necessary api cookies.
- Test on FEC VPN - www redirect sends internal traffic to fec.gov (fec-proxy app) we might need to make sure that FEC HQ traffic gets routed to fecfile properly
- What about www.fecfile.fec.gov?
- Login.gov sandbox configuration - needs new redirect URLs

domain-with-cdn plan: https://cloud.gov/docs/services/external-domain-service/

### Design ###

 
 null

 See full ticket and images here: [FECFILE-569](https://fecgov.atlassian.net/browse/FECFILE-569)

**Comment by MitchellTCG** [comment]
Dependent on [#780](https://github.com/fecgov/fecfile-web-api/issues/780)

**Comment by MitchellTCG** [comment]
@lbeaufort will add a follow on ticket dealing with Cache issue.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

All browsers are able to use the new URL at https://dev.fecfile.fec.gov/login/
