### ISSUE TITLE
Allow user to add report memo text to the Form 24 report

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1496]
Business Reason 
 

As a user, I will be able to add memo text at the report level so that I can provide additional information needed to FEC upon submission and have it become part of the public record.

 Acceptance Criteria 
 

**Given** I am editing a Form 24 report (status: in-Progress)
**Then** I will be able to add report memo text at the report level _(4000 character limit)_
**And** the user will be able to save the Report level memo text.
**And** the user can edit as needed before the report is submitted.

 Dev Notes 

Let's refactor the reports/f3x/report-level-memo into a common component used across all reports. The new shared component can be created in the directory reports/shared/report-level-memo.

Memo records should be saved in their own table and linked to their report with a foreign key.

 Wireframe
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDBWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2de35e32e4015d51475c8ab2377f6f59ea8c84f/1496%20Report%20level%20memo.png)

### QA Notes ### 
 
- [x] BA/Design Quality Checklist complete

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@GreggMoreland 
please review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting a Form 24 from the Manage reports table, then selecting Edit Report 

<img width="1325" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGlvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20a2cbeac597605eecb804d2c670decfc3e32f0a/image.png" alt="image.png" />

Transactions in this report page is then displayed.

<img width="1396" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG1vQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d853fa8384da01d86198d30819dd820b630e4245/image.png" alt="image.png" />

_____________________________________________________________________________________________________________________________
From the Left NAV - select "REVIEW A REPORT" left NAV expands to include "ADD A REPORT LEVEL MEMO"

<img width="262" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDJvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20a2ba96e5b31dbb8adfe1839406dc5eb9c22d66/image.png" alt="image.png" />


(NOTE:   @MitchellTCG @mjtravers The grayed out boxes under REVIEW A REPORT will be addressed in a future ticket.)
_____________________________________________________________________________________________________________________________
Verified "Report level memo" is displayed.

<img width="1399" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUdvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1eea020f7b9638372e7ed2ec8a7b6ee14f65897/image.png" alt="image.png" />

Select "Save & Continue" button, the "Transactions in this report" page is redisplayed.

<img width="1382" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVNvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b4a3bd40b76082942c90a3289a6a8da66db3757/image.png" alt="image.png" />

Reopen the "ADD A REPORT LEVEL MEMO", verify text previous entered and saved is displayed.

<img width="1107" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXVvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d8eb6d4e33521b96ec17de7ef66e04aa0d439df/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
