### ISSUE TITLE
Allow user to add Independent Expenditures to a Form 24 report

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1499]
Business Reason

As a user, I will be able to add Independent Expenditures (Schedule E transactions) to a Form 24 report as needed so I can accurately report to the FEC within the allotted timeframe.

 Acceptance Criteria

**Given** a Form 24 report (in-progress)
**When** the user opens the Form 24 report from the Reports table,
**Then** they will land on the Transactions table with only a Disbursements section.

---

**When** the user goes to "Add a disbursement"
**Then** they will be able to add the follow transactions:

- Independent Expenditure
- Void of Independent Expenditure
- Multistate Independent Expenditure
- Credit Card Payment for Independent Expenditure
- Staff Reimbursement for Independent Expenditure
- Payment to Payroll for Independent Expenditure

**and** there will be NO ability to mark the transactions as memo items.

 Wireframes

# Transactions in this report page
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzRWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f51e03d8e94405a2ece2269b982a0fae6a9c2358/1499%20Transaction%20Page.png)

# Add an independent expediture
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b377b24244316f0196964c3c229e700220026db3/1499%20add%20IE.png)

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
- The transactions will behave exactly like they do on the Form 3X, including the Tier 2 transactions, _except_ that the transactions cannot be marked as memo items. 
- Transactions table matches Form 3X disbursements section on transactions table.
### DEV Notes ### 
 The core code for this should live in reports/f24 with sharing code (with necessary refactoring of reports/f3x code into the new reports/shared directory) for the transactions and transactions table for this ticket.
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@GreggMoreland 
please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG please add "Void of Independent Expenditure" as a transaction option under "Independent Expenditure" in the wireframe.

**Comment by mjtravers** [comment]
@MitchellTCG A couple of questions on the wireframes:

What is the "#1" in the "Form 24" label. Does this show the order in which this Form24 has been created for this report?

On the left nav there are 2 titles the "Add" page: "Add a disbursement" and "Add an independent expenditure". Which is preferred? I checked other reports and "Add a disbursement" is the norm.

**Comment by mjtravers** [comment]
@Elaine-Krauss-TCG There are a couple of discrepancies between the wireframe and what comes up on the screen:
<img width="683" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXVrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8930e8734682ddd05f7e059dbd6e5d576cca9559/image.png" alt="image.png" />

The title is "Add an independent expenditure" and also has the "Form 24 #1" subtitle. See comment above asking about the "#1"

The box title is "Disbursements" in the wireframe.

I think the accordion should be expanded when the page loads. Or maybe the accordion should be eliminated? I can't think of a case where it would be closed.

I merged develop into the ticket branch to resolve conflicts so you'll want to pull the updates before making changes. Sending ticket back to In Progress.

**Comment by mjtravers** [comment]
Issues with the independent expenditure picker were resolved. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified an Independent Expenditure can be added to the Form 24 report.  Verified Manage your transactions table is updated and displays Independent Expenditures (tested using the IE's displayed in the transactions table)

<img width="1308" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL08yQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0de36097ca9a7e41784e922818ca2bed87502fed/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
