### ISSUE TITLE
Fix/remove Django unit tests that are currently failing

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#15]
***Acceptance Criteria:***

*   Django unit tests should pass in Circle CI
*   At least one Django unit test must be present
*   A unit test should be present that verifies the existence of a test database in the CI environment.
*   Unit tests should be runnable in the docker-compose development environment via a script or single command

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1362](https://fecgov.atlassian.net/browse/FECFILE-1362)

**Comment by WiseQA** [comment]
As noted no QA action required on this ticket - moved to closed as ticket complete.
