### ISSUE TITLE
Fix missing verbiage on first time Submission page.

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1506]
During QA and DEV review when submitting a report the submission page is missing verbiage.  (Tested on Stage using login.gov authentication)  (Tested on both Stage and DEV environments)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnEzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27183426389c148d09611c016cd0b88e24d731a3/image.png)

Verbiage should be - **Congratulations.   Your report was accepted by the FEC.**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjIzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61fb3de325c63b492227d841ac7262302034851c/image.png)

@MitchellTCG @mjtravers fix verbiage on first time Submission page.   Bug fix 2 pts.  assigned to Sprint 35.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
@dheitzer @MitchellTCG With the code change for this ticket, if I go to the report status page for a report I have not yet submitted, I see the "Thank you for submitting..." message. (See below screenshot) Do we have a wireframe somewhere on what to show on the page before a report is submitted? The only ticket I found with a wireframe for this page is [here](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/355) Also, I believe the copy for a report with status of "ACCEPTED", should be changed to "Congratulations. Your report was accepted by the FEC." See ticket AC.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1RTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7944c99c440a20f570a340d5b9da0573e5a1aaa/image.png)


Sending ticket back to In Progress.

**Comment by mjtravers** [comment]
Requested updates made. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified upon submission of report the first message is displayed.  "Thank you for submitting your report. It is currently being processed."

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFg5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9276446616a5d8c874d20d61497cfbf78001b02/image.png)

Status of report is "Submission failure"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGY5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--836446cb4eba17529cc4fb09ed4713db3d73392c/image.png)

On-hold need to review with DEV team.

**Comment by WiseQA** [comment]
QA review verified the submission page verbiage was corrected to read "Congratulations. Your report was accepted by the FEC."

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG9MQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ede83ebecb9f0b8fd1017567ad8b938433ad04e/image.png)

QA Review Completed.   Moved to Stage Ready.
