### ISSUE TITLE
Fix save buttons (e.g., Save both transactions, Save transactions, Save, etc.) functionality.  Once selected button should be disabled.

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1507]
During QA and DEV testing it was verified when creating a transaction using an existing lookup, when clicking the Save button (e.g., Save both transactions, Save transactions, Save, etc.) continuously several times the transaction will be saved however many times the save button was selected. (Tested with Earmark Receipt / Earmark Memo and Joint Fundraising Transfer) (Tested STAGE and DEV)

Below example Joint Fundraising Transfer transactions when selecting "Save" 3 times in a row. (NOTE: A new transaction ID was created for each transaction)

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU80QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0ef90640267d36f48f261723ad89b4796af9d49/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU80QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0ef90640267d36f48f261723ad89b4796af9d49/image.png))

Below Earmark Receipt / Earmark Memo transactions saving several times when continually selecting the "Save' button (e.g., Save both transactions, Save transactions, Save, etc.)

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTY0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef439faa4a6b0b901a1dccfff03320be837ab139/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTY0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef439faa4a6b0b901a1dccfff03320be837ab139/image.png))

### QA Notes ###
null

### DEV Notes ###
Walked through this bug with @toddlees to verify it is all save buttons causing this issue.

@MitchellTCG @mjtravers @toddlees Fix save buttons (e.g., Save both transactions, Save transactions, Save, etc.) functionality.  Once selected button should be disabled.   Bug 5 pts. assigned to Sprint 34.

### Design ###
null

 See full ticket and images here: [FECFILE-560](https://fecgov.atlassian.net/browse/FECFILE-560)

**Comment by WiseQA** [comment]
@mjtravers @dheitzer @MitchellTCG please add comment to this ticket of how this fix was implemented for testing purposes.   Was the save button disabled after clicking once for all save's ?  or how was this fixed.    Thanks

**Comment by mjtravers** [comment]
The fix for the multiple click issue is to disable the button temporarily after it is clicked. A default value of 3 seconds was chosen, but that time limit is changeable. To test this ticket, simply see if you can click fast and get multiple records saved. You will see the button become temporarily disabled for screens that do not transition to a different page after clicked.

**Comment by WiseQA** [comment]
QA review verified fix for multiple click issue for the "Save" buttons was implemented by disabling the button (temporarily) after a single click.  (Retested using Joint Fundraising Transfer)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi9hQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--670019f3ce9fe2a1426084839e06a0cd056e9629/image.png)

Unable to select save multiple times.   Transactions are saving and displaying correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0hhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--98522bb34e8021c65f078bd523f059aee3cbf4fa/image.png)

QA review verified fix for multiple click issue for the "Save both transactions" button was implemented by disabling the button (temporarily) after a single click.  (Retested using Earmark Receipt / Earmark Memo)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3phQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9472f5d512e62cfd83e4767dd1866dcb55840bd2/image.png)

Unable to select save multiple times.   Transactions are saving and displaying correctly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOERhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e1e9e75922dfa11294efb029c4a8a9bf5604000/image.png)

QA Review Completed.   Moved to Stage Ready.
