### ISSUE TITLE
Defect - Fix Ticket 1173 and 1174 calculations from 11.c to 11.d in Summary Page and Detailed Summary Page

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1516]
Defect fix calculations in Summary Page and Detailed Summary Page 1173 and 1174 from 11.c to 11.d

11.c Total Contributions (#808) should have been 11.d #283 for both tickets,   Comment in tickets noted for incorrect list in AC.

@MitchellTCG @mjtravers Defect created (hotfix) for Sprint 33.   Defect (hotfix) pointed 2.   

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
The DSP fix was made to change the 11c to 11d when calculating 6c.

Passes CR. Sending to QA. Available on STAGE for QA.

**Comment by WiseQA** [comment]
QA review verified DSP fix made changing 11.c to 11.d calculation correct for 6(c)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0hNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6806c6efb6a003363d0e6accbea36deede0a950/image.png)

QA Review Completed.   Moved to Stage Ready.
