### ISSUE TITLE
Increase application instances in stage/prod

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#152]
We should be running at least 2 application instances to prevent downtime and identify any concurrency issues. Ideally we should make our staging environment match production if we have enough memory. 

- Confirm we have enough memory (max 15 GB, see https://docs.google.com/spreadsheets/d/1EsY3zOFv2mv9-f-sf64xbPI8dUGwEawQN2l68aHtO5w/edit#gid=0
- Update manifest files for web app and Web API to run 2 instances in stage and prod environments

- [x] API dev/stage/prod
- [x] Web app dev/stage/prod

**Acceptance Criteria**
- App works on all 3 spaces: dev, stage, and prod

**Quality Assurance**
- [x] Able to access/log in/use web app: https://fecfile-web-app-dev.app.cloud.gov/
- [x] Able to access API docs page: https://fecfile-web-api-dev.app.cloud.gov/api/docs/

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by lbeaufort** [comment]
cloud.gov org memory tracking doc: https://docs.google.com/spreadsheets/d/1EsY3zOFv2mv9-f-sf64xbPI8dUGwEawQN2l68aHtO5w/edit#gid=0

**Comment by WiseQA** [comment]
Verified access/log in/use web app: https://fecfile-web-app-dev.app.cloud.gov/
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b2a20ac8-620a-4dbb-a151-3e2977fc007f)

Verified access API docs page: https://fecfile-web-api-dev.app.cloud.gov/api/docs/
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/99dd4147-523c-4cb8-9f2c-c6603a9186b4)

QA review completed.  Moved to Stage Ready.
