### ISSUE TITLE
 5a - Summary Page: System to calculate Cash-on-Hand at Beginning of Report Period (Line 6.b) for first report

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1521]
Business Reason

System to auto-populate Cash-on-hand at Beginning of Report Period (Line 6.b) using the value in Line 6.a for the very first report created in FECfile Online to reduce the potential for user error.

Acceptance Criteria

***Given*** a user creates a new Form 3x report

  ***And*** there are no previous Form 3x reports created by the committee

  ***When*** the user enters Cash-on-hand (#196) which is put on 6.a

  ***Then*** the system will copy that value to Line 6.b

### QA Notes ###
- [x] BA/Design Quality Checklist complete
- When Cash On Hand is entered or updated on the first report, that value is currently on 6.a.

### DEV Notes ###
- On very first report, #196 sets initial cash on hand (or zero value)

### Design ###
null

 See full ticket and images here: [FECFILE-557](https://fecgov.atlassian.net/browse/FECFILE-557)

**Comment by toddlees** [comment]
passes cr moving to qa

**Comment by WiseQA** [comment]
@MitchellTCG @AureliaKhorsand per our conversation please clarify COH Column B 6a is the only value I should see in this ticket.   6a Column A will remain blank with no $0.00.

<img width="1356" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzVLQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6cdfd2e6af3ed82ca1c063bae5e6d1b79eb9a510/image.png" alt="image.png" />

**Comment by toddlees** [comment]
@WiseQA @MitchellTCG Fix for issue Shelly found above is deployed to dev.  When the user updates cash on hand, it will updated in 6a and 6b

**Comment by WiseQA** [comment]
QA review verified first time report Cash On Hand entered is displayed on the Summary Page.  Dollar amount displayed in 6(a) "Calendar-Year-To-Date" column and 6(b) "This Period" column.  

<img width="1133" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU5RQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f800b52479d857244fe3f58a78a8cd9da65340f/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
