### ISSUE TITLE
508: Make top nav tabable

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1522]
Issue
Users can not access the top navigation by TABBING

 Tasks
On a page without the left nav:
Tab in this order:
1. "Here's how you know v"
2. FECFile logo
3. Dashboard
4. Reports
5. Transactions
6. contacts
7. Tools
8. Notification bell
9. User Avatar

On a page with the left nav:
Tab in this order:
1. Here's how you know
2. FECFile Online
3. Enter a transactions
4. Manage you transactions
5. Add a receipt
6. Add a disbursement
7. Add loans and debts
8. Review a report
9. submit your report
10. Dashboard
11. Reports
12. Transactions
13. Contacts
14. Tools
15. Notification bell
16. User Avatar

 Recommendation action
- remove "aria-hidden=true" tag from tab buttons

 Solution
- set tag to false

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG sending back to In-Progress for tabbing fix of the "Actions" dropdown.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMy84QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96502a154b7c60f63559344a169726f6d862ff84/image.png)

Note:  @WiseQA this fix is in ticket #1523.   After discussion with @MitchellTCG working as designed.   Returning to QA Review.

**Comment by WiseQA** [comment]
QA review verified tabbing working as designed.   Tested the following tabbing functionality per UX.

On a page without the left nav:
Tab in this order:

"Here's how you know v"
FECFile logo
Dashboard
Reports
Transactions
contacts
Tools
Notification bell
User Avatar
On a page with the left nav:
Tab in this order:

Here's how you know
FECFile Online
Enter a transactions
Manage you transactions
Add a receipt
Add a disbursement
Add loans and debts
Review a report
submit your report
Dashboard
Reports
Transactions
Contacts
Tools
Notification bell
User Avatar

QA Review Completed.   Moved to Stage Ready.
