### ISSUE TITLE
508: Make action kabob tabable for manage reports page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1523]
Issue: 
On the Reports page - No way to tab into Action kebob dropdown menu, tab just moves to the next page item while leaving the dropdown open

 Tasks
(To open the action kebob with the keyboard, tab to the specific kebob and click the spacebar.)
After the dropdown is visible the user should be able to tab through the selection in the dropdown list.

 Wireframe

# Context
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1RpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b86fffaf955e3ac8f20d954759d3823cc2755a4/Screenshot%202023-11-16%20at%204.54.58%E2%80%AFPM.png)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
In CR, I noticed the vertical alignment of the "Add new transactoin" on the MANAGE YOUR TRANSACTION is off. Is this a side effect of the style changes in this ticket?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEQ5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d8e43299cba2c16b4ac8b5cc06954218c1fb073/image.png)

Sending back to In Progress

**Comment by mjtravers** [comment]
From CR: There was a merge conflict with the develop branch and after the merge, the unit tests are not working. Sending back to In Progress for a look at the unit tests.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Tabbing on action kabob on manage reports page not showing the kabob when tabbing.

@MitchellTCG @mjtravers returned to in-progress.

After clearing cache (Wise) this is working as UX designed.   Moving back to QA Review.

**Comment by WiseQA** [comment]
QA review verified, testing on STAGE, when tabbing on the Manage reports page the "Actions" dropdown (kabob) is tabable.  

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlVOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f11694631e13ab08d4f1b75a2bb7c7ae32d082e4/image.png)

When selecting the "Shift > spacebar" the "Actions" dropdown (kabob) is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmtOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15a9a6f79744f5ead5e1b9a00366651101e3310d/image.png)

Verified the "Action" dropdown (kabob) is tabable.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjROQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6b61fe5b11ed2265bae21d5b5ef42cb1a640b85/image.png)

QA verified working as designed by UX.   

QA Review Completed.   Moved to Stage Ready.
