### ISSUE TITLE
508: Name "Manage reports" table

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1524]
Issue:
Table on Manage Reports page is not named

 Task:
Give the table the following description: "Data table of all reports created by the committee broken down by form type, report type, coverage date, status, version, Date filled, and actions."

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by sasha-dresden** [comment]
Screen reader was used to verify label of table.  

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2N5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--afcdd49394245fde66899922858e927ef8e82062/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
QA requested screenshot of change.   @sasha-dresden provided above.  

QA review found typo.   Change "Date filled" to "date filed".   Make "Date" lowercase

<img width="1001" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2N6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c4a4d31dae5975b62df109da46b1957ebec4672/image.png" alt="image.png" />

@sasha-dresden @MitchellTCG returning to in-progress for type fix.

**Comment by toddlees** [comment]
passes cr moving to qa

**Comment by WiseQA** [comment]
QA review verified typo fixed from Date filled to Date filed.  (Date left as UC).

<img width="1524" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0JOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee5b2a9ebaf2a4e6c83c51ed86c1a934774ce1eb/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
