### ISSUE TITLE
508: Redesign "Create new report" modal

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1525]
508 Issue:
It is not possible to tab to the "x"

Task:
Resign
1. Modal should be 512px wide and viable height; 
- Hexcode: #FFFFFF; 
- Border-radius: 4px; 
- box-shadow: 0px 0px 4px 0px rgba(33,33,33,0.5);
2. remove grey background at the top 
3. Change title of the modal from :Select form type" to "Create a new report"
- font: 36px Gandhi Serif bold
- color: #212121
- padding-bottom: 10px (between text and 2px hairline)
4. Make the "x" tabable (make sure this is a description "cancel" on the X
5. Hairline should be 2px thick and 448 px long; color: #212121
6. 64px space between hairline and "Form type text
7. Change dropdown title from "choose form" to From type
- font-family: karla bold
- color: #212121
- change font-size from 16px to 14px
- text all cap
- margin-bottom: 5px 
8. the dropdown should be 400px wide
- text inside of dropdown should be 14px
- center dropdown
9. there should be 64 pixel betwen dropdown and button
10. remove grey background at bottom 
11. center button and remove the check
12. there should be 32 space between bottom of the button and the bottom of the modal

 Wireframe
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXpXQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe5f101d1d2265a92fb0a1b3a55291a10219d34e/1525%20-%20Create%20a%20new%20report%20modal.png)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Assigned ticket review to @MitchellTCG as UX design.

**Comment by MitchellTCG** [comment]
@sasha-dresden 
1. push the modal 250 pixels down the page
2. add an X and make it close 
3. make **R**eport lowercase "Create a new report"

**Comment by mjtravers** [comment]
From CR: The some of the e2e tests are breaking because they can't click the kabob in the tables, such as "Edit report" in the reports table. I suspect it is cypress clashing with the bootstrap updates made for keyboard accessibility. A good test suite to run to see the issue is the reports-f3x-loans-bank suite. Here a screen shot:
<img width="618" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3ViQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f7265de1decea2492b8d50be8793956b3f33183/image.png" alt="image.png" />

Sending ticket back to In Progress to investigate the kabob issue.

**Comment by mjtravers** [comment]
Passes CR with e2e fixes. Sending to QA.

**Comment by WiseQA** [comment]
Assigned ticket review to @MitchellTCG as UX design, as previously discussed with this ticket, to verify requested changed were made. 

1. push the modal 250 pixels down the page
2. add an X and make it close 
3. make **R**eport lowercase "Create a new report"

**Comment by MitchellTCG** [comment]
This ticket meets the acceptance criteria as stated

@WiseQA please move to Stage Ready

**Comment by WiseQA** [comment]
As noted there is no QA review for this ticket passed as stated above.

Ticket review completed.   Moved to Stage Ready
