### ISSUE TITLE
508: Make action kabob tabable for transactions in this report page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1526]
Issue: 
On the transactions in this report page - No way to tab into Action kebob dropdown menu, tab just moves to the next page item while leaving the dropdown open

 Tasks
(To open the action kebob with the keyboard, tab to the specific kebob and click the spacebar.)
After the dropdown is visible the user should be able to tab through the selection in the dropdown list.

 Wireframe

# Context
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2JpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7dde08a72d84ce51fc62849504292f69ae8ba77/Screenshot%202023-11-16%20at%204.56.33%E2%80%AFPM.png)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by sasha-dresden** [comment]
Verified this should be fixed by the same fix applied to #1523

**Comment by mjtravers** [comment]
Same CR as #1523. Sending to QA.

**Comment by WiseQA** [comment]
Tabbing on action kabob on transactions in this report page not showing the kabob when tabbing.

@MitchellTCG @mjtravers returned to in-progress.

After clearing cache (Wise) this is working as UX designed.   Moving back to QA Review.

**Comment by WiseQA** [comment]
QA review verified, testing on STAGE, when tabbing on the Transactions in this report page the "Actions" dropdown (kabob) is tabable.  

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlVOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f11694631e13ab08d4f1b75a2bb7c7ae32d082e4/image.png)

When selecting the "Shift > spacebar" the "Actions" dropdown (kabob) is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3dOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0797e6b4a2ce5f8b72b4220a310239cf2797fa1/image.png)


Verified the "Action" dropdown (kabob) is tabable.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjROQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6b61fe5b11ed2265bae21d5b5ef42cb1a640b85/image.png)

QA verified working as designed by UX.   

QA Review Completed.   Moved to Stage Ready.
