### ISSUE TITLE
Restore Consent & Continue modal when a user logs in

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#153]
When a user logs into the app, they should be presented with a consent and continue modal when first loading the dashboard page. This functionality was lost in the Angular 13 upgrade. See the attached screenshot for UAT version.

![consent-and-continue.png]([https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/0a8b9799-fe8e-4cc3-b27d-f96b6de67988](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/0a8b9799-fe8e-4cc3-b27d-f96b6de67988))

***Acceptance Criteria***

*   As a user who is logging in, I want to see the Consent & Continue modal the first time I load the Dashboard page.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1273](https://fecgov.atlassian.net/browse/FECFILE-1273)

**Comment by AureliaKhorsand** [comment]
@mjtravers how does this relate to the [web-app ticket #120](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/120)? Is this a blocker to that, the technical side, or a duplicate?

**Comment by mjtravers** [comment]
It is a duplicate. I will close out this ticket.
