### ISSUE TITLE
UAT Finding: Fix misspelling of CONTINUE and AUTOMATICALLY on Loan Received from bank

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1536]
Issue:

  Sarah Vivian discovered a couple of misspelled words on "Loan Received from bank" transaction

Task: 

  Under the page header "Loan Received from Bank" fix the following typo

  Sentence three - "Saving a loan received from bank will ***autmatically*** create an associated disbursement."

*   [x] Change to "automatically"

In the footer of Step One:

  Sentence two - Review the disbursement; enter a purpose of disbursement or note/memo text; or ***contiue*** without reviewing and "Save transactions."

*   [x] Change to "continue"

Reference

1.  1.  Task 1
        [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0xvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2189bbb405efb842a7e0e0ce8b310debd711883e/Screenshot%202023-11-17%20at%201.52.34%E2%80%AFPM.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0xvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2189bbb405efb842a7e0e0ce8b310debd711883e/Screenshot%202023-11-17%20at%201.52.34%E2%80%AFPM.png))

1.  1.  Task 2
        [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1RvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--245cb2a48538d4c9953b3e636c1aad0f3937dd0f/Screenshot%202023-11-17%20at%201.52.21%E2%80%AFPM.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1RvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--245cb2a48538d4c9953b3e636c1aad0f3937dd0f/Screenshot%202023-11-17%20at%201.52.21%E2%80%AFPM.png))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-550](https://fecgov.atlassian.net/browse/FECFILE-550)

**Comment by MitchellTCG** [comment]
@GreggMoreland please review

**Comment by GreggMoreland** [comment]
@MitchellTCG Reviewed. Clarified the transaction name (updated it to match the capitalization of the transaction name)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified typo has been fixed.  Changed autmatically to correct spelling automatically.

<img width="1253" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelV5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70b4778c2aa6f5af226cf06db157ca7e6b8d4be5/image.png" alt="image.png" />

Verified typo has been fixed.  Changed contiue to correct spelling continue.

<img width="1200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemd5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4afdbb055c1e53d6550ef21af8007f9f2a8d033/image.png" alt="image.png" />

QA Review Completed.  Moved to Stage Ready (Note will move after Sprint 34 review)
