### ISSUE TITLE
Allow user to switch between associated Committee Accounts without logging out

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1538]
As a user associated with multiple committee accounts, I will be able to switch between committee accounts without logging out so I can save time.

Acceptance Criteria

**Given** the user is on any page _except_ a login page,

**When** they select the account dropdown,

**Then** they can choose “Switch committees”

**And** the system will take them to the committee account selection screen.

Note: Even if the user only has one committee account, it will still function the same, since they would need to go to the committee account selection page to add a new committee.

### DEV Notes ###
**Link in DEV**
https://dev.fecfile.fec.gov/login/select-committee 
**Link on Stage**
https://stage.fecfile.fec.gov/login/select-committee  
**Link on Production**
https://fecfile.fec.gov/login/select-committee 

### Design ###
h2. Wireframes

h3. Current state

!Screenshot 2024-08-14 at 10.24.02 AM.png|width=2133,height=1788,alt="Screenshot 2024-08-14 at 10.24.02 AM.png"!

h3. Ideal State (Select Switch committee)

!Screenshot 2024-08-14 at 10.24.15 AM.png|width=2133,height=1788,alt="Screenshot 2024-08-14 at 10.24.15 AM.png"!

h3. Ideal State (where you will resolve to - “Get started now” page)

!336115898-9f0a4824-b26c-401b-a559-40ac4ebb4b11.png|width=1200,height=827,alt="336115898-9f0a4824-b26c-401b-a559-40ac4ebb4b11.png"!

 See full ticket and images here: [FECFILE-549](https://fecgov.atlassian.net/browse/FECFILE-549)

**Comment by MitchellTCG** [comment]
@GreggMoreland @AureliaKhorsand 
Please review. I added links and wireframes. Let me know what other info to need to update the ACs.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG this is not in Test Release 1, so we are keeping it in the product backlog.
