### ISSUE TITLE
Update Form and Schedule Schemas to match updated specification templates

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1539]
Business Reason

Task 1: Update the Form 3X schema to match the current updated specification standards, using the specification in [this document]([https://docs.google.com/spreadsheets/d/1wdXJVzqHwCY0rU78grDcZl2bD0RppgYO/edit#gid=1170828928](https://docs.google.com/spreadsheets/d/1wdXJVzqHwCY0rU78grDcZl2bD0RppgYO/edit#gid=1170828928))

Task 2: Verify the Form 1M schema matches the current updated specification standards, using the specification in [this document]([https://docs.google.com/spreadsheets/d/1wdXJVzqHwCY0rU78grDcZl2bD0RppgYO/edit#gid=823571419](https://docs.google.com/spreadsheets/d/1wdXJVzqHwCY0rU78grDcZl2bD0RppgYO/edit#gid=823571419)) (Differences highlighed in yellow)

*   [ ] All Form 1M changes are complete

Task 3: Verify the Form 24 schema matches the current updated specification standards, using the specification in [this document]([https://docs.google.com/spreadsheets/d/1wdXJVzqHwCY0rU78grDcZl2bD0RppgYO/edit#gid=624948803](https://docs.google.com/spreadsheets/d/1wdXJVzqHwCY0rU78grDcZl2bD0RppgYO/edit#gid=624948803)) (Differences highlighed in yellow)

*   [ ] All Form 24 changes are complete

Task 4: Verify the Form 99 schema to matches the current updated specification standards, using the specification in [this document]([https://docs.google.com/spreadsheets/d/1wdXJVzqHwCY0rU78grDcZl2bD0RppgYO/edit#gid=624948803](https://docs.google.com/spreadsheets/d/1wdXJVzqHwCY0rU78grDcZl2bD0RppgYO/edit#gid=624948803)) (Differences highlighed in yellow)

*   [ ] All Form 99 changes are complete

### QA Notes ###

 
  
 - [x] BA/Design Quality Checklist complete
- [ ] BA's will verify ticket

### DEV Notes ###

 
  
 - compare with https://fecgov.github.io/fecfile-validate/
- Note: Even though we are including new fields, we know they are not added to the generated *.fec file because there is no COL SEQ #.

### Design ###

 
  
 null

[FECFILE-548](https://fecgov.atlassian.net/browse/FECFILE-548)

**Comment by AureliaKhorsand** [comment]
Thanks @GreggMoreland , let's talk through this at our next sync-up

**Comment by WiseQA** [comment]
No QA review for this tickets as noted in AC BA's verified ticket before moving to QA bucket.

Ticket moved to Stage Ready.

**Comment by AureliaKhorsand** [comment]
@sasha-dresden and @GreggMoreland - has this actually been reviewed? I'm looking at the schemas and they don't seem to be updated. I might be totally missing something, but they should be matching what is in the linked documents.

**Comment by AureliaKhorsand** [comment]
@mjtravers and I chatted, and the schedule updates no longer apply based on how we use (or rather, don't use) the schedule schemas. The schedule schemas match the vendorpak, but we validate against transaction and form schemas. Updated ticket to clarify that it's just the Form ones that need updating. @sasha-dresden @GreggMoreland

**Comment by GreggMoreland** [comment]
@sasha-dresden @mjtravers Here are the things I have found:
- In C1, it has 'X (warerrorning)' in the validation for Lender State. It should be 'X (error)'
- In C2, GUARANTEED AMOUNT has the 'X (error)' in the Rule Reference column but it should be in the Required column

**Comment by mjtravers** [comment]
@GreggMoreland The C1 and C2 specs have had the 2 issues listed above corrected:

https://fecgov.github.io/fecfile-validate/SchC1_spec.html
https://fecgov.github.io/fecfile-validate/SchC2_spec.html

**Comment by GreggMoreland** [comment]
@mjtravers @sasha-dresden @AureliaKhorsand It looks good to me now.
