### ISSUE TITLE
Fix sorting of the columns in "Manage report" table

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1542]
During QA testing and DEV review verified the columns in the "Manage report" table are not sorting when selecting ascending / descending order. Columns need fixed include:

*   Form type (untestable at this time due to one type of form listed)
*   Type of report
*   Coverage dates
*   Status
*   Version
*   Date filed

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnI5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a5dba015d88c57a050a45855c373f94d418b6940/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnI5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a5dba015d88c57a050a45855c373f94d418b6940/image.png))

Dev Note

Default display of columns should be "Ascending" order

@MitchellTCG @mjtravers fix sorting of columns in the "Manage report" table. Bug fix pointed as a 3 point bug fix and assigned to Sprint 35.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-547](https://fecgov.atlassian.net/browse/FECFILE-547)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified sorting of the columns in "Manage report" table was fixed.

<img width="1208" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFEwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ed4f95ed125c8732df59591f74c022c5191c54d/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
