### ISSUE TITLE
Fix Line column in "Transactions in this report" table to initially display ascending order when table is populated

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1543]
During QA testing and DEV review the Line column in "Transactions in this report" table under the Loans and Debts is displaying the order descendng when the "Transactions in this report" table is populated within a transaction.

Fix = The table should be displaying the Line column in Ascending order (e.g., 9, 10). Currently when "Transactions in this report" table is populated the Line column is displaying in decending order (e.g., 10, 9)

[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS85QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b18e72455abb451a762b0513fb7a242d447d785d/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS85QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b18e72455abb451a762b0513fb7a242d447d785d/image.png))

(NOTE: Sort is working correctly)

@MitchellTCG @mjtravers fix the bug for Ascending order display in line column under Loans and Debts in the transactions table. Bug fix pointed as a 2 point bug fix and assigned to Sprint 35.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-546](https://fecgov.atlassian.net/browse/FECFILE-546)

**Comment by dheitzer** [comment]
Line is a character field ("11(a)(i)" for example) and is currently being sorted in lexicographical order.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the Fix for "Transactions in this report" table is displaying the Line column in Ascending order (e.g., 9, 10) when "Transactions in this report" table is populated.

<img width="246" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDgwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19f25fa07d51b5c743557079cca767cbf57a8cf0/image.png" alt="image.png" />

<img width="150" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUUwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdb2754bb95c2f0c2b42a0888cfe2c204897e75d/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
