### ISSUE TITLE
Fix "Manage report" page left NAV appear's which should not appear

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1545]
During QA testing and DEV review verified when selecting Reports from the dashboard and the "Manage report" page is displayed the left NAV bar appears.

Fix the left NAV bar to not appear on the "Manage report" page in a report

@MitchellTCG @mjtravers fix Fix the left NAV bar to not appear from the "Manage report" page in a report. Bug fix pointed as a 2 point bug fix and assigned to Sprint 35.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-545](https://fecgov.atlassian.net/browse/FECFILE-545)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified left NAV removed from "Manage report" page.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDMrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--097ad8f87918f0c69a5139e870495045073b3265/image.png)

QA Review Completed.   Moved to Stage Ready.
