### ISSUE TITLE
Update QUALIFICATION STATUS in .fec header

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1549]
Business Reason

As a [role], I will be able to [blank] so that I can [business reason]

Acceptance Criteria

***Given*** [precedent]

  ***When*** [action]

  ***Then*** [result]

### QA Notes ###
- [ ] BA/Design Quality Checklist complete

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-544](https://fecgov.atlassian.net/browse/FECFILE-544)

**Comment by AureliaKhorsand** [comment]
Closed as duplicate of #1569.
