### ISSUE TITLE
System to allow existing Schedule E transactions to be associated with a Form 24 Report

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1550]
Business Reason

As a user, I want to be able to select one or many Schedule E transactions in a Form 3X report of any status to add to a Form 24 report so that I can accurately report my Independent Expenditures to FEC.

Acceptance Criteria

***Given*** Schedule E transactions on a Form 3X report in _any_ status,

  ***Then*** the user will be able take action on a Tier 1 Schedule E transactions

  ***And*** indicate that they should be on an existing Form 24 report

  ***And*** when they confirm, the transactions and any linked Tier 2 transactions will appear on the selected Form 24 report.

  ***And*** any updates made to the transaction will be reflected in both reports it is present in.

1.  Text in modal:

       This independent expenditure will be added to the following Form 24:
    _and_ 

       ***Note:*** Unitemized IEs on Form 3X will appear itemized on the Form 24\. They will remain unitemized on Form 3X.

report naming convention is 24-Hour Report [Year] [(Number this year)](#(Number this year))

Please add a toast that confirm success

  (Langauge here for toast)

Wireframes

1.  Add to Form 24

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/d559eed3-03b4-4887-9eea-3d7137657190](https://github.com/fecgov/fecfile-web-app/assets/94924171/d559eed3-03b4-4887-9eea-3d713765719))

1.  Confirm modal

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/ecef9c6a-1544-4bdd-91bc-5f9f650d2c14](https://github.com/fecgov/fecfile-web-app/assets/94924171/ecef9c6a-1544-4bdd-91bc-5f9f650d2c1))

1.  If two choices

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/9c207a25-901e-49ea-b2e5-fb26250d7d14](https://github.com/fecgov/fecfile-web-app/assets/94924171/9c207a25-901e-49ea-b2e5-fb26250d7d1))

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/d85b0823-3058-4460-b26e-225c47c798be](https://github.com/fecgov/fecfile-web-app/assets/94924171/d85b0823-3058-4460-b26e-225c47c798b))

Video

1.  Confirm Form 24
    [https://github.com/fecgov/fecfile-web-app/assets/94924171/87c0baa7-2ded-488f-bd75-af270db77d7f](https://github.com/fecgov/fecfile-web-app/assets/94924171/87c0baa7-2ded-488f-bd75-af270db77d7f)

1.  Confirm which Form 24
    [https://github.com/fecgov/fecfile-web-app/assets/94924171/c7249f09-fc03-44b2-ac2e-7b73a014cc02](https://github.com/fecgov/fecfile-web-app/assets/94924171/c7249f09-fc03-44b2-ac2e-7b73a014cc02)

### QA Notes ###
- [ ] BA/Design Quality Checklist complete

### DEV Notes ###
- The system will maintain a single copy of the Schedule E transaction so that when it might be edited in either the Form 3X report or the Form 24 report, it will show the updates in both reports.

### Design ###
null

 See full ticket and images here: [FECFILE-543](https://fecgov.atlassian.net/browse/FECFILE-543)

**Comment by GreggMoreland** [comment]
@MitchellTCG I will modify this ticket based on the design, but here is where you can put the wires for the import (and probably the Manage Transactions page with transactions displayed)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
wires added. let me know if you would like to meet to discuss any other screens

**Comment by MitchellTCG** [comment]
@mary-tcg 
Create a wire:
Please add an opt-in for importing already existing IE's

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg we really need to let the users pick exactly what Schedule E transactions they want in the Form 24, since not all of them may be relevant. We shouldn't be automatically importing them for them. Instead, we need something like a way to select them from the Form 3X report and generate a Form 24 off of them that way? And then what if they need to add more to it later?

**Comment by AureliaKhorsand** [comment]
@MitchellTCG something to consider is letting the users know that if unitemized on the Form 3X, it will still show up on the Form 24 when sent to FEC

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG workflow looks good. Only suggestion is to add language that even if a transaction is unitemized on the Form 3X, it will still show up on the Form 24 when sent to FEC. Perhaps "Unitemized independent expenditures will be included in the Form 24 when submitted to FEC".

**Comment by AureliaKhorsand** [comment]
BA updates needed: how the report names should be displayed, note the Form 24 should be in-progress.

**Comment by MitchellTCG** [comment]
@GreggMoreland 
please review
report naming convention is 24-Hour Report [Year] [#(Number this year)]

**Comment by MitchellTCG** [comment]
@JonellaCulmer 
can you help me come up with toast language for success

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when editing the Schedule E Transaction (Independent Expenditure) and saving the change.   The transaction is updated for both the Form 3x and Form 24. 

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/4934979d-b2f2-4fa4-99c4-3b587df43cc6)

_______________________________________________________________________________________________________________

Verified the dropdown list for a Form 3x displays the "Add to Form24 Report" selection.

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/e61c51bd-b37f-4b96-a868-58e93845e5bc)

_______________________________________________________________________________________________________________________

Select "Add to Form24 Report" verify the "Confirm" popup window is displayed.

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/a1422c38-b120-4d15-8325-62c63db5b55e)

__________________________________________________________________________________________________________________

Select the Form 24 dropdown list the active 24-hour and 48-hour Form 24s are displayed. ( @MitchellTCG  NOTE:  This functionality for displaying list is working as designed to this point.   Functionality passes)

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/391f664a-4a70-4a8b-b0c0-f084004dde8e)

__________________________________________________________________________________________________________________

Verify Form 3x is linked to the Form 24 report.

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/d749fc99-967f-4749-950d-dbc376038537)

___________________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
