### ISSUE TITLE
Allow user to select Qualification fields on Report 1M

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1555]
Business Reason

As a Committee Administrator, I will be able to enter the Qualification fields when I create a Notification of Multi-Candidate Status transaction on Form 1M so that I can submit Notification of Multi-Candidate Status as needed.

Acceptance Criteria

***Given*** the user is on the Reports page

  ***When*** I go to create a new report and select Form 1M

  ***Then*** I will be able to indicate whether they qualify by qualification and required to complete the following fields:

1.  Qualification

       #

If the user indicates that they will qualify by qualification, then they must enter the following:

*   ***DATE OF 51st CONTRIBUTION*** (Required)
*   ***DATE OF ORIGINAL REGISTRATION*** (Required)
*   ***DATE COMMITTEE MET REQUIREMENTS*** (Required)

and ***five*** UNIQUE instances of candidate information, with the fields as follows:

*   ***CANDIDATE ID***(Required)
*   ***CANDIDATE LAST NAME*** (Required)
*   ***CANDIDATE FIRST NAME*** (Required)
*   ***CANDIDATE MIDDLE NAME*** (Optional)
*   ***CANDIDATE PREFIX*** (Optional)
*   ***CANDIDATE SUFFIX*** (Optional)
*   ***CANDIDATE OFFICE*** (Required)
*   ***CANDIDATE STATE*** (Required if CANDIDATE OFFICE is 'House' or 'Senate')
*   ***CANDIDATE DISTRICT*** (Required if CANDIDATE OFFICE is 'House')
*   ***DATE OF CONTRIBUTION*** (Required)

***Then*** I will be able to:

*   Cancel
*   Save
*   Save and continue
*   Edit

Wireframes

1.  Form 1M Qualification - Other collapsed
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemNOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e86564e124c1a51711237c5069f0949af413668d/1292%20-%20Qualification%20Other%20collapsed.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemNOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e86564e124c1a51711237c5069f0949af413668d/1292%20-%20Qualification%20Other%20collapsed.png))

1.  Form 1M Qualification - Other expanded
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmNoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e67e5b8d5e2573cfdff324f39e72ef80dbc15fea/1292%20-%20Qualification%20Other%20Expanded.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmNoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e67e5b8d5e2573cfdff324f39e72ef80dbc15fea/1292%20-%20Qualification%20Other%20Expanded.png))

1.  Form 1M Qualification - Other error
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemtOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e2ace3580b9b8ed3a0e4586416a186ae34823be/1292%20-%20Qualification%20Other%20collapsed%20%E2%80%93%20Errors.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemtOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e2ace3580b9b8ed3a0e4586416a186ae34823be/1292%20-%20Qualification%20Other%20collapsed%20%E2%80%93%20Errors.png))

### QA Notes ###
- [ ] BA/Design Quality Checklist complete

### DEV Notes ###
Once a contact has been selected, ensure that lookups for the other contacts exclude that contact from their results, so that the same contact cannot be used twice.

### Design ###
null

[FECFILE-541](https://fecgov.atlassian.net/browse/FECFILE-541)

**Comment by GreggMoreland** [comment]
@MitchellTCG This is the ticket to split out the qualification fields for 1M

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Fixed last name, First name, Middle etc.
Please Review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
During QA / DEV review when creating the second candidate (using the same candidate ID), which is not allowed, the Candidate ID field doesn't clear (stays red box).  When creating new contact the lookup stays red box.   

@MitchellTCG @mjtravers Adding fix for both.

**Comment by WiseQA** [comment]
QA review verified Form 1M Qualification section.   

<img width="270" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUJOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d101bcc2ed921a52baaf68ec4942476a2cf95ea1/image.png" alt="image.png" />

Verified the 5 candidate(s) have been entered, and the Form 1M is savable.  (Note:   Candidate cannot be entered twice)

Verified "This is a Required Field" errors and "Candidate information is required" error fields functionality working correctly.

QA Review Completed.   Moved to Stage Ready.
