### ISSUE TITLE
Update PDF/print preview UI pages for Form 3X

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1557]
1.  ***Button colors can be dealt with in a future UX Ticket***

Business Reason

As a user, I will be able to generate and view a PDF of my report so that I can see how Form 3X looks as a paper form.

Acceptance Criteria

***Given*** a report in any status

  ***When*** the user goes to the "Print preview" page

  ***Then*** they can generate a PDF of their report in it's current state

  ***And*** when they click to generate a PDF, they will receive a message indicating "This may take a moment..."

  ***And*** if after 5 seconds the PDF:

*   IS ready: the user will have the option to download it as a PDF by opening it in a new tab; the system will provide a date/time stamp for when the PDF was generated; and the button to compile a new PDF will be available.
*   IS NOT ready: the system will indicate that "Your report is still being processed. Please check back later to access your PDF" and the process will continue in the background until it is ready _(Dev note: check status endpoint each time page is accessed)_

***And*** once the URL is no longer available from WebPrint service _(after 24 hours)_, the page resets _(only one button for Compile PDF)_.

Dev Tasks

The report-web-print component should be moved out of the reports/f3x directory and moved into the reports/shared directory to be used by all reports. Rename the component from "report-web-print" to "print-preview" and the referencing routerLink definitions should be updated to /reports/print-preview

The layout/sidebar/menu-report will need to be refactored into 2 sidebars, one for f3x and one for f99., and also update manage of sidebarState values in the ngrx store. The current menu-report can be the one for f3x.

Create an endpoint on the webservice worker to submit a fec file to the FEC WebPrint service. Return the WebPrint response to the Celery broker

Documents: [https://efoservices.fec.gov/static/webprint_help.html#webservice](https://efoservices.fec.gov/static/webprint_help.html#webservice)
[https://webforms.fec.gov/psa/getstarted.htm](https://webforms.fec.gov/psa/getstarted.htm)

![loading--primary.gif]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a2699e4c-620d-421b-99dc-4a23c382af52](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a2699e4c-620d-421b-99dc-4a23c382af52))

1.  Placeholder image (replace fan of 5 form 3x's)
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkVPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3159eeea621d507fab260f57d810b2f2d01e44f/Image%20-Placeholder.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkVPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3159eeea621d507fab260f57d810b2f2d01e44f/Image%20-Placeholder.png))

1.  Would you like to compile
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOThjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba1248e069966c9bc1100574d09b05fe2c23a05e/1557%20Would%20you%20like%20to.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOThjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba1248e069966c9bc1100574d09b05fe2c23a05e/1557%20Would%20you%20like%20to.png))

1.  Compiling
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0FjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4978e802f5fdb4cf1eb33c36e9eaf6fcda57ab16/1557%20-%20compiling.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0FjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4978e802f5fdb4cf1eb33c36e9eaf6fcda57ab16/1557%20-%20compiling.png))

1.  Compiled
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0VjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5a658f5ea10129f7130c6de3e1d85173d09590c/1557%20-%20compilied.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0VjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5a658f5ea10129f7130c6de3e1d85173d09590c/1557%20-%20compilied.png))

1.  processing
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0ljQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe137f59d5422086895980d2f8fad5d706120a2d/1557-%20processing.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0ljQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe137f59d5422086895980d2f8fad5d706120a2d/1557-%20processing.png))

### QA Notes ###
 
 null

### DEV Notes ###
 
 null

### Design ###
 
 - [x] BA/Design Quality Checklist complete

 See full ticket and images here: [FECFILE-540](https://fecgov.atlassian.net/browse/FECFILE-540)

**Comment by GreggMoreland** [comment]
@MitchellTCG Here is the ticket to update the pdf print pages for Form 3x

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Please review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Select Print Preview from the left NAV bar

<img width="1183" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFY5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0362806dd87d960552ccbdc3cbeefeb149fc80a1/image.png" alt="image.png" />

_____________________________________________________________________________________________________________________________
Print preview page "Compile PDF"

<img width="1270" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEo5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f476ec7b5187f2d12e48cf063b9dcb4666a352ef/image.png" alt="image.png" />

_____________________________________________________________________________________________________________________________
@mjtravers @MitchellTCG fix Print Preview windows button, verbiage for each window (see wireframes above).

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG moving to in-progress as a Hotfix for Sprint 35.   Code changes to this ticket will also update ticket #1504 PDF print preview windows

**Comment by mjtravers** [comment]
Hotfix passed CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "Placeholder image" updated on print preview pages.

<img width="1409" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU9GQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--daf4bb3572780d9ce65098c9766d3c4e98bb0390/image.png" alt="image.png" />

Verified verbiage fix for print preview page was added "Would you like to compile a print preview?  

<img width="1409" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVNGQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--434c7d4c6967f4d2e549a95f326eeaeb5474f70e/image.png" alt="image.png" />

During testing Print Preview an "Error ! Email address in invalid" ....

<img width="1346" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVdGQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--625cdc8888a57694cdc4a394c994b51d1afb7a8a/image.png" alt="image.png" />

Selected Submit your report from NAV bar and then selected "Confirm information"  updated email and confirmed information.

<img width="1299" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWFGQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8351bf6d345f7480a9bae1e24ac325bad579353d/image.png" alt="image.png" />

Selected "Print Preview" again email Error still displayed.  (Cache was cleared but will not "Compile pdf"

<img width="1309" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWVGQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d0bc476da2d3a08c6b96e8d80c9d8768983c17e/image.png" alt="image.png" />

@mjtravers putting ticket on-hold until DEV review.

**Comment by WiseQA** [comment]
@mjtravers see above test.   Second test logged in using login.gov and using efo test filing account.  Here's the outcome:

Print preview page displayed correctly.

 <img width="810" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWlGQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b232115713aa95d89be50f60981314b6b9afab5/image.png" alt="image.png" />

Selected "Compiling your preview" 

<img width="789" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW1GQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d9834c7e3a8a321593af9b0e3bba464c87f4770/image.png" alt="image.png" />

Received same Printing error - Email error

<img width="1315" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXFGQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--559d53413bdaaf9eb6e0f3e20e9a5c89477da85a/image.png" alt="image.png" />

@mjtravers tested 2 different ways same error populating.

**Comment by WiseQA** [comment]
@mjtravers "Compiling your preview" page is a continual spin not returning PDF Compiled Print preview page.  (NOTE:  if you select refresh the "Compiling your preview" page will quit spinning and take you to PDF Compiled Print preview page)

<img width="1269" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXVJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09096d1136be9e04b481515ef7b2c66727fc664e/image.png" alt="image.png" />

@mjtravers ticket on-hold until hotfix.

**Comment by mjtravers** [comment]
Hotfix made so that the "Compiling your preview" spinner does not spin forever.

**Comment by mjtravers** [comment]
Processing screen updated with different image:
(screenshot updated)
<img width="705" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGVNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cadb5572ec06efbcf574e60177decb24ca00bb66/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
QA review retested and verified the Print Preview (Placeholder image) PDF have been updated for the Form 3x report.  (Note: used test efo filing Committee using login.gov for testing)

<img width="1316" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUNNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--518ea6e6ac494896f3e5764ee0062c26acf1045f/image.png" alt="image.png" />

Compiling:

<img width="1319" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU9NQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84271fb923c72be4fec66e6c884385f592b4e2ac/image.png" alt="image.png" />

Compiled:

<img width="1308" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVdNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc18d3fff8be31ebdf6ee454e8ead19994f9dac9/image.png" alt="image.png" />

Still processing (Note: The screenshot has been updated and verified by DEV and QA. Due to no wait on processing the verification of Print Preview screen passes testing)

<img width="712" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWFNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d80e9820c7316652f7eba11014c6381791c6e74/image.png" alt="image.png" />

@MitchellTCG @mjtravers per conversation a future ticket will be written to fix button color and verbiage consistency where needed. This ticket passes.

QA Review Completed. Moved to Stage Ready.

**Comment by mjtravers** [comment]
Added colon to the form title:
<img width="705" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmFPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de099cec05f440faf466c31f503f762b7741c603/image.png" alt="image.png" />
