### ISSUE TITLE
Update UI on Form 3x Report Status Submit

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1559]
Business Reason

Task: Update UI to display the Submission Status page on Form 3X with the updated image.

 Acceptance Criteria

**Given** a Form 3x report that has all the information
**When** I click "Submit" on the "Submit report" page
**Then** I will see the "Report status" page with the updated image

# Wireframes

# Congratulations
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXNjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7aa4d479b145d563cd8df116a02a984bd23ae767/1553%20Congratulations.png)

# Processing
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTBjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7774f42b9fd233805401d8b537614ef7aef65855/1553%20processing.png)

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
## UX Comment
We will not change the general look and feel. No new grey box. we will add in illustration instead of old fan of 5 pages

### Design ### 
 null

**Comment by GreggMoreland** [comment]
@MitchellTCG Here is the ticket for the Form 3x submit wires

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Please review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified UI update displaying correct on Form 3x Report Status Submit (example screen shot below of updated UI -  "Congratulations. Your report was accepted by the FEC."

<img width="1143" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0ZzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c556fb8c94280789a98b2e139f08f46ae51c58e8/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
