### ISSUE TITLE
Reorganize web-app code base

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#156]
Business Reason

In order to be able to develop and test the existing and new features of the app, move existing code that is not part of OP1 to the code backlog.

***Tasks***

*   Identify code that is not necessary for OP1 features and move to the code backlog in the repo.
*   Update package.json to suspend phased out dependencies

Acceptance Criteria

*   Users can log into site
*   Dashboard with navigation presents at login

QA

*   Can log into site and view dashboard

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1271](https://fecgov.atlassian.net/browse/FECFILE-1271)

**Comment by WiseQA** [comment]
Log into https://fecfile-web-app-dev.app.cloud.gov/ using test account.   Verified Dashboard appeared.  (Note links not working just display of naming).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/74eab81c-27ca-4189-bf87-6bf59c4c36c4)

QA review completed.  Moved to Stage Ready.
