### ISSUE TITLE
508: Name "Receipts", "Disbursements", and  "Loans and Debts" tables on Transactions in this report page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1562]
Issue:
The following tables on Transactions in this report page is not named

1. Receipts
2. Disbursements
3. Loans and Debts

 Task:
- [ ] Give the "Receipts" table the following description: "Data table of all reports created by the committee broken down by Line, Type, Name, Date, Memo, Amount, Aggregate, Transaction ID, Associated with, and Actions."

- [ ] Give the "Disbursements" table the following description: "Data table of all reports created by the committee broken down by Line, Type, Name, Date, Memo, Amount, Transaction ID, Associated with, and Actions."

- [ ] Give the "Loans and Debts" table the following description: "Data table of all reports created by the committee broken down by Line, Type, Name, Date incurred, Amount, Balance, Transaction ID, Associated with, and Actions."

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by toddlees** [comment]
Updated <img width="1630" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0F0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad24b53cdd1099fd204fd2e41bd52d743008f2a4/image.png" alt="image.png" />
to 
<img width="1658" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL010QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ef205ed3468ff0501c036e45af58e8ec1a473cf/image.png" alt="image.png" />

**Comment by toddlees** [comment]
Descriptions are showing up for all tables locally:

<img width="1483" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2t6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--046023135fee48fc28332790a9293a4d8a6ff2cc/image.png" alt="image.png" />
<img width="886" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd296QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eba78b2de0a0a0a3884bf397e7e9765ff546ce7c/image.png" alt="image.png" />
<img width="1173" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3N6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--905aedb62f74dbd690395f331935c8dd71d71c3f/image.png" alt="image.png" />

**Comment by toddlees** [comment]
passes CR moving to QA

**Comment by WiseQA** [comment]
QA review verified tables for "Receipts"; "Disbursements" and "Loans and Debts" using ANDI.

Verified "Receipts" table has the following description: "Data table of all reports created by the committee broken down by Line, Type, Name, Date, Memo, Amount, Aggregate, Transaction ID, Associated with, and Actions."

<img width="1767" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEkwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7d7aad457b46cf4d20cb4aa1c6b5fff94033417/image.png" alt="image.png" />

Verified "Disbursements" table has the following description: "Data table of all reports created by the committee broken down by Line, Type, Name, Date, Memo, Amount, Transaction ID, Associated with, and Actions."

<img width="1763" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGMwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27cad1d28411debca098c622412d47776748d492/image.png" alt="image.png" />

Verified "Loans and Debts" table has the following description: "Data table of all reports created by the committee broken down by Line, Type, Name, Date incurred, Amount, Balance, Transaction ID, Associated with, and Actions."

<img width="1764" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHMwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d434c55848c6838827d322404c55c68b87d6818b/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
