### ISSUE TITLE
Fix save buttons (e.g., Save both transactions, Save transactions, Save, etc.) functionality from reenabling quickly and allowing multiple clicks

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1563]
During QA and DEV testing it was verified that once a save buttons (e.g., Save both transactions, Save transactions, Save, etc.) was selected in transactions (to include memo's), reports, cash on hand for example the disable save buttons (e.g., Save both transactions, Save transactions, Save, etc.) 

### QA Notes ### 
 null
### DEV Notes ### 
  

Rather than using a directive with timing, have the button disable when the submit observable is created and then re-enabled when the subscribed request returns, with or without an error.

This affects all buttons where the `appSingleClick` directive was applied including `(<page name>: <button name>)`:

- Cash on hand: Save & continue
- Create f3x: Save
- Create f3x: Save and continue
- Report Level Memo: Save & continue
- Web print: Compile PDF
- Web print: Compile New PDF
- Submit f3x step 1: Confirm information
- Submit f3x step 2: Submit
- Transaction pages: Save (and all variants)

@MitchellTCG @mjtravers fix timing issue from disable to enable of save buttons (e.g., Save both transactions, Save transactions, Save, etc.).   Bug fix 2 pts.   Assigned to Sprint 35.
### Design ### 
 null

**Comment by mjtravers** [comment]
@dheitzer Would you add to the ticket the list of buttons you determined were in need of this fix?

**Comment by dheitzer** [comment]
@mjtravers added buttons affected to dev notes

**Comment by mjtravers** [comment]
Have a thought about this ticket. Sending back to In Progress. @sasha-dresden Give me a ping when you have a moment to go over this ticket.

**Comment by sasha-dresden** [comment]
I followed your advice and reworked this to use that spinner store. It really simplified the logic in many ways, though there was an issue with the button not re-enabling if the api call was never made, but I believe I've handled that situation by falling back to the 3 second delay in that situation.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review when testing "Save transactions" button the button was not working.
1.  Created Loan Received from Bank transaction
2.  Click "Save transactions" button - button stayed activated - transaction didn't save.

<img width="1052" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTV0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f24fbd59d492cffe6f8ae0ebb6fe407060ee335b/image.png" alt="image.png" />

<img width="794" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWx0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3458f80b5cebaec08a2becce2724f5a0efabe575/image.png" alt="image.png" />
____________________________________________________________________________________________________________________________

QA review created an "Individual Receipt" transaction when selecting "Save" button the button became disabled to the count of 1001, 1002, 1003.   Then the "Save" button displayed as not selected (blue button) before transaction was saved.

<img width="385" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlJ0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3678abcde01d71c01a8b147305bdedfd1ca938db/image.png" alt="image.png" />

<img width="539" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkp0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2bfd732422a21671fb1b112ad7f0ab7da82b906d/image.png" alt="image.png" />

@mjtravers as discussed returning to In-progress to verify the functionality of the above.

**Comment by mjtravers** [comment]
The issues have been addressed and passed CR. The hotfix has been deployed to STAGE and is ready for QA.

**Comment by WiseQA** [comment]
QA review retested "Save transactions" button fix was implemented.  Created Loan Received from Bank transaction
Click "Save transactions" button - transaction saved.  Hotfix passes with current design.

<img width="1288" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGlKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c4f87791649536568c5fa2dc1e9ef348740f23d/image.png" alt="image.png" />

<img width="1278" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG1KQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d2287e7c4e60635de38b2dfd55d1ae01d5893bd/image.png" alt="image.png" />

Retested the "Save" button lagging once creating a "Individual Receipt" transaction.  Once select the "Save" button

 <img width="187" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHFKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0fb8c35e18fd154e577d68891ab670ffada9973/image.png" alt="image.png" />

The "Save" button outlined text box stays displayed to count of 1001, 1002, 1003.   (Note:  this is a performance issue and will be addressed in ticket #633.

<img width="187" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHlKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b763395f227e7343385f09e4db3c14f497e7c8e8/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
