### ISSUE TITLE
Fix misspelling of "Expenditure" on "Select form type" dropdown list

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1568]
During QA testing verbiage for Form 24: 24/48 Hour Notice of Independent Expenditure in the "Select form type" dropdown has a misspelled word.

Change "Expentiture" to "Expenditure"

@MitchellTCG @mjtravers fix misspelling of Expenditure. Bug pointed as 1 pt assigned to Sprint 35.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-535](https://fecgov.atlassian.net/browse/FECFILE-535)

**Comment by toddlees** [comment]
passes cr moving to qa

**Comment by WiseQA** [comment]
QA verified the verbiage for Form 24: 24/48 Hour Notice of Independent Expenditure in the "Select form type" dropdown was changed from "Expentiture" to "Expenditure"

<img width="718" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzVNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b3f248d9613846d771e24cce5ff18d138d84051/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
