### ISSUE TITLE
System will determine if Committee is qualified on Form 3X

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1569]
Acceptance Criteria

***Given*** a Committee Administrator

  ***When*** a F3X header row is generated (submission, print preview, or manually generated)

  ***If*** my Committee Type (FILED CMTE TYPE from Committee Detail endpoint![](/images/icons/emoticons/help_16.png)) is Q, W, or Y, 

  ***Then*** COL SEQ 16 in the Form 3X header row will show the Qualified value to be TRUE

***ELSE***

***Then*** COL SEQ 16 in the Form 3X header row will show the Qualified value to be FALSE

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
- Reference [HERE](https://docs.google.com/spreadsheets/d/10fwbBXjS9C3N0Q2QqjWbyPpWF_ow4F59WdZbh0_osu4/edit#gid=1295372537)
- Committee data will be captured at log in, and it is not expected that it is "refreshed" upon submission. FEC has determined that the data gathered at log in is acceptable and it is highly unlikely it would change between log in and submission. (This will still amount to calculating and assigning `qualified_committee` for the f3x upon submission, BUT using the committee data in local storage, which was retrieved from FEC at login)

### Design ###
The system should capture the Committee Type and Designation for the committee so that when the .fec file is generated, the data in COL SEQ 16 in the Form 3X header row will have the correct data to determine if the committee is qualified or not.

 See full ticket and images here: [FECFILE-534](https://fecgov.atlassian.net/browse/FECFILE-534)

**Comment by AureliaKhorsand** [comment]
Great catch @Elaine-Krauss-TCG . AC is updated to indicate it should be any time a header row is created. Thanks!

**Comment by dheitzer** [comment]
Per updated AC, this feature will now show:

1. On report submit
2. On print preview
3. On manual dev .fec generation in reports page

**Comment by dheitzer** [comment]
Local testing confirmed 2 & 3:
2.
<img width="671" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmhqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd822a4cb9f53d827565c0f073ed42ee0d6cbf64/image.png" alt="image.png" />

3.
<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmRqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82a26c9cce9c72797f0b160a9e09d15553410828/image.png" alt="image.png" />

**Comment by dheitzer** [comment]
Updated code to meet new ACs and re-opened CR.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified by visual inspection of DEV local machine the following:

Local testing confirmed 2 & 3:
2.
<img width="671" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmhqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd822a4cb9f53d827565c0f073ed42ee0d6cbf64/image.png" alt="image.png" />

3.
<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmRqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82a26c9cce9c72797f0b160a9e09d15553410828/image.png" alt="image.png" />

QA unable to test this on system, as committee accounts and IDs are already setup for testing.

@mjtravers please verify this is a visual inspection with DEV on local.   Thanks

**Comment by mjtravers** [comment]
It can be a visual inspection of the .fec files David provided or you could create a F3X report and then download the .fec file to inspect it visually. You'll have to pick out the 16th value in the second row. Each value is separated by the "FS" field with the black background as seen in the David's screenshot.
<img width="939" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVdNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94df59063807db05996b706696c71f1385789030/download-fec.jpg" alt="download-fec.jpg" />

**Comment by MitchellTCG** [comment]
### QA verified the following:
Checked this by using web print that my committee is a multicandidate
#### Web Print
<img width="952" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemVrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b39685269d5dd5c34b41376f78c1cfa8ab14a666/Screenshot%202024-03-01%20at%209.19.31%E2%80%AFAM.png" alt="Screenshot 2024-03-01 at 9.19.31 AM.png" />

#### The PDF
<img width="620" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejZrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9ad813817e7b67a4a1203913b2c879605face1e/Screenshot%202024-03-01%20at%209.19.26%E2%80%AFAM.png" alt="Screenshot 2024-03-01 at 9.19.26 AM.png" />

### QA Review Completed. Moved to Stage Ready.
