### ISSUE TITLE
Fix table labels location for Summary Page and Detail Summary Page

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1572]
QA and UX review verified the Summary Page and Detailed Summary Page table labels placement needs fixed. Tested on DEV, STAGE and PROD labels are incorrect on each environement.

Below is the way the summary page was designed and location of verbiage "Report Summary"

_______________________________________________________________________________________________________________________________

  ***1\. Summary Page - Move table verbiage "Report Summary" to above table (reference above screenshot)***

***2\. Detailed Summary Page - Move table verbiage "Receipts" above receipts table.***

***3, Detailed Summary Page - Move table verbiage "Disbursements" above disbursements table.***

***4\. Detailed Summary Page - Move table verbiage "Net contributions/operating expenditures" above Net contributions/operating expenditures***

@MitchellTCG @mjtravers Fix table labels verbiage location as denoted in steps above. Bug pointed as 3 pts and assigned to Sprint 35.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-532](https://fecgov.atlassian.net/browse/FECFILE-532)

**Comment by toddlees** [comment]
passes cr moving to qa

**Comment by WiseQA** [comment]
QA review verified the following table labels location was fixedd.

1. Summary Page - table verbiage "Report Summary" moved above table.

<img width="1191" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEJNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db75f79f70e34f1e10f9c6fc20eb073aba33d259/image.png" alt="image.png" />

2. Detailed Summary Page - table verbiage "Receipts" moved above receipts table. 

<img width="726" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEpNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3197c864c83d3487312420eceaa15eb7165be16/image.png" alt="image.png" />

3, Detailed Summary Page - table verbiage "Disbursements" moved above disbursements table.

<img width="873" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFpNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd59e425ad214c6b8623cc4e3fc59462634ff5b5/image.png" alt="image.png" />

4. Detailed Summary Page - Move table verbiage "Net contributions/operating expenditures" above Net contributions/operating expenditures.

<img width="911" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGxNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3a6487ba695075839abfd2551483026a129c68e/image.png" alt="image.png" />

QA Review Completed.  Moved to Stage Ready.
