### ISSUE TITLE
Fix Logout functionality for DEV, STAGE and PROD using login.gov

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1581]
During QA and DEV testing when logging into DEV, STAGE and/or PROD, selecting the "Login with login.gov" the user cannot logout.

1\. Select the "Login with login.gov" button. Login in with credentials. Dashboard is displayed.

2\. User cannot logout of FECfile

3\. Logout functionality broken. Selected refresh and refresh did not refresh page.

@MitchellTCG @mjtravers fix logout broken functionality using login.gov for DEV, STAGE and PROD environments. Defect pointed 5 pts assigned to Awaiting Sprint Assignment.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-530](https://fecgov.atlassian.net/browse/FECFILE-530)

**Comment by mjtravers** [comment]
Logout fixed per issue described here:
https://stackoverflow.com/questions/18300674/window-location-href-not-working#answer-18300733

Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified logout functionality for DEV, STAGE and PROD using login.gov has been fixed.  (DEV TESTED ONLY BELOW)

<img width="1252" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2JDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61fc337683af88f584d3ce1f3ad07f470c7f3cff/image.png" alt="image.png" />

<img width="869" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd25DQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--603a44d9f120532e3f5500cabf0540fb66cc6658/image.png" alt="image.png" />

Logout successful.

<img width="1002" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3JDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1f2aa6e46873e292a8f3caf40aaf70fe3520ad1/image.png" alt="image.png" />

@mjtravers @MitchellTCG Placing ticket on-hold until fix is pushed to STAGE and PROD to test.

**Comment by WiseQA** [comment]
QA review verified logout functionality using login.gov.  (TESTED Using STAGE, DEV and PROD)

1.  Select the "Login with login.gov" button. Login in with credentials. Dashboard is displayed.

<img width="1205" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0hIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1edaaf0f5a8727810e39d1bee59f70441e6ed4e3/image.png" alt="image.png" />

<img width="1089" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0xIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f78b2752e602683c56e67f55eca7ad94cf725bbf/image.png" alt="image.png" />

3.  Returned to Login page

<img width="1036" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1RIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f481fd66e124e6e292d46de6118f7da7e5673a3/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
