### ISSUE TITLE
Fix line 6(a) line description to include "year" of Cash on hand

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1582]
QA and DEV review verified Line 6(a) in the Summary Report is missing the Cash on hand date being pulled forward in the line description.  Found during testing in Sprint 35.

1.  Created 3 monthly reports within the same year.

<img width="1177" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFpTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1ff17cc33ce0f21b0157a81d57adf10e2ac1f43/image.png" alt="image.png" />

2. Created the first monthly report (e.g., FEBRUARY 20 MONTHLY REPORT (M2) 01/01/2021 — 01/31/2021)

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGhTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0d02d590092458e91944f92bd5a879ccf36fe95/image.png" alt="image.png" />

3.   Select Summary Report line 6(a) line description is displaying correctly.

<img width="1108" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODFTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c796643a05392e095b7d15422ddafed434ebd56a/image.png" alt="image.png" />

4.  Select the second monthly report (e.g., MARCH 20 MONTHLY REPORT (M3) 02/01/2021 — 02/28/2021) the line 6(a) line description "year" is not being pulled forward.   

<img width="1131" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUpTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2bba51a5acb003836f16e776c88d135b61e55028/image.png" alt="image.png" />

@MitchellTCG @mjtravers fix the line 6(a) line description to pull the "year" forward.   Bug pointed as 1 pt. and assigned to Sprint 35.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
<img width="1577" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU5VQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8464441f4b86ccf5666aad176f4a67268e56a1b9/image.png" alt="image.png" />

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
The migration failed on DEV. Here is the error message from the logs. Sending ticket back to In Progress.

10:44:36.113: [APP/PROC/WEB.0] File "/home/vcap/app/django-backend/fecfiler/reports/migrations/0007_update_l6a_coh_year.py", line 10, in update_coh_year
10:44:36.113: [APP/PROC/WEB.0] year = report.coverage_from_date.year
10:44:36.113: [APP/PROC/WEB.0] AttributeError: 'NoneType' object has no attribute 'year'
10:44:36.380: [APP/PROC/WEB.0] Exit status 1

This ticket was merged. The branch is there but a new PR will need to be created.

**Comment by mjtravers** [comment]
Patch made to the migration to account for older reports without dates. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the fix for line 6(a) line description the "year" is pulling forward in the Summary Page.

1.  First monthly report (e.g., FEBRUARY 20 MONTHLY REPORT (M2) 01/01/2021 — 01/31/2021).   Summary page line 6(a) is displaying correctly.

<img width="1393" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekJzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8fcad5053f6cf070e6f36536093463709f59eab2/image.png" alt="image.png" />

2.  Select the second monthly report (e.g., MARCH 20 MONTHLY REPORT (M3) 02/01/2021 — 02/28/2021) the line 6(a) line description "year" is being pulled forward and displaying correctly.

<img width="1418" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelJzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc16b329f52087ee835ec45711dacd0ffc87de0a/image.png" alt="image.png" />

3.  Verified with third monthly report (e.g., APRIL 20 MONTHLY REPORT (M4) 03/01/2021 — 03/31/2021) the line 6(a) line description "year" is being pulled forward and displaying correctly.

<img width="1403" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelpzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--973b327a792d677d3e141034978ef9d8a3a085ee/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
