### ISSUE TITLE
User to confirm Form 3X that will include Independent Expenditure (Schedule E) transactions created from a Form 24

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1583]
Business Reason

As a user, I will be able to designate and select which Form 3X Report to link each Independent Expenditure transaction that is created on a Form 24 Report so that I can report on all my transactions

Acceptance Criteria

***Given*** a Form 24 report (in-progress)

 ***When*** the user CREATES one of the following transactions:

*   Independent Expenditure
*   Void of Independent Expenditure
*   Multistate Independent Expenditure
*   Credit Card Payment for Independent Expenditure
*   Staff Reimbursement for Independent Expenditure
*   Payment to Payroll for Independent Expenditure

***Then*** the user will see a message at the top of the transaction indicating that there must be an in-progress Form 3X with coverage dates that include the IE they will enter (see text below)

 ***And*** if they need to, they can click "Create Form 3X" to initiate a new Form 3X report (coverage date selection screen), or "Return to manage reports" to return to the Manage reports page.

***Given*** the user enters the dissemination and/or disbursement dates

 ***then*** the system will use the following logic to determine the linked in-progress Form 3X report:

*   if only one date is present, that date must be within the selected Form 3X coverage period. If both dates are present, the Date of Disbursement must be within the report coverage period.

***And*** there will be a tooltip with additional information (see text below) and an in-line validation error if there is no applicable Form 3X report.

Wireframe

 

1.  Example

      

1.  Errors

      

Video

 [Private Zenhub Video]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1NTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed5c413aea08a983be51db9cad6187a41939b516/Form%2024%20-%20video.mp4](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1NTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed5c413aea08a983be51db9cad6187a41939b516/Form%2024%20-%20video.mp4))

### QA Notes ###
- [x] BA/Design Quality Checklist complete
- The linked report should be listed as "MARCH 20 (M3):  02/01/24 - 02/29/24", or "Report Code (without MONTLHY/QUARTERLY REPORT) followed by coverage dates.
- Note form @MitchellTCG : This ticket on is only validating the Report displayed in the "linked report" box falls within the date range of the two date boxes based on the logic at the top of this ticket. The real linking of tickets will be tested in ticket :[web-api 756](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/756)

### DEV Notes ###
- The linked report should be listed as "MARCH 20 (M3):  02/01/24 - 02/29/24", or "Report Code (without MONTLHY/QUARTERLY REPORT) followed by coverage dates.

**Text for top of page:**
"Independent expenditures (IE) submitted on a Form 24 must also be submitted on the regularly scheduled Form 3X report. In order to create an IE on the Form 24, the IE's date of disbursement must fall within the corresponding Form 3X coverage dates. If date of disbursement is not available, date of dissemination will be used. IEs already created on a Form 3X can be added to an existing Form 24."

**ToolTip text:**
"Transactions created in Form 24 must be linked to a Form 3X with corresponding coverage dates. To determine coverage dates, calculations rely on an IE’s date of disbursement. If date of disbursement is not available, date of dissemination will be used. Before saving this transaction, create a Form 3X with corresponding coverage dates."

### Design ###
null

 See full ticket and images here: [FECFILE-528](https://fecgov.atlassian.net/browse/FECFILE-528)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg @JonellaCulmer this is ready for design considerations. I'm absolutely open to workshopping the last AC - it doesn't look like a user-friendly experience right now. Essentially, we need to prevent them from saving a Form 24 without also saving it to a Form 3X. Also, not sure where you want to put the message that any updates here will also update it on the Form 3X (perhaps in the confirmation message?)

**Comment by toddlees** [comment]
@AureliaKhorsand @MitchellTCG Would it be simpler if we asked them what f3x they want to make the ie for before they start the transaction?  That way we avoid the scenario where they make the transaction and realize the report they want to put it in doesn't exist.  And it will mean we know what coverage dates the transaction needs to be within while they're filling out the form rather than checking after.

**Comment by toddlees** [comment]
Additionally, is it worth having AC that the transaction will appear in the F3X?

**Comment by AureliaKhorsand** [comment]
@toddlees @MitchellTCG Agreed on asking them to confirm the Form 3X before they start the transaction, but that will be up to design. I did add an AC for indicating the transaction will appear on the relevant Form 3X.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Please review

And here is the text at the top of page to review:
"Form 3X and Form 24 transactions can be linked. Before you create an independent expenditure (IE) for the second time, IEs already created on Form 3X can be added to this Form 24. Also, if you want to create an IE in this Form 24 for the first time, make sure you’ve created a Form 3X with corresponding coverage dates first. To determine coverage dates, calculations rely on an IE’s date of disbursement. If date of disbursement is not available, date of dissemination will be used."

Here is the text in the tooltip:
"Transactions created in Form 24 must be linked to a Form 3X with corresponding coverage dates. To determine coverage dates, calculations rely on an IE’s date of disbursement. If date of disbursement is not available, date of dissemination will be used. Before saving this transaction, create a Form 3X with corresponding coverage dates."

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @JonellaCulmer how is this updated language?

Top of page text:
"Independent expenditures (IE) submitted on a Form 24 must also be submitted on the regularly scheduled Form 3X report. In order to create an IE on the Form 24, the IE's date of disbursement must fall within the corresponding Form 3X coverage dates. If date of disbursement is not available, date of dissemination will be used. IEs already created on a Form 3X can be added to an existing Form 24."

ToolTip text (did not change):
"Transactions created in Form 24 must be linked to a Form 3X with corresponding coverage dates. To determine coverage dates, calculations rely on an IE’s date of disbursement. If date of disbursement is not available, date of dissemination will be used. Before saving this transaction, create a Form 3X with corresponding coverage dates."

**Comment by AureliaKhorsand** [comment]
BA to split this ticket into two on delineator, each ticket is 5 points. (#756 blocks both)

**Comment by toddlees** [comment]
passes CR moving to QA

**Comment by MitchellTCG** [comment]
### Please update
- [ ] The read-only text in the "Linked report" textbox should look like this:
<img width="597" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDNJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f16c8687d10c33c4177536401a03dd3ba16dced3/Screenshot%202024-03-08%20at%205.00.58%E2%80%AFPM.png" alt="Screenshot 2024-03-08 at 5.00.58 PM.png" />

- [ ] the report should be displayed like: 
JULY 31 (MY): 01/01/2017 - 06/30/2017
**NOT**
JULY 31 MID-YEAR REPORT (MY): 01/01/2017 - 06/30/2017

**Comment by toddlees** [comment]
https://github.com/fecgov/fecfile-web-app/pull/1767
addresses readonly style and bug introduced in first implementation

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "Dissemination Date" and/or "Disbursement Date" are required fields for "Linked Report" 

<img width="1318" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzdlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7aaa29b9be2b9d4c4795262e8237e055274fb48d/image.png" alt="image.png" />

_____________________________________________________________________________________________________________________

Verified when a "Dissemination Date" and/or "Disbursement Date" are entered the following error message is displayed as required field for "Linked Report" 

<img width="1373" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1BlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--447feed11a4c41afa86b5b7fabda84f67b240f61/image.png" alt="image.png" />
____________________________________________________________________________________________________________________

Verified Help Tooltip verbiage is correct.

<img width="826" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd25mQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0018a058823ae7ded7952ffbd32bb1c82afab71a/image.png" alt="image.png" />

______________________________________________________________________________________________________________

Verified linked report date is displayed correctly per @MitchellTCG comment above.   (the report should be displayed like:  JULY 31 (MY): 01/01/2017 - 06/30/2017)

<img width="1368" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL25lQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43c8abae53dd7b3e6dc1e5ab5be70817846e1587/image.png" alt="image.png" />

_____________________________________________________________________________________________

(NOTE:  Actual linkage for reports will be tested in api.756 as denoted in QA notes)

QA Review Completed.   Moved to Stage Ready.
