### ISSUE TITLE
Fix Cash on hand entry screen displaying on first row report in the Manage reports table

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1587]
QA and DEV review verified Cash on hand entry screen displays on the report in the first row of Manage reports table instead of remaining with First report created for the reporting period.   Found during testing in Sprint 35.

1.   Reports create and in Manage reports table (M2, M3 and M4) - 

<img width="1095" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXBZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3fdb0713e7b0362030cc7004c6cfae22131c435/image.png" alt="image.png" />

__________________________________________________________________________________________________________________________________
2.   Select M2 which is the first report created, and is listed first in the table.   Cash on hand entry screen displayed correctly.

<img width="1172" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0JZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1839b7aaf57faa1f7343f7ceabec0e3f49a9972/image.png" alt="image.png" />

_________________________________________________________________________________________________________________________________
3.  Sort Manage reports table making the order of reports change to M4 being displayed first.

<img width="1156" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2hZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33b2a224a34bf12e6029ce2f4c9cc9a4f505d252/image.png" alt="image.png" />

__________________________________________________________________________________________________________________________________
4.  Select M4 report the Cash on hand entry screen is displaying.   This is the bug fix, as the Cash on hand entry screen is displaying on first report in Manage reports table.   Cash on hand entry screen should stay with the first report entered for that reporting period.

<img width="1195" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0JZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--033aef1a420220903b19c5fea110604096952234/image.png" alt="image.png" />

_________________________________________________________________________________________________________________________________
@MitchellTCG @mjtravers Fix Cash on hand entry screen displaying on first row report in the Manage reports table. Bug pointed as 3 pt. and assigned to Sprint 35.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the fix for Cash on hand entry screen displaying on first row report in the Manage reports table.

1.  Select M2 which is the first report created, and is listed first in the table. Cash on hand entry screen displayed correctly.

<img width="1234" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFZzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a74fb19a5b4a61c5b537082e080a251fcefee47/image.png" alt="image.png" />

<img width="1381" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFpzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a9807ad01246dd127c6e1268553ac3574f6e1f0/image.png" alt="image.png" />

2.  Sorted Manage reports table making the order of reports change to M4 being displayed first.

<img width="1109" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGRzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d69f55f786cfde072ca1f9c3ebf9a336c2d2c31/image.png" alt="image.png" />

3.  Select M4 report verified the Cash on hand entry screen is **not** displaying.  Cash on hand entry screen is displaying correctly for first report entered for that reporting period.

<img width="1423" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDVzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee287a186845e538e2d106116b0ff89458def058/image.png" alt="image.png" />

QA Review Completed.  Moved to Stage Ready,
