### ISSUE TITLE
Update UI text for Calendar Year-To-Date on all Schedule E transactions to be 'Calendar Year-To-Date Per Election for Office Sought'

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1588]
Business Reason

As a user, I will be able to see the aggregate field displayed on all Schedule E transactions with the label 'Calendar Year-To-Date Per Election for Office Sought' so that I can match what is disclosed on the Schedule E form.

 Acceptance Criteria

**Given** a user updating one of the following transactions:

- Independent Expenditure
- Void of Independent Expenditure
- Multistate Independent Expenditure
- Credit Card Payment for Independent Expenditure
- Credit Card Memo for Independent Expenditure
- Staff Reimbursement for Independent Expenditure
- Staff Reimbursement Memo for Independent Expenditure
- Payment to Payroll for Independent Expenditure
- Payroll Memo for Independent Expenditure

**When** I view the label on the aggregate field
**Then** I will see the label updated to be 'Calendar Year-To-Date Per Election for Office Sought'

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
### DEV Notes ### 
  Wireframe
<img width="337" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelIyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--840a85808479666945ef3db8b2a21ea7aea2a18e/1082%20-%20Allow%20user%20to%20enter%20Independent%20Expenditure%20on%20Schedule%20E%20%E2%80%93%203.png" alt="1082 - Allow user to enter Independent Expenditure on Schedule E – 3.png" />

### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
PLS review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified text was changed from CALENDAR YEAR-TO-DATE to CALENDAR YEAR-TO-DATE PER ELECTION FOR OFFICE SOUGHT on Schedule E transactions (tested us Independent Expenditure)

<img width="1114" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTE5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61e33d1dbb1d074fda41f9edcc817e5a4e720869/image.png" alt="image.png" />

Verified the following Independent Expenditures transactions were changed.

<img width="312" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkY5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae56240633eb215a90724c1e2b5b6d31817786ad/image.png" alt="image.png" />

QA Review Completed.  Moved to Stage Ready.
