### ISSUE TITLE
Allow user to edit contact from transaction entry

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#159]
Acceptance Criteria 
 

**Given** a user has pulled in contact info to a transaction using the Contact Management Lookup
**If** the user makes edits to the contact information in the transaction entry screen
**When** the user goes to save the transaction (whether it's Save and Add More or Save and View Transactions)
**Then** they must acknowledge the following message:

"By saving this transaction, you are also updating the contact for [CONTACT NAME]. This change will only affect transactions with receipt date on or after [Transaction Date Received, MM/DD/YYYY]"

**And** the message will show their changes as:
- Changes:
-- Updated [field] to [new entry]
-- _etc..._

**And** the user will be able to
- Continue (this will save the transaction and contact at this point)
- Cancel (this just takes them back to the transaction form to continue editing)

 Wireframes
<img width="1113" alt="Screen Shot 2022-09-21 at 11 18 50 AM" src="https://user-images.githubusercontent.com/31663028/191544802-d4ef7560-fc3c-4507-9915-05f1d068fe59.png">

### QA Notes ### 
  
The only fields being tested in this ticket is the Contact Information fields which include:
Name
Address
Employer
Occupation

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
From 7/26/22 requirements meeting, Users enter a contact in Contact Management as an ENTITY. Then, while entering a transaction into a report, users can use the Contact Management Lookup to pull in the existing ENTITY's contact information into the transaction. However, the user then makes change to the contact information that was pulled onto the transaction form. This change will apply to that transaction and any transactions that fall after that transaction date. It will not update any contact info on transactions prior to that date. (This all must be clear to the user). The ENTITY in Contact Management will also be updated.

**Comment by JonellaCulmer** [comment]
@AureliaKhorsand Is there a requirement to be able to edit ALL fields for a contact in the transaction? For example, a receipt transaction from a candidate doesn't list the office or district information from a House candidate. Only required fields for the transaction appear. Is it alright that the filer will only be able to edit certain fields, already present in the transaction? Or does the filer need to be able to edit all fields for a contact within a transaction?

cc: 
@GreggMoreland @mary-tcg @MitchellTCG

**Comment by AureliaKhorsand** [comment]
Just to close the loop and capture what we discussed on the call: as of now, the requirement is just that the contact fields available for the transaction entry screen be editable. So, unless it is already present, a user can't edit ALL contact fields on a transaction screen. If they are creating a new contact from a transaction entry screen, however, then all contact fields are available.

**Comment by JonellaCulmer** [comment]
@MitchellTCG @AureliaKhorsand @mary-tcg @GreggMoreland 
Similar to what a filer might see when [creating a new contact](https://github.com/fecgov/fecfile-web-app/issues/72#issuecomment-1226177575), a filer will be alerted with a pop-up that clarifies changes were made to the contact, in addition to creating a new transaction. 

<img width="477" alt="Screen Shot 2022-08-25 at 1 08 46 PM" src="https://user-images.githubusercontent.com/31663028/186727763-df83ec05-841f-47f4-afeb-600134ffa13d.png">

**Comment by AureliaKhorsand** [comment]
BA Note: This does NOT include the amendment workflow, discussed at the requirements session on 9/1/22. Contact updates within a transaction in a report that has subsequent reports after may need to open and amend those other reports. TBD.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand Please Test this

**Comment by mjtravers** [comment]
From CR, the contact_id needs to remain required and the contact object should be passed to the new endpoint so that contact form inputs not on the transaction form for contacts are still saved. Sending to In Progress

**Comment by mjtravers** [comment]
Passes CR, moving to QA

**Comment by WiseQA** [comment]
QA review "Offsets to Operating Expenditures" transaction when editing the contact the  pop-up the only thing I changed was address.  The popup includes Employer and Occupation listed changes.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a023da73-c036-4712-a04b-86991ad8eb32)

@mjtravers @MitchellTCG @toddlees

**Comment by WiseQA** [comment]
QA review "Other Receipts" transaction when editing the contact the pop-up the only thing I changed was city, I didn't make changes to the ORG name

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4f0d2fc2-ad11-4987-a619-2d958f9f0218)

**Comment by JonellaCulmer** [comment]
> QA review "Offsets to Operating Expenditures" transaction when editing the contact the pop-up the only thing I changed was address. The popup includes Employer and Occupation listed changes.
@mjtravers @MitchellTCG @toddlees @AureliaKhorsand 

Looks like we need to account for when an edit is a removal of information. "Undefined" is no good. Are there business requirements around that within a cycle - when a filer removes information? Or is this something we want to prevent?

**Comment by AureliaKhorsand** [comment]
@JonellaCulmer no business requirements as of yet. I can add it for discussion at next week's requirements session. I'm guessing it will be very rare, since users can't remove required fields, and most likely will be over $200.

**Comment by toddlees** [comment]
@JonellaCulmer @AureliaKhorsand  I agree that we'll want language like "Cleared/Removed employer".  I think the example above is produced when employer is never filled out.  The representation of the blank field is different between the first time it was opened and the second time it was edited so it came up as a "change".  I'm going to approach the issue with that perspective and improve both the discrepancy of representations and change detection

**Comment by WiseQA** [comment]
FYI - QA review when entering an Individual Transaction, then editing and saving seems as though popup is working correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9f10f629-30a7-4e75-b01b-23d69c1d2318)

**Comment by toddlees** [comment]
Resolved bugs. In code review. Will notify when deployed to stage

**Comment by mjtravers** [comment]
Bug patch passes CR, sending to QA

**Comment by WiseQA** [comment]
QA review when entering an Individual Transaction, then editing and saving seems as though popup is working correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9f10f629-30a7-4e75-b01b-23d69c1d2318)

When selecting "Cancel" return to Transactions page when selecting "Save & view all transactions" transaction is saved and return to Transactions page.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3f8522f4-ae2c-44ef-92ef-8eec92c1c518)

If contribution aggregate > $200.00 able to save "Individual Receipt" and "Other Receipt" without adding "Employer / Occupation" fields.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0e93a906-99b1-444d-bd7e-96e41ab79076)

If contribution aggregate < $200.00 able to save "Individual Receipt" and "Other Receipt" "Employer / Occupation" fields. (they become required fields)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e7c318a3-9c56-4c70-a874-de7593e093a8)

QA Review Completed.  Moved to Stage Ready.
