### ISSUE TITLE
Remove left NAV bar on "Create new report" page

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1590]
QA and DEV review verified left NAV should not be populating before report is created.   Remove left NAV from the create report page. Found during testing in Sprint 35.

1.  Select "Create new report" button

<img width="325" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlZmQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10523cecae8294b243309c97d9382093355720e2/image.png" alt="image.png" />

_________________________________________________________________________________________________________________________________
2.  Select Form 3x: Report of Receipts and Disbursements from the "Create a new Report" dropdown then select "Start building report"

<img width="434" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmxmQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff7c5dcf7fa6d75a8e2448478eaf29723652b009/image.png" alt="image.png" />

__________________________________________________________________________________________________________________________________
3.  The create report page is displayed.   The left NAV should not be populating before report is created.   Remove left NAV from the create report page.  This is the bug

<img width="985" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzFmQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59ac984ca2a393bc73dcfd12d7577a4b91b67bfb/image.png" alt="image.png" />

__________________________________________________________________________________________________________________________________
@mjtravers @MitchellTCG fix removing the left NAV from the create report page. Bug pointed as 2 pt. and assigned to Sprint 35.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified left NAV has been removed from lthe create report page.

1.  Select "Create new report" button

<img width="359" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODV4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de3372a544704f40d1f290cbe45e5b587184e31c/image.png" alt="image.png" />

2.  Select Form 3x: Report of Receipts and Disbursements from the "Create a new Report" dropdown then select "Start building report"

<img width="493" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODl4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aafa7d6b38427db0e56a5867a905c707149e27bf/image.png" alt="image.png" />

3.  The create report page is displayed. The left NAV has been removed from the create report page. 

<img width="933" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVJ4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eac5c9ff23a90e0205b82ec9a3e6d887f5669fe6/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
