### ISSUE TITLE
Fix box and grey background around FECFile and box around "Here's how you know"

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1595]
QA and UX review there is a box and grey background around FECFile and a box around "Here's how you know".  The bug is there should not be a box displayed on either field.  Grey background should not be displayed "FECFile"

<img width="448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXhzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7c66a983c36710cc515fb4f5f3e9fec2e60a542/image.png" alt="image.png" />

@MitchellTCG @mjtravers Fix grey background on "FECFile" and remove boxes around "FECFile" and "Here's how you know". Bug pointed as 2 pts and assigned to Sprint Backlog.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified grey background "FECFile" and boxes around "FECFile" and "Here's how you know" have been removed.   

<img width="611" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFZ4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--779ba51f7acd46e80643bc5909e4a2a28b5cf4bc/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
