### ISSUE TITLE
System to allow one role per user per committee account

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1598]
Business Reason

The system will only allow one role per user for each committee account. Note that users can have different roles in different committee accounts.

Acceptance Criteria

***Given*** a user with access to a committee account,

  ***Then*** they will be assigned ONE role within that committee account

  ***And*** that user can be seen on the Manage Users page with the following information:

*   Name
*   Email
*   Role _(only Committee Administrator right now)_
*   Status _(only Registered right now)_

Wireframe

  

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
- [x] Action kabob will not be active
- [x] Update committee viewset to work with new design below
- [x] Leave _Status_ not hooked up to anything in the front end table.  There is no design for the state of a user's enrollment in a committee yet
- [x] Separate User and Committee from the one model they are part of now, into two tables with a join table that stores the role (Ignore casing in image: the app the model was drawn in autoformatted):

### Design ###
null

[FECFILE-523](https://fecgov.atlassian.net/browse/FECFILE-523)

**Comment by toddlees** [comment]
added dev notes <img width="1626" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFZ1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73735988de84a2057e0bf2578a8302d7794547b9/image.png" alt="image.png" />

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
PLS Review

**Comment by mjtravers** [comment]
For QA: Unit tests pass
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/2998/workflows/54a80f39-4bb2-44e4-bb6a-3c72d5053ddb/jobs/9365
<img width="722" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDBSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--337f32f3a434411f6357da158557fc302123e107/image.png" alt="image.png" />

Also, here are 2 records in my DEV committee account that show up in the Committee Users page:
<img width="934" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHdZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e7b7baf74c4b91625d52792fff442994644dc58/image.png" alt="image.png" />

QA NOTES: Shelly has two accounts but they are in two separate committees so she cannot verify on DEV that multiple users are displayed in a committee. Matt has two accounts in one committee on DEV so was able to verify for Shelly that the AC of this ticket has been met. See screenshot above.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review was visual inspection as denoted above by DEV.   QA does not have two separate committees on DEV that multiple users are displayed in a committee, therefore QA cannot test this functionality.  

QA Review Completed by Visual Inspection.   Moved to Stage Ready.
