### ISSUE TITLE
Update front-end prettier formatting file and implement Circle CI to fail on linting errors.

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1599]
As a developer, I need formatting to be consistent from all developers on the team so that file diffs only highlight changed code and not changed formatting. Also, CircleCI should fail commits with linting errors.

The prettier formatting config file is here: [https://github.com/fecgov/fecfile-web-app/blob/develop/front-end/.prettierrc.js](https://github.com/fecgov/fecfile-web-app/blob/develop/front-end/.prettierrc.js)

*   [x] Investigate the diffs in the app Github pull requests and identify the Prettier automated formatting rules that will automatically correct them upon saving the file.
*   [x] Update the prettierrc.js file it implement new rules
*   [x] Update the CircleCI lint job configuration of eslint to implement the new rules and fail commit when violated.

Here is an example of mismatched formatting:

  

  

### QA Notes ###
 
 null

### DEV Notes ###
 
 null

### Design ###
 
 null

[FECFILE-522](https://fecgov.atlassian.net/browse/FECFILE-522)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

Passed unit tests:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/5569/workflows/08da37c9-41f4-4842-9884-cf949912dd5e/jobs/19292
![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/63b5e4b6-b42a-442d-8888-1acb1ca12bd8)

Passed lint tests:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/5569/workflows/08da37c9-41f4-4842-9884-cf949912dd5e/jobs/19294
![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/9e13d750-5f43-4805-974c-171e799be98e)

**Comment by WiseQA** [comment]
QA review verified with DEV Passes unit tests:

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/7b722cf1-9ede-4df3-9875-81aa68c06aa5)
______________________________________________________________________________________________________

Passes lint tests:

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/56ad9130-ccb7-4ef1-935c-438d11b67ea6)
____________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
