### ISSUE TITLE
Allow PROVISIONED user to register committee account on FECfile Online (AUTHORIZE)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1603]
Business Reason

As a user with the same login.gov email as the email from my committee's Form 1, I will be able to create my committee account on FECfile Online for the first time as a Committee Administrator as long as the committee account does not already exist.

Acceptance Criteria

***Given*** a provisioned user 

  ***When*** they log into FECfile Online

  ***Then*** they will have the ability to "Create a new committee account"

***Given*** the user has selected "Create a new committee account",

  ***when*** they click this button

  ***then*** there will be a committee lookup available with a Tooltip (see wireframe) that will lookup committees in the mock committee endpoint.

***Given*** the user has selected a committee from the lookup and clicked "Create account"

  ***Then*** the system will ensure that the user's login.gov email matches the email from the committee's Form 1 data from mock committee endpoint (COMMITTEE EMAIL) ***AND*** the committee account does not already exist on FECfile Online,

  ***Then*** they will see a success message if that is the case and be able to either:

*   go back
*   lookup another committee

Wireframes

1.  Look up

       

1.  Typeahead

       

1.  Tooltip

       

1.  Select

       

Assets

  

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
- Email must match either COMMITTEE EMAIL in COL SEQ 12 of Form 1
- Implement emails and committees in our mock committee setup.
- Add a search into the mock JSON file for the lookup

Headline: "What am I searching?"
Body Text: 
"The committee name and ID lookup searches FEC’s global lookup of all committees registered with the Federal Election Commission. 

This lookup is not searching FECFile’s database of committees with a FECFile account. 

If the system cannot find the committee ID entered, please double-check that the ID was entered correctly.  Also, if the committee was just created and the Form 1 was recently submitted, please wait 24 hours for the database to update. For all other questions, don’t hesitate to get in touch with FECFile technical support for assistance."

### Design ###
null

[FECFILE-521](https://fecgov.atlassian.net/browse/FECFILE-521)

**Comment by AureliaKhorsand** [comment]
Probably a duplicate of #1655.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG Can you add the lookup language to make it really clear that the lookup results don't necessarily mean that an account exists on FECfile Online yet, as discussed?

@GreggMoreland can you do the BA/UX review?

**Comment by toddlees** [comment]
@MitchellTCG @mary-tcg can I get an asset for the person on the computer?

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**QA Note**: We need to upload a file into the S3 service in cloud.gov before this ticket can be tested. Please hold off testing until the file has been uploaded.

**Comment by MitchellTCG** [comment]
### QA verified the following:
1. After testing Ticket #91 and Matt deleted by user profile from Committee Test-Committee-8, I was no longer associated with a committee.
2. I logged out of FECFile and did the following steps:
- Go to Get started now page and click "Create a new committee" tile
- Use lookup to find committee
- Click "Create account"
- See the Success message and then click "Go back"
- Select new committee 
- See dashboard of new committee

<img width="233" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTJsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89d8a573774ebf9ad001bc422157a18b56a2646c/1603%20-%20Allow%20PROVISIONED%20user%20to%20register%20committee%20account%20on%20FECfile%20Online%20-%20AUTHORIZE%20%E2%80%93%201.png" alt="1603 - Allow PROVISIONED user to register committee account on FECfile Online - AUTHORIZE – 1.png" />


### QA Review Completed. Moved to Stage Ready.
