### ISSUE TITLE
Upgrade PrimeNG to latest v17.6.1

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1612]
Our current version of PrimeNG, v16.1, has a menu bug that is adversely affecting the left nav and is a blocker for ticket #1339, submitting a report for an F99.

Bug issue:
[https://github.com/primefaces/primeng/issues/13469](https://github.com/primefaces/primeng/issues/13469)

Since this is a major version number upgrade, there may be breaking changes. This upgrade ticket will fix the bug and is being set as a blocker for #1339

### QA Notes ###
 
 null

### DEV Notes ###
 
 null

### Design ###
 
 null

[FECFILE-520](https://fecgov.atlassian.net/browse/FECFILE-520)

**Comment by mjtravers** [comment]
Moving back to ADQTR. PrimeNG v17.X requires Angular v17. This ticket will be dependent on the Angular upgrade.

**Comment by mjtravers** [comment]
A workaround for the left nav bug is in v16.1 can handle the necessity of delaying this ticket for the angular 17 upgrade. On hold.

**Comment by mjtravers** [comment]
A workaround for the left nav bug is in v16.1 can handle the necessity of delaying this ticket for the angular 17 upgrade. On hold.

**Comment by WiseQA** [comment]
@sasha-dresden please attach passing Unit test for this ticket = thanks

**Comment by sasha-dresden** [comment]
Passing unit tests
![Image](https://github.com/fecgov/fecfile-web-app/assets/149604256/10c92439-742e-4777-a60c-391b496ffc3c)

**Comment by WiseQA** [comment]
Per DEV QA verified Unit Tests passing for this ticket.
____________________________________________________________________________________________________

QA added screenshot of  Upgraded PrimeNG 17.6.1.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/ead54b40-4b2c-483e-b2b4-23d5c1b7e845)

_____________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
