### ISSUE TITLE
Failing e2e tests on CircleCI

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1618]
The latest updates to the modal for selecting a report type does not disappear cleanly when the report is selected. The new code introduced in #1525

[https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/1525](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/1525)

As a result, the e2e tests are failing to complete where back-to-back tests create a new report.

***To reproduce:***

1\. Pull from github branch e2e-fixes-34 (PR: [https://github.com/fecgov/fecfile-web-app/pull/1617](https://github.com/fecgov/fecfile-web-app/pull/1617))

  2\. Run the test suite reports-f3x-debts

  3\. The second test will fail when the modal background does not clear after a report is selected to be created

Here's a screen shot:

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-519](https://fecgov.atlassian.net/browse/FECFILE-519)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
Unit test screenshot:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/4609/workflows/0351f274-c912-42bf-a487-d90c52400190/jobs/16443
<img width="746" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXlnQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--573095ccca000f1c06b4407466c69b0af792746d/image.png" alt="image.png" />

**Comment by mjtravers** [comment]
The e2e code is running locally but there is a docker container issue occurring when run in CircleCI:
<img width="729" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelduQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3aea8514c095451b5ec5dc78c80b094328d60d8e/image.png" alt="image.png" />


Sending ticket back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
This ticket should pass if the e2e tests run successfully on the evening of Jan 8.

**Comment by WiseQA** [comment]
@mjtravers e2e test failed evening of Jan 8.

<img width="1278" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekd0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--066cd116aa5b97fcd82933d7d00f9d97776b9998/image.png" alt="image.png" />

Placing ticket on-hold until DEV review of failure.

**Comment by WiseQA** [comment]
@mjtravers e2e test failed evening of Jan 9.

<img width="1096" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEswQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50c1f85988540c55ba8ca7a3bfcd09bbea1dcf2f/image.png" alt="image.png" />

@mjtravers @MitchellTCG moving back to in-progress as nightly runs are failing (see 2 days comments above)

**Comment by mjtravers** [comment]
Passes CR and passed evening test on CircleCI. Moving to QA.

**Comment by WiseQA** [comment]
QA review verified e2e test passed CircleCI and notification received for test passing.  Nigh run passed 11 Jan

<img width="1442" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3JDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd9f3bc8aace2a80289f844073ce13bb4e55efcd/image.png" alt="image.png" />


<img width="1374" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK25DQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0425d04a1a8e7c0a97699138a1eec24ad43357b2/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
