### ISSUE TITLE
test efo filing committee accounts submission of Form 3X

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1625]
During DEV and QA testing the submit button does not appear in the second report created unless the first report has a transaction added.

***DEV NOTES***

  The hide/show of the submit button to submit an F3X depends on whether or not the L6a_year_for_above_ytd field of the report has a value. When the second report is created, the step2 submit component is not getting a value in that field for the report initially even though the correct COH have value is displaying in the summary page. We were able to get the button to show after adding a transaction to the report. Maybe the locally stored report is getting updated later that expected?

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-518](https://fecgov.atlassian.net/browse/FECFILE-518)

**Comment by WiseQA** [comment]
@dheitzer @mjtravers - Matt this ticket might be OBE with all the Form 3x submissions we have successfully submitted lately, as I wrote this bug back in December.

**Comment by dheitzer** [comment]
This can be reproduced as follows:
1) create a report with COH
2) create a subsequent report
3) attempt to file subsequent report
4) you will see a 'no COH' warning

this will always happen if you don't generate a summary before attempting to submit a subsequent report.  A potential solution would be to generate the summary numbers when loading the submit page or shortly after report creation.

**Comment by mjtravers** [comment]
@WiseQA The COH logic is getting reworked, but until then the summary calculation issue pointed out by David above is being addressed in a separate ticket: https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/736

Suggest this ticket passes with an understanding of the workaround.

No code to review. Sending to QA.

**Comment by WiseQA** [comment]
Per DEV comments, there is no Code change to review by QA.   (See comment above).  COH logic is getting reworked, but until then the summary calculation issue pointed out by David above is being addressed in a separate ticket: 

Moved to Stage Ready.
