### ISSUE TITLE
Fix navigation dropdown buttons in e2e tests

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1636]
The dropdown button in the transactions e2e test is getting clicked but is no longer firing off the event handler.

Specific problem issues are:

  1\. The contact entity type select

  2\. Select memo button on JF Transfers and similar tier 1 transactions

Here is the error:

  

Both errors are in the file reports-f3x-transactions.cy.ts

Test: Create a Partnership Receipt transaction and memos with correct aggregate values

  Bad line: PageUtils.dropdownSetValue('[data-test="navigation-control-dropdown"]', 'Partnership Attribution');

Test: Create a Joint Fundraising Transfer transaction with Tier 3 child transactions

  Bad Line: PageUtils.dropdownSetValue('[data-test="navigation-control-dropdown"]', 'Partnership Receipt');

Acceptance Criteria

e2e tests run successfully with 2 tests listed above activated.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-516](https://fecgov.atlassian.net/browse/FECFILE-516)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
Here is a screenshot of all the e2e tests passing locally. We can see if they run on CircleCI this evening.
<img width="536" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTdTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86ba84982696f760859a7d656782343436965df7/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG QA review on hold until verify this runs on CircleCI this evening (3/12/2024) for results,  Passes on DEV local as denoted above.

**Comment by mjtravers** [comment]
Nightly e2e tests passed:
<img width="536" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUhZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5dd988749c5c849d03b226f9e3c1f49f6a441b7/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
QA review verified e2e nightly-run successfully passed.

QA Review Completed.  Moved to Stage Ready.
