### ISSUE TITLE
Fix amendments e2e test to mock test EFO submission.

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1637]
The amendments e2e test needs updating so that it:

1\. Does not reach out to the test EFO service to submit a report. The submit should use our current test EFO mock setup in the api.

  2\. Does not store any type of password, including fake passwords in the repo. Instead use the Cypress environment variables.

File for e2e test: reports-f3x-amendments.cy.ts

  Test name: 'should test Create an amendment'

Acceptance Criteria

The e2e test 'should test Create an amendment' should run successfully. Screenshot of test report to be provided.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-515](https://fecgov.atlassian.net/browse/FECFILE-515)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers will this be tested and passed if nightly run is successful ?

**Comment by mjtravers** [comment]
e2e tests passed nightly run on 4/24


![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/a1c5bf3d-e2ed-4ba2-b19e-1cd8f01fa4c5)

**Comment by WiseQA** [comment]
QA received email of nightly run successfully passing 04/24/2024 and DEV noted above.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/3860d2e1-edf7-478a-8ae0-aff34f8876e1)

_______________________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
