### ISSUE TITLE
Allow user to have ONE Schedule E transaction on both a Form 24 and Form 3X

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1645]
Business Reason

As a user, I will be able to update the same Schedule E transaction that is both on a Form 24 and Form 3X and have those updates reflected through both reports so that I can keep my data in sync.

 Acceptance Criteria

**Given** a Schedule E transaction on an in-progress Form 24,
**When** a user edits that transaction from _either_ the Form 3X or Form 24,
**Then** that transaction will reflect those updates on both forms when the user clicks Save.

---

**Given** a Schedule E transaction on an in-progress Form 3X that also is on a Form 24,
**When** a user edits that transaction from _either_ the Form 3X or Form 24,
**Then** that transaction will reflect those updates on both forms when the user clicks Save.

### QA Notes ### 
 - [ ] BA/Design Quality Checklist complete
- Note that if the Form 24 is in "Submission success" status and the SE transaction is edited on the Form 3X, it will still reflect the updates on the submitted Form 24. This is expected behavior, as we do not "freeze" data on submitted reports.
### DEV Notes ### 
 - A Schedule E transaction can exist on its own on the Form 3x, but anytime that transaction is create from a Form 24 or later linked to a Form 24, then the same transaction can be edited in either Form.
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
Functionality of "one transaction" will be completed in #1550 and #1583. Closing as OBE.
