### ISSUE TITLE
Allow user to view reports

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#165]
Business Reason

As a Committee Administrator, I will be able to view a list of reports associated with my committee account so that I can manage reports as needed.

Technical Notes

*   The status and date/time fields will be placeholders until the data is added to the system
*   Create a Django fixture that creates a set of test reports for testing
*   All columns in the wireframe should be sortable. Sort coverage dates by ending coverage date.

Acceptance Criteria

***Given*** I am a Committee Administrator

  ***When*** I go to the reports management page for my committee account

  ***Then*** I will see a list of reports associated with my committee account and the following information for each:

*   ***Form type*** (e.g., Form 3X)
*   ***Type of report*** (e.g., April Monthly (M4))
*   ***Coverage dates***
*   ***Status*** - _Note: this is a placeholder for now_
*   ***Version*** all will be Original for now unless specifically created for testing purposes_
*   ***Date filed***

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1267](https://fecgov.atlassian.net/browse/FECFILE-1267)

**Comment by MitchellTCG** [comment]
New wire in [fecfile-project-management#44](https://github.com/fecgov/fecfile-project-management/issues/44)

**Comment by AureliaKhorsand** [comment]
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/beba2dab-e476-4d6b-925b-0ff1d582f730)

**Comment by MitchellTCG** [comment]
Wireframe to code

![Manage Reports – Form type – 1.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d9f6e2d9-bb11-4af8-bc06-8b576b5e4eb3)

**Comment by MitchellTCG** [comment]
@WiseQA 
I asked Matt to code to the wireframe. I will update the ticket. This is my bad. Sorry

**Comment by WiseQA** [comment]
Verified list of "Manage reports" page contains the following and each column is sortable:
Form type (e.g., Form 3X)
Type of report (e.g., April Monthly (M4))
Coverage dates
Status - Note: this is a placeholder for now
Version all will be Original for now unless specifically created for testing purposes_
Date filed
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/57f44bf0-5818-4fd0-8cd9-3ec4f50de5fe)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/6974038b-1727-4e84-8295-405a126cfc8c/download](https://app.zenhub.com/files/306118986/6974038b-1727-4e84-8295-405a126cfc8c/download)

QA review completed.  Moved to Stage Ready.
