### ISSUE TITLE
Remove "aggregate" and "itemize" actions from transactions on Form 24

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1651]
Business Reason

As a user, I will not be able to force aggregate/unaggregate or itemize/unitemize a SE transaction on Form 24 since that does not apply to that form.

Acceptance Criteria

***Given*** a SE transaction on a Form 24,

  ***When*** the user selects the action kabob next to the transaction on the transactions table,

  ***Then*** they will _not_ see the following actions:

*   Aggregate _or_ Unaggregate
*   Itemize _or_ Unitemize

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-512](https://fecgov.atlassian.net/browse/FECFILE-512)

**Comment by toddlees** [comment]
Passes CR moving to QA

**Comment by WiseQA** [comment]
QA review verified under "Actions", "Unaggregated > aggregated" and "Unitemized > itemized" have been removed for a Form 24.

Screenshot showing before fix:

<img width="1290" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVBKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d1c8842828eab1584047bd165ca052414ccaf40/image.png" alt="image.png" />

Screenshot showing "Unaggregated > aggregated" and "Unitemized > itemized"  have been removed:

<img width="1252" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVRKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b9049f99b326385e2ec2adf34af007087ec1abc/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
