### ISSUE TITLE
System to inform UNAUTHORIZED users they do not have access to committee account(s)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1652]
Business Reason

As a provisioned but _unauthorized_ user on FECfile Online, I will be able to see that I do not have access to any committee accounts so I know to contact my administrator for access.

Acceptance Criteria

***Given*** a user is NOT authorized on any committee accounts on FECfile Online,

  ***When*** they log in to FECfile Online and, if relevant, have entered their user profile information and security consent,

  ***Then*** they will not see any committee accounts to select.

Wireframes

  

Assets

1.  Magnifying Glass
    [https://drive.google.com/file/d/1QdGJStGxDPr_mbkfMyuBz30UmxN0Mw4X/view?usp=drive_link](https://drive.google.com/file/d/1QdGJStGxDPr_mbkfMyuBz30UmxN0Mw4X/view?usp=drive_link)

1.  Plus in SVG
    [https://drive.google.com/file/d/1VzOgCrvy2Ho2fSyE7tWkZouS_znP9qB1/view?usp=drive_link](https://drive.google.com/file/d/1VzOgCrvy2Ho2fSyE7tWkZouS_znP9qB1/view?usp=drive_link)

### QA Notes ###
- [x] BA/Design Quality Checklist complete
- "Create new committee account" button is a dead link here (not in scope for this ticket)

### DEV Notes ###
- Most of the work was done in #1654. The only new image will be the magnifying glass and text where active committee accounts would go.
- Can create an account that never gets access to a committee to test.

### Design ###
null

[FECFILE-511](https://fecgov.atlassian.net/browse/FECFILE-511)

**Comment by dheitzer** [comment]
@MitchellTCG  @mary-tcg do you have the .svg for the magnifying glass + text?

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers can you provide screenshots from your local machine to test this ticket, as this will be a visual inspection from QA using the DEV local machine.

**Comment by mjtravers** [comment]
For QA: Here is a screenshot from a local setup showing the committee select page when a user is not associated with any committees:
<img width="1168" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE9NQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08e5d351eea996856e0b289d5f771ce3d8e9e074/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
QA review verified Visual Inspection screenshots from DEV.  (See screenshot above)

QA Review Completed.   Moved to Stage Ready.
