### ISSUE TITLE
Allow committee administrator to grant access to additional users on the committee account

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1653]
Business Reason

As a Committee Administrator, I will be able to add new users to my committee so that I can grant access to the appropriate users.

Acceptance Criteria

***Given*** a user with access to a committee account

  ***Then*** select 'Users' to go to Manage Users

  ***When*** I select '+Add New User'

  ***Then*** I will be able to enter the following to add a new user:

*   Email _(must be a valid email format AND email cannot already exist in user table for that committee)_
*   Role _(only Committee Administrator right now)_

***And*** when I click 'Add' the user email address and role will be added to the Manage Users table

  ***And*** that user will now have access to the committee account

  ***And*** the status will read 'Active' if the user has a FECFile Online account (user profile saved per #92) or 'Pending' if they do not.

***Or*** when I click 'Cancel' then the popup will close

Wireframes

1.  Manage User page (Admin clicks Add user)

       

1.  Add new user modal

       

1.  New user added with status of pending

       

1.  New user error

       

### QA Notes ###
- [x] BA/Design Quality Checklist complete
- Note that a user can be re-added after they are removed. We should not prevent that.

### DEV Notes ###
- We'll need a committee account endpoint that creates a record in the membership table.  If the user is a fecfile online user we'll use their user uuid in the record.  If they are not a fecfile online user, we'll need to put there email in a new email column.
- We'll need to add a hook on user creation that updates any records in the memberships with the new users email to add thier user uuid to the record

### Design ###
null

 See full ticket and images here: [FECFILE-510](https://fecgov.atlassian.net/browse/FECFILE-510)

**Comment by MitchellTCG** [comment]
@JonellaCulmer @mary-tcg 
Please review this workflow

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Please review

**Comment by toddlees** [comment]
@AureliaKhorsand @GreggMoreland @MitchellTCG suggestion to change 

>And when I click 'Add' the user email address and role will be added to the Manage Users table with status 'Pending' 
And the status will be "Active" when that user creates their user profile (#92).

to
>And when I click 'Add' the user email address and role will be added to the Manage Users table
>And the status will read 'Active' if the user has a FECFile Online account or 'Pending' if they do not.

The change to avoid interpreting the AC to mean that adding a member will always go to 'Pending'

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by MitchellTCG** [comment]
### QA verified the following:
**1.** Go to the "Users" page
**2.** Click the "Add user" button
**3.** Enter the email of the user you would like to add (in the future, when there are more roles, select a role)
**4.** Click "Add" button
**5.** View success message
**6.** the added user can now see the new committee displayed
Also 
**Error message**
<img width="232" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHFlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--515386b2ab66b24566012b0c6d18a79cb63c37b6/1653%20-%20Allow%20committee%20administrator%20to%20grant%20access%20to%20additional%20users%20on%20the%20committee%20account.png" alt="1653 - Allow committee administrator to grant access to additional users on the committee account.png" />


### QA Review Completed. Moved to Stage Ready.
