### ISSUE TITLE
Allow AUTHORIZED user to select committee account upon login

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1654]
Business Reason

As a provisioned and authorized user on FECfile Online, I will be able to select what committee account I am logging into so that I can switch committee accounts if needed.

Acceptance Criteria

***Given*** a user is authorized on one or more committee accounts on FECfile Online,

  ***When*** they log in to FECfile Online and, if relevant, have enter their user profile information and security consent,

  ***Then*** they will be able to select which committee account they want to log in to

  ***And*** if there are more than three, they will be able to scroll to see more.

  ***And*** when they select a committee account they will be directed to the dashboard

1.  One entry

       

1.  Multiple entries

       

Assets

  

HTML and CSS

  ***"Get started now"***

  Class h1

  color: #212121

  font-family: "gandhi",serif;

  font-weight: 700;

  line-height: 1.2;

  margin: 0

***"Let’s file your FEC report with FECFile…"***

  color: #212121

  font-family: karla,sans-serif;

  font-size: 14px

  font-weight: 700;

  letter-spacing: -.3px;

  margin-bottom: 12px;

  line-height: 1.8;

  text-transform: uppercase;

  margin: 0px 0px 10px

"Select a committee account"

### QA Notes ###
- [x] BA/Design Quality Checklist complete
- Need to work with dev to connect to multiple committee accounts as one user

### DEV Notes ###
 Wireframes

### Design ###
null

[FECFILE-509](https://fecgov.atlassian.net/browse/FECFILE-509)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @JonellaCulmer 
please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG should the name of the committee here just be the Committee Name that we're using in the system already? We can change it later, just want to be sure we know what to pull here. (For example, in the committee header across the system we may be listing out something more specific based on the Committee Detail endpoint.)

Also, the pop up says the same thing as the text next to the question mark box. Is the pop up text just a placeholder?

**Comment by AureliaKhorsand** [comment]
@MitchellTCG I wonder actually if we should just combine this with #1652, and include the wires for if the user doesn't see anything? Also, let me know if we're nixing the pop-up.

**Comment by toddlees** [comment]
<img width="550" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL29yQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7e7416fc9b3b92773c9a984106a224a634f8cc5/image.png" alt="image.png" />

added ac

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers remove dashboard display from the Committee Account login page(s).  The only icon that should display is:

<img width="884" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU02QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--757b1567613c99f9b91948a6a88dcaff923a1c61/image.png" alt="image.png" />

Ticket on-hold until hotfix.

**Comment by mjtravers** [comment]
With @MitchellTCG approval, the person icon for logout is being replaced with the words, "LOG OUT"

**Comment by WiseQA** [comment]
QA review verified the dashboard is not displaying bug fix passes.  "LOG OUT" has been added in right corner of "Select a committee account" page.

Verified one committee account is displayed:

<img width="1207" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUE4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b707bf16b54ba8af523490e9bae04c8e58e9670d/image.png" alt="image.png" />

______________________________________________________________________________________

QA does not have 3 committee accounts.   DEV and QA did a visual of the multiple Committee Accounts displaying.  @MitchellTCG note for demo this is a visual.

<img width="630" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEU4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8adcad2388110e2967db7e7f63d8b9481750c1fa/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.

**Comment by toddlees** [comment]
https://github.com/fecgov/fecfile-web-api/pull/714
addresses the behavior where even though you activate one committee, you would be interacting with records for your first committee regardless.  This patch means that when you select a committee account, not only is that the committee account you log into, the records you interact with are for that committee and not your first
