### ISSUE TITLE
System to show relevant Form 3X transactions for "PAC/PTY" Committee Type

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1659]
Business Reason

As a Committee Administrator, I will be able to only see, create, and update all Form 3X transactions that correspond to my committee type so that I can only create and update the transactions that apply to my committee type.

Acceptance Criteria

***If*** I am a Committee Administrator for a PAC/PTY committee type (Committee Type is included [HERE]([https://docs.google.com/spreadsheets/d/10fwbBXjS9C3N0Q2QqjWbyPpWF_ow4F59WdZbh0_osu4/edit#gid=1295372537](https://docs.google.com/spreadsheets/d/10fwbBXjS9C3N0Q2QqjWbyPpWF_ow4F59WdZbh0_osu4/edit#gid=1295372537)))

  ***When*** I see which transactions are available for me to add and update on a report

  ***Then*** I will see ALL transactions in ALL Form 3x Schedules:

***Add a Receipt*** 

  Contributions from Individuals/Persons:

*   [ ] Individual Receipt
*   [ ] Tribal Receipt
*   [ ] Partnership Receipt
*   [ ] In-kind Receipt
*   [ ] Returned/Bounced Receipt
*   [ ] Earmark Receipt
*   [ ] Conduit Earmark (System shows Conduit Earmark Receipt - tested against this name)
*   [ ] Receipt from Unregistered Entity
*   [ ] Receipt from Unregistered Entity - Returned/Bounced Receipt

Contributions from Registered Users:

*   [ ] Party Receipt
*   [ ] Party In-kind Receipt
*   [ ] Party Returned/Bounced Receipt
*   [ ] PAC Receipt
*   [ ] PAC In-kind Receipt
*   [ ] PAC Earmark Receipt

       ```
*   [ ] PAC Conduit Earmark (System shows this naming used this to test not the two listed below)
*   [ ] PAC Conduit Earmark (Deposited)
*   [ ] PAC Conduit Earmark (Undeposited)

       ```
*   [ ] PAC Returned/Bounced Receipt

Transfers:

*   [ ] Transfer
*   [ ] Joint Fundraising Transfer
*   [ ] In-kind Transfer
*   [ ] In-kind Transfer - Federal Election Activity
*   [ ] Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account
*   [ ] Joint Fundraising Transfer - National Party Pres. Nominating Convention Account
*   [ ] Joint Fundraising Transfer - National Party Headquarters Buildings Account

Refunds:

*   [ ] Refund of Contribution to Federal Candidate
*   [ ] Refund of Contribution to Other Political Committee
*   [ ] Refund of Contribution to Unregistered Committee

Other:

*   [ ] Offset to Operating Expenditures
*   [ ] Other Receipts
*   [ ] Individual Receipt - Non-contribution Account
*   [ ] Other Committee Receipt - Non-contribution Account
*   [ ] Business/Labor Organization Receipt - Non-contribution Account
*   [ ] Individual Recount Receipt
*   [ ] Party Recount Receipt
*   [ ] PAC Recount Receipt
*   [ ] Tribal Recount Receipt
*   [ ] Partnership Recount Account Receipt
*   [ ] Individual National Party Recount/Legal Proceedings Account
*   [ ] Party National Party Recount/Legal Proceedings Account
*   [ ] PAC National Party Recount/Legal Proceedings Account
*   [ ] Tribal National Party Recount/Legal Proceedings Account
*   [ ] Partnership National Party Recount/Legal Proceedings Account
*   [ ] Individual National Party Headquarters Buildings Account
*   [ ] Party National Party Headquarters Buildings Account
*   [ ] PAC National Party Headquarters Buildings Account
*   [ ] Tribal National Party Headquarters Buildings Account
*   [ ] Partnership National Party Headquarters Buildings Account
*   [ ] Individual National Party Pres. Nominating Convention Account
*   [ ] Party National Party Pres. Nominating Convention Account
*   [ ] PAC National Party Pres. Nominating Convention Account
*   [ ] Tribal National Party Pres. Nominating Convention Account
*   [ ] Partnership National Party Pres. Nominating Convention Account
*   [ ] Earmark Receipt for National Party Recount/Legal Proceedings Account (Contribution)
*   [ ] Earmark Receipt for National Party Pres. Nominating Convention Account (Contribution)
*   [ ] Earmark Receipt for National Party Headquarters Buildings Account (Contribution)

***Add a disbursement*** 

  Operating Expenditures:

*   [ ] Operating Expenditure
*   [ ] Credit Card Payment for Operating Expenditure
*   [ ] Staff Reimbursement for Operating Expenditure
*   [ ] Payment to Payroll for Operating Expenditure
*   [ ] Void of Operating Expenditure

Contributions/Expenditures to Registered Filers:

*   [ ] Transfers to Affiliates/Other Committees
*   [ ] Contribution to Candidate
*   [ ] In-kind Contribution to Candidate
*   [ ] Void of Contribution to Candidate
*   [ ] Contribution to Other Committee
*   [ ] In-kind Contribution to Other Committee
*   [ ] Void of Contribution to Other Committee

Other Expenditures:

*   [ ] Other Disbursements
*   [ ] Credit Card Payment for Other Disbursement
*   [ ] Staff Reimbursement for Other Disbursement
*   [ ] Payment to Payroll for Other Disbursement
*   [ ] Void of Other Disbursement
*   [ ] Non-contribution Account Disbursement
*   [ ] Non-contribution Account Credit Card Payment
*   [ ] Non-contribution Account Staff Reimbursement
*   [ ] Non-contribution Account Payment to Payroll
*   [ ] Individual Refund - Non-contribution Account
*   [ ] Other Committee Refund - Non-contribution Account
*   [ ] Business/Labor Organization Refund - Non-contribution Account
*   [ ] Recount Account Disbursement
*   [ ] National Party Recount/Legal Proceedings Account Disbursement
*   [ ] National Party Headquarters Buildings Account Disbursement
*   [ ] National Party Pres. Nominating Convention Account Disbursement
*   [ ] Individual Refund - National Party Headquarters Buildings Account
*   [ ] Other Committee Refund - National Party Headquarters Buildings Account
*   [ ] Tribal Refund - National Party Headquarters Buildings Account
*   [ ] Individual Refund - National Party Pres. Nominating Convention Account
*   [ ] Other Committee Refund - National Party Pres. Nominating Convention Account
*   [ ] Tribal Refund - National Party Pres. Nominating Convention Account
*   [ ] Individual Refund - National Party Recount/Legal Proceedings Account
*   [ ] Other Committee Refund - National Party Recount/Legal Proceedings Account
*   [ ] Tribal Refund - National Party Recount/Legal Proceedings Account

Refunds:

*   [ ] Refund of Individual Contribution
*   [ ] Refund of Individual Contribution - Void
*   [ ] Refund of Party Contribution
*   [ ] Refund of Party Contribution - Void
*   [ ] Refund of PAC Contribution
*   [ ] Refund of PAC Contribution - Void
*   [ ] Refund of Unregistered Receipt from Person
*   [ ] Refund of Unregistered Receipt from Person - Void

Federal Election Activity Expenditures:

*   [ ] 100% Federal Election Activity Payment
*   [ ] Credit Card Payment for 100% Federal Election Activity
*   [ ] Staff Reimbursement for 100% Federal Election Activity
*   [ ] Payment to Payroll for 100% Federal Election Activity
*   [ ] Void of 100% Federal Election Activity

Independent Expenditures:

*   [ ] Independent Expenditure
*   [ ] Multistate Independent Expenditure
*   [ ] Credit Card Payment for Independent Expenditure
*   [ ] Staff Reimbursement for Independent Expenditure
*   [ ] Payment to Payroll for Independent Expenditure
*   [ ] Void of Independent Expenditure (System name tested - Independent Expenditure - Void)

***Add a loan or debt***

*   [ ] Loan Received from Individual
*   [ ] Loan Received from Bank
*   [ ] Loan by Committee
*   [ ] Debt Owed to Committee
*   [ ] Debt Owed by Committee

Dev Notes

*   Committee Type can be determined using the following: [https://docs.google.com/spreadsheets/d/10fwbBXjS9C3N0Q2QqjWbyPpWF_ow4F59WdZbh0_osu4/edit#gid=1295372537](https://docs.google.com/spreadsheets/d/10fwbBXjS9C3N0Q2QqjWbyPpWF_ow4F59WdZbh0_osu4/edit#gid=1295372537)

       //

### QA Notes ###
 
 - [x] BA/Design Quality Checklist complete
- Will need to test this with a Non-qualified Party committee (Committee Designation 'U' and Committee Type 'X)
- Update to #1472, where U and X was designated as PTY only. It should be considered PAC/PTY by the system. Since the code is changing, should test a PAC committee, PTY committee, and PAC/PTY committee.

### DEV Notes ###
 
 null

### Design ###
 
 null

[FECFILE-506](https://fecgov.atlassian.net/browse/FECFILE-506)

**Comment by toddlees** [comment]
@AureliaKhorsand @GreggMoreland Which transactions can PAC committees use and which transactions can PTY committees use?  Can Non-qualified committees (PAC/PTY) use any transaction type?

**Comment by AureliaKhorsand** [comment]
@toddlees Correct, non-qualified committees (PAC/PTY) can use any transaction type. This ticket will be done in conjunction with #404 and #1472 , which will specify what transactions PAC and PTY committees can use.

**Comment by AureliaKhorsand** [comment]
<del>BA note: look into if we can differentiate between U and X committee that is a HOST/CONVENTION committee versus not. </del>

As we cannot differentiate a Host/Convention committee at this time, we will treat all U and X committees as such.

**Comment by sasha-dresden** [comment]
@AureliaKhorsand did we get an answer on how to determine when a committee is PAC/PTY? The only example on the spreadsheet was line 38, which is:  
U	X	Non-qualified Party	PAC/PTY

However this seems to be the exact same as line 22:
U	X	Non-qualified Party	PTY


The way I had determined whether a committee is PAC or PTY was by looking at the Committee Type:
PAC = "O", "U", "D", "N", "Q", "V", "W"
PTY = "X", "Y"

Anything else is being treated as PAC/PTY (which is to say, it will see every transaction type)

**Comment by AureliaKhorsand** [comment]
Yes, this is an update to #1472 in that a committee with U and X will be considered a PAC/PTY, _not_ a PTY. Confirmed with Sasha that this will require some code updates and all three scenarios should be tested. @MitchellTCG recommend bumping to a 5 since this will be additional QA lift.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Please provide the same level of detail with checkboxes for the transactions we should see as a PAC/PTY like you did in tickets 404 and 1472. Ping me if you have any questions.

On hold and sent back to in-progress til updated.

Thank you.

**Comment by GreggMoreland** [comment]
@MitchellTCG Initially they were not listed since it is EVERY tranasaction. Listed here now.

**Comment by sasha-dresden** [comment]
My code was just allowing every transaction through if it wasn't one of the other two, so no code change required. Returning to QA for verification.

**Comment by WiseQA** [comment]
@GreggMoreland your list in the acceptance criteria shows the following for conduit ?

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/87a58d89-5d1c-455d-9166-d7030bba9bfd)

The only transaction in the list is named "Conduit Earmark Receipt" ?

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/b650790a-8a32-4c5d-8413-91abe4226125)

________________________________________________________________________________________________________________________

@MitchellTCG @GreggMoreland standing by for clarification and update on naming where needed. - thanks

**Comment by GreggMoreland** [comment]
@WiseQA Yes, I took everything from our master spreadsheet and didn't go back to change that one. Updated now. (I have too many lists I've been putting together today)

@GreggMoreland so is it Conduit Earmark Receipt like transaction list ?   or Conduit Earmark like you updated list ?

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/b478cf14-6413-4889-beea-b6772f537897)

Still on-hold for this ?  I will take on-hold off once verify this is correct = thanks !!

**Comment by WiseQA** [comment]
Per Gregg There are no changes to transactions names that are in the system.

I will make note in the AC (as we are not allowed to change AC) if any names different what the system is showing.   Thanks

___________________________________________________________________________________________________________________________

@GreggMoreland so is it Conduit Earmark Receipt like transaction list ?   or Conduit Earmark like you updated list ?

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/b478cf14-6413-4889-beea-b6772f537897)

Still on-hold for this ?  I will take on-hold off once verify this is correct = thanks !!

**Comment by WiseQA** [comment]
QA verified the following transactions show for PAC/PTY Committee (copied AC list to verify). (Note: Tested Individual Receipt, Party Receipt, Operating Expenditure, Contribution to Candidate transactions - verified transactions were created and saved)

**Add a Receipt** 
Contributions from Individuals/Persons:
- [x] Individual Receipt
- [x] Tribal Receipt
- [x] Partnership Receipt
- [x] In-kind Receipt
- [x] Returned/Bounced Receipt
- [x] Earmark Receipt
- [x] Conduit Earmark **(System shows Conduit Earmark Receipt - tested against this name)**
- [x] Receipt from Unregistered Entity
- [x] Receipt from Unregistered Entity - Returned/Bounced Receipt

Contributions from Registered Users:
- [x] Party Receipt
- [x] Party In-kind Receipt
- [x] Party Returned/Bounced Receipt
- [x] PAC Receipt
- [x] PAC In-kind Receipt
- [x] PAC Earmark Receipt
- [x] PAC Conduit Earmark  **(System shows this naming used this to test not the two listed below)**
- [ ] PAC Conduit Earmark (Deposited)
- [ ] PAC Conduit Earmark (Undeposited)
- [x] PAC Returned/Bounced Receipt

Transfers:
- [x] Transfer
- [x] Joint Fundraising Transfer
- [x] In-kind Transfer
- [x] In-kind Transfer - Federal Election Activity
- [x] Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account
- [x] Joint Fundraising Transfer - National Party Pres. Nominating Convention Account
- [x] Joint Fundraising Transfer - National Party Headquarters Buildings Account

Refunds:
- [x] Refund of Contribution to Federal Candidate
- [x] Refund of Contribution to Other Political Committee
- [x] Refund of Contribution to Unregistered Committee

Other:
- [x] Offset to Operating Expenditures
- [x] Other Receipts
- [x] Individual Receipt - Non-contribution Account
- [x] Other Committee Receipt - Non-contribution Account
- [x] Business/Labor Organization Receipt - Non-contribution Account
- [x] Individual Recount Receipt
- [x] Party Recount Receipt
- [x] PAC Recount Receipt
- [x] Tribal Recount Receipt
- [x] Partnership Recount Account Receipt
- [x] Individual National Party Recount/Legal Proceedings Account
- [x] Party National Party Recount/Legal Proceedings Account
- [x] PAC National Party Recount/Legal Proceedings Account
- [x] Tribal National Party Recount/Legal Proceedings Account
- [x] Partnership National Party Recount/Legal Proceedings Account 
- [x] Individual National Party Headquarters Buildings Account
- [x] Party National Party Headquarters Buildings Account
- [x] PAC National Party Headquarters Buildings Account
- [x] Tribal National Party Headquarters Buildings Account
- [x] Partnership National Party Headquarters Buildings Account
- [x] Individual National Party Pres. Nominating Convention Account
- [x] Party National Party Pres. Nominating Convention Account
- [x] PAC National Party Pres. Nominating Convention Account
- [x] Tribal National Party Pres. Nominating Convention Account
- [x] Partnership National Party Pres. Nominating Convention Account
- [x] Earmark Receipt for National Party Recount/Legal Proceedings Account (Contribution)
- [x] Earmark Receipt for National Party Pres. Nominating Convention Account (Contribution)
- [x] Earmark Receipt for National Party Headquarters Buildings Account (Contribution)

**Add a disbursement** 
Operating Expenditures:
- [x] Operating Expenditure
- [x] Credit Card Payment for Operating Expenditure
- [x] Staff Reimbursement for Operating Expenditure
- [x] Payment to Payroll for Operating Expenditure
- [x] Void of Operating Expenditure

Contributions/Expenditures to Registered Filers:
- [x] Transfers to Affiliates/Other Committees
- [x] Contribution to Candidate
- [x] In-kind Contribution to Candidate
- [x] Void of Contribution to Candidate
- [x] Contribution to Other Committee
- [x] In-kind Contribution to Other Committee
- [x] Void of Contribution to Other Committee

Other Expenditures:
- [x] Other Disbursements
- [x] Credit Card Payment for Other Disbursement
- [x] Staff Reimbursement for Other Disbursement
- [x] Payment to Payroll for Other Disbursement
- [x] Void of Other Disbursement
- [x] Non-contribution Account Disbursement
- [x] Non-contribution Account Credit Card Payment
- [x] Non-contribution Account Staff Reimbursement
- [x] Non-contribution Account Payment to Payroll
- [x] Individual Refund - Non-contribution Account
- [x] Other Committee Refund - Non-contribution Account
- [x] Business/Labor Organization Refund - Non-contribution Account
- [x] Recount Account Disbursement
- [x] National Party Recount/Legal Proceedings Account Disbursement
- [x] National Party Headquarters Buildings Account Disbursement
- [x] National Party Pres. Nominating Convention Account Disbursement
- [x] Individual Refund - National Party Headquarters Buildings Account
- [x] Other Committee Refund - National Party Headquarters Buildings Account
- [x] Tribal Refund - National Party Headquarters Buildings Account
- [x] Individual Refund - National Party Pres. Nominating Convention Account
- [x] Other Committee Refund - National Party Pres. Nominating Convention Account
- [x] Tribal Refund - National Party Pres. Nominating Convention Account
- [x] Individual Refund - National Party Recount/Legal Proceedings Account
- [x] Other Committee Refund - National Party Recount/Legal Proceedings Account
- [x] Tribal Refund - National Party Recount/Legal Proceedings Account

Refunds:
- [x] Refund of Individual Contribution
- [x] Refund of Individual Contribution - Void
- [x] Refund of Party Contribution
- [x] Refund of Party Contribution - Void
- [x] Refund of PAC Contribution
- [x] Refund of PAC Contribution - Void
- [x] Refund of Unregistered Receipt from Person
- [x] Refund of Unregistered Receipt from Person - Void

Federal Election Activity Expenditures:
- [x] 100% Federal Election Activity Payment
- [x] Credit Card Payment for 100% Federal Election Activity
- [x] Staff Reimbursement for 100% Federal Election Activity
- [x] Payment to Payroll for 100% Federal Election Activity
- [x] Void of 100% Federal Election Activity

Independent Expenditures:
- [x] Independent Expenditure
- [x] Multistate Independent Expenditure
- [x] Credit Card Payment for Independent Expenditure
- [x] Staff Reimbursement for Independent Expenditure
- [x] Payment to Payroll for Independent Expenditure
- [x] Void of Independent Expenditure (System name tested - Independent Expenditure - Void)

**Add a loan or debt**
- [x] Loan Received from Individual
- [x] Loan Received from Bank
- [x] Loan by Committee
- [x] Debt Owed to Committee
- [x] Debt Owed by Committee

**Comment by WiseQA** [comment]
QA review completed with the following naming exceptions from AC to System Transaction names.  BA verified to use system naming not list in the AC naming.

1.  Conduit Earmark (System shows Conduit Earmark Receipt - tested against this name)
2.  PAC Conduit Earmark (System shows this naming used this to test not the two listed below)
 PAC Conduit Earmark (Deposited)
 PAC Conduit Earmark (Undeposited)

This test for PAC/PTY included every current transaction listed in the system.

QA Review Completed.   Moved to Stage Ready.
