### ISSUE TITLE
Allow user to add Report Memo Text to Form 3X report

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#166]
Business Reason 
 

As a user, I will be able to add memo text at the report level so that I can provide additional information needed to FEC upon submission and have it become part of the public record.

 Acceptance Criteria 
 

**Given** I am a (Backup) Committee Administrator
**When** I am editing a report that has not yet been submitted
**Then** I will be able to add report memo text at the report level _(4000 character limit)_
**And** the user will be able to save the report memo text.
**And** the user can edit as needed before the report is submitted.

 Dev Tasks 
 
1. creation of report memo schema (will be used to validate records and dictate order of columns in .fec)
2. use schema for validating memos (occurs while user creates memo and when it's saved to the fecfile backend)

 Dev Notes 

Memo records should be saved in their own table and linked to their report with a foreign key.

![Report Level Memo.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/3dbe12b3-898c-4b5c-8e18-c7981990aa5d)

### QA Notes ### 
 
To test, go to the "Add a report level memo" and edit the form. After saving the form, go to any other page and then come back to the report level memo page. If the memo text that you typed the first time on the page is in the input box, then the page is working correctly
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
Mocks in fecfile-project-management#42

**Comment by AureliaKhorsand** [comment]
**5/11/22 Refinement Meeting Notes**: Devs will build this out to accommodate if in the future, FEC requires the ability for multiple memo comments to be added. This is not the requirement right now.

**Comment by AureliaKhorsand** [comment]
**5/11/22 Refinement Meeting Notes**: Devs will build this out to accommodate if in the future, FEC requires the ability for multiple memo comments to be added. This is not the requirement right now.

@MitchellTCG to provide updated wireframe.

**Comment by AureliaKhorsand** [comment]
Waiting on questions from #346 to be answered from usability testing.

@toddlees note that the wireframe may change, although the requirements will not (report level memo may just be on a separate page).

**Comment by AureliaKhorsand** [comment]
@MitchellTCG Now that this is it's own page, do we have a wireframe for this?

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA review complete.   Report Memo Text for Form3X Report passes when entering text and editing memo.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/82f9ac6e-3736-4428-a816-ec50971261c9)

Back button not working once "Add a report level memo" is selected and memo text entered and saved.  Returned to in-progress @MitchellTCG @mjtravers 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a5c61dc6-082d-4b30-aa68-d16b64695679)

**Comment by mjtravers** [comment]
The back button is wired to go the the "View print preview" page which is currently not live so the button doesn't go anywhere. After the "View print preview" page is available the back button will be wired to go to it. This ticket will stay in "In Progress" until ticket #290 is completed

**Comment by mjtravers** [comment]
Passes CR. Left report menu links to Print Preview now working. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers moved ticket back to In-Progress.   Hard returns (carriage returns) need added to memo field as verified with requirements and FEC.    

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/12f8a15c-5795-4af1-8e87-edc29da960c6)

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers per clarification from FEC, hard returns (carriage returns) are NOT allowed in Report memo due to FEC documentation.   Therefore, report memo text will be continuous text strings as shown in screenshot below:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2ad68195-e7ce-4621-92e9-58ea70cdfdbc)

**Comment by mjtravers** [comment]
In light of no carriage returns allowed, sending ticket back to QA.

**Comment by WiseQA** [comment]
QA testing verified back button fixed see below screenshot:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/897b4eaf-309d-4a68-a35e-509b85ff3ae0)

QA Review Completed.   Moved to Stage Ready
