### ISSUE TITLE
System to inform user committee account cannot be created if their email does not match OR it already exists

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1662]
Business Reason

If the user's login.gov email does not match either of the Form 1 emails OR the committee account already exists, then the system will not let the user create a new committee account so that we do not create duplicates in the system.

Acceptance Criteria

***Given*** a provisioned user has selected "Create a new committee account" from the committee account selection screen,

  ***when*** they chose a committee from the lookup and click "Create account",

  ***IF*** either of the following are true:

*   their login.gov email does NOT match either email on the Form 1 (mock committee data) for that committee (COMMITTEE EMAIL)
*   the committee account already exists in FECfile Online

***then*** the system will inform them there was an issue creating the committee, and they can either:

*   select another committee from the lookup
*   go back

Wireframe

  

Asset

  

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
- Check against COMMITTEE EMAIL of Form 1 data

### Design ###
null

 See full ticket and images here: [FECFILE-504](https://fecgov.atlassian.net/browse/FECFILE-504)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
wire updated

**Comment by dheitzer** [comment]
@MitchellTCG @mary-tcg do you have any .svg for the exclamation circle? Thanks.

**Comment by MitchellTCG** [comment]
I will look and post

*H. Mitchell Jarrett, CSP-SM, CSPO*
Agile Project Manager
*TCG, Inc. - Positively Distinct* - CMMI-DEV Level 3 - CMMI-SVC Level 2 -
ISO 9001:2008
Tel: 202.395.2462 | Mobile: 202.270.1935 | ***@***.*** |
www.tcg.com
<https://www.facebook.com/TCG-32241785903>
<https://twitter.com/TCGnews> [image:
Linkedin] <https://www.linkedin.com/in/mitchell-jarrett-4610096>

**Comment by MitchellTCG** [comment]
@dheitzer see if this works
<img width="94" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzJ6QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c6a3eef747b87da6de9c7d8b47aa33e7dd93811/Exclamation.svg" alt="Exclamation.svg" />

**Comment by toddlees** [comment]
Passes CR moving to QA

**Comment by WiseQA** [comment]
QA review verified when entering an existing Committee ID the "Unable to create account" explanation is displayed and committee unable to be created.   

<img width="1407" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVhKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23fbc0a10d8c0958a182c07d4f453b18d3b673db/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
