### ISSUE TITLE
Allow user to edit Memo item on Independent Expenditures in a Form 24 report

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1664]
Business Reason

As a user, I will be able to edit Memo Code on Independent Expenditures (Schedule E transactions) on a Form 24 report as needed so I can accurately report to the FEC within the allotted timeframe. ***Note:*** This is a requirements update from #1499, as we need the SE transaction to be completely the same in look and functionality to the Form 3X SE transaction build.

Acceptance Criteria

***Given*** the user is creating/editing an Independent Expenditure on a Form 24,

*   Independent Expenditure
*   Void of Independent Expenditure
*   Multistate Independent Expenditure
*   Credit Card Payment for Independent Expenditure
*   Staff Reimbursement for Independent Expenditure
*   Payment to Payroll for Independent Expenditure

***then*** there WILL be the ability to mark the Tier 1 transactions as memo items.

—

***Given*** the user is creating/editing an Independent Expenditure Tier 2 Transaction on a Form 24,

*   Credit Card Payment Memo for Independent Expenditure
*   Staff Reimbursement Memo for Independent Expenditure
*   Payment to Payroll Memo for Independent Expenditure

***then*** they will see Memo item as checked and read-only.

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
 Wireframes
Independent Expenditure

Independent Expenditure - Void

Credit Card Payment for IE

Payment to Payroll

Staff Reimbursement

Multistate

### Design ###
null

[FECFILE-503](https://fecgov.atlassian.net/browse/FECFILE-503)

**Comment by mary-tcg** [comment]
@AureliaKhorsand @MitchellTCG wires added

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
**QA review tested using Login.gov and Test Committee ID C00100495 assigned to QA for testing.**

Verified Memo Item checkbox has been added to the Form 24 Independent Expenditures.  Memo Item checkbox is Optional and selectable.   Verified the Independent Expenditures transactions listed in the AC.

<img width="973" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGIyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--471dd170f0bdf1dff961e789fb92c62e838dc9c6/image.png" alt="image.png" />

__________________________________________________________________________________________________________________
Verified when creating/editing an Independent Expenditure Tier 2 Transaction on a Form 24 the Memo Item check box is checked and read only.    Verified the following memo transactions.

- Credit Card Payment Memo for Independent Expenditure
- Staff Reimbursement Memo for Independent Expenditure
- Payment to Payroll Memo for Independent Expenditure

<img width="1081" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelAyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--528dcab7c35a641eb843b5e46ebbd677cb13f3ce/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
