### ISSUE TITLE
Remove developer Docker setup for front-end app

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#167]
For the development environment, the Docker setup is problematic for a number of reasons mainly based on the need for the Docker process running as root:
- Root permission issues between container and host file systems
- Unable to upgrade to node 16 because of permission issues within container

It is easier and more reliable to run the development server using the ng command line: "ng serve". The front-end for the "local" environment has already been modified to use ng serve with listens for app requests on port 4200

## Task ##
- Remove the Dockerfile and docker-compose.yml and related configuration files from the repo.
- Update the developer notes in the README files in GitHub to reflect the changes and with the new instructions
- Upgrade the node images in the .circleci/config.yml file from version 14 to version 16

## QA ##
- It can be verified that the "Dockerfile" entry is no longer in the code by seeing it not here in this directory: https://github.com/fecgov/fecfile-web-app
- The developer notes were updated and can be seen in the "Running the Front-End locally" section of the REAME: https://github.com/fecgov/fecfile-web-app
- A visual inspection can be made of the use of node 16.15 in the [Circle CI configuration file](https://github.com/fecgov/fecfile-web-app/blob/develop/.circleci/config.yml#L14)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by toddlees** [comment]
when extracting the snyk cli install.  Please add documentation for M1 Mac user who use the following lines in the current Dockerfile:
```
RUN curl https://static.snyk.io/cli/latest/version > snyk.version
RUN curl -sO https://static.snyk.io/cli/v$(cat snyk.version)/snyk-linux-arm64
RUN curl -q -sO https://static.snyk.io/cli/v$(cat snyk.version)/snyk-linux-arm64.sha256
RUN sha256sum -c snyk-linux-arm64.sha256
```

**Comment by WiseQA** [comment]
Verified Dockerfile entry is no longer in the code.  
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/79c6ef7a-277c-41ac-b094-eda72187497d)

Visual inspection of ticket for QA review with DEV team.

QA review completed.  Moved to Stage Ready.
