### ISSUE TITLE
Test only: Select and create Schedule E memo transactions from Form 24 Schedule E tier 1 transactions

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1672]
Business Reason

As a user, I will be able to 'Save and Add Memo' for each of the Schedule E transactions which have a memo when I am creating from a Form 24 report so that I can report on my committee's transactions.

 Acceptance Criteria

Given the user is creating/editing an Independent Expenditure Schedule E Transaction on a Form 24,  The following Schedule E transactions can create/edit a memo (Tier 2).   

- Credit Card Payment Memo for Independent Expenditure
- Staff Reimbursement Memo for Independent Expenditure
- Payment to Payroll Memo for Independent Expenditure

### QA Notes ### 
 - [ ] BA/Design Quality Checklist complete

This is a test ticket only for creating / editing of memo's for the Schedule E Independent Expenditure transactions that were already built out for Form 24.  #1499
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by WiseQA** [comment]
QA review verified Credit Card Payment Memo for Independent Expenditure created / editable / saved.

<img width="1264" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkxWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--480768e2ac32892a1e28994212b348a47b5fceb1/image.png" alt="image.png" />

<img width="1565" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm5WQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57af9659a88ed53d859372e27e6e2f6a7b5a7ee5/image.png" alt="image.png" />


______________________________________________________________________________________________________________
Verified Staff Reimbursement Memo for Independent Expenditure created / editable / saved.


<img width="1288" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXJWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c649fd4f9642dd09ad67899eff76306c475a953c/image.png" alt="image.png" />

<img width="1421" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNS9WQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf26670c17675c857e5736f0d62762f431491aa6/image.png" alt="image.png" />

______________________________________________________________________________________________________________________
Verified Payment to Payroll Memo for Independent Expenditure created / editable / saved.

<img width="1233" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNURWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8304721e17f1ece0812957079117ba739fea77c/image.png" alt="image.png" />

<img width="1549" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVhWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23652e0b544b9e6e78c4c60ea1f025fec148fc89/image.png" alt="image.png" />

_________________________________________________________________________________________________________
Transactions in this report page for FORM 24 showing memo transactions

<img width="1546" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3JWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51aaff19bc8e546d72c74fcb50922dd933200549/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
QA Review Completed.   Moved to Stage Ready (Ticket tested in Sprint 36)
