### ISSUE TITLE
Fix Form 1M Affiliation Committee Lookup / Create New Contact to be able to "Save"

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1677]
During verification of testing with DEV, the Form 1M Affiliation Committee Lookup / Create New Contact functionality is broken on stage not allowing the Form 1M to be "Saved".  (Tested on STAGE using login.gov Committee ID#C00100495)

1.  Create Form 1M
2.  Select radio button for Affiliation under "Status By" 
3.  Under Lookup select "Search for a contact" for Committee.   Verify "Affiliated Committee Name" and "Affiliated Committee ID" fields are populated.    
4.  Enter "Affiliated Date" then select the "Save" button.   (NOTE:   This is where the breakage occurs.   The 500 error appears, and the Form 1M cannot be saved)

<img width="1347" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTdnQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29a481c6327ea893f8720e98c42951c53a0269e3/image.png" alt="image.png" />

5.  Redo above steps creating a NEW Committee contact under "Affiliation" Lookup the same bug occurs.

@mjtravers @MitchellTCG fix Form 1M Affiliation Committee Lookup / Create New Contact to be able to "Save".   Hotfix for Sprint 36 as this functionality was working and passing.   Pointed Hotfix 2 pts and put In-Progress.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
The contact ID was not getting set correctly in the payload being sent back to the API. This fix cleared up the 500 errors being seen on the front end.

Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified hotfix fixed.

1.  Create Form 1M
2.  Select radio button for Affiliation under "Status By"
3.  Under Lookup select "Search for a contact" for Committee. Verify "Affiliated Committee Name" and "Affiliated Committee ID" fields are populated.
4.  Enter "Affiliated Date" then select the "Save" button. (NOTE:  Hotfix completed.)
5.  Redo above steps creating a NEW Committee contact under "Affiliation" Lookup the same bug occurs.  Verified Hotfix completed.

<img width="1283" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2ppQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68565725ba28710a0802e1b102935297c6d305fd/image.png" alt="image.png" />

Form 1M displayed in Mange reports table.   As an extra test verified submission still working.  (NOTE:   Have to use an existing Committee / Committee ID cannot create a new Committee / Committee ID for submission.  This is a future fix)

QA Review Completed.   Moved to Stage Ready.
