### ISSUE TITLE
Duplicate name appearing when updating COMMITTEE NAME for F3X Party Receipt

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1679]
In the Party Receipt, we save the committee name in both the contributor_organization_name and the donor_committee_name fields in the transaction. This double entry is not being handled properly so that the contact change pop-up when saving with a changed committee name shows 2 name changes. In addition, the donor_committee_name does not get updated when a contact is updated so that the 2 names in the transaction get out of sync.

Party Receipt spec: [https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=2079918222](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=2079918222)

To replicate the issue:

  1\. Create a new Party Receipt and create a new committee for the receipt.

  2\. Go to the Contact Manager and change the name of the committee.

  3\. Go back to the Party Receipt and then change the committee name again.

  4\. Two names in pop up, 1 correct and 1 incorrect.

  5\. Save the transaction. The contact and all transactions will have the incorrect name.

Pop-up displaying 2 name when only BIDEN FOR PRESIDENT B should be displayed.

  

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-500](https://fecgov.atlassian.net/browse/FECFILE-500)

**Comment by WiseQA** [comment]
QA retested and verified get the same "bug" for duplicate name appearing when updating COMMITTEE NAME for Party Receipt (Schedule A) on the Form 3x.

___________________________________________________________________________________________________________________
Changed Committee Name in the Party Receipt transaction.

<img width="1249" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDhrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d610d18d687e9e55f5ec8b31d62f222dd6052cc/image.png" alt="image.png" />

_______________________________________________________________________________________________________________
Bug is still broken

<img width="450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0lrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dece5dec20d89b9846e00c35eb42eca3cf612bc8/image.png" alt="image.png" />

**Comment by sasha-dresden** [comment]
I think this might be OBE. I tried replicating the issue following the steps listed and only one change occurred and nothing got out of sync

**Comment by mjtravers** [comment]
Yes, this ticket is OBE. The issue was fixed when the candidate info was pulled from the transactions and consolidated exclusively in the contact table.

**Comment by toddlees** [comment]
no code changes.  moving to QA

**Comment by WiseQA** [comment]
QA review tested to verify "Bug" was fixed.  (Note fixed issue was fixed when the candidate info was pulled from the transactions and consolidated exclusively in the contact table per DEV).   

1.  Createda new Party Receipt and create a new committee for the receipt.
2.  Go to the Contact Manager and change the name of the committee.  Then save 1 name change popup appears.

<img width="408" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW5KQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--115a9aab69a220eace95465f8b2f14869d11f09f/image.png" alt="image.png" />

3.  Go back to the Party Receipt and then change the committee name again. Popup displays one contact name and is saved correctly.

<img width="404" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXJKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--927ed230e48714802f60b2d85fb42a88786072cc/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
