### ISSUE TITLE
Remove unused Cloud.gov database instances

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1688]
After we recently upgraded and cleaned out our RDS instances on Cloud.gov we left the old instances running just in case we needed to roll back.

Remove old database instances. The are named: ***fecfile-api-rds_mved***

Needs to be done for all 2 spaces: dev, stage, prod

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-495](https://fecgov.atlassian.net/browse/FECFILE-495)

**Comment by dheitzer** [comment]
all 3 instances have been removed

**Comment by mjtravers** [comment]
No code to review. Sending to QA.

Screenshot of cloud.gov dashboard without fecfile-api-reds_mved services:
<img width="796" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1IxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d21444d1e28a0cad6e9419f3036188986b989a15/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of Screenshot of cloud.gov dashboard without fecfile-api-reds_mved services: built for this ticket per DEV.

<img width="873" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnQyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a757a3e1fc667d9ebe86c116c1e8a718b508398a/image.png" alt="image.png" />

QA Review Completed.  Moved to Stage Ready.
