### ISSUE TITLE
e2e tests for Form 1M

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1689]
We need e2e tests set up for:

- [ ] Creating a Form 1M affiliation report
- [ ] Creating a Form 1M qualification report
- [ ] Form 1M report level memo text

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by toddlees** [comment]
@mjtravers  I'm starting on f1m affiliation.  so if you split this up, you can assign that one to me

**Comment by mjtravers** [comment]
From CR, some code changes need to be made to remove issues caused by random record generation. Moving back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
The e2e test updates have been pushed to DEV. An email will go out tonight when the tests are run if any fail during the nightly run.

**Comment by WiseQA** [comment]
QA received email for e2e nightly run 04/092024.   e2e test run was successful.  

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/b00a62b5-321a-4fdf-90ce-87d5fd6494f8)

QA Review Completed.  Moved to Stage Ready.
