### ISSUE TITLE
System to display user account details entered in the user profile

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1696]
Business Reason

As a user, I will be able to see the first and last name that I entered when I first created my FECfile Online account on the User management page so that I can verify my user profile details.

Acceptance Criteria

***Given*** I am a user who just created my account (#92) 

  ***When*** I select 'Users' from the drop down in the upper righthand corner,

  ***Then*** in the Manage Users table, I will see:

*   Last name, First name under "Name" column (this will pull from what I entered in #92)
*   my email under "Email"
*   Committee Administrator under "Role" _(note this is our only role for now)_
*   Active under "Status"

### QA Notes ###
- [ ] BA/Design Quality Checklist complete

### DEV Notes ###
There are two statuses:
- [ ] Active
- [ ] Pending

### Design ###
null

 See full ticket and images here: [FECFILE-491](https://fecgov.atlassian.net/browse/FECFILE-491)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg can the design team decide on the "status" options for users? I think we have "Invited" for if they have been granted access but haven't logged in yet, but what about active vs. inactive? Do we need an inactive, or are they just deleted?

**Comment by AureliaKhorsand** [comment]
<img width="1313" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEFzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39e12fe2dbd11dc718fc44a91f89992930f5f336/image.png" alt="image.png" />

**Comment by MitchellTCG** [comment]
@GreggMoreland 
@AureliaKhorsand 
please check this. I believe this is OBE and was already coded in when they initially built out the functionality.

**Comment by GreggMoreland** [comment]
@MitchellTCG
@AureliaKhorsand 

Yes, it looks like we have this now that all the other pieces are in place. 
<img width="1631" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMno0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ae72b3cfdf8ee8670d4daebb99977b160947304/image.png" alt="image.png" />

**Comment by AureliaKhorsand** [comment]
Agreed. Closing as OBE.
