### ISSUE TITLE
Run Protractor tests in CI pipeline

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#17]
**Acceptance Criteria**
- At least one protractor end-to-end test runs successfully in the Circle CI environment
- The protractor end-to-end tests are runnable in the docker-compose development environment via script or single command.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by albertcrowley** [comment]
This is a CI pipeline task, so no specific QA outside of code review needed.

**Comment by WiseQA** [comment]
As noted no QA action required on this ticket - moved to closed as ticket complete.
