### ISSUE TITLE
Fix the missing Report Name and Report Date on the Left NAV Bar

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1708]
During testing the Left NAV bar is missing the Report Name and Report Date. (Tested on STAGE and DEV)

Left NAV displaying currently:

_______________________________________________________________________________________________________________________

Left NAV should display:

_________________________________________________________________________________________________________

@MitchellTCG @mjtravers Hotfix bug ticket. Assigned to Sprint 37, pointed as 3 pts.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-490](https://fecgov.atlassian.net/browse/FECFILE-490)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Left NAV Report Name and Report Date have been fixed and are displaying. (Tested on STAGE).

<img width="277" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGM4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c8bf7762c2d47ddca3f887d190014c201e69801/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
