### ISSUE TITLE
Allow user to reattribute a Tier 1 Schedule A transaction within current report

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#171]
Business Reason

As a user, I will be able to "reattribute" a Tier 1 transaction within a current open report so that I can reattribute part or all of the receipt amount to a different entity, changing the aggregation amount for the entity on each new transaction.

Acceptance Criteria

***Given*** a Tier 1 receipt on Schedule A in the current open report (In-progress)

  ***When*** I initiate the 'Reattribute' action for that transaction,

  ***Then*** I will be able to indicate the how much should be reattributed, to whom, and when as follows:

—

1.  Contact

       #

*   ***CONTACT TYPE***- _(Required, contact type values should match the original receipt specification)_

—
_if CONTACT TYPE = Organization_

*   ***ORGANIZATION NAME*** (Required, LOOKUP)

—
_if CONTACT TYPE = Committee_

*   ***COMMITTEE NAME*** (Required, LOOKUP)
*   ***COMMITTEE ID*** (Required)

—
_if CONTACT TYPE = Individual_

*   ***LAST NAME*** (Required, LOOKUP)
*   ***FIRST NAME*** (Required)
*   ***MIDDLE NAME*** (Optional)
*   ***PREFIX*** (Optional)
*   ***SUFFIX*** (Optional)

1.  Address

       #

*   ***STREET ADDRESS*** (Required)
*   ***APARTMENT, SUITE, ETC.*** (Optional)
*   ***CITY*** (Required)
*   ***STATE/PROVINCE*** (Required)
*   ***ZIP/POSTAL CODE*** (Required)

1.  Receipt Information

       #

*   ***REATTRIBUTION DATE*** (required)
*   ***MEMO ITEM*** (required, automatically checked by the system and user cannot change it)
*   ***REATTRIBUTED AMOUNT*** (required, must be positive and cannot exceed amount of original contribution)
*   ***AGGREGATE*** (read-only, will match logic of original transaction)

1.  Additional information

       #

*   ***PURPOSE OF RECEIPT*** (Required, system generated) 
      *   "Reattribution from XX", where XX is the Entity Name from the original contribution
*   ***NOTE OR MEMO TEXT*** (Optional)

—

***And*** the system will auto-generate a transaction showing amount _reattributed from_ with the following information:

1.  Contact

       #

*   _(Contact will auto-pull from original receipt and user cannot edit it)_

1.  Address

       #

*   _(Address will auto-pull from original receipt and user cannot edit it)_

1.  Receipt Information

       #

*   ***REATTRIBUTION DATE*** (required, auto-generated from "reattributed to" transaction and user cannot edit it)
*   ***MEMO ITEM*** (required, automatically checked by the system and user cannot change it)
*   ***REATTRIBUTED AMOUNT*** (required, auto-generated from "reattributed to" transaction and _made negative_, and user cannot edit it)
*   ***AGGREGATE*** (read-only, will match logic of original transaction)

1.  Additional information

       #

*   ***PURPOSE OF RECEIPT*** (Required, system generated) 
      *   "Reattribution to XX", where XX is the Entity Name from "reattributed to" transaction
*   ***NOTE OR MEMO TEXT*** (Optional)

—

  ***Then*** I will be able to:

*   Cancel
*   Edit
*   Save transactions (users must save both at the same time)

***And*** upon saving:

*   both transactions will be saved as memo items with line numbers matching the original receipt.
*   both will be associated to the original receipt by their back reference IDs.
*   the original transaction will have ***PURPOSE OF RECEIPT*** updated to (Required, system generated) 
      *   "See reattribution below."
*   on the backend: 
      *   Original transaction: REATTRIBUTION REDESIGNATION TAG set to REATTRIBUTED
    *   First transaction above (Reattributed To): REATTRIBUTION REDESIGNATION TAG set to REATTRIBUTION_TO
    *   Second transaction above (Reattributed From): REATTRIBUTION REDESIGNATION TAG set to REATTRIBUTION_FROM

***And*** when the user opens a reattributed transaction, it will take them back to the "Reattribution From/To" entry form.

QA Note 

  Dev Note

*   This functionality should ONLY be for Tier 1 (parent) transactions.
*   This will be a **[specification overlay]([https://docs.google.com/spreadsheets/d/1AbYjbtwZNuB8Y1GHAXMwSzxJW41Pr_3J/edit#gid=1968442852)**](https://docs.google.com/spreadsheets/d/1AbYjbtwZNuB8Y1GHAXMwSzxJW41Pr_3J/edit#gid=1968442852)**), with specifications here replacing those on the original receipt. The remaining specifications will match the original.
*   Original transaction: REATTRIBUTION REDESIGNATION TAG set to REATTRIBUTED
*   First transaction above: REATTRIBUTION REDESIGNATION TAG set to REATTRIBUTION_TO
*   Second transaction above: REATTRIBUTION REDESIGNATION TAG set to REATTRIBUTION_FROM

Wireframes

1.  Select Reattribute
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUoyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d60d7733ff4b725936e7f0cbfdeba2e1bf32704b/171%20-%20Kabob.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUoyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d60d7733ff4b725936e7f0cbfdeba2e1bf32704b/171%20-%20Kabob.png))

1.  Reattribution to
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnNtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f097725a66b5cb28db1662f163e4a899059a7cb9/171%20-%20Reattribution%20to.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnNtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f097725a66b5cb28db1662f163e4a899059a7cb9/171%20-%20Reattribution%20to.png))

1.  Reattribution from
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmRvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cb6f9c6dcafc7fe2735efb650db651de3c525d2/171%20-%20Reattribution%20from.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmRvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cb6f9c6dcafc7fe2735efb650db651de3c525d2/171%20-%20Reattribution%20from.png))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
- [x] BA/Design Quality Checklist complete
- This functionality should ONLY be for Tier 1 (parent) transactions.
- Note for when testing verify under Receipt information section field names are changed to Reattribution Date and Reattributed Amount (Wise)

 See full ticket and images here: [FECFILE-1263](https://fecgov.atlassian.net/browse/FECFILE-1263)

**Comment by AureliaKhorsand** [comment]
**Notes from PI 2 Planning:** 

- Reattribution: Person gives contribution to committee and is too much, wants it back. Committee needs to refund excess OR reattribute to someone else (for example, spouse). Need the original contribution, and then reattribute to another person. Need to show original contribution (memo), another negative value (memo), and third transaction (memo) that shows reattribution to another person.
- Generally happens over reports, so can be up to 4 transactions. If it happens in the last reporting period, then would show as two contributions.
-  Schedule B is refunds given by committee. (There are refunds received by committee in Schedule A).
- Excess is determined by regulation (exceeded threshold), or if the contributor wants it back and asks.

[See reattribution guidance on fec.gov here](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/remedying-excessive-contribution/)

**Comment by JonellaCulmer** [comment]
@AureliaKhorsand Do you mind elaborating on your second bullet point? Having trouble understanding what you mean by up to 4 **_transactions_** and if in the last reporting period, 2 _**contributions**_.

> Generally happens over reports, so can be up to 4 transactions. If it happens in the last reporting period, then would show as two contributions.

cc: @MitchellTCG

**Comment by MitchellTCG** [comment]
@JonellaCulmer & @mary-tcg
Please review these wires for design considerations

THIS DESIGN IS NOT FINAL BECAUSE THE REQUIREMENTS ARE NOT FINAL
I will review after reqs are finalized

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg On the second wireframe, "CONTRIBUTION AMOUNT" should say "REATTRIBUTED AMOUNT" to match the first wire.

**Comment by mary-tcg** [comment]
@AureliaKhorsand @MitchellTCG @GreggMoreland "reattribution from" wire fixed

**Comment by mjtravers** [comment]
Issues came up in CR regarding saving multiple reattributions for a particular transaction and how the TO and FROM transactions are paired in the database. Sending back to In Progress and changing ticket sprint to 35.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting a "Receipt" (Tier 1 - Schedule A) from the "Transactions in this report" table "Reattribute" is an option and displayed under the "Actions" dropdown list. (Note used report JULY 15 QUARTERLY REPORT (Q2) 04/01/2023 — 06/30/2023 for testing)

<img width="1333" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDA1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a8d20200d6f3aa161a1f153ba99f9fac1703747/image.png" alt="image.png" />

Verified "Reattribute" is not an option for a Tier 2 Schedule A transaction.

<img width="1272" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDg1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f16f7c047007607daecd09c901a67b9eaa492ca0/image.png" alt="image.png" />

Verified the "Reattribution" page is displayed.

<img width="1332" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU01QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a5a3ce335cd3d0520887ef370ee4110cf0b761a9/image.png" alt="image.png" />

"Reattribution to" contact lookup for "Individual" displayed.  (CONTACT TYPE- (Required, contact type values matches the original receipt specification)

<img width="1309" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3c1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71aacc9cff1dcac8b40d7a0e1d357d8e1a75a824/image.png" alt="image.png" />

Verified "Reattribution from" contact information is pulled from original receipt.

<img width="1257" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE01QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8a8899a04ca63b5b6cdf37aab1f4b5221528b62/image.png" alt="image.png" />

Verified "Reattribution from" receipt information is read-only.

<img width="912" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG81QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e89147d61818e26ef2023eaeea8921d569f6a6d8/image.png" alt="image.png" />

Verified Original receipt (Robert Smith), Reattribution to (Robert Smith) and Reattribution from (Bogey Bogart) transactions are displayed in the transactions table and the correct associated with are displayed.  (Note: validation to verify all 3 transactions are displayed correctly in the transactions table was not denoted in AC)

<img width="1349" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEk2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--189fca92305843666b102ae683ae9c420cba6671/image.png" alt="image.png" />

Purpose of Receipt should be :  PURPOSE OF RECEIPT (SYSTEM-GENERATED).   Purpose of receipt is showing (OPTIONAL). 

<img width="912" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODQ1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--afa7817e329eba30e389feef6b0d69a3cbf2a846/image.png" alt="image.png" />

@MitchellTCG @mjtravers returning to in-progress to fix PURPOSE OF RECEIPT label.  Purpose of Receipt should be :  PURPOSE OF RECEIPT (SYSTEM-GENERATED).   Purpose of receipt is showing (OPTIONAL).  Fix label

**Comment by toddlees** [comment]
issue found in QA resolved.  moving to CR

**Comment by mjtravers** [comment]
Fix passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified PURPOSE OF RECEIPT label was fixed: PURPOSE OF RECEIPT (SYSTEM-GENERATED). 

<img width="434" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWhOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f1a6c36cdd0f73c55c65c038456917069bca9fc/image.png" alt="image.png" />

QA Review Completed.   Moved to Staqe Ready.
