### ISSUE TITLE
Fix dropdown list in dashboard under "User Profile Icon" for dead links

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1714]
During UX/DEV/QA review the dropdown list in dashboard under "User Profile Icon" for non selectable links (greyed out links) are selectable and display next page. The "Switch Committees" and "User Profile" should be dead links. (Tested on STAGE and DEV)

_______________________________________________________________________________________________________________________

TASKS

*   [x] Make "Switch commiittees" a dead link (currently clickable)
*   [x] Make "User profile" a dead link (currently clickable)

@MitchellTCG @mjtravers Fix dashboard under "User Profile Icon" for dead links. Bug pointed as 3 pts and assigned to Sprint 38.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-489](https://fecgov.atlassian.net/browse/FECFILE-489)

**Comment by MitchellTCG** [comment]
@WiseQA 
Updated

**Comment by mjtravers** [comment]
This was a bug on sprint-37. For CR, review this closed PR: https://github.com/fecgov/fecfile-web-app/pull/1725/files

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the ""Switch Committees" and "User Profile" are dead links under the "Use Profile Icon".  Fix verified and corrected.

<img width="1246" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHRwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--783a4d959b71ed29c92df25a4f406a7ea9122032/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
