### ISSUE TITLE
UPDATE to "System to require users to consent to security notice annually"

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1715]
1.  This is an iterative update to #120

Business Reason

Per FEC Security team guidance, users will be required to consent to a security notice the first time they log in to FECFile Online, then annually after that and the user will have the option to consent to the terms every time they log on OR click the checkbox next to "You consent to the security notification for one year" to hide the notification for 365 days. We should require all users to acknowledge the system use notification the first time they access the application. [Re:"You consent to the security notification for one year" – We should track this acknowledgement. Subsequent displays of the notification should happen at least yearly. We only need to keep a record of the most recent acknowledgement.]

Acceptance Criteria

***When*** a newly provisioned user logs in to FECFile Online (first time login)

  ***And*** they have entered their user profile information (#92) and clicked "Continue"

  ***Then*** the system will display the following message:

  "insert PLACEHOLDER text here. We will updated with approved language closer to go-live"

***And*** they can either:

1\. ***Click "Decline and exit"*** and be sent back to the landing page, and the security notice will appear on the next login attempt or;

  2\. ***Click "Consent"*** (without checking the checkbox) and continue to Committee Account selection page, and the security notice will appear on the next login attempt or;

  3\. ***Click the checkbox*** next to "You consent to the security notification for one year" and then ***Click "Consent"*** and continue to Committee Account selection page, and the security notice ***WILL NOT*** appear for 365 days.

—

***And if*** the user checks the box "You consent to the security notification for one year.", then they will not see the message again for one year (otherwise they see it on each login, and must consent each time).

Dev Notes

*   [ ] Remove require field validation

Wireframes

1.  Unchecked

       

1.  Checked

       

1.  Please REMOVE THIS VALIDATION

       

### QA Notes ###
 

- [x] BA/QA checklist complete
- Will need to work with devs to test the AC for one year time limit

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-488](https://fecgov.atlassian.net/browse/FECFILE-488)

**Comment by MitchellTCG** [comment]
@WiseQA @mjtravers 
please review

@AureliaKhorsand 
I will review this ticket with you

**Comment by WiseQA** [comment]
@MitchellTCG reviewed.   As noted will need to work with DEV if the one year consent is selected then the checkbox "You consent to the security notification for one year" is not displayed.

**Comment by AureliaKhorsand** [comment]
Pulled #120 back top implement in that ticket, this ticket no longer needed and closing as OBE.
