### ISSUE TITLE
Fix Committee Name and Committee ID from displaying on the "Select a committee account" page

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1716]
During UX/DEV/QA review the, when returning to the "Select a committee account" page Committee Name and Committee ID should not be displaying. Remove Committee Name and Committee ID when returning to this page. (Tested on STAGE)

1\. "Select a committee account"

__________________________________________________________________________________

2\. Verify committee account page is displayed. Click on the back arrow, return to the "Select a committee account" page.

____________________________________________________________________________________________________

3\. The committee account name and ID should not be displayed on this page. Page should look like screenshot in step 1\. (This is the fix)

__________________________________________________________________________________________

@MitchellTCG @mjtravers fix committee account name and ID from displaying on the ""Select a committee account" page when selecting the back arrow. Bug pointed as 2 pts and assigned to Sprint 38.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-487](https://fecgov.atlassian.net/browse/FECFILE-487)

**Comment by toddlees** [comment]
@MitchellTCG Very clear that the committee the user picked should not show up at the top as the active committee (that is definitely a bug). Unclear about removing "select a committee account".  Shouldn't going to this page mean that you're selecting your account again?  It's should be the same as if you just logged in.  This behavior will be especially important when we give them a link to this page so they can change what committee they're working on

**Comment by toddlees** [comment]
@MitchellTCG @dheitzer I just did a bad job of reading this ticket.  I thought the ac was suggesting to remove the "select a committee account" label as in, going back to this page doesn't let you select a new committee.  I see now that the ticket is only prescribing the clearing of the current active committee when going back

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting back to the "Select a committee account" page Committee Name and Committee ID should not be displaying. Verified Committee Name and Committee ID when returning to this page was removed.

<img width="1275" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHBwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46d6db46955f1cff54e75ceac82417958ccbe3bc/image.png" alt="image.png" />

QA Review Completed.  Moved to Stage Ready.
