### ISSUE TITLE
Fix the inconsistent routing when selecting the "Decline and Exit" button from the security notification page

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1719]
During QA / DEV review when selecting the "Decline and Exit" button from the security notification page, first time goes to landing page. Then if you login again then select "Decline and Exit" the second time from the security notification page, you are redirected to the login.gov page. (Screenshots below showing issue)

1\. Select "Decline and Exit" button

________________________________________________________________________________________________________________

2\. Landing page is displayed

_______________________________________________________________________________________

3\. Select the "Log into FECfile" button from the landing page, the Security notification page is redisplayed.

______________________________________________________________________________

4\. Select "Decline and Exit" button the second time, takes you to the login.gov page instead of the Landing Page (this is the Fix)

_________________________________________________________________________________

@MitchellTCG @mjtravers Fix the inconsistent routing when selecting the "Decline and Exit" button from the security notification page (reference ticket #120). The routing should take you to the Landing Page. Bug pointed as 3 pts and assigned to Sprint 38.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-486](https://fecgov.atlassian.net/browse/FECFILE-486)

**Comment by WiseQA** [comment]
@MitchellTCG the routing when selecting "Decline and Exit" button should take you to the Landing Page, each time and not the login.gov page ?  Please verify - thanks !

**Comment by mjtravers** [comment]
On hold until log out process is fixed in #1721

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by GreggMoreland** [comment]
@mjtravers I still got the same result as noted in the original defect. first time clicked decline, it went to landing page, then second time clicked decline and it went to Login.gov sign out page

**Comment by MitchellTCG** [comment]
### QA verified the following:
Tested this three times - When the user clicks "Decline and exit" on the security notification page the system NOW  resolves to the "Do you want to sign out of Login.gov and return to FECFile API (Stage)?"

<img width="558" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUdiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae6e50fa669aafcad884898a0559fd98db903645/120%20-%20System%20to%20require%20users%20to%20consent%20to%20security%20notice%20annually%20%E2%80%93%201.png" alt="120 - System to require users to consent to security notice annually – 1.png" />

### QA Review Completed. Moved to Stage Ready.
