### ISSUE TITLE
System to itemize an "Individual Receipt", "Tribal Receipt", "Offsets", and "Other Receipts"  if Contribution Aggregate is >$200

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#172]
Business Reason

Per FECA regulations, certain transactions must be itemized on the Form 3X. That includes Individual, Tribal Receipts, Offsets to Operating Expenditures, and Other Receipts, when the contribution aggregate is over $200.

Acceptance Criteria

***For the following transactions:***

1\. Individual Receipt

  2\. Tribal Receipt 

  3\. Offsets to Operating Expenditures

  4\. Other Receipts

***If*** the Contribution Aggregate amount is >= $200.01

  ***Then*** the transaction will be itemized upon saving

  ***and*** saved with it's own line item on the *.fec file:

*   Individual/Tribal Receipt form type: SA11AI
*   Offsets to Operating Expenditures form type: SA15
*   Other Receipts form type: SA17

***OR***

***If*** the Contribution Aggregate amount is <= $200,

  ***Then*** the transaction will be unitemized upon saving

  ***and*** saved _without_ it's own line item on the *.fec file.

*   Individual/Tribal Receipt form type: SA11AII
*   Offsets to Operating Expenditures form type: SA15
*   Other Receipts form type: SA17

(Note: Unitemized transactions are still included in Summary Page/Detailed Summary Page aggregations.)

DEV NOTES

Users will need to see what is itemized versus unitemized in the UI (front-end #302)

  Account for future functionality of the user being able to itemize/unitemize a transaction, regardless of the transaction amount or built-in logic.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1262](https://fecgov.atlassian.net/browse/FECFILE-1262)

**Comment by MitchellTCG** [comment]
### App#172 FAILED ###
@toddlees 
All transactions Itemized except Other Receipts

We discovered while debugging via screen share that the "Other_Receipts" tag was misspelled.

Todd is fixing and I will retest shortly.

**Comment by toddlees** [comment]
@MitchellTCG patch is up for review https://github.com/fecgov/fecfile-web-api/pull/249

**Comment by mjtravers** [comment]
Fix passes CR, moving to QA

**Comment by MitchellTCG** [comment]
### App#172 Passed ###

#### Individual Receipt ####
- Created Janine Brown with a $199 contribution & Danielle Brown with a $201 contribution
- Only Danielle shows on the .FEC on Line 11
   - SA11AIC00277616C845B5E88F1022E9E332INDBrownDanielle617 S Troy StRoyal OakMI3254620210209201.00201.00University of ArizonaLawyer
___

#### Tribal Receipt ####
- Created Tribal Organization 1 with a $201 contribution & Tribal Organization 2 with a $199 contribution
- Only Tribal Organization 2 shows on the .FEC on Line 11
   - SA11AIC002776169838A88D6C31FF984DE4ORGTribal Organization 112355 Main StDenverCO5682120210222201.00201.00Tribal Receipt 
___
#### Offset to Operating Expeditures ####
##### Individual #####
- Created Sarah Laibstain with a $201 contribution & Kami Hu with a $199 contribution
- Only Sarah Laibstain shows on the .FEC on Line 15
   - SA15C00277616B474A8A0B4D6D6BAC452INDLaibstainSarah227 Windsor Castle DrNewport NewsAZ6658520210211201.00201.00

##### Committee #####
- Created John Kerry for President Inc with a $201 contribution & Bush-Cheneyn'04 with a $199 contribution
- Only John Kerry for President Inc shows on the .FEC on Line 15
   - SA15C00277616B0D8890CAD513DE5B2CACOMJOHN KERRY FOR PRESIDENT INC10 G Street NESuite 710WashingtonDC2000220210211201.00201.00  
##### Organization #####
- Created Offset Organization 1 with a $201 contribution & Offset Organization 2 with a $199 contribution
- Only Offset Organization 2 shows on the .FEC on Line 15
   - SA15C002776160CB183F91B27A0DAD80EORGOffset Organization 1516 South StCvilleVA2290420210223201.00201.00
___
#### Other Receipts ####
##### Individual #####
- Created Faisal Khan with a $201 contribution & Marvis Ferrell with a $199 contribution
- Only Faisal Khan shows on the .FEC on Line 17
   - SA17C00277616A42581C4476BF0957742INDKhanFaisal311 GwathmeyCvilleVA2290220210309201.00201.00Hampton InstitueProfessor

##### Committee #####
- Created Beto for Texas with a $201 contribution & Abbott Laboratories... with a $199 contribution
- Only Beto for Texas shows on the .FEC on Line 17
   - SA17C00277616263B93CEB973F57D01A8COMBETO FOR TEXASPO BOX 3628EL PASOTX7992320210308201.00201.00  
##### Organization #####
- Created Other Organization 1 with a $201 contribution & Other Organization 2 with a $199 contribution
- Only Other Organization 2 shows on the .FEC on Line 17
   - SA17C0027761625C8944E6CDF7BE0F77FORGOther Organization 1513 FirthNeddyNV9518320210323201.00201.00
![Screen Shot 2022-10-17 at 9.18.55 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/da9843bb-0624-4dd8-8b7b-b6ff4f957b30)![Screen Shot 2022-10-17 at 9.18.48 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0e7c9911-060a-4366-a33e-116a558605bb)

![Screen Shot 2022-10-17 at 9.31.18 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/1ae20f34-33ff-45e0-86b0-616a3e013ee7)

![Screen Shot 2022-10-17 at 9.32.16 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/b3de90e3-62b3-4a1d-b861-b7a104b39035)
