### ISSUE TITLE
Fix when selecting Refresh, on the address bar, is redirecting to login screens on cloud.gov servers

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1721]
Fix when selecting Refresh, on the address bar, is redirecting to login screens on cloud.gov servers. (Tested on STAGE)

One example below is:

1\. Select refresh from the address bar on the "Manage reports" page

_________________________________________________________________________________________

2\. The following is displayed (this is the bug)

____________________________________________________________________________________

@mjtravers tested also on STAGE, and when refreshing get's a different login screen.

_________________________________________________________________________________________

@MitchellTCG @mjtravers Fix when selecting Refresh, on the address bar, is redirecting to login screens on cloud.gov servers. Bug pointed as 3 pts and assigned to Sprint 38.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-485](https://fecgov.atlassian.net/browse/FECFILE-485)

**Comment by mjtravers** [comment]
After deploying to DEV, it was found that the logout process is not working as expected. The logout call to the backend is not redirecting properly.

Here is a screenshot of the network call on STAGE that is working:
<img width="1008" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVZvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c489f0267a21dc2e4d527c3344b372a78d343096/image.png" alt="image.png" />

Here is the network on DEV where it is failing:
<img width="1008" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWhvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--137215b65643baa404773da008cdc399f0d30398/image.png" alt="image.png" />

Sending ticket back to In Progress. Putting #120 and #1719 on hold.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers what were the changes for QA to test ?   The redirection was fixed and on DEV ? So this is testable only on Stage ?  Thanks !

**Comment by mjtravers** [comment]
@WiseQA The fix is that now when the page is refreshed by clicking the button on the address bar, the page does not redirect but refreshes the current page. If on the reports list page, it should stay on the reports page. The fix is only on DEV. It will be pushed to STAGE when we deploy the release branch this afternoon.

**Comment by GreggMoreland** [comment]
@mjtravers was this pushed to stage? If it was, I still see this refreshing to the consent page when I'm on the reports page and click on the browser refresh

**Comment by MitchellTCG** [comment]
@mjtravers 
This works if you have selected the 365 consent check box BUT it still doesn't work if you have not.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by mjtravers** [comment]
There was a cookie domain issue that was affecting the logging in and logging out with Login.gov. A patch has been deployed and the functionality was fixed. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified "Bug" fix when selecting Refresh.    Retested "bug" error @MitchellTCG was still finding.

1.  Select "Consent" button 

<img width="1004" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTcyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8ef035c99b86774526ad0168909d3c42973dee5/image.png" alt="image.png" />

__________________________________________________________________________________________________________

2.  Get started now page is displayed.    Select the refresh icon, refresh working correctly.

<img width="1294" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1QyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53a3922688172ad1a33d48674abe3f94bf737e0c/image.png" alt="image.png" />
__________________________________________________________________________________________________________________

Adhoc tested various screens, the refresh is working corretly.

QA Review Completed.    Moved to Stage Ready.
