### ISSUE TITLE
System to include unitemized Form 24 transactions on the *.fec file

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1727]
Business Reason

Any transaction entered on a Form 24 should be shown on the generated Form 24 *.fec file for submission, regardless of if it is itemized or not. This is to be consistent with FECfile Desktop, and confirmed with Ryan via Slack on 2/13/2024.

Acceptance Criteria

***Given*** an itemized _or_ unitemized transaction on a Form 24,

  ***When*** the *.fec file is generated

  ***Then*** _all_ transactions will show, itemized or not.

### QA Notes ###
- [x] BA/Design Quality Checklist complete
- This should be the only exception we have so far of showing unitemized transactions on a *.fec/print preview. 
- Note that as of #1651, users cannot take the action of itemizing/unitemizing within a Form 24. A transaction can only be unitemized if it is unitemized on the Form 3X.

### DEV Notes ###
- This should be the only exception we have so far of showing unitemized transactions on a *.fec/print preview.

### Design ###
null

[FECFILE-483](https://fecgov.atlassian.net/browse/FECFILE-483)

**Comment by Elaine-Krauss-TCG** [comment]
A form 24 transaction with force-unitemized set
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDZnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44f88240d2438638f752c799c12372e15cc037fc/image.png" alt="image.png" />

Is still present in a generated .fec
<img width="1868" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVdnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4852b90b72d4abe958ade7f8d979c8506c80486/image.png" alt="image.png" />

**Comment by toddlees** [comment]
Passes CR moving to QA

**Comment by MitchellTCG** [comment]
On hold until web-app#1550 is complete

**Comment by MitchellTCG** [comment]
### QA review verified the following
**1. Created a print preview of a Form 3X with two IE's, one itemized and one unitemized, as a control**
<br>
#### Form 3X Transaction page displaying 9 transactions with 2 IE's
<img width="938" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzdPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4727b0e00c27b1a79c172eb69e03dff6e70ea06b/Screenshot%202024-03-11%20at%204.30.31%E2%80%AFPM.png" alt="Screenshot 2024-03-11 at 4.30.31 PM.png" />
<br>

#### Web Print displays lots of transactions with only 1 IE and no Line 11AII
<img width="1871" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9PQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9aca70fca4a489f05b384941b6b223259ab2481/Screenshot%202024-03-11%20at%204.41.21%E2%80%AFPM.png" alt="Screenshot 2024-03-11 at 4.41.21 PM.png" />
<br>
<br>

**2. Created a print preview of a Form 24 with two IE's, one that would be itemized on a Form 3x and one that would be unitemized on a Form 3X.**
<br>

#### Form 24 Transaction page displaying 2 transactions with 2 IE's

<img width="1683" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNy9PQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c83a2e6751bb0740e127eaad45a5300a30fce4b/Screenshot%202024-03-11%20at%204.30.54%E2%80%AFPM.png" alt="Screenshot 2024-03-11 at 4.30.54 PM.png" />
<br>

#### Web Print displays 2 transactions with 2 IE's
<img width="1636" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUhPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55e265f12eb413f8dd71687d426e0b804e597424/Screenshot%202024-03-11%20at%204.41.32%E2%80%AFPM.png" alt="Screenshot 2024-03-11 at 4.41.32 PM.png" />

### QA Review Completed. Moved to Stage Ready.
