### ISSUE TITLE
Allow user to manually unitemize a transaction

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#173]
### Business Reason ### 

As a user, I will be able to unitemize any transaction so that I can report efficiently if needed, for example: Separate segregated fund PAC for union or corporation, monthly dues, etc.  Amount they give never goes above $200 threshold, so committee just shows a lump sum instead. Individual donor level never is over $200.

### Acceptance Criteria ### 

**If** a transaction is itemized 
**Then** the user will have the ability to force unitemize that transaction
**And** it will be saved _without_ it's own line item on the *.fec file.

### Dev Notes ###
a check box with itemize this transaction (all caps) 
 
#### Wireframes ####
![591 + 173 Itemized.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/6f305e2c-6b78-44ab-9776-ad2f416c11b7)
![591 + 173 Unitemized.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a64bfb7b-9bd2-431a-9c5f-2852d91e07f1)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @mary-tcg @JonellaCulmer 
Updated

**Comment by AureliaKhorsand** [comment]
Duplicate of #591. Closing as OBE.
