### ISSUE TITLE
Manage session timeout on front-end

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1735]
The front-end needs to keep track of when the back-end session times out or is ended. To do this, we'll set the session expiration date in a cookie that is secondary to the session cookie.

Set up the cookies on the front-end so that:

*   [x] A cookie is set in the back end with the timestamp that the back-end session will end.
*   [x] Keep cookie timestamp value current using Django SESSION_SAVE_EVERY_REQUEST variable.
*   [x] Remove timestamp cookie on log out.
*   [x] Stop sending cookies from the API with the user first name, last name, email, and security consent.
*   [x] Update guards to pull user first name, last name, security consent, etc. from the back-end via a to be created API endpoint.
*   [x] Update all api manifest.yml files to set the SESSION_COOKIE_AGE environment variable to 64800

1.  1.  QA Notes ##

             Test that the provision and security login pages route to the right places depending on the user action.

### QA Notes ###
Set up the cookies on the front-end so that:

- [x] A cookie is set in the back end with the timestamp that the back-end session will end.
- [x] Keep cookie timestamp value current using Django SESSION_SAVE_EVERY_REQUEST variable.
- [x] Remove timestamp cookie on log out.
- [x] Stop sending cookies from the API with the user first name, last name, email, and security consent.
- [x] Update guards to pull user first name, last name, security consent, etc. from the back-end via a to be created API endpoint.
- [x] Update all api manifest.yml files to set the SESSION_COOKIE_AGE environment variable to 64800

## QA Notes ##
Test that the provision and security login pages route to the right places depending on the user action.

### DEV Notes ###
null

### Design ###
null

[FECFILE-481](https://fecgov.atlassian.net/browse/FECFILE-481)

**Comment by mjtravers** [comment]
Unit tests pass:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/3502/workflows/e5b600da-fb07-4960-b93e-2fc09e99f0c1/jobs/10578
![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/e21c1177-9e32-45bc-8dc8-ad185a807960)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified per DEV unit tests passing.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/d43309ef-1dd4-4872-bcf5-6cef06d5eea0)

Per QA notes also Tested that the provision and security login pages route to the right places depending on the user action.

Moved to Stage Ready.
