### ISSUE TITLE
System to hide "unitemized" for transactions on Form 24

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1737]
Business Reason

In a Form 24, transactions will appear on the *.fec whether they are unitemized or not (unlike the Form 3X, for example). To not confuse the user, FEC direction is to _not_ show the word "unitemized" on the transaction table (confirmed with

Acceptance Criteria

***Given*** a Form 24 transaction is unitemized (would occur on the Form 3X)

  ***When*** the user views it from the transaction table

  ***Then*** they will _not_ see the word "unitemized".

### QA Notes ###
- [X] BA/Design Quality Checklist complete
- This does NOT apply to "unaggregated". If a transaction is already unaggregated, it will still show under the transaction name in the transaction table. This ticket is just for "unitemized".
- Note that as of #1651, users cannot take the action of itemizing/unitemizing within a Form 24. A transaction can only be unitemized if it is unitemized on the Form 3X.
- This can be tested by making an IE on a Form 24 for a NEW entity and with an amount less than $200.  The transaction meets the criteria to unitemize (as it will be in any Form 3X) but it will show in the Form 24 without the `unitemized` tag.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-480](https://fecgov.atlassian.net/browse/FECFILE-480)

**Comment by Elaine-Krauss-TCG** [comment]
Since this will be hard to test in the time between disabling the Itemize table action and enabling sharing transactions between F24 and F3X, I've included a screenshot of this working.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDZnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44f88240d2438638f752c799c12372e15cc037fc/image.png" alt="image.png" />


We can see in the above image that the transaction in the table does not have the "Unitemized" even though Force Itemized is set to false (it defaults to undefined, when it's set to "false," the transaction is force-unitemized).

**Comment by toddlees** [comment]
Added way to test on Dev in body of ticket:
>This can be tested by making an IE on a Form 24 for a NEW entity and with an amount less than $200. The transaction meets the criteria to unitemize (as it will be in any Form 3X) but it will show in the Form 24 without the unitemized tag.

**Comment by toddlees** [comment]
passed CR moving to QA

**Comment by MitchellTCG** [comment]
### QA review verified the following
1. I created a $150 Independent expenditure on a Form 3X and an IE over $200. The under $200 appeared as Unitemized on the Transactions in this report page
<img width="1568" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHJPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f1f5e9842f87bcaaf587d8afd51e4f53682f788/Screenshot%202024-03-11%20at%202.20.45%E2%80%AFPM.png" alt="Screenshot 2024-03-11 at 2.20.45 PM.png" />
<br>
2. I created a $150 Independent expenditure on Form 24 and an IE over $200.  Neither transaction appears as Unitemized on the Transactions in this report page.
<img width="1560" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDNPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53a005ca6a85d9d5472f06835f8157197e65ebfd/Screenshot%202024-03-11%20at%202.21.43%E2%80%AFPM.png" alt="Screenshot 2024-03-11 at 2.21.43 PM.png" />
<br>

### QA Review Completed. Moved to Stage Ready.
