### ISSUE TITLE
System to default backdoor code question to "no" on amendment submission pages for any Form 3X or Form 24 amendment

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1739]
Business Reason

System should automatically select and default 'No' to the question 'Do you need to use a backdoor code?' on the "Submit Report' page for an Amendment for a Form 3X or Form 24 report.

Acceptance Criteria

_**Given**_ an amended report (Form 3X or Form 24) _**When**_ the user goes to submit the report _**Then**_ the _option_ to enter a "Backdoor Code" ('Do you need to use a backdoor code?') will show a default 'No' automatically selected.

### QA Notes ###

 
 - [x] BA/Design Quality Checklist complete

### DEV Notes ###

 
 null

### Design ###

**Default State:**

!image-20240612-174702.png|width=75%,alt="image-20240612-174702.png"! [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-479)   

![Image](https://github.com/fecgov/fecfile-web-app/assets/100313668/19a38957-2ed3-4329-88ad-48ac508c7e10)

**When user clicks checkbox:**

!image-20240612-174724.png|width=83.33333333333334%,alt="image-20240612-174724.png"!

![Image](https://github.com/fecgov/fecfile-web-app/assets/100313668/d1ed3960-fc23-4c1c-82d4-f6ebbdbd9432)

[FECFILE-479](https://fecgov.atlassian.net/browse/FECFILE-479)

**Comment by MitchellTCG** [comment]
@JonellaCulmer 
Let's talk about this on Monday

**Comment by MitchellTCG** [comment]
@JonellaCulmer 
Here are the wires to review:


**Initial State**
![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/545cb582-425a-4dc5-b935-4dbca19ef018)

**Selected**
![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/05e5fb99-25cf-4297-99e2-cb675ec8b0e2)

**Comment by JonellaCulmer** [comment]
@MitchellTCG Looks good. Would like to rephase that sentence under "Enter password"

If you **_have_** any questions on how to enroll, confirming your email, two-factor authentication, or your Personal Key, visit FEC.gov for [Electronic Filing Password Assignment System](https://webforms.fec.gov/psa/getstarted.htm) help.

**Comment by mary-tcg** [comment]
@MitchellTCG wires corrected and added to ticket

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG during review of this ticket with QA, the ticket is a UI change, not new functionality.    The following "Checkbox" is working as current design.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/acfd9474-0878-46ee-ab5b-3659acb645f5)

QA Review Completed.   Moved to Stage Ready.
