### ISSUE TITLE
SPIKE - Investigate how to post user feedback to a new GitHub issue

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1745]
See comment below how the feedback is implemented on FEC.

There is a javascript widget on their front end and a REST API endpoint that accepts the feedback and posts it to GitHub using the python github3 package:

[https://github3.readthedocs.io/en/latest/](https://github3.readthedocs.io/en/latest/)

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-477](https://fecgov.atlassian.net/browse/FECFILE-477)

**Comment by lbeaufort** [comment]
@mjtravers I came across this issue. In case it's helpful:

Feedback box is on every fec.gov page, in the lower right hand corner: https://www.fec.gov/

JavaScript: https://github.com/fecgov/fec-cms/blob/ea897966b75f65cdeb2cd3575411745aac3fc3cc/fec/fec/static/js/modules/feedback.js#L22
Python: https://github.com/fecgov/fec-cms/blob/ea897966b75f65cdeb2cd3575411745aac3fc3cc/fec/data/views.py#L991-L1045

Sample issue: https://github.com/fecgov/FEC/issues/13120

**Comment by mjtravers** [comment]
No code to review or QA steps to take. Information needed for this spike is in Laura's comment.

**Comment by WiseQA** [comment]
No QA review needed on this ticket per DEV.

Moved to Stage Ready.
