### ISSUE TITLE
Update vulnerable `gitpython` package for web app

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#1748]
[https://github.com/fecgov/fecfile-web-app/blob/develop/requirements.txt](https://github.com/fecgov/fecfile-web-app/blob/develop/requirements.txt)
[https://security.snyk.io/package/pip/gitpython](https://security.snyk.io/package/pip/gitpython)

Currrently gitpython==3.1.27

Fixed in gitpython@3.1.35

See ticket where this was done already on the back end: [https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/719](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/719)

1.  1.  QA Notes ##

             Passes if tests pass for front end. Screenshot will be provided.

### QA Notes ###
https://security.snyk.io/package/pip/gitpython

Currrently gitpython==3.1.27

Fixed in gitpython@3.1.35

See ticket where this was done already on the back end: https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/719

## QA Notes ##
Passes if tests pass for front end. Screenshot will be provided.

### DEV Notes ###
null

### Design ###
null

[FECFILE-476](https://fecgov.atlassian.net/browse/FECFILE-476)

**Comment by toddlees** [comment]
passes CR moving to QA

**Comment by toddlees** [comment]
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/5127/workflows/e27d7c13-ff0d-4a7d-93aa-d38fe24e9672/jobs/17962
QA Notes: No visual changes in the UI. 
unit tests passing: 
<img width="1596" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODY2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a911611400e9d24b8fe678fcc7297d2957619896/image.png" alt="image.png" />

**Comment by MitchellTCG** [comment]
### QA verified screenshot from Todd

### QA Review Completed
