### ISSUE TITLE
Update Snyk checking on front end to include requirements.txt

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1749]
Currently, the Snyk dependency checker is only scanning the Angular package.json file.

  This process in CircleCI needs to be expanded to check the front end requirements.txt file as well.

File location fecfile-web-app/requirements.txt

Here's the code snippet in CircleCI's config.yml:

1.  1.  QA Notes ##

             CircleCI successfully runs the Snyk process. Screenshot will be provided. 
            1.  QA Notes ###

                   This process in CircleCI needs to be expanded to check the front end requirements.txt file as well.

File location fecfile-web-app/requirements.txt

Here's the code snippet in CircleCI's config.yml:

1.  1.  QA Notes ##

             CircleCI successfully runs the Snyk process. Screenshot will be provided. 
            1.  DEV Notes ###

                   null
        2.  Design ###

                   null

### QA Notes ###
 
 This process in CircleCI needs to be expanded to check the front end requirements.txt file as well.

File location fecfile-web-app/requirements.txt

Here's the code snippet in CircleCI's config.yml:

## QA Notes ##
CircleCI successfully runs the Snyk process. Screenshot will be provided.

### DEV Notes ###
 
 null

### Design ###
 
 null

[FECFILE-475](https://fecgov.atlassian.net/browse/FECFILE-475)

**Comment by sasha-dresden** [comment]
New snyk python step added to circle config. Shown passing here:



![Image](https://github.com/fecgov/fecfile-web-app/assets/149604256/c2530d94-90bf-48ed-b2ca-dbef202df192)

**Comment by WiseQA** [comment]
QA review verified with DEV the new snyk python step added to circle config.   Unit test passes.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/b827f661-de19-462f-8650-b3b05bf22110)

QA Review Completed.  Moved to Stage Ready.
