### ISSUE TITLE
Remove Save and Add More button on Edit Contact Modal

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#175]
### Business Reason ###
As a Committee Administrator, I will be able to edit an existing contact BUT I do not need to Save and Add More entries while editing.

### Acceptance Criteria ###
If I am a Committee Administrator 
When I access my committee's contact list 
 Then I will be able to EDIT and SAVE any of that contact's data except Type

### Task ###
1. Remove "Save & Add More" button from modal

Dev Tasks:
	1	refactor old code
	2	unit tests
	3	documentation
	4	logging in the back-end
	5	accessible in the UI

**Comment by mjtravers** [comment]
@MitchellTCG Okay for me to close this ticket now that app #184, #185, #186, #187 are in the Sprint Backlog?
