### ISSUE TITLE
BUG: Update spelling of FECFile on the 'Get started now' page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1754]
***Found by @JonellaCulmer***

User Story:

  As the UX stakeholder, I would like the word "FECFile" spelled correctly on the application.

Update text:

1.  Currently:

       LOOKING FOR AN EXISTING ***FEFILE*** COMMITTEE ACCOUNT?

       Contact the administrator for that committee.

1.  Correct verbiage

       LOOKING FOR AN EXISTING FECFILE COMMITTEE ACCOUNT?

       Contact the administrator for that committee.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-474](https://fecgov.atlassian.net/browse/FECFILE-474)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @JonellaCulmer is it "FECFile" or "FECfile"?

**Comment by mjtravers** [comment]
From CR: I noticed  that there are lines altered by changing around the order of HTML tags. This get problematic when it is widespread and affects a large number of files and lines. Is there a way to turn this off in your IDE?

Sending back to In Progess to correct html tag changes.

**Comment by mjtravers** [comment]
Requested changes were made. Passes CR.

**Comment by MitchellTCG** [comment]
### QA verified the following:
The update was made per image below
<img width="512" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0cvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d836514f273d57dad04c43cf0b5e3fbbc7ee8bd9/unnamed.png" alt="unnamed.png" />
### QA Review Completed. Moved to Stage Ready.
