### ISSUE TITLE
Implement Feedback Box Functionality

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1755]
Business Reason

As a Alpha Tester of FECFile, I would like a way to provide Feedback on the application so that I can report any defects, bugs, or peculiarities found while testing

Acceptance Criteria

***Given*** the user is on any page in the FECFile Online application _following a successful login_,

  ***When*** they click on the 'Feedback' button

  ***Then*** a popup will be displayed where they can enter:

*   WHAT WERE YOU TRYING TO DO ON FECFILE ONLINE, AND HOW CAN WE IMPROVE IT? (Required)
*   GENERAL WEBSITE FEEDBACK
*   TELL US ABOUT YOURSELF

***And when*** they enter data and click 'Post'

*   the feedback entered will be captured in GitHub
*   they will have the option to "Submit more feedback" which takes them to a cleared form, or close

***OR when*** they click on the collapse icon, the feedback box will close (any data entered will be lost).

***And*** if any errors are returned from GitHub

  ***Then*** the screen will display 'Try Again' button so the user can return to the form to try again.

Dev Notes

*   [ ] Create a Feedback button the overlays the app (99 z-index)
*   [ ] Display a modal that will capture the feedback in a private GitHub repository 0
*   [X] Create Github repository [https://github.com/fecgov/fecfile-feedback](https://github.com/fecgov/fecfile-feedback)
*   [ ] in Github issue, include Details section to include URL and browser, as shown in Laura's ticket:
    [https://github.com/fecgov/fecfile-web-app/issues/1745](https://github.com/fecgov/fecfile-web-app/issues/1745)
*   [ ] Allow for 2000 characters in each section, characters entered will be the same that are defined in the e-filing specifications

the api will need to create tickets as a user that is added to the private repo

1.  Source code

       Feedback box is on every fec.gov page, in the lower right hand corner: [https://www.fec.gov/](https://www.fec.gov/)

JavaScript: [https://github.com/fecgov/fec-cms/blob/ea897966b75f65cdeb2cd3575411745aac3fc3cc/fec/fec/static/js/modules/feedback.js#L22](https://github.com/fecgov/fec-cms/blob/ea897966b75f65cdeb2cd3575411745aac3fc3cc/fec/fec/static/js/modules/feedback.js#L22)

  CSS (including for animation): [https://github.com/fecgov/fec-cms/blob/ea897966b75f65cdeb2cd3575411745aac3fc3cc/fec/fec/static/scss/components/_feedback.scss](https://github.com/fecgov/fec-cms/blob/ea897966b75f65cdeb2cd3575411745aac3fc3cc/fec/fec/static/scss/components/_feedback.scss)

  Python: [https://github.com/fecgov/fec-cms/blob/ea897966b75f65cdeb2cd3575411745aac3fc3cc/fec/data/views.py#L991-L1045](https://github.com/fecgov/fec-cms/blob/ea897966b75f65cdeb2cd3575411745aac3fc3cc/fec/data/views.py#L991-L1045)

Wireframes

1.  Button

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/a05ee8eb-572e-4c93-85dc-ffabe5939287](https://github.com/fecgov/fecfile-web-app/assets/110493670/a05ee8eb-572e-4c93-85dc-ffabe593928))

1.  Overlay

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/cbdd7998-2011-47f0-b838-3ff945369874](https://github.com/fecgov/fecfile-web-app/assets/25588182/cbdd7998-2011-47f0-b838-3ff94536987))

1.  Success

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/78810e02-8895-4cdd-bf72-7f96e9af3583](https://github.com/fecgov/fecfile-web-app/assets/110493670/78810e02-8895-4cdd-bf72-7f96e9af358))

1.  Error

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/2c9420a8-ff0f-43e5-9a58-f2c9b0cc7f8d](https://github.com/fecgov/fecfile-web-app/assets/110493670/2c9420a8-ff0f-43e5-9a58-f2c9b0cc7f8))

Video
[https://github.com/fecgov/fecfile-web-app/assets/110493670/0068370a-a218-4a46-ab65-063fdd69a801](https://github.com/fecgov/fecfile-web-app/assets/110493670/0068370a-a218-4a46-ab65-063fdd69a801)

/

### QA Notes ###

- [ ] BA/Design Quality Checklist complete
- Feedback box only shows after login. It will NOT appear on the FECFile landing page, but will appear on security consent, committee selection, etc.

 

### DEV Notes ###
null

### Design ###
null

[FECFILE-473](https://fecgov.atlassian.net/browse/FECFILE-473)

**Comment by MitchellTCG** [comment]
@mjtravers please make sure that this ticket has the info for connecting Github to the modal:https://github.com/fecgov/fecfile-web-app/issues/1745

**Comment by MitchellTCG** [comment]
@JonellaCulmer @AureliaKhorsand 
Please review

**Comment by MitchellTCG** [comment]
@GreggMoreland 
please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG does collapsing the modal/pop up delete ay data they have entered? Or are we expected to preserve it as they navigate the site?

**Comment by MitchellTCG** [comment]
Since I am expecting the text to be cleared when the user clicks post, then also clear the data when the modal is minimized.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG some more questions: What are the character limits for the boxes? Assuming all characters that we allow in the system are also allowed here? I'm guessing passing the CAPTCHA will be required for clicking "post"? Are there links you can provide for the two hyperlinks above the captcha?

**Comment by MitchellTCG** [comment]
1. Let's say 2000 Characters
2. All the same characters
3. Jonella says it is a Passive reCAPTCHA
4. "Use of reCAPTCHA": https://www.fec.gov/use-recaptcha/
5. "Contact the FEC about a specific question": https://www.fec.gov/contact/

**Comment by JonellaCulmer** [comment]
@MitchellTCG 

Options for reCaptcha:
https://developers.google.com/recaptcha/docs/v3 (Passive)
https://developers.google.com/recaptcha/docs/display (Checkbox)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG please remove anything to do with reCAPTCHA from the wireframes for this ticket. Also, what kind of error messages do you expect to receive, or is that something we should confer with dev on? If there is an error,  does "Try Again" immediately submit, or bring them back to the feedback form they were editing?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
1. regarding reCAPTCHA, I updated the wireframe not to have it
2. The error may be that GitHub does not respond or throws an error. Also, when the user clicks try again, they will be returned to the previously populated form.

**Comment by MitchellTCG** [comment]
I marked this as HIGH PRIORITY and moved it into Sprint 40 since it was originally slated for a Sprint 40 release.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG given that it is in progress and in sprint 40, is there a reason it's marked as high priority over the other tickets for test release 1 in sprint 40?

**Comment by AureliaKhorsand** [comment]
@dheitzer updated ACs to clarify that this does not include the landing page pre-login. Let me know if it needs anything else!

**Comment by dheitzer** [comment]
@MitchellTCG @mary-tcg do you have a .svg for the custom close icon?

**Comment by dheitzer** [comment]
@AureliaKhorsand @MitchellTCG the ACs for these two headings don't seem to match the wireframe (specifically the parens text).  Can you clarify which one to follow?

- GENERAL WEBSITE FEEDBACK (Optional)

- TELL US ABOUT YOURSELF (Optional)

Also, should the teal buttons have black text like like in the wireframe? our info buttons of this color have white text in other places.

**Comment by GreggMoreland** [comment]
@dheitzer "Optional" was mentioned not as a display label, but as a note for testing to see that field as Optional. I've removed it here, but if it comes up again in QA, I will add it back.

**Comment by WiseQA** [comment]
@MitchellTCG @AureliaKhorsand I thought we added the verbiage "(Optional)" to the field names that were applicable and optional ?  Just clarifying which is correct ?   @dheitzer I see your original question to Mitchell and Aurelia regarding the teal buttons and text color.   Thanks !

**Comment by MitchellTCG** [comment]
> [@MitchellTCG](https://github.com/MitchellTCG) [@AureliaKhorsand](https://github.com/AureliaKhorsand) I thought we added the verbiage "(Optional)" to the field names that were applicable and optional ? Just clarifying which is correct ? [@dheitzer](https://github.com/dheitzer) I see your original question to Mitchell and Aurelia regarding the teal buttons and text color. Thanks !

fair comment on the optional/required

I'll touch base with Jonella and discuss

**Comment by MitchellTCG** [comment]
Talked to Jonella. Please leave it as is. (Leave Required).

**Comment by WiseQA** [comment]
@mjtravers @dheitzer @MitchellTCG why was this moved back from CR to In-Progress ?   Just like to know what fixes being made for testing ?   Thanks

**Comment by MitchellTCG** [comment]
@WiseQA I was moved back to in progress because parts of the design didn't match the wires. I updated one wire, but no changes were made that should affect testing.

**Comment by dheitzer** [comment]
changes have been made to use p-overlaypanel instead of p-dialog for the needed effect.  This is back in code review now.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by MitchellTCG** [comment]
@dheitzer @WiseQA 
**PLEASE MAKE THE FOLLOWING FIXES:**

1. Remove the Circle hover-over state on the Down arrow in the upper right-hand corner of the Feedback box. Either make the arrow white on hover or have no visual change (but keep the pointer finger cue).

2. The border radius is currently 4px all the way around. Please change to:  **border-radius: 4px 4px 0px 0px;**

**Comment by WiseQA** [comment]
@MitchellTCG @dheitzer please clarify what border radius needs changed on the screen please - thanks

**Comment by dheitzer** [comment]
met with @MitchellTCG and he clarified it's just the feedback button. 
Thanks David !

**Comment by mjtravers** [comment]
Changes made to the buttons of feedback. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the Feedback Box functionality.

Verified "Feedback" button is not located on the landing page.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/374f621c-6a6d-4010-aab6-6e2f0cd10a2b)

_____________________________________________________________________________________________________________

Verified "Feedback" button is located on every page starting with the "Security notification" page.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/8a5011fb-35cf-4488-9028-707e704892f7)

_____________________________________________________________________________________________________________

Select "Feedback" button the "Post feedback about FECFile anonymously" popup window is displayed.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/cf146f22-6686-42b5-851e-bedd5daa0c68)

_____________________________________________________________________________________________________________

Verified "What are you trying to do . . . " text box is a required field.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/d8ccabed-c16c-4f2c-8b30-79e5f31e6a3f)

_____________________________________________________________________________________________________________

Entered text in required field then select the "Post" Button.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/cbacebd5-1a32-472f-b8e6-82ad5c3794ae)

_____________________________________________________________________________________________________________

Verified "Thanks for helping us improve FECFile" popup window is displayed.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/755a3957-71ad-45f2-9f0c-29a07fed99a1)

_________________________________________________________________________________________________________

Verified the Circle hover-over state on the Down arrow in the upper right-hand corner of the Feedback box was removed. Either make the arrow white on hover or have no visual change (but keep the pointer finger cue).

Select the down arrow to close the feedback popup window.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/ec3602c9-fba2-45f2-a800-ae82ff81a195)

______________________________________________________________________________________________________________

Verified "Ooops ..." popup window is displayed (Note to test turn off wifi and non accessibility will populate this error.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/424e6fcf-53c3-451b-acf0-956eab

**Comment by WiseQA** [comment]
QA verified the links at the bottom of the FEEDBACK popup screen were correct and working.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/9dc8a1ed-da10-4867-8aac-7f2d2ee07d1b)

_____________________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/7ea9b9b6-7e61-4911-9ce8-0cb93ff81d74)

____________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/0dfeacd7-cf75-4e38-ab00-03af5f5bc775)

____________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/bfec4610-2f7c-485d-8625-275929fdc1f2)

**Comment by WiseQA** [comment]
QA Review Completed.   Moved to Stage Ready.
