### ISSUE TITLE
Schedule E transactions will be shared between Form 3X and Form 24

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1760]
Business Reason

Any Form 24 transaction _must_ be saved on a Form 3X, and they must remain in-sync. Thus, they will be the same transaction.

Acceptance Criteria

***Given*** a user saving a transaction on a Form 24,

  ***When*** the user successfully saves the transaction, it will also appear on the Form 3X selected,

  ***And*** any updates made to the transaction will be reflected in both reports it is present in.

### QA Notes ###
- [ ] BA/Design Quality Checklist complete

### DEV Notes ###
- The system will maintain a single copy of the Schedule E transaction so that when it might be edited in either the Form 3X report or the Form 24 report, it will show the updates in both reports.

### Design ###
null

 See full ticket and images here: [FECFILE-472](https://fecgov.atlassian.net/browse/FECFILE-472)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Schedule E transactions are visible and displayed between the Form 3x and Form 24.  (Tested using Independent Expenditure).  

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/1d1f3031-a183-4ee6-af7e-9fb8df7e4d17)

___________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/29c8e1fc-1562-4515-9e8b-9d7e4a8bd43a)
_______________________________________________________________________________________________________________________

Verified when editing the Schedule E Transaction (Independent Expenditure) and saving the change.   The transaction is updated for both the Form 3x and Form 24. 

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/90b97c1f-1f75-4f39-a9fc-89bbe03b1140)

_______________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/8d8c9fb7-dbb5-4454-a750-568484de1524)
______________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
