### ISSUE TITLE
UI Update: Add show/hide feature and icon to the PASSWORD field on report submission

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1766]
User Story:

  As a UX specialist, I would like the show/hide feature added to the electronic filing password box on the "Submit report" page to match users traditional expectation for password fields.

Acceptance Criteria

***Given*** the 'Submit report' page

  ***When*** the user enters the Electronic Filing Password

  ***Then*** the password will default to _hidden_

  ***And*** they are able to click on the 'show password' eyeball 

  ***Then*** the password will be visible

  ***And then*** they are able to click the 'show password' eyeball again

  ***And*** the password will not be visible

Dev Notes

*   [ ] Add Show/hide feature on the electronic filing password box on the "Submit report" page.
*   [ ] Use the icons being used on the password field on the landing page of DEV

The feature should look and work exactly like it does in the password field on the landing page of DEV

Reference

1.  The SHOW icon should look like:

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/9cf4bb7f-5af9-4604-bb91-1c5e532a579d](https://github.com/fecgov/fecfile-web-app/assets/94924171/9cf4bb7f-5af9-4604-bb91-1c5e532a579))

1.  The HIDE icon should look like:

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/275749df-11d6-4c05-b6b1-2bd7bc95add9](https://github.com/fecgov/fecfile-web-app/assets/94924171/275749df-11d6-4c05-b6b1-2bd7bc95add))

### QA Notes ###

- [ ] BA/Design Quality Checklist complete

### DEV Notes ###
null

### Design ###
null

[FECFILE-471](https://fecgov.atlassian.net/browse/FECFILE-471)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG I am assuming it should default to hidden, so I have updated the ACs.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified on the "Submit Report" page the Electronic Filing Password field is defaulted to "hidden" text.

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/20fb9792-a6e8-4dd2-b3d7-f59d64cb4870)

______________________________________________________________________________________________________________________

Verified when selecting the "show icon" the password is displayed correctly.

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/ba3304ba-dd66-4d16-a41e-e529d1fdf931)



_________________________________________________________________________________________________________________

QA Review Completed.    Moved to Stage Ready.
