### ISSUE TITLE
UI - Update text on Landing Page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1776]
User Story:

1.  1.  As the UX specialist, I would like to update the verbiage to convey filers can create, review and submit report on not just a desktop.

Tasks:

*   [x] Change headline from  'Made for filers Built for productivity'  to ***Made for filers Built to work anywhere***

       

*   [x] Change headline from  'FECFile is a FREE Web-based software system that committees can use for electronic filing. and the Electronic Filing Office is available to answer filers' questions about the system.'  to  ***FECFile is free web-based software filers can use for electronic filing. You and your team can create, review and submit your reports from anywhere.***

       

Wireframe

1.  1.  Current page

             ![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/2e032f45-7be6-435d-a675-326a05f90eb8](https://github.com/fecgov/fecfile-web-app/assets/110493670/2e032f45-7be6-435d-a675-326a05f90eb))

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### Design ###
![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/5d89f0ca-cb09-4076-8361-89e02a8d71b0)

[FECFILE-468](https://fecgov.atlassian.net/browse/FECFILE-468)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Please review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified text on Landing Page has been updated.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/b4f2fc3f-7949-44d1-a04f-52bbefc0e4ef)

QA Review Completed.  Moved to Stage Ready.
