### ISSUE TITLE
Remove "Online" from the FECFile Online displayed in the blue navigation bar

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1777]
Business Reason

As a user, I will be able to only see FECfile in the blue navigation bar that displays my report progress so that I can see it displayed without the 'Online'

Acceptance Criteria

***Given*** a user viewing 'Transactions in this report' or Add new transaction

  ***When*** the left blue navigation bar is displayed

  ***Then*** it shows 'FECfile' , followed by FEDERAL ELECTION COMMISSION

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
- remove the word 'Online' from the 'FECfile Online' displayed in the blue navigation box on the left.
![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/fd7d537d-e809-4e88-9c7f-8806abee36db)

### Design ###
null

[FECFILE-467](https://fecgov.atlassian.net/browse/FECFILE-467)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
It looks good to me. Please review and move to ADQTR

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "Online" has been removed from the left NAV bar.   Reads "FECFile" only.

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/d53658b9-379d-44fe-97c7-4da174cd0d61)



QA Review Completed.   Moved to Stage Ready.
