### ISSUE TITLE
UI: Correct headers on Single Transaction pages

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1778]
User Story:

1.  As the UX Specialist, the section headers on transaction pages should be H2s as to correctly represent the level of importance of each section.

Tasks

Make sure the section headers are H2s for ALL single transactions.

Wireframes

1.  1.  Current (individual receipt)

             ![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/adf86a7d-5a4c-4b28-840f-df8d72341baf](https://github.com/fecgov/fecfile-web-app/assets/110493670/adf86a7d-5a4c-4b28-840f-df8d72341ba))

1.  1.  Updated

             ![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/fda792d9-9d09-480f-98ab-52ce4ac88ca4](https://github.com/fecgov/fecfile-web-app/assets/110493670/fda792d9-9d09-480f-98ab-52ce4ac88ca))

### QA Notes ###
- [x] BA review completed

### DEV Notes ###
- [ ] Only update single transactions NOT Double or Triple
- [ ] The need of this ticket is for h1 -> h2 -> h3 hierarchy to be followed for 508.  The DOM element for say Address is defined as an h3.  The trickiness is that while that's correct in a double or triple transaction (transaction title is h2 and "Contact" label is h3), in a single transaction, everything is shifted up a level so the transaction title is h1, the "Contact" label is an h2.  So in a single transaction, all the section labels are a step lower than they should be.  We can solve this by letting the transaction form component know which context it's in (am I inserted starting at h2 or h3?) and having it render these labels conditionally.
Sections that are hardcoded as h3:

- Address
- Employer
- Receipt information (called "Expenditure information" in Bs and IEs, "Guaranteed financial information" in C2s)
- Debt or obligation information (only Ds)
- Loan information (Cs different element than the one in C1s)
- Terms (only Cs)
- Loan information (C1s different element than the one in Cs)
- Additional information ( everything but C1 and C2)
- Committee treasurer (C1 and IEs)
- Authorized representative (C1 only)
- Committee/Candidate information ( in-kind Candidate or Other Committee,  called "Candidate information" in IEs)

### Design ###
null

[FECFILE-466](https://fecgov.atlassian.net/browse/FECFILE-466)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Please Review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG is this something that can be done for more transactions than just these at the same time?

**Comment by toddlees** [comment]
The need of this ticket is for h1 -> h2 -> h3 hierarchy to be followed for 508.  The DOM element for say Address is defined as an h3.  The trickiness is that while that's correct in a double or triple transaction (transaction title is h2 and "Contact" label is h3), in a single transaction, everything is shifted up a level so the transaction title is h1, the "Contact" label is an h2.  So in a single transaction, all the section labels are a step lower than they should be.  We can solve this by letting the transaction form component know which context it's in (am I inserted starting at h2 or h3?) and having it render these labels conditionally.
Sections that are hardcoded as h3:

- Address
- Employer
- Receipt information (called "Expenditure information" in Bs and IEs, "Guaranteed financial information" in C2s)
- Debt or obligation information (only Ds)
- Loan information (Cs different element than the one in C1s)
- Terms (only Cs)
- Loan information (C1s different element than the one in Cs)
- Additional information ( everything but C1 and C2)
- Committee treasurer (C1 and IEs)
- Authorized representative (C1 only)
- Committee/Candidate information ( in-kind Candidate or Other Committee,  called "Candidate information" in IEs)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the following headers listed in AC have been changed to  h1 -> h2 -> h3 hierarchy:

- Address
- Employer
- Receipt information (called "Expenditure information" in Bs and IEs, "Guaranteed financial information" in C2s)
- Debt or obligation information (only Ds)
- Loan information (Cs different element than the one in C1s)
- Terms (only Cs)
- Loan information (C1s different element than the one in Cs)
- Additional information ( everything but C1 and C2)
- Committee treasurer (C1 and IEs)
- Authorized representative (C1 only)

@MitchellTCG might want to double check if you want, but QA review is completed.
_________________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/99b63919-7df0-4a15-9aa0-5d8cdfc977cb)

_____________________________________________________________________________________________________________________________


![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/5693b75b-1b2a-4a5c-b256-13a57ba78f5f)

QA Review Completed.   Moved to Stage Ready.
