### ISSUE TITLE
UI: Update the Contact Type section on Transactions and add magnifying glass

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1780]
User Story

As Lead UX, I would like the contact type section to look like the wireframes

Acceptance Criteria

*   [ ] Update all border to be the following hexcode: #AEB0B5

*   [ ] Fix the border-radius for the Contact title

       change from:

       border-radius: 4px

       change to: 

       border-radius: 4px 0 0 4px;

*   [ ] Fix right side of contact type box

       border-radius: 4px

       change to: 

       border-radius: 0 4px 4px 0;

*   [ ] Add a magnifying glass at the right side of the contact type text box

       The MAGNIFYING GLASS icon should be 20px by 20px

*   [ ] Update the plus next to "Create a new contact"

       The PLUS icon it should be 20px by 20px and color: #112E51

Validate changes using the following transactions:

*   [ ] ***Individual Receipt (Schedule A, Receipts)***
*   [ ] ***Contribution from Registered Committee (Schedule A, Receipts)***
*   [ ] ***Operating Expenditure (Schedule B, Disbursements)***
*   [ ] ***Contribution to Candidate Committee (Schedule B, Disbursements)***

Wireframe

1.  1.  Change from:

             ![Screenshot 2023-03-26 at 8.38.57 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4a7d41f1-896b-4d4f-8458-49b863112ee3](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4a7d41f1-896b-4d4f-8458-49b863112ee3))

1.  1.  Change to:

             

_(Arrow only if applicable)_

Assets

1.  1.  Grey Loupe (Magnifying glass)

             

             

1.  1.  Plus Icon

             

             

1.  1.  Down Arrow

             

### QA Notes ###

- [x] BA/Design Quality Checklist complete

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-464](https://fecgov.atlassian.net/browse/FECFILE-464)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Wires updated, and assets added
Please review

**Comment by MitchellTCG** [comment]
I'm placing on Hold. I will OBE it if necessary.

**Comment by MitchellTCG** [comment]
OBE
create accidentially
