### ISSUE TITLE
UI: Add Padding to the Transactions pages

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1781]
User Story:

  As the UX Specialist, the transaction page can have 32px of padding on the left and right of transaction pages

Tasks

Make sure the both sides of the transaction area have 32pixels of space on the Transaction pages.

Wireframes

1.  1.  Current (Individual receipts)

             ![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/6164e06e-61ce-4e45-b285-59147c252b97](https://github.com/fecgov/fecfile-web-app/assets/110493670/6164e06e-61ce-4e45-b285-59147c252b9))

1.  1.  Updated

             ![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/3c2f14a4-64a3-4335-a0bd-601347766cc4](https://github.com/fecgov/fecfile-web-app/assets/110493670/3c2f14a4-64a3-4335-a0bd-601347766cc))

_***Only worry about header updates and no other design changes***_/

### QA Notes ###
- [X]  BA/UX Review Completed
- [ ]  Please check the following transactions first:
- Individual Receipt
- PAC Receipt
- Operating Expenditure
- Contribution to Candidate
- [ ] Spot check at least 4 other single transactions

### DEV Notes ###
Update for **ALL** transaction types
- [x] Single transactions
- [x] Double transactions (e.g. Earmark)
- [x] Triple transactions (e.g. Loan received from bank)

### Design ###
null

[FECFILE-451](https://fecgov.atlassian.net/browse/FECFILE-451)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG will this have to be transaction by transaction, or is it something we can fix and fix other transactions at the same time?

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
Here is a screenshot of a transaction page showing the 32px margins on the left and right of the content of the main page.


![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/7e1fe1e0-e6a6-4884-8a86-ecd2174b6bc2)

**Comment by WiseQA** [comment]
QA review verified with DEV (see screenshot above) transaction page showing the 32px margins on the left and right of the content of the main page.

Verified per UX Individual Receipt; PAC Receipt; Operating Expenditure; Contribution to Candidate.  Adhoc tested several other transactions.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/3a7954df-ae75-4375-ba64-aa928915083d)

____________________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/3a1bac08-3fa9-40fe-b280-9e913e97439d)

____________________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/cfc32ee8-25c7-4603-b3c4-c6023b4e536a)

_________________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/521aa45f-3f40-4b17-8aae-1a372cd6ac9f)


QA Review Completed.   Moved to Stage Ready
