### ISSUE TITLE
Report status confirmation page should use Karla font

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1784]
Business Reason

Task: Currently, the Report status page uses Ghandi in the form. This needs to be changed to use Karla

Acceptance Criteria

***Given*** a Form 3x report that has all the information

  ***When*** I click "Submit" on the "Submit report" page

  ***Then*** I will see the "Report status" page with the updated font (Karla)

1.  1.  This is how it looks

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/6e244bb1-9a24-4ad3-8397-5ac727f76940](https://github.com/fecgov/fecfile-web-app/assets/94924171/6e244bb1-9a24-4ad3-8397-5ac727f7694))

1.  1.  This is how it SHOULD look

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/3093df2f-47ff-467d-918d-212283b7eca9](https://github.com/fecgov/fecfile-web-app/assets/94924171/3093df2f-47ff-467d-918d-212283b7eca))

### QA Notes ###
- [x] BA/Design Quality Checklist complete
- [ ] Don't worry about how the H1 is displayed, only worry about the font on the list to the left of the picture

### DEV Notes ###
 Wireframe

### Design ###
null

[FECFILE-449](https://fecgov.atlassian.net/browse/FECFILE-449)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Please review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Report status confirmation page font changed to Karla.

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/bf15ae08-ad59-4a1a-831e-200a2b0c28e9)

QA Review Completed.   Moved to Stage Ready.
