### ISSUE TITLE
System to display 'No data available in table' when a UI table is empty

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1786]
Business Reason

Task: on all UI tables, if the table is empty, then display text: "No data available in table"

Acceptance Criteria

***Given*** Manage Reports Page

  ***When*** there are no reports to display

  ***Then*** display the text below the column headings, "No data available in table"

***Given*** Manage transactions Page

  ***When*** there are no transactions for a type of transaction (i.e. Receipts, Disbursements, Loans and Debts)

  ***Then*** display the text below the column headings for the blank table, "No data available in table"

***Given*** Manage Contacts Page

  ***When*** there are no contacts to display

  ***Then*** display the text below the column headings, "No data available in table"

Wireframes

1.  1.  Contacts

             ![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/a6ff576c-71c5-4efb-be92-8bb9cc5d3832](https://github.com/fecgov/fecfile-web-app/assets/94924171/a6ff576c-71c5-4efb-be92-8bb9cc5d383))

1.  1.  Reports

             ![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/b790a754-0205-4f1e-a744-56ab68a7e388](https://github.com/fecgov/fecfile-web-app/assets/94924171/b790a754-0205-4f1e-a744-56ab68a7e38))

1.  1.  Transactions

             ![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/d82b8ee3-8d7b-4ddb-859b-00104285becc](https://github.com/fecgov/fecfile-web-app/assets/94924171/d82b8ee3-8d7b-4ddb-859b-00104285bec))

### QA Notes ###
- [X] BA/Design Quality Checklist complete

### DEV Notes ###
Primeng provides an empty message api.  we might be able to use that: https://primeng.org/table#api.table.templates.emptymessage
FIx in the following places:
- [ ] Manage Reports
- [ ] Manage Contacts
- [ ] Manage Transacations in this report
- [ ]

### Design ###
null

[FECFILE-463](https://fecgov.atlassian.net/browse/FECFILE-463)

**Comment by GreggMoreland** [comment]
@MitchellTCG please add wires

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Updates complete

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG need a new blank Committee Account to test the "No data available in table".  After talking with Matt we will do a visual and walk through a blank committee account to test this fix.

**Comment by mjtravers** [comment]
@WiseQA  Here are screenshots of message in empty tables:


![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/3551be73-859c-4296-a261-fa42b241433f)



![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/d2f914b3-c41d-4c3b-8378-1e5f3139831f)




![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/5fc59446-cc21-4115-b2dc-6c868f9be5d9)

**Comment by WiseQA** [comment]
QA review verified "No data available in table"  when a UI table is empty.   This was tested with DEV (see screenshots above)

QA Review Completed.   Moved to Stage Ready.
