### ISSUE TITLE
UI: Fix off-center loading overlay on print preview page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1787]
User Story

  As the UX Lead, I would like the loading overlay to be centered in the Compiling your preview box

Task

*   [ ] Center overly in box
*   [ ] Add 32px padding to the bottom of the image to create space between loader and message

Wireframe

1.  1.  Currently look like

             

1.  1.  SHOULD look like

             

### QA Notes ###
- [x] BA Reveiw complete

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-462](https://fecgov.atlassian.net/browse/FECFILE-462)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
PLease review

**Comment by MitchellTCG** [comment]
@GreggMoreland 
PLease review

**Comment by GreggMoreland** [comment]
OBE - created accidentally
