### ISSUE TITLE
UI: Remove “Checking web-print status” from web-print page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1788]
User Story

  As the UX Lead, I would like the text “Checking web-print status” removed from the Print Preview page because it could confuse the user

Task

*   [ ] remove “Checking web-print status”

Wireframe

1.  1.  Currently look like

             ![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/23bdb4e5-1b89-4d18-8cfa-054173f1effa](https://github.com/fecgov/fecfile-web-app/assets/94924171/23bdb4e5-1b89-4d18-8cfa-054173f1eff))

1.  1.  SHOULD look like

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/4b85776d-6ea4-4a50-9181-4b8790e15557](https://github.com/fecgov/fecfile-web-app/assets/94924171/4b85776d-6ea4-4a50-9181-4b8790e1555))

### QA Notes ###
- [x] BA Reveiw complete

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-461](https://fecgov.atlassian.net/browse/FECFILE-461)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Please review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified text “Checking web-print status” was removed from the Print Preview page  (Verified Form 3x, Form 24, Form 1M)

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/8a28593c-f3c1-4b35-9253-025a4c79ba37)

QA Review Completed.  Moved to Stage Ready.
