### ISSUE TITLE
UI: Fix off-center loading overlay on print preview page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1789]
User Story

  As the UX Lead, I would like the loading overlay to be centered in the Compiling your preview box

Task

*   [ ] Center overly in box
*   [ ] Add 32px padding to the bottom of the image to create space between loader and message

Wireframe

1.  1.  Currently look like

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/37b713bb-254c-48ea-883e-58626080d58e](https://github.com/fecgov/fecfile-web-app/assets/94924171/37b713bb-254c-48ea-883e-58626080d58))

1.  1.  SHOULD look like

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/19763eff-de82-4f79-89e6-d645d4df84f7](https://github.com/fecgov/fecfile-web-app/assets/94924171/19763eff-de82-4f79-89e6-d645d4df84f))

### QA Notes ###
- [x] BA Reveiw complete

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-460](https://fecgov.atlassian.net/browse/FECFILE-460)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the fix for off-center loading overlay on print preview page was implemented.

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/6d6c1edb-b601-4b48-9b21-f34956be9599)

QA Review Completed.   Moved to Stage Ready.
