### ISSUE TITLE
UI: Update Confirm information Page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1790]
User Story

  As the UX Lead, I would like the email confirmation and Address more closely related the data being collected

Task

*   [x] Place Email #1 and Email #2 boxes side by side with 20px between the two (Fields are too long)
*   [x] Make Yes and No radio buttons closer together. DO NOT place into separate COL (responsive columns)
*   [x] Please make "Verify physical address" an H2

Wireframe

1.  1.  Currently look like

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/ed107e70-1dda-4150-b23f-bce053dc1dfb](https://github.com/fecgov/fecfile-web-app/assets/94924171/ed107e70-1dda-4150-b23f-bce053dc1df))

1.  1.  SHOULD look like

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/6e601544-2fbd-4787-9283-c5c98362353b](https://github.com/fecgov/fecfile-web-app/assets/94924171/6e601544-2fbd-4787-9283-c5c98362353))

### QA Notes ###
- [x] BA Reveiw complete

### DEV Notes ###
null

### Design ###
null

[FECFILE-459](https://fecgov.atlassian.net/browse/FECFILE-459)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Please review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG does the email format fix go for both Form 3x and Form 24 ?   Verify Physical Address - Radio buttons are only in Form 3x, so the Form 24 will not need radio buttons formatted.  - Thanks

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/ba4d234c-6f81-40ce-99ff-f8b4771e3a1e)

**Comment by WiseQA** [comment]
@mjtravers confirmed with @MitchellTCG the Form 24 email boxes need to be formatted like the Form 3x (see Form 24 screenshot above)

Please fix -  Place Email #1 and Email #2 boxes side by side with 20px between the two (Fields are too long)

Returning to In-Progress for Form 24 Confirm Information page fix.

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG the Form 24 Confirm Information page has been fixed prior to me sending ticket back.   Returning this ticket to QA Review as the Form 24 fix - Place Email #1 and Email #2 boxes side by side with 20px between the two (Fields are too long) is displaying correctly.

QA review verified Form 24 Email #1 and #2 are displayed as designed.

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/a619724e-919e-445c-8779-534c9a9e5edc)


QA Review Completed.  Moved to Stage Ready.
