### ISSUE TITLE
UI: Fix Alignment of Active/terminated status indicator in regards to committee info below the committee name

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1791]
User Story

  As the UX Lead, I would like the Active/terminated status indicator align vertical centered with the text to the right

Task

*   [ ] Align Active/terminated status indicator (push down 3pixels)

Wireframe

1.  1.  Currently look like

             ![Image](https://github.com/fecgov/fecfile-web-app/assets/97105825/7e9f0a0e-4964-45e4-ab8e-3eb8c2ded166](https://github.com/fecgov/fecfile-web-app/assets/97105825/7e9f0a0e-4964-45e4-ab8e-3eb8c2ded16))

1.  1.  SHOULD look like

             ![Image](https://github.com/fecgov/fecfile-web-app/assets/97105825/04053284-16f8-430a-b51c-266c48390305](https://github.com/fecgov/fecfile-web-app/assets/97105825/04053284-16f8-430a-b51c-266c4839030))

### QA Notes ###
- [x]  BA Reveiw complete

### DEV Notes ###
null

### Design ###
null

[FECFILE-458](https://fecgov.atlassian.net/browse/FECFILE-458)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
please review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the Active/terminated status indicator is aligned vertical centered with the text to the right
 
![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/28f01495-6406-4296-a2a9-b063d0967638)

QA Review Completed.   Moved to Stage Ready.
