### ISSUE TITLE
 UI - Update VERBIAGE on "Get started now" page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1792]
User Story:

1.  1.  As the UX Principal, I would like the word "Account" add the end of "Create a new committee" so it matches the original wireframe.

Tasks:

*   [ ] Please add the word "Account" after "Create a new committee" so it reads:

       ***"CREATE A NEW COMMITTEE ACCOUNT"***

       

Wireframe

1.  1.  Current page

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/ff2da9dc-d378-4b88-9f75-c425d1b8a536](https://github.com/fecgov/fecfile-web-app/assets/94924171/ff2da9dc-d378-4b88-9f75-c425d1b8a53))

### QA Notes ###
- [x] BA/Design Quality Checklist complete (completed by Mitchell)

### Design ###
![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/541e49f4-ffb0-4bec-bee6-bb6740e037c8)

[FECFILE-457](https://fecgov.atlassian.net/browse/FECFILE-457)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified verbiage on the "Get started now" page has been changed and updated to read "CREATE A NEW COMMITTEE ACCOUNT" per UX design.



![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/dc77d72d-400d-4630-aa6c-1fdc1db4ffac)


_________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
