### ISSUE TITLE
Increase application memory to 1GB

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#1797]
Business Reason

As a technical requirement, we should increase the web-app application memory to 1GB

`cf cpu-entitlement fecfile-web-app` (see [https://github.com/cloudfoundry/cpu-entitlement-plugin?tab=readme-ov-file](https://github.com/cloudfoundry/cpu-entitlement-plugin?tab=readme-ov-file))

***dev***

  | instance | avg usage | curr usage | | - | – | - | | #0 | 120.54% | 126.39% | | #1 | 352.88% | 384.52% | 

***stage***

  | instance | avg usage | curr usage | | - | – | - | | #0 | 401.22% | 387.90% | | #1 | 404.53% | 391.30% | 

***prod***

  | instance | avg usage | curr usage | | - | – | - | | #0 | 322.17% | 339.73% | | #1 | 310.12% | 287.49% | 

`App-Metrics` dashboard, past 15 days

  

### QA Notes ###
- [ ] BA/Design Quality Checklist complete

### DEV Notes ###
To update app (front-end) cloud.gov space to 1GB, the manifest files in the repo.
Here: https://github.com/fecgov/fecfile-web-app/tree/develop/deploy-config

### Design ###
null

 See full ticket and images here: [FECFILE-456](https://fecgov.atlassian.net/browse/FECFILE-456)

**Comment by mjtravers** [comment]
For QA: Screenshot of successful deploy with memory upgrade


![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/4b78c546-b52b-451a-94e8-1a01d404493a)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified with DEV successful deployment of memory upgrade.

Moved to Stage Ready.
