### ISSUE TITLE
System to separate committee account emails to Email #1 and #2 fields if two are available on Form 1

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1800]
Business Reason

The system will parse Email field from FEC to split into two email if semicolon or comma is present. The first will populate Email 1 and if there is a second after the , or ; it will populate Email 2 on the "Confirm Information" page in the submission workflow, so that it saves the user from manually typing them in.

Acceptance Criteria

***Given*** the user is on the "Confirm Information" page of a report,

  ***Then*** they will be able to enter two Confirmation Emails, 

  ***And*** the system will validate they are in the correct email format:

Email # 1 - this should default to the _first_ email from Form 1, and the user has the option to change if needed. This is a required field.

  Email # 2 - this should default to the _second_ email from Form 1 if one exists after a , or ; and the user has the option to change if needed. If no second email is present on the Form 1, this will default as blank. This field is optional.

### QA Notes ###
- [X] BA/Design Quality Checklist complete (N/A)
- Emails must be entered in correct email format (validation error already built in).
- This functionality applies to any report submission workflow. Current reports include:
- - Form 3X
- - Form 99
- - Form 1M
- - Form 24

### DEV Notes ###
- Current state if there are two emails on the Form 1 for a committee (system puts both in Email # 1 field, separated with a semicolon):
-  FEC has a single email field, caused by the design of the .fec format. We will need to parse the email field into two emails if there is a semicolon or comma in the field.

![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/90615e33-a285-4ac7-a910-7d66679ff0bb)

### Design ###
null

[FECFILE-454](https://fecgov.atlassian.net/browse/FECFILE-454)

**Comment by toddlees** [comment]
@GreggMoreland @AureliaKhorsand found this in the EFO specs for form 1:


![Image](https://github.com/fecgov/fecfile-web-app/assets/97105825/e3b33efe-c110-4069-aeff-164fa4d54561)


proposed edits to ticket:

> The system will parse Email field from FEC to split into two email if semicolon or comma is present.  The first will populate Email 1 and if there is a second after the `,` or `;` it will populate Email 2 on the "Confirm Information" page in the submission workflow, so that it saves the user from manually typing them in.


> DEV Notes 
FEC has a single email field, caused by the design of the .fec format.  We will need to parse the email field into two emails if there is a semicolon or comma in the field.


also, do you happen to know which committee had the smooshed emails so that we can test it?

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@dheitzer @toddlees @mjtravers See Matt's comment, add additional email(s) to Mary Committee (C00100479) to test this ticket.   Thanks !

**Comment by dheitzer** [comment]
@WiseQA @MitchellTCG additional email has been added to Mary Committee (C00100479) in dev.

**Comment by WiseQA** [comment]
@dheitzer can you please provide the emails for Mary account - thanks !

**Comment by dheitzer** [comment]
@WiseQA sure thing, the emails are these:
mary.honard@tcg.com
fakeemail@test.com


Thanks @dheitzer

**Comment by WiseQA** [comment]
QA verified backend showing 2 emails as depicted below:  

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/f5bf3b98-60af-4620-a864-4e95e48197bd)

_____________________________________________________________________________________________________________________________________

Verified front end is separating committee account emails to Email # 1 and Email # 2.  

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/56882039-dc2b-435b-acff-de6c9a722c7c)

_____________________________________________________________________________________________________________________________________

QA Review Completed.  Moved to Stage Ready.

(Note:  Verified on the following reports:  Form 3X; Form 99; Form 1M; Form 24)
