### ISSUE TITLE
e2e tests for Form 24

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1818]
We need e2e tests set up for:

- [ ] Creating a Form 24 and add an Independent Expenditure
- [ ] Verify IE transaction appears on Form3X

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
The e2e test updates have been pushed to DEV. An email will go out tonight when the tests are run if any fail during the nightly run.

**Comment by WiseQA** [comment]
QA received email for e2e nightly run 04/092024.   e2e test run was successful.  

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/b00a62b5-321a-4fdf-90ce-87d5fd6494f8)

QA Review Completed.  Moved to Stage Ready.
