### ISSUE TITLE
Update State Dropdown for ADD Contact (ONLY Candidate Type)

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#182]
Business Reason

As a Committee Administrator, I will be able to select a US State or US Territory without Armed Forces location while add contacts for a Candidate

Acceptance Criteria

***If*** I am a Committee Administrator 

  ***When*** I go to the Contact page 

   ***Then*** I will select the "New" button

  ***Then*** I will see a dropdown with the list of State written in full from the below list, ***i.e. "Virginia"***:
[https://docs.google.com/spreadsheets/d/17YmnaZgqvFOUyv4-Qknd8ikHe8o9LoDb/edit#gid=494776297](https://docs.google.com/spreadsheets/d/17YmnaZgqvFOUyv4-Qknd8ikHe8o9LoDb/edit#gid=494776297)

  ***Then*** the corresponding two letter abbreviation will appear on the back-end per the excel sheet above. ***ex. "VA"***

***Dev Note:***

  Make sure the state/province is defaulted to blank

  And blank is not a valid option

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1255](https://fecgov.atlassian.net/browse/FECFILE-1255)

**Comment by MitchellTCG** [comment]
here is a wire of the candidate contact page for reference:

![Candidate_State_Dropdown.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/22752807-e0d7-40de-a032-f52bd0da24d5)

**Comment by WiseQA** [comment]
Verified STATE/PROVINCE field is blank.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/76ad774b-1d6e-4250-aca7-75912bd42571)

Verified STATE/PROVINCE drop down menu contains US State and US Territory without Armed Forces and matches list denoted in Acceptance criteria.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f9caad45-2b67-4198-b993-3bae93529572)

Verified once Selected a STATE/PROVINCE (e.g., Virginia), state is displayed in STATE/PROVINCE field.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d4eafa95-9c2f-4e51-9d53-b7a3b369f3c5)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/2e9ad6d4-5dfe-4f2d-8266-22f2c1dc7117/download](https://app.zenhub.com/files/306118986/2e9ad6d4-5dfe-4f2d-8266-22f2c1dc7117/download)

QA review completed.  Moved to Stage Ready.
