### ISSUE TITLE
BUG - Add Login Guard to angular app

### ISSUE THREAD

**Issue by toddlees** [fecgov/fecfile-web-app#1828]
We need a route guard to prevent the app from loading any pages before the user is logged in. A small but consistent way of seeing this is to, in a new tab, go directly to [https://fecfile-web-app-dev.app.cloud.gov/dashboard](https://fecfile-web-app-dev.app.cloud.gov/dashboard) while logged out. You will see a page flicker and then the login page will appear.

In addition, the lack of the guard can affect the login process of the e2e tests as it will not route to the proper user info or confirmation page in some situations.

*   [x] add guard to all routes other than the login page to prevent access until logged in

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-446](https://fecgov.atlassian.net/browse/FECFILE-446)

**Comment by WiseQA** [comment]
@mjtravers @toddlees @MitchellTCG - Matt this is the bug you and I walked through the other day and verified the "page flickering".   I am not sure what we decided on points for this "Bug".   Thanks for writing the ticket for the "Bug".

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review, when testing on my computer, verified the "page flickering" bug has been fixed.

QA Review Completed.   Moved to Stage Ready.
