### ISSUE TITLE
Update State Dropdown for EDIT Contact (ONLY Candidate Type)

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#183]
Business Reason

As a Committee Administrator, I will be able to select a US State or US Territory without Armed Forces location while EDIT contacts for a Candidate

Acceptance Criteria

***If*** I am a Committee Administrator 

  ***When*** I go to the Contact page 

   ***Then*** I will select an edit pencil icon from any listing on the table

  ***Then*** I will see a dropdown with the list of State written in full from the below list, ***i.e. "Virginia"***:
[https://docs.google.com/spreadsheets/d/17YmnaZgqvFOUyv4-Qknd8ikHe8o9LoDb/edit#gid=494776297](https://docs.google.com/spreadsheets/d/17YmnaZgqvFOUyv4-Qknd8ikHe8o9LoDb/edit#gid=494776297)

  ***Then*** the corresponding two letter abbreviation will appear on the back-end per the excel sheet above. ***ex. "VA"***

***Dev Note:***

  Make sure the state/province is defaulted to blank (This is for ADD function not EDIT function)

  And blank is not a valid option

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1254](https://fecgov.atlassian.net/browse/FECFILE-1254)

**Comment by WiseQA** [comment]
Verified STATE/PROVINCE field in Candidate Contact Virginia is displayed.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/68ec55e7-02fa-49c5-ad37-b9e763bccc86)

Edit STATE/PROVINCE change to West Virginia and save.  Verified STATE/PROVINCE changed to West Virginia
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0cb83018-fa7a-4443-bc71-e9ee72e4f32d)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/9676a6e9-83a7-466e-8211-09dc6cf213fd/download](https://app.zenhub.com/files/306118986/9676a6e9-83a7-466e-8211-09dc6cf213fd/download)

QA review completed.  Moved to Stage Ready.
