### ISSUE TITLE
BUG - Update consent so that not checking box asks again a login

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1833]
Currently, the behavior of the consent checkbox does not meet the requirements from ticket [app#120](#120)([https://app.zenhub.com/workspaces/fecfile-online---archived-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/120):](https://app.zenhub.com/workspaces/fecfile-online---archived-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/120):)

*   "Consent" without the checkbox selected and continue to the dashboard (or Committee Account selection with [1654](#1654)([https://github.com/fecgov/fecfile-web-app/issues/1654](https://github.com/fecgov/fecfile-web-app/issues/1654))), whereupon they will see the security message on next login as well

If the user does not select the checkbox and clicks the consent button, they can log in without seeing the consent request screen again for 24 hours.

Business Reason

As a user, I will be able to get the consent screen after logging out after not selecting the consent checkbox and clicking the consent button.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-445](https://fecgov.atlassian.net/browse/FECFILE-445)

**Comment by AureliaKhorsand** [comment]
@mjtravers @WiseQA if this is in Sprint Backlog, it needs points. Did you all discuss points or should we look at it in refinement?

**Comment by WiseQA** [comment]
@AureliaKhorsand @MitchellTCG @mjtravers this was a bug that was found late yesterday, the Bug is put in Sprint Backlog, and will point as we have in the past the Bugs we find during testing.    @mjtravers please add 3 points as discussed.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified that when the checkbox "You consent to the security notification for one year" was not selected and the "Consent" button only selected, upon logout out and logging back in the "Security notification" page is displayed with the capability of selecting the "Consent" button again.  

______________________________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/f071546d-df02-4ee8-89b8-9e25935ae0b9)

______________________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
