### ISSUE TITLE
Remove SAVE & ADD MORE button for the Individual Edit Contacts modals

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#184]
Business Reason

As a Committee Administrator, when I edit an existing individual contact, I should be able to SAVE or CANCEL but not SAVE & ADD MORE contacts

Acceptance Criteria

1.  ***Individual***

       #

       ***If*** I am a Committee Administrator

       ***When*** I go to the Contacts page

       ***Then*** I will look for an "individual" contact type

       ***Then*** I will click the "pencil" edit on the right side of that contact

       ***Then*** I will see a modal with ONLY a CANCEL and SAVE button (No SAVE & ADD MORE Button)

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1253](https://fecgov.atlassian.net/browse/FECFILE-1253)

**Comment by WiseQA** [comment]
Verified Save & Add More button has been removed from the Individual Contact edit page.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6bc17aa5-2365-4878-92ab-f86f4cc90fcb)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/a61f3d41-d674-4aaf-8906-7cd7b710a4d0/download](https://app.zenhub.com/files/306118986/a61f3d41-d674-4aaf-8906-7cd7b710a4d0/download)

QA review completed.  Moved to Stage Ready.
