### ISSUE TITLE
BUG - Country/Region field blank after selecting the Save & Add More button on contact page

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1840]
The following Bug was found during testing with DEV in Sprint 40\. Country/Region field not displaying "United State of America" after selecting the Save & Add More button on contact page. Field is blank instead of the default of "United State of America".

1\. Add "New" contact. Country/Region field is displaying correctly "United State of America".

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/03c06b8f-dd69-46ee-94a3-6244ffa92ed4](https://github.com/fecgov/fecfile-web-app/assets/96139912/03c06b8f-dd69-46ee-94a3-6244ffa92ed))

  _____________________________________________________________________________________________________________________

2\. After creating the new contact then select the Save & Add More button on contact page. Country/Region field is blank instead of displaying "United State of America". (This is the Bug Fix)

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/153e0c6d-2cb9-4f76-997f-f14365bf6671](https://github.com/fecgov/fecfile-web-app/assets/96139912/153e0c6d-2cb9-4f76-997f-f14365bf667))

___________________________________________________________________________________________________________________

3\. Fix Country/Region field to default to "United State of America" once select the "Save & Add More" button.

@MitchellTCG @mjtravers Bug fix found during testing in Sprint 40\. Pointed 3 points and assigned to Sprint 41 per DEV.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-442](https://fecgov.atlassian.net/browse/FECFILE-442)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified bug fix.  After creating the new contact then select the Save & Add More button on contact page the Country/Region field is displaying "United State of America" as default correctly.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/6b56d19e-d256-4c84-a0cb-21b6648eeb68)

________________________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
