### ISSUE TITLE
BUG - Under Status By remove additional text being displayed

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1841]
During testing under Status By remove the extra text displaying when selecting "Affiliation" and/or "Qualification" radio buttons.

Affiliation:

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/c67be5ab-83cb-4cf1-ac71-25deca9d0f0b](https://github.com/fecgov/fecfile-web-app/assets/96139912/c67be5ab-83cb-4cf1-ac71-25deca9d0f0))

  ___________________________________________________________________________________________________________________

Qualification:

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/24fd575d-c5fa-4b24-8a81-c2887c855bcd](https://github.com/fecgov/fecfile-web-app/assets/96139912/24fd575d-c5fa-4b24-8a81-c2887c855bc))

________________________________________________________________________________________________________________

@MitchellTCG @mjtravers per direction assigned as Hotfix for Sprint 40\. Pointed 2 pts. Assigned to @Elaine-Krauss-TCG

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-441](https://fecgov.atlassian.net/browse/FECFILE-441)

**Comment by mjtravers** [comment]
Fixes two bugs:

Removed floating text "Affiliation" and "Qualification" on the F1M creation page.

Makes it so that when changing the statusBy radiobutton to "Affiliation", the excluded ids arrays are emptied, preventing a bug where you would be unable to lookup a specific candidate again

Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified under Status By the extra text displaying when selecting "Affiliation" and/or "Qualification" radio buttons was removed.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/0e37f8a7-90fc-4cfd-8161-a7d231990af6)
________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/5bb1f053-357a-47d4-b2db-3479154c6776)

_______________________________________________________________________________________________________

QA Review Completed.  Moved to Stage Ready.
