### ISSUE TITLE
BUG - When in a Form 3x the "Add to Form 24" dropdown selection should only be applicable to Independent Expenditures (IEs)

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1843]
During testing of Sprint 40 when selecting when in a Form 3x the "Add to Form 24" dropdown selection should only be applicable to Independent Expenditures (IEs). (Tested on Both STAGE and DEV)

The bug is to remove from the dropdown the "Add to Form 24" for other disbursements, Independent Expenditures (IEs) are the only transactions that should be able to select "Add to Form 24"

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/cc58d5c5-bbf9-4de3-a6e7-eeddb09b7592](https://github.com/fecgov/fecfile-web-app/assets/96139912/cc58d5c5-bbf9-4de3-a6e7-eeddb09b759))

_______________________________________________________________________________________________________________________

@MitchellTCG @mjtravers per direction assigned to Sprint 41\. Pointed 2 points.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-440](https://fecgov.atlassian.net/browse/FECFILE-440)

**Comment by Elaine-Krauss-TCG** [comment]
Bug fixed.

Dropdown of a Schedule B transaction:
![Image](https://github.com/fecgov/fecfile-web-app/assets/104506225/c0d79a2c-9de0-448d-99c5-9cf00551b5ef)

Dropdown of a Schedule E transaction:
![Image](https://github.com/fecgov/fecfile-web-app/assets/104506225/c9e875fc-a4b3-4434-ab39-9a075f31ee7f)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified and tested the bug was fixed.   "Add to Form 24" was removed from the Actions dropdown for disbursements other than the Independent Expenditures (IEs).  Independent Expenditures (IEs) are the only transactions that should be able to select "Add to Form 24"

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/a527667c-1a09-46f2-a1ec-911fc36ba964)

__________________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/0694bda1-4a49-4aa6-a9f6-ccab3271e209)

_________________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/e1134516-0594-40cd-9c84-406a6461f410)

__________________________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
