### ISSUE TITLE
Fix Print Preview PDF

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1849]
Business Reason

As a user, I will be able to create a Print Preview PDF that has the Committee Name and Address displayed so that the PDF looks how FEC intented.

Task

*   [ ] Make sure the committee name and address appear on Page 1
*   [ ] Make sure the committee name appears at the top of page 2
*   [ ] Make sure the committee name appears at the top of pages 6 - 10

Wireframe

 ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/30167290-ac8d-4f52-a6cc-c05f94c5f272](https://github.com/fecgov/fecfile-web-app/assets/25588182/30167290-ac8d-4f52-a6cc-c05f94c5f27))

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
- [ ] add committee_name to report model (app and api)
- [ ] save committee_name to report in all places `qualified_committee` is saved (print preview, submit report, and test .fec generation)

### Design ###
null

 See full ticket and images here: [FECFILE-438](https://fecgov.atlassian.net/browse/FECFILE-438)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand Please review

**Comment by MitchellTCG** [comment]
@toddlees Please review and add notes to dev note section so we can point

**Comment by toddlees** [comment]
checking a .fec generated by Dev, it's missing the committee name.  we should just be able to figure out why that's not being populated

**Comment by MitchellTCG** [comment]
BA reviewed by mitchell

**Comment by toddlees** [comment]
Identified why committee name is not in the .fec.  We lost this functionality in a refactor last year.  We need to add `committee_name` to the report model (api side) and save it to the report before any request to make a .fec.  This is already being done with `qualified_committee` so it really should just be adding a line wherever that's already happening.

**Comment by mjtravers** [comment]
Some requested changes made in CR. See PR comments for details.

https://github.com/fecgov/fecfile-web-api/pull/835

Sending back to In Progress.

**Comment by toddlees** [comment]
Passes CR moving to QA

**Comment by WiseQA** [comment]
QA review verified Print Preview PDF pages have been fixed to display 

- [x] Make sure the committee name and address appear on Page 1
- [x] Make sure the committee name appears at the top of page 2 and 3
- [x] Make sure the committee name appears at the top of pages 6 - 10

___________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/28c58a97-d98e-4c0e-929e-f7ed490bbb6c)

____________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/9af11878-84a9-4392-a41a-3481002c4219)

_______________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/2990071c-1418-4a0a-a5af-efc0e639b734)

_______________________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
