### ISSUE TITLE
Remove SAVE & ADD MORE button for the Candidate Edit Contacts modals

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#185]
Business Reason

As a Committee Administrator, when I edit an existing candidate contact, I should be able to SAVE or CANCEL but not SAVE & ADD MORE contacts

Acceptance Criteria

1.  ***Individual***

       #

       ***If*** I am a Committee Administrator

       ***When*** I go to the Contacts page

       ***Then*** I will look for an "Candidate" contact type

       ***Then*** I will click the "pencil" edit on the right side of that contact

       ***Then*** I will see a modal with ONLY a CANCEL and SAVE button (No SAVE & ADD MORE Button)

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1252](https://fecgov.atlassian.net/browse/FECFILE-1252)

**Comment by WiseQA** [comment]
Verified Save & Add More button has been removed from the Candidate Contact edit page.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/79de081f-9a59-4568-8396-d0cfabffab28)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/83eecf3e-00ef-4305-880e-1c23110c2e20/download](https://app.zenhub.com/files/306118986/83eecf3e-00ef-4305-880e-1c23110c2e20/download)

QA review completed.  Moved to Stage Ready.
