### ISSUE TITLE
UI: Update headers on the submit reports page.

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1850]
Issue

  The Committee treasurer and Enter password are h3's and they should be H2's

Task

*   [x] Change "Committee treasurer" to H2
*   [x] Change "Enter password" to H2

### QA Notes ###
- [ ] BA/Design Quality Checklist complete

### DEV Notes ###
 Wireframe
![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/2c033c4e-84cc-4e68-866e-d1127500679e)

### Design ###
null

[FECFILE-437](https://fecgov.atlassian.net/browse/FECFILE-437)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG looks good, moving to ADQTR

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the following changes were make on the "Submit report" page.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/63ffb038-3f73-4842-9306-449ce74044b5)

___________________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/73057362-c286-49ed-9270-96043ade8299)

________________________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
