### ISSUE TITLE
Fix the Confirm information Page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1851]
Issue

  EMAIL#1 and EMAIL#2 (OPTIONAL) should be capitalized

  The Confirm information button should be justified right

Tasks

*   [x] Capitalize "EMAIL#1" and "EMAIL#2 (OPTIONAL)"
*   [x] Right justify "Confirm information" button

Wireframe

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/8a65de43-38d2-44a8-a301-630ecef3b24d](https://github.com/fecgov/fecfile-web-app/assets/25588182/8a65de43-38d2-44a8-a301-630ecef3b24))

### QA Notes ###
- [ ] BA/Design Quality Checklist complete

### DEV Notes ###
There should be a space between EMAIL and the # symbol. (I couldn't in this ticket because of markdown script)

### Design ###
null

[FECFILE-436](https://fecgov.atlassian.net/browse/FECFILE-436)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand Please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG looks good, moving to ADQTR.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the following changes were made on the "Confirm information" page.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/ad3b11f2-a4aa-483c-979d-0a98a9ff9b1b)

______________________________________________________________________________________________________________________________


![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/dcdc4850-3169-4dfc-b156-2569b723389f)

______________________________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
