### ISSUE TITLE
Fix Summary and Detail Summary Page loading icon

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1852]
Issue

  The loader should be centered

Tasks

*   [x] Center the loader on the Summary Page
*   [x] Center the loader on the Detail Summary Page

Wireframe

1.  Current

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/e37d6260-9d9b-48ae-9b94-bc085e827d7b](https://github.com/fecgov/fecfile-web-app/assets/25588182/e37d6260-9d9b-48ae-9b94-bc085e827d7))

1.  Fixed

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/1c6713ee-2fb5-4420-921c-6fadaff7dae6](https://github.com/fecgov/fecfile-web-app/assets/25588182/1c6713ee-2fb5-4420-921c-6fadaff7dae))

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
- [x] For testing, also check the Print Preview Page as it uses the same styling class.

### Design ###
null

[FECFILE-435](https://fecgov.atlassian.net/browse/FECFILE-435)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg @mjtravers is there anywhere else in the system this appears that we can add to the ticket?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
No. I talked to devs this morning. They believe this was pushed off-center when we updated [#1789](https://github.com/fecgov/fecfile-web-app/issues/1789)

Please BA review and move to ADQTR

**Comment by MitchellTCG** [comment]
BA review by Mitchell

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified both Summary Page and Detailed Summary Page the loader is centered.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/e12debd1-838b-473d-b3e1-097d8dee6a1f)

QA Review Completed.   Moved to Stage Ready.
