### ISSUE TITLE
Bold "(REQUIRED IF OTHER)" for Election Description field in relevant transactions

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1853]
Task

  On any transaction with Election information, make the text black on "(REQUIRED IF OTHER)" after the label Election description.

*   [ ] Contribution to Candidate
*   [ ] Void of Contribution to Candidate
*   [ ] Contribution to Candidate - In-Kind
*   [ ] 100% Federal Election Activity Payment
*   [ ] Void of 100% Federal Election Activity
*   [ ] Credit Card Payment for 100% Federal Election Activity
*   [ ] Credit Card Memo for 100% Federal Election Activity
*   [ ] Payment to Payroll for 100% Federal Election Activity
*   [ ] Payroll Memo for 100% Federal Election Activity
*   [ ] Staff Reimbursement for 100% Federal Election Activity
*   [ ] Staff Reimbursement Memo for 100% Federal Election Activity
*   [ ] Conduit Earmark Out
*   [ ] PAC Conduit Earmark Out
*   [ ] Independent Expenditure
*   [ ] Multistate Independent Expenditure
*   [ ] Credit Card Payment for Independent Expenditure
*   [ ] Credit Card Memo for Independent Expenditure
*   [ ] Staff Reimbursement for Independent Expenditure
*   [ ] Staff Reimbursement Memo for Independent Expenditure
*   [ ] Payment to Payroll for Independent Expenditure
*   [ ] Payroll Memo for Independent Expenditure
*   [ ] Void of Independent Expenditure

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
 Wireframe
![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/7999ea6d-b82f-4982-99a0-4ed187b4b454)

### Design ###
null

[FECFILE-434](https://fecgov.atlassian.net/browse/FECFILE-434)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand Please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg is this the only place they want this formatting?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
I talked to Todd earlier. I would be wiser to fix everywhere there is an election information block. But I will need the BA's help figuring that out. Sorry for not writing that in sooner.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG All relevant transactions now listed

**Comment by MitchellTCG** [comment]
Thank you

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
I know you have pretty much done this but can you please BA review this and move to ADQTR

**Comment by sasha-dresden** [comment]
If I remember correctly from the point estimation of this ticket, there was talk that we might reverse this in the future to have all labels which have notes to use this format, so I am leaving the css style class for this feature alone, which is called: label-note. Switching back to this style would simply be a matter of reapplying the style class to all these notes.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified under Election information the text for ELECTION DESCRIPTION "REQUIRED IF OTHER" text, "REQUIRED IF OTHER" has been changed to bold text.   (NOTE:  Below screenshots show change testing with "Contribution to Candidate".   Spot checking on list of transactions in AC was also tested)

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/8eaf5eb0-079a-4d6e-8093-d0bfdf761c9e)

_________________________________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/5bf3a664-ebfa-49f2-a689-6321d2ec4490)

___________________________________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
