### ISSUE TITLE
UI: Add striping to all tables

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1858]
Business Reason

As the principal UX, I would like all tables striped to more easily read data.

Acceptance Criteria

*   [ ] Use p-datatable-striped class (the Striped rows function for PrimeNG)
*   [ ] Make the striped rows the following hex code: #E8E8E8 ***#F8F8F8***

***Update the following seven tables***

*   [ ] Stripe the Manage reports table
*   [ ] Stripe the Manage contacts table
*   [ ] Stripe the Restore deleted contact(s) table
*   [ ] Stripe the Manage Users table
*   [ ] Stripe the transaction in this report table
*   [ ] Stripe the Guarantors table
*   [ ] Stripe Transaction history table inside the Edit contact modal

1.  PrimeNG Class

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/303e21d4-1e37-4bb7-a3ac-2ac9695e86a8](https://github.com/fecgov/fecfile-web-app/assets/25588182/303e21d4-1e37-4bb7-a3ac-2ac9695e86a))

1.  Example

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/79df6e53-0d33-4df0-ae44-dafbee76c59d](https://github.com/fecgov/fecfile-web-app/assets/25588182/79df6e53-0d33-4df0-ae44-dafbee76c59))

### QA Notes ###
- [ ] BA/Design Quality Checklist complete

### DEV Notes ###
 Wireframes

### Design ###
null

[FECFILE-432](https://fecgov.atlassian.net/browse/FECFILE-432)

**Comment by MitchellTCG** [comment]
BA reviewed by mitchell

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the following tables have been updated by adding striping.
**Update the following seven tables**
- [x] Stripe the Manage reports table
- [x] Stripe the Manage contacts table
- [x] Stripe the Restore deleted contact(s) table
- [x] Stripe the Manage Users table (verified by DEV see comment below)
- [x] Stripe the transaction in this report table
- [x] Stripe the Guarantors table
- [x] Stripe Transaction history table inside the Edit contact modal

Below showing a few screenshots of completed tasks.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/0952593e-055e-44e6-b45c-b402cf3941dd)

______________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/6e27b8db-8d68-4e70-8159-29e854fc7c7b)

____________________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/65308f59-07aa-4ccc-8082-6f5e86685db9)

___________________________________________________________________________________________________________________________

@mjtravers verified User's table (as QA only has one user listed)

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/b97888ae-f4e3-4089-b784-41516e16a1f2)

_________________________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.

**Comment by MitchellTCG** [comment]
@sasha-dresden @WiseQA @mjtravers @toddlees 
It appears I screwed the pooch on this one. 
The color should be #F8F8F8 not #E8E8E8

I updated the AC's and I'm moving this back in the queue

**Comment by mjtravers** [comment]
Screenshot of updated background color:


![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/be25b244-2d28-467e-9878-39494907d362)

**Comment by mjtravers** [comment]
Code update passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified background color was changed to #F8F8F8.   Adhoc tested tables as listed in the previous QA test.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/11f8e76a-20fd-41bf-8bae-2b20334d614e)

____________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/0a476d5d-6a33-4119-971d-ebbb31e178a4)

________________________________________________________________________________________________________________

QA Review Completed.  Moved to Stage Ready.
