### ISSUE TITLE
Remove SAVE & ADD MORE button for the Committee Edit Contacts modals

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#186]
Business Reason

As a Committee Administrator, when I edit an existing committee contact, I should be able to SAVE or CANCEL but not SAVE & ADD MORE contacts

Acceptance Criteria

1.  ***Individual***

       #

       ***If*** I am a Committee Administrator

       ***When*** I go to the Contacts page

       ***Then*** I will look for an "Committee" contact type

       ***Then*** I will click the "pencil" edit on the right side of that contact

       ***Then*** I will see a modal with ONLY a CANCEL and SAVE button (No SAVE & ADD MORE Button)

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1251](https://fecgov.atlassian.net/browse/FECFILE-1251)

**Comment by WiseQA** [comment]
Verified Save & Add More button has been removed from the Committee Contact edit page.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/08f3f102-c89c-4e98-b895-2103929c44b8)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/a5c6499f-8c7d-499d-bf30-20c8701bf66f/download](https://app.zenhub.com/files/306118986/a5c6499f-8c7d-499d-bf30-20c8701bf66f/download)

QA review completed.  Moved to Stage Ready.
