### ISSUE TITLE
Replace agency placeholder text and image on login.gov sign-in screen

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1868]
**Task:** Replace agency placeholder text and image on Login.gov sign-in screen.

Current state: [![](https://github.com/fecgov/fecfile-web-app/assets/94924171/0ad7ea6f-85dd-48f1-ace7-fa1c44f517ee)](https://github.com/fecgov/fecfile-web-app/assets/94924171/0ad7ea6f-85dd-48f1-ace7-fa1c44f517ee)

### QA Notes ###

 
  Dev Notes

### DEV Notes ###

 
 null

### Design ###

 
 null

 See full ticket and images here: [FECFILE-430](https://fecgov.atlassian.net/browse/FECFILE-430)

**Comment by AureliaKhorsand** [comment]
BA questions:
1. Are there any other places placeholder content appears on login.gov?
2. Do need to be on production for this?

**Comment by lbeaufort** [comment]
@AureliaKhorsand I uploaded the logo below via the login.gov partner dashboard:

- Go to https://dashboard.int.identitysandbox.gov/
- Click on the app you want to edit
- Scroll down to "Upload your logo"

Side note, I fixed the casing (FECfile -> FECFile) as well. 



![Image](https://github.com/fecgov/fecfile-web-app/assets/31420082/e23af2fe-c46d-42bf-9ed8-4932ba1948d9)



![Image](https://github.com/fecgov/fecfile-web-app/assets/31420082/0279252b-b121-4d00-8fa0-80faa09cb1f4)

**Comment by AureliaKhorsand** [comment]
@lbeaufort that's great! Is this essentially all that is needed for this ticket?

I also noticed that the link to go back to FECFile Web API (Stage) does not link correctly. Is that something we want to fix here too?


![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/3d503279-5ee5-46ef-963a-41588c84ed32)

**Comment by lbeaufort** [comment]
> @lbeaufort that's great! Is this essentially all that is needed for this ticket?
> 
> I also noticed that the link to go back to FECFile Web API (Stage) does not link correctly. Is that something we want to fix here too?
> 
> ![Image](https://private-user-images.githubusercontent.com/94924171/330089344-3d503279-5ee5-46ef-963a-41588c84ed32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTQ2ODgsIm5iZiI6MTcxNTY5NDM4OCwicGF0aCI6Ii85NDkyNDE3MS8zMzAwODkzNDQtM2Q1MDMyNzktNWVlNS00NmVmLTk2M2EtNDE1ODhjODRlZDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEzNDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMDA3MjZjNDI4YTk2MGUzMGI1NWI5ZWQ1YTQ2N2I3N2IyN2U1ZTFiYTJmNjMxZTcxOTIzNGQ1Njc2YTZlZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HpTjqp23fffz5pHmsvso54I46rbMeK_ZfYtwjAb3AuM)

@AureliaKhorsand I'm not sure for this ticket, I'd agree that some UX attention would be good. I also changed the app label from `FECFile Web API (DEV)` to just `FECFile (DEV)` etc. 

Re: the broken "Back to FECFile" URL, I think we'll need to handle that on our end - on the API side, I believe. Login.gov sends the user to https://fecfile-web-api-dev.app.cloud.gov/oidc/callback/?error=access_denied&state=<state>, which redirects to https://fecfile-web-api-dev.app.cloud.gov/ which 404's. We should probably have a new ticket for this work. More info: https://developers.login.gov/user-experience/cancel-url/

**Comment by AureliaKhorsand** [comment]
@mjtravers given what Laura found, I'd say it is probably worth updating this ticket to include what Laura did (updating the placeholder text and image and renaming the app label) and breaking out into a new ticket fixing the "Back to FECFile" url. Does that work for you?

@MitchellTCG (and any others) in terms of UX, was this the only placeholder that you know of?

**Comment by AureliaKhorsand** [comment]
@mjtravers @MitchellTCG thoughts on the comment above?
