### ISSUE TITLE
Remove SAVE & ADD MORE button for the Organization Edit Contacts modals

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#187]
Business Reason

As a Committee Administrator, when I edit an existing organization contact, I should be able to SAVE or CANCEL but not SAVE & ADD MORE contacts

Acceptance Criteria

1.  ***Individual***

       #

       ***If*** I am a Committee Administrator

       ***When*** I go to the Contacts page

       ***Then*** I will look for an "organization" contact type

       ***Then*** I will click the "pencil" edit on the right side of that contact

       ***Then*** I will see a modal with ONLY a CANCEL and SAVE button (No SAVE & ADD MORE Button)

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1250](https://fecgov.atlassian.net/browse/FECFILE-1250)

**Comment by WiseQA** [comment]
Verified Save & Add More button has been removed from the Organization Contact edit page.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ffd1d59d-7ad6-4063-ac3e-04d411964fc7)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/7677715d-6b02-4466-81bb-c90a061e4e63/download](https://app.zenhub.com/files/306118986/7677715d-6b02-4466-81bb-c90a061e4e63/download)

QA review completed.  Moved to Stage Ready.
