### ISSUE TITLE
Move to cloud.gov buildpacks (rather than cloud foundry builpacks)

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#1872]
in manifest:

`buildpack: [https://github.com/cloudfoundry/nginx-buildpack.git](https://github.com/cloudfoundry/nginx-buildpack.git)`

we should be using ***cloud.gov's*** `nginx_buildpack` because it's reviewed by cloud.gov to make sure there are no breaking changes, and that deployment will work

Business Reason

As a developer, I will be able to deploy tested buildpacks so that I can deploy with fewer unexpected deployment errors.

### QA Notes ###
 
 This is a system configuration change that only applies to Cloud.gov. Passes QA, if DEV is up and running after deployment.

### DEV Notes ###
 
 null

### Design ###
 
 null

[FECFILE-426](https://fecgov.atlassian.net/browse/FECFILE-426)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
For QA, screenshot of DEV cloud.gov dashboard showing update and that system is running without issues.


![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/6533c113-bfaf-43eb-9318-298260b45e6f)

**Comment by WiseQA** [comment]
QA review verified with DEV the screenshot of DEV cloud.gov dashboard showing update and that system is running without issues.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/d7feafad-491d-431b-a2d0-18705dd018e4)

QA Review Completed.   Moved to Stage Ready.
