### ISSUE TITLE
BUG: UI: Submit button misaligned

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1880]
Issue

  The Submit button should be justified right on the same line as the back button

Tasks

*   [x] Right justify "Submit" button

1.  Current

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/b1ccb52f-ea57-4339-9d24-9a7b647d254d](https://github.com/fecgov/fecfile-web-app/assets/25588182/b1ccb52f-ea57-4339-9d24-9a7b647d254))

1.  Fixed

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/a6e972d0-9a57-40ca-9959-a13ce7fb5a9e](https://github.com/fecgov/fecfile-web-app/assets/25588182/a6e972d0-9a57-40ca-9959-a13ce7fb5a9))

### QA Notes ###
- [ ] BA/Design Quality Checklist complete

### DEV Notes ###
 Wireframe

### Design ###
null

 See full ticket and images here: [FECFILE-418](https://fecgov.atlassian.net/browse/FECFILE-418)

**Comment by toddlees** [comment]
passes CR moving to QA

**Comment by WiseQA** [comment]
QA verified Submit button is justified right on the same line as the back button

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/93503419-20a0-4636-bd25-3b90e1d93660)

_______________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
