### ISSUE TITLE
UX: Security notification: Consent button is greyed out when consent button is checked while decline and exit is blue, which is confusing

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#1881]
Business Reason

As a user, I will be able to clearly differentiate between the “Consent” and “Decline and exit” buttons with colors clearly indicating which is which so that I can quickly understand my options to exit the Consent page.

Acceptance Criteria

**Given** a user who has never clicked on the consent checkbox on the security notification page (e.g., new user, user who has never consented)

**When** the system displays the security notification page

**Then** the buttons for ‘Consent’ and ‘Decline and exit’ will be the following colors: 

### DEV Notes ###
 
 null

### Design ###
Current state of buttons: 

!image-20240730-162833.png|width=100%,alt="image-20240730-162833.png"!

*Design Notes* 

* *Button: "Decline and Exit"*
*# *Default State:*
*#* The button will be *gray (#F1F1F1)* to differentiate it from the "Consent" button and indicate that it's a secondary action.
*# *Hover State:*
*#* On hover, the button color will change to *blue (#112E51)* to signal that the user is about to interact with it.
*# *Selected State:*
*#* Once clicked, the button will remain *blue (#112E51)* to confirm the user's selection.

!Security Consent (eeb73a42-8868-49ea-8d88-d90c77c6a0a5).png|width=1735,height=1073,alt="Security Consent.png"!

I did not edit the text inside because I don’t know what it’s supposed to say, and I don’t have access to the original wireframe currently. Will update once both are received.

 See full ticket and images here: [FECFILE-417](https://fecgov.atlassian.net/browse/FECFILE-417)

**Comment by MitchellTCG** [comment]
@MitchellTCG 
please update criteria
Add wireframe
@JonellaCulmer we can discuss
