### ISSUE TITLE
Upgrade Angular to v17

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1887]
Upgrade front-end to Angular v17 from our current Angular 16.

Angular does a major release every 6 months: [https://angular.io/guide/releases#release-frequency](https://angular.io/guide/releases#release-frequency)

Here are the breaking changes: [https://angular.io/guide/update-to-version-17#highlighted-breaking-changes-in-angular-v17](https://angular.io/guide/update-to-version-17#highlighted-breaking-changes-in-angular-v17)

Steps to upgrade: [https://update.angular.io/?l=3&v=16.0-17.0](https://update.angular.io/?l=3&v=16.0-17.0)

***QA Notes***

  Ticket passes if unit tests and e2e tests pass.

1.  1.  1.  QA Notes ###

                   Angular does a major release every 6 months: [https://angular.io/guide/releases#release-frequency](https://angular.io/guide/releases#release-frequency)

Here are the breaking changes: [https://angular.io/guide/update-to-version-17#highlighted-breaking-changes-in-angular-v17](https://angular.io/guide/update-to-version-17#highlighted-breaking-changes-in-angular-v17)

Steps to upgrade: [https://update.angular.io/?l=3&v=16.0-17.0](https://update.angular.io/?l=3&v=16.0-17.0)

***QA Notes***

  Ticket passes if unit tests and e2e tests pass.

1.  1.  1.  DEV Notes ###

                   null
        2.  Design ###

                   null

### QA Notes ###
 
 Angular does a major release every 6 months: https://angular.io/guide/releases#release-frequency

Here are the breaking changes: https://angular.io/guide/update-to-version-17#highlighted-breaking-changes-in-angular-v17

Steps to upgrade: https://update.angular.io/?l=3&v=16.0-17.0

**QA Notes**
Ticket passes if unit tests and e2e tests pass.

### DEV Notes ###
 
 null

### Design ###
 
 null

[FECFILE-415](https://fecgov.atlassian.net/browse/FECFILE-415)

**Comment by mjtravers** [comment]
@Elaine-Krauss-TCG I'm getting one e2e test failure when running locally in the reports-f3x-amendments tests:


![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/3b82e437-8a80-4c7d-98c4-6527d677b950)


Sending back to In Progress to investigate test failure.

**Comment by Elaine-Krauss-TCG** [comment]
All E2E tests are passing for me, locally.  Would you be able to get me screenshots or the automatically recorded video?

![Image](https://github.com/fecgov/fecfile-web-app/assets/104506225/8713d9b0-99a7-480d-b9b5-2c61ddb18a29)


![Image](https://github.com/fecgov/fecfile-web-app/assets/104506225/3d4998a1-b4d2-427a-9c70-3e82a841e3f9)

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG @Elaine-Krauss-TCG @sasha-dresden please add passing current unit tests and validation screenshot Angular was upgraded to v17 for validation of this fix.  Thanks

**Comment by sasha-dresden** [comment]
Passing unit tests
![Image](https://github.com/fecgov/fecfile-web-app/assets/149604256/9a4f18b0-79e0-4dc4-95ba-46f5a32986a3)

Package details. Note the ones marked @angular are set to 17
![Image](https://github.com/fecgov/fecfile-web-app/assets/149604256/12e46c5c-396c-4da3-b993-6349864a970d)

**Comment by WiseQA** [comment]
Per DEV QA verified Unit Tests passing for this ticket.

QA verified with DEV Angular version upgraded.

Moved to Stage Ready.
