### ISSUE TITLE
UI: Activate table sort arrow on page load for all tables. Make background color of sorted column gray.

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1888]
Business Reason

As a user, I will be able to see the table sorted by the left-most column on tables when I view them.

Acceptance Criteria

***Given*** a table on the site

  ***When*** when viewing the table at page load

  ***Then*** the table will be sorted in ascending order by the left most column. Also, the column that is sorted will have a gray background.

Wireframes

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/087d81ad-3561-4ed7-88ec-bfcb86f888de](https://github.com/fecgov/fecfile-web-app/assets/25588182/087d81ad-3561-4ed7-88ec-bfcb86f888d))

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/3bb50db6-4163-447b-8807-b12f3303452c](https://github.com/fecgov/fecfile-web-app/assets/25588182/3bb50db6-4163-447b-8807-b12f3303452))

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/544802ed-5356-4488-a440-c353184ab30f](https://github.com/fecgov/fecfile-web-app/assets/25588182/544802ed-5356-4488-a440-c353184ab30))

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/47969400-8a4e-45fa-9547-88539ae0841e](https://github.com/fecgov/fecfile-web-app/assets/25588182/47969400-8a4e-45fa-9547-88539ae0841))

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/9a667781-c0fa-46f0-a109-b03f53b1da9c](https://github.com/fecgov/fecfile-web-app/assets/25588182/9a667781-c0fa-46f0-a109-b03f53b1da9))

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/ecd27758-531b-4ca6-9b51-8a43765c828d](https://github.com/fecgov/fecfile-web-app/assets/25588182/ecd27758-531b-4ca6-9b51-8a43765c828))

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/5f829137-b8ae-4eaf-b810-be801b7aac01](https://github.com/fecgov/fecfile-web-app/assets/25588182/5f829137-b8ae-4eaf-b810-be801b7aac0))

### QA Notes ###
 
 null

### DEV Notes ###
 
 Background color of table header for selected sort: #D6D7D9

Tables to update with default sort:
- [x] Manage Users
- [x] Manage Contacts
- [x] Restore deleted contacts
- [x] Contact Transaction History
- [x] Manage Reports
- [x] Receipts List
- [x] Disbursements List
- [x] Loans & Debts List
- [x] Guarantors List

### Design ###
 
 null

 See full ticket and images here: [FECFILE-414](https://fecgov.atlassian.net/browse/FECFILE-414)

**Comment by WiseQA** [comment]
QA review verified background color of sorted column is gray per UX.   Verified table sorted by the left-most column on tables when viewed.

- [x] Manage Users
- [x] Manage Contacts
- [x] Restore deleted contacts
- [x] Contact Transaction History
- [x] Manage Reports
- [x] Receipts List
- [x] Disbursements List
- [x] Loans & Debts List
- [x] Guarantors List

QA Review Completed.   Moved to Stage Ready.
