### ISSUE TITLE
Integrate validate npm package into INDIVIDUAL contacts EDIT form validation screens

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#189]
Business Reason

As a user, I want the validation check on the contact edit forms to use the validation javascript library so it validates against the validation schema.

Acceptance Criteria

*   Current validation code for the 4 contact edit screens replaced by javascript validation npm package work as they did previously.
*   All 4 contact edit screens (Individual, Organization, Committee, Candidate) pass the sprint-6 regression tests.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1249](https://fecgov.atlassian.net/browse/FECFILE-1249)

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 3/30/22:** @mjtravers to split out into a ticket for each contact type, and point each at 5.

**Comment by WiseQA** [comment]
Contacts screen selecting Individual contact:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/68d594fa-dfa6-42e4-9c50-7107de63f5a3)

Successful - Contact Updated Popup Screen Shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/28afe654-0dd1-4c77-9b90-6c0c97d5fac2)

Contacts screen showing Individual edit name successful:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ac16577b-55f3-469f-8a57-9e442c143f9a)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/9c05e433-b64d-4420-b7d6-de0a1393f102/download](https://app.zenhub.com/files/306118986/9c05e433-b64d-4420-b7d6-de0a1393f102/download)

QA review completed.  Moved to Stage Ready.
