### ISSUE TITLE
Fix "Sign up with login.gov" buttons

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#1896]
These buttons don't work:

https://fecfile-web-app-stage.app.cloud.gov/login

<img width="1356" alt="Screenshot 2024-04-29 at 3 17 26 PM" src="https://github.com/fecgov/fecfile-web-app/assets/31420082/8db6d409-028b-4f6a-a42d-59780bb07bda">

### Business Reason

As a [role], I will be able to [blank] so that I can [business reason]

### Acceptance Criteria

**Given** [precedent]
**When** [action]
**Then** [result]

### QA Notes
- [ ] BA/Design Quality Checklist complete

**Comment by AureliaKhorsand** [comment]
@lbeaufort we already have a ticket for this in #1683 . Do you mind if we close this one?

**Comment by lbeaufort** [comment]
> @lbeaufort we already have a ticket for this in #1683 . Do you mind if we close this one?

@AureliaKhorsand sorry about that, sounds good to close this one.
