### ISSUE TITLE
Hitting refresh causes 404 error

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#190]
Steps to reproduce 

Log in to https://fecfile-web-app-prod.app.cloud.gov
Click on "Contacts"
Hit refresh
Get 404
 
<img width="884" alt="Screen Shot 2022-03-29 at 10 40 24 AM" src="https://user-images.githubusercontent.com/31420082/160637510-fd3f34b1-1639-4671-b8f1-1f8a2e971897.png">

@mjtravers NOTE: I suspect the 404 is happening because the JWT token management by Django to the Angular front-end needs an overhaul. Here is one article (there are many out there to look at... [another](https://www.metaltoad.com/blog/angular-api-calls-django-authentication-jwt) and [another](https://github.com/maratumba/boilerplate-angular-django-jwt-login)) on [how to integrate Django JWT management with an Angular front-end](https://humberto.io/blog/jwt-authentication-with-angular-and-django/) 

Related Task: Lockout should be changed to 5 attempts and not 1

 Acceptance Criteria 
 

**If** a user logs into the app
**When** they have been logged in for 5 - 10 minutes
**Then** the app still functions with the user logged in and does not display a 404 error

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by WiseQA** [comment]
@mjtravers retested 404 error. 

Login  to Stage:  https://fecfile-web-app-stage.app.cloud.gov/  - no 404 error
Login to DEV:  https://fecfile-web-app-dev.app.cloud.gov/dashboard - no 404 error

Login to https://fecfile-web-app-prod.app.cloud.gov/contacts - 404 error

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/42547220-2f46-464c-b61f-0a58c3b5271c)

**Comment by toddlees** [comment]
@WiseQA I just checked, and sprint 12 was deployed to production Thursday August 25th.  I did a quick test and it does seem like refresh works!  I think we can make this OBE.

**Comment by WiseQA** [comment]
@toddlees I just verified 404 Not Found error for PROD was fixed with Sprint 12 deployment.   This ticket if DEV is satisfied can be moved to QA Review and assigned to me.  Thanks

**Comment by WiseQA** [comment]
QA review verified when login to https://fecfile-web-app-prod.app.cloud.gov/contacts - 404 error has been fixed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/543a9d6d-4248-4049-9068-ded1ddd9a43a)

QA Review Completed.  Moved to Stage Ready.

**Comment by toddlees** [comment]
@lbeaufort https://github.com/fecgov/fecfile-web-app/pull/410 was implemented because we had made a test screen that we wanted QA to be able to hit by typing in a url to test [342](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/342).  Typing in a url to access a specific page was triggering the same nginx 404 issue, so a side effect of fixing it was fixing the refresh error.
