### ISSUE TITLE
Update "Add new user" enter email field on pop-up to be case in-sensitive

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#1901]
Description

"Add new user" enter email field is case sensitive and needs to be changed to not be case sensitive.

NOTE: I added an email to my account proper-cased and it only allowed access after I added the account lower-cased. I was able to create two accounts.

Business Reason

### QA Notes ###
 
 null

### DEV Notes ###
 
 As a committee administrator, I will be able to add a new user without worrying about case sensitivity so that I can reliably and predictably add users.

**DEV Notes**
- [x] Front-end checks for duplicate email copies regardless of case.
- [x] Back-end checks for duplicate email copies regardless of case.
- [x] Create migration to remove any duplicate emails per each committee

### Design ###
 
 null

 See full ticket and images here: [FECFILE-428](https://fecgov.atlassian.net/browse/FECFILE-428)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when "Adding a new user" the email field on popup is not case sensitive.   

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/d937dea8-81ab-49fa-bf86-a8cb95cd0bd4)

______________________________________________________________________________________________

QA tested using MATT.travers@tcg.com.   Entered email as MATT.travers@tcg.com and role then added user.  User displayed in Existing Users table.  

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/ef6c8b63-b969-49c1-9d59-5f0fc95db987)
__________________________________________________________________________________________________________

Reentered usingn email as matt.travers@tcg.com. The "Add new user" popup window identifies email already exists.  Case is verified in-sensitive.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/29dd0956-d639-4096-9b70-e4115119933c)

____________________________________________________________________________________________________

Reentered using email as MAtt.travers@tcg.com The "Add new user" popup window identifies email already exists.  Case is verified in-sensitive.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/01c8beec-8d6b-4a6f-ae1d-0f968ae8a63e)

_________________________________________________________________________________________________________

QA Review Completed.  Moved to Stage Ready.
