### ISSUE TITLE
UI: Tables: Remove border from all Tables

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1903]
Business Reason

  As the principal UX, I would like all borders removed from all tables to more easily read data.

Acceptance Criteria

  ***Remove the following:***

  Inside the .card class

 {—bs-card-border-width: var(--bs-border-width); --bs-card-border-color: var(--bs-border-color-translucent); --bs-card-border-radius: var(--bs-border-radius)} 

*   [x] On the Manage reports table
*   [x] On the Manage contacts table
*   [x] On the transaction in this report table
*   [x] On the Guarantors table

***Remove the following:***

  Inside the .p-card class

 {box-shadow: inset 0 0 0 15px #0000000f;} 

Inside the .p-card .p-card-body classes

 {padding: 1.5 rem} 

*   [x] On the Manage Users table

1.  Current State for Manage reports, Manage contacts, Transactions in this report, and Guarantors

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/03203810-29f2-450d-995d-7b36c466d804](https://github.com/fecgov/fecfile-web-app/assets/25588182/03203810-29f2-450d-995d-7b36c466d80))

1.  Current state for Manage users

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/e2788dc5-65c4-40a2-b281-19254b33689f](https://github.com/fecgov/fecfile-web-app/assets/25588182/e2788dc5-65c4-40a2-b281-19254b33689))

1.  Ideal state

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/29958920-1212-4fcd-9d95-83be23dab280](https://github.com/fecgov/fecfile-web-app/assets/25588182/29958920-1212-4fcd-9d95-83be23dab28))

### QA Notes ###
 
 - [x] BA/Design Quality Checklist complete

### DEV Notes ###
 
  Wireframes

### Design ###
 
 null

[FECFILE-405](https://fecgov.atlassian.net/browse/FECFILE-405)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified borders were removed from tables:

- [x] On the Manage reports table
- [x] On the Manage contacts table
- [x] On the transaction in this report table
- [x] On the Guarantors table

Below screenshots are showing a few of the tables changed.
_____________________________________________________________________________________________________________________

Manage reports

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/e780f091-747e-4a47-b136-684f8b4435d9)

______________________________________________________________________________________________________________________

Manage contacts

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/c0fcaefb-8258-4fef-b9fb-43bd62d4b408)

________________________________________________________________________________________________________________________

Manage users

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/d08be117-1ac1-498d-afd8-52d359451c06)

__________________________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
