### ISSUE TITLE
UI: Tables: Manage Contacts: Add an actions column

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1904]
Business Reason

  As the principal UX, I would like all tables to have continuity so users will have a similar experience throughout the site.

Tasks

*   [x] Change the Delete column to an “Actions” column
*   [x] add kebobs in the action column to all contacts
*   [x] Each contact should have the choice of edit and delete
*   [x] if the contact has transactions associated to it, the delete should be greyed out

1.  1.  Current State

![image-20240530-191528.png](/attachments/11280?name=image-20240530-191528.png)

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/44a31f30-5f2f-4962-a790-7b9ac9e2ad72](https://github.com/fecgov/fecfile-web-app/assets/25588182/44a31f30-5f2f-4962-a790-7b9ac9e2ad7))

1.  1.  Ideal State

![image-20240530-191549.png](/attachments/11279?name=image-20240530-191549.png)

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/df4d93cc-7b8a-4042-80cd-62154bbbb905](https://github.com/fecgov/fecfile-web-app/assets/25588182/df4d93cc-7b8a-4042-80cd-62154bbbb90))

### QA Notes ###
 
  
 - [x] BA/Design Quality Checklist complete

### DEV Notes ###
 
  
  Wireframes

### Design ###
 
  
 null

[FECFILE-404](https://fecgov.atlassian.net/browse/FECFILE-404)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
pls review this ticket instead

**Comment by GreggMoreland** [comment]
@MitchellTCG Is there a wireframe for this?

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the Manage contacts table has been updated with the following changes.

- [x] Changed the Delete column to an “Actions” column
- [x] Added kebobs in the action column to all contacts
- [x] Contact should have the choice of edit and delete
- [x] if the contact has transactions associated to it, the delete should be greyed out 
- [x] If the contact has no transactions associated, the delete function is then optional 
- [ ] Font-weight: change from 400 to **600**
- [ ] Change active color from #5B616B to #212121

____________________________________________________________________________________________________________



![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/6bce5c46-0d5b-41ea-bc28-63a4995fb63b)

___________________________________________________________________________________________________________

Screenshot of contact with transactions associated to it, the delete should be greyed out

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/2de74685-5f12-4c62-bcbb-bcf872d2f3b5)

________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.

**Comment by mjtravers** [comment]
Update passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the additional font changes added by UX.   

- [x] Font-weight: change from 400 to **600**
- [x] Change active color from #5B616B to #212121

_____________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/44397da2-fda1-492a-94dd-e1c3f2a51dcb)

___________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/39251f54-e2fd-4ea4-88bd-485582d5cb63)

___________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
