### ISSUE TITLE
UI: Tables: Move or Add “Results per table:” to all tables

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1906]
Business Reason

  As the principal UX, I would like all tables to have continuity so users will have a similar experience throughout the site.

Tasks

  using the PrimeNG Table/Programmatic as a baseline

Please place the Results per table left justified under the data table (with 10px padding left) and the pagination justified to the right (with 10px padding to the right).

Move

  –

  Move the “Results per table” on the same line as the pagination on the following pages:

*   [x] Transactions in this report table
*   [x] Guarantors table

Add

  –

  Add“Results per table” to the table and place it on the same line as the pagination on the following pages:

*   [x] Manage reports table
*   [x] Manage Users table
*   [x] Manage contacts table
*   [x] Restore deleted contact(s) table
*   [x] Transaction history table inside the Edit contact modal

Icons

  –

  Update Icons

*   [x] Down Arrow
*   [x] Beginning
*   [x] Back One Page
*   [x] Forward One Page
*   [x] End

Wireframes

1.  Prime NG Reference

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/66500f11-002c-41c8-be40-a3639cf26b2a](https://github.com/fecgov/fecfile-web-app/assets/25588182/66500f11-002c-41c8-be40-a3639cf26b2))

1.  Current state for Transactions in this report and Guarantors

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/59135b58-0a6e-4741-830d-ef0c3d851ec7](https://github.com/fecgov/fecfile-web-app/assets/25588182/59135b58-0a6e-4741-830d-ef0c3d851ec))

1.  Current state for Manage reports, Manage users, Mange Contacts, Restore delete contact(s), and Transactions history

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/24673b86-d268-4a0c-af2a-06bdaed40943](https://github.com/fecgov/fecfile-web-app/assets/25588182/24673b86-d268-4a0c-af2a-06bdaed4094))

1.  Ideal State

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/512361ab-b2ad-4269-a68d-5e3ce297baa5](https://github.com/fecgov/fecfile-web-app/assets/25588182/512361ab-b2ad-4269-a68d-5e3ce297baa))

Assets

  ***Down Arrow***

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/26e1aea8-3c4b-4a0a-836a-f9d0651e74a1](https://github.com/fecgov/fecfile-web-app/assets/25588182/26e1aea8-3c4b-4a0a-836a-f9d0651e74a))

***Beginning***

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/4065a3c5-56c6-402c-8c32-dc88cd231a55](https://github.com/fecgov/fecfile-web-app/assets/25588182/4065a3c5-56c6-402c-8c32-dc88cd231a5))

***Back One Page***

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/5c16532d-218c-4b28-826f-82903e1074cc](https://github.com/fecgov/fecfile-web-app/assets/25588182/5c16532d-218c-4b28-826f-82903e1074c))

***Forward One Page***

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/92d3960b-94e7-4666-8859-b099142558f7](https://github.com/fecgov/fecfile-web-app/assets/25588182/92d3960b-94e7-4666-8859-b099142558f))

***End***

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/125d6c97-9ea7-42b6-92a9-c356e0980ca7](https://github.com/fecgov/fecfile-web-app/assets/25588182/125d6c97-9ea7-42b6-92a9-c356e0980ca))

### QA Notes ###
 
  
 null

### DEV Notes ###
 
  
 null

### Design ###
 
  
 null

[FECFILE-402](https://fecgov.atlassian.net/browse/FECFILE-402)

**Comment by MitchellTCG** [comment]
@sasha-dresden 
Here are the updated I promised to put in 
- [x] On the Restore deleted contact(s) table please change the col width so the Results per page and the dropdown are on the same line
- [x] On pages without a left nav, @ the sm 576 breakpoint please stack the Results per page and Pagination with at least 24 px of padding between the two
- [x] On pages with a left nav, @ the sm 576 & md 768 breakpoints please stack the Results per page and Pagination with at least 24 px of padding between the two

**Comment by mjtravers** [comment]
@sasha-dresden A couple of feedback items in the app and api PRs for this ticket from CR. Sending back to In Progress. Also, would you review the checkbox items in the ticket description and Mitchell's comment and tick off the ones that have been completed?

**Comment by sasha-dresden** [comment]
Per conversation with Mitchel made the following changes:

- remove bottom margin from toolbar
- get rid of of header top border
- header bottom padding set to 8px
- header top padding from 16 to 64
- header left padding set to 0
- th border top 0
- th border bottom 1px #212121
- add 2px border to top and bottom of footer
- add 16px top and bottom padding and 10px left and right padding to footer
- change padding from 8 to 32px for the main-content of the page
- add 32px padding top to app-footer

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
@sasha-dresden @Elaine-Krauss-TCG CircleCI is having an issue downloading Google Chrome this morning to run the unit tests:


![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/4f4d3d91-2d27-463e-8379-6833254bb914)

I don't know if this is a connection issue or if the recent package upgrades are the root of the problem. The ticket is on hold until this is resolved.

**Comment by WiseQA** [comment]
QA review verified “Results per table” to the table and place on the same line as the pagination.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/12105047-b515-49b7-b547-e3dc94a4bcaa)
_______________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/a89dabd3-292e-4960-b263-bac5328620e3)
___________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/7db6900e-49eb-470d-98dd-8f2d5811e85c)

_____________________________________________________________________________________________________________________

The following was tested, verified and passed by QA.


Move the “Results per table” on the same line as the pagination on the following pages:
- [x] Transactions in this report table
- [x] Guarantors table

Add
--
Add“Results per table” to the table and place it on the same line as the pagination on the following pages:
- [x] Manage reports table
- [x] Manage Users table
- [x] Manage contacts table
- [x] Restore deleted contact(s) table
- [x] Transaction history table inside the Edit contact modal

Icons
--
Update Icons
- [x] Down Arrow
- [x] Beginning
- [x] Back One Page
- [x] Forward One Page
- [x] End

QA Review Completed.   Moved to Stage Ready.
