### ISSUE TITLE
Unable to minimize feedback box at certain screen resolutions, blocking page

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#1918]
**Description:** **Where was the issue found:** * **Committee ID:** C00100495 * **Environment:** STAGE / DEV * **Browser:** Chrome

**Please describe the issue:** Original issue found by Laura: When selecting the "Feedback" button when making the screen size smaller the feedback box, the top of the feedback popup display can disappear off the top of the screen (along with its close button) and cannot be accessed so that the popup cannot be closed.

Overarching issue (reviewed by Mitchell): The "Feedback" box is coded with a fixed width and height - 830px H by 500px W. Since the Box is snapped to the bottom of the page, this is causing the top of the Feedback box and the closing icon to disappear when the screen is shrunk under 788 px vertically.

Please use FEC.gov's Feedback box as a template.

1.  The top of the Feedback box never gets closer than 40px to the top if the page
2.  The second the page is smaller than 870px vertically a scroll bar is added. See wireframe below.

**Approx. time the issue was found:** 10:20 am on 06/18/2024 (Note: QA retesting issue submitted to update template and verify bug)

**How to replicate the issue:**

1.  Click the "Feedback" button on the bottom of any page.
2.  Resize the screen vertically to less than 780 pixel (you should see the carat disappear).
3.  The ability to close the feedback box is the bug as this cannot be done.

**Screenshots:** Current issue on Dev and Stage

[![](https://github.com/fecgov/fecfile-web-app/assets/31420082/5ae206b3-22b1-428c-aad3-5d1fc6523353)](https://github.com/fecgov/fecfile-web-app/assets/31420082/5ae206b3-22b1-428c-aad3-5d1fc6523353)

[![](https://github.com/fecgov/fecfile-web-app/assets/31420082/5ae206b3-22b1-428c-aad3-5d1fc6523353)](https://github.com/fecgov/fecfile-web-app/assets/31420082/5ae206b3-22b1-428c-aad3-5d1fc6523353)

How FEC.gov deals with the issue:

[![](https://github.com/fecgov/fecfile-web-app/assets/25588182/9abc11c3-6c84-40d2-aa5a-902429c4865d)](https://github.com/fecgov/fecfile-web-app/assets/25588182/9abc11c3-6c84-40d2-aa5a-902429c4865d)

[![](https://github.com/fecgov/fecfile-web-app/assets/25588182/9abc11c3-6c84-40d2-aa5a-902429c4865d)](https://github.com/fecgov/fecfile-web-app/assets/25588182/9abc11c3-6c84-40d2-aa5a-902429c4865d)

* * *

 ~~@MitchellTCG @mjtravers suggest adding "Close" button or the ability for a scroll bar to close the feedback window. This is an UX discussion / decision on how to handle this fix.~~

### QA Notes ###

null

### DEV Notes ###

null

### Design ###

null

 See full ticket and images here: [FECFILE-399](https://fecgov.atlassian.net/browse/FECFILE-399)

**Comment by MitchellTCG** [comment]
@lbeaufort 
Please provide detailed instructions to replicate the issue you found so Shelly can replicate it. 
Is the issue when you shrink the page vertically or horizontally? 
Are you expecting a scroll bar on the feedback box?
And when you say minimize, am I correct in assuming you mean close?

**Comment by WiseQA** [comment]
@lbeaufort please update ticket so we know what to retest, and what needs fixed per Mitchell's questions.   Thanks

**Comment by lbeaufort** [comment]
@MitchellTCG @WiseQA  - Mitchell and I discussed and he said he would add more information to the ticket

**Comment by AureliaKhorsand** [comment]
BAs will take a first pass at fleshing out ticket then will pass on to design for verification before QA review of ticket.

**Comment by WiseQA** [comment]
@AureliaKhorsand @MitchellTCG I will update this ticket with Bug / Defect template now that we have one that the team is using.   The Bug / Defect tickets this is the last one to update from QA.

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers per our conversation needs updated with UX design on this screen, DEV Notes and screenshots how this feedback box should be positioned.  Thanks

**Comment by MitchellTCG** [comment]
@GreggMoreland Please review

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers per bug review, retested on DEV / STAGE and both displaying the same, bug found in Sprint 44 testing.   Bug pointed 3 pts and moved to Sprint Backlog and assigned to Sprint 45.

**Comment by sasha-dresden** [comment]
@MitchellTCG  I updated the css on this to prevent it from overflowing:

Large screen:
![Screenshot 2024-06-27 170753](https://github.com/fecgov/fecfile-web-app/assets/149604256/55d995a5-520e-47dc-b8d5-c2d36d185fcb)


Small screen:
![Screenshot 2024-06-27 170816](https://github.com/fecgov/fecfile-web-app/assets/149604256/16176c7b-3386-433e-93ad-bfbbbdddaeb0)
