### ISSUE TITLE
Integrate validate npm package into INDIVIDUAL contacts ADD form validation screens

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#192]
Business Reason

As a user, I want the validation check on the contact add forms to use the validation javascript library so it validates against the validation schema.

Acceptance Criteria

*   Current validation code for the 4 contact add screens replaced by javascript validation npm package work as they did previously.
*   All 4 contact add screens (Individual, Organization, Committee, Candidate) pass the sprint-5 regression test

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1247](https://fecgov.atlassian.net/browse/FECFILE-1247)

**Comment by WiseQA** [comment]
Individual Contact field messages screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5277170e-2cbc-4765-ad30-db0a8adb0e7d)

Individual Contact field error messages screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7add78aa-ec9e-4b1e-af45-a68f9ca35505)

Individual Contact "required fields" screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/65621499-e5dc-4369-8579-070b9f3040b2)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/d1f48d1a-c6e5-4745-852d-50777de28b42/download](https://app.zenhub.com/files/306118986/d1f48d1a-c6e5-4745-852d-50777de28b42/download)

QA review completed.  Moved to Stage Ready.
