### ISSUE TITLE
System to hide/disable 'Save & add memo' button on reattribution and redesignation transactions

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1920]
Business Reason

As a user, I will not be able to add a memo on a 'Reattribution to' or 'Reattribution from' or a 'Redesignation to' or 'Redesignation from' transaction so that I can accurately report on my committee's transactions.

Acceptance Criteria

_**Given**_ a Reattribution function _**And**_ the Reattribution 'parent' transaction is one of the following:

*   [ ] Partnership Receipt
*   [ ] Joint Fundraising Transfer
*   [ ] Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account
*   [ ] Joint Fundraising Transfer - National Party Pres. Nominating Convention Account
*   [ ] Joint Fundraising Transfer - National Party Headquarters Buildings Account
*   [ ] Partnership Recount Account Receipt
*   [ ] Partnership National Party Recount/Legal Proceedings Account
*   [ ] Partnership National Party Headquarters Buildings Account
*   [ ] Partnership National Party Pres. Nominating Convention Account

_**When**_ I create the 'Reattribution to' transaction _**Or**_ later edit either the 'Reattribution to' or 'Reattribution from' transaction _**Then**_ the 'Save & and add memo' button will be hidden/disabled

* * *

_**Given**_ a Redesignation function _**And**_ the Redesignation 'parent' transaction is one of the following:

*   [ ] Credit Card Payment for 100% Federal Election Activity
*   [ ] Staff Reimbursement for 100% Federal Election Activity
*   [ ] Payment to Payroll for 100% Federal Election Activity

_**When**_ I create the 'Redesignation to' transaction _**Or**_ later edit either the 'Redesignation to' or 'Reattribution from' transaction _**Then**_ the 'Save & and add memo' button will be hidden/disabled

### QA Notes ###

 
 - [x] BA/Design Quality Checklist complete

### DEV Notes ###

 
  Design

### Design ###

Current, with button:

!image-20240612-183600.png|width=75%,alt="image-20240612-183600.png"!    

![Image](https://github.com/fecgov/fecfile-web-app/assets/100313668/512937c6-3a35-419f-b3ef-51428bda7130)

New, without button:

!image-20240612-183621.png|width=75%,alt="image-20240612-183621.png"!

![Image](https://github.com/fecgov/fecfile-web-app/assets/100313668/1a3dacc2-bfbc-4933-bbca-8aeeabb0ae7a)

 See full ticket and images here: [FECFILE-398](https://fecgov.atlassian.net/browse/FECFILE-398)

**Comment by AureliaKhorsand** [comment]
@GreggMoreland can this ticket cover redesignation as well? And can you add in the affected transactions for testing?

**Comment by mary-tcg** [comment]
@MitchellTCG @AureliaKhorsand wires updated

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the "Save & add memo" button on the following reattribution transactions are not accessible and/or displayed.

Created Initial Transaction (below is showing Partnership Receipt transaction), then save to Transactions in this report table.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/e8c8eaad-0522-4e0c-8cee-e07847bd01b4)
____________________________________________________________________________________

Select "Reattribute" from the Actions dropdown list.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/f2d185fd-2db8-4c48-9efe-5e3d3c8f952f)
______________________________________________________________________________________

Verify the "Reattribution" page is displayed

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/757067c3-94fb-4394-8201-962ccd7ac63f)

_________________________________________________________________________________________

Verify the "Save & add memo" button on the following reattribution transaction is not accessible and/or displayed.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/06f1b66e-fd25-43ff-ad60-18ee4f991a67)

________________________________________________________________________________________

QA Review verified this functionality was implemented for the following "Reattribution" transactions.
*   [x] Partnership Receipt
*   [x] Joint Fundraising Transfer
*   [x] Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account
*   [x] Joint Fundraising Transfer - National Party Pres. Nominating Convention Account
*   [x] Joint Fundraising Transfer - National Party Headquarters Buildings Account
*   [x] Partnership Recount Account Receipt
*   [x] Partnership National Party Recount/Legal Proceedings Account
*   [x] Partnership National Party Headquarters Buildings Account
*   [x] Partnership National Party Pres. Nominating Convention Account

______________________________________________________________________________

QA Review verified this functionality was implemented for the following "Redesignation" transactions.

*   [x] Credit Card Payment for 100% Federal Election Activity
*   [x] Staff Reimbursement for 100% Federal Election Activity
*   [x] Payment to Payroll for 100% Federal Election Activity

QA Review Completed.   Moved to Stage Ready.
