### ISSUE TITLE
508: Fix Manage Report Header

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1923]
Business Reason

As a user with accessibility issues, I would like headers to be identified correctly to understand every page's hierarchy.

Task

*   [x] On the Reports page make sure "Manage reports" is an H1 (Currently a Span)
*   [x] change Recent reports from h5 to h2

### QA Notes ###
 
 - [x] BA/Design Quality Checklist complete

### DEV Notes ###
 
  Wireframe
![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/0a01c9ac-125e-4ef7-b5da-2b40ce278eef)

### Design ###
 
 null

[FECFILE-397](https://fecgov.atlassian.net/browse/FECFILE-397)

**Comment by Elaine-Krauss-TCG** [comment]
Changed to H1 and H2 respectively

![Image](https://github.com/fecgov/fecfile-web-app/assets/104506225/beb0a7da-9ba2-4a87-b7ba-bde5d5a69f9e)

**Comment by mjtravers** [comment]
@Elaine-Krauss-TCG The changes for this ticket were made in #1906 with the refactoring of the new app-table component which has been merged into the develop branch already. This ticket can move forward with #1906 without any branch merging.

**Comment by WiseQA** [comment]
QA review  verified:

 - [x] On the Reports page make sure "Manage reports" is an H1 (Currently a Span) was changed
 - [x] Recent reports from h5 to h2 was changed

Reference DEV screenshot above for visual.

QA Review Completed.   Moved to Stage Ready.
