### ISSUE TITLE
508: Make the Form type dropdown tabbable on the Create a new report modal

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1926]
Business Reason

As a user with accessibility issues, I would like the dropdown menu to be focused so that I know there are options to choose from.

Task

  On the Create a new report

*   [ ] Have a blue focus appear around the dropdown box when the user tabs to it.

1.  When tabbed to the dropdown is not highlight (focused)

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/4558203e-3017-4cc8-9102-d849a6cb9dfb](https://github.com/fecgov/fecfile-web-app/assets/25588182/4558203e-3017-4cc8-9102-d849a6cb9df))

1.  When the dropdown is selected the box is not highlight or focused even when the choices are displayed

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/613d71ae-500e-4322-9486-b848f28a5d6d](https://github.com/fecgov/fecfile-web-app/assets/25588182/613d71ae-500e-4322-9486-b848f28a5d6))

### QA Notes ###
 
  
  
 - [x] BA/Design Quality Checklist complete
- after the user tabs to the "Create a new report modal" dropdown the user should be able to make the dropdown appear by selecting "enter" from the keyboard

### DEV Notes ###
 
  
 null

### Design ###
 
  
 null

[FECFILE-396](https://fecgov.atlassian.net/browse/FECFILE-396)

**Comment by sasha-dresden** [comment]
@MitchellTCG  question on style consistency. I like the blue ring, which is what we use in most places, but I noticed the dropdown items have a black ring. Should I make it a blue ring like the close button and dropdown button?


https://github.com/fecgov/fecfile-web-app/assets/149604256/3f124b4f-2a72-4f7e-8ad0-8c2c20520fcc

**Comment by WiseQA** [comment]
QA review verified blue focus appears around the dropdown box when tabbing to the "Create a new report" modal.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/07ac0554-b178-42be-acb5-1c864d7a8c77)
________________________________________________________________________________________________________________________

Once tabbed to the "Create a new report" modal select enter from the keyboard the dropdown list will appear showing selectable form types.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/d87c65b3-48fd-4160-9451-2de5e57c80fc)

___________________________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
