### ISSUE TITLE
508: Make 48 hour report type tabbable and selectable

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1927]
Business Reason As a user with accessibility issues, I would like to be able to tab and select a report-type option when creating a Form 24.

Task On the Create a new report

*   [ ] Be able to tab through and select 24 hour or 48 hour. (_Currently only able to tab to 24 hour and then use the arrow key to get to 48 hour._)

### QA Notes ###

- [x] BA/Design Quality Checklist complete

### DEV Notes ###

Wireframe 

!image-20240617-175229.png|width=943,height=672,alt="image-20240617-175229.png"! [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-395)  

 

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/439cc06f-ccc5-475f-88c4-bdf99b74d784)

### Design ###

null

[FECFILE-395](https://fecgov.atlassian.net/browse/FECFILE-395)

**Comment by MitchellTCG** [comment]
@GreggMoreland PLS review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
