### ISSUE TITLE
Fix nightly e2e tests

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1928]
The e2e tests have been failing the nightly run since May 6.

The issue appears to be Cypress not being able to find the email input on the legacy login page. The issue is not occurring locally, only on CircleCI.

Error Message:

  ![image]([https://github.com/fecgov/fecfile-web-app/assets/2971785/eda1056c-9074-469b-b36a-e7cb6be76fd0](https://github.com/fecgov/fecfile-web-app/assets/2971785/eda1056c-9074-469b-b36a-e7cb6be76fd0))

### QA Notes ###
 
 null

### DEV Notes ###
 
 null

### Design ###
 
 null

[FECFILE-394](https://fecgov.atlassian.net/browse/FECFILE-394)

**Comment by lbeaufort** [comment]
On May 2, the e2e tests passed for the `release/sprint-41` branch. When I re-ran them today (5/15), they failed for the same commit: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app?branch=release%2Fsprint-41. One difference between the failing and passing tests:

On the `Setup a remote Docker engine` step:
**Passing**
```
Created container accessible with:
  DOCKER_HOST=unix:///var/run/docker.sock
  DOCKER_MACHINE_NAME=localhost
Server Engine Details:
  Version:          24.0.9
  API version:      1.43 (minimum version 1.12)
```
**Failing**
```
Created container accessible with:
  DOCKER_HOST=unix:///var/run/docker.sock
  DOCKER_MACHINE_NAME=localhost
Server Engine Details:
  Version:          26.0.2
  API version:      1.45 (minimum version 1.24)
```

Pinning the version to 24 in the Circle config resulted in [passing e2e tests](https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/5672/workflows/e53db6ad-04c0-42c9-910d-e03c5d2330c8/jobs/19601). The best guess I have so far is that the Docker API had a breaking change: https://docs.docker.com/engine/api/version-history/#v145-api-changes. Hotfix PRs in progress,

Additional follow-up ticket needed to get off the older docker version, ticket forthcoming.

**Comment by mjtravers** [comment]
@lbeaufort The CircleCI config.yml changes look good but I noticed while code reviewing that there is a Snyk issue being raised on the PR branches. I do not have access to see what the issue is.

**Comment by sasha-dresden** [comment]
Laura's fixes corrected the error. There were a couple failing tests that I fixed. Here is screenshot of passing nightly e2e


![Image](https://github.com/fecgov/fecfile-web-app/assets/149604256/894351ae-8672-4760-9f68-2f1869d277ec)

**Comment by WiseQA** [comment]
e2e tests nightly run failed May 17, 18 and 19.    Below screenshot of May 19th error's being reported.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/45188424-bc75-4d28-82c5-8a3f2549b859)

___________________________________________________________________________________________________________________________

@mjtravers @MitchellTCG @sasha-dresden moving back to In-Progress.

**Comment by mjtravers** [comment]
Passes CR and the nightly run. Moving to QA.

**Comment by WiseQA** [comment]
QA review verified nightly e2e tests passed 05/20/2024.    

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/d4d1b600-4875-4d5e-82f0-6e9565d0314d)

QA Review Completed.   Moved to Stage Ready.
