### ISSUE TITLE
UI: Update font size of "An official website of the United States government" banner

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1945]
Business Reason

The Banner needs to match the USDS Standards.

Tasks

*   [x] Change "An official website of the United States government" from 14.4px to ***13px***
*   [x] Change "Here's how you know" from 16px to ***13px***

1.  1.  The Banner Currently looks like...

![image-20240517-020326.png](/attachments/11249?name=image-20240517-020326.png) [See image in Jira]([https://fecgov.atlassian.net/browse/FECFILE-1380](https://fecgov.atlassian.net/browse/FECFILE-1380)) [See image in Jira]([https://fecgov.atlassian.net/browse/FECFILE-1380](https://fecgov.atlassian.net/browse/FECFILE-1380)) [See image in Jira]([https://fecgov.atlassian.net/browse/FECFILE-1380](https://fecgov.atlassian.net/browse/FECFILE-1380))

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/8e507452-078a-4fda-8645-a5a09980985c](https://github.com/fecgov/fecfile-web-app/assets/25588182/8e507452-078a-4fda-8645-a5a09980985))

1.  1.  Ideal State

![image-20240517-020216.png](/attachments/11248?name=image-20240517-020216.png)

1.  1.  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/2e303844-620a-4d41-9e95-e805c2787536](https://github.com/fecgov/fecfile-web-app/assets/25588182/2e303844-620a-4d41-9e95-e805c278753))

### QA Notes ###
 
  
  
 * [X] BA/Design Quality Checklist complete

### DEV Notes ###
 
  
  
  Wireframes

### Design ###
 
  
  
 null

[FECFILE-1380](https://fecgov.atlassian.net/browse/FECFILE-1380)

**Comment by MitchellTCG** [comment]
@GreggMoreland Pls review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified with UX the following changes were implemented.

* [x] Change "An official website of the United States government" from 14.4px to **13px**
* [x] Change "Here's how you know" from 16px to **13px**

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/bdad8cad-9b1e-497c-8491-6045e5dd22e2)

QA Review Completed.   Moved to Stage Ready.
