### ISSUE TITLE
UI: Fix Manage contacts H1

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1946]
Business Reason

  Make sure there is continuity across all H1's on the site

Tasks

*   [x] There should be 64px between the committee information (under the Committee Name) and the H1 "Manage contacts".
*   [x] Change Manage Contacts to ***Manage contacts***
*   [x] Remove the 16px to the left of Manage contacts
*   [x] Remove 20px right padding to "+ Add contact" button
*   [x] Remove 16px right padding to "Restore deleted contact(s)" button
*   [x] There should be 48px between Manage contacts and Contacts

1.  1.  Current State

![image-20240530-182846.png](/attachments/11277?name=image-20240530-182846.png)

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/be3772e8-bd9a-4686-957c-e77d98adc36a](https://github.com/fecgov/fecfile-web-app/assets/25588182/be3772e8-bd9a-4686-957c-e77d98adc36))

1.  1.  Ideal State

![image-20240530-182910.png](/attachments/11276?name=image-20240530-182910.png)

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/ebc09aa2-442f-4ebf-a5ee-c4e8eea1d63b](https://github.com/fecgov/fecfile-web-app/assets/25588182/ebc09aa2-442f-4ebf-a5ee-c4e8eea1d63))

### QA Notes ###
 
  
  
 - [x] BA/Design Quality Checklist complete

### DEV Notes ###
 
  
  
  Wireframes

### Design ###
 
  
  
 null

[FECFILE-1381](https://fecgov.atlassian.net/browse/FECFILE-1381)

**Comment by MitchellTCG** [comment]
@GreggMoreland pls review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by MitchellTCG** [comment]
@WiseQA 
looks good to me. I will make a ticket for moving the restore deleted contacts buttons so ignore that

**Comment by WiseQA** [comment]
QA review verified along with UX the following completed.

- [x] There should be 64px between the committee information (under the Committee Name) and the H1 "Manage contacts".
- [x] Change Manage Contacts to **Manage contacts**
- [x] Remove the 16px to the left of Manage contacts
- [x] Remove 20px right padding to "+ Add contact" button
- [x] Remove 16px right padding to "Restore deleted contact(s)" button
- [x] There should be 48px between Manage contacts and Contacts

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/5b868577-03d1-497a-8e8a-f231a45fab4a)

QA Review Completed.  Moved to Stage Ready.
