### ISSUE TITLE
UI: Fix Manage users H1, + Add user Button, and Capitalization in the H2

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1947]
Business Reason

  Make sure there is continuity across all H1's on the site

Tasks

*   [x] There should be 64px between the committee information (under the Committee Name) and the H1 "Manage users".
*   [x] Change Manage Users to ***Manage users***
*   [x] Remove the 16px to the left of Manage users
*   [x] Change the main color and hover color on the "+ Add User" Button to match the styling of the "+ Add contact" button on the Manage contacts page.
*   [x] Remove the 20px right padding to "+ Add user" button
*   [x] There should be 48px between Manage users and Existing users
*   [x] Change Existing Users to ***Existing users***

1.  1.  Current State

![image-20240530-204302.png](/attachments/11306?name=image-20240530-204302.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/055dd776-2436-4bf9-8176-1e85747b956a](https://github.com/fecgov/fecfile-web-app/assets/25588182/055dd776-2436-4bf9-8176-1e85747b956))

1.  1.  Ideal State

![image-20240530-204327.png](/attachments/11307?name=image-20240530-204327.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/53b76bf7-5e62-4a8e-abe3-747d8f4e8f9e](https://github.com/fecgov/fecfile-web-app/assets/25588182/53b76bf7-5e62-4a8e-abe3-747d8f4e8f9))

### QA Notes ###
 
  
  
 - [x] BA/Design Quality Checklist complete

### DEV Notes ###
 
  
  
  Wireframes

### Design ###
 
  
  
 null

[FECFILE-1382](https://fecgov.atlassian.net/browse/FECFILE-1382)

**Comment by MitchellTCG** [comment]
@GreggMoreland pls review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Manage users page the following was changed.

- [x] There should be 64px between the committee information (under the Committee Name) and the H1 "Manage users".
- [x] Change Manage Users to **Manage users**
- [x] Remove the 16px to the left of Manage users
- [x] Change the main color and hover color on the "+ Add User" Button to match the styling of the "+ Add contact" button on the Manage contacts page.
- [x]  Remove the 20px right padding to "+ Add user" button
- [x] There should be 48px between Manage users and Existing users
- [x] Change Existing Users to **Existing users**

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/a0af65d3-2d3a-4dd0-9c3c-d7e4d6e87f4e)

QA Review Completed.   Moved to Stage Ready.
