### ISSUE TITLE
UI: Fix Manage reports H1

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1948]
Business Reason

  Make sure there is continuity across all H1's on the site

Tasks

*   [x] There should be 64px between the committee information (under the Committee Name) and the H1 "Manage reports".
*   [x] Remove the 16px to the left of Manage reports
*   [x] Change text on "+ Create a new report" to "+ Create report"
*   [x] Remove 20px right padding to "+ Create report" button
*   [x] There should be 48px between Manage reports and Recent reports

1.  1.  Current State

![image-20240530-204133.png](/attachments/11304?name=image-20240530-204133.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/b945d043-ed07-4995-86ee-dbed299c0e78](https://github.com/fecgov/fecfile-web-app/assets/25588182/b945d043-ed07-4995-86ee-dbed299c0e7))

1.  1.  Ideal State

![image-20240530-204205.png](/attachments/11305?name=image-20240530-204205.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/9d094488-cddf-40d2-bfa5-3254e9cebe43](https://github.com/fecgov/fecfile-web-app/assets/25588182/9d094488-cddf-40d2-bfa5-3254e9cebe4))

/

### QA Notes ###
 
  
  
 - [x] BA/Design Quality Checklist complete

### DEV Notes ###
 
  
  
  Wireframes

### Design ###
 
  
  
 null

[FECFILE-1383](https://fecgov.atlassian.net/browse/FECFILE-1383)

**Comment by MitchellTCG** [comment]
@GreggMoreland pls review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Manage reports page the following was changed.

- [x] There should be 64px between the committee information (under the Committee Name) and the H1 "Manage reports".
- [x] Remove the 16px to the left of Manage reports
- [x] Change text on "+ Create a new report" to "+ Create report"
- [x] Remove 20px right padding to  "+ Create report" button
- [x] There should be 48px between Manage reports and Recent reports

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/db666d5c-f79c-42d6-a5ae-b7e29dc807bb)

QA Review Completed.  Moved to Stage Ready.
