### ISSUE TITLE
UI: Fix H1 on Transactions in this report

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1949]
Business Reason

  Make sure there is continuity across all H1's on the site

Tasks

*   [x] There should be 64px between the committee information (under the Committee Name) and the H1 "Transactions in this report".
*   [x] Remove the 16px to the left of "Transactions in this report" and "Form 3X: ..."
*   [x] Add 2px line below Mange transaction and form info
*   [x] Change text on "+ Add new transaction" to "***+ Add transaction***"
*   [x] Remove 20px right padding to ***+ Add transaction*** button
*   [x] Make the to of the + Add transaction button align with Transactions in this report
*   [x] There should be 48px between Transactions in this report and the 2px line

1.  1.  Current State

![image-20240530-203959.png](/attachments/11303?name=image-20240530-203959.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/8d25f271-824f-472a-b92e-2a557c6cd6d0](https://github.com/fecgov/fecfile-web-app/assets/25588182/8d25f271-824f-472a-b92e-2a557c6cd6d))

1.  1.  Ideal State

![image-20240530-204036.png](/attachments/11302?name=image-20240530-204036.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/f955ca24-277c-446c-ab36-286f52fca342](https://github.com/fecgov/fecfile-web-app/assets/25588182/f955ca24-277c-446c-ab36-286f52fca34))

### QA Notes ###
 
  
  
 - [x] BA/Design Quality Checklist complete

### DEV Notes ###
 
  
  
  Wireframes

### Design ###
 
  
  
 null

[FECFILE-1384](https://fecgov.atlassian.net/browse/FECFILE-1384)

**Comment by MitchellTCG** [comment]
@GreggMoreland pls Review

**Comment by sasha-dresden** [comment]
@MitchellTCG I was looking into this and I had a few questions.
The "Add 2px line below Mange transaction and form info". I'm guessing that's referring to new line being added below the toolbar. I just wanted to confirm if we want this as this line is not included in #1946 and #1948. Or maybe the line should be added there? Or maybe it's correct as is, considering the Transaction List is a bit unique in having 3 tables on it.

My second question about that line is how much space should be between the Form3X text and the new line? It says:
"There should be 48px between Transactions in this report and the 2px line" but that doesn't look right based on the screenshot. Looks more like 8px between the form 3x and the 2px line. Based on the text in the other two tickets, I think this 48px is referring to the space between the bottom of the new 2px line and the top of "Receipts"

**Comment by MitchellTCG** [comment]
> @MitchellTCG I was looking into this and I had a few questions. The "Add 2px line below Mange transaction and form info". I'm guessing that's referring to new line being added below the toolbar. I just wanted to confirm if we want this as this line is not included in #1946 and #1948. Or maybe the line should be added there? Or maybe it's correct as is, considering the Transaction List is a bit unique in having 3 tables on it.

The line is there when there is a subhead. So since Form 3X: June 20... is there, I would like a horizontal rule

**Comment by MitchellTCG** [comment]
> My second question about that line is how much space should be between the Form3X text and the new line? It says: "There should be 48px between Transactions in this report and the 2px line" but that doesn't look right based on the screenshot. Looks more like 8px between the form 3x and the 2px line. Based on the text in the other two tickets, I think this 48px is referring to the space between the bottom of the new 2px line and the top of "Receipts"

This is correct 48 px between the HR and receipt

THX

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Transactions in this report page the following was changed.

- [x] There should be 64px between the committee information (under the Committee Name) and the H1 "Transactions in this report".
- [x] Remove the 16px to the left of "Transactions in this report" and "Form 3X: ..."
- [x] Add 2px line below Mange transaction and form info
- [x] Change text on "+ Add new transaction" to "**+ Add transaction**"
- [x] Remove 20px right padding to **+ Add transaction** button
- [x] Make the to of the + Add transaction button align with Transactions in this report
- [x] There should be 48px between Transactions in this report and the 2px line

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/f5d1b17e-5667-4405-bf00-5014cca7af86)

QA Review Completed.   Moved to Stage Ready.
