### ISSUE TITLE
UI: Update Manage report data table column headers

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1950]
Business Reason

  Make sure column headers are named in a consistent manner

Tasks

*   [x] Change "Form type" to "***Form***"
*   [x] Change "Type of report" to "***Type***"
*   [x] Change "Coverage dates" to "***Coverage***"
*   [x] Change "Date filed" to "***Filed***"

1.  1.  Current State

![image-20240530-203850.png](/attachments/11301?name=image-20240530-203850.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/d7125304-d229-4bea-9e61-00d53cc15cd2](https://github.com/fecgov/fecfile-web-app/assets/25588182/d7125304-d229-4bea-9e61-00d53cc15cd))

1.  1.  Ideal State

![image-20240530-203914.png](/attachments/11300?name=image-20240530-203914.png)

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/69cc88fa-b371-4e63-a5b8-98e08614acfb](https://github.com/fecgov/fecfile-web-app/assets/25588182/69cc88fa-b371-4e63-a5b8-98e08614acf))

### QA Notes ###
 
  
  
 - [x] BA/Design Quality Checklist complete

### DEV Notes ###
 
  
  
  Wireframe

### Design ###
 
  
  
 null

[FECFILE-1385](https://fecgov.atlassian.net/browse/FECFILE-1385)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
pls review

**Comment by mjtravers** [comment]
Passes CR. Sending To QA.

**Comment by MitchellTCG** [comment]
@WiseQA 
looks good to me

**Comment by WiseQA** [comment]
QA review verified Manage reports table the following table labels were changed.

- [x] Change "Form type" to "**Form**"
- [x] Change "Type of report" to "**Type**"
- [x] Change "Coverage dates" to "**Coverage**"
- [x] Change "Date filed" to "**Filed**"

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/6dd3d5e2-8ed4-4536-af46-d5a16783e449)

QA Review Completed.   Moved to Stage Ready.
