### ISSUE TITLE
UI: Update Transactions in this report data table column headers

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1951]
Business Reason

  Make sure column headers are named in a consistent manner

Tasks

  On Loans and debts table

*   [x] Change "Date incurred" to "***Incurred***"

1.  1.  Current State

![image-20240530-203651.png](/attachments/11298?name=image-20240530-203651.png)

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/ef573cc5-53dc-4335-8d05-7c2e36e10460](https://github.com/fecgov/fecfile-web-app/assets/25588182/ef573cc5-53dc-4335-8d05-7c2e36e1046))

1.  1.  Ideal State

![image-20240530-203728.png](/attachments/11299?name=image-20240530-203728.png)

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/76ca522f-579a-4152-a4ff-4c2bac6fa7a0](https://github.com/fecgov/fecfile-web-app/assets/25588182/76ca522f-579a-4152-a4ff-4c2bac6fa7a))

### QA Notes ###
 
  
  
 - [x] BA/Design Quality Checklist complete

### DEV Notes ###
 
  
  
  Wireframe

### Design ###
 
  
  
 null

[FECFILE-1386](https://fecgov.atlassian.net/browse/FECFILE-1386)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
pls review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by MitchellTCG** [comment]
@WiseQA this looks good to me

**Comment by WiseQA** [comment]
QA review verified On Loans and debts table "Date incurred" was changed to "Incurred".

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/7b01e507-f2b1-4915-85e8-6328cee899ec)

QA Review Completed.  Moved to Stage Ready.
