### ISSUE TITLE
UI: Fix location on column sorts on all Tables

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1953]
Business Reason

  To make tables functionality to mimic FEC.gov

Tasks

  Right justify arrows and dashes inside the header columns

*   [x] Transaction history
*   [x] Existing users
*   [x] Restore deleted contact(s)
*   [x] Contacts
*   [x] Guarantors
*   [x] Loans and debts
*   [x] Disbursements
*   [x] Receipts
*   [x] Recent reports

1.  Current state

![image-20240530-175750.png](/attachments/11266?name=image-20240530-175750.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/c1f4322e-53c9-40ae-9b39-a35680575a45](https://github.com/fecgov/fecfile-web-app/assets/25588182/c1f4322e-53c9-40ae-9b39-a35680575a4))

![image-20240530-175839.png](/attachments/11270?name=image-20240530-175839.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/882352cc-e6eb-48b3-8687-d2ce25001ec4](https://github.com/fecgov/fecfile-web-app/assets/25588182/882352cc-e6eb-48b3-8687-d2ce25001ec))

![image-20240530-175920.png](/attachments/11268?name=image-20240530-175920.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/86c44623-add4-4772-9c07-f3ac0e4f73d9](https://github.com/fecgov/fecfile-web-app/assets/25588182/86c44623-add4-4772-9c07-f3ac0e4f73d))

![image-20240530-180053.png](/attachments/11275?name=image-20240530-180053.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/827eb1d5-1fef-4327-af8e-484f501879f4](https://github.com/fecgov/fecfile-web-app/assets/25588182/827eb1d5-1fef-4327-af8e-484f501879f))

![image-20240530-180541.png](/attachments/11272?name=image-20240530-180541.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/f03badbb-a2f1-46df-b81e-bd8ebb86dab9](https://github.com/fecgov/fecfile-web-app/assets/25588182/f03badbb-a2f1-46df-b81e-bd8ebb86dab))

![image-20240530-180616.png](/attachments/11273?name=image-20240530-180616.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/35fb7769-5a13-4d13-b709-b0475b5d5d4b](https://github.com/fecgov/fecfile-web-app/assets/25588182/35fb7769-5a13-4d13-b709-b0475b5d5d4))

![image-20240530-180827.png](/attachments/11274?name=image-20240530-180827.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/e7b43b30-fb82-422c-b2be-eb897b848e36](https://github.com/fecgov/fecfile-web-app/assets/25588182/e7b43b30-fb82-422c-b2be-eb897b848e3))

![image-20240530-180900.png](/attachments/11271?name=image-20240530-180900.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/ee3d97df-a936-406c-b9d6-c7fe47f7ed4a](https://github.com/fecgov/fecfile-web-app/assets/25588182/ee3d97df-a936-406c-b9d6-c7fe47f7ed4))

![image-20240530-180926.png](/attachments/11267?name=image-20240530-180926.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/1ef0dbc6-cf4c-400a-aecf-25f0349a7c30](https://github.com/fecgov/fecfile-web-app/assets/25588182/1ef0dbc6-cf4c-400a-aecf-25f0349a7c3))

1.  Ideal state

![image-20240530-180956.png](/attachments/11269?name=image-20240530-180956.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/7b4b1312-5e70-4f4f-aafe-946eae698cd4](https://github.com/fecgov/fecfile-web-app/assets/25588182/7b4b1312-5e70-4f4f-aafe-946eae698cd))

### QA Notes ###
 
  
  
  
 - [x] BA/Design Quality Checklist complete

### Design ###
 
  
  
 null

 See full ticket and images here: [FECFILE-1388](https://fecgov.atlassian.net/browse/FECFILE-1388)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
pls review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified location of column sorts for tables were changed to Right justify arrows and dashes inside the header columns

- [x] Transaction history
- [x] Existing users
- [x] Restore deleted contact(s)
- [x] Contacts
- [x] Guarantors
- [x] Loans and debts
- [x] Disbursements
- [x] Receipts
- [x] Recent reports

Screenshot of Manage reports table showing this change.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/f1e11442-b045-48b8-8794-82925c26959f)

____________________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
