### ISSUE TITLE
UI: Add vertical divider lines between table columns

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1954]
Business Reason

  Try to create continuity between FECFile and FEC.gov tables

Tasks

  Add vertical lines between table columns. Vertical lines should be 1px wide, and this color #F1F1F1\. there should be no vertical line on the edges of the table.

*   [x] Transaction history
*   [x] Existing users
*   [x] Restore deleted contact(s)
*   [x] Contacts
*   [x] Guarantors
*   [x] Loans and debts
*   [x] Disbursements
*   [x] Receipts
*   [x] Recent reports

Wireframes

  Ideal state

![image-20240530-174241.png](/attachments/11265?name=image-20240530-174241.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/4e4065ea-e2d4-4db4-a6c4-ce8939c90de1](https://github.com/fecgov/fecfile-web-app/assets/25588182/4e4065ea-e2d4-4db4-a6c4-ce8939c90de))

### QA Notes ###
 
  
 - [x] BA/Design Quality Checklist complete

### DEV Notes ###
 
  
 use p-datatable-gridlines to impliment: https://www.primefaces.org/primeng-v16-lts/table#gridlines

### Design ###
 
  
 null

[FECFILE-1389](https://fecgov.atlassian.net/browse/FECFILE-1389)

**Comment by MitchellTCG** [comment]
@GreggMoreland pls review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by MitchellTCG** [comment]
@WiseQA 

looks good to me

**Comment by WiseQA** [comment]
QA review verified with UX Vertical lines should be 1px wide, and this color #F1F1F1.  Vertical divider lines were added between table columns.   Verified no vertical line on the edges of the table.   

- [x] Transaction history
- [x] Existing users
- [x] Restore deleted contact(s)
- [x] Contacts
- [x] Guarantors
- [x] Loans and debts
- [x] Disbursements
- [x] Receipts
- [x] Recent reports

_____________________________________________________________________________________________________

Screenshot of Manage reports table showing changes.  

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/9007aaa9-3a57-4a44-ada6-42d485148906)

_____________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
