### ISSUE TITLE
"Memo" column for Receipts / Disbursements

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1975]
During testing on the "Transactions in this report" table the "Memo" column for Receipts / Disbursements is not sorting correctly. (Tested on STAGE and DEV)

_**MEMO SORT FOR RECEIPTS/DISBURSEMENTS**_

1\. When Memo column "-" and no transaction is associated with a Memo, the column still sorts.

2\. Select "Memo" column for Receipts with transactions showing no memo's associated then select sort, the table sorting.

a. Screenshot below before selecting memo and sort:

[[![](/attachments/11294?name=image-20240530-193831.png) [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1398)| /attachments/11294?name=image-20240530-193831.png] [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1398)| /attachments/11294?name=image-20240530-193831.png] See image in Jira

[![](https://github.com/fecgov/fecfile-web-app/assets/96139912/c199833e-5cea-4189-a13f-9535166976aa%5D(https://github.com/fecgov/fecfile-web-app/assets/96139912/c199833e-5cea-4189-a13f-9535166976a))](https://github.com/fecgov/fecfile-web-app/assets/96139912/c199833e-5cea-4189-a13f-9535166976aa%5D(https://github.com/fecgov/fecfile-web-app/assets/96139912/c199833e-5cea-4189-a13f-9535166976a))

b. Screenshot below after selecting memo and sort:

[[!image-20240530-193942.png! [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1398)| /attachments/11297?name=image-20240530-193942.png] [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1398)| /attachments/11297?name=image-20240530-193942.png]

[![](https://github.com/fecgov/fecfile-web-app/assets/96139912/327fab93-80c6-4079-bde2-deab3167595a%5D(https://github.com/fecgov/fecfile-web-app/assets/96139912/327fab93-80c6-4079-bde2-deab3167595))](https://github.com/fecgov/fecfile-web-app/assets/96139912/327fab93-80c6-4079-bde2-deab3167595a%5D(https://github.com/fecgov/fecfile-web-app/assets/96139912/327fab93-80c6-4079-bde2-deab3167595))

3\. Select "Memo" column for Disbursements with transactions showing no memo's associated then select sort, the table sorting.

a. Screenshot below before selecting memo and sort:

[!image-20240530-194029.png!| /attachments/11296?name=image-20240530-194029.png]

[![](https://github.com/fecgov/fecfile-web-app/assets/96139912/9095283e-c2cc-4223-b54a-3959539b6b2a%5D(https://github.com/fecgov/fecfile-web-app/assets/96139912/9095283e-c2cc-4223-b54a-3959539b6b2))](https://github.com/fecgov/fecfile-web-app/assets/96139912/9095283e-c2cc-4223-b54a-3959539b6b2a%5D(https://github.com/fecgov/fecfile-web-app/assets/96139912/9095283e-c2cc-4223-b54a-3959539b6b2))

b. Screenshot below after selecting memo and sort:

[!image-20240530-194113.png!| /attachments/11295?name=image-20240530-194113.png]

[![](https://github.com/fecgov/fecfile-web-app/assets/96139912/d98c9e54-519b-4281-bd22-7eeb2d564c25%5D(https://github.com/fecgov/fecfile-web-app/assets/96139912/d98c9e54-519b-4281-bd22-7eeb2d564c2))](https://github.com/fecgov/fecfile-web-app/assets/96139912/d98c9e54-519b-4281-bd22-7eeb2d564c25%5D(https://github.com/fecgov/fecfile-web-app/assets/96139912/d98c9e54-519b-4281-bd22-7eeb2d564c2))

@MitchellTCG @mjtravers fix "Memo" sort "column for Receipts / Disbursements on the "Transactions in this report" table. Bug found in testing for Sprint 43\. Pointed 3 points and assigned to Sprint 43.

### QA Notes ###

 
  
  
 null

### DEV Notes ###

 
  
  
 null

### Design ###

 
  
  
 null

[FECFILE-1398](https://fecgov.atlassian.net/browse/FECFILE-1398)

**Comment by dheitzer** [comment]
@WiseQA can say what environment and committee id this was? I think the reason we are seeing the difference in order is not because memo is being sorted on (since all the data is the same) but actually because the Line column sort is being removed (due to only sorting on one column at a time).  This would be expected behavior and we would need to add support for multi-field sorting to prevent it.  I wanted to confirm with the data you were using first though before definitively saying this is what is occurring.  Thanks.

**Comment by WiseQA** [comment]
@dheitzer I used Committee ID:

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/d9172f06-c487-4b97-86f4-d419886cf8a

Just retested on DEV this morning using the same Committee ID.    Meeting to discuss issue.

**Comment by Elaine-Krauss-TCG** [comment]
This problem is actually a bit more complicated than it looks at face value.  What's _currently_ happening is that when all transactions in a table have the same memo_code value, secondary sorting is applied.  Making it so that sorting will have no visible changes if all transactions have the same memo code value would be very complicated.  We could disable the memo_code sorting button when all transactions in that table have the same value, but this requires a check on the back-end because the front-end only knows what transactions are present on the current page.  This can definitely be done, but doing this while mitigating the performance impact will likely require more dev effort than expected for a 3-pointer.

**Comment by Elaine-Krauss-TCG** [comment]
Custom sorting has been implemented to ensure that ordering does not change if all transactions in a given category have the same memo_code value.

Sorting works when there are transactions with memo_code and without
![Image](https://github.com/fecgov/fecfile-web-app/assets/104506225/56a48ee0-d051-41d8-b5bb-f6b1d3b0884b)
![Image](https://github.com/fecgov/fecfile-web-app/assets/104506225/a6ea0405-e8ed-4c4c-b651-0cdb15e07489)

Nothing changes when they're all the same
![Image](https://github.com/fecgov/fecfile-web-app/assets/104506225/c1cbf759-7ea8-4e47-a04d-e93220cfb139)
![Image](https://github.com/fecgov/fecfile-web-app/assets/104506225/34bad33f-2bc5-4394-a254-1634b7be8f73)

**Comment by mjtravers** [comment]
From CR, let's refactor the use of test data out of the Django fixtures and into the utils functions.

Sending back to In Progress.

**Comment by mjtravers** [comment]
Unit tests updated and expanded. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA tested bug fix verifying changes have been implemented using Committee ID: C00100263 on DEV.

MEMO SORT FOR RECEIPTS/DISBURSEMENTS

1. Selected sorting Memo column for Disbursement showing no memo's associated with transactions "-" the column does not sort on the  "-".   

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/155367ed-fe9e-419b-b5c3-5f125a7c3a34)
________________________________________________________________________________________

2. Selected "Memo" column for Receipts with transactions showing "Y' and "-" for memo's the table is sorting correctly

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/2b34da01-b526-4f03-a82a-d3a7749844e2)

_______________________________________________________________________________________

QA Review Completed.  Moved to Stage Ready.
