### ISSUE TITLE
Candidate State field does not stay saved for "Presidential" candidate when creating Independent Expenditure transaction

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1978]
Candidate State field does not stay saved for "Presidential" candidate when creating Independent Expenditure transaction. Tested on DEV environment using Committee ID TEST_COMMITTEE_NAME8

1\. Created Multistate Independent Expenditure transaction.

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/0dda7d85-aca4-48d6-99c3-1595f1773360](https://github.com/fecgov/fecfile-web-app/assets/94924171/0dda7d85-aca4-48d6-99c3-1595f177336))

___________________________________________________________________________________________________________

2\. Entered a "Presidential" candidate and entered "Candidate State" required field then select save.

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/96fef5bf-b4fc-4a36-8767-651355ecbf64](https://github.com/fecgov/fecfile-web-app/assets/94924171/96fef5bf-b4fc-4a36-8767-651355ecbf6))

___________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/8a85e825-2208-4b19-a5df-986955351032](https://github.com/fecgov/fecfile-web-app/assets/94924171/8a85e825-2208-4b19-a5df-98695535103))

_________________________________________________________________________________________________________

3\. Reopened the saved transaction the "Candidate State" field does not stay saved. (This is the DEFECT)

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/40dbb0f6-4c0c-4036-a126-455f2d5b592e](https://github.com/fecgov/fecfile-web-app/assets/94924171/40dbb0f6-4c0c-4036-a126-455f2d5b592))

__________________________________________________________________________________________________________

@MitchellTCG @mjtravers fix "Candidate State" field should save. Defect found in testing for Sprint 43\. Pointed 3 point and assigned to Sprint 43.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-1401](https://fecgov.atlassian.net/browse/FECFILE-1401)

**Comment by dheitzer** [comment]
@WiseQA @AureliaKhorsand I was looking at the original requirements in [ticket 1118](https://github.com/fecgov/fecfile-web-app/issues/1118) and it seems like this is behaving properly per the following:
`
CANDIDATE STATE (Required If CANDIDATE OFFICE = President and the Election Code = P-Primary)`

Just wanted to clarify I'm looking in the right place.  Thanks.

**Comment by AureliaKhorsand** [comment]
@dheitzer that's correct, and Multistate IEs will always default to a primary. It looks like it's working as expected.

**Comment by dheitzer** [comment]
@AureliaKhorsand thanks for checking!

**Comment by WiseQA** [comment]
Please put this ticket back to QA bucket so I can reverify - thanks



*Shelly Wise*
*QA/Test Engineer*
*Tygart Technology*
***@***.*** ***@***.***>*
*304-657-9070*
*CMMI - ITIL - ISO 9001:2015 - Agile/SAFe*

**Comment by WiseQA** [comment]
Moving ticket back to QA review, to retest Multistate, as working correctly.   Per BA review the "State" is a required field not "Read Only"

Retesting - Thanks everyone

**Comment by mjtravers** [comment]
Added a comment to the [PR](https://github.com/fecgov/fecfile-web-api/pull/904) during CR. 

Sending ticket back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified fix for defect.  Retested and the Candidate State field stays saved for "Presidential" candidate when creating Multistate  Independent Expenditure transaction.   Tested using TEST_COMMITTEE_NAME16 on STAGE environment.  

____________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/77f1bfc7-603b-4ced-8107-c4b1c4b7c593)

__________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/730dd8d6-a172-4429-b9d6-6511fde2a06a)

________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
