### ISSUE TITLE
UI: Bold Action kebobs

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1979]
1.  Business Reason To make the action kebob more noticeable for users

1.  Tasks Bold the pi-ellipsis icon. Change from "font-weight: 400" to "font-weight: 900"

*   [x] Manage reports
*   [x] Manage users
*   [x] Transactions in this report
*   [x] Manage contacts

1.  Current state

[[[![](/attachments/11281?name=image-20240530-192545.png) [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1402)| /attachments/11281?name=image-20240530-192545.png] [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1402)| /attachments/11281?name=image-20240530-192545.png] [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1402)| /attachments/11281?name=image-20240530-192545.png]

[![](https://github.com/fecgov/fecfile-web-app/assets/25588182/6fb452a3-4ccc-4a66-8531-1b28d5865263%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/6fb452a3-4ccc-4a66-8531-1b28d586526))](https://github.com/fecgov/fecfile-web-app/assets/25588182/6fb452a3-4ccc-4a66-8531-1b28d5865263%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/6fb452a3-4ccc-4a66-8531-1b28d586526))

1.  Ideal state

[[[!image-20240530-192609.png! [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1402)| /attachments/11282?name=image-20240530-192609.png] [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1402)| /attachments/11282?name=image-20240530-192609.png] [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1402)| /attachments/11282?name=image-20240530-192609.png]

[![](https://github.com/fecgov/fecfile-web-app/assets/25588182/fa8a5b12-3851-4547-ba9d-ab3a908e6c58%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/fa8a5b12-3851-4547-ba9d-ab3a908e6c5))](https://github.com/fecgov/fecfile-web-app/assets/25588182/fa8a5b12-3851-4547-ba9d-ab3a908e6c58%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/fa8a5b12-3851-4547-ba9d-ab3a908e6c5))

### QA Notes ###

 
  
  
  
 - [x] BA/Design Quality Checklist complete

### Design ###

 
 null

[FECFILE-1402](https://fecgov.atlassian.net/browse/FECFILE-1402)

**Comment by MitchellTCG** [comment]
@GreggMoreland pls review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers per ticket review please add "Delete" in the dropdown as an option for the Manage users table.  (NOTE:  Use same "Delete" format as used in the Contacts page)

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/a6519cf6-8719-40a9-a4f5-13f7d9a38ecf)
____________________________________________________________________________________________________
 
Returned to In-Progress for above fix.

**Comment by sasha-dresden** [comment]
@WiseQA, "Delete" appears to already an option for the Manage Users page, as long as the user you are attempting to delete isn't yourself.

![Image](https://github.com/fecgov/fecfile-web-app/assets/149604256/ccb0cb4d-5f93-48f6-ac4b-63fc1593c501)

**Comment by WiseQA** [comment]
@mjtravers @sasha-dresden Matt please update Sasha with our findings this morning please - thanks.    The actions box is not to be empty and even though cannot delete yourself the word Delete to appear in box and the format is the same as Manage contacts page.   Thanks !

**Comment by sasha-dresden** [comment]
Thanks for the clarification. Got it set up so the Delete option will be visible but disabled for the current user, rather than hidden altogether.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "Delete" option will be visible but disabled for the current user.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/751d5461-fbdc-4fc2-9599-70c3c1d10a18)
__________________________________________________________________________________

QA review verified the following tables kabob action list have been bolded per UX design.

*   [x] Manage reports
*   [x] Manage users
*   [x] Transactions in this report
*   [x] Manage contacts
___________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
