### ISSUE TITLE
UI: Update Table Headers

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1980]
1.  Business Reason Update headers to be more succinct

1.  Tasks

Restore deleted contacts

*   [x] Change Restore deleted contact(s) to Restore deleted contacts (both locations)
*   [x] Change "Contact name" to "_**Name**_"
*   [x] Change "Contact Type" to "_**Type**_"
*   [x] Change "Contact Employer" to "_**Employer**_"
*   [x] Change "Contact Occupation" to "_**Occupation**_"

Transaction history

*   [x] Change "Transaction type" to "_**Type**_"
*   [x] Change "Form Type" to "_**Form**_"
*   [x] Change "Report Type" to "_**Report**_"

1.  ## Current State

[current-state](#current-state)

[current-state](#current-state)

[[!image-20240530-172837.png! [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1403)| /attachments/11262?name=image-20240530-172837.png] [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1403)| /attachments/11262?name=image-20240530-172837.png]

[![](https://github.com/fecgov/fecfile-web-app/assets/25588182/ff370136-1d64-46dc-81fd-37e214e993c9%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/ff370136-1d64-46dc-81fd-37e214e993c))](https://github.com/fecgov/fecfile-web-app/assets/25588182/ff370136-1d64-46dc-81fd-37e214e993c9%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/ff370136-1d64-46dc-81fd-37e214e993c))

[![](/attachments/11263?name=image-20240530-172918.png) [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1403)| /attachments/11263?name=image-20240530-172918.png]

[![](https://github.com/fecgov/fecfile-web-app/assets/25588182/c4d4fefe-2732-462c-a422-ca8fdc41d5ca%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/c4d4fefe-2732-462c-a422-ca8fdc41d5c))](https://github.com/fecgov/fecfile-web-app/assets/25588182/c4d4fefe-2732-462c-a422-ca8fdc41d5ca%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/c4d4fefe-2732-462c-a422-ca8fdc41d5c))

1.  ## Ideal State

[ideal-state](#ideal-state)

[ideal-state](#ideal-state)

[!image-20240530-172946.png!| /attachments/11261?name=image-20240530-172946.png]

[![](https://github.com/fecgov/fecfile-web-app/assets/25588182/b71e08c2-aab0-4be7-a3a0-7f829db2661e%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/b71e08c2-aab0-4be7-a3a0-7f829db2661))](https://github.com/fecgov/fecfile-web-app/assets/25588182/b71e08c2-aab0-4be7-a3a0-7f829db2661e%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/b71e08c2-aab0-4be7-a3a0-7f829db2661))

[!image-20240530-173013.png!| /attachments/11264?name=image-20240530-173013.png]

[![](https://github.com/fecgov/fecfile-web-app/assets/25588182/90773a5a-ef2e-4d6c-8168-96c0c3b5e23b%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/90773a5a-ef2e-4d6c-8168-96c0c3b5e23))](https://github.com/fecgov/fecfile-web-app/assets/25588182/90773a5a-ef2e-4d6c-8168-96c0c3b5e23b%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/90773a5a-ef2e-4d6c-8168-96c0c3b5e23))

### QA Notes ###

 
  
 - [x] BA/Design Quality Checklist complete

### DEV Notes ###

 
  
  Wireframe

### Design ###

 
  
 null

[FECFILE-1403](https://fecgov.atlassian.net/browse/FECFILE-1403)

**Comment by MitchellTCG** [comment]
@GreggMoreland pls review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the following labels on the "Restored deleted contacts" page were changed.

Restore deleted contacts

*   [x] Change Restore deleted contact(s) to Restore deleted contacts (both locations)
*   [x] Change "Contact name" to "_**Name**_"
*   [x] Change "Contact Type" to "_**Type**_"
*   [x] Change "Contact Employer" to "_**Employer**_"
*   [x] Change "Contact Occupation" to "_**Occupation**_"

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/368510f3-a405-4fd4-9e6c-13f8e0e1213e)
________________________________________________________________________________

QA review verified the following labels on the "Transaction history" page were changed.

*   [x] Change "Transaction type" to "_**Type**_"
*   [x] Change "Form Type" to "_**Form**_"
*   [x] Change "Report Type" to "_**Report**_"

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/a250c989-49d3-4c3e-a3ea-83c6a670eecb)

_________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
