### ISSUE TITLE
System to prevent user from deleting an amended report

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1982]
Business Reason

As a user, I will NOT be able to delete a report that has been amended so that I can retain data that feeds into future reports.

Acceptance Criteria

_**Given**_ the user is on the 'Manage reports' page, _**If**_ a report is _amended_, regardless of status or version, _**Then**_ the 'delete' option on the action kebab will not be available. (A report must be in-progress AND original to be deleted).

### QA Notes ###

 
 * original requirements to delete a report were in [https://fecgov.atlassian.net/browse/FECFILE-1133|https://fecgov.atlassian.net/browse/FECFILE-1133|smart-link] (#386) 
* [x] BA/Design Quality Checklist complete

### DEV Notes ###

 
 * original ticket to delete a report, [https://fecgov.atlassian.net/browse/FECFILE-1133|https://fecgov.atlassian.net/browse/FECFILE-1133|smart-link] (#386) did not distinguish between first time reports and amended reports.
 * The options should be disabled in the kabob on the front end as well as **blocked in the back end at the delete endpoint**.

 

### Design ###

 
**Current state**

!image-20240611-184643.png|width=78.32811956899549%,alt="image-20240611-184643.png"!       
![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/e6fcef6d-0611-4bf2-8f59-559e42486515)

 **Ideal state**

!image-20240611-184706.png|width=78.32811956899549%,alt="image-20240611-184706.png"!
![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/0d326719-a992-4f0f-9401-1cdbf86de792)

**Explanation:**
If the Amendment is in progress, the user will not see the option to delete it.
  

 See full ticket and images here: [FECFILE-1407](https://fecgov.atlassian.net/browse/FECFILE-1407)

Pull Request: https://github.com/fecgov/fecfile-web-api/pull/911

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg this should be a quick one - just a wire showing the "delete" greyed out for an amended report that is in progress.

**Comment by mary-tcg** [comment]
@MitchellTCG thoughts?

![Image](https://github.com/fecgov/fecfile-web-app/assets/100313668/25c02349-92a1-400b-a3c1-2c3ae1e45e8e)

**Comment by MitchellTCG** [comment]
@mary-tcg looks good to me
@JonellaCulmer you cool with this?

**Comment by JonellaCulmer** [comment]
@mary-tcg Please change "View" to "Review". Otherwise good to go.

**Comment by mary-tcg** [comment]
Upon reviewing the current dropdown in the system, there is already an absence ofthe  "delete" option in this use case. Dropdown update is on hold while we validate some requirements. 

![Image](https://github.com/fecgov/fecfile-web-app/assets/100313668/9ea19a84-c446-4f73-b843-6a236ce06376)

**Comment by AureliaKhorsand** [comment]
@mary-tcg the report you used in your example above was the status "Submission success". What this ticket is saying is that the delete option should not be there for an amendment with a status of "In-progress".

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Wire in the body of the ticket.

**Comment by mjtravers** [comment]
From CR: Need unit tests on the reports.models.can_delete() method. This will be important as we're most likely going to refactor the method and how we determine if a report can be deleted for better performance.

Sending back to In Progress.

**Comment by sasha-dresden** [comment]
Added unit tests for can_delete

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers per comment above where their unit tests developed and passed for "Need unit tests on the reports.models.can_delete() method".   If so can we put unit tests passing in this ticket ?

**Comment by WiseQA** [comment]
QA review verified on the "Manage reports" page, If a report is amended, regardless of status or version, the "delete" option on the action kebab does not appear.  (Tested using a Form 24)

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/dab514e8-1ca9-4c97-941f-0002c59cedbc)
__________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/b87f9f4e-6aea-48d2-89f0-00ec90129814)
______________________________________________________________________________

Verified a report on the "Manage reports" page with status of "In-progress" and Version "Original" the option to "Delete" the report is displayed and accessible.  (Tested using a Form 24)

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/496961ef-8cf4-4aea-988d-17454ac70b56)

___________________________________________________________________________________

Verified unable to delete a Form 3x if linked to a Form 24 and does not contain any linked transactions to a future report (e.g., Schedule C, D) per ticket #386. 

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/28bc549a-4bc1-4115-913f-9e008ba3bad4)
____________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
