### ISSUE TITLE
UI: Remove H2 from Manage user page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1988]
1.  Business Reason

As the UX Lead, I do not believe an H2 is necessary for the "Manage user" page to convey what information is found there. However, the data table will need to keep its current title so users with accessibility issues will know what data is in it.

1.  Acceptance Criteria

Wireframes

1.  ## Current State

[current-state](#current-state)

[![](/attachments/11332?name=image-20240603-152343.png) [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1414)| /attachments/11332?name=image-20240603-152343.png] See image in Jira [![](https://github.com/fecgov/fecfile-web-app/assets/25588182/738e16e9-62a2-4464-bff3-3bcea95b74f4%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/738e16e9-62a2-4464-bff3-3bcea95b74f))](https://github.com/fecgov/fecfile-web-app/assets/25588182/738e16e9-62a2-4464-bff3-3bcea95b74f4%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/738e16e9-62a2-4464-bff3-3bcea95b74f))

1.  ## Ideal State

[ideal-state](#ideal-state)

[!image-20240603-152408.png! [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1414)| /attachments/11331?name=image-20240603-152408.png] [![](https://github.com/fecgov/fecfile-web-app/assets/25588182/0ce56100-b5ec-4b30-bcc8-c54aa21c36c8%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/0ce56100-b5ec-4b30-bcc8-c54aa21c36c))](https://github.com/fecgov/fecfile-web-app/assets/25588182/0ce56100-b5ec-4b30-bcc8-c54aa21c36c8%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/0ce56100-b5ec-4b30-bcc8-c54aa21c36c))

### QA Notes ###

 
 - [ ] Remove the H2 text "Existing users".
- [ ] Remove the 48px of padding above and the 8px below the old H2 
- [ ] Add 8px of padding below the H1 "Manage users".

# QA Notes
- [x] BA/Design Quality Checklist complete

# DEV Notes

# Design

### DEV Notes ###

 
 null

### Design ###

 
 null

[FECFILE-1414](https://fecgov.atlassian.net/browse/FECFILE-1414)

**Comment by MitchellTCG** [comment]
@GreggMoreland Please review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the following UX changes were implemented.

 - [x] Remove the H2 text "Existing users".
- [x] Remove the 48px of padding above and the 8px below the old H2 
- [x] Add 8px of padding below the H1 "Manage users".

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/d1a55a3f-0b89-4c1a-b5ce-c39eba8492c1)
_______________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
