### ISSUE TITLE
UI: Remove H2 from "Manage reports" page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1989]
1.  Business Reason As the UX Lead, I do not believe an H2 is necessary for the "Manage reports" page to convey the information it contains. However, the data table must keep its current title so users with accessibility issues will know what data is in it.

1.  Acceptance Criteria

Wireframes

1.  ## Current State

[current-state](#current-state)

[![](/attachments/11338?name=image-20240603-171901.png) [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1417)| /attachments/11338?name=image-20240603-171901.png] [![](https://github.com/fecgov/fecfile-web-app/assets/25588182/d4d28098-41d5-4bf2-bf68-01aa61acce0b%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/d4d28098-41d5-4bf2-bf68-01aa61acce0))](https://github.com/fecgov/fecfile-web-app/assets/25588182/d4d28098-41d5-4bf2-bf68-01aa61acce0b%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/d4d28098-41d5-4bf2-bf68-01aa61acce0))

1.  ## Ideal State

[ideal-state](#ideal-state)

[!image-20240603-172023.png! [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1417)| /attachments/11339?name=image-20240603-172023.png] [![](https://github.com/fecgov/fecfile-web-app/assets/25588182/9675a546-34d8-4d38-a6d7-26a748e69f75%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/9675a546-34d8-4d38-a6d7-26a748e69f7))](https://github.com/fecgov/fecfile-web-app/assets/25588182/9675a546-34d8-4d38-a6d7-26a748e69f75%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/9675a546-34d8-4d38-a6d7-26a748e69f7))

### QA Notes ###

- [ ] Remove the H2 text "Recent reports".
- [ ] Remove the 48px of padding above and the 8px below the old H2 
- [ ] Add 8px of padding below the H1 "Manage reports".

# QA Notes
- [x] BA/Design Quality Checklist complete

# DEV Notes

# Design

### DEV Notes ###

null

### Design ###

null

[FECFILE-1417](https://fecgov.atlassian.net/browse/FECFILE-1417)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
pls review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the following UX changes were implemented.

- [x] Remove the H2 text "Recent reports".
- [x] Remove the 48px of padding above and the 8px below the old H2 
- [x] Add 8px of padding below the H1 "Manage reports".

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/ab8adb1a-def0-4c79-ad34-9100e6f99ef7)
_____________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
