### ISSUE TITLE
User receives a 404 error when they click on a transaction on the transaction history table.

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1990]
**Issue**

When a user clicks on a transaction from the transaction history table, a 404 error appears.

**Replicating issue**

  1\. Go to the contacts page

  2\. Click on a contact from the Manage Contacts data table

  3\. Scroll to the bottom of the "Edit contact" modal 

  4\. Click on ANY transaction in the "Transaction history" table

  5\. the user will see a 404 error that simply reads: Incoming HTTP Error - [Error Code]: 404 OK

**Screenshots**

Edit contact modal on Manage contacts page

![](/attachments/11337?name=image-20240603-163041.png)

[See image in Jira]([https://fecgov.atlassian.net/browse/FECFILE-1415](https://fecgov.atlassian.net/browse/FECFILE-1415)) [See image in Jira]([https://fecgov.atlassian.net/browse/FECFILE-1415](https://fecgov.atlassian.net/browse/FECFILE-1415)) [See image in Jira]([https://fecgov.atlassian.net/browse/FECFILE-1415](https://fecgov.atlassian.net/browse/FECFILE-1415))

![](/attachments/11352?name=image-20240607-133533.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/826901ef-3fac-4366-9055-db9e98fcd5e9](https://github.com/fecgov/fecfile-web-app/assets/25588182/826901ef-3fac-4366-9055-db9e98fcd5e))

**Enviroment(s):** DEV and STAGE

### DEV Notes ###

 
  
  
  
 from [~accountid:627ebeb2236090006f61d37d]  at 11am 06/03/2024:  "Yea, it looks like when I set that up I grabbed the same open transaction logic from the report list page, but that has the report id available, whereas on the contact page it does not"

### Design ###

 
  
  
  
 null

[FECFILE-1415](https://fecgov.atlassian.net/browse/FECFILE-1415)

**Comment by MitchellTCG** [comment]
@WiseQA  
Please review and validate this issue I found. If you can replicate the same behavior, please move it forward. Thank you.

**Comment by WiseQA** [comment]
Tested using -  Committee ID: C00100495  TEST_COMMITTEE_NAME16

QA verified this is a "Defect"  tested using the steps to replicate error provided in ticket.

1. Go to the contacts page
2. Click on a contact from the Manage Contacts data table
3. Scroll to the bottom of the "Edit contact" modal 
4. Click on ANY transaction in the "Transaction history" table
5. the user will see a 404 error that simply reads: Incoming HTTP Error - [Error Code]: 404 OK

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/5dd63ea7-85f5-4917-94c7-62342a607f06)

Validated error on both DEV and STAGE environments.

@MitchellTCG @mjtravers pointed 2 points per conversation.   Moved to Sprint Backlog

**Comment by WiseQA** [comment]
![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/a6d071ba-a2e4-4835-9b71-073fa1260f1d)

**Comment by WiseQA** [comment]
![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/34459537-a651-47bd-976d-21b8f35b1a6a)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "defect" error was fixed.

1.  From the contacts page
2  Clicked on a contact from the Manage Contacts data table
3.  Scrolled to the bottom of the "Edit contact" modal
4.  Clicked on ANY transaction in the "Transaction history" table
5.  The transaction type selected from the table was displayed correctly HTTP Error - [Error Code]: 404 not displaying.  

_____________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/b9bf0469-0128-408b-929f-43191400b3b7)

__________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/6242035e-7282-4b6c-9c3a-a74ce1f7794d)

_________________________________________________________________________________________________

QA Review Completed.  Moved to Stage Ready.
