### ISSUE TITLE
When creating or editing a Form 99 the "Save" and "Save and Continue" buttons are overlapping

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#2007]
**Description:** **Where was the issue found:** * **Committee ID:** C00100495 * **Environment:** DEV * **Browser:** Chrome

**Please describe the issue:** When creating or editing a Form 99 the "Save" and "Save and Continue" buttons are overlapping.

**Approx. time the issue was found:** 1:30 pm on 06/19/2024

**How to replicate the issue:**

1.  Select the "Create report" button on the Manage reports page.
2.  Select Form 99 from the "Form Type" dropdown menu
3.  Select the "Start building report" button the Form 99 will display
4.  The "Save" and "Save and Continue" buttons are overlapping (this is the bug)

**Screenshots:**

![](https://github.com/fecgov/fecfile-web-app/assets/96139912/a417ceef-a56c-4574-8f1c-c5b147d3307e)

[!https://github.com/fecgov/fecfile-web-app/assets/96139912/a417ceef-a56c-4574-8f1c-c5b147d3307e!](https://github.com/fecgov/fecfile-web-app/assets/96139912/a417ceef-a56c-4574-8f1c-c5b147d3307e)

![](https://github.com/fecgov/fecfile-web-app/assets/96139912/a417ceef-a56c-4574-8f1c-c5b147d3307e)

[!https://github.com/fecgov/fecfile-web-app/assets/96139912/a417ceef-a56c-4574-8f1c-c5b147d3307e!](https://github.com/fecgov/fecfile-web-app/assets/96139912/a417ceef-a56c-4574-8f1c-c5b147d3307e)

* * *

@MitchellTCG @mjtravers this is an UX discussion / decision on how to handle this fix and correct positioning of buttons. Bug found when testing Sprint 44.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-1432](https://fecgov.atlassian.net/browse/FECFILE-1432)

**Comment by MitchellTCG** [comment]
I will be updating this ticket by COB

I already spoke to @sasha-dresden and @WiseQA

**Comment by MitchellTCG** [comment]
ONLY TESTING THE  OVERLAPPING BUTTON FIX.

New ticket for holistic update to come

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified this bug fix was implemented and functionality working as designed.  (Tested both creating / editing a Form 99)

1. Selected the "Create report" button on the Manage reports page.
2. Selected Form 99 from the "Form Type" dropdown menu
3. Selected the "Start building report" button the Form 99 will display
4. Verified the "Save" and "Save and Continue" buttons are not overlapping and fixed per current UX design.
![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/c3e93585-62f9-4d1e-be53-eb064a95f536)
________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
