### ISSUE TITLE
System to validate Committee ID format when adding or editing a Committee contact

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#205]
Business Reason

The Committee ID must be in a specific format in order to be accepted by FEC upon submission.

Acceptance Criteria

***If*** I am adding or editing an existing Committee contact through Contact Management

  ***When*** I enter or edit the Committee ID

  ***Then*** I must enter the ID in the following format: "CXXXXXXXX" where X is a numeric value _(C, then 8 numbers)_

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1239](https://fecgov.atlassian.net/browse/FECFILE-1239)

**Comment by WiseQA** [comment]
Committee ID Add Screen and Saved
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/763aadb5-93d5-42b7-b47b-9645f58ba43b)

Committee ID Edit Screen and Saved
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f7fba7ac-6d9a-4d0a-8cf2-904838ced35d)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/44767d98-193d-444a-86e3-b2106807c032/download](https://app.zenhub.com/files/306118986/44767d98-193d-444a-86e3-b2106807c032/download)

QA review completed.  Moved to Stage Ready.
