### ISSUE TITLE
System to validate Candidate ID format when adding or editing a Candidate contact

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#206]
Business Reason

The Candidate ID must be in a specific format in order to be accepted by FEC upon submission.

Acceptance Criteria

***If*** I am adding or editing an existing Candidate contact through Contact Management

  ***When*** I enter or edit the Candidate ID

  ***Then*** I must enter the ID in one of the following formats:

*   "PXXXXXXXX" where X is a numeric value _(P, then 8 numbers)_
*   [H|S][0-9] {1} 

    [A-Z]

     {2} 

    [0-9]

     {5} 

    _(H or S, 1 number, 2 letters, 5 numbers)_

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1238](https://fecgov.atlassian.net/browse/FECFILE-1238)

**Comment by WiseQA** [comment]
Candidate ID Add Screens for P, H and S and Saved
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e7b15415-ca3f-4419-be01-6eaddcce7b5b)

Candidate ID Edit Screens for P, H and S and Saved
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/198bd23b-7bd7-429a-839e-60416e50b688)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/1cc6d072-5211-4b89-b2fd-ebb875b5cb38/download](https://app.zenhub.com/files/306118986/1cc6d072-5211-4b89-b2fd-ebb875b5cb38/download)

QA review completed.  Moved to Stage Ready.
