### ISSUE TITLE
1 - Allow user to amend a Form 3X report

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#207]
Business Reason 
 

As a user, I will be able to amend a submitted report so that I can provide FEC with the correct information per regulations.

 Acceptance Criteria 
 

**Given** the user has a Form 3X report in 'Submission success' status,
**Then** they will have the option in the action menu to "Amend" 
**And** when they amend the report, then:
- the report will have a status of 'In progress'
- the report will have a version of "Amendment X", where "X" is the amendment number
- the report and transactions will be completely editable _except_ for Report Type and report Coverage Dates
-- Note: This includes COH if the report is the first report submitted by the committee in FECfile Online.
- any contacts in the report/transactions will be updated to the most current contact information stored in their contact management

**Given** I have amended a report
**When** I add new transactions,
**Then** they will appear following the same ordering logic on an original report (copied below)

1. Within a report, by **Schedule**
2. Within a schedule, by **Line Number**
3. Within line number, **by order transaction was created**
4. And child transactions be displayed directly after the parent in the order in which they were created **only if it is in the same schedule.** If the associated transaction is in a different schedule, it will be listed within that schedule following the rules above.

 Wireframe

# Action kabob
![207 - Allow user to amend a Form 3X report - Mange Report.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/22874642-2ac3-439a-b8c4-bc98f8e82587)

# Status changed to in-progress & Version changed to Amendment "x" for all affected transactions
![207 - Allow user to amend a Form 3X report - Mange Report – 1.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/c8f48fee-9306-4f4a-b328-38cab072846d)

# Please notice transaction title changed "**Form 3x:** February 20 monthly Report (M2) - Amendment 1"
![207 - Transactions.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/c417f00a-0597-4084-804e-3e6a860dc69a)

### QA Notes ### 
 - [x] BA/Design Quality Checklist complete
- The amended report essentially _replaces_ the previous iteration of the report. We will not be storing previous iterations of reports.
- This ticket does _not_ include submission functionality.
### DEV Notes ### 
 -  Ensure that the previous iterations of reports do _not_ count in the aggregate totals for entity aggregates in transactions and (Detailed) Summary Page totals.
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
4/13/2022 Requirements Session note: "Currently, we only let them see the most recent amendment that they filed. If they want to see other iterations, they can go to fec.gov. Can provide a link to them."

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @JonellaCulmer @GreggMoreland 
Wires added

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified with @toddlees the functionality of this ticket passes.  (NOTE:  @MitchellTCG @mjtravers Fix for displaying Amendment 2 to be fixed in ticket #1197)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0F1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6efb223af708fff1326a8d84704a81c556a40c49/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTR1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd2c544242d88028307cc950ffac2768eed33f48/image.png)

QA Review Completed.   Moved to Stage Ready.
