### ISSUE TITLE
Create automated regression tests for QA scripts (Sprint 6)

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#209]
Business Reason

As a developer or QA, I will be able to automatically run the Sprint-6 test scripts using the Cypress e2e framework so that I can run regression tests in an automated fashion.

Acceptance Criteria

***If*** I want to run the Sprint test scripts to retest the tickets

  ***When*** I run the automated tests in the Cypress framework

  ***Then*** I will get a report on which scripts failed and which passed

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1235](https://fecgov.atlassian.net/browse/FECFILE-1235)

**Comment by AureliaKhorsand** [comment]
**4/6/22 Refinement Meeting**: This ticket encompasses encoding scripts into framework. Does not including rewriting for Sprint 5.

**Comment by mjtravers** [comment]
Some changes requested from Code Review as documented in the [PR](https://github.com/fecgov/fecfile-web-app/pull/273)

**Comment by Elaine-Krauss-TCG** [comment]
The pull request intended to resolve this ticket is now made obsolete by [this one](https://github.com/fecgov/fecfile-web-app/pull/282)

**Comment by WiseQA** [comment]
Demo of Sprint 6 automated tests against QA test scripts.  Visual everything looked good.

QA review completed.  Moved to Stage Ready.
