### ISSUE TITLE
Use FECFile web API to retrieve committee profile data

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#216]
Original ticket: [https://github.com/fecgov/fecfile-web-app/issues/87](https://github.com/fecgov/fecfile-web-app/issues/87)
 Pull request: [https://github.com/fecgov/fecfile-web-app/pull/210](https://github.com/fecgov/fecfile-web-app/pull/210)

Per discussion with @mjtravers and @toddlees we should use the FECFile web API to retrieve committee profile data so we can do this request server-side and not client-side. This would allow us to remove the hard-coded FEC API keys in the web app, which isn't great practice

 Business Reason 

As a user, I will be able to see the committee account data without being able to see the FEC API key in the code.

 Acceptance Criteria 

***If*** search the front-end code sent to the browser
 ***Then*** I will not be able to find the FEC API key

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-1233](https://fecgov.atlassian.net/browse/FECFILE-1233)

**Comment by mjtravers** [comment]
Requested change in api part of code from CR. Sending back to In Progress.

**Comment by sasha-dresden** [comment]
@GreggMoreland As part of the update for this, we need to validate that the user has provided a good candidate id. I've noticed the few I've looked at seem to follow the pattern of capital letter + 8 numbers. Is this correct or would there be other valid variations we should accept

**Comment by toddlees** [comment]
@sasha-dresden According
 to the vendor pack, candidate ID's are:
presidential: P + 8 numbers
house: H + number + (two letters representing state) + 5 numbers
senate: S + number + (two letters representing state) + 5 numbers

Though I'm not sure adding validation adds value to the endpoint.  The fec endpoint validates already.  Also, the endpoint is only called after picking a candidate id from a list fec-provided ids.  Would it be more consistent to send the id as-is to the fec api and catch any failure on that request? <img width="1470" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0JpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--963c96c90ba6d99285b8f233f3ddafc8232ded79/image.png" alt="image.png" />

**Comment by sasha-dresden** [comment]
That's what I had intended to do, but there was an issue with sonarcloud in the api. It does not like having user input used for building a url. Which makes sense if the user could effect what domain the request was going to be made to, however in this instance the user can only effect this one parameter. I found [this](https://community.sonarsource.com/t/change-this-code-to-not-construct-the-url-from-user-controlled-data/34393/6) while looking it up, and the sonar sourcer said it was a known issue with their process that it doesn't check where the user input is contributing to the url being built. In that chain they recommended validating and sanitizing the user input, which once I did that, it passed sonarcloud's check.

**Comment by sasha-dresden** [comment]
After playing with it a little bit, I agree. Adding validation here wouldn't be a good thing. Especially if, for whatever reason, the validation rule changed, say it could now start with a 'T' or something. We'd need to update this as well. Instead I put in a barebones validation. Only checks if it's not empty. And didn't do any sanitizing, but I managed to get it past the sonar check.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers @sasha-dresden please put link in ticket for Unit Test to pass as QA review - thanks

**Comment by mjtravers** [comment]
Link to unit tests: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/4424/workflows/28a3c4a2-5774-48dd-a119-cf6d5b58371c/jobs/15802

<img width="712" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGhvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b977012f50b3d5f44121ac6f043c32d4416d48d5/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of Unit Test passing as denoted in app.circleci per DEV.

<img width="1527" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenhzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bfc0d4d9eb0fd59e3f5b5368346cf89b62737507/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
