### ISSUE TITLE
Allow user to see report status from Report Management page

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#218]
Business Reason

As a Committee Administrator, I will be able to see the status of each of my reports so that I can accurately track my committee's reports.

Acceptance Criteria

### QA Notes ###
**If** I am a Committee Administrator
**When** I review my reports listed on the Report Management Page
**Then** I will see the appropriate status listed beside each report, as follows:

- In progress (any report that is being updated by the user and has not yet been submitted to FEC)
- Submission pending -(any report that has been submitted by the user, but has not yet failed, nor has it yet been accepted by FEC)
- Submission failure (a report that has reported a failure anytime after being submitted)
- Submission success (any report that has been accepted by FEC)

**And** when report status is 'In progress' 
**Then the report can be edited and submitted**

**And** when report status is anything other than 'In progress' or 'Submission failure'
**Then the report cannot be edited, but can be viewed**

**QA Notes**

**DEV Notes**
This is a timeline of the report status.  https://docs.google.com/spreadsheets/d/1lRqm7MYKdHse2BTJtck7xT2Fy-cY9ovhMcCUikNWZPE/edit#gid=0

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1231](https://fecgov.atlassian.net/browse/FECFILE-1231)

**Comment by MitchellTCG** [comment]
No wire required

**Comment by Elaine-Krauss-TCG** [comment]
Altered existing status mapping (ty, Todd!) to match acceptance criteria.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHhtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f52c8d03610bc1c656651f3cc31c9c32ddd11b04/image.png)

An example of two reports after the changes:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUZtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--392715b95560260b890460f19c6e94316d48815a/image.png)

**Comment by mjtravers** [comment]
Passes CR. Can send to QA for sprint 30 if there is enough time for testing.

**Comment by Elaine-Krauss-TCG** [comment]
When submitting a report, the labels that can be observed on the Reports Management page have been updated.

 - "In-progress" changed to "In progress"
 - "Submitted" changed to:
   - "Submission pending" before it has been processed
   - "Submission success" when the FEC has accepted it
 - "Failed" changed to "Submission failure"
 
Because we currently stub-out submission to the FEC and automatically set "submitted" reports to the success state, "Submission pending" and "Submission failure" cannot be observed or tested in the app at this moment.

**Comment by WiseQA** [comment]
@Elaine-Krauss-TCG thanks for the update.  Straight forward and simple list to test by.  

QA review verified using the following list of labels on the Reports Management page (see DEV comment above) were displayed correctly.

"In-progress" changed to "In progress"  **(QA review verified changed)**
"Submitted" changed to:
   "Submission pending" before it has been processed  **(Non-testable at this point in time.  Not verified by QA)**
   "Submission success" when the FEC has accepted it  **(QA review verified changed)**
"Failed" changed to "Submission failure"  **(Non-testable at this point in time.  Not verified by QA)**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFpzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4950c337f53af6ee80e9eb0b92615d11f44481ad/image.png)

QA Review Completed.   Moved to Stage Ready.
