### ISSUE TITLE
Add new `requirements-test.txt` file

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#22]
In order to have better testing requirements tracking, we should create a `requirements-test.txt` file and have Circle install these dependencies from this file rather than `pip install <package>`

**Acceptance criteria**
- [x] `flake8` is installed from a requirements file in Circle

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by albertcrowley** [comment]
This issue modifies the CI pipeline and does not require formal QA after code review.  Moving to the 'done' state.
