### ISSUE TITLE
System to default to Quarterly or Monthly report selection based on committee filing frequency

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#222]
Business Reason

As a Committee Administrator, I will be able to, by default, see the monthly or quarterly report listing on Manage Reports based on my filing frequency so that I can more easily see my report options, but optionally be able to change to a different frequency.

Acceptance Criteria

**_Given_** I select 'Add a report' on the 'Manage reports' page

**_When_** I select Form 3x from the dropdown

**_Then_** the form is displayed, the 'Reporting frequency' radio button will default according to the following:

*   if Filing Frequency = M, system will default to 'Monthly Reporting'
*   if Filing Frequency = Q, A or T, system will default to 'Quarterly Reporting'

**_And_** I can still change the 'Reporting frequency' selected

### QA Notes ###
Devs will work with QA to verify

### DEV Notes ###
* Currently, this page defaults to 'Quarterly Reporting' when it is loaded.
*  [API Endpoint here]([https://api.open.fec.gov/v1/committee/C00672311/?api_key=DEMO_KEY&per_page=100&page=1|https://api.open.fec.gov/v1/committee/C00672311/?api_key=DEMO_KEY&per_page=100&page=1]) 
see "filing_frequency"

* -(Filing frequency is stored on the back end for each Committee Account)- Filing frequency is retrieved per-session from the configured source of committee data (mock data/prod efo/test efo) through a request made from the fecfile api, and will determine what the default selection is when a user goes to create a report. Includes Q (Quarterly), M (Monthly), T (Termination), A (Administrative Termination)
* If filing frequency is Q or M, then default to that option, but allow user to change it

### Design ###

 
 null

 See full ticket and images here: [FECFILE-1229](https://fecgov.atlassian.net/browse/FECFILE-1229)

**Comment by AureliaKhorsand** [comment]
BA Note: YE reports cover remaining of the entire calendar year.

**Comment by AureliaKhorsand** [comment]
Per the quarterly design review in October of 2023, Debbie confirmed that the report should _not_ be pre-selected. However, system should default to either the Monthly or Quarterly tab based on filing frequency. 

@GreggMoreland can you take a pass at adding ACs that say based on the filing frequency we read from FEC, we default the appropriate "tab" in the create report section?

**Comment by GreggMoreland** [comment]
@AureliaKhorsand after the 6/4/2024 Requirement meeting decision, how should the system treat a filing frequency that is something other than M or Q?   I have updated it to look for any condition.
