### ISSUE TITLE
Create Schedule A Transaction Type selection screen

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#228]
***Note:*** _These links/items will be inactive until we develop transactions, and they will become active as we go._

  

Business Reason

As a Committee Administrator within an existing Form 3X report, I will be able to see a list of available Schedule A transactions grouped by type so that in the future I can easily see and select what I need to enter.

Acceptance Criteria

***Given*** I am editing an open Form 3X report

  ***When*** I go to enter a Schedule A transaction

  ***Then*** available Schedule A transactions will be grouped by the following:

—

1.  Contributions from Individuals/Persons

       #

*   Individual Receipt
*   Tribal Receipt
*   Partnership Receipt
*   Reattribution
*   In-Kind Receipt
*   Returned/Bounced Receipt (Individual)
*   Earmark Receipt
*   Conduit Earmark (Deposited)
*   Conduit Earmark (Undeposited)
*   Unregistered Receipt from Person
*   Unregistered Receipt from Person - Returned/Bounced Receipt

       —

1.  Contributions from Registered Filers

       #

*   Party Receipt
*   Party In-Kind
*   Returned/Bounced Receipt (Party)
*   PAC Receipt
*   PAC In-Kind
*   PAC Earmark Receipt
*   PAC Conduit Earmark (Deposited)
*   PAC Conduit Earmark (Undeposited)
*   Returned/Bounced Receipt (PAC)

       —

1.  Transfers

       #

*   Transfers
*   JF Transfers
*   In-Kind Transfer
*   In-Kind Transfer-FEA
*   JF Transfer - National Party Recount Account
*   JF Transfer - National Party Convention Account
*   JF Transfer - National Party Headquarters Account

       —

1.  Refunds

       #

*   Refunds of Contributions to Registered Committees
*   Refunds of Contributions to Unregistered Committees

       —

1.  Other

       #

*   Offsets to Operating Expenditures
*   Other Receipts
*   Ind. Receipt - Non-Contribution Account
*   Other Committee Receipt - Non-Contribution Account
*   Business/Labor Org. Receipt - Non-Contribution Account
*   Individual Recount Receipt
*   Party Recount Receipt
*   PAC Recount Receipt
*   Tribal Recount Receipt
*   Individual National Party Recount Account
*   Party National Party Recount Account
*   PAC National Party Recount Account
*   Tribal National Party Recount Account
*   Individual National Party Headquarters Buildings Account
*   Party National Party Headquarters Buildings Account
*   PAC National Party Headquarters Buildings Account
*   Tribal National Party Headquarters Buildings Account
*   Individual National Party Convention Account
*   Party National Party Convention Account
*   PAC National Party Convention Account
*   Tribal National Party Convention Account
*   Earmark Receipt for Recount Account (Contribution)
*   Earmark Receipt for Convention Account (Contribution)
*   Earmark Receipt for Headquarters Account (Contribution)

       —

[https://images.zenhubusercontent.com/306118986/cff18492-f192-4a73-9dbd-951b808e82a4/select_receipt_type_video.mp4](https://images.zenhubusercontent.com/306118986/cff18492-f192-4a73-9dbd-951b808e82a4/select_receipt_type_video.mp4)

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1225](https://fecgov.atlassian.net/browse/FECFILE-1225)

**Comment by MitchellTCG** [comment]
**Contributions from individuals-persons**
![Contributions from individuals-persons.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/3c15038b-6a1b-4862-bace-f397a73d424f)

**Contributions from registered filers**
![Contributions from registered filers.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/27b9b1c0-de84-4ea3-9714-d39b94d438ce)

**Other**
![Other.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/76111f3e-0e8d-4e36-95c7-85d2c6b6ca66)

**Refunds**
![Refunds.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/026033bb-cc91-40fb-924c-01ca8776b04b)

**Transfer**
![Transfer.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/6cc28a5f-2e6b-4a05-a6a0-b5df7e65472e)

**Comment by MitchellTCG** [comment]
@toddlees 
Sent back

Please change the text "FEC Form 3X" to "Receipts"

**Comment by WiseQA** [comment]
Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/4dea0af7-fa67-4dcf-a79c-afc54d063b3e/download](https://app.zenhub.com/files/306118986/4dea0af7-fa67-4dcf-a79c-afc54d063b3e/download)

QA review completed.  Moved to Stage Ready.
