### ISSUE TITLE
Create Group A Transaction Screen

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#229]
Business Reason 
 

As a Committee Administrator, I will be able to enter a transaction for **"Individual Receipt"** on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Contributions from individuals/persons" Accordion link  
**Then** I can enter a transaction with the type "Individual Receipt" 
**And** I will be required to enter the following information (unless otherwise noted):

# Contributor 
#
-	**CONTRIBUTOR TYPE** (Read-only)
Field description in API: ENTITY TYPE
Disabled textbox: “Individual” will appear
Description for individual in disabled textbox in API: IND
-	**LAST NAME** (A/N-30, Required)
Field description in API: CONTRIBUTOR LAST NAME
Data field: textbox
-	**FIRST NAME** (A/N-20, Required)
Field description in API: CONTRIBUTOR FIRST NAME
Data field: textbox
-	**MIDDLE NAME** (A/N-20, Optional)
Field description in API: CONTRIBUTOR MIDDLE NAME
Data field: textbox
-	**PREFIX** (A/N-10, Optional)
Field description in API: CONTRIBUTOR PREFIX
Data field: textbox
-	**SUFFIX** (A/N-10, Optional)
Field description in API: CONTRIBUTOR SUFFIX
Data field: textbox
<br>

# Address 
#
-	**STREET ADDRESS** (A/N-34, Required)
Field description in API: CONTRIBUTOR STREET 1
Data field: textbox
-	**APARTMENT, SUITE, ETC.** (A/N-34, Optional)
Field description in API: CONTRIBUTOR STREET 2
Data field: textbox
-	**CITY** (A/N-30, Required)
Field description in API: CONTRIBUTOR CITY
Data field: textbox
-	**STATE/PROVINCE** (ALPHA-2, Required)
Field description in API: CONTRIBUTOR STATE
Data field: Dropdown
          Dropdown options: States without military
          https://docs.google.com/spreadsheets/d/17YmnaZgqvFOUyv4-Qknd8ikHe8o9LoDb/edit#gid=494776297
-	**ZIP/POSTAL CODE** (A/N-9, Required)
Field description in API: CONTRIBUTOR ZIP
Data field: textbox
<br>

# Employer 
#
-	**EMPLOYER** (A/N-38, Required if donor aggregate > $200)
Field description in API: CONTRIBUTOR EMPLOYER
Data field: textbox
-	**OCCUPATION** (A/N-38, Required if donor aggregate > $200)
Field description in API: CONTRIBUTOR OCCUPATION
Data field: textbox
<br>

NOTE: Currently, the aggregate field is set to 0 by default and cannot be changed in the UI. As a result, the occupation and employer "required if aggregate > $200" cannot be tested and will have to be tested in a later ticket when the aggregation amount functionality is added.

# Contribution 
#
-	**DATE RECEIVED** (NUM-8…YYYYMMDD, Required)
Field description in API: CONTRIBUTION DATE
Data field: Date picker 
-	**MEMO ITEM** (A/N-1, Optional)
Field description in API: MEMO CODE
Data field: Checkbox
-	**CONTRIBUTION AMOUNT** (AMT-12, Required)
Field description in API: CONTRIBUTION AMOUNT
Data field: textbox
-	**CONTRIBUTION AGGREGATE** (AMT-12, Required)
Field description in API: CONTRIBUTION AGGREGATE
Data field: textbox (FOR NOW it will say $0.00)
This is automatically calculated as an aggregate of this contributor's contributions YTD, in any reports, in chronological order)
<br>

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (A/N-100, Optional)
Field description in API: RECEIPT DESCRIPTION
Data field: multi-line textbox
**Description should be read-only and the user will be unable to edit. (Auto-generated in Future Ticket)**

-	**NOTE OR MEMO TEXT** (A/N-100, Optional)
Field description in API: MEMO TEXT/DESCRIPTION
Data field: multi-line textbox

**Then** I will be able to:

- Cancel
- Save & view all transactions
- Save & add another
- Edit

 Dev Note 

Save dates as date object instead of string
Please show "Contribution Amount" and "Contribution Aggregate" as **Currency**

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See Individual Receipt spec [here](https://fecgov.github.io/fecfile-validate/INDV_REC_spec.html). 
#

![Group A - Individual Receipt - Individual.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/08604a4a-487c-4cf6-87e7-68aaf29eb89d)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
**Wireframe Filled In**
![Group A - Individual Receipt - Individual - Filled In.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a1f11698-9f2a-49ed-8312-550d18cb632e)


**Errors**
![Group A - Individual Receipt - Individual - errors.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/30f13328-8234-474f-a4b5-ac48c4b03af2)

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG which Transaction Screen am I suppose to test against for Group A ? I can enter a transaction with the type "Individual Receipts" from the Transaction Screen.  Which Individual transaction link under "Other" is being tested ?   Ind. Receipt - Non-Contribution Account ?

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG 
By the Acceptance Criteria these are required fields, however these are based on Aggregate field being filled in.   Should these be grayed out for now ?   Also the "This is required field" not populating.

EmployerEMPLOYER (A/N-38, Required if donor aggregate > $200)
Field description in API: CONTRIBUTOR EMPLOYER
Data field: textbox

OCCUPATION (A/N-38, Required if donor aggregate > $200)
Field description in API: CONTRIBUTOR OCCUPATION
Data field: textbox
 
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a81b643e-164f-4047-b5f3-fdb07d23f5a9)

Returning to In-progress for above fix.

**Comment by mjtravers** [comment]
Currently, the aggregate field is set to 0 by default and cannot be changed in the UI. As a result, the occupation and employer "required if aggregate > $200" cannot be tested and will have to be tested in a later ticket when the aggregation amount functionality is added.

**Comment by AureliaKhorsand** [comment]
@mjtravers @WiseQA we can test employer/occupation required validation in #276.

**Comment by WiseQA** [comment]
QA reviewed on this ticket to enter, Save & view all transactions, Save and add another, and edit a Group A Transaction. Test Case/Test Scripts written to test all these functionalities per acceptance criteria.  Tested "EMPLOYER" section as denoted in ticket update.

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/3e2dc018-8692-4849-995f-aad69bbe56b8/download](https://app.zenhub.com/files/306118986/3e2dc018-8692-4849-995f-aad69bbe56b8/download)

QA review completed.  Moved to Stage Ready.
