### ISSUE TITLE
Allow users to enter Group B Transaction

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#230]
Business Reason 
 

As a Committee Administrator, I will be able to enter a transaction for **"Offsets to Operating Expenditures"** on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**Then** I can enter a transaction with the type "Offsets to Operating Expenditures" from the Transaction Screen (for Individual and Organization Only)
**Then** I will be required to enter the following information (unless otherwise noted):

# Contributor 
#
-	**CONTRIBUTOR TYPE** 
Field description in API: ENTITY TYPE
Data field: Dropdown
Dropdown options: Individual, Organization
---
_if Entity = Organization_
-	**ORGANIZATION NAME** (A/N-200, Required)
Field description in API: CONTRIBUTOR ORGANIZATION NAME
Data field: textbox
---
_if Entity = Individual_
-	**LAST NAME** (A/N-30, Required)
Field description in API: CONTRIBUTOR LAST NAME
Data field: textbox
-	**FIRST NAME** (A/N-20, Required)
Field description in API: CONTRIBUTOR FIRST NAME
Data field: textbox
-	**MIDDLE NAME** (A/N-20, Optional)
Field description in API: CONTRIBUTOR MIDDLE NAME
Data field: textbox
-	**PREFIX** (A/N-10, Optional)
Field description in API: CONTRIBUTOR PREFIX
Data field: textbox
-	**SUFFIX** (A/N-10, Optional)
Field description in API: CONTRIBUTOR SUFFIX
Data field: textbox
---

# Address 
#
-	**STREET ADDRESS** (A/N-34, Required)
Field description in API: CONTRIBUTOR STREET 1
Data field: textbox
-	**APARTMENT, SUITE, ETC.** (A/N-34, Optional)
Field description in API: CONTRIBUTOR STREET 2
Data field: textbox
-	**CITY** (A/N-30, Required)
Field description in API: CONTRIBUTOR CITY
Data field: textbox
-	**STATE/PROVINCE** (ALPHA-2, Required)
Field description in API: CONTRIBUTOR STATE
Data field: Dropdown
          Dropdown options: States without military
          https://docs.google.com/spreadsheets/d/17YmnaZgqvFOUyv4-Qknd8ikHe8o9LoDb/edit#gid=494776297
-	**ZIP/POSTAL CODE** (A/N-9, Required)
Field description in API: CONTRIBUTOR ZIP
Data field: textbox

# Contribution 
#
-	**DATE RECEIVED** (NUM-8…YYYYMMDD, Required)
Field description in API: CONTRIBUTION DATE
Data field: Date picker
-	**MEMO ITEM** (A/N-1, Optional)
Field description in API: MEMO CODE
Data field: Checkbox
-	**CONTRIBUTION AMOUNT** (AMT-12, Required)
Field description in API: CONTRIBUTION AMOUNT
Data field: textbox
-	**CONTRIBUTION AGGREGATE** (AMT-12, Required)
Field description in API: CONTRIBUTION AGGREGATE
Data field: textbox (FOR NOW it will say $0.00)
_This is automatically calculated as an aggregate of this contributor's contributions YTD, in any reports, in chronological order_
<br>

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only: A/N-100, Optional)
Field description in API: RECEIPT DESCRIPTION
Data field: multi-line textbox
-	**NOTE OR MEMO TEXT** (A/N-100, Optional)
Field description in API: MEMO TEXT/DESCRIPTION
Data field: multi-line textbox

**Then** I will be able to:

- Cancel
- Save & view all transactions
- Save & add another
- Edit

 Dev Note 

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See Offsets to Operating Expenditures spec [here](https://fecgov.github.io/fecfile-validate/OFFSET_TO_OPEX_spec.html). 
#

**Individual**
![Group B - Offsets to Operating Expenditures - Individual.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/afffd09d-4d24-4698-86bc-63e0e4c5e590)

**Organization**
![Group B - Offsets to Operating Expenditures - Organization.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0f618491-330b-404b-9b62-29e91da3eaf3)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
Individual
![Group B - Offsets to Operating Expenditures - Individual - Filled In.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7018b725-b473-4cfb-a0e2-697fb4bc22b6)

![Group B - Offsets to Operating Expenditures - Individual - Errors.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f174401f-4088-45ac-81b2-e96cd0723ffe)

**Comment by MitchellTCG** [comment]
Organization
![Group B - Offsets to Operating Expenditures - Organization - Filled In.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0c744ca3-dd83-4089-a41d-7fcff74cedb6)

![Group B - Offsets to Operating Expenditures - Organization - Errors.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f13886ac-5a63-41fc-bd49-0dd22481415d)

**Comment by AureliaKhorsand** [comment]
@mjtravers , there is updated text for the guidance text under "Memo Item". It should read "Check the ‘Memo Item’ box for informational entries that are not counted in the committee’s cash on hand (e.g., contributor attribution, conduit information, ultimate payee, etc.)"

@MitchellTCG will provide updated wireframe.

**Comment by mjtravers** [comment]
Ready for CR. PR's to review are:
https://github.com/fecgov/fecfile-validate/pull/76
https://github.com/fecgov/fecfile-web-api/pull/121/
https://github.com/fecgov/fecfile-web-app/pull/270

**Comment by WiseQA** [comment]
Transaction type "Offsets to Operating Expenditures" used for testing this ticket and selected from the Transactions Screen "Other" drop down menu.  This transaction used as denoted in the Acceptance Criteria.

**Comment by WiseQA** [comment]
@mjtravers - bug fix "This is a required field" not displaying for the following:
CONTRIBUTION AMOUNT (AMT-12, Required)

Bug fix - This field cannot contain more than 100 alphanumeric characters.

CONTRIBUTION PURPOSE DESCRIPTION (Read-only: A/N-100, Optional)
NOTE OR MEMO TEXT (A/N-100, Optional)

Bug Fix:
Once the individual contact info was entered and saved, when I selected the same report to add another transaction the fields did NOT clear.

**Comment by mjtravers** [comment]
Bugs patched for CONTRIBUTION AMOUNT, CONTRIBUTION PURPOSE DESCRIPTION, NOTE OR MEMO TEXT, and the form not clearing properly. Ready for QA.

**Comment by WiseQA** [comment]
QA reviewed on this ticket to enter, Save & view all transactions, Save and add another, and edit a Group B Transaction.   Test Case/Test Scripts written to test all these functionalities per acceptance criteria.

Two (2) Test Case/Test Scripts were developed for this ticket.  One to encompass Individual / Candidate and one to encompass Organization / Committee.  Reasoning is the steps are the same for these Contributor Types and test scripts can be rerun as written, and denoted in each test script.

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/26b42a3c-5017-4813-a963-13f22d46d955/download](https://app.zenhub.com/files/306118986/26b42a3c-5017-4813-a963-13f22d46d955/download)

[https://app.zenhub.com/files/306118986/e468ff69-1cde-4072-9926-46c5086beeb0/download](https://app.zenhub.com/files/306118986/e468ff69-1cde-4072-9926-46c5086beeb0/download)

QA review completed.  Moved to Stage Ready.

**Comment by WiseQA** [comment]
Second review.   Acceptance Criteria was incorrect, should only test Individual and Organization.  

QA reviewed on this ticket to enter, Save & view all transactions, Save and add another, and edit a Group B Transaction.   Test Case/Test Scripts written to test all these functionalities per acceptance criteria.

Two (2) Test Case/Test Scripts were developed for this ticket.  One to encompass Individual and one to encompass Organization .  

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/aeb2aeef-0dd0-4865-af4e-843560e29616/download](https://app.zenhub.com/files/306118986/aeb2aeef-0dd0-4865-af4e-843560e29616/download)

[https://app.zenhub.com/files/306118986/e3750d43-55ea-40f1-a885-2d8f720ee424/download](https://app.zenhub.com/files/306118986/e3750d43-55ea-40f1-a885-2d8f720ee424/download)

QA review completed.  Moved to Stage Ready.

**Comment by mjtravers** [comment]
The screen was updated so that the only options available for the Contributor Type select box are "Individual" and "Organization". Ready for QA

**Comment by WiseQA** [comment]
QA completed 
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/202edc05-b4e7-4577-9601-f29871d06012)

Verified pulldown changed to Individual and Organization only.   Passes adhoc testing.
