### ISSUE TITLE
Allow users to enter Group C Transaction

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#231]
Business Reason 
 

As a Committee Administrator, I will be able to enter a transaction for **“Other Receipts”** on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type "Other Receipts"
**Then** I will be required to enter the following information (unless otherwise noted):

# Contributor 
#
-	**CONTRIBUTOR TYPE** 
Field description in API: ENTITY TYPE
Data field: Dropdown
Dropdown options: Individual, Organization, Committee
---
_if Entity = Organization or Committee_
-	**ORGANIZATION NAME** or **COMMITTEE NAME** (A/N-200, Required)
Field description in API: CONTRIBUTOR ORGANIZATION NAME
Data field: textbox
---
_if Entity = Individual_
-	**LAST NAME** (A/N-30, Required)
Field description in API: CONTRIBUTOR LAST NAME
Data field: textbox
-	**FIRST NAME** (A/N-20, Required)
Field description in API: CONTRIBUTOR FIRST NAME
Data field: textbox
-	**MIDDLE NAME** (A/N-20, Optional)
Field description in API: CONTRIBUTOR MIDDLE NAME
Data field: textbox
-	**PREFIX** (A/N-10, Optional)
Field description in API: CONTRIBUTOR PREFIX
Data field: textbox
-	**SUFFIX** (A/N-10, Optional)
Field description in API: CONTRIBUTOR SUFFIX
Data field: textbox
---

# Address 
#
-	**STREET ADDRESS** (A/N-34, Required)
Field description in API: CONTRIBUTOR STREET 1
Data field: textbox
-	**APARTMENT, SUITE, ETC.** (A/N-34, Optional)
Field description in API: CONTRIBUTOR STREET 2
Data field: textbox
-	**CITY** (A/N-30, Required)
Field description in API: CONTRIBUTOR CITY
Data field: textbox
-	**STATE/PROVINCE** (ALPHA-2, Required)
Field description in API: CONTRIBUTOR STATE
Data field: Dropdown
          Dropdown options: States without military
          https://docs.google.com/spreadsheets/d/17YmnaZgqvFOUyv4-Qknd8ikHe8o9LoDb/edit#gid=494776297
-	**ZIP/POSTAL CODE** (A/N-9, Required)
Field description in API: CONTRIBUTOR ZIP
Data field: textbox
<br>

-	**EMPLOYER** (A/N-38, Required if donor aggregate > $200)
Field description in API: CONTRIBUTOR EMPLOYER
Data field: textbox
-	**OCCUPATION** (A/N-38, Required if donor aggregate > $200)
Field description in API: CONTRIBUTOR OCCUPATION
Data field: textbox
<br>

NOTE: Currently, the aggregate field is set to 0 by default and cannot be changed in the UI. As a result, the occupation and employer "required if aggregate > $200" cannot be tested and will have to be tested in a later ticket when the aggregation amount functionality is added.

# Contribution 
#
-	**DATE RECEIVED** (NUM-8…YYYYMMDD, Required)
Field description in API: CONTRIBUTION DATE
Data field: Date picker
-	**MEMO ITEM** (A/N-1, Optional)
Field description in API: MEMO CODE
Data field: Checkbox
-	**CONTRIBUTION AMOUNT** (AMT-12, Required)
Field description in API: CONTRIBUTION AMOUNT
Data field: textbox
-	**CONTRIBUTION AGGREGATE** (AMT-12, Required)
Field description in API: CONTRIBUTION AGGREGATE
Data field: textbox (FOR NOW it will say $0.00)
_This is automatically calculated as an aggregate of this contributor's contributions YTD, in any reports, in chronological order_
<br>

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (A/N-100, Optional)
Field description in API: RECEIPT DESCRIPTION
Data field: multi-line textbox
**Description should be read-only and the user will be unable to edit. (Auto-generated in Future Ticket)**

-	**NOTE OR MEMO TEXT** (A/N-100, Optional)
Field description in API: MEMO TEXT/DESCRIPTION
Data field: multi-line textbox

**Then** I will be able to:

- Cancel
- Save & view all transactions
- Save & add another
- Edit

 Dev Note 

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See Other Receipts spec [here](https://fecgov.github.io/fecfile-validate/OTH_REC_spec.html). 
#

**Individual**
![Group C - Other Receipts - Individual.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/449df68e-5010-48e9-94a1-a248ad711cb3)

**Organization**
![Group C - Other Receipts - Organization.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8bc55278-0ad7-49be-a770-18aa42f88bd3)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
**Individual**
![Group C - Other Receipts - Individual - Filled In.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/267e9b5d-5324-499b-8184-abe61a2a7258)

![Group C - Other Receipts - Individual - Errors.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4330e0b4-9ece-4986-bbe6-bfedd40cdcdb)

**Comment by MitchellTCG** [comment]
**Organization**
![Group C - Other Receipts - Organization - Filled In.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0ea0a384-935c-460e-b936-4a854d84664b)

![Group C - Other Receipts - Organization - Errors.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/da1e43fc-8f77-4353-bd12-d7e223972a7b)

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG which Transaction Screen am I suppose to test against for Group C ?  I can enter a transaction with the type "Other Receipts" from the Transaction Screen.

Ticket clarified - Under Other dropdown select "Other Receipts"

**Comment by WiseQA** [comment]
Two (2) Test Case/Test Scripts were developed for this ticket.  One to encompass Individual and one to encompass Organization / Committee.  Reasoning is the steps are the same for these Contributor Types and test scripts can be rerun as written, and denoted in each test script.

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/3769a3d8-3424-4e32-933f-9d6d05d6d855/download](https://app.zenhub.com/files/306118986/3769a3d8-3424-4e32-933f-9d6d05d6d855/download)

[https://app.zenhub.com/files/306118986/4870398e-dcc2-48d9-b745-510c47b429a6/download](https://app.zenhub.com/files/306118986/4870398e-dcc2-48d9-b745-510c47b429a6/download)

QA review completed.  Moved to Stage Ready.
