### ISSUE TITLE
Create Group D Transaction Screen

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#232]
Business Reason 
 

As a Committee Administrator, I will be able to enter a transaction for **“Tribal Receipt”** on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Contributions from individuals/persons" Accordion link  
**Then** I can enter a transaction with the type "Tribal Receipt" from the Transaction Screen
**Then** I will be required to enter the following information (unless otherwise noted):

# Contributor 
#
-	**CONTRIBUTOR TYPE** 
Field description in API: ENTITY TYPE
Data field: Dropdown, READ-ONLY
Dropdown options: Organization
---
-	**ORGANIZATION NAME** (A/N-200, Required)
Field description in API: CONTRIBUTOR ORGANIZATION NAME
Data field: textbox
---

# Address 
#
-	**STREET ADDRESS** (A/N-34, Required)
Field description in API: CONTRIBUTOR STREET 1
Data field: textbox
-	**APARTMENT, SUITE, ETC.** (A/N-34, Optional)
Field description in API: CONTRIBUTOR STREET 2
Data field: textbox
-	**CITY** (A/N-30, Required)
Field description in API: CONTRIBUTOR CITY
Data field: textbox
-	**STATE/PROVINCE** (ALPHA-2, Required)
Field description in API: CONTRIBUTOR STATE
Data field: Dropdown
          Dropdown options: States without military
          https://docs.google.com/spreadsheets/d/17YmnaZgqvFOUyv4-Qknd8ikHe8o9LoDb/edit#gid=494776297
-	**ZIP/POSTAL CODE** (A/N-9, Required)
Field description in API: CONTRIBUTOR ZIP
Data field: textbox
<br>

# Contribution 
#
-	**DATE RECEIVED** (NUM-8…YYYYMMDD, Required)
Field description in API: CONTRIBUTION DATE
Data field: Date picker 
-	**MEMO ITEM** (A/N-1, Optional)
Field description in API: MEMO CODE
Data field: Checkbox
-	**CONTRIBUTION AMOUNT** (AMT-12, Required)
Field description in API: CONTRIBUTION AMOUNT
Data field: textbox
-	**CONTRIBUTION AGGREGATE** (AMT-12, Required)
Field description in API: CONTRIBUTION AGGREGATE
Data field: textbox (FOR NOW it will say $0.00)
_This is automatically calculated as an aggregate of this contributor's contributions YTD, in any reports, in chronological order_
<br>

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only: A/N-100, Optional)
Field description in API: RECEIPT DESCRIPTION
Data field: multi-line textbox
**Auto-populates with "Tribal Receipt"**
**Description should be read-only and the user will be unable to edit.**
-	**NOTE OR MEMO TEXT** (A/N-100, Optional)
Field description in API: MEMO TEXT/DESCRIPTION
Data field: multi-line textbox

**Then** I will be able to:

- Cancel
- Save & view all transactions
- Save & add another

 Dev Note 

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See Tribal Receipt spec [here](https://fecgov.github.io/fecfile-validate/TRIB_REC_spec.html). 
#

![Group D - Tribal Receipt - Organization.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/2d9dc1bd-3d7f-4912-a84b-6fa286e713d2)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
**Filled In**
![Group D - Tribal Receipt - Organization - Filled In.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/e8ee7418-bfb7-4e88-8f4e-6cab722097e5)

**Errors**
![Group D - Tribal Receipt - Organization- Organization - Errors.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/18328006-97db-40bb-b173-82ddefb5bea7)

**Comment by AureliaKhorsand** [comment]
Dev/QA question: For this particular transaction we're using to build this screen "Tribal Recount Receipt", the Contribution Purpose Description needs to default to "Recount Account". Can we do that as part of this ticket? Or do we need to keep this ticket as basic as possible to account for all transactions in this group?

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG which Transaction Screen am I suppose to test against for Group D ? I can enter a transaction with the type "Tribal Receipt" from the Transaction.  
Saw noted in comments within the ticket - we are using "Tribal Recount Receipt" for this ticket.   Please add to Acceptance Criteria the actual transaction name we are testing against.  Ticket has been updated.

**Comment by WiseQA** [comment]
QA reviewed on this ticket to enter, Save & view all transactions, Save and add another, and edit a Group D Transaction. Test Case/Test Scripts written to test all these functionalities per acceptance criteria.

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/160d1904-623a-44f1-9c8a-a62497c479c4/download](https://app.zenhub.com/files/306118986/160d1904-623a-44f1-9c8a-a62497c479c4/download)

QA review completed.  Moved to Stage Ready.
