### ISSUE TITLE
Allow user to select JF Transfer Memo type for sub-transaction (Dropdown)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#234]
Business Reason

As a Committee Administrator, I will be able to enter sub-transactions for under ***"Joint Fundraising Transfer"*** on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

Acceptance Criteria

***Given*** I am a Committee Administrator

  ***And*** I am editing a JF Transfer transaction on an open report

  ***Then*** I will have the _option_ to enter the following sub-transactions as follows:

*   Individual JF Transfer Memo (Group A screen)
*   Party JF Transfer Memo (Group F Screen)
*   PAC JF Transfer Memo (Group F Screen) (This link is selectable)
*   Tribal JF Transfer Memo (Group D screen)
*   Partnership Receipt Joint Fundraising Transfer Memo (Group D Screen)

(Note: 3 Links will be "dead links" until the transaction they link to exists)

![Group E - JF Transfers – 5.png]([https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/5a5ed6ac-d20c-46d4-bf20-9186453d9fc3](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/5a5ed6ac-d20c-46d4-bf20-9186453d9fc3))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1219](https://fecgov.atlassian.net/browse/FECFILE-1219)

**Comment by AureliaKhorsand** [comment]
Questions for FEC: 
1. What should the Entity type default to? Is it "Organization"? It seems like it only has one option in the specs. **Correct.**
2. How are "Donor Committee Name" and "Donor Committee ID" captured? What are these fields referring to? **Donor Committee Name will be the same as Organization Name. We should pull in the FEC ID for it if available.**

**NOTE: All Group F transactions are SUB TRANSACTIONS for a transaction from Group E!**

**Comment by MitchellTCG** [comment]
@AureliaKhorsand Updated

**Comment by AureliaKhorsand** [comment]
@MitchellTCG two quick updates - can you fix the order of the CPB and Memo Text fields? And take out "Partnership Individual Joint Fundraising Transfer Memo" as a sub-transaction option? (Updates from requirements meeting today)

**Comment by mary-tcg** [comment]
@AureliaKhorsand Wireframe updated

**Comment by Elaine-Krauss-TCG** [comment]
Ticket functionality is complete

A dropdown/button is present
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/7d1e3120-6ea8-4816-a86f-11e25e7a98bd)

Which if selected presents the following options:
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/48c0e900-6d2f-4f7f-839c-43f2bd63e107)

*QA Notes:*
Clicking on 3 of the 4 links does nothing.  Clicking on the "PAC JF Transfer Memo" option saves the current transaction and opens up the child transaction page for a JF Transfer Memo.

**Comment by Elaine-Krauss-TCG** [comment]
Modifying the *style* of the button is proving tricky as the primeNG styleClass attribute does not seem to be functioning as expected

**Comment by WiseQA** [comment]
QA Review verified JF Transfer Memo dropdown:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/44a022f8-471f-40d9-9b6e-173906883aad)

(Note:  Only "PAC Joint Fundraising Transfer Memo" is selectable as denoted in ticket) 

Select "PAC Joint Fundraising Transfer Memo"  from the dropdown list verify PAC Joint Fundraising Transfer Memo page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/93bed05e-16ae-4f34-97af-88f3f69361c0)

Enter PAC Joint Fundraising Transfer Memo, then select save, verify Transactions table is updated.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c3845ea7-af83-4d71-9cd1-33f85ec1a060)

QA Review Completed.   Moved to Stage Ready.
