### ISSUE TITLE
Allow users to view transactions within Form 3X

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#244]
Business Reason 
 

As a Committee Administrator, I will be able to view and access transactions within Form 3X so that I can verify what has been entered and edit or add more if necessary.

 Technical Notes 

- Create a Django fixture that creates a set of test transactions for testing
- All columns in the wireframe should be sortable. 

 Acceptance Criteria 
 

**Given** I am a Committee Administrator
**When** I go to the transactions page for an active Form 3X
**Then** I will see a list of existing transactions and the following information for each:
- TRANSACTION TYPE
- CONTRIBUTOR NAME
- CONTRIBUTION DATE
- MEMO CODE 
- CONTRIBUTION AMOUNT
- CONTRIBUTION AGGREGATE

 Dev Note 
 
The action column does not need to work
This table does not need to be limited to the coverage dates (**in a future ticket**)
Clicking on the Transaction Type will open the transaction (hyperlink)

![Transaction Table - Initial State.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/6dfd0f5b-44ef-44d4-ae6c-2f9d67c89c0a)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by toddlees** [comment]
User can get to the table page as a part of the f3x form flow.  next step is populating the table

**Comment by toddlees** [comment]
table is functional and sortable. you can open the transactions by clicking on the type.  Finishing a transaction takes you back to the transactions slide of the f3x report you came from.

Need to update unit tests and handle linting

**Comment by WiseQA** [comment]
Added Laura as assignee for CR per conversation with DEV.   Please change to QA Review and assignee to WISEQA when CR is completed.   Thanks !!!

**Comment by MitchellTCG** [comment]
@WiseQA 
Wireframe updated

**Comment by WiseQA** [comment]
Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/c9806f61-d032-4348-81af-dd7e2c7ad89a/download](https://app.zenhub.com/files/306118986/c9806f61-d032-4348-81af-dd7e2c7ad89a/download)

QA review completed.  Moved to Stage Ready.
