### ISSUE TITLE
Integrate validate npm package into CANDIDATE contact EDIT form validation screen

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#245]
Business Reason

As a user, I want the validation check on the contact edit forms to use the validation javascript library so it validates against the validation schema.

Acceptance Criteria

*   Current validation code for the 4 contact edit screens replaced by javascript validation npm package work as they did previously.
*   All 4 contact edit screens (Individual, Organization, Committee, Candidate) pass the sprint-6 regression tests.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1210](https://fecgov.atlassian.net/browse/FECFILE-1210)

**Comment by WiseQA** [comment]
Contacts screen selecting Candidate contact:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/818cdbba-07ea-4f70-abbb-a44cf0764972)

Successful - Contact Updated Popup Screen Shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f73c4322-e2d7-44eb-be33-a10ed303d86d)

Contacts screen showing Candidate edit name successful:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dec8a14d-7a59-42ae-a13b-f6a73d58c839)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/894386dc-d81e-4d7d-a10d-a7af05737ec0/download](https://app.zenhub.com/files/306118986/894386dc-d81e-4d7d-a10d-a7af05737ec0/download)

QA review completed.  Moved to Stage Ready.
