### ISSUE TITLE
Integrate validate npm package into ORGANIZATION contacts EDIT form validation screens

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#246]
Business Reason

As a user, I want the validation check on the contact edit forms to use the validation javascript library so it validates against the validation schema.

Acceptance Criteria

*   Current validation code for the 4 contact edit screens replaced by javascript validation npm package work as they did previously.
*   All 4 contact edit screens (Individual, Organization, Committee, Candidate) pass the sprint-5 regression tests.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1209](https://fecgov.atlassian.net/browse/FECFILE-1209)

**Comment by WiseQA** [comment]
Contacts screen selecting Organization contact:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/294e9795-d746-4e63-aa00-5ebe6c4a3905)

Successful - Contact Updated Popup Screen Shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/620eb206-e9d6-4309-b569-0401688d069f)

Contacts screen showing Organization edit name successful:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3f9cf4b7-3986-4497-b32f-2a73a95e9d70)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/96eaf319-56ac-4f21-8054-f7aa9336d3b6/download](https://app.zenhub.com/files/306118986/96eaf319-56ac-4f21-8054-f7aa9336d3b6/download)

QA review completed.  Moved to Stage Ready.
