### ISSUE TITLE
Integrate validate npm package into COMMITTEE contacts EDIT form validation screens

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#247]
Business Reason

As a user, I want the validation check on the contact edit forms to use the validation javascript library so it validates against the validation schema.

Acceptance Criteria

*   Current validation code for the 4 contact edit screens replaced by javascript validation npm package work as they did previously.
*   All 4 contact edit screens (Individual, Organization, Committee, Candidate) pass the sprint-5 regression tests.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1208](https://fecgov.atlassian.net/browse/FECFILE-1208)

**Comment by WiseQA** [comment]
Contacts screen selecting Committee contact:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bb139985-7033-4606-97e3-61eebe0840e0)

Successful - Contact Updated Popup Screen Shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/da80583c-d589-4c3a-be8e-aed5ee174b42)

Contacts screen showing Committee edit name successful:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5a009073-972a-45fa-ac5a-a88c801d7121)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/937e6d07-c0d1-4c07-83c7-7e561a66f1cb/download](https://app.zenhub.com/files/306118986/937e6d07-c0d1-4c07-83c7-7e561a66f1cb/download)

QA review completed.  Moved to Stage Ready.
