### ISSUE TITLE
Integrate validate npm package into CANDIDATE contacts ADD form validation screens

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#248]
Business Reason

As a user, I want the validation check on the contact add forms to use the validation javascript library so it validates against the validation schema.

Acceptance Criteria

*   Current validation code for the 4 contact add screens replaced by javascript validation npm package work as they did previously.
*   All 4 contact add screens (Individual, Organization, Committee, Candidate) pass the sprint-5 regression tests.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1207](https://fecgov.atlassian.net/browse/FECFILE-1207)

**Comment by WiseQA** [comment]
Candidate Contact field messages screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/83573855-1f60-4a9c-9260-54d5dfc1455d)

Candidate Contact field error messages screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/631c5450-6fe9-4df9-a85e-91e240aa77aa)

Candidate Contact "required fields" screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/61de75c5-2283-46a8-ac0a-ad4c2ee2b579)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/dd804352-5d4e-4374-baff-a2d420d495d0/download](https://app.zenhub.com/files/306118986/dd804352-5d4e-4374-baff-a2d420d495d0/download)

QA review completed.  Moved to Stage Ready.
