### ISSUE TITLE
Integrate validate npm package into ORGANIZATION contacts ADD form validation screens

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#249]
Business Reason

As a user, I want the validation check on the contact add forms to use the validation javascript library so it validates against the validation schema.

Acceptance Criteria

*   Current validation code for the 4 contact add screens replaced by javascript validation npm package work as they did previously.
*   All 4 contact add screens (Individual, Organization, Committee, Candidate) pass the sprint-5 regression tests.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1206](https://fecgov.atlassian.net/browse/FECFILE-1206)

**Comment by WiseQA** [comment]
This was not closed needs in QA review

**Comment by WiseQA** [comment]
Organization Contact field messages screen shot:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0d358ca2-a6c7-4126-b9dc-0362102afa7b)


Organization Contact field error messages screen shot:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4595d5a3-8f3d-4fb6-854b-ee789dfb3c27)

Organization Contact "required fields" screen shot:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c64f60d7-f11d-49b8-877c-b11d7f3b7ef2)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/5e08b90d-2dfc-4e86-8452-a166448579fd/download](https://app.zenhub.com/files/306118986/5e08b90d-2dfc-4e86-8452-a166448579fd/download)

QA review completed.  Moved to Stage Ready.
