### ISSUE TITLE
Integrate validate npm package into COMMITTEE contacts ADD form validation screens

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#250]
Business Reason

As a user, I want the validation check on the contact add forms to use the validation javascript library so it validates against the validation schema.

Acceptance Criteria

*   Current validation code for the 4 contact add screens replaced by javascript validation npm package work as they did previously.
*   All 4 contact add screens (Individual, Organization, Committee, Candidate) pass the sprint-5 regression tests.
*   Fix spelling of "Apartment" on Contact Profile page.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1205](https://fecgov.atlassian.net/browse/FECFILE-1205)

**Comment by WiseQA** [comment]
Fixed spelling of "Apartment" on Contact Profile page.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/de557dd9-82e2-4014-9eb7-3ca8918994df)

Committee Contact field messages screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ca2c78aa-03cc-4785-8a3f-02734520706e)

Committee Contact field error messages screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/89373175-d66a-47c0-a534-fe72a72ba987)

Committee Contact "required fields" screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/79059365-14ff-4776-93e5-f07dd43b731d)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/2c010b10-3b15-40b0-a621-6c273d5bdda0/download](https://app.zenhub.com/files/306118986/2c010b10-3b15-40b0-a621-6c273d5bdda0/download)

QA review completed.  Moved to Stage Ready.
