### ISSUE TITLE
Allow user to create a Form 3X MONTHLY REPORT for an ELECTION YEAR:  (Create Form 3X-Part 1)

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#257]
Business Reason 

As a Committee Administrator, I will be able to create a Form 3X Monthly Report for an election year.

 Acceptance Criteria 

**Given** I am a Committee Administrator
**When** I create a new Form 3X Monthly report for an election year
**Then** I will be required to select a monthly reporting frequency (stop-gap measure)
**Then** I will be required to select a report type with the following logic:

If Committee has a MONTHLY Filing frequency 
**and** creates a report for an ELECTION YEAR:
•	FEBRUARY 20 MONTHLY REPORT (M2)
•	MARCH 20 MONTHLY REPORT (M3)
•	APRIL 20 MONTHLY REPORT (M4)
•	MAY 20 MONTHLY REPORT (M5)
•	JUNE 20 MONTHLY REPORT (M6)
•	JULY 20 MONTHLY REPORT (M7)
•	AUGUST 20 MONTHLY REPORT (M8)
•	SEPTEMBER 20 MONTHLY REPORT (M9)
•	OCTOBER 20 MONTHLY REPORT (M10)
•	12-DAY PRE-ELECTION GENERAL (12G)
•	30-DAY POST-ELECTION GENERAL (30G)
•	JANUARY 31 YEAR-END (YE)
•	TERMINATION REPORT (TER)

If 12-DAY PRE-ELECTION GENERAL (12G) or 30-DAY POST-ELECTION GENERAL (30G) is selected:
•	Election on date picker appears.  **And**
•	In the state/province of dropdown appears

 Dev Note	

When a monthly report type has been selected by clicking the correct radio button, the coverage dates section will appear per ticket (web-app #137)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
![Custom Size – 31.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/16bb41b6-0a88-4967-a133-1430695671c6)

![Custom Size – 32.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/bd3edc41-da00-4a82-bf43-81285992a11c)

![Custom Size – 34.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/cf49c9ef-83f6-4486-a60c-95e7119841b5)

![Custom Size – 35.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/87bd59de-c544-4b0f-acaa-a7b83bbf8316)

**Comment by WiseQA** [comment]
Verified capability to create a Form 3X Monthly Report for a Election Year by selecting the radio buttons denoted in Wireframe.
![Ticket #257 - Monthly Report Election Year.JPG](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a06e8888-6b16-409e-942a-de93445b599d)

Verified when 12-DAY PRE-ELECTION GENERAL (12G) or 30-DAY POST-ELECTION GENERAL (30G) is selected: Election on date picker appears and In the state/province of dropdown appears:
![Ticket #257 - Monthly Report Election Year 12 day.JPG](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7279552d-6790-442b-a18a-e6393d6b5d56)

![Ticket #257 - Monthly Report Election Year 30 day.JPG](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0d0c6318-fd9f-4b25-a851-02260b298878)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/ec120fab-f4d3-4d9e-837d-e1391d1d51b6/download](https://app.zenhub.com/files/306118986/ec120fab-f4d3-4d9e-837d-e1391d1d51b6/download)

QA review completed.  Moved to Stage Ready.
