### ISSUE TITLE
Allow user to create a Form 3X MONTHLY REPORT for a NON-ELECTION YEAR  (Create Form 3X-Part 1)

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#258]
Business Reason 
 
As a Committee Administrator, I will be able to create a Form 3X Monthly Report for an election year.

 Acceptance Criteria 
 
Given I am a Committee Administrator
When I create a new Form 3X Monthly report for a non-election year
Then I will be required to select a monthly reporting frequency (stop-gap measure)
Then I will be required to select a report type with the following logic:

If Committee has a MONTHLY Filing frequency:
**and** creates a report for a NON-ELECTION YEAR:
•	FEBRUARY 20 MONTHLY REPORT (M2)
•	MARCH 20 MONTHLY REPORT (M3)
•	APRIL 20 MONTHLY REPORT (M4)
•	MAY 20 MONTHLY REPORT (M5)
•	JUNE 20 MONTHLY REPORT (M6)
•	JULY 20 MONTHLY REPORT (M7)
•	AUGUST 20 MONTHLY REPORT (M8)
•	SEPTEMBER 20 MONTHLY REPORT (M9)
•	OCTOBER 20 MONTHLY REPORT (M10)
•	NOVEMBER 20 MONTHLY REPORT (M11)
•	DECEMBER 20 MONTHLY REPORT (M12)
•	JANUARY 31 YEAR-END (YE)
•	TERMINATION REPORT (TER)

 Dev Note	
 
When a monthly report type has been selected by clicking the correct radio button, the coverage dates section will appear per ticket (web-app #137)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
![Custom Size – 31.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f1a53748-fa27-4eb9-9fc2-97a33da0b7de)

![Custom Size – 33.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/34130430-d09d-4dcb-83c8-233b4d5ef963)

![Custom Size – 36.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/79f69aa4-e709-4fe6-8573-2d5f99dbea67)

**Comment by WiseQA** [comment]
Verified capability to create a Form 3X Monthly Report for a non-election year by selecting the radio buttons denoted in Wireframe.
![Ticket #258 - Monthly Report Non Election Year.JPG](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/02dd89f6-ec6f-4390-9fd5-7cd57e3111c8)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/a6c5022f-04b9-4234-8d70-453d03433648/download](https://app.zenhub.com/files/306118986/a6c5022f-04b9-4234-8d70-453d03433648/download)

QA review completed.  Moved to Stage Ready.
