### ISSUE TITLE
Allow user to create a Form 3X QUARTERLY REPORT for an ELECTION YEAR: (Create Form 3X-Part 1)

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#259]
Business Reason 
 
As a Committee Administrator, I will be able to create a Form 3X QUARTERLY Report for an election year.

 Acceptance Criteria 
 
Given I am a Committee Administrator
When I create a new Form 3X quarterly report for an election year
Then I will be required to select a quarterly reporting frequency (stop-gap measure)
Then I will be required to select a report type with the following logic:

If Committee has a QUARTERLY Filing frequency:
**and** creates a report for an ELECTION YEAR:
•	APRIL 15 QUARTERLY REPORT (Q1) 
•	JULY 15 QUARTERLY REPORT (Q2) 
•	OCTOBER 15 QUARTERLY REPORT(Q3) 
•	12-DAY PRE-ELECTION GENERAL (12G) 
•	30-DAY POST-ELECTION GENERAL (30G) 
•	JANUARY 31 YEAR-END (YE)
•	TERMINATION REPORT (TER)

If 12-DAY PRE-ELECTION GENERAL (12G) or 30-DAY POST-ELECTION GENERAL (30G) is selected:
•	Election on date picker appears.  And
•	In the state/province of dropdown appears

 Dev Note	
 
When a quarterly report type has been selected by clicking the correct radio button, the coverage dates section will appear per ticket (web-app #137)

![Custom Size – 29.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/44ed3753-2bba-4346-ab2f-abdc8ec9519f)

![Custom Size – 30.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/dcf6730f-5b5d-434b-9698-b9a4547c794e)

![Custom Size – 39.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/946d3518-609b-47ab-ad0a-6e63c4002455)

![Custom Size – 42.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/adbe877f-db98-4c5c-af12-8564c53706cf)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by WiseQA** [comment]
Verified capability to create a Form 3X Quarterly Report for a Election Year by selecting the radio buttons denoted in Wireframe.
![Ticket #259 - Quarterly Report Election Year.JPG](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e8b47826-ca84-4719-9fc3-4cb8831cfe2d)

Verified when 12-DAY PRE-ELECTION GENERAL (12G) or 30-DAY POST-ELECTION GENERAL (30G) is selected: Election on date picker appears and In the state/province of dropdown appears:
![Ticket #259 - Quarterly Report Election Year 12 day.JPG](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3358b4a9-2dd5-4fbd-b5b5-c23da5bbf74f)

![Ticket #259 - Quarterly Report Election Year 30 day.JPG](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/eb342632-18cf-44a5-86fb-24a14cd69171)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/d8d41a21-b718-43a2-bff4-e54131f4ab13/download](https://app.zenhub.com/files/306118986/d8d41a21-b718-43a2-bff4-e54131f4ab13/download)

QA review completed.  Moved to Stage Ready.
