### ISSUE TITLE
Allow user to create a Form 3X QUARTERLY REPORT for a NON-ELECTION YEAR: (Create Form 3X-Part 1)

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#260]
Business Reason 
 
As a Committee Administrator, I will be able to create a Form 3X QUARTERLY Report for a non-election year.

 Acceptance Criteria 
 
Given I am a Committee Administrator
When I create a new Form 3X quarterly report for an election year
Then I will be required to select a quarterly reporting frequency (stop-gap measure)
Then I will be required to select a report type with the following logic:

If Committee has a QUARTERLY Filing frequency:
**and** creates a report for an ELECTION YEAR:
•	APRIL 15 QUARTERLY REPORT (Q1) 
•	JULY 31 MID-YEAR REPORT (NON-ELECTION YEAR ONLY) (MY)
•	OCTOBER 15 QUARTERLY REPORT(Q3) 
•	JANUARY 31 YEAR-END (YE)
•	TERMINATION REPORT (TER)

  Dev Note 
 	
When a quarterly report type has been selected by clicking the correct radio button, the coverage dates section will appear per ticket (web-app #137)
 
![Custom Size – 29.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ac9b8099-b504-4711-8683-9dfd0d9db4ce)

![Custom Size – 37.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f74e8661-d342-47e3-bf84-31e4f62f615c)

![Custom Size – 40.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/6b6b9f59-da8a-4d45-a377-aede0c7ad4df)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by WiseQA** [comment]
Verified capability to create a Form 3X QUARTERLY Report for a non-election year by selecting the radio buttons denoted in Wireframe.
![Ticket #260 - Quarterly Report Non Election Year.JPG](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d6823bba-a273-488f-a4ca-cced8b240712)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/2c118049-fbad-4176-9e47-6ce5282b591e/download](https://app.zenhub.com/files/306118986/2c118049-fbad-4176-9e47-6ce5282b591e/download)

QA review completed.  Moved to Stage Ready.
