### ISSUE TITLE
Allow user to create a Form 3X QUARTERLY REPORT for a SPECIAL REPORTS: (Create Form 3X-Part 1)

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#261]
Business Reason 
 
As a Committee Administrator, I will be able to create a Form 3X QUARTERLY Special Report.

 Acceptance Criteria 
 
Given I am a Committee Administrator
When I create a new Form 3X quarterly Special Report 
Then I will be required to select a quarterly reporting frequency (stop-gap measure)
Then I will be required to select a report type with the following logic:

If Committee has a QUARTERLY Filing frequency:
**and** creates a report for an ELECTION YEAR:
•	12-Day Pre-Election Primary (12P)
•	12-Day Pre-Election Runoff (12R)
•	12-Day Pre-Election Convention (12C)
•	12-Day Pre-Election Special (12S)
•	30-Day Post-Election Runoff (30R)
•	30-Day Post-Election Special (30S)

If 12-DAY or 30-Day is selected:
•	Election on date picker appears.  And
•	In the state/province of dropdown appears

 Dev Note	
 
When a quarterly report type has been selected by clicking the correct radio button, the coverage dates section will appear per ticket (web-app #137)
 

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
![Custom Size – 29.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/dbd1fa97-24a8-4179-ac1a-66553358bee3)

![Custom Size – 38.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ba55e815-a4e5-4876-8e97-fdbfd06ad850)

![Custom Size – 41.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ec457a9c-84b1-4d83-9e70-274657339e0a)

**Comment by WiseQA** [comment]
Verified capability to create a Form 3X Quarterly Report for Special reports by selecting the radio buttons denoted in Wireframe.
![Ticket #261 - Quarterly Report Special Report 12 and 30 day.JPG](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/87bbb048-a398-4b1d-b8b7-b55666f165bf)

Verified when 12-DAY PRE-ELECTION GENERAL (12G) or 30-DAY POST-ELECTION GENERAL (30G) is selected: Election on date picker appears and In the state/province of dropdown appears for each Special Report.

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/8220224c-e29a-4446-af2a-be1c0dfcb721/download](https://app.zenhub.com/files/306118986/8220224c-e29a-4446-af2a-be1c0dfcb721/download)

QA review completed.  Moved to Stage Ready.
