### ISSUE TITLE
System to prevent user from overlapping Report Coverage dates

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#262]
Business Reason

As a Committee Administrator, I will be able to set and edit the coverage dates for my Form 3X report so that, along with report type, I will be able to save a Form 3X report record to my Committee Account.

Acceptance Criteria

***Given*** I am a Committee Administrator that is creating a new Form 3X Report 

  ***When*** I select any report type

   ***Then*** I will be required to enter a starting and ending coverage date for that report 

  ***And*** I will be unable to save any dates that overlap with existing report coverage dates within the Committee Account.

  ***And if*** the dates overlap, the user will receive a message indicating what has overlapped.

Dev Notes

the message will have the following structure:

  "You have entered coverage dates that overlap the coverage dates of the following report: [Report Type Here] [Coverage dates here]

ex.

  "You have entered coverage dates that overlap the coverage dates of the following report: 12-Day Pre-Special General (12S) 03/24/2022 - 04/13/2022

This error will fire inline (on edit).

  Lastly, this error message can happen on either start or end date.

![Coverage Date Overlapping.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ed65752c-c82f-4728-8a6e-ccc0184ae67a](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ed65752c-c82f-4728-8a6e-ccc0184ae67a))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1199](https://fecgov.atlassian.net/browse/FECFILE-1199)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG this ticket looks good, thanks for splitting it out. Makes sense to me.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG this needs pointing

**Comment by AureliaKhorsand** [comment]
**5/25/22 Refinement Meeting:** Needs design solution added, moving back to AA.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG what is the status of the design solution?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Ticket and Wire updated, please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG looks great, removing UX/UI tag.

**Comment by WiseQA** [comment]
QA verified  unable to save any dates that overlap with existing report coverage dates within the Committee Account.  (Note:  No business logic developed in this ticket just date overlap)

Received message notifying  overlap "You have entered coverage dates that overlap the coverage dates of the following report: [Report Type Here] [Coverage dates here] (see below screenshot)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/58333ac4-9018-4f9a-8e74-8c1e0bc87858)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/18882d00-480c-4788-8e93-2f3fc5ad6751/download](https://app.zenhub.com/files/306118986/18882d00-480c-4788-8e93-2f3fc5ad6751/download)

QA review completed.  Moved to Stage Ready.
