### ISSUE TITLE
Create automated regression tests for QA scripts (Sprint 7)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#271]
Business Reason

As a developer or QA, I will be able to automatically run the Sprint-7 test scripts using the Cypress e2e framework so that I can run regression tests in an automated fashion.

Acceptance Criteria

***If*** I want to run the Sprint test scripts to retest the tickets

  ***When*** I run the automated tests in the Cypress framework

  ***Then*** I will get a report on which scripts failed and which passed

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1198](https://fecgov.atlassian.net/browse/FECFILE-1198)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG I created this for Sprint 7, let me know where it should go in the pipeline. Also, we should consider making an issue template so it's easy to duplicate for each sprint.

**Comment by Elaine-Krauss-TCG** [comment]
QA Scripts to implement
- [x] 119
- [x] 137
- [x] 165
- [x] 189
- [x] 192
- [x] 224
- [x] 245
- [x] 246
- [x] 247
- [x] 248
- [x] 249
- [x] 250
- [x] 257
- [x] 258
- [x] 260
- [x] 261

Laying the foundation for the Reports page E2E tests
- [x] Report-Object Generator
- [x] Automating Entering Reports
  - [x] Automating Calendar Interactions

**Comment by WiseQA** [comment]
Demo of Sprint 7 automated tests against QA test scripts.  Visual everything looked good.

QA review completed.  Moved to Stage Ready.
