### ISSUE TITLE
System to calculate Contribution Aggregate for "Other Receipts" (Group C)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#272]
Business Reason

The Contribution Aggregate YTD field must display the total of the entity's contributions from the calendar year of the report. This is necessary to track contribution limits as well as itemization logic. This amount will be a _rolling total_.

Acceptance Criteria

For the following transaction:

Other Receipts (Group C)

CONTRIBUTION AGGREGATE field must meet the following criteria:

*   AMT-12, Required, Read-Only
*   Can be negative
*   Amount Displayed will be the total of contributions that are: 
      *   From the person (ENTITY)
    *   within Aggregation Group of "OTHER_RECEIPTS"
    *   _from_ January 1 of report year _to_ the transaction Contribution Date* of the transaction.
    *   *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

AND when saving a transaction, any subsequent transactions for the same entity will update. (E.g., if a previous transaction receipt amount is _changed_, it will affect the future aggregations).

### QA Notes ###
 
-   Other Receipts (Individual, Committee, Organization)
-   Verify Contribution aggregate in the Transactions table is accumulative
-   Verify aggregate is accumulative with each contact (e.g., Individual, Committee, Organization)

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1197](https://fecgov.atlassian.net/browse/FECFILE-1197)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA review verified Other Receipts (Individual, Committee and Organization) using same Individual, Committee, Organization name the Contribution Aggregate displayed in both contacts page and Transactions table was accumulative value.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/88745152-152e-414f-8f99-61cf44b03441)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fb9fcfe1-5d5e-4bbd-acd7-5c7ba8e89aed)

No test script written - e2e testing to satisfy this ticket.

QA Review Completed.    Moved to Stage Ready
