### ISSUE TITLE
Employer/Occupation is required if Contribution Aggregate > $200 (OP1 Transactions)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#276]
Business Reason

The system will require Employer and Occupation fields if the Contribution Aggregate is greater than $200.

Acceptance Criteria

For the following transactions:

1\. Individual Receipt

  2\. Other Receipt

***If*** Contribution Aggregate is equal to or greater than $200.01

  ***Then*** "Employer" and "Occupation" will be required to save the transaction.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1195](https://fecgov.atlassian.net/browse/FECFILE-1195)

**Comment by Elaine-Krauss-TCG** [comment]
While the contribution aggregate field is not *yet* being automatically populated, it can still be tested.  I tested this on DEV, by inspecting the field using my browser's dev panel and removing the "readonly" attribute.  This allowed me to set the value of a new transaction's contribution aggregate by hand.

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/be4e68ac-cbfb-429e-a6a2-fdbf536d399c)
On setting that value on an Individual transaction, the Employer and Occupation fields became required.

In testing the Other Receipt, the front-end *did not* require the Employer and Occupation fields when the Contribution Aggregate was over $200.  The server did require the fields, though, and it properly threw a 400 error (invalid request) when I attempted to save the transaction.

**Comment by Elaine-Krauss-TCG** [comment]
A fix for this error has been developed and has been tested locally.

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/3f0bb3d6-ca50-4472-9d4a-7428992c8e6d)

**Comment by MitchellTCG** [comment]
@WiseQA 
Please wait on testing this ticket. We need rework on #472 before you can test this

**Comment by MitchellTCG** [comment]
@WiseQA 
Please wait on testing this ticket. We need rework on #472 before you can test this

**Comment by MitchellTCG** [comment]
@WiseQA @AureliaKhorsand 

I can only test independent receipts and other receipts. 

We can't test Earmark Receipts until App#459 and App#460 are pushed to Stage.

**Comment by WiseQA** [comment]
@MitchellTCG is this ticket being broken out and one made for earmark ?   This ticket as we talked needs to be at least 3 points for this sprint to pass what is working

**Comment by MitchellTCG** [comment]
### App#276 PASSED ###

#### Individual Receipt ####
1. Went to add a receipt page and chose Individual Receipt
2. Created a new contact "Harper Jarrett" but did not enter an Employer or Occupation
3. The Individual Receipt was populated new contact info (sans Employer info)
4. Added a Date Received and $200.01 Contribution Amount
5. When Save & view all transaction is selected, the error message "This is a required field" appears below BOTH Employer and Occupation
6. After entering Employer and Occupation and clicking Save & view all transactions, a popup appears informing the user an employer and occupation are being added to the contact "Harper Jarrett"
7. After clicking Continue, the individual receipt is created and the Contact is updated (Both Verified)
![Screen Shot 2022-10-17 at 10.18.15 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8e24c070-fd11-462d-b708-bbced7a7d3e4)

![Screen Shot 2022-10-17 at 10.18.23 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7a3c292d-00ba-4d9c-8317-929ba8fb0cbd)

![Screen Shot 2022-10-17 at 10.18.33 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/950fcca7-4f89-4099-b7d8-8457180f2581)
![Screen Shot 2022-10-17 at 10.18.39 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4255658e-5372-4ae7-b979-384d85e91fe0)

#### Other Receipt ####
1. Went to add a receipt page and chose Other Receipt
2. Created a new contact "Kami Hu" but did not enter an Employer or Occupation
3. The Other Receipt was populated new contact info (sans Employer info)
4. Added a Date Received and $200.01 Contribution Amount
5. When Save & view all transaction is selected, the error message "This is a required field" appears below BOTH Employer and Occupation
6. After entering Employer and Occupation and clicking Save & view all transactions, a popup appears informing the user an employer and occupation are being added to the contact "Kami Hu"
7. After clicking Continue, the individual receipt is created and the Contact is updated (Both Verified)
![Screen Shot 2022-10-17 at 10.19.43 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/2df970b0-3da4-43fc-8717-4891cf56a1a4)
![Screen Shot 2022-10-17 at 10.20.08 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/2605603a-39ed-477e-85b0-424d04b9cd0f)
![Screen Shot 2022-10-17 at 10.20.23 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a70390e5-6a30-448c-b27b-f7b9907f57f2)
![Screen Shot 2022-10-17 at 10.20.26 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d373d8c0-06f7-4b2d-af82-10e031733538)
