### ISSUE TITLE
DSP: System to calculate Contributions (line 11 and 33) (Column A)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#283]
Business Reason 
 

On the Detailed Summary Page, Line 11 should be a breakdown of the total of transactions and Line 33 should be total of transacitons with form type SA11AI, SA11AII, SA11B, SA11C _except_ for if the transaction has "Memo Code" checked. This ticket is for Column A only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 11 (column A) of Form 3X must:
-- NOT include any transactions with "Memo Code" checked
--  consist of the total of transactions with form type "SA11*"  within the report period, as follows:
-- If transaction form type is SA11AI then add total to 11.a.i Itemized in Column A
-- If transaction form type is SA11AI and the transaction is Unitemized then add total to 11.a.ii Unitemized in Column A
-- Total from both 11.a.i and 11.a.ii should be added to 11.a.iii TOTAL
-- If transaction form type is SA11B then add total to 11.b
-- If transaction form type is SA11C then add total to 11.c
--  All totals in 11.a.iii, 11.b, 11.c should be added to 11.d Total Contributions
-- The value in 11.d Total Contributions should be copied to Line 33
2. These numbers will update as needed until the report is submitted.

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

 QA NOTES
NOTE wireframe does not match ac. see comment with edits
--SA11AI:
Individual Receipt (Itemized or unitemized)
Tribal Receipt (Itemized or unitemized)
Partnership Receipt (Itemized or unitemized)
In-Kind Receipt (Itemized or unitemized)
Returned/Bounced Receipt (Itemized or unitemized)
Earmark Receipt (Itemized only)
Conduit Earmark (Deposited) (Itemized only)
Conduit Earmark (Undeposited) (Itemized only)
Unregistered Receipt from Person (Itemized or unitemized)
Unregistered Receipt from Person - Returned/Bounced Receipt (Itemized or unitemized)

--SA11B:
Party Receipt 
Party In-Kind
Party Returned/Bounced Receipt

--SA11C:
PAC Receipt
PAC In-Kind
PAC Earmark Receipt
PAC Conduit Earmark (Deposited)
PAC Conduit Earmark (Undeposited)
PAC Returned/Bounced Receipt

NOTE: The page rows in FECfile Online are currently incorrect. There is an extra "unitemized" row. Please see paper form screenshot below.
![image.png](https://images.zenhubusercontent.com/62eac7883f87756fe900911f/be8bbfd2-5657-4791-92df-10c77214edbb)

![image.png](https://images.zenhubusercontent.com/62eac7883f87756fe900911f/2c592bcc-021f-4cdb-9f0c-73863541128a)

Paper Form: 
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/f8543b5e-091d-469c-b3c2-dcd301ff9472)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by GreggMoreland** [comment]
@toddlees I updated the AC as we discussed. Is this correct?

**Comment by toddlees** [comment]
looks good!

**Comment by toddlees** [comment]
passes cr moving to qa

**Comment by toddlees** [comment]
Edits to wireframe below.  Functionality should match red markups
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/d8860aa8-f0b0-4b95-bb5e-396e40450f09)

**Comment by WiseQA** [comment]
@MitchellTCG the above wireframe is correct on discrepancies in text descriptions that need corrected ? as per our discussion this will be written in a separate ticket.

**Comment by WiseQA** [comment]
QA review verified changes were made to DSP according to redlined wireframe attached above.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6904794e-910a-408e-85b4-c610750e2b45)

QA review verified transactions with form type "SA11" and "SA11.a through SA11.d are displayed in the Detailed Summary Page.  (NOTE:  e2e testing to be run on all transactions)  Total line SA11.d  $-$97,504.68.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c549ca42-1a11-4744-a860-faf86e6332a3)

Verified total in SA11.d is displayed in line 33 ($-$97,504.68).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a945ef59-15ae-4356-bd2c-d5fa5a21d491)


**NOTE:  e2e testing to be run on all transactions**

QA Review Completed.   Moved to Stage Ready.
