### ISSUE TITLE
DSP: System to calculate Transfers (line 12) (Column A)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#284]
Business Reason 
 

On the Detailed Summary Page, Line 12 should be a total of transactions with form type SA12 _except_ for if the transaction has "Memo Code" checked. This ticket is for Column A only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 12 (column A) of Form 3X must:
--  consist of the total of transactions with form type "SA12"  **within the report period**
-- NOT include any transactions with "Memo Code" checked
2. These numbers will update as needed until the report is submitted.

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
  
The following 'Main' transaction types are included here:

- Transfer
- Joint Fundraising Transfer

![image.png](https://images.zenhubusercontent.com/62eac7883f87756fe900911f/3cfba2de-4cfd-4df5-93fa-bfc9b3e913ee)
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified Transfer and Joint Fundraising Transfer transactions are calculated in the Detailed Summary Page.   Line 12 - TRANSFERS FROM AFFILIATED COMMITTEES calculated correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/333ce5bc-239a-43be-b041-2022f83777bd)

QA Review Completed.   Moved to Stage Ready.
