### ISSUE TITLE
DSP: System to calculate Loans received (line 13) (Column A)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#285]
Business Reason 
 

On the Detailed Summary Page, Line 13 should be a total of all transactions with form type SA13 _except_ for if the transaction has "Memo Code" checked. This ticket is for Column A only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 13 (column A) of Form 3X must:
--  consist of the total of all transactions with form type "SA13" within the report period
-- NOT include any transactions with "Memo Code" checked

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

 QA NOTES
Transaction types included here:
- Loan Received From Individual
- Loan Received From Bank

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "ALL LOANS RECEIVED" are calculated correctly in Line 13 - Column A. (Note: tested with Loan Received From Individual and Loan Received From Bank to verify calculation is correct)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTZYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5c5c89ee4dac3502c9431042671f0f4e04b48354/image.png)

QA Review Completed. Moved to Stage Ready.
