### ISSUE TITLE
DSP: System to calculate Loan repayments received (line 14) (Column A)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#286]
Business Reason 
 

On the Detailed Summary Page, Line 14 should be a total of all transactions with form type SA14 _except_ for if the transaction has "Memo Code" checked. This ticket is for Column A only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 14 (column A) of Form 3X must:
--  consist of the total of all transactions with form type "SA14"  within the report period
-- NOT include any transactions with "Memo Code" checked

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
 Transactions included here:

- Loan Repayment Received
- NOTE for testing:   Loan By Committee > will create the Schedule A Loan Repayment Received
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by Elaine-Krauss-TCG** [comment]
This run of the unit tests on CircleCI includes all 8 DSP line additions and their respective tickets.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakNYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bc82aa921caa837d82c57f9b0c6265630c404cad/image.png)

**Comment by WiseQA** [comment]
QA review verified "LOAN REPAYMENTS RECEIVED" are calculated correctly in Line 14 - Column A. (Note: tested with Loan Repayment Received (Schedule A) to verify calculation is correct - without Memo Item checked)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0NYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--17f67a0ef89aa8c9693fad41951ab96be76b28c7/image.png)

QA Review Completed. Moved to Stage Ready.
