### ISSUE TITLE
DSP: System to calculate Offsets to Operating Expenditures (line 15 and 37) (Column A)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#287]
Business Reason 
 

On the Detailed Summary Page, Line 15 should be a total of all transactions with form type SA15 (Offsets to Operating Expenditures) _except_ for if the transaction has "Memo Code" checked. This number should be duplicated on Line 37. This ticket is for Column A only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 15 (column A) of Form 3X must:
--  consist of the total of all transactions with form type "SA15" (Offsets to Operating Expenditures) within the report period
-- NOT include any transactions with "Memo Code" checked
-- _Note: This currency amount can be positive or negative._

2. Detailed Summary Page Line 37 (column A) of Form 3X must be an exact duplicate of Line 15 (column A), respectively.

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

 QA NOTES
Note:  Memo Item Box MUST be unchecked to display currency amount in Detailed Summary Page
If Memo Item Box checked will not display currency amount in Detail Summary Page

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
7/27 Discussion with Dev team + Laura: Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

**Comment by WiseQA** [comment]
@AureliaKhorsand @GreggMoreland - Can the total of the transactions be a negative value for the Detailed Summary Page Line 15 (column A) of Form 3X ?  If so, can we update acceptance criteria to reference negative value ?

**Comment by AureliaKhorsand** [comment]
@WiseQA yes, just confirmed with Ryan. Will add to AC now.

**Comment by WiseQA** [comment]
QA Review verified calculations of contribution amounts displays in Detailed Summary Report, lines 15 and 37.  (Note:  Offsets to Operating Expenditures only was tested per Acceptance Criteria)
1.  Verified "Memo Item" box is unchecked.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7d83c7f3-81ce-494c-ae59-b65034c9a404)

2,  Verify Contribution amounts are calculated in Lines 15 and 37 of Display Summary Report.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b7565819-9415-4403-a617-8599c018ce46)

Line 15:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f8dc1054-51fc-4494-a87e-800c0613a9db)

Line 37:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3330a4e3-0694-44f7-8c5c-459f0a0eeb63)

Verified when "Memo Item" selected will not calculate in lines 15 and 37.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c73a2e8c-a5bf-469c-a2ca-78be14b36453)

Line 15:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c4f7efe5-6eaf-4883-8bd3-488debbc3cb7)

Line 37:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c7b6ee90-1d73-4eda-80e3-0f4af6dd904a)

QA Review Completed.  Moved to Stage Ready.
