### ISSUE TITLE
DSP: System to calculate Refunds (line 16) (Column A)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#288]
Business Reason 
 

On the Detailed Summary Page, Line 16 should be a total of transactions with form type SA16 _except_ for if the transaction has "Memo Code" checked. This ticket is for Column A only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 16 (column A) of Form 3X must:
--  consist of the total of transactions with form type "SA16"  within the report period
-- NOT include any transactions with "Memo Code" checked

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
 
Main "Receipt" transaction types under Refunds Accordion:
- Refund of Contribution to Federal Candidate
- Refund of Contribution to Other Political Committee
- Refund of Contribution to Unregistered Committee

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Transfers to Affiliates/Other Committees - Disbursement Line 16 (Column A).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dd42080c-f376-4327-8e91-0a666c8dd95b)

Verified when Memo Item checkbox is selected the transaction amount is not calculated in Line 16 Column A.

QA Review Completed.  Moved to Stage Ready.
