### ISSUE TITLE
DSP: System to calculate Other Federal Receipts (line 17) (Column A)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#289]
Business Reason 
 

On the Detailed Summary Page, Line 17 should be a total of transactions with form type SA17 _except_ for if the transaction has "Memo Code" checked. This ticket is for Column A only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 17 (column A) of Form 3X must:
--  consist of the total of transactions with form type "SA17"  within the report period
-- NOT include any transactions with "Memo Code" checked
2. These numbers will update as needed until the report is submitted.

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

 QA NOTES
The following transaction types are applicable here:

1.	Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account
2.	Joint Fundraising Transfer - National Party Pres. Nominating Convention Account
3.	Joint Fundraising Transfer - National Party Headquarters Buildings Account
4.	Other Receipts
5.	Individual Receipt - Non-Contribution Account
6.	Other Committee Receipt - Non-Contribution Account
7.	Business/Labor Organization Receipt - Non-Contribution Account
8.	Individual Recount Receipt
9.	Party Recount Receipt
10.	PAC Recount Receipt
11.	Tribal Recount Receipt
12.	Partnership Recount Account Receipt
13.	Individual National Party Recount/Legal Proceedings Account
14.	Party National Party Recount/Legal Proceedings Account
15.	PAC National Party Recount/Legal Proceedings Account
16.	Tribal National Party Recount/Legal Proceedings Account
17.	Partnership National Party Recount/Legal Proceedings Account 
18.	Individual National Party Headquarters Buildings Account
19.	Party National Party Headquarters Buildings Account
20.	PAC National Party Headquarters Buildings Account
21.	Tribal National Party Headquarters Buildings Account
22.	Partnership National Party Headquarters Buildings Account
23.	Individual National Party Pres. Nominating Convention Account
24.	Party National Party Pres. Nominating Convention Account
25.	PAC National Party Pres. Nominating Convention Account
26.	Tribal National Party Pres. Nominating Convention Account
27.	Partnership National Party Pres. Nominating Convention Account
28.	Earmark Receipt for National Party Recount/Legal Proceedings Account (Contribution)
29.	Earmark Receipt for National Party Pres. Nominating Convention Account (Contribution)
30.	Earmark Receipt for National Party Headquarters Buildings Account (Contribution)

![image.png](https://images.zenhubusercontent.com/62eac7883f87756fe900911f/51d1e6bb-8686-46ac-ace4-39d83123230f)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/23d88796-a503-4e37-8718-3f9c1f4961d0)

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/e431cfc9-cc9b-4c88-9f0f-2b2135dde810)

**Comment by Elaine-Krauss-TCG** [comment]
SA17 transactions are being tallied appropriately and are showing up on the DSP

**Comment by toddlees** [comment]
passes cr moving to qa

**Comment by WiseQA** [comment]
QA review verified transactions with form type "SA17" within the report period the  Detailed Summary Page Line 17 (column A) of Form 3X consisted of the total of transactions.   (NOTE:  e2e testing to be run on all transactions)  Total line 17 $49,383.07.  

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2319df3e-fb9d-4ba3-9a65-6378c175e64d)

Verified transaction with "memo code" checked does not calculate in DSP for line 17.  Total line 17 remains $49,383.07 and does not include transaction amount of $3,000.00.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/560d55b7-1211-4086-b069-d55ee23e1c65)

**NOTE:  e2e testing to be run on all transactions**

QA Review Completed.   Moved to Stage Ready.
