### ISSUE TITLE
 Allow user to create a PDF/print preview of the Form 3X report (Page 1, SP, DSP, SA)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#290]
Business Reason

As a user, I will be able to generate and view a PDF of my report so that I can see how Form 3X looks as a paper form.

Acceptance Criteria

***Given*** a report in any status

  ***When*** the user goes to the "PDF/Print Preview" page

  ***Then*** they can generate a PDF of their report in it's current state

  ***And*** when they click to generate a PDF, they will receive a message indicating "This may take a moment..."

  ***And*** if after 5 seconds the PDF:

*   IS ready: the user will have the option to download it as a PDF by opening it in a new tab; the system will provide a date/time stamp for when the PDF was generated; and the button to compile a new PDF will be available.
*   IS NOT ready: the system will indicate that "Your report is still being processed. Please check back later to access your PDF" and the process will continue in the background until it is ready _(Dev note: check status endpoint each time page is accessed)_

***And*** once the URL is no longer available from WebPrint service _(after 24 hours)_, the page resets _(only one button for Compile PDF)_.

Dev Tasks

  Create an endpoint on the webservice worker to submit a fec file to the FEC WebPrint service. Return the WebPrint response to the Celery broker

Documents: [https://efoservices.fec.gov/static/webprint_help.html#webservice](https://efoservices.fec.gov/static/webprint_help.html#webservice)
[https://webforms.fec.gov/psa/getstarted.htm](https://webforms.fec.gov/psa/getstarted.htm)

![Compile 2.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8b1a919e-3366-4a4b-b92f-de32397e2e85](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8b1a919e-3366-4a4b-b92f-de32397e2e85))

![Custom Size – 85.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a6a03b6c-d74d-4476-bb14-a4976ba485a2](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a6a03b6c-d74d-4476-bb14-a4976ba485a2))

![Print Preview 2.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/66ec3992-e92d-439a-9cfe-bf29ba402e7e](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/66ec3992-e92d-439a-9cfe-bf29ba402e7e))

![files1920.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4859ec7a-e3a3-4b0c-9b60-7da32d9500a2](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4859ec7a-e3a3-4b0c-9b60-7da32d9500a2))

![loading--primary.gif]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a2699e4c-620d-421b-99dc-4a23c382af52](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a2699e4c-620d-421b-99dc-4a23c382af52))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1186](https://fecgov.atlassian.net/browse/FECFILE-1186)

**Comment by AureliaKhorsand** [comment]
BA Note: Any transactions or transaction totals not from SA will be zero.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand Updated

**Comment by AureliaKhorsand** [comment]
[WebPrint page at EFO services](https://efoservices.fec.gov/static/webprint_help.html#webservice)

**Comment by AureliaKhorsand** [comment]
After chatting with @Elaine-Krauss-TCG, determined that the "Download PDF" button is superfluous since it will also open the PDF in a new tab unless we code some extra fluff. AC changed to just one button to "Open PDF", along with the button to compile a new one.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by toddlees** [comment]
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/607f8ba9-5ca7-42a3-bac8-63b6030ba42c)

**Comment by toddlees** [comment]
Pdf generated from webprint
[https://app.zenhub.com/files/306118986/7741db0e-3ea5-45bb-a8f8-9644289e990f/download](https://app.zenhub.com/files/306118986/7741db0e-3ea5-45bb-a8f8-9644289e990f/download)

**Comment by WiseQA** [comment]
QA "Visual" Review with DEV as a demo verifying .pdf generated from webprint using FEC production site due to errors received from test site.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6a032fd2-d364-431a-be19-f9ff1af7fbdf)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cd27b5b2-0cfb-4568-a6d3-f87074c7000c)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4e59006a-293d-4644-84fb-137ecb161737)

QA "Visual" Inspection Complete.   Moved to Stage Ready.
