### ISSUE TITLE
Allow user to submit Form 3X report (front-end only, not connected to FEC)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#291]
Business Reason

As a user, I will be able to submit a completed Form 3X report so that I can generate a *.fec file and send it to the FEC.

Acceptance Criteria

### QA Notes ###
**Given** the Form 3X report includes all required information
**When** a user is on the "Submit Report" page 
**Then** the will be required to check the box with the following text before being able to submit:
> I certify that I have examined this Statement and to the best of my knowledge and belief it is true, correct, and complete. NOTE: Submission of false, erroneous, or incomplete information may subject the person signing this Statement to the penalties of 52 U.S.C. § 30109.

**And** when the user clicks "Submit your Form3X", they will receive a confirmation popup with the following language: 
> Are you sure you want to submit this form electronically? Please note that you cannot undo this action. Any changes needed will need to be filed as an amended report.

**And** when the user confirms submission
**Then** the user will be redirected to the View Reports page with an indication of submission.

- Dev Note: Dev will need to set up an API endpoint that provides a mock response to the front-end similar to one coming from the FEC WebUpload API

https://images.zenhubusercontent.com/306118986/de0e6507-e4db-4d9e-959d-35e208fb353d/submit.mp4

![Submit Report - Empty – 1.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/b007d232-534b-483b-b497-33db1a15901b)
![Submit Report - Empty – 2.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/9ca4d6f1-67c1-4bb4-9030-d661db7fa24e)

![Submit Report - Amend – 3.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/c49e3e4a-d97d-4ae4-8e7b-8a577cb72083)

TEXT:
If you any questions on how to enroll, confirming your email, two-factor authentication, or your Personel Key please go to the following page: **FEC Electronic Filing Password Assignment System Help**

link for password assignment: https://webforms.fec.gov/psa/help.htm

## QA Notes ##
To get to the confirmation page, edit a report and the report navigation in the left sidebar will appear. Select "SUBMIT YOUR REPORT" -> "Submit report"

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1185](https://fecgov.atlassian.net/browse/FECFILE-1185)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand  Submit will be two steps. I'm not sure how you want to split the pages. We can discuss. Please review the prototype video.

**Comment by AureliaKhorsand** [comment]
BA Note: Need confirmation of language from FEC for both messages, but need to push ticket through. Can update text as needed later.

**Comment by mjtravers** [comment]
Passes CR, sending to QA

**Comment by MitchellTCG** [comment]
Please make sure this validation works for the E-filing password

![Screen Shot 2022-07-25 at 7.53.38 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/6817c94c-d010-4e73-a9a2-88458f65570a)

**Comment by WiseQA** [comment]
QA review validation of E-filing password not working.  See above validation for E-filing password. 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0ca3afbb-efee-4c1d-8f65-90788abc2ed6)

Returned to "In Progress" for PW validation.

**Comment by mjtravers** [comment]
Added password validation. Ready for CR

**Comment by mjtravers** [comment]
Passed CR. Sent to QA

**Comment by WiseQA** [comment]
QA review completed and verified Submission of Form 3x (front-end-only).

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/f174a623-fd55-4876-abea-59b2e29f943d/download](https://app.zenhub.com/files/306118986/f174a623-fd55-4876-abea-59b2e29f943d/download)

QA review completed.  Moved to Stage Ready.
