### ISSUE TITLE
Create Submission Status Page

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#292]
Business Reason 
 

As a user, I will be able to view the status of a report submission to FEC so that I can determine if further action is needed on my part.

 Acceptance Criteria 

### QA Notes ### 
 **If** I am viewing a report that has been submitted to FEC
**When** I go to the Submission Status page
**Then** I will see the following information:
- Form Type
- Report Type
-Coverage Dates
- Confirmation Emails (entered before report submission)

**And** I have the option to close and return to Manage Reports from the page.

![Processing.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/5f8e3b44-8d1b-406f-a562-19023ab89a2b)

![FormStack-image.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/c7b7ca37-127a-4db1-98f3-df1a4bf1329e)

## QA Notes ##
To get to the status page, edit a report and the report navigation in the left sidebar will appear. Select "SUBMIT YOUR REPORT" -> "Report status"
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
I attached one successful submission and one pending/processing submission

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA review - Submission Status Page missing "Confirmation Emails" as denoted in the wireframe above.   

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ff52c25a-3073-411b-b722-ff4e432fb926)

Returned to "In-Progress".  

Retested the Submission Status Page, after clearing cache - the emails populated correctly on the Status Page.  

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e6163dfc-cd7f-42e2-be27-7a2b298dc4ee)

@mjtravers  @MitchellTCG Returned to QA review, no further DEV work needed at this point in time.

**Comment by WiseQA** [comment]
QA review completed and verified Submission Status Page is displayed as denoted in Wireframes.  (Note:  Complete Ticket 334 first before verifying this ticket)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/0c21c5cf-0269-40c3-9eeb-d2bc45fcd07a/download](https://app.zenhub.com/files/306118986/0c21c5cf-0269-40c3-9eeb-d2bc45fcd07a/download)

QA review completed.  Moved to Stage Ready.
