### ISSUE TITLE
System to require Memo Item if Transaction Date falls outside Report Coverage Dates

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#294]
Business Reason 
 

Although users can add transactions with dates outside report coverage dates, those transactions _must_ be memo items, so the system will require it if they try to save.

 Acceptance Criteria 
 

**Given** I am adding or editing a transaction within a report
**If** I add a Date Received prior to the Report start date **or** after the Report end date
**Then** I will receive a popup message indicating that the Memo Item will be required, with the following text: "Just checking... [MM/DD/YYYY] falls outside the report coverages dates of [MM/DD/YYYY  - MM/DD/YYYY]. Did you mean to date this transaction outside of the report coverage period? If the date entered is correct, this transaction must be a Memo Item." with the option (Close) to continue.

**And**When I click 'close' on the Popup message
**And**If I click the Memo checkbox
**Then** I will be able to save the transaction.

**If** I try to uncheck Memo Item
**Then** I will get a popup warning message informing me that this field is required because the transaction falls outside the report coverage dates, with the following text: "Just checking... [MM/DD/YYYY] falls outside the report coverages dates of [MM/DD/YYYY  - MM/DD/YYYY]. Did you mean to date this transaction outside of the report coverage period? If the date entered is correct, this transaction must be a Memo Item." with the option (Close) to continue.

 Dev Notes 

After the user enters a date outside the coverage dates, right after the inline validation sees the uses case a warning modal will appear titled  "Just checking"
Validation error red test under check box if user tries to save without Memo Item checked : This is required.

# Modal Updates 
#
- [ ] "Just checking..." font: Gandhi Serif Bold, Font-size: 36px, color: #212121
- [ ] Body text - font: karla, font-size: 14px, color: #212121

 Wireframes 

![294 - warning message – 1.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7f740fa1-5a9f-4e56-b005-dfaa6e8c59c5)
![294 - warning message – 2.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/bde56996-1d2d-4cec-848c-ebe33c0db380)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@mary-tcg 

Please create a wire for this by COB today

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @JonellaCulmer here is what we discussed at the requirements session:

- Jonella will look into options for when a user returns later and needs information on why Memo Item is read-only (if we go the pop-up route)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand  @mary-tcg @JonellaCulmer 
Updated

**Comment by MitchellTCG** [comment]
Per the design review with Debbie yesterday: Please place this on hold.

**Comment by MitchellTCG** [comment]
I'll move to AA after I talk to Matt

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland @WiseQA @mjtravers 
Here is the updated workflow:
https://images.zenhubusercontent.com/306118986/a47c0d17-23bb-45f7-9973-0112b1981ea0/294___system_to_require_memo_iten_if_transaction_date_falls_outside_report_coverage_dates_v5.mp4

After everyone on the team thinks this is cool, we can show this to Ryan

**Comment by AureliaKhorsand** [comment]
Updated as of 3/20/23

https://images.zenhubusercontent.com/306118986/f9055ddf-215e-434f-bcf3-65c37bf9748f/294___system_to_require_memo_iten_if_transaction_date_falls_outside_report_coverage_dates.mp4

**Comment by toddlees** [comment]
@MitchellTCG @AureliaKhorsand Is this fragment a leftover from the old workflow?

> If I edit the Date Received to BLANK, or to fall within the report coverage dates
Then the system will uncheck the Memo Item (no longer read-only)
And I can edit "Memo Item" as needed.

What is supposed to happen if a user doesn't check memo item after selecting an out of bounds date and tries to save?  do we show a validation error under the check box?

**Comment by AureliaKhorsand** [comment]
@toddlees @Elaine-Krauss-TCG Please note the changes in the ticket - the popup language has changed to accommodate all transactions (including transactions where Memo Item is already checked). Validation text is now in the Dev notes. ACs updated to remove old information.

@MitchellTCG can you please update the wires with the new text?

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG below is the screenshot for the "Just checking . . . " popup window.   However the screenshot in the above wireframe the popup window font looks different.    

Is this correct ?


![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/757c2bf6-3717-48fd-99e8-96c8d7c3c731)

**Comment by MitchellTCG** [comment]
@mjtravers @Elaine-Krauss-TCG 
I updated wires to match the AC.
I also added CSS for the fonts in the modal in the Dev Notes Section.

in new wire, there is red error message under memo item check box if the user tries to save if the date is outside the report date.

**Comment by WiseQA** [comment]
@mjtravers  @MitchellTCG Per above update to this ticket moving back to In-Progress for fixes.   (Please see updated wireframes as denoted above)

**Comment by Elaine-Krauss-TCG** [comment]
the "Just Checking" box after changes at >2500 pixels wide:
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/ffcef01d-5569-4f13-9bba-38088f448a01)

At 1024 pixels wide:
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/eae8365a-89ab-4dc4-96a2-b13baddd89da)

**Comment by MitchellTCG** [comment]
@Elaine-Krauss-TCG 
Please make the pop-up a fixed width of 496px

Also please change line-height in the body of the modal to:
line-height: 1.3;

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/2e969683-2da9-415e-b852-3c2e45654f10)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review the "This is required field" is below the Memo Item Checkbox (see wireframe above)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5c36f4d3-b5a4-45e6-a791-d622005a45c1)

@mjtravers @MitchellTCG returned to In-Progress for this fix.

**Comment by Elaine-Krauss-TCG** [comment]
Sorry, sorry
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/26091694-e1cf-4ab5-b15a-3bc0b7f20d0d)

**Comment by mjtravers** [comment]
back to In Progress to look at AMOUNT input box turning red after just checking modal closed

**Comment by mjtravers** [comment]
Fix to positioning of memo item error message made. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when adding a transaction outside the Report Coverage date the following popup window appears.  (Note: red background to be fixed in future ticket and changed to Black [fecgov/fecfile-web-app] UI: Fix RED Background overlay (Issue #997)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/245eaa93-0c99-47fa-bcf4-9b168db42b98)

Select close return to transactions page, verify "This is a required field." is displayed below the Memo Item.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7f9da529-3b93-49ff-9dd5-68a2d6402590)

Select the Memo Item checkbox box

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6105be11-9cb2-4522-8a4e-2e5d2d676a9b)

Then select save verify transaction is updated.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c3cad5c1-baee-433d-bf9f-859f2172dd84)

QA review verified both adding and editing a transaction.

QA Review Completed.  Moved to Stage Ready.
