### ISSUE TITLE
Install git repository protection against committing secret info

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#30]
To guard against inadvertently committing secret information such as passwords to the public git repositories, add an installation process for AWS git secrets.

[https://github.com/awslabs/git-secrets](https://github.com/awslabs/git-secrets)

There is currently a MacOS solution for this covered by caulking provided by Cloud.gov. We need a non-MacOS solution:

[https://github.com/cloud-gov/caulking](https://github.com/cloud-gov/caulking)

Acceptance criteria:

  1) Should install git pre-hook to check for secrets globally

  2) README.md file for fecfile-online updated with install instructions

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1358](https://fecgov.atlassian.net/browse/FECFILE-1358)

**Comment by mjtravers** [comment]
The code for this ticket is a developer utility script and not subject to the regular QA procedures. Assigning to Shelly.

**Comment by WiseQA** [comment]
As noted no QA action required on this ticket - moved to closed as ticket complete.
