### ISSUE TITLE
System to indicate to user which transactions are "unitemized"

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#302]
Business Reason

It should be made clear to the user which transactions are unitemized, so they know what will not have it's own line item on the *.fec file and can take action accordingly.

Acceptance Criteria

***If*** a transaction is unitemized,

  ***When*** the user is on the Manage Transactions page

  ***Then*** it will be clear that the transaction is unitemized.

![Unitemized.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/c589d793-97b9-44bf-9bb8-ac61feba57d4](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/c589d793-97b9-44bf-9bb8-ac61feba57d4))

### QA Notes ###
As of 10/19/22, the following transactions can be unitemized:
1. Individual Receipt (Group A)
2. Tribal Receipt (Group D)
3. Offsets to Operating Expenditures (Group B)
4. Other Receipts (Group C)

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1181](https://fecgov.atlassian.net/browse/FECFILE-1181)

**Comment by MitchellTCG** [comment]
Added wire based on the UX team discussion 10/17/22
@JonellaCulmer @mary-tcg @AureliaKhorsand

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/c2d8155b-18a9-4f00-abcf-6b80d629cac5)

**Comment by mjtravers** [comment]
Passes CR, sending to QA.

**Comment by WiseQA** [comment]
QA review verified the System indicates on the Transactions table the "**Unitemized**" transactions (see screenshot below).   Transactions verified were:  Individual Receipt (Group A), Tribal Receipt (Group D), Offsets to Operating Expenditures (Group B), Other Receipts (Group C) (as denoted in ticket).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1d82c960-9252-4b85-aacf-3c2e0ee470d9)

QA Review Completed.  Moved to Stage Ready.
