### ISSUE TITLE
System to auto-populate coverage dates based on report type selection

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#303]
See [this spreadsheet ]([https://docs.google.com/spreadsheets/d/1c4cJvmAChcKl9o8a_5w0Zi0iizUTyxYa/edit#gid=1409996071)as](https://docs.google.com/spreadsheets/d/1c4cJvmAChcKl9o8a_5w0Zi0iizUTyxYa/edit#gid=1409996071)as) a starting point.

Business Reason

As a Committee Administrator, I will be able to view report coverage dates that are populated by the system so that I can create my report with the standard dates or edit the dates if necessary.

Acceptance Criteria

***If*** I create a new report

 ***When*** I select 'Reporting Frequency', 'Time Period', and 'Report Type'

 ***Then*** The system will set the 'Covering Period' 'From' and 'To' dates as follows:

Report type code: M2

 Coverage start Date: 1/1/YYYY (YYYY = current year)

 Coverage End Date: 1/31/YYYY (YYYY = current year)

Report type code: M3

 Coverage start Date: 2/1/YYYY (YYYY = current year)

 Coverage End Date: 2/28/YYYY (YYYY = current year)

 ( ***Note:*** In leap years, the Coverage End Date is 2/29/YYYY)

Report type code: M4

 Coverage start Date: 3/1/YYYY (YYYY = current year)

 Coverage End Date: 3/31/YYYY (YYYY = current year)

Report type code: M5

 Coverage start Date: 4/1/YYYY (YYYY = current year)

 Coverage End Date: 4/30/YYYY (YYYY = current year)

Report type code: M6

 Coverage start Date: 5/1/YYYY (YYYY = current year)

 Coverage End Date: 5/31/YYYY (YYYY = current year)

Report type code: M7

 Coverage start Date: 6/1/YYYY (YYYY = current year)

 Coverage End Date: 6/30/YYYY (YYYY = current year)

Report type code: M8

 Coverage start Date: 7/1/YYYY (YYYY = current year)

 Coverage End Date: 7/31/YYYY (YYYY = current year)

Report type code: M9

 Coverage start Date: 8/1/YYYY (YYYY = current year)

 Coverage End Date: 8/31/YYYY (YYYY = current year)

Report type code: M10

 Coverage start Date: 9/1/YYYY (YYYY = current year)

 Coverage End Date: 9/30/YYYY (YYYY = current year)

Report type code: M11

 Coverage start Date: 10/1/YYYY (YYYY = current year)

 Coverage End Date: 10/31/YYYY (YYYY = current year)

Report type code: M12

 Coverage start Date: 11/1/YYYY (YYYY = current year)

 Coverage End Date: 11/30/YYYY (YYYY = current year)

Report type code: MY

 Coverage start Date: 1/1/YYYY (YYYY = current year)

 Coverage End Date: 6/30/YYYY (YYYY = current year)

Report type code: Q1

 Coverage start Date: 1/1/YYYY (YYYY = current year)

 Coverage End Date: 3/31/YYYY (YYYY = current year)

Report type code: Q2

 Coverage start Date: 4/1/YYYY (YYYY = current year)

 Coverage End Date: 6/30/YYYY (YYYY = current year)

Report type code: Q3

 Coverage start Date: 7/1/YYYY (YYYY = current year)

 Coverage End Date: 9/30/YYYY (YYYY = current year)

Report type code: YE (Non-election year, Quarterly Reporting Frequency)

 Coverage start Date: 7/1/YYYY-1 (YYYY = current year; 'YYYY-1' = previous year)

 Coverage End Date: 12/31/YYYY-1 (YYYY = current year; 'YYYY-1' = previous year)

Report type code: YE (Non-election year, Monthly Reporting Frequency)

 Coverage start Date: 12/1/YYYY-1 (YYYY = current year; 'YYYY-1' = previous year)

 Coverage End Date: 12/31/YYYY-1 (YYYY = current year; 'YYYY-1' = previous year)

Report type code: YE (Election year)

 Coverage start Date: 10/1/YYYY-1 (YYYY = current year; 'YYYY-1' = previous year)

 Coverage End Date: 12/31/YYYY-1 (YYYY = current year; 'YYYY-1' = previous year)

***And*** I should be allowed to edit those dates before I

*   Click 'Save'
*   Click 'Save and Continue'

***And*** even if I manually edit the dates, if I select another report type

 ***Then*** the default dates for the report type selection will auto-populate.

### QA Notes ###
- In addition to checking that the correct dates are auto-populated, verify the overlapping dates message still appears when there is overlap(this should still occur).
- If a report type is chosen, like 30R or TER, where there is no default date range (any report code not listed above), the date range will not be updated. 
- Dev team - please do not clear out reports in database in QA Committee ID Account before sending to QA.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1180](https://fecgov.atlassian.net/browse/FECFILE-1180)

**Comment by AureliaKhorsand** [comment]
_BA Note from PI 2 Planning: Quarterly filers may need to file special reports. By law, some may need to file pre-election report and those coverage dates need to be manually edited. It also may affect the quarterly report before and after. If we want to pull coverage dates into the App, should read from EFO. This could be a question of defaulting to something, but allowing the user to change_

**Comment by toddlees** [comment]
@AureliaKhorsand @MitchellTCG @mjtravers I have developed this such that, when a report code is selected that is not represented in the rules above (e.g. TER or 30R), the coverage dates are untouched.  Can someone confirm that this is correct?

**Comment by WiseQA** [comment]
@toddlees @MitchellTCG @mjtravers per today's conversation - Dev team - please do not clear out reports in database in QA Committee ID Account before sending to QA.  Doing workaround for testing.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA. Per discussion, no reports will be deleted from the database as an alternative account with minimal data will be used for testing.

**Comment by toddlees** [comment]
@WiseQA I just updated the QA notes to clarify a special case, where the user selects a report code that doesn't have an associated date range.

**Comment by WiseQA** [comment]
During QA review verified, got overlapping error for  Report type code: M6
Coverage start Date: 5/1/YYYY (YYYY = current year)
Coverage End Date: 5/31/YYYY (YYYY = current year)


![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/35aeee4c-a2e8-4d51-906b-85c65f4249a0)

Report coverage dates were already created as denoted in screenshot below

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/79075cfc-d906-4ed8-aaf2-8b31ccf91828)

Monthly Reports QA review verified "Election Year"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/52e29faa-c4f0-4e27-9796-c8d3f242233c)

@MitchellTCG @mjtravers @toddlees e2e testing needs to be run across the application for the coverage dates to validate "Non-Election" year, quarterly reports, etc.   

QA review completed as "Ad-hoc" testing.   Moved to Stage Ready.
