### ISSUE TITLE
Allow user to select a report type when creating Form 3X report (Design Updates)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#309]
Business Reason

As a Committee Administrator, I will be able to create a Form 3X report and specify the report type for Form 3X so that, along with coverage date, I will be able to save a Form 3X report record for my Committee Account.

Purpose

Update the how the Quarterly Reports are displayed on Report Creation.

  Replacing Election year, Non-Election Year, and Special Election with just two choices Election Year and Non-Election Year.

Acceptance Criteria

***Given*** I am a Committee Administrator

  ***When*** I create a new Form 3X report

  ***Then*** I will be ***required*** to select a report type with the following logic:

*   If Committee has a QUARTERLY Filing frequency: 
      *   And creates a report for an ELECTION YEAR: 
            *   April 15 Quarterly Report (Q1)
        *   July 15 Quarterly Report (Q2)
        *   October 15 Quarterly Report(Q3)
        *   12-Day Pre-General (12G)
        *   30-Day Post-General (30G)
        *   January 31 Year-end (YE)
        *   Termination report (TER)
        *   12-Day Pre-Primary (12P)
        *   12-Day Pre-Runoff (12R)
        *   12-Day Pre-Convention (12C)
        *   30-Day Post-Runoff (30R)
        *   30-Day Post-Special (30S)
        *   TER Termination

                   ![Quarterly - Election Year.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/fd4e398a-db6a-405c-907c-e737aa7afb18](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/fd4e398a-db6a-405c-907c-e737aa7afb18))

– And creates a report for a NON ELECTION YEAR:

  — July 31 Mid-Year Report (MY)

  — January 31 Year-end (YE)

  — 12-Day Pre-Primary (12P)

  — 12-Day Pre-Runoff (12R)

  — 12-Day Pre-Special (12S)

  — 12-Day Pre-Convention (12C)

  — 30-Day Post-Runoff (30R)

  — 30-Day Post-Special (30S)

  — Termination report (TER)

  ![Quarterly - Non-election Year.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/80ea9080-8e5a-4753-a7b6-9e33f681195a](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/80ea9080-8e5a-4753-a7b6-9e33f681195a))

QA NOTES

To test, start report creation and verify that there are only the two "Time Period" options in the Report Type slide. The available report types should match the acceptance criteria above.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1176](https://fecgov.atlassian.net/browse/FECFILE-1176)

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 6/1/22:** Shelly and Todd not present.

**Comment by WiseQA** [comment]
Per discussion with @MitchellTCG @Elaine-Krauss-TCG we are updating the list on DEV to match the naming convention in the wireframes, NOT the abbreviated list in the Acceptance Criteria.

**Comment by WiseQA** [comment]
QA reviewed this ticket and verified Election year, Non-Election Year, and Special Election were changed to just two choices Election Year and Non-Election Year.   Special Election selections, from wireframes have been added under Quarterly Reporting.   (Note:  Acceptance criteria updated to add special report --- 12-Day Pre-Special (12S) which was not in list)

Below screenshot of Quarterly Reporting selecting Election Year:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dbb6b29b-135a-43f1-968c-4bd85792e14a)

Below screenshot of Quarterly Reporting selecting Non-Election Year:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/08a247f3-dec1-4fc4-8195-790142796157)

No Test Script written for this ticket as this was a visual inspection and no e2e testing needs created.

QA review completed.  Moved to Stage Ready.
