### ISSUE TITLE
Defect - "Contribution Amount" and "Contribution Aggregate" NOT displayed as currency

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#312]
1.  RELATED TO TICKET:
2.  fecfile-web-app #230

Business Reason

As a User (all roles), I will be able to see "Contribution Amount" and "Contribution Aggregate" as Currency ($0.00) so that I know the numbers are related to money.

Acceptance Criteria

***If*** I am a Committee Administrator (or any role in the future)

  ***When*** I create or edit a transaction, both "Contribution Amount" and "Contribution Aggregate" will be displayed as currency [($X.XX - Dollar sign, followed by whole number, follows by a decimal, and last followed by two numbers (two decimals)]

Defect found in Sprint 8 (by @MitchellTCG)

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1175](https://fecgov.atlassian.net/browse/FECFILE-1175)

**Comment by WiseQA** [comment]
QA inspection of Defect verified Contribution Amount and Contribution Aggregate are displaying as Currency.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f2cd2fb9-c117-4fbb-a4d5-3fb4aa1b73a3)

QA review completed.  Moved to Stage Ready.
