### ISSUE TITLE
Create automated regression tests for QA scripts (Sprint 8)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#313]
Business Reason

As a developer or QA, I will be able to automatically run the Sprint-8 test scripts using the Cypress e2e framework so that I can run regression tests in an automated fashion.

Acceptance Criteria

***If*** I want to run the Sprint test scripts to retest the tickets

  ***When*** I run the automated tests in the Cypress framework

  ***Then*** I will get a report on which scripts failed and which passed

1.  QA Scripts

       #

*   [x] 244
*   [x] 230
*   [x] 228
*   [x] 215
*   [x] 206
*   [x] 205
*   [x] 138
*   [x] 133

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1174](https://fecgov.atlassian.net/browse/FECFILE-1174)

**Comment by Elaine-Krauss-TCG** [comment]
It is becoming a problem that created reports persist between tests, so I have to configure Cypress to hit the REST API endpoint to delete the created reports after each test finishes.

This requires:
- [x] retrieving authentication credentials through Cypress
- [x] retrieving the list of reports in a way that Cypress can parse them
- [x] sending DELETE requests to the API

**Comment by Elaine-Krauss-TCG** [comment]
E2E Test for QA Script #133 requires feedback from Shelly.
Depending on feedback it might be as much as 90% done.

Team discussed #133, good to go.

**Comment by Elaine-Krauss-TCG** [comment]
QA Script #230 is the first to involve creating a transaction.  This will require a little more work to create a flexible system for dynamically creating transactions.  This one E2E test will take a bit longer to produce, but there will be large time saves later down the line.

**Comment by WiseQA** [comment]
Demo of Sprint 8 automated tests against QA test scripts.  Visual everything looked good.  

QA review completed.  Moved to Stage Ready.
