### ISSUE TITLE
Defect: Contribution Purpose Description should be Read Only

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#316]
***Steps to Reproduce:***

1\. Create new "Offsets to Operating Expenditures" transaction or open an existing one.

  2\. Click in "Contribution Purpose Description" field.

***Expected Result:*** In "Offsets to Operating Expenditures", per ACs in Web App #230, Contribution Purpose Description should be read-only and the user will be unable to edit.

***Actual result:*** Contribution Purpose Description is an editable field.

  ![image.png]([https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/77e7ada3-a4c4-47d2-b698-6781570afb7f](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/77e7ada3-a4c4-47d2-b698-6781570afb7f))

1.  DEV NOTE:

       #

       Please grey out box: #F1F1F1

1.  Defect found in Sprint 8

       #

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1173](https://fecgov.atlassian.net/browse/FECFILE-1173)

**Comment by WiseQA** [comment]
QA inspection of Defect verified Contribution Purpose Description field is grayed out and "Read Only".

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/62d1bcc3-973f-4788-a4f3-a3c224c4e3bd)

QA review completed.  Moved to Stage Ready.
