### ISSUE TITLE
Allow user to delete a transaction

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#319]
Business Reason

As a user, I will be able to delete a transaction on a report with a status "In progress" or "Submission failure" so that I can maintain an accurate list of transactions.

Acceptance Criteria

**Given** a user is viewing transactions on a report with a status "In progress" or "Submission failure"

**Then** they will be able to select 'Delete' on the Action kebab in the Manage Transactions list next to any transaction _except_ loans or debts with related transactions on future Submitted reports

**And when** the user selects delete

**then** they will see a confirmation message, "Are you sure?" (see wireframe) where the user will be able to:

*   Cancel (nothing happens)
*   Confirm

**And if** the user clicks "Confirm,

**Then** any lower tier transactions in that report and/or related transactions will ALSO be deleted (see list of related transactions below).

* * *

Related Transactions and what also should be deleted

*   Tier 1 transaction > Tier 2s, Tier 3s (_only_ if it is not reattributed/redesignated in a future submitted report)
*   Tier 2 transaction >Tier 3s (_only_ if it is not reattributed/redesignated in a future submitted report)
*   Earmark Receipt or Memo > corresponding Memo or Receipt, respectively
*   Reattributed/redesignated transaction in _current_ report (Tier 1) > Both FROM and TO transactions (Tier 2)
*   Reattributed/redesignated FROM/TO transaction in _current_ report > Corresponding FROM/TO transaction (Tier 2)
*   Reattributed/redesignated FROM/TO transaction in _prior_ report OR copy of that original transaction> Copy of original transaction (Tier1) , Corresponding FROM/TO transaction (Tier 2)
*   Loan (SC) or Debt (SD) _only if there are no related transactions on future Submitted or amended reports >_ Associated C1s and C2s (Loans only), Any payments against the loan/debt, in current and future reports

### QA Notes ###
* If the user deletes a child transaction, only that child and any children beneath it will be deleted. The parent will _not_ be deleted if a child is (unless it is an Earmark/Conduit Earmark).
* This will be for transactions in _all_ schedules: A, B, C, D, and E.
* Deleting a transaction does NOT delete any contact information.

### DEV Notes ###
* Deleting a transaction does NOT delete any contact information in Contact Management.
* Only delete the copied Original when removing the last reatt/redes from the current report.
* Will be modeled after the “can delete” flag on reports - will be complicated to set up but will help with calculation load.

### Design ###

 
 !image-20240528-190615.png|width=1200,height=1622,alt="image-20240528-190615.png"!  

![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/434ff901-f160-48c4-9c21-1690d0411ddd)

!image-20240528-190633.png|width=1200,height=1622,alt="image-20240528-190633.png"!

![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/8faaf38f-9c67-4249-909b-11cdbb44e4b1)

 See full ticket and images here: [FECFILE-1172](https://fecgov.atlassian.net/browse/FECFILE-1172)

**Comment by AureliaKhorsand** [comment]
@GreggMoreland requirements session notes from 5/26/22 may be helpful for this ticket

**Comment by GreggMoreland** [comment]
@AureliaKhorsand The questions for FEC in this ticket are important to be asked in the next requirements meeting.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @mary-tcg @JonellaCulmer 
Posted / wires attached

**Comment by AureliaKhorsand** [comment]
**BA Notes:** 
- Separate ticket for viewing recovering a deleted transaction. This ticket is a SOFT DELETE.
- The user should have the ability to delete memo transactions. 
- The user must delete the memo transactions first, or the entire "family group" together. That way there are no "orphaned" transactions. 
- another transaction (no back reference ID), RAD has ability to question them for additional information. 
- FECfile Desktop won't let you delete a parent if there are children.
- If the transaction is "paired" with another transaction in a different schedule (e.g., In-Kinds or Conduit Earmarks), one cannot be deleted without deleting the other, and the user should be notified that both will be deleted if they attempt to delete one.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 

All mocks updated. This will cover all scenarios listed. We can adjust further in a later ticket but this is the agreed upon first pass.

**Comment by AureliaKhorsand** [comment]
@mary-tcg @MitchellTCG can we adjust the language a bit to make it clear that it's just the transactions _beneath_ (aka the children) of the deleted transaction that will also get deleted?

**Comment by mary-tcg** [comment]
Discussed with @AureliaKhorsand and further information is required before I can workshop different message phrasings. Will readdress later this week.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
I reviewed this with The design team and Todd.
Here is my mock up:
![319B - Allow user to delete a transaction ONLY on a report that hasn't been submitted 2 – 2b.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/acb782d1-17f8-49c2-8123-fc748f193053)

**Comment by AureliaKhorsand** [comment]
On hold for #1188

**Comment by AureliaKhorsand** [comment]
@mjtravers @toddlees can you let me know how the reattribution/redesignation "linking works? I think the ACs are overly simplified right now (though if they work as is, let me know.)

**Comment by mjtravers** [comment]
@AureliaKhorsand For reattributions and redesignations within the same report, we have a reattribution/redesignation links from the TO and FROM transactions to the REATT/REDES transaction. In addition, we have a parent link from the FROM transaction to the TO transaction (TO being the parent). The parent link is so we can track the FROM/TO transactions as a pair in the database. The reatt/redesig for a transaction in a prior report is still under development but will be similar the the in-report version.

**Comment by GreggMoreland** [comment]
@AureliaKhorsand AC's updated/clarified a little. Please review

**Comment by AureliaKhorsand** [comment]
@mjtravers @toddlees now that we have the reatt/redesig working from prior reports, is it still safe to say that the linkages work similarly whether or not the transaction is reattributed from a prior report or the current report? In terms of deleting, my only worry is figuring out the reatt/redesig from a prior report. The FROM/TO can be deleted, but keeping the copied original transaction would make no sense. Essentially, the scenarios for deletion would be as follows:

![Image](https://github.com/fecgov/fecfile-web-app/assets/94924171/e216ba71-a5aa-4346-92ba-785dd45b365f)


For the above, the idea is that these are the groupings that can be deleted, and anything in the red box with them also goes. This is the ideal, I'm just wondering what we're looking at behind the scenes. Thoughts?

**Comment by mjtravers** [comment]
@AureliaKhorsand The above diagrams are exactly what's happening with the pointers in the back end. For the prior report, there is an additional pointer not shown from the COPIED Original Transaction to the transaction in the prior, closed report but that link will be removed when the copy is removed. We can delete as outlined above.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG given the updated ACs, are the wireframes still good or did your team want to update them?

Confirmed with Mitchell on 4/26/24 that wires are good for now.

**Comment by AureliaKhorsand** [comment]
BA note: Need to ask FEC what happens if you delete the original loan/debt. Would it delete future transactions? What about if you delete a transaction in an amended report with closed reports after it, would it delete the transactions in future closed reports? (recommend yes for consistency).

**Comment by GreggMoreland** [comment]
@AureliaKhorsand Please review the additional detail I added regarding Loans and Debts
