### ISSUE TITLE
Reduce report creation from 2-part task to 1-part task

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#320]
### Business Reason ### 
As a Committee Administrator, I would like to reduce the number of steps to create a Form 3X report, so users can more quickly create functional, accurate reports 
 
### Acceptance Criteria ### 
**Given** I am a Committee Administrator that is creating a new Form 3X Report 
**When** I select a time period (Election or Non-election)
 **Then** I choose the correct report type
 **Then** I will be required to enter a starting and ending coverage date for that report 
**And** I will be able to add an optional report level memo
**And** save and continue to transactions

![Report Page Creation - one step.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a9d97ea2-3cad-40c9-b3e7-476afe1a3fa9)

### Dev Notes ###
Move the memo box from the second page of the report creation process to the first page and then have the save button take the user to a transaction table.

**Comment by MitchellTCG** [comment]
@mjtravers can you give this a look

**Comment by AureliaKhorsand** [comment]
Superseded by #349. Closing as OBE.
