### ISSUE TITLE
5c - Summary Page: System to auto-calculate Cash-on-Hand (line 6a and 6b) for subsequent reports

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#325]
Business Reason

System to calculate Cash-on-Hand automatically for subsequent reports to reduce the potential for user-error.

Acceptance Criteria

***Given*** a user creates a new Form 3X report

  ***And*** there is at least one existing Form 3X report for that committee account,

  ***Then*** the system will auto-populate (pull forward) the following and the user will be unable to edit:

  1\. 6a - This value remains the same for all reports in the same calendar year

  a. If this is the first report of a calendar year, then 6a is the value from Summary Page Line 8, Column B from the prior report

  2\. 6b - Summary Page Line 8, Column A from the prior report

  3\. The numbers will update from prior report as needed until the report is submitted.

Dev Notes

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1170](https://fecgov.atlassian.net/browse/FECFILE-1170)

**Comment by Elaine-Krauss-TCG** [comment]
After a conversation with @GreggMoreland the formula for calculating Line 6d column B was changed from `6a[b] + 6c[b]` to `6a[b] + 6c[a]`

Similarly, Line 8[b] calculation was changed from `6d[b] - 7[b]` to `6d[b] - 7[a]`

These changes were necessary to prevent transactions from being counted multiple times now that Cash on Hand is being carried forward between reports.

**Comment by toddlees** [comment]
I believe the requirement for 6a should actually be the cash on hand at the beginning of the year rather than the line 8 of the prior report.  Coincidentally, line 8 col B of the the previous report is in fact the cash on hand at the beginning of the year for the very first report of the year, but for all the others it would need to point to the cash on hand at the beginning of the year rather than line 8 col B of the prior report. 

The changes proposed above to line 6d  and 8b would not need to occur if this correction is made

**Comment by toddlees** [comment]
>6a - This value remains the same for all reports in the same calendar year
a. If this is the first report of a calendar year, then 6a is the value from Summary Page Line 8, Column B from the prior report

for this requirement, what do you think of "6a - 6a is assigned the value of Line 8 column B from the last report before the calendar year. In the case where there is no report from a previous year, use line 6 column A of the earliest report this year."  This captures the case where there's no previous year and reduces the 2 conditions above to one.

**Comment by toddlees** [comment]
passes cr moving to qa

**Comment by WiseQA** [comment]
QA review verified Summary Page to auto-calculate Cash on had for previous report for line 6(a) and 6(b) per AC.

First monthly report created FEBRUARY 20 MONTHLY REPORT (M2) 01/01/2021 — 01/31/2021

<img width="1052" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGhSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--752b5b996e858ef0c46fbff0d5369621fe940065/image.png" alt="image.png" />

Second monthly report created MARCH 20 MONTHLY REPORT (M3) 02/01/2021 — 02/28/2021
<img width="976" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDVSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21f141b346462c7b91c40f3feef678a61a3e0960/image.png" alt="image.png" />

QA Review Completed.  Moved to Stage Ready.
