### ISSUE TITLE
Create Group F Transaction Screen (PAC JF Transfer Memo)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#327]
Business Reason

As a Committee Administrator, I will be able to enter a sub-transaction under ***"JF Transfers"*** on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

***NOTE:*** This is a "child" transaction that will be associated with a parent transaction.

Acceptance Criteria

***Given*** I am a Committee Administrator

  ***And*** I am editing a JF Transfer transaction on an open report

  ***Then*** I will have the _option_ to enter the following sub-transaction:

*   PAC JF Transfer Memo

***And*** I will be required to enter the following information (unless otherwise noted):

1.  Contributor

       #

*   ***CONTRIBUTOR TYPE*** (Read-only)

       Field description in API: ENTITY TYPE

       Data field: COMMITTEE
*   ***CONTRIBUTOR COMMITTEE*** (A/N-200, Required)

       Field description in API: CONTRIBUTOR ORGANIZATION NAME

       Data field: textbox
*   ***CONTRIBUTOR FEC ID*** (A/N-9, Required)

       Field description in API: DONOR COMMITTEE FEC ID

       Data field: textbox

       With the ID in the following format: "CXXXXXXXX" where X is a numeric value _(C, then 8 numbers)_

       ***FEC ID IS A STOP-GAP UNTIL THE LOOKUP IS IN PLACE***

1.  Address

       #

*   ***STREET ADDRESS*** (A/N-34, Required)

       Field description in API: CONTRIBUTOR STREET 1

       Data field: textbox
*   ***APARTMENT, SUITE, ETC.*** (A/N-34, Optional)

       Field description in API: CONTRIBUTOR STREET 2

       Data field: textbox
*   ***CITY*** (A/N-30, Required)

       Field description in API: CONTRIBUTOR CITY

       Data field: textbox
*   ***STATE/PROVINCE*** (ALPHA-2, Required)

       Field description in API: CONTRIBUTOR STATE

       Data field: Dropdown

       Dropdown options: States without military
    [https://docs.google.com/spreadsheets/d/17YmnaZgqvFOUyv4-Qknd8ikHe8o9LoDb/edit#gid=494776297](https://docs.google.com/spreadsheets/d/17YmnaZgqvFOUyv4-Qknd8ikHe8o9LoDb/edit#gid=494776297)
*   ***ZIP/POSTAL CODE*** (A/N-9, Required)

       Field description in API: CONTRIBUTOR ZIP

       Data field: textbox

       

1.  Contribution

       #

*   ***DATE RECEIVED*** (NUM-8…YYYYMMDD, Required)

       Field description in API: CONTRIBUTION DATE

       Data field: Date picker
*   ***MEMO ITEM*** (A/N-1, Optional)

       Field description in API: MEMO CODE

       Data field: Checkbox
*   ***CONTRIBUTION AMOUNT*** (AMT-12, Required)

       Field description in API: CONTRIBUTION AMOUNT

       Data field: textbox
*   ***CONTRIBUTION AGGREGATE*** (AMT-12, Required)

       Field description in API: CONTRIBUTION AGGREGATE

       Data field: textbox (FOR NOW it will say $0.00)

       

1.  Additional information

       #

*   ***CONTRIBUTION PURPOSE DESCRIPTION*** (Read-only)

       Field description in API: RECEIPT DESCRIPTION

       Data field: multi-line textbox that must read "JF Memo: XX", where XX is auto-populated with the name of the committee entered in parent transaction JF_TRAN COL SEQ 8
*   ***NOTE OR MEMO TEXT*** (A/N-100, Optional)

       Field description in API: MEMO TEXT/DESCRIPTION

       Data field: multi-line textbox

***Then*** I will be able to:

*   "Save & add another JF Transfer Memo" associated to the same "parent"
*   Back to JF Transfer
*   Save & view all transactions [will go to "Manage your transactions" Table]
*   Edit as needed

Dev Note

*   BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
*   BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

1.  See Schedule A spec [here]([https://fecgov.github.io/fecfile-validate/SchA_spec.html](https://fecgov.github.io/fecfile-validate/SchA_spec.html)).

       #

1.  See spec [here]([https://fecgov.github.io/fecfile-validate/JF_TRAN_PAC_MEMO_spec.html](https://fecgov.github.io/fecfile-validate/JF_TRAN_PAC_MEMO_spec.html)).

       #

![Group F - PAC JF Transfer Memo.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/75c84630-4112-43e5-a64e-6c3e45e389f0](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/75c84630-4112-43e5-a64e-6c3e45e389f0))

![Group F - PAC JF Transfer Memo - Errors.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/188a10ae-db7e-450e-afa3-71027046d067](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/188a10ae-db7e-450e-afa3-71027046d067))

![Group F - PAC JF Transfer Memo - Required Fields.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/eabdfe0b-7a2c-445c-ad3f-fc500977f8db](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/eabdfe0b-7a2c-445c-ad3f-fc500977f8db))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1168](https://fecgov.atlassian.net/browse/FECFILE-1168)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Updated

**Comment by AureliaKhorsand** [comment]
Consideration for FEC discussion: If the Parent Transaction name changes after the sub-transaction ticket has been saved, the Contribution Purpose Description note will still display the old name. This is an edge case, but we can prevent this issue a few ways. This is a discussion topic for the 7/5 requirements meeting and _not_ in scope of this ticket.

**Comment by mjtravers** [comment]
Requested some changes in the fecfile-app and fecfile-validate repos for this ticket. Sending to In Progress

**Comment by WiseQA** [comment]
Returned to in-progress "Date Field" not showing "Required Field".   This is broken in this ticket, as it worked in Sprint 9.  QA was not aware of any defect being written on this ticket.

**Comment by Elaine-Krauss-TCG** [comment]
The date field not showing that it is required is not isolated to this ticket, and correcting this error has its own ticket

https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/363

**Comment by WiseQA** [comment]
Note:  Wireframe and Acceptance showed:
-	**CONTRIBUTOR FEC ID** (A/N-10, Required)
Field description in API: DONOR COMMITTEE FEC ID
Data field: textbox
With the ID in the following format: "CXXXXXXXX" where X is a numeric value _(C, then 8 numbers)

After verifying requirements **CONTRIBUTOR FEC ID** (A/N-10, Required) should be A/N-9.   

Changed Acceptance criteria in #233 and #327

**Comment by WiseQA** [comment]
QA reviewed and verified Group F Transaction Screen using JF Transfers.

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/84dea257-4cc7-4e9e-9ac5-3c8b14ef439f/download](https://app.zenhub.com/files/306118986/84dea257-4cc7-4e9e-9ac5-3c8b14ef439f/download)

QA review completed.  Moved to Stage Ready.
