### ISSUE TITLE
Integrate Login.gov code into develop branch

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#328]
The login.gov code developed and tested on the feature/109-django-login-dot-gov branch is being deployed to the secondary test environment. This ticket is for the task of merging that code into the develop branch and deploying it to the develop server.

During integration, the Login.gov site will create new account records in the backend that will need to have the committee account associated from the previous account to them.

Follow on ticket to [109](#109)([https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-api/109](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-api/109))

1.  1.  Technical tasks (to be done in order)

*   [x] Current users set up sandbox Login.gov accounts
*   [x] Dev must add the new sandbox accounts to each Cloud.gov space (dev, stage, prod) for each sandbox app.
*   [x] Merge code into develop branch
*   [ ] Current users log into develop server to create the new record in the backend database

*   - [x] swise@tygart.com, C00277608
*   - [x] mitchell.jarrett@tcg.com, C00277616
*   - [x] aurelia.khorsand@tcg.com, C00277673
*   - [x] mary.honard@tcg.com, C00277863
*   - [ ] todd.lees@tcg.com (use me.toddlees@gmail.com temporarily. waiting on sandbox to delete old tcg account), C00771964
*   - [x] elaine.krauss@tcg.com, C00707398
*   - [x] david.heitzer@tcg.com, C00693044
*   - [x] matt.travers@tcg.com, C00776013

### QA Notes ###
- You must have created a login.gov sandbox account before authenticating with FECFile and you must have been added to the FECFile application within the sandbox by an administrator.
- Naviage to https://fecfile-web-app-dev.app.cloud.gov/
- Click the **Login with login.gov** button
- Enter your credentials and complete the 2-factor auth requested
- You should be redirected to the FECFile app dashboard page.  _Note: If you do not see a committee ID/name on this dashboard, you will need to request that an administrator link a committee id to your account.  Please logout/re-login after this is complete._
- You should be able to navigate around per the usual now.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1167](https://fecgov.atlassian.net/browse/FECFILE-1167)

**Comment by mjtravers** [comment]
Found that we may need the env vars for stage and prod set up in addition to the dev cloud.gov space in CR. Sending ticket back to In Progress for the update.

**Comment by MitchellTCG** [comment]
@mjtravers @toddlees @Elaine-Krauss-TCG @dheitzer 

Please make sure there is some form of Acceptance Criteria AND Steps for QA to follow so QA can test this feature. Please make sure it is there before it leaves Code Review.

**Comment by MitchellTCG** [comment]
Mitchell.jarrett@tcg.com
Committee ID: C00277616

**Comment by MitchellTCG** [comment]
This is Paul's Slack messgae on what terminated accounts to use:
Paul Clark
  9:52 AM
From Jonella in Google Chat:
Jonella Culmer
9:50 AM
Used the PAC datatable. Filtered by 2021-2022 and terminated. https://www.fec.gov/data/committees/pac-party/?cycle=2022&filing_frequency=T

**Comment by WiseQA** [comment]
QA performed dry run 07/13/2022 awaiting 2 fixes:
1.  QA Committee ID loaded into login.gov
2.  Logout has a 15 minute timing issue - awaiting logout fix.
Will perform another dry run once these are completed.

**Comment by WiseQA** [comment]
QA verified COMMITTEE ID C00277608 loaded into login.gov.   Logged in and the  COMMITTEE ID C00277608 took a few minutes clicking around but then populated.  However, errors were found (see Defect #365).

Logout error is still being worked.

**Comment by dheitzer** [comment]
@WiseQA I removed your reports/transactions in DEV as requested.

**Comment by WiseQA** [comment]
@dheitzer @mjtravers Reports / transactions all working using login.gov.

**Comment by WiseQA** [comment]
This ticket per discussion with @mjtravers @MitchellTCG will not test the logout functionality as denoted in the acceptance criteria.  Ticket #411 has been created and tracking the logout issue with login.gov.  

https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/411

Removed steps in Acceptance Criteria for logout functionality:

- [ ] Users log out
- [ ] Devs update the new database records with the committee account associations
- [ ]  Users log into dev again and verify they can see their existing report and transaction data in the UI

Removed steps from QA for logout testing;
- When you are done in the application, you may click Profile -> Logout.  You should be redirected to the original FECfile login page

**Comment by mjtravers** [comment]
Ticket passes CR and is ready for QA. The two open PRs for this ticket ([app PR 394](https://github.com/fecgov/fecfile-web-app/pull/394) and [api PR 176](https://github.com/fecgov/fecfile-web-api/pull/176)) are new code for the logout issue and will be reassigned to the follow up ticket: [app#411](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/411).

**Comment by WiseQA** [comment]
QA review completed testing of Login using the following steps:

1.  Navigate e to https://fecfile-web-app-dev.app.cloud.gov/
2.  Click the Login with login.gov button
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/14222e18-32e2-4aba-95ef-1a03e66e2895)
3.  Enter your credentials and complete the 2-factor auth requested.
4.  Redirected to the FECFile app dashboard page. 
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/831dffa6-1bc1-4d29-af25-c2d71bedd449)
5.  Verify can access Reports, Contacts, accounts, etc. from dashboard.

QA review completed.  Moved to Stage Ready.
