### ISSUE TITLE
Updates to "Offsets to Operating Expenditures" Transaction (Group B)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#330]
Business Reason 
 

As a Committee Administrator, I will be able to enter a transaction for **"Offsets to Operating Expenditures"** on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This ticket is to include COMMITTEE options, and to ensure specs are correct on the back end.  NOTE:  (Original Group B transactions Ticket #230 (Sprint 8) transaction with the type "Offsets to Operating Expenditures" from the Transaction Screen (for Individual and Organization Only))  This ticket adding "Committee"

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type "Offsets to Operating Expenditures"
**Then** I will be required to enter the following information (unless otherwise noted):

# Contributor 
#
-	**CONTRIBUTOR TYPE** 
Field description in API: ENTITY TYPE
Data field: Dropdown
Dropdown options: Individual, Organization, **Committee**
---
_if Entity = Organization or Committee_
-	**ORGANIZATION NAME** or **COMMITTEE NAME** (A/N-200, Required)
Field description in API: CONTRIBUTOR ORGANIZATION NAME
Data field: textbox
---
_if Entity = Individual_
-	**LAST NAME** (A/N-30, Required)
Field description in API: CONTRIBUTOR LAST NAME
Data field: textbox
-	**FIRST NAME** (A/N-20, Required)
Field description in API: CONTRIBUTOR FIRST NAME
Data field: textbox
-	**MIDDLE NAME** (A/N-20, Optional)
Field description in API: CONTRIBUTOR MIDDLE NAME
Data field: textbox
-	**PREFIX** (A/N-10, Optional)
Field description in API: CONTRIBUTOR PREFIX
Data field: textbox
-	**SUFFIX** (A/N-10, Optional)
Field description in API: CONTRIBUTOR SUFFIX
Data field: textbox
---

# Address 
#
-	**STREET ADDRESS** (A/N-34, Required)
Field description in API: CONTRIBUTOR STREET 1
Data field: textbox
-	**APARTMENT, SUITE, ETC.** (A/N-34, Optional)
Field description in API: CONTRIBUTOR STREET 2
Data field: textbox
-	**CITY** (A/N-30, Required)
Field description in API: CONTRIBUTOR CITY
Data field: textbox
-	**STATE/PROVINCE** (ALPHA-2, Required)
Field description in API: CONTRIBUTOR STATE
Data field: Dropdown
          Dropdown options: States without military
          https://docs.google.com/spreadsheets/d/17YmnaZgqvFOUyv4-Qknd8ikHe8o9LoDb/edit#gid=494776297
-	**ZIP/POSTAL CODE** (A/N-9, Required)
Field description in API: CONTRIBUTOR ZIP
Data field: textbox

# Contribution 
#
-	**DATE RECEIVED** (NUM-8…YYYYMMDD, Required)
Field description in API: CONTRIBUTION DATE
Data field: Date picker
-	**MEMO ITEM** (A/N-1, Optional)
Field description in API: MEMO CODE
Data field: Checkbox
-	**CONTRIBUTION AMOUNT** (AMT-12, Required)
Field description in API: CONTRIBUTION AMOUNT
Data field: textbox
-	**CONTRIBUTION AGGREGATE** (AMT-12, Required)
Field description in API: CONTRIBUTION AGGREGATE
Data field: textbox (FOR NOW it will say $0.00)
_This is automatically calculated as an aggregate of this contributor's contributions YTD, in any reports, in chronological order_
<br>

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only: A/N-100, Optional)
Field description in API: RECEIPT DESCRIPTION
Data field: multi-line textbox
-	**NOTE OR MEMO TEXT** (A/N-100, Optional)
Field description in API: MEMO TEXT/DESCRIPTION
Data field: multi-line textbox

**Then** I will be able to:

- Cancel
- Save & view all transactions
- Save & add another
- Edit

 Dev Note 

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See Offsets to Operating Expenditures spec [here](https://fecgov.github.io/fecfile-validate/OFFSET_TO_OPEX_spec.html). 
#

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by WiseQA** [comment]
QA reviewed on this ticket to enter, Save & view all transactions, Save and add another, and edit a Group B Transaction. Test Case/Test Scripts written to test the added Committee functionalities per acceptance criteria. 

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/3550248f-4476-40e9-8a8a-d07dea65fdaf/download](https://app.zenhub.com/files/306118986/3550248f-4476-40e9-8a8a-d07dea65fdaf/download)

QA review completed.  Moved to Stage Ready.
