### ISSUE TITLE
Allow user to enter confirmation email and verify address before submission

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#334]
Business Reason

As a user, I will be able to enter up to two email addresses to receive FEC confirmation of submission and verify that the committee address has or has not changed so that I can send the most updated information for FEC upon submission.

Acceptance Criteria

***Given*** the user is on the "Confirm Information" page

  ***Then*** they will be able to enter two Confirmation Emails, and the system will validate they are in the correct email format:

  1\. Email # 1 - this should default to the email from Form 1, and the user has the option to change if needed. This is a required field.

  2\. Email # 2 - this field defaults to blank, and is optional.

***And*** they will be able to indicate if their address has changed or not, and this will always default to ***NO***. 

  ***And*** if the user selects "YES", then the user will see their current address of the committee in editable textboxes, and have the ability to edit the address

*   STREET ADDRESS (A/N-34, required)
*   APARTMENT, SUITE, ETC. (A/N-34, not required)
*   CITY (A/N-30, required)
*   STATE/PROVINCE (required. Should be a dropdown) {note: will show written out state name and A/N-2 on back-end}
*   ZIP/POSTAL CODE (A/N-9, required)

***And*** they can Save and Confirm, and go back and edit as needed before the report is submitted.

[https://images.zenhubusercontent.com/306118986/7c61f9db-194f-4526-bf2b-34aa50dac37c/submit.mp4](https://images.zenhubusercontent.com/306118986/7c61f9db-194f-4526-bf2b-34aa50dac37c/submit.mp4)

![Confirm Information - 1 Blank.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/3e1b1946-49b3-4ae7-afbb-8f434d474643](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/3e1b1946-49b3-4ae7-afbb-8f434d474643))

### QA Notes ###
 
To get to the confirmation page, edit a report and the report navigation in the left sidebar will appear. Select "SUBMIT YOUR REPORT" -> "Confirmation information"

### DEV Notes ###
 
 null

### Design ###
 
 null

 See full ticket and images here: [FECFILE-1163](https://fecgov.atlassian.net/browse/FECFILE-1163)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand  Submit will be two steps. I'm not sure how you want to split the pages. We can discuss. Please review the prototype video.

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 7/6:** BA action item - add requirements for verifying address to this ticket since it will need to be added into automated testing for this page.

**Comment by mjtravers** [comment]
Some requests were made in code review. Sending ticket back to In Progress.

**Comment by mjtravers** [comment]
Looks good for CR. Just need the unit test coverage increased over 80%. Sending back to In Progress for unit tests and one ANDI issue

**Comment by mjtravers** [comment]
Passes CR, sending to QA

**Comment by WiseQA** [comment]
QA review completed and verified Confirming of emails and address as denoted in Wireframes.  

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/bd33bb7e-914d-4d0d-83d0-2f848e663a00/download](https://app.zenhub.com/files/306118986/bd33bb7e-914d-4d0d-83d0-2f848e663a00/download)

QA review completed.  Moved to Stage Ready.
