### ISSUE TITLE
Defect - 500 Error when Accessing Reports from DEV / STAGE

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#339]
This Defect is to correct the 500 error when logging into DEV and STAGE to access Reports from the dashboard.

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a6bc6093-cc96-40c5-8c44-56ffd41735be](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a6bc6093-cc96-40c5-8c44-56ffd41735be))

Acceptance Criteria

If I am a Committee Administrator be able to access both DEV and STAGE environments and selecting Reports from the dashboard.

Defect found in Sprint 9

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1162](https://fecgov.atlassian.net/browse/FECFILE-1162)

**Comment by toddlees** [comment]
There were records in both the develop and stage F3X Summary tables that could not be converted by the conventional migration code.  We added a step to the F3X Summary migration to correctly convert those values. There were no such records in the Schedule A table but the migration was vulnerable to the same issue.  We updated the Schedule A migration the same way

**Comment by toddlees** [comment]
Reason it was missed in development: Local development database did not contain the problematic records
How to avoid in the future: TBD
Reason it was missed at deployment:  Failure in running migrations does not cause the deploy to fail or alert developer of migration error
How to avoid in the future:  Update deploy process to fail or alert on migration failure

**Comment by WiseQA** [comment]
QA reviewed and tested defect - 500 error when logging into DEV and STAGE to access Reports from the dashboard.   Both DEV and STAGE working and corrected see DEV comments above for fix.

QA completed moved to Stage Ready
