### ISSUE TITLE
WebService Worker: development setup

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#340]
We need to be able to run a celery worker whose task is developed in the fecfile-web-api repo.

## Tasks ##
- Install Celery in api repo
- Configure Celery and Celery with Django
- Create a Redis Docker image/file for local dev development

## Acceptance Criteria ##
- Screenshot of docker service console

## QA Notes ##
Here are screenshots of the new services in the development environment:
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/c112c317-a23a-4273-abcb-f09d46cad282)

![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/5ab8498a-fd49-455f-b189-2d60e16b34c1)
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/0e26dcd3-84e8-4e0a-9135-1867172a9896)

## Tasks ##
- Install Celery in api repo
- Configure Celery and Celery with Django
- Create a Redis Docker image/file for local dev development

## Acceptance Criteria ##
- Screenshot of docker service console

## QA Notes ##
Here are screenshots of the new services in the development environment:
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/c112c317-a23a-4273-abcb-f09d46cad282)

![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/5ab8498a-fd49-455f-b189-2d60e16b34c1)
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/0e26dcd3-84e8-4e0a-9135-1867172a9896)
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by WiseQA** [comment]
QA reviewed this ticket as a visual inspection of the screenshots of the new services in the development environment as denoted in the QA Notes.

QA review completed.  Moved to Stage Ready.
