### ISSUE TITLE
WebService Worker: create a Celery task that creates an FEC header row

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#341]
Django client Celery creates a task that instructs the Celery worker to create an empty FEC file.

## Acceptance Criteria ##
- Django endpoint takes a report_id
- Django endpoint starts a Celery worker
- Celery worker creates an FEC file containing the FEC header row (no transaction yet)
- Celery will print the header row which will then be captured by the cloud.gov logging service

## QA ##
- A screenshot of the celery log showing the FEC header row in the output in comments below

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
There are a couple of code smells being reported by SonarCloud. The issues are commented on in the PR comments. Moving ticket back to In Progress to address the code change requests.

**Comment by mjtravers** [comment]
Screen shot of celery log for QA review:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/15aced0b-243f-40d5-944a-d62cdd9ef60b)

**Comment by WiseQA** [comment]
QA Visual inspection completed per DEV screenshot above.   This will need back end testing.

QA review completed.  Moved to Stage Ready.
