### ISSUE TITLE
WebService Worker: Celery worker adds transactions and S3

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#342]
Now that the Celery worker is pulling the FEC header row, add the transactions rows and write out the data to a FEC file stored on S3

## Acceptance Criteria 

- Setup connection between api and s3
- Setup connection between worker and s3
- Setup local disk storage method for worker to facilitate unit tests
- .FEC File includes rows for each transaction of report
- .FEC file saved to S3 at the end of create_dot_fec task
- Create postgres table for .fec file records (report_id to key, no content is stored)
- S3 Key is saved in postgres to be retrieved by report_id
- endpoint to download most recent .FEC given report_id

## Developer Notes ##
- Update report_id and parent_transaction_id fields to remove '_id' on backend and to maintain '_id' when sent to front end
- we have to have the api retrieve the files from s3 to maintain committee access controls

## QA ##
- ~Link to the FEC file in S3 with header and transaction records~
- in the reports table, decide which report you want to test and click on the three dots next to the pen icon
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/48693813-80d2-4a02-a7af-423177d93b9c)
- you're now on a test page for the report.
- click "generate .FEC"
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/507771a3-d519-4923-a226-5cca1c0d6875)
- wait a couple seconds just to be safe.  The new stuff is making the .fec file and storing it in S3
- click "download .FEC"
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/090d4d27-44f9-4f6c-9e0e-514f7072b691)
- you'll download a file called `X.fec` where X is the report's id
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/3990000e-d064-43b8-87c8-48aff78c4ca7) 
- you should be able to open the file with notepad on windows.  let me know if that doesn't work
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/8ecaad41-9b45-4716-ac57-dc8a618c322a)
- You will see a first line that starts with "F3XN" which has all the report summary info in .fec format
- There will also be a "SA" row for each transaction in the report with all the transaction info in it

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by mjtravers** [comment]
Updates to test button pass CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review completed FEC Generation and download of report as visual inspection.

1.  Select "3 DOT" icon by report 
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b8af6742-cffa-4565-9381-cdb356df902b)

2.  Verify .FEC generation for xx report displays.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/682509a6-f5ab-493e-a8e7-a5822b2bc494)

3.  Select "Generate.FEC" button then select "Download.FEC" button and open report using notepad.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/02e4bce4-befb-4af3-91d0-4bb7143341b6)
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9367bdcd-0dca-4c44-9e3a-e1fda01474b6)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0a7ea280-98e4-4cb3-bf9c-b1a36118467e)

**Comment by WiseQA** [comment]
Output needs corrected remove INDV_REC, TRIB_REC, etc. for all transactions.   This string should not be in the download FEC file.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/671c23ac-faee-4336-ae0d-237202dcd101)

Returned to QA review for hot fix @mjtravers @toddlees 

Output corrected removed INDV_REC, TRIB_REC, etc. for all transactions.   This string should not be in the download FEC file.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0940e0a3-34a4-4b47-9962-a9875696629a)

QA Review Completed.   Moved to Stage Ready.
