### ISSUE TITLE
Create User Interface for Summary Page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#344]
Purpose 
 
Create the outline for the Summary Page. This is just a visual ticket

 Business Reason 
 
As a Committee Administrator, I will be able to review the information from Lines 6-10 on the Form3X Summary Page.

 Building Specs 

Summary page - this is a H1

Form 3X: [Report Type here] 
- FORM3X: (bold, Karla, 14px , all caps)
- "Report type" (Karla, 14px)

**Data Table**
It will have FOUR columns (text will be all caps)
the column titles are:
-  LINE NUMBERS
-  LINE DESCRIPTION
- THIS PERIOD
- CALENDAR YEAR-TO-DATE

**Row 1:**
- C1: "6(a)"
- C2: "Cash on hand January 1, 20XX" [XX=current year]
- C3: BLANK/No Data
- C4: Zero'd out (display Currency)

**Row 2:**
- C1: "6(b)"
- C2: "Cash on hand at beginning of reporting period" 
- C3: Zero'd out (display Currency)
- C4: BLANK/No Data

**Row 3:**
- C1: "6(c)"
- C2: "Total receipts (from Line 19)"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 4:**
- C1: "6(d)"
- C2: "Subtotal (add Lines 6(b) and 6(c) for Column A and Lines 6(a) and 6(c) for Column B)"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 5:**
- C1: "7"
- C2: "Total disbursements (from Line 31)"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 6:**
- C1: "8"
- C2: "Cash on hand at close of reporting period (subtract Line 7 from Line 6(d))"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 7:**
- C1: "9"
- C2: "Debts and obligations owed TO the committee (Itemize all on Schedule C and/or Schedule D"
   ["TO" should be all caps and bold]
- C3: Zero'd out (display Currency)
- C4: BLANK/No Data

**Row 8:**
- C1: "10"
- C2: "Debts and obligations owed BY the committee (Itemize all on Schedule C and/or Schedule D)"
   ["BY" should be all caps and bold]
- C3: Zero'd out (display Currency)
- C4: BLANK/No Data

Buttons/Call to Actions
"Back" - Grey outlined button
- Previous: Validate Your Report  [text all caps under button]

"Review detailed summary page " -  Federal Blue button
- NEXT: Detailed summary Page  [text all caps under button]

![Summary page – Just Screen.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/813f631d-0f59-4e7d-8f9c-0b8354f13e98)

![Summary page.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/59db752b-57f3-4fd2-b6f9-ffd25916b674)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passed CR from Todd and Elaine. Sending ticket to QA

**Comment by WiseQA** [comment]
Verified Summary page is displayed per wireframe.  NOTE:  There is NO real data for this ticket, test script written with steps verifying visual inspection.

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/ead06c74-21dc-4b2d-be2c-8514f6a2af45/download](https://app.zenhub.com/files/306118986/ead06c74-21dc-4b2d-be2c-8514f6a2af45/download)

QA review completed.  Moved to Stage Ready.
