### ISSUE TITLE
Create User Interface for Detailed Summary Page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#345]
Purpose 
 
Create the outline for the Detailed Summary Page. This is just a visual ticket

 Business Reason 
 
As a Committee Administrator, I will be able to review the information from Lines 11-38 on the Form3X Detailed Summary Page.

 Building Specs 

Detailed summary page - this is a H1

Form 3X: [Report Type here] 
- FORM3X: (bold, Karla, 14px , all caps)
- "Report type" (Karla, 14px)

**Data Table**
It will have FOUR columns (text will be all caps)
the column titles are:
-  LINE NUMBERS
-  LINE DESCRIPTION
- THIS PERIOD
- CALENDAR YEAR-TO-DATE

# Receipts 
#  
**Row 1:** - [greyed background, #f1f1f1]
- C1: "11"
- C2: "TOTAL CONTRIBUTIONS" - [All caps]
- C3: BLANK/No Data
- C4: BLANK/No Data

**Row 2:**
- C1: "(a)"
- C2: "Total individual contributions" 
- C3: BLANK/No Data
- C4: BLANK/No Data

**Row 3:**
- C1: "(i)"
- C2: "Itemized individual contributions"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 4:**
- C1: "(ii)"
- C2: "Unitemized individual contributions"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 5:**
- C1: "(iii)"
- C2: "Unitemized individual contributions"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 6:**
- C1: "(b)"
- C2: "Party committee contributions"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 7:**
- C1: "(c)"
- C2: "Other committee contributions"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 8:**
- C1: "(d)"
- C2: "Presidential public funds"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 9:** - [greyed background, #f1f1f1]
- C1: "12"
- C2: "TRANSFERS FROM AFFILIATED COMMITTEES" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 10:** - [greyed background, #f1f1f1]
- C1: "13"
- C2: "ALL LOANS RECEIVED" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 11:** - [greyed background, #f1f1f1]
- C1: "14"
- C2: "LOAN REPAYMENTS RECEIVED" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 12:** - [greyed background, #f1f1f1]
- C1: "15"
- C2: "OFFSETS TO OPERATING EXPENDITURES (REFUNDS, REBATE, ETC.)" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 13:** - [greyed background, #f1f1f1]
- C1: "16"
- C2: "CANDIDATE REFUNDS" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 14:** - [greyed background, #f1f1f1]
- C1: "17"
- C2: "OTHER FEDERAL RECEIPTS" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 15:** - [greyed background, #f1f1f1]
- C1: "18"
- C2: "TRANSFERS FROM NON-FEDERAL AND LEVIN FUNDS" - [All caps]
- C3: BLANK/No Data
- C4: BLANK/No Data

**Row 16:** 
- C1: "(a)"
- C2: "Non-federal transfers" 
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 17:** 
- C1: "(b)"
- C2: "Levin funds (from Schedule H5)	" 
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 18:** 
- C1: "(c)"
- C2: "Total Transfers" 
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 19:** - [greyed background, #f1f1f1]
- C1: "19"
- C2: "TOTAL RECEIPTS" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 20:** - [greyed background, #AEB0B5]
- C1: "20"
- C2: "TOTAL  FEDERAL RECEIPTS" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

# Disbursements 
#  
**Row 1:** - [greyed background, #f1f1f1]
- C1: "21"
- C2: "OPERATING EXPENDITURES" - [All caps]
- C3: BLANK/No Data
- C4: BLANK/No Data

**Row 2:**
- C1: "(a)(i)" 
- C2: "Allocated operating expenditures - federal" - [italics]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 3:**
- C1: "(a)(ii)"
- C2: "Allocated operating expenditures - non-federal" - [italics]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 4:**
- C1: "(b)"
- C2: "Other federal operating expenditures	"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 5:**
- C1: "(c)"
- C2: "Total operating expenditures"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 6:** - [greyed background, #f1f1f1]
- C1: "22"
- C2: "TRANSFERS TO AFFILIATED COMMITTEES" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 7:** - [greyed background, #f1f1f1]
- C1: "23"
- C2: "CONTRIBUTIONS TO OTHER COMMITTEES" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 8:** - [greyed background, #f1f1f1]
- C1: "24"
- C2: "INDEPENDENT EXPENDITURES" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 9:** - [greyed background, #f1f1f1]
- C1: "25"
- C2: "PARTY COORDINATED EXPENDITURES" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 10:** - [greyed background, #f1f1f1]
- C1: "26"
- C2: "LOANS MADE" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 11:** - [greyed background, #f1f1f1]
- C1: "27"
- C2: "LOAN REPAYMENTS MADE" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 12:** - [greyed background, #f1f1f1]
- C1: "28"
- C2: "TOTAL CONTRIBUTION REFUNDS" - [All caps]
- C3: BLANK/No Data
- C4: BLANK/No Data

**Row 13:**
- C1: "(a)"
- C2: "Individual refunds" 
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 14:**
- C1: "(b)"
- C2: "Political party refunds"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 15:**
- C1: "(c)"
- C2: "Other committee refunds"
- C3: BLANK/No Data
- C4: BLANK/No Data

**Row 16:** 
- C1: "(d)"
- C2: "Total Contribution Refunds" 
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 17:**  - [greyed background, #f1f1f1]
- C1: "29"
- C2: "OTHER DISBURSEMENTS" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 18:**  - [greyed background, #f1f1f1]
- C1: "30"
- C2: "TOTAL FEDERAL ELECTION ACTIVITY"  - [All caps]
- C3: BLANK/No Data
- C4: BLANK/No Data

**Row 19:** 
- C1: "(a)(i)"
- C2: "Allocated federal election activity - federal share"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 20:** 
- C1: "(a)(ii)"
- C2: "Allocated federal election activity - Levin share"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 21:** 
- C1: "(b)"
- C2: "Federal election activity paid entirely with federal funds"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 22:** 
- C1: "(c)"
- C2: "Total Federal election activity"
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 23:**  - [greyed background, #F1F1F1]
- C1: "31"
- C2: "TOTAL DISBURSEMENTS" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

**Row 24:** - [greyed background, #AEB0B5]
- C1: "32"
- C2: "TOTAL RECEIPTS" - [All caps]
- C3: Zero'd out (display Currency)
- C4: Zero'd out (display Currency)

Buttons/Call to Actions
"Back" - Grey outlined button
- Previous: Summary Page  [text all caps under button]

"See print preview" -  Federal Blue button
- NEXT: Print Preview  [text all caps under button]

![Detailed Summary Page.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0b0c830e-7431-4fae-9cf6-16a18c23a83b)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passed CR by David. Sending to QA

**Comment by WiseQA** [comment]
QA Review completed as "Visual" inspection as denoted in Acceptance Criteria.  No real data being pulled for the Detailed Summary Page.  
1.  Select "Summary" button for a report
2.  Select "Review detailed summary page" button
3.  Verify Detailed Summary Page is displayed
4.  Select "Back" button return to Summary Page

Detailed Summary Page (not all is visible in the below screenshot)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a68d28ea-3648-4cef-8590-23c9ede848b6)

(NOTE:   No e2e testing needed on this ticket)

QA review completed.   Moved to Stage Ready
