### ISSUE TITLE
Allow user to see associated transactions on View All Transactions screen (stop-gap)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#347]
Business Reason 
 

As a user, when I am on the View All Transactions screen I can see that the child is associated to a parent transaction so that I can verify I have associated my transactions correctly.

 Acceptance Criteria 
 

**Given** there are transactions with associated sub-transactions
**When** I am on the View All Transactions screen
**Then** I can see that the child is associated to a parent transaction using the following columns:
1. Transaction ID (use internal database ID for now)
2. Associated with _(lists internal database ID of parent)_

![Transactions w-ID and Assoc.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7800ee4c-7369-48fe-8dca-e3c94dd1c90c)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand Updated

**Comment by MitchellTCG** [comment]
Updated with 20-digit code

**Comment by WiseQA** [comment]
QA reviewed and verified View All Transactions table to the child is associated to a parent transaction (see below screenshot and test case/test script).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/84141178-a5d2-43be-baa2-18daa492b9b4)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/1dca49b5-5d70-4ab3-a1a4-1858bf380576/download](https://app.zenhub.com/files/306118986/1dca49b5-5d70-4ab3-a1a4-1858bf380576/download)

QA review completed.  Moved to Stage Ready.
