### ISSUE TITLE
Allow user to create and select a new Form

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#349]
Business Reason 
 
As a Committee Administrator, I will be able to create a report by selecting the Form Type.

 Acceptance Criteria 

**Given** the user is on the Reports page.
**If** they click "Create new Report"
**Then** they will have the option to select which Form type they want to create
**And** the list will default to Form 3X as read only.

 Dev Notes 

"Form 3X: Report of Receipts and Disbursements" is the default selection

# Wireframes 
#
![349 - Select Form type DEFAULTED.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/6a549834-421c-4b94-9f79-dd55b0dc5cbc)

### QA Notes ### 
 

"Form 3X: Report of Receipts and Disbursements" is the default and only available selection. Additional report options will be coming later as we develop the reports. 

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
Waiting answer on questions in #346 from usability testing.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG can you add the wireframes to this ticket, and I will update the AC to reflect them?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @mary-tcg @JonellaCulmer 
Updated

**Comment by mjtravers** [comment]
@toddlees Problems found by unit tests and lint check. Also, David has a relevant comment about creating a general pop up CSS file to use the same setting across the site. Sending back to In Progress.

**Comment by toddlees** [comment]
comments addressed

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified when selecting Create a new report the "Select form type" popup window is displayed.  Under Choose Form the Default currently set at "Form 3x:  Report of Receipts and Disbursements.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9f9065ad-98ac-4ee7-92e7-479ec622cdb9)

Verified when selecting Start building report button the FEC Form 3X - REPORT OF RECEIPTS AND DISBURSEMENTS FOR OTHER THAN AN AUTHORIZED COMMITTEE page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b6595521-b8aa-4a20-9d59-f4db6b80b7cd)

QA Review Completed.  Moved to Stage Ready.
