### ISSUE TITLE
[Dev Task] Create login accounts in Sandbox

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#353]
Task: Please generate logins (including committee accounts) for the following in the sandbox environment. **Please use fec.gov emails for all of the following.**

The Login.gov setup is strictly for STAGE ONLY server in Cloud.gov.

- [x] 1.  Laura Beaufort - lbeaufort@fec.gov
    Committee ID: **C00672394**
~- [ ] 2. Ken Lally - klally@fec.gov
    Committee ID: **C00759811**~
- [x] 3. Paul Clark - pcclark@fec.gov
    Committee ID: **C00763698**
- [x] 4. Ryan Lanz - rlanz@fec.gov
    Committee ID: **C00474387**
~- 5. Marlene Colucci - mcolucci@fec.gov
    Committee ID: **C00743252**~
- [x] 6. Jonella Culmer - jculmer@fec.gov
     Committee ID: **C00742775**

_Note: Aurelia Khorsand, Mitchell Jarrett, and Shelly Wise should already have one_

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
BA Task: Get emails folks want to use for login.gov and add to ticket. David estimates this is around a 1-pointer. @MitchellTCG how do we want to handle this ticket in terms of sprint process, given it's a dev task and not development work?

**Comment by MitchellTCG** [comment]
@mjtravers Can you Please select defunct committee ids for Paul, Ken and Marlene

**Comment by MitchellTCG** [comment]
Creating new ticket to deal with Marlene and Ken. 
I also subtracted 1 Storypoint from this ticket.
