### ISSUE TITLE
Allow user to sign Form 3X report and enter eFiling password

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#354]
Business Reason

As a user, I want to be able to sign my Form 3X report and enter my eFiling password so that I can submit it with the necessary information to be accepted by FEC.

Acceptance Criteria

***Given*** a user is on the "Submit Report" page

 ***Then*** the following information is required:

*   TREASURER LAST NAME [A/N-30]
*   TREASURER FIRST NAME [A/N-20]
*   TREASURER MIDDLE NAME [A/N-20, optional]
*   TREASURER PREFIX [A/N-10, optional]
*   TREASURER SUFFIX [A/N-10, optional]

***And*** the above fields should default to the fields on Form 1 of the Committee Account, but can be edited by the user.

 ***And*** the user will be required to enter an FEC Electronic Filing Password

 ***And*** the page will link to "https://webforms.fec.gov/psa/help.htm" _which will open in a new tab_ in case the user needs assistance

Note: Ticket 291 in Sprint 11 tested and verified the above, fields, password that is denoted in acceptance criteria of this ticket. [https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/291](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/291)

QA Note:

Validate that the link for the password info screen opens in a new tab

 ![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6cf7e3a8-4a37-4f0d-973f-a44e8a7aa10d](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6cf7e3a8-4a37-4f0d-973f-a44e8a7aa10d))

[https://webforms.fec.gov/psa/help.htm](https://webforms.fec.gov/psa/help.htm)

![Confirm Information - 1 Blank.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/951ab26f-6c8e-4877-a660-716f6cdba3dc](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/951ab26f-6c8e-4877-a660-716f6cdba3dc))

![Submit Report - Empty.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/e4fa06e3-2e87-4dae-80e4-a7b6492a118a](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/e4fa06e3-2e87-4dae-80e4-a7b6492a118a))

![Submit Report - 2 Filled in.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a8a41f4d-8047-4502-9956-b9d0c06d5296](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a8a41f4d-8047-4502-9956-b9d0c06d5296))

![Submit Report - 3 Pop up.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/1eb21ad7-4770-49a1-89a8-627ddab6a24b](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/1eb21ad7-4770-49a1-89a8-627ddab6a24b))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1148](https://fecgov.atlassian.net/browse/FECFILE-1148)

**Comment by AureliaKhorsand** [comment]
Password system is maintained by Electronic Filing Office (EFO) and when filer submits a report, we first check for submission parameters for valid Committee ID & Password and based on Agency ID, we direct to corresponding database schema (EFO / VEND).

**Comment by MitchellTCG** [comment]
@AureliaKhorsand  Submit will be two steps. I'm not sure how you want to split the pages. We can discuss. Please review the prototype video.

**Comment by WiseQA** [comment]
QA reviewed and verified as denoted in the QA notes the link for password info screen opens in a new tab.  See below screenshot.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4a5322bc-c0d6-47cf-931b-dc4948bad2ee)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ca1f88ff-8fbf-45cb-9b1b-8b4f157ca5fe)

QA review completed.   Moved to Stage Ready.
