### ISSUE TITLE
Allow user to view submitted Form 3X reports (submitted to FEC)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#355]
Business Reason

As a user, I will be able to view closed/submitted F3X reports as read only.

Acceptance Criteria

***If*** a report has been submitted to FEC

  ***Then*** it will have a Status of "Submitted" on the Manage Reports Page

  ***And when*** the user opens the report (or immediately upon submission - update from #291)

  ***Then*** the following pages will be available:

***Accordion Navigation***

REVIEW A REPORT

*   View summary page
*   View detailed summary page
*   View print preview

SUBMIT YOUR REPORT

*   View Submission Status _(this will be the default landing page for opening a Submitted Report)_

![Custom Size – 91.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0e5d4294-931d-414d-8587-7f41d73966d1](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0e5d4294-931d-414d-8587-7f41d73966d1))

![Print Preview – 1.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/56a061e5-ca62-48e9-ad69-515c3289bb54](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/56a061e5-ca62-48e9-ad69-515c3289bb54))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1147](https://fecgov.atlassian.net/browse/FECFILE-1147)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by mjtravers** [comment]
Bug found in QA: The left report nav does not switch to read only  on submission, only when the report is left and returned to.

**Comment by mjtravers** [comment]
Elaine's code updates to fix the report left menu look good. Sending to QA.

**Comment by WiseQA** [comment]
Moved back to QA review

**Comment by MitchellTCG** [comment]
![Screen Shot 2022-08-16 at 2.06.32 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/2cf8bf08-f32a-4043-9743-0242e8938250)

![Screen Shot 2022-08-16 at 2.06.42 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7c9746ec-1371-4ffc-a280-14c05f2518b0)

**Comment by WiseQA** [comment]
QA "Visual" Inspection Complete.  Reference screenshots above.   Moved to Stage Ready.
