### ISSUE TITLE
System to prevent user from having multiple reports of the same type within calendar year

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#361]
Business Reason 
 
The system will prevent the user from creating multiple reports of the same type within a calendar year to reduce the chance of user error.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator that is creating a new Form 3X Report 
**When** I go to select a report type
**Then** the system will _only_ let me select report types that do not yet already exist for the current calendar year
**And** the report selection will default to the first available report for that calendar year.

![361 -Coverage Date Overlapping.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/53433128-3afb-465d-9e8f-62c442381548)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by GreggMoreland** [comment]
@AureliaKhorsand I have a question, probably for the design team. If a user tries to create a duplicate report, what will the user see to alert them that they cannot create multiple reports of the same type within a calendar year?

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @JonellaCulmer @mary-tcg We need some kind of message to let the user know why they cannot create a duplicate report type at the time of report creation.

**Comment by JonellaCulmer** [comment]
@MitchellTCG @mary-tcg I can imagine a couple different scenarios for this. A message that pops up that says something like: "A report like this is already in progress. Would you like to edit that report?" Or we gray out that option and prevent them from selecting it. In parens next to the name say something like "In progress"

**Comment by mjtravers** [comment]
Needs lint and unit tests fixed. Sending to In Progress.

**Comment by MitchellTCG** [comment]
Currently working as intended. Greyed out text means a report has already been created.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified (e.g., Quarterly Reporting > Election Year) reports that have already been created are greyed out text and non selectable.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fabf7511-9da0-494b-9ff5-6af06219562b)

QA Review Completed.   Moved to Stage Ready.
