### ISSUE TITLE
Remove transactions "save and add another" button from edit screens

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#362]
The "add and add another" button on the transaction screens should only appear when creating a new transaction and not on an edit transaction screen

Acceptance Criteria

*   When creating a transaction, I will see the "save and add another" button
*   When editing a transaction, I will NOT see the "save and add another" button

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1143](https://fecgov.atlassian.net/browse/FECFILE-1143)

**Comment by WiseQA** [comment]
QA verified when creating a transaction, the "save and add another" button is displayed and selectable:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8c6012e0-f17a-4eff-836a-207aa7408ee8)

QA verified when editing a transaction the "save and add another" button is not accessible.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/248b1caa-d43d-4e3f-a5fb-5e6439c9877f)

QA review completed.  Moved to Stage Ready.
