### ISSUE TITLE
Transaction date input is missing required field message

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#363]
The DATE calendar input is not showing the red required text when the form is submitted.

See here for example on JF_TRAN screen:

![image.png]([https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/a86ff13e-2b33-4584-8d95-b51eb6f2fd0e](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/a86ff13e-2b33-4584-8d95-b51eb6f2fd0e))

1.  1.  Acceptance Criteria ##

             When submitting the field the "This is a required field." text should display below the calendar select input box for ***ALL*** transaction forms.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1142](https://fecgov.atlassian.net/browse/FECFILE-1142)

**Comment by WiseQA** [comment]
This Defect affects both Group F (ticket #327) and Group E (ticket #233) and both have been returned to In-progress" for Sprint 10 tickets.    Awaiting DEV fix.

**Comment by WiseQA** [comment]
This Defect has been fixed within both Group F (ticket #327) and Group E (ticket #233).  No test script / test case for this ticket - this is being tested within #327 and #233.

QA review completed as is.   Moved to Stage Ready
