### ISSUE TITLE
Defect - Incoming HTTP Error on DEV when selecting Reports

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#365]
This Defect is HTTP error on DEV when logging into [https://fecfile-web-app-dev.app.cloud.gov](https://fecfile-web-app-dev.app.cloud.gov)

  The following steps shows where the error appears.

  1\. Login to [https://fecfile-web-app-dev.app.cloud.gov](https://fecfile-web-app-dev.app.cloud.gov)

  2\. Select Contacts from the dashboard (error does not appear)

  3\. Select Reports from dashboard and error appears.

  4\. Then select the green "Edit" button to add transaction - same error appears

  5\. This is where the error pops up: cannot add transaction.

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/16a7702c-b116-42a4-8274-4781c0a70441](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/16a7702c-b116-42a4-8274-4781c0a70441))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1141](https://fecgov.atlassian.net/browse/FECFILE-1141)

**Comment by mjtravers** [comment]
Passes CR, sending to QA

**Comment by WiseQA** [comment]
The following steps were retested and verified NO error message appears.

1.  Login to https://fecfile-web-app-dev.app.cloud.gov
2.  Select **login with login.gov button**
3.  Select Contacts from the dashboard.
4.  Select Reports from dashboard.
5.  Then select the green "Edit" button to add transaction.
No errors were populated.

QA review completed.  Moved to Stage Ready.

**Comment by WiseQA** [comment]
Passed with no Committee ID info under reports, contacts, etc.   Moved back to QA to reverify once Committee ID info is working with login.gov.

**Comment by WiseQA** [comment]
QA review once COMMITTEE ID info loaded the following errors appear there are three (3) errors.  @mjtravers returned to In-progress as discussed.   The following steps were taken to verify "Error" messages:

The following steps shows where the error appears.

1.  Login to https://fecfile-web-app-dev.app.cloud.gov
2.  Select login.gov button
3.  Select Contacts from the dashboard (error does not appear)
4.  Select Reports from dashboard and the following error appears.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4fe236a3-d134-4e2c-a6d7-8def2d19a57c)

5.  Then select the green "Edit" button for a report the following error appears:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1d62f5b4-8e19-4e30-9890-d15161abe049)

6.   Then select "Summary Detail" button for a report the following error appears.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f6eab12a-01cf-4061-8d1c-59273ba84dd2)

**Comment by WiseQA** [comment]
@mjtravers same errors are now populating logging in the regular way into DEV and not through login.gov

**Comment by mjtravers** [comment]
This was tracked down to a caching issue to the specific browser. The CORS wildcard * is stuck in the browser cache and manifests the error in existing reports and transactions but not in new ones. The work around is to remove the old reports and transactions from the database for this committee account.

**Comment by WiseQA** [comment]
The following steps were retested and verified NO error message appears.  As denoted above the previous errors were due to caching issues.

1.  Login to https://fecfile-web-app-dev.app.cloud.gov
2.  Select login with login.gov button
3.  Select Contacts from the dashboard.
4.  Select Reports from dashboard.
5  Then select the green "Edit" button
6.  Then select "Summary" button
7.  Then select "Detail" button
No errors were populated. 

Ran this test on both logins on DEV and Stage.

(NOTE:  No e2e testing needed on this ticket)

QA review completed. Moved to Stage Ready.

**Comment by dheitzer** [comment]
Also note that when this error occurs, you will see the following error in your browser console complaining about "Access-Control-Allow-Origin header being set to '*' :
![image](https://user-images.githubusercontent.com/104843885/179237269-1256eab2-c363-421c-8dd9-7dc47a0a99ae.png)
