### ISSUE TITLE
Review and document management of user data in existing code base.

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#37]
Audit and document how site users are managed in the web app and the data related to users stored in the database. Cite in the documentation how users are related/linked to Committee Profiles in the application and database.

Acceptance Criteria:

*   Document describing user management in the application, related data stored in the database, and relations to committee profiles.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1356](https://fecgov.atlassian.net/browse/FECFILE-1356)

**Comment by mjtravers** [comment]
No code to review. Sending directly to QA.
QA can review document here in FEC shared docs:
https://docs.google.com/document/d/1kHZFwMPL-wJlGhG0ID2OKYUbzPeBghrylRqHbqt_R8o

**Comment by mjtravers** [comment]
Here is where the document lives: https://drive.google.com/drive/u/1/folders/1fJ47E55n7em3tMRjGZnLQRRjpzr46ddN

**Comment by lbeaufort** [comment]
It looks like this is more of an issue with Django than with anything cloud.gov specific. Here are some example resources:
- https://gist.github.com/majackson/493c3d6d4476914ca9da63f84247407b
- https://lucasroesler.com/2017/02/zero-downtime-deploys-a-tale-of-django-migrations/
- https://pankrat.github.io/2015/django-migrations-without-downtimes/

This seems like it's exacerbated by large data sets, so keeping this in mind seems like a good thing to keep in mind before we go live. I haven't come across this before - the fec.gov (Django) database is so small that this hasn't come up for us, and we use hand-rolled zero-downtime migrations and Flyway for the openFEC API (we use Flask and not Django).

**Comment by WiseQA** [comment]
Reviewed Phase 1 User Management document.   One error found and corrected.

QA review completed.  Moved to Stage Ready.
