### ISSUE TITLE
Allow user to see Filing ID upon successful submission to FEC

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#379]
Business Reason

As a user, I will be able to view the filing ID received from FEC upon successful submission so that I can have it for reference later as needed.

Acceptance Criteria

***If*** I am viewing a report that has been successfully submitted to FEC

  ***When*** I go to the Submission Status page

  ***Then*** I will see the following information:

*   Congratulations, your report was successfully submitted and accepted.
*   Filing ID _(received from FEC)_: FEC-XXXXXXX (FEC dash 7 characters)

***And*** when the user returns to Manage Reports, it will now list the Date Filed _(Note: This is the date we received confirmation of success from FEC)._

![Success.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f5bd8d5c-7c5c-4ed6-90b5-11ed879c1d1c](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f5bd8d5c-7c5c-4ed6-90b5-11ed879c1d1c))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1139](https://fecgov.atlassian.net/browse/FECFILE-1139)

**Comment by AureliaKhorsand** [comment]
Note: @lbeaufort looking into documentation to see if a test filing ID is something that comes back from the test server when a .fec file is successfully submitted. 

Update: It is. Confirmed with Mahi on 7/21/22.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by MitchellTCG** [comment]
![Screen Shot 2022-08-16 at 1.59.42 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/93115ec2-0bb2-451b-90c2-48be6b51ffdb)

**Comment by WiseQA** [comment]
QA "Visual" Inspection Complete.  Reference screenshots above.   Moved to Stage Ready.
