### ISSUE TITLE
MacOS Build Failure

### ISSUE THREAD

**Issue by toddlees** [fecgov/fecfile-web-app#38]
`docker-compose up --build` fails on Mac M1 chip.  Specifically during the pip3 install of pandas.  
Causes: 
- docker runs out of memory
- cython + numpy + pandas dont install correctly without special pip3 params

Fixes:
- developer must allocate 3GB+ mem for docker
- add a step in the dockerfile to pip3 install cython + numpy + pandas separately

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes code review.
This is an infrastructure ticket so there are no QA tests to perform. I did test that I could stand up the development system during code review to confirm that it is still operational.
Sending to QA.

**Comment by WiseQA** [comment]
Verified acceptance criteria and no testing required.  This ticket was written against MACOS environment.  QA review completed.  Moved to Stage Ready.
