### ISSUE TITLE
Allow user to delete a report

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#386]
Business Reason

As a user, I will be able to delete an 'In Progress' report that hasn't been submitted and has no transactions in a future report or a non-standard report (such as a Form 24) that are linked to transactions in the current report so that I can remove the report from my Report Management list.

Acceptance Criteria

***Given*** the user is on the 'Manage reports' page,

 ***If*** the report is:

*   in status of "In Progress"
*   does _not_ contain any linked transactions to a future report (e.g., Schedule C, D)
*   does _not_ contain transactions associated with a non-standard report (e.g., a Form 3X linked with a Form 24).

***and if*** a Form 24 report is deleted, the system will _not_ delete the transactions in the associated Form 3X report.

***Then*** they will have the option to "delete" when selecting the action kebab.

 ***And when*** they confirm deletion, that report along with all it's transactions will be deleted _(note: not the contacts)._

Dev Notes

*   FEC confirmed that report recovery is not needed.

Wireframe

1.  Delete function

      ![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/13af4c35-464c-4865-801d-b896f93db91e](https://github.com/fecgov/fecfile-web-app/assets/110493670/13af4c35-464c-4865-801d-b896f93db91))

1.  Delete confirmation

      ![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/444da224-f4d9-4bec-84ef-3d2eb565d7dc](https://github.com/fecgov/fecfile-web-app/assets/110493670/444da224-f4d9-4bec-84ef-3d2eb565d7d))

1.  Delete success

      ![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/f58f13ef-38cd-4a78-8ced-4bc71b76943b](https://github.com/fecgov/fecfile-web-app/assets/110493670/f58f13ef-38cd-4a78-8ced-4bc71b76943))

### QA Notes ###

- [x] BA/Design Quality Checklist complete
- If "delete" is not available (criteria for delete does not apply), then "Delete" will not appear on the dropdown at all. 

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1133](https://fecgov.atlassian.net/browse/FECFILE-1133)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Do I need more than this wire?

**Comment by GreggMoreland** [comment]
@MitchellTCG this is good. The only other thing is, what if the report cannot be deleted? will the delete not be there or will it be greyed out?

**Comment by AureliaKhorsand** [comment]
@MitchellTCG can we have a confirmation message wire?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
wires updated

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Updated

**Comment by mjtravers** [comment]
Code recommendations made in CR. Sending back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the "Delete" option on a report is not available (criteria for delete does not apply), then "Delete" will not appear on the dropdown at all. 

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/dc064056-c568-4f4c-ab76-1a49a12b28f0)

_________________________________________________________________________________________________________

Select Form 99 with In-progress status from the Manage reports table.  (Repeat steps below for linked transactions future reports)

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/313f8938-fb80-4489-ad44-89eebaf2be83)

___________________________________________________________________________________________________________

The popup window is displayed “Hang on . . . “

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/561a612e-85d3-4a72-9264-afef1feefc07)

________________________________________________________________________________________________________

Select “Confirm” the “Successful Report Deleted” popup window is displayed. 

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/ab0b31eb-06a7-4810-957b-5c5b1c629663)

________________________________________________________________________________________________________

Verify the Form 99 was deleted from the Manage reports table.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/970de778-37aa-4b19-86ed-60416565ed6e)

_______________________________________________________________________________________________________

Select Form 24 with In-progress status.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/a363f590-deae-4e88-b19d-8bee4bd4305c)

______________________________________________________________________________________________________

Verified the Linked Report field is filled in with a Form 3x.  

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/c03a5b84-31af-43df-bf17-44a3d3d04593)

_____________________________________________________________________________________________________

From the Manage reports table select “Delete” for the Form 24

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/75f33005-bce3-4a97-995f-5796260f7942)

__________________________________________________________________________________________________

The popup window is displayed “Hang on . . . “

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/b451fa56-8cd7-46a8-be52-47009ac8ba60)

_________________________________________________________________________________________________

Select “Confirm” the “Successful Report Deleted” popup window is displayed.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/6e67fdfb-1de9-488d-b643-d020573c97ab)

__________________________________________________________________________________________________

Form 24 Report has been deleted from the Manage reports table.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/45be3bb0-d228-4931-b887-9d2b651b5820)

____________________________________________________________________________________________________

Form24 Table of Disbursements before deleting the Form 24 report.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/120f4c08-0a97-4902-ae55-c5c2d4398c7e)

____________________________________________________________________________________________________

Verified the Independent Expenditure was not deleted from the Form 3x.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/d26018a7-772c-498d-bcce-40c0498ca9a3)

_____________________________________________________________________________________________________

PASSES
 @mjtravers awaiting database hotfix PR.  Will adhoc and retest this ticket once PR pushed to Stage.

**Comment by mjtravers** [comment]
There was an issue discovered after the merge of this ticket where the related reports_form* tables were not getting their records deleted when the reports_report records was deleted. The hotfix corrects the problem and has been deployed to STAGE and DEV. Ready for QA on this ticket.

**Comment by WiseQA** [comment]
@mjtravers QA review verified the "Delete" option on a report is not available (criteria for delete does not apply), then "Delete" will not appear on the dropdown at all.  This is the fix, as "Submission Success" reports should not see "Delete" option.  

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/1d6ee13f-17c2-4cc3-a427-15480c77689d)

______________________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/aca637e2-39b5-4c8c-b1f5-0ba137c0ed19)

@mjtravers this is the hotfix.  Remove "Delete" option for Submission success reports.

**Comment by mjtravers** [comment]
Additional hotfix has been made to correct the "Delete" option in the menu kabob so that it only shows for In Progress reports.

**Comment by WiseQA** [comment]
During QA review the status of reports that are "Submission success" are not displaying as "Submission pending".   These reports have been submitted correctly.   The status of report needs fixed.

1.  Before menu kabob fix the status of report was displaying as:

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/45e1c115-898e-4b86-b81f-865563ce0967)

_____________________________________________________________________________________________________________________

2.  Report status is now displaying incorrectly as "Submission pending"

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/d4e16722-9b2c-495f-a77a-1968c5535069)

___________________________________________________________________________________________________________________

@MitchellTCG @mjtravers fix status of reports.   Ticket remains on hold for this fix.

**Comment by mjtravers** [comment]
Hotfix made to allow code enums to handle comparison operations like a string. Deployed to STAGE and ready for QA.

**Comment by WiseQA** [comment]
QA review verified status of reports was fixed and is being displayed correctly as "Submission success" are not as "Submission pending". 

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/fa22478d-e5d4-4cb0-867b-55d15a2faf9b)

____________________________________________________________________________________________________________________________________

Verified "Delete" option has been removed from the dropdown for "Submission successful" reports.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/9330a502-5c3c-4df1-a99f-b8a05578a269)

_________________________________________________________________________________________________________________________________________

Retested and verified the "Delete" option from the dropdown (kabob) is displayed and active for "In progress" reports.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/d7519661-be6b-4cd7-8f10-3e5675c83daf)

___________________________________________________________________________________________________________________________________

Adhoc tested and repeated test steps in initial QA review denoted above.

QA Review Completed.   Moved to Stage Ready.
