### ISSUE TITLE
Defect - Contribution Amount field should be able to contain cent value and not just whole dollar value

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#389]
Defect written as the Contribution Amount field should be able to contain cent value (e.g., $200.50) and not just whole dollar value (e.g., $200.00).

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c79ada88-bca0-43b2-b079-c8a36cb4bf15](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c79ada88-bca0-43b2-b079-c8a36cb4bf15))

Acceptance Criteria

As a Committee Administrator when entering a Transaction the Contribution Amount should be able to enter cent value (e.g., $250.75) and save the transaction.

Defect found in Sprint 10.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1132](https://fecgov.atlassian.net/browse/FECFILE-1132)

**Comment by MitchellTCG** [comment]
Pointed and moved into the sprint

**Comment by WiseQA** [comment]
QA reviewed and verified when entering a Transaction the Contribution Amount should be able to enter cent value (e.g., $250.75) and save the transaction.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c71b8c02-0b89-4657-8809-08dd64b1d8a7)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/aae6d74d-aa12-49e9-92bf-684cdd51765f)

(NOTE:  e2e testing has already been completed for this field, no additional e2e testing needed)

QA review completed.  Moved to Stage Ready.
