### ISSUE TITLE
Set up Circle to deploy to cloud.gov

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#40]
We should set up Circle to deploy to cloud.gov. `develop` builds should deploy to cloud.gov dev space, and `release/` should deploy to stage.

See 
https://github.com/fecgov/openFEC/blob/0507c6963cf9a97832bcf4f57352adb54b68f2a4/.circleci/config.yml#L115-L124
and
https://github.com/fecgov/openFEC/blob/82233df98543c1683de149b9f6c5a8b1372ce27c/tasks.py#L157-L254

Manifest files will need to be written up:
https://github.com/fecgov/openFEC/tree/0507c6963cf9a97832bcf4f57352adb54b68f2a4/manifests

**ACCEPTANCE CRITERIA:**
- [x] CircleCI deploys develop branch to cloud.gov develop space ( verify by ensuring these URLs return a page:
VERIFY DEVELOP FRONT-END IS RUNNING:  https://fecfile-web-app-dev.app.cloud.gov/
VERIFY DEVELOP BACK-END IS RUNNING: https://fecfile-web-api-dev.app.cloud.gov/api/v1/token/obtain
- [x] CircleCI deploys release branch to cloud.gov stage space ( verify by ensuring these URLs return a page:
VERIFY STAGE FRONT-END IS RUNNING:  https://fecfile-web-app-stage.app.cloud.gov/ 
VERIFY STAGE BACK-END IS RUNNING:  https://fecfile-web-api-stage.app.cloud.gov/api/v1/token/obtain 
- [x] develop/stage deploys for fecfile-web-app, fecfile-web-api ( verify by ensuring these URLs return a page:
VERIFY PRODUCTION FRONT-END IS RUNNING: https://fecfile-web-app-prod.app.cloud.gov/
VERIFY PRODUCTION BACK-END IS RUNNING: https://fecfile-web-api-prod.app.cloud.gov/api/v1/token/obtain 
- [x] Push test database to cloud.gov RDS services (verify by a successful login to the development site)

**Comment by mjtravers** [comment]
@lbeaufort There is some cloud.gov documentation that there are issues with migrations at deployment. Does the tasks.py script resolve these know issues?

**Comment by lbeaufort** [comment]
> @lbeaufort There is some cloud.gov documentation that there are issues with migrations at deployment. Does the tasks.py script resolve these know issues?

@mjtravers can you share the documentation you're referencing for context?

**Comment by mjtravers** [comment]
@lbeaufort It was a sentence that got my attention in the Zero-downtime deploy section of the documentation and Paul mentioned at the Monday PI meeting that you had dealt with this type of database issue in your web work.
https://cloud.gov/docs/deployment/production-ready/#zero-downtime-deploy

**Comment by lbeaufort** [comment]
> @lbeaufort It was a sentence that got my attention in the Zero-downtime deploy section of the documentation and Paul mentioned at the Monday PI meeting that you had dealt with this type of database issue in your web work. https://cloud.gov/docs/deployment/production-ready/#zero-downtime-deploy

@mjtravers that's helpful, thank you! Per https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html: 
>Deployments do not handle database migrations. Migrating an app database when the existing app is not compatible with the migration can result in downtime.

So, if the deploy triggers a database migration that is incompatible with the previously deployed version of the app, there will be issues while cloud foundry deploys 1 application instance at a time. This rolling deployment usually takes a matter of seconds to work through each application instance. Happy to discuss this further - We use flyway for database migrations for the API and Django for the CMS and it hasn't come up yet. I'd need to think more about how the Django migrations work and whether an older version of the application would have breaking changes with a new migration.

**Comment by mjtravers** [comment]
@lbeaufort I see. That makes sense. We'll have to keep that in mind. Thx.

**Comment by lbeaufort** [comment]
It looks like this is more of an issue with Django than with anything cloud.gov specific. Here are some example resources:
- https://gist.github.com/majackson/493c3d6d4476914ca9da63f84247407b
- https://lucasroesler.com/2017/02/zero-downtime-deploys-a-tale-of-django-migrations/
- https://pankrat.github.io/2015/django-migrations-without-downtimes/

This seems like it's exacerbated by large data sets, this seems like a good thing to keep in mind before we go live. I haven't come across this before - the fec.gov (Django) database is so small that this hasn't come up for us, and we use hand-rolled zero-downtime migrations and Flyway for the openFEC API (we use Flask and not Django).

**Comment by AureliaKhorsand** [comment]
**Backlog Grooming Notes 1/20:** Discussed splitting up the ticket for each repo. Team agreed on keeping it all as one ticket. The test data we load in will be the same data in Circle CI. 

For QA, would need to log into the Web app on Stage and Develop and do a smoke test.

**Comment by lbeaufort** [comment]
Here's a WIP PR for deploying fecfile-validate to cloud.gov, from the command line and also through CircleCI: https://github.com/fecgov/fecfile-Validate/pull/24

**Comment by mjtravers** [comment]
Passes CR. Moving to QA and assigning to Shelly

**Comment by WiseQA** [comment]
Matt from the acceptance criteria, there is a lot of info, can you provide a link to verify like you have been doing for testing.  Returning to Code Review for more information on this ticket to test.

**Comment by WiseQA** [comment]
QA performed verified the following from Acceptance Criteria:

VERIFY DEVELOP FRONT-END IS RUNNING: https://fecfile-web-app-dev.app.cloud.gov/
VERIFY DEVELOP BACK-END IS RUNNING: https://fecfile-web-api-dev.app.cloud.gov/api/v1/token/obtain

VERIFY STAGE FRONT-END IS RUNNING: https://fecfile-web-app-stage.app.cloud.gov/
VERIFY STAGE BACK-END IS RUNNING: https://fecfile-web-api-stage.app.cloud.gov/api/v1/token/obtain

VERIFY PRODUCTION FRONT-END IS RUNNING: https://fecfile-web-app-prod.app.cloud.gov/
VERIFY PRODUCTION BACK-END IS RUNNING: https://fecfile-web-api-prod.app.cloud.gov/api/v1/token/obtain

QA review completed.  Moved to Stage Ready.
