### ISSUE TITLE
Update report action buttons on Manage Reports page

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#402]
Note: This ticket is for the ACTION DROPDOWN and opening the report only. The action for download will be a separate ticket.

 Business Reason 
 

As a FECfile user, I will be able to download any or my reports as a .fec file so that I can reconcile and troubleshoot any issues or audit questions, as applicable.

 Acceptance Criteria 
 

**Given** I am on the Manage Reports screen for my committee account
**When** I select the report action button for a report _in-progress_
**Then** I will have the following options:
- Edit report - clicking here opens the report for editing
- Download a .FEC

**OR**

**Given** I am on the Manage Reports screen for my committee account
**When** I select the report action button for a report in _filed_ status
**Then** I will have the following options:
- View report - clicking here opens the report for viewing
- Download a .FEC

 

 Dev Notes 
 
the ticket will get rid of the edit pencil icon and create a dropdown to 
1. allow the user to "Edit report"  or "Download a .FEC" if report is In-progress. 
OR
2. allow the user to "Review report"  or "Download a .FEC" if the report has been submitted.

### QA Notes ### 
 "Download a .FEC" is a dead link for this ticket, and is not expected to go anywhere.

Replace this :
![Screen Shot 2022-09-07 at 11.09.32 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d3495d96-fb57-4548-b702-0853354a7eec)

With this:
![Download fec.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/58f7e591-7dad-4709-97ef-5423962c8bb1)
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
I am only seeing one button under Actions which is a solid green round button.    

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/08449cdb-21aa-4aef-aa8b-727c180cbd40)

Sending back to In-Progress @mjtravers @toddlees as I have already talked with Todd.

**Comment by mjtravers** [comment]
@WiseQA The pop-up menu has been updated so that it is square and does not have the pointer in the corner. Passes CR and ready for QA.

**Comment by WiseQA** [comment]
QA review verified the 2 green circle buttons under "Actions" were replaced with the one circle (with vertical dots).  Select circle verify square popup is displayed with options of "Edit report" and "Download as .fec".   

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1a214915-762d-4966-b7e7-415ea6bc709a)

When selecting "Edit report" from the popup the Manage your transactions page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5811f1cc-acbe-493d-b5c9-ac27f190e451)

When selecting "Download as .fec" from the popup the option to Generate .fec page is displayed (Note this is setup for testing)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0c1e2485-7ee6-4f2f-91f4-76197d5bda95)

QA Review Completed.  Moved to Stage Ready.
