### ISSUE TITLE
System to save Transaction Memo Text as separate TEXT record

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#403]
Business Reason

As a user, I will be able to enter additional information for a transaction in the Memo Text field of a transaction and it will save as a Text record associated with the transaction so that I can have more space for my documentation.

Acceptance Criteria

***Given*** the user is creating or editing a transaction

  ***Then*** they will have the option to enter Memo Text (A/N, 4000)

  ***And*** when they save the transaction, the Memo Text will be saved as a TEXT record associated with that transactions.

  ***And*** the TEXT record row will be saved in the *.fec file directly beneath the transaction row.

### QA Notes ###
The screenshot of the fec file has been replaced here with a file that can be downloaded and opened with MS Notepad: ~~[The .fec generated in testing.](https://app.zenhub.com/files/306118986/ecbb03c8-1865-4449-b781-bff66827a488/download)~~ (Click on this link [new](https://app.zenhub.com/files/306118986/d4738372-716c-4f04-b6ea-28e23671471a/download) one generated after some last minute revisions to .fec generation)  It was renamed to have a .txt extension because Zenhub does not allow the .fec extension for some reason...

Transactions that need testing (as of 10/13/22)

- Individual Receipt (Group A)
- Tribal Receipt (Group D)
- Earmark Receipt (Group A)
- Earmark Memo (Group G)
- Joint Fundraising Transfer (Group E)
- PAC JF Transfer Memo (Group F)
- Offset to Operating Expenditures (Group B)
- Other Receipts (Group C)

DEV per meeting last week, please add screen shot of .fec file in QA notes what needs verified.   Also, if there is an order to the output in .fec file please denote in QA notes for testing purposes.

### DEV Notes ###
- See specs for Text record [here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=4932567).
- Backend development should put the memo text from the form input into the memo_text Django model to ease the output to the *.fec file
- Ideally, we'll have a foreign key from the memo_text table to the transaction table so the memo_text is linked to its parent transaction. The wrinkle in this is that the foreign key on memo_text should look to ALL transaction tables not just scha_transactions but also future tables such as schb_transactions and the others
- Part of this ticket will be to implement the memo_text management similarly as we do the contact data. For this to work across more than Sch A transactions, the code for the contact and memo_text management when a transaction is saved needs to be refactored out to a couple of SerializerMixin classes: ContactTransactionSerializer and MemoTextSerializer that pull this code into the SchATransactionSerializer
- Also, please rename the SchATransactionParentSerializer to SchaTransactionSerializer and the current SchATransactionSerializer to SchATransactionBaseSerializer classes

### Design ###
null

 See full ticket and images here: [FECFILE-1127](https://fecgov.atlassian.net/browse/FECFILE-1127)

**Comment by AureliaKhorsand** [comment]
Per Ryan via Slack on 7/19/22:  In OP2 my preference would be that we ignore Field 44 in the .fec and instead output any text in the Memo Text Description box to the Text field in the .fec with a backreference to the specific transaction.  This will allow the filer to provide additional information, which may be needed for some transactions, specifically multi-state IEs.  Please let me know if anyone has any comments or questions on this one.  Below I have provided some additional information in regards to the two different memo texts that exist in the format specifications (.fec files).”

See notes with screenshot [here](https://docs.google.com/document/d/1r-adG8vnCoftnkXlWklCFm60zNJBONEgttrAoUOF36U/edit).

**Comment by mjtravers** [comment]
Changes requested in CR. Sending to In Progress.

**Comment by Elaine-Krauss-TCG** [comment]
A .fec generated with this ticket

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/4e8c7c68-83cf-442f-bc4d-291514ac8ed8)

**Comment by mjtravers** [comment]
Some requests from CR. Sending back to In Progress

**Comment by mjtravers** [comment]
Issues found with the memo text and the Earmark Receipts screen. Sending back to "In Progress"

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG  what was the changes sent back to In-progress or does it matter to QA ?  Also is there a pattern I need to see in the response from .fec ?  or does it matter on the order of things being posted ?

**Comment by Elaine-Krauss-TCG** [comment]
@WiseQA 

The changes requested as part of CR mostly reflected code changes that needed to be made in order to have the cleanest possible solution rather than anything that a user would be able to observe.

The generated .fec should have the memo text descriptions present on their own separate lines immediately following their respective transactions per the ticket requirements

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA verified .fec file is downloadable, and viewable as denoted in acceptance criteria.  (Note downloaded to NotePad)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/813973f2-6fff-4e37-bdab-87d861579f91)

QA Review Completed.   Moved to Stage Ready.
