### ISSUE TITLE
System to only show relevant Form 3X transactions for "PAC" Committee Type

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#404]
Business Reason

As a Committee Administrator, I will be able to only see, create, and update transactions that correspond to my committee type so that I can only create and update the transactions that apply to my committee type.

Acceptance Criteria

***If*** I am a Committee Administrator for a PAC committee type (Committee Type is included [HERE]([https://docs.google.com/spreadsheets/d/10fwbBXjS9C3N0Q2QqjWbyPpWF_ow4F59WdZbh0_osu4/edit#gid=1295372537](https://docs.google.com/spreadsheets/d/10fwbBXjS9C3N0Q2QqjWbyPpWF_ow4F59WdZbh0_osu4/edit#gid=1295372537)))

  ***When*** I see which transactions are available for me to add and update on a Form 3X report

  ***Then*** I will see only the following transactions:

***Add a Receipt*** 

  Contributions from Individuals/Persons:

*   [ ] Individual Receipt
*   [ ] Tribal Receipt
*   [ ] Partnership Receipt
*   [ ] In-kind Receipt
*   [ ] Returned/Bounced Receipt
*   [ ] Earmark Receipt
*   [ ] Conduit Earmark Receipt
*   [ ] Receipt from Unregistered Entity
*   [ ] Receipt from Unregistered Entity - Returned/Bounced Receipt

Contributions from Registered Users:

*   [ ] Party Receipt
*   [ ] Party In-kind Receipt
*   [ ] Party Returned/Bounced Receipt
*   [ ] PAC Receipt
*   [ ] PAC In-kind Receipt
*   [ ] PAC Earmark Receipt
*   [ ] PAC Conduit Earmark
*   [ ] PAC Returned/Bounced Receipt

Transfers:

*   [ ] Transfer
*   [ ] Joint Fundraising Transfer
*   [ ] In-kind Transfer

Refunds:

*   [ ] Refund of Contribution to Federal Candidate
*   [ ] Refund of Contribution to Other Political Committee
*   [ ] Refund of Contribution to Unregistered Committee

Other:

*   [ ] Offset to Operating Expenditures
*   [ ] Other Receipts
*   [ ] Individual Receipt - Non-contribution Account
*   [ ] Other Committee Receipt - Non-contribution Account
*   [ ] Business/Labor Organization Receipt - Non-contribution Account

***Add a disbursement*** 

  Operating Expenditures:

*   [ ] Operating Expenditure
*   [ ] Credit Card Payment for Operating Expenditure
*   [ ] Staff Reimbursement for Operating Expenditure
*   [ ] Payment to Payroll for Operating Expenditure
*   [ ] Void of Operating Expenditure

Contributions/Expenditures to Registered Filers:

*   [ ] Transfers to Affiliates/Other Committees
*   [ ] Contribution to Candidate
*   [ ] Void of Contribution to Candidate
*   [ ] Contribution to Other Committee
*   [ ] Void of Contribution to Other Committee
*   [ ] In-kind Contribution to Candidate
*   [ ] In-kind Contribution to Other Committee

Other Expenditures:

*   [ ] Business/Labor Organization Receipt - Non-contribution Account
*   [ ] Individual Refund - Non-contribution Account
*   [ ] Other Committee Refund - Non-contribution Account
*   [ ] Other Disbursement
*   [ ] Credit Card Payment for Other Disbursement
*   [ ] Staff Reimbursement for Other Disbursement
*   [ ] Payment to Payroll for Other Disbursement
*   [ ] Void of Other Disbursement
*   [ ] Non-contribution Account Disbursement
*   [ ] Non-contribution Account Credit Card Payment
*   [ ] Non-contribution Account Staff Reimbursement
*   [ ] Non-contribution Account Payment to Payroll

Refunds:

*   [ ] Refund of Individual Contribution
*   [ ] Refund of Individual Contribution - Void
*   [ ] Refund of Party Contribution
*   [ ] Refund of Party Contribution - Void
*   [ ] Refund of PAC Contribution
*   [ ] Refund of PAC Contribution - Void
*   [ ] Refund of Unregistered Receipt from Person
*   [ ] Refund of Unregistered Receipt from Person - Void

Independent Expenditures

*   [ ] Independent Expenditure
*   [ ] Multistate Independent Expenditure
*   [ ] Credit Card Payment for Independent Expenditure
*   [ ] Staff Reimbursement for Independent Expenditure
*   [ ] Payment to Payroll for Independent Expenditure
*   [ ] Void of Independent Expenditure

***Add a loan or debt***

*   [ ] Loan Received from Individual
*   [ ] Loan Received from Bank
*   [ ] Loan by Committee
*   [ ] Debt Owed to Committee
*   [ ] Debt Owed by Committee

Dev Notes

*   Committee Type can be determined using the following: [https://docs.google.com/spreadsheets/d/10fwbBXjS9C3N0Q2QqjWbyPpWF_ow4F59WdZbh0_osu4/edit#gid=1295372537](https://docs.google.com/spreadsheets/d/10fwbBXjS9C3N0Q2QqjWbyPpWF_ow4F59WdZbh0_osu4/edit#gid=1295372537)
*   Schedule A and B PAC and PAC/PTY transactions: [https://docs.google.com/spreadsheets/d/1PfDEfdMtUmiLIW1pOeA7_M4_lbwzs3Bb/edit?usp=drive_link&ouid=101369876548603687926&rtpof=true&sd=true](https://docs.google.com/spreadsheets/d/1PfDEfdMtUmiLIW1pOeA7_M4_lbwzs3Bb/edit?usp=drive_link&ouid=101369876548603687926&rtpof=true&sd=true)

### QA Notes ###
- [x] BA/Design Quality Checklist complete
- Will need to test using a PAC committee type, such as a Non-qualified Leadership PAC (Committee Designation 'D' and Committee Type 'N') or Non-Qualified PAC (Committee Designation 'U' and Committee Type 'N')

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1126](https://fecgov.atlassian.net/browse/FECFILE-1126)

**Comment by AureliaKhorsand** [comment]
[Transactions per Committee Type](https://docs.google.com/spreadsheets/d/1dmFWuigbA9drBum6TxrAR4SDSTN_smNZ/edit#gid=772595287)
- See comments in spreadsheet
- Don't worry about highlighted colors.
- Need to look for Committee Type to determine what to show. See this spreadsheet

1) See Column F. "Non-Party" is PAC, "Party" is Party, "Other" is PAC. 
2) For Host/Convention Committee, no way to tell for us in the database. Is also UX. For now, allow access to Form 3X.

**Comment by GreggMoreland** [comment]
@AureliaKhorsand This has been updated to look at one spreadsheet with three tabs instead of three separate spreadsheets.

**Comment by mjtravers** [comment]
@GreggMoreland A few comments/questions:

- This is technically straight forward, we get and store the committee information in the browser at login. The info includes the "committee_type" and "designation" fields in the data we pull from FEC regarding the logged in user's committee.
- Is it the transaction type accordion pick lists will only show transaction types for that particular committee type?
- How time consuming would it be to get the transaction type identifier listed in the spreadsheets that list what transaction type is a PAC, PTY, or PAC/PTY? That would aid in code development greatly.

**Comment by GreggMoreland** [comment]
@mjtravers Thanks for the comments.

- Yes, since they would be selecting the transactions and not the memos, it would be just the transaction type. I've updated the lists to only show the Tier 1 transactions.
- I've also updated the lists to include the transaction type identifier. This was pulled from the master transaction spreadsheet, so it was simple.

**Comment by AureliaKhorsand** [comment]
@GreggMoreland I'm thinking it would be helpful to condense the lists into one, so it's easy to go straight down the page and check them off when testing. Also, could you maybe add the transaction groupings like they appear in the app as well, and give some committee type options for testing like in #1472 ? Thanks!

**Comment by GreggMoreland** [comment]
@AureliaKhorsand I have updated this as suggested. If this looks good, then I will go on to update the other ticket similarly.

**Comment by GreggMoreland** [comment]
@sasha-dresden @AureliaKhorsand Spreadsheet link is updated and AC's were validated

**Comment by MitchellTCG** [comment]
On hold until Mary's account is changed to a Party or PAC

Mary's committee id is: C00100479

**Comment by dheitzer** [comment]
@WiseQA @MitchellTCG Mary's committee has been set to **PAC - qualified** in **dev**

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA verified the following transactions show for PAC Committee (copied AC list to verify).  (Note:  Tested Individual Receipt, Party Receipt, Operating Expenditure, Contribution to Candidate transactions - verified transactions were created and saved)

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/0201144a-5f51-40c7-bfd3-8d5ac9aed0c4)

________________________________________________________________________________________________________________________

**Add a Receipt** 
Contributions from Individuals/Persons:
- [x] Individual Receipt
- [x] Tribal Receipt
- [x] Partnership Receipt
- [x] In-kind Receipt
- [x] Returned/Bounced Receipt
- [x] Earmark Receipt
- [x] Conduit Earmark Receipt
- [x] Receipt from Unregistered Entity
- [x] Receipt from Unregistered Entity - Returned/Bounced Receipt

Contributions from Registered Users:
- [x] Party Receipt
- [x] Party In-kind Receipt
- [x] Party Returned/Bounced Receipt
- [x] PAC Receipt
- [x] PAC In-kind Receipt
- [x] PAC Earmark Receipt
- [x] PAC Conduit Earmark 
- [x] PAC Returned/Bounced Receipt

Transfers:
- [x] Transfer
- [x] Joint Fundraising Transfer
- [x] In-kind Transfer

Refunds:
- [x] Refund of Contribution to Federal Candidate
- [x] Refund of Contribution to Other Political Committee
- [x] Refund of Contribution to Unregistered Committee

Other:
- [x] Offset to Operating Expenditures
- [x] Other Receipts
- [x] Individual Receipt - Non-contribution Account
- [x] Other Committee Receipt - Non-contribution Account
- [x] Business/Labor Organization Receipt - Non-contribution Account

**Add a disbursement** 
Operating Expenditures: 
- [x] Operating Expenditure
- [x] Credit Card Payment for Operating Expenditure
- [x] Staff Reimbursement for Operating Expenditure
- [x] Payment to Payroll for Operating Expenditure
- [x] Void of Operating Expenditure

Contributions/Expenditures to Registered Filers:
- [x] Transfers to Affiliates/Other Committees
- [x] Contribution to Candidate
- [x] Void of Contribution to Candidate
- [x] Contribution to Other Committee
- [x] Void of Contribution to Other Committee
- [x] In-kind Contribution to Candidate
- [x] In-kind Contribution to Other Committee

Other Expenditures:
- [x] Business/Labor Organization Receipt - Non-contribution Account
- [x] Individual Refund - Non-contribution Account
- [x] Other Committee Refund - Non-contribution Account
- [x] Other Disbursement
- [x] Credit Card Payment for Other Disbursement
- [x] Staff Reimbursement for Other Disbursement
- [x] Payment to Payroll for Other Disbursement
- [x] Void of Other Disbursement
- [x] Non-contribution Account Disbursement
- [x] Non-contribution Account Credit Card Payment
- [x] Non-contribution Account Staff Reimbursement
- [x] Non-contribution Account Payment to Payroll

Refunds:
- [x] Refund of Individual Contribution
- [x] Refund of Individual Contribution - Void
- [x] Refund of Party Contribution
- [x] Refund of Party Contribution - Void
- [x] Refund of PAC Contribution
- [x] Refund of PAC Contribution - Void
- [x] Refund of Unregistered Receipt from Person
- [x] Refund of Unregistered Receipt from Person - Void

Independent Expenditures
- [x] Independent Expenditure
- [x] Multistate Independent Expenditure
- [x] Credit Card Payment for Independent Expenditure
- [x] Staff Reimbursement for Independent Expenditure
- [x] Payment to Payroll for Independent Expenditure
- [x] Void of Independent Expenditure

**Add a loan or debt**
- [x] Loan Received from Individual
- [x] Loan Received from Bank
- [x] Loan by Committee
- [x] Debt Owed to Committee
- [x] Debt Owed by Committee

_____________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
