### ISSUE TITLE
Split up fecfile front-end and back-end applications into new repos

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#41]
Per @mjtravers we should split up the fecfile front-end and back-end applications into new repos. Team consensus is `fecfile-web-app` for the front-end and `fecfile-web-api` for the back-end.

Directories to exist in fecfile-web-app after split:
- .circleci
- deploy-config
- front-end
- protractor
- selenium

Directories to exist in fecfile-web-api after split:
- .circleci
- db
- django-backend

**Acceptance criteria**
- [x] Back-end code and commit history is in `fecfile-web-api` repo: https://github.com/fecgov/fecfile-web-api. Repo branch protections and default branch settings should be brought over 
- [x] Front-end code and commit history is in `fecfile-web-app` repo (rename fecfile-online)
- [x] CircleCI config.yml and .circleci/README updated in both repositories to reflect changes in their respective code bases.
- [ ] **THIS ACCEPTANCE CRITERIA IS OBE** Assuming that Issue #47 has been completed, then the CircleCI config.yml for fecfile-web-app will need to be modified to build a version of fecfile-web-api so that e2e testing can run
- [x] Docker-compose config updated in both repositories to reflect changes in their respective code bases.
- [x] README file in the roots of each repository updated to reflect changes.
- [x] Directory changes as listed above made in each new repository
- [x] All open issues will need to be replicated in the appropriate repo, either fecfile-web-api or fecfile-web-app. 
- [x] Replicated open issues should not be duplicated. (i.e. every open issue should be copied to either web-app or web-api)
- [x] The fecfile-online Wiki can be left in place in fecfile-online.
- [x] User accounts and permissions in fecfile-online must be replicated in both fecfile-web-app and fecfile-web-api

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Issue [#47](https://github.com/fecgov/fecfile-web-app/issues/47) was not completed so the acceptance criteria 4th in the list is not necessary and will be handled in issue #47.

**Comment by mjtravers** [comment]
For QA: Here are the links to the repository directories that should contain the directories listed in the ticket descriptions. Note that there can be additional files and directories in addition to the ones on the list. Also, for "deploy-config", it has only one subdirectory, "front-end-nginx-config" so GitHub displays the 2 directories together like "deploy-config/front-end-nginx-config" in the UI.

https://github.com/fecgov/fecfile-web-app
https://github.com/fecgov/fecfile-web-api

**Comment by WiseQA** [comment]
Verified the following directories exist in fecfile-web-app after split.  Verified each directory can be accessed.  Verified "deploy-config" directory has one subdirectory.
.circleci
deploy-config
front-end
protractor
selenium

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a663c3e3-4a11-4d10-b660-931a0b948505)

fecfile-web-app directories pass QA review.

**Comment by WiseQA** [comment]
Verified the following directories exist in fecfile-web-api after split.  Verified each directory can be accessed.
.circleci
db
django-backend

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0e2881ce-52ad-40ff-853d-58c5772f78f2)

fecfile-web-api directories pass QA review.

QA review completed on this ticket.  Moved to Stage Ready.
