### ISSUE TITLE
Users Log Out on Login.gov in DEV Branch

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#411]
This ticket is for the Log Out capability from Login.gov on the DEV server branch.   Currently there is a timing issue (15 minutes) for logout from login.gov.

(Note ticket #328:  The login.gov code developed and tested on the feature/109-django-login-dot-gov branch is being deployed to the secondary test environment. This ticket is for the task of merging that code into the develop branch and deploying it to the develop server.)

https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/328

Technical tasks (to be done in order)

- [x] Users log out
- [x]  Users log into dev again and verify they can see their existing report and transaction data in the UI

 Dev Notes 

- The create_user() override of BaseUserManager does not keep the signature integrity of the parent function. Updates needed to authentication models.py and the mozilla-django-oidc repo. See: https://docs.djangoproject.com/en/3.2/ref/contrib/auth/#django.contrib.auth.models.UserManager.create_user

### QA Notes ### 
 -  When you are done in the application, click Profile -> Logout.  You should be redirected to the original FECfile login page
-  Select the Login with login.gov button.   The login.gov email / PW credential page is displayed to re-login.
-  Note that the original login method still works and can be tested as well
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by WiseQA** [comment]
-  When you are done in the application, click Profile -> Logout. You should be redirected to the original FECfile login page.   Following error appears (tested 3 times, browser cache, cookies all cleared before restesting).  

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b7f06336-4127-4800-8e18-a54ddf28448e)

@mjtravers @toddlees @dheitzer returned in "In-Progress" per our meeting discussison.

**Comment by mjtravers** [comment]
Passes CR, ready for QA on STAGE

**Comment by WiseQA** [comment]
QA Review verified the timeout issue for logout from Login.gov in both Stage and DEV branches has been fixed.   Logout is working from Login.gov

1.  Select the Login with login.gov button. The login.gov email / PW credential page is displayed to login. 
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f61afb3a-b342-49de-aafc-b0f6b40dc972)

2.  After login click Profile -> Logout. Verify redirected to the original FECfile login page.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6da1208c-65af-4e51-b201-1734ee7e5a33)

3.  Select the Login with login.gov button. The login.gov email / PW credential page is displayed to re-login.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d515ba00-1c8f-4fc2-a9d6-8658ead7062e)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/71da5f12-d66f-4ef7-a16f-5ef637683697)

QA Review Completed.  Moved to Stage Ready.
