### ISSUE TITLE
Allow user to save new Committee contact from Transaction entry to Contact Management-Part 2

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#413]
Business Reason 
 

As a user, if I do not see the Committee contact available in the Lookup (Contact Management) when entering a Transaction, I will be able to enter a new contact in a transaction screen within the Form 3X report, with the option to use the FEC Lookup, and that new contact will save to my committee account's Contact Management so that I can easily pull that contact again in the future using Lookup (Contact Management). 

 Acceptance Criteria 
 

_Note: The transaction entry form will _only_ show the contact lookup until a contact is selected. Once a contact is selected, the transaction form will show._

**Given** a user is entering a transaction with Entity Type COM"
**Then** the user will have the option to create a new contact of that type from within the transaction by _either_

- FEC Lookup
- Manual entry

**If** the user uses the FEC Lookup, it will:
- Appear in the search dropdown under "Create a new contact from the list of registered Committees"
- highlight the matching text from the search box within the results
- highlight a selection grey if hovered over with the pointer
- be limited to **5** maximum _(Dev/QA note: for now, users need to type more to narrow it down. #542 will address when results are more than 10.)_
- upon contact selection, open a popup to enter a new contact with the contact info pulled from FEC pre-populated. 

**If** the user uses manual entry, 
**then**  the system will provide a popup to enter a new contact.

**And** when they save the new contact by either selecting a committee from the Lookup or saving the manually entered contact, the transaction screen will be populated with relevant info and show the full transaction entry form.

**When** the user saves the transaction, they must confirm that this will create a new contact in their committee account
**And** the confirmation message will be dynamic and include the contact type and contact name created
**And when** the transaction is saved, a new contact in Contact Management will be created with the contact info from the Create New Contact popup and any edits made on the transaction page itself.

 DEV NOTES
From the FEC lookup search endpoint, once a contact is selected, use that key to pull the full committee data (same endpoint as Form 1 data).

Will need to also add the highlight layer to the FEC lookup results coming in. 

 QA notes 

Relevant existing Transactions to test:
- Joint Fundraising Transfer
- PAC JF Transfer Memo
- Other Receipts

Verify "Cancel" (enabled) "Save & view all transactions" and "Save & add another" buttons (disabled).

 Wireframes: 
(Note: down arrow next to "Committee" only if other entity types are valid for selection.)

Transaction Entry screen before selecting a contact:
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/7783f975-0107-4f85-a4a4-45d558d5f981)

"Create new Contact" buttons:
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/b5a1bad5-1556-4aee-a831-3fe2f4a7c0ca)

![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/ad147da5-ea89-4294-b08c-6f7895701637)

![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/93220ec1-8c9c-4848-86ba-f3eb845717dd)

Creating a new Contact in the popup:
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/1f07b21a-2bc6-41a7-b76b-39750abe93c2)

Confirmation message when saving:
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/913ac1fd-2155-439b-966b-898887087275)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR and released to STAGE server.

**Comment by WiseQA** [comment]
QA review incomplete.     @mjtravers @MitchellTCG returned to 'In-Progress" for the following fixes:

1.  Fix hiding and showing of forms until contact link selected.

2.  Change green button to match what is in wireframe.

 ![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/82c4d129-c331-4262-8407-0cdee62b969f)

3.   Fix display of lookup and Create new contact (spacing issues)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c32ba351-4d2a-4ec7-aa94-eb3adf4645a1)

@mjtravers please add any issues not listed above.

**Comment by mjtravers** [comment]
Passes CR, ready for QA

**Comment by MitchellTCG** [comment]
@dheitzer  @mjtravers 
### App#413 — PASSED ###
When I clicked "Create a new contact" on JF Transfer, Other and Offset:
1. I was able to enter data in the fields of the "Create a new contact" modal
 ![Screen Shot 2022-10-10 at 9.33.16 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/429747b4-160b-404f-8aaf-005c087fce4d)

2. After clicking Save and continue, the modal disappeared and the data I entered into the previous modal populated the transaction form
![Screen Shot 2022-10-10 at 9.28.58 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/6d909f3e-140d-4ca0-a6c3-0cb7ddac7bf0)

3. After filling in the Contribution date and amount  and clicking Save and view all transactions (It also works for Save and add more), a pop up appears asking you to confirm you want to create a new contact
![Screen Shot 2022-10-10 at 9.26.44 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/10a00ea1-cfbb-4653-9c90-bf6bcab82c50)

4. You will return to the transaction page and see your new transactions created with the associated committee displayed
![Screen Shot 2022-10-10 at 9.29.19 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/36174f08-0954-488c-ac0c-28cdce062052)

5. And you will see the new contact on the contact page:
![Screen Shot 2022-10-10 at 9.29.30 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/e4950bfb-c975-48b3-bf49-cad243ac5c66)

This ticket works as expected.
