### ISSUE TITLE
Fix display of report left nav for edit transaction screens

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#415]
The urls assigned to the edit transaction screens need to be changed so that the report left nav displays and shows the "ENTER A TRANSACTION" -> "Manage your transactions" menu item

1.  1.  Acceptance Criteria ##

             WHEN a user clicks on "Manage your transactions" in the left report nav when editing a report, and then edits a transaction, THEN the left report nav will still be displayed the the selected item will be "Manage your transactions"

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1123](https://fecgov.atlassian.net/browse/FECFILE-1123)

**Comment by mjtravers** [comment]
This ticket was split off from the left nav work done in #350: https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/350

**Comment by mjtravers** [comment]
Passed CR by Elaine. Sending to QA

**Comment by WiseQA** [comment]
QA review verified the report left navigation for edit transaction screens display was fixed.

1.  Click on "Manage your transactions" in the left navigation when editing a report.

2.  After editing and saving a report verify  "Manage your transactions" from the left navigation is still displayed and selected

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9711b502-ce96-4a1f-8c16-f836e0531d36)

QA Review Completed.   Moved to Stage Ready.
