### ISSUE TITLE
Remove population of filer_committee_id_number from front end

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#419]
The filer_committee_id_number that is part of any transaction so far is being populated in the front end which can be problematic. Factor out the filer_committee_id_number and remove it from the transactions_transaction table in the back end. Also do this for the back_reference_tran_id_number and back_reference_sched_name as we use foreign keys to manage this in the database.

***DEV Tasks***

*   Remove filer_committee_id_number references from the front end
*   Remove the filer_committee_id_number from the transactions_transaction table
*   Make sure that the *.fec file create process is adding the correct committee account number to the filer_committee_id_number fields in the *.fec file
*   Remove back_reference_tran_id_number and back_reference_sched_name references from the front end.
*   Remove back_reference_tran_id_number and back_reference_sched_name references from the transactions_transaction table
*   Make sure that the *.fec file create process is adding the correct transaction_id and schedule_name to the back_reference_tran_id_number and the back_reference_sched_name fields in the *.fec file

***QA Notes***

  To test this, the *.fec file should have the correct values in the filer_committee_id_number, back_reference_tran_id_number, and back_reference_sched_name fields in the file.

### QA Notes ###
**DEV Tasks**

- Remove filer_committee_id_number references from the front end
- Remove the filer_committee_id_number from the transactions_transaction table
- Make sure that the *.fec file create process is adding the correct committee account number to the filer_committee_id_number fields in the *.fec file
- Remove back_reference_tran_id_number and back_reference_sched_name references from the front end.
- Remove back_reference_tran_id_number and back_reference_sched_name references from the transactions_transaction table
- Make sure that the *.fec file create process is adding the correct transaction_id and schedule_name to the back_reference_tran_id_number and the back_reference_sched_name fields in the *.fec file

**QA Notes**
To test this, the *.fec file should have the correct values in the filer_committee_id_number, back_reference_tran_id_number, and back_reference_sched_name fields in the file.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1122](https://fecgov.atlassian.net/browse/FECFILE-1122)

**Comment by mjtravers** [comment]
Duplicate of #625. Closing ticket

**Comment by mjtravers** [comment]
Removed wrong duplicate. Restoring this ticket.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers @toddlees Please add screenshot to support this ticket.

**Comment by mjtravers** [comment]
Screenshot of *.fec file with 1 parent transaction and 1 child transaction. Linked fields are in the same color highlight.
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/dfd7f922-d3fb-4d81-ab9f-261714eaa41c)

**Comment by WiseQA** [comment]
QA review verified .fecfile displaying the parent and child transaction.   

QA Review Completed.   Moved to Stage Ready.
