### ISSUE TITLE
Investigate setting up Login.gov sandbox account

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#42]
Investigate setting up a Login.gov sandbox account for general development use (if possible)

There may be a .gov email account restriction on the usage of the sandbox account

Instructions for creating a sandbox account:
[https://developers.login.gov/testing/](https://developers.login.gov/testing/)

***ACCEPTANCE CRITERIA:***

*   If possible, developers will be able to make API calls to the sandbox account.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1352](https://fecgov.atlassian.net/browse/FECFILE-1352)

**Comment by lbeaufort** [comment]
Noting that an email address ending in .gov or .mil is needed to set up a login.gov sandbox account.

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 3/3/22:** Learning curve ticket. Blocker: you need a .gov or .mil to set up a sandbox account. Need to follow up, this is now an investigation ticket.

**Comment by lbeaufort** [comment]
Work so far on demo app lives here: https://github.com/fecgov/login-gov-demo

Notes/resources:
https://docs.google.com/document/d/1LJVdS7CIVgd-9OmBnfSIaPCfH30iDTfF-4BGXFSSjFA/edit

**Comment by lbeaufort** [comment]
Potential workflow diagram, thank you @toddlees for your help!
https://docs.google.com/drawings/d/1l5qDa7N_iU4MbSPZUKX2xrvknjEVFa70WhKMYcJFleU/edit
