### ISSUE TITLE
System to allow negative values for currency fields in Transactions

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#421]
Business Reason

The system must allow negative values for currency fields in Transactions so that users can accurately report disbursements, refunds, etc.

Acceptance Criteria

***Given*** a user is entering a transaction

  1\. Individual Receipt (Group A)

  2\. Tribal Receipt (Group D)

  3\. Joint Fundraising Transfer (Group E)

  4\. Joint Fundraising PAC Memo (Group F)

  5\. Offsets to Operating Expenditures (Group B)

  6\. Other Receipt (Group C)

***When*** they enter a currency amount for Contribution Amount

  ***Then*** a negative value will be accepted as valid.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1121](https://fecgov.atlassian.net/browse/FECFILE-1121)

**Comment by Elaine-Krauss-TCG** [comment]
The requirements of this ticket _seem_ to already be fulfilled?

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/ad925a85-ee71-466e-b500-35fdb461a95c)

**Comment by WiseQA** [comment]
@mjtravers - Elaine tested and the negative values are showing for the transactions.   This negative value was verified when COH was developed.   I plan on retesting this ticket and verify negative values for each of the transactions before moving to Stage Ready.

**Comment by mjtravers** [comment]
@WiseQA - Ok, that sounds like a good QA plan
@mjtravers - awaiting CR before testing.

**Comment by WiseQA** [comment]
QA review verified negative values for the following transactions as shown in screenshot below:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/97bfd32b-4cc8-48f1-9598-5a805e407838)

QA Review Complete.  Moved to Stage Ready
