### ISSUE TITLE
DSP: System to calculate Offsets to Operating Expenditures (line 15 and 37) (Column B)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#426]
Business Reason 
 

On the Detailed Summary Page, Line 15 and Line 37 should each be a total of transactions with form type SA15 _except_ for if the transaction has "Memo Code" checked. This ticket is for Column B only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 15 (column B) of Form 3X must:
--  consist of the total of transactions with form type "SA15"  **from January 1 of current year to the report coverage period end date**
-- NOT include any transactions with "Memo Code" checked
2. Detailed Summary Page Line 37 (column B) should be a copy of Line 15 (column B)
3. These numbers will update as needed until the report is submitted.

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

Example: Ryan explained that these numbers must be rolling figures - if you amend an M2 report, and are working on an open M5 report, then the M5 should be showing the total with the amended M2 taken into account, even if M3 and M4 were never submitted

### QA Notes ### 
  
The following 'Main' transaction type is included here:
Offset to Operating Expenditures

![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/7887a61e-3428-4367-9302-a60bf373ae54)

![image.png](https://images.zenhubusercontent.com/62eac7883f87756fe900911f/eba055d3-65f1-400a-9d9e-cff232472452)
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
**BA questions:** What triggers updating the Column B summation? (Changing a transaction on a previous report, deleting old transaction, amending a previous report, etc.) Also, where do we get the initial Column B number for the report? From the last number of the last report? 

Laura mentioned "locking down reports" like other vendors have. Something to consider - notifying filers that this will change based on changed transactions in other reports.

**Comment by Elaine-Krauss-TCG** [comment]
Column B calculation is working
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/30287bdc-ec8d-4a1c-a64d-89eba4a7df00)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified transactions with form type "SA15" (Column B) is displayed in the Detailed Summary Page. (NOTE: e2e testing to be run on all transactions) Total line SA15 $550.00.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f4ad15a4-50c4-414c-a044-a4406b16e5cd)

Verified total in SA15 (Column B) is displayed in line 37 (Column B) ($550.00).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b424b430-0fb9-4619-b7f1-2598de1ddec8)

**NOTE: e2e testing to be run on all transactions**

QA Review Completed. Moved to Stage Ready.
