### ISSUE TITLE
508 Compliance: Update Page Title on ALL Page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#428]
Business Reason

As The FEC Product Owner, I like 508 Compliance ticket resolved to improve the accessibility and usability of the application.

Dev Notes

This built in angular service should let us update the title cleanly [https://stackoverflow.com/a/47900525/18957717](https://stackoverflow.com/a/47900525/18957717)

Tasks

Change the page title from ***FECFile Online*** to the whatever is written next to "Page"

*   [x] ***Section:*** Dashboard

       ***Page:*** FECFile Dashboard

       _[https://fecfile-web-app-dev.app.cloud.gov/dashboard_](https://fecfile-web-app-dev.app.cloud.gov/dashboard_)

       
*   [x] ***Section:*** Reports

       ***Page:*** Manage Reports

       _[https://fecfile-web-app-stage.app.cloud.gov/reports_](https://fecfile-web-app-stage.app.cloud.gov/reports_)

       
*   [x] ***Section:*** Reports

       ***Page:*** Create a report

       _[https://fecfile-web-app-stage.app.cloud.gov/reports/f3x/create/step1_](https://fecfile-web-app-stage.app.cloud.gov/reports/f3x/create/step1_)

       
*   [x] ***Section:*** Enter a Transaction

       ***Page:*** Manage your transactions

       _[https://fecfile-web-app-dev.app.cloud.gov/transactions/report/91/list_](https://fecfile-web-app-dev.app.cloud.gov/transactions/report/91/list_)

       
*   [x] ***Section:*** Enter a Transaction

       ***Page:*** Cash on hand

       _[https://fecfile-web-app-stage.app.cloud.gov/reports/f3x/create/cash-on-hand/:reportId_](https://fecfile-web-app-stage.app.cloud.gov/reports/f3x/create/cash-on-hand/:reportId_)

       
*   [x] ***Section:*** Enter a Transaction

       ***Page:*** Add a receipt

       _[https://fecfile-web-app-dev.app.cloud.gov/transactions/report/91/create_](https://fecfile-web-app-dev.app.cloud.gov/transactions/report/91/create_)

       
*   [x] ***Section:*** Enter a Transaction

       ***Page:*** Individual Receipt

       _[https://fecfile-web-app-dev.app.cloud.gov/transactions/report/91/create/INDV_REC_](https://fecfile-web-app-dev.app.cloud.gov/transactions/report/91/create/INDV_REC_)

       
*   [x] ***Section:*** Enter a Transaction

       ***Page:*** Tribal Receipt

       _[https://fecfile-web-app-dev.app.cloud.gov/transactions/report/91/create/TRIB_REC_](https://fecfile-web-app-dev.app.cloud.gov/transactions/report/91/create/TRIB_REC_)

       
*   [x] ***Section:*** Enter a Transaction

       ***Page:*** Offsets to Operating Expenditures

       _[https://fecfile-web-app-dev.app.cloud.gov/transactions/report/91/create/OFFSET_TO_OPEX_](https://fecfile-web-app-dev.app.cloud.gov/transactions/report/91/create/OFFSET_TO_OPEX_)

       
*   [x] ***Section:*** Enter a Transaction

       ***Page:*** Other Receipts

       _[https://fecfile-web-app-dev.app.cloud.gov/transactions/report/91/create/OTH_REC_](https://fecfile-web-app-dev.app.cloud.gov/transactions/report/91/create/OTH_REC_)

       
*   [x] ***Section:*** Enter a Transaction

       ***Page:*** JF Transfers

       _[https://fecfile-web-app-dev.app.cloud.gov/transactions/report/91/create/JF_TRAN_](https://fecfile-web-app-dev.app.cloud.gov/transactions/report/91/create/JF_TRAN_)

       
*   [x] ***Section:*** Enter a Transaction

       ***Page:*** JF Transfer PAC Memos

       _[https://fecfile-web-app-dev.app.cloud.gov/transactions/report/91/list/edit/74/create-sub-transaction/JF_TRAN_PAC_MEMO_](https://fecfile-web-app-dev.app.cloud.gov/transactions/report/91/list/edit/74/create-sub-transaction/JF_TRAN_PAC_MEMO_)

*   [x] ***Section:*** Review a report

       ***Page:*** View summary page

       _[https://fecfile-web-app-dev.app.cloud.gov/reports/f3x/summary/91_](https://fecfile-web-app-dev.app.cloud.gov/reports/f3x/summary/91_)

       
*   [x] ***Section:*** Review a report

       ***Page:*** View detailed summary page

       _[https://fecfile-web-app-dev.app.cloud.gov/reports/f3x/detailed-summary/91_](https://fecfile-web-app-dev.app.cloud.gov/reports/f3x/detailed-summary/91_)

       
*   [x] ***Section:*** Review a report

       ***Page:*** Print preview

       _[https://fecfile-web-app-dev.app.cloud.gov/reports/f3x/web-print/91_](https://fecfile-web-app-dev.app.cloud.gov/reports/f3x/web-print/91_)

       
*   [x] ***Section:*** Review a report

       ***Page:*** Add a report level memo

       _[https://fecfile-web-app-dev.app.cloud.gov/reports/f3x/memo/91_](https://fecfile-web-app-dev.app.cloud.gov/reports/f3x/memo/91_)

       
*   [x] ***Section:*** Submit your report

       ***Page:*** Confirm information

       _[https://fecfile-web-app-dev.app.cloud.gov/reports/f3x/submit/step1/91_](https://fecfile-web-app-dev.app.cloud.gov/reports/f3x/submit/step1/91_)

       
*   [x] ***Section:*** Submit your report

       ***Page:*** Submit report

       _[https://fecfile-web-app-dev.app.cloud.gov/reports/f3x/submit/step2/91_](https://fecfile-web-app-dev.app.cloud.gov/reports/f3x/submit/step2/91_)

       
*   [x] ***Section:*** Submit your report

       ***Page:*** Report status

       _[https://fecfile-web-app-dev.app.cloud.gov/reports/f3x/submit/status/91_](https://fecfile-web-app-dev.app.cloud.gov/reports/f3x/submit/status/91_)

       
*   [x] ***Section:*** Contact

       ***Page:*** Manage Contacts

       _[https://fecfile-web-app-dev.app.cloud.gov/contacts_](https://fecfile-web-app-dev.app.cloud.gov/contacts_)

*   [x] ***Section:*** Profile

       ***Page:*** Account Page

       _[https://fecfile-web-app-dev.app.cloud.gov/profile/account_](https://fecfile-web-app-dev.app.cloud.gov/profile/account_)

*   [x] ***Section:*** Profile

       ***Page:*** Manage Users

       _[https://fecfile-web-app-dev.app.cloud.gov/committee/users_](https://fecfile-web-app-dev.app.cloud.gov/committee/users_)

### QA Notes ###

- Get ANDI from https://www.ssa.gov/accessibility/andi/help/install.html
 add ANDI to bookmarks
- Once ANDI is accessed select 'Structures' -> 'More Details' -> 'Page Title'

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1116](https://fecgov.atlassian.net/browse/FECFILE-1116)

**Comment by WiseQA** [comment]
QA review not valid testing for QA.   Provide testing for QA.  Moved back to Code Review.  

09/01/2022 - Moved back to QA got ANDI application to verify above changes.  Thanks @Elaine-Krauss-TCG 

@toddlees and I added QA note above to test this ticket using ANDI.

**Comment by Elaine-Krauss-TCG** [comment]
When using the ANDI tool while creating a report, two reference alerts are normally created regarding the Election/Non-Election select button.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/39d7ee7e-e82a-4750-b586-2cb878f99507)

With the changes made as a result of this ticket, no such reference errors are found by ANDI.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/33925380-0eb7-4661-b31a-a2332d295e49)

**Comment by WiseQA** [comment]
QA review verified, using ANDI, the above page titles have been changed.  (Screenshots of a few images showing how was verified)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6a886c2f-a834-4ac0-9c3f-b446919586eb)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dd71de98-6962-4048-bc45-8c94a4297393)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/32f10d04-f1eb-4a1a-92be-081fac7cc5eb)

QA Review Completed.  Moved to Stage Ready
