### ISSUE TITLE
Update Transaction names and remove abbreviations

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#429]
The following names must be updated in Form 3X, Schedule A to remove any abbreviations.

Transaction Selection Screen (Accordion dropdown):

  1\. "JF Transfers" should be "Joint Fundraising Transfer"

  2\. "In-Kind Transfer-FEA" should be "In-Kind Transfer - Federal Election Activity"

  3\. "JF Transfer - National Party Recount Account" should be "Joint Fundraising Transfer - National Party Recount Account"

  4\. "JF Transfer - National Party Convention Account" should be "Joint Fundraising Transfer - National Party Convention Account"

  5\. "JF Transfer - National Party Headquarters Account" should be "Joint Fundraising Transfer - National Party Headquarters Account"

  6\. "Ind. Receipt - Non-Contribution Account" should be "Individual Receipt - Non-Contribution Account"

  7\. "Business/Labor Org. Receipt - Non-Contribution Account" should be "Business/Labor Organization Receipt - Non-Contribution Account"

Transaction entry screens:

  ***JF Transfer (current name)***

  1\. "JF Transfers" should be "Joint Fundraising Transfer"

  2\. Replace "JF Transfer Memo" with "Memo" on the button to add a child transaction

***NOTE: Memo button was changed to "Save & add a Memo"***

  ![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5baf1e11-6b8e-44eb-bf16-93df29b43d09](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5baf1e11-6b8e-44eb-bf16-93df29b43d09))

### QA Notes ###

Create a new transaction and in transaction type accordion, you should see the new names for the transaction types.  Create a Joint Fundraising Transfer.  The title should be "Joint Fundraising Transfer".  The add memo button should say "Save & add a Memo".  Click that to start creating a memo.  The title for this form should be "PAC Joint Fundraising Transfer Memo".  The add another memo button should say "Save & add Memo"

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1115](https://fecgov.atlassian.net/browse/FECFILE-1115)

**Comment by WiseQA** [comment]
QA review verified names and abbreviations removed from the Transaction Selection dropdown for the following:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ae5da1ef-9534-42d7-9d0f-752224a4a021)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/65d88e65-bb74-4a12-8379-fe60f291ca5e)

QA review verified Transaction entry screens naming was changed as follows:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5c2c8ef4-5103-4bde-bbfc-09340aa8d4eb)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bd988918-7807-4825-9bda-5902521940a8)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9354bd23-08cd-4871-a36b-c908015076a0)

Verified memo button updated from:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e44b3a5b-5523-4296-84c0-02bd39163d2e)

To:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cc7fd916-f3b9-43f0-beb9-bc59b41f6f8e)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/00110acc-5fc8-4623-81bc-32fceabdbf1d)

QA Review Completed.  Moved to Stage Ready.
