### ISSUE TITLE
System to order reports in Manage reports to include form type order of 1M, 3X, 24, 99

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#435]
Business Reason

As a Committee Administrator, I will be able to view a list of reports associated with my committee account so that I can manage reports as needed.

Acceptance Criteria

_**Given**_ I am a Committee Administrator _**When**_ I go to the _**Manage reports**_ page _**Then**_ I will see a list of reports associated with my committee account in the following order by form type: – 1M – 3X – 24 – 99

### QA Notes ###

 
 - [x] BA/Design Quality Checklist complete

### DEV Notes ###

 

- Currently, form type is in alphanumeric order
- AC listed is from #165 with modification to specify form type order and include Coverage **end** date (tech notes on 165 mentioned that coverage end date was used, but AC did not specify that)
- To create a flexible and future proof sorting on the report type list, lets change sort order so that it does not sort on the report type (e.g. 1M, 3X, etc) but on a numeric value mapped to the report type.

REPORT_ORDER = {
    '1M': 10,
    '3x': 20,
    '24': 30,
    '99': 40
}
We have the order separated by tens so we can fill in additional reports anywhere in the list at a later time.

### Design ###

 
 null

[FECFILE-1113](https://fecgov.atlassian.net/browse/FECFILE-1113)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland @WiseQA 
No wire needed.

Just make sure the reports are ordered **1M, 3X, 24, and 99** 

**NOT** 1M, 24, 3X, 99

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified upon initial load the Mange reports page Form type order displays as FORM 1M, FORM 3X, FORM 24, and FORM 99 correctly

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/ff2eb262-b128-46eb-9700-a45d1bd49b4f)
_________________________________________________________________________________________

Verified when selecting the descending error the Manage reports Form type order displays FORM 99. FORM 24, FORM 3X,  and FORM 1M

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/3116c300-0968-4e0b-8ce2-82bf00cac832)
______________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
