### ISSUE TITLE
Allow user to edit Contribution Purpose Description IF it is not system-generated

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#436]
Business Reason

As a user, I will be able to manually enter information to the Contribution Purpose Description _unless_ it has pre-populated text so that I can provide additional information needed for the transaction and have it appear in the expected place for public record.

Acceptance Criteria

***Given*** there is no pre-populated text for the Contribution Purpose Description

  ***When*** the user is creating or editing the transaction

  ***Then*** they have the option to enter text (A/N, 100).

  ***And*** the page will indicate that it is "optional".

OR

***Given*** there is pre-populated text for the Contribution Purpose Description

  ***When*** the user is creating or editing the transaction

  ***Then*** they will not be able to enter text in the Contribution Purpose Description

  ***And*** the page will indicate that it is "system-generated".

Wires

1.  1.  ***do not*** have pre-populated text

             ##

             For Individual Receipt, Offset to Operating Expenditures, and Other Receipts

             ![Group A - Individual Receipt - Individual.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/854ec613-6d79-4d98-a759-954de354eecd](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/854ec613-6d79-4d98-a759-954de354eecd))

1.  1.  ***do*** have pre-populated text

             ##

             For Tribal Receipt, Joint Fundraising Transfer, PAC JF Transfer Memo, Earmark Receipt, and Earmark Memo

             ![Group D - Tribal Receipt - Organization – 2.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/07869dcd-8ada-4526-9ddd-9930a1d4fddb](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/07869dcd-8ada-4526-9ddd-9930a1d4fddb))

### QA Notes ###

As of 10/13/22, Transactions that **do not** have pre-populated text:

- Individual Receipt
- Offset to Operating Expenditures
- Other Receipts

As of 10/13/22, Transactions that **do** have pre-populated text:

- Tribal Receipt
- Earmark Receipt
- Earmark Memo
- Joint Fundraising Transfer
- PAC JF Transfer Memo

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1112](https://fecgov.atlassian.net/browse/FECFILE-1112)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand Wires have been added

**Comment by mjtravers** [comment]
Passes CR. Holding off from sending to QA until all the Sprint 17 tickets are sent to Stage Ready.

**Comment by WiseQA** [comment]
QA review verified Contribution Purpose Description (Optional) if not system generated is an editable field.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/67bda3c4-d1d8-42e5-a554-1206b3ee110b)

Field edited and saved of "Contribution Purpose Description"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b0bf74c6-e423-458c-a79e-1a287d75fa52)

QA Review Completed.  Moved to Stage Ready.
