### ISSUE TITLE
Update Memo Item help text in Transactions

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#439]
***Task:*** Update "lorem ipsum" text on transaction entry screens to read: “The dollar amount in a memo item is not incorporated into the total figure for the schedule.”

***Transactions:***

1\. Individual Receipt (Group A)

  2\. Tribal Receipt (Group D)

  3\. Joint Fundraising Transfer (Group E)

  4\. Joint Fundraising PAC Memo (Group F)

  5\. Offsets to Operating Expenditures (Group B)

  6\. Other Receipt (Group C)

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1110](https://fecgov.atlassian.net/browse/FECFILE-1110)

**Comment by MitchellTCG** [comment]
![Wire.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/c5fe809d-3600-4fb3-b582-13836a58dcad)

**Comment by AureliaKhorsand** [comment]
From fec.gov: Supplemental or explanatory information on a reporting schedule. A memo entry is often used to disclose additional information about an itemized transaction that is included in the total receipts or disbursements for the current report or a previous report. The dollar amount in a memo entry is not incorporated into the total figure for the schedule.

**Comment by mjtravers** [comment]
Passed CR. Sending to QA

**Comment by WiseQA** [comment]
QA review findings text in both DEV and STAGE currently read:

MEMO ITEM
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.

should read:
MEMO ITEM
The dollar amount in a memo item is not incorporated into the total figure for the schedule.

@mjtravers Returned in In-Progress for text field fix and language fix as denoted in acceptance criteria and wireframe above.

**Comment by mjtravers** [comment]
@WiseQA The code has been deployed to the DEV server and is now testable. Moving ticket to QA

**Comment by WiseQA** [comment]
QA review verified the below transactions memo help test was updated to:  “The dollar amount in a memo item is not incorporated into the total figure for the schedule.”
1. Individual Receipt (Group A)
2. Tribal Receipt (Group D)
3. Joint Fundraising Transfer (Group E)
4. Joint Fundraising PAC Memo (Group F)
5. Offsets to Operating Expenditures (Group B)
6. Other Receipt (Group C)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/43394465-bc60-4d65-9d03-d45cbddfffe1)

QA Review Completed.  Moved to Stage Ready.
