### ISSUE TITLE
508 Compliance: Fix empty table cell on Manage Report Page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#442]
Task

*   [ ] Add "Actions" title to the Far left column table header (This column is not sortable)

![Screen Shot 2022-08-10 at 12.48.02 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/68c67a9a-2ea8-46ee-84e7-fe0d44d3abd6](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/68c67a9a-2ea8-46ee-84e7-fe0d44d3abd6))

  ![Screen Shot 2022-08-10 at 12.48.09 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/1a081f2e-4832-47be-9099-51343615769c](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/1a081f2e-4832-47be-9099-51343615769c))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1107](https://fecgov.atlassian.net/browse/FECFILE-1107)

**Comment by WiseQA** [comment]
QA review verified "Actions" label added to table row headings.   

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e009043f-f98b-4c87-9415-6920caf136bd)

QA Review Completed.   Moved to Stage Ready
