### ISSUE TITLE
508 Compliance: Improper use of [Aria-labelledby] purpose

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#443]
Tasks

There are 2 errors:

*   [x] 1\. Improper use of [aria-labelledby] possible: Referenced ids "Election,Year" not found.

*   [x] 2\. Improper use of [aria-labelledby] possible: Referenced ids "Non-Election,Year" not found.

![Screen Shot 2022-08-10 at 12.55.02 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/6cea8f9f-5d4d-4eb2-a36a-658aa0ba5e3a](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/6cea8f9f-5d4d-4eb2-a36a-658aa0ba5e3a))

![Screen Shot 2022-08-10 at 12.54.55 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/dd2f76ff-48d8-4579-adca-2ad08e8a2fbe](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/dd2f76ff-48d8-4579-adca-2ad08e8a2fbe)

  )

![Screen Shot 2022-08-17 at 1.45.01 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/85a079b1-54a1-42c2-bb0d-0a36a4f43c82](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/85a079b1-54a1-42c2-bb0d-0a36a4f43c82))

### QA Notes ###

- Get ANDI from https://www.ssa.gov/accessibility/andi/help/install.html
 add ANDI to bookmarks
- Once ANDI is accessed select 'Structures' -> 'More Details' -> 'Page Title'

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1106](https://fecgov.atlassian.net/browse/FECFILE-1106)

**Comment by mjtravers** [comment]
@Elaine-Krauss-TCG Here is the code to extend for the PrimeNG select button: https://github.com/primefaces/primeng/blob/master/src/app/components/selectbutton/selectbutton.ts

**Comment by WiseQA** [comment]
QA review check boxes in task not checked off as complete.   Screen shots of corrections not provided.  Moved back to Code Review.

**Comment by Elaine-Krauss-TCG** [comment]
When using the ANDI tool while creating a report, two reference alerts are normally created regarding the Election/Non-Election select button.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/39d7ee7e-e82a-4750-b586-2cb878f99507)

With the changes made as a result of this ticket, no such reference errors are found by ANDI.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/33925380-0eb7-4661-b31a-a2332d295e49)

**Comment by WiseQA** [comment]
QA review verified, using ANDI, the Alerts errors while creating a report have been fixed.  (Also reference screenshots above).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/50a33ab9-c083-46f8-b322-a06422e150d4)

QA Review Completed.   Moved to Stage Ready.
