### ISSUE TITLE
System to check "Memo Item" as read-only on PAC Joint Fundraising Transfer Memo

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#445]
PAC Joint Fundraising Transfer Memo will always have Memo Item checked, and it cannot be unchecked by the user, so that the transaction is never aggregated onto the Detailed Summary page.

Acceptance Criteria

***Given*** the user is entering or editing a PAC Joint Fundraising Transfer Memo

  ***Then*** the "Memo Item" checkbox will be checked and read-only.

![image.png]([https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/f7364dc6-f128-451a-9750-c7a3b01c18a5](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/f7364dc6-f128-451a-9750-c7a3b01c18a5))

### QA Notes ###

No additional information needed for this ticket.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1105](https://fecgov.atlassian.net/browse/FECFILE-1105)

**Comment by WiseQA** [comment]
QA Review verified the Memo Item checkbox is "Read Only" for PAC Joint Fundraising Transfer Memo

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/050c1846-8e5c-4dc1-bfb1-a0747ad15c3f)

QA Review Completed.   Moved to Stage Ready
