### ISSUE TITLE
Allow user to enter Party Joint Fundraising Transfer Memo on Schedule A (Group F)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#447]
Business Reason 
 

As a Committee Administrator, I will be able to enter a sub-transaction under **"Joint Fundraising Transfers"** on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator
**And** I am editing a Joint Fundraising Transfer transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction:
- Party Joint Fundraising Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	CONTACT TYPE (Read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	COMMITTEE NAME (Required)
-	COMMITTEE FEC ID (Required)

# Address 
#
-	STREET ADDRESS (Required)
-	APARTMENT, SUITE, ETC. (Optional)
-	CITY (Required)
-	STATE/PROVINCE (Required)
-	ZIP/POSTAL CODE (Required)

# Receipt Information 
#
-	DATE RECEIVED (Required)
-	MEMO ITEM (Required, read-only)
-- This will be automatically checked and the user CANNOT change it.
-	AMOUNT (Required)
-- Note: AMOUNT can contain a negative value.
-	AGGREGATE (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	CONTRIBUTION PURPOSE DESCRIPTION (Read-only, Optional)
-- Must read "JF Memo: XX", where XX is auto-populated with name of committee entered in parent transaction JF_TRAN COL SEQ 8
-	NOTE OR MEMO TEXT (A/N-100, Optional)

---
**Then** I will be able to:

- "Save & add another Joint Fundraiser Transfer Memo" associated to the same "parent"
- Back to Joint Fundraiser Transfer
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And** the transaction will be itemized upon saving with it's own line item on the *.fec file (SA12). _(Dev note: All SA12 transactions are itemized regardless of amount)._

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=470736977)

![Group F - Party JF Transfer Memo – 3.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/78939f38-f907-4a1b-84d8-7798e1d9b3c4)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@mary-tcg please add the wires to this ticket

**Comment by AureliaKhorsand** [comment]
@mary-tcg please swap the Additional Information boxes to have Contribution Purpose Description to show first, and remove bold font within pre-populated text.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
After entering a Joint Fundraising Transfer transaction, click the Save & add a memo button.  Verify dropdown list is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/af75ecec-8753-4142-b05c-97ce135e69c2)

Verify Confirm popup window is displayed - creating a new Party Memo, then select the Continue Button

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2ccdb1f1-00ce-4222-84c7-1e34b3e22b04)

Verified Party Joint Fundraising Transfer Memo page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d9a2ab69-a928-4bc9-9b4e-7f55cae0dbed)

Create a new contact.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e76c38ca-dabf-44b0-aed7-21c039329de2)

Verify Party Joint Fundraising Transfer Memo is listed in Transactions table as a "Child" to the original Joint Fundraising Transfer transaction.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d95a80b1-d911-4cab-9b20-9362297ba4ef)

QA Review Completed.   Moved to Stage Ready.
