### ISSUE TITLE
Allow user to enter Tribal Joint Fundraising Transfer Memo on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#448]
Business Reason 
 

As a Committee Administrator, I will be able to enter a sub-transaction under "Joint Fundraising Transfers"** on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator
**And** I am editing a Joint Fundraising Transfer transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction:
- Tribal Joint Fundraising Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	CONTACT TYPE (Read-only, **INCLUDES LOOKUP**)
-- Organization Only
-	ORGANIZATION NAME (Required)

# Address 
#
-	STREET ADDRESS (Required)
-	APARTMENT, SUITE, ETC. (Optional)
-	CITY (Required)
-	STATE/PROVINCE (Required)
-	ZIP/POSTAL CODE (Required)

# Receipt Information 
#
-	DATE RECEIVED (Required)
-	MEMO ITEM (Required, read-only)
-- This will be automatically checked and the user CANNOT change it.
-	AMOUNT (Required)
-- Note: AMOUNT can contain a negative value.
-	AGGREGATE (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	CONTRIBUTION PURPOSE DESCRIPTION (Read-only, Optional)
-- Must read "JF Memo: XX", where XX is auto-populated with name of committee entered in parent transaction JF_TRAN COL SEQ 8
-	NOTE OR MEMO TEXT (A/N-100, Optional)

---
**Then** I will be able to:

- "Save & add another Joint Fundraiser Transfer Memo" associated to the same "parent"
- Back to Joint Fundraiser Transfer
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And** the transaction will be itemized upon saving with it's own line item on the *.fec file (SA12). _(Dev note: All SA12 transactions are itemized regardless of amount)._

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

- [ ] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=2005370048)

![Group D - Tribal JF Transfer Memo – 4.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/5aa0d932-0d16-4f56-baf3-641d3fc91491)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@mary-tcg please add the wires to this ticket

**Comment by AureliaKhorsand** [comment]
@mary-tcg please swap the Additional Information boxes to have Contribution Purpose Description to show first, and remove bold font within pre-populated text.

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by mjtravers** [comment]
2 small changes requested in CR. Sending back to In Progress

**Comment by mjtravers** [comment]
Requested code changes will be made in new ticket: https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/668

Sending to QA.

**Comment by WiseQA** [comment]
After entering a Joint Fundraising Transfer transaction, click the Save & add a memo button.  Verify dropdown list is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d9dfdcf7-2632-4eae-a84c-8d18ab0ace19)

Verify Confirm popup window is displayed - creating a new Tribal Memo, then select the Continue Button

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/205ca0a2-a8e2-4347-9176-1cfb2b50ce78)

Verified Tribal Joint Fundraising Transfer Memo page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ccacf5bf-5ef6-4856-a548-ba680694cc11)

Create a new contact.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/46bbd75e-247d-453e-a177-5123237df41b)

Verify Tribal Joint Fundraising Transfer Memo is listed in Transactions table as a "Child" to the original Joint Fundraising Transfer transaction.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6aba46ed-9588-4e7e-a51e-1251aee66e14)

QA Review Completed.   Moved to Stage Ready.
