### ISSUE TITLE
Allow user to enter Individual Joint Fundraising Transfer Memo on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#451]
Business Reason

As a Committee Administrator, I will be able to enter a ***’Individual Joint Fundraising Transfer Memo ‘*** sub-transaction under "Joint Fundraising Transfers" on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

NOTE: This is a "child" transaction that will be associated with a parent transaction.

Acceptance Criteria

***Given*** I am a Committee Administrator

 ***And*** I am editing a Joint Fundraising Transfer transaction on an open report

 ***Then*** I will have the _option_ to enter the following sub-transaction:

*   Individual Joint Fundraising Transfer Memo

***And*** I will be required to enter the following information (unless otherwise noted):

—

1.  Contact

      #

*   CONTACT TYPE (required, read-only, ***INCLUDES LOOKUP***)
      *   Individual only
*   LAST NAME (Required)
*   FIRST NAME (Required)
*   MIDDLE NAME (Optional)
*   PREFIX (Optional)
*   SUFFIX (Optional)

1.  Address

      #

*   STREET ADDRESS (Required)
*   APARTMENT, SUITE, ETC. (Optional)
*   CITY (Required)
*   STATE/PROVINCE (Required)
*   ZIP/POSTAL CODE (Required)
*   EMPLOYER ***(Required if Contributor Aggregate > $200)***
*   OCCUPATION ***(Required if Contributor Aggregate > $200)***

1.  Receipt Information

      #

*   DATE RECEIVED (Required)
*   MEMO ITEM (Required, read-only)
      *   This will be automatically checked and the user CANNOT change it.
*   AMOUNT (Required)
      *   Note: AMOUNT can contain a negative value.
*   AGGREGATE (Required)
      *   Amount Displayed will be the total of contributions that are:
            *   From the person (ENTITY)
    *   within Aggregation Group of "GENERAL"
            *   _from_ January 1 of report year _to_ the Contribution Date* of the transaction.
        *   *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

1.  Additional information

      #

*   CONTRIBUTION PURPOSE DESCRIPTION (Read-only, Optional)
      *   Must read "JF Memo: XX", where XX is auto-populated with name of committee entered in parent transaction JF_TRAN COL SEQ 8
*   NOTE OR MEMO TEXT (A/N-100, Optional)

—

 ***Then*** I will be able to:

*   "Save & add another Joint Fundraiser Transfer Memo" associated to the same "parent"
*   Back to Joint Fundraiser Transfer
*   Save & view all transactions [will go to "Manage your transactions" Table]
*   Edit as needed

***And*** the transaction will be itemized upon saving with it's own line item on the *.fec file (SA12). _(Dev note: All SA12 transactions are itemized regardless of amount)._

—

DEV TASKS

*   BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
*   BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

*   [ ] Update schema to match [Spec Updates spreadsheet tab here]([https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1327522366](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1327522366))

![Group A - Individual JF Transfer Memo.png]([https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/87bf592e-ebd8-4da3-b4cc-f93239aa3b7b](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/87bf592e-ebd8-4da3-b4cc-f93239aa3b7b))

QA NOTES

Similar to other transaction types:

*   Must be able to enter, save, and edit according to acceptance criteria above.
*   Aggregate is part of "GENERAL" group, so it should aggregate along with transactions like INDIVIDUAL RECEIPT and should not aggregate with something like an OTHER RECEIPT. Let me know if this isn't clear. Trying to avoid over-explaining.
*   Itemization: should itemize (appear in .fec and not have "unitemized" in the transaction table) always

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1101](https://fecgov.atlassian.net/browse/FECFILE-1101)

**Comment by MitchellTCG** [comment]
@mary-tcg please add the wires to this ticket

**Comment by AureliaKhorsand** [comment]
@mary-tcg please swap the Additional Information boxes to have Contribution Purpose Description to show first, and remove bold font within pre-populated text.

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated with corrections

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
After entering a Joint Fundraising Transfer transaction, click the Save & add a memo button.  Verify dropdown list is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0887d5b6-fe21-46ed-bad7-1231bf80f71c)

Verify Confirm popup window is displayed - creating a new Individual Memo, then select the Continue Button

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3eabf4d0-070a-48e7-a8fa-4a3e044cf3cd)

Verified Individual Joint Fundraising Transfer Memo page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/78a1a868-ca23-44cd-8e1f-9eebd5569fb6)

Create a new contact.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bc57b262-1dea-41ee-8d4c-79e99bb4ccb3)

Verify Individual Joint Fundraising Transfer Memo is listed in Transactions table as a "Child" to the original Joint Fundraising Transfer transaction.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bfca5e7e-bd3b-49c1-9b82-de6e67aab5fa)

QA Review Completed.   Moved to Stage Ready.
