### ISSUE TITLE
Allow user to enter Partnership Individual Joint Fundraising Transfer Memo on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#452]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **'Partnership Individual Joint Fundraising Transfer Memo‘** sub-transaction under "Partnership Receipt Joint Fundraising Transfer Memo" on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a Tier 3 transaction that will be associated with a Tier 2 transaction.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator
**And** I am editing a Partnership Receipt Joint Fundraising Transfer Memo transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction:

- Partnership Individual Joint Fundraising Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Required, includes LOOKUP)
--INDIVIDUAL
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (A/N-10, Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Required, system checked and read-only)
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.
-	**EMPLOYER** (Required if Aggregate > $200)
-	**OCCUPATION** (Required if Aggregate > $200)

# Additional information 
#
-	**PURPOSE OF RECEIPT** (Read-only, System-generated)
-- JF Memo: XX (Partnership Attribution), where XX is auto-populated with name of committee entered in **Tier 1** transaction JF_TRAN COL SEQ 8

-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & add memo _(Note that this is a transaction with a tier 3 transaction)._
-- Memo name list: Partnership Individual
- Edit

**And if** the Aggregate amount is >= $200.01 or negative,
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SA12.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- This is our first example of a "grandchild"/Tier 3 transaction that is associated with a memo transaction.
- The Committee name in the Purpose of Receipt comes from the Tier 1 transaction.

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=589486675)

 Wireframe 

![452 - Partnership Individual Joint Fundraising Memo.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/20ab20da-efbe-4d83-aecf-b7fd7d94936e)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by AureliaKhorsand** [comment]
@MitchellTCG can you update the wireframe CPD to match the AC?

**Comment by mary-tcg** [comment]
@AureliaKhorsand @GreggMoreland @MitchellTCG wire updated

**Comment by AureliaKhorsand** [comment]
Marked as high priority so that it is done _before_ other transactions of this kind (with Tier 3 transactions).

**Comment by toddlees** [comment]
@AureliaKhorsand @MitchellTCG based on our conversation with the dropdowns.  Shouldn't there just be a single item in the dropdown as it's full name (including the word memo at the end)?
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/d6fd1f6a-af68-43e8-ba58-6d3863e61e6a)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review on-hold until #449 ticket is fixed.  @MitchellTCG @mjtravers @toddlees

**Comment by AureliaKhorsand** [comment]
Decision requested from FEC on 5/1 to solve #449 blocked, and subsequently this ticket: 

1. (Low level of dev effort): If the committee name happens to be long and the text runs over 100 characters, the schema validation will just make sure that “JF Memo:” is present with text that follows, and accept that the text is truncated at the end. So, for example, the screenshot above would pass. Example: “JF Memo: Really Long Test Committee Name (Partnership attributions do not require…”
2. (High level of dev effort): If the system determines that the text will run over 100 characters, the system will truncate the committee name so that whatever is in parentheses will fit. Example: “JF Memo: Really Long Test Com… (Partnership attributions do not require itemization)”

**Currently awaiting response.**

**Comment by AureliaKhorsand** [comment]
Decision from FEC over email on 5/1: If the system determines that the text will run over 100 characters, the system will truncate the committee name so that whatever is in parentheses will fit. Example: “JF Memo: Really Long Test Com… (Partnership attributions do not require itemization)”

ACs describing this functionality will be included in all similar transaction tickets:

**If** the Purpose of Receipt surpasses the 100 character limit,
**then** the system will truncate the committee name (XX text) and end it with "..." so that everything in the parentheses can fit.

**Comment by mjtravers** [comment]
Patch for truncating long description passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Prerequisite a "Partnership Receipt Joint Fundraising Transfer Memo" transaction to be created, saved in the "Transactions" table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/af50e51d-e34d-4eb3-93b9-2a6bb2638dc6)

Select the + Save & add memo button. Verify dropdown list is displayed. Then select "Partnership Individual" from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e4246576-c76d-4b61-9df3-1e191f2c7319)

Verify "Partnership Individual Joint Fundraising Transfer Memo" page is displayed and contact type is "Individual" only

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1c597726-94b1-4a0a-87c1-50b4c6223826)

Verified text - PURPOSE OF RECEIPT (SYSTEM-GENERATED) "JF Memo: Joint Fundraising Transfer Partnership (Partnership Attribution)"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/374a10b6-e75f-466e-aa3b-c5a737ac7e4b)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1a5a3030-8c57-49f4-930b-c48148cef67e)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0a8bc230-b98a-4e97-96df-38be04a8a1ed)

Verified the "Transaction ID" and "Associated with" for tier 3 is displayed and referenced correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/75be68f6-5e88-42ef-9fec-783b141d43c0)

QA Review Completed. Moved to Stage Ready.
