### ISSUE TITLE
Allow user to enter Refund of Contribution to Other Political Committee on Schedule A (Group I)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#453]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Refund of Contribution to Other Political Committee”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a receipt 
**Then** Click(open) on the "Refunds" Accordion link  
**Then** I can enter a transaction with the type "Refund of Contribution to Other Political Committee"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required) _(Dev/QA Note: Aggregation Group is "LINE_16")_
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# ELECTION INFORMATION 
#
-	**ELECTION CODE** (Required)
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Convention, Runoff, Special, or Recount)

# Additional information 
#
-	**PURPOSE OF RECEIPT** (Optional, allow updates)
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save
- Edit

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file. _(Note that everything on Line 16 is itemized regardless of amount)._

 Dev Note 

**Note:** This is a name change to the transaction listed in the accordion/dropdown. Replace 'Refunds of Contributions to Registered Committees' with 'Refund of Contribution to Other Political Committee'

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#
- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=2083397974)

 Wireframe 

![453 - Refund of Contribution to Other Political Committee.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ab80459a-932d-43ac-bb0d-ab04079a185f)

### QA Notes ### 
 - Election Description should have "OPTIONAL IF PRIMARY OR GENERAL" in non-bold text next to the field name.
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand @MitchellTCG Updated wireframe

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg @GreggMoreland Design folks, can you remove the Donor Information fields from the wireframe, as they will pull from the Committee Name and ID fields as other SA transactions currently do? Also, please update the Election Description to read "(OPTIONAL IF PRIMARY OR GENERAL)" instead of just "(OPTIONAL)"

**Comment by mary-tcg** [comment]
@AureliaKhorsand @MitchellTCG @GreggMoreland wireframe fixed

**Comment by mary-tcg** [comment]
@AureliaKhorsand @MitchellTCG @GreggMoreland updated wireframe with above requests and new buttons

**Comment by AureliaKhorsand** [comment]
Marked as high priority to indicate it should be done before other similar transactions

**Comment by WiseQA** [comment]
@MitchellTCG wireframe needs updated please for QA review.   Title of transaction sentence case and PURPOSE OF RECEIPT needs updated from Contribution Purpose Description.   Thanks !

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers ticket On-Hold until #947 Election Type dropdown is fixed.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Refund of Contribution to Other Political Committee transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cf2b7602-8d43-4ba9-b151-70d47c3c0cbe)

Contact type is Committee Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dcfeaddc-6ee6-419e-a42d-4d523145be9f)

Verified Election Type and Election Year are required fields and ELECTION DESCRIPTION (OPTIONAL IF PRIMARY OR GENERAL) 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/184a8818-8928-4767-aa98-90e30fa927b2)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8b502949-9607-4175-96c2-1dee686393c1)

Verified PURPOSE OF RECEIPT (OPTIONAL) is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c2cf19ec-afb7-40c0-be6c-a3154a7c1751)

QA Review Completed. Moved to Stage Ready.
