### ISSUE TITLE
Allow user to enter Refund of Contribution to Unregistered Committee on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#454]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **” Refund of Contribution to Unregistered Committee”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a Receipt
**Then** Click(open) on the "Refunds" Accordion link  
**Then** I can enter a transaction with the type "Refund of Contribution to Unregistered Committee"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Organization Only
-	**Organization NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required)  _(Dev/QA Note: Aggregation Group is "LINE_16")_
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF RECEIPT** (Optional, allow edits)
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & add another 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file. _(Everything on Line 16 is itemized regardless of amount)._

 QA Note
- Validation should include a name change to the transaction listed in the accordian/dropdown. It should be 'Refund of Contribution to Unregistered Committee'
- Button labels are out of scope for this ticket, and will be addressed in #855. 

 Dev Note 

**Note:** This is a name change to the transaction listed in the accordian/dropdown. It should be a singular 'Refund', 'Contribution', and 'Committee'. The transaction name should be 'Refund of Contribution to Unregistered Committee'

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#
- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=261685728)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand  and @GreggMoreland 

If this is OBE please add an OBE label. I just want to make sure it wasn't close accidentally. (I've definitely done that before).

**Comment by GreggMoreland** [comment]
@MitchellTCG I'm not sure how I closed this. I will reopen it.

**Comment by toddlees** [comment]
passes cr moving to qa

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a receipt" then select Refund of Contribution to Unregistered Committee a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fb1b7a12-abc6-4e37-a3a5-0e090fcdc86d)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ef4aadee-76d2-453f-8c99-304d81228112)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/19e627d8-2cad-4b63-afaf-3b0f042b5f7f)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bd82a466-30dc-4084-ad72-b974e69b2ff9)

QA Review Completed. Moved to Stage Ready.

**Comment by AureliaKhorsand** [comment]
UPDATE: Itemization logic has been updated, moving back to In Progress. New AC: **And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file. _(Everything on Line 16 is itemized regardless of amount)._

**Comment by WiseQA** [comment]
QA review above verified Itemized and Unitemized.   Per BA's findings the transaction will be itemized upon saving and saved with it's own line item on the *.fec file. (Everything on Line 16 is itemized regardless of amount).

@toddlees @dheitzer moving out of Stage Ready and returning to In-Progress for fix.

**Comment by WiseQA** [comment]
QA review above verified Itemized and Unitemized.   Per BA's findings the transaction will be itemized upon saving and saved with it's own line item on the *.fec file. (Everything on Line 16 is itemized regardless of amount).

@toddlees @dheitzer moving out of Stage Ready and returning to In-Progress for fix.

**Comment by toddlees** [comment]
patch passes cr moving to qa

**Comment by WiseQA** [comment]
QA review **RETESTED** and verified when selecting "Add a receipt" then select Refund of Contribution to Unregistered Committee a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/70d24ec1-ed22-4cd3-97e5-a566fec72534)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/464c2272-a7ea-4471-8557-2ee204e42132)

Verified amount can be negative value.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/01fd4ca4-6a26-4dda-9f7b-bcac32015210)

FAILED

Following error is displayed when select "Save & view all transactions" button.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f9f36d08-a433-4515-bd2a-a2f90dda39ff)

Negative amount value cannot be saved.    @toddlees @dheitzer returning to in-progress for fix.

**Comment by dheitzer** [comment]
Error possibly because of an app/api mismatch due to the circleci outage.  Unable to reproduce - moving back to qa.

**Comment by WiseQA** [comment]
QA retested per findings from DEV on circileci outage.  QAreview verified the amount value can be a negative value.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f0e24115-5be7-419e-b220-e8399a3d3e0e)

Verified transaction is displayed in transactions table.    

QA Review Completed.   Moved to Stage Ready.
