### ISSUE TITLE
Allow user to enter Earmark Receipt on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#459]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Earmark Receipt”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

NOTE: This transaction requires a "child" (memo) transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Contributions From Individuals/Persons" Accordion link  
**Then** I can enter a transaction with the type "Earmark Receipt"
**Then** I will be required to enter the following information **for step one** (unless otherwise noted):

# Contributor 
#
-	**CONTRIBUTOR TYPE** 
**Note: this can be Individual only**
-	**LAST NAME** ( Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)
---

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)
-	**EMPLOYER** 
-	**OCCUPATION**

# Contribution 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**CONTRIBUTION AMOUNT** (Required) 
**Note:**CONTRIBUTION AMOUNT Can be a negative value
-	**CONTRIBUTION AGGREGATE** (Required, read-only) 

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, Optional)
Field description in API: RECEIPT DESCRIPTION
Data field: multi-line textbox that MUST SAY “Earmarked through XX” where XX is auto-populated with the name of the committee entered in filer_committee_id_number
-	**NOTE OR MEMO TEXT** (Optional)

**Then** I will be able to:

- Cancel
- Edit fields (cannot edit fields without saving this function not tested in #459 but will test in #460)

(Note: user will not be able to save at this point. They must save with Earmark Memo, which requires ticket #460)

 Dev Task 

- [x] Update Earmark Receipt spec with updates in yellow. See [Spec Updates spreadsheet](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1313999683).

![Custom Size – 51.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a64389d0-06d7-4d01-817c-1f9c138cd010)
![Group A - Earmark Receipt.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/7add52dc-5588-401c-bcb7-dcc9c38d192b)

### QA Notes ### 
 
- Ticket #459 revolves around Step #1 of the Earmark process
- Step #1 of the Earmark process will NOT be able to "Save & view all transactions"
- Step #2 Enter fields in Earmark Transaction the select Step #2, second screen of Earmark will appear #460.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/07dfba28-e077-4eef-bce8-752320e55ac7)

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
![Screenshot (10).png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/3ef057b4-7c9c-4406-b1a3-96e32a46392b)![Screenshot (11).png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/b361e05a-bf71-43a7-9c06-7a9495aef45d)

**Comment by AureliaKhorsand** [comment]
@mary-tcg @MitchellTCG this looks great from a requirements perspective. Only suggestion is to remove the word "special" above the button to add an Earmark Memo.

**Comment by mjtravers** [comment]
Passes CR, sending to QA

**Comment by WiseQA** [comment]
QA Review verified selecting "Step One" "Add receipt and contributor information proceeded to blank Earmark Receipt page to enter information.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/056226f2-1a79-418d-bf76-9ad0f292d20c)
***
QA Review verified fields for Earmark Receipt are entered.   Note cannot save this receipt to verify fields are valid.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5ee5f5f4-6741-46da-8f20-0876a18e0a17)
___
Required fields tested - Date Received and Contribution Amount not displaying "Required Field"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f2e8ea23-ac4b-470f-b699-322f4ac92200)

**@toddlees @mjtravers @MitchellTCG Returned to In-Progress for "Required Field" labels for Date Received and Contribution Amount not populating**

**Comment by MitchellTCG** [comment]
@AureliaKhorsand Please Test this

**Comment by mjtravers** [comment]
Passed CR but holding from QA until #552 is merged. See comment at end of #460 ticket

**Comment by mjtravers** [comment]
#552 is in QA so sending this ticket to QA, too.

**Comment by mjtravers** [comment]
Passes CR, sending to QA

**Comment by WiseQA** [comment]
QA Review verified selecting "Step One" "Add receipt and contributor information proceeded to blank Earmark Receipt page to enter information.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b81009a1-bb92-47e5-93c9-40ee9ac5fa06)

Verify Earmark Receipt page is displayed.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9c7924db-8f2d-48ac-a600-bc05015a72cd)

Verify required fields are filled in and the receipt cannot be saved.  Proceed to "Step 2"  #460.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a7d0450b-ccb9-402e-b809-760b42fcce50)

QA Review Completed.   Moved to Stage Ready.
