### ISSUE TITLE
Allow user to enter Earmark Memo on Schedule A (Group G)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#460]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Earmark Memo”** sub-transaction under **”Earmark Receipt”**  on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Earmark Receipt transaction on an open report
**Then**  I will **be required** to complete step two to add an Earmark Memo transaction
**And** I will be required to enter the following information (unless otherwise noted):

# Conduit 
#
-	**ENTITY TYPE**
Field description in API: ENTITY TYPE
Data field: Dropdown
Dropdown options: Individual, Committee 
*Note - please default to COMMITTEE
---
_if CONTRIBUTOR TYPE = Committee_
-	**CONDUIT NAME** (A/N-200, Required)
Field description in API: CONTRIBUTOR ORGANIZATION
Data field: textbox
-	**CONDUIT FEC ID** (A/N-9, Required)
Field description in API: DONOR COMMITTEE FEC ID
Data field: textbox
With the ID in the following format: "CXXXXXXXX" where X is a numeric value _(C, then 8 numbers)_
**FEC ID IS A STOP-GAP UNTIL THE LOOKUP IS IN PLACE**
---
_if CONTRIBUTOR TYPE = Individual_
-	**LAST NAME** (A/N-30, Required)
Field description in API: CONTRIBUTOR LAST NAME
Data field: textbox
-	**FIRST NAME** (A/N-20, Required)
Field description in API: CONTRIBUTOR FIRST NAME
Data field: textbox
-	**MIDDLE NAME** (A/N-20, Optional)
Field description in API: CONTRIBUTOR MIDDLE NAME
Data field: textbox
-	**PREFIX** (A/N-10, Optional)
Field description in API: CONTRIBUTOR PREFIX
Data field: textbox
-	**SUFFIX** (A/N-10, Optional)
Field description in API: CONTRIBUTOR SUFFIX
Data field: textbox
-	**EMPLOYER** (A/N-38, **Required regardless of aggregate**)
Field description in API: CONTRIBUTOR EMPLOYER
Data field: textbox
-	**OCCUPATION** (A/N-38, **Required regardless of aggregate**)
Field description in API: CONTRIBUTOR OCCUPATION
Data field: textbox
<br>
---

# Address 
#
-	**STREET ADDRESS** (A/N-34, Required)
Field description in API: CONTRIBUTOR STREET 1
Data field: textbox
-	**APARTMENT, SUITE, ETC.** (A/N-34, Optional)
Field description in API: CONTRIBUTOR STREET 2
Data field: textbox
-	**CITY** (A/N-30, Required)
Field description in API: CONTRIBUTOR CITY
Data field: textbox
-	**STATE/PROVINCE** (ALPHA-2, Required)
Field description in API: CONTRIBUTOR STATE
Data field: Dropdown
          Dropdown options: States without military
          https://docs.google.com/spreadsheets/d/17YmnaZgqvFOUyv4-Qknd8ikHe8o9LoDb/edit#gid=494776297
-	**ZIP/POSTAL CODE** (A/N-9, Required)
Field description in API: CONTRIBUTOR ZIP
Data field: textbox
<br>

# Contribution 
#
-	**DATE RECEIVED** (NUM-8…YYYYMMDD, Required)
Field description in API: CONTRIBUTION DATE
Data field: Date picker 
-	**MEMO ITEM** (A/N-1, **Required**)
Field description in API: MEMO CODE
Data field: Checkbox
This will be automatically checked and the user CANNOT change it. 
-	**AMOUNT** (AMT-12, Required, **read-only**)
Field description in API: CONTRIBUTION AMOUNT
**This should automatically be the same as the Earmark Receipt (parent) and read-only**
Data field: textbox
**Note"**CONTRIBUTION AMOUNT Can be a negative value
-	**AGGREGATE** (AMT-12, Required, read-only, can be negative)
Field description in API: CONTRIBUTION AGGREGATE
Data field: textbox 

<br>

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** ~(Read-only)~ (SYSTEM-GENERATED)
Field description in API: RECEIPT DESCRIPTION
Data field: multi-line textbox that must read "Total earmarked through conduit."
-	**NOTE OR MEMO TEXT** (A/N-100, Optional)
Field description in API: MEMO TEXT/DESCRIPTION
Data field: multi-line textbox

**Then** I will be able to:
-Toggle between step 1 and 2 and edit fields as needed
- Save & view all transactions [will go to "Manage your transactions" Table]
- Cancel (Note: This cancels _both_ transactions)

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

- [x] Update Earmark Memo spec with updates in yellow. See [Spec Updates spreadsheet](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=720066559).
- [x] Use django transaction for save so we can rollback a partial success https://docs.djangoproject.com/en/4.1/topics/db/transactions/

![Group A - Earmark Memo.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/05e7046b-ab44-4148-8144-b3812895dfb2)

### QA Notes ### 
 
- Ticket #459 MUST be done first to validate CONTRIBUTION PURPOSE DESCRIPTION (SYSTEM-GENERATED) field is populated
- Ticket #460 revolves around Step #2 (Earmark Memo) of the Earmark Receipt workflow
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/22e246b6-f290-42b3-bd7e-9b30f02cb8b7)
-  Will be able to "Save & view all transactions"

**Fields with changes:  (Tested in #570 also)
Contributor > Conduit (Individual / Committee Only)
Contribution Amount > Amount
Contribution Aggregate > Aggregate
Employer Field (Not Required > Employer Field (Required)
Occupation Field (Not Required) > Occupation Field (Required)**

Added (10/28/2022) for testing purposes:
Changed  "Contributor Committee" to "Conduit Name"
Changed "Contributor FEC ID" to "Conduit FEC ID"

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
![Screenshot (12).png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/99cd2ee9-20bb-49b9-9e85-e56d9a6755f5)![Screenshot (13).png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/19e3967c-a2a9-41d1-94dd-c496c4398a8d)

**Comment by AureliaKhorsand** [comment]
@mary-tcg @MitchellTCG only update to make is that the contributor entity can be an Individual or Committee, so the Contributor Type field should be a dropdown.

**Comment by toddlees** [comment]
@MitchellTCG Should there be an entity type selector in this form?  the specs say it can be an Individual or Committee

**Comment by AureliaKhorsand** [comment]
@toddlees yes, per the acceptance criteria in the ticket, there needs to be an entity type selector on the form for Individual or Committee, and it should default to Committee.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand Please Test this

**Comment by mjtravers** [comment]
@AureliaKhorsand For the CPD of the earmark receipt: what should be in XX of the read-only text if the earmark memo entity_type is an Individual and not a Committee?

**Comment by mjtravers** [comment]
@dheitzer During ad hoc testing of #459 and #460 on DEV server, I found that sending contact objects that have not been updated with the changes made to the in the transaction form are failing validation when an existing contact is used that has invalid data. This scenario is possible when pulling committee contacts from the FEC api. Let's fix this issue in ticket #552 when you refactor the contact update code out of the API and into the front-end. Will hold this ticket from QA until that fix is made and pushed in #552

**Comment by mjtravers** [comment]
#552 is in QA so sending this ticket to QA, too.

**Comment by mjtravers** [comment]
Passes CR, sending to QA

**Comment by WiseQA** [comment]
@toddlees @MitchellTCG - After discussion retuned to QA - #459 and #460 updated QA notes denoting how to test these tickets.  

Error below is OBE:

QA review the CONTRIBUTION PURPOSE DESCRIPTION (SYSTEM-GENERATED) field needs "dummy" text entered in field.

**Comment by WiseQA** [comment]
QA review verified once Earmark Receipt filled in then proceed to "Step 2"  #459 the Earmark Memo page is displayed.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8d0fe097-48e3-4b0b-928d-d4cbbb39ffed)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2bde9131-1596-4186-b45c-ced54efe4b60)

Verify Amount, Aggregate, and Contribution Purpose Description (Optional) fields are read only (grayed out).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/aab151d5-c41c-47c5-93b5-6e8373276a19)

Verified select "Save & view all transactions" the "Confirm" popup window is displayed then select "Continue"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0e92641a-0c9a-47c6-83b1-17d97abcae53)

Verify Earmark Receipt and Earmark memo are displayed in the Transactions table.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dec758df-b472-4fe7-af2c-02066b5034b8)

QA Review Completed.  Moved to Stage Ready.
