### ISSUE TITLE
Allow user to enter Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account on Schedule A (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#463]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "parent" transaction that will typically have associated sub-transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Transfers" Accordion link  
**Then** I can enter a transaction with the type "Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Committee only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:**AMOUNT can be a negative value
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Recount Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_RECOUNT_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system-generated)
Data field: multi-line textbox that MUST SAY "Recount/Legal Proceedings Account Transfer of JF Proceeds"
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & view all transactions
- Save & add another
- Save & add a... _(Note these will be dead links for this ticket)_
--Individual National Party Recount/Legal Proceedings Account JF Transfer Memo
--PAC National Party Recount/Legal Proceedings Account JF Transfer Memo
--Tribal National Party Recount/Legal Proceedings Account JF Transfer Memo
--Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See Joint Fundraising Transfer - National Party Recount Account spec [here](https://fecgov.github.io/fecfile-validate/JF_TRAN_NP_RECNT_ACC_spec.html). 
#

### QA Notes ### 
  Dev Notes 
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg can we get a wireframe for this transaction?

**Comment by Elaine-Krauss-TCG** [comment]
Transaction implemented
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/10fc58b4-33bc-4380-b302-aa11cbe5b13d)

Unitemized when under $200
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/574e6f16-e01c-41d0-b1fb-861a316ff33f)

**Comment by Elaine-Krauss-TCG** [comment]
Sub transactions are listed correctly
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/949f5ac8-4f87-4f21-87a4-c18cf107b6ad)

**edit:** I completely missed that the Tribal sub transaction was listed twice.  That has been fixed.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/3cad6ae1-a00c-487b-abf7-276ddc5eebf1)

**Comment by Elaine-Krauss-TCG** [comment]
New transaction added to E2E coverage
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/83994d15-ab5a-43b2-886d-a6824333e515)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers naming of this transaction needs to match the ticket name in both accordion dropdown and Title of Transaction page.

Correct Naming is: 
Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account 

Accordion dropdown needs changed to naming of ticket (see below what is being displayed)
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8a2b0f92-9be2-480b-a1f7-a76fc60b31de)

Title on Transaction Page needs changed to naming of ticket (see below what is being displayed)
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3bdaca8b-74da-4411-a6e2-3c7590c1147e)

Returned to in-progress for these fixes.

**Comment by mjtravers** [comment]
Fix made to accordion and title. See screenshot below. Passes CR. Sending to QA.
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/8c85c75d-f2a4-4ca5-8803-1014c2d5f2de)

**Comment by WiseQA** [comment]
QA review verified Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/65671880-6566-40b1-b8e4-a2c509a9e00c)

Verify Confirm popup window is displayed - creating a new committee contact.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/26f522b7-0ed5-4776-af42-7b7e662c80b2)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e222eee1-a6d9-4e6d-9b85-296407f331f4)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d0275d76-3a85-4cd9-9a13-0de4ec52cf33)

Verified “Cancel”, “Save & add another”, “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/410caec2-dc47-4d6c-84f8-1bb54a26d3bb)

QA Review Completed.   Moved to Stage Ready.
