### ISSUE TITLE
Allow user to enter Individual National Party Recount/Legal Proceedings Account JF Transfer Memo on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#464]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **” Individual National Party Recount/Legal Proceedings Account JF Transfer Memo”** sub-transaction under a **”Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account”**  on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account on an open report  
**Then** I will have the option to enter the following sub-transaction: 
- Individual National Party Recount/Legal Proceedings Account JF Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Required)
-- Individual Only

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)
-	**EMPLOYER** (Required if Aggregate > $200)
-	**OCCUPATION** (Required if Aggregate > $200)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Read-Only)
This will be automatically checked and the user CANNOT change it.
-	**AMOUNT** (Required)
**Note:**AMOUNT Can be a negative value

-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Recount Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_RECOUNT_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system-generated)
textbox that MUST SAY “Recount/Legal Proceedings Account JF Memo: XX” where XX is auto-populated with the name of the committee entered in parent transaction JF_TRAN COL SEQ 8
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & add another “Individual National Party Recount/Legal Proceedings Account JF Transfer Memo" associated to the same "parent"
- Back to Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See Individual National Party Recount Account JF Transfer Memo spec [here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=884905277). 
#

### QA Notes ### 
  Dev Notes 
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg can we get a wireframe for this transaction please?

**Comment by Elaine-Krauss-TCG** [comment]
Transaction implemented and creating as expected
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/e530df9c-10a0-4a3b-bc69-1f9dba5d9b3f)

**Comment by Elaine-Krauss-TCG** [comment]
Transaction implemented and creating as expected
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/e530df9c-10a0-4a3b-bc69-1f9dba5d9b3f)

**Comment by Elaine-Krauss-TCG** [comment]
Added child transaction to E2E coverage, and it's passing
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/d199c1f3-2974-4474-9ff9-bcdc3e69393f)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers naming of this transaction needs to match the ticket name in both accordion dropdown and Title of Transaction memo page.

Correct Naming is: 
Individual National Party Recount/Legal Proceedings Account JF Transfer Memo

Accordion dropdown needs changed to naming of ticket (see below what is being displayed)  Ticket #463
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2ffb03f4-f8ba-4221-9e6a-decb3c69c5d4)

Title on Transaction Memo Page needs changed to naming of ticket 

Returned to in-progress for these fixes.

**Comment by mjtravers** [comment]
This is a child transaction of the Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account so will not have an entry in the accordion. It is accessed through the save button on the Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account screen. See screenshot below:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/69143411-d85e-4967-80d3-974f2a0e01ec)

Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Individual National Party Recount/Legal Proceedings Account JF Transfer Memo transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/907938b2-5027-4776-9136-d0c4638bfc48)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8a15b9f9-c04e-4b0b-a6ab-3710d763bc9d)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cf910470-0b07-413e-bcef-e7979c2c45ca)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f23a8299-1029-41e9-be16-22e844180ac9)

Verified “Back to Joint Fundraising Transfer” and “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3b0acb2f-ab73-462d-b386-c35768df9f4d)

QA Review Completed.   Moved to Stage Ready.
