### ISSUE TITLE
Allow user to enter PAC National Party Recount/Legal Proceedings Account JF Transfer Memo on Schedule A (Group F)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#465]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”PAC National Party Recount/Legal Proceedings Account JF Transfer Memo”** sub-transaction under a **”Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account”**  on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account on an open report  
**Then** I will have the option to enter the following sub-transaction: 
- PAC National Party Recount/Legal Proceedings Account JF Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT** (Read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
This will be automatically checked and the user CANNOT change it.
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Recount Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_RECOUNT_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system-generated)
textbox that MUST SAY “Recount/Legal Proceedings Account JF Memo: XX” where XX is auto-populated with the name of the committee entered in parent transaction JF_TRAN COL SEQ 8
-	**NOTE OR MEMO TEXT** ( Optional)

---
**Then** I will be able to:
- Cancel
- Save & add another “PAC National Party Recount/Legal Proceedings  Account JF Transfer Memo" associated to the same "parent"
- Back to Joint Fundraising Transfer - National Party Recount/Legal Proceedings  Account
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See Individual National Party Recount Account JF Transfer Memo spec [here](https://fecgov.github.io/fecfile-validate/JF_TRAN_NP_RECNT_PAC_MEMO_spec.html). 
#

### QA Notes ### 
  Dev Note 
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg ready for wireframe

**Comment by Elaine-Krauss-TCG** [comment]
Transaction implemented and creating as expected
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/e530df9c-10a0-4a3b-bc69-1f9dba5d9b3f)

**Comment by Elaine-Krauss-TCG** [comment]
Added child transaction to E2E coverage, and it's passing
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/d199c1f3-2974-4474-9ff9-bcdc3e69393f)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
@WiseQA While doing some testing it was found that the contribution purpose description is incorrect for this ticket. It was coded to be "Pres. Nominating Convention Account JF Memo: XXX" while it should be "Recount/Legal Proceedings Account JF Memo: XXX". This will need to corrected on STAGE.

**Comment by toddlees** [comment]
@mjtravers @WiseQA I found that I broke this while implementing another ticket.  I have a patch up ready to be merged into stage here https://github.com/fecgov/fecfile-web-app/pull/760

**Comment by WiseQA** [comment]
@toddlees @mjtravers Please let us know when patch has been pushed to Stage.   Good catch Todd  thanks !

**Comment by mjtravers** [comment]
@WiseQA The patch has been pushed to STAGE and is ready for testing.

**Comment by WiseQA** [comment]
@mjtravers naming of this transaction needs to match the ticket name in both accordion dropdown and Title of Transaction memo page.

Correct Naming is: 
PAC National Party Recount/Legal Proceedings Account JF Transfer Memo

Accordion dropdown needs changed to naming of ticket (see below what is being displayed)  Ticket #463

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3267393c-ece2-47f5-ab5b-f0407d5c3381)

Title on Transaction Memo Page needs changed to naming of ticket 

Returned to in-progress for these fixes.



Returned to in-progress for these fixes.

**Comment by mjtravers** [comment]
This is a child transaction of the Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account so will not have an entry in the accordion. It is accessed through the save button on the Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account screen. See screenshot below:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/69143411-d85e-4967-80d3-974f2a0e01ec)

Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified PAC National Party Recount/Legal Proceedings Account JF Transfer Memo transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a2cd09a9-fcfd-4f2b-8174-445d9bdf81f9)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7bb86b4d-23b5-4d8d-bf2c-f85ec283879d)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fb82286c-1c14-429e-a4d3-9b4c0b30bdf2)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/072482aa-3cc9-478e-8148-10bb803916c6)

Verified “Back to Joint Fundraising Transfer” and “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3fae4af1-79f6-4753-9c79-bc94e6fb3f67)

QA Review Completed.   Moved to Stage Ready.
