### ISSUE TITLE
Allow user to enter Tribal National Party Recount/Legal Proceedings Account JF Transfer Memo on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#466]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Tribal National Party Recount/Legal Proceedings Account JF Transfer Memo”** sub-transaction under a **”Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account”**  on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account on an open report  
**Then** I will have the option to enter the following sub-transaction: 
- Tribal National Party Recount/Legal Proceedings Account JF Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Organization Only

-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Read only, Optional)
This will be automatically checked and the user CANNOT change it.
-	**AMOUNT** ( Required) 
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** ( Required) 
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Recount Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_RECOUNT_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system-generated)
Textbox that MUST SAY “Recount/Legal Proceedings Account JF Memo: XX” where XX is auto-populated with the name of the committee entered in parent transaction JF_TRAN COL SEQ 8
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & add another “Tribal National Party Recount/Legal Proceedings  Account JF Transfer Memo " associated to the same "parent"
- Back to Joint Fundraising Transfer - National Party/Legal Proceedings  Recount Account
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See Tribal National Party Recount Account JF Transfer Memo spec [here](https://fecgov.github.io/fecfile-validate/JF_TRAN_NP_RECNT_TRIB_MEMO_spec.html). 
#

### QA Notes ### 
  Dev Note 
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg ready for wireframe

**Comment by Elaine-Krauss-TCG** [comment]
Transaction implemented and creating as expected
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/e530df9c-10a0-4a3b-bc69-1f9dba5d9b3f)

**Comment by Elaine-Krauss-TCG** [comment]
Added child transaction to E2E coverage, and it's passing
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/d199c1f3-2974-4474-9ff9-bcdc3e69393f)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers naming of this transaction needs to match the ticket name in both accordion dropdown and Title of Transaction memo page.

Correct Naming is: 
Tribal National Party Recount/Legal Proceedings Account JF Transfer Memo

Accordion dropdown needs changed to naming of ticket (see below what is being displayed)  Ticket #463
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2803d1f4-d60a-470b-92f3-4a63d54b67e7)

Title on Transaction Memo Page needs changed to naming of ticket (see below what is being displayed)

Returned to In-progress for these fixes.

**Comment by mjtravers** [comment]
This is a child transaction of the Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account so will not have an entry in the accordion. It is accessed through the save button on the Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account screen. See screenshot below:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/69143411-d85e-4967-80d3-974f2a0e01ec)

Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Tribal National Party Recount/Legal Proceedings Account JF Transfer Memo transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d3dac2a8-56e9-406b-8876-e2106765934a)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/05145bac-5b59-4aa7-ab61-847ebf17ecae)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0aeb6030-af19-433f-b6ba-77c1c034c4c4)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/29bc957b-6f1d-4d7c-9d2b-ca0cea455b1c)

Verified “Back to Joint Fundraising Transfer” and “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/068003fb-69f3-4404-8220-1ac01f8ad1f8)

QA Review Completed.   Moved to Stage Ready.
