### ISSUE TITLE
Allow user to enter Partnership Individual Recount/Legal Proceedings Account JF Transfer Memo on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#469]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Partnership Individual Recount/Legal Proceedings Account JF Transfer Memo”** sub-transaction under a **”Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo”**  on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a Tier 3 transaction that will be associated with a Tier 2 AND Tier 1 transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo on an open report  
**Then** I will have the option to enter the following sub-transaction: 

- Partnership Individual Recount/Legal Proceedings Account JF Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, includes LOOKUP)
-- Individual 
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)
-	**EMPLOYER** (Required if Aggregate > $200)
-	**OCCUPATION** (Required if Aggregate > $200)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Required, system checked and read-only)
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required) 
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Recount Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_RECOUNT_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF RECEIPT** (Read-only, system generated)
-- Recount/Legal Proceedings Account JF Memo: XX (Partnership Attribution), where XX is auto-populated with name of committee entered in **Tier 1** transaction JF_TRAN COL SEQ 8
**-- Note: If the Purpose of Receipt surpasses the 100 character limit, then the system will truncate the committee name (XX text) and end it with "..." so that everything in the parentheses can fit.**
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & add memo _(Note that this is a tier 3 transaction)_
-- Group Name: Partnership Receipt Recount/Legal Proceedings Account JF Transfer; Memo name list: Partnership Individual
- Save
- Edit as needed

**And if** the Aggregate amount is >= $200.01 or negative,
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SA17.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note 

#468 passed as first Tier 3 tested and passed for JF Transfer Memo's.  Tickets with JF Transfer Memo's Tier 3 should be passing from this point forward.

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1257992500)

 Wireframe 

![469 - Partnership Individual Recount-Legal Proceedings Account JF Transfer Memo.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f6fe96e6-7cd1-4d57-8150-8cac9ff546c2)

# Tier 3 Dropdown with ONE option
#
![469 - One Option.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/da9328c6-0580-4f6c-93f4-b92564a46f68)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
updated

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Updated again (Looks the same but two wires. 1 with transaction and 1 with dropdown)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers per review, returned ticket to in-progress for fix of error denoted during testing and the "Associated with"  not displaying in the transactions table.

**Comment by mjtravers** [comment]
Fix for missing Associated With ids on transaction list tables made. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Retested this ticket after fixes. This Tier 3 transaction is live and developed.

Prerequisite a "Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account"  "Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo" transaction to be created, saved in the "Transactions" table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b9653c29-344d-45af-b91d-8e243b42835f)

Verify Tier 3 link for "Partnership Individual" under "Save & Add Memo" selectable.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a5132334-0922-4527-9680-ef8d60bdf2ab)

Verify Tier 3 memo is created "Partnership Individual Recount/Legal Proceedings Account JF Transfer Memo" 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6c8f6f66-5bf6-45b2-a7bf-4fab7f435f5d)

Verified the "Transaction ID" and "Associated with" for tier 3 is displayed and referenced correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/024e3596-e364-4940-804c-32b37f567fb8)

QA Review Completed. Fixes have been implemented and Pass. Moved to Stage Ready.
