### ISSUE TITLE
Automated front-end tests needs back-end support

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-web-app#47]
The Cypress e2e tests need to be able to spin up a baseline test database each time it is run. The database should spin up a baseline Django database and then use Django fixtures to update the database schema to the version being tested.

***User Story***

  As a developer/QA, 

  I would like to have automated end to end testing that exercises full workflows that our end users will run

  so that we can catch and regressions occurring in integration

***Acceptance Criteria***

*   e2e tests should start a working database populated with enough data to run tests
*   e2e job should be configured so that Cypress tests can login and run the existing e2e tests
*   All e2e tests should be passing.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1347](https://fecgov.atlassian.net/browse/FECFILE-1347)

**Comment by mjtravers** [comment]
@albertcrowley Do you envision this database/endpoint being a custom Docker image with a test database and a snapshot of the backend code running? So the bulk of this ticket would be creating a Dockerfile and figuring out an automated way of keeping it up to date?

**Comment by mjtravers** [comment]
This ticket is OBE. e2e tests are too long running to be practical in CircleCI. Will run e2e tests in another automated fashion TBD

**Comment by mjtravers** [comment]
@albertcrowley On second thought, because of the need for an isolated database that needs to be reinitialized before running tests, I'd like to look into if CircleCI can be used ad hoc and/or on a time interval basis. Re-opening ticket.

**Comment by WiseQA** [comment]
QA Review of the following:
- e2e tests should start a working database populated with enough data to run tests
- e2e job should be configured so that Cypress tests can login and run the existing e2e tests
- All e2e tests should be passing.
Automated testing working and passing.
QA review completed and passed.  Moved to Stage Ready
