### ISSUE TITLE
508 Compliance: Add Google Lighthouse to CI Pipeline (RESEARCH)

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#470]
Business Reason

As a the product owner, I would like 508 Compliance scan run along with other CI Pipeline processes to make sure we are always 508 compliant

Task

### QA Notes ###
- [x] Review he Google Lighthouse CI works. 
        General overview: https://developer.chrome.com/docs/lighthouse/overview/
        More info: https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md
- [ ] Create a checklist of task in this ticket
- [ ] Install and intgrate Lighthouse
- [ ] Create QA Notes to test this or relay to the team how the Devs will test this 
- [ ] Create a script for demoing this to Stakeholders

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1089](https://fecgov.atlassian.net/browse/FECFILE-1089)

**Comment by dheitzer** [comment]
Analyzed two approaches to lighthouse accessibility testing that I think that the dev team should discuss:

1. Using lighthouse to analyze our static .html templates using lighthouse-ci (as linked to above).
2. Integration of lighthouse analysis into Cypress tests (allowing for analysis of dynamic html).

Both may have pros/cons worth discussing.

**Comment by mjtravers** [comment]
@dheitzer I really like the option of running Lighthouse in conjunction with the Cypress e2e tests for a number of reasons. Will put that option in the ticket for actually doing the work.
