### ISSUE TITLE
Create Contact Lookup Prototype for Committee (existing and FEC lookup)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#471]
***Task:*** Create the Contact Lookup prototype for use in FECFile online for Contact Management and Transaction entries.

Acceptance Criteria:

1\. User will be able to use the Lookup feature to find and select a Committee from their Contact Management OR registered with FEC by ***name or ID*** 

  2\. Results will show up to ***5*** existing Committee contacts from the Committee Account, and specify "In Contacts"

  3\. Results will show up to ***5*** Committee contacts from the FEC Lookup.

  2\. The Lookup results will show the committee name and committee ID.

Technical Notes

_Old note:_ Robert has a fancy autocomplete widget that is being used on the FEC site. Obtain the code for the widget and modify accordingly to use it in the Angular framework.

### QA Notes ###

Prerequisites:
1. Enter a new committee contact with name "Test Biden Committee Name"
2. Enter a new committee contact with name "Test Committee Name"

Steps for testing:
1. Navigate to contacts and in the new search box next to the "delete" button search "biden"
2. Verify that "Test Biden Committee Name" shows up in **Select an existing committee account:** and "Test Committee Name" does not appear.  
(Note:  Verify lookup results shows the committee name and committee ID)
3. Also verify that 5 additional BIDEN committees are populated in **Create a new contact from list of registered committees:**   
4. Verify Committee id's are searchable. Type in "C00703975" and verify that the "Biden for President" PAC is returned

Wireframe:
![ad147da5-ea89-4294-b08c-6f7895701637.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/3f1f8ae2-adfa-484f-86ba-45fe7ab67cb7)

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1088](https://fecgov.atlassian.net/browse/FECFILE-1088)

**Comment by AureliaKhorsand** [comment]
Dropdown example from fec.gov that we are basing design off of: 
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/e9845eff-168e-48c5-bb30-aa83b7f8a593)

**Comment by WiseQA** [comment]
QA Review verified lookup for Committee prototype as denoted in QA notes.  Verified lookup showed Committee Name and Committee ID in parenthesis.  

1.  Verified that "Test Biden Committee Name" shows up in Select an existing committee account: and "Test Committee Name" does not appear.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/23baef10-fc9b-46db-949a-3378e76f34c3)


2.  Verified that 5 additional BIDEN committees are populated in Create a new contact from list of registered committees:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/11c6f3ec-5c79-4f44-bff7-6563ebc85395)


3.  Verified Committee id's are searchable. Type in "C00703975" and verify that the "Biden for President" PAC is returned
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a73c632d-090e-4fd7-9c65-f0492ad47fee)

QA Review Completed.    Moved to Stage Ready
