### ISSUE TITLE
System to calculate Contribution Aggregate for "Offsets for Operating Expenditures" (Group B)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#473]
Business Reason

The Contribution Aggregate field must display the total of the entity's contributions from the calendar year of the report. This is necessary to track contribution limits as well as itemization logic. This amount will be a _rolling total_.

Acceptance Criteria

For the following transactions:

Offsets for Operating Expenditures (Group B)

CONTRIBUTION AGGREGATE field must meet the following criteria:

*   AMT-12, Required, Read-Only
*   Can be negative
*   Amount Displayed will be the total of contributions that are: 
      *   From the person (ENTITY)
    *   within Aggregation Group of "LINE_15"
    *   _from_ January 1 of report year _to_ the transaction Contribution Date* of the transaction.
    *   *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

AND when saving a transaction, any subsequent transactions for the same entity will update. (E.g., if a previous transaction receipt amount is _changed_, it will affect the future aggregations).

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1086](https://fecgov.atlassian.net/browse/FECFILE-1086)

**Comment by Elaine-Krauss-TCG** [comment]
This ticket is satisfied by existing code.

You can create an Offset to Operating Expenditures receipt with a date of 10/10/2022 and an amount of $100

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/27e33a91-be7d-43a8-9311-7876d57a3923)

Creating a second receipt with a future date in the same year includes the amount from the prior receipt in the aggregate.

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/e47e4865-0b43-435c-9929-6dce30b90e18)

Creating a third transaction with a date between the two previously created receipts works as expected

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/8b9a6c5f-fcb8-456a-98f3-03ff4c4f1cd1)

And the aggregate for the receipt dated for the 12th is updated in turn

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/3688c1e3-d140-4ff2-ac00-6470db52d61e)

**Comment by mjtravers** [comment]
Code reviewed in previous ticket and branch. No code changes to review for this ticket. Sending to QA

**Comment by mjtravers** [comment]
Pulling back to In Progress to add more unit test code coverage.

**Comment by MitchellTCG** [comment]
@wise @mjtravers 
This functionality was completed in Code branch #472

When the new aggregation groups were create, Offsets were done at the same time.

Still new unit testing.

**Comment by mjtravers** [comment]
New unit testing has been implemented. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA adhoc testing completed on this ticket.  No test script written - e2e testing to satisfy this ticket.

Per DEV This functionality was completed in Code branch #472 when the new aggregation groups were created, Offsets were done at the same time.

QA Review Completed.   Moved to Stage Ready.
