### ISSUE TITLE
Allow user to enter Partnership Receipt on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#477]
Business Reason

As a Committee Administrator, I will be able to enter a ***”Partnership Receipt”*** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

***NOTE:*** This is a "parent" transaction that will have an associated child ‘Memo’ transaction.

DEV NOTES

Per the team discussion, we want to code up the change in the parent CPD when children are added to the parent retroactively by adding a flag the the child create call back to the API that tell the backend to also update the parent transaction in a database transaction atomic call. We want this so we have the atomic call but also explicitly tell the back end to update the parent transaction because, by default, it won't.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

 ***Then*** Add a new transaction

 ***Then*** Click(open) on the "Contributions from Individuals/Persons" Accordion link

 ***Then*** I can enter a transaction with the type "Partnership Receipt"

 ***Then*** I will be required to enter the following information (unless otherwise noted):

—

1.  Contact

      #

*   CONTACT TYPE (Read-only, ***includes Lookup***)
      *   Organization
*   ORGANIZATION NAME (Required)

1.  Address

      #

*   STREET ADDRESS (Required)
*   APARTMENT, SUITE, ETC. (Optional)
*   CITY (Required)
*   STATE/PROVINCE (Required)
*   ZIP/POSTAL CODE (Required)

1.  Contribution

      #

*   DATE RECEIVED (Required)
*   MEMO ITEM (Optional)
*   AMOUNT (Required)
      *   Note: AMOUNT can contain a negative value.
*   AGGREGATE (Required)
      *   Amount Displayed will be the total of contributions that are:
            *   From the person (CONTACT)
    *   within Aggregation Group of "GENERAL"
            *   _from_ January 1 of report year _to_ the Contribution Date* of the transaction.
        *   *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

1.  Additional information

      #

*   CONTRIBUTION PURPOSE DESCRIPTION (Required, System generated)
      *   If a Partnership Receipt has no associated Partnership memos, the Contribution Purpose Description should read: "Partnership attributions do not require itemization"
    *   If a Partnership Receipt has associated Partnership memos, the Contribution Purpose Description should read: "See Partnership Attribution(s) below".
*   NOTE OR MEMO TEXT (Optional)

—

 ***Then*** I will be able to:

*   Cancel
*   Add “Partnership Memo"
*   Save & view all transactions [will go to "Manage your transactions" Table]
*   Edit as needed

***And if*** the Aggregate amount is >= $200.01,

 ***Then*** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

***If*** the Aggregate amount is [x] Update schema to match [[Spec Updates spreadsheet tab here]([https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=2095865865](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=2095865865))]

      ![Group D - Partnership Receipt.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/27b614c1-5674-4228-9d7d-e005477c8c8f](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/27b614c1-5674-4228-9d7d-e005477c8c8f))

      —

      ![Group D - Partnership Receipt - Errors – 2.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ce937d5a-412d-4090-be24-2bae27f8e6cb](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ce937d5a-412d-4090-be24-2bae27f8e6cb))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1085](https://fecgov.atlassian.net/browse/FECFILE-1085)

**Comment by mary-tcg** [comment]
@AureliaKhorsand updated wireframe

**Comment by AureliaKhorsand** [comment]
@mary-tcg can you update this so it's a stand-alone transaction? This is not like Earmark Receipt/Memo

**Comment by mary-tcg** [comment]
@AureliaKhorsand fixed

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Added updated wire to the requirements at the top

@mary-tcg @JonellaCulmer 
PLease review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG here is what we discussed at the requirements meeting:

- Need to add information for the user underneath the label “Contribution Purpose Description”
- When the user clicks to save and add a memo, the system will notify the user with a popup that the CPD is changing

**Comment by MitchellTCG** [comment]
@AureliaKhorsand  Updated

**Comment by WiseQA** [comment]
@AureliaKhorsand clarified the Partnership Receipt transaction can have one, none, or multiple "memo's"

**Comment by mjtravers** [comment]
Passes CR. Ready for QA

**Comment by MitchellTCG** [comment]
ON HOLD TIL I COMEBACK WITH A SOLUTION

**Comment by MitchellTCG** [comment]
Until there is a holistic ticket to replace all cancel/back button provided by and sign off by our stakeholder @JonellaCulmer , we the naming convention will stay "back to [complete name of parent transaction]"

This upcoming ticket will be in Sprint 21.

**Comment by WiseQA** [comment]
QA review verified Partnership Receipt transaction is created and is editable once saved.

Verified when Partnership Receipt saved without a memo the following message is displayed.
"Partnership attributions do not require itemization"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2d49382f-9979-4dbc-b02a-90d3adad8bef)

Verified when Partnership Receipt saved with a memo the following message is displayed.
"See Partnership Attribution(s) below"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0c39a481-700d-405d-a0c2-af95f9ba548b)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2b528946-7011-4d8c-9126-b6e1f8977553)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8b4824c4-207e-4f8d-82d4-cd40ca90f2b0)

Verified “Cancel” and “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/12daa16f-e284-470d-8d9e-de2b49e1fa85)

QA Review Completed. Moved to Stage Ready.
