### ISSUE TITLE
Allow user to enter Partnership Memo on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#478]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Partnership Memo”** sub-transaction under a **”Partnership Receipt”** on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**And**I am editing a “Partnership Receipt” on an open report
**Then** I will have the option to enter the following sub-transaction:  
- Partnership Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	CONTACT TYPE (Read-only, **includes Lookup**)
-- Individual only

-	LAST NAME (Required)
-	FIRST NAME (Required)
-	MIDDLE NAME (Optional)
-	PREFIX (Optional)
-	SUFFIX (Optional)

# Address 
#
-	STREET ADDRESS (Required)
-	APARTMENT, SUITE, ETC. (Optional)
-	CITY (Required)
-	STATE/PROVINCE (Required)
-	ZIP/POSTAL CODE (Required)

# Receipt Innformation 
#
-	DATE RECEIVED (Required)
-	MEMO ITEM (Required, read-only)
-- This will be automatically checked and the user CANNOT change it.
-	AMOUNT (Required)
-- Note: AMOUNT can contain a negative value.
-	AGGREGATE (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (CONTACT) 
-- within Aggregation Group of "GENERAL"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.
-	EMPLOYER (Required if Aggregate > $200)
-	OCCUPATION (Required if Aggregate > $200)

# Additional information 
#
-	CONTRIBUTION PURPOSE DESCRIPTION (Read-only, System generated)
-- Must read "Partnership Attribution"
-	NOTE OR MEMO TEXT (A/N-100, Optional)

---
**Then** I will be able to:

- Cancel
- Back to “Partnership Receipt” 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note 

Pre-requisite - create a Partnership Receipt

 DEV TASKS

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- Note that the CPD of the parent must adhere to requirements in #477 ("See Partnership Attribution(s) below."). 

- [ ] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1349912643)

![Group A - Partnership Memo.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/84188012-af41-42f4-90bf-e60bdbbd6f5c)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by AureliaKhorsand** [comment]
@mary-tcg can you update this so it's a stand-alone transaction? This is not like Earmark Receipt/Memo

**Comment by mary-tcg** [comment]
@AureliaKhorsand fixed

**Comment by WiseQA** [comment]
@AureliaKhorsand clarified the Partnership Receipt transaction can have one, none, or multiple "memo's"

**Comment by mjtravers** [comment]
Passes CR. Ready for QA

**Comment by WiseQA** [comment]
@MitchellTCG @GreggMoreland sent email for clarification of button naming. Awaiting verification before testing can be completed.

**Comment by MitchellTCG** [comment]
ON HOLD TIL I COMEBACK WITH A SOLUTION

**Comment by MitchellTCG** [comment]
Until there is a holistic ticket to replace all cancel/back button provided by and sign off by our stakeholder @JonellaCulmer , we the naming convention will stay "back to [complete name of parent transaction]"

This upcoming ticket will be in Sprint 21.

**Comment by WiseQA** [comment]
QA review select Partnership Receipt from the transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f736acf1-2109-40dd-944c-30f5ef66e119)

Select Partnership Memo from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1ab15cc5-b175-45c1-967f-a05860aa8578)

QA review verified Partnership Receipt Memo transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/af53d4f2-84a5-4219-b5d4-33ee9c125ff8)

Verified buttons working as designed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fded2ba3-cd3a-4d49-a4ee-3448219aaac8)

QA Review Completed. Moved to Stage Ready.
