### ISSUE TITLE
Allow user to enter Party Returned/Bounced Receipt on Schedule A (Group F)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#479]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Party Returned/Bounced Receipt”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Contributions from Registered Filers" Accordion link  
**Then** I can enter a transaction with the type "Party Returned/Bounced Receipt"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Committee Only

-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note: System will automatically make the amount negative. AMOUNT MUST be a non-zero negative value to save, and max value is -$0.01. If amount exceeds that, then display error message 'Amount must be negative (example: -$20.00)'**
-	**AGGREGATE** (Required) 
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) and within "General" _(Dev/QA Note: Aggregation Group is "GENERAL")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** **(Required, A/N 100)**
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**

-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & add another “Party Returned/Bounced Receipt" 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

 Dev Note 

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See Party Returned/Bounced Receipt spec [here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=823247884). 
#

### QA Notes ### 
 - Contribution Purpose Description is required and editable by user.
- Note that AMOUNT must be negative.
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg wireframes need updating. Please note label name changes and CPD requirements.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg Ready for wireframe.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg Ready for wireframe.

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/6cc3fd82-2754-4894-8d27-450ec6ee058d)

**Comment by WiseQA** [comment]
@mjtravers per discussion with Mitchell this ticket needs fix "Amount" field where negative must appear on initial key stroke not after tabbing as noted in Tickets #489, #511 and #512.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA review retested the Party Returned/Bounced Receipt.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/71967b27-0177-4e57-90d3-490df621a069)

Verified when entering $0.00 amount the following message appears below amount field.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fb8e9e26-c164-4074-9825-c6ec9b22fe0f)

Verified when entering "Amount" field negative appears on initial key stroke not after tabbing.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/138efe12-06a3-4051-bfe0-0ffaeb02ab26)

QA Review Completed. Moved to Stage Ready.
