### ISSUE TITLE
Upgrade Angular code to version 14

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#480]
fecfil-online/front-end is currently using Angular 13. This should be upgraded to version 14 to maintain compliance with the QASP standard of being at most one major version behind the latest release.

**Acceptance Criteria**
- [x] The npm modules for Angular are version 14.1.3
- [x] The unit tests that passed before the upgrade also pass after the upgrade

**QA**
Verification that Angular version is 14 can be found in [this configuration file](https://github.com/fecgov/fecfile-web-app/blob/develop/front-end/package.json#L26-L33)
Passing unit tests can be found in this `link tbd` under the "run unit tests" section.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA verified as a visual  upgraded to 14.1.3   see below screenshot 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f9693f38-3437-4ee3-9105-d0596045181b)

Not sure as QA who is tracking lastest versions of SW and where spreadsheet is ?



QA Review Completed.  Moved to Stage Ready
