### ISSUE TITLE
Allow user to enter Party Receipt on Schedule A (Group F)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#481]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Party Receipt”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Contributions from Registered Filers" Accordion link  
**Then** I can enter a transaction with the type “Party Receipt"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contributor 
#
-	CONTRIBUTOR TYPE (Read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	COMMITTEE NAME (Required)
-	COMMITTEE FEC ID (Required)

# Address 
#
-	STREET ADDRESS (Required)
-	APARTMENT, SUITE, ETC. (Optional)
-	CITY (Required)
-	STATE/PROVINCE (Required)
-	ZIP/POSTAL CODE (Required)

# Contribution 
#
-	DATE RECEIVED (Required)
-	MEMO ITEM (Optional)
-	CONTRIBUTION AMOUNT (Required)
-- Note: AMOUNT can contain a negative value.
-	CONTRIBUTION AGGREGATE (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.
<br>

# Additional information 
#
-	CONTRIBUTION PURPOSE DESCRIPTION (Read-only, Optional)
-	NOTE OR MEMO TEXT (A/N-100, Optional)

---
**Then** I will be able to:

- Cancel
- Save & add another “Party Receipt" 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And** the transaction will be itemized upon saving with it's own line item on the *.fec file (SA11B). _(Dev note: All SA11B transactions are itemized regardless of amount)._

 Dev Task 

- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=2079918222)

![Group A - Party Receipt - Individual – 14.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/adcad054-eefa-43d5-b301-0cc50152462d)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passed CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review and testing completed on this ticket. Verified able to enter Party Receipt.  No test script written - e2e testing to satisfy this ticket.

Per DEV this functionality was completed and satisfied with this ticket.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bf932394-1518-4c16-9201-e0ed92242cdc)

QA Review Completed.  Moved to Stage Ready.
