### ISSUE TITLE
Allow user to enter Unregistered Receipt from Person on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#488]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Unregistered Receipt from Person”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Contributions from Individuals/Persons" Accordion link  
**Then** I can enter a transaction with the type “Unregistered Receipt from Person"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Organization Only
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required) 
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) and within "General" _(Dev/QA Note: Aggregation Group is "GENERAL")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Required, user-entry, A/N 100)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Cancel
- Save & add another “Unregistered Receipt from Person" 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 Dev Note 

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See Unregistered Receipt from Person spec [here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=2054954772). 
#

### QA Notes ### 
 - Contribution Purpose Description is required but editable by user.
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg wireframes need updating. Please note label name changes and CPD requirements.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Unregistered Receipt from Person transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b06b55c3-c340-416b-8c4d-0e9f32130935)

Verified Contribution Purpose Description (Required) verbiage a required field.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/33ac4246-2f49-4294-8563-0265a904553a)

Verify Confirm popup window is displayed 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/01536816-5838-4ef0-8d80-a85bbff62f38)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/76f50c06-7854-4468-b717-75bd6578b135)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e010c900-cf1d-4466-8255-1396bbf4000b)

Verified “Cancel”, “Save & add another”, “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ed78a865-7e80-4665-9b40-39b7c1ea2a6c)

QA Review Completed.   Moved to Stage Ready.
(Note:  Ignore ticket being moved back oversight on QA part)
