### ISSUE TITLE
Allow user to enter Unregistered Receipt from Person - Returned/Bounced Receipt on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#489]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **” Unregistered Receipt from Person - Returned/Bounced Receipt”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Contributions from Individuals/Persons" Accordion link  
**Then** I can enter a transaction with the type “Unregistered Receipt from Person - Returned/Bounced Receipt"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Organization Only
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**CONTRIBUTION DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note: System will automatically make the amount negative. AMOUNT MUST be a non-zero negative value to save, and max value is -$0.01. If amount exceeds that, then display error message 'Amount must be negative (example: -$20.00)'**

-	**AGGREGATE** (Required) 
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) and within "General" _(Dev/QA Note: Aggregation Group is "GENERAL")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** **(Required, A/N 100)**
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Cancel
- Save & add another “Unregistered Receipt from Person - Returned/Bounced Receipt" 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

 Dev Note 

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See Unregistered Receipt from Person - Returned/Bounced Receipt spec [here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=909525284). 
#

### QA Notes ### 
 - Contribution Purpose Description is required and editable by user.
- Note that AMOUNT must be negative.
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg wireframes need updating. Please note label name changes and CPD requirements.

**Comment by Elaine-Krauss-TCG** [comment]
Transaction implemented, and it does not allow a positive value for contribution amount:
![image](https://user-images.githubusercontent.com/104506225/210628157-4e39865b-cb20-4b26-b892-7d8c97ec1861.png)

Contribution Purpose Description is user-entered and required: (We might need to reconsider "_Optional_")
![image](https://user-images.githubusercontent.com/104506225/210628389-67ee3e23-2258-43a2-9264-576b7253fb19.png)

The transaction is saving as expected
![image](https://user-images.githubusercontent.com/104506225/210629489-3057243a-31a1-4505-8d83-6b92a21b70bd.png)

The transaction is being itemized
![image](https://user-images.githubusercontent.com/104506225/210629898-4f5c23df-1652-41b7-a158-540ab5e093f6.png)

**Comment by Elaine-Krauss-TCG** [comment]
Transaction added to E2E testing coverage
![image](https://user-images.githubusercontent.com/104506225/210634518-106cd3c7-65c4-405c-a56a-35414fe09973.png)

**Comment by Elaine-Krauss-TCG** [comment]
Added new error messages for exclusive maximum and exclusive minimum values
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/8efbcc05-7198-444b-a7dd-ce3f9582802d)
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/cb0aebe1-b010-4f76-9114-8d7a889dc96b)

**Comment by WiseQA** [comment]
@AureliaKhorsand @MitchellTCG Ticket #512 denotes verbiage in acceptance criteria for Amount (see below)
Note: AMOUNT MUST be a non-zero negative value. Max value is -0.01. If amount is higher than than, then display error message '**Amount must be negative**'

Also verbiage for Contribution Purpose Description.

@AureliaKhorsand @GreggMoreland @MitchellTCG should the verbiage be the same for this ticket ?  If so can we denote in Acceptance Criteria correct verbiage to be consistent across tickets.  Thanks !

**Comment by MitchellTCG** [comment]
@Elaine-Krauss-TCG 
I am moving this out of CR and back to in progress til the error language is vetted by Jonella. This will be done at the 1pm UX meeting today.

**Comment by Elaine-Krauss-TCG** [comment]
The error text for when a negative value is expected has been updated
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/91ef7e47-813d-4bd2-aeed-34b186b836d3)
THIS COMMENT AND CHANGE IS OBE DUE TO FUNCTIONALITY CHANGE.   DISREGARD THIS CHANGE.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Unregistered Receipt from Person - Returned/Bounced Receipt transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cce5f740-50ad-4e2a-8f16-c47d848f9965)

@mjtravers per discussion with Mitchell this ticket being returned to fix "Amount" field where negative must appear on initial key stroke not after tabbing.

**Comment by mjtravers** [comment]
The new handling of the negative amount has been implemented and passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review retested the Unregistered Receipt from Person - Returned/Bounced Receipt.  

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b3080991-9ffe-4239-8d5b-2a84ed76ff4e)

Verified when entering $0.00 amount the following message appears below amount field.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/96fc2a93-e8b6-470c-9f83-b70db3df1aa9)

Verified when entering "Amount" field negative appears on initial key stroke not after tabbing.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1712f104-61e0-4209-8a79-30b58cbe42c6)

QA Review Completed.  Moved to Stage Ready.
