### ISSUE TITLE
Allow user to enter PAC Earmark Receipt on Schedule A (Group F)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#490]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”PAC Earmark Receipt”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

NOTE: This transaction requires a "child" (memo) transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Contributions from Registered Filers" Accordion link  
**Then** I can enter a transaction with the type “PAC Earmark Receipt"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	CONTACT TYPE (Read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	COMMITTEE NAME (Required)
-	COMMITTEE FEC ID (Required)

# Address 
#
-	STREET ADDRESS (Required)
-	APARTMENT, SUITE, ETC. (Optional)
-	CITY (Required)
-	STATE/PROVINCE (Required)
-	ZIP/POSTAL CODE (Required)

# Receipt Infomation 
#
-	DATE RECEIVED (Required)
-	MEMO ITEM (Optional)
-	AMOUNT (Required)
-- Note: AMOUNT can contain a negative value.
-	AGGREGATE (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.
<br>

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only)
--If ENTITY TYPE of associated EAR_MEMO = COM, "Earmarked through XX" where XX is the conduit from EAR_MEMO associated
--If ENTITY TYPE of associated EAR_MEMO  = IND,  "Earmarked through XX" where XX is first_name last_name from EAR_MEMO associated
-	**NOTE OR MEMO TEXT** (A/N-100, Optional)
---

**Then** I will be able to:

- Cancel
- Edit fields

(Note: user will not be able to save at this point. They must save with Earmark Memo, which requires ticket #491)

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=909853874)

 QA Note 

This includes the Lookup functionality for Committee.
![Group F - PAC Earmark Receipt.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/4aedbdb8-2963-4fc6-b9b9-7b40a6ec7592)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@mary-tcg 
Please knock this out first thing tomorrow

**Comment by AureliaKhorsand** [comment]
@mary-tcg can you update the field names in the wireframes to match the ACs in the ticket? Thanks!

**Comment by mary-tcg** [comment]
@AureliaKhorsand done

**Comment by mjtravers** [comment]
Passes CR but there is an issue when editing an existing PAC Earmark Receipt record that, when saved, throws and error on the back end:
`[WARNING] django.request: Bad Request: /api/v1/transactions/schedule-a/c50b03c7-a6cf-4fcb-a13f-f71e83938652/`

This error exists on the Earmark Receipt/Memo transaction type as well and is being addressed in ticket [api#320](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/320)

**Comment by WiseQA** [comment]
QA review verified PAC Earmark Receipt transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/407786f0-f91e-4644-b0e2-7357e13cac9f)

Verify Confirm popup window is displayed - creating a new committee contact 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ccb7d901-f987-484a-b498-2a2f5a5568ed)

Verified Transactions table is updated.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/70a278e5-8990-4c1f-a8b2-ff3bcf7a3204)

Verified “Cancel” and "Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4a669cb9-b4f6-42f8-92fc-c3c195ad7e2e)

QA Review Completed.   Moved to Stage Ready.
