### ISSUE TITLE
Allow user to enter PAC Earmark Memo on Schedule A (Group G)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#491]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”PAC Earmark Memo”** sub-transaction under **”PAC Earmark Receipt”**  on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a PAC Earmark Receipt transaction on an open report
**Then**  I will **be required** to enter the following sub-transaction:

- PAC Earmark Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Conduit 
#
-	**ENTITY TYPE** (Required, **INCLUDES LOOKUP**)
Dropdown options: Individual, Committee 
*Note - please default to COMMITTEE

_if CONTRIBUTOR TYPE = Committee_
-	**CONDUIT NAME** (Required)
-	**CONDUIT FEC ID** (Required)

_if CONTRIBUTOR TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)
-	**EMPLOYER** (**Required regardless of aggregate**)
-	**OCCUPATION** (**Required regardless of aggregate**)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Contribution 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Required)
**This will be automatically checked and read-only.**
-	**AMOUNT** (Required, **read-only**, can be negative)
**This should automatically be the same as the earmark Receipt (parent) and read-only**
-	CONTRIBUTION AGGREGATE (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (System Generated)
Data field: multi-line textbox that must read "Total earmarked through conduit."
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Toggle between step 1 and 2 and edit fields as needed
- Save & view all transactions [will go to "Manage your transactions" Table]
- Cancel (Note: This cancels _both_ transactions)

**And** upon saving, both PAC Earmark Receipt and PAC Earmark Memo will be saved with their own line items (itemized) on the *.fec file (SA11C). _(Dev note: All 11B and 11C transactions are itemized regardless of amount)._

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [x] Update PAC Earmark Memo spec with updates in yellow. See [Spec Updates spreadsheet](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=636234359).
- [ ] Use django transaction for save so we can rollback a partial success https://docs.djangoproject.com/en/4.1/topics/db/transactions/
![PAC Earmark 2.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/8633afd5-ad19-4bba-a0ec-4c02f564e9de)

### QA Notes ### 
 
Reminders below for testing that fields are required fields now.
Employer Field (Not Required > Employer Field (Required)
Occupation Field (Not Required) > Occupation Field (Required)
This includes Lookup functionality.

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@mary-tcg 
Please knock this out first thing tomorrow

**Comment by mjtravers** [comment]
@dheitzer @WiseQA What does this QA Note from the acceptance criteria mean? Should the EMPLOYER and OCCUPATION fields have the (Required) or (Not Required) text attached to them depending whether the contact is an IND or COM?
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/520ab7ed-1059-4210-ad63-090d1c435e2d)

**Comment by mjtravers** [comment]
Passes CR but there is an issue when editing an existing PAC Earmark Receipt record that, when saved, throws and error on the back end:
`[WARNING] django.request: Bad Request: /api/v1/transactions/schedule-a/c50b03c7-a6cf-4fcb-a13f-f71e83938652/`

This error exists on the Earmark Receipt/Memo transaction type as well and is being addressed in ticket [api#320](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/320)

**Comment by WiseQA** [comment]
QA review the "PAC Earmark Memo" label is not displaying in transactions table (see below screenshot).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e136c65d-510a-4d3f-aa09-d3dba3cb62ce)

@mjtravers @MitchellTCG returning to In-progress for defect fix #833 which affects this ticket.

**Comment by toddlees** [comment]
label fixed in defect 833

**Comment by mjtravers** [comment]
Passes CR after fix. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the fix for label not displaying is fixed.  The "PAC Earmark Memo" label is displaying in transactions table (see below screenshot).  

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/49faf1c7-15c7-4941-b22c-ccd9551b8c23)

QA Review Completed.   Moved to Stage Ready.
