### ISSUE TITLE
Allow user to enter Transfer on Schedule A (Group F)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#492]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Transfers”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Transfer" Accordion link  
**Then** I can enter a transaction with the type “Transfer"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# ~Contributor~ Contact 
#
-	~CONTRIBUTOR~ CONTACT TYPE (Read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	COMMITTEE NAME (Required)
-	COMMITTEE FEC ID (Required)

# Address 
#
-	STREET ADDRESS (Required)
-	APARTMENT, SUITE, ETC. (Optional)
-	CITY (Required)
-	STATE/PROVINCE (Required)
-	ZIP/POSTAL CODE (Required)

# Contribution 
#
-	DATE RECEIVED (Required)
-	MEMO ITEM (Optional)
-	~CONTRIBUTION~ AMOUNT (Required)
-- Note: AMOUNT can contain a negative value.
-	~CONTRIBUTION~ AGGREGATE (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.
<br>

# Additional information 
#
-	CONTRIBUTION PURPOSE DESCRIPTION (Read-only, Optional)
-	NOTE OR MEMO TEXT (A/N-100, Optional)
---
**Then** I will be able to:

- Save & add another
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed
- Cancel 

**And** the transaction will be itemized upon saving with it's own line item on the *.fec file (SA12). _(Dev note: All SA12 transactions are itemized regardless of amount)._

 Dev Note 

- [ ] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=559306225)

![Group F - Transfer Receipt.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/8b073b14-1cf8-429a-850c-19dc75b9b974)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Some changes requested in CR. Sending back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review - Cancel button not selectable.  Only buttons selectable "Save & add another Memo" and "Save & view all transactions".  

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c418b619-b6cb-40d5-ab38-bfb7b5793864)

@mjtravers @MitchellTCG - Cancel button should be selectable ?  If so, need added to Acceptance Criteria and button fixed.  Standing by for clarification.

Returned to "in-progress" for "Cancel" button.

**Comment by MitchellTCG** [comment]
@WiseQA @toddlees @mjtravers 
Re: Cancel button ...
Yes the Cancel button should work. I will update the ticket. Dev's please fix.

**Comment by toddlees** [comment]
@WiseQA @MitchellTCG @mjtravers got a PR for it up now.  It also removes the yellow/orange "Save & add another Memo" which is not supposed to be on this form https://github.com/fecgov/fecfile-web-app/pull/658

**Comment by mjtravers** [comment]
Patch for cancel button passes CR. It also passes a quick smoke test on DEV. Sending to QA.

**Comment by WiseQA** [comment]
QA review "Save & add another" button not displaying in Transfer Transaction page.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d642c3fd-ee22-47eb-b757-ad83067b20b5)

@mjtravers @toddlees @MitchellTCG - Returned to "In-progress" for "Save & add another" button fix.

**Comment by mjtravers** [comment]
Button moved and code passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "Save & add another" button is displaying and functional.  Retested functionality of the buttons for Transfer transaction.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8f231b5e-9b84-4b15-9743-ed912b5e12fb)

QA Review Completed.   Moved to Stage Ready.
