### ISSUE TITLE
Allow user to enter Joint Fundraising Transfer - National Party Pres. Nominating Convention Account on Schedule A (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#497]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Joint Fundraising Transfer - National Party Pres. Nominating Convention Account”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "parent" transaction that will typically have associated sub-transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Transfers" Accordion link  
**Then** I can enter a transaction with the type " Joint Fundraising Transfer - National Party Pres. Nominating Convention Account "
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Committee Only

-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:**AMOUNT can be a negative value
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Convention Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_CONVENTION_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system-generated)
Multi-line textbox that MUST SAY "Pres. Nominating Convention Account Transfer of JF Proceeds"
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & view all transactions
- Save & add another
- Save & add a... _(Note these will be dead links for this ticket)_
--Individual National Party Pres. Nominating Convention Account JF Transfer Memo
--PAC National Party Pres. Nominating Convention Account JF Transfer Memo
--Tribal National Party Pres. Nominating Convention Account JF Transfer Memo
--Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See Joint Fundraising Transfer - National Party Pres. Nominating Convention Account spec [here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1096675313). 
#

### QA Notes ### 
  Dev Note 
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg ready for wireframe

**Comment by dheitzer** [comment]
@mjtravers can I confirm that the Dev Note can be removed from this ticket? I think it should only be there for child transactions (not parents) and wanted to confirm.

**Comment by mjtravers** [comment]
Found in CR that the new transaction type needs to be added to the cypress e2e tests per Elaine's slack message in the dev channel on Nov. 16 at 12pm. Sending back to In Progress

**Comment by dheitzer** [comment]
Added/tested e2e tests for this.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Joint Fundraising Transfer - National Party Pres. Nominating Convention Account transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b651171e-80c1-47e2-8846-dd75a6a7b2ca)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d739793a-7643-4ba0-a5ac-0f65465e4a58)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/294e0c7d-b000-4c10-88c0-e17f3ed37e24)

Verified “Cancel”, “Save & add memo”, “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b723f93d-5e15-4956-8857-9bda2f8e26c1)

QA Review Completed.   Moved to Stage Ready.
