### ISSUE TITLE
Allow user to enter Joint Fundraising Transfer - National Party Headquarters Buildings Account on Schedule A (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#498]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Joint Fundraising Transfer - National Party Headquarters Buildings Account”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "parent" transaction that will typically have associated sub-transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Transfers" Accordion link  
**Then** I can enter a transaction with the type "Joint Fundraising Transfer - National Party Headquarters Buildings Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE**(Read-only, **INCLUDES LOOKUP**)
-- Committee Only

-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:**AMOUNT can be a negative value
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Headquarters Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_HEADQUARTERS_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, System-generated)
Multi-line textbox that MUST SAY "Headquarters Buildings Account Transfer of JF Proceeds"
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & view all transactions
- Save & add another
- Save & add a... _(Note these will be dead links for this ticket)_
--Individual National Party Headquarters Buildings Account JF Transfer Memo
--PAC National Party Headquarters Buildings Account JF Transfer Memo
--Tribal National Party Headquarters Buildings Account JF Transfer Memo
--Partnership Receipt Headquarters Buildings Account JF Transfer Memo
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See Joint Fundraising Transfer - National Party Headquarters Buildings Account spec [here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=863998401). 
#

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg wireframe needs updated. Please note the transaction name and label changes.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg wireframe needs updating. Please note transaction name and label changes.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg Outdated wireframe removed. **Needs updating to match current requirements and label names.**

**Comment by dheitzer** [comment]
![image.png](https://images.zenhubusercontent.com/6298ce840c1c301e7c4a4151/e720e065-b3ef-418d-a1be-f7a1bca6b7df)

**Comment by mjtravers** [comment]
Passes CR. Holding ticket in Code Review until Sprint-17 tickets are all moved to Stage Ready.

**Comment by WiseQA** [comment]
QA review verified Joint Fundraising Transfer - National Party Headquarters Buildings Account transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4a457eb4-4419-468f-95e0-9cae3d0bdaeb)

Verify Confirm popup window is displayed - creating a new committee contact.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7e5ac687-f0c7-4f04-bf0b-4c8861c401c9)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a5965c6d-8695-41e6-8383-44d10323598d)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5257ce05-6ad9-4388-85f1-d557afac10b1)

Verified “Back to Joint Fundraising Transfer” and “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7eda3c06-e82c-4e3d-b004-3b510e8ca7cb)

QA Review Completed.   Moved to Stage Ready.
