### ISSUE TITLE
Allow user to enter Individual National Party Pres. Nominating Convention Account JF Transfer Memo on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#499]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **’Individual National Party Pres. Nominating Convention Account JF Transfer Memo‘** sub-transaction under **"Joint Fundraising Transfer - National Party Pres. Nominating Convention Account" on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

NOTE: This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator
**And** I am editing a Joint Fundraising Transfer - National Party Pres. Nominating Convention Account transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction:
- Individual National Party Pres. Nominating Convention Account JF Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- INDIVIDUAL only

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)
-	**EMPLOYER** (Required if Aggregate > $200)
-	**OCCUPATION** (Required if Aggregate > $200)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
This will be automatically checked and the user CANNOT change it.
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of  all contributions that are:
--- From the person (ENTITY) and within "National Party Convention Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_CONVENTION_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system-generated)
Multi-line textbox that must read "Pres. Nominating Convention Account JF Memo: XX ", where XX is auto-populated with the name of the committee entered in parent transaction JF_TRAN COL SEQ 8
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & add another “Individual National Party Pres. Nominating Convention Account JF Transfer Memo" associated to the same "parent"
- Back to Joint Fundraising Transfer - National Party Pres. Nominating Convention Account
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See Individual National Party Convention Account JF Transfer Memo spec [here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=660658633). 
#

### QA Notes ### 
  Dev Note 
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg ready for wireframe

**Comment by mjtravers** [comment]
Passes CR but awaiting e2e screenshot. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Individual National Party Pres. Nominating Convention Account JF Transfer Memo is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b9d29a75-dc03-463f-9345-fc9680f9d517)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2f830610-a36c-4498-8cba-9eeaf1b8d822)

Verify Confirm popup window is displayed - creating a new Individual contact.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c27d8656-448c-4f09-8510-90792593e79c)
Verified Child / Parent association.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ef3dd59d-9289-4132-9e53-0652c18c276a)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/576ed946-bd0e-4bf1-9d70-635a32962aeb)

Verified "Confirm" popup window displayed showing Employer and Occupation was added to contact.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/91760ac3-2854-4457-82c1-42ec9c9911e1)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ca16aca5-2b9a-4812-a868-20ea88d5fb65)

Verified “Back to Joint Fundraising Transfer”, “Save & add another memo”, “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ceb537b1-d051-449b-84cd-36e1d69aad75)

QA Review Completed.   Moved to Stage Ready.

**Comment by WiseQA** [comment]
QA review verified Party Recount Receipt transaction is created and is editable once saved.
