### ISSUE TITLE
Draft Ticket Management Process

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#5]
**Task:** Draft Ticket Management Process for FECFile Online project

**Acceptance Criteria:**

1. Includes Ticket Workflow
2. Includes Ticket Review Norms
3. Includes Ticket Writing Criteria
4. Includes Ticket Organization

**Definition of Done:**

1. Complete internal review with Program Manager, Product manager, and Project manager
2. Complete internal review with Developers
3. Post to FECFile Project Management repository on GitHub for FEC access

**Comment by AureliaKhorsand** [comment]
Draft located here: https://docs.google.com/document/d/1TOMFwugTRcPaEOQ21nY90gqYl3wR4l4KauyxUg3i2nI/edit#

**Comment by alexander-lin** [comment]
For QA review, Aurelia will walkthrough it with Shelly. After approval from QA, Aurelia will post to shared space for review with FEC.

**Comment by AureliaKhorsand** [comment]
Issue moved to [fecgov/fecfile-project-management #13](https://github.com/fecgov/fecfile-project-management/issues/13) via [**ZenHub**](https://www.zenhub.com/)

**Comment by AureliaKhorsand** [comment]
Marked as OBE. Created in wrong repo.
