### ISSUE TITLE
Synchronization issue between Angular and Protractor

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-web-app#50]
There is some unusual behavior in the app that is causing the default waitForAngular() function in Protractor to fail.  Adding this:
```
protractor.browser.ignoreSynchronization = true;
```
to the end-to-end tests script will allow the tests to run without timeout, but it does cause difficulty in synchronizing the test with the app.  

It is possible that an open web request made by the application is causing waitForAngular to think the page is not in a ready state. In my development instance, this URL is listed as an open network request:
```
http://localhost/sockjs-node/267/auvmxhil/xhr_streaming
```

**User Story**
As a developer/QA, 
I would like the protractor end to end unit tests to work without disabling browser sync
so that unit tests can be written without requiring synchronization work arounds.

**Acceptance Criteria**
- [ ] e2e test job runs properly in CircleCI
- [ ] Calls to waitForAngular in protractor tests work as expected.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/2/22:** Pointed at 8 due to large number of unknowns.

**Comment by mjtravers** [comment]
This is OBE as we have learned that Protractor reaches end of life at the end of the year.

https://github.com/angular/protractor/issues/5502

Closing ticket.
