### ISSUE TITLE
Allow user to enter Individual National Party Headquarters Buildings Account JF Transfer Memo on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#500]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **’Individual National Party Headquarters Buildings Account JF Transfer Memo‘** sub-transaction under **"Joint Fundraising Transfer - National Party Headquarters Buildings Account"** on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

NOTE: This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator
**And** I am editing a Joint Fundraising Transfer - National Party Headquarters Buildings Account transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction:

- Individual National Party Headquarters Buildings Account JF Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- INDIVIDUAL only

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

-	**EMPLOYER** (Required if Aggregate > $200)
-	**OCCUPATION** (Required if Aggregate > $200)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Contribution 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
This will be automatically checked and the user CANNOT change it.
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Headquarters Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_HEADQUARTERS_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system-generated)
Multi-line textbox that must read "Headquarters Buildings Account JF Memo: XX ", where XX is auto-populated with the name of the committee entered in parent transaction JF_TRAN COL SEQ 8
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & add another “Individual National Party Headquarters Buildings Account JF Transfer Memo" associated to the same "parent"
- Back to Joint Fundraising Transfer - National Party Headquarters Buildings Account
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See Individual National Party Headquarters Account JF Transfer Memo spec [here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=175285777). 
#

### QA Notes ### 
  Dev Note 
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg wireframe needs updating. Please note the new transaction name and the label changes.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg Outdated wireframe removed. **Needs updating to match current requirements and label names.**

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/6d658132-bf0a-468d-8464-51360e89ee6f)

**Comment by mjtravers** [comment]
Discovered contribution_employer and contribution_occupation properties missing in validation schema during code review. Sending back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
After entering a Joint Fundraising Transfer - National Party Headquarters Buildings Account, click the Save & add a memo button.  Verify dropdown list is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9d3af4eb-7cb4-406b-aedb-5ecc14a810d7)

Select Individual National Party Headquarters Buildings Account JF Transfer Memo from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f0f87537-c85d-4353-aeee-df663a52268c)

Verify Confirm popup window is displayed - creating a new committee contact.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/65e3ff1b-ca85-49b9-ac2f-d196d3695783)

Verify Individual National Party Headquarters Buildings Account JF Transfer Memo page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d2b25e6f-450f-4b08-b2cf-3350e7339a49)

Verify transactions table updated showing memo as "Child" to the Joint Fundraising Transfer - National Party Headquarters Buildings Account transaction.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/50e24ae0-92c3-4be4-a95f-622d4c443117)

QA Review Completed.   Moved to Stage Ready.
