### ISSUE TITLE
Allow user to enter PAC National Party Pres. Nominating Convention Account JF Transfer Memo on Schedule A (Group F)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#501]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”PAC National Party Pres. Nominating Convention Account JF Transfer Memo”** sub-transaction under a **”Joint Fundraising Transfer - National Party Pres. Nominating Convention Account”**  on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Joint Fundraising Transfer - National Party Pres. Nominating Convention Account on an open report  
**Then** I will have the option to enter the following sub-transaction: 
- PAC National Party Pres. Nominating Convention Account JF Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Contribution 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
This will be automatically checked and the user CANNOT change it.
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of  all contributions that are:
--- From the person (ENTITY) and within "National Party Convention Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_CONVENTION_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system-generated)
Field description in API: RECEIPT DESCRIPTION
Data field: multi-line textbox that MUST SAY “Pres. Nominating Convention Account JF Memo: XX” where XX is auto-populated with the name of the committee entered in parent transaction JF_TRAN COL SEQ 8
-	**NOTE OR MEMO TEXT** (A/N-100, Optional)

---
**Then** I will be able to:
- Cancel
- Save & add another “PAC National Party Pres. Nominating Convention Account JF Transfer Memo" associated to the same "parent"
- Back to Joint Fundraising Transfer - National Party Pres. Nominating Convention Account
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See PAC National Party Pres. Nominating Convention Account JF Transfer Memo spec [here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=2071510353). 
#

### QA Notes ### 
  Dev Note 
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg ready for wireframe

**Comment by mjtravers** [comment]
Passes CR but awaiting e2e screenshot. Sending to QA.

**Comment by WiseQA** [comment]
QA verified PAC National Party Pres. Nominating Convention Account JF Transfer Memo is selectable from the dropdown

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6c7931cd-d5c0-4734-b63d-ee82645f6942)

Verified PAC National Party Pres. Nominating Convention Account JF Transfer Memo  page is displayed

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8faf8140-b484-4549-ac28-0cdf2773e6a4)

Verify Confirm popup window is displayed - creating a new committee contact

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/96dd1605-75be-464b-b783-335092ab255f)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/75f88df2-c091-4e4e-9441-ce617b95beac)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b9f7d069-5cee-4755-a0dc-407554350a89)

Verified “Cancel”, “Save & add another”, “Save & view all transactions” buttons functional and working.

Verified “Save & add another memo”, “Back to Joint Fundraising Transfer”, “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f36dc20f-0e90-4f9d-af83-84a9bfc88ee1)

QA Review Completed.   Moved to Stage Ready.
