### ISSUE TITLE
Allow user to enter PAC National Party Headquarters Buildings Account JF Transfer Memo on Schedule A (Group F)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#502]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”PAC National Party Headquarters Buildings Account JF Transfer Memo”** sub-transaction under a **”Joint Fundraising Transfer - National Party Headquarters Buildings Account”**  on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Joint Fundraising Transfer - National Party Headquarters Buildings Account on an open report  
**Then** I will have the option to enter the following sub-transaction: 
- PAC National Party Headquarters Buildings Account JF Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
This will be automatically checked and the user CANNOT change it.
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Headquarters Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_HEADQUARTERS_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system-generated)
Multi-line textbox that MUST SAY “Headquarters Buildings Account JF Memo: XX” where XX is auto-populated with the name of the committee entered in parent transaction JF_TRAN COL SEQ 8
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Cancel
- Save & add another “PAC National Party Headquarters Buildings Account JF Transfer Memo" associated to the same "parent"
- Back to Joint Fundraising Transfer - National Party Headquarters Buildings Account
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See PAC National Party Headquarters Buildings Account JF Transfer Memo spec [here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=106423180). 
#

### QA Notes ### 
  Dev Note 
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg needs updated wireframe. Please note transaction name change and label changes

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg Outdated wireframe removed. **Needs updating to match current requirements and label names.**

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/d7d72d87-d824-4069-b119-bd1915e71859)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
After entering a Joint Fundraising Transfer - National Party Headquarters Buildings Account transaction, click the Save & add a memo button.  Verify dropdown list is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c8372bdb-45f7-43f7-98d1-2f48d276006d)

Select PAC National Party Headquarters Buildings Account JF Transfer Memo from the dropdown

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7fd8b402-0ea6-415b-866e-1f465a5e4f1d)

Verify PAC National Party Headquarters Buildings Account JF Transfer Memo page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/732613bb-f8ea-4068-a139-669970c41f40)

Verify transactions table updated showing memo as "Child" to the Joint Fundraising Transfer - National Party Headquarters Buildings Account transaction.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9b5a4918-3680-44c9-b154-83d3e6db5fef)

QA Review Completed.   Moved to Stage Ready.
