### ISSUE TITLE
Allow user to enter Partnership Individual Pres. Nominating Convention Account JF Transfer Memo on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#506]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Partnership Individual Pres. Nominating Convention Account JF Transfer Memo”** sub-transaction under a **”JPartnership Receipt Pres. Nominating Convention Account JF Transfer Memo”**  on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a Tier 3 transaction that will be associated with a Tier 2 transaction. [#504](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/504)

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo on an open report  
**Then** I will have the option to enter the following sub-transaction: 
- Partnership Individual Pres. Nominating Convention Account JF Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, includes Lookup)
-- Individual 
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)
-	**EMPLOYER** (Required if Aggregate > $200)
-	**OCCUPATION** (Required if Aggregate > $200)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Required, system checked and read-only)
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required) 
-- Amount Displayed will be the total of  all contributions that are:
--- From the person (ENTITY) and within "National Party Convention Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_CONVENTION_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF RECEIPT** (Read-only, system generated)
Multi-line textbox that MUST SAY “Pres. Nominating Convention Account JF Memo: XX (Partnership Attribution)", where XX is auto-populated with name of committee entered in Tier 1 transaction JF_TRAN COL SEQ 8
**-- Note: If the Purpose of Receipt surpasses the 100 character limit, then the system will truncate the committee name (XX text) and end it with "..." so that everything in the parentheses can fit.**
-	**NOTE OR MEMO TEXT** (Optional)
---
**Then** I will be able to:

- Cancel
- Save & add memo _(Note that this is a possible tier 3 transaction)._ 
Group Name: Partnership Receipt Pres. Nominating Convention Account JF Transfer; Memo name list: Partnership Individual
- Save
- Edit as needed

**And if** the Aggregate amount is >= $200.01 or negative,
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SA17.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1973712710)

 Wireframe 

![506 - Partnership Individual Pres. Nominating Convention Account JF Transfer Memo.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/acc1c90b-a864-4cc7-a5e4-a9f6551d5432)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
UIpdated

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Prerequisite a "Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo" transaction to be created, saved in the "Transactions" table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/858245c7-af03-4f60-b994-ab00d2241078)

Select the + Save & add memo button. Verify dropdown list is displayed. Then select "Partnership Individual" from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2fb5fbc5-2f13-430e-9b8b-6c0b9f984e4e)

Verify "Partnership Individual Pres. Nominating Convention Account JF Transfer Memo" page is displayed and contact type is "Individual" only

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/595e1f80-2151-4e22-b249-d0daf886aac9)

Verified the "Transaction ID" and "Associated with" for tier 3 is displayed and referenced correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5e7e8800-aa1b-454d-9aab-44e579c73489)

QA Review Completed.  Moved to Stage Ready.
