### ISSUE TITLE
Allow user to enter Partnership Individual Headquarters Buildings Account JF Transfer Memo on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#507]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Partnership Individual Headquarters Buildings Account JF Transfer Memo”** sub-transaction under a **”Partnership Receipt Headquarters Buildings Account JF Transfer Memo”**  on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a Tier 3 transaction that will be associated with a Tier 2 transaction [#505](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/505)

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Partnership Receipt Headquarters Buildings Account JF Transfer Memo on an open report  
**Then** I will have the option to enter the following sub-transaction: 
- Partnership Individual Headquarters Buildings Account JF Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT** (Read-only, includes LOOKUP)
-- Individual
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)
-	**EMPLOYER** (Required if Aggregate > $200)
-	**OCCUPATION** (Required if Aggregate > $200)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Required, system checked and read-only)
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Headquarters Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_HEADQUARTERS_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF RECEIPT** (Read-only, system generated)
Multi-line textbox that MUST SAY “Headquarters Buildings Account JF Memo: XX (Partnership Attribution)", where XX is auto-populated with name of committee entered in Tier 1 transaction
**-- Note: If the Purpose of Receipt surpasses the 100 character limit, then the system will truncate the committee name (XX text) and end it with "..." so that everything in the parentheses can fit.**
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & add memo _(Note that this is a tier 3 transaction)._
Group Name: Partnership Headquarters Buildings Account JF Transfer; Memo name list: Partnership Individual
- Save
- Edit 

**And if** the Aggregate amount is >= $200.01 or negative,
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SA17.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1462614266)

 WIreframe 

![507 - Partnership Individual Headquarters Buildings Account JF Transfer Memo.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a487ca45-4db2-44c9-af72-c9260eaff78b)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Update

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Prerequisite a "Partnership Receipt Headquarters Buildings Account JF Transfer Memo" transaction to be created, saved in the "Transactions" table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/54de0f3f-d360-4879-84ac-c657db1260c0)

Select the + Save & add memo button. Verify dropdown list is displayed. Then select "Partnership Individual" from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b662f20e-2a44-4405-bc86-34d85e7310b7)

Verify "Partnership Individual Headquarters Buildings Account JF Transfer Memo" page is displayed and contact type is "Individual" only

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/03a196fc-b60c-4af9-b82e-5fc2a0ed6885)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ac3617ef-cc1c-4f50-b3b8-64b2ae0afbea)

Transaction name "Partnership Individual Headquarters Buildings Account JF Transfer Memo" is missing from the above 2 transaction pages.   

Memo name is missing from Transactions table:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5619b06d-bcb3-4e0f-b269-4b394633463e)

The "Transaction ID" and "Associated with" for these transactions are not displayed and referenced correctly in transactions table.

@mjtravers @MitchellTCG Returned to In-Progress for fixing "Name of memo" not displaying on transactions pages (see above screenshots) and  "Associated with" transaction fix for memo to transaction.

**Comment by mjtravers** [comment]
Fix for missing Associated With ids on transaction list tables made. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Retested this ticket after fixes. This Tier 3 transaction is live and developed.

Prerequisite a "Joint Fundraising Transfer - National Party Headquarters Buildings Account" "Partnership Receipt Headquarters Buildings Account JF Transfer Memo" transaction to be created, saved in the "Transactions" table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/eb2c234e-a0fc-4993-a172-c1338acf6832)

Verify Tier 3 link for "Partnership Individual" under "Save & Add Memo" selectable.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6a4dea3c-bdd2-4910-857f-603f4f01b806)

Verify Tier 3 memo is created "Partnership Individual Headquarters Buildings Account JF Transfer Memo"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c290a387-72c4-4b8b-b3fc-74832cf6d7de)

Verified the "Transaction ID" and "Associated with" for tier 3 is displayed and referenced correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5bb4b4c2-c10a-4011-93a5-d2a2405d6a02)

QA Review Completed. Fixes have been implemented and Pass. Moved to Stage Ready.
