### ISSUE TITLE
Allow user to enter Returned/Bounced Receipt on Schedule A (Group C)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#512]
Business Reason

As a Committee Administrator, I will be able to enter a ***”Returned/Bounced Receipt”*** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

  ***Then*** Add a new transaction 

  ***Then*** Click(open) on the "Contributions from Individuals/Persons" Accordion link 

  ***Then*** I can enter a transaction with the type "Returned/Bounced Receipt"

  ***Then*** I will be required to enter the following information (unless otherwise noted):

—

1.  Contact

       #

*   ***CONTACT TYPE*** (Required, Dropdown, ***INCLUDES LOOKUP***) 
      *   Options: Individual, Organization

_if CONTACT TYPE = Organization_

*   ***ORGANIZATION NAME*** (Required)

_if CONTACT TYPE = Individual_

*   ***LAST NAME*** (Required)
*   ***FIRST NAME*** (Required)
*   ***MIDDLE NAME*** (Optional)
*   ***PREFIX*** (Optional)
*   ***SUFFIX*** (Optional)
*   ***EMPLOYER*** (Required if Aggregate > $200)
*   ***OCCUPATION*** (Required if Aggregate > $200)

1.  Address

       #

*   ***STREET ADDRESS*** (Required)
*   ***APARTMENT, SUITE, ETC.*** (Optional)
*   ***CITY*** (Required)
*   ***STATE/PROVINCE*** (Required)
*   ***ZIP/POSTAL CODE*** (Required)

1.  Receipt Information

       #

*   ***DATE RECEIVED*** (Required)
*   ***MEMO ITEM*** (A/N-1, Optional)
*   ***AMOUNT*** (Required)

       ***Note: System will automatically make the amount negative. AMOUNT MUST be a non-zero negative value to save, and max value is -$0.01\. If amount exceeds that, then display error message 'Amount must be negative (example: -$20.00)'***

*   ***AGGREGATE*** (Required) 
      *   Amount Displayed will be the total of contributions that are: 
            *   From the person (ENTITY) and within "General" _(Dev/QA Note: Aggregation Group is "GENERAL")_
        *   _from_ January 1 of report year _to_ the Contribution Date* of the transaction.
        *   *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

1.  Additional information

       #

*   ***CONTRIBUTION PURPOSE DESCRIPTION*** ***(Required, A/N 100)***

       ***Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."***
*   ***NOTE OR MEMO TEXT*** (Optional)

—

  ***Then*** I will be able to:

*   Cancel
*   Save & add another “Returned/Bounced Receipt"
*   Save & view all transactions [will go to "Manage your transactions" Table]
*   Edit as needed

***And*** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

Dev Note

1.  See Schedule A spec [here]([https://fecgov.github.io/fecfile-validate/SchA_spec.html](https://fecgov.github.io/fecfile-validate/SchA_spec.html)).

       #

1.  See Returned/Bounced Receipt spec [here]([https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1669393101](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1669393101)).

       #

### QA Notes ###
- ENTITY options are Individual _and_ Organization
- Contribution Purpose Description is required and editable by user.
- Note that AMOUNT must be negative.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1056](https://fecgov.atlassian.net/browse/FECFILE-1056)

**Comment by AureliaKhorsand** [comment]
@GreggMoreland can you update the specs to include accounting for "ORG" entity? Specs are updated in the spreadsheet

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg wireframes need updating. Please note label name changes and CPD requirements.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg Outdated wireframe removed. **Needs updating to match current requirements and label names.**

**Comment by WiseQA** [comment]
@mjtravers per discussion with Mitchell this ticket being returned to fix "Amount" field where negative must appear on initial key stroke not after tabbing.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA review retested the Returned/Bounced Receipt.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c98b739d-b9a1-46d0-8606-537811f6f3af)

Verified when entering $0.00 amount the following message appears below amount field.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/92338fab-e79b-4d11-8575-79e952d7e690)

Verified when entering "Amount" field negative appears on initial key stroke not after tabbing.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fee4cad0-9c11-4401-a6b2-52fcbf5096ee)

QA Review Completed. Moved to Stage Ready.
