### ISSUE TITLE
Allow user to enter Earmark Receipt for Recount/Legal Proceedings Account (Contribution) on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#513]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Earmark Receipt for Recount/Legal Proceedings Account (Contribution)”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

NOTE: This transaction requires a "child" (memo) transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type “Earmark Receipt for Recount/Legal Proceedings Account (Contribution)"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**Contact TYPE** (includes Lookup)
Dropdown options: Individual

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)
-	**EMPLOYER** (Required if Entity aggregate > $200)
-	**OCCUPATION** (Required if Entity aggregate > $200))
---

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:**AMOUNT Can be a negative value
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "NATIONAL_PARTY_RECOUNT_ACCOUNTT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (System generated)
Data field: multi-line textbox that MUST SAY “"Recount/Legal Proceedings Account - Earmarked Through XX"
-If CONTACT TYPE of associated Earmark Memo = COM, XX is the committee from associated memo 
-If CONTACT TYPE of associated Earmark Memo  = IND,  XX is first_name last_name from associated memo”
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Cancel
- Edit
- Save & add Earmark Memo (note: an Earmark Memo for Recount/Legal Proceedings Account (Contribution)  is required with each Earmark Receipt for Recount/Legal Proceedings Account (Contribution). They can never save just an Earmark Receipt for Recount/Legal Proceedings Account (Contribution)).

# Wireframes 
#
*These are the buttons and accordions that should appear on the page*
![513-514 Earmark Receipt for Recount Legal Proceedings Account Contribution.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/26bba98e-2cd5-4e8f-b003-641734768a32)

 QA Note

 Dev Note 

Please change **"Earmark Receipt for Recount Account (Contribution)"** on the **ACCORDION** to **"Earmark Receipt for Recount/Legal Proceedings Account (Contribution)"**

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=535142363) **Please note this a "consolidated" specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg ready for wireframe. Note that this is Step One - Earmark Receipt.

**Comment by Elaine-Krauss-TCG** [comment]
Successfully created an Earmark Receipt for Recount/Legal Proceedings Account
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/ea18ad1d-c198-4f2f-adec-50844695b299)

**Comment by Elaine-Krauss-TCG** [comment]
After reviewing with Aurelia, the National Party Earmark Receipts should belong to group AG and not group GG.  The receipts have been updated and are in working order.  Returning to CR.

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/bb7c25d3-4949-47d6-aab4-b247346732a9)

**Comment by Elaine-Krauss-TCG** [comment]
Labels updated:
On the transaction accordion
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/0b1d8583-2a1b-4363-bf8e-062a173a33e3)

And on the transaction management screen
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/15324957-e26c-4bad-b1c8-377c6127464c)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Earmark Receipt for Recount/Legal Proceedings Account (Contribution) transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fb444a1c-2a11-4920-86f5-0405c2b3164c)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ee84ffbb-dce7-45d3-94d7-37b7605cbbfc)

**Comment by WiseQA** [comment]
When I create an Earmark Receipt then add the memo and select the "save & add transactions" button I get this error when testing 513 and 514.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e3b66345-93d9-4362-aef9-7908e8383561)

@mjtravers thinks there is a problem with the validator.   Returned to In-Progress

**Comment by mjtravers** [comment]
The fix ellipsis fix for the error commented above has passed CR. Sending ticket back to QA.

**Comment by WiseQA** [comment]
QA review retested Earmark Receipt for Recount/Legal Proceedings Account (Contribution) and fixes have been incorporated.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8bce48b3-c03c-43cd-9c51-4b2d604a9ea4)

QA Review Complete.   Moved to Stage Ready.
