### ISSUE TITLE
Allow user to enter Earmark Memo for Recount/Legal Proceedings Account (Contribution) on Schedule A (Group G)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#514]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Earmark Memo for Recount/Legal Proceedings Account (Contribution)”** sub-transaction under **”Earmark Receipt for Recount/Legal Proceedings Account (Contribution)”**  on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Earmark Receipt for Recount/Legal Proceedings Account (Contribution) transaction on an open report
**Then**  I will **be required** to enter the following sub-transaction:

- Earmark Memo for Recount/Legal Proceedings Account (Contribution)

**And** I will be required to enter the following information (unless otherwise noted):

---

# Conduit 
#
-	**ENTITY TYPE** (includes Lookup)
Dropdown options: Individual, Committee 
*Note - please default to COMMITTEE

---
_if ENTITY TYPE = Committee_
-	**CONDUIT NAME** (Required)
-	**CONDUIT FEC ID** (Required)

---
_if ENTITY TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)
-	**EMPLOYER** (Required regardless of aggregate)
-	**OCCUPATION** (Required regardless of aggregate)
---

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Contribution 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Required)
**This will be automatically checked and read-only.**
-	**AMOUNT** (Required, **read-only**, can be negative)
**This should automatically be the same as the earmark Receipt (parent) and read-only**
-	**AGGREGATE** (Required, can be negative)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "NATIONAL_PARTY_RECOUNT_ACCOUNT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (System generated)
Data field: multi-line textbox that must read "Total earmarked through conduit."
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Save (same as Save & view all transactions button)
- Back to Earmark Receipt for Recount/Legal Proceedings Account (Contribution) (NOT a button)  Button is Cancel
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And** upon saving, both the parent transaction and this transaction will be itemized and appear as line items on the *.fec file (regardless of amount).

# Wireframes 
#
*These are the buttons and accordions that should appear on the page*
![513-514 Earmark Receipt for Recount Legal Proceedings Account Contribution.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/26bba98e-2cd5-4e8f-b003-641734768a32)

 QA Note
- ENTITY can be Individual or Committee, but should default to Committee.
NOTE:   There are only 2 buttons for Earmark Memo to date, Cancel and Save & view all transactions.

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- Please change **"Earmark Memo for Recount Account (Contribution)"** on the **ACCORDION** to **"Earmark Memo for Recount/Legal Proceedings Account (Contribution)"**

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1102834035) **Please note this a "consolidated" specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg ready for wireframe. Note that this is Step Two - Earmark Memo.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
When I create an Earmark Receipt then add the memo and select the "save & add transactions" button I get this error when testing 513 and 514.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e3b66345-93d9-4362-aef9-7908e8383561)

@mjtravers thinks there is a problem with the validator.   Returned to In-Progress

**Comment by mjtravers** [comment]
The fix ellipsis fix for the error commented above has passed CR. Sending ticket back to QA.

**Comment by WiseQA** [comment]
QA review verified Earmark Memo for Recount/Legal Proceedings Account (Contribution) is created and saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1a81f18b-7e01-41ad-987b-4ba55c075461)

Missing button **Back to Earmark Receipt for Recount/Legal Proceedings Account (Contribution)**.    

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ef8f9076-e64e-4eb1-bb2c-31889ada292c)

@mjtravers @MitchellTCG Returned in In-progress for button fix.

**Comment by WiseQA** [comment]
After clarification of what buttons should be displayed, QA review retested and verified "Cancel" and "Save & view all transactions" buttons are working.   

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/be21447b-d654-423b-9af0-85da7d3fc339)

Verified Earmark Memo for Recount/Legal Proceedings Account (Contribution) is displayed in Transactions Table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/24fd6e92-77fd-44f3-9d19-75f5e3a51c33)

QA Review Complete.  Moved to Stage Ready.
