### ISSUE TITLE
Allow user to enter Earmark Receipt for Pres. Nominating Convention Account (Contribution) on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#515]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Earmark Receipt for Pres. Nominating Convention Account (Contribution)”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

NOTE: This transaction requires a "child" (memo) transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type “Earmark Receipt for Pres. Nominating Convention Account (Contribution)"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**Contact TYPE** (**includes Lookup**)
Dropdown options: Individual

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)
-	**EMPLOYER** (Required if Entity aggregate > $200)
-	**OCCUPATION** (Required if Entity aggregate > $200))

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:**AMOUNT Can be a negative value
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "NATIONAL_PARTY_CONVENTION_ACCOUNT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (System generated)
Data field: multi-line textbox that MUST SAY “"Pres. Nominating Convention Account - Earmarked Through XX""
If ENTITY TYPE of associated Earmark Memo = COM, XX is the committee from associated memo 
If ENTITY TYPE of associated Earmark Memo  = IND,  XX is first_name last_name from associated memo"		
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Cancel
- Edit
- Add Earmark Memo (note: an Earmark Memo for Pres. Nominating Convention Account (Contribution)  is required with each Earmark Receipt for Pres. Nominating Convention Account (Contribution). They can never save just an Earmark Receipt for Convention Account (Contribution)).

# Wireframes 
#
*These are the buttons and accordions that should appear on the page*
![515-516 Earmark Receipt for Pres Nominating Convention Account Contribution.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/5e230f9d-2a6b-408d-a498-b60770e586cc)

 QA Note

 Dev Note 

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=535142363) **Please note this a "consolidated" specification.**
- Please change **"Earmark Receipt for Convention Account (Contribution) "** on the **ACCORDION** to **"Earmark Receipt for Pres. Nominating Convention Account (Contribution) "**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg ready for wireframe. Note that this is Step One - Earmark Receipt.

**Comment by Elaine-Krauss-TCG** [comment]
Successfully created an Earmark Receipt for Pres. Nominating Convention Account
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/f49f8808-b608-44a6-8d0b-8327836a3f92)

**Comment by WiseQA** [comment]
@mjtravers please verify ticket has passed and completed CR.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA review verified Earmark Receipt for Pres. Nominating Convention Account (Contribution) transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d453221a-b699-4cef-afc1-5164e5cb62f0)

@MitchellTCG @AureliaKhorsand @GreggMoreland Contact TYPE (includes Lookup)
Dropdown options: Individual.   However under QA notes "ENTITY can be Individual or Committee, but should default to Individual".   

Question for clarification is this Individual only or Individual or Committee ?

**Comment by MitchellTCG** [comment]
@WiseQA  the parent is individual only
@MitchellTCG thanks removed QA note "ENTITY can be Individual or Committee, but should default to Individual".

**Comment by WiseQA** [comment]
QA review verified Earmark Receipt for Pres. Nominating Convention Account (Contribution) transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d4df9998-c6e7-46fb-a327-4ff85f929cff)

Verified Earmark Receipt for Pres. Nominating Convention Account (Contribution) displayed in Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d9458f0c-07c2-41ab-8f72-84180147644b)

QA Review Complete.   Moved to Stage Ready.
