### ISSUE TITLE
Allow user to enter Earmark Receipt for Headquarters Buildings Account (Contribution) on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#517]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Earmark Receipt for Headquarters Buildings Account (Contribution)”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

NOTE: This transaction requires a "child" (memo) transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type “Earmark Receipt for Headquarters Buildings Account (Contribution)"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**Contact TYPE** (includes Lookup)
Dropdown options: Individual

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)
-	**EMPLOYER** (Required if Entity aggregate > $200)
-	**OCCUPATION** (Required if Entity aggregate > $200))

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:**AMOUNT Can be a negative value

-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "NATIONAL_PARTY_HEADQUARTERS_ACCOUNT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (System generated)
Data field: multi-line textbox that MUST SAY “Headquarters Buildings Account - Earmarked Through XX"
_If ENTITY TYPE of associated Earmark Memo = COM, XX is the committee from associated memo 
_If ENTITY TYPE of associated Earmark Memo  = IND,  XX is first_name last_name from associated memo
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Cancel
- Edit
- Add Earmark Memo (note: an Earmark Memo for Headquarters Buildings Account (Contribution)  is required with each Earmark Receipt for Headquarters Account (Contribution). They can never save just an Earmark Receipt for Headquarters Account (Contribution)).

# Wireframes 
#
*These are the buttons and accordions that should appear on the page*
![517-518 Earmark Receipt for Headquarters Buildings Account Contribution.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/90ba5a61-9a2b-409b-b38a-7b53c220c502)

 QA Note

 Dev Note 

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=535142363) **Please note this is our first "consolidated" specification.**
- Please change **"Earmark Receipt for Headquarters Account (Contribution)"** on the **ACCORDION** to **"Earmark Receipt for Headquarters Buildings Account (Contribution)"**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg ready for wireframe. Note that this is Step One - Earmark Receipt.

**Comment by Elaine-Krauss-TCG** [comment]
Status update:

The Group G transaction component (Individual/Committee transactions) has been added, along with the Earmark Receipt for Headquarters Buildings Account (Contribution)
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/84b86390-a9e4-4616-b268-cec8b7f100f0)

Currently I am trying to figure out how to generate the Contribution Purpose Description with values derived from the form as it is being filled out.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/6eab6d82-49dd-4641-a977-ea0396c2fd73)

**Comment by Elaine-Krauss-TCG** [comment]
Successfully created an Earmark Receipt for Headquarters Buildings Account
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/c23aea51-9d78-4c26-b9cd-13b3dc579a0e)

**Comment by Elaine-Krauss-TCG** [comment]
CPD is being populated as specified in the spec, but the Conduit FEC ID is not being filled when saved transactions are loaded...
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/cec414b2-5212-44cf-942d-300d55de10f3)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Earmark Receipt for Headquarters Buildings Account (Contribution) transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ca316156-7beb-48ed-9383-363bc8427ed7)

Verified displayed in transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b4b13bc5-15c0-4e76-bf35-afafcbe669e0)

QA Review Completed.   Moved to Stage Ready.
