### ISSUE TITLE
Allow user to enter Earmark Memo for Headquarters Buildings Account (Contribution) on Schedule A (Group G)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#518]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Earmark Memo for Headquarters Buildings Account (Contribution)”** sub-transaction under **”Earmark Receipt for Headquarters Buildings Account (Contribution)”**  on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Earmark Receipt for Headquarters Buildings Account (Contribution) transaction on an open report
**Then**  I will **be required** to enter the following sub-transaction:

- Earmark Memo for Headquarters Buildings Account (Contribution) 

**And** I will be required to enter the following information (unless otherwise noted):

---

# Conduit 
#
-	**Contact TYPE** (includes Lookup)
Dropdown options: Individual, Committee 
*Note - please default to COMMITTEE

---
_if ENTITY TYPE = Committee_
-	**CONDUIT NAME** (Required)
-	**CONDUIT FEC ID** (Required)

---
_if ENTITY TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)
-	**EMPLOYER** (Required regardless of aggregate)
-	**OCCUPATION** (Required regardless of aggregate)
---

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Contribution 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Required)
**This will be automatically checked and read-only.**
-	**AMOUNT** (Required, **read-only**, can be negative)
**This should automatically be the same as the earmark Receipt (parent) and read-only**
-	**AGGREGATE** (Required, can be negative)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "NATIONAL_PARTY_HEADQUARTERS_ACCOUNT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (System generated
Data field: multi-line textbox that MUST contain "Total earmarked through conduit"
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Save 
- Back to Earmark Receipt for Headquarters Buildings Account (Contribution)
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And** upon saving, both the parent transaction and this transaction will be itemized and appear as line items on the *.fec file (regardless of amount).

# Wireframes 
#
*These are the buttons and accordions that should appear on the page*
![517-518 Earmark Receipt for Headquarters Buildings Account Contribution.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/90ba5a61-9a2b-409b-b38a-7b53c220c502)

 QA Note
- ENTITY can be Individual or Committee, but should default to Committee.

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- Please change **"Earmark Memo for Headquarters Account (Contribution)"** on the **ACCORDION** to **"Earmark Memo for Headquarters Buildings Account (Contribution)"**

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1102834035) **Please note this a "consolidated" specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg ready for wireframe. Note that this is Step Two - Earmark Memo.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Earmark Memo for Headquarters Buildings Account (Contribution) transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dc8b3d0c-cf3c-4741-9ac9-347f74e23368)

Verified transactions memo displayed in transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3fe75eb4-ebdf-4531-a702-beebe57d5027)

QA Review Completed.   Moved to Stage Ready.
