### ISSUE TITLE
Allow user to enter Individual Receipt - Non-Contribution Account on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#519]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Individual Receipt - Non-Contribution Account”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type “Individual Receipt - Non-Contribution Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contributor 
#
-	**CONTRIBUTOR TYPE** (required, read-only, **INCLUDES LOOKUP**)
-- Individual Only
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

-	**EMPLOYER** (Required if Contribution Aggregate > $200)
-	**OCCUPATION** (Required if Contribution Aggregate > $200)

# Contribution 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**CONTRIBUTION AMOUNT** (Required)
**Note:**CONTRIBUTION AMOUNT Can be a negative value
-	**CONTRIBUTION AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) and within "Non-Contribution Account" _(Dev/QA Note: Aggregation Group is "NON_CONTRIBUTION_ACCOUNT")_
--- from January 1 of report year to the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, Required)
Data field: multi-line textbox that MUST SAY “Non-contribution Account Receipt”
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Cancel
- Save & view all transactions
- Save & add another
- Edit as needed

**And if** the Contribution Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Contribution Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- Aggregation Group is "NON_CONTRIBUTION_ACCOUNT"

 Dev Note 

- [ ] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1611977426)
![Group A - Non-Contribution Account (individual).png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/3cce3423-4754-4527-8f4e-f013bcd37e1f)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe labels corrected per ticket #570

**Comment by Elaine-Krauss-TCG** [comment]
Transaction added
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/0d865343-a7c3-4ffc-8436-85d184b5f3b3)

**Comment by mjtravers** [comment]
e2e test output:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/37551dce-9205-42dd-be70-874d801cf99c)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Individual Receipt - Non-Contribution Account transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/adefccab-8b5d-406e-a3d0-f5e6b76c4f9a)

Verify Confirm popup window is displayed - creating a new individual contact 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0dce3eb6-932f-4c7b-b3a8-d060a68a5ac0)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1391128a-6668-4e9f-9b7c-154a2a048b40)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ee80a344-1ba7-4676-bfcf-dbdf56f34b9a)

Verified “Cancel”, “Save & add another”, “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bf213ec0-7b2a-464b-9956-48821392bf5f)

QA Review Completed.   Moved to Stage Ready.
