### ISSUE TITLE
Allow user to enter Individual Recount Receipt on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#520]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Individual Recount Receipt”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type “Individual Recount Receipt"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (required, read-only, **INCLUDES LOOKUP**)
-- Individual Only
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

-	**EMPLOYER** (Required if Aggregate > $200)
-	**OCCUPATION** (Required if Aggregate > $200)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:**AMOUNT Can be a negative value
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) and within "Recount Account" _(Dev/QA Note: Aggregation Group is "RECOUNT_ACCOUNT")_
--- from January 1 of report year to the Contribution Date of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system-generated)
Data field: multi-line textbox that MUST SAY “Recount Account” 
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Cancel
- Save & view all transactions
- Save & add another
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=675493605)
![Group A - Individual Recount Receipt.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/45c08705-6a1d-457e-b64b-1a3b4a43b596)

### QA Notes ### 
 - Very similar to PAC RECOUNT RECEIPT, with different contact fields
- Itemization happens when aggregation is over $200 rather than always
- This transaction type is part of the RECOUNT_ACCOUNT aggregation group.  There are *currently* no other transactions implemented in this group so it should only aggregate with other PAC Recount Receipts.
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated per ticket #570

**Comment by toddlees** [comment]
Passes CR moving to QA

**Comment by WiseQA** [comment]
QA review verified Individual Recount Receipt transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/adb45989-df1e-4047-bdc2-c9686123c33d)

Verify Confirm popup window is displayed - creating a new committee contact Individual Recount Receipt, then select the Continue Button

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d2969ac4-bdfa-4802-9ece-9487b96b37d8)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1748b20c-3c33-4c52-acef-1ff1144db5db)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e96aa184-8231-4ac3-a6a1-c3bd93523ab8)

Verified “Cancel”, “Save & add another”, “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c5ef6cfe-9358-465c-b725-98a918dfd1a2)

QA Review Completed.   Moved to Stage Ready.

**Comment by mjtravers** [comment]
Awaiting  e2e screenshot for verification.
