### ISSUE TITLE
Allow user to enter Individual National Party Recount/Legal Proceedings Account on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#521]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Individual National Party Recount/Legal Proceedings Account”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type “Individual National Party Recount/Legal Proceedings Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Individual Only

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)
-	**EMPLOYER** (Required if Aggregate > $200)
-	**OCCUPATION** (Required if Aggregate > $200)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:**AMOUNT Can be a negative value
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Recount Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_RECOUNT_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system generated)
Data field: multi-line textbox that MUST SAY “Recount/Legal Proceedings Account”
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Cancel
- Save & view all transactions
- Save & add another
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
N/A

 Dev Note 

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1017857131)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg Outdated wireframe removed. **Needs updating to match current requirements and label names.**

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/0521a698-e9d9-42a6-947a-61cc4f3f36c3)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA when sprint-19 starts.

**Comment by WiseQA** [comment]
QA review verified Individual National Party Recount/Legal Proceedings Account transaction is created and is editable once saved.

![image](https://user-images.githubusercontent.com/96139912/210823811-7b43db5f-a6d0-44b9-b5c4-f5df1c2d756e.png)

Verify Confirm popup window is displayed.

![image](https://user-images.githubusercontent.com/96139912/210824013-0de879e9-b322-4df9-9ab4-f08de358e6af.png)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image](https://user-images.githubusercontent.com/96139912/210824251-649ed529-b5d3-4af1-861d-7007a4055470.png)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image](https://user-images.githubusercontent.com/96139912/210824524-6c65de2e-ce26-47c5-9fa9-b1afcef50a00.png)

Verified “Cancel”, “Save & add another”, “Save & view all transactions” buttons functional and working.

![image](https://user-images.githubusercontent.com/96139912/210824717-3dedd095-0264-4de5-91ff-869169a022b6.png)

QA Review Completed.   Moved to Stage Ready.
