### ISSUE TITLE
Allow user to enter Party National Party Recount/Legal Proceedings Account on Schedule A (Group F)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#522]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Party National Party Recount/Legal Proceedings Account”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type “Party National Party Recount/Legal Proceedings Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:**AMOUNT Can be a negative value
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Recount Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_RECOUNT_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system generated)
Data field: multi-line textbox that MUST SAY “Recount/Legal Proceedings Account”
-	**NOTE OR MEMO TEXT** (Optional)
---
**Then** I will be able to:
- Cancel
- Save & view all transactions
- Save & add another
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
N/A

 Dev Note 

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1963340550)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg Ready for updated wireframe. Please note label name changes and requirements in ticket.

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/9d36d871-c3bf-4b6d-9f9c-bda5bcf8d1fa)

**Comment by MitchellTCG** [comment]
@WiseQA please test

THIS IS ONLY A TEST

**Comment by mjtravers** [comment]
Passes code review. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified Party National Party Recount/Legal Proceedings Account transaction is created and is editable once saved.

![image](https://user-images.githubusercontent.com/96139912/210825942-810dee45-9317-4b88-a832-74fe09054a18.png)

Verify Confirm popup window is displayed.

![image](https://user-images.githubusercontent.com/96139912/210826107-6403054c-b4b6-4004-ac2d-e3d1f7877e76.png)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01.

![image](https://user-images.githubusercontent.com/96139912/210826300-baeb7bfc-7377-495d-8eeb-ab09c117cc0d.png)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00.

![image](https://user-images.githubusercontent.com/96139912/210826506-10a0f100-c954-4441-bd4b-6d022b8a1d99.png)

Verified “Cancel”, “Save & add another”, “Save & view all transactions” buttons functional and working.

![image](https://user-images.githubusercontent.com/96139912/210826704-822ae89c-1e56-4c83-b8ea-23a6afbd7c80.png)

QA Review Completed.   Moved to Stage Ready.
