### ISSUE TITLE
Allow user to enter Individual National Party Pres. Nominating Convention Account on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#524]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Individual National Party Pres. Nominating Convention Account”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type “Individual National Party Pres. Nominating Convention Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Individual Only
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)
-	**EMPLOYER** (Required if Aggregate > $200)
-	**OCCUPATION** (Required if Aggregate > $200)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:**AMOUNT Can be a negative value
-	**AGGREGATE** (Required) 
-- Amount Displayed will be the total of  all contributions that are:
--- From the person (ENTITY) and within "National Party Convention Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_CONVENTION_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system generated)
Data field: multi-line textbox that MUST SAY “Pres. Nominating Convention Account”
-	**NOTE OR MEMO TEXT** (Optional)

---

**Then** I will be able to:
- Cancel
- Save & view all transactions
- Save & add another
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
N/A

 Dev Note 

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=2136154971)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand updated wireframe

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg ready for updated wireframe.

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/4c30fa7b-e07c-4741-a7c5-e9be87f0007b)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the "Individual National Party Pres. Nominating Convention Account" is not listed in the accordion dropdown list for "Other".   Naming needs changed in accordion dropdown and Transaction page Party National Party Pres. Nominating Convention Account.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/256464d6-67ab-4fd0-804f-453d0842eeb0)

@mjtravers @MitchellTCG returned to In-progress for naming change.   @mjtravers  QA good with testing this ticket in Sprint 18 once fix is made.

**Comment by Elaine-Krauss-TCG** [comment]
Corrected the labels for the Individual and Party National Party Pres. Nominating Convention Account receipts.

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/7e70e9b0-2d7c-40e6-9702-5f60dc11602f)
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/72f5d9b7-b6dd-433e-929b-e1452662c5c7)

**Comment by mjtravers** [comment]
Fix passes CR. Ready for QA on DEV server.

**Comment by WiseQA** [comment]
QA review verified Individual National Party Pres. Nominating Convention Account transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f7eb92a6-3919-4d4b-a6f1-3c4d687842a1)

Verify Confirm popup window is displayed - creating a new individual contact.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/27e3e65e-dd45-41f9-afce-b3ddc8c4148b)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/55aa0f8d-4c47-4704-b625-c9feb619676c)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c5398f4d-8802-4b87-9266-c606821b9d8c)

Verified “Cancel”, “Save & add another”, “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a045220a-879f-4beb-90b8-ce5d42e34bd5)

QA Review Completed.   Moved to Stage Ready.
