### ISSUE TITLE
Allow user to enter PAC National Party Headquarters Buildings Account on Schedule A (Group F)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#526]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”PAC National Party Headquarters Buildings Account”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type "PAC National Party Headquarters Buildings Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Headquarters Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_HEADQUARTERS_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system generated)
Data field: multi-line textbox that MUST SAY “Headquarters Buildings Account”
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & add another 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note 
N/A

 Dev Note 

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=161290325)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg ready for wireframe

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/fb2313fa-43af-43d4-8352-5e8b32c5d34a)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified PAC National Party Headquarters Buildings Account transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ec182281-923f-4a8b-8213-ac0e43cd57a6)

Verify Confirm popup window is displayed - creating a new committee contact.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a57df018-c0f2-4685-8378-6d13b0f7ab47)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/663e00f0-d242-43af-a832-23365aaeaa55)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3ef04c96-82d6-414d-a8c3-42d8f1537a23)

Verified “Cancel”, “Save & add another”, “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b4f7e2d5-b6f3-47d7-a5a6-cc36e8248851)

QA Review Completed.   Moved to Stage Ready.
