### ISSUE TITLE
Allow user to enter Other Committee Receipt - Non-Contribution Account on Schedule A (Group F)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#528]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Other Committee Receipt - Non-Contribution Account”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type "Other Committee Receipt - Non-Contribution Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (required, read-only, **INCLUDES LOOKUP**)
Data field: COMMITTEE
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) and within "Non-Contribution Account" _(Dev/QA Note: Aggregation Group is "NON_CONTRIBUTION_ACCOUNT")_
--- from January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, Required)
Data field: multi-line textbox that MUST SAY “Non-contribution Account Receipt”
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & add another “Other Committee Receipt - Non-Contribution Account" 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Contribution Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Contribution Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- Aggregation Group is "NON_CONTRIBUTION_ACCOUNT"

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=254782384)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg Outdated wireframe removed. **Needs updating to match current requirements and label names.**

**Comment by mjtravers** [comment]
Passes CR but awaiting e2e screenshot. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Other Committee Receipt - Non-Contribution Account transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3811e74a-d0bc-4c1d-a09a-8dca2e3e8fdc)


Verify Confirm popup window is displayed - creating a new committee contact

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0440e716-88e5-4933-b167-f3d25e4bfbd2)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3a7490d5-a002-4735-a204-b9f5af37ce28)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c9c98e78-41d7-4a6e-8a16-e3f0c4775698)

Verified “Cancel”, “Save & add another”, “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1c8a4923-d728-40c4-b121-a214bc0e850e)

QA Review Completed.   Moved to Stage Ready.
