### ISSUE TITLE
Allow user to enter Party Recount Receipt on Schedule A (Group F)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#529]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Party Recount Receipt”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type "Party Recount Receipt"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (required, read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) and within "Recount Account" _(Dev/QA Note: Aggregation Group is "RECOUNT_ACCOUNT")_
--- from January 1 of report year to the Contribution Date of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system-generated)
Data field: multi-line textbox that MUST SAY “Recount Account”
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & add another “Party Recount Receipt" 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1608352995)
![Group F - Party Recount Receipt – 1.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/1da62c2d-c5a7-41e3-b59b-0b4592da8ce1)

### QA Notes ### 
 - Itemization happens when aggregation is over $200 rather than always
- This transaction type is part of the RECOUNT_ACCOUNT aggregation group.  There are *currently* no other transactions implemented in this group so it should only aggregate with other PAC Recount Receipts.
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by toddlees** [comment]
Passes CR, moving to QA

**Comment by WiseQA** [comment]
QA review verified Party Recount Receipt transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d766ed4c-868e-4076-82a3-4256206ff55e)

Verify Confirm popup window is displayed - creating a new committee contact Party Recount Receipt, then select the Continue Button

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5a3180bf-d074-4bd4-8095-6e24de69186b)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3af8e3f5-2e68-4637-8625-d3e0c4ff7a4b)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/811acc12-3d33-41ac-81ce-5e9e2e5f420c)

Verified “Cancel”, “Save & add another”, “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5937ce42-8c99-4b5c-a477-a700288fed7f)

QA Review Completed.   Moved to Stage Ready.

**Comment by mjtravers** [comment]
Awaiting  e2e screenshot for verification.
