### ISSUE TITLE
Add code coverage report to angular code

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-web-app#53]
**User Story**
As a dev/QA,
I would like to see a code coverage report on the angular front-end web application
so that our project will complete our QASP requirements

NOTE: This is for unit test only. It is not required for the unit tests to pass

**Acceptance Criteria**
- [x] Code coverage should run in the CI pipeline ( QA: See this [code coverage report](https://692-306118986-gh.circle-artifacts.com/0/coverage-report/index.html) stored in CircleCI as an artifact)
- [x] Code coverage report sent to SonarCloud report, or at least config.yml set up if report cannot be generated due to failing unit tests.  (QA: See the [branch summary on SonarCloud](https://sonarcloud.io/summary/new_code?id=fecgov_fecfile-web-app&branch=feature%2F53-add-code-coverage). Note that there is a 1.1% coverage estimate after merge)
- [x] Modify CI to not deploy if unit tests fail (QA: Look at the [CircleCI workflow summary](https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/183/workflows/ee8e224d-bd0d-403f-88ea-4f2c003c60f9) for this PR and notice that the deploy step was not executed due to an issue with the dependency check)
- [x] Fail the CI test job if the unit tests fail 
- [x] Remove the backup unit tests CI job (QA: Look at the [CircleCI workflow summary](https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/183/workflows/ee8e224d-bd0d-403f-88ea-4f2c003c60f9) note that the backup unit test job is not being run)

**QA**
QA can verify the code coverage report is running on Sonar Cloud here and see the 1.1% estimate in the bottom left grid square in the report. https://sonarcloud.io/summary/new_code?id=fecgov_fecfile-web-app&pullRequest=132

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/2/22:** This ticket should be done after unit tests are running, but want to get this in plce before Al leaves the team. Pointed at 3.

**Comment by WiseQA** [comment]
Verified the code coverage report is running on Sonar Cloud here and see the 1.1% estimate in the bottom left grid square in the report as stated in Acceptance Criteria.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5f4cb7db-b0cc-4744-b920-5b40cf9abd4a)

QA review completed.  Moved to Stage Ready.
