### ISSUE TITLE
Allow user to enter PAC Recount Receipt on Schedule A (Group F)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#530]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”PAC Recount Receipt”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type "PAC Recount Receipt"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (required, read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) and within "Recount Account" _(Dev/QA Note: Aggregation Group is "RECOUNT_ACCOUNT")_
--- from January 1 of report year to the Contribution Date of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system-generated)
Data field: multi-line textbox that MUST SAY “Recount Account”
-	**NOTE OR MEMO TEXT** (Optional)

**Then** I will be able to:

- Cancel
- Save & add another “PAC Recount Receipt" 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 Dev Note 

- [ ] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=967565263)

![Group F - PAC Recount Receipt.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/387641ad-e5b8-4ca4-91f5-7f496887c4d8)

### QA Notes ### 
 
- Itemization happens when aggregation is over $200 rather than always
- This transaction type is part of the RECOUNT_ACCOUNT aggregation group.  There are *currently* no other transactions implemented in this group so it should only aggregate with other PAC Recount Receipts.

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified PAC Recount Receipt transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3da05fe3-8aa7-4b7a-90ad-cb9cff1ed5a1)

Verify Confirm popup window is displayed - creating a new committee contact PAC Recount Receipt, then select the Continue Button

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3d42296d-6778-4113-bcfd-e51b7067b051)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3130a194-60ec-406a-b193-c4112e64ebae)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c07f9792-0572-4895-a5fa-9638c454ba74)

Verified “Cancel”, “Save & add another”, “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1ee24ce9-98fd-48b7-a802-f3b88dba8c22)

QA Review Completed.   Moved to Stage Ready.

**Comment by mjtravers** [comment]
Awaiting  e2e screenshot for verification.
