### ISSUE TITLE
Allow user to enter Party National Party Pres. Nominating Convention Account on Schedule A (Group F)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#532]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Party National Party Pres. Nominating Convention Account”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type "Party National Party Pres. Nominating Convention Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Convention Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_CONVENTION_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-Only, system generated)
Multi-line textbox that MUST SAY "Pres. Nominating Convention Account"
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & add another 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note

 Dev Note 

- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=628460328)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg ready for updated wireframe

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/397f026e-8496-41dc-b32b-5188fe1bce08)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the "Tribal National Party Pres. Nominating Convention Account" is not listed in the accordion dropdown list for "Other".   Naming needs changed in accordion dropdown and Transaction page Party National Party Pres. Nominating Convention Account.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ecbace12-47a3-4db0-838e-62cc68f7ce19)

@mjtravers @MitchellTCG returned to In-progress for naming change.   @mjtravers  QA good with testing this ticket in Sprint 18 once fix is made.

**Comment by mjtravers** [comment]
Fix passes CR. Ready for QA on DEV server.

**Comment by WiseQA** [comment]
QA review verified Party National Party Pres. Nominating Convention Account transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a424d634-165d-4a72-af2e-5c9057b71a91)

Verify Confirm popup window is displayed - creating a new committee contact.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6da2dcc5-1f4e-44da-b0c8-ed3edf954af0)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/da745eb2-053c-4eef-a6da-55f05f0ebc1a)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6e62f65d-9295-4e2d-8c16-59ba96994d8e)

Verified “Cancel”, “Save & add another”, “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4c5b1796-1624-42dc-8262-61cfac4bb05e)

QA Review Completed.   Moved to Stage Ready.
