### ISSUE TITLE
Allow user to enter Business/Labor Organization Receipt - Non-Contribution Account on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#533]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **” Business/Labor Organization Receipt - Non-Contribution Account”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type "Business/Labor Organization Receipt - Non-Contribution Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (required, read-only, **INCLUDES LOOKUP**)
-- Organization Only
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) and within "Non-Contribution Account" _(Dev/QA Note: Aggregation Group is "NON_CONTRIBUTION_ACCOUNT")_
--- from January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, required)
Data field: multi-line textbox that MUST say “Non-contribution Account Receipt”
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & add another 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Contribution Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Contribution Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- Aggregation Group is "NON_CONTRIBUTION_ACCOUNT"

 Dev Note 

- [ ] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1173906584)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg Outdated wireframe removed. **Needs updating to match current requirements and label names.**

**Comment by Elaine-Krauss-TCG** [comment]
Transaction creating and itemized correctly
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/f969f03e-da66-4d08-8f6a-4e9c542a2124)

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/a5434694-be23-4f5c-90a2-9cd19cc3595a)

**Comment by Elaine-Krauss-TCG** [comment]
Added E2E support

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/ef2c6972-98f1-48ee-9183-5f53b200922a)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Business/Labor Organization Receipt - Non-Contribution Account transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/93d459f2-3a50-4856-a733-a066ab41d5ca)


Verify Confirm popup window is displayed - creating a new organization contact.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ad394978-9a80-4339-83bc-96641ff50a47)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1173130a-7719-4ffa-820e-e811106b2716)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/301c8ddb-f331-43f0-ba41-38318e3ac98e)

Verified “Cancel”, “Save & add another”, “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f4c59a81-1ed9-41df-887b-ef5dc22629b0)


QA Review Completed.   Moved to Stage Ready.
