### ISSUE TITLE
Allow user to enter Tribal National Party Pres. Nominating Convention Account on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#537]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Tribal National Party Pres. Nominating Convention Account”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type "Tribal National Party Pres. Nominating Convention Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Organization Only
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required) 
-- Amount Displayed will be the total of  all contributions that are:
--- From the person (ENTITY) and within "National Party Convention Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_CONVENTION_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system generated)
Data field: multi-line textbox that MUST say “Pres. Nominating Convention Account” 
-	**NOTE OR MEMO TEXT** (Optional)
---
**Then** I will be able to:

- Cancel
- Save & add another 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
N/A

 Dev Note 

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=62475128)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg ready for updated wireframe

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/824db5fc-21ef-4a75-9052-5c5373ac656e)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the "Tribal National Party Pres. Nominating Convention Account" is not listed in the accordian dropdown list for "Other".   Naming needs changed in accordian dropdown and Transaction page title.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c3503ebb-e26e-42c5-8d0b-19bcac58feb7)

@mjtravers @MitchellTCG Returning to In-progress for fix.

**Comment by mjtravers** [comment]
Label updated to "Tribal National Party Pres. Nominating Convention Account"
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/4b5b82e6-6bfe-44b6-a44c-58b39a3221f6)

Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Tribal National Party Pres. Nominating Convention Account transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d8288e79-4a3c-4548-bfd9-18b87be873ec)


Verify Confirm popup window is displayed - creating a new committee contact.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fef03df2-0ab0-4395-a278-6a6f9e4f1745)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3bb9fe71-9db1-40f6-bcfc-2ae017478108)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/40314c5e-ccc8-4007-972d-a88095d84f56)

Verified “Cancel”, “Save & add another”, “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/51c5e645-7b7d-4228-bac2-be4c4555433b)

QA Review Completed.   Moved to Stage Ready.
