### ISSUE TITLE
Allow user to use Lookup within transaction for existing Committee Contact-Part 1

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#538]
Business Reason

The system will employ a Lookup feature when entering transactions in order to allow the user to pull existing contact information from the committee account's Contact Management table. This will also assist the FEC in making more accurate data available to the public.

Acceptance Criteria

_Note: The transaction entry form will _only_ show the contact lookup until a contact is selected. Once a contact is selected, the transaction form will show._

***Given*** the user is entering a transaction with the Entity Type of "COM", whether user-selected or required by transaction type, 

  ***Then*** they will be able to search their committee account's Contact Management table by _name or ID_ using a Lookup feature to find and select an existing contact

  ***And*** the results will including the following information in the dropdown:

*   Committee Name
*   Committee ID
*   "In Contacts"

***And*** the Lookup results will:

*   highlight the matching text from the search box within the results
*   highlight a selection grey if hovered over with the pointer
*   be limited to ***5*** maximum _(Dev/QA note: for now, users need to type more to narrow it down. #542 will address when results are more than 10.)_

***And*** when I select the contact I want, the system will pull in the contact information necessary for the transaction and show the full transaction entry form.

  ***If*** there are no results, the system will indicate as such.

BA notes

FECFile Online basic requirements as follows:

*   Users will be able to search their committee account's Contact Management table using a Lookup feature to find and select an existing contact for a transaction
*   When the user selects the contact, the system will pull in the contact information necessary for the transaction.
*   The transaction will be associated with that contact (used for aggregations/itemization logic)

QA notes

Relevant existing Transactions to test:

*   Joint Fundraising Transfer
*   PAC JF Transfer Memo
*   Other Receipts

NOTE: Other Receipts is Group C therefore Committee ID field is not displayed.

To test, identify an existing committee contact in Contact Management for your committee account and use that ID or name to search.

Wireframes: 

  (Note: down arrow next to "Committee" only if other entity types are valid for selection.)

![image.png]([https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/10bf3724-11d9-40ae-a609-7394adf62bca](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/10bf3724-11d9-40ae-a609-7394adf62bca))

![image.png]([https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/fd722b08-4da2-4075-b699-a956b8b0d2ce](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/fd722b08-4da2-4075-b699-a956b8b0d2ce))

![image.png]([https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/03a3b103-23b2-4476-84d1-5635ad144194](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/03a3b103-23b2-4476-84d1-5635ad144194))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1030](https://fecgov.atlassian.net/browse/FECFILE-1030)

**Comment by WiseQA** [comment]
QA review  of ticket #72 impacts this ticket also.   "Address"  fields not updating when using the lookup and selecting a Contact.

@dheitzer @AureliaKhorsand @GreggMoreland per meeting returning to In-Progress for fix.

**Comment by mjtravers** [comment]
Passes CR, moving to QA

**Comment by WiseQA** [comment]
QA review verified lookup is searchable and contains Committee name and Committee ID and verified In Contacts.  (Note also verified that the highlight a selection grey if hovered over with the pointer.)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/353decd8-dca2-4577-a566-678a06c3a3f1)

Once contact selected verified Contributor fields and Address fields updated with contact information.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/450c3c26-4a1d-4f29-9e72-ae5405b1234e)

During testing the Joint Fundraising Transfer, PAC JF Transfer Memo, and Other Receipts transactions once select "Save and add another" button, a blank receipt is displayed but the "Searchable" field is not clearing out.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/694601e6-0de2-43da-b618-797d4d67fdba)

@dheitzer @MitchellTCG returned to In-Progress for fix 
(Note Ticket #72 will need updated also per our discussion)

**Comment by WiseQA** [comment]
@dheitzer @MitchellTCG 
Joint Fundraising Transfer page doesn't include "Searchable" field.   (See QA notes of transactions included on this ticket that should have "Searchable" field.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b7ae44aa-7744-407f-9ab5-163d7bc18af8)

**Comment by mjtravers** [comment]
Lookup box is now cleared after the user selects a contact and copies it into the the transaction input fields. The lookup box was also added to the JF TRAN screen. Passed CR so sending to QA.

**Comment by WiseQA** [comment]
QA review and verified "Search" field is cleared out once "Save and add another" button is selected.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/13c82576-e4c7-42bc-9240-623d6a33300b)

QA Review completed Joint Fundraising Transfer has a "Searchable" field.

QA verified Joint Fundraising Transfer, PAC JF Transfer Memo and Other Receipts have searchable fields and upon "Save and add another" the searchable field is cleared.

QA Review Completed.   Moved to Stage Ready.
