### ISSUE TITLE
Create automated regression tests for QA scripts (Sprint 12)

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#546]
Business Reason

As a developer or QA, I will be able to automatically run the Sprint-12 test scripts using the Cypress e2e framework so that I can run regression tests in an automated fashion.

Acceptance Criteria

If I want to run the Sprint test scripts to retest the tickets

  When I run the automated tests in the Cypress framework

  Then I will get a report on which scripts failed and which passed

1.  QA Scripts

       #

*   [x] 166

### QA Notes ###
null

### DEV Notes ###
#
Investigate login with Login.gov

### Design ###
null

 See full ticket and images here: [FECFILE-1026](https://fecgov.atlassian.net/browse/FECFILE-1026)

**Comment by Elaine-Krauss-TCG** [comment]
Updated tests are all passing when run as a batch.

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/6ce8a286-57c7-4bcb-880f-d99546b0c06a)

**Comment by Elaine-Krauss-TCG** [comment]
Cypress updated from 9.5.3 to 10.7.0.  End-to-end tests updated to be compatible with the new version and to be compatible with the experimental session updates that will be standard when 11.0 releases early next year.

End-to-end tests were refactored to be more consistent and modestly more performant.

**Comment by mjtravers** [comment]
Passes CR, sending to QA. @WiseQA See comment above to see the screenshot of e2e tests running successfully.

**Comment by WiseQA** [comment]
QA Review verified by inspection per DEV the e2e tests ran successfully.

QA Review Completed.  Moved to Stage.
