### ISSUE TITLE
Allow user to save new Organization contact from Transaction entry to Contact Management-Part 2

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#549]
Business Reason 
 

As a user, if I do not see the Organization contact available in the Lookup (Contact Management) when entering a Transaction, I will be able to enter a new contact in a transaction screen within the Form 3X report and it will save to my committee account's Contact Management so that I can easily pull that contact again in the future using a Lookup. 

 Acceptance Criteria 
 

**Given** a user is entering a transaction with Entity Type "ORG" 
**Then** the user will have the option to create a new Organization contact from within the transaction.
**And when** the user chooses to create a new contact, the system will provide a popup to enter a new contact.

**When** they save the new contact in the popup, the popup will close and the transaction screen will be populated with relevant contact info from that new contact

**When** the user saves the transaction, they must confirm that this will create a new contact in their committee account
**And** the confirmation message will be dynamic and include the contact type and contact name created
**And when** the transaction is saved, a new contact in Contact Management will be created with the contact info from the Create New Contact popup and any edits made on the transaction page itself.

 QA notes 

Relevant existing Transactions to test:
- Tribal Receipt
- Offsets to Operating Expenditures
- Other Receipts

Verify "Cancel" (enabled) "Save & view all transactions" and "Save & add another" buttons (disabled).

 Wireframes: 
(Note: down arrow next to "Organization" only if other entity types are valid for selection.)

Transaction Entry screen before selecting a contact:
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/dacf3ae8-366b-42eb-bda4-ca7904280090)

"Create new Contact" buttons:
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/b83bd1ba-7788-43bc-9ad2-905ef110751f)

![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/b5cf4d56-8f1c-48d9-816a-fe336f6d7266)

![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/97e87f36-bf28-4a40-80c6-9211b782c640)

Creating a new Contact in the popup:
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/5e64ec68-d702-4514-adbb-687daa17617f)

Confirmation message when saving:
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/7c7b2b41-1862-4c04-b599-aef36cf4f99f)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR and released to STAGE server.

**Comment by WiseQA** [comment]
QA review incomplete.     @mjtravers @MitchellTCG returned to 'In-Progress" for the following fixes:

1.  Fix hiding and showing of forms until contact link selected.

2.  Change green button to match what is in wireframe.

 ![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/82c4d129-c331-4262-8407-0cdee62b969f)

3.   Fix display of lookup and Create new contact (spacing issues)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c32ba351-4d2a-4ec7-aa94-eb3adf4645a1)

@mjtravers please add any issues not listed above.

**Comment by mjtravers** [comment]
Contact lookup changes pushed to STAGE. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified following fixes were implemented (See QA comments above):

1.  Fix hiding and showing of forms until contact link selected.
2.  Change green button to match what is in wireframe.
3.  Fix display of lookup and Create new contact (spacing issues)

Test Case/Test Script attached showing ticket “PASS”.

[https://app.zenhub.com/files/306118986/52d1de91-03f0-4f06-a5ae-b9ffa1440adb/download](https://app.zenhub.com/files/306118986/52d1de91-03f0-4f06-a5ae-b9ffa1440adb/download)

Updated Test Script to include verifying "Cancel" (enabled) "Save & view all transactions" and "Save & add another" buttons (disabled). 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f1f3484f-842e-4c24-8743-f393525a5801)

QA review completed.  Moved to Stage Ready.
