### ISSUE TITLE
(Spike) Decide on mechanism of Accessibility evaluation for QASP

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-web-app#55]
The QASP is not specific on the matter of accessibility testing. The assessment method is listed as:

> Combination of manual review and automated testing through an automated tool  such as Lighthouse, SiteImprove Accessibility checker, pa11y or Spectrum chrome plugin.

Before we can generate this metric, we have to decide what tools we want to use for the accessibility evaluation.  The output of this issue will be a that choice.

**Acceptance Criteria**
- [ ] Selection of some number of tools we will use to evaluate the project against the accessibility section of the QASP

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
The mechanism of accessibility evaluation was decided to be by running Lighthouse as part of the e2e scripts. OBE and closing ticket.
