### ISSUE TITLE
Remove old "page two" of Report Creation Workflow

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#550]
Task: Remove "step2" page of report creation, since that data entry has now been moved to the submit report process and the page for adding a report level memo and the page is no longer needed. "Save and Continue" after coverage date selection should lead the user directly to "Manage Transactions".

Acceptance Criteria

***Given*** the user has selected a report type and coverage dates for a new report

  ***When*** they click "save and continue"

  ***Then*** they will be on the "Manage Transactions" page for that new report.

"Save and Continue" button from Create Report page 1:

  ![image.png]([https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/fd5dc96b-9ccc-44af-b376-a3294bb9bb31](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/fd5dc96b-9ccc-44af-b376-a3294bb9bb31))

Current "step two" page to be removed:

  ![image.png]([https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/35ba3909-3e6b-46b2-bb08-a8db9231118f](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/35ba3909-3e6b-46b2-bb08-a8db9231118f))

Manage Transactions page:

  ![image.png]([https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/9e0c262b-e0be-4a63-80cf-cee9878ac9a2](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/9e0c262b-e0be-4a63-80cf-cee9878ac9a2))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1022](https://fecgov.atlassian.net/browse/FECFILE-1022)

**Comment by Elaine-Krauss-TCG** [comment]
Step 2 of the Report creation process has been removed.  All unit tests are passing.

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/5355fafa-aa94-44b1-81f1-b1495673536c)

**Comment by mjtravers** [comment]
One code issue was found in CR. Elaine is making a code change to flatten out a couple of rxjs subscriptions and then will resubmit to CR

**Comment by mjtravers** [comment]
Code change requests have been made. Ticket passes CR and sending to QA

**Comment by WiseQA** [comment]
During QA testing the "Save and Continue" button not working, not taking to next page.   below 2 examples of reports created.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7c6c6d15-4ce2-48ef-8b49-662d5bfba232)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5c9d1d32-957b-41cd-ade8-6a2923b017ee)

@mjtravers  @Elaine-Krauss-TCG Returned to In-progress.

**Comment by Elaine-Krauss-TCG** [comment]
It seems that on dev, cashOnHand is being set to null for some strange reason...

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/007441c6-4198-4dbe-b955-d7ffa5c29185)

**Comment by Elaine-Krauss-TCG** [comment]
After a change, I was able to create a report on Dev.

Clearing your cache will most likely be necessary.

**Comment by WiseQA** [comment]
@mjtravers sent back for Code Review with above change.  
Note:  I cleared my cache and browser several times when testing before.  I will clear again. Thanks

**Comment by mjtravers** [comment]
Passes CR, sending to QA

**Comment by WiseQA** [comment]
QA review verified once report created and then select the "Save and continue" button, the workflow goes to "Manage your transactions" page.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bc640b95-62e5-40eb-bf75-536dc8dd5fcd)

QA Review Completed.   Moved to Stage Ready
