### ISSUE TITLE
Committee Contact Lookup to only show one of each contact 

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#552]
Ensure that the IDs appear only once in the selection dropdown if pulling from both Contact Management and FEC, favoring the Contact Management occurrence.

Business Reason

Users should always select an existing contact from their committee accounts Contact Management table over creating a new one from the FEC registered database. To limit confusion in this regard, we should not show a Committee/Candidate contact in the FEC lookup results if the ID matches one existing in the contact management table.

Acceptance Criteria

***If*** the user uses the Committee Contact lookup, 

  ***Then*** the FEC Lookup results should only show Committee results that do _not_ have a matching Committee ID within the Contact Management Lookup.

### QA Notes ###

If you have save a committee to your Contacts previously,  your contact should not appear in  both the Contacts and FEC lookup section at the same time.

(This ticket is for Committee only, as we cannot yet test Candidate. However, the same logic will apply there).

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1021](https://fecgov.atlassian.net/browse/FECFILE-1021)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA review verified Committee Contact lookup if a previous contact then your contact should not appear in both the Contacts and FEC lookup section at the same time.  (See below screenshots).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/da7f9a04-8dd9-465c-9c71-6e33fea814af)


![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f430aa11-738a-4451-91e8-35a1110181f0)

QA Review Completed.   Moved to Stage Ready.
