### ISSUE TITLE
Add Footer to Website

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#553]
Business Purpose

As the CIO of FEC, I would like a footer so the site meets Federal regulations.

Acceptance Criteria

The Footer has two parts:

1.  The Upper footer:

       #

       Height: 80px

       Background color: #E8E8E8

1.  1.  Column 1:

             ##
        ***Need help? Contact your RAD Analyst*** [Karla - Bold - 18pt - #212121](#212121)
        John Doe (888) 888-8888 [Karla - Italic - 18pt - #212121](#212121)

             ***Need help? Contact us*** [Karla - Bold - 18pt - #212121](#212121)

             (this above will be dynamically generated in a later ticket)

1.  1.  Column 2

             ##

             ***Feedback*** [Karla - Bold - 18pt - #212121](#212121)

             (This will not be linked. The Feedback link will be in another ticket)

1.  1.  Column 3

             ##

             ***Legal disclaimer*** [Karla - Bold - 18pt - #212121](#212121)

             (This will not be linked. The Legal Disclaimer link will be in another ticket)

1.  The Lower footer:

       #

       Height: 234px

       Background color: #164F85

1.  1.  Column 1

             ##

             ***FEC Seal:***
        [Logo below or download from https://www.fec.gov/static/img/seal--inverse.svg - please make 100px by 100px]

***Text:***

  Federal Election Commission [Gandhi Serif - Bold - 22pt - #FFFFFF](#FFFFFF)

  1050 First Street, NE Washington, DC 20463 [Karla - Regular - 14pt]

1.  1.  Column 2

             ##

             ***Hyperlink 1:*** Privacy and security policy [Karla - Regular - 16pt - #FFFFFF](#FFFFFF)

             URL: [https://www.fec.gov/about/privacy-and-security-policy/](https://www.fec.gov/about/privacy-and-security-policy/)

***Hyperlink 2:*** Plain language [Karla - Regular - 16pt - #FFFFFF](#FFFFFF)

  URL: [https://www.fec.gov/about/plain-language/](https://www.fec.gov/about/plain-language/)

***Hyperlink 3:*** No FEAR Act [Karla - Regular - 16pt - #FFFFFF](#FFFFFF)

  URL: [https://www.fec.gov/about/no-fear-act/](https://www.fec.gov/about/no-fear-act/)

***Hyperlink 4:*** Strategy, budget, and performance [Karla - Regular - 16pt - #FFFFFF](#FFFFFF)

  URL: [https://www.fec.gov/about/reports-about-fec/strategy-budget-and-performance/](https://www.fec.gov/about/reports-about-fec/strategy-budget-and-performance/)

1.  1.  Column 3

             ##

             ***Hyperlink 1:*** Open government [Karla - Regular - 16pt - #FFFFFF](#FFFFFF)

             URL: [https://www.fec.gov/about/open/](https://www.fec.gov/about/open/)

***Hyperlink 2:*** Protect Voices [Karla - Regular - 16pt - #FFFFFF](#FFFFFF)

  URL: [https://www.fbi.gov/investigate/counterintelligence/foreign-influence/protected-voices](https://www.fbi.gov/investigate/counterintelligence/foreign-influence/protected-voices)

***Hyperlink 3:*** USA.gov [Karla - Regular - 16pt - #FFFFFF](#FFFFFF)

  URL: [https://www.usa.gov/](https://www.usa.gov/)

***Hyperlink 4:*** Inspector General [Karla - Regular - 16pt - #FFFFFF](#FFFFFF)

  URL: [https://www.fec.gov/office-inspector-general/](https://www.fec.gov/office-inspector-general/)

***Hyperlink 5:*** FOIA [Karla - Regular - 16pt - #FFFFFF](#FFFFFF)

  URL: [https://www.fec.gov/freedom-information-act/](https://www.fec.gov/freedom-information-act/)

Dev Notes

All links should open in a new tab.

![Screen Shot 2022-09-02 at 3.13.48 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/df10281d-237f-4bcd-8236-d68125369478](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/df10281d-237f-4bcd-8236-d68125369478))

![seal--inverse.svg]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d6e582f8-c4c6-4618-90db-039806571121](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d6e582f8-c4c6-4618-90db-039806571121))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1020](https://fecgov.atlassian.net/browse/FECFILE-1020)

**Comment by MitchellTCG** [comment]
@JonellaCulmer 
Please review this ticket

**Comment by Elaine-Krauss-TCG** [comment]
Footer implemented according to specs with no complaints from ANDI
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/3f1e75d6-0242-4220-87ac-9e4f437034b9)

**Comment by Elaine-Krauss-TCG** [comment]
All unit tests passing
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/acced53d-e04a-48ef-85b1-7eb199552f1a)

**Comment by mjtravers** [comment]
There is a white padding around the footer left, bottom, and right side that does not appear in the wire frame. Here is a screen shot showing the extra padding when the footer blue should to to the left, right, and bottom edges
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/73c3a144-9343-4577-9da5-70caa46c7741)
Sending back to In Progress

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by MitchellTCG** [comment]
@Elaine-Krauss-TCG 
PLease update "Need help? Contact your RAD Analyst" with "Contact us"
And get rid of the phone number per this wireframe

![Screen Shot 2022-10-06 at 10.22.21 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/3b89d99d-a48d-4cb2-85ba-ff47f0ab0413)

**Comment by Elaine-Krauss-TCG** [comment]
Footer updated accordingly
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/c4f4d90e-a4a8-449a-93a2-3a997193cbb8)

**Comment by mjtravers** [comment]
Passes CR, moving to QA

**Comment by MitchellTCG** [comment]
### TESTING: App553 ###
Following Links work and resolve to the correct links:
- [x] Privacy and security policy
- [x] Plain language
- [x] No FEAR Act
- [x] Strategy, budget, and performance

- [x] Open government
- [x] Protect Voices
- [x] USA.gov
- [x] Inspector General
- [x] FOIA

The following Text is correctly placed and phrased
- [x] Feedback
- [x] Legal Disclaimer
- [x] LOGO
- [x] Federal Election Commission (title)
- [x] 1050 First Street, NE Washington, DC 20463 (address)

**Comment by MitchellTCG** [comment]
### App553 — FAILED ### 
@Elaine-Krauss-TCG  Please make the following updates _(do not check the boxes, I will when i retest the issue)_

- [ ] Please change "Contact us" to "Need help? Contact us" (this is my fault UX)
- [ ] Please change "Need help? Contact us", "Feedback", and "Legal Disclaimer" from Karla (regular) to Karla (bold). I believe karla-bold should work.
- [ ] Somewhere in the ng packet the fonts are being overwritten by a relative sizing (em or rem) causing the pt (points) to be bigger than expected. Please change all "pt" to "px"
Update the following:
    - [ ] "Need help? Contact us", "Feedback", and "Legal Disclaimer" change from 18pt to **18px**
    - [ ] "Federal Election Commission" change from 22pt to **22px**
    - [ ] "1050 First Street, NE Washington, DC 20463" change from 14pt to **14px** 
    - [ ] Change ALL hyperlinks in columns 2 and 3 from 16pt to **16px** 
- [ ] Lastly change "Protect Voices" to "Protected Voices"  (this is also UX fault. I missed the "ed". The wireframe was wrong. Sorry.)

**Comment by Elaine-Krauss-TCG** [comment]
- "Contact us" -> "Need help? Contact us"
 - Upper footer text changed from being wrapped in \<strong\> to using the karla-bold font
 - All instances of "pt" font sizing in the footer changed to "px"
 - "Protect" -> "Protected"

**Comment by mjtravers** [comment]
Passes CR, sending to QA

**Comment by MitchellTCG** [comment]
### App553 — PASSED ### 
@Elaine-Krauss-TCG  Please make the following updates _(do not check the boxes, I will when i retest the issue)_

- [x] "Contact us" changed to "Need help? Contact us" 
- [x] "Need help? Contact us", "Feedback", and "Legal Disclaimer" changed from Karla (regular) to Karla (bold).
The following were updated:
    - [x] "Need help? Contact us", "Feedback", and "Legal Disclaimer" change from 18pt to **18px**
    - [x] "Federal Election Commission" change from 22pt to **22px**
    - [x] "1050 First Street, NE Washington, DC 20463" change from 14pt to **14px** 
    - [x] Change ALL hyperlinks in columns 2 and 3 from 16pt to **16px** 
- [x] "Protect Voices" changed to "Protected Voices"
