### ISSUE TITLE
Setup mock Login.gov process for e2e tests

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#557]
To allow for e2e tests to log into the test site and run the e2e tests, Cypress needs to be able to get past the Login.gov process. The strategy decided upon is to create a feature flag that turns on a streamlined version of the "old" login process. This streamlined version will simply consist of a REST endpoint the grants access and does not include any front-end screens that need to be accessed by a browser.

DEV NOTE: See if Django has a test suite has a session generator to create the session other than using the existing code.

*   *   Acceptance Criteria**
*   Cypress e2e tests log into the site through a mock login REST endpoint
*   The mock login REST endpoint can be "turned off" via a Cloud.gov environment variable and coded feature flag
*   The feature flag is turned off by default so that the mock login REST endpoint is not accessible by default

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-1018](https://fecgov.atlassian.net/browse/FECFILE-1018)

**Comment by Elaine-Krauss-TCG** [comment]
- Cypress tests now log in directly through the API.
 - The local login process (as opposed to login.gov) has been refactored and is now a one-step process.
 - Local logins are disabled by default, only being enabled on Local and on the hypothetical future E2E environment.
 - The local login form is hidden by default and becomes available after checking for its availability with the API.

**Comment by mjtravers** [comment]
Passes CR and code pushed to STAGE. Sending to QA

**Comment by WiseQA** [comment]
QA review verified Login entering Email, Committee ID, Password:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/aa2c3abe-b87a-4d2a-ac1f-9ef39d65b547)

Select Enter button verify Committee ID and dashboard are displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e31c6e93-8610-471b-adeb-7831d5794d33)

QA Review Completed.   Moved to Stage Ready.
