### ISSUE TITLE
Add static code analysis to JavaScript and Python code

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-web-app#56]
**User Story**
As a developer/QA,
I would like to get a code quality report on each commit based on static code analysis
so that I can ensure our code is meeting quality standards described in the QASP.

**Acceptance Criteria**
* On each build in the CI pipeline, static code analysis is run
* The pipeline should be configured to fail the build if any medium or high security vulnerabilities are found
* The CI pipeline should be configurable to disable the build failure in the case of medium/high findings. 
* Specific tools used are not defined as part of the AC but suggestions include Bandit or SonarQube
* AC above apply to TypeScript/JavaScript and Python code in any active fecfile repository

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
The functionality of this ticket may be covered by SonarQube. Leaving this ticket in Product Backlog for further review after SonarQube is set up and running.

**Comment by mjtravers** [comment]
SonarCloud provides a report in the PR during each commit. The report links can be clicked on to drill down into report statistics
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/7c3ed73f-20bb-4fbf-bc1e-8f81f03aad93)
Closing ticket.
