### ISSUE TITLE
Allow user to download a .FEC file from the Manage Reports Page

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#560]
As a user, I will be able to generate and view a *.fec file of my report so that I can see how the Form 3X will output to FEC and troubleshoot as needed.

Acceptance Criteria 

  Dev Notes

*   [ ] set up record tied to report to track state of .fec compilation (should be akin to webprintsubmission and uploadsubmission records)
*   [ ] query reports to see status of dot_fec_task for each report, show download rows for each report that has a task

The grey block is a drawer that slides up from the bottom.

1\. "Your downloads"

  font: karla regular

  hex: #112e51

  size: 16pt

2\. "schedule_a-2022-09-14..." / [name of file downloading] 

  font: karla regular

  hex: #112E51

  size: 12pt

3\. Drawer background color: #F1F1F1

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/cecd2fe9-3012-480a-8b33-b7db3239ab3c](https://github.com/fecgov/fecfile-web-app/assets/25588182/cecd2fe9-3012-480a-8b33-b7db3239ab3))

  ***Above: The user is waiting for their download to process. The 3 dots will be animated, a .gif borrowed from FEC.***

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/7756361b-a4e3-4d6b-a1b3-60ed2b9d2c72](https://github.com/fecgov/fecfile-web-app/assets/25588182/7756361b-a4e3-4d6b-a1b3-60ed2b9d2c7))

  ***Above: The download has completed and the 'download' button is available. The 3-dots gif has changed to a checkmark.***

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/da84db89-2f03-4fb8-99ca-b9e5d90d38d4](https://github.com/fecgov/fecfile-web-app/assets/25588182/da84db89-2f03-4fb8-99ca-b9e5d90d38d))

  ***Above: Multiple downloads show on the same screen. They keep stacking***

[https://images.zenhubusercontent.com/306118986/854f1e70-ba3a-4311-bea1-97abf05d1a30/exportvideo.mov](https://images.zenhubusercontent.com/306118986/854f1e70-ba3a-4311-bea1-97abf05d1a30/exportvideo.mov)

### QA Notes ###
 
 null

### DEV Notes ###
 
 null

### Design ###
 
 **Given** a report in any status
**When** the user opens the action icon to the right of a report on the Manage Reports page
**Then** they will have the option to download a .fec file
**And** when they click to download the .fec file, they will receive a message stating "We are preparing your download. Your wait will vary depending on how many records you requested and how many downloads we are processing"
**And when** the file is ready to download, they will have the option to download the .fec file.

**Design ACs**
- The user can click the X next to a single download at any time to cancel the relevant download, and if no downloads are in progress, the tray will close.
- The tray persists if the user changes page (but will disappear if the user logs out),
- The downloads stack in the tray if the user chooses to download more than one at a time.

 See full ticket and images here: [FECFILE-1017](https://fecgov.atlassian.net/browse/FECFILE-1017)

**Comment by MitchellTCG** [comment]
Here are components for the Export Drawer:
![loading-ellipsis.gif](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a47ee9a8-3335-4207-a19c-7faabad41602)

![Check.svg](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/3414dae4-6673-4d28-a3e2-0f0b3a70b988)

![X.svg](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/fdcbbdbc-26d8-4560-a804-d6f527b9fc4f)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
I think we have delivered everything you and the devs need. Back in your court to complete the AC.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
I added a wire. I think you were only waiting for the multiple downloads wireframe.

**Comment by AureliaKhorsand** [comment]
Moving back to AA since this was in ASA for a long time. It's currently marked as needed for Production release in the roadmap. Need to confirm with FEC, then go through design and Dev/QA review again to update.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by MitchellTCG** [comment]
@sasha-dresden 
Please make sure the feedback button in on a higher z-index than the .fec drawer

I just updated the wireframes

**Comment by WiseQA** [comment]
QA review selected "Download as .fec" from the "Manage reports" "Actions" dropdown for a Form 1M report

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/648f30e8-9d7c-4063-8ca9-ceca2670406b)

________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/432fbdf6-a6d9-4665-9e12-ff87a0f6bf98)

________________________________________________________________________________________________________________

Selected  "Download as .fec" from the "Manage reports" "Actions" dropdown for a Form 3X report   Verified the "Feedback"  button is on a higher z-index than the .fec drawer per UX comment above.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/889c00b6-1b63-4d78-adac-5eef99c6c51c)

____________________________________________________________________________________________________________________

Select "Download" button verify file name is displayed for download

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/da5a3672-6171-4882-9ba5-d954cf5bfb71)

_____________________________________________________________________________________________________________________

Select the "X" icon to delete / remove any downloads from the list.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/d76b0352-bd86-47e8-8e4f-ce51c10ef02c)

________________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
