### ISSUE TITLE
Eliminate ngModel from reactive form

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#562]
We're getting a depreciation warning in unit tests for the ngModel attribute in the Transaction Group F HTML template.

Here is the warning:

![image.png]([https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/21d32c3f-f4ea-495f-ab94-94514dc7ee5a](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/21d32c3f-f4ea-495f-ab94-94514dc7ee5a))

Here is the line of code causing the warning:

[https://github.com/fecgov/fecfile-web-app/blob/develop/front-end/src/app/transactions/transaction-group-f/transaction-group-f.component.html#L151](https://github.com/fecgov/fecfile-web-app/blob/develop/front-end/src/app/transactions/transaction-group-f/transaction-group-f.component.html#L151)

***Acceptance Criteria***

  To be able to create/edit a transaction in Group F (JF_TRAN_PAC_MEMO) with the MEMO ITEM checkbox working correctly without the use of the ngModel attribute.

***QA Notes***

  To pass QA, the MEMO ITEM checkbox on a Group F transaction (JF_TRAN_PAC_MEMO) should save the checkmark as expected when the transaction is created or updated.

### QA Notes ###
Here is the warning:

![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/21d32c3f-f4ea-495f-ab94-94514dc7ee5a)

Here is the line of code causing the warning:

https://github.com/fecgov/fecfile-web-app/blob/develop/front-end/src/app/transactions/transaction-group-f/transaction-group-f.component.html#L151

**Acceptance Criteria**
To be able to create/edit a transaction in Group F (JF_TRAN_PAC_MEMO) with the MEMO ITEM checkbox working correctly without the use of the ngModel attribute.

**QA Notes**
To pass QA, the MEMO ITEM checkbox on a Group F transaction (JF_TRAN_PAC_MEMO) should save the checkmark as expected when the transaction is created or updated.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1016](https://fecgov.atlassian.net/browse/FECFILE-1016)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA Review cannot verify this change.   Need screenshot of warning fixed and unit test passed.  The only thing in this ticket is showing the warning screen where failed.   To pass QA, the MEMO ITEM checkbox on a Group F transaction (JF_TRAN_PAC_MEMO) should save the checkmark as expected.   Sending back to in-progress.

**Comment by dheitzer** [comment]
![image.png](https://images.zenhubusercontent.com/6298ce840c1c301e7c4a4151/14d45423-0d8e-450b-96ff-d7653dc1599e)

**Comment by WiseQA** [comment]
QA review passed as a visual inspection of test was run successfully and passed as denoted in screenshot above by DEV.

QA Visual Inspection Completed.   Moved to Stage Ready.
