### ISSUE TITLE
System to calculate Aggregate/Itemization for "Earmark Receipt" (Group A), "Earmark Memo" (Group G)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#565]
Business Reason

The Aggregate field must display the total of the entity's contributions from the calendar year of the report. This is necessary to track contribution limits as well as itemization logic. This amount will be a _rolling total_.

Acceptance Criteria

For the following transactions:

1\. Earmark Receipt (Group A)

  2\. Earmark Memo (Group G)

AGGREGATE fields must meet the following criteria:

*   AMT-12, Required, Read-Only, Currency amount
*   Can be negative
*   Amount Displayed will be the total of contributions that are: 
      *   From the person (ENTITY) 
            *   *   within Aggregation Group of "GENERAL"**
    *   _from_ January 1 of report year _to_ the Contribution Date* of the transaction.
    *   *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

***And*** when saving a transaction, any subsequent transactions for the same entity will update. (E.g., if a previous transaction receipt amount is _changed_, it will affect the future aggregations).

***And*** the transactions will be itemized upon saving, with their own line items on the *.fec file.

### QA Notes ###

Aggregation:
1. create an individual contact and a committee contact
2. create an individual receipt and a jf transfer using the contacts made in step 1
    and
    create an "other receipts" for both contacts
3. create an earmark memo and earmark receipt using the contacts made in step 1 with contribution dates after the transactions made in step 2.
4. verify on the transaction list page that:
  * the earmark receipt aggregate includes the amount from both the individual receipt and the earmark receipt but not the other receipt (because earmark memo and individual receipt are in the "GENERAL" group and other receipt is in the "OTHER_RECEIPTS" group)
  * the earmark memo aggregate includes the amount from both the jf transfer and the earmark memo but not the other receipt (because earmark memo and jf transfer are in the "GENERAL" group and other receipt is in the "OTHER_RECEIPTS" group)

Itemization:
both earmark receipt and earmark memo should be itemized no matter the aggregation amount.
* Easiest way to check: On the transaction list page, they should never say "Unitemized" in the first column even if the aggregate is below $200
* In-depth check:  
  * Download the .fec by clicking the second green button on the report list page, click generate .fec, wait 5 seconds, click download .fec.  Open the .fec in notepad.  
  * There should be a row with "Earmarked through " near the end of the line.  That's the earmark receipt.
  * There should be a row with "Total earmarked through conduit." that's your earmark memo.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1015](https://fecgov.atlassian.net/browse/FECFILE-1015)

**Comment by Elaine-Krauss-TCG** [comment]
The requirements of this ticket seem to be met by existing code

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/815cd05c-5298-43bf-90c0-f1f558b39987)

**Comment by mjtravers** [comment]
No new code branch for this ticket as code development was completed on previous tickets. Sending to QA.

**Comment by mjtravers** [comment]
Pulling back to In Progress to add more unit test code coverage.

**Comment by MitchellTCG** [comment]
@WiseQA @mjtravers 
This was developed and CR'd under 459 & 460

This code is currently on DEV

**Comment by mjtravers** [comment]
New unit testing has been implemented. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG ticket on-hold.  
11/01/2022 - QA notes completed.   As discussed this will be e2e testing.

**Comment by WiseQA** [comment]
QA adhoc testing completed on this ticket.   No test script written - e2e testing to satisfy this ticket.

Per DEV this functionality was completed in Code branch when Aggregate/Itemization were created,  Refer to DEV comments this was developed and CR'd under 459 & 460.

This code is currently on DEV

QA Review Completed.  Moved to Stage Ready.
