### ISSUE TITLE
Package dependency analysis for web application code

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-web-app#57]
**User Story**
As a developer/QA,
I would like to have dependencies checked for known vulnerabilities on each commit 
so that I can ensure our code is meeting quality standards described in the QASP.

**Acceptance Criteria**
- [x] On each build in the CI pipeline, dependency checking is run
- [x] The pipeline should be configured to fail the build if any medium or high security vulnerabilities are found
- [x] The tool used should be capable and configured to allow for delays of package updates/patching
- [x] Safety should be used for Python code
- [x] Snyk should be used for Javascript packages
- [x] AC above apply to TypeScript/JavaScript and Python code in fecfile-web-app, fecfile-web-api, fecfile-validate
- [x] Test fails will be left as is for now

**QA:** Verify that the dependency check ran in CircleCI [here](https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/146/workflows/eab1d619-6257-43cf-86c0-44aa035a87e5/jobs/575). Note that the Snyk test found issues and failed but the requirement for this issue is that it ran, not whether it passed the tested packages or not.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by WiseQA** [comment]
Verified dependency check ran. Unit test "failed" as denoted in Acceptance Criteria for this ticket.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/592f39fd-80e4-4b13-aed7-2bbdf70a548f)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b0b9323c-117a-407c-9fb5-ab543634b7c0)

QA review completed.  Moved to Stage Ready.
