### ISSUE TITLE
Update label names for each Transaction Group

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#570]
Task: Make the following updates to field names:

***Group A Transactions (Individual Receipt):***

*   [x] Section Header for contact should be "Contact" (changed from "Contributor")
*   [x] "Contributor Type" should be "Contact Type"
*   [x] Section header for receipt should be "Receipt Information" (changed from "Contribution")
*   [x] "Contribution Amount" should be "Amount"
*   [x] "Contribution Aggregate" should be "Aggregate

***Group B Transactions (Offsets to Operating Expenditures):***

*   [x] Section Header for contact should be "Contact" (changed from "Contributor")
*   [x] "Contributor Type" should be "Contact Type"
*   [x] Section header for receipt should be "Receipt Information" (changed from "Contribution")
*   [x] "Contribution Amount" should be "Amount"
*   [x] "Contribution Aggregate" should be "Aggregate"

***Group C Transactions (Other Receipt):***

*   [x] Section Header for contact should be "Contact" (changed from "Contributor")
*   [x] "Contributor Type" should be "Contact Type"
*   [x] Section header for receipt should be "Receipt Information" (changed from "Contribution")
*   [x] "Contribution Amount" should be "Amount"
*   [x] "Contribution Aggregate" should be "Aggregate"

***Group D Transactions (Tribal Receipt):***

*   [x] Section Header for contact should be "Contact" (changed from "Contributor")
*   [x] "Contributor Type" should be "Contact Type"
*   [x] Section header for receipt should be "Receipt Information" (changed from "Contribution")
*   [x] "Contribution Amount" should be "Amount"
*   [x] "Contribution Aggregate" should be "Aggregate"

***Group E Transactions (Joint Fundraising Transfer):***

*   [x] Section Header for contact should be "Contact" (changed from "Contributor")
*   [x] "Contributor Type" should be "Contact Type"
*   [x] Section header for receipt should be "Receipt Information" (changed from "Contribution")
*   [x] "Contribution Amount" should be "Amount"
*   [x] "Contribution Aggregate" should be "Aggregate"

***Group F Transactions (PAC Joint Fundraising Transfer Memo):***

*   [x] Section Header for contact should be "Contact" (changed from "Contributor")
*   [x] "Contributor Type" should be "Contact Type"
*   [x] "Contributor Committee" should be "Committee Name"
*   [x] "Contributor FEC ID" should be "Committee ID"
*   [x] Section header for receipt should be "Receipt Information" (changed from "Contribution")
*   [x] "Contribution Amount" should be "Amount"
*   [x] "Contribution Aggregate" should be "Aggregate"

(Note: Group G Transaction (Earmark) is addressed in #460 and will be tested in #460)

### QA Notes ###
Transactions that need testing (as of 10/13/22)

- Individual Receipt
- Tribal Receipt
- Earmark Receipt (Tested in Ticket #460)
- Joint Fundraising Transfer
- PAC JF Transfer Memo
- Offset to Operating Expenditures
- Other Receipts

(Note:  Groups A-E should have same label changes - Group F will have additional label changes)

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1013](https://fecgov.atlassian.net/browse/FECFILE-1013)

**Comment by mjtravers** [comment]
Passes CR, sending to QA.

**Comment by WiseQA** [comment]
QA review verified label names for each transaction group (as denoted in Acceptance Criteria) has been changed:
1. Group A Transactions (Individual Receipt)
2. Group B Transactions (Offsets to Operating Expenditures)
3. Group C Transactions (Other Receipt)
4. Group D Transactions (Tribal Receipt)
5. Group E Transactions (Joint Fundraising Transfer
6. Group F Transactions (PAC Joint Fundraising Transfer Memo)
7. Group G Transaction (Earmark) (tested in ticket #460

QA Review Completed.  Moved to Stage Ready
