### ISSUE TITLE
Defect - When selecting "Save and Add More" for additional contacts the Telephone (Optional) field not clearing

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#576]
This defect is to correct when selecting the "Save and Add More" for additional contacts the Telephone (Optional) field not clearing. (Note: This error occurs when entering any of the contacts).

1\. Enter an "Individual" contact including the Telephone number (Optional):

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2cb36ece-2d46-489c-b060-b3cf061d608a](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2cb36ece-2d46-489c-b060-b3cf061d608a))

2\. Select "Save and Add More" button blank contact page is displayed, but the Telephone number field IS NOT cleared.

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c8581f65-7f0b-4556-8c1e-508362891900](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c8581f65-7f0b-4556-8c1e-508362891900))

3\. Upon manually clearing the Telephone number field, the Telephone number field then becomes "Required" and a phone number has to be entered to "Save" and/or "Save and Add More".

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dcaf1be1-1862-4e81-b628-ed60b878d4db](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dcaf1be1-1862-4e81-b628-ed60b878d4db))

Additional Error - when tabbing between contact fields the Telephone number field then becomes "Required" and a phone number has to be entered.

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/36e69b89-3379-4203-aba6-c92ecd555fa1](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/36e69b89-3379-4203-aba6-c92ecd555fa1))

1.  1.  QA NOTES ##

             Note the Telephone Number (Optional) field error became evident after adding the International dropdown for telephone numbers.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1011](https://fecgov.atlassian.net/browse/FECFILE-1011)

**Comment by toddlees** [comment]
In regards to the additional error ("This field must contain 10..."), this is almost certainly caused by an empty string `''` in the phone number, which is a value (so passing 'required' but failing 'length' rule).  One solution to this is map `''` to `undefined` before validation

**Comment by MitchellTCG** [comment]
@toddlees 
### App #576 — PASSED ###

When I typed in a contact I saw 555-555-1000 as the phone number:
![Screen Shot 2022-10-10 at 8.57.28 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/29d7fa0a-2db9-4cfe-a7b8-b7c4b36dbf09)

After clicking Save & add more, I received a successful message, ALL FIELDS were cleared as displayed below, and the contact was saved as expected:
![Screen Shot 2022-10-10 at 8.57.35 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a841c5b9-d4fd-4e78-ae58-2a67c81e3c31)
