### ISSUE TITLE
Remove extraneous left-hand nav bar

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#583]
Businuess Case

As a UX designer, I would like the extraneous 300px wide blue nav bar from pages that have a workflow nav so the user can regain some screen real estate.

Acceptance Criteria

Please remove the 300px Blue Nav from the following pages:

1.  1\. Dashboard

       #

       A. Dashboard Page

*   [https://fecfile-web-app-prod.app.cloud.gov/dashboard](https://fecfile-web-app-prod.app.cloud.gov/dashboard)

       ***Change from:***

       ![Screen Shot 2022-10-31 at 8.31.44 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/145f7dd6-52dd-423c-b62a-37978006eb83](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/145f7dd6-52dd-423c-b62a-37978006eb83)) 

       ***Change to:***

       ![Screen Shot 2022-10-31 at 8.31.30 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7e5a2499-d4e9-47c5-83cc-b39f8f8eefaa](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7e5a2499-d4e9-47c5-83cc-b39f8f8eefaa))

1.  2\. Reports

       #

       A. Manage Reports Page

*   [https://fecfile-web-app-prod.app.cloud.gov/reports](https://fecfile-web-app-prod.app.cloud.gov/reports)

       ***Change from:***

       ![Screen Shot 2022-10-31 at 8.33.11 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ba8cbb7f-e642-4695-bf37-178cfc1cd5f9](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ba8cbb7f-e642-4695-bf37-178cfc1cd5f9))

       ***Change to:***

       ![Screen Shot 2022-10-31 at 8.33.02 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/27fe6a3e-26f1-4ff1-9d89-17485644b27e](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/27fe6a3e-26f1-4ff1-9d89-17485644b27e))

B. Create a new report

*   [https://fecfile-web-app-prod.app.cloud.gov/reports/f3x/create/step1](https://fecfile-web-app-prod.app.cloud.gov/reports/f3x/create/step1)

       ***Change from:***

       ![Screen Shot 2022-10-31 at 8.32.38 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0e9760d4-20d5-442b-8a39-eec0a3d5d2a4](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0e9760d4-20d5-442b-8a39-eec0a3d5d2a4))

       ***Change to:***

       ![Screen Shot 2022-10-31 at 8.32.46 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4273b2a0-7132-4c16-addc-ee3e85beec07](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4273b2a0-7132-4c16-addc-ee3e85beec07))

1.  3\. Contacts

       #

       A. Manage Contacts

*   [https://fecfile-web-app-prod.app.cloud.gov/contacts](https://fecfile-web-app-prod.app.cloud.gov/contacts)

       ***Change from:***

       ![Screen Shot 2022-10-31 at 8.33.11 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/bc064947-681e-457d-95b5-3415198cd2f5](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/bc064947-681e-457d-95b5-3415198cd2f5))

       ***Change to:***

       ![Screen Shot 2022-10-31 at 8.33.02 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/37f37a4e-5869-47d2-9660-74361fa02dbe](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/37f37a4e-5869-47d2-9660-74361fa02dbe))

1.  4\. Profile

       #

       A. Account Info

*   [https://fecfile-web-app-prod.app.cloud.gov/profile/account](https://fecfile-web-app-prod.app.cloud.gov/profile/account)

       ***Change from:***

       ![Screen Shot 2022-10-31 at 8.33.43 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f0f774d0-a5a7-40bf-8a15-cbb8765296c2](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f0f774d0-a5a7-40bf-8a15-cbb8765296c2)) 

       ***Change to:***

       ![Screen Shot 2022-10-31 at 8.33.50 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4879126e-c714-4864-97a6-d78d2e40bfde](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4879126e-c714-4864-97a6-d78d2e40bfde))

B. Manage Users

*   [https://fecfile-web-app-prod.app.cloud.gov/profile/account](https://fecfile-web-app-prod.app.cloud.gov/profile/account)

       ***Change from:***

       ![Screen Shot 2022-10-31 at 8.49.34 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f9bfa59f-cf23-480e-9ef9-ea62a2e45109](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f9bfa59f-cf23-480e-9ef9-ea62a2e45109))

       ***Change to:***

       ![Screen Shot 2022-10-31 at 8.49.40 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/b1588c67-a68f-43cf-81da-4bc3c35e817f](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/b1588c67-a68f-43cf-81da-4bc3c35e817f))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1006](https://fecgov.atlassian.net/browse/FECFILE-1006)

**Comment by MitchellTCG** [comment]
@mjtravers @WiseQA 

Can you two please let me know if this is clear enough?

**Comment by mjtravers** [comment]
> @mjtravers @WiseQA
> 
> Can you two please let me know if this is clear enough?

Which is a better way to look at this as more pages are added to the site: the left navigation is there or it is hidden? If it is hidden by default, it would be better to list the pages where the left nav is present rather than absent.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Wires added

@mary-tcg @JonellaCulmer 
Please review

**Comment by Elaine-Krauss-TCG** [comment]
Functionality implemented per AC.  The Dashboard, Contacts, Reports, and Profile pages no longer display the sidebar.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/0f970fd6-d38a-4f3a-8010-8c6a68fcb475)

**Comment by mjtravers** [comment]
Sending back to In Progress so that the resolver solution as discussed in the PR can be implemented.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the left-hand nav bar has been removed from the following:

**Dashboard**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/00635c73-31c5-4071-9d12-405c5481295e)

**Reports > Manage Reports Page**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d3486685-a948-4cce-8360-5e970d94d67f)

**Create a new report**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cfb44f91-8d6a-4805-af85-3d7b43a76131)

**Contacts > Manage Contacts**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7e82b61a-f21c-445b-b9b9-32b8c2acec1c)

**Profile > Account Info**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/20d5afc2-8adf-4728-941f-24dd0fff58c7)

**Profile > Manage Users**

**Comment by WiseQA** [comment]
During testing of Profile > Manage Users to verify Nav Bar has been removed.   Received the following error.   Cleared cookies / cache, retested and still received same error.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0034a2bd-6314-47be-86c8-9c78773c36aa)

@mjtravers @Elaine-Krauss-TCG moving back to In-Progress for fix.

**Comment by WiseQA** [comment]
Bug #386 created for the above error fix.   This ticket will be retested upon fix of bug.

**Comment by WiseQA** [comment]
QA review verified the Nav Bar has been removed from the Profile > Manage Users page.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3b1a78e9-e2bf-4bf8-8f5f-01d3938bd6c7)

Bug #386 has been fixed as mentioned above.

QA Review Completed.   Moved to Stage Ready.
