### ISSUE TITLE
Update Transaction Table to show full transaction names and updated column headers

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#587]
Business Reason

As a RAD SME, I would like the full name of transactions written out on the "Transactions during coverage dates" table on the Manage your transactions page within a report.

Acceptance Criteria

1\. Under the "Transaction Type" Column, any transaction listed should show the full transaction name, wrapped to accommodate column width.

  2\. Change "CONTRIBUTOR NAME" to "NAME"

  3\. Change "CONTRIBUTION AMOUNT" to "AMOUNT"

  4\. Change "CONTRIBUTION AGGREGATE" to "AGGREGATE"

### QA Notes ###

Validate names here:
https://docs.google.com/spreadsheets/d/1gdcvYQBFMeCGt-1NfVuaSTsB0sB-dl2N/edit#gid=1395788914

![Transaction page without ellipses.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/c47d9e05-df8b-49a4-90a7-6fa1c29a65a1)

### DEV Notes ###

Use the existing label pipe as used in transaction-type-picker

Source of truth for transaction names is Master Transaction Spreadsheet [here](https://docs.google.com/spreadsheets/d/1gdcvYQBFMeCGt-1NfVuaSTsB0sB-dl2N/edit#gid=1395788914). 

### Design ###
null

 See full ticket and images here: [FECFILE-1005](https://fecgov.atlassian.net/browse/FECFILE-1005)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG where is this requirement from?

**Comment by AureliaKhorsand** [comment]
@MitchellTCG should we have some design in here to account for super long names?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
I added the wire to the ticket with some dev notes

@JonellaCulmer @mary-tcg Please review

**Comment by JonellaCulmer** [comment]
@MitchellTCG I would much rather just have long transaction names wrap in the cell. We'll also get a better idea about data needs and what should appear in this table after this current survey, right? So there may be more space to play with than we know at this point. There's also no indicator to accompany the tooltip.

**Comment by mjtravers** [comment]
Passes CR. Holding ticket in Code Review until Sprint-17 tickets are all moved to Stage Ready.

**Comment by WiseQA** [comment]
QA review verified Transaction Table column headers changed to:

Change "CONTRIBUTOR NAME" to "NAME"
Change "CONTRIBUTION AMOUNT" to "AMOUNT"
Change "CONTRIBUTION AGGREGATE" to "AGGREGATE"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6b0e984d-58ed-42d3-842a-1800fdb3cbe7)

QA verified transaction listed shows the full transaction name (examples below)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/28e10eed-2947-4fe5-94d1-68a9e7d1c76b)

QA Review Completed.   Moved to Stage Ready.
