### ISSUE TITLE
Install SonarCloud

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-web-app#59]
**User Story**
As a developer/QA,
I would like to have SonarCloud connected to our build pipeline, 
so that our code analysis can be consolidated into one place 

Investigate if SonarCloud can be installed on Cloud.gov

cf-sonarqube-buildpack
https://github.com/springernature/cf-sonarqube-buildpack

**Acceptance Criteria**
- [x] Install SonarCloud on a publicly accessible server (possibly AWS)
- [x] Connect the SonarCloud installation to all active GitHub repositories
- [x] If time allows, feed the output of CI pipeline reports back into SonarCloud for consolidation.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
**Backlog Grooming 1/20 Notes**: SonarQube provides code analysis for security issues, duplicate code, etc., consolidates QASP-type testing, and gives a history of changes. 

The intention was to put it on a TCG instance, but Laura suggested running it on Cloud.gov. From a continuity standpoint, it is better to run on Cloud.gov. 

Note: "(If time allows)" is not accounted for in the pointing.

**Comment by mjtravers** [comment]
Passes code review, ready for QA
https://sonarcloud.io/organizations/fecgov/projects

**Comment by WiseQA** [comment]
SonarCloud Installation:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/712b83f7-6cbc-46df-99fa-447f0001a098)

GitHub repositories connected to the SonarCloud producing consolidation report:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5f4216ac-f9d6-4ef0-9926-d122e3e752b1)

QA review completed.  Moved to Stage Ready.
