### ISSUE TITLE
Allow user to use Lookup for Earmark Receipt (Group A) /Earmark Memo (Group G)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#590]
Business Reason

The system will employ a Lookup feature when entering transactions in order to allow the user to pull existing contact information from the committee account's Contact Management table. This will also assist the FEC in making more accurate data available to the public.

Acceptance Criteria

***Given*** a transaction type of Earmark Receipt (Group A) or Earmark Memo (Group G),

  ***When*** the user adds an ENTITY type of Individual

  ***Then*** they will be able to use Lookup functionality to:

*   create a new Individual contact _or,_
*   select an existing contact from Contact Management.

—

***Given*** a transaction type of Earmark Memo,

  ***When*** the user adds an ENTITY type of Committee,

  ***Then*** they will be able to use Lookup functionality to:

*   create a new Committee contact _or,_
*   select an existing contact from Contact Management _or,_
*   create a new contact from the FEC database.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1003](https://fecgov.atlassian.net/browse/FECFILE-1003)

**Comment by Elaine-Krauss-TCG** [comment]
On DEV, you can currently lookup both contacts in an Earmark Receipt

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/c2dca023-4d9e-4707-9d04-90f464515fca)

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/24d58688-6faf-400d-9c56-a896c555ef58)

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/7d96ce20-8bc0-4602-adc5-13e373beed61)

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/83892816-4969-473d-8ce1-8c4821680b70)

**Comment by mjtravers** [comment]
Code for contact management for transaction screens in general has been completed. No additional code to CR as the contact lookup integration was completed in tickets #459 and #460. Sending to QA for verification.

**Comment by MitchellTCG** [comment]
@WiseQA @mjtravers 
This was coded and CR'd under #459 and #460.

This code is currently on DEV

**Comment by WiseQA** [comment]
QA review verified lookup worked for Earmark Receipt
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5f3998c3-f690-4bfb-aced-39e95b28cb5e)

Fields populated and displayed:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d5ee7833-f7a4-4717-846d-41498f54097d)

QA Review Completed.  Moved to Stage Ready
