### ISSUE TITLE
Allow user to manually itemize or unitemize a transaction

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#591]
Business Reason

As a user, I will be able to force itemize or unitemize any transaction so that I can report efficiently if needed.

Acceptance Criteria

***Given*** the user is on the Manage Transactions page,

 ***When*** they select the action menu for an _itemized_ transaction

 ***Then*** there will be the following options in the dropdown:

*   Edit
*   Unitemize

***And*** if the user selects "Edit", they will be brought to the transaction entry form

 ***And*** if the user selects "Unitemize", the transaction will be unitemized on the *.fec file.

—

***Given*** the user is on the Manage Transactions page,

 ***When*** they select the action menu for an _unitemized_ transaction

 ***Then*** there will be the following options in the dropdown:

*   Edit
*   Itemize

***And*** if the user selects "Edit", they will be brought to the transaction entry form

 ***And*** if the user selects "Itemize", the transaction will be itemized on the *.fec file.

Dev Notes

*   FEC has accepted that the transaction will never be able to return to the "default" logic state.

1.  Wireframes

      #

      ![591 Base.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/08ea5899-1d9c-4072-a4d0-8c60cf9f0c39](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/08ea5899-1d9c-4072-a4d0-8c60cf9f0c39))

      ![591 Itemize.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/e94fb9b7-3d10-4221-ba11-efdbd3564bf8](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/e94fb9b7-3d10-4221-ba11-efdbd3564bf8))

      ![591 Unitemize.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d202fd2b-e392-4060-aa1f-828e6cf45363](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d202fd2b-e392-4060-aa1f-828e6cf45363))

### QA Notes ###
Different logic examples:
- Individual Receipt: This transaction must be itemized if the calculated aggregate (based on aggregation group) exceeds $200 per calendar year.
- Earmark Receipt/Memo: Itemized regardless of amount. 

Itemization logic for each transaction can be found [here](https://docs.google.com/spreadsheets/d/1gdcvYQBFMeCGt-1NfVuaSTsB0sB-dl2N/edit#gid=1395788914) in Column S.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1002](https://fecgov.atlassian.net/browse/FECFILE-1002)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @mary-tcg @JonellaCulmer 
Updated

**Comment by mjtravers** [comment]
From CR, api looks good but there are some requested changes in the app repo. Sending back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified on the "Transactions" page under  the "Actions" dropdown the option when a transaction is "Itemized" to manually change to "Unitemize".

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f060bd2c-0e68-4c99-9122-79a525b8cb3b)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1f3547e0-c309-4fb1-bd36-bc6bcf3a2fe2)

Verified when selecting "Unitemize" from the "Actions" dropdown the Transaction type on the transactions table is updated to show "Unitemized" transaction.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0fba6747-7435-4cdf-bd99-d482c9be73ed)

Verified when selecting "Itemize" from the "Actions" dropdown the Transaction type on the transactions table is updated to show "Itemize" transaction.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/947dc932-49a2-4843-9794-ac69d8f4a180)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0db753d2-77c5-4c6d-817a-f8d9f690b510)

QA Review Complete.   Moved to Stage Ready.
