### ISSUE TITLE
Feature/601 Fix sorting on the Manage Contacts page

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#601]
Business Reason

As the UX Lead, I would like users to have the ability to sort the columns on the Manage Contacts table alphabetically or reverse-alphabetically and have the system work as expected.

Acceptance Criteria

1.  Step One:

       #

       ***Given:*** A User wants to sort a column of data on the ***Manage Contacts*** Table found here: [https://fecfile-web-app-stage.app.cloud.gov/contacts](https://fecfile-web-app-stage.app.cloud.gov/contacts)

***When:*** A user clicks on an ***up & down arrows*** icon next to a column title (either Name, Type, Employer, or Occupation)

***Then:*** The Data will sort based on the column the user chose

***And:*** The data in the selected column will sort ***A - Z*** with an ***Up Arrow*** appearing

1.  Step Two:

       #

       ***Given:*** A user has sorted the Data table by clicking the ***Up & Down arrows*** icon next to the column title (either Name, Type, Employer, or Occupation)

***And:*** An ***Up arrow*** icon is displaying (denoting the table is sorted by this column)

***When:*** the user clicks on the ***Up arrow*** icon

***Then:*** The Data will sort based on the column the user chose

***And:*** The data in the selected column will sort ***Z - A*** with an ***Down Arrow*** appearing

Dev Notes

The Name column should be sorted "Last name, First name"

![Screen Shot 2022-09-29 at 7.41.01 AM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/82f1e9fa-16b0-48d7-8754-2305018b4ea2](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/82f1e9fa-16b0-48d7-8754-2305018b4ea2))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1000](https://fecgov.atlassian.net/browse/FECFILE-1000)

**Comment by Elaine-Krauss-TCG** [comment]
Contacts are now sorting as expected

**Comment by Elaine-Krauss-TCG** [comment]
"Name" as an example:

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/c7cb9f12-4a29-4497-ba67-837eeb6bec31)

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/3a5d542a-3af6-4619-b927-57431bd893ae)

**Comment by mjtravers** [comment]
Failed CR. The sorting on the Name column is not working when there is a mix of contact types:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/d04721a3-81d4-4b48-a4d0-756ca2895156)

**Comment by MitchellTCG** [comment]
@Elaine-Krauss-TCG 
I updated the dev notes above with the info from our chat conversation:

The Name column should be sorted "Last name, First name"

**Comment by Elaine-Krauss-TCG** [comment]
It seems like the API wasn't filling the "name" field for Individuals/Candidates, so they're all lumped together.  Because I only tested with one Individual contact, it was missed.

The issue has been fixed with a new annotated field

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/5c8054bd-a927-480f-8f4f-791012b04a90)
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/7b3f3731-a6be-4922-8377-91066654de76)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified each column on the Manage Contacts page sorts ascending and descending order.   Columns tested:   Name; Type; Employer; Occupation.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8b3dd5ac-0946-4ee5-93a9-59d4b16bd984)

QA Review Complete.   Moved to Stage Ready.

**Comment by WiseQA** [comment]
QA during adhoc testing noticed sort of name column should sort last name, first name (Individual).    

As noted Candidates and individuals will appear lastname, firstname and org and committee will just stay the same.

Awaiting sort fix to retest.

**Comment by Elaine-Krauss-TCG** [comment]
Updated to _display_ individual and candidate names as "last, first" in addition to sorting

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/eb002e4f-8fae-4503-bb6b-cc789ef367a1)

**Comment by mjtravers** [comment]
Code changed so that the name in the contacts table are displayed "last name, first name". Passed CR and deployed change to STAGE. Ready for QA

**Comment by WiseQA** [comment]
QA review verified fix has been implemented and the contacts table "type" has been fixed to display "last name, first name".  

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4fdb74e3-23fe-46e1-b39f-a0d33610f501)

QA Review Complete.   Moved to Stage Ready.
