### ISSUE TITLE
Allow user to create a contact - individual

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#61]
Business Reason 
 

As a Committee Administrator, I will be able to create an Individual contact associated with my committee so that I can pull them into necessary transactions and reports as needed.

 Acceptance Criteria 
 

**If** I am a Committee Administrator
**When** I access my committee's contact list
**And** add a new contact with the Type "Individual"
**Then**  I will be able to input the following:
- LAST NAME	(A/N-30, required)
- FIRST NAME	(A/N-20, required)
- MIDDLE NAME (A/N-20, not required)
- PREFIX	(A/N-10, not required)	
- SUFFIX	(A/N-10, not required)
- COUNTRY/REGION (dropdown, required. Should default to United States)
- ADDRESS (A/N-34, required)
- APARTMENT, SUITE, ETC. 	(A/N-34, not required)
- CITY	(A/N-30, required)
- STATE/PROVINCE	(required. _Should be a dropdown_) {note: will show written out state name and A/N-2 on back-end}
- ZIP/POSTAL CODE	(A/N-9, required)
- TELEPHONE (N-10, not required)
- EMPLOYER	(A/N-38, not required for a new contact)	
- OCCUPATION  (A/N-38, not required for a new contact)	

**Expected Error Messages:**
1. This is a required field.
- LAST NAME (A/N-30, required)
- FIRST NAME	(A/N-20, required)
- MIDDLE NAME (A/N-20, not required)
- COUNTRY/REGION (dropdown, required. Should default to United States)
- ADDRESS (A/N-34, required)
- APARTMENT, SUITE, ETC. 	(A/N-34, not required)
- CITY	(A/N-30, required)
- STATE/PROVINCE	(A/N-2, required. _Should be a dropdown_)
- ZIP/POSTAL CODE	(A/N-9, required)

2. This field cannot contain more than 30 alphanumeric characters.
- LAST NAME	(A/N-30, required)
- CITY	(A/N-30, required)

3. This field cannot contain more than 34 alphanumeric characters.
- ADDRESS (A/N-34, required)
- APARTMENT, SUITE, ETC. 	(A/N-34, not required)

4. This field cannot contain more than 10 alphanumeric characters.
- PREFIX	(A/N-10, not required)	
- SUFFIX	(A/N-10, not required)
- ZIP/POSTAL CODE	(A/N-9, required)

5. This field cannot contain more than 10 numeric characters.
- TELEPHONE (N-10, not required)

6. This field cannot contain more than 20 alphanumeric characters.
- FIRST NAME	(A/N-20, required)
- MIDDLE NAME (A/N-20, not required)

7. This field cannot contain more than 10 alphanumeric characters.
- STATE/PROVINCE	(A/N-2, required. _Should be a dropdown_)

8. This field cannot contain more than 38 alphanumeric characters.
- EMPLOYER	(A/N-38, not required for a new contact)	
- OCCUPATION  (A/N-38, not required for a new contact)	

 UX (HTML/CSS) details for Devs 

Please review the below link for sizing, style, and grid with breakpoints 
https://docs.google.com/document/d/1qfx3vMPGAoMcMZzTQkvmvNmWvUSVC4bvGwC7vvhs6Ag/edit

[See data fields needed here](https://docs.google.com/spreadsheets/d/181bZMw59iT3JdVOCOsjps5DIf8P2_gfa/edit?rtpof=true)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
Note: avoiding roles if possible for now. 

Question for FEC: Telephone is not in the specs, but is in the Salient App for both individuals and an organization. Should it be an optional field or no?

Answer: Phone number is optional. Zip code is required, should not have dash count against character length. UX/UI discussion needed on how to display data on the front end for all entries.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG take a look.

**Comment by MitchellTCG** [comment]
Wireframe Attached

![Individual.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/bcb2554f-4d91-4a94-a725-c61e692e97e1)

![Individual - Required Fields.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/288e1a99-27f2-4431-9bb4-3d420997138b)

![Individual - Character Count.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a37fdd7c-2db1-4946-8a6e-59c346511238)


State/Province Dropdown:
<ul class="dropdown__list">
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-AL" type="checkbox" value="AL" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-AL">Alabama</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-AK" type="checkbox" value="AK" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-AK">Alaska</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-AS" type="checkbox" value="AS" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-AS">American Samoa</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-AZ" type="checkbox" value="AZ" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-AZ">Arizona</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-AR" type="checkbox" value="AR" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-AR">Arkansas</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-AA" type="checkbox" value="AA" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-AA">Armed Forces Americas</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-AE" type="checkbox" value="AE" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-AE">Armed Forces Europe</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-AP" type="checkbox" value="AP" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-AP">Armed Forces Pacific</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-CA" type="checkbox" value="CA" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-CA">California</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-CO" type="checkbox" value="CO" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-CO">Colorado</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-CT" type="checkbox" value="CT" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-CT">Connecticut</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-DE" type="checkbox" value="DE" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-DE">Delaware</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-DC" type="checkbox" value="DC" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-DC">District of Columbia</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-FL" type="checkbox" value="FL" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-FL">Florida</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-ZZ" type="checkbox" value="ZZ" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-ZZ">Foreign Countries</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-GA" type="checkbox" value="GA" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-GA">Georgia</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-GU" type="checkbox" value="GU" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-GU">Guam</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-HI" type="checkbox" value="HI" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-HI">Hawaii</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-ID" type="checkbox" value="ID" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-ID">Idaho</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-IL" type="checkbox" value="IL" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-IL">Illinois</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-IN" type="checkbox" value="IN" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-IN">Indiana</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-IA" type="checkbox" value="IA" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-IA">Iowa</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-KS" type="checkbox" value="KS" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-KS">Kansas</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-KY" type="checkbox" value="KY" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-KY">Kentucky</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-LA" type="checkbox" value="LA" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-LA">Louisiana</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-ME" type="checkbox" value="ME" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-ME">Maine</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-MD" type="checkbox" value="MD" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-MD">Maryland</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-MA" type="checkbox" value="MA" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-MA">Massachusetts</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-MI" type="checkbox" value="MI" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-MI">Michigan</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-MN" type="checkbox" value="MN" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-MN">Minnesota</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-MS" type="checkbox" value="MS" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-MS">Mississippi</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-MO" type="checkbox" value="MO" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-MO">Missouri</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-MT" type="checkbox" value="MT" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-MT">Montana</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-NE" type="checkbox" value="NE" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-NE">Nebraska</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-NV" type="checkbox" value="NV" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-NV">Nevada</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-NH" type="checkbox" value="NH" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-NH">New Hampshire</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-NJ" type="checkbox" value="NJ" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-NJ">New Jersey</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-NM" type="checkbox" value="NM" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-NM">New Mexico</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-NY" type="checkbox" value="NY" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-NY">New York</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-NC" type="checkbox" value="NC" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-NC">North Carolina</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-ND" type="checkbox" value="ND" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-ND">North Dakota</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-MP" type="checkbox" value="MP" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-MP">Northern Mariana Islands</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-OH" type="checkbox" value="OH" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-OH">Ohio</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-OK" type="checkbox" value="OK" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-OK">Oklahoma</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-OR" type="checkbox" value="OR" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-OR">Oregon</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-PA" type="checkbox" value="PA" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-PA">Pennsylvania</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-PR" type="checkbox" value="PR" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-PR">Puerto Rico</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-RI" type="checkbox" value="RI" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-RI">Rhode Island</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-SC" type="checkbox" value="SC" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-SC">South Carolina</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-SD" type="checkbox" value="SD" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-SD">South Dakota</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-TN" type="checkbox" value="TN" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-TN">Tennessee</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-TX" type="checkbox" value="TX" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-TX">Texas</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-VI" type="checkbox" value="VI" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-VI">U.S. Virgin Islands</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-UT" type="checkbox" value="UT" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-UT">Utah</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-VT" type="checkbox" value="VT" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-VT">Vermont</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-VA" type="checkbox" value="VA" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-VA">Virginia</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-WA" type="checkbox" value="WA" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-WA">Washington</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-WV" type="checkbox" value="WV" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-WV">West Virginia</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-WI" type="checkbox" value="WI" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-WI">Wisconsin</label>
            </li>
          
            <li class="dropdown__item">
              <input name="contributor_state" id="state-checkbox-WY" type="checkbox" value="WY" tabindex="0" class="is-active-filter">
              <label class="dropdown__value" for="state-checkbox-WY">Wyoming</label>
            </li>
          
        </ul>

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/9/22:** Removed "save" functionality into #110. This ticket is for data input only. 

**Discussion 2/10/22:** Will develop with United States as default (and only) country, and won't include international phone numbers. Those will be covered in #111. Error message is standard angular and will be updated with redesign effort.

**Comment by WiseQA** [comment]
Individual Contact field messages screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5cfe8b9d-e1ef-41b4-8052-29f049406341)

Individual Contact field error messages screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/92f1ea5c-15a1-4e5f-9680-915dfefd8d25)

Individual Contact "required fields" screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5e8ad0ad-779f-4033-89ca-82b6cf9c1564)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/dbebdca3-6bc5-4800-960d-5bd20adcbb03/download](https://app.zenhub.com/files/306118986/dbebdca3-6bc5-4800-960d-5bd20adcbb03/download)

QA review completed.  Moved to Stage Ready.
