### ISSUE TITLE
Create automated regression tests for #472

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#617]
Business Reason

As a developer or QA, I will be able to automatically run the Test for #472 using the Cypress e2e framework so that I can run regression tests in an automated fashion.

Acceptance Criteria

If I want to run the Sprint test scripts to retest the tickets

  When I run the automated tests in the Cypress framework

  Then I will get a report on which scripts failed and which passed

1.  QA Scripts

       #

*   [x] 472

(Note e2e testing verify changes in above tickets have been implemented. Reference QA review in tickets)

### QA Notes ###
null

### DEV Notes ###
#

### Design ###
null

 See full ticket and images here: [FECFILE-996](https://fecgov.atlassian.net/browse/FECFILE-996)

**Comment by Elaine-Krauss-TCG** [comment]
Completed.  An E2E test has been created that:

1) creates two Individual Receipts on the same date and checks the aggregation
2) creates a third Individual Receipt for a different year and checks that the prior receipts aren't in the aggregation
3) Repeats steps #1 and #2 for Tribal Receipts
4) Repeats steps #1 and #2 for JF Transfers
5) Creates two JF Transfer PAC Memos in the same year as the two JF Transfers and checks their aggregation.
6) Creates a third JF Transfer PAC Memo in a different year and checks that the prior receipts aren't in the aggregation.

**Comment by Elaine-Krauss-TCG** [comment]
This E2E test will be included in the PR for #616 given that it is dependent on changes in that PR.

**Comment by mjtravers** [comment]
Passes CR and was able to successfully run sprint-15 end-to-end tests. Sending to QA.

**Comment by WiseQA** [comment]
Passes QA visual inspection for sprint-15 end-to-end tests passing per DEV.

QA Inspection Review completed. Moved to Stage Ready
