### ISSUE TITLE
Allow user to create a contact - committee

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#62]
Business Reason 
 

As a Committee Administrator, I will be able to create a Committee contact associated with my committee so that I can pull them into necessary transactions and reports as needed even if they are not yet registered with FEC.

 Acceptance Criteria 
 

**If** I am a Committee Administrator
**When** I access my committee's contact list
**And** add a new contact with the Type "Committee"
**Then**  I will be able to input the following:

- COMMITTEE ID (A/N-9, required)
- NAME (A/N-200, required)
- COUNTRY/REGION (dropdown, required. Should default to United States)
- ADDRESS (A/N-34, required)
- APARTMENT, SUITE, ETC. (A/N-34, not required)
- CITY (A/N-30, required)
- STATE/PROVINCE (required. Should be a dropdown) {note: will show written out state name and A/N-2 on back-end}
- ZIP/POSTAL CODE (A/N-9, required)
- TELEPHONE (N-10, not required)

**Expected Error Messages:**

This is a required field.
- COMMITTEE ID
- NAME
- ADDRESS
- CITY
- STATE/PROVINCE
- ZIP/POSTAL CODE
- COUNTRY/REGION

This field cannot contain more than 200 alphanumeric characters.
- NAME

This field cannot contain more than 34 alphanumeric characters.
- ADDRESS
- APARTMENT, SUITE, ETC.

This field cannot contain more than 30 alphanumeric characters.
- CITY

This field cannot contain more than 10 numeric characters.
- TELEPHONE

This field cannot contain more than 9 alphanumeric characters.
- ZIP/POSTAL
- COMMITTEE ID

**UX (HTML/CSS) details for Devs**
Please review the below link for sizing, style, and grid with breakpoints
https://docs.google.com/document/d/1qfx3vMPGAoMcMZzTQkvmvNmWvUSVC4bvGwC7vvhs6Ag/edit

[See data fields needed here](https://docs.google.com/spreadsheets/d/181bZMw59iT3JdVOCOsjps5DIf8P2_gfa/edit?rtpof=true)

---
1. refactor old code
2. unit tests
3. documentation
4. logging in the back-end
5. accessible in the UI

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
Wireframe Attached

![Committee.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/413eff5c-50a4-4edd-8605-1730d327cb33)

![Committee – Required Fields.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/33ef590d-506d-4395-b93f-c84f7478223b)

![Committee – Character Count.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/e6beb042-1e53-4cfe-b3eb-80b1d47d0a2b)

**Comment by AureliaKhorsand** [comment]
The ID should be required as it is a data integrity issue if we do not have them. Per Ryan: The scenario brought up during our requirements meeting involved a candidate that hasn't registered with the FEC since they haven't met the legal requirements for doing so yet.  In that situation, we would steer the user to entering in that transaction as a contribution (expenditure) to an unregistered organization, which in the current FECfile Online application would be entered as an Other Disbursement.  That type of transaction and the accompanying contact do not require an ID.

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/16/22:** Note that this ticket is for validating fields, and not saving the contact. That ticket is split out into #110. Pointed at 5.

**Comment by WiseQA** [comment]
Committee Contact field messages screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/92637c30-8597-4a8d-a771-1b4bd06589e0)

Committee Contact field error messages screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/eec3cbbc-e5a8-4399-bea2-71998aa8947b)

Committee Contact "required fields" screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3d472b5e-9b65-4af4-86b8-03ec1f286b49)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/27cc4199-3ea5-4d08-9f9d-68aec44843d8/download](https://app.zenhub.com/files/306118986/27cc4199-3ea5-4d08-9f9d-68aec44843d8/download)

QA review completed.  Moved to Stage Ready.
