### ISSUE TITLE
Employer/Occupation is required if Contribution Aggregate > $200 for Earmark Receipt (Group A)

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#621]
Business Reason

The system will require Employer and Occupation fields if the Contribution Aggregate is greater than $200.

Acceptance Criteria

For the following transaction:

1\. Earmark Receipt (Group A)

***If*** Contribution Aggregate is equal to or greater than $200.01

  ***Then*** "Employer" and "Occupation" will be required to save the transaction.

1.  Earmark Receipt

       #

       1\. Go to add a receipt page and chose Earmark Receipt

       2\. Created a new contact "XXX" but do not enter an Employer or Occupation

       3\. The Earmark Receipt is populated the new contact info (sans Employer info)

       4\. Add a Date Received and $200.01 Contribution Amount

       5\. Now click in the Employer field and a Validation Error should fire (This field is required)

       6\. Add a Employer and Occupation and then you should be able to save

       7\. After hitting save a popup will appear stating the employer and occupation have changed

### QA Notes ###

Please test the following:

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-995](https://fecgov.atlassian.net/browse/FECFILE-995)

**Comment by Elaine-Krauss-TCG** [comment]
Working as intended

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/e1c4177b-02a7-4ec0-ae70-20b47d1f4671)

You cannot save an Earmark Receipt with an Aggregate over $200 without setting Employer and Occupation, and when you add them, the confirmation pop-up appears as expected

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/e2c25425-bb2a-4a8a-858f-5ebf4659da8a)

The receipt saved as expected

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/be8a3324-eec5-4949-81ff-e0e9ce20c858)

And so did the contact

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/cebe8e73-8c64-4536-8086-fd557e96d016)

**Comment by mjtravers** [comment]
Code passes CR. Sending to QA.

**Comment by MitchellTCG** [comment]
This coding of this ticket occur during the development of #486. It passed CR then.

**Comment by WiseQA** [comment]
@toddlees @MitchellTCG - After discussion retuned to QA - #459 and #460 updated QA notes denoting how to test these tickets.  

Error below is OBE:

QA review the CONTRIBUTION PURPOSE DESCRIPTION (SYSTEM-GENERATED) field needs "dummy" text entered in field.

**Comment by WiseQA** [comment]
QA review verified if Aggregate >$200.00 "Employer and Occupation" fields are required.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/323ffea1-9a78-4d02-ab8c-5cd677d2abea)

QA review verified if Aggregate <$200.00 "Employer and Occupation" fields are not required.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b5ab0b89-074c-4de0-b5ef-e3e5b8878e86)

QA Review Completed.  Moved to Stage Ready.
