### ISSUE TITLE
Refactor GroupAG HTML template into components

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#622]
***Acceptance Criteria***

  1\. Earmark Receipt & Memo input form works as it did before

  2\. Unit tests pass

  3\. Group AG template broken out into the following components to be located in shared/components/inputs:

  a. app-committee-input

  b. app-name-input

  c. app-address-input

  d. app-employer-input

  e app-contribution-input

  f. app-additional-info-input

*   *   QA Notes **

             This is a reorganization of existing code for the EARMARK_RECEIPT page. The ticket passes if that page still works as expected. Per App#459 & App#460

### QA Notes ###
1. Earmark Receipt & Memo input form works as it did before
2. Unit tests pass
3. Group AG template broken out into the following components to be located in shared/components/inputs:
a. app-committee-input
b. app-name-input
c. app-address-input
d. app-employer-input
e app-contribution-input
f. app-additional-info-input

** QA Notes **
This is a reorganization of existing code for the EARMARK_RECEIPT page. The ticket passes if that page still works as expected. Per App#459 & App#460

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-994](https://fecgov.atlassian.net/browse/FECFILE-994)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified ticket reran ticket #459 and #460.  

QA Review Completed.  Moved to Stage Ready.
