### ISSUE TITLE
System to default to "Organization" contact type for Offsets to Operating Expenditures

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#623]
Requirement from Ryan Lanz during stakeholder interviews in late August 2022.

Business Reason

As a user, I will be able to create new Offsets to Operating Expenditure transactions that are defaulted to "Organization" contact type so that I can reduce the number of clicks needed to add this transaction type.

Acceptance Criteria

***Given*** the transaction type "Offsets to Operating Expenditures" (Group B)

  ***When*** the user creates a new transaction

  ***Then*** the contact type will default to "Organization".

_Note: Other contact types available are Individual and Committee._

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-993](https://fecgov.atlassian.net/browse/FECFILE-993)

**Comment by Elaine-Krauss-TCG** [comment]
Offset to Opex presents "Organization" as the default contact type
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/2235edfd-bea6-4ff1-aa23-b20fec13b1b7)

**Comment by Elaine-Krauss-TCG** [comment]
Devs can now override the contact type options for a specific transaction type.  (See line #24)  The first type in the list is the default option presented to the user when a new transaction form is opened.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/94fbee82-87c7-4ce8-90c3-ba7fc8688ef0)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "Organization" is the default contact type for Offsets to Operating Expenditures (see screenshot below).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7e82cfa8-62ad-40d1-bd7b-8a3d2f0c09be)

QA Review Completed.   Moved to Stage Ready.

Changed naming from **Offset** to Operating Expenditure to **Offsets** to Operating Expenditure in acceptance criteria to be consistent what transaction page is showing.
