### ISSUE TITLE
Allow user to reattribute a Tier 1 Schedule A transaction from a previous report

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#624]
Business Reason

As a user, I will be able to "reattribute" a Tier 1 transaction within a previous report so that I can reattribute part or all of the receipt amount to a different entity, changing the aggregation amount for the entity on each new transaction.

Acceptance Criteria

***Given*** a Tier 1 receipt on Schedule A in a previous report with status "Submission success"

 ***When*** I initiate the 'Reattribute' action for that transaction,

 ***Then*** the system will ask me to confirm which "In progress" report of the ***same report type*** I would like to add the reattribution to,

 ***And*** when I confirm the report selection,

 ***Then*** I will be able to indicate the how much should be reattributed, to whom, and when as follows:

1.  Contact

      #

*   ***CONTACT TYPE***- _(Required, contact type values should match the original receipt specification)_

—

 _if CONTACT TYPE = Organization_

*   ***ORGANIZATION NAME*** (Required, LOOKUP)

—

 _if CONTACT TYPE = Committee_

*   ***COMMITTEE NAME*** (Required, LOOKUP)
*   ***COMMITTEE ID*** (Required)

—

 _if CONTACT TYPE = Individual_

*   ***LAST NAME*** (Required)
*   ***FIRST NAME*** (Required)
*   ***MIDDLE NAME*** (Optional)
*   ***PREFIX*** (Optional)
*   ***SUFFIX*** (Optional)

1.  Address

      #

*   ***STREET ADDRESS*** (Required)
*   ***APARTMENT, SUITE, ETC.*** (Optional)
*   ***CITY*** (Required)
*   ***STATE/PROVINCE*** (Required)
*   ***ZIP/POSTAL CODE*** (Required)

1.  Receipt Information

      #

*   ***REATTRIBUTION DATE*** (required)
*   ***MEMO ITEM*** (required, automatically checked by the system and user cannot change it)
*   ***REATTRIBUTED AMOUNT*** (required, must be positive and cannot exceed amount of original contribution)
*   ***AGGREGATE*** (read-only, will match logic of original transaction)

1.  Additional information

      #

*   ***PURPOSE OF RECEIPT*** (Required, system generated)
      *   "Reattribution from XX", where XX is the Entity Name from the original contribution
*   ***NOTE OR MEMO TEXT*** (Optional)

—

***And*** the system will auto-generate a transaction showing amount _reattributed from_ with the following information:

1.  Contact

      #

*   _(Contact will auto-pull from original receipt and user cannot edit it)_

1.  Address

      #

*   _(Address will auto-pull from original receipt and user cannot edit it)_

1.  Receipt Information

      #

*   ***REATTRIBUTION DATE*** (required, auto-generated from "reattributed to" transaction and user cannot edit it)
*   ***MEMO ITEM*** (required, automatically checked by the system and user cannot change it)
*   ***REATTRIBUTED AMOUNT*** (required, auto-generated from "reattributed to" transaction and _made negative_, and user cannot edit it)
*   ***AGGREGATE*** (read-only, will match logic of original transaction)

1.  Additional information

      #

*   ***PURPOSE OF RECEIPT*** (Required, system generated)
      *   "Reattribution to XX", where XX is the Entity Name from "reattributed to" transaction
*   ***NOTE OR MEMO TEXT*** (Optional)

—

***And*** the system will auto-generate a transaction with the following information:

*   Copy of the all the details from the original transaction, with the MEMO checkbox selected.
*   - ***PURPOSE OF RECEIPT*** (Required, system generated)
      *   "(Originally disclosed on XX report.) See reattribution below." where XX will be filled in with #1454 (remain XX for now).

—

 ***Then*** I will be able to:

*   Cancel
*   Edit
*   Save transactions (users must save all three at the same time)

***And*** upon saving:

*   the user will be taken to the in-progress report the reattribution has been saved on
*   all three transactions will be saved on the selected report as memo items with their original line numbers.
*   all three will be associated to the copy of the original receipt on the current report by their back reference IDs.
*   the copy of the original transaction will be ***unaggregated.***
*   on the backend:
      *   Copy of original transaction: REATTRIBUTION REDESIGNATION TAG set to REATTRIBUTED
    *   First transaction above (Reattributed To): REATTRIBUTION REDESIGNATION TAG set to REATTRIBUTION_TO
    *   Second transaction above (Reattributed From): REATTRIBUTION REDESIGNATION TAG set to REATTRIBUTION_FROM

***And*** when the user opens a reattributed transaction, it will take them back to the "Reattribution From/To" entry form.

QA Note

 Dev Note

*   This functionality should ONLY be for Tier 1 (parent) transactions.
*   Any existing "children" of the original transaction do _not_ come over to the current report.
*   The copy of the original transaction will be ***unaggregated.***
*   This will be a **[specification overlay]([https://docs.google.com/spreadsheets/d/1AbYjbtwZNuB8Y1GHAXMwSzxJW41Pr_3J/edit#gid=1968442852)**](https://docs.google.com/spreadsheets/d/1AbYjbtwZNuB8Y1GHAXMwSzxJW41Pr_3J/edit#gid=1968442852)**), with specifications here replacing those on the original receipt. The remaining specifications will match the original.
*   Copy of original transaction: REATTRIBUTION REDESIGNATION TAG set to REATTRIBUTED
*   First transaction above (Reattributed To): REATTRIBUTION REDESIGNATION TAG set to REATTRIBUTION_TO
*   Second transaction above (Reattributed From): REATTRIBUTION REDESIGNATION TAG set to REATTRIBUTION_FROM

Wireframe

1.  Select Reattribute

      [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVYyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e0fc3ada2c41b25729bfe3227e718c70f8ab3e7/624%20-%20Kabob.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVYyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e0fc3ada2c41b25729bfe3227e718c70f8ab3e7/624%20-%20Kabob.png))

1.  Select a report

      [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWtXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d69deaf57a25c49b6c97820b28e94a1407bd8bb6/624%20select.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWtXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d69deaf57a25c49b6c97820b28e94a1407bd8bb6/624%20select.png))

1.  Report Selected

      [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW9XQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7991904e2a56b580acdcf5e98cbf9605c40c1426/624%20-%20Allow%20user%20to%20reattribute%20a%20Tier%201%20transaction%20from%20a%20previous%20report.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW9XQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7991904e2a56b580acdcf5e98cbf9605c40c1426/624%20-%20Allow%20user%20to%20reattribute%20a%20Tier%201%20transaction%20from%20a%20previous%20report.png))

1.  Memo 1

      [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEVtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00cc5ec525fe21896977a60cb117090e09abe850/171%20-%20Tier%201.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEVtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00cc5ec525fe21896977a60cb117090e09abe850/171%20-%20Tier%201.png))

1.  Memo 2

      [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODBWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--deda191b32fc66519976c8af9132f6845918c37c/624%20Tier%202.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODBWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--deda191b32fc66519976c8af9132f6845918c37c/624%20Tier%202.png))

1.  Memo 3

      [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFltQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--daddef52df8d9f796619c82c5eb6cb2b02ea0ba5/171%20-%20Tier%203.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFltQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--daddef52df8d9f796619c82c5eb6cb2b02ea0ba5/171%20-%20Tier%203.png))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
- [x] BA/Design Quality Checklist complete
- This functionality should ONLY be for Tier 1 (parent) transactions.
- Any existing "children" of the original transaction do _not_ come over to the current report.
- The copy of the original transaction will be **unaggregated.**

 See full ticket and images here: [FECFILE-992](https://fecgov.atlassian.net/browse/FECFILE-992)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg On the third wireframe, "CONTRIBUTION AMOUNT" should say "REATTRIBUTED AMOUNT" to match the second wire.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
mock #3 finally fixed sorry

@GreggMoreland 
please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG what does selecting the correct in-progress report look like when they first reattribute? Is there no modal wireframe for that yet?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Report selection added

**Comment by mjtravers** [comment]
During CR, there were some issues discovered with the contact lookup select box. The issues will be addressed in the closely related #1064 ticket. Placing ticket on hold. This ticket will pass with #1064.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers the Purpose of Receipt should be system-generated and read-only as denoted in AC and wireframe (see below).

<img width="316" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGs1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--812d4900e7af16b1cbdb343a0c7d0be8345a975c/image.png" alt="image.png" />

______________________________________________________________________________________________
Purpose of Receipt currently displaying as:

<img width="844" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDQ1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--17680527a6ba85414b4b268e2cfd5af9702a652e/image.png" alt="image.png" />

____________________________________________________________________________________________________________

Ticket placed on-hold for hotfix.

**Comment by WiseQA** [comment]
During DEV / QA review, the functionality for the **"Select a report" from the dropdown for reattribute is for Form 3x reports only** (Original and future reports).   In the "Select a report" drop down when **reattributing** or redesignating a transaction from a prior submitted F3X report, the drop down is also showing all Form 1M, Form 24, Form 99, and past Form 3X reports.

<img width="1227" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlZBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cbe559ed9c1ce615b060aa2d8029b94173f5ac8/image.png" alt="image.png" />

@MitchellTCG @mjtravers Hotfix for this ticket.

**Comment by mjtravers** [comment]
Fix made for dropdown issue and labels. Deployed to STAGE.

**Comment by WiseQA** [comment]
QA review the label for "Reattribute from" is missing.  Fix label

<img width="1046" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzVHQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--145dc518a968ea5e9d8cafa178dabe063289e408/image.png" alt="image.png" />

@mjtravers @MitchellTCG fix label.

**Comment by WiseQA** [comment]
QA review verified the fix was implemented for the functionality for the "Select a report" from the dropdown for reattribute is for Form 3x reports only (Original and future reports)

<img width="796" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUpIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e219d69e8314efead1f84545bc96256375d11b82/image.png" alt="image.png" />

This fix passes.

**Comment by WiseQA** [comment]
QA testing using Login.gov on STAGE. QA review verified reattribution of Receipts (Schedule A) from previous report. (Tested using INDIVIDUAL RECEIPT. e2e testing for additional transactions)

Verified "Select Reattribute"

<img width="1402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUZIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d83da75a0cff9114c70796a10331616b6696401/image.png" alt="image.png" />

_____________________________________________________________________________________

Verified the fix was implemented for the functionality for the "Select a report" from the dropdown for reattribute is for Form 3x reports only (Original and future reports). Then select report to reattribution.

<img width="1386" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUpIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3d0e67f16fbee3c9984f318e6934d7f7f982dc5/image.png" alt="image.png" />

______________________________________________________________________________________________________

Verified "Reattribution to" page is displayed. Enter required fields.

<img width="1159" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWxIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1876c2fa1b6f6717ec56b5c6ec7aaa3b12153bf3/image.png" alt="image.png" />

_____________________________________________________________________________________________

Verified "Reattribution from" page is displayed. Enter required fields.

<img width="1068" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTVIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d0c26283fb704aa9b5c2c61725bea2b7e0ada8f/image.png" alt="image.png" />

______________________________________________________________________________________________

Verified PURPOSE OF RECEIPT and NOTE OR MEMO TEXT fields populating correctly for each level of transaction.

___________________________________________________________________________________________________________

Verify transaction has been reattributed to the correct report.

<img width="1539" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTlIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8074fa822a7a0606be4c6612309357ec9a406480/image.png" alt="image.png" />

__________________________________________________________________________

QA Review Completed. Moved to Stage Ready.
