### ISSUE TITLE
Resolve and refactor TransactionType.parentTransaction

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#626]
Questions to resolve:

1. Will the parent transaction be updated if included in the serializer when saving a transaction. We don't want that.
2. Without the depth=1 setting in the scha_transaction serializer, will we go into infinite loops. (I think yes) And will grandchildren work with depth=1

After #460 is merged, the parent transaction (if a transaction has one) will be bundled up in the transaction payload returned from the API. This ticket is to refactor TransactionType.parentTransaction to use the new TransactionType.transaction.parent_transaction field in it's place

**Acceptance Criteria**
Transactions that have a parent transaction, like PAC JF TRANSFER MEMO, create and update as they did before the code change.

**QA Notes**
Test to make sure PAC JF TRANSFER and EARMARK RECEIPT can be created, updated, the menu navigates properly, and the transaction shows up in the transactions table with the correct parent transaction_id showing up in the table.
### QA Notes ### 
 1. Will the parent transaction be updated if included in the serializer when saving a transaction. We don't want that.
2. Without the depth=1 setting in the scha_transaction serializer, will we go into infinite loops. (I think yes) And will grandchildren work with depth=1

After #460 is merged, the parent transaction (if a transaction has one) will be bundled up in the transaction payload returned from the API. This ticket is to refactor TransactionType.parentTransaction to use the new TransactionType.transaction.parent_transaction field in it's place

**Acceptance Criteria**
Transactions that have a parent transaction, like PAC JF TRANSFER MEMO, create and update as they did before the code change.

**QA Notes**
Test to make sure PAC JF TRANSFER and EARMARK RECEIPT can be created, updated, the menu navigates properly, and the transaction shows up in the transactions table with the correct parent transaction_id showing up in the table.
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
A code change is requested from CR. See the [PR](https://github.com/fecgov/fecfile-web-app/pull/686) comment. Sending back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA verified PAC JF TRANSFER and EARMARK RECEIPT can be created per refactor of TransactionType.parent Transaction.

QA Review Completed.  Moved to Stage Ready.
