### ISSUE TITLE
Allow user to create a contact - candidate

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#63]
Business Reason 
 

As a Committee Administrator, I will be able to create a Candidate contact associated with my committee so that I can pull them into necessary transactions and reports as needed even if they are not yet registered with FEC.

 Acceptance Criteria 
 

**If** I am a Committee Administrator
**When** I access my committee's contact list
**And** add a new contact with the Type "Candidate"
**Then**  I will be able to input the following:

- CANDIDATE ID (A/N-9, required)
- LAST NAME (A/N-30, required)
- FIRST NAME (A/N-20, required)
- MIDDLE NAME (A/N-20, not required)
- PREFIX (A/N-10, not required)
- SUFFIX (A/N-10, not required)
- COUNTRY/REGION (dropdown, required. Should default to United States)
- ADDRESS (A/N-34, required)
- APARTMENT, SUITE, ETC. (A/N-34, not required)
- CITY (A/N-30, required)
- STATE/PROVINCE (required. Should be a dropdown) {note: will show written out state name and A/N-2 on back-end}
- ZIP/POSTAL CODE (A/N-9, required)
- TELEPHONE (N-10, not required)
- EMPLOYER (A/N-38, not required for a new contact)
- OCCUPATION (A/N-38, not required for a new contact)

**(Note:  Candidate Office, Candidate State and Candidate District not field validated in this ticket and is not tested in this ticket.   Ticket 110 will test this validation)**

 Expected Error Messages: 
 

**This is a required field.**
CANDIDATE ID
LAST NAME
FIRST NAME 
ADDRESS
CITY
STATE/PROVINCE
ZIP/POSTAL CODE
COUNTRY/REGION

**This field cannot contain more than 38 alphanumeric characters.**
EMPLOYER
OCCUPATION

**This field cannot contain more than 34 alphanumeric characters.**
ADDRESS
APARTMENT, SUITE, ETC.

**This field cannot contain more than 30 alphanumeric characters.**
LAST NAME
CITY

**This field cannot contain more than 20 alphanumeric characters.**
FIRST NAME
MIDDLE NAME

**This field cannot contain more than 10 numeric characters.**
TELEPHONE

**This field cannot contain more than 9 alphanumeric characters.**
ZIP/POSTAL
CANDIDATE ID

1. refactor old code
2. unit tests
3. documentation
4. logging in the back-end
4. accessible in the UI

**UX (HTML/CSS) details for Devs**
Please review the below link for sizing, style, and grid with breakpoints
https://docs.google.com/document/d/1qfx3vMPGAoMcMZzTQkvmvNmWvUSVC4bvGwC7vvhs6Ag/edit

[See data fields needed here](https://docs.google.com/spreadsheets/d/181bZMw59iT3JdVOCOsjps5DIf8P2_gfa/edit?rtpof=true)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
Wireframe Attached

[Uploading... Candidate.png]

**Comment by MitchellTCG** [comment]
Wireframe Attached

![Candidate.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/98622ecf-e9a7-436d-82c4-b7042c04828e)

![Candidate – Required Fields.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/24387636-c347-4456-bc26-e19b33666b77)

![Candidate – Character Count.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/63e9b537-ec0b-4407-9303-2570acba8ae1)

![Candidate Office– Required Fields.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/be92183a-aca2-431b-b279-61dabeb90d21)

**Comment by AureliaKhorsand** [comment]
The ID should be required as it is a data integrity issue if we do not have them. Per Ryan: The scenario brought up during our requirements meeting involved a candidate that hasn't registered with the FEC since they haven't met the legal requirements for doing so yet.  In that situation, we would steer the user to entering in that transaction as a contribution (expenditure) to an unregistered organization, which in the current FECfile Online application would be entered as an Other Disbursement.  That type of transaction and the accompanying contact do not require an ID.

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/16/22:** Note that this ticket is for validating fields, and not saving the contact. That ticket is split out into #110. Pointed at 5.

**Comment by WiseQA** [comment]
Candidate Contact field messages screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d2776249-a80e-4a11-9fa2-8bbbb7122695)

Candidate Contact field error messages screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7bdd878a-a4af-43ad-992e-539ab2c727e7)

Candidate Contact "required fields" screen shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/836c5867-a8a8-4ba1-a8cb-0e0579015c69)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/3455bf22-e22c-43ca-a077-8b816071cf25/download](https://app.zenhub.com/files/306118986/3455bf22-e22c-43ca-a077-8b816071cf25/download)

QA review completed.  Moved to Stage Ready.
