### ISSUE TITLE
Defect: System to itemize JF Transfer regardless of amount

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#631]
Implementation of #486 was broken by subsequent development. This ticket is to re-code and re-test this functionality. Note that itemization logic is _not_ determined by aggregation group.

 Business Reason 
 

Per FECA regulations, all Form 3X transactions on Line 12 must be itemized on Schedule A, regardless of amount. This includes JF Transfer transactions.

 Acceptance Criteria 
 

**Given** one of the following transactions: 
- Joint Fundraising Transfer
- PAC JF Transfer Memo

**Then** the transaction will be itemized upon saving
**and** appear on it's own line item on the *.fec file

 QA notes 

1. In a report, make a JF Transfer transaction.  (to make a later step easier, i'd recommend putting something in the memo text that you cans search for like "jf transfer test 1"
2. go to the reports list page.  find the report where you added the JF Transfer and click the second green button on that row (for some reason the icons are missing)
3. you should be on a page that says "Test .FEC generation for <letters and numbers>"
4. Click "generate .fec". another button will appear, but wait about 5 seconds before pressing it
5. Click "download .fec" after about 5 seconds
6. Open the file that was just downloaded with notepad for PC or textedit for Mac. There must be a row representing the JF Transfer that was made in step 1, regardless of contribution aggregate (other transaction types show up depending on if the contribution aggregate is above $200).  You can be sure the line for the transaction you made if the text at the end of the line matches the memo text you filled out in the form.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA Review completed as denoted by DEV in QA notes above.    Tested various Transactions to verify this code was not broke.    Retested JF Transfer.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a2f31139-5062-4744-9452-d932ee3d8967)

QA Review Completed.   Moved to Stage Ready.
