### ISSUE TITLE
Allow user to enter Partnership Recount Account Receipt on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#632]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Partnership Recount Account Receipt”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "parent" transaction that will have an associated child ‘Memo’ transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type "Partnership Recount Account Receipt"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	CONTACT TYPE (Read-only, **includes Lookup**)
-- Organization Only
-	ORGANIZATION NAME (Required)

# Address 
#
-	STREET ADDRESS (Required)
-	APARTMENT, SUITE, ETC. (Optional)
-	CITY (Required)
-	STATE/PROVINCE (Required)
-	ZIP/POSTAL CODE (Required)

# Receipt Information 
#
-	DATE RECEIVED (Required)
-	MEMO ITEM (Optional)
-	AMOUNT (Required)
-- Note: AMOUNT can contain a negative value.
-	AGGREGATE (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "RECOUNT_ACCOUNT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	CONTRIBUTION PURPOSE DESCRIPTION (System generated)
-- If transaction has no associated Partnership memos, reads "Recount Account (Partnership attributions do not require itemization)".
--If transaction has associated Partnership memos, reads "Recount Account (See Partnership Attribution (s) below)"
-	NOTE OR MEMO TEXT (Optional)

---
**Then** I will be able to:

- Cancel
- Save & add another
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- There should be italics text under the CPD title (see Wire)

 Dev Note 

- There should be italics text under the CPD title (see Wire)

- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=476207410)
![27b614c1-5674-4228-9d7d-e005477c8c8f.png](https://images.zenhubusercontent.com/62eac7883f87756fe900911f/a039d4cd-bbf2-4c0b-a77b-031269f74522)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
Transactions are creating and saving as expected
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/9635a609-29ec-4076-b0e6-8749abdb5db1)

**Comment by Elaine-Krauss-TCG** [comment]
When no memos have been created, the Purpose Description reads:
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/8f23f1f0-77ea-4922-a675-34b158ab3c73)

**Comment by Elaine-Krauss-TCG** [comment]
And with one or more memos:
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/d2f82524-43bd-4894-bd5f-f2d3aa51880f)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Partnership Recount Account Receipt transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2ea40558-8ab2-4523-8009-8a2158749bee)

Verified without a memo  "Recount Account (Partnership attributions do not require itemization)" is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7cf02424-3ac0-42c7-a804-12edcbe4c50b)

Verified with a memo "Recount Account (See Partnership Attribution(s) below)" is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/37ea775f-9e77-474b-86f9-aa38def2955f)

From the dropdown select add memo - Partnership Recount Account Receipt Memo

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/41058069-23f6-47fa-8197-7c099d9f5eaa)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2c236a27-8f8e-45c6-9026-b20d3e4cb2e7)

Verify memo is created.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/917aa431-40d4-45fe-9ecb-0f0bd6e4896b)

Verify Partnership Recount Account Receipt transaction and memo are displayed in Transactions Table.

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/363bbfbd-f428-454c-ad31-ccdb03a61d6c)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0fbd6144-6f0f-4b7a-a0f4-6a0d54fca46e)

QA Review Complete.  Moved to Stage Ready.
