### ISSUE TITLE
Allow user to enter Partnership National Party Headquarters Buildings Account on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#634]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **” Partnership National Party Headquarters Buildings Account”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "parent" transaction that will have an associated child ‘Memo’ transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type " Partnership National Party Headquarters Buildings Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	CONTACT TYPE (Read-only, **including Lookup**)
-- Organization Only
-	ORGANIZATION NAME (Required)

# Address 
#
-	STREET ADDRESS (Required)
-	APARTMENT, SUITE, ETC. (Optional)
-	CITY (Required)
-	STATE/PROVINCE (Required)
-	ZIP/POSTAL CODE (Required)

# Receipt Information 
#
-	DATE RECEIVED (Required)
-	MEMO ITEM (Optional)
-	AMOUNT (Required)
-- Note: AMOUNT can contain a negative value.
-	AGGREGATE (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "NATIONAL_PARTY_HEADQUARTERS_ACCOUNT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	CONTRIBUTION PURPOSE DESCRIPTION (System generated)
-- If transaction has no associated Partnership memos, reads "Headquarters Buildings Account (Partnership attributions do not require itemization)".
--If transaction has associated Partnership memos, reads "Headquarters Buildings Account (See Partnership Attribution(s) below)"
-	NOTE OR MEMO TEXT (Optional)

---
**Then** I will be able to:

- Cancel
- **Remove - Save & add another  (Remove there is no button to do this functionality)**
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- Note the italics above the Contribution Purpose Description field.
- For Contribution Purpose Description field text:
-- If transaction has no associated Partnership memos, reads "Headquarters Buildings Account (Partnership attributions do not require itemization)".
--If transaction has associated Partnership memos, reads "Headquarters Buildings Account (See Partnership Attribution(s) below)"

 Dev Note 

- Note the italics above the Contribution Purpose Description field.
- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=622262881) **Note this is a consolidated specification**

![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/72b5d373-dadd-430e-a092-304e81af462c)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
Partnership National Party Headquarters Receipt and Memo implemented
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/1b93f854-fc81-48a7-a917-798752033e90)

**Comment by Elaine-Krauss-TCG** [comment]
Partnership National Party Headquarters Receipt and Memo implemented
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/1b93f854-fc81-48a7-a917-798752033e90)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Partnership National Party Headquarters Buildings Account transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2702360e-84fc-4244-bb27-5b2bd3428e20)

Verified without a memo "Headquarters Buildings Account (Partnership attributions do not require itemization)" is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c27d94b4-02b3-424d-a752-bc436bacfb95)

Verified with a memo "Recount Account (See Partnership Attribution(s) below)" is displayed.

From the dropdown select add memo - Partnership National Party Headquarters Buildings Account Memo

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8e21f4e6-6905-4742-9a9e-cece73ab8eb1)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d5c16701-925e-417b-934c-543040d0b921)

Verify memo is created.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/57ed6706-1454-4a5a-84f5-fd472b7cb45d)

Verify Partnership Recount Account Receipt transaction and memo are displayed in Transactions Table.

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4b6da574-95a6-4614-9b54-054b0d3bfe6a)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bd67a6f7-127f-41d1-a55b-9be93d450e81)

QA Review Completed. Moved to Stage Ready.
