### ISSUE TITLE
Allow user to enter Partnership National Party Headquarters Buildings Account Memo on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#635]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **Partnership National Party Headquarters Buildings Account Memo** sub-transaction under **"Partnership National Party Headquarters Buildings Account"** on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

NOTE: This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator
**And** I am editing a Partnership National Party Headquarters Buildings Account transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction:
- Partnership National Party Headquarters Buildings Account Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **includes Lookup**)
-- INDIVIDUAL only

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (A/N-10, Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Required)
This will be automatically checked and the user CANNOT change it.
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "NATIONAL_PARTY_HEADQUARTERS_ACCOUNT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.
-	**EMPLOYER** (Required if Aggregate > $200)
-	**OCCUPATION** (Required if Aggregate > $200)

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (System generated)
Data field: multi-line textbox that must read "Headquarters Buildings Account Partnership Attribution”
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save & view all transactions
- Go back to parent transaction
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1492384539) **Please note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
Partnership National Party Headquarters Receipt and Memo implemented
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/1b93f854-fc81-48a7-a917-798752033e90)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review pre-requisite Partnership National Party Headquarters Buildings Account transaction created and displayed in transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fc5845de-3adb-4e02-b254-46b26b0d8e19)

From the dropdown select add memo - Partnership National Party Headquarters Buildings Account Memo

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/45b0c011-f89b-410d-8722-261efb65d53b)

Verify Partnership National Party Headquarters Buildings Account Memo is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3a86785b-9ce5-4aa4-aaca-f204f9175f76)

Verify Partnership National Party Headquarters Buildings Account Memo is displayed in Transactions Table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3df6193d-c2f0-4c14-87a8-0c91b9b38149)

QA Review Completed.   Moved to Stage Ready.
