### ISSUE TITLE
Allow user to enter Partnership National Party Pres. Nominating Convention Account on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#636]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Partnership National Party Pres. Nominating Convention Account”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "parent" transaction that will have an associated child ‘Memo’ transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click (open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type "Partnership National Party Pres. Nominating Convention Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	CONTACT TYPE (Read-only, **includes Lookup**)
-- Organization Only
-	ORGANIZATION NAME (Required)

# Address 
#
-	STREET ADDRESS (Required)
-	APARTMENT, SUITE, ETC. (Optional)
-	CITY (Required)
-	STATE/PROVINCE (Required)
-	ZIP/POSTAL CODE (Required)

# Receipt Information 
#
-	DATE RECEIVED (Required)
-	MEMO ITEM (Optional)
-	AMOUNT (Required)
-- Note: AMOUNT can contain a negative value.
-	AGGREGATE (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "NATIONAL_PARTY_CONVENTION_ACCOUNT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	CONTRIBUTION PURPOSE DESCRIPTION (System generated)
-- If transaction has no associated Partnership memos, reads "Pres. Nominating Convention Account (Partnership attributions do not require itemization)".
--If transaction has associated Partnership memos, reads "Pres. Nominating Convention Account (See Partnership Attribution(s) below)"

-	NOTE OR MEMO TEXT (Optional)

---
**Then** I will be able to:

- Cancel
- Add “Partnership  National Party Pres. Nominating Convention Account Memo" 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- Note the italics above the Contribution Purpose Description field.
- For Contribution Purpose Description field text:
-- If transaction has no associated Partnership memos, reads "Pres. Nominating Convention Account (Partnership attributions do not require itemization)".
--If transaction has associated Partnership memos, reads "Pres. Nominating Convention Account (See Partnership Attribution(s) below)"

 Dev Note 

- Note the italics above the Contribution Purpose Description field.
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=622262881) **Please note this is a consolidated transaction specification**

![27b614c1-5674-4228-9d7d-e005477c8c8f.png](https://images.zenhubusercontent.com/62eac7883f87756fe900911f/26575004-4e18-415f-bd29-0aecafb57bc8)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Some requests made in CR. Sending back to In Progress

**Comment by toddlees** [comment]
addressed CR changes

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Partnership National Party Pres. Nominating Convention Account transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fa2a6f9b-3588-4401-84de-bd3b4ecf8bf2)

Verified without a memo "Pres. Nominating Convention Account (Partnership attributions do not require itemization)" is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6402b0ea-9f1c-404f-89b4-d1e726a6c896)

Verified with a memo "Pres. Nominating Convention Account (See Partnership Attribution(s) below)" is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/409bf090-a1d5-4058-bcca-0072caba6a3c)

From the dropdown select add memo - Partnership National Party Pres. Nominating Convention Account Memo

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3c896e79-0f8f-450e-a114-22c2c9340b9b)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bdadd573-0984-4188-99d8-55b02ba52ef9)

Verify memo is created.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f223d414-6d4c-4eaa-a132-df36f6fff6f6)

Verify Partnership National Party Pres. Nominating Convention Account transaction and memo are displayed in Transactions Table.

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/40d20a3b-5547-4afe-b2a1-1830ba3810c6)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

Unitemized not displaying in transaction table - waiting for @mjtravers @toddlees to verify if broken.  @toddlees verified broken returning to In-Progress for fix.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/48dc60ed-0fb6-418e-b3ce-c28f57e5ad4c)

**Comment by toddlees** [comment]
before fix
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/37f633d3-357a-447d-8071-ecdd6902e097)
after fix
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/a2513c6c-f340-4237-a344-eb8070a2fd24)

**Comment by toddlees** [comment]
@WiseQA Fix is deployed

**Comment by WiseQA** [comment]
QA review verified, fix was implemented, and the Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6a23441f-a951-46dc-a7a6-73e3ce2529ee)

QA Review Completed.   Moved to Stage Ready.
