### ISSUE TITLE
BUG: DO NOT delete PAC JF Transfer Memos when creating new ones

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#639]
### Business Reason ###
As a FECFile User, I should be able to add a new/additional PAC JF Transfer Memo while updating a Joint Fundraising Transfer. And any previous created and associated PAC JF Transfer Memos should persist when these new/additional memos are made.

### How to Replicate the Issue ###
1. Create a JF Transfer and create a new committee contact that has never been used in the system
2. after creating the new contact, add a date and contribution amount.
3. Next click Save & add a memo
4. Create a memo with a new committee contact that has never been used in the system
5. after creating the new contact, add a date and contribution amount for the memo
6. Next click Save & add a memo
7.  Next repeat steps 4-5 and click Save and view all transactions

You should see a JF Transfer with two PAC JF Transfer Memos

Next:
8. Click the hyperlink of the JF Transfer
9. Click Save and add a memo button
10. Complete steps 4-5 and click Save and view all transactions

You should see a JF Transfer with only ONE PAC JF Transfer Memo

(Conclusion: the system has disassociated or deleted the previous PAC JF Transfer Memos)

**Expected result:** All PAC JF Transfer Memos previously created should persist even if more are created.

**Comment by MitchellTCG** [comment]
@WiseQA 
Please review and let me know if this doesn't make sense.

**Comment by WiseQA** [comment]
@MitchellTCG QA review of "BUG" written ticket completed.

**Comment by dheitzer** [comment]
Reviewed with @MitchellTCG and this appears to be fixed.  Putting on-hold for now.

**Comment by MitchellTCG** [comment]
After talking to David, I retested this bug. It appears to be working as intended now. 

![Screenshot 2022-11-10 at 11.05.12 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7d29b429-b582-4f12-a66c-729a27c501b1)

@mjtravers Please ping me about this ticket when you get back. I will most likely make it OBE.

**Comment by WiseQA** [comment]
@MitchellTCG I also retested, I think ticket #447 - Allow user to enter Party Joint Fundraising Transfer Memo on Schedule A (Group F) might have fixed this "bug".

**Comment by mjtravers** [comment]
I believe #460 fixed this bug which looks to have been in the front-end transaction resolver. Here's the [PR](https://github.com/fecgov/fecfile-web-app/pull/586) and the specific [commit](https://github.com/fecgov/fecfile-web-app/commit/d0545de3c8528aba04b7893e17f75cbcc6c7fdec) where the code change was made.

Closing this ticket as it is OBE.
