### ISSUE TITLE
Allow user to create a contact - organization

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#64]
Business Reason 
 

As a Committee Administrator, I will be able to create an Organization contact associated with my committee so that I can pull them into necessary transactions and reports as needed.

 Acceptance Criteria 
 

**If** I am a Committee Administrator
**When** I access my committee's contact list
**And** add a new contact with the Type "Organization"
**Then**  I will be able to input the following:
- NAME (A/N-200, required)
- COUNTRY/REGION (dropdown, required. Should default to United States)
- ADDRESS (A/N-34, required)
- APARTMENT, SUITE, ETC. (A/N-34, not required)
- CITY	(A/N-30, required)
- STATE/PROVINCE (required. Should be a dropdown) {note: will show written out state name and A/N-2 on back-end}
- ZIP/POSTAL CODE	(A/N-9, required)
- TELEPHONE (N-10, not required)

 Expected Error Messages: 
 

**This is a required field.**
NAME
COUNTRY/REGION
ADDRESS
CITY
STATE/PROVINCE
ZIP/POSTAL CODE

**This field cannot contain more than 200 alphanumeric characters.**
NAME

**This field cannot contain more than 34 alphanumeric characters.**
ADDRESS
APARTMENT, SUITE, ETC.

**This field cannot contain more than 30 alphanumeric characters.**
CITY

**This field cannot contain more than 10 numeric characters.**
TELEPHONE

**This field cannot contain more than 9 alphanumeric characters.**
ZIP/POSTAL

 UX (HTML/CSS) details for Devs 

Please review the below link for sizing, style, and grid with breakpoints 
https://docs.google.com/document/d/1zxzKbX9MfznzuD6cfXf1UbdFyRKMg4SOe7ZB8J09z2c/edit

[See data fields needed here](https://docs.google.com/spreadsheets/d/181bZMw59iT3JdVOCOsjps5DIf8P2_gfa/edit?rtpof=true)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
Wireframe Attached

![Organization.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/1664c32c-6ac7-42d5-bada-95e4bb73ee52)

![Organization – Required Fields.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a0747790-d393-43dd-8fcb-ee726e3c390d)

![Organization – Character Count.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/aea88f81-c27f-42fc-bdda-7fd6e1ec9665)

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/9/22:** Removed "save" functionality into #110. This ticket is for data input only. 

**Discussion 2/10/22:** Will develop with United States as default (and only) country, and won't include international phone numbers. Those will be covered in #111. Error message is standard angular and will be updated with redesign effort.

**Comment by WiseQA** [comment]
Organization Contact field messages screen shot: 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fe419c02-18be-4d82-a0be-49dad25954e8)

Organization Contact field error messages screen shot:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f24485c9-a17b-46d5-856f-7e9c5acffbf3)

Organization Contact "required fields" screen shot:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/359dd913-dd2b-41cf-a8e8-d0dd7aa2e513)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/9867101e-e089-4454-a16d-4eacdb011a0c/download](https://app.zenhub.com/files/306118986/9867101e-e089-4454-a16d-4eacdb011a0c/download)

QA review completed.  Moved to Stage Ready.
