### ISSUE TITLE
Defect - Logout error when logging in using login.gov in both DEV and STAGE

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#641]
This defect is being written for when logging out of login.gov the following error is received in both DEV and STAGE environments.

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/604138da-28e2-4906-8e3e-209a5e12476d](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/604138da-28e2-4906-8e3e-209a5e12476d))

Steps to reproduce

1\. Login to [https://fecfile-web-app-dev.app.cloud.gov](https://fecfile-web-app-dev.app.cloud.gov) selecting the Login with login.gov button

  ![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/51ab2994-8f5f-4494-91ed-46e91d4f6ba3](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/51ab2994-8f5f-4494-91ed-46e91d4f6ba3))

2\. Verify dashboard appears

3\. Select Logout from the Profile dropdown

  ![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1d6fcb18-3092-4676-a00d-3803240498e5](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1d6fcb18-3092-4676-a00d-3803240498e5))

4\. Following error appears.

  ![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/10b6d1d8-3bbc-4acb-b040-f875e0e854fc](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/10b6d1d8-3bbc-4acb-b040-f875e0e854fc))

Repeat the above steps for [https://fecfile-web-app-stage.app.cloud.gov](https://fecfile-web-app-stage.app.cloud.gov)

DEV

Per @dheitzer comments in slack this is a code fix.

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/adc420d1-7f34-4dee-b2b3-e1c411357724](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/adc420d1-7f34-4dee-b2b3-e1c411357724))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-981](https://fecgov.atlassian.net/browse/FECFILE-981)

**Comment by dheitzer** [comment]
Initial development complete, however during testing I found an issue with one of the new links that login.gov provides during logout 
![image.png](https://images.zenhubusercontent.com/6298ce840c1c301e7c4a4151/01a8ab7d-457d-4608-ae21-dff39ffc4ce8)

![image.png](https://images.zenhubusercontent.com/6298ce840c1c301e7c4a4151/57b6ba81-65b8-4442-a596-986a38fa63dc)

Clicking this displays an error since this link re-sends the original login auth request and fecfile api (mozilla-django package) rejects it due to a potential replay attack.  

I confirmed with login.gov that this is a bug they are working on.

**Comment by dheitzer** [comment]
The fix here was to remove 'id_token_hint' from the oidc logout payload and add 'client_id' as required in [the latest Logout request update from login.gov](https://developers.login.gov/oidc/#logout-request)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified logout error when logging in using login.gov in both DEV and Stage working correctly.
1.  Select Logout verify below page is displayed.  Select "Yes, sign out of Login.gov" button.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4b187a74-8634-4111-89af-b6e1248db835)

2.  Return to login page.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/27693e8b-e6d1-419d-9b1c-356d84a354c4)

QA Review Completed.  Moved to Stage Ready.
