### ISSUE TITLE
Allow user to enter In-kind Receipt on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#642]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”In-kind Receipt”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a receipt
**Then** Click(open) on the "Contributions from Individuals/Persons" Accordion link  
**Then** I can enter a transaction with the type "In-kind Receipt"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	CONTACT TYPE (required, read-only)
-- Individual only
-	LAST NAME (Required)
-	FIRST NAME (Required)
-	MIDDLE NAME (Optional)
-	PREFIX (Optional)
-	SUFFIX (Optional)

# Address 
#
-	STREET ADDRESS (Required)
-	APARTMENT, SUITE, ETC. (Optional)
-	CITY (Required)
-	STATE/PROVINCE (Required)
-	ZIP/POSTAL CODE (Required)
-	EMPLOYER (Required if Aggregate > $200)
-	OCCUPATION (Required if Aggregate > $200)

# Receipt Information 
#
-	DATE RECEIVED (Required)
-	MEMO ITEM (Optional, will be required if CONTRIBUTION DATE falls outside of report dates)
-	AMOUNT (Required, can be negative)
-	AGGREGATE (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	PURPOSE OF RECEIPT (Required, system generated and user updated)
-- Text should read: In Kind: XX
-- And 'XX' is user entered and concatenated with 'In Kind:' within the CPD
**NOTE: System will automatically prefix the entered text with 'In Kind: '**
-	NOTE OR MEMO TEXT (A/N-100, Optional)

---
**Then** I will be able to:

- Cancel
- Edit
- Save both transactions (When this is Saved, an 'In-kind Out' transaction is created on Schedule B as defined in [#739])

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SA11AI.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file (line SA11AII).

 DEV TASKS

- To display 'In Kind:' in the CPD, use https://primeng.org/inputnumber#prefixsuffix as an example

- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=946664839)
- [x] Text under H1 title:
       "This receipt type automatically creates an associated transaction. Saving an in-kind receipt will automatically create an in-kind out."
- [x] First accordion text: "Enter data: Add contact and receipt information"
- [x] Text at the bottom the transaction above second accordion button
- [x] When user opens the page, the first accordion should be defaulted to _open_ with the lookup available.

 Wireframe 

![642 - In-kind Receipt.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0e100d9b-1b90-4e87-9679-ebfb403233d6)

### QA Notes ### 
 - Design note: When user opens the page, the first accordion should be defaulted to _open_ with the lookup available.
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
Wires added and DEV NOTES updated

cc'd:
@mary @JonellaCulmer

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review when tabbing between fields the following error appears: This is a required field.This field contains characters that are not allowed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/584b8592-4537-4bc3-91ec-8b391184456f)

Change error to read: This is a required field.

@mjtravers per review sending back to in-progress for fix.

(Note: Button name changed from "Save" to "Save both transactions" verified from button name change ticket #1135)

**Comment by mjtravers** [comment]
The fix has been made to clean up the error message of the PURPOSE OF RECEIPT/DISBURSEMENT field and pushed to DEV. Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified fix for error message for Purpose of Receipt (Required) field changed to "This is a required field."

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9fe4da3d-f2f9-4429-9ff6-5c79b98747f8)

**Comment by WiseQA** [comment]
QA review verified when selecting "In-kind Receipt" a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/addd6e70-4453-4e97-8581-bf7b0fa757f6)

Verified Contact Type is "Individual" Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e62327d5-e129-4c92-a8a5-120413a02238)

Verified Purpose of Disbursement (Required) field is displayed and the words "In-Kind:" are system generated and the field is editable.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2c585413-af21-40e8-86af-90787584f273)

Verified "Cancel" and "Save both transactions" buttons are displayed.  (Note:  Upon saving the "In-kind out" is auto-populated and displayed in the Transactions table as a disbursement)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c9b83c03-4fbb-4d8a-a371-b24dcfc7a8f2)

Verified "In-kind Receipt" is displayed in the Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/54638278-ca66-44e7-9ceb-1c30af5c26bb)

 (Note:  Upon saving the "In-kind out" is auto-populated and displayed in the Transactions table as a disbursement)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b3153a8a-be73-400f-88bf-f9af1698d60c)

QA Review Completed. Moved to Stage Ready,

**Comment by WiseQA** [comment]
QA review when testing associated In-kind Receipt Disbursement the "Employer" and "Occupation" fields are not saving correctly.   

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/11fc72db-9c9c-4326-b882-a881795d661a)

Once you save the "In-kind Receipt" transaction and reopen from the transactions table, the Employer and Occupation fields are blank.  Not keeping text previously entered.

(NOTE:  Wireframe is incorrect and AC shows - EMPLOYER (Required if Aggregate > $200)
OCCUPATION (Required if Aggregate > $200).  UI ticket made for future design on labels for Employer and Occupation fields)  Will not treat this as a bug @MitchellTCG @mjtravers   

Only test as:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1e67dc5a-88ec-402b-acf6-2fb7eb7de990)

@mjtravers per our review pulled out of Stage Ready for this fix.   Sending back to In-progress for fix.

**Comment by mjtravers** [comment]
Fix has been made for the blank EMPLOYER and OCCUPATION fields when filling out the fields after the contact is selected from the lookup. Passed CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review retested and verified fixes have been implemented in the "In-kind Receipt" transaction is created and is editable once saved. 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3bc40c43-2b28-4b93-a1f7-c19134752575)

Verified Contact Type is "Individual" Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ceb46160-33c8-4031-91c1-e64a95f8fa01)

Verified Purpose of Disbursement (Required) field is displayed and the words "In-Kind:" are system generated and the field is editable.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d372e2c3-fec3-4516-a2c0-e0219851e14a)

Verified "In-kind Receipt" is displayed in the Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e8d1c8ac-30a2-404f-a10d-ade911dd76ec)

(Note: Upon saving the "In-kind out" is auto-populated and displayed in the Transactions table as a disbursement)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8a45b68f-c654-429a-96e7-7ec141b2c65b)

Retested and verified the fix for Employer and Occupation fields are staying populated once transactions are saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e39283a4-87d1-457f-9ade-0ad3f9d6c8d9)

QA Review Completed. Moved to Stage Ready.
