### ISSUE TITLE
Allow user to enter Conduit Earmark (Undeposited) on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#644]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Conduit Earmark (Undeposited)”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

NOTE: This transaction requires a "child" (memo) transaction on Schedule B that will be associated with a parent transaction.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Contributions from Individuals/Persons" Accordion link  
**Then** I can enter a transaction with the type "Conduit Earmark (Undeposited)"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Conduit 
#
-	CONDUIT TYPE (Required, includes LOOKUP)
-- Individual only
-	LAST NAME (Required)
-	FIRST NAME (Required)
-	MIDDLE NAME (Optional)
-	PREFIX (Optional)
-	SUFFIX (Optional)

# Address 
#
-	STREET ADDRESS (Required)
-	APARTMENT, SUITE, ETC. (Optional)
-	CITY (Required)
-	STATE/PROVINCE (Required)
-	ZIP/POSTAL CODE (Required)

# Receipt Infomation 
#
-	DATE RECEIVED (Required)
-	MEMO ITEM (Required)
-- This will be automatically **checked** and the user CANNOT change it.
-	AMOUNT (Required, can be negative)
-	EMPLOYER (Required if **AMOUNT** > $200)
-	OCCUPATION (Required if **AMOUNT** > $200)

# Additional information 
#
-	PURPOSE OF RECEIPT (Required, system generated)
"Earmarked through XX" where XX is the conduit from the associated Conduit Earmark Memo
-	NOTE OR MEMO TEXT (Optional)

---
**Then** I will be able to:

- Cancel
- Save
- Edit

**And the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SA11AI.

(Note: user will not be able to save at this point. They must save with Conduit Earmark Memo, which requires ticket [#746](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/746))

 DEV TASKS
- [ ] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=450199144) **This is a consolidated specification**
- [ ] Text under the "Conduit Earmark" H1 - 
       This receipt type requires an associated transaction. Follow this two-step process to create both an earmark receipt and an earmark memo:
- [ ] When toggle is on Undeposited the front end will read "(a check) MEMO ITEM" - The backend will carry the same value as an unchecked memo item box.
- [ ] Above the second accordion block the following text will appear: "This type of receipt requires a memo transaction."
- [ ] SVG check Icon attached below

# Icon 
#
![Check.svg](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f4379c6c-7bac-4fb7-9b6e-9d2491478040)

 WIREFRAME
![643 - Conduit Earmark – Closed.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/b14a3e27-0088-44b3-853a-b1a7324b14cd)

![644 - Conduit Earmark (Undeposited).png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0320d908-98b3-4e0b-a35c-c02906a5f8ef)

### QA Notes ### 
 - There is no aggregate for this transaction. Transaction will be itemized, regardless of amount.
- Because there is no aggregate, EMP/OCC is only required it the AMOUNT is over $200.
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@GreggMoreland @AureliaKhorsand @MitchellTCG wireframe updated

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
Wires added and DEV NOTES updated

cc'd:
@mary @JonellaCulmer

**Comment by AureliaKhorsand** [comment]
Closing as OBE since we're combining deposited and undeposited.
