### ISSUE TITLE
Allow user to enter Party In-kind Receipt on Schedule A (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#645]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Party In-kind Receipt”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a receipt
**Then** Click(open) on the "Contributions from Registered Filers" Accordion link  
**Then** I can enter a transaction with the type "Party In-kind Receipt"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**CONTRIBUTION DATE** (Required)
-	**MEMO ITEM** (Optional, will be required if CONTRIBUTION DATE falls outside of report dates)
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required) _(Dev/QA Note: Aggregation Group is "GENERAL")_
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	PURPOSE OF RECEIPT (Required, system generated and user updated)
-- Text should read: In Kind: XX
-- And 'XX' is user entered and concatenated with 'In Kind:' within the CPD
**NOTE: System will automatically prefix the entered text with 'In Kind: '**
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save both transactions (When this is Saved, an 'In kind Out' transaction is created on Schedule B as defined in [#740]
- Edit 

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SA11B _(everything on Line 11B is itemized regardless of amount)._

 QA Note 

 Dev Note 

- To display 'In Kind:' in the CPD, use https://primeng.org/inputnumber#prefixsuffix as an example

- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=364628495) **This is a consolidated specification**

 Wireframe 

![645 - Party In-Kind Receipt.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/ea0b6c5c-a514-4ec4-89f9-35c4f97ae479)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@mary-tcg 
Please add the wire to this ticket

**Comment by mary-tcg** [comment]
@MitchellTCG @AureliaKhorsand @GreggMoreland wire updated

**Comment by WiseQA** [comment]
QA review verified when selecting "Party In-kind Receipt" a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cd45bc42-4d2a-4f20-80ef-137fe6b86b13)

Verified Contact Type is "Committee" Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3392c40c-abf1-4df3-8358-034a45aafa2d)

Verified Purpose of Disbursement (Required) field is displayed and the words "In-Kind:" are system generated and the field is editable.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/01101bb5-5329-43ce-912f-8260f5d28f51)

Verified "Cancel" and "Save both transactions" buttons are displayed. (Note: Upon saving the "In-kind out" is auto-populated and displayed in the Transactions table as a disbursement)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/439b0e83-6222-4d11-b526-33b9578f0041)

Verified "Party In-kind Receipt" is displayed in the Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e6230be2-47df-49fa-af19-f314d3050023)

(Note: Upon saving the "Party In-kind out" is auto-populated and displayed in the Transactions table as a disbursement)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1fd5b86f-f122-4935-8297-8e82ba6a2b92)

QA Review Completed.   Moved to Stage Ready.
