### ISSUE TITLE
Allow user to enter PAC In-kind Receipt on Schedule A (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#646]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”PAC In-kind Receipt”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a receipt 
**Then** Click(open) on the "Contributions from Registered Filers" Accordion link  
**Then** I can enter a transaction with the type "PAC In-kind Receipt"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**CONTRIBUTION DATE** (Required)
-	**MEMO ITEM** (Optional, will be required if CONTRIBUTION DATE falls outside of report dates))
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required) _(Dev/QA Note: Aggregation Group is "GENERAL")_
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	PURPOSE OF RECEIPT (Required, system generated and user updated)
-- Text should read: In Kind: XX
-- And 'XX' is user entered and concatenated with 'In Kind:' within the CPD
**NOTE: System will automatically prefix the entered text with 'In Kind: '**
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save both transactions (When this is Saved, an 'In kind Out' transaction is created on Schedule B as defined in [#741]
- Edit 

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SA11C _(Note everything on line 11C is itemized regardless of amount)._

 QA Note 

 Dev Note 

- To display 'In Kind:' in the CPD, use https://primeng.org/inputnumber#prefixsuffix as an example

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#
- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=364628495) **This is a consolidated specification**

 Wireframe 
![646 - PAC In-Kind Receipt.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/e46bacc6-6851-4488-bef1-e50d94b16371)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@mary-tcg 
Please add the wire to this ticket

**Comment by mary-tcg** [comment]
@MitchellTCG @AureliaKhorsand @GreggMoreland wire added

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "PAC In-kind Receipt" a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b6df085d-1d87-4c3c-8861-2d94143d9c3c)

Verified Contact Type is "Committee" Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6641e131-bb0e-4c67-809c-d2ce848f8c10)

Verified Purpose of Disbursement (Required) field is displayed and the words "In-Kind:" are system generated and the field is editable.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8934cef7-ed60-41dd-a4a3-69d4208a779c)

Verified "PAC In-kind Receipt" is displayed in the Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/24952f4b-8023-45c7-890c-9f279855a342)

(Note: Upon saving the "PAC In-kind out" is auto-populated and displayed in the Transactions table as a disbursement)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a02922c0-f1f1-4bca-af68-f1c24cd4e0af)

QA Review Completed. Moved to Stage Ready.
