### ISSUE TITLE
Allow user to enter PAC Conduit Earmark (Undeposited) on Schedule A (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#648]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”PAC Conduit Earmark (Undeposited)”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

NOTE: This transaction requires a "child" (memo) transaction on Schedule B that will be associated with a parent transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a receipt
**Then** Click(open) on the "Contributions from Registered Filers" Accordion link  
**Then** I can enter a transaction with the type "PAC Conduit Earmark (Undeposited)"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Conduitt 
#
-	**CONDUIT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	**CONDUIT NAME** (Required)
-	**CONDUIT ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**CONTRIBUTION DATE** (Required)
-	**MEMO ITEM** (Required)
-- This will be automatically **checked** and the user CANNOT change it.
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.

# Additional information 
#
-	**PURPOSE OF RECEIPT** (Required, system generated)
"Earmarked through XX" where XX is the conduit from the associated PAC Conduit Earmark Memo
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save
- Edit

**And the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SA11C.

(Note: user will not be able to save at this point. They must save with Earmark Memo, which requires ticket [#748](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/748))

 QA Note
- There is no aggregate for this transaction. Transaction will be itemized, regardless of amount.

 Dev Note 

- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=950031027) **This is a consolidated specification**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
Closing as OBE since we're combining deposited and undeposited.
