### ISSUE TITLE
Allow user to enter In-kind Transfer on Schedule A (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#649]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”In-kind Transfer”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a receipt
**Then** Click(open) on the "Transfers" Accordion link  
**Then** I can enter a transaction with the type "In-kind Transfer "
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**CONTRIBUTION DATE** (Required)
-	**MEMO ITEM** (Optional, will be required if CONTRIBUTION DATE falls outside of report dates)
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required) _(Dev/QA Note: Aggregation Group is "GENERAL")_
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	PURPOSE OF RECEIPT (Required, system generated and user updated)
-- Text should read: In Kind: XX
-- And 'XX' is user entered and concatenated with 'In Kind:' within the CPD
**NOTE: System will automatically prefix the entered text with 'In Kind: '**
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save both transactions (When this is Saved, an 'In kind Out' transaction is created on Schedule B as defined in [#742]
- Edit as needed

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file in line SA12 _(Note everything on Line 12 is itemized regardless of amount)._

 QA Note 

 Dev Note 

- To display 'In Kind:' in the CPD, use https://primeng.org/inputnumber#prefixsuffix as an example

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#
- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=364628495) **This is a consolidated specification**

 Wireframe 

![649 - In-Kind Transfer.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/cd8f8734-6a7e-45cf-950e-9b5f745484a2)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@mary-tcg 
Please add the wire to this ticket

**Comment by mary-tcg** [comment]
@MitchellTCG @AureliaKhorsand @GreggMoreland wire added

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/5129e406-4c99-4239-97a4-13e9736b2aa2)

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/104e64ef-c6ce-4019-8d98-6815eb3275ec)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "In-kind Transfer" a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f18d1f0c-896e-435d-bfd4-84e76fc9c846)

Verified Contact Type is "Committee" Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fac72ecd-f99a-4868-9244-9c3971c856ee)

Verified Purpose of Disbursement (Required) field is displayed and the words "In-Kind:" are system generated and the field is editable.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b82e265a-e500-4d4b-b144-03be4851872c)

Verified "In-kind Transfer" is displayed in the Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9774f237-4e10-415c-a464-26094cf13946)

(Note: Upon saving the "In-kind Transfer out" is auto-populated and displayed in the Transactions table as a disbursement)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5384d3bf-d5bd-408b-8deb-2723ab1a4fdd)

QA Review Completed. Moved to Stage Ready.
