### ISSUE TITLE
Allow user to enter In-kind Transfer - Federal Election Activity on Schedule A (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#650]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”In-kind Transfer - Federal Election Activity”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a receipt
**Then** Click (open) on the "Transfers" Accordion link  
**Then** I can enter a transaction with the type "In-kind Transfer - Federal Election Activity "
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-- Committee Only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**CONTRIBUTION DATE** (Required)
-	**MEMO ITEM** (Optional, will be required if CONTRIBUTION DATE falls outside of report dates)
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required) _(Dev/QA Note: Aggregation Group is "GENERAL")_
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF RECEIPT** (Required)
-- Text should read: In Kind: XX
-- And 'XX' is user entered and concatenated with 'In Kind:' within the Purpose Description
**NOTE: System will automatically prefix the entered text with 'In Kind: '**
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Save both transactions (When this is Saved, an 'In kind Out' transaction is created on Schedule B as defined in [#743]
- Edit 

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SA12

 QA Note 

 Dev Note 

- To display 'In Kind:' in the CPD, use https://primeng.org/inputnumber#prefixsuffix as an example

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#
- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=364628495) **This is a consolidated specification**

 Wireframe 

![650 - In-Kind Transfer Federal Election Activity.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/4524c1b1-1596-4c02-a5e2-706f3021d0cd)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@mary-tcg 
Please add the wire to this ticket

**Comment by mary-tcg** [comment]
@MitchellTCG @AureliaKhorsand @GreggMoreland wire added

**Comment by mary-tcg** [comment]
@AureliaKhorsand @MitchellTCG @GreggMoreland  added dash to transaction title as requested

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/068dadb1-8483-426e-97a3-4e6b5efc7175)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "In-kind Transfer - Federal Election Activity" a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c6b0988e-0235-4735-ad8f-d18478c5b5d3)

Verified Contact Type is "Committee" Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5e47a511-afc7-489d-b4a1-8d5a54a8aa64)

Verified Purpose of Disbursement (Required) field is displayed and the words "In-Kind:" are system generated and the field is editable.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7da57c81-1ef0-4241-a3ff-c81b921ae828)

Verified "In-kind Transfer - Federal Election Activity" is displayed in the Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6c1147a9-4d2a-4f79-b7d7-db31a10a819d)

(Note: Upon saving the "In-kind Transfer Federal Election Activity Out" is auto-populated and displayed in the Transactions table as a disbursement)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e5ab9841-a110-40cb-9784-31b3efb3e3f0)

QA Review Completed. Moved to Stage Ready.
