### ISSUE TITLE
System to automatically itemize transaction when Aggregate is less than $0.00

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#651]
Business Reason

As a FECfile user, I will be able to see all transactions itemized by the system whenever the aggregate falls below $0.00 so that I can accurately view my committee's transactions.

Acceptance Criteria

***Given*** a user is saving a transaction

 ***When*** the Aggregate is calculated to be less than $0.00 (a negative value)

 ***Then*** the transaction will be itemized upon saving

 ***and*** appear on it's own line item on the *.fec file

### QA Notes ###
Negative value includes "-" symbol - max at $-99,999,999.99 (total 12 characters) instead of positive value  max at $999,999,999.99
No limitation of negative value per Ryan 12/06/2022
This should apply to any transaction we have built out. 
For testing, this will be adhoc testing based on the amount of transactions built at the time of implementation. Will also have testing coverage with E2E testing.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-971](https://fecgov.atlassian.net/browse/FECFILE-971)

**Comment by mjtravers** [comment]
Passes CR. Holding ticket in Code Review until Sprint-17 tickets are all moved to Stage Ready.

**Comment by WiseQA** [comment]
QA review verified aggregate is less than $0.00 is negative value.  Negative value (includes the - and $ symbols) value 12 characters.  Max negative value is at $-99,999,999.99

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/790c0ca2-811d-4e60-82fa-537c2e545b7f)

Retesting these values.

QA Review Completed.  Moved to Stage Ready.
