### ISSUE TITLE
508 Compliance: Set up Lighthouse with Cypress

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#652]
Business Reason

As a the product owner, I would like 508 Compliance scan run with our processes to make sure we are always 508 compliant

Dev Notes

Overview:
[https://developer.chrome.com/docs/lighthouse/overview/](https://developer.chrome.com/docs/lighthouse/overview/)
[https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md)

Cypress & Lighthouse:
[https://glebbahmutov.com/blog/cypress-lighthouse/](https://glebbahmutov.com/blog/cypress-lighthouse/)
[https://www.lambdatest.com/blog/using-cypress-google-lighthouse-performance-testing/](https://www.lambdatest.com/blog/using-cypress-google-lighthouse-performance-testing/)

Acceptance Criteria

Lighthouse is run in conjunction with our Cypress e2e tests and reports are produced for verification and documentation of accessibility.

### QA Notes ###

This is a visual inspection of the screenshots in the comments below.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-970](https://fecgov.atlassian.net/browse/FECFILE-970)

**Comment by Elaine-Krauss-TCG** [comment]
Cypress integration is done.  Due to the design of Lighthouse, it is not able to test any pop-ups, notably including the contact forms.

**Comment by Elaine-Krauss-TCG** [comment]
Lighthouse generates individual reports for each page tested

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/9553bcda-0940-463a-b111-9b8c411db702)
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/1b8b2aea-da23-46c7-bd25-9c10366560a5)

**Comment by Elaine-Krauss-TCG** [comment]
An actual report file:
[Uploading... transaction-creation-group-AG.html]

**Comment by Elaine-Krauss-TCG** [comment]
The lighthouse testing runs as a cypress test.  Currently, all pages are passing
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/b6686242-0c14-415b-b3de-aec9d9a9f2c6)

**Comment by Elaine-Krauss-TCG** [comment]
The Cypress test for a page will fail if Lighthouse reports an accessibility score below 90.

Performance, "best practices," search-engine-optimization, and "pwa" are measured, but low scores in these categories will *not* cause the Cypress test to fail.

**Comment by mjtravers** [comment]
Passes CR. Holding off from sending to QA until all the Sprint 17 tickets are sent to Stage Ready.

**Comment by WiseQA** [comment]
@MitchellTCG per our conversation, you, @mjtravers and myself to verify 508 compliance is being met as a visual. 

No QA inspection required on this ticket and no validation on this ticket to be performed by QA.

Moved to Stage Ready per @MitchellTCG
