### ISSUE TITLE
Allow user to enter Partnership National Party Recount/Legal Proceedings Account on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#656]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Partnership National Party Recount/Legal Proceedings Account”** transaction on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "parent" transaction that will have an associated child ‘Memo’ transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other" Accordion link  
**Then** I can enter a transaction with the type "Partnership National Party Recount/Legal Proceedings Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	CONTACT TYPE (Read-only, **includes Lookup**)
-- Organization Only
-	ORGANIZATION NAME (Required)

# Address 
#
-	STREET ADDRESS (Required)
-	APARTMENT, SUITE, ETC. (Optional)
-	CITY (Required)
-	STATE/PROVINCE (Required)
-	ZIP/POSTAL CODE (Required)

# Receipt Information 
#
-	DATE RECEIVED (Required)
-	MEMO ITEM (Optional)
-	AMOUNT (Required)
-- Note: AMOUNT can contain a negative value.
-	AGGREGATE (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "NATIONAL_PARTY_RECOUNT_ACCOUNT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	CONTRIBUTION PURPOSE DESCRIPTION (System generated)
-- If transaction has no associated Partnership memos, reads "Recount/Legal Proceedings Account (Partnership attributions do not require itemization)".
--If transaction has associated Partnership memos, reads "Recount/Legal Proceedings Account (See Partnership Attribution(s) below)"

-	NOTE OR MEMO TEXT (Optional)

---
**Then** I will be able to:

- Cancel
- Save & add another 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- Note the italics above the Contribution Purpose Description field.
- For Contribution Purpose Description field text:
-- If transaction has no associated Partnership memos, reads "Recount/Legal Proceedings Account (Partnership attributions do not require itemization)".
--If transaction has associated Partnership memos, reads "Recount/Legal Proceedings Account (See Partnership Attribution(s) below)"

 Dev Note 

- Note the italics above the Contribution Purpose Description field.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=622262881) **Please note this a "consolidated" specification.**

![27b614c1-5674-4228-9d7d-e005477c8c8f.png](https://images.zenhubusercontent.com/62eac7883f87756fe900911f/f9400e2c-eac7-47de-bdea-3c333215ff58)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
First consolidated specification ticket, must be completed before other consolidated spec tickets.

**Comment by dheitzer** [comment]
pushed an initial implementation of the shared spec to devs for code review.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA

**Comment by WiseQA** [comment]
QA review verified Partnership National Party Recount/Legal Proceedings Account transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bc141104-4631-40a8-8682-a7bd92ec9fd1)

Verified when Partnership National Party Recount/Legal Proceedings Account saved without a memo the following message is displayed.
 "Recount/Legal Proceedings Account (Partnership attributions do not require itemization)"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cba2cfd2-2af0-4990-b8c4-31a9dd12d872)

Verified when Partnership National Party Recount/Legal Proceedings Account saved with a memo the following message is displayed. "Recount/Legal Proceedings Account (Partnership attributions do not require itemization)


![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/85013b5b-1f03-4f5d-af20-819dbe736b9e)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dbd1b7b5-831a-4aed-8f76-0e720654552f)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e984ba27-7e40-491e-8625-2d45d04f9e41)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0ffbba13-5737-4718-b2ce-f4884866f58e)

Verified “Cancel” and “Save & view all transactions” buttons functional and working.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0bd5a225-7df2-4fce-a2e0-c1289bd2d5ff)

QA Review Completed.   Moved to Stage Ready.
