### ISSUE TITLE
Allow user to enter Partnership National Party Recount/Legal Proceedings Account Memo on Schedule A (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#657]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **’Partnership National Party Recount/Legal Proceedings Account Memo‘** sub-transaction under **"Partnership National Party Recount/Legal Proceedings Account"** on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

NOTE: This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator
**And** I am editing a Partnership National Party Recount/Legal Proceedings Account transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction:
- Partnership National Party Recount/Legal Proceedings Account Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, **includes Lookup**)
-- INDIVIDUAL only

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (A/N-10, Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Required)
This will be automatically checked and the user CANNOT change it.
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "NATIONAL_PARTY_RECOUNT_ACCOUNT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.
-	**EMPLOYER** (Required if Aggregate > $200)
-	**OCCUPATION** (Required if Aggregate > $200)

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (System generated)
Data field: multi-line textbox that must read "Recount/Legal Proceedings Account Partnership Attribution”
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:

- Cancel
- Go back to parent transaction 'Partnership National Party Recount/Legal Proceedings Account'
- Save & view all transactions
- Save & add another memo transaction
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note 

Pre-requisite - create a Partnership National Party Recount/Legal Proceedings Account and saved in the Transactions Table.

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1492384539) **Please note this is a consolidated specification**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Ready for QA

**Comment by WiseQA** [comment]
QA review select Partnership National Party Recount/Legal Proceedings Account from the transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d12778ae-7db9-42f9-95ff-ab12a4225f22)

Select Partnership National Party Recount/Legal Proceedings Account Memo from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ec12e979-57b9-43b1-b6ec-d4c20edcea72)

QA review verified Partnership National Party Recount/Legal Proceedings Account Memo transaction is created and is editable once saved.

NOTE:  Button naming changed - verifying with UX.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f6ab2596-f1f9-4502-a9e5-85c9c9211fa7)

@MitchellTCG @GreggMoreland @AureliaKhorsand sent email for clarification of button naming.   Awaiting verification.

**Comment by MitchellTCG** [comment]
ON HOLD TIL I COME BACK WITH A SOLUTION

**Comment by MitchellTCG** [comment]
Until there is a holistic ticket to replace all cancel/back button provided by and sign off by our stakeholder @JonellaCulmer , we the naming convention will stay "back to [complete name of parent transaction]"

This upcoming ticket will be in Sprint 21.

**Comment by WiseQA** [comment]
QA review verified buttons working as designed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4dc2a752-b916-40ee-87de-eace5b21a9dd)

Verified Partnership National Party Recount/Legal Proceedings Account Memo saved and displayed in Transactions Table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/63aeb64e-5244-4c89-b8ec-206e0e48c8f6)

QA Review Completed.   Moved to Stage Ready
