### ISSUE TITLE
Update user message for when contact info is removed while updating

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#663]
Task: Update the language from "Updated [field] to [new value]" to "Removed [field]" when a user removes optional contact information while editing contact info within a transaction. Right now, the new value shows as "Undefined" or "blank" and is not user-friendly.

***Acceptance Criteria:***

***If*** the user makes edits to the contact information by _removing_ an optional field

  ***When*** the user goes to save the transaction (whether it's Save and Add More or Save and View Transactions)

  ***Then*** the message for the field they removed data for will read under Change(s):

*   "Removed [field label name]

***And*** the user will be able to

*   Continue (this will save the transaction and contact at this point)
*   Cancel (this just takes them back to the transaction form to continue editing)

       ![663 -Update user message – 1.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/128b0e67-a477-47a4-a192-82919731a778](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/128b0e67-a477-47a4-a192-82919731a778))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-965](https://fecgov.atlassian.net/browse/FECFILE-965)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified when contact info is "Removed" and "Save & view all transactions" the following message appears:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7013192b-2e58-4e41-8b0f-d2fd22c7fcaa)


QA review reverified and retested functionality when contact info is updated (added Apartment, Suite, etc. which was blank) and "Save & view all transactions" the following message appears with "Updated ..." still working as designed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ecb21ace-080e-4163-a34a-389431dc0dd2)

QA Review Completed.   Moved to Stage Ready.
