### ISSUE TITLE
Refactor group transaction screens to use new input components

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#669]
***Dev Tasks***

  Refactor group A - F and AG transaction HTML templates to use the new input components

***QA Notes***

  Ad hoc test the following transaction screens. e2e testing will cover the full regression testing.

*   INDIVIDUAL_RECEIPT (A group)
*   OFFSET_TO_OPERATING_EXPENDITURES (B group)
*   OTHER_RECEIPT (C group)
*   TRIBAL_RECEIPT (D group)
*   JOINT_FUNDRAISING_TRANSFER (E group)
*   TRANSFER (F group)
*   EARMARK MEMO (AG group)

### QA Notes ###
Refactor group A - F and AG transaction HTML templates to use the new input components

**QA Notes**
Ad hoc test the following transaction screens. e2e testing will cover the full regression testing.
- INDIVIDUAL_RECEIPT (A group)
- OFFSET_TO_OPERATING_EXPENDITURES (B group)
- OTHER_RECEIPT (C group)
- TRIBAL_RECEIPT (D group)
- JOINT_FUNDRAISING_TRANSFER (E group)
- TRANSFER (F group)
- EARMARK MEMO (AG group)

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-963](https://fecgov.atlassian.net/browse/FECFILE-963)

**Comment by mjtravers** [comment]
Passes CR. Holding off from sending to QA until all the Sprint 17 tickets are sent to Stage Ready.

**Comment by WiseQA** [comment]
QA review verified following transaction screens appear as denoted in acceptance criteria.

(Note:  e2e testing will cover the full regression testing of these transactions)

INDIVIDUAL_RECEIPT (A group)
OFFSET_TO_OPERATING_EXPENDITURES (B group)
OTHER_RECEIPT (C group)
TRIBAL_RECEIPT (D group)
JOINT_FUNDRAISING_TRANSFER (E group)
TRANSFER (F group)
EARMARK MEMO (AG group)

QA Review Completed.   Moved to Stage Ready.
