### ISSUE TITLE
Defect - "Amount" field exceeding max amount of $999,999,999.99

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#673]
Business Reason

This defect is to correct the "Amount" field requirement amount should be max at $999,999,999.99, shouldn't be able to reach $1 billion but you can currently enter $999,999,999,999.99 in amount field.

This defect was found in Sprint 16 the Transfer transaction.

e2e testing will be performed on the Transfer transaction and the other transactions developed to date to verify Amount field is correct.

(Note: e2e testing caught this error, and will be retested both QA review and e2e testing)

### QA Notes ###
THIS TICKET WILL NOT BE MOVED TO STAGE READY UNTIL FINAL QA REVIEW:

Elaine will need to run a new e2e test on this functionality and move through the process of CR.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-962](https://fecgov.atlassian.net/browse/FECFILE-962)

**Comment by Elaine-Krauss-TCG** [comment]
All transactions creating with this schema
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/c58aa9c5-1452-480f-b383-173367f9fa01)

All transactions passing field testing with this schema
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/ecfd7783-0ef6-411c-96eb-9a5664cb5373)

**Comment by WiseQA** [comment]
No Code Review denoted in ticket,  Returned for Code Reviewer ?   @toddlees are you code reviewing ?

**Comment by toddlees** [comment]
Passed CR, moving to QA

**Comment by toddlees** [comment]
Passed CR, E2E tests run, moving to QA

**Comment by WiseQA** [comment]
QA review verified "Amount" field cannot exceed max amount of $999,999,999.99.  Verified could not "Save".  (Note adhoc tested entering incorrect amount $999,999,999,999,99 Transfer, Other Receipts, Tribal Receipts).   

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d236737c-7008-4e27-ab84-e980da74e223)

Verified "Amount" field cannot exceed max amount of $999,999,999.99.  Entered correct max amount and verified when "Save" both contribution amount and aggregate amount were correct in transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9980fe87-aa2e-457e-80c8-ac9240c53774)

e2e Testing will be performed on the transactions currently developed for this fix.

QA Review Completed.
