### ISSUE TITLE
Allow user to enter Credit Card Payment for Operating Expenditure on Schedule B (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#679]
Business Reason

As a Committee Administrator, I will be able to enter a ***”Credit Card Payment for Operating Expenditure”*** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

 ***Then*** Add a Disbursement

 ***Then*** Click (open) on the "Operating Expenditures" Accordion link

 ***Then*** I can enter a transaction with the type “Credit Card Payment for Operating Expenditure"

 ***Then*** I will be required to enter the following information (unless otherwise noted):

—

Contact

 #

*   ***CONTACT TYPE***

      -Organization only
*   ***ORGANIZATION NAME*** (Required)

1.  Address

      #

*   ***STREET ADDRESS*** (Required)
*   ***APARTMENT, SUITE, ETC.*** (Optional)
*   ***CITY*** (Required)
*   ***STATE/PROVINCE*** (Required)
*   ***ZIP/POSTAL CODE*** (Required)

1.  Expenditure Information

      #

*   ***DATE*** (Required)
*   ***MEMO ITEM*** (Optional)
*   ***AMOUNT*** (Required)

      ***Note:*** AMOUNT can be a negative amount
*   ***AGGREGATE*** (Required)
      *   Amount Displayed will be the total of contributions that are:
            *   From the person (ENTITY)
    *   within Aggregation Group of "GENERAL_DISBURSEMENT"
            *   _from_ January 1 of report year _to_ the Contribution Date* of the transaction.
        *   *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

1.  Additional information

      #

*   ***PURPOSE OF DISBURSEMENT*** (Required, system generated)

      --Text must read: 'Credit Card: See Below'
*   ***NOTE OR MEMO TEXT*** (Optional)
*   ***CATEGORY CODE*** (Optional)

—

 ***Then*** I will be able to:

*   Go back to previous page without saving
*   Save & add another
*   Save & Add Memo
*   Save & view all transactions [will go to "Manage your transactions" Table]
*   Edit

***And if*** the Aggregate amount is >= $200.01,

 ***Then*** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

***If*** the Aggregate amount is [Spec Updates spreadsheet tab here]( [https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=367598665](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=367598665)) ***Please note this is a consolidated specification.***

Wireframes

1.  Committee

      #

      ![Operating expenditure - COM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ef185812-7ec0-4be8-8d50-d8925876b4f7](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ef185812-7ec0-4be8-8d50-d8925876b4f7))

1.  Committee w/dropdown

      #

      ![Operating expenditure - COM – Dropdown.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/dd5d484a-6c2c-4370-b0f9-33196fb34032](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/dd5d484a-6c2c-4370-b0f9-33196fb34032))

1.  Individual

      #

      ![Operating expenditure - IND.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d77b6260-957d-4138-81d3-3d5726bf2e04](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d77b6260-957d-4138-81d3-3d5726bf2e04))

1.  Organization

      #

      ![Operating expenditure - ORG.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/372b1460-7559-4cc4-bfcc-2e650c615a05](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/372b1460-7559-4cc4-bfcc-2e650c615a05))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-960](https://fecgov.atlassian.net/browse/FECFILE-960)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @mary-tcg @JonellaCulmer 

I updated and attached Schedule B transactions here

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/e01e1954-65c2-47a0-b21a-70cdd888d734)

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/c32e45ac-bbfe-48da-b655-496bd190050a)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA on DEV. Note the change in acceptance criteria for the Save & Add Memo button. That button will be visible and testable in the future tickets for the memo transactions for this parent transaction.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Credit Card Payment for Operating Expenditure a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/eed79d7b-77b3-4093-a7b5-6c667296469a)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3283c74a-fa70-413a-95e5-c5ad64631ed3)

Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed 'Credit Card: See Below'.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6b7adac9-0943-4436-af01-91c8ea7e1306)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c2302c12-3a6c-4f87-b4b4-4f8502d22bfb)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/06e6a6a0-fa0d-4b29-bab8-ee9cef36ead9)

QA Review Completed.   Moved to Stage Ready.
