### ISSUE TITLE
Allow user to edit an existing Individual contact

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#68]
Business Reason 
 

As a Committee Administrator, I will be able to edit an existing contact so that I can maintain an accurate database of contacts as contact metadata such as addresses, employers, etc. change over time.

 Acceptance Criteria 
 

**If** I am a Committee Administrator
**When** I access my committee's contact list and select an Individual type contact
**Then** I will be able to edit and save any of that contact's data **except Type**

 Dev Notes 
 
So, that a Contact name will appear on the Contact Page, find a way for the name to display in the  Contact Table:
 **First Name**  **Last Name**

Dev Tasks:
1. refactor old code
2. unit tests
3. documentation
4. logging in the back-end
5. accessible in the UI

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
Per Ryan 2/10/22 :  [Committee and Candidate IDs] should be editable in case there is a reason they entered the incorrect ID. There are instances where committees and candidates register more than once, which creates multiple IDs.  These scenarios are rare, but again we should allow the user to update if needed. For now, we want to give users maximum flexibility in their data entry.

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/23/22:** Split out ticket by contact type to aid in testing. Additional contact type tickets will also be a 3, team agreed on call.

**Comment by WiseQA** [comment]
Contacts screen selecting Individual contact:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/68d594fa-dfa6-42e4-9c50-7107de63f5a3)

Successful - Contact Updated Popup Screen Shot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/28afe654-0dd1-4c77-9b90-6c0c97d5fac2)

Contacts screen showing Individual edit name successful:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ac16577b-55f3-469f-8a57-9e442c143f9a)

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/930a2c98-3ee0-4ba8-a953-862e1a2b0b98/download](https://app.zenhub.com/files/306118986/930a2c98-3ee0-4ba8-a953-862e1a2b0b98/download)

QA review completed.  Moved to Stage Ready.
