### ISSUE TITLE
Allow user to enter Staff Reimbursement for Operating Expenditure on Schedule B (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#681]
Business Reason

As a Committee Administrator, I will be able to enter a ***”Staff Reimbursement for Operating Expenditure”*** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

 ***Then*** Add a Disbursement

 ***Then*** Click(open) on the "Operating Expenditures" Accordion link

 ***Then*** I can enter a transaction with the type “Staff Reimbursement for Operating Expenditure "

 ***Then*** I will be required to enter the following information (unless otherwise noted):

—

Contact

 #

*   ***CONTACT TYPE***

      -Individual Only

*   ***LAST NAME*** (Required)
*   ***FIRST NAME*** (Required)
*   ***MIDDLE NAME*** (Optional)
*   ***PREFIX*** (Optional)
*   ***SUFFIX*** (Optional)

1.  Address

      #

*   ***STREET ADDRESS*** (Required)
*   ***APARTMENT, SUITE, ETC.*** (Optional)
*   ***CITY*** (Required)
*   ***STATE/PROVINCE*** (Required)
*   ***ZIP/POSTAL CODE*** (Required)

1.  Expenditure Information

      #

*   ***DATE*** (Required)
*   ***MEMO ITEM*** (Optional)
*   ***AMOUNT*** (Required)

      ***Note:*** AMOUNT can be a negative amount
*   ***AGGREGATE*** (Required)
      *   Amount Displayed will be the total of contributions that are:
            *   From the person (ENTITY)
    *   within Aggregation Group of "GENERAL_DISBURSEMENT"
            *   _from_ January 1 of report year _to_ the Contribution Date* of the transaction.
        *   *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

1.  Additional information

      #

*   ***PURPOSE OF DISBURSEMENT*** (Required, System generated)

      --Text must read: "Reimbursement: See Below"
*   ***NOTE OR MEMO TEXT*** (Optional)
*   ***CATEGORY CODE*** (Optional)

—

 ***Then*** I will be able to:

*   Go back to previous page without saving
*   Save & add another
*   Save & Add Memo
*   Save & view all transactions [will go to "Manage your transactions" Table]
*   Edit

***And if*** the Aggregate amount is >= $200.01,

 ***Then*** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

***If*** the Aggregate amount is [Spec Updates spreadsheet tab here]([https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=674454239](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=674454239)) ***Please note this is a consolidated specification.***

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-958](https://fecgov.atlassian.net/browse/FECFILE-958)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA on DEV. Note the change in acceptance criteria for the Save & Add Memo button. That button will be visible and testable in the future tickets for the memo transactions for this parent transaction.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Staff Reimbursement for Operating Expenditure a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/be7cbb07-0dcf-4edb-9a64-d66eddc2ec28)

Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed 'Reimbursement: See Below'.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/99d6c2c5-9303-4eeb-aa80-d759fec11d76)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/da24581e-5d97-4448-a55c-ab3a445a4b85)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/049d8bd2-d203-42a8-a4d1-f467331003cc)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cdd8c834-c263-4f0a-bd20-21ece301c0e5)

QA Review Completed. Moved to Stage Ready.
