### ISSUE TITLE
Allow user to enter Staff Reimbursement Memo for Operating Expenditure on Schedule B (Group B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#682]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Staff Reimbursement Memo for Operating Expenditure”** sub-transaction under **”Staff Reimbursement for Operating Expenditure”** on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator 
**And** I am editing a Staff Reimbursement for Operating Expenditure transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction: 
- Staff Reimbursement Memo for Operating Expenditure

**And** I will be required to enter the following information (unless otherwise noted):

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee 
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Required, must be checked)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Go back to previous page without saving (Don't save & go back to previous page)
- Save & add memo
- Save & view all transactions [will go to "Manage your transactions" Table]

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- ENTITY can be Organization, Individual, or Committee, but should default to Organization.
- Button labels are out of scope for this ticket, and will be addressed in #855. 

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=537733255) **Please note this is a consolidated specification**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/bc3db0cc-a894-4b1a-9f25-d87fd840b606)

**Comment by toddlees** [comment]
passes cr moving to qa

**Comment by WiseQA** [comment]
Pre-requisite - create a Staff Reimbursement for Operating Expenditure and saved in the Transactions Table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1329d251-b60e-420f-aee6-c965044a5f72)

After entering a Staff Reimbursement for Operating Expenditure transaction, click the Save & add a memo button. Verify dropdown list is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9dac4102-826b-4b0f-8354-df8ffa263a06)

QA review stopped.   Verified naming of Memo should include the word "Staff ...." (see below question)  

”Reimbursement Memo for Operating Expenditure” sub-transaction under ”Staff Reimbursement for Operating Expenditure”
Is the memo for this naming correct ?   Just checking should this be Staff Reimbursement ..... or just Reimbursement ?

@AureliaKhorsand verified with Ryan this change.   Adding  @GreggMoreland @toddlees @MitchellTCG to this comment.

@toddlees returning to "In-Progress" for this change.

Screenshot of current naming below.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4e3e413b-c1f0-4f06-90e5-7c74ec2f640c)

**Comment by toddlees** [comment]
Added 'Staff' to the beginning of the memo transaction title:
"Staff Reimbursement Memo for Operating Expenditure"

**Comment by WiseQA** [comment]
QA review retested this ticket.
Pre-requisite - create a Staff Reimbursement for Operating Expenditure and saved in the Transactions Table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d35690e9-f6dd-45d9-b14c-d86f5af50a99)

After entering a Staff Reimbursement for Operating Expenditure transaction, click the Save & add a memo button. Verify dropdown list is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a7a8ed70-2ed0-4526-a705-392e53191f9a)

Staff Reimbursement Memo for Operating Expenditure page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/261285d6-c62c-405f-a952-321cd4a4993b)

Verify Purpose of Disbursement (Required) field is displayed and required.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/24d448ab-fc04-4daf-b990-dcea05239f5c)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d7b9b1f8-8dbe-4749-b409-8af24d773a07)

Staff Reimbursement Memo for Operating Expenditure is displayed in the transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3396d638-b1fe-4ed4-9a7c-34482e3a4846)

QA Review Completed. Moved to Stage Ready.
