### ISSUE TITLE
Allow user to enter Payment to Payroll for Operating Expenditure on Schedule B (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#683]
Business Reason

As a Committee Administrator, I will be able to enter a ***”Payment to Payroll for Operating Expenditure”*** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

 ***Then*** Add a Disbursement

 ***Then*** Click(open) on the "Operating Expenditures" Accordion link

 ***Then*** I can enter a transaction with the type “Payment to Payroll for Operating Expenditure "

 ***Then*** I will be required to enter the following information (unless otherwise noted):

—

Contact

 #

*   ***CONTACT TYPE***
*   Organization only

*   ***LAST NAME*** (Required)
*   ***FIRST NAME*** (Required)
*   ***MIDDLE NAME*** (Optional)
*   ***PREFIX*** (Optional)
*   ***SUFFIX*** (Optional)

1.  Address

      #

*   ***STREET ADDRESS*** (Required)
*   ***APARTMENT, SUITE, ETC.*** (Optional)
*   ***CITY*** (Required)
*   ***STATE/PROVINCE*** (Required)
*   ***ZIP/POSTAL CODE*** (Required)

1.  Expenditure Information

      #

*   ***DATE*** (Required)
*   ***MEMO ITEM*** (Optional)
*   ***AMOUNT*** (Required)

      ***Note:*** AMOUNT can be a negative amount
*   ***AGGREGATE*** (Required)
      *   Amount Displayed will be the total of contributions that are:
            *   From the person (ENTITY)
    *   within Aggregation Group of "GENERAL_DISBURSEMENT"
            *   _from_ January 1 of report year _to_ the Contribution Date* of the transaction.
        *   *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

1.  Additional information

      #

*   ***PURPOSE OF DISBURSEMENT*** (Required, system generated)

      --Text should read: "Payroll: See Below"
*   ***NOTE OR MEMO TEXT*** (Optional)
*   ***CATEGORY CODE*** (Optional)

—

 ***Then*** I will be able to:

*   Go back to previous page without saving
*   Save & add another
*   Save & Add Memo
*   Save & view all transactions [will go to "Manage your transactions" Table]
*   Edit

***And if*** the Aggregate amount is >= $200.01,

 ***Then*** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

***If*** the Aggregate amount is [Spec Updates spreadsheet tab here]( [https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=367598665](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=367598665)) ***Please note this is a consolidated specification.***

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-956](https://fecgov.atlassian.net/browse/FECFILE-956)

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/66f0236d-b654-4fee-b44e-8a76fe364335)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA on DEV. Note the change in acceptance criteria for the Save & Add Memo button. That button will be visible and testable in the future tickets for the memo transactions for this parent transaction.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Payment to Payroll for Operating Expenditure a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1635d712-51a0-4bbc-8a06-0e4788c73929)

Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed 'Payroll: See Below'.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9ba9cbcf-79c3-4829-8d64-f86cb541b8b8)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4ba4152e-a296-403f-ba0e-d5dc4a734edb)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4531fdce-e8ee-4713-ab98-77f395f30774)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/911e977e-30a4-4ff0-acf5-64b425843979)

QA Review Completed. Moved to Stage Ready.
