### ISSUE TITLE
Allow user to enter Payroll Memo for Operating Expenditure on Schedule B (Group B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#684]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Payroll Memo for Operating Expenditure”** sub-transaction under **”Payment to Payroll for Operating Expenditure”** on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator 
**And** I am editing a Payment to Payroll for Operating Expenditure transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction: 
- Payroll Memo for Operating Expenditure

**And** I will be required to enter the following information (unless otherwise noted):

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee 
*Note - please default to Individual.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Required, must be checked)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Go back to previous page without saving (Don't save & go back to previous page)
- Save & add memo
- Save & view all transactions [will go to "Manage your transactions" Table]

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,00
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- ENTITY can be Organization, Individual, or Committee, but should default to Individual.
- Button labels are out of scope for this ticket, and will be addressed in #855. 

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=537733255) **Please note this is a consolidated specification**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by toddlees** [comment]
passes cr moving to qa

**Comment by WiseQA** [comment]
Pre-requisite - create a Payment to Payroll for Operating Expenditure and saved in the Transactions Table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ad477dd4-4280-4eff-866d-23103cfd4254)

After entering a Payment to Payroll for Operating Expenditure transaction, click the Save & add a memo button. Verify dropdown list is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2404d505-b9e6-4295-b3b0-ae5fd58d01e6)

Payroll Memo for Operating Expenditure Memo page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/03655d95-f04c-44bb-bfe7-10458521e4cc)

Verify Purpose of Disbursement (Required) field is displayed and required.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7ca6aa5d-e7b7-4f2c-9654-7f10aa3b84cb)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ccee541d-a5dd-4343-8578-9beb305350e4)

Verify Payroll Memo for Operating Expenditure is displayed in the transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f029ea37-d297-4fa1-9528-fccdf763dea9)

QA Review Completed. Moved to Stage Ready.

**Comment by AureliaKhorsand** [comment]
Updating ACs to indicate that the entity should default to INDIVIDUAL based on Sprint 22 demo feedback.

**Comment by WiseQA** [comment]
This changes should be from Sprint 22 demo not Sprint 23

*Shelly Wise*
*QA/Test Engineer*
*Tygart Technology*
***@***.*** ***@***.***>*
*304-657-9070*
*CMMI - ITIL - ISO 9001:2015 - Agile/SAFe*

**Comment by mjtravers** [comment]
Patch made to contact dropdown so that Individual is default selection. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified dropdown is defaulted to Individual.

QA Review Completed.   Moved back to Stage Ready.

**Comment by WiseQA** [comment]
QA review verified dropdown is defaulted to Individual.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/94c973b3-99ba-4675-8f00-733982999901)

QA Review Completed. Moved back to Stage Ready.
