### ISSUE TITLE
Allow user to enter Void of Operating Expenditure on Schedule B (Group B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#685]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Void of Operating Expenditure”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a Disbursement
**Then** Click(open) on the "Operating Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Void of Operating Expenditure "
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee 
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)
---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
--AMOUNT must be a negative value
**Note: System will automatically make the amount negative. AMOUNT MUST be a non-zero negative value to save, and max value is -$0.01. If amount exceeds that, then display error message 'Amount must be negative (example: -$20.00)'**
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY)
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- from January 1 of report year to the Contribution Date* of the transaction.
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)
---
**Then** I will be able to:
- Go back to previous page without saving
- Save & add another
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit

**And** upon saving, the transaction will be itemized regardless of amount.

 QA Note
- Button labels are out of scope for this ticket, and will be addressed in #855. 

 Dev Note 

- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1961093545) **Please note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
There is a known bug in this ticket that will be better fixed in the validator ticket [#876](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/876). The bug is that if the amount entered is "-0.00", the red "Amount must be negative (example: -$20.00)" text below the input box does not display.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review on hold until decision of fix on ticket #876 of known bug for this ticket, as known bug should fail this ticket.   Decision on whether ticket #876 being fixed in Sprint 21.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Operating Expenditures then select Void of Operating Expenditure a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d8abb9c3-33d1-482a-9676-f131f45dcffb)

Verify amount field max value is -$0.01. Bug fix #876 verified when entering $-0.00 error message is displayed 'Amount must be negative (example: -$20.00)'

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d11a1217-c374-4fb1-8b6b-bbd21260a8a8)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c9b38ebe-2dee-4992-9dc8-fd5a9e886b0f)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8cf88bd1-77f8-4ae4-ace9-755e8af1bc05)

Verified Purpose of Disbursement (Required) field is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/276c0ee1-395c-402c-bd28-4f9aacad6473)

Verify Category Code (Optional) dropdown field is displayed and selectable.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9fdee189-deab-4304-93c5-482b0a1ece83)

Verified Void of Operating Expenditure disbursement is displayed in the transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/56f2a8ff-b0f8-4bb8-8375-7927bcf4a78d)

QA Review Completed.   Moved to Stage Ready.
