### ISSUE TITLE
Allow user to enter Transfer to Affiliates/Other Committees on Schedule B (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#687]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Transfer to Affiliates/Other Committees”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Contributions/Expenditures to Regular Filers" Accordion link  
**Then** I can enter a transaction with the type “Transfer to Affiliates/Other Committees"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE** (Required, includes LOOKUP)
-Committee
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be negative)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Optional)
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE**  (Optional)

---
**Then** I will be able to:
- Cancel 
- Save
- Edit

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on SB22.

 QA Note
- There is no aggregate for this transaction.

 Dev Note 

- BENEFICIARY COMMITTEE FEC ID and NAME will pull from PAYEE ORGANIZATION NAME and the Committee ID, similar to functionality in Schedule A.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=200374453)

 Wireframe 

![687 - Transfer to Affiliates-Other Committees.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7b22e3ca-eee2-411f-b6fb-a3f2c9700367)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
Wireframe Added

**Comment by MitchellTCG** [comment]
@AureliaKhorsand wire added

**Comment by AureliaKhorsand** [comment]
@MitchellTCG there should be no Aggregate field for this transaction

**Comment by AureliaKhorsand** [comment]
@mary-tcg @MitchellTCG can one of you update the wires to show Purpose of Disbursement as Optional? Sorry I didn't catch that before!

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
Wire is updated

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Transfer to Affiliates/Other Committees" a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5452cf34-ffc4-475d-b0fa-67d929a972fa)

Verified Contact Type is "Committee" Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4379f2b4-68d0-4dea-a81d-06a8808cabdd)

Verified Purpose of Disbursement (Optional) field is displayed

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/90631d94-116c-443a-98be-d0bcf7ee8e36)

Verify "Aggregate" field not displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b985c9cb-4ec8-431c-a726-b1ab10339a75)

Verified Transactions table "Disbursements" is updated.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1fe049ca-f8e8-4a42-be2c-8821cf86170e)

QA Review Completed.  Moved to Stage Ready.
