### ISSUE TITLE
Allow user to enter Contribution to Candidate on Schedule B (Group M)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#688]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Contribution to Candidate”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Contributions/Expenditures to Regular Filers" Accordion link  
**Then** I can enter a transaction with the type “Contribution to Candidate"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE** (Required, includes LOOKUP)
-- Committee
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional, will be required if DATE falls outside of report dates)
-	**AMOUNT** (Required, can be negative)

# COMMITTEE/CANDIDATE INFORMATION 
#
- **COMMITTEE ID** (Required, must match Payee Committee ID and is read-only)
- **COMMITTEE NAME** (Required, must match Payee Committee Name and is read-only)

**And** the user will be required to select a Candidate using the LOOKUP, and upon selection the following will be populated:

-	**CANDIDATE ID** (Required)
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)
- **CANDIDATE OFFICE** (Required)
- **CANDIDATE STATE** (Required if CANDIDATE OFFICE is 'House' or 'Senate')
- **CANDIDATE DISTRICT** (Required if CANDIDATE OFFICE is 'House') 

# ELECTION INFORMATION 
#
-	**ELECTION CODE** (Required)
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Other)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Optional, user entered)
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB23

 QA Note
- There is no aggregate on this transaction and each transaction is itemized.

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1910396547)  **This is a consolidated specification**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Contribution to Candidate transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/761b45e7-af41-4527-b9c9-cbc664aa294f)

Contact type is Committee Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4319c088-7106-42a4-be84-76f3bdd0b914)

Verified PURPOSE OF DISBURSEMENT (OPTIONAL) is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e40f34fd-3b12-4a72-aca4-74429d88864d)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/409f3fb5-13c4-476f-bdb8-34d712367333)

Verified Beneficiary Information - Candidate fields populated:


![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/44b4e533-f863-4383-a251-b0a0bff9c373)

Verified Contribution to Candidate transaction is displayed in the "Disbursements" list in the transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3b91ad4f-8266-4497-bb4a-19c951896a08)

QA Review Completed.   Moved to Stage Ready.
