### ISSUE TITLE
Allow user to enter Void of Contribution to Candidate on Schedule B (Group M)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#689]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Void of Contribution to Candidate”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Contributions/Expenditures to Regular Filers" Accordion link  
**Then** I can enter a transaction with the type “Void of Contribution to Candidate"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Committee
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional, will be required if DATE falls outside of report dates)
-	**AMOUNT** (Required)
**Note: System will automatically make the amount negative. AMOUNT MUST be a non-zero negative value to save, and max value is -$0.01. If amount exceeds that, then display error message 'Amount must be negative (example: -$20.00)'**

# COMMITTEE/CANDIDATE INFORMATION 
#
- **COMMITTEE ID** (Required, must match Payee Committee ID and is read-only)
- **COMMITTEE NAME** (Required, must match Payee Committee Name and is read-only)

**And** the user will be required to select a Candidate using the LOOKUP, and upon selection the following will be populated:

-	**CANDIDATE ID** (Required)
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)
- **CANDIDATE OFFICE** (Required)
- **CANDIDATE STATE** (Required if CANDIDATE OFFICE is 'House' or 'Senate')
- **CANDIDATE DISTRICT** (Required if CANDIDATE OFFICE is 'House') 

# ELECTION INFORMATION 
#
-	**ELECTION CODE** (Required)
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Other)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, user entered)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Required)

---
**Then** I will be able to:
- Cancel 
- Save 
- Edit

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB23

 QA Note
- There is no aggregate on this transaction and each transaction is itemized separately.

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1910396547) **This is a consolidated specification**

 Wireframes 

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Void of Contribution to Candidate a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/eda1b924-9c4b-4c91-9188-1def92c4d719)

Verified PURPOSE OF DISBURSEMENT (REQUIRED) is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fb8b4161-a5c5-4b98-87bc-b5e782ea7b12)

Verified Beneficiary Information - Candidate fields populated:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/51dd6156-e55d-44a5-83c2-e486d42966e4)

Verified Void of Contribution to Candidate transaction is displayed in the "Disbursements" list in the transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f1608d06-1d6d-46ba-ab0e-525e90f5ebca)

QA Review Completed. Moved to Stage Ready.
