### ISSUE TITLE
Allow user to enter Contribution to Other Committee on Schedule B (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#690]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Contribution to Other Committee”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement 
**Then** Click (open) on the "Contributions/Expenditures to Regular Filers" Accordion link  
**Then** I can enter a transaction with the type “Contribution to Other Committee"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE** (Required, includes LOOKUP)
- Committee only

-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be negative)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Optional, user entered)
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on SB23.

 QA Note
- There is no aggregate for this transaction.

 Dev Note 

- Beneficiary Committee Name and ID can be taken from the PAYEE Name and ID.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1965695035)  **This is a consolidated transaction**

 Wireframe 

![690 - Contribution to Other Committee.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/24c7b628-8a8d-4a5d-b1ea-e28b3364eb40)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@GreggMoreland  
Is the aggregate not shown here?

**Comment by MitchellTCG** [comment]
Wire Attached

**Comment by GreggMoreland** [comment]
@MitchellTCG Correct, there is no aggregate for this transaction

**Comment by AureliaKhorsand** [comment]
@MitchellTCG there should be no Election Information in the wireframe

**Comment by MitchellTCG** [comment]
@AureliaKhorsand updated

**Comment by AureliaKhorsand** [comment]
@mary-tcg @MitchellTCG can one of you update the wires to show Purpose of Disbursement as Optional? Sorry I didn't catch that before!

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
Wire is updated

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Contribution to Other Committee" a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/32a7a997-1aee-4132-8c29-79b4107ae9c8)

Verified Contact Type is "Committee" Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3944c38f-b777-4881-a084-3501356d314c)

Verified "Aggregate" field is not displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bfb3b631-11b5-4745-b7e7-ac1b9ee9038b)

Verified Purpose of Disbursement (Optional) field is displayed

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8174847c-a7ca-47ee-b8c7-967ef3887fba)

Verified Transactions table "Disbursements" is updated.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f1551d3d-084e-4b42-81d9-fcc1a489800b)

QA Review Completed.   Moved to Stage Ready.
