### ISSUE TITLE
Allow user to enter Void of Contribution to Other Committee on Schedule B (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#691]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Void of Contribution to Other Committee”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Contributions/Expenditures to Regular Filers" Accordion link  
**Then** I can enter a transaction with the type “Void of Contribution to Other Committee"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE** (Required, includes LOOKUP)
Dropdown options: Committee

-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, user entered)
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel 
- Save
- Edit

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on SB23.

 QA Note
- There is no aggregate on this transaction and each transaction is itemized separately.
- NOTE:  If date within the Report Reporting dates the Memo Item checkbox is Optional.   If the date is outside the Report Reporting dates then the Memo Item Checkbox is Required.  Updated this note as AC states (Optional) which functionality has changed.

 Dev Note 

- Beneficiary Committee Name and ID can be taken from the PAYEE Name and ID.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1965695035) **This is a consolidated specification**

 Wireframe 

![691 - Void of Contribution to Other Committee.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/54cffd3d-9509-4c91-b010-19f8779922f2)

### QA Notes ### 
 -	**DATE** (Required)
-	**MEMO ITEM** (Optional)  (See Note in QA Notes)
-	**AMOUNT** (Required, must be negative)
**Note: System will automatically make the amount negative. AMOUNT MUST be a non-zero negative value to save, and max value is -$0.01. If amount exceeds that, then display error message 'Amount must be negative (example: -$20.00)'**
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
Wireframe Attached

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Void of Contribution to Other Committee a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/caa7be86-e406-468d-ab40-f84a50e3be55)

Contact type dropdown is "Committee" Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b1eca121-783d-432e-b2f8-a68494257931)

Verified Purpose of Disbursement is (Optional)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f5eb1a98-f520-4432-9519-3d7e3ef2186d)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ea46bcd3-d086-4949-945a-67e40dd6b94d)

QA review entered same contact for Contribution to Other Committee (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount. (Note - VOID is a negative value)


**BELOW bug fix -** 

When saving transaction the Purpose of Disbursement (Optional) has error message - "This is a required field".    The label needs changed from (Optional) to (Required) as denoted in wireframe and acceptance criteria.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/90f1f58b-aced-4904-9e35-a970d615f8e1)

@mjtravers @MitchellTCG returned to In-Progress for fix. of label.

**Comment by mjtravers** [comment]
Patch passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Purpose of Disbursement label has been changed from (Optional) to (Required).   Error message populated correctly "This  is a required field"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e75cb6f1-188d-4f62-98cc-f4ec2d741d5c)

During testing the Memo Item field shows error message "This  is a required field".   The Memo Item is Optional for this transaction as denoted in the wireframe and acceptance criteria.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/af356b10-836e-412c-ac3a-f0d29d2581c0)

@mjtravers @MitchellTCG Returning to In-Progress for bug fix.

**Comment by mjtravers** [comment]
Upon review with @WiseQA, it was determined that the functionality is working correctly: if DATE is selected within the report date range the MEMO ITEM is optional, if the DATE is selected outside the report date range then the MEMO ITEM is required to be checked.

**Comment by WiseQA** [comment]
During QA review with DEV as noted above this ticket will pass.   

QA added a note to QA Notes above for future reference.
- NOTE:  If date within the Report Reporting dates the Memo Item checkbox is Optional.   If the date is outside the Report Reporting dates then the Memo Item Checkbox is Required.  Updated this note as AC states (Optional) which functionality has changed.
- 
QA Review Completed.   Moved to Stage Ready
