### ISSUE TITLE
Allow user to enter Other Disbursement on Schedule B (Group B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#692]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Other Disbursement”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a Disbursement
**Then** Click(open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Other Disbursement"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee 
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Go back to previous page without saving
- Save & add another
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- Button labels are out of scope for this ticket, and will be addressed in #855. 

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1961093545) **Please note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Other Disbursement a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/053cc8ef-84aa-4f6d-b2c4-74e746256716)

Verify Purpose of Disbursement (Required) field is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cffef9c9-24bc-46ba-8ad6-4f1496fb2fec)

Verify Category Code (Optional) dropdown field is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/839a84b3-8dc8-441a-ab07-471a52f5b043)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/09552217-531d-4d1b-a3db-2d64386ee0d8)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8cf7ba83-e16b-45b2-9be1-409aec32e3c3)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9eab9e7b-fa7b-4b42-8751-8ffcc4368659)

Verified “Cancel”, “Save & add another”, “Save & view all transactions” buttons functional and working as current design.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2cbca229-3f00-43a1-ab8c-47dd3d11070f)

Verified Organization (default), Individual, and Committee Operating Expenditures were created and displayed in Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/656940ad-817e-4ab6-987a-e7415a24a20b)

QA Review Completed. Moved to Stage Ready.
