### ISSUE TITLE
Allow user to enter Credit Card Payment for Other Disbursement on Schedule B (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#693]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Credit Card Payment for Other Disbursement”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a Disbursement
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Credit Card Payment for Other Disbursement"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
-Organization only
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, system generated)
--Text must read: 'Credit Card: See Below'
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Go back to previous page without saving
- Save & add another
- Save & Add Memo 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- QA to receive both transaction and memo tickets together to verify workflow is correct.
- Note the Save & Add Memo button will not be visible until memo transaction types have been added to the system.
- Note that the transaction name is not plural, and should be updated on the transaction selection screen to "Credit Card Payment for Other Disbursement"
- Button labels are out of scope for this ticket, and will be addressed in #855. 

 Dev Note 

- Note that the transaction name is not plural, and should be updated on the transaction selection screen to "Credit Card Payment for Other Disbursement"
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=367598665) **Please note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Ready for QA on DEV. Note the change in acceptance criteria for the Save & Add Memo button. That button will be visible and testable in the future tickets for the memo transactions for this parent transaction.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Credit Card Payment for Other Disbursement a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/445b037f-dc65-486b-9f91-1a2178666eee)

Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed 'Credit Card: See Below'.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5e906a07-f429-4d4b-8a19-5278f847952b)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5c03933d-b12f-4db5-9c13-34b184dcca70)

Verify amount can be a negative number.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cce38092-5f13-4d32-beb6-9af2d64d9f25)

Verified Transactions table is updated,

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/39129a96-287c-41b3-bc43-32400235840b)

QA Review Completed. Moved to Stage Ready.

**Comment by WiseQA** [comment]
Moved back to QA - Itemization rule was missing in acceptance criteria.   @GreggMoreland updated ticket.   @toddlees please verify.    @GreggMoreland updated 695 and 700 tickets also as these were also missing the itemization rule.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/203fdd02-3e60-42df-b8b3-704662de65ec)

**Comment by toddlees** [comment]
Itemization functionality implemented in patch to develop.  Behavior matches AC now

**Comment by WiseQA** [comment]
QA review verified the following itemization rule was fixed and transactions table updated.

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/52351a72-bed6-412a-a81b-a9506b171a4d)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e15fe84b-37cc-4209-982e-706cc8266a20)

QA Review retest is Completed.  Moved to Stage Ready.
