### ISSUE TITLE
Allow user to enter Staff Reimbursement for Other Disbursement on Schedule B (Group A) 

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#695]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Staff Reimbursement for Other Disbursement”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a Disbursement 
**Then** Click(open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Staff Reimbursement for Other Disbursement"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
-Individual Only
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, System generated)
--Text must read: "Reimbursement: See Below"
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Go back to previous page without saving
- Save & add another
- Save & Add Memo
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
-  QA to receive both transaction and memo tickets together to verify workflow is correct. 
-  Note the Save & Add Memo button will not be visible until memo transaction types are added to the system.  (OBE)
- Note that the transaction name is not plural, and should be updated on the transaction selection screen to ”Staff Reimbursement for Other Disbursement”.
- Button labels are out of scope for this ticket, and will be addressed in #855. 

 Dev Note 

- Note that the transaction name is not plural, and should be updated on the transaction selection screen to ”Staff Reimbursement for Other Disbursement”.
- [ ] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=674454239) **Please note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Ready for QA on DEV. Note the change in acceptance criteria for the Save & Add Memo button. That button will be visible and testable in the future tickets for the memo transactions for this parent transaction.

**Comment by toddlees** [comment]
Itemization functionality implemented in patch to develop.  Behavior matches AC now

QA Note:   Itemization rule was missing in acceptance criteria.   @GreggMoreland updated ticket.   @toddlees please verify.    @GreggMoreland updated 683 and 700 tickets also as these were also missing the itemization rule.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Staff Reimbursement for Other Disbursement a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/106e0cf8-5f71-4ae8-84d8-1cb6376049e2)

Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed 'Reimbursement: See Below'.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/68aece07-8113-43ab-9c21-5afc7ec2134c)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9c4581e8-57fb-4967-919b-0bcf5a7492ca)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/893df01c-6383-4812-ae54-2d94e9ef6271)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1bdc424c-8c7f-4df6-8cb2-6a9c121d3be8)

QA Review Completed. Moved to Stage Ready.
