### ISSUE TITLE
BUG:   Earmark Receipt/Memo should only display Earmark Receipt/Memo Lookup until Entity is selected 

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#696]
This Bug is written as the Earmark Receipt Transaction Step One (once selected) is displaying the entire form versus "Lookup" to proceed entering a Earmark Receipt, as is Earmark Memo Step Two.

How to Replicate the Issue

1\. Create Earmark Receipt. 

  2\. Select Step One

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/72a67e8e-837e-421f-9d3f-ffe081eb3c7c](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/72a67e8e-837e-421f-9d3f-ffe081eb3c7c))

3\. Only Earmark Receipt "Lookup" should be displayed until an entity is selected/created using the Lookup functionality.

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1608551b-4953-41d1-862c-bface264b2c8](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1608551b-4953-41d1-862c-bface264b2c8))

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8df6decc-7981-4324-b3ef-f35f17842af0](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8df6decc-7981-4324-b3ef-f35f17842af0))

4\. Repeat for Earmark Memo.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-944](https://fecgov.atlassian.net/browse/FECFILE-944)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Earmark Receipt displays Contact Lookup once selecting Step One of Earmark.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/222a94a5-63aa-4edd-a1a2-440fc7633dd3)

QA review verified Earmark memo displays Contact Lookup once selecting Step Two of Earmark.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/49f70974-4968-4b2a-8b17-ef77bef6d6be)

@MitchellTCG should the "Save & view all transactions" button be grayed out in Earmark Receipt "Step One" since this function is not applicable until after Earmark Memo entered ?

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b42ae977-0e89-45e3-ab04-123cc2db98fe)

**Comment by MitchellTCG** [comment]
@WiseQA 
In theory it should but there is a larger UX and development question about how and when error message will show. For that reason, please ignore this issue for now. The UX team will look into it and we will create an additional ticket later to address this.

This is not a showstopper.

@MitchellTCG thanks for clarification.

**Comment by WiseQA** [comment]
QA Review Completed.  Moved to Stage Ready.
