### ISSUE TITLE
Allow user to enter Staff Reimbursement Memo for Other Disbursement on Schedule B (Group B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#699]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Staff Reimbursement Memo for Other Disbursement”** sub-transaction under **”Staff Reimbursement for Other Disbursement”** on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator 
**And** I am editing a Staff Reimbursement for Other Disbursement transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction: 
- Staff Reimbursement Memo for Other Disbursement

**And** I will be required to enter the following information (unless otherwise noted):

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee 
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Required, must be checked)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Go back to previous page without saving (Don't save & go back to previous page)
- Save & add memo
- Save & view all transactions [will go to "Manage your transactions" Table]

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- ENTITY can be Organization, Individual, or Committee, but should default to Organization.
- Button labels are out of scope for this ticket, and will be addressed in #855. 

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=537733255) **Please note this is a consolidated specification**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/0f4afa3b-d90c-4cf3-986c-701155b656c8)

**Comment by toddlees** [comment]
passes cr moving to qa

**Comment by WiseQA** [comment]
QA review stopped.   Verified naming of Memo should include the word "Staff ...." (see below question)  

”Reimbursement Memo for Operating Expenditure” sub-transaction under ”Staff Reimbursement for Operating Expenditure”
Is the memo for this naming correct ?   Just checking should this be Staff Reimbursement ..... or just Reimbursement ?

@AureliaKhorsand verified with Ryan this change.   Adding  @GreggMoreland @toddlees @MitchellTCG to this comment.

@toddlees returning to "In-Progress" for this change.

**Comment by toddlees** [comment]
Added 'Staff' to the beginning of the memo transaction title:
"Staff Reimbursement Memo for Other Disbursement"

**Comment by WiseQA** [comment]
Pre-requisite - create a Staff Reimbursement for Other Disbursement and saved in the Transactions Table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f5f85809-ec40-4440-9a86-82b05ca88b05)

After entering a Staff Reimbursement for Other Disbursement transaction, click the Save & add a memo button. Verify dropdown list is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/08bbf45c-2b2b-441e-9dd3-691646dbaee9)

Staff Reimbursement Memo for Other Disbursement page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a4253e36-bc39-45bf-ac02-bbaa0586312d)

Verify Purpose of Disbursement (Required) field is displayed and required.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/984f4f43-3ca8-4039-9fa0-3b04b036dcbf)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e3ee69f2-da0a-4692-99cf-b07952086ce7)

Verify Staff Reimbursement Memo for Other Disbursement is displayed in the transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/38719961-23c6-4eb1-bf02-0cee3e2e7c27)

QA Review Completed. Moved to Stage Ready.
