### ISSUE TITLE
Allow user to enter Payment to Payroll for Other Disbursement on Schedule B (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#700]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Payment to Payroll for Other Disbursement”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a Disbursement
**Then** Click(open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Payment to Payroll for Other Disbursement"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
-- Organization only

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, system generated)
--Text should read: "Payroll: See Below"
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Go back to previous page without saving
- Save & add another
- Save & Add Memo 
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,00
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- QA to receive both transaction and memo tickets together to verify workflow is correct.
- Note that the transaction name is not plural, and should be updated on the transaction selection screen to "Payment to Payroll for Other Disbursement"
- Note the Save & Add Memo button will not be visible until memo transaction types are added to the system. (OBE)
- Button labels are out of scope for this ticket, and will be addressed in #855. 

 Dev Note 

- Note that the transaction name is not plural, and should be updated on the transaction selection screen to "Payment to Payroll for Other Disbursement"
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=367598665) **Please note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/c44f819e-73e8-4b50-b7e4-d1598870f06b)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA on DEV. Note the change in acceptance criteria for the Save & Add Memo button. That button will be visible and testable in the future tickets for the memo transactions for this parent transaction.

**Comment by toddlees** [comment]
Itemization functionality implemented in patch to develop.  Behavior matches AC now

QA Note:   Itemization rule was missing in acceptance criteria.   @GreggMoreland updated ticket.   @toddlees please verify.    @GreggMoreland updated 683 and 695 tickets also as these were also missing the itemization rule.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Payment to Payroll for Other Disbursement a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/05a9a9e4-6daf-4186-bcaa-c621f6d20c70)

Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed 'Payroll: See Below'.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/35938146-b110-4d13-ba0e-b83b952a7b08)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9f69cf2c-98d6-4a3f-9c18-961d1a8c2aff)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c412695e-8092-412a-8225-ebf08e7c1b3b)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c7c3764e-174a-4e23-897e-ac3938fc4f35)

QA Review Completed. Moved to Stage Ready.
