### ISSUE TITLE
Allow user to enter Payroll Memo for Other Disbursement on Schedule B (Group B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#701]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Payroll Memo for Other Disbursement”** sub-transaction under **”Payment to Payroll for Other Disbursement”** on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator 
**And** I am editing a Payment to Payroll for Other Disbursement transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction: 
- Payroll Memo for Other Disbursement

**And** I will be required to enter the following information (unless otherwise noted):

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee 
*Note - please default to Individual.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Required, must be checked)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Go back to previous page without saving (Don't save & go back to previous page)
- Save & add memo
- Save & view all transactions [will go to "Manage your transactions" Table]

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- ENTITY can be Organization, Individual, or Committee, but should default to **Individual**.
- Button labels are out of scope for this ticket, and will be addressed in #855. 

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=537733255) **Please note this is a consolidated specification**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
@toddlees The COMMITTEE ID field is not showing up on the form for the memo. I see there is a includeFecId on the app-committee-input component but I'm wondering if it needs to be dynamically set 
 (maybe based on schedule type) for the Group B template so as not to appear on the SchedA forms.

Sending back to In Progress

**Comment by toddlees** [comment]
The committee id field was not supposed to be in the AC.  BAs have updated the ticket (and other tickets) to remove committee id when it's not needed.

**Comment by toddlees** [comment]
passed cr moving to qa

**Comment by WiseQA** [comment]
Pre-requisite - create a Payment to Payroll for Other Disbursement and saved in the Transactions Table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e0877b5a-755c-4bce-a38f-35b93a3f2715)

After entering a Payment to Payroll for Other Disbursement transaction, click the Save & add a memo button. Verify dropdown list is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6a6c9a3f-7fad-4b11-8417-a886e053d2b0)

Payroll Memo for Other Disbursement page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fa306a94-5a4a-4825-80b6-347eaf844618)

Verify Purpose of Disbursement (Required) field is displayed and required.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a00c93c4-7856-493a-ab55-148bd000ef27)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5cd71ad7-2026-47fc-a122-f02fbc514ac3)

Verify Payroll Memo for Other Disbursement is displayed in the transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d4b4a187-17a6-4ed6-9cc0-51c19a07438d)

QA Review Completed. Moved to Stage Ready.

**Comment by AureliaKhorsand** [comment]
Updating ACs to indicate that the entity should default to INDIVIDUAL based on Sprint 22 demo feedback.

**Comment by WiseQA** [comment]
This changes should be from Sprint 22 demo not Sprint 23

*Shelly Wise*
*QA/Test Engineer*
*Tygart Technology*
***@***.*** ***@***.***>*
*304-657-9070*
*CMMI - ITIL - ISO 9001:2015 - Agile/SAFe*

**Comment by mjtravers** [comment]
Patch made to contact dropdown so that Individual is default selection. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified dropdown is defaulted to Individual.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8113a4d9-95da-4ec5-97e1-5b936f7624d0)

QA Review Completed.   Moved back to Stage Ready.
