### ISSUE TITLE
Allow user to enter Void of Other Disbursement on Schedule B (Group B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#702]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Void of Other Disbursement”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a Disbursement
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Void of Other Disbursement"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee 
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note: System will automatically make the amount negative. AMOUNT MUST be a non-zero negative value to save, and max value is -$0.01. If amount exceeds that, then display error message 'Amount must be negative (example: -$20.00)'**
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Go back to previous page without saving
- Save & add another
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit

**And** upon saving, the transaction will be itemized regardless of amount.

 QA Note
- Button labels are out of scope for this ticket, and will be addressed in #855. 

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1961093545) **Please note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
There is a known bug in this ticket that will be better fixed in the validator ticket [#876](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/876). The bug is that if the amount entered is "-0.00", the red "Amount must be negative (example: -$20.00)" text below the input box does not display.

**Comment by mjtravers** [comment]
There is a known bug in this ticket that will be better fixed in the validator ticket [#876](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/876). The bug is that if the amount entered is "-0.00", the red "Amount must be negative (example: -$20.00)" text below the input box does not display.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review on hold until decision of fix on ticket #876 of known bug for this ticket, as known bug should fail this ticket.   Decision on whether ticket #876 being fixed in Sprint 21.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Other Expenditures then select Void of Other Disbursement a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7112f578-3f06-42ba-895c-bc475e6b9df0)

Verify amount field max value is -$0.01. Bug fix #876 verified when entering $-0.00 error message is displayed 'Amount must be negative (example: -$20.00)'

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f5573bee-bfc5-418b-90bb-305ec5b20ef2)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9257b872-fa5f-4c27-8bfd-cb964a89e4a7)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/705134dc-b7df-4d3f-95bc-7c83de7b427a)

Verified Purpose of Disbursement (Required) field is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/47eef25e-f131-4fac-878d-8c71c39cfd85)

Verify Category Code (Optional) dropdown field is displayed and selectable.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/21bc106f-1d80-41bd-b4de-3e7619904d4e)

Verified Void of Other Disbursement disbursement is displayed in the transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d6d70034-1622-4492-8286-2176bacb63ad)

QA Review Completed. Moved to Stage Ready.
