### ISSUE TITLE
Allow user to enter Non-contribution Account Disbursement on Schedule B (Group B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#703]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Non-contribution Account Disbursement”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement 
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Non-contribution Account Disbursement"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee 
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)
---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)
---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#

-	**PURPOSE OF DISBURSEMENT** (Required, system-generated AND user-entered)
-- "Non-Contribution Account: XX", where "XX" is generated by the user
--**NOTE: System will automatically prefix the entered text with 'Non-Contribution Account: '**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on SB29.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- Purpose of Disbursement is part system-generated, part user-entered.

 Dev Note 

- To display ‘Non-Contribution Account:' in the CPD, use https://primeng.org/inputnumber#prefixsuffix as an example
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1837001720)

 Wireframe 

![703 - Non-contribution Account Disbursement.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/9378000f-0a3f-4352-8c67-3d8445aac84f)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg @JonellaCulmer This is the first time we are seeing a Purpose of Disbursement where part of it is system-generated, part of it is user-entered, and it will be concatenated on the *.fec file. What can this look like?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
wireframe attached
please notice I added the word Required after Item Memo

Let me know if this causes an issue

ex. MEMO ITEM (REQUIRED)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG I don't see the wireframe - can you try to add it again? 
Also, Memo Item is optional here, the ACs were miscopied. I've updated it, so Memo Item should be optional.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Sorry Wire Attached

**Comment by Elaine-Krauss-TCG** [comment]
The underlying transaction has been fully implemented

Defaults to Committee
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/c1916276-5ecf-4657-baf4-51a1198940e9)

All three Entity Types are supported and Itemization works
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/bf824631-4c4f-40fd-946b-5945dfd9a2f0)

**Comment by mjtravers** [comment]
The new prefix description code looks good. Nice and simple. There are some minor fixes to make input screen meet acceptance criteria. See inline comments in the PR. Sending back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Non-contribution Account Disbursement a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e854dd9d-e7a7-4267-b963-41f5e84cde29)

Verified Dropdown options: Organization, Individual, Committee and Defaulted to "Organization"

 ![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/db6f6065-aab6-4844-943e-a96e9eea55ad)

Verified the PURPOSE OF DISBURSEMENT (REQUIRED) field the system generated "Non-Contribution Account:" and is displayed in the text field.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a9fc1d14-4054-4b8d-b931-6115162f2250)

Verified text can be added to Purpose of Disbursement.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/62c4e97e-b4a1-4311-9ef7-c935f0690082)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9ef4f528-6f55-40a3-a0ab-fba419b9e6c9)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ec154fde-eb59-457d-8286-2fdbe3b0d9f9)

QA Review Completed. Moved to Stage Ready.
