### ISSUE TITLE
Allow user to enter Non-contribution Account Credit Card Payment on Schedule B (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#704]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Non-contribution Account Credit Card Payment”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click(open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Non-contribution Account Credit Card Payment"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
-Organization only
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#

-	**PURPOSE OF DISBURSEMENT** (System generated)
--Text must read: 'Non Contribution Account - Credit Card: See Below'

**Note Changed to (see fix below):

PURPOSE OF DISBURSEMENT (System generated)
--Text must read: 'Non-contribution Account - Credit Card: See Below'**

-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

**Then** I will be able to:
- Cancel
- Save
- Save & add memo (Memo Group: Non-Contribution Account Credit Card Payment; Memo name in list: Credit Card Memo)
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
NOTE:   ALL transactions $0.00 and below negative aggregate value is always Itemized per BA.

 Dev Note 

- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=55770474) **Note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/d6b65c62-29c5-4a52-9565-ee908bbf8f76)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Non-contribution Account Credit Card Payment a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f85fe6cf-0e18-4f82-b6b2-3765c84e7e46)

Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed "Non-Contribution Account - Credit Card: See Below"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/19a154c8-e5b4-43a0-8fc2-b86de4e15158)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/72774690-ee62-4c3c-9da9-864bf85f76ae)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is >$0.00 and <200.00 (Note:  Value cannot be below $0.00 negative value. Negative value is itemized)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/01411570-73e8-450f-9c8a-e05abed9ad04)

QA Review Completed.   Moved to Stage Ready.

**Comment by mjtravers** [comment]
Fix for purpose description bug was made. Validation schema was updated to lowercase the c in Non-contribution Account so validation passes.

**Comment by WiseQA** [comment]
PURPOSE OF DISBURSEMENT (System generated)
--Text must read: 'Non Contribution Account - Credit Card: See Below' is changed to:

PURPOSE OF DISBURSEMENT (System generated)
--Text must read: 'Non-contribution Account - Credit Card: See Below'

Non-Contribution will be changed to lower case "c" = Non-contribution in both transaction and spec sheet.  

Moved back to QA review to retest this change.

Added screenshot of Non-contribution Account Credit Card Payment error:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2ab8fc08-ef9a-4619-98a2-3ed87e9edbfa)

**Comment by WiseQA** [comment]
QA review retested and verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed "Non-contribution Account - Credit Card: See Below"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/db5893e8-62ef-4b93-9079-fb5b1cb0c68c)

QA Review retest Completed.   Moved to Stage Ready.

**Comment by WiseQA** [comment]
During review today it was caught the + Save & add memo button is missing from this transaction.  See Acceptance Criteria above.

@MitchellTCG @mjtravers moving out of Stage Ready back to In-Progress for this fix

**Comment by mjtravers** [comment]
The old button code was still in this transaction type. Fix has been made. Passes CR. Ready for QA on STAGE.

**Comment by WiseQA** [comment]
QA retested the button add memo function is available 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7e91863f-eada-4b0b-8b26-f31268a88339)

The drop down list has both:
Non-contribution Account Credit Card Payment and
Credit Card Memo

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/be106298-967d-4d1b-88c6-0a6ceeffb512)

Credit Card Memo should not be listed in drop down.   Returning to in-progress for fix ...

**Comment by GreggMoreland** [comment]
@WiseQA Actually, this is correct. The Memo Group name is 'Non-contribution Account Credit Card Payment'; The memo transaction is supposed to be linked to the 'Credit Card Memo' listed. This is how it is in the AC. Also, see #902 for how this should work for all similar transactions.

**Comment by WiseQA** [comment]
@MitchellTCG So what I am I suppose to be seeing in dropdown list ?  
Both names ???

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f12f6178-ca27-42ee-94d4-492c641fa6c2)

No where in this ticket is a wireframe or explicate what drop down needs to be

**Comment by WiseQA** [comment]
Please update ticket wireframe what dropdown suppose to be to verify testing

**Comment by GreggMoreland** [comment]
@WiseQA If you look in #902. Originally when this one was written, along with 902, there was supposed to be a bolded memo group name, followed by the list of memos. In 902, I forgot it was modified to only show the memo. So in this case, it should only show 'Credit Card Memo' . Similar pattern for the other two.

**Comment by WiseQA** [comment]
Ignore below test:
QA retested the button add memo function is available.   Ticket #902 was implemented after this ticket.  Therefore the + Save & add memo button was not functional during testing of this ticket originally.

The drop down list has both:
**Non-contribution Account Credit Card Payment**
Credit Card Memo

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/be106298-967d-4d1b-88c6-0a6ceeffb512)

Button working as designed.   Verified fix was implement.

Verified when selecting Credit Card Memo from the dropdown the Non-contribution Account Credit Card Memo page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ed60b030-00e1-47ff-accd-dc53bff44c8e)

**Comment by WiseQA** [comment]
QA retested the button add memo function is available.   Ticket #902 was implemented after this ticket.  Therefore the + Save & add memo button was not functional during testing of this ticket originally.

The drop down list shows ONLY the following (per ticket #902):
Non-contribution Account Credit Card Payment Memo

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e3f7f483-1820-4dd4-a4f3-cb71346765eb)

(Note:  3 tier button dropdown ticket has not been implemented to date)
