### ISSUE TITLE
Allow user to enter Non-contribution Account Credit Card Payment Memo on Schedule B (Group B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#705]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Non-contribution Account Credit Card Payment Memo”** sub-transaction under **”Non-contribution Account Credit Card Payment”** on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator 
**And** I am editing a Non-contribution Account Credit Card Payment transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction: 
- Non-contribution Account Credit Card Payment Memo
**And** I will be required to enter the following information (unless otherwise noted):

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee 
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)
---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Required, must be checked)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save 
- Save & add memo (Memo Group: Non-Contribution Account Credit Card Payment; Memo name in list: Credit Card Memo)
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- ENTITY can be Organization, Individual, or Committee, but should default to Organization.
- Memo Item must be checked and read-only.

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=710072427) **Please note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/d6b65c62-29c5-4a52-9565-ee908bbf8f76)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
Pre-requisite - create a Non-contribution Account Credit Card Payment and saved in the Transactions Table.

**Comment by WiseQA** [comment]
Pre-requisite - create a Non-contribution Account Credit Card Payment and saved in the Transactions Table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dd9d70cc-672c-4e01-b947-9fee5fe08c6c)

After entering a  Non-contribution Account Credit Card Payment transaction, click the Save & add a memo button. Verify dropdown list is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d8aae125-4f97-4c40-af85-28b5a643bfd2)

Non-Contribution Account Credit Card Memo page is displayed and defaulted to "Organization".

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/09afc47d-6fb0-45af-9841-7f3b34b41fca)

Verify Purpose of Disbursement (Required) field is displayed and required.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/721cd225-77f5-44b7-afc1-36f75030a5dc)

Non-Contribution Account Credit Card Memo is displayed in the transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e50f2a47-9c0c-4073-aa6c-327b82ffdfa8)

Accordion dropdown, Save & add a memo and memo page need changed from "Non-Contribution" to "Non-contribution" per acceptance criteria.   (Ignore ticket name changes made incorrectly)

**Comment by WiseQA** [comment]
Verified Accordion dropdown, Save & add a memo and memo page have been changed from "Non-Contribution" to "Non-contribution" per acceptance criteria.   (Ignore ticket name changes made incorrectly)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/87cc96e6-1fb6-4420-89f3-a694eb0a9407)

QA Review Completed. Moved to Stage Ready.

**Comment by WiseQA** [comment]
Ignore test below:
QA review retested and verified + Save & add memo button.  Ticket #902 was implemented after this ticket.  

After entering a Non-contribution Account Credit Card Payment transaction, click the Save & add a memo button. Verify dropdown list is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4fb38be5-6cab-4978-88c7-0347399b416d)

+ Save & add memo button has been updated and working as designed.

**Comment by WiseQA** [comment]
QA retested the button add memo function is available. Ticket #902 was implemented after this ticket. Therefore the + Save & add memo button was not functional during testing of this ticket originally.

The drop down list shows ONLY the following (per ticket #902):
Non-contribution Account Credit Card Payment Memo

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/941e1bdd-8724-4337-9e3c-5da84ca3ea8e)

(Note: 3 tier button dropdown ticket has not been implemented to date)
