### ISSUE TITLE
Allow user to enter Non-contribution Account Staff Reimbursement on Schedule B (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#706]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Non-contribution Account Staff Reimbursement”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Non-contribution Account Staff Reimbursement"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
-Individual Only

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, system generated)
--Text must read: 'Non Contribution Account - Reimbursement: See Below'

**Note Changed to (see fix below):
PURPOSE OF DISBURSEMENT (Required, system generated)
--Text must read: 'Non-contribution Account - Reimbursement: See Below'**

-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel 
- Save 
- Save & add memo (Memo Group: Non-contribution Account Staff Reimbursement; Memo name in list: Staff Reimbursement Memo)

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note 

NOTE: ALL transactions $0.00 and below negative aggregate value is always Itemized per BA.

 Dev Note 

- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=291971870)

 Wireframe
Memo Group Name: Non-Contribution Account Staff Reimbursement
Memo Name (in list--example shows 'Organization'): Staff Reimbursement Memo
![image001.png](https://images.zenhubusercontent.com/62eac7883f87756fe900911f/d630fede-b16a-4e96-8d18-3a02be9a9ea2)

 Wireframe for buttons 

![User Journey - P5](https://user-images.githubusercontent.com/31663028/226462568-bf86aa5d-3e4d-4698-ab3a-bb94c5d2cd1f.jpg)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/d6b65c62-29c5-4a52-9565-ee908bbf8f76)

**Comment by mjtravers** [comment]
From CR: Changes have been requested to the validate schema for this ticket. See comments in PR. Sending back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Non-contribution Account Staff Reimbursement a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fef6615c-c442-4b05-81d6-62e38b97dac0)

Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed "Non-Contribution Account - Reimbursement: See Below"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a695764d-4e4b-4449-a23a-fa8a81b7b47a)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bf11df62-1b5a-4aa8-979a-650453d0fa39)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is >$0.00 and <200.00 (Note: Value cannot be below $0.00 negative value. Negative value is itemized)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/561089ea-3f1b-4945-8a8a-d0917c53482b)

QA Review Completed. Moved to Stage Ready.

**Comment by mjtravers** [comment]
Fix for purpose description bug was made. Validation schema was updated to lowercase the c in Non-contribution Account so validation passes.

**Comment by WiseQA** [comment]
PURPOSE OF DISBURSEMENT (Required, system generated)
--Text must read: 'Non Contribution Account - Reimbursement: See Below' is changed to:

PURPOSE OF DISBURSEMENT (Required, system generated)
--Text must read: 'Non-contribution Account - Reimbursement: See Below'

Non-Contribution will be changed to lower case "c" = Non-contribution in both transaction and spec sheet.

Moved back to QA review to retest this change.

Added screenshot for Non-contribution Account Staff Reimbursement error:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/85dfe834-3611-441b-a842-0747a8acf97d)

**Comment by WiseQA** [comment]
QA review retested and verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed "Non-contribution Account - Reimbursement: See Below"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/60a5a333-40a0-4ac6-8d42-c342a5d197bb)

QA Review retest Completed. Moved to Stage Ready.

**Comment by WiseQA** [comment]
During review today it was caught the + Save & add memo button is missing from this transaction.  See Acceptance Criteria above.

@MitchellTCG @mjtravers moving out of Stage Ready back to In-Progress for this fix

**Comment by mjtravers** [comment]
The old button code was still in this transaction type. Fix has been made. Passes CR. Ready for QA on STAGE.

**Comment by mjtravers** [comment]
The old button code was still in this transaction type. Fix has been made. Passes CR. Ready for QA on STAGE.

**Comment by WiseQA** [comment]
The drop down list has both:
Non-contribution Account Staff Reimbursement
Staff Reimbursement Memo

Staff Reimbursement Memo should not be listed in drop down. Returning to in-progress for fix ...

**Comment by WiseQA** [comment]
@MitchellTCG So what I am I suppose to be seeing in dropdown list ?  
Both names ???

**Comment by WiseQA** [comment]
Ignore below test:
QA retested the button add memo function is available. Ticket #902 was implemented after this ticket. Therefore the + Save & add memo button was not functional during testing of this ticket originally.

The drop down list has both:
**Non-contribution Account Staff Reimbursement**
 Staff Reimbursement Memo

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cb4cf703-da55-4292-9256-c72461efb94b)

Button working as designed. Verified fix was implement.

Verified when selecting  Staff Reimbursement Memo from the dropdown the Non-contribution Account Staff Reimbursement Memo page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/faac2f52-4db7-4937-aafc-514879c0c8c2)

**Comment by WiseQA** [comment]
QA retested the button add memo function is available. Ticket #902 was implemented after this ticket. Therefore the + Save & add memo button was not functional during testing of this ticket originally.

The drop down list shows ONLY the following (per ticket #902):
Non-contribution Account Staff Reimbursement Memo

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1d9d3968-31ab-471a-bcd2-eb64e479804a)

(Note: 3 tier button dropdown ticket has not been implemented to date)
