### ISSUE TITLE
Allow user to enter Non-contribution Account Staff Reimbursement Memo on Schedule B (Group B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#707]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Non-contribution Account Staff Reimbursement Memo”** sub-transaction under **”Non-contribution Account Staff Reimbursement ”** on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator 
**And** I am editing a Non-contribution Account Staff Reimbursement transaction on an open report
**Then** I will have the _option_ to enter the sub-transaction "Non-contribution Account Staff Reimbursement Memo"
**And** I will be required to enter the following information (unless otherwise noted):

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee 
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE ** (Required)
-	**MEMO ITEM** (Required, must be checked)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save
- Save & Add Memo (Memo Group: Non-contribution Account Staff Reimbursement; Memo name in list: Staff Reimbursement Memo)
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- ENTITY can be Organization, Individual, or Committee, but should default to Organization.
- Memo Item must be checked and read-only.

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=710072427) **Please note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/d6b65c62-29c5-4a52-9565-ee908bbf8f76)

**Comment by mjtravers** [comment]
From CR: Changes have been requested to the validate schema for this ticket. See comments in PR. Sending back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
Pre-requisite - create a Non-contribution Account Staff Reimbursement and saved in the Transactions Table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b17020c1-43f9-4946-948b-f941db72e844)

After entering a Non-contribution Account Staff Reimbursement transaction, click the Save & add a memo button. Verify dropdown list is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d696ed5f-c45b-45b2-9c00-675d0c10b8c4)

Non-contribution Account Staff Reimbursement Memo page is displayed and defaulted to "Organization".

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/72956a92-6402-4459-a065-18962575b674)

Verify Purpose of Disbursement (Required) field is displayed and required.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/05a9f3d5-db10-4700-af92-d2c677c5c003)

Non-contribution Account Staff Reimbursement Memo is displayed in the transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ff7251dc-8acf-4839-88c0-ee1de9156388)

Verified Accordion dropdown, Save & add a memo and memo page have been changed from "Non-Contribution" to "Non-contribution".   (Fix pushed in ticket #705).

QA Review Completed. Moved to Stage Ready.

**Comment by WiseQA** [comment]
QA retested the button add memo function is available. Ticket #902 was implemented after this ticket. Therefore the + Save & add memo button was not functional during testing of this ticket originally.

The drop down list shows ONLY the following (per ticket #902):
Non-contribution Account Staff Reimbursement Memo

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c63f0673-3c19-462a-896b-ff051279bd79)

(Note: 3 tier button dropdown ticket has not been implemented to date)
