### ISSUE TITLE
Allow user to enter Non-contribution Account Payment to Payroll on Schedule B (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#708]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Non-contribution Account Payment to Payroll”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Non-contribution Account Payment to Payroll"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
-Organization only
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, system generated)
--Text must read: 'Non-Contribution Account - Payroll: See Below'

**Note Changed to (see fix below):
PURPOSE OF DISBURSEMENT (Required, system generated)
--Text must read: 'Non-contribution Account - Payroll: See Below'**

-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save & Add Memo (Memo group: Non-Contribution Account Payment to Payroll; Memo name in list: Payment to Payroll Memo)
- Save
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note 

NOTE:   ALL transactions $0.00 and below negative aggregate value is always Itemized per BA.

 Dev Note 

- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=55770474) **Please note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/d6b65c62-29c5-4a52-9565-ee908bbf8f76)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Non-contribution Account Payment to Payroll a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0bf3b045-e88f-4a96-8ffa-af2e35724321)

Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed "Non-Contribution Account - Payroll: See Below"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5828b68a-6c69-4be8-8703-d24e7c6ed7f2)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3217159e-0266-4b63-9852-1d831ac0f301)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is >$0.00 and <200.00 (Note: Value cannot be below $0.00 negative value. Negative value is itemized)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/66b6e57f-6b3c-424c-8246-c378299237ce)

QA Review Completed. Moved to Stage Ready.

**Comment by mjtravers** [comment]
Fix for purpose description bug was made. Validation schema was updated to lowercase the c in Non-contribution Account so validation passes.

**Comment by WiseQA** [comment]
PURPOSE OF DISBURSEMENT (Required, system generated)
--Text must read: 'Non-Contribution Account - Payroll: See Below' is changed to:

PURPOSE OF DISBURSEMENT (Required, system generated)
--Text must read: 'Non-contribution Account - Payroll: See Below'

Non-Contribution will be changed to lower case "c" = Non-contribution in both transaction and spec sheet.

Moved back to QA review to retest this change.

Added screenshot of Non-contribution Account Payment to Payroll error:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/92587e19-f429-4615-86a4-fcd7c89cf886)

**Comment by WiseQA** [comment]
QA review retested and verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed "Non-contribution Account - Payroll: See Below"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f4e8566c-2222-48ff-9a52-2dafd6a798fa)

QA Review retest Completed. Moved to Stage Ready.

**Comment by WiseQA** [comment]
During review today it was caught the + Save & add memo button is missing from this transaction.  See Acceptance Criteria above.

@MitchellTCG @mjtravers moving out of Stage Ready back to In-Progress for this fix

**Comment by mjtravers** [comment]
The old button code was still in this transaction type. Fix has been made. Passes CR. Ready for QA on STAGE.

**Comment by WiseQA** [comment]
@MitchellTCG So what I am I suppose to be seeing in dropdown list ?  
Both names ???

**Comment by WiseQA** [comment]
@MitchellTCG Why does Acceptance Criteria read this way ?  Save & Add Memo (Memo group: Non-Contribution Account Payment to Payroll; Memo name in list: Payment to Payroll Memo)   So group bolded and selection of memo grayed out.   If this the way it works, then its working.   However the Memo group name should be greyed out and the memo name bolded to select in my mind.

**Comment by WiseQA** [comment]
Ignore test below:
QA retested the button add memo function is available.   Ticket #902 was implemented after this ticket.  Therefore the + Save & add memo button was not functional during testing of this ticket originally.

The drop down list has both:
Non-Contribution Account Payment to Payroll
Payment to Payroll Memo

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f9c6159f-14eb-46a2-8ff9-d99b63be662d)

Button working as designed. Verified fix was implement.

Verified when selecting Payment to Payroll Memo from the dropdown the Non-contribution Account Payment to Payroll Memo page is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7812a41f-5a9c-4017-8d33-7e34e3168a6d)

**Comment by WiseQA** [comment]
QA retested the button add memo function is available. Ticket #902 was implemented after this ticket. Therefore the + Save & add memo button was not functional during testing of this ticket originally.

The drop down list shows ONLY the following (per ticket #902):
Non-contribution Account Payment to Payroll Memo

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ca09dec7-eea6-4eea-ac0a-5946197e0cfc)

(Note: 3 tier button dropdown ticket has not been implemented to date)
