### ISSUE TITLE
Allow user to enter Non-contribution Account Payment to Payroll Memo on Schedule B (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#709]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Non-contribution Account Payment to Payroll Memo”** sub-transaction under **”Non-contribution Account Payment to Payroll”** on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator 
**And** I am editing a Non-contribution Account Payment to Payroll transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction: 
- Non-contribution Account Payment to Payroll Memo
**And** I will be required to enter the following information (unless otherwise noted):

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Individual, Organization
*Note - please default to Individual

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---

_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Required, must be checked)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save
- Save & Add Memo (Memo group: Non-Contribution Account Payment to Payroll; Memo name in list: Payment to Payroll Memo)
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- ENTITY can be Organization, Individual, or Committee, but should default to Individual.
- Memo Item must be checked and read-only.

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=710072427) **Please note this is a consolidated specification.**

 Wireframe
Memo Group Name: Non-Contribution Account Payment to Payroll
Memo Name (in list--example shows 'Organization'): Payment to Payroll Memo
![image001.png](https://images.zenhubusercontent.com/62eac7883f87756fe900911f/d630fede-b16a-4e96-8d18-3a02be9a9ea2)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/d6b65c62-29c5-4a52-9565-ee908bbf8f76)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
Pre-requisite - create a Non-contribution Account Payment to Payroll and saved in the Transactions Table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ae4f0c12-fc84-4d4e-a775-128440eb6bbf)

After entering a Non-contribution Account Payment to Payroll transaction, click the Save & add a memo button. Verify dropdown list is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/75419193-84d1-419c-93bb-ff388eb8a74d)

Non-contribution Account Staff Reimbursement Memo page is displayed and defaulted to "Individual".

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2c96d91a-06ba-4772-98c6-374884dfe0e9)

Verify Purpose of Disbursement (Required) field is displayed and required.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/33f6499b-25d2-496c-95cd-9a8a607bcea5)

Non-contribution Account Staff Reimbursement Memo is displayed in the transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/47b1ede9-f765-4f1c-b698-855bf605ee5f)

Verified Accordion dropdown, Save & add a memo and memo page have been changed from "Non-Contribution" to "Non-contribution". (Fix pushed in ticket #705).

QA Review Completed. Moved to Stage Ready.

**Comment by WiseQA** [comment]
Ignore test below:
QA review retested and verified + Save & add memo button. Ticket #902 was implemented after this ticket.

After entering a Non-contribution Account Payment to Payroll transaction, click the Save & add a memo button. Verify dropdown list is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/01fdcfb5-f5c6-4138-a069-1d4d43906c7c)

Save & add memo button has been updated and working as designed.

**Comment by WiseQA** [comment]
QA retested the button add memo function is available. Ticket #902 was implemented after this ticket. Therefore the + Save & add memo button was not functional during testing of this ticket originally.

The drop down list shows ONLY the following (per ticket #902):
Non-contribution Account Payment to Payroll Memo

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/05c2340e-b186-43de-8668-d7f2ad338ce4)

(Note: 3 tier button dropdown ticket has not been implemented to date)
