### ISSUE TITLE
Allow user to enter National Party Recount/Legal Proceedings Account Disbursement on Schedule B (Group B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#710]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”National Party Recount/Legal Proceedings  Account Disbursement”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “National Party Recount/Legal Proceedings Account Disbursement"
**Then** I will be required to enter the following information (unless otherwise noted):

---
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee 
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)
---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)
---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be a negative)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, system-generated AND user-entered)
--Text must read: 'Recount/Legal Proceedings Account: XX', where XX is user entered text'
--**NOTE: System will automatically prefix the entered text with 'Recount/Legal Proceedings Account:'**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save 
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB29.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- The Purpose of Disbursement is part system-generated, part user-entered.
- The transaction name needs to be updated on the accordion dropdown list to read "National Party Recount/Legal Proceedings Account Disbursement" (Currently is National Party Recount Account Disbursement")

 Dev Note 

- To display ‘Recount/Legal Proceedings Account:' in the CPD, use https://primeng.org/inputnumber#prefixsuffix as an example
- The transaction name needs to be updated on the accordion dropdown list to read "National Party Recount/Legal Proceedings Account Disbursement" (Currently is National Party Recount Account Disbursement")
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1972759847) **This is a consolidated specification**

 Wireframe 

![710 - National Party Recount-Legal Proceedings Account Disbursement.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/59c68eaa-15bd-4f5b-8e3b-f4b3fdcf08c5)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
Wire added

**Comment by MitchellTCG** [comment]
@AureliaKhorsand Wire updated

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "National Party Recount/Legal Proceedings Account Disbursement" a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/29da4dae-ee00-46c2-bb9a-50ac96924e7f)

Verified CONTACT TYPE dropdown contains: Organization, Individual, Committee and dropdown for Contact Type is defaulted to Organization.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/456d48f2-bbb8-48de-81a6-9aac17cd5e5e)
Review withh @mjtravers and @MitchellTCG

**Comment by mjtravers** [comment]
Per review with @WiseQA , @MitchellTCG , @mjtravers , the following bugs were found with the CPD prefix field:
- Clicking the save button without editing the CPD saves without showing the "text required" error message
- If a comment string is added and then the space between the comment and prefix (system generated text) is removed, the prefix (system generated text) is displayed twice
- If the trailing space of the prefix (system generated text) is removed and save is clicked, an error message for invalid character displays
- add space after the colon to prefix (system generated text) string by default

**Comment by mjtravers** [comment]
Bug fix passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA reviewed the following bugs have been fixed for the Purpose of Disbursement (Required) field.

1.  Clicking the save button without editing the CPD saves without showing the "text required" error message

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5c13a942-40c5-4165-817e-9a27b98e218f)


2.  If a comment string is added and then the space between the comment and prefix (system generated text) is removed, the prefix (system generated text) is displayed twice

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c733f7e4-2a3a-441b-bebc-f39260c7ea35)

3.  If the trailing space of the prefix (system generated text) is removed and save is clicked, an error message for invalid character displays

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/958438c4-395b-483f-b265-4724bab969db)

4.  add space after the colon to prefix (system generated text) string by default

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9116d97f-ff6b-4ff2-8b61-1c95b757545d)

QA Review Completed.   Moved to Stage Ready.
