### ISSUE TITLE
Allow user to enter Recount Account Disbursement on Schedule B (Group B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#711]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Recount Account Disbursement”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Recount Account Disbursement"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee 
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)
---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)
---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBUSRSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, system-generated AND user entered)
-- Text: ‘Recount Account: XX’, where XX is user entered text
--**NOTE: System will automatically prefix the entered text with Recount Account: '**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And if** the Aggregate amount is >= $200.01 or negative,
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB29.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- The Purpose of Disbursement is part system-generated, part user-entered.
- The transaction name needs to be updated on the accordion dropdown list to read "Recount Account Disbursement" (Currently is Recount Disbursement")

 Dev Note 

- To display ‘Recount Account:' in the EPD, use https://primeng.org/inputnumber#prefixsuffix as an example
- The transaction name needs to be updated on the accordion dropdown list to read "Recount Account Disbursement" (Currently is Recount Disbursement")
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1972759847)  **This is a consolidated specification**

 Wireframe 

![711 - Recount Account Disbursement.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/55e1514a-47cf-439f-a6fd-e556d173dbe1)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
should the text beside **Purpose of Disbursement** be "(Required, system-generated AND user entered)" or just "(Required)?

Review Wire for context

**Comment by MitchellTCG** [comment]
@AureliaKhorsand Wire Updated

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Ticket to be put on-hold.   Bug fixes listed below will be fixed in ticket #710.  #710 will be retested first to verify bug fixes have been corrected.

Per review with @WiseQA , @MitchellTCG , @mjtravers , the following bugs were found with the CPD prefix field:

Clicking the save button without editing the CPD saves without showing the "text required" error message
If a comment string is added and then the space between the comment and prefix (system generated text) is removed, the prefix (system generated text) is displayed twice
If the trailing space of the prefix is removed and save is clicked, an error message for invalid character displays
add space after the colon to prefix (system generated text) string by default

**Comment by WiseQA** [comment]
QA review verified when selecting "Recount Account Disbursement" a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/739740ee-4253-4445-b5c5-a9cd3e0c690d)

Verified CONTACT TYPE dropdown contains: Organization, Individual, Committee and dropdown for Contact Type is defaulted to Organization.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9843720d-a795-4cc7-a3b0-84a20ae1c9e7)

Verified Purpose of Disbursement (Required) is a required field

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4d8da8af-d1bf-4ba6-a061-eafdabe24204)

Verify "Transactions in this report" table is updated with Disbursement.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7930d90b-1e6b-4b41-a4fd-dc2a2c97273f)

QA Review Completed.  Moved to Stage Ready.
