### ISSUE TITLE
Allow user to enter National Party Pres. Nominating Convention Account Disbursement on Schedule B (Group B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#713]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”National Party Pres. Nominating Convention Account Disbursement”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement 
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “National Party Pres. Nominating Convention Account Disbursement"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee 
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be a negative)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, system-generated AND user-entered)
--Text:  "Pres. Nominating Convention Account: XX", where "XX" is generated by the user
--**NOTE: System will automatically prefix the entered text with 'Pres. Nominating Convention Account: '**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB21B

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- The Purpose of Disbursement is part system-generated, part user-entered.
- The transaction name needs to be updated on the accordion dropdown list to read "National Party Pres. Nominating Convention Account Disbursement" (Currently is Convention Account Operating Expense for National Party Expense")

 Dev Note 

- To display ‘Pres. Nominating Convention Account: ' in the CPD, use https://primeng.org/inputnumber#prefixsuffix as an example
- The transaction name needs to be updated on the accordion dropdown list to read "National Party Pres. Nominating Convention Account Disbursement" (Currently is Convention Account Operating Expense for National Party Expense")
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1972759847) **This is a consolidated specification**

 Wireframe 

![713 - National Party Pres. Nominating Convention Account Disbursement.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/c8a35636-1609-4a7a-a63c-cb3e00096907)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
Wire posted

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg Next to Purpose of Disbursement, usually we just say (Required) if it is required, or (Optional) if it's optional. Also, the box should maybe be white, since the user can edit it? Finally, Memo Item is optional.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand  Wire Updated

It appears i put the wrong title on 713  oops fixed

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Ticket to be put on-hold.   Bug fixes listed below will be fixed in ticket #710.  #710 will be retested first to verify bug fixes have been corrected.

Per review with @WiseQA , @MitchellTCG , @mjtravers , the following bugs were found with the CPD prefix field:

Clicking the save button without editing the CPD saves without showing the "text required" error message
If a comment string is added and then the space between the comment and prefix (system generated text) is removed, the prefix (system generated text) is displayed twice
If the trailing space of the prefix is removed and save is clicked, an error message for invalid character displays
add space after the colon to prefix (system generated text) string by default

**Comment by WiseQA** [comment]
QA review verified when selecting "National Party Pres. Nominating Convention Account Disbursement" a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/855b607d-b587-470c-aa6e-6e1d182815ba)

Verified CONTACT TYPE dropdown contains: Organization, Individual, Committee and dropdown for Contact Type is defaulted to Organization.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/786c8ccd-8b84-416f-a1c2-4ca91d165163)

Verified Purpose of Disbursement (Required) is a required field

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d4f9e5be-8003-4555-a738-862cc4186f28)

Verify "Transactions in this report" table is updated with Disbursement.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/89ee4fe4-5b93-4186-85b9-1c5f4d032310)

(Note:   Memo Item checkbox is unselected for #710, #711 and #712.)

QA Review Completed. Moved to Stage Ready.
