### ISSUE TITLE
Allow user to enter Individual Refund - National Party Headquarters Buildings Account on Schedule B (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#714]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Individual Refund - National Party Headquarters Buildings Account”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Individual Refund - National Party Headquarters Buildings Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
-Individual Only

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (System generated)
--Text must read: "Headquarters Buildings Account: Refund"
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group "NATIONAL_PARTY_HEADQUARTERS_ACCOUNT", including:
- Joint Fundraising Transfer - National Party Headquarters Buildings Account
- Individual National Party Headquarters Buildings Account JF Transfer Memo
- _Partnership Receipt Headquarters Buildings Account JF Transfer Memo - not developed_
- _Partnership Individual Headquarters Buildings Account JF Transfer Memo - not developed_
- Individual National Party Headquarters Buildings Account
- Partnership National Party Headquarters Buildings Account
- Partnership National Party Headquarters Buildings Account Memo
- Earmark Receipt for National Party Headquarters Buildings Account (Contribution) & Memo

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file with form type SB21b.

 QA Note
- No Aggregate field should be on the entry form.
- Note that these amounts must be _subtracted_ from the aggregates in Schedule A that share the same entity.

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=827168155) **Please note this is a consolidated specification.**

 Wireframe
Transaction Button design
![User Journey - P2](https://user-images.githubusercontent.com/31663028/226462518-4b5254b7-388f-4161-bccf-55ae9aaef377.jpg)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by dheitzer** [comment]
local development/testing complete EXCEPT changes to subtract from the scha aggregate happening in branch  `feature/716-719-722-tribal-refunds`.  Once this branch is complete, we will need to pull this in and add it to the REFUND transaction list.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Individual Refund - National Party Headquarters Buildings Account a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8d39d323-1e87-45db-be14-7cb80779c467)

Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed "Headquarters Buildings Account: Refund"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6e90d816-b2ce-4de8-a45e-55f8f876c824)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5eeeacfe-aa2c-4c3c-b6eb-93363a20ad69)

QA review entered same contact for Individual Refund - National Party Headquarters Buildings Account  (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount.

Following error is displayed after:
1.  Entering disbursement for Individual Refund - National Party Headquarters Buildings Account
2.  Save transaction - transaction successfully saved
3.  Create receipt for Individual Refund - National Party Headquarters Buildings Account
4.  Upon saving receipt the following error appears:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e9de9b80-e677-4a07-ab33-4db95799e470)

QA tested twice and getting same error.  Cleared cache - cookies and retested getting same error.

Returned to In-progress for review of error.

**Comment by WiseQA** [comment]
@mjtravers and I recreated transactions and he got same error after testing twice.   Ticket status changed to Hot Fix for Sprint 23.

**Comment by mjtravers** [comment]
The bug was in the $id field of the validate schema for this transaction type. It had a wrong identifier. Fix was made, passed CR, and has been deployed on STAGE. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified bug fix.  

QA review entered same contact for Individual Refund - National Party Headquarters Buildings Account (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3e3f3671-ab60-4f59-a6de-fe21a3fe21ae)

QA Review Completed.   Moved to Stage Ready.

**Comment by WiseQA** [comment]
QA Review noticed the "Memo Item" check box for Individual Refund - National Party Headquarters Buildings Account (Schedule A) was checked.  This was noticed when doing refund for Schedule B and verifying aggregate working with Schedule A ticket.  (Note:  This was also verified by BA the Memo Item checkbox should be unchecked).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/72c44ca7-4a05-402c-a425-b5d0d45645bf)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/600d56ea-0a8e-4729-82a5-7e052c8560bc)

@MitchellTCG @mjtravers returned to In-progress for another hotfix for this ticket.

**Comment by mjtravers** [comment]
Bug fix was made in validation schema for this transaction type. Passes CR. Ready for QA on STAGE.

**Comment by WiseQA** [comment]
QA Review verified hotfix (bug fix) for "Memo Item" checkbox to be unchecked for Individual Refund - National Party Headquarters Buildings Account  (Schedule A)  (see below screenshot).  

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/30dbf183-5806-4146-bfc5-431b9e8c9c4d)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bda7411a-f184-4e32-8315-99a900434310)

QA Review Completed on this Hotfix (Bug Fix).   Moved back to Stage Ready.
