### ISSUE TITLE
Allow user to enter Other Committee Refund - National Party Headquarters Buildings Account on Schedule B (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#715]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Other Committee Refund - National Party Headquarters Buildings Account”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Other Committee Refund - National Party Headquarters Buildings Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE** (required, includes LOOKUP)
-Committe
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be negative)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (System-generated)
-Text: 'Headquarters Buildings Account: Refund'
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group "NATIONAL_PARTY_HEADQUARTERS_ACCOUNT", including:
- Joint Fundraising Transfer - National Party Headquarters Buildings Account
- PAC National Party Headquarters Buildings Account JF Transfer Memo
- Party National Party Headquarters Buildings Account
- PAC National Party Headquarters Buildings Account
- Partnership National Party Headquarters Buildings Account
- Partnership National Party Headquarters Buildings Account Memo
- Earmark Receipt for National Party Headquarters Buildings Account (Contribution) & Memo

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file with form type SB21B.

 QA Note
- No Aggregate field should be on the entry form.

 Dev Note 

- BENEFICIARY COMMITTEE FEC ID and NAME will pull from PAYEE ORGANIZATION NAME and the Committee ID, similar to functionality in Schedule A.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1383049735) **Please note this is a consolidated specification.** 

 Wireframe 

![703 - Non-contribution Account Disbursement.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/edde9faa-5e5e-4984-9381-fc8df3d29897)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
Wire attached. like 718, I left the Purpose as System-generated. please let me know if i need to change it.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
uploaded

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Other Committee Refund - National Party Headquarters Buildings Account a transaction "Committee" only is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0e8ac631-f741-4e55-9fd5-36671863781e)

Contact type is Committee Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d3dadc6f-54d2-4b35-9080-225fcce5d862)

Verified PURPOSE OF DISBURSEMENT (SYSTEM-GENERATED) is displayed with text field displaying 'Headquarters Buildings Account: Refund'

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/62571203-4e99-4e3e-81a5-81be21db5313)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bd8ecbdd-e4f5-4c4b-8f78-d5679d374dac)

QA review entered same contact for Other Committee Refund - National Party Headquarters Buildings Account(same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount.  (Tested with other Committee transaction - Joint Fundraising Transfer - National Party Headquarters Buildings Account.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7fb7db25-2b9b-4d8e-93e4-51044e7f3d9c)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/90c6a949-bdc2-4201-90e4-f861979b0a0b)

**(Note:   e2e testing to verify all aggregate groups.)**

QA Review Completed.   Moved to Stage Ready.

**Comment by AureliaKhorsand** [comment]
Removed the following from the list of transactions that share the aggregation group since they would never have the same entity, thus cannot be aggregated together:
- Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo
- Partnership Individual Recount/Legal Proceedings Account JF Transfer Memo

**Comment by WiseQA** [comment]
QA review reverified list.
