### ISSUE TITLE
Allow user to enter Individual Refund - National Party Pres. Nominating Convention Account on Schedule B (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#717]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Individual Refund - National Party Pres. Nominating Convention Account”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Individual Refund - National Party Pres. Nominating Convention Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
-Individual Only

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, System generated)
--Text must read: "Pres. Nominating Convention Account: Refund"
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)
---
**Then** I will be able to:
- Cancel
- Save 
- Edit

**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group "NATIONAL_PARTY_CONVENTION_ACCOUNT", including:
- Joint Fundraising Transfer - National Party Pres. Nominating Convention Account
- Individual National Party Pres. Nominating Convention Account JF Transfer Memo
- _Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo – not developed_
- _Partnership Individual Pres. Nominating Convention Account JF Transfer Memo – not developed_
- Individual National Party Pres. Nominating Convention Account
- Partnership National Party Pres. Nominating Convention Account
- Partnership National Party Pres. Nominating Convention Account Memo
- Earmark Receipt for National Party Pres. Nominating Convention Account (Contribution) & Memo

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file with form type SB21b.

 QA Note
- No Aggregate field should be on the entry form.
- Note that these amounts must be _subtracted_ from the aggregates in Schedule A that share the same entity.

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=827168155) **Please note this is a consolidated specification.**

 Wireframe
Transaction Button design
![User Journey - P2](https://user-images.githubusercontent.com/31663028/226462518-4b5254b7-388f-4161-bccf-55ae9aaef377.jpg)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by dheitzer** [comment]
local development/testing complete EXCEPT changes to subtract from the scha aggregate happening in branch  `feature/716-719-722-tribal-refunds`.  Once this branch is complete, we will need to pull this in and add it to the REFUND transaction list.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Individual Refund - National Party Pres. Nominating Convention Account a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1d65c64e-a063-4086-b99a-ec52d18f2d5b)

Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed "Pres. Nominating Convention Account: Refund"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7de591bd-c672-4a8c-b337-d4b6752f2182)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/db372c6e-8861-4d1c-ace6-9f70fb21952b)

QA review entered same contact for Individual Refund - National Party Pres. Nominating Convention (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/52391417-2bfe-4ecf-b503-ac47eaadc0c9)

QA Review Completed.   Moved to Stage Ready.
