### ISSUE TITLE
Allow user to enter Other Committee Refund - National Party Pres. Nominating Convention Account on Schedule B (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#718]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Other Committee Refund - National Party Pres. Nominating Convention Account”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click(open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Other Committee Refund - National Party Pres. Nominating Convention Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
-Committee
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be a negative value)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (System-generated)
-Text: 'Pres. Nominating Convention Account: Refund'
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)
---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group  "NATIONAL_PARTY_CONVENTION_ACCOUNT", including:
- Joint Fundraising Transfer - National Party Pres. Nominating Convention Account
- PAC National Party Pres. Nominating Convention Account JF Transfer Memo
- Party National Party Pres. Nominating Convention Account
- PAC National Party Pres. Nominating Convention Account
- Partnership National Party Pres. Nominating Convention Account
- Partnership National Party Pres. Nominating Convention Account Memo
- Earmark Receipt for National Party Pres. Nominating Convention Account (Contribution) & Memo

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB21B. 

 QA Note
- No Aggregate field should be on the entry form.

 Dev Note 

- BENEFICIARY COMMITTEE FEC ID and NAME will pull from PAYEE ORGANIZATION NAME and the Committee ID, similar to functionality in Schedule A.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1383049735) **Please note this is a consolidated specification.**

 Wireframe 

![718 - Other Committee Refund - National Party Pres. Nominating Convention Account.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/e22a73b0-d31d-416f-9b0a-3d5a24180ed3)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
Is this Required or System-generated. I thought required was forced text ":" then user entered

**Comment by AureliaKhorsand** [comment]
@MitchellTCG system-generated. I updated the AC to make it clearer.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Other Committee Refund - National Party Pres. Nominating Convention Account a transaction "Committee" only is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bd53c229-c4d9-42ab-b42f-473be6d07be7)

Contact type is Committee Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8d99c771-de95-4e79-9877-a9b3ed240d8b)

Verified PURPOSE OF DISBURSEMENT (SYSTEM-GENERATED) is displayed with text field displaying 'Pres. Nominating Convention Account: Refund'

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f9cf6a96-94e9-4b8a-88ed-169415573694)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/60adca53-ade1-4df8-b3dc-3020cee71376)

QA review entered same contact for Other Committee Refund - National Party Pres. Nominating Convention Account (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount. (Tested with other Committee transaction - Joint Fundraising Transfer - National Party Pres. Nominating Convention Account.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/416efb23-a76f-4fdb-a229-fb15dfc7f7de)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b8862569-bac4-4e4f-a1e0-dadea4badf97)

**(Note: e2e testing to verify all aggregate groups.)**

QA Review Completed. Moved to Stage Ready.

**Comment by AureliaKhorsand** [comment]
Removed the following from the list of transactions that share the aggregation group since they would never have the same entity, thus cannot be aggregated together:
- Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo
- Partnership Individual Recount/Legal Proceedings Account JF Transfer Memo

**Comment by WiseQA** [comment]
QA review reverified list.
