### ISSUE TITLE
Allow user to enter Tribal Refund - National Party Pres. Nominating Convention Account on Schedule B (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#719]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Tribal Refund - National Party Pres. Nominating Convention Account”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Tribal Refund - National Party Pres. Nominating Convention Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
-Organization only
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, system generated)
--Text must read: 'Pres. Nominating Convention Account: Refund'
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group "NATIONAL_PARTY_CONVENTION_ACCOUNT", including:
- Joint Fundraising Transfer - National Party Pres. Nominating Convention Account
- Tribal National Party Pres. Nominating Convention Account JF Transfer Memo
- _Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo – not developed_
- _Partnership Individual Pres. Nominating Convention Account JF Transfer Memo – not developed_
- Tribal National Party Pres. Nominating Convention Account
- Partnership National Party Pres. Nominating Convention Account
- Partnership National Party Pres. Nominating Convention Account Memo
- Earmark Receipt for National Party Pres. Nominating Convention Account (Contribution) & Memo

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file with form type SB21b.

 QA Note
- No Aggregate field should be on the entry form.
- Note that these amounts must be _subtracted_ from the aggregates in Schedule A that share the same entity.

 Dev Note 

- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=595885121) **Please note this is a consolidated specification.**

 Wireframe
Transaction Button design
![User Journey - P2](https://user-images.githubusercontent.com/31663028/226462518-4b5254b7-388f-4161-bccf-55ae9aaef377.jpg)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
Server-side aggregate calculations are working as intended
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/521bfb09-916e-4246-bb38-963f48722caf)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Tribal Refund - National Party Pres. Nominating Convention Account a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/af578bc3-e720-4be5-8c74-23d74a501839)

Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed "Pres. Nominating Convention Account: Refund"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/db321954-bd7b-4d4d-a991-0eced9fbc685)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/39ab0e25-224d-41d3-b64e-768733fc6f10)

**Comment by WiseQA** [comment]
QA review entered same contact for Tribal National Party Pres. Nominating Convention Account (same aggregation group).  Below screen shot where Aggregate is showing the amount from current and previous transaction.


![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d024ec32-46b5-424b-9b0c-d72f8a8c2c37)

Transactions table is displaying correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fdfbee3a-f5b1-48b8-977e-c5bd05f69d54)

Returned to In-Progress for fix - reviewed with @toddlees

**Comment by mjtravers** [comment]
Patch made so that the sting concatenation is converted to a number so sum is properly calculated before shown on aggregate box on form page. Passes CR. Sending back to QA.

**Comment by WiseQA** [comment]
QA review reentered same contact for Tribal National Party Pres. Nominating Convention Account (same aggregation group). Below screen shot where Aggregate is showing the amount correctly.   

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/81a58bd2-0175-4737-abe2-6cfdb12761c5)

Verified bug fix.

QA Review Completed.   Moved to Stage Ready.
