### ISSUE TITLE
Allow user to use Lookup within Transactions for existing Individual Contacts-Part 1

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#72]
Business Reason

The system will employ a Lookup feature when entering transactions in order to allow the user to pull existing contact information from the committee account's Contact Management table. This will also assist the FEC in making more accurate data available to the public.

Acceptance Criteria

_Note: The transaction entry form will _only_ show the contact lookup until a contact is selected. Once a contact is selected, the transaction form will show._

***Given*** the user is entering a transaction

  ***And*** they have indicated an Entity Type of "IND" (or "IND" is required entity type)

  ***Then*** they will be able to search their committee account's Contact Management table by _name_ using a Lookup feature to find and select an existing contact

  ***And*** the results will including the following information in the dropdown under the text "Select an existing individual contact":

*   Last Name, First Name
*   "In Contacts"

***And*** the Lookup results will:

*   highlight the matching text from the search box within the results _(QA note: excluding delimiters such as spaces and commas)_
*   highlight a selection grey if hovered over with the pointer
*   be limited to 10 maximum _(Dev/QA note: for now, users need to type more to narrow it down. #542 will address when results are more than 10.)_

***And*** when I select the contact I want, the system will pull in the contact information necessary for the transaction and show the full transaction entry form. 

  ***(Note information to include Contributor, Address Fields and Employer and Occupation Fields)***

  ***If*** there are no results, the system will indicate as such.

BA notes

FECFile Online basic requirements as follows:

*   Users will be able to search their committee account's Contact Management table using a Lookup feature to find and select an existing contact for a transaction
*   When the user selects the contact, the system will pull in the contact information necessary for the transaction.
*   The transaction will be associated with that contact (used for aggregations/itemization logic)

DEV notes

From this point on, contacts and transactions need to be connected. _Each transaction must be associated with a contact, such as a UUID._

QA notes

Relevant existing Transactions to test:

*   Individual Receipt
*   Offsets to Operating Expenditures
*   Other Receipts

***(Note information when selecting a contact from the lookup includes Contributor, Address Fields and Employer and Occupation Fields)***

To test, identify an existing individual contact in Contact Management for your committee account and use that name to search.

Wireframes: 

  (Note: down arrow next to "individual" only if other entity types are valid for selection.)

![image.png]([https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/03652075-c2cc-4512-9386-d4cbd75fb36b](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/03652075-c2cc-4512-9386-d4cbd75fb36b))

![image.png]([https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/c61b76c3-177f-4df5-a5b5-1e52c31eeb38](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/c61b76c3-177f-4df5-a5b5-1e52c31eeb38))

![image.png]([https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/c5cf9ea9-dbdd-4f45-a027-4d4ff0ed9778](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/c5cf9ea9-dbdd-4f45-a027-4d4ff0ed9778))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1326](https://fecgov.atlassian.net/browse/FECFILE-1326)

**Comment by JonellaCulmer** [comment]
@MitchellTCG @AureliaKhorsand @mary-tcg @GreggMoreland 
What follows is a walk-through of how to create a new contact and edit an existing contact. Please let me know if you have any questions, comments or concerns. 

Appearance of lookup across all contact types, including All option. 
![Screen Shot 2022-08-24 at 3 30 57 PM](https://user-images.githubusercontent.com/31663028/186507156-15b71c9e-d06e-46b2-bb93-9aa2d9979cd2.png)

Here are the mockups for editing a contact from a transaction. 

1. When opening a transaction for the first time, you will see only the contact selection portion of the transaction. Once the contact selection is made the all other sections/fields of a given transaction will appear. As for the selection of a contact, only those contact types relevant to a given transaction will appear. In this example the dropdown is disabled and you only see "Individual" listed. Additionally, the filer will be able to search for a specific contact's name with a typeahead search (not free text) or create a new contact. 
![Screen Shot 2022-08-24 at 3 37 16 PM](https://user-images.githubusercontent.com/31663028/186508056-0e5d9579-475c-45eb-be02-7bbadfa8f3e8.png)

2. If a filer selects “Create a new contact”, a pop-up appears. For transactions with multiple relevant contact types, a dropdown will be on the pop-up and allow filers to select the type from the dropdown. 
![Screen Shot 2022-08-24 at 3 37 24 PM](https://user-images.githubusercontent.com/31663028/186508134-7a4f8336-4bf8-4996-aab3-ff3ff9a3be64.png)

3. If a filer is on a transaction with a single relevant contact type, the pop-up will default to the contact type and populate the required and optional fields for that contact type. Once the contact is complete, the filer will select “Save and continue”, the pop-up will close and the filer will be on the form, now populated with that contact’s information. 
![Screen Shot 2022-08-24 at 3 37 34 PM](https://user-images.githubusercontent.com/31663028/186508158-0365b8c4-e3d5-4ceb-b510-7bd122a1bc30.png)

4. Only the information required for that transaction will appear. The filer will then complete the remaining fields for that transaction and select “Save & add another” or “Save & view all transactions”.
![Screen Shot 2022-08-24 at 3 37 46 PM](https://user-images.githubusercontent.com/31663028/186508176-ab640af0-cffd-4d43-a4b3-1ba5db2fc1ee.png)

5. Before the filer is taken to the next screen (whether it be to create another new transaction, or the manage all transactions page), a second pop-up will appear alerting the filer that, in addition to creating a new transaction, they are also creating a new contact. The language will need to be dynamic enough to clarify the contact name, as well as the contact type in this pop-up.
<img width="481" alt="Screen Shot 2022-08-25 at 1 08 28 PM" src="https://user-images.githubusercontent.com/31663028/186727720-322ba8f0-6b31-464b-adff-cc66ba870e46.png">

Additional notes:
- When selecting from a name in the lookup dropdown, selections will be limited to 10 and the filer will need to have an option to see the full list of contacts. This will require additional design work. 
- The full list of contacts, at this point, will need to be an additional pop-up and include a searchable table. This is so the filer does not have to leave a transaction to make the correct selection. 
- The searchable table will need to have pagination capabilities. 
![Screen Shot 2022-08-24 at 3 38 17 PM](https://user-images.githubusercontent.com/31663028/186508287-79581b3a-498a-4bed-b6bb-e5d35560bad9.png)

**Comment by AureliaKhorsand** [comment]
Archived from ticket: 

Dropdown example from fec.gov that we are basing design off of: 
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/e9845eff-168e-48c5-bb30-aa83b7f8a593)

**Comment by AureliaKhorsand** [comment]
Archived: Robert has a fancy autocomplete widget that is being used on the FEC site. Obtain the code for the widget and modify accordingly to use it in the Angular framework. Reuse functionality from fec.gov for lookup, but will also need to build in pulling full data for contact.

**Comment by AureliaKhorsand** [comment]
**BA To Do:** Split out Individual and Organization into separate tickets. Individual will be 13, Organization will be 8.

**Comment by mjtravers** [comment]
Some questions and comments sent back to David from CR before moving to QA

**Comment by dheitzer** [comment]
added CR fixes and pushed back to CR.

**Comment by mjtravers** [comment]
One last CR comment to fix brought up by Elaine about handling the different name order permutations in the search and in the highlighting. Sending ticket back to In Progress for further development.

**Comment by toddlees** [comment]
In a meeting with @MitchellTCG  we decided that we will pass on matching names with `'` until later

**Comment by WiseQA** [comment]
QA review "Address" "Employer" "Occupation" fields not updating when using the lookup and selecting a Contact.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e68af5b6-a3fd-476b-943b-7ecb8386ac66)

@dheitzer @AureliaKhors @GreggMoreland and returned to In-progress for fix per our discussion.   Note Tickets 548 and 538 will need updated with same change.

**Comment by mjtravers** [comment]
Latest fix passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA review verified lookup is searchable and contains last name, first name and In Contacts for Individual Contacts.  (Note also verified that the highlight a selection grey if hovered over with the pointer.)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2996d65d-aca5-4d8f-8719-0f5abdd8708c)

Once contact selected verified Contributor fields, Address fields, Employer and Occupation fields updated with contact information.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/06e4f2e3-7b82-40c1-91c4-3b31d24dfd45)

Verified testing the Individual Receipt, Offsets to Operating Expenditures,  and Other Receipts transactions as denoted in Acceptance Criteria.

QA Review Completed.   Moved to Stage Ready.

**Comment by WiseQA** [comment]
QA retested Individual contacts and verified once select the "Save and add another" transaction the "Searchable" field has been cleared.   (Note this error found in ticket #548 and #538)   

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/288d4c78-7c4b-4d58-9703-bbb9015e9676)

Second QA review completed.
