### ISSUE TITLE
Allow user to enter Other Committee Refund - National Party Recount/Legal Proceedings Account on Schedule B (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#721]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Other Committee Refund - National Party Recount/Legal Proceedings Account”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a new transaction 
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Other Committee Refund - National Party Recount/Legal Proceedings Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
-Committee
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be a negative value)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required)
-Text: 'Recount/Legal Proceedings Account: Refund'
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save 
- Edit

**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group "NATIONAL_PARTY_RECOUNT_ACCOUNT", including:
- Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account
- PAC National Party Recount/Legal Proceedings Account JF Transfer Memo
- Party National Party Recount/Legal Proceedings Account
- PAC National Party Recount/Legal Proceedings Account
- Partnership National Party Recount/Legal Proceedings Account 
- Partnership National Party Recount/Legal Proceedings Account Memo
- Earmark Receipt for National Party Recount/Legal Proceedings Account (Contribution) & Memo

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB29. 

 QA Note
- No Aggregate field should be on the entry form.

 Dev Note 

- BENEFICIARY COMMITTEE FEC ID and NAME will pull from PAYEE ORGANIZATION NAME and the Committee ID, similar to functionality in Schedule A.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1383049735) **Please note this is a consolidated specification.**

 Wireframe 

![721 - Other Committee Refund - National Party Recount-Legal Proceedings Account.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/2496392b-d807-4815-b537-887ee3a6de79)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Wire attached 
Once again i could figure out this transaction with the ones listed on the accordion. Lets discuss today (This maybe a known problem but just want to dot my i's)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG Thanks for checking - they aren't there because they are new transactions added after the original list was put on the accordion page. It's expected that they aren't there already, they'll be added with their respective tickets.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Other Committee Refund - National Party Recount/Legal Proceedings Account a transaction "Committee" only is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bf72d71b-d270-4204-8823-50ec04ca3282)

Contact type is Committee Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0a2fb7c4-3ee2-463f-ab0d-9904d23a8ef8)

Verified PURPOSE OF DISBURSEMENT (SYSTEM-GENERATED) is displayed with text field displaying 'Recount/Legal Proceedings Account: Refund'

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bccd28b6-37ed-4da2-8d5b-0c62f8837e7d)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/96417ab4-fef8-41ed-9a68-e0f086b332ea)

QA review entered same contact for Other Committee Refund - National Party Recount/Legal Proceedings Account (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount. (Tested with other Committee transaction - Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7eadde62-c1bd-414c-ac03-686b4e16409a)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7fe870b1-aa29-4ff8-a120-62c4b4180044)

**(Note: e2e testing to verify all aggregate groups.)**

QA Review Completed. Moved to Stage Ready.

**Comment by AureliaKhorsand** [comment]
Removed the following from the list of transactions that share the aggregation group since they would never have the same entity, thus cannot be aggregated together:
- Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo
- Partnership Individual Recount/Legal Proceedings Account JF Transfer Memo

**Comment by WiseQA** [comment]
QA review reverified list.
