### ISSUE TITLE
Allow user to enter Tribal Refund - National Party Recount/Legal Proceedings Account on Schedule B (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#722]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Tribal Refund - National Party Recount/Legal Proceedings Account”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Tribal Refund - National Party Recount/Legal Proceedings Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
-Organization only
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, system generated)
--Text must read: 'Recount/Legal Proceedings Account: Refund'
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group  "NATIONAL_PARTY_RECOUNT_ACCOUNT", including:
- Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account
- Tribal National Party Recount/Legal Proceedings Account JF Transfer Memo
- _Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo- not developed_
- _Partnership Individual Recount/Legal Proceedings Account JF Transfer Memo- not developed_
- Tribal National Party Recount/Legal Proceedings Account
- Partnership National Party Recount/Legal Proceedings Account 
- Partnership National Party Recount/Legal Proceedings Account Memo
- Earmark Receipt for National Party Recount/Legal Proceedings Account (Contribution) & Memo

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file with form type SB29.

 QA Note
- No Aggregate field should be on the entry form.
- Note that these amounts must be _subtracted_ from the aggregates in Schedule A that share the same entity.

 Dev Note 

- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=595885121) **Please note this is a consolidated specification.**

 Wireframe
Transaction Button design
![User Journey - P2](https://user-images.githubusercontent.com/31663028/226462518-4b5254b7-388f-4161-bccf-55ae9aaef377.jpg)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/bc114ccd-7e14-4c1e-9c9a-9754997338fc)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Tribal Refund - National Party Recount/Legal Proceedings Account a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ed12c4f9-87fb-49e9-9201-dd4576ab63f6)

Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed "Recount/Legal Proceedings Account: Refund"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/760afa84-0bd8-416e-8f07-309285fe111a)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6233de24-61d6-4f9d-ad08-5e2a16c45eca)

QA review entered same contact for Tribal Refund - National Party Recount/Legal Proceedings Account (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e96721d9-af31-4075-baf6-7a7bd1b0c015)

QA Review Completed.  Moved to Stage Ready.
