### ISSUE TITLE
Allow user to enter Refund of Individual Contribution on Schedule B (Group B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#723]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Refund of Individual Contribution”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Refunds" Accordion link  
**Then** I can enter a transaction with the type “Refund of Individual Contribution"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Individual, Organization
*Note - please default to Individual.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Individual_

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be negative)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Optional)

-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group "GENERAL". 

- Individual Receipt

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB28A. 

 QA Note
- Note: There should be no Aggregate calculated or displayed, but the amount is included in aggregates in Schedule A via the Aggregation Group.
- Note that these amounts must be _subtracted_ from the aggregates in Schedule A that share the same entity. (Note, since this is a negative value, the result will be an increased aggregate in Schedule A.)

 Dev Note 

- Note: Aggregate is not calculated, but there IS an aggregation group to aggregate these amounts with some Schedule A transactions.
- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1989662991) **Please note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Refund of Individual Contribution a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4a65386b-5038-4373-886a-c1651265e506)

Contact type dropdown displays Individual (default) and Organization.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/172489e1-762d-4c55-9a65-cb0da2016d55)

Verified Purpose of Disbursement is (Optional)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2ad65359-9889-4075-a9f6-c8744f040984)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b31b85d2-6f38-47d6-b5c2-63bbbfffa626)

QA review entered same contact for Refund of Individual Contribution (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f3815df4-c72b-41d2-a53a-91bed7dd4fac)

QA Review Completed.   Moved to Stage Ready.
