### ISSUE TITLE
Allow user to enter Refund of Individual Contribution - Void on Schedule B (Group B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#724]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Refund of Individual Contribution - Void”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement 
**Then** Click(open) on the "Refunds" Accordion link  
**Then** I can enter a transaction with the type “Refund of Individual Contribution - Void"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Individual, Organization
*Note - please default to Individual.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Individual_

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, _must_ be negative)
**Note: System will automatically make the amount negative. AMOUNT MUST be a non-zero negative value to save, and max value is -$0.01. If amount exceeds that, then display error message 'Amount must be negative (example: -$20.00)'**

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Optional)

-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group "GENERAL". _(Note, since this is a negative value, the result will be an increased aggregate in Schedule A.)_

- Individual Receipt

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file

 QA Note
- Note: There should be no Aggregate calculated or displayed, but the amount is included in aggregates in Schedule A via the Aggregation Group.
- Note that these amounts must be _subtracted_ from the aggregates in Schedule A that share the same entity. However, since this is a negative value, the result will be an increased aggregate in Schedule A.

 Dev Note 

- Note: Aggregate is not calculated, but there IS an aggregation group to aggregate these amounts with some Schedule A transactions.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1989662991) **Please note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Refund of Individual Contribution - Void a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a15e60b2-085a-4269-b4d8-5bae8a41be89)

Contact type dropdown displays Individual (default) and Organization.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c46ddf12-5e4c-4504-adb0-174aaca25582)

Verified Purpose of Disbursement is (Optional)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4ce1d611-76d8-4a58-b5e7-7dd4c6e5e557)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e7338dd8-8803-45e9-adb5-63d0b26fee4c)

QA review entered same contact for Refund of Individual Contribution - Void (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount.  (Note - VOID is a negative value)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5a0f5fb5-735d-4c6e-9dac-4999f7e9c043)

QA Review Completed.   Moved to Stage Ready.
