### ISSUE TITLE
Allow user to enter Refund of Party Contribution on Schedule B (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#725]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Refund of Party Contribution”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click(open) on the "Refund" Accordion link  
**Then** I can enter a transaction with the type “Refund of Party Contribution"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE** (Required, includes LOOKUP)
-Committee
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be negative)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Optional, user entered)

-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Required)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group "GENERAL":

- Party Receipt

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB28B.

 QA Note
- Note: There should be no Aggregate calculated or displayed, but the amount is included in aggregates in Schedule A via the Aggregation Group.
- Note that these amounts must be _subtracted_ from the aggregates in Schedule A that share the same entity.

 Dev Note 

- Note: Aggregate is not calculated, but there IS an aggregation group to aggregate these amounts with some Schedule A transactions.
- BENEFICIARY COMMITTEE FEC ID and NAME will pull from PAYEE ORGANIZATION NAME and the Committee ID, similar to functionality in Schedule A.
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=954835295) **Please note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/2676916c-31b7-4141-9a7f-71ceec5b6dc5)

**Comment by Elaine-Krauss-TCG** [comment]
~~The new disbursements are working as intended, but there's a couple glitches in the behavior that are coming to light because the two VOID refunds are the first required-negative disbursements in SchB.  Probably not a big lift~~

The new models were missing a simple flag, and it was a 10 second fix once I knew what the issue was.  This was figured out soon after I made this comment, but I forgot to come back and follow up on it here.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Refund of Party Contribution transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7daa1097-4553-44d9-833a-1bc7d11681ab)

Contact type is Committee Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cc3552b9-924c-4e9a-ad71-347fbc5daaa5)

Verified PURPOSE OF DISBURSEMENT (OPTIONAL) is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/62f914c5-4b4d-4035-8f66-78bdec52a3b8)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5db3fc2c-d98e-4f72-85de-18cfed118a05)

QA review entered same contact for  Refund of Party Contribution (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount. (Tested with Party Receipt)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5ea28f67-e584-4156-92d4-f3816c897be7)

**(Note: e2e testing to verify all aggregate groups.)**

QA Review Completed. Moved to Stage Ready.
