### ISSUE TITLE
Allow user to enter Refund of PAC Contribution on Schedule B (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#727]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Refund of PAC Contribution”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Refund" Accordion link  
**Then** I can enter a transaction with the type “Refund of PAC Contribution"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, includes LOOKUP)
-- Committee 
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be negative)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Optional, user entered)

-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Required)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group "GENERAL":

- PAC Receipt

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB28C. 

 QA Note
- Note: There should be no Aggregate calculated or displayed, but the amount is included in aggregates in Schedule A via the Aggregation Group.
- Note that these amounts must be _subtracted_ from the aggregates in Schedule A that share the same entity.

### QA Notes ### 
 null
### DEV Notes ### 
 - BENEFICIARY COMMITTEE FEC ID and NAME will pull from PAYEE ORGANIZATION NAME and the Committee ID, similar to functionality in Schedule A.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=954835295) **Please note this is a consolidated specification.**
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Refund of PAC Contribution transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/baf789ab-6498-45a4-b50b-66c0cd39400e)

Contact type is Committee Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/90048591-3495-4ea2-997d-f3c20eb74204)

Verified PURPOSE OF DISBURSEMENT (OPTIONAL) is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9ab0d0e5-d443-4554-a2bf-e35a08d4ce03)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/457dfbc4-3c03-49b6-a046-305ba435ae97)

QA review entered same contact for Refund of PAC Contribution (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount. (Tested with PAC Receipt)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7463fb05-f8c4-4274-9ff4-f6a7a5a56ada)

QA Review Completed. Moved to Stage Ready.
