### ISSUE TITLE
Allow user to enter Refund of PAC Contribution - Void on Schedule B (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#728]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Refund of PAC Contribution - Void”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Refund" Accordion link  
**Then** I can enter a transaction with the type “Refund of PAC Contribution - Void"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, includes LOOKUP)
-- Committee 
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, _must_ be negative)
**Note: System will automatically make the amount negative. AMOUNT MUST be a non-zero negative value to save, and max value is -$0.01. If amount exceeds that, then display error message 'Amount must be negative (example: -$20.00)'**

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Optional)
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Required)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group "GENERAL". _(Note that since this is a negative value, the result will be an increased aggregate in Schedule A.)_

- PAC Receipt

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB28C. 

 QA Note
- Note: There should be no Aggregate calculated or displayed, but the amount is included in aggregates in Schedule A via the Aggregation Group.
- Note that these amounts must be _subtracted_ from the aggregates in Schedule A that share the same entity. However, since this is a negative value, the result will be an increased aggregate in Schedule A.

### QA Notes ### 
 null
### DEV Notes ### 
 - BENEFICIARY COMMITTEE FEC ID and NAME will pull from PAYEE ORGANIZATION NAME and the Committee ID, similar to functionality in Schedule A.
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=954835295) **Please note this is a consolidated specification.**
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Refund of PAC Contribution - Void a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7b86e17f-4985-4d3d-a075-04eadb052d03)

Contact type is Committee only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c70f36dd-8efc-4828-afef-2eb270dd4855)

Verified Purpose of Disbursement is (Optional)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/221e978f-80e8-407e-9e7b-c51c03b7aa65)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b9bf2679-13b0-43b0-a088-740b95976059)

QA review entered same contact for Refund of Refund of PAC Contribution - Void (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount. (Note - VOID is a negative value)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/30d773b0-cdd9-4c54-a245-f0ac1d0f7f11)

QA Review Completed. Moved to Stage Ready.
