### ISSUE TITLE
Allow user to enter Refund of Unregistered Receipt from Person on Schedule B (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#729]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Refund of Unregistered Receipt from Person”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement 
**Then** Click(open) on the "Refund" Accordion link  
**Then** I can enter a transaction with the type “Refund of Unregistered Receipt from Person"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, includes LOOKUP)
-- Organization 
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be negative)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Optional)
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group "GENERAL":

- Unregistered Receipt from Person

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB28A. 

 QA Note
- Note: There should be no Aggregate calculated or displayed, but the amount is included in aggregates in Schedule A via the Aggregation Group.
- Note that these amounts must be _subtracted_ from the aggregates in Schedule A that share the same entity.

 Dev Note 

- Note: Aggregate is not calculated, but there IS an aggregation group to aggregate these amounts with some Schedule A transactions.
- Note: The transaction name has changed. Was 'Refund of Unregistered Contribution - Void' and now is 'Refund of Unregistered Receipt from Person - Void'
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=94751392)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Refund of Unregistered Receipt from Person a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/16073d51-81ce-4925-b333-073609fda8f1)

Contact type is Organization Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/12af05de-1bf2-4a78-9899-ae6163cfeaf5)

Verified PURPOSE OF DISBURSEMENT (OPTIONAL) is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e1704f51-c88a-439d-914b-e54c090b78fa)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/145b2f5e-4f70-4336-9d9b-9e9661655b92)

QA review entered same contact for Refund of Unregistered Receipt from Person (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount. (Tested with other Organization transaction - Unregistered Receipt from Person

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1a62c81c-58ce-4385-9372-37634f3dbc86)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/af480c1a-3979-453e-84c0-f834958fb30d)

(Note: e2e testing to verify all aggregate groups.)

QA Review Completed. Moved to Stage Ready.
