### ISSUE TITLE
Allow user to enter Refund of Unregistered Receipt from Person - Void on Schedule B (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#730]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Refund of Unregistered Receipt from Person - Void”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click(open) on the "Refund" Accordion link  
**Then** I can enter a transaction with the type “Refund of Unregistered Receipt from Person - Void"
**Then** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, includes LOOKUP)
-- Organization 
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, _must_ be negative)
**Note: System will automatically make the amount negative. AMOUNT MUST be a non-zero negative value to save, and max value is -$0.01. If amount exceeds that, then display error message 'Amount must be negative (example: -$20.00)'**

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Optional)
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group "GENERAL". _(Note, since this is a negative value, the result will be an increased aggregate in Schedule A)._

- Unregistered Receipt from Person

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB28A.

 QA Note
- Note: There should be no Aggregate calculated or displayed, but the amount is included in aggregates in Schedule A via the Aggregation Group.
- Note that these amounts must be _subtracted_ from the aggregates in Schedule A that share the same entity. However, since this is a negative value, the result will be an increased aggregate in Schedule A.

 Dev Note 

- Note: Aggregate is not calculated, but there IS an aggregation group to aggregate these amounts with some Schedule A transactions.
- Note: The transaction name has changed. Was 'Refund of Unregistered Contribution - Void' and now is 'Refund of Unregistered Receipt from Person - Void'
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=94751392) **Please note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Refund of Unregistered Receipt from Person - Void a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/60660da8-88e0-4b04-9025-d1962e0208fb)

Contact type is Organization only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/75c78121-1419-4090-8731-ee6344665780)

Verified Purpose of Disbursement is (Optional)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2924d596-32be-445d-b867-32fb1bc9874c)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/91fbbfdd-1785-4e31-a7e9-b642ad5ce2ef)

QA review entered same contact for Refund of Unregistered Receipt from Person - Void (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount. (Note - VOID is a negative value)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/69da5a4d-d341-41eb-80e9-f8a3537da2d9)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/758741ee-a413-4b8b-982a-310332e2807f)

QA Review Completed. Moved to Stage Ready.
