### ISSUE TITLE
Allow user to enter 100% Federal Election Activity Payment on Schedule B (Group O)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#731]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”100% Federal Election Activity Payment”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click(open) on the " Federal Election Activity Expenditures" Accordion link  
**Then** I can enter a transaction with the type “100% Federal Election Activity Payment"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee
*Note - please default to Organization.

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional, will be required if DATE falls outside of report dates)
-	**AMOUNT** (Required, can be a negative)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# CANDIDATE/COMMITTEE INFORMATION 
#

**And** the user will have the OPTION to select a Candidate using the **LOOKUP,** and upon selection the following will be populated:

-	**CANDIDATE ID** (Optional)
-	**LAST NAME** (Required if CANDIDATE ID is populated)
-	**FIRST NAME** (Required if CANDIDATE ID is populated)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# ELECTION INFORMATION 
#
-	**ELECTION CODE** (Required)
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Other)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Required)
	
---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB30B.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 UX Note 

for Election code please show
1. "Election year" dropdown
2. "Election type" Dropdown

 QA Note 

- ENTITY can be Organization, Individual, or Committee, but should default to Organization.
- We are NOT capturing Committee ID for this transaction.
- Note:   Candidate/Committee Information is sentence case
- ![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fbb43226-75d2-4d90-8840-c0608b9ec1aa)

 Dev Note 

- Ensure the required fields have the red outline and text if there is an error (missing).
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=600537496) **Please note this is a consolidated specification.**

 Wireframe 
![731 - 100% Federal Election Activity Payment.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/baa6de49-0487-41ea-8f89-25d24aaa8255)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@mary-tcg @MitchellTCG Can we have a wireframe for this transaction? It's slightly different in that we need a Candidate lookup under Beneficiary information (but _no_ Committee Lookup).

**Comment by mary-tcg** [comment]
@AureliaKhorsand @GreggMoreland @MitchellTCG wire updated

**Comment by WiseQA** [comment]
QA review started returning to In-Progress - Aggregate field is missing from this transaction.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/38a8f4f9-82a1-41bb-9907-f95a133fc82d)

Per wireframe and AC below is the display for "Amount" and "Aggregate" for this transaction.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/440f253e-b246-4c81-92ee-291c2b45d765)

@MitchellTCG @mjtravers returning to In-Progress for adding the  field Aggregate and display should be side by side per wireframe.

**Comment by mjtravers** [comment]
Patch made for missing aggregate field. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select 100% Federal Election Activity Payment transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1722b086-110a-44d8-8461-8defad43484e)

Verified PURPOSE OF DISBURSEMENT (Required) is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ae3a0294-8e84-4a58-a37e-6a933e9295cc)

Verified "Amount" and "Aggregate" are displayed for this transaction. (Verified fix)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c064ea83-2db1-47e8-9d6c-3836ca250914)

Verified Beneficiary Information - Candidate fields populated (These are required fields. Fix to address showing this area required in ticket #1164)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ad86e509-1dac-4a83-8951-2b866c9845a4)

Verified 100% Federal Election Activity Payment transaction is displayed in the "Disbursements" list in the transactions table.

**Comment by GreggMoreland** [comment]
'Beneficiary Information' header should not display here. It should be 'Committee/Candidate Information' shown in wireframe.

Thanks Gregg - still testing this one.  Got a couple errors.

@GreggMoreland can you please update acceptance criteria and make the Committee/Candidate Information case sensitive, if looking at the acceptance criteria is is all in CAPS and may be misconstrued as it should be all CAPS.   Thanks !!

**Comment by WiseQA** [comment]
QA tested twice and when entering an unique Candidate ID (not used before) get the below error.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e1fc5448-37e2-4f90-88bb-5ca2135387a7)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/01e58f3c-e29a-48de-a685-32fe6df80e8a)

Section labeled incorrectly as denoted also in #738.

Change Beneficiary Information label:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dc9f9618-a8be-4ab6-b097-8ec7f91bfdb5)

Correct Label is:  Candidate/Committee Information (case sensitive)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8dc6823b-d66b-47b8-ac8d-0af50290e6d9)

@MitchellTCG @mjtravers sending back to In-Progress for the error fix, and the label fix.

**Comment by dheitzer** [comment]
Issues addressed and ready for re-CR

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review retested and verified label fix was changed from Beneficiary to Committee/Candidate Information

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b8cf0367-04d6-4f92-b50a-ddd55f8cb221)

QA retested the second fix when entering an unique Candidate ID (not used before) the 400 error was fixed, and the transaction is saving correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dd293fd2-ce4f-4d18-8d0a-e67c2184275b)

QA Review Completed.   Moved to Stage Ready.
