### ISSUE TITLE
Allow user to enter Credit Card Payment for 100% Federal Election Activity on Schedule B (Group R)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#732]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Credit Card Payment for 100% Federal Election Activity”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement 
**Then** Click(open) on the " Federal Election Activity Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Credit Card Payment for 100% Federal Election Activity"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE** (Required, includes LOOKUP)
-Organization
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# ELECTION INFORMATION 
#
-	**ELECTION CODE** (Required)
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Convention, Runoff, Special, or Recount)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, system generated)
--Text must read: 'Credit Card: See Below'
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)
	
---
**Then** I will be able to:
- Cancel
- Save & add Memo  (Memo Name: Credit Card Memo for 100% Federal Election Activity)
- Save 
- Edit

**And if** the Aggregate amount is >= $200.01 or negative,
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB30B.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- Under "Save & Add Memo", "Credit Card Memo for 100% Federal Election Activity" will be a dead link. It is a placeholder until we develop the Tier 2 (child) transaction.

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=511051030) **Please note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Credit Card Payment for 100% Federal Election Activity transaction is created and is editable once saved.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Credit Card Payment for 100% Federal Election Activity a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5d033106-d579-4240-8780-6373a2d8a6df)

Verified Election Type (Code) and Election Year are required fields and Election Description (Required if Election Code is Convention, Runoff, Special, or Recount)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9dea83b6-a1e4-478f-8074-b8eb3362e528)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/62d6efbe-9512-4173-ac39-caeea55c9829)

Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed 'Credit Card: See Below'.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/30acaa54-8c47-425b-9eef-b4dd67c1eee4)

Verified "Save & Add Memo" dropdown displays "Credit Card Memo for 100% Federal Election Activity" only.  (**Note this is a dead link until memo is built out in future ticket)**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/228db849-763c-471c-b84a-0452c12af7f5)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c0db8e6b-0f6f-4861-a3e7-106797997228)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/444c3aef-16b7-4ab4-a0af-8776a716fa80)

QA Review Completed.   Moved to Stage Ready.
