### ISSUE TITLE
Allow user to enter Credit Card Memo for 100% Federal Election Activity on Schedule B (Group O)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#733]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Credit Card Memo for 100% Federal Election Activity"** sub-transaction under **”Credit Card Payment for 100% Federal Election Activity”** on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator 
**And** I am editing a Credit Card Payment for 100% Federal Election Activity transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction: 
- Credit Card Memo for 100% Federal Election Activity
**And** I will be required to enter the following information (unless otherwise noted):

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee 
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Required, must be checked)
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

**And** the user will have the OPTION to select a Candidate using the **LOOKUP,** and upon selection the following will be populated:

-	**CANDIDATE ID** (Optional)
-	**LAST NAME** (Required if CANDIDATE ID is populated)
-	**FIRST NAME** (Required if CANDIDATE ID is populated)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# ELECTION INFORMATION 
#
-	**ELECTION CODE** (Required)
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Other)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Save & add memo (Memo Name: Credit Card Memo for 100% Federal Election Activity)
- Cancel
- Save 
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB30B.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note 

- ENTITY can be Organization, Individual, or Committee, but should default to Organization.

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1479097042) **Please note that this is a consolidated specification**

 Wireframe 
![733 - Credit Card Memo for 100Percent Federal Election Activity.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/50c7f261-0483-435f-80e7-5aaac6120f15)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
Wireframes attached
I have some questions about a few fields

**Comment by mjtravers** [comment]
From CR: I am seeing the CANDIDATE OFFICE, CANDIDATE STATE, and CANDIDATE DISTRICT fields on the form but don't see them listed in either the acceptance criteria or in the validation schema for DISBURSEMENT_MEMOS_FEA. Sending back to In Progress to see if those fields are needed or not for this transaction type.

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers comments above state wireframe attached, but not seeing a wireframe ?

**Comment by mjtravers** [comment]
@AureliaKhorsand confirmed that CANDIDATE OFFICE, CANDIDATE STATE, and CANDIDATE DISTRICT should not be part of this transaction type and displayed on the form.

**Comment by mary-tcg** [comment]
@AureliaKhorsand @GreggMoreland @MitchellTCG wire added

**Comment by dheitzer** [comment]
Changes made and pushed back for CR

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Prerequisite a Credit Card Payment for 100% Federal Election Activity transaction to be created, saved in the "Transactions" table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9ab508d9-a8d1-41e7-836f-ceb57c94642d)

Select the + Save & add memo button. Verify dropdown list is displayed. Then select Credit Card Memo for 100% Federal Election Activity from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d5644b9d-9599-46b1-84bf-39f3eb484935)

Verify Credit Card Memo for 100% Federal Election Activity page is displayed and contact type is defaulted to "Organization"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/662ae3c6-7846-4cb0-b876-6ff78e234147)

Verified Amount and Aggregate fields displayed correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/baa5bddf-c788-42e4-a56b-af7e459f0fb2)

Verified PURPOSE OF DISBURSEMENT (REQUIRED) is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e845c071-361e-4a24-90fd-0d35316ce73b)

Verified Credit Card Memo for 100% Federal Election Activity transaction is displayed in Disbursements in the transaction table and associated with ID verified.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c681789e-df21-49f1-bb9b-a50a73957608)

QA Review Completed. Moved to Stage Ready.
