### ISSUE TITLE
Allow user to enter Staff Reimbursement for 100% Federal Election Activity on Schedule B (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#734]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Staff Reimbursement for 100% Federal Election Activity”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click(open) on the " Federal Election Activity Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Staff Reimbursement for 100% Federal Election Activity"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
-Individual Only

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional, will be required if DATE falls outside of report dates)
-	**AMOUNT** (Required, can be a negative)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, System generated)
--Text must read: "Reimbursement: See Below"
-	**NOTE OR MEMO TEXT** (Optional)	
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save & Add Memo (Memo Name: Staff Reimbursement Memo for 100% Federal Election Activity)
- Save
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB30B.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- Under "Save & Add Memo", "Staff Reimbursement Memo for 100% Federal Election Activity" will be a dead link. It is a placeholder until we develop the Tier 2 (child) transaction.

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1158706041)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Staff Reimbursement for 100% Federal Election Activity transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b9e89d8d-18dd-49a1-a11c-35b70fac78d7)

Contact type is Individual Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b7757365-b7e3-4aa9-898e-a2b099c1f246)

Verified "Aggregate" field is displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f90e7649-eb42-4cef-9e3f-d8c9f67baa18)

Verified PURPOSE OF DISBURSEMENT (SYSTEM-GENERATED) is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c4131063-263a-4417-b077-b0e8cfd048a4)

Verified "Save & add memo" button is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1fde0407-9a2c-497d-900f-3d853889dd3a)

@MitchellTCG @mjtravers the Amount and Aggregate fields should be displayed side by side, these are showing Aggregate is displayed below Amount.  Returning to In-Progress for fix of displaying these fields.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/87854d61-8036-4949-aee9-f14833fa724f)

Verified Staff Reimbursement for 100% Federal Election Activity transaction is displayed in Disbursements in the transaction table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/02e4f56d-4392-4699-bd31-6cbb1cf598d5)

**Comment by WiseQA** [comment]
Amount and Aggregate fields in previous transactions displayed as the following:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8f561be9-88d4-4dff-a306-622dbd492b74)

This transaction is displaying the Amount and Aggregate fields are above and below each other.  Returning to In-Progress for fix of displaying these fields.  (Note no Wireframe within this ticket showing the display for Amount and Aggregate - however #735 has wireframe which is the memo ticket)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/87854d61-8036-4949-aee9-f14833fa724f)

Returning to In-Progress for layout fix.

**Comment by mjtravers** [comment]
Patch made for aggregate field below amount field. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified fix for the amount and aggregate fields displaying correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b345af9d-5f89-4955-82e8-f277682744ef)

Verified + Save & add memo dropdown displays Staff Reimbursement Memo for 100% Federal Election Activity

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8c563f33-6c71-4c95-9649-601c1fcef599)

Verified Staff Reimbursement for 100% Federal Election Activity transaction is displayed in Disbursements in the transaction table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4584e767-2507-42eb-82ad-385c87e4d814)

QA Review Completed.   Moved to Stage Ready.
