### ISSUE TITLE
Allow user to enter Staff Reimbursement Memo for 100% Federal Election Activity on Schedule B (Group S)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#735]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Staff Reimbursement Memo for 100% Federal Election Activity”** sub-transaction under **”Staff Reimbursement for 100% Federal Election Activity”** on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator 
**And** I am editing a Staff Reimbursement for 100% Federal Election Activity transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction: 
- Staff Reimbursement Memo for 100% Federal Election Activity

**And** I will be required to enter the following information (unless otherwise noted):

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee 
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Required, must be checked)
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# ELECTION INFORMATION 
#
-	**ELECTION CODE** (Required)
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Other)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Save & add memo  (Memo Name: Staff Reimbursement Memo for 100% Federal Election Activity)
- Cancel
- Save
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file onl line SB30B.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note 

- ENTITY can be Organization, Individual, or Committee, but should default to Organization.

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1479097042) **Please note that this is a consolidated specification**

 Wireframes 

![735 - Staff Reimbursement Memo for 100percent Federal Election Activity.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/9a424c91-8626-405c-9c47-1f1eb7c1a150)

# Save and add a memo dropdown 
#
![735 - One Option .png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/5bdbbfd8-2d51-4151-9170-967662f1b284)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Is this the right direction?

**Comment by dheitzer** [comment]
I believe `COMMITTEE ID (Required)` should be removed from this ticket as it is not in the spec or the Group O.  @AureliaKhorsand @GreggMoreland  can either of you confirm? Thanks!

**Comment by AureliaKhorsand** [comment]
@dheitzer That is correct, it's been removed. Thank you!

**Comment by mjtravers** [comment]
From CR, this transaction type is going to move to Group S. Sending back to In Progress.

**Comment by dheitzer** [comment]
CR fixes made and re-review requested.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Prerequisite a Staff Reimbursement for 100% Federal Election Activity transaction to be created, saved in the "Transactions" table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a299aecf-fb0d-453c-839b-0291258c78d6)

Select the + Save & add memo button. Verify dropdown list is displayed. Then select Staff Reimbursement Memo for 100% Federal Election Activity from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/10251c97-842a-491a-9134-ea1e6c1b344a)

Verify Staff Reimbursement Memo for 100% Federal Election Activity page is displayed and contact type is defaulted to "Organization"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/902be3b7-f216-4d7e-af26-85cba1007720)

This transaction is displaying the Amount and Aggregate fields are above and below each other. Returning to In-Progress for fix of displaying these fields. (See wireframe above - same fix as #734)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5d30303e-a6d8-4cdb-82d9-b84fad6745be)

Amount and Aggregate fields should be displayed as the following:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/446affb0-44cb-4c59-95c5-36e5e00c1bc4)

@MitchellTCG @mjtravers Returned to In-Progress for fix.

**Comment by mjtravers** [comment]
Patch made for aggregate field below amount field. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified fix for the amount and aggregate fields displaying correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cd2e0c50-3337-4a8e-925d-48e982f50e0b)

Verified Staff Reimbursement Memo for 100% Federal Election Activity transaction is displayed in Disbursements in the transaction table and associated with ID verified.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e2bfabaa-80de-4570-af3b-313fff07264f)

QA Review Completed.  Moved to Stage Ready.
