### ISSUE TITLE
Allow user to enter Payment to Payroll for 100% Federal Election Activity on Schedule B (Group R)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#736]
Business Reason

As a Committee Administrator, I will be able to enter a ***”Payment to Payroll for 100% Federal Election Activity Payment”*** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

  ***Then*** Add a disbursement

  ***Then*** Click(open) on the " Federal Election Activity Expenditures" Accordion link 

  ***Then*** I can enter a transaction with the type “Payment to Payroll for 100% Federal Election Activity Payment"

  ***Then*** I will be required to enter the following information (unless otherwise noted):

—

Contact 

  #

*   ***CONTACT TYPE*** (Required, includes LOOKUP)

       -Organization
*   ***ORGANIZATION NAME*** (Required)

1.  Address

       #

*   ***STREET ADDRESS*** (Required)
*   ***APARTMENT, SUITE, ETC.*** (Optional)
*   ***CITY*** (Required)
*   ***STATE/PROVINCE*** (Required)
*   ***ZIP/POSTAL CODE*** (Required)

1.  Expenditure Information

       #

*   ***DATE*** (Required)
*   ***MEMO ITEM*** (Optional)
*   ***AMOUNT*** (Required, can be negative)
*   ***AGGREGATE*** (Required) 
      *   Amount Displayed will be the total of contributions that are: 
            *   From the person (ENTITY)
    *   within Aggregation Group of "GENERAL_DISBURSEMENT" 
            *   _from_ January 1 of report year _to_ the Contribution Date* of the transaction.
        *   *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

1.  ELECTION INFORMATION

       #

*   ***ELECTION CODE*** (Required)
*   ***ELECTION YEAR*** (Required)
*   ***ELECTION DESCRIPTION*** (Required if Election Code is Convention, Runoff, Special, or Recount)

1.  Additional information

       #

*   ***PURPOSE OF DISBURSEMENT*** (Required, system generated)

       --Text should read: "Payroll: See Below"
*   ***NOTE OR MEMO TEXT*** (Optional)
*   ***CATEGORY CODE*** (Optional)

—

  ***Then*** I will be able to:

*   Cancel
*   Save & Add Memo (Memo Name: Payment to Payroll Memo for 100% Federal Election Activity)
*   Save
*   Edit

***And if*** the Aggregate amount is >= $200.01 or negative,

  ***Then*** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB30B.

***If*** the Aggregate amount is [x] Update schema to match [Spec Updates spreadsheet tab here]( [https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=511051030](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=511051030)) ***Please note this is a consolidated specification.***

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-906](https://fecgov.atlassian.net/browse/FECFILE-906)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Payment to Payroll for 100% Federal Election Activity Payment a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/726fc304-03a4-46ba-8c7e-14be87961797)

Verified Election Type (Code) and Election Year are required fields and Election Description (Required if Election Code is Convention, Runoff, Special, or Recount)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9421b1f8-b8ca-4aa6-b32b-19319782ff10)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/547c7b89-0a21-4039-8eaa-b878027ee613)

Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed 'Payroll: See Below'.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0b10a336-7e36-4523-ac3c-fb83fe94cddc)

Verified "Save & Add Memo" dropdown displays "Payment to Payroll Memo for 100% Federal Election Activity" only. **(Note this is a dead link until memo is built out in future ticket)**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4a250914-8106-4eec-b1e0-d96af18efa6f)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f9a0945d-4beb-4201-a97c-c6035a5689dc)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/12493165-7c26-4565-b660-287ca350e300)

QA Review Completed. Moved to Stage Ready.
