### ISSUE TITLE
Allow user to enter Payroll Memo for 100% Federal Election Activity on Schedule B (Group S)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#737]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Payroll Memo for 100% Federal Election Activity”** sub-transaction under **”Payment to Payroll for 100% Federal Election Activity”** on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator 
**And** I am editing a Payment to Payroll for 100% Federal Election Activity transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction: 
- Payroll Memo for 100% Federal Election Activity
**And** I will be required to enter the following information (unless otherwise noted):

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Individual, Organization, Committee 
*Note - please default to Individual.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Required, must be checked)
-	**AMOUNT** (Required, can be negative amount)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# ELECTION INFORMATION 
#
-	**ELECTION CODE** (Required)
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Other)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Save & add memo  (Memo Name: Payroll Memo for 100% Federal Election Activity)
- Cancel
- Save 
- Edit

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB30B.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- ENTITY can be Individual, Organization, or Committee, but should default to Individual.

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1479097042) **Please note that this is a consolidated specification**

 Wireframes 

![737 - Payroll Memo for 100Percent Federal Election Activity – 1.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/e4a1d50b-90ad-42bc-a1bd-0c7adffc6128)

# Save and add a memo dropdown 
#
![737 - One Option.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/3fc0b17f-7187-462d-bca2-844719ad23dc)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Wires attached

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Prerequisite a Payment to Payroll for 100% Federal Election Activity transaction to be created, saved in the "Transactions" table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/463a18e7-b92c-4bf8-abae-f3baa2428713)

Select the + Save & add memo button. Verify dropdown list is displayed. Then select Payroll Memo for 100% Federal Election Activity from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d276fd43-c86b-47c9-83e4-7fdd048b3817)

Verify Payroll Memo for 100% Federal Election Activity page is displayed and contact type is defaulted to "Individual"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8300dc59-3e40-4d8d-9812-370a53daa3b6)

Verified Amount and Aggregate fields displayed correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e179b643-804d-40e1-b0e2-d73a8fbe7450)

Verified PURPOSE OF DISBURSEMENT (REQUIRED) is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8f76b9a5-8b45-4791-87e2-04dd16695098)

Verified Payroll Memo for 100% Federal Election Activity transaction is displayed in Disbursements in the transaction table and associated with ID verified.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/65dc32b9-c223-4bb0-9748-5e89e423edb3)

QA Review Completed.   Moved to Stage Ready.
