### ISSUE TITLE
Allow user to enter Void of 100% Federal Election Activity on Schedule B (Group O)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#738]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Void of 100% Federal Election Activity Payment”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click(open) on the " Federal Election Activity Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Void of 100% Federal Election Activity Payment"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual, Committee 
*Note - please default to Organization.

---
_if CONTACT TYPE = Committee_
-	**COMMITTEE NAME** (Required)
*Note - Committee ID not needed for this transaction

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional, will be required if DATE falls outside of report dates)
-	**AMOUNT** (Required)
**Note: System will automatically make the amount negative. AMOUNT MUST be a non-zero negative value to save, and max value is -$0.01. If amount exceeds that, then display error message 'Amount must be negative (example: -$20.00)'**
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL_DISBURSEMENT"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# CANDIDATE/COMMITTEE INFORMATION 
#

**And** the user will have the OPTION to select a Candidate using the **LOOKUP,** and upon selection the following will be populated:

-	**CANDIDATE ID** (Optional)
-	**LAST NAME** (Required if CANDIDATE ID is populated)
-	**FIRST NAME** (Required if CANDIDATE ID is populated)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# ELECTION INFORMATION 
#
-	**ELECTION CODE** (Required)
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Other)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required)
**Note: This field is REQUIRED but editable by the user. The User must enter information here to save. If the field is not populated, red error message "This is a required field."**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Required)
		
---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And**  the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB30B.

 QA Note
- ENTITY can be Organization, Individual, or Committee, but should default to Organization.
- Note:   Candidate/Committee Information is sentence case
- ![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fbb43226-75d2-4d90-8840-c0608b9ec1aa)

 Dev Note 

- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=600537496) **Please note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by WiseQA** [comment]
QA review started returning to In-Progress - Aggregate field is missing from this transaction.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5c70713b-3caf-43e9-b098-6dec7fe95df2)

Per AC "Amount" and "Aggregate" both are displayed for this transaction.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d0b1529c-822b-48bb-babb-305e333d4877)

@MitchellTCG @mjtravers returning to In-Progress for adding the field Aggregate and display should be side by side per previous wireframes.

**Comment by mjtravers** [comment]
Patch made for missing aggregate field. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Void of 100% Federal Election Activity Payment transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9f0b82d9-c368-465e-9b50-5be01c463829)

Verified PURPOSE OF DISBURSEMENT (Required) is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/28adc873-bd73-4adf-9506-0c2a0dfc4199)

Verified "Amount" and "Aggregate" are displayed for this transaction. (Verified fix)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f6936cb6-2c7c-4722-b0ec-c68ca2e1cd9a)

Verified Beneficiary Information - Candidate fields populated (These are required fields.   Fix to address showing this area required in ticket #1164)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/af1c3a37-44f0-4aff-bcd4-c710f7089779)

Verified Void of 100% Federal Election Activity Payment  transaction is displayed in the "Disbursements" list in the transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/872fae44-255b-490e-b537-a98142388e4e)

QA Review Completed. Moved to Stage Ready.

**Comment by WiseQA** [comment]
Section labeled incorrectly, this error found after QA moved to Stage Ready.

Change Beneficiary Information label:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dc9f9618-a8be-4ab6-b097-8ec7f91bfdb5)

Correct Label is:  Candidate/Committee Information (sentence case)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8dc6823b-d66b-47b8-ac8d-0af50290e6d9)

@MitchellTCG @mjtravers pulled from Stage Ready and sent back to In-Progress for this fix.

**Comment by dheitzer** [comment]
Issues addressed and ready for re-CR

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review retested and verified label fix was changed from Beneficiary to Committee/Candidate Information

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b8cf0367-04d6-4f92-b50a-ddd55f8cb221)

QA Review Completed.   Moved to Stage Ready.

**Comment by WiseQA** [comment]
QA review retested and verified label fix was changed from Beneficiary to Committee/Candidate Information

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b8cf0367-04d6-4f92-b50a-ddd55f8cb221)

QA Review Completed.   Moved to Stage Ready.
