### ISSUE TITLE
Allow system to create In-kind Out on Schedule B (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#739]
Business Reason

As a Committee Administrator, I will be able to view an ***In-kind Out*** transaction on Schedule B of a Form 3x report when an ***In-kind Receipt*** Transaction on Schedule A of a Form 3x report is saved, so that I can accurately report on my committee's transactions.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

 ***If*** an ***"In-kind Receipt"*** (Schedule A) transaction is saved

 ***Then*** an ***In-kind Out*** (Schedule B) transaction will be created with the following information as read-only unless otherwise indicated (users can edit through the transaction on Schedule A):

—

Contact

 #

*   ***CONTACT TYPE***

      -Individual Only

*   ***LAST NAME*** (Required, auto-generated from associated IN_KIND_RECEIPT)
*   ***FIRST NAME*** (Required, auto-generated from associated IN_KIND_RECEIPT)
*   ***MIDDLE NAME*** (Optional, auto-generated from associated IN_KIND_RECEIPT)
*   ***PREFIX*** (Optional, auto-generated from associated IN_KIND_RECEIPT)
*   ***SUFFIX*** (Optional, auto-generated from associated IN_KIND_RECEIPT)

1.  Address

      #

*   ***STREET ADDRESS*** (Required, auto-generated from associated IN_KIND_RECEIPT)
*   ***APARTMENT, SUITE, ETC.*** (Optional, auto-generated from associated IN_KIND_RECEIPT)
*   ***CITY*** (Required, auto-generated from associated IN_KIND_RECEIPT)
*   ***STATE/PROVINCE*** (Required, auto-generated from associated IN_KIND_RECEIPT)
*   ***ZIP/POSTAL CODE*** (Required, auto-generated from associated IN_KIND_RECEIPT)

1.  Expenditure Information

      #

*   ***DATE*** (Required, auto-generated from associated IN_KIND_RECEIPT)
*   ***MEMO ITEM*** (auto-generated from associated IN_KIND_RECEIPT)
*   ***AMOUNT*** (Required, auto-generated from associated IN_KIND_RECEIPT)
*   AGGREGATE (Required)
      *   Amount Displayed will be the total of contributions that are:
            *   From the person (ENTITY)
    *   within Aggregation Group of "GENERAL_DISBURSEMENT"
            *   _from_ January 1 of report year _to_ the Contribution Date* of the transaction.
        *   *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

1.  Additional information

      #

*   ***PURPOSE OF DISBURSEMENT*** (Required, System generated)

      --Text is Auto-generated from associated IN_KIND_RECEIPT
*   ***NOTE OR MEMO TEXT*** (Optional)
*   ***CATEGORY CODE*** (Optional)

—

 ***Then*** I will be able to:

*   Cancel
*   Save both transactions
*   Edit

***And if*** the Aggregate amount is >= $200.01,

 ***Then*** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB21B.

***If*** the Aggregate amount is [x] Update schema to match [Spec Updates spreadsheet tab here]( [https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=926727850](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=926727850))
*   [x] Second accordion text: "AUTO-POPULATED: Review disbursement information"

Wireframe

![739 - In-kind out.png]([https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/805974fe-e3ed-4b96-adfb-4d0381437d9d](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/805974fe-e3ed-4b96-adfb-4d0381437d9d))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-903](https://fecgov.atlassian.net/browse/FECFILE-903)

**Comment by JonellaCulmer** [comment]
Perhaps there's some flexibility with the name "In-Kind Out" and we can find the space to think through some alternatives.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
Wires added and DEV NOTES updated

cc'd:
@mary @JonellaCulmer

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg chatted with Matt - can you add Category Code and Aggregate to the wireframe, and make sure the K is lowercase?

**Comment by mary-tcg** [comment]
@AureliaKhorsand @MitchellTCG @GreggMoreland @mjtravers @WiseQA wireframe updated to match AC

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Pre-requisite a "In-kind Receipt" transaction is created and displayed in the Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b4f33d1c-5d87-4f74-8883-4ba3f7c67f15)

From the "In-kind Receipt" transactions page select the ">AUTO-POPULATED: Review disbursement information" link.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/25186097-f5aa-4d51-808e-ea8d6075e0b4)

Verified the "In-kind Out" disbursement transaction is displayed.   Fields are displayed as "Read-only"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8dfa57de-92f6-4f16-8612-73974a34c38a)

Verified the "In-kind out" is auto-populated and displayed in the Transactions table as a disbursement.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9b376a49-dd19-4e58-8465-bc7990a9af13)

**Comment by WiseQA** [comment]
Pre-requisite a "In-kind Receipt" transaction is created and displayed in the Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4c8ec29c-8783-4861-8da7-e4ec96e42ae5)

From the "In-kind Receipt" transactions page select the ">AUTO-POPULATED: Review disbursement information" link.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b8824b32-b726-4883-8e31-f4a59cb01a21)

Verified the "In-kind Out" disbursement transaction is displayed. Fields are displayed as "Read-only" (with exception of "Note or Memo Text (Optional) and Category Code (Optional).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/aa5b4929-2be5-424a-9ca3-5f9322459ed7)

Verified the "In-kind out" is auto-populated and displayed in the Transactions table as a disbursement. Verified the Transaction ID and Associated With is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/425be47e-53c0-43f5-861d-96120eef4048)

QA Review Completed. Moved to Stage Ready.
