### ISSUE TITLE
Testing template

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-app#74]
### Business Reason ### 

As a [role], I will be able to [blank] so that I can [business reason]

### Acceptance Criteria ### 

**If** [precedent]
**When** [action]
**Then** [result]

**Comment by lbeaufort** [comment]
@AureliaKhorsand is this how you wanted the template to look?

**Comment by AureliaKhorsand** [comment]
@lbeaufort yes this looks good. Closing this as a test issue.
