### ISSUE TITLE
Allow user to enter Party In-kind Out on Schedule B (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#740]
Business Reason

As a Committee Administrator, I will be able to view an ***Party In-kind Out*** transaction on Schedule B of a Form 3x report when an ***Party In-kind*** Transaction on Schedule A of a Form 3x report is saved, so that I can accurately report on my committee's transactions.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

 ***If*** an ***"Party In-kind Receipt"*** (Schedule A) transaction is saved

 ***Then*** an ***Party In-kind Out*** (Schedule B) transaction will be created with the following information as read-only (users can edit through the transaction on Schedule A):

—

Contact

 #

*   ***CONTACT TYPE***
      *   Committee Only
*   ***COMMITTEE NAME*** (Required)
*   ***COMMITTEE ID*** (Required)

1.  Address

      #

*   ***STREET ADDRESS*** (Required, auto-generated from associated PARTY_IN_KIND_RECEIPT)
*   ***APARTMENT, SUITE, ETC.*** (Optional, auto-generated from associated PARTY_IN_KIND_RECEIPT)
*   ***CITY*** (Required, auto-generated from associated PARTY_IN_KIND_RECEIPT)
*   ***STATE/PROVINCE*** (Required, auto-generated from associated PARTY_IN_KIND_RECEIPT)
*   ***ZIP/POSTAL CODE*** (Required, auto-generated from associated PARTY_IN_KIND_RECEIPT)

1.  Expenditure Information

      #

*   ***DATE*** (Required, auto-generated from associated PARTY_IN_KIND_RECEIPT)
*   ***MEMO ITEM*** (auto-generated from associated PARTY_IN_KIND_RECEIPT)
*   ***AMOUNT*** (Required, auto-generated from associated PARTY_IN_KIND_RECEIPT)
*   Note: There is _no_ aggregate field, but must be included in aggregation group "GENERAL_DISBURSEMENT"

1.  Additional information

      #

*   ***PURPOSE OF DISBURSEMENT*** (Required, System generated)

      --Text is Auto-generated from associated PARTY_IN_KIND_RECEIPT
*   ***NOTE OR MEMO TEXT*** (Optional)
*   ***CATEGORY CODE*** (Optional)

—

 ***Then*** I will be able to:

*   Cancel
*   Save both transactions

***And*** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB21B

 ***And*** users will be able to access the two-part transaction either in the Receipts section (Party In-Kind Receipt) or the Disbursements section (Party In-Kind Out).

QA Note

*   Note: There is _no_ aggregate field, but must be included in aggregation group "GENERAL_DISBURSEMENT"
*   Please note that the Memo Text and Category Code fields are editable.
*   Once saved, the user will be able to access the two-part transaction either in the Receipts section (Party In-kind Receipt) or the Disbursements section (Party In-kind Out). This is similar to how the user can click either Earmark Receipt or Earmark Memo to open the two-part transaction page.

DEV Note

*   BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the Party In-kind Receipt transaction. This is required.
*   BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the Party In-kind Receipt transaction. This is required.
*   [x] Update schema to match [Spec Updates spreadsheet tab here]( [https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1371282424](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1371282424)) ***This is a consolidated specification***

Wireframe

 ![740 - Party In-Kind Out.png]([https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/080f70bd-3fd7-44d1-9706-a43940e434b0](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/080f70bd-3fd7-44d1-9706-a43940e434b0))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-902](https://fecgov.atlassian.net/browse/FECFILE-902)

**Comment by MitchellTCG** [comment]
@mary-tcg 
Please add the wire to this ticket

**Comment by mary-tcg** [comment]
@MitchellTCG @AureliaKhorsand @GreggMoreland wire added

**Comment by WiseQA** [comment]
Pre-requisite a "Party In-kind Receipt" transaction is created and displayed in the Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/365dc0b3-f15f-46cc-8088-6ee3db8a611d)

From the "Party In-kind Receipt" transactions page select the ">AUTO-POPULATED: Review disbursement information" link.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b7f88118-ad2f-4492-9c1e-a3ea250d1a4b)

Verified the "Party In-kind Out" disbursement transaction is displayed. Fields are displayed as "Read-only" (with exception of "Note or Memo Text (Optional) and Category Code (Optional).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c0eeaab6-8978-4fd2-8acf-f43805f9d50c)

Verified the "Party In-kind out" is auto-populated and displayed in the Transactions table as a disbursement.  Verified the Transaction ID and Associated With is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ede6ce03-28b6-46db-8680-615c6f58ca2b)

QA Review Completed.  Moved to Stage Ready.
