### ISSUE TITLE
Allow user to enter PAC In-kind Out on Schedule B (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#741]
Business Reason

As a Committee Administrator, I will be able to view an ***PAC In-kind Out*** transaction on Schedule B of a Form 3x report when an ***PAC In-kind*** Transaction on Schedule A of a Form 3x report is saved, so that I can accurately report on my committee's transactions.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

 ***If*** an ***"PAC In-kind Receipt"*** (Schedule A) transaction is saved

 ***Then*** an ***PAC In-kind Out*** (Schedule B) transaction will be created with the following information as read-only (users can edit through the transaction on Schedule A):

—

Contact

 #

*   ***CONTACT TYPE***
      *   Committee Only
*   ***COMMITTEE NAME*** (Required)
*   ***COMMITTEE ID*** (Required)

1.  Address

      #

*   ***STREET ADDRESS*** (Required, auto-generated from associated PAC_IN_KIND_RECEIPT)
*   ***APARTMENT, SUITE, ETC.*** (Optional, auto-generated from associated PAC_IN_KIND_RECEIPT)
*   ***CITY*** (Required, auto-generated from associated PAC_IN_KIND_RECEIPT)
*   ***STATE/PROVINCE*** (Required, auto-generated from associated PAC_IN_KIND_RECEIPT)
*   ***ZIP/POSTAL CODE*** (Required, auto-generated from associated PAC_IN_KIND_RECEIPT)

1.  Expenditure Information

      #

*   ***DATE*** (Required, auto-generated from associated PAC_IN_KIND_RECEIPT)
*   ***MEMO ITEM*** (auto-generated from associated PAC_IN_KIND_RECEIPT)
*   ***AMOUNT*** (Required, auto-generated from associated PAC_IN_KIND_RECEIPT)
*   Note: There is _no_ aggregate field, but must be included in aggregation group "GENERAL_DISBURSEMENT"

1.  Additional information

      #

*   ***PURPOSE OF DISBURSEMENT*** (Required, System generated)

      --Text is Auto-generated from associated PAC_IN_KIND
*   ***NOTE OR MEMO TEXT*** (Optional)
*   ***CATEGORY CODE*** (Optional)

—

 ***Then*** I will be able to:

*   Cancel
*   Save both transactions

***And*** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB21B

 ***And*** users will be able to access the two-part transaction either in the Receipts section (PAC In-Kind Receipt) or the Disbursements section (PAC In-Kind Out).

QA Note

*   Note: There is _no_ aggregate field, but must be included in aggregation group "GENERAL_DISBURSEMENT"
*   Please note that the Memo Text and Category Code fields are editable.
*   Once saved, the user will be able to access the two-part transaction either in the Receipts section (PAC In-kind Receipt) or the Disbursements section (PAC In-kind Out). This is similar to how the user can click either Earmark Receipt or Earmark Memo to open the two-part transaction page.

DEV Note

*   BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the PAC In-kind transaction. This is required.
*   BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the PAC In-kind transaction. This is required.
*   [x] Update schema to match [Spec Updates spreadsheet tab here]( [https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1371282424](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1371282424)) ***This is a consolidated specification***

Wireframe

 ![741 - PAC In-Kind Out.png]([https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/30d334f8-8449-4045-aeb9-42f38a0191df](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/30d334f8-8449-4045-aeb9-42f38a0191df))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-901](https://fecgov.atlassian.net/browse/FECFILE-901)

**Comment by MitchellTCG** [comment]
@mary-tcg 
Please add the wire to this ticket

**Comment by mary-tcg** [comment]
@MitchellTCG @AureliaKhorsand @GreggMoreland wire added

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/0d627da2-a0f5-4b56-bb1b-9e33ca49496a)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Pre-requisite a "PAC In-kind Receipt" transaction is created and displayed in the Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/51032c79-3744-401d-8297-b84411040f5b)

From the "PAC In-kind Receipt" transactions page select the ">AUTO-POPULATED: Review disbursement information" link.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b77857ca-4575-433e-a3f1-2717738608b9)

Verified the "PAC In-kind Out" disbursement transaction is displayed. Fields are displayed as "Read-only" (with exception of "Note or Memo Text (Optional) and Category Code (Optional).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8355ce46-baad-4f48-8f45-680bb542f571)

Verified the "PAC In-kind out" is auto-populated and displayed in the Transactions table as a disbursement. Verified the Transaction ID and Associated With is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9b5fc47c-d78c-4539-9387-a64977b74a0e)

QA Review Completed. Moved to Stage Ready.
