### ISSUE TITLE
Allow user to enter In-kind Transfer Out on Schedule B (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#742]
Business Reason 
 

As a Committee Administrator, I will be able to view an **In-kind Transfer Out** transaction on Schedule B of a Form 3x report when an **In-kind Transfer** Transaction on Schedule A of a Form 3x report is saved, so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**If** an **"In-kind Transfer"** (Schedule A) transaction is saved
**Then**  an **In-kind Transfer Out**  (Schedule B) transaction will be created with the following information as read-only (users can edit through the transaction on Schedule A):

---

 Contact 
#
-	**CONTACT TYPE**
-- Committee Only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required, auto-generated from associated IN_KIND_TRANSFER)
-	**APARTMENT, SUITE, ETC.** (Optional, auto-generated from associated IN_KIND_TRANSFER)
-	**CITY** (Required, auto-generated from associated IN_KIND_TRANSFER)
-	**STATE/PROVINCE** (Required, auto-generated from associated IN_KIND_TRANSFER)
-	**ZIP/POSTAL CODE** (Required, auto-generated from associated IN_KIND_TRANSFER)

# Expenditure Information 
#
-	**DATE** (Required, auto-generated from associated IN_KIND_TRANSFER)
-	**MEMO ITEM** (auto-generated from associated IN_KIND_TRANSFER)
-	**AMOUNT** (Required, auto-generated from associated IN_KIND_TRANSFER)
- Note: There is _no_ aggregate field, but must be included in aggregation group "GENERAL_DISBURSEMENT"

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, System generated)
--Text is Auto-generated from associated IN_KIND_TRANSFER 
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save both transactions

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB21B
**And** users will be able to access the two-part transaction either in the Receipts section (In-kind Transfer) or the Disbursements section (In-kind Transfer Out).

 QA Note 

- Note: There is _no_ aggregate field, but must be included in aggregation group "GENERAL_DISBURSEMENT"
- Please note that the Memo Text and Category Code fields are editable.
- Once saved, the user will be able to access the two-part transaction either in the Receipts section (In-kind Transfer) or the Disbursements section (In-kind Transfer Out). This is similar to how the user can click either Earmark Receipt or Earmark Memo to open the two-part transaction page.

 DEV Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the In-kind Transfer transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the In-kind Transfer transaction. This is required.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1371282424) **This is a consolidated specification**

 Wireframe 
![742 - In-Kind Transfer Out.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/e40e8b7a-826c-4e72-879e-73759aa44e3a)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@mary-tcg 
Please add the wire to this ticket

**Comment by mary-tcg** [comment]
@MitchellTCG @AureliaKhorsand @GreggMoreland wire added

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/ada1d13d-6562-4e3d-ba5a-6c866a55db21)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Pre-requisite a "In-kind Transfer" transaction is created and displayed in the Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/52b4c12d-3ac5-47c4-af30-8d6f8dfdf5eb)

From the "In-kind Transfer" transactions page select the ">AUTO-POPULATED: Review disbursement information" link.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b322f7a2-c344-4569-ad8b-a786c8b8f324)

Verified the "In-kind Transfer Out" disbursement transaction is displayed. Fields are displayed as "Read-only" (with exception of "Note or Memo Text (Optional) and Category Code (Optional).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3f1fdd5c-60c7-4df4-be3f-7a3365ca3bf3)

Verified the "In-kind Transfer out" is auto-populated and displayed in the Transactions table as a disbursement. Verified the Transaction ID and Associated With is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/30052945-d0f2-4462-9185-61850fb606a8)

QA Review Completed. Moved to Stage Ready.
