### ISSUE TITLE
Allow user to enter In-kind Transfer - Federal Election Activity Out on Schedule B (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#743]
Business Reason 
 

As a Committee Administrator, I will be able to view an **In-kind Transfer - Federal Election Activity Out** transaction on Schedule B of a Form 3x report when an **In-kind Transfer - Federal Election Activity** Transaction on Schedule A of a Form 3x report is saved, so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**If** an **"In-kind Transfer - Federal Election Activity"** (Schedule A) transaction is saved
**Then**  an **In-kind Transfer - Federal Election Activity Out**  (Schedule B) transaction will be created with the following information as read-only (users can edit through the transaction on Schedule A):

---

 Contact 
#
-	**CONTACT TYPE**
-- Committee Only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required, auto-generated from associated IN_KIND_TRANSFER_FEA)
-	**APARTMENT, SUITE, ETC.** (Optional, auto-generated from associated IN_KIND_TRANSFER_FEA)
-	**CITY** (Required, auto-generated from associated IN_KIND_TRANSFER_FEA)
-	**STATE/PROVINCE** (Required, auto-generated from associated IN_KIND_TRANSFER_FEA)
-	**ZIP/POSTAL CODE** (Required, auto-generated from associated IN_KIND_TRANSFER_FEA)

# Expenditure Information 
#
-	**DATE** (Required, auto-generated from associated IN_KIND_TRANSFER_FEA)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, auto-generated from associated IN_KIND_TRANSFER_FEA)
- Note: There is _no_ aggregate field, but must be included in aggregation group "GENERAL_DISBURSEMENT"

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, System generated)
--Text is Auto-generated from associated IN_KIND_TRANSFER_FEA
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save both transactions

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB30B
**And** users will be able to access the two-part transaction either in the Receipts section (In-kind Transfer - Federal Election Activity) or the Disbursements section (In-kind Transfer - Federal Election Activity Out).

 QA Note 

- Note: There is _no_ aggregate field, but must be included in aggregation group "GENERAL_DISBURSEMENT"
- Please note that the Memo Text and Category Code fields are editable.
- Once saved, the user will be able to access the two-part transaction either in the Receipts section (In-kind Transfer - Federal Election Activity) or the Disbursements section (In-kind Transfer - Federal Election Activity Out). This is similar to how the user can click either Earmark Receipt or Earmark Memo to open the two-part transaction page.

 DEV Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the In-kind Transfer Federal Election Activity transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the In-kind Transfer Federal Election Activity transaction. This is required.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1371282424) **This is a consolidated specification**

 Wireframe 
![743 - In-Kind Transfer - Federal Election Activity Out.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/a120f2bc-1df0-4d20-b4e5-1a65a41c4f91)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@mary-tcg 
Please add the wire to this ticket

**Comment by mary-tcg** [comment]
@MitchellTCG @AureliaKhorsand @GreggMoreland wire added

**Comment by mary-tcg** [comment]
@AureliaKhorsand @GreggMoreland @MitchellTCG added dash to transaction name as requested

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/2b1d5399-ae89-4434-acea-5a850d9d1118)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Pre-requisite a "In-kind Transfer - Federal Election Activity" transaction is created and displayed in the Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ed110eaf-0ce2-4265-83e5-b06dde7a59ec)

From the "In-kind Transfer - Federal Election Activity" transactions page select the ">AUTO-POPULATED: Review disbursement information" link.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ab9ffec8-d9c9-47a1-95a5-16331a7de9f3)

Verified the "In-kind Transfer Federal Election Activity Out" disbursement transaction is displayed. Fields are displayed as "Read-only" (with exception of "Note or Memo Text (Optional) and Category Code (Optional).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e998d3c1-de98-475c-8b42-ebcecca9f9f9)

Verified the "In-kind Transfer Federal Election Activity Out" is auto-populated and displayed in the Transactions table as a disbursement. Verified the Transaction ID and Associated With is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/da456e40-8c41-4bab-a587-ebf1b299b81d)

QA Review Completed. Moved to Stage Ready.
