### ISSUE TITLE
Allow user to enter Conduit Earmark Out on Schedule B (Group M)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#745]
Business Reason

As a Committee Administrator, I will be able to enter a ***”Conduit Earmark Out”*** sub-transaction under ***”Conduit Earmark”*** on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

***NOTE:*** This is a "child" transaction that will be associated with a parent transaction. The "parent" transaction is on Schedule A.

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

 ***And*** I am editing a Conduit Earmark transaction on an open report

 ***Then*** I will ***be required*** to enter the following sub-transaction:

*   Conduit Earmark Out

***And*** I will be required to enter the following information (unless otherwise noted):

—

1.  Contact

      #

*   ***CONTACT TYPE*** (Required, includes LOOKUP)
      *   Committee only
*   ***COMITTEE NAME*** (Required)
*   ***COMITTEE FEC ID*** (Required)

1.  Address

      #

*   ***STREET ADDRESS*** (Required)
*   ***APARTMENT, SUITE, ETC.*** (Optional)
*   ***CITY*** (Required)
*   ***STATE/PROVINCE*** (Required)
*   ***ZIP/POSTAL CODE*** (Required)

1.  COMMITTEE /CANDIDATE INFORMATION

      #

*   ***COMMITTEE ID*** (Required, must match Committee ID and is read only)
*   ***COMMITTEE NAME*** (Required, must match Committee Name and is read only)

***And*** the user will be required to select a Candidate using the LOOKUP, and upon selection the following will be populated:

*   ***CANDIDATE ID*** (Required)
*   ***CANDIDATE LAST NAME*** (Required)
*   ***CANDIDATE FIRST NAME*** (Required)
*   ***CANDIDATE MIDDLE NAME*** (Optional)
*   ***CANDIDATE PREFFIX*** (Optional)
*   ***CANDIDATE SUFFIX*** (Optional)
*   ***CANDIDATE OFFICE*** (Required)
*   ***CANDIDATE STATE*** (Required if Office = H or S)
*   ***CANDIDATE DISTRICT*** (Required if Office = H)

1.  ELECTION INFORMATION

      #

*   ***ELECTION CODE*** (Required)
*   ***ELECTION YEAR*** (Required)
*   ***ELECTION DESCRIPTION*** (Required if Election Code is Other)

1.  Expenditure Information

      #

*   ***DATE*** (Required)
*   ***MEMO ITEM*** (Must match the Conduit Earmark)
*   ***AMOUNT*** (Required, ***read-only***, can be negative)

      ***This should automatically be the same as the Conduit Earmark Receipt (parent) and read-only***

1.  Additional information

      #

*   ***PURPOSE OF DISBURSEMENT*** (System Generated)

      Data field: multi-line textbox that must read "Earmark from XX", where "XX" is Individual First Name, Last Name from the parent Conduit Earmark Receipt on Schedule A
*   ***NOTE OR MEMO TEXT*** (Optional)
*   ***CATEGORY CODE*** (Optional)

—

 ***Then*** I will be able to:

*   Toggle between step 1 and 2 and edit fields as needed
*   Save both transactions
*   Cancel (Note: This cancels _both_ transactions)

***And*** upon saving, both Conduit Earmark and Conduit Earmark Memo will be saved with their own line items (itemized) on the *.fec file on lines SA11AI and SB23, respectively.

Dev Note

*   BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
*   BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

*   [x] Update schema to match [Spec Updates spreadsheet tab here]( [https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=66905475](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=66905475)) ***This is a consolidated specification***
*   [x] Use django transaction for save so we can rollback a partial success [https://docs.djangoproject.com/en/4.1/topics/db/transactions/](https://docs.djangoproject.com/en/4.1/topics/db/transactions/)
*   [x] Text in second accordion box: "STEP TWO: Add earmarked memo and conduit information (REQUIRED FOR CONDUIT EARMARKED RECEIPTS)"
*   [x] Please note that the transaction type identifier ***depends on the Memo Item selection***.

Wireframe

![745 - Conduit Earmark (Deposited).png]([https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/73d8c000-3411-4517-bb24-bc76db241316](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/73d8c000-3411-4517-bb24-bc76db241316))

### QA Notes ###

- There is no aggregate for this transaction. Transaction will be itemized, regardless of amount.
- Note that Beneficiary information should function exactly the same as Donor information, just a text change in the header.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-897](https://fecgov.atlassian.net/browse/FECFILE-897)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
Wires added and DEV NOTES updated

cc'd:
@mary @JonellaCulmer

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Wires updated

**Comment by AureliaKhorsand** [comment]
@mary-tcg @MitchellTCG please update the button to say "Save both transactions", per the new two-part transaction design rule

**Comment by mary-tcg** [comment]
@AureliaKhorsand @MitchellTCG updated

**Comment by Elaine-Krauss-TCG** [comment]
Work in progress.  The Conduit Earmark Out is proving troublesome, but it is coming along.  At the moment, I *believe* that the Committee/Candidate information fields are the last major hurdle.  This was never implemented for double-transactions, and I've been doing my best to mirror it over from single-transactions, but it's slow going.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/971beb36-fc8e-41d9-a8cd-d1dac8b3e990)

**Comment by Elaine-Krauss-TCG** [comment]
@AureliaKhorsand @GreggMoreland 

When you have some time, it would be helpful to know what you mean by this:
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/702f1d76-e4db-4a5a-8a4c-920f2343243b)

Is this supposed to match the user's committee, is it supposed to be auto-populated based on information related to the candidate, or is it neither?

**Comment by AureliaKhorsand** [comment]
@Elaine-Krauss-TCG it should be the same as the Committee entered at the top of the form (the primary contact). It's going to repeat that information, which is expected. If the user wants to change it, they change it at the top of the form.

**Comment by Elaine-Krauss-TCG** [comment]
The Conduit Earmarks are now saving!  There's a lot of polish that's needed before it can go into CR, but we're finally in the final stages.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/a8669af8-cac5-46d8-bd17-9975c7cf8b81)

**Comment by Elaine-Krauss-TCG** [comment]
The Conduit Earmarks are now saving!  There's a lot of polish that's needed before it can go into CR, but we're finally in the final stages.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/a8669af8-cac5-46d8-bd17-9975c7cf8b81)

**Comment by toddlees** [comment]
passes CR moving to QA

**Comment by WiseQA** [comment]
Pre-requisite a "Conduit Earmark" transaction is created and displayed in the Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a715d711-3df3-4ddb-8ffe-af095134bd4e)

From the "Conduit Earmark" transactions page select the ">Step 2 . . . " link.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8a22485c-36fa-4fa7-9a2d-4c94881b4392)

Verified the "Conduit Earmark Out" disbursement transaction is displayed. 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fe1bf07b-a846-439a-ba49-a603806a2d2e)

Enter the Committee/Candidate Information; Candidate Office; and Election Information 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6da7d62b-c013-4b03-9b97-4eaa126c88e4) 

Verified the "Conduit Earmark Out" is displayed in the Transactions table as a disbursement. Verified the Transaction ID and Associated With is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/889bfd50-1c80-4223-b5bc-977a556e6868)

QA Review Completed. Moved to Stage Ready.
