### ISSUE TITLE
Allow user to enter Conduit Earmark Out (Undeposited) on Schedule B (Group M)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#746]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Conduit Earmark Out (Undeposited)”** sub-transaction under **”Conduit Earmark (Undeposited)”**  on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "child" transaction that will be associated with a parent transaction. The "parent" transaction is on Schedule A

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Conduit Earmark (Undeposited) transaction on an open report
**Then**  I will **be required** to enter the following sub-transaction:

- Conduit Earmark Out (Undeposited)

**And** I will be required to enter the following information (unless otherwise noted):

---

# Conduit 
#
-	**ENTITY TYPE** (Required, **INCLUDES LOOKUP**)
-- Committee Only

-	**CONDUIT NAME** (Required)
-	**CONDUIT FEC ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# BENEFICIARY INFORMATION 
#
-	**BENEFICIARY COMMITTEE ID** (Required)
-	**BENEFICIARY COMMITTEE NAME** (Required)

**And** the user will be required to select a Candidate using the LOOKUP, and upon selection the following will be populated:

-	**BENEFICIARY CANDIDATE ID** (Required)
-	**BENEFICIARY CANDIDATE NAME** (Required)
-	**BENEFICIARY CANDIDATE OFFICE** (Required)
-	**BENEFICIARYCANDIDATE STATE** (Required if CANDIDATE OFFICE is 'Senate' or 'House')
-	**BENEFICIARY CANDIDATE DISTRICT** (Required if CANDIDATE OFFICE is 'House')

# ELECTION INFORMATION 
#
-	**ELECTION CODE** (Required)
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Other)

# Expenditure Information  
#
-	**DATE** (Required)
-	MEMO ITEM (Required, system checked and read-only)
-	AMOUNT (Required, read-only)
-- **This should automatically be the same as the Conduit earmark Receipt (parent) and read-only**
-	EMPLOYER (Required if **AMOUNT** > $200)
-	OCCUPATION (Required if **AMOUNT** > $200)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (System Generated)
Data field: multi-line textbox that must read "Earmark from XX", where "XX" is Individual First Name, Last Name from the parent Conduit Earmark Receipt on Schedule A
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)
---
**Then** I will be able to:
- Toggle between step 1 and 2 and edit fields as needed
- Save 
- Cancel (Note: This cancels _both_ transactions)

**And** upon saving, both Conduit Earmark (Undeposited) and Conduit Earmark Memo (Undeposited) will be saved with their own line items (itemized) on the *.fec file on line SB23

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=66905475)  **This is a consolidated specification**
- [ ] Use django transaction for save so we can rollback a partial success https://docs.djangoproject.com/en/4.1/topics/db/transactions/
- [ ] Text in second accordion box: "STEP TWO:  Add earmarked memo and conduit information (REQUIRED FOR EARMARKED RECEIPTS)"

 Wireframe 

![746 - Conduit Earmark (Undeposited).png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/dad27de9-5d82-41ea-bab9-1b3e636e4a1b)

### QA Notes ### 
 
There is no aggregate. Because there is no aggregate, EMP/OCC is only required if the AMOUNT is over $200.

text next to Election Description title = "(optional if general or primary)"

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
Wires added and DEV NOTES updated

cc'd:
@mary @JonellaCulmer

**Comment by AureliaKhorsand** [comment]
Closing as OBE since we're combining deposited and undeposited.
