### ISSUE TITLE
Allow user to enter PAC Conduit Earmark Out on Schedule B (Group M)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#747]
Business Reason

As a Committee Administrator, I will be able to enter a ***”PAC Conduit Earmark Out”*** sub-transaction under ***”PAC Conduit Earmark”*** on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

***NOTE:*** This is a "child" transaction that will be associated with a parent transaction. The "parent" transaction is on Schedule A

Acceptance Criteria

***Given*** I am a Committee Administrator editing an open Form 3X report

 ***And*** I am editing a PAC Conduit Earmark transaction on an open report

 ***Then*** I will ***be required*** to enter the following sub-transaction:

*   PAC Conduit Earmark Out

***And*** I will be required to enter the following information (unless otherwise noted):

—

1.  Contact

      #

*   ***CONTACT TYPE*** (Required, includes LOOKUP)
      *   Committee Only
*   ***COMMITTEE NAME*** (Required)
*   ***COMMITTEE FEC ID*** (Required)

1.  Address

      #

*   ***STREET ADDRESS*** (Required)
*   ***APARTMENT, SUITE, ETC.*** (Optional)
*   ***CITY*** (Required)
*   ***STATE/PROVINCE*** (Required)
*   ***ZIP/POSTAL CODE*** (Required)

1.  COMMITTEE/CANDIDATE INFORMATION

      #

*   ***COMMITTEE ID*** (Required, must match Committee ID amd is read only)
*   ***COMMITTEE NAME*** (Required, must match Committee Name and is read only)

***And*** the user will be required to select a Candidate using the LOOKUP, and upon selection the following will be populated:

*   ***CANDIDATE ID*** (Required)
*   ***CANDIDATE LAST NAME*** (Required)
*   ***CANDIDATE FIRST NAME*** (Required)
*   ***CANDIDATE MIDDLE NAME*** (Optional)
*   ***CANDIDATE PREFFIX*** (Optional)
*   ***CANDIDATE SUFFIX*** (Optional)
*   ***CANDIDATE OFFICE*** (Required)
*   ***CANDIDATE STATE*** (Required if Office = H or S)
*   ***CANDIDATE DISTRICT*** (Required if Office = H)

1.  ELECTION INFORMATION

      #

*   ***ELECTION CODE*** (Required)
*   ***ELECTION YEAR*** (Required)
*   ***ELECTION DESCRIPTION*** (Required if Election Code is Other)

1.  Expenditure Information

      #

*   ***DATE*** (Required)
*   ***MEMO ITEM*** (Required)

      ***Must match the PAC Conduit Earmark and read-only.***
*   ***AMOUNT*** (Required, ***read-only***, can be negative)

      ***This should automatically be the same as the Conduit earmark Receipt (parent) and read-only***

1.  Additional information

      #

*   ***PURPOSE OF DISBURSEMENT*** (System Generated)

      Data field: multi-line textbox that must read "Earmark from XX", where "XX" is Conduit Name from the parent PAC Conduit Earmark Receipt on Schedule A
*   ***NOTE OR MEMO TEXT*** (Optional)
*   ***CATEGORY CODE*** (Optional)

      —

      ***Then*** I will be able to:
*   Toggle between step 1 and 2 and edit fields as needed
*   Save both transactions
*   Cancel (Note: This cancels _both_ transactions)

***And*** upon saving, both PAC Conduit Earmark and PAC Conduit Earmark Out will be saved with their own line items (itemized) on the *.fec file on lines SA11C and SB23, respectively.

Dev Note

*   BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
*   BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

*   [x] Update schema to match [Spec Updates spreadsheet tab here]( [https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=66905475](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=66905475)) ***This is a consolidated specification***
*   [x] Use django transaction for save so we can rollback a partial success [https://docs.djangoproject.com/en/4.1/topics/db/transactions/](https://docs.djangoproject.com/en/4.1/topics/db/transactions/)
*   [x] Please note that the transaction type identifier ***depends on the Memo Item selection***.

Wireframe

 ![747 - PAC Conduit Earmark Out.png]([https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/f4f01640-0379-4fcf-a251-8abc7a4c53fb](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/f4f01640-0379-4fcf-a251-8abc7a4c53fb))

### QA Notes ###

There is no aggregate.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-895](https://fecgov.atlassian.net/browse/FECFILE-895)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Pre-requisite a "PAC Conduit Earmark" transaction is created and displayed in the Transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c92058de-ac9c-42bb-95f7-7336a8c61e52)

From the "PAC Conduit Earmark" transactions page select the ">Step 2 . . . " link.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5038e378-e7bc-4e76-b9d5-34100b0e7de4)

Verified the "PAC Conduit Earmark Out" disbursement transaction is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a9c0318b-fce9-44b2-a049-37c8040529e3)

Enter the Committee/Candidate Information; Candidate Office; and Election Information

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4275a1b9-e51c-4fd6-a392-a438ee6f5e3d)

Verified the "PAC Conduit Earmark Out" is displayed in the Transactions table as a disbursement. Verified the Transaction ID and Associated With is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/27535f4b-c177-4c2f-9b3e-4357628650b5)

QA Review Completed. Moved to Stage Ready.
