### ISSUE TITLE
Allow user to enter PAC Conduit Earmark Memo (Undeposited) on Schedule B (Group M)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#748]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”PAC Conduit Earmark Memo (Undeposited)”** sub-transaction under **”PAC Conduit Earmark (Undeposited)”**  on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "child" transaction that will be associated with a parent transaction. The "parent" transaction is on Schedule A

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a PAC Conduit Earmark (Undeposited) transaction on an open report
**Then**  I will **be required** to enter the following sub-transaction:

- PAC Conduit Earmark Memo (Undeposited)

**And** I will be required to enter the following information (unless otherwise noted):

---

# Conduit 
#
-	**ENTITY TYPE** (Required, **INCLUDES LOOKUP**)
Dropdown options: Committee 

-	**CONDUIT NAME** (Required)
-	**CONDUIT FEC ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# BENEFICIARY INFORMATION 
#
-	**BENEFICIARY COMMITTEE ID** (Required if ENTITY is COMMITTEE)
-	**BENEFICIARY COMMITTEE NAME** (Required if ENTITY is COMMITTEE)

**And** the user will be required to select a Candidate using the LOOKUP, and upon selection the following will be populated:

-	**BENEFICIARY CANDIDATE ID** (Required if ENTITY is COMMITTEE **AND** ENTITY is linked to a Candidate)
-	**BENEFICIARY CANDIDATE NAME** (Required if ENTITY is COMMITTEE **AND** ENTITY is linked to a Candidate)
-	**BENEFICIARY CANDIDATE OFFICE** (Required if ENTITY is COMMITTEE **AND** ENTITY is linked to a Candidate)
-	**BENEFICIARYCANDIDATE STATE** (Required if ENTITY is COMMITTEE **AND** ENTITY is linked to a Candidate)
-	**BENEFICIARY CANDIDATE DISTRICT** (Required if RECIPIENT CANDIDATE OFFICE is 'House')

# ELECTION INFORMATION 
#
-	**ELECTION CODE** (Required)
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Other)

# Expenditure Information  
#
-	**DATE** (Required)
-	**MEMO ITEM** (Required)
**This will be automatically checked and read-only.**
-	**AMOUNT** (Required, **read-only**, can be negative)
**This should automatically be the same as the Conduit earmark Receipt (parent) and read-only**

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (System Generated)
Data field: multi-line textbox that must read "Earmark from XX", where "XX" is Conduit Name from the parent PAC Conduit Earmark Receipt on Schedule A
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Toggle between step 1 and 2 and edit fields as needed
- Save 
- Cancel (Note: This cancels _both_ transactions)

**And** upon saving, both PAC Conduit Earmark (Undeposited) and PAC Conduit Earmark Memo (Undeposited) will be saved with their own line items (itemized) on the *.fec file on line SB23

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.

- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=66905475)  **This is a consolidated specification**
- [ ] Use django transaction for save so we can rollback a partial success https://docs.djangoproject.com/en/4.1/topics/db/transactions/

### QA Notes ### 
 
- There is no aggregate for this transaction. Transaction will be itemized, regardless of amount.

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
Closing as OBE since we're combining deposited and undeposited.
