### ISSUE TITLE
Allow user to view contacts

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#75]
Business Reason

As a Committee Administrator, I will be able to view all contacts in my committee so that I can group transactions by entity for fundraising purposes or to disclose transactions in aggregate per contact.

Acceptance Criteria

***If*** I am a Committee Administrator

  ***When*** I go to Contact Management

  ***Then*** I will be able to see all contacts associated with the Committee Account, including:

*   Contact Name
*   Contact Type
*   Employer
*   Occupation

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1324](https://fecgov.atlassian.net/browse/FECFILE-1324)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg the wireframe looks good but has some extra features that we won't be using in OP1.

**Comment by MitchellTCG** [comment]
Here you go

![Manage_Contacts_v4.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/643b448e-36ee-4258-a6ef-3ac4c8de7f26)

**Comment by AureliaKhorsand** [comment]
**4/6/22 Refinement Meeting:** Closed as a duplicate of #144.
