### ISSUE TITLE
System to truncate the field if Purpose Description is greater than 100 characters

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#756]
### Business Reason ### 
As a FECfile Online user, I should see that transactions with system generated Purpose Descriptions that contain a long entity name are truncated so that they do not exceed 100 characters.

### Acceptance Criteria ###

**Given** a system-generated Purpose Description
**If** the description is longer than 100 characters
**Then** they system will truncate the description to 100 characters. _(Ask devs: when?)_

UX/UI Question: Should the user receive a warning or message that their CPD is being truncated?

**Comment by Elaine-Krauss-TCG** [comment]
As part of App ticket #513/514, a temporary solution was put into place where system generated purpose descriptions longer than 100 characters are truncated to 97 characters and an ellipsis is appended.

E.G.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/3900ab17-09f4-4506-b500-89d1e58a5377)

When the corresponding Conduit Name was:
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/77cf1fa6-570f-497d-b9a8-7febc2187813)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG can we look into if this is OBE due to @Elaine-Krauss-TCG 's comment above? It looks to be the same idea as the wireframe in [#54 ](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-project-management/54)

**Comment by MitchellTCG** [comment]
re: UX/UI Question: Should the user receive a warning or message that their CPD is being truncated?

Executive decision. this is OBE. no warning needed.

here is another screencap of the truncation in use.
![Screenshot 2023-02-14 at 11.39.48 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0e4eca4a-eec3-425f-a09f-bdeb53fc5e25)

**Comment by AureliaKhorsand** [comment]
Resolved with another ticket. Closed as OBE.
