### ISSUE TITLE
Refactor TransactionTypeBaseComponent code

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#763]
The TransactionTypeBaseComponent has ballooned to 500+ lines. The technical debt task is to split the component into 2: TransactionTypeBaseComponent and TransactionTypeX1BaseComponent.

***Tasks***

  1\. TransactionTypeBaseComponent will contain the properties and methods used by both the TransactionTypeX1BaseComponent and TransactionTypeX2BaseComponent child and grandchild classes that inherit it. (Note: TransactionTypeX2BaseComponent component extends TransactionTypeX1BaseComponent)

  2\. (Stretch goal) Migrate the contact management methods into a separate static class file that is imported by TransactionTypeBaseComponent

***Acceptance Criteria***

  Unit tests and e2e tests pass for transaction screens

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-890](https://fecgov.atlassian.net/browse/FECFILE-890)

**Comment by mjtravers** [comment]
For QA: Refactored code passes all unit tests:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/435f4300-d4f2-4fef-a66b-8dbc408063ae)

**Comment by toddlees** [comment]
For QA: Passes e2e tests
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/0d766a7c-c938-4c83-9b77-26304fb40fbf)

**Comment by WiseQA** [comment]
QA review visual inspection completed with DEV - screenshots provided above.  Moved to Stage Ready.
