### ISSUE TITLE
Create Sched B Angular model and service

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#766]
Similarly to the SchATransaction model and SchATransactionService, create a SchBTransaction model and SchBTransactionService in the angular shared directory.

***Tasks***
 1\. Create SchBTransaction model. Use SchATransaction and SchB validation schema as a template.
 2\. Refactor SchATransaction and SchBTransaction classes to factor out common code, if any, to a Transaction parent class. If a Transaction parent class is necessary, incorporate and remove the Transaction interface. Create a transaction directory in the shared/services and shared/models directory to hold the pertinent model and service files.
 3\. Create SchBTransactionService class. If it makes sense, refactor SchATransactionService and SchBTransaction service to inherit a parent abstract TransactionService class. (Would generics make this possible and useful?)

***Acceptance Criteria***
 Passing of Angular unit tests for the SchBTransaction and SchBTransactionService classes.

***QA Notes***
 A screenshot of all the unit tests passing without errors is attached below in the comments for visual verification that the acceptance criteria has been met.

### QA Notes ###
**Tasks**
1. Create SchBTransaction model. Use SchATransaction and SchB validation schema as a template.
2. Refactor SchATransaction and SchBTransaction classes to factor out common code, if any, to a Transaction parent class. If a Transaction parent class is necessary, incorporate and remove the Transaction interface. Create a transaction directory in the shared/services and shared/models directory to hold the pertinent model and service files.
3. Create SchBTransactionService class. If it makes sense, refactor SchATransactionService and SchBTransaction service to inherit a parent abstract TransactionService class. (Would generics make this possible and useful?)

**Acceptance Criteria**
Passing of Angular unit tests for the SchBTransaction and SchBTransactionService classes.

**QA Notes**
A screenshot of all the unit tests passing without errors is attached below in the comments for visual verification that the acceptance criteria has been met.

### DEV Notes ###
null

### Design ###
null

[FECFILE-889](https://fecgov.atlassian.net/browse/FECFILE-889)

**Comment by mjtravers** [comment]
Screenshot of unit test report showing that all 429 of the unit tests passed  with 0 failures:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/ba3bbe29-4ca4-4963-aa4b-f1054f69bf1e)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review as an inspection from the screenshot provided above from the DEV team.   

No true QA review completed on this ticket.

Moved to Stage Ready.
