### ISSUE TITLE
Data Architecture: Group transaction types with same 

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#78]
**Problem**
Creating web app forms that input transaction information that perform well and are maintainable yet do not contain duplicate code.

**Background**
In Angular, input forms are captured in components that define how the HTML page is designed. In order to avoid duplicate code and improve maintainability of the code, transaction types that have the exact same array of FIELD DESCRIPTION rows in the Form_3X_Receipts_Vendor can use the same component. What is needed is a list of named groupingss of the Sched A transaction types listed out by transaction type ID. The name of the group is a descriptive identifier (in the form of all-caps letters and underscores) that classifies the group and can be used in the code for the component that is used to create the input form used by that group of transaction types

**Acceptance Criteria**
- [ ] List of grouped Sched A transaction types that have the same exact array of FIELD DESCRIPTION rows. The other rows, such as TYPE and REQUIRED are not important in determining similarity between transaction types.
- [ ] Each grouping in the list will have a unique name that describes the transaction types in the group. (in the form of all-caps letters and underscores)

**Comment by AureliaKhorsand** [comment]
**Backlog Grooming 1/20 Notes:** Field description needs to be identical - there are currently discrepancies between the tabs of the transaction type specs (typos, different names, etc). Assumption is that Ryan Lanz (FEC) will be providing the groupings, and pointing is accounting for the developer working with Ryan. 

QA will just be verifying the list exists per the Acceptance criteria. The list of unique identifiers should not have any duplicates.

Per Laura, we need to make sure this matches the current specifications as well, and the data architecture should still support the current specs. Matt replied that the validation does not affect figured out what has the same fields. The validator can catch if something changes, and this will help for future testing.

**Comment by mjtravers** [comment]
Had a lengthy meeting with Ryan about the development of the new spec from the old spec that has rendered this ticket obsolete. Grouping of the transaction types to streamline the build out of the Angular components for the input forms can be achieved through other strategies.
