### ISSUE TITLE
Generate production build of Angular app

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-web-app#80]
Business Reason

As a developer, I will be able to create a production build of the fecfile-web-app so that I can deploy an optimized version of the application.

Acceptance Criteria

***If*** I run "npm run build" in the fecfile-web-app/front-end directory

  ***When*** the Angular build is complete

  ***Then*** the static application is created in the fecfile-web-app/front-end/dist directory.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1321](https://fecgov.atlassian.net/browse/FECFILE-1321)

**Comment by mjtravers** [comment]
This ticket is OBE. CircleCI and Cloud.gov have been set up to deploy to production.
Closing ticket.
