### ISSUE TITLE
DSP: System to calculate Transfers (line 12) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#801]
Business Reason 
 

On the Detailed Summary Page, Line 12 should be a total of transactions with form type SA12 _except_ for if the transaction has "Memo Code" checked. This ticket is for Column B only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 12 (column B) of Form 3X must:
--  consist of the total of transactions with form type "SA12"  **from January 1 of current year to the report coverage period end date**
-- NOT include any transactions with "Memo Code" checked
2. The numbers will update as needed until the report is submitted.

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
  
The following 'Main' transaction types are included here:

- Transfers
- Joint Fundraising Transfers

![image.png](https://images.zenhubusercontent.com/62eac7883f87756fe900911f/ba64f4e6-1786-49dd-9c40-88451d9b5319)
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/b437da08-f1da-4004-8a83-96c0959fcb5d)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified transactions with form type "SA12" within the report period the Detailed Summary Page Line 12 (column B) of Form 3X consisted of the total of transactions. (NOTE: e2e testing to be run on all transactions)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/822bd487-16e3-45b5-8e75-a68f7a6a2e4b)

**NOTE: e2e testing to be run on all transactions**

QA Review Completed. Moved to Stage Ready.
