### ISSUE TITLE
Create Disbursements selection screen (Schedule B transactions only)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#805]
***Note:*** _These links/items will be inactive until we develop transactions, and they will become active as we go._

  

Business Reason

As a Committee Administrator within an existing Form 3X report, I will be able to see a list of available Disbursements grouped by type so that in the future I can easily see and select what I need to enter.

Acceptance Criteria

***Given*** I am editing an open Form 3X report

  ***Then*** I can enter a Disbursement by clicking "Add a Disbursement" in the left-hand navigation menu (currently greyed-out),

  ***Then*** I can see available Disbursements within Schedule B, grouped by the following:

—

1.  Operating Expenditures

       #

*   Operating Expenditure
*   Credit Card Payment for Operating Expenditure
*   Staff Reimbursement for Operating Expenditure
*   Payment to Payroll for Operating Expenditure
*   Void of Operating Expenditure

—

1.  Contributions/Expenditures to Regular Filers

       #

*   Void of Operating Expenditure
*   Transfers to Affiliates/Other Committees
*   Contribution to Candidate
*   Void of Contribution to Candidate
*   Contribution to Other Committee
*   Void of Contribution to Other Committee

—

1.  Other Expenditures

       #

*   Other Disbursements
*   Credit Card Payment for Other Disbursements
*   Staff Reimbursements for Other Disbursements
*   Payment to Payroll for Other Disbursements
*   Void of Other Disbursements
*   Non-Contribution Account Disbursements
*   Non-Contribution Account Credit Card Payment
*   Non-Contribution Account Staff Reimbursement
*   Non-Contribution Account Payment to Payroll
*   National Party Recount Account Disbursements
*   Recount Disbursements
*   Headquarters Account Operating Expense for National Party Expenses
*   Convention Account Operating Expense for National Party Expense
*   Headquarters Account - Individual Refund
*   Headquarters Account - Regular Filer Refund
*   Headquarters Account - Tribal Refund
*   Convention Account - Individual Refund
*   Convention Account - Regular Filer Refund
*   Convention Account - Tribal Refund
*   National Party Recount Account - Individual Refund
*   National Party Recount Account - Regular Filer Refund
*   National Party Recount Account - Tribal Refund

—

1.  Refund

       #

*   Refund of Individual Contribution
*   Refund of Individual Contribution - Void
*   Refund of Party Contribution
*   Refund of Party Contribution - Void
*   Refund of PAC Contribution
*   Refund of PAC Contribution - Void
*   Refund of Unregistered Contribution
*   Refund of Unregistered Contribution - Voids

       —

1.  Federal Election Activity Expenditures

       #

*   100% Federal Election Activity Payment
*   Credit Card Payment for 100% Federal Election Activity
*   Staff Reimbursement for 100% Federal Election Activity
*   Payment to Payroll for 100% Federal Election Activity
*   Void of 100% Federal Election Activity

![Disbursement Selector]([https://user-images.githubusercontent.com/25588182/210792890-516795f5-47be-48e0-8e08-3aac072f175d.png](https://user-images.githubusercontent.com/25588182/210792890-516795f5-47be-48e0-8e08-3aac072f175d.png))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-883](https://fecgov.atlassian.net/browse/FECFILE-883)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand mock added

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG - Please change name on the selection screen from "Add a disbursements" to "Add a disbursement" as denoted in wireframe above

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1b6897ef-92dd-4cd2-8181-1e6e855f8f8f)

**Comment by mjtravers** [comment]
The fix to "Add a disbursements" typo has been merged and deployed to STAGE. Ready for QA.

**Comment by WiseQA** [comment]
QA review completed and verified "Add a Disbursement" in the left-hand navigation menu is linked to accordion dropdown list.    

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/875d90c5-8461-4b13-a6a5-5e1866f5ce54)

QA review verified each accordion list contained the correct disbursements lists as listed above (below shows Operating Expenditures dropdown list as example of testing.)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ff88b3b9-6d0a-481d-a3be-60d57ae8d354)

QA Review Completed.   Moved to Stage Ready
