### ISSUE TITLE
DSP: System to calculate Contributions (line 11 and 33) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#808]
Business Reason 
 

On the Detailed Summary Page, Line 11 should be a breakdown of the total of transactions and Line 33 should be total of transactions with form type SA11AI, SA11AII, SA11B, SA11C _except_ for if the transaction has "Memo Code" checked. This ticket is for Column B only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 11 (column B) of Form 3X must:
-- NOT include any transactions with "Memo Code" checked
--  consist of the total of transactions with form type "SA11"  **from January 1 of current year to the report coverage period end date** as follows:
--           If transaction form type is SA11AI then add total to 11.a.i Itemized in Column B
--           If transaction form type is SA11AII then add total to 11.a.ii Unitemized in Column B
--          Total from both SA11AI and SA11AII should be added to 11.a.III TOTAL
--          If transaction form type is SA11B then add total to 11.b
--          If transaction form type is SA11C then add total to 11.c
--          All totals in 11.a.iii, 11.b, 11.c should be added to 11.d Total Contributions
-- The value in 11.d Total Contributions should be copied to Line 33
2. The numbers will update as needed until the report is submitted.

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

 QA NOTES
Note the wireframe needs edits made in comment below

The following transaction types are applicable here:
--SA11AI and SA11AII:
Individual Receipt "SA11AI" or "SA11AII"
Tribal Receipt "SA11AI" or "SA11AII"
Partnership Receipt "SA11AI" or "SA11AII"
In-Kind Receipt "SA11AI" or "SA11AII"
Returned/Bounced Receipt "SA11AI" or "SA11AII"
Earmark Receipt SA11AI Only
Conduit Earmark (Deposited) SA11AI Only
Conduit Earmark (Undeposited) SA11AI Only
Unregistered Receipt from Person "SA11AI" or "SA11AII"
Unregistered Receipt from Person - Returned/Bounced Receipt "SA11AI" or "SA11AII"

--SA11B:
Party Receipt SA11B only
Party In-Kind
Party Returned/Bounced Receipt

--SA11C:
PAC Receipt
PAC In-Kind
PAC Earmark Receipt
PAC Conduit Earmark (Deposited)
PAC Conduit Earmark (Undeposited)
PAC Returned/Bounced Receipt

Note: There is an extra "unitemized contributions" row that should be resolved in a previous ticket. 
![image.png](https://images.zenhubusercontent.com/62eac7883f87756fe900911f/28d4fbf9-9dcd-4f4a-9a1c-f64b35702f90)

![image.png](https://images.zenhubusercontent.com/62eac7883f87756fe900911f/948df5ac-400b-460b-bfb4-5c6189845cbd)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by toddlees** [comment]
Edits to wireframe below.  Functionality should match red markups
![Untitled 4.jpg](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/84d6e07d-ab32-4819-bce7-8da0d9214f2f)

**Comment by mjtravers** [comment]
@Elaine-Krauss-TCG  Per the DEV notes in the ticket, the transactions_transaction table needs an index on the form_type column. Sending back to In Progress.

**Comment by mjtravers** [comment]
@Elaine-Krauss-TCG Todd has requested a change in the CR. Moving ticket to In Progress for possible code updates

**Comment by mjtravers** [comment]
Passes CR. Ready for QA

**Comment by WiseQA** [comment]
During QA review line 11 is displaying in Column B.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dc8ffc27-fc40-47e0-86eb-747c17fa5160)

Line 33 is not displaying as denoted in the ticket.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/11df997a-66a3-4792-8e49-64ae69016fea)

@mjtravers returned to In-Progress for fix.

**Comment by mjtravers** [comment]
This looks to be a bug in the API code. The line assignments are missing the L33_total_contributions_ytd (https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/summary/tasks.py#L52-L70) and the ytd is not getting calculated for line 11d which is then used to populate line 33 (https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/summary/summary.py#L96-L104).

**Comment by mjtravers** [comment]
Line 33 column B bug fixed. Passes CR and sending to QA.

**Comment by WiseQA** [comment]
QA review verified changes were made to DSP according to redlined wireframe attached above.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/de6d2646-5374-45ae-92b3-ceeef1bda152)

QA review verified transactions with form type "SA11" and "SA11.a through SA11.d are displayed in the Detailed Summary Page (Column B). **(NOTE: e2e testing to be run on all transactions)** Total line SA11.d $-$7,412.70.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e54c20ea-400e-4895-9d9b-d3455738e25f)

Verified total in SA11.d is displayed in Column B - line 33 ($-$7,412.70).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ce13e5d6-c693-4fd3-a617-1666b4678a19)

**NOTE: e2e testing to be run on all transactions**

QA Review Completed. Moved to Stage Ready.
