### ISSUE TITLE
System to provide Memo Item information in a ToolTip

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#825]
Task: Currently, the text "The dollar amount in a memo item is not incorporated into the total figure for the schedule." is in italics underneath the checkbox for "Memo Item". This text needs to be moved into a tooltip to the right of the checkbox and field name.

![image.png]([https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/d5250ec6-8aa1-49a9-8131-e1019a97e8a2](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/d5250ec6-8aa1-49a9-8131-e1019a97e8a2))

Acceptance Criteria

***Given*** the user is in a transaction entry form

  ***Then*** there will be a ToolTip to the right of the Memo Item checkbox

  ***And*** when the user hovers over the ToolTip, then the system provides the following text: "The dollar amount in a memo item is not incorporated into the total figures for the schedule."

1.  Wireframe with tooltip

       #

       ![825 - Memo Item tool tip.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/5368ca72-d480-4e10-a3fa-73e99887cb69](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/5368ca72-d480-4e10-a3fa-73e99887cb69))

1.  Video of tooltip

       #
    [https://images.zenhubusercontent.com/306118986/9cc406d4-27c5-4e59-8e81-0e1a427448a0/825___video_tool_tip.mp4](https://images.zenhubusercontent.com/306118986/9cc406d4-27c5-4e59-8e81-0e1a427448a0/825___video_tool_tip.mp4)

### QA Notes ###
- Note that "figures" must be plural, which is a change from the previous iteration of text

![Screenshot 2023-01-17 at 11.48.50 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f7034ce5-d2ce-4513-80c5-45fd50c31618)

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-878](https://fecgov.atlassian.net/browse/FECFILE-878)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG or @mary-tcg can you add the wireframe for the finished version?

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Memo tooltip displays help information.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d659ff2c-2041-4a52-ba3a-816ffe3a3042)

QA Review Completed.   Moved to Stage Ready.
