### ISSUE TITLE
System to default order transactions *within* a report and include Line Numbers

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#828]
Business Reason 
 

As a FECfile administrator viewing my report in FECfile Online, I will be able to view the transactions in the order listed below in the acceptance criteria so that I can view the transactions in a logical order to help in reporting and supporting the data in the report.

 Acceptance Criteria 
 

**Given**  I am a FECfile administrator
**And** I am viewing my report in FECfile Online
**Then** I will see the transactions in the following order:

1. Within a report, by category: Receipt, Disbursement _(Future functionality: Loans_ and Debts, Other) (Left Hand Navigation groupings)
2. Within a grouping, by **Line Number**
_Note: This is a new column in each group._
3. Within line number, **by order transaction was created**

 Wireframe 

![1057 - Transactions in this report – Loan – 2.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4b6f5d5c-8a34-4138-abef-3aab675418fc)

### QA Notes ### 
 To test this ticket:
generate a .fec and make sure the "Transactions in this report" match the order of the .fec
### DEV Notes ### 
 - Query for sorting built out on #194, but need to translate that into the front-end
### Design ### 
 null

**Comment by JonellaCulmer** [comment]
> ...child transactions will always be displayed directly after the parent in the order in which they were created.

@AureliaKhorsand From a BA perspective, what would you say is the value of showing both children and grandchildren transactions? Would you say grandchildren have the same level of importance?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
Wires added and DEV NOTES updated
#5 in the AC should probably be pushed since we are going to implement the Angular Tree Table

cc'd:
@mary @JonellaCulmer

**Comment by AureliaKhorsand** [comment]
@MitchellTCG Removed AC#5, will implement with #951.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Per discussion this ticket tested by generating a .fec and make sure the "Transactions in this report" match the order of the .fec (Note:   .fec shows creation date NOT the transaction date).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d0a1dcb7-b81b-4888-ad8d-a3a6f896e139)

Transactions table front end:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/db787095-4ef6-40da-9125-8e8a8e015558)

QA Review Completed.  Moved to Stage Ready.
