### ISSUE TITLE
Allow user to view each transaction on submitted reports

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#830]
Business Reason

As a user, I will be able to view detailed transactions on submitted reports so that I can have access to all my data even if the report has been submitted.

Acceptance Criteria

***Given*** the user is on the Manage Transactions page of a submitted report,

  ***And*** they open a transaction,

  ***Then*** they will not be able to edit ANY data,

  ***And*** they will see "READ ONLY" under the Transaction title

  ***And*** they can click "Go Back" to go back to the list of transactions.

Wireframe

![964 - Joint Fundraising Transfer.png]([https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/d61e9374-c386-4443-a490-b0cbc1bf7112](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/d61e9374-c386-4443-a490-b0cbc1bf7112))

### QA Notes ###
- There should be text "READ ONLY" underneath the transaction name.
- There is no "Save" or "Cancel" button, nor is there a "Save & Add More" button (if applicable).
- 
Checkoff list for QA review from below comment.  

Read Only text under the transaction title
Grey out the Check box
Remove + Save & add more if there
instead of Cancel and Save - > Only have a Go back button

### DEV Notes ###
- The "Memo Item" checkbox should be greyed out if checked _or_ unchecked.

### Design ###
null

 See full ticket and images here: [FECFILE-876](https://fecgov.atlassian.net/browse/FECFILE-876)

**Comment by mary-tcg** [comment]
@MitchellTCG @AureliaKhorsand @GreggMoreland example wireframe added

**Comment by AureliaKhorsand** [comment]
@mary-tcg @MitchellTCG this looks good to me. Do you mind just updating it to read "Purpose of Receipt" instead of "Contribution Purpose Description" for that field? Thank you

**Comment by mary-tcg** [comment]
@AureliaKhorsand @MitchellTCG fixed

**Comment by AureliaKhorsand** [comment]
On Hold to point along with #964

**Comment by MitchellTCG** [comment]
Here are some thoughts ro add/incorporate to the AC:

1. Read Only text under the transaction title
2. Grey out the Check box
3. Remove + Save & add more if there
4. instead of Cancel and Save - > Only have a Go back button

**Comment by AureliaKhorsand** [comment]
@MitchellTCG updated ACs to incorporate your suggestions.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "Review Transactions" on submitted report the fields were grayed out and read-only

However, underneath the transaction name should have "READ ONLY" as denoted above in the wireframe and acceptance criteria.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1a10d512-6630-420e-9347-0792dea6a4b1)

@toddlees @mjtravers returning to In-Progress for this bug fix.

**Comment by mjtravers** [comment]
Bug fix passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Prerequisite is testing #964 prior to this ticket to verify functionality.  

QA review verified once review a transaction is selected, the transaction is "READ ONLY" and Memo Item checkbox is grayed and non-selectable.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0d4d66cc-7e1e-40e9-a490-6bae0a34f073)

Verify the only button on the "READ ONLY" transactions is the "Go Back" button.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/240bec04-3626-4801-b780-a82acd933a53)

@MitchellTCG "Go back" button is different from Wireframe to Read Only transactions page.   Please verify what action is needed.  Thanks

**Comment by MitchellTCG** [comment]
@WiseQA @toddlees 
YES I would like to have Go back on One line. I looked at the HTML and CSS and not really sure how it is working. Todd can we loop up around 12:30n or 2p

**Comment by WiseQA** [comment]
@MitchellTCG @toddlees per discussion of "Go back" button, moved back to In-Progress to fix button as one line and G is the only capital letter (see wireframe).

**Comment by toddlees** [comment]
@MitchellTCG @WiseQA Made "back" lowercase.  The incorrect dimensions were a result of the component being moved in another ticket recently merged.  I updated the css to handle the change.

**Comment by mjtravers** [comment]
Passes CR for button change. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "Go back" button corrected.   

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/08974a87-ef52-448a-b82e-b25538a97745)

QA Review Complete.   Moved to Stage Ready.
