### ISSUE TITLE
Correct Schedule A differences between Spec Spreadsheet and JSON Schema files

### ISSUE THREAD

**Issue by Elaine-Krauss-TCG** [fecgov/fecfile-web-app#831]
See comment below for ticket details

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-875](https://fecgov.atlassian.net/browse/FECFILE-875)

**Comment by Elaine-Krauss-TCG** [comment]
These are the errors found by the new diff checker script


EARMARK_MEMO
 - [x]    Error: donor_committee_fec_id - The JSON has a pattern of ^C[0-9]{8}$ but the expected pattern is ^(?:[PC][0-9]{8}|[HS][0-9]{1}[A-Z]{2}[0-9]{5})$


INDIVIDUAL_JF_TRANSFER_MEMO
 - [x]    Error: contributor_employer - The field is conditionally required, but it is present in the JSON's required array
 - [x]    Error: contributor_employer - The field is conditionally required, but it is not present in the JSON's allOf rules
 - [x]    Error: contributor_occupation - The field is conditionally required, but it is present in the JSON's required array
 - [x]    Error: contributor_occupation - The field is conditionally required, but it is not present in the JSON's allOf rules


INDIVIDUAL_NATIONAL_PARTY_CONVENTION_ACCOUNT
 - [x]    Error: contributor_employer - The field is conditionally required, but it is present in the JSON's required array
 - [x]    Error: contributor_occupation - The field is conditionally required, but it is present in the JSON's required array


INDIVIDUAL_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO
 - [x]    Error: contribution_purpose_descrip - Sheet has Type A/N-100 but the JSON field's pattern's length adds up to 102


INDIVIDUAL_RECEIPT
 - [x]    Error: contributor_employer - The field is required, but the JSON's FEC Spec does not have "X (error)"
 - [x]    Error: contributor_employer - The field is required, but it's not present in the JSON's required array
 - [x]    Error: contributor_occupation - The field is required, but the JSON's FEC Spec does not have "X (error)"
 - [x]    Error: contributor_occupation - The field is required, but it's not present in the JSON's required array


INDIVIDUAL_RECEIPT_NON_CONTRIBUTION_ACCOUNT
 - [x]    Error: contribution_purpose_descrip - The field is required, but it's not present in the JSON's required array

JOINT_FUNDRAISING_TRANSFER
 - [x]    Error: contribution_purpose_descrip - The field is required, but the JSON's FEC Spec does not have "X (error)"
 - [x]    Error: contribution_purpose_descrip - The field is required, but it's not present in the JSON's required array
 - [x]    Error: donor_committee_name - The field is required, but it's not present in the JSON's required array


NATIONAL_PARTY_EARMARK_MEMOS
 - [x]    Error: transaction_type_identifier - The field is not required, but it's marked as "X (error)" in the JSON
 - [x]    Error: transaction_type_identifier - The field is not required, but it's present in the JSON's required array
 - [x]    Error: donor_committee_fec_id - The JSON has a pattern of ^C[0-9]{8}$ but the expected pattern is ^(?:[PC][0-9]{8}|[HS][0-9]{1}[A-Z]{2}[0-9]{5})$


NATIONAL_PARTY_EARMARK_RECEIPTS
 - [x]    Error: transaction_type_identifier - The JSON has a TTI of "EARMARK_RECEIPT_RECOUNT_ACCOUNT" that is not present in the sheet
 - [x]    Error: transaction_type_identifier - The Sheet has a TTI of "EARMARK_RECIEPT_RECOUNT_ACCOUNT" that is not present in the JSON
 - [x]    Error: contributor_last_name - The field is conditionally required, but it is present in the JSON's required array
 - [x]    Error: contributor_last_name - The field is conditionally required, but it is not present in the JSON's allOf rules
 - [x]    Error: contributor_first_name - The field is conditionally required, but it is present in the JSON's required array
 - [x]    Error: contributor_first_name - The field is conditionally required, but it is not present in the JSON's allOf rules


OFFSET_TO_OPERATING_EXPENDITURES
 - [x]    Error: contributor_organization_name - The field is required, but it's not present in the JSON's required array
 - [x]    Error: contributor_last_name - The field is required, but it's not present in the JSON's required array
 - [x]    Error: contributor_first_name - The field is required, but it's not present in the JSON's required array


PAC_EARMARK_MEMO
 - [x]    Error: entity_type - The sheet has an entity type "ORG" that is not present in the JSON's entity type
 - [x]    Error: entity_type - The JSON has an entity type "COM" that is not present in the Sheet's entity type


PAC_JF_TRANSFER_MEMO
 - [x]    Error: contribution_purpose_descrip - Sheet has Type A/N-100 but the JSON field's pattern's length adds up to 115
 - [x]    Error: donor_committee_name - The field is required, but it's not present in the JSON's required array


PAC_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO
 - [x]    Error: donor_committee_fec_id - The JSON has a pattern of ^[ -~]{0,9}$ but the expected pattern is ^(?:[PC][0-9]{8}|[HS][0-9]{1}[A-Z]{2}[0-9]{5})$


PAC_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO
 - [x]    Error: contribution_purpose_descrip - Sheet has Type A/N-100 but the JSON field's pattern's length adds up to 102


PAC_RECEIPT
 - [x]    Error: transaction_type_identifier - The field is not required, but it's marked as "X (error)" in the JSON
 - [x]    Error: transaction_type_identifier - The field is not required, but it's present in the JSON's required array


PAC_RETURN
 - [x]    Error: transaction_type_identifier - The field is not required, but it's marked as "X (error)" in the JSON
 - [x]    Error: transaction_type_identifier - The field is not required, but it's present in the JSON's required array


PARTNERSHIP_RECOUNT_ACCOUNT_RECEIPT
 - [x]    Error: aggregation_group - The field is not required, but it's marked as "X (error)" in the JSON
 - [x]    Error: aggregation_group - The field is not required, but it's present in the JSON's required array


PARTNERSHIP_RECOUNT_ACCOUNT_RECEIPT_MEMO
 - [x]    Error: contributor_employer - The field is conditionally required, but the JSON's FEC Spec does not have "X (conditional error)"
 - [x]    Error: contributor_occupation - The field is conditionally required, but the JSON's FEC Spec does not have "X (conditional error)"


TRANSFER
 - [x]    Error: donor_committee_name - The field is required, but it's not present in the JSON's required array


TRIBAL_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO
 - [x]    Error: contribution_purpose_descrip - Sheet has Type A/N-100 but the JSON field's pattern's length adds up to 102

**Comment by Elaine-Krauss-TCG** [comment]
## 2/22/2023
The [spec verification report](https://app.zenhub.com/files/306118986/04b09ac6-770a-47f4-be3b-77dd63e46a9d/download) from after a first pass of fixes

## 2/14/2023
The [spec verification report](https://app.zenhub.com/files/184271254/38a8c611-a91d-468b-b55d-b9e86c3d5c7a/download) from after the report tool was first finished

**Comment by Elaine-Krauss-TCG** [comment]
The following are believed to possibly be errors with the spec spreadsheets:

INDIVIDUAL_RECEIPT
 - contributor_employer - should be marked as conditionally required
 - contributor_occupation - should be marked as conditionally required

NATIONAL_PARTY_EARMARK_MEMOS
 - transaction_type_identifier - should be marked as required

NATIONAL_PARTY_EARMARK_RECEIPTS
 - transaction_type_identifier - typo in the TTI: "RECIEPT" -> "RECEIPT"
 - contributor_last_name - should _not_ be marked as conditionally required
 - contributor_first_name - should _not_ be marked as conditionally required

OFFSET_TO_OPERATING_EXPENDITURES
 - contributor_organization_name - should be marked as conditionally required
 - contributor_last_name - should be marked as conditionally required
 - contributor_first_name - should be marked as conditionally required

PAC_RECEIPT
 - transaction_type_identifier - should be marked as required

PAC_RETURN
 - transaction_type_identifier - should be marked as required

PARTNERSHIP_RECOUNT_ACCOUNT_RECEIPT
 - aggregation_group - should be marked as required

**Comment by GreggMoreland** [comment]
All of the items identified in the specs have now been updated.

**Comment by Elaine-Krauss-TCG** [comment]
Thanks to Gregg's quick work, the script is now reporting zero errors!
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/80ad7278-93ae-4fcd-b64d-5f3e48d796d4)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review cannot be completed to verify information BA's are requiring. This is up to BA's to verify output of this ticket. Moving to stage ready without QA review.
