### ISSUE TITLE
Defect -  "Earmark Memo" the transactions table is not displaying the transaction type "Earmark Memo" 

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#833]
This defect is being written for after creating an "Earmark Memo" the transactions table is not displaying the transaction type "Earmark Memo" as shown in screenshot below. This was tested in both DEV and STAGE environments.

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8a8e125d-ec3a-4fce-b960-ef454748c2f3](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8a8e125d-ec3a-4fce-b960-ef454748c2f3))

DEV

Note: The isDependentChild property in the TransactionType class, when set to true, identifies the transaction type as being the child transaction in a "double entry" transaction screen like AG and AF

Per @toddlees It has no label because it's missing from `ScheduleATransactionTypeLabels` in the front end

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-874](https://fecgov.atlassian.net/browse/FECFILE-874)

**Comment by WiseQA** [comment]
Per direction assigned "Defect" to Todd as a label change as denoted in ticket.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA review verified the fix for label not displaying is fixed. The "Earmark Memo" label is displaying in transactions table (see below screenshot).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/eff5df00-b4d0-40d7-bbdd-96ef90057064)

QA Review Completed. Moved to Stage Ready.
