### ISSUE TITLE
System to show uncoded transactions as greyed out in transaction select screen

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#834]
Business Reason

As a user, I will be able to see what transactions are available versus not so that I can see what I can use for testing purposes.

Acceptance Criteria

***Given*** the user is on the Add receipts or Add disbursements page,

  ***If*** a transaction has not yet been coded (i.e., is a dead link)

  ***Then*** the text will be 50% opacity.

Dev Notes
_PER MITCHELL: please make sure this clickable hand does not appear. the greyed out dead links should only see an arrow on hover._

### QA Notes ###
BA was to provide updated list in QA notes for verification against testing.  QA to be provided list to test against.

@GreggMoreland confirmed the following : 

Reattribution
In-Kind Receipt
	Conduit Earmark (Deposited)
	Conduit Earmark (Undeposited)
	Party In-Kind
	PAC In-Kind
	PAC Conduit Earmark (Deposited)
	PAC Conduit Earmark (Undeposited)
In-Kind Transfer
In-Kind Transfer - Federal Election Activity
Refunds of Contribution to Registered Committees
Refunds of Contribution to Unregistered Committees

NOTE: Naming of Refunds dropdown to be updated with future tickets.  Naming is passing as denoted currently in dropdown,

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-873](https://fecgov.atlassian.net/browse/FECFILE-873)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@AureliaKhorsand @GreggMoreland according to QA notes BA's are to add completed list of transactions to test against.   Please provide before testing can continue.  Thanks

**Comment by AureliaKhorsand** [comment]
@WiseQA updated. For future reference, the master list of transactions has this information and is updated each sprint - see column D "100% complete". It is located [here](https://docs.google.com/spreadsheets/d/1gdcvYQBFMeCGt-1NfVuaSTsB0sB-dl2N/edit#gid=1395788914).

**Comment by WiseQA** [comment]
Thanks appreciate adding the info needed for QA testing as denoted.

**Comment by WiseQA** [comment]
QA Review Verified the following are greyed out according to acceptance criteria in QA notes.

Reattribution shows finished but not in acceptance criteria.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/868594a7-9f65-42f7-961a-7d6cc0dc0f68)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/750bdeb5-4bfa-4d27-ab8a-183ae4b7f01c)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e18fbe8d-c2c9-473f-b899-f2777b31344c)

Naming is different than acceptance criteria list ?  Needs verified

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e300b713-d49a-4993-807e-4dae6dd06367)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6c2b1fde-0950-4cf4-856a-6d247afb6fa5)

**Transactions greyed out that shouldn't be by BA's notes:

Reattrbution**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9c5b2a36-ac34-47a6-96a7-fb05b60caefa)

Names different in Acceptance Criteria versus dropdown ?   Which names are correct ?


Acceptance Criteria:

Refund of Contribution to Federal Candidate
Refund of Contribution to Other Political Committee
Refund of Contribution to Unregistered Committee

Dropdown List

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/419401c9-122e-4c93-8ae0-550db363bb3b)

Other Transactions different in Acceptance Criteria versus dropdown ?   Which names are correct ?

Acceptance Criteria:
Partnership Recount Account Receipt (in Sprint 20, currently in code review)
Partnership National Party Headquarters Buildings Account
Partnership National Party Pres. Nominating Convention Account

Dropdown List

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c0e51423-a83d-4147-8ea1-8ab10d654e50)

Naming of transactions needs updated in Acceptance Criteria to dropdowns to verify correct greying out is correct.

@MitchellTCG @mjtravers Returning to In-Progress for BA verification of naming and verify completion of transactions.

**Comment by WiseQA** [comment]
QA review determine the following needs clarification as follows:

Below naming is different than dropdown list.   Naming needs verified and Acceptance Criteria updated to verify.

**Refund of Contribution to Federal Candidate
Refund of Contribution to Other Political Committee
Refund of Contribution to Unregistered Committee
Partnership Recount Account Receipt _(in Sprint 20, currently in code review)_
Partnership National Party Headquarters Buildings Account
Partnership  National Party Pres. Nominating Convention Account**

Reattribution is greyed out in Contributions from Individuals/Persons dropdown, but not in the completed list in acceptance criteria.

@MitchellTCG @mjtravers Returning to In-Progress for BA verification of naming and verify completion of transactions.

**Comment by GreggMoreland** [comment]
@toddlees Updated as discussed. No changes to what is displayed.

**Comment by toddlees** [comment]
Cursor is now arrow hand over disabled options

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA verified from the list in QA Notes that the following are greyed out as non coded transactions.

**Contributions from Individuals/Persons**
Reattribution
In-Kind Receipt
Conduit Earmark (Deposited)
Conduit Earmark (Undeposited)

**Contribution from Registered Filers**
Party In-Kind
PAC In-Kind
PAC Conduit Earmark (Deposited)
PAC Conduit Earmark (Undeposited)

**Transfers**
In-Kind Transfer
In-Kind Transfer - Federal Election Activity

**Refunds**  NOTE:   Naming of Refunds dropdown to be updated with future tickets.
Refunds of Contribution to Registered Committees
Refunds of Contribution to Unregistered Committees

**Other
None Listed** 

QA verified arrow on hover over greyed out transactions (non selectable) and hand on hover over non-greyed out transactions (selectable).

QA Review Completed.   Moved to Stage Ready.
