### ISSUE TITLE
Allow user to select Category Code for Form 3X Schedule B Transaction

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#835]
Business Reason

As a user, I will be able to select from a list of Category Codes for my schedule B transaction on Form 3X so that I can categorize my disbursements for bookkeeping purposes.

Acceptance Criteria

***Given*** the user is entering an "Operating Expenditure" (Schedule B transaction). Select Add a Disbursement then select Operating Expenditure.

  ***Then*** they will have the option to select one Category Code from the dropdown under "Additional Information"

  ***And*** the list will include the following in this order:

*   001 Administrative/Salary/Overhead Expenses
*   002 Travel Expenses - including travel reimbursement expenses
*   003 Solicitation and Fundraising Expenses
*   004 Advertising Expenses - including general public political advertising
*   005 Polling Expenses
*   006 Campaign Materials
*   007 Campaign Event Expenses
*   008 Transfers
*   009 Loan Repayments
*   010 Refunds of Contributions
*   011 Political Contributions
*   012 Donations

### QA Notes ###
- This is an optional field.
NOTE:  From the side panel select "Add a Disbursement"  from dropdown then select Operating Expenditures to verify this ticket.

### DEV Notes ###
- The three character numeric value is what is captured and saved for .fec file

### Design ###
null

 See full ticket and images here: [FECFILE-872](https://fecgov.atlassian.net/browse/FECFILE-872)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review updated Acceptance Criteria and QA notes for selecting from the "Add a Disbursement".   The following Category Code drop down menu is optional.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c028fd80-55bc-443e-b331-c0a661e4c055)

The following list is displayed and selectable.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/23367df6-bced-43e1-a920-0c29e99b34f9)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4d9a7a79-8d65-4847-b91e-430d89f5be10)

QA Review Completed.   Moved to Stage Ready.
