### ISSUE TITLE
Create initial Cascading Stylesheet (CSS) based on FEC Pattern Library

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#84]
**This will be a non-testable ticket**

 Business Reason 
 

As a FEC Stakeholder, I will be able to UI the compliments FEC.gov but 

 User Story 
 

As the Product Owner, I would like the CSS library to match the FEC Pattern Library so there is continuity between FEC.gov and FECFile Online but doesn't confuse the user in believing they are on FEC.gov; this will also position to app to follow 508 compliance best practices.
 

 Acceptance Criteria 
 
- [x] All tags should be based on FEC Typography Pattern Library found here: https://fec-pattern-library.app.cloud.gov/docs/typography.html
Create the following SCSS and CSS files: 
- [x] _variables.scss (Several Class adjusted using PrimeNGs SCSS)
- [x] _variables_light.scss (Several Class adjusted using PrimeNGs SCSS)
- [x] theme.css (Several Class adjusted using PrimeNGs SCSS)
- [x] Update the following tags: a, label, and input
- [x] Create class for buttons
- [x] CSS should be clean and minimalist. It should be uploaded to the FECfile-web-app repo
Attach any needed or associated assets, e.g. fonts
- [x] Create Fonts.css
- [x] typography.css
Upload the attached fonts below:
[https://app.zenhub.com/files/306118986/90b9296b-a647-44c0-b6b6-6e3bca462676/download](https://app.zenhub.com/files/306118986/90b9296b-a647-44c0-b6b6-6e3bca462676/download)

 Tasks 
 
- [x] Load files up on Joint Google drive for Matt to access
- [x] Update CSS on Github as needed

### QA Notes ### 
  
QA will be performed by UX not QA or Devs
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
Here is the CSS so far:
[https://app.zenhub.com/files/306118986/99efab77-0312-475d-901a-ea55e77f8669/download](https://app.zenhub.com/files/306118986/99efab77-0312-475d-901a-ea55e77f8669/download)

**Comment by MitchellTCG** [comment]
Here are the Fonts that need to be loaded on the site:
[https://app.zenhub.com/files/306118986/ed0e98bb-c190-405a-ac7f-0500f121ddc7/download](https://app.zenhub.com/files/306118986/ed0e98bb-c190-405a-ac7f-0500f121ddc7/download)

**Comment by AureliaKhorsand** [comment]
**Refinement meeting 2/2/22:** Adjust the ticket/acceptance criteria to reflect the intended effect on the app. Need more discussion on approach. Mitchell will discuss with devs and Robert.

A user story is not needed, but need to make the case for working on this story.
