### ISSUE TITLE
"Save & add another Memo" button on edit screen not routing

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#845]
To reproduce the issue:

1\. Create a new JF Transfer transaction and save using the "Save..." button to immediately open the create screen for a memo such as "Individual Joint Fundraising Transfer Memo"

  2\. Create a new memo transaction and save using the "Save & veiw all transactions" button

  3\. From the transaction 

  4\. From the "Manage Your Transactions" table, click to edit the new memo transaction just created

  5\. In the edit memo screen, click the "Save & add another Memo" button.

  6\. The screen form will blank out the field inputs but we will actually still be on the edit screen of the existing memo.

The button is assuming the page is on the create a transaction screen and not handling the case where the page needs to be routed to the create transaction screen for this particular transaction type.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-870](https://fecgov.atlassian.net/browse/FECFILE-870)

**Comment by MitchellTCG** [comment]
OBE
