### ISSUE TITLE
Update Transaction Entry Form Buttons (Tier 1 with no Tier 2 -- Parent with no Child)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#855]
***Task:*** Update each of the following transaction types to reflect the available buttons. These are Single PARENT Transaction (no option for child transactions).

Acceptance Criteria

*   Given the user is on one of the following transactions,
*   Then they will have the ability to:
    _Save_
    _Cancel_

LIST OF (Completed) TRANSACTIONS (Schedule A - Receipts) - (Total 33):

*   Individual Receipt
*   Tribal Receipt
*   Returned/Bounced Receipt
*   Unregistered Receipt from Person
*   Unregistered Receipt from Person - Returned/Bounced Receipt
*   Party Receipt
*   Party Returned/Bounced Receipt
*   PAC Receipt
*   PAC Returned/Bounced Receipt
*   Transfer
*   Refund of Contribution to Unregistered Committee
*   Offset to Operating Expenditures
*   Other Receipts
*   Individual Receipt - Non-Contribution Account
*   Other Committee Receipt - Non-Contribution Account
*   Business/Labor Organization Receipt - Non-Contribution Account
*   Individual Recount Receipt
*   Party Recount Receipt
*   PAC Recount Receipt
*   Tribal Recount Receipt
*   Individual National Party Recount/Legal Proceedings Account
*   Party National Party Recount/Legal Proceedings Account
*   PAC National Party Recount/Legal Proceedings Account
*   Tribal National Party Recount/Legal Proceedings Account
*   Individual National Party Headquarters Buildings Account
*   Party National Party Headquarters Buildings Account
*   PAC National Party Headquarters Buildings Account
*   Tribal National Party Headquarters Buildings Account
*   Individual National Party Pres. Nominating Convention Account
*   Party National Party Pres. Nominating Convention Account
*   PAC National Party Pres. Nominating Convention Account
*   Tribal National Party Pres. Nominating Convention Account
*   ***Refund of Contribution to Unregistered Committee***

(Schedule B - Disbursements) (Total 13):

*   Operating Expenditure
*   Credit Card Payment for Operating Expenditure
*   Staff Reimbursement for Operating Expenditure
*   Payment to Payroll for Operating Expenditure
*   Void of Operating Expenditure
*   Other Disbursement
*   Credit Card Payment for Other Disbursement
*   Staff Reimbursement for Other Disbursement
*   Payment to Payroll for Other Disbursement
*   Void of Other Disbursement
*   Non-contribution Account Credit Card Payment
*   Non-contribution Account Staff Reimbursement
*   Non-contribution Account Payment to Payroll

Wireframes

![User Journey - P2]([https://user-images.githubusercontent.com/31663028/226462518-4b5254b7-388f-4161-bccf-55ae9aaef377.jpg](https://user-images.githubusercontent.com/31663028/226462518-4b5254b7-388f-4161-bccf-55ae9aaef377.jpg)))

Dev Notes

### QA Notes ###

- Updated Schedule B list according to the "Disbursement" accordion dropdowns, and transactions completed in Sprint 22 and Sprint 23 prior to this functionality of this ticket implemented.    ALL transactions are being tested.
- Total transactions for Schedule A listed above = 33 transactions (added overall total to list above)
- Total transactions for Schedule B listed above = 13 transactions (added overall total to list above)

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-868](https://fecgov.atlassian.net/browse/FECFILE-868)

**Comment by MitchellTCG** [comment]
early iterations can be found here: https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-project-management/56

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 

We can go over this tomorrow

CC:
@mary-tcg @JonellaCulmer

**Comment by AureliaKhorsand** [comment]
• Single PARENT Transaction (no option for child transactions)
		○ Individual Receipt
		○ Tribal Receipt
		○ Returned/Bounced Receipt
		○ Unregistered Receipt from Person
		○ Unregistered Receipt from Person - Returned/Bounced Receipt
		○ Party Receipt
		○ Party Returned/Bounced Receipt
		○ PAC Receipt
		○ PAC Returned/Bounced Receipt
		○ Transfer
		○ Refund of Contribution to Federal Candidate
		○ Refund of Contribution to Other Political Committee
		○ Refund of Contribution to Unregistered Committee
		○ Offset to Operating Expenditures
		○ Other Receipts
		○ Individual Receipt - Non-Contribution Account
		○ Other Committee Receipt - Non-Contribution Account
		○ Business/Labor Organization Receipt - Non-Contribution Account
		○ Individual Recount Receipt
		○ Party Recount Receipt
		○ PAC Recount Receipt
		○ Tribal Recount Receipt
		○ Individual National Party Recount/Legal Proceedings Account
		○ Party National Party Recount/Legal Proceedings Account
		○ PAC National Party Recount/Legal Proceedings Account
		○ Tribal National Party Recount/Legal Proceedings Account
		○ Individual National Party Headquarters Buildings Account
		○ Party National Party Headquarters Buildings Account
		○ PAC National Party Headquarters Buildings Account
		○ Tribal National Party Headquarters Buildings Account
		○ Individual National Party Pres. Nominating Convention Account
		○ Party National Party Pres. Nominating Convention Account
		○ PAC National Party Pres. Nominating Convention Account
		○ Tribal National Party Pres. Nominating  Convention Account
	• Single CHILD transaction (no option for grandchildren)
		○ Partnership Memo
		○ Earmark Memo
		○ Individual Joint Fundraising Transfer Memo
		○ Party Joint Fundraising Transfer Memo
		○ PAC Joint Fundraising Transfer Memo
		○ Tribal Joint Fundraising Transfer Memo
		○ Partnership Individual Joint Fundraising Transfer Memo
		○ Individual National Party Recount/Legal Proceedings Account JF Transfer Memo
		○ PAC National Party Recount/Legal Proceedings Account JF Transfer Memo
		○ Tribal National Party Recount/Legal Proceedings Account JF Transfer Memo
		○ Individual National Party Pres. Nominating Convention Account JF Transfer Memo
		○ PAC National Party Pres. Nominating Convention Account JF Transfer Memo
		○ Tribal National Party Pres. Nominating Convention Account JF Transfer Memo
		○ Individual National Party Headquarters Buildings Account JF Transfer Memo
		○ PAC National Party Headquarters Buildings Account JF Transfer Memo
		○ Tribal National Party Headquarters Buildings Account JF Transfer Memo
		○ Partnership Recount Account Receipt Memo
		○ Partnership National Party Recount/Legal Proceedings Account Memo
		○ Partnership National Party Headquarters Buildings Account Memo
		○ Partnership National Party Pres. Nominating Convention Account Memo
	• Transaction with option for ONE child transaction type (e.g., Partnership Receipt/Memo)
		○ Partnership Receipt
		○ Partnership Recount Account Receipt
		○ Partnership National Party Recount/Legal Proceedings Account 
		○ Partnership National Party Headquarters Buildings Account
		○ Partnership National Party Pres. Nominating Convention Account
	• Transaction with option for multiple types of child transactions (e.g., JF Transfer Memos)
		○ Joint Fundraising Transfer
		○ Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account
		○ Joint Fundraising Transfer - National Party Pres. Nominating Convention Account
		○ Joint Fundraising Transfer - National Party Headquarters Buildings Account
	• Child Transaction with option for grandchild transaction (e.g., NP Partnership Memos)
		○ Partnership Receipt Joint Fundraising Transfer Memo 
		○ Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo
		○ Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo
		○ Partnership Receipt Headquarters Buildings Account JF Transfer Memo
	• Transaction with requirement for child transaction (e.g., Earmark Receipt/Memo)
		○ In-Kind Receipt/In-Kind Out
		○ Earmark Receipt/Earmark Memo
		○ Conduit Earmark (Deposited)/Conduit Earmark Out (Deposited)
		○ Conduit Earmark (Undeposited)/Conduit Earmark Out (Undeposited)
		○ Party In-Kind Receipt/Party In-Kind Out
		○ PAC In-Kind Receipt/PAC In-Kind Out
		○ PAC Earmark Receipt/PAC Earmark Memo
		○ PAC Conduit Earmark (Deposited)/PAC Conduit Earmark Out (Deposited)
		○ PAC Conduit Earmark (Undeposited)/PAC Conduit Earmark Out (Undeposited)
		○ Earmark Receipt for National Party Recount/Legal Proceedings Account (Contribution)/Memo
		○ Earmark Receipt for National Party Pres. Nominating Convention Account (Contribution)/Memo
		○ Earmark Receipt for National Party Headquarters Buildings Account (Contribution)/Memo

**Comment by AureliaKhorsand** [comment]
@GreggMoreland this ticket is only for parents with NO option to have any memo transactions added. We need separate tickets for transactions that are completed for the other scenarios (See project-management [#56](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-project-management/56) for the different scenarios. Note that #902 already exists for single children.)

**Comment by GreggMoreland** [comment]
@toddlees I added one more to the list. This is the only one I am aware of. All the rest go to #902

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@GreggMoreland @AureliaKhorsand please add the transactions to the Acceptance Criteria we passed and tested yesterday.   These will be 704, 706, and 708.    Adding to QA testing list also.   Thanks!

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a9332c0e-3f05-42be-860b-9c9ada8b4e60)

Verified with @toddlees these transactions did not have the button change prior to QA testing on 04/04/2023.   Adding to the Schedule B list above @AureliaKhorsand as we talked these will be added to testing list.   Thanks !

**Comment by WiseQA** [comment]
Also, adding the following to Schedule B transactions list above as these were transactions completed in Sprint 22 prior to ticket being implemented.   Following will be added to QA testing and E2E testing for this ticket.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8536fa78-565b-4e5f-a959-a3657f457b7f)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2073bc13-9c1e-4ebf-b6c2-caf954c2f0c2)

**Comment by WiseQA** [comment]
QA review verified "Cancel" and "Save" buttons functionality for the following Transactions lists for Schedule A (Total 33) and Schedule B (Total 13).  **(NOTE:  This functionality will be added to e2e Testing)**

LIST OF (Completed) TRANSACTIONS (Schedule A - Receipts): - Total 33 transactions
1.	Individual Receipt
2.	Tribal Receipt
3.	Returned/Bounced Receipt
4.	Unregistered Receipt from Person
5.	Unregistered Receipt from Person - Returned/Bounced Receipt
6.	Party Receipt
7.	Party Returned/Bounced Receipt
8.	PAC Receipt
9.	PAC Returned/Bounced Receipt
10.	Transfer
11.	Refund of Contribution to Unregistered Committee
12.	Offset to Operating Expenditures
13.	Other Receipts
14.	Individual Receipt - Non-Contribution Account
15.	Other Committee Receipt - Non-Contribution Account
16.	Business/Labor Organization Receipt - Non-Contribution Account
17.	Individual Recount Receipt
18.	Party Recount Receipt
19.	PAC Recount Receipt
20.	Tribal Recount Receipt
21.	Individual National Party Recount/Legal Proceedings Account
22.	Party National Party Recount/Legal Proceedings Account
23.	PAC National Party Recount/Legal Proceedings Account
24.	Tribal National Party Recount/Legal Proceedings Account
25.	Individual National Party Headquarters Buildings Account
26.	Party National Party Headquarters Buildings Account
27.	PAC National Party Headquarters Buildings Account
28.	Tribal National Party Headquarters Buildings Account
29.	Individual National Party Pres. Nominating Convention Account
30.	Party National Party Pres. Nominating Convention Account
31.	PAC National Party Pres. Nominating Convention Account
32.	Tribal National Party Pres. Nominating Convention Account
33.	Refund of Contribution to Unregistered Committee

(Schedule B - Disbursements)  - Total 13 
1.	Operating Expenditure
2.	Credit Card Payment for Operating Expenditure
3.	Staff Reimbursement for Operating Expenditure
4.	Payment to Payroll for Operating Expenditure
5.	Void of Operating Expenditure
6.	Other Disbursement
7.	Credit Card Payment for Other Disbursement
8.	Staff Reimbursement for Other Disbursement
9.	Payment to Payroll for Other Disbursement
10.	Void of Other Disbursement
11.	Non-contribution Account Credit Card Payment
12.	Non-contribution Account Staff Reimbursement
13.	Non-contribution Account Payment to Payroll

QA Review Completed.   Moved to Stage Ready.
