### ISSUE TITLE
Implement dropdown for "Add a Transaction" on Transactions page [Report] 

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#862]
Business Reason 
 

As a user, I will be able to add a Transaction directly from the Manage your Transactions page. 

 Acceptance Criteria 
 

**Given** the user is on the (all) Transactions page of a report
**Then** they will be able to click "Add a Transaction**
**And** clarify which type of transaction:
- Add a Receipt
- Add a Disbursement
- Add Loans and Debts
- Add Other Transactions

**And when** the user clicks on Add a Receipt, they are taken to the Add a Receipt page
**And when** the user clicks on Add a Disbursement, they are taken to the Add a Disbursement page.
**And**  "Add Loans and Debts" and "Add Other Transactions" will be read-only.

 QA Note
Only Add a Receipt and Add a Disbursement will be clickable. Add loans and debts/Add Other Transactions will come later.

QA Note:  Select "Add new transaction" a dropdown list is displayed.   Labels are sentence cased.   Tested below names displayed correctly per wireframe.

- Add a receipt
- Add a disbursement
- Add loans and debts
- Add other transactions

 Dev Note
"Add Loans and Debts" and "Add Other Transactions" should be greyed out and "dead links" in this iteration. They will come "live" when we build out future schedules.

 WIREFRAME 

![862 - Implement dropdown for Add a Transaction in Manage Transactions.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a143b9d9-f54c-499a-9822-ea0b0a52f6f0)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
@mary-tcg 
@JonellaCulmer 

UPDATED

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified from the "Manage Your Transactions" table, select "+Add new transaction"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5baf665e-e805-4714-9f81-404bf8043c8b)

Verified dropdown list is displayed consisting of: Add a receipt; Add a disbursement; Add loans and debts; and Add other transactions.  (Note:  Labels are sentence cased and displayed correctly per wireframe.)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/adeb6f69-430c-4150-8038-df3a2c842b91)

Select "Add a receipt" verify "Add a receipt" page to include accordion dropdowns is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/045dda5a-16c8-454c-b469-901525db6e0e)

Select "Add a disbursement" verify "Add a disbursement" page to include accordion dropdowns is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/da6bb54d-a4f3-4dc5-b422-b3937f31bcc3)

Verified "Add loans and debts" and "Add other transactions" links are greyed out and non-selectable 

QA Review Completed.   Moved to Stage Ready.
