### ISSUE TITLE
Allow user to enter In-kind Contribution to Candidate on Schedule B 

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#863]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”In-kind Contribution to Candidate”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click(open) on the "Contributions/Expenditures to Regular Filers" Accordion link  
**Then** I can enter a transaction with the type “In-kind Contribution to Candidate"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE** (Required)
Dropdown options: Organization, Individual 
*Note - please default to Organization

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional, will be required if DATE falls outside of report dates)
-	**AMOUNT** (Required, can be negative)

# COMMITTEE /CANDIDATE INFORMATION 
#
**And** the user will be required to select a Committee using the LOOKUP, and upon selection the following will be populated:
-	**COMMITTEE ID** (Required if ENTITY is COMMITTEE)
-	**COMMITTEE NAME** (Required if ENTITY is COMMITTEE)

**And** the user will be required to select a Candidate using the LOOKUP, and upon selection the following will be populated:

- **CANDIDATE ID** (Required)
- 	**CANDIDATE  LAST NAME** (Required)
-	**CANDIDATE FIRST NAME** (Required)
-	**CANDIDATE MIDDLE NAME** (Optional)
-	**CANDIDATE PREFIX** (Optional)
-	**CANDIDATE SUFFIX** (Optional)
- **CANDIDATE OFFICE** (Required)
- **CANDIDATE STATE** (Required if CANDIDATE OFFICE is 'House' or 'Senate')
- **CANDIDATE DISTRICT** (Required if CANDIDATE OFFICE is 'House') 

# ELECTION INFORMATION 
#
-	**ELECTION CODE** (Required)
-	**ELECTION YEAR** (Required)
-	**ELECTION  DESCRIPTION** (Required if Election Code is Other)

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, user entered)
' In-kind: XX' where XX is user ended and appended to 'In-kind: '
**NOTE: System will automatically prefix the entered text with 'In-kind: '**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save
- Edit

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on SB23

 QA Note 

- ENTITY can be Organization or Individual, but should default to Organization.
- There is no aggregate on this transaction and each transaction is itemized separately.
- This is a new transaction and does not currently exist in the accordion dropdown.

 Dev Note 

- This is a new transaction and does not currently exist in the accordion dropdown and will need to be added.
- To display 'In Kind:' in the CPD, use https://primeng.org/inputnumber#prefixsuffix as an example
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=839677321) **This is a consolidated specification**

 Wireframe  

![863 - In-kind Contribution to Candidate.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/41063f13-3fa5-41cd-81cf-019b55ff23f4)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand @GreggMoreland @MitchellTCG added wireframe

**Comment by GreggMoreland** [comment]
@mary-tcg Transaction name on wireframe needs to be changed to "In-kind Contribution to Candidate"

**Comment by mjtravers** [comment]
2 things:

- The "In-Kind" text for PURPOSE OF DISBURSEMENT needs a lower case "k". This will require a change to the validation schema as well.
- Although the committee record is getting saved correctly, I'm getting "null" in the user message for the save when creating a committee:

![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/423a4ef1-ad8d-4949-87d3-dfba71b11c9e)

Sending ticket back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
During QA review the following are fixes:

1.  When adding new contact for In-kind Contribution to Candidate and select "Save & continue" when the In-kind Contribution to Candidate transaction page is displayed, it jumps to the "Committee/Candidate Information" area and highlights the "Candidate" dropdown.


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBak1hIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--af043d7648fb91b39892757bf3a9389becdd0093/image.png)

2.  Verbiage is missing under the In-kind Contribution to Candidate (see wireframe) @MitchellTCG  Need updated text as current text does not match transaction type  (NOTE:   This is OBE and not testable as wireframe verbiage is incorrect per UX review).
3.  Change "Contact Lookup" to "Contact Type"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamdhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3b8c28fc794a49f348dea64de52d3defca12dcce/image.png)

4.   Change "Committee/Candidate Information" label to "Committee/Candidate information".

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa29hIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--836502531ddb1da8295d12259133613ff14e1fda/image.png)

@MitchellTCG @mjtravers returning to In-Progress for above fixes.

Ticket #1164 to be implemented before verifying "Required fields needed for Committee/Candidate Information" section can be verified.

**Comment by WiseQA** [comment]
Placing ticket on-hold until UX decision on questions in QA review. @MitchellTCG

**Comment by Elaine-Krauss-TCG** [comment]
Per QA's requests:

"Contact Lookup" has been changed to "Contact Type" on all single-transactions
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXNoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0a44479f6ff32df9d808f38c41d5747b3d4c9bc9/image.png)

"Committee/Candidate Information" has been changed to "Committee/Candidate information" on all single-transactions
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmNoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--553851f0e0abfd0dc2b3d2569c4a24723cd181c7/image.png)


The bug where adding a contact on a two- or three-contact transaction scrolls the window halfway down the page has been fixed.

**Comment by WiseQA** [comment]
mary.honard@tcg.com to verify verbiage (if text or no text) under the transaction name for QA finding Step 2 as denoted above and update ticket as such. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2tuIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c13aa2cc1ba0b42d67e0747a752a5e4acf31272b/image.png)

**Comment by mary-tcg** [comment]
@WiseQA UX has confirmed that the given subheader text does not apply to this ticket, removal is acceptable.

Thanks Mary !

**Comment by WiseQA** [comment]
Per UX confirmation the verbiage as shown in the wireframe is not valid for this ticket.   I have marked Step 2 above as OBE due to these findings.   Removed On-Hold status.

**Comment by toddlees** [comment]
Passes CR moving to QA

**Comment by WiseQA** [comment]
QA review retested, verified the following fixes were implemented:

1.  Verified fix implement for when adding new contact for In-kind Contribution to Candidate and select "Save" the scrolling jumped to the "Committee/Candidate information" area and highlights the Candidate and the transactions page is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTR1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--91368dce326290eeddc1c29da390009f3dc2bad3/image.png)

2.  "Contact Lookup" changed to "Contact Type"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckl1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3a5ac7ef321e551976a54530ee79c8c8f2c316cb/image.png)

3.  "Committee/Candidate Information" label changed to "Committee/Candidate information"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclV1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1f2abf384f517295043cc51f9c418e093786ae3a/image.png)

Also tested upon selecting "Save" button, the Committee/Candidate information fields are required fields (refer to ticket #1164)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcll1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--338b44fd35e063979e7ccb7121c03f5d5402b157/image.png)

Verified Committee/Candidate information is saved and displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmt1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7d8cd567757a6088f0009e366dfb2e22c93a94bf/image.png)

Verified In-kind Contribution to Candidate disbursement transaction is displayed in the transactions table.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0F2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--743b606778092c1f93f0f48b436db62acc5628ec/image.png)

QA Review Completed. Moved to Stage Ready.
