### ISSUE TITLE
Allow user to enter In-kind Contribution to Other Committee on Schedule B 

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#864]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”In-kind Contribution to Other Committee ”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Contributions/Expenditures to Regular Filers" Accordion link  
**Then** I can enter a transaction with the type ”In-kind Contribution to Other Committee”
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**
Dropdown options: Organization, Individual 
*Note - please default to Organization.

---
_if CONTACT TYPE = Organization_
-	**ORGANIZATION NAME** (Required)

---
_if CONTACT TYPE = Individual_
-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional, will be required if DATE falls outside of report dates)
-	**AMOUNT** (Required, can be negative)

# COMMITTEE /CANDIDATE INFORMATION 
#
**And** the user will be required to select a Committee using the LOOKUP, and upon selection the following will be populated:
-	**COMMITTEE ID** (Required)
-	**COMMITTEE NAME** (Required)

# Additional Information 
#
-	**PURPOSE OF DISBURSEMENT** (Required, user entered)
' In-Kind: XX' where XX is user ended and appended to 'In-kind: '
**NOTE: System will automatically prefix the entered text with 'In-kind: '**
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)

---
**Then** I will be able to:
- Cancel
- Save 
- Edit

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on SB23

 QA Note 

- There is no aggregate on this transaction and each transaction is itemized separately.
- ENTITY can be Organization or Individual, but should default to Organization.
- This is a new transaction name to be added to the dropdown/accordion list.

 Dev Note 

**This is a new transaction name to be added to the dropdown/accordion list**
- To display 'In Kind:' in the CPD, use https://primeng.org/inputnumber#prefixsuffix as an example
- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=839677321) **This is a consolidated specification**

 Wireframe 

![864 - In-kind Contribution to Other Committee.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/42f434f8-45b6-42e6-948a-13bdb1472521)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand @GreggMoreland @MitchellTCG wireframe updated

**Comment by GreggMoreland** [comment]
@mary-tcg Transaction name is "In-kind Contribution to Other Committee". Please update wire

**Comment by mjtravers** [comment]
The candidate lookup is showing up in this input form and it's not in the acceptance criteria. It looks like only the committee information is needed. This will require some additional conditional logic in the validation schema so that the candidate fields that need to be required are only required for the IN_KIND_CONTRIBUTION_FOR_CANDIDATE.

Sending ticket back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
During QA review the following are fixes:

1.  When adding new contact for In-kind Contribution to Other Committee and select "Save & continue" when the In-kind Contribution to Other Committee  transaction page is displayed, it jumps to the "Committee/Candidate information" area and highlights the Committee" dropdown.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazhhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5c18e93741306efec00294c7393d8187fd9ebae6/image.png)

2.  Verbiage is missing under the In-kind Contribution to Candidate (see wireframe) @MitchellTCG Need updated text as current text doesn't fit the transaction type.  (NOTE: This is OBE and not testable as wireframe verbiage is incorrect per UX review).
3.  Change "Contact Lookup" to "Contact Type"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFFhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c9754718a6f7e658d5a60436a89a58ee743adc85/image.png)

4.  Change "Committee/Candidate Information" label to "Committee/Candidate information".

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGNhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--36434a820bb9459cfa82bf2efe697f6a292f1e27/image.png)

@MitchellTCG @mjtravers returning to In-Progress for above fixes.

Ticket #1164 to be implemented before verifying "Required fields needed for Committee/Candidate Information" section can be verified.

**Comment by WiseQA** [comment]
Placing ticket on-hold until UX decision on questions in QA review. @MitchellTCG

**Comment by Elaine-Krauss-TCG** [comment]
Per QA's requests:

"Contact Lookup" has been changed to "Contact Type" on all single-transactions
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXNoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0a44479f6ff32df9d808f38c41d5747b3d4c9bc9/image.png)

"Committee/Candidate Information" has been changed to "Committee/Candidate information" on all single-transactions
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmNoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--553851f0e0abfd0dc2b3d2569c4a24723cd181c7/image.png)


The bug where adding a contact on a two- or three-contact transaction scrolls the window halfway down the page has been fixed.

**Comment by WiseQA** [comment]
mary.honard@tcg.com to verify verbiage (if text or no text) under the transaction name for QA finding Step 2 as denoted above and update ticket as such. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0VuIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8e9113b4f53be9a0c0b2f90f4d51cf7b3cfbd928/image.png)

**Comment by mary-tcg** [comment]
@WiseQA UX has confirmed that the given subheader text does not apply to this ticket, removal is acceptable.

Thanks Mary !

**Comment by WiseQA** [comment]
Per UX confirmation the verbiage as shown in the wireframe is not valid for this ticket. I have marked Step 2 above as OBE due to these findings. Removed On-Hold status.

**Comment by toddlees** [comment]
passes CR moving to QA

**Comment by WiseQA** [comment]
QA review retested, verified the following fixes were implemented:

1.  Verified fix implement for when adding new contact for In-kind Contribution to Other Committee and select "Save" the scrolling jumped to the "Committee/Candidate information" area and highlights the Committee" and the transactions page is displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFV1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a7d02952102f436bab2aafaf089ee46ddedefef2/image.png)

2.  "Contact Lookup" changed to "Contact Type"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTR1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--54b686f87c3b41b22c61ea9cafe85553c1a75e6a/image.png)

3.  "Committee/Candidate Information" label changed to "Committee/Candidate information"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkV1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9463edad2629aae59a1087000dd6c5dcf680ecc3/image.png)

Also tested upon selecting "Save" button, the Committee/Candidate information field is a required field (refer to ticket #1164)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjB1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--58cf5dafc61d2a6afaf4058bc2f54b70a73459fc/image.png)

Verified In-kind Contribution to Other Committee disbursement transaction is displayed in the transactions table.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDB1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--be42158cdf98bbf50907e11df4cc35d6c98fa761/image.png)

QA Review Completed.   Moved to Stage Ready.
