### ISSUE TITLE
Allow user to view Committee Profile data (read-only)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#87]
Business Reason

As a Committee Administrator, I will be able to view my Committee Profile data so that I can verify it is all correct and determine if changes are needed.

Technical Tasks

*   Set up API pulls from the FECFile web app to open FEC API (public key) to get the most recent committee account data to provide the data needed for the front end web page.
*   Create read-only Angular screen under Profile -> Account menu item
*   API endpoint is [/committee/committee_id/]([https://api.open.fec.gov/developers/#/committee/get_committee__committee_id__](https://api.open.fec.gov/developers/#/committee/get_committee__committee_id__))

Acceptance Criteria

***If*** I am a Committee Administrator

  ***When*** I go to the Account page

  ***Then*** I will see Committee Profile data from Form 1 as read-only.

Fields to be shown (if no data from FEC, will be blank):

General

*   Committee ID
*   Committee Name
*   Type of Committee _(pull directly from committee_type_full field in API)_
*   Address
*   Apartment, Suite, Etc.
*   City
*   State/Province
*   Zip/Postal Code
*   Email 1
*   Website

Treasurer

*   First Name
*   Last Name
*   Address
*   Apartment, Suite, Etc.
*   City
*   State/Province
*   Zip/Postal Code
*   Telephone

Custodian of Records _(pull directly from custodian_name_full field in API)_

_Note: remove Candidate and Bank information currently in app._

![image.png]([https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/dbe1c288-cfa4-43a3-895b-71e4d2f0228a](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/dbe1c288-cfa4-43a3-895b-71e4d2f0228a))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1319](https://fecgov.atlassian.net/browse/FECFILE-1319)

**Comment by AureliaKhorsand** [comment]
Per email from Ryan Lanz over email on 2/16/22, Candidate information should be removed since it does not apply to Form 3X. We will need to add it back in, but it should only appear for Form 3 and Form 3P committees. This will need additional research when we pick this up in OP3, such as a link to the candidate's Form 2.

For Type of Committee – I strongly encourage us to add this to the page.  I personally would even like to see it added to the overall banner that currently shows a committee’s ID and name.  Committee type is going to be extremely important in the backend since it directly impacts what type of reports and schedules they need to file with the FEC.  I think we should make that transparent to the user.  If we add it, we need to add a few more committee types besides the four listed below:  https://drive.google.com/file/d/1m5vmv4uUg1-WPnvYb0Smg95A1A4hxBlI/view?usp=sharing. Please note that the codes should be used to pull the descriptions from the FEC database, not from this list.  I can provide the official types/descriptions if needed.

**Comment by AureliaKhorsand** [comment]
@mjtravers @toddlees I suspect there should be a separate API ticket to account for pulling the data from the FEC database to populate these fields. Is that correct? Or is it already in place? Let me know and I will create the appropriate ticket(s).

**Comment by mjtravers** [comment]
> @mjtravers @toddlees I suspect there should be a separate API ticket to account for pulling the data from the FEC database to populate these fields. Is that correct? Or is it already in place? Let me know and I will create the appropriate ticket(s).

@AureliaKhorsand No, we don't have a ticket yet for pulling committee data from FEC

**Comment by mjtravers** [comment]
@AureliaKhorsand I don't have a dev ticket to pull committee account data from the profile but can create one unless you have already done so. I will pull the list of committee account types you've attached into the code. I can also display the committee account type on the page header along with the ID and name and will do so

**Comment by AureliaKhorsand** [comment]
@mjtravers let's repurpose [web-api #52](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-api/52), which I had closed thinking it wasn't needed. Feel free to update it with what needs to be done technically.

@lbeaufort Paul provided the following endpoint for pulling the Form 1 data for Committee Accounts. Can you confirm this is the correct one? He said you may know. We can chat about it next week as well. [https://api.open.fec.gov/developers/#/committee/get_committees_](https://api.open.fec.gov/developers/#/committee/get_committees_)

**Comment by AureliaKhorsand** [comment]
**3/16/22 Refinement Meeting:** Laura recommended pulling directly from the FEC API endpoint, rather than building our own in FECFile Online. Could also pull from the electronically filed Form 1, but that is something we can set up later. 

Per Laura: maybe this one [click here](https://api.open.fec.gov/v1/committee/C00344234/?api_key=DEMO_KEY)

During discussion, talked about how there can be numerous banks listed on a Form 1, but there is no "primary" bank. We will remove the "Bank Information" section here, and link to additional bank information. Needs further discussion.

**Comment by MitchellTCG** [comment]
![Account.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ef3588dc-aac3-4fcc-9097-9f31b7c7885a)

**Comment by AureliaKhorsand** [comment]
During the [3/17/22 requirements meeting](https://docs.google.com/document/d/1tQ9GMhrqTDHsVHlIzKxydHEnPT1vm1fShgN-z6Jbfw8/edit#), FEC noted that committee's can have numerous banks and there is no way on Form 1 to designate a "primary" bank. The current API just shows the top one, and it's also possible to show a list of all the bank names only, but this needs design work and further analysis to determine what is necessary. See web-app #164 for Bank Information requirements.

@MitchellTCG and @mary-tcg this is ready for a wireframe for the FIELDS. Separate ticket for links for Form 1 and fec.gov forthcoming.

**Comment by MitchellTCG** [comment]
![Account - READ ONLY.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/1971ece6-e701-480d-a864-456146114d7c)

**Comment by AureliaKhorsand** [comment]
**3/23 Refinement Meeting:** Email 2 does not come over on the API, so removing for now. Telephone is only for Treasurer in this ticket, and the Committee does not have a telephone field. Determined we are keeping Treasurer last and first name separate for now, and only including name for Custodian of Records

**Comment by MitchellTCG** [comment]
wire added

removing tag

**Comment by WiseQA** [comment]
Logged in as Committee ID C00601211 verified Account page showed Committee Profile data from Form 1 as ready only as shown in wireframe.  Visual test verifying read only page.

QA review completed.  Moved to Stage Ready.
