### ISSUE TITLE
Update e2e tests for latest develop branch

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#875]
The e2e tests are throwing errors on the latest release branch of sprint-20

***Tasks***

*   Run e2e tests and investigate tests that are failing
*   Update test code or create a ticket to list of bugs in the code the tests caught

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

[FECFILE-862](https://fecgov.atlassian.net/browse/FECFILE-862)

**Comment by mjtravers** [comment]
Screenshot of passing e2e tests:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/07509e99-4bad-4dfb-a13e-ed99c557f1e8)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review completed as visual inspection to date on e2e testing.   Reports will be future inspection with DEV.

QA Review Completed.   Moved to Stage Ready.
