### ISSUE TITLE
Bug: Convert Validate service to a simple Utils class and fix -0.00

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#876]
The Validate service that manages the transaction type form validation using the JSON schema files was implemented as an Angular service. As the code base has evolved it has become apparent that instantiating the Valditate class as a service is unnecessary and is limiting for our double-entry transaction forms.

In addition, it was discovered on tickets #685 and #702 that have the negative AmountOnly rule for the DISBURSEMENTS schema that a value of -0.00 does not trigger the conditional schema rule because the data in the schema validation does not include the transaction_type_identifier. Currently, the data available for conditional schema rules only includes the data fields that have form inputs on the screen.

**Task**

- Create a shared/utils/valdiate.utils.ts with a ValidateUtils class
- Convert the Validate service to the ValidateUtils class
- Refactor transaction components to use the ValidateUtils class
- Remove the Validate service from the code base
- Pass a full transaction payload packet to the custom validate function callback for the validator so the -0.00 bug is fixed.

**QA Notes**
Ticket passes if all unit tests pass after code is changed as above.
### QA Notes ### 
 In addition, it was discovered on tickets #685 and #702 that have the negative AmountOnly rule for the DISBURSEMENTS schema that a value of -0.00 does not trigger the conditional schema rule because the data in the schema validation does not include the transaction_type_identifier. Currently, the data available for conditional schema rules only includes the data fields that have form inputs on the screen.

**Task**

- Create a shared/utils/valdiate.utils.ts with a ValidateUtils class
- Convert the Validate service to the ValidateUtils class
- Refactor transaction components to use the ValidateUtils class
- Remove the Validate service from the code base
- Pass a full transaction payload packet to the custom validate function callback for the validator so the -0.00 bug is fixed.

**QA Notes**
Ticket passes if all unit tests pass after code is changed as above.
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Deployed to STAGE. Ready for QA on STAGE.

**Comment by WiseQA** [comment]
QA review verified bug fix for "Disbursements" transactions that  $-0.00 is not accepted value and error populates  'Amount must be negative (example: -$20.00)'

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b22df205-935c-41e5-be81-4402faa597b5)

AMOUNT MUST be a non-zero negative value to save, and max value is -$0.01.
