### ISSUE TITLE
Allow user to recover a deleted contact

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#88]
Business Reason 
 

As a Committee Administrator, I will be able to recover a deleted contact so that I can restore it to Contact Management if it was deleted in error, or it is needed again.

 Acceptance Criteria 
 

**If** I am a user
**And** I go to Contact Management
**Then** I can see an option to "Restore deleted contact(s)" _(and this link will be disabled if there are no deleted contacts)_
**And when** I open to "Restore deleted contact(s)", I will view deleted contacts (including pagination)
**Then** I will be able to restore one or multiple deleted contact(s) to the Contact Management list.

 Dev Tasks:
1. refactor old code
2. unit tests
3. documentation
4. logging in the back-end
5. accessible in the UI

# Wireframes 
#
![88  - Restore deleted contacts link.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/aac63eff-6595-44f2-adef-f37abbc09052)

![88  - Restore deleted contacts modal.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/673e088c-7d9d-40d7-b324-2cd1f8e0532c)

### QA Notes ### 
 Restored contacts should appear back in the Contact Management list in the default Contact sort order (alphabetical).
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @mary-tcg @JonellaCulmer 
Updated

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @WiseQA  added wireframe with pagination

**Comment by toddlees** [comment]
@MitchellTCG @AureliaKhorsand Should the "Restore selected" button be disable until at least one contact is selected?

Do we need the parenthetical plural for contacts if "Restore deleted contacts" is still pretty clearly the place to restore a single contact?

**Comment by AureliaKhorsand** [comment]
@toddlees executive decisions while Mitchell is out: Yes, disable the restore button unless one contact is selected (AC is updated). Keep the parenthetical plural as is in the wireframe and we can change it later if needed.

**Comment by toddlees** [comment]
Thanks!

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@toddlees @mjtravers so all but my recent contacts the "delete" trash can is not accessible.   Is there a reason ?

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f57ae0e0-05bf-4e11-ab80-499061d55c78)

**Comment by WiseQA** [comment]
QA Review verified a contact can be deleted and restored

Created new contact (e.g., Testing Delete, Contact) and verified the Delete column displayed an active Trash Can.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/751f6b02-7608-4d3b-91ad-dab316a0790f)

Select trash can verify following popup dialog box is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cd1e3dd6-5389-44f7-af68-fdd23f807308)

Select "No" Manage Contacts page is redisplayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/94ebb978-f663-4d5a-82de-b55348524a49)

Select "Yes" contact has been removed from Manage Contacts.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4d69d36f-04e7-41b9-a63b-90b06db7a10a)

Select contact to be restored (e.g., Testing Delete, Contact), then select the restore selected button.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5ab4fef9-9d3b-4331-bb0c-3849eaa61ee8)

Verify contact has been restored in the Manage Contacts table and the Delete column redisplays an active Trash Can.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7943d49a-85a0-496f-ad57-053354582fea)

QA Review Completed.   Moved to Stage Ready.
