### ISSUE TITLE
Allow user to enter Individual Refund - Non-contribution Account on Schedule B (Group A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#890]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Individual Refund - Non-contribution Account”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Individual Refund - Non-contribution Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-Individual Only

-	**LAST NAME** (Required)
-	**FIRST NAME** (Required)
-	**MIDDLE NAME** (Optional)
-	**PREFIX** (Optional)
-	**SUFFIX** (Optional)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
**Note:** Although Aggregate is not displayed, the Aggregation Group must be NON_CONTRIBUTION_ACCOUNT.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (System-Generated)
-Text: ‘Non-contribution Account Refund’
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)
---
**Then** I will be able to:

-Cancel
- Save
- Edit
---
**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group **"NON_CONTRIBUTION_ACCOUNT"**:
- Individual Receipt - Non-Contribution Account
- Other Committee Receipt - Non-Contribution Account
- Business/Labor Organization Receipt - Non-Contribution Account

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file

 QA Note
- Note: There should be no Aggregate calculated or displayed, but the amount is included in aggregates in Schedule A via the Aggregation Group.
- Note that these amounts must be _subtracted_ from the aggregates in Schedule A that share the same entity.

 Dev Note 

- Note: Aggregate is not calculated, but there IS an aggregation group to aggregate these amounts with some Schedule A transactions.
- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=632321712) **Note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Individual Refund - Non-contribution Account a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2d6d5a02-e643-4a97-9721-1a77fa4aae3d)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c6cd9886-9f35-4666-8630-606357aeba54)

Verified amount can be negative value.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2374b176-d2e6-4707-9def-3e02a04f24cc)

Verify "Purpose of Disbursement (System-Generated) field text is displayed:  Non-contribution Account Refund 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4e732aa9-fa0a-4d77-ab27-ce36e0f9e7ed)

Verified transaction is displayed in transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ec5a4dde-45bf-405d-bf6c-5afd21cc0502)

QA Review Completed.  Moved to Stage Ready.

**Comment by MitchellTCG** [comment]
**Moved out of Sprint 22 during Demo due to Calculation Error.** 

**Awaiting further analysis: BAs and Devs need to discuss the paradigm shift of subtracting Aggregation Groups.**

**Comment by AureliaKhorsand** [comment]
New calculation requirement is in the ACs. Additional 1 point of work, but keeping original points for reporting purposes.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA Review retested.

QA review verified when selecting "Add a disbursement" then select Individual Refund - Non-contribution Account a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ecd356b3-0325-482d-83ec-b0dabf39dec4)


Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed "Non-contribution Account Refund"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1efea8cc-dfb7-4365-b8f5-cf6e54b15a14)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/721f3f8e-e964-46a5-9856-6df3e32a33d3)

QA review entered same contact for Individual Refund - Non-contribution Account (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/40be1999-5695-4ccf-9df6-cd0667a482d9)

QA Review Completed.   Moved to Stage Ready.
