### ISSUE TITLE
Allow user to enter Other Committee Refund - Non-contribution Account on Schedule B (Group E)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#891]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Other Committee Refund - Non-contribution Account”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Other Committee Refund - Non-contribution Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
#
-	**CONTACT TYPE**(Read-only, includes LOOKUP)
-- Committee Only
-	**COMMITTEE NAME** (Required)
-	**COMMITTEE ID** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required, can be negative)
**Note:** Although Aggregate is not displayed, the Aggregation Group must be NON_CONTRIBUTION_ACCOUNT.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (System generated)
--Text must read:  ‘Non-contribution Account Refund’
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)
---
**Then** I will be able to:
- Cancel
- Save
- Edit
---
**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group "NON_CONTRIBUTION_ACCOUNT":
- Other Committee Receipt - Non-contribution Account
- Business/Labor Organization Receipt - Non-contribution Account

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SB29.

 QA Note
- Note: There should be no Aggregate calculated or displayed, but the amount is included in aggregates in Schedule A via the Aggregation Group.

 Dev Note 

- Note: Aggregate is not calculated, but there IS an aggregation group to aggregate these amounts with some Schedule A transactions.
- BENEFICIARY COMMITTEE FEC ID and NAME will pull from PAYEE ORGANIZATION NAME and the Committee ID, similar to functionality in Schedule A.
- [ ] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=632321712) **Note this is a consolidated specification.**

 Wireframe 

![891 - Other Committee Refund - Non-contribution Account.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/33a7fbf1-5281-47ed-a666-709a6e087775)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
Need to confirm that since we're pulling Beneficiary Committee Name/ID from the Entity, that we do not need to show on the front-end.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Wire is attached
please be aware I do not currently see this transaction under the Other Expenditure Accordion on Stage per the AC

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/be014028-3165-4eb9-8dd9-84c429362902)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by AureliaKhorsand** [comment]
Removed the following from the list of transactions that share the aggregation group since they would never have the same entity, thus cannot be aggregated together:
- Individual Receipt - Non-contribution Account

**Comment by WiseQA** [comment]
QA review verified updated aggregation group listed for this ticket.   Thanks for the update.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Other Committee Refund - Non-contribution Account transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9f0edf4e-486b-4a5e-a8d9-0761bbda37b5)

Contact type is Committee Only.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1fb357e4-b6cd-4cf8-ae9f-1cca55ab8b62)

Verified PURPOSE OF DISBURSEMENT (System generated) and text reads: ‘Non-contribution Account Refund’

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/aadea38e-737e-4d2d-bf47-f1516de07e53)

Verified "No Aggregate" field is not displayed on form.  **(NOTE:   Wireframe incorrect showing Aggregate field)**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/15738c91-82d4-46d1-a359-2136c6a939d4)

QA review entered same contact for Other Committee Refund - Non-contribution Account (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount. (Tested with Other Committee Receipt - Non-contribution Account)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3f3aab0f-5e5c-40b3-b8ad-cc417aae1b54)

QA Review Completed. Moved to Stage Ready.
