### ISSUE TITLE
Allow user to enter Business/Labor Organization Refund - Non-contribution Account on Schedule B (Group C)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#892]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Business/Labor Organization Refund - Non-contribution Account”** transaction on Schedule B of a Form 3X report so that I can accurately report on my committee's transactions.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**Then** Add a disbursement
**Then** Click (open) on the "Other Expenditures" Accordion link  
**Then** I can enter a transaction with the type “Business/Labor Organization Refund - Non-contribution Account"
**Then** I will be required to enter the following information (unless otherwise noted):

---

 Contact 
# 
-	**CONTACT TYPE** (Read-only, **INCLUDES LOOKUP**)
-Organization only
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Expenditure Information 
#
-	**DATE** (Required)
-	**MEMO ITEM** (Optional)
-	**AMOUNT** (Required)
**Note:** AMOUNT can be a negative amount
**Note:** Although Aggregate is not displayed, the Aggregation Group must be NON_CONTRIBUTION_ACCOUNT.

# Additional information 
#
-	**PURPOSE OF DISBURSEMENT** (System generated)
--Text must read:  ‘Non-contribution Account Refund’
-	**NOTE OR MEMO TEXT** (Optional)
-	**CATEGORY CODE** (Optional)
---
**Then** I will be able to:

-Cancel
- Save
- Edit
---
**And** upon saving, the amount will **BE SUBTRACTED** from the aggregates of the same entity for Schedule A transactions with the Aggregation Group "NON_CONTRIBUTION_ACCOUNT":
- Individual Receipt - Non-contribution Account
- Other Committee Receipt - Non-contribution Account
- Business/Labor Organization Receipt - Non-contribution Account

**And** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file

 QA Note
- Note: There should be no Aggregate calculated or displayed, but the amount is included in aggregates in Schedule A via the Aggregation Group.
- Note that these amounts must be _subtracted_ from the aggregates in Schedule A that share the same entity.

 Dev Note 

- Note: Aggregate is not calculated, but there IS an aggregation group to aggregate these amounts with some Schedule A transactions.
- [ ] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=632321712) **Note this is a consolidated specification.**

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting "Add a disbursement" then select Business/Labor Organization Refund - Non-contribution Account a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b2d38b38-139c-4623-af87-e81cc6d6bdf6)

Verify Confirm popup window is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/800f09a5-cbba-4ef6-aa7c-c6b127b4b385)

Verified amount can be negative value.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/47c431fc-aa87-4f9a-9629-3b8904ee8985)

Verify "Purpose of Disbursement (System-Generated) field text is displayed: Non-contribution Account Refund

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b798996a-cdb9-469e-9784-ce5b3bafc35e)

Verified transaction is displayed in transactions table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/deaaf197-2973-44d0-b459-321d75737245)

QA Review Completed. Moved to Stage Ready.

**Comment by MitchellTCG** [comment]
**Moved out of Sprint 22 during Demo due to Calculation Error.** 

**Awaiting further analysis: BAs and Devs need to discuss the paradigm shift of subtracting Aggregation Groups.**

**Comment by AureliaKhorsand** [comment]
New calculation requirement is in the ACs. Additional 1 point of work, but keeping original points for reporting purposes.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA Review retested.

QA review verified when selecting "Add a disbursement" then select Business/Labor Organization Refund - Non-contribution Account a transaction is created and is editable once saved.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/65b55d38-c20d-4198-a445-9d578b10930e)

Verified Purpose of Disbursement (System-Generated) field is displayed and text in field is displayed "Non-contribution Account Refund"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a4239c73-23c0-4b07-ae55-d9fb160374a2)

Verified "No Aggregate" field is not displayed on form.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/14c99ae4-32df-49e1-a5cb-b5e598677ed8)

QA review entered same contact for Business/Labor Organization Refund - Non-contribution Account (same aggregation group) for a disbursement and receipt. Below screenshot shows where Aggregate is showing the correct aggregate amount.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/861bd02a-ee83-4511-9059-7dabeb806e04)

QA Review Completed.  Moved to Stage Ready.
