### ISSUE TITLE
Grant team access to project tools

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#9]
**Task:** Get TCG team access to project tools

**Acceptance Criteria:**
1. Team has access to GitHub/ZenHub
2. Team has access to previous JIRA instance (for research purposes)
3. Team has access to FEC Slack

**Comment by alexander-lin** [comment]
Status as of 12/13: New QA Engineer (Shelly Wise) needs access to Github/Zenhub, FEC Slack. (Requested by Laura.) Alex to pull JIRA instance results in HTML (as Laura did) and post to shared space.

**Comment by AureliaKhorsand** [comment]
Issue moved to [fecgov/fecfile-project-management #17](https://github.com/fecgov/fecfile-project-management/issues/17) via [**ZenHub**](https://www.zenhub.com/)

**Comment by AureliaKhorsand** [comment]
Marked as OBE. Created in wrong repo.
