### ISSUE TITLE
Update Transaction Entry Form Buttons (Tier 1 with Tier 2 and Tier 2 - Single Child)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#902]
***Tasks:***

1\. Update each of the following transaction types to reflect the available buttons. These are Single CHILD transaction (no option for grandchildren).

  2\. Update "Save & Add Memo" dropdown lists to include Group Name followed by the list of available memos in short-form (specified below).

Acceptance Criteria

*   Given the user is on one of the following transactions,
*   Then they will have the ability to:
    _Save_
    _Cancel_
    _Save & add memo_

**Save & Add Memo** will display a dropdown which will display a _Group Name_ header and include a list of the _Memo Name_ transactions that can be created

***LIST OF TRANSACTIONS with _Group Name_ and _List Items (Memo Name beside each transaction is the item name in the list that will link to that transaction)_***

1.  Schedule A (Receipts) - Multiple Options (See wireframes)

       #

       —

       ***Group Name: Joint Fundraising Transfer Memo***

       ***List Items: Individual, Party, PAC, Tribal, Partnership***

*   ***Joint Fundraising Transfer***
*   Individual Joint Fundraising Transfer Memo _(Memo Name: Individual)_
*   Party Joint Fundraising Transfer Memo _(Memo Name: Party)_
*   PAC Joint Fundraising Transfer Memo _(Memo Name: PAC)_
*   Tribal Joint Fundraising Transfer Memo _(Memo Name: Tribal)_
*   Partnership Joint Fundraising Transfer Memo _(Memo Name: Partnership)_***Dead link until transaction is complete***

—

  ***Group Name: JF Transfer - National Party Recount/Legal Proceedings Account Memo***

  ***List Items: Individual, PAC, Tribal, Partnership***

*   ***Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account***
*   Individual National Party Recount/Legal Proceedings Account JF Transfer Memo _(Memo Name: Individual)_
*   PAC National Party Recount/Legal Proceedings Account JF Transfer Memo _(Memo Name: PAC)_
*   Tribal National Party Recount/Legal Proceedings Account JF Transfer Memo _(Memo Name: Tribal)_
*   Partnership National Party Recount/Legal Proceedings Account JF Transfer Memo _(Memo Name: Partnership)_***Dead link until transaction is complete***

       —

       ***Group Name: JF Transfer - National Party Pres. Nominating Convention Account Memo***

       ***List Items: Individual, PAC, Tribal, Partnership***
*   ***Joint Fundraising Transfer - National Party Pres. Nominating Convention Account***
*   Individual National Party Pres. Nominating Convention Account JF Transfer Memo _(Memo Name: Individual)_
*   PAC National Party Pres. Nominating Convention Account JF Transfer Memo _(Memo Name: PAC)_
*   Tribal National Party Pres. Nominating Convention Account JF Transfer Memo _(Memo Name: Tribal)_
*   Partnership National Party Pres. Nominating Convention Account JF Transfer Memo _(Memo Name: Partnership)_***Dead link until transaction is complete***

       —

       ***Group Name: JF Transfer - National Party Headquarters Buildings Account Memo***

       ***List Items: Individual, PAC, Tribal, Partnership***
*   ***Joint Fundraising Transfer - National Party Headquarters Buildings Account***
*   Individual National Party Headquarters Buildings Account JF Transfer Memo _(Memo Name: Individual)_
*   PAC National Party Headquarters Buildings Account JF Transfer Memo _(Memo Name: PAC)_
*   Tribal National Party Headquarters Buildings Account JF Transfer Memo _(Memo Name: Tribal)_
*   Partnership National Party Headquarters Buildings Account JF Transfer Memo _(Memo Name: Partnership)_***Dead link until transaction is complete***

       —

1.  Schedule A (Receipts) - One Option (see wireframes)

       #

       —

       ***List Item: Partnership Receipt Memo***

*   ***Partnership Receipt***
*   Partnership Receipt Memo _(Memo Name: Partnership Receipt Memo)_

       —

***List Item: Partnership Recount Account Receipt Memo***

*   ***Partnership Recount Account Receipt***
*   Partnership Recount Account Receipt Memo _(Memo Name: Partnership Recount Account Receipt Memo)_

       —

***List Item: Partnership National Party Recount/Legal Proceedings Account Receipt Memo***

*   ***Partnership National Party Recount/Legal Proceedings Account Receipt***
*   Partnership National Party Recount/Legal Proceedings Account Memo _(Memo Name: Partnership National Party Recount/Legal Proceedings Account Memo)_

       —

***List Item: Partnership National Party Headquarters Buildings Account Receipt Memo***

*   ***Partnership National Party Headquarters Buildings Account Receipt***
*   Partnership National Party Headquarters Buildings Account Memo _(Memo Name: Partnership National Party Headquarters Buildings Account Memo)_

       —

***List Item: Partnership National Party Pres. Nominating Convention Account Receipt Memo***

*   ***Partnership National Party Pres. Nominating Convention Account Receipt***
*   Partnership National Party Pres. Nominating Convention Account Memo _(Memo Name: Partnership National Party Pres. Nominating Convention Account Memo)_

       —

1.  Schedule B (Disbursements) - One Option (see wireframes)

       #

—

  **List Item: Credit Card Memo for Operating Expenditure **

*   ***Credit Card Payment for Operating Expenditure***
*   Credit Card Memo for Operating Expenditure

       —

***List Item: Staff Reimbursement Memo for Operating Expenditure***

*   ***Staff Reimbursement for Operating Expenditure***
*   Staff Reimbursement Memo for Operating Expenditure

       —

       **List Item: Payroll Memo for Operating Expenditure **
*   ***Payment to Payroll for Operating Expenditure***
*   Payroll Memo for Operating Expenditure

       ___

***List Item: Credit Card Memo for Other Disbursement***

*   ***Credit Card Payment for Other Disbursement***
*   Credit Card Memo for Other Disbursement

       —

**List Item: Staff Reimbursement Memo for Other Disbursement *

*   ***Staff Reimbursement for Other Disbursement***
*   Staff Reimbursement Memo for Other Disbursement

       —

***List Item: Payroll Memo for Other Disbursement***

*   ***Payment to Payroll for Other Disbursement***
*   Payroll Memo for Other Disbursement

Wireframes

1.  One Option

       #

       ![One Option.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/49975529-3e4f-420f-b83c-78e7f481a012](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/49975529-3e4f-420f-b83c-78e7f481a012))

1.  Multiple Options

       #

       ![Multiple Options.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8534c220-3b20-4b97-9e4e-2dc1a41ba3e4](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8534c220-3b20-4b97-9e4e-2dc1a41ba3e4))

Dev Notes

There are some transaction screens were not moved into the standardized button objects shared out of the transaction-navigation-controls.model.ts... the STANDARD_CONTROLS, STANDARD_CONTROLS_MINIMAL and getChildNavigationControls() function. This ticket should include refactoring those transaction_type classes to use the above standardized objects.

1.  Styling

       #

       Hexcode for button color: #F77B42

       Hexcode for text: #212121

       Bold text

       Leave 16px padding left and right

### QA Notes ###

**LIST OF TRANSACTIONS with _Group Name_ and _List Items (Memo Name beside each transaction is the item name in the list that will link to that transaction)_**

There are two pieces of functionality this ticket is updating:
1.  Updating each of the following transaction types to reflect the available buttons. These are Single CHILD transaction (no option for grandchildren).
2. Updating "Save & Add Memo" dropdown lists to include Group Name followed by the list of available memos in short-form.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-857](https://fecgov.atlassian.net/browse/FECFILE-857)

**Comment by toddlees** [comment]
@GreggMoreland 
- We're missing `PARTNERSHIP RECEIPT` and `PARTNERSHIP RECEIPT MEMO` Tier 1 root and Teir 2 respectively.  Suggested AC below.
- I'm seeing some inconsistency between the 'memo name' in schedule a and b.  The pattern seems to be:
```
schedule a memo name = "{kind-of-entity-recorded-in-memo}" (unless there's one option and it's the full name).
schedule b memo name = "{kind-of-entity-recorded-in-memo} Memo"
```
Should we put "Memo" at the end of the Schedule A options or take "Memo" off the end of the Schedule B options? Or make the Schedule B options the full name to be consistent with the one-to-one transactions like Partnership Recount Account Receipt and Partnership Recount Account Receipt Memo?
- should `JF Transfer - National Party Headquarters Buildings Account Memo` be `Joint Fundraising Transfer - National Party Headquarters Buildings Account Memo`
- `ConventionAccount` should be `Convention Account `?


---
**Group Name: Partnership Receipt**
**List Item: Partnership Receipt Memo**
- **Partnership Receipt**
- Partnership Receipt Memo _(Memo Name: Partnership Receipt Memo)_
---

**Comment by AureliaKhorsand** [comment]
@toddlees agree that we should add in Partnership Receipt ACs here. I've added them in. Your second to last question on JF Transfer actually has me thinking we should make all the group names "JF Transfer" to shorten them, as we had permission from Ryan to use the acronym for these dropdowns. I've updated that too. Yes, a space should be added for Convention Account and I've also done that.  Stand by for a decision on schedule A/B inconsistency in naming...

@MitchellTCG @GreggMoreland  I'm inclined to keep the names the way they are between Schedule A and B. So, in Schedule B we say "memo", but don't in Schedule A. The way the transactions are labeled makes that make more sense to me, but open to other ideas.

**Comment by toddlees** [comment]
Thanks!  One more clarification, all of the tier 2 transactions in this ticket are allowed to have siblings (tier 2 transactions with the same root tier 1)
Is that correct?

also, here's the wireframe i used to confirm tier 1 parent functionality:![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/1372469a-d2de-4bd7-b4ed-461e661375b1)

**Comment by AureliaKhorsand** [comment]
@toddlees correct - for now, the only Tier 1 transactions that do not allow for multiple Tier 2's are Earmark receipts, and they are not included in this ticket since they're a separate screen.

**Comment by GreggMoreland** [comment]
@AureliaKhorsand @toddlees @MitchellTCG The reason for the naming in Schedule B is because the original master spreadsheet and all the original documentation and specs just had the shorter names, Credit Card Memo, Payroll Memo, Reimbursement Memo as the transaction names, and those same three transaction names are used three more times in Schedule B. So they retain their name but I made the distinction of 'operating expenditure' or 'other disbursement' etc. at the end.

**Comment by toddlees** [comment]
This just seems hard to keep track of from a planning perspective, using different naming conventions for the same components. For some the group name is the memo for others its the parent
so as written, it looks like this:
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/767a671a-9923-47dc-9c8c-4fbc090742b2)
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/fad5113f-d659-4053-a28a-41d82845e979)
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/c1944d41-2580-4283-9029-d335131eb777)

To me this is pretty confusing that for jf transfer, the group and not the children says 'memo', but for the other two, the group doesn't say 'memo' but the options do. and the third option is neither the full name nor how a shortened name appears in the first example

Would it not make more sense to leave the first case as is, and the other two scenarios (schedule a+one memo, schedule b+one memo) handle like so?
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/f4eeda54-f6ae-4bfc-adda-45cd994006ee) 
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/1ef743ce-5446-447e-9e4d-0c76c93e892a)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Wires are updated

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
**QA review verified that the below "Receipt"  Schedule A transactions with multiple memo options have been verified select "Save & add memo +" then "Group Name" is displayed and the list of memo's per each Receipt transaction.  (See dropdown screenshot below).**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/faf09ab7-1990-4d76-9f94-5fa19c017034)


Schedule A (Receipts) - Multiple Options (See wireframes above).   .**NOTE:  Partnerships is greyed out for the following as a dead link.**

Group Name: Joint Fundraising Transfer Memo
List Items: Individual, Party, PAC, Tribal, Partnership 

Group Name: JF Transfer - National Party Recount/Legal Proceedings Account Memo
List Items: Individual, PAC, Tribal, Partnership

Group Name: JF Transfer - National Party Pres. Nominating Convention Account Memo
List Items: Individual, PAC, Tribal, Partnership

Group Name: JF Transfer - National Party Headquarters Buildings Account Memo
List Items: Individual, PAC, Tribal, Partnership

**QA review verified that the below "Receipt"  Schedule A transactions with single memo options have been verified select "Save & add memo +" then "Memo Name" is displayed.  (See dropdown screenshot below).**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c67b002e-09aa-4bbf-a550-4898393dd80b)

Partnership Receipt
Partnership Receipt Memo (Memo Name: Partnership Receipt Memo)

Partnership Recount Account Receipt
Partnership Recount Account Receipt Memo (Memo Name: Partnership Recount Account Receipt Memo)

Partnership National Party Recount/Legal Proceedings Account Receipt
Partnership National Party Recount/Legal Proceedings Account Memo (Memo Name: Partnership National Party Recount/Legal Proceedings Account Memo)

Partnership National Party Headquarters Buildings Account Receipt
Partnership National Party Headquarters Buildings Account Memo (Memo Name: Partnership National Party Headquarters Buildings Account Memo)

Partnership National Party Pres. Nominating Convention Account Receipt
Partnership National Party Pres. Nominating Convention Account Memo (Memo Name: Partnership National Party Pres. Nominating Convention Account Memo)

**QA review verified that the below "Disbursement"  Schedule B transactions with single memo options have been verified select "Save & add memo +" then "Memo Name" is displayed.  (See dropdown screenshot below).**

 ![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/44ba2e64-53f0-426a-9e35-db2c649a4755)

Credit Card Payment for Operating Expenditure
Credit Card Memo for Operating Expenditure

Staff Reimbursement for Operating Expenditure
Staff Reimbursement Memo for Operating Expenditure

Payment to Payroll for Operating Expenditure
Payroll Memo for Operating Expenditure

Credit Card Payment for Other Disbursement
Credit Card Memo for Other Disbursement

Staff Reimbursement for Other Disbursement
Staff Reimbursement Memo for Other Disbursement

Payment to Payroll for Other Disbursement
Payroll Memo for Other Disbursement

**NOTE:  The transactions tested and verified by QA are the ones listed in this ticket's Acceptance Criteria only.   Additional Schedule A and Schedule B transactions, not listed above, will be added to e2e testing.**

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers so the current button looks like this:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ab9e0758-4a99-4e2f-a458-9cf1142b54a1)

The button in the Wireframes looks like this:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b8fc200c-bf35-4a30-9537-f4d7eba356b1)

Which one is correct for this button ticket ?

**Comment by MitchellTCG** [comment]
In regards to the above question: 
Please update the button color and move the icon from the right to left.

I updated the styling in the AC above - (styling section).

**Comment by WiseQA** [comment]
Moving back to In-Progress @MitchellTCG @mjtravers for button format fix as noted above.   All other functionality for this tickets has been tested and passes.   Will adhoc test once button is updated.

**Comment by mjtravers** [comment]
The styling of the dropdown button on transaction screens was updated. Passes CR. Sending to QA. Patch is ready to QA on STAGE.

**Comment by WiseQA** [comment]
QA review verified button format change.   Tested on Stage.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/03c481a3-0dec-4d35-85ce-56f044e7c5b8)

This ticket passes as written.

QA Review Completed.  Moved to Stage Ready.
