### ISSUE TITLE
System to default Entity dropdown for Schedule B Payroll Memos

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#907]
Task: Update Entity dropdowns for Payroll Memo for Operating Expenditure and Payroll Memo for Other Disbursements to default to IND, ORG, then COM. 

### Acceptance Criteria ### 

**If** [precedent]
**When** [action]
**Then** [result]

**Comment by AureliaKhorsand** [comment]
Closed as OBE, accomplished in transaction tickets in Sprint 22.

**Comment by WiseQA** [comment]
This should be Sprint 22 tickets.   No tickets from Sprint 23 have been
passed through.

*Shelly Wise*
*QA/Test Engineer*
*Tygart Technology*
***@***.*** ***@***.***>*
*304-657-9070*
*CMMI - ITIL - ISO 9001:2015 - Agile/SAFe*
