### ISSUE TITLE
System to hide "Aggregate Amount" for Schedule B Transactions

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#908]
Business Reason

As a user, I should not be able to see the "Aggregate Amount" for the listed Schedule B transactions, as it is not relevant to the user, nor is it sent to FEC.

Acceptance Criteria

### QA Notes ###
**Given** one the following Schedule B transactions on a report "In-progress" or "Submission success",
- [x] Operating Expenditure
- [x] Credit Card Payment for Operating Expenditure
- [x] Credit Card Memo for Operating Expenditure
- [x] Staff Reimbursement for Operating Expenditure
- [x] Staff Reimbursement Memo for Operating Expenditure
- [x] Payment to Payroll for Operating Expenditure
- [x] Payroll Memo for Operating Expenditure
- [x] Void of Operating Expenditure
- [x] Other Disbursements
- [x] Credit Card Payment for Other Disbursement
- [x] Credit Card Memo for Other Disbursement
- [x] Staff Reimbursement for Other Disbursement
- [x] Staff Reimbursement Memo for Other Disbursement
- [x] Payment to Payroll for Other Disbursement
- [x] Payroll Memo for Other Disbursement
- [x] Void of Other Disbursement
- [x] Non-contribution Account Disbursement
- [x] Non-contribution Account Credit Card Payment
- [x] Non-Contribution Account Credit Card Payment Memo
- [x] Non-contribution Account Staff Reimbursement
- [x] Non-contribution Account Staff Reimbursement Memo
- [x] Non-contribution Account Payment to Payroll
- [x] Non-contribution Account Payment to Payroll Memo
- [x] Recount Account Disbursement
- [x] National Party Recount/Legal Proceedings Account Disbursement
- [x] National Party Headquarters Buildings Account Disbursement
- [x] National Party Pres. Nominating Convention Account Disbursement
- [x] 100% Federal Election Activity Payment
- [x] Credit Card Payment for 100% Federal Election Activity
- [x] Credit Card Memo for 100% Federal Election Activity
- [x] Staff Reimbursement for 100% Federal Election Activity
- [x] Staff Reimbursement Memo for 100% Federal Election Activity
- [x] Payment to Payroll for 100% Federal Election Activity
- [x] Payroll Memo for 100% Federal Election Activity
- [x] Void of 100% Federal Election Activity

**When** I go to view or edit the transaction,
**Then** I will _not_ see the "AGGREGATE" field

**And** When I save the transaction
--AGGREGATE will not be sent on the .FEC file

## QA Notes
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
- Aggregate amount is still calculated in the back end

### Design ###
null

 See full ticket and images here: [FECFILE-855](https://fecgov.atlassian.net/browse/FECFILE-855)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review adhoc tested the **list of transactions in the Acceptance Criteria** that "Aggregate Amount" is not displayed on the transaction(s) page.  This is hidden but not displayed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLy9tQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02448f633651a4ae091cbb81a3826fe725419d56/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0xuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6913404aeb5c719a53c410b52956b46b8f68b49c/image.png)

Note e2e tests will be updated for Schedule B transactions and display of "Aggregate Amount"

QA Review Completed.   Moved to Stage Ready.
