### ISSUE TITLE
DSP: System to calculate Other Federal Operating Expenditures (Line 21.b) (Column A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#911]
Business Reason 
 

On the Detailed Summary Page, Line 21.b should be a total of transactions with form type SB21B _except_ for if the transaction has "Memo Code" checked. This ticket is for Column A only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 21.b (column A) of Form 3X must:
--  consist of the total of transactions with form type "SB21B"  within the report period
-- NOT include any transactions with "Memo Code" checked

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
 
Main "Disbursement" transaction types included here:
- Operating Expenditure
- Credit Card Payment for Operating Expenditure
- Staff Reimbursement for Operating Expenditure
- Payment to Payroll for Operating Expenditure
- Void of Operating Expenditure
- National Party Headquarters Buildings Account Disbursement
- National Party Pres. Nominating Convention Account Disbursement
- Individual Refund - National Party Headquarters Buildings Account
- Other Committee Refund - National Party Headquarters Buildings Account
- Tribal Refund - National Party Headquarters Buildings Account
- Individual Refund - National Party Pres. Nominating Convention Account
- Other Committee Refund - National Party Pres. Nominating Convention Account
- Tribal Refund - National Party Pres. Nominating Convention Account

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review selected and entered Operating Expenditure and Tribal Refund - National Party Headquarters Buildings Account disbursements without memo item checkbox selected.    

Detailed Summary Page Line 21.b (Column A) is not displaying value.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2d901b87-fdb4-4d0c-b983-bb91cd435e21)

@mjtravers @MitchellTCG per review returning to In-Progress for fi.

**Comment by mjtravers** [comment]
The issue was the initial branch was reverted out of the develop branch. It has been restored. Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review retested and selected and entered Operating Expenditure and Tribal Refund - National Party Headquarters Buildings Account disbursements without memo item checkbox selected.

Detailed Summary Page Line 21.b (Column A) is displaying value correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6c8e726e-b2cf-45f5-8c98-4b9ed6320826)

QA Review Completed. Moved to Stage Ready.
