### ISSUE TITLE
DSP: System to calculate Transfers to Affiliated/Other Party Committees (Line 22) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#914]
Business Reason 
 

On the Detailed Summary Page, Line 22 should be a total of transactions with form type SA22 _except_ for if the transaction has "Memo Code" checked. This ticket is for Column A only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 22 (column A) of Form 3X must:
--  consist of the total of transactions with form type "SB22"  **from January 1 of current year to the report coverage period end date**
-- NOT include any transactions with "Memo Code" checked
2. The numbers will update as needed until the report is submitted.

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
 
Main transaction types included here:
- Transfers to Affiliates/Other Committees - Disbursement under "Contributions/Expenditures to Regular Filers"
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Transfers to Affiliates/Other Committees - Disbursement Line 22 (Column B).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/06c3cb41-66d7-4048-b9f8-41635e959ed1)

Verified when Memo Item checkbox is selected the transaction amount is not calculated in Line 22 Column B.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4cc603c2-d3d1-450e-bb88-818bfec7d75a)

QA Review Completed. Move to Stage Ready after Sprint 26 review 22 June 2023.
