### ISSUE TITLE
DSP: System to calculate Contributions to Federal Candidates/Committees and Other Political Committees (line 23) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#916]
Business Reason 
 

On the Detailed Summary Page, Line 23 should be a total of transactions with form type SB23 _except_ for if the transaction has "Memo Code" checked. This ticket is for Column B only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 23 (column B) of Form 3X must:
--  consist of the total of transactions with form type "SB23"  **from January 1 of current year to the report coverage period end date**
-- NOT include any transactions with "Memo Code" checked
2. The numbers will update as needed until the report is submitted.

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
 
Main transaction types included here:
- Contribution to Candidate
- In-kind Contribution to Candidate 
- Void of Contribution to Candidate
- Contribution to Other Committee
- In-kind Contribution to Other Committee 
- Void of Contribution to Other Committee

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "CONTRIBUTIONS TO FEDERAL CANDIDATES/COMMITTEES AND OTHER POLITICAL COMMITTEES" are calculated correctly in Line 23 - Column B. (Note: tested without Memo Item checked)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTJYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--821e048bd8c184a400c633a8ea86843daca91356/image.png)

QA Review Completed. Moved to Stage Ready.
