### ISSUE TITLE
DSP: System to calculate Refunds of Contributions (Line 28 and Line 34) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#918]
Business Reason 
 

On the Detailed Summary Page, Line 28.a, Line 28.b, Line 28.c should be a breakdown of the total of transactions and Line 28.d should be a total of all transactions with form type SA28A, SA28B, SA28C _except_ for if the transaction has "Memo Code" checked. The value in Line 28.d should be duplicated in Line 34. This ticket is for Column B only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 28 (column B) of Form 3X must:
-- NOT include any transactions with "Memo Code" checked
-- If transaction form type is SB28A then add total to 28.a from January 1 of current year to the report coverage period end date 
-- If transaction form type is SB28B then add total to 28.b from January 1 of current year to the report coverage period end date
-- If transaction form type is SB28C then add total to 28.C from January 1 of current year to the report coverage period end date 
-- Total sum of Column B values in 28.a, 28.b, and 28.c should be in 28.d **for the report period in Column B**
2. Detailed Summary Page Line 34 (column B) on Form 3x must be a duplicate of the sum that is calculated for 28.d in Column B
3. The numbers will update as needed until the report is submitted.

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

 Wireframe
![918 - Column 2.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/1af8cb08-9c67-4be6-ae78-152cea4a1343)

### QA Notes ### 
 
Main transaction types included here:
**SB28A**
- Refund of Individual Contribution
- Refund of Individual Contribution – Void

**SB28B**
- Refund of Party Contribution
- Refund of Party Contribution – Void

**SB28C**
- Refund of PAC Contribution
- Refund of PAC Contribution – Void
- Refund of Unregistered Receipt from Person
- Refund of Unregistered Receipt from Person – Void

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by toddlees** [comment]
passes CR moving to QA

**Comment by WiseQA** [comment]
QA review verified when using the following "Disbursements" the detailed summary page (Line 28 and 34 in Column B) is updated correctly as denoted in this ticket. Tested using: Refund of Individual Contribution; Refund of Party Contribution; Refund of PAC Contribution.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/afc07be0-96a6-4f22-9fc8-e583a5c28a82)

QA Review Completed. Moved to Stage Ready.
