### ISSUE TITLE
Allow user to create user account on FECfile Online through login.gov (AUTHENTICATE and PROVISION)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#92]
Business Reason

As a user, I will be able to create a FECfile Online account through login.gov so that I can be authenticated by login.gov, allowing FECfile to recognize me as a valid user so I can be provisioned.

Acceptance Criteria

***Given*** a user with a valid login.gov login

  ***When*** the user logs in with login.gov through FECfile Online for the first time,

  ***Then*** they will be prompted to create a user profile with the following information:

*   LAST NAME (A/N-30, required)
*   FIRST NAME (A/N-20, required)
*   EMAIL (auto-populated from login.gov email, user cannot edit)

***And*** the user can then:

*   click "Continue", at which point: 
      *   the user will be provisioned in FECfile Online
    *   brings them to the dashboard (or committee account selection screen when #1654)
*   click "Cancel and exit" which takes them back to the FECfile landing page.

Wireframes

1.  Create User Account in FECFile

       

1.  Error Message

       

Asset

  

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
- [ ] Set up initial landing page with a "login" and "register" button that redirects to Login.gov
- [ ] Login.gov will return the authenticated user to the dashboard page with the legalese pop up displayed.
- [ ] The authenticated user session will be linked to the appropriate user record in the authentication_account table in the database
- Note: This does NOT include setting up a user with a committee account. This is just getting them a login.gov account associated with FECfile Online.
- Integrate the Login.gov web service into the web-app and web-api authentication process

Documentation: https://developers.login.gov/overview/

### Design ###
null

[FECFILE-1314](https://fecgov.atlassian.net/browse/FECFILE-1314)

**Comment by AureliaKhorsand** [comment]
For this ticket, it will create a login process via Login.gov for a committee account admin role that is linked to only 1 committee account.

Future tickets will expand on this process to include users linked to more than one committee account and roles beyond committee account admin

**Comment by AureliaKhorsand** [comment]
@mjtravers to meet with internal TCG contact for LoE information.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @JonellaCulmer 
wires added

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @JonellaCulmer 
Please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG let's talk about this today. Is the intention here that it is a user that already has a login.gov account, it's just not associated with FECfile Online yet? If so, that's fine, but won't we need another ticket for if the user does not have a login.gov account at all?

**Comment by AureliaKhorsand** [comment]
@MitchellTCG let's talk about this today. Is the intention here that it is a user that already has a login.gov account, it's just not associated with FECfile Online yet? If so, that's fine, but won't we need another ticket for if the user does not have a login.gov account at all?

**Comment by AureliaKhorsand** [comment]
@MitchellTCG updated ACs, can you check them? Also ticket needs artifacts for new pages, and character limit for names.

**Comment by mjtravers** [comment]
@dheitzer  There are menu links at the top of the page and links at the bottom of the page that are not in the wireframe. Otherwise, looks good and works well.
<img width="715" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWNuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eedfc65efa726d81fb63c13b7edefae70a789079/image.png" alt="image.png" />

Sending back to In Progress.

**Comment by mjtravers** [comment]
Menu items and top part of footer removed.
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA testing using Login.gov on STAGE.    Verified Menu items and top part of footer removed (see comment above)

Login verify "Create profile" page is displayed.

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2s3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f43258498083b376a7bef3823c59c84defb58a8/image.png" alt="image.png" />

__________________________________________________________________________________________

Verify Last Name / First Name are both required fields and email is filled is as read-only..

<img width="1211" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL283QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--181e6e2c7aad672876cd38ecddb3126c036764e4/image.png" alt="image.png" />

___________________________________________________________________________________________________________

Enter First Name / Last Name 

<img width="1284" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3M3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c9e8a2d9a310d208fd9177b5628b24afd755973/image.png" alt="image.png" />

_______________________________________________________________________

Select "Continue" verify Security Notification page is displayed (reference ticket #120

<img width="1209" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzA3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94e9e5981ddde23a6dcdefacee4e9793452fa5c4/image.png" alt="image.png" />

__________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
