### ISSUE TITLE
DSP: System to calculate Other Disbursements (line 29) (Column B)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#920]
Business Reason 
 

On the Detailed Summary Page, Line 29 should be a total of transactions with form type SB29 except for if the transaction has "Memo Code" checked. This ticket is for Column B only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 29 (column B) of Form 3X must:
-- consist of the total of transactions with form type "SB29" **from January 1 of current year to the report coverage period end date**
-- NOT include any transactions with "Memo Code" checked
2. The numbers will update as needed until the report is submitted.

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
 
Main transaction types included here (for each of these transactions, 'Add a Disbursement'):
- Other Disbursements
- Credit Card Payment for Other Disbursement
- Staff Reimbursement for Other Disbursement
- Payment to Payroll for Other Disbursement
- Void of Other Disbursement
- Non-contribution Account Disbursement
- Non-contribution Account Credit Card Payment
- Non-contribution Account Staff Reimbursement
- Non-contribution Account Payment to Payroll
- Individual Refund - Non-contribution Account
- Other Committee Refund - Non-contribution Account
- Business/Labor Organization Refund - Non-contribution Account
- Recount Account Disbursement
- National Party Recount/Legal Proceedings Account Disbursement
- Individual Refund - National Party Recount/Legal Proceedings Account
- Other Committee Refund - National Party Recount/Legal Proceedings Account
- Tribal Refund - National Party Recount/Legal Proceedings Account

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified from acceptance criteria, Column B value in Line 29 (tested with Other Disbursements and Void of Other Disbursement)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/271171a8-7458-4b0b-b15b-3b2168d86032)

e2e tests to be run on each transaction.

QA Review Completed. Moved to Stage Ready.
