### ISSUE TITLE
DSP: System to calculate Federal Election Activity Paid Entirely with Federal Funds (line 30.b) (Column A)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#921]
Business Reason 
 

On the Detailed Summary Page, Line 30.b should be a total of transactions with form type SB30B except for if the transaction has "Memo Code" checked. This ticket is for Column A only.

 Acceptance Criteria 
 

1. Detailed Summary Page Line 30.b (column A) of Form 3X must:
-- consist of the total of transactions with form type "SB30B" within the report period 
-- NOT include any transactions with "Memo Code" checked

 DEV NOTES
Transactions should only ever appear on one line in the detailed summary page, so we can implement this by Form Type, and do not need to list out all of the transaction types that go into each line.

Please create index on "Form Type".

[See paper form for reference here.](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf)

### QA Notes ### 
 
Main transaction types included here:
- 100% Federal Election Activity Payment
- Credit Card Payment for 100% Federal Election Activity
- Staff Reimbursement for 100% Federal Election Activity
- Payment to Payroll for 100% Federal Election Activity
- Void of 100% Federal Election Activity

(**Note** The remainder of Line 30 will be completed when Schedule H6 is complete)
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified from acceptance criteria, Column A value in  Line 30.b (tested with 100% Federal Election Activity Payment and Void of 100% Federal Election Activity)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2699e701-6b9b-4d24-8586-976f4df0dfb3)

e2e tests to be run on each transaction.

QA Review Completed.   Moved to Stage Ready.
