### ISSUE TITLE
Update Non-contribution Account transactions Purpose of Contribution to remove "Receipt"

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#929]
***Task:*** Remove the work "Receipt" from the following transaction Purpose of Contributions so that they read "Non-contribution Account":

*   Individual Receipt - Non-contribution Account
*   Other Committee Receipt - Non-contribution Account
*   Business/Labor Organization Receipt - Non-contribution Account

Acceptance Criteria

***Given*** I am entering or editing one of the following transactions

*   Individual Receipt - Non-contribution Account
*   Other Committee Receipt - Non-contribution Account
*   Business/Labor Organization Receipt - Non-contribution Account

***Then*** the system-generated Purpose of Contribution will read "Non-contribution Account".

Dev Notes

### QA Notes ###
 
Note:   This ticket is not the label being changed (e.g., PURPOSE OF RECEIPT (SYSTEM-GENERATED)) however, the functionality changing is the system-generated text field.  Note:  These 3 transactions are under the "Other" accordion dropdown list.

From > To change detailed in QA review.    

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-841](https://fecgov.atlassian.net/browse/FECFILE-841)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified the 3 transactions under "Other" the Purpose of Contribution text field has been updated.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b2d8213b-24ef-4011-adca-8f0201b35da8)

QA review verified the "PURPOSE OF RECEIPT (SYSTEM-GENERATED)" for Individual Receipt - Non-contribution Account was changed.

From:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/aec1309f-e9f1-4c1d-9d9e-8067cadb40d2)

To:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/60309ea7-ab24-4719-8603-9b6fb9385d68)

QA review verified the "PURPOSE OF RECEIPT (SYSTEM-GENERATED)" for Other Committee Receipt - Non-contribution Account was changed.

From:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c715046c-b964-4499-acbf-8cf339cc8f11)

To:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d9fd083a-a8bd-4e03-a667-f9e4e2da8b55)

QA review verified the "PURPOSE OF RECEIPT (SYSTEM-GENERATED)" for Business/Labor Organization Receipt - Non-contribution Account was changed.

From:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/13682405-829a-49c5-ae71-eff74c122f8c)

To:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/21f948b9-7afe-44a5-b13a-382a3b753287)

QA Review Completed.   Moved to Stage Ready.
