### ISSUE TITLE
UI: Fix/Relink Fonts in FecFile

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#935]
As the UX Lead, I would like the app to present the correct fonts as listed out in the FEC Pattern Library: [https://fec-pattern-library.app.cloud.gov/docs/typography.html](https://fec-pattern-library.app.cloud.gov/docs/typography.html)

Acceptance Criteria

1.  Font 1

       #

       Karla (this font appears to be working)
    _as displayed in the HEAD of FEC.gov_

       

       

1.  Font 2

       #

       Gandhi serif (THIS IS NOT DISPLAYING CORRECT) The system i showing the system font Serif
    _as displayed in the HEAD of FEC.gov_

       

       

       

_I found this in the Github respository_

  The FEC currency monospace font files in `fec-cms/fec/fec/static/fonts/` are a custom, modified version of the Karla font by [Jonny Pinhorn]([https://github.com/jonpinhorn](https://github.com/jonpinhorn)), licensed under the [SIL Open Font License]([http://scripts.sil.org/cms/scripts/page.php?item_id=OFL](http://scripts.sil.org/cms/scripts/page.php?item_id=OFL)).

The Gandhi Serif font files in `fec-cms/fec/fec/static/fonts/` are from [Librerias Gandhi]([http://www.tipografiagandhi.com/](http://www.tipografiagandhi.com/)), and copyright 2012 [Librerias Gandhi S.A. de C.V.]([http://www.gandhi.com.mx/](http://www.gandhi.com.mx/)) with Reserved Font Name ‘Gandhi Serif’. The English version of this License is reproduced below.

Dev Notes

I think I ( @MitchellTCG ) miscoded Gandhi

  The inspector tool shows:

  font-family: gandhi-serif-bold,serif;

  & 

  font-family: gandhi-serif,serif;

And if i change the fonts to read "gandhi-bold" and "gandhi-regular" in the inspector, the font look correct.

BUT I ALSO HAVE A FONT MANAGER ON MY COMPUTER SO THIS MAY NOT BE A SOLUTION

***Incorrect font***

  ![Screenshot 2023-03-24 at 8.14.38 AM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/9f1bd5fe-2376-4c2c-ab6c-676801218333](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/9f1bd5fe-2376-4c2c-ab6c-676801218333))

***Correct font***

  ![Screenshot 2023-03-24 at 8.14.42 AM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/2545b5aa-e154-45c1-bd99-9765a5141de3](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/2545b5aa-e154-45c1-bd99-9765a5141de3))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-840](https://fecgov.atlassian.net/browse/FECFILE-840)

**Comment by MitchellTCG** [comment]
@mjtravers @toddlees @Elaine-Krauss-TCG @dheitzer 

Please review this ticket and let me know if you have any questions

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/05eb83a5-c005-48c4-82d2-25a5c1b37b6d)

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/bcecd590-5ce3-4774-86e5-867cf0a143e0)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
Here is a screenshot showing the calculated font-family for the WORLD CAPITALIST PARADISE title on the dashboard is "gandhi-serif-bold".
![font-family.jpg](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/6546fa03-1ae2-4480-a1bf-57550d2d4468)

**Comment by WiseQA** [comment]
QA Review consists visual inspection with DEV.

QA Review Completed.   Moved to Stage Ready.

**Comment by Elaine-Krauss-TCG** [comment]
![image](https://user-images.githubusercontent.com/104506225/230923353-0bc02904-0db0-4118-b4ae-c24fdd6c4c32.png)
Weird, I don't have this on local

**Comment by Elaine-Krauss-TCG** [comment]
![image](https://user-images.githubusercontent.com/104506225/230923685-9ce7a2be-ee08-4322-9951-81d50ea5f26c.png)
Same on DEV
