### ISSUE TITLE
DSP: Redesign Detail Summary Page with Calculation Tooltips

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#937]
Business Reason 
 

As a user, I will be able to see an updated Detail Summary Page for Form 3x, which includes tooltips on each line, so that I can view the summary totals for my committee.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator Reviewing a Form 3X report
**Then** Click on the View Detailed Summary Page 
**Then** I will be able to view the updated Detail Summary Page
**And** I will be able to click on the calculator icon on a totals line
**Then** I will see the high-level calculation that is used to determine that value

**The text (for cutting and pasting, to reduce error):**
_Also please be aware the functions (+, -, =) are ALL BOLD_

Line 11(a)(iii)
**CALCULATIONS:**
Lines 11(a)(i) **+** 11(a)(ii) **=** Line 11(a)(iii) 

Line 11(d)
**CALCULATIONS:**
Lines 11(a)(iii) **+** 11(b) **+** 11(c) **=** Line 11(d) 
(This total will also appear on Line 33).

Line 15
**CALCULATIONS:**
(This total will also appear on Line 37).

Line 18(c)
**CALCULATIONS:**
Lines 18(a) **+** 18(b) **=** Line 18(c)

Line 19
**CALCULATIONS:**
Lines 11(d) **+** 12 **+** 13 **+** 14 **+** 15  **+** 16 **+** 17 **+** 18(c) **=** 
Line 19

Line 20
**CALCULATIONS:**
Lines 19 **-** 18(c) **=** Line 20

Line 21(c)
**CALCULATIONS:**
Lines 21(a)(i) **+** 21(a)(ii) **+** 21(b) **=** Line 21(c)

Line 28(d)
**CALCULATIONS:**
Lines 28(a) **+** 28(b) **+** 28(c) **=** Line 28(d)

Line 30(c)
**CALCULATIONS:**
Lines 30(a)(i) **+** 30(a)(ii) **+** 30(b) **=** Line 30(c)

Line 31
**CALCULATIONS:**
Lines 21(c) **+** 22 **+** 23 **+** 24 **+** 25  **+** 26 **+** 27 **+** 28(d) 
**+** 29 **+** 30(c) **=** Line 31

Line 32
**CALCULATIONS:**
Lines  31 **-** 21(a)(ii) **+** 30(a)(ii) **=** Line 32

Line 33
**CALCULATIONS:**
Carried from Line 11(d).

Line 34
**CALCULATIONS:**
Carried from Line 28(d).

Line 35
**CALCULATIONS:**
Line 34 **-** 33 **=** Line 35 

Line 36
**CALCULATIONS:**
Line 21(a)(i) **+** 21(b) **=** Line 36

Line 37
**CALCULATIONS:**
Carried from Line 15.

Line 38
**CALCULATIONS:**
Line 37 **-** 36 **=** Line 38 

 DEV NOTES
- Wireframes below show the new DSP, and the accompanying calculation values in the tooltips
- Following video shows how the tool tip works
https://images.zenhubusercontent.com/417265237/d98e0c61-3df5-42b1-b5e3-5423ac14c1bc/283_dsp_system_to_calculate_contributions_line_11_and_33_column_a.mp4

- Calculator Icon from the FEC Pattern Library
https://fec-pattern-library.app.cloud.gov/docs/icons.html
![calculator.svg](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/5ded190a-f526-4c19-bf16-818fd8a83ce9)

 Wireframes 

- This is the updated DSP

![Detailed Summary Page – Full Page.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/884dabd3-b030-4205-a54d-78240fc5ef21)

- These are the calculations
![Detailed Summary Page – Pop ups.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/cf743e3f-5b85-4bf4-a342-b046645c51fe)

- Here are files with tooltips:

- Line 11d
![Detailed Summary Page – Line 11d.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/5ae5b2c0-77a0-4a2d-a27a-e824b658262a)

- Line 15
![Detailed Summary Page – Line 15.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7987efe4-d2f7-42d5-8f7b-ba1787a1fb3d)

- Line 18c
![Detailed Summary Page – Line 18c.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0fa2667d-4c92-445f-ad2f-414881a3cb23)

- Line 19
![Detailed Summary Page – Line 19.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/09c2da42-0d49-4b44-a62b-e37324f9b86b)

- Line 20
![Detailed Summary Page – Line 20.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/fe88f370-740d-4d02-a3f4-aabfe87c7082)

- Line 21c
![Detailed Summary Page – Line 21c.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/6239f2e8-cc0d-409a-aaaa-c4fa4e5f866b)

-Line 28d
![Detailed Summary Page – Line 28d.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/53971c61-9609-44fa-bbcb-76d5a0a419f0)

- Line 30c
![Detailed Summary Page – Line 30c.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ddbebe25-3413-4fb9-bc02-9c12ad912ef6)

- Line 31
![Detailed Summary Page – Line 31.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/382cf715-055f-46ac-9e06-ce4490071e41)

- Line 32
![Detailed Summary Page – Line 32.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/2f79880c-e313-4816-8779-9f01a31f1802)

- Line 33
![Detailed Summary Page – Line 33.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/1b0b3546-708f-4ec2-97e8-1b2931c9a9b4)

- Line 34
![Detailed Summary Page – Line 34.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8c114615-32f3-4d15-9e39-d5e73845709f)

- Line 35
![Detailed Summary Page – Line 35.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0a9cac74-6b94-4344-b136-99c691e1ab3f)

- Line 36
![Detailed Summary Page – Line 36.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/e48b484f-05a1-4181-b158-37715c3b7994)

- Line 37
![Detailed Summary Page – Line 37.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/26fbc32e-0dba-410a-ac83-1beda1137998)

- Line 38
![Detailed Summary Page – Line 38.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/fc843ec4-ad48-4291-9d53-4dad0b3dfdab)

### QA Notes ### 
 
- See the wireframes below

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by toddlees** [comment]
passes CR moving to QA

**Comment by WiseQA** [comment]
QA review calculation tooltips added to Detailed summary page per the wireframes above.  Verified lines: 11(a)(iii); 11(d); 15; 18(c); 19; 20; 21(c); 28(d); 30(c); 31; 32; 33-38.

Screenshot below of one of the calculation tooltips only.   

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2215a042-9c0f-490d-a229-60fde4cc06b7)

QA Review Completed.   Moved to Stage Ready.
