### ISSUE TITLE
UI: Update logo in upper left corner of pages without the bar nav bar

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#938]
As the UX lead, i would like a FEC logo and the title application title "FECFile" in the upper left corner of every page without blue left nav bar.

Acceptance Criteria

Logo should look like:

![FECFile-Logo-Blue.svg]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ea59a246-5d84-4511-8a09-29005d890c14](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ea59a246-5d84-4511-8a09-29005d890c14))

The nav section should be 80px tall

Place a SVG logo in the upper left corner of the page.

  Center it vertically in the 80px space.

  The logo should be 48px by 48px

Padding around the logo:

  Padding-left: 16px

  Padding-top: 16px

  Padding-right: 8px

Here is the logo in context:

  ![UPDATE HEADER.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/25ae6e47-accd-4a60-bc9a-f163b4681880](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/25ae6e47-accd-4a60-bc9a-f163b4681880))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-838](https://fecgov.atlassian.net/browse/FECFILE-838)

**Comment by MitchellTCG** [comment]
@mjtravers @toddlees @dheitzer @Elaine-Krauss-TCG 

Please review this ticket and make sure all the info makes sense.

**Comment by MitchellTCG** [comment]
@MitchellTCG 
create a SVG

**Comment by MitchellTCG** [comment]
SVG Added

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified logo has been updated in the upper left corner of pages without the Nav Bar.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c735b5ba-3766-41f8-89a5-4eabb5be3885)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b2fb4e6f-3f0f-4c1a-99d4-48e0c99556b0)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/47014f58-9b60-4ac4-ac0c-7797a6c96409)

QA Review Completed.   Moved to Stage Ready.
