### ISSUE TITLE
UI: Update styling of committee name, reporting frequency, committee type, & committee ID on pages

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#940]
User Story

As a user of FECFile, I would like an easy to find and standardized way to view the committee name, reporting frequency, committee type, & committee ID on every page to reduce the chance entering information into the wrong committee account.

Acceptance Criteria

Beneath the 80px top nav area

There should be a 32px Margin (left and right) for the area under the nav bar and above the footer

The Committee Name will be a H1 on every page (the size will differ on pages with the blue left nav)

1.  Line 1

       #

       ***Committee Name:***

       Font-family: Karla bold

       font-size: 36px

       color: #212121

       line height: 1.2

       default margin: 0

       left aligned

1.  Line 2

       #

*   [x] Committee Type (Committee Type full)

       a. It should be pulled from the committee type field

       b. Karla bold 14px #212121
*   [x] 18px high vertical piping (1px wide)

       a. Padding 8px (left and right)
*   [x] Committee ID

       a. Karla bold 14px #212121

1.  Examples

       #

       ![The Dashboard – 14.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/cabd2faf-58af-4ec2-bcd2-4779e8fbfe4f](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/cabd2faf-58af-4ec2-bcd2-4779e8fbfe4f))

![The Dashboard – 15.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ea6f890b-8429-4865-884c-1b9dd45fd356](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ea6f890b-8429-4865-884c-1b9dd45fd356))

![The Dashboard – 16.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d0b2ec78-2e25-490d-9347-0337445a6954](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d0b2ec78-2e25-490d-9347-0337445a6954))

![The Dashboard – 17.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/77af34e6-fcd2-4fb5-a4ea-ad5bc1e7c576](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/77af34e6-fcd2-4fb5-a4ea-ad5bc1e7c576))

![The Dashboard – 18.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8a7cf378-042e-4cba-99ce-e3c68735ccee](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8a7cf378-042e-4cba-99ce-e3c68735ccee))

### QA Notes ###

All text are ALL CAPS

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-836](https://fecgov.atlassian.net/browse/FECFILE-836)

**Comment by MitchellTCG** [comment]
@mjtravers @toddlees @dheitzer @Elaine-Krauss-TCG

Please review this ticket and make sure all the info makes sense.

**Comment by MitchellTCG** [comment]
@JonellaCulmer 
please review

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
I don't think this needs more UX attention. let me k
now if I am wrong

**Comment by AureliaKhorsand** [comment]
@MitchellTCG Since right now this is purely design (we haven't done requirements gathering on this), I'll leave it solely up to your team. No objections from me.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified text is ALL caps per UX notes for design.   Moved to Stage Ready.
