### ISSUE TITLE
UI: Update styling of committee name, reporting frequency, committee type, & committee ID on pages WITH Blue left nav

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#941]
User Story 

As a user of FECFile, I would like an easy to find and standardized way to view the committee name, reporting frequency, committee type, & committee ID on every page to reduce the chance entering information into the wrong committee account.

 Acceptance Criteria 

Beneath the 80px top nav area on the right of the page direct next to the Blue nav bar

There should be a 32px Margin (left and right) for the area under the nav bar and above the footer

Sadly the Committee Name will be a H1 on every page (the size will differ on pages with the blue left nav)

# Line 1 
#
**Committee Name:**
Font-family: Karla bold
**font-size: 18px** _(only difference compared to without right nav text)_
color: #212121
line height: 1.2
default margin: 0

# Line 2 
#
1. a 10px by 10px circle that corresponds to the filing frequency
     a. green = Active
         color: #4FA469
     b. red = terminated or administratively terminated
         color: #AEB0B5
2. Filing Frequency Status
     a. It should be pulled from Status field
     b. Karla bold 14px  #212121
3. 18px high vertical piping (1px wide)
     a. Padding 8px (left and right)
4. Committee Type
     a. It should be pulled from the committee type field
     b. Karla bold 14px  #212121
5. 18px high vertical piping (1px wide)
     a. Padding 8px (left and right)
6. Committee ID
     a. Karla bold 14px  #212121

# Example 
#
![The Dashboard – 18.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/897b0e98-4592-45a6-a988-618c00243096)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@mjtravers @toddlees @dheitzer @Elaine-Krauss-TCG

Please review this ticket and make sure all the info makes sense.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG is this ticket still relevant?

**Comment by AureliaKhorsand** [comment]
No longer needed with updated #940. Closing as OBE.
