### ISSUE TITLE
UI: Update transaction page filler text

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#942]
User Story

As a user with visual accessibility issues, I would like all text inside of a text box to be darker

Acceptance Criteria

1.  Text inside of the Contact type box change from #999999 to #212121
2.  All other text boxes change from #5B616B to #212121
3.  Text prompts should still be light grey: #5b616b

### QA Notes ###

- [ ] BA/Design Quality Checklist complete

### DEV Notes ###

null

### Design ###
h2. Wireframes

h3. Current state 

!image-20240813-175654.png|width=763,height=107,alt="image-20240813-175654.png"! [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-834)

h3. Ideal state 

!image-20240813-175709.png|width=719,height=119,alt="image-20240813-175709.png"!

[FECFILE-834](https://fecgov.atlassian.net/browse/FECFILE-834)

**Comment by MitchellTCG** [comment]
@mjtravers @toddlees @dheitzer @Elaine-Krauss-TCG

Please review this ticket and make sure all the info makes sense.

**Comment by toddlees** [comment]
It's not clear what state of the contact type input should be styled #212121 and which state of the 'search for contact' input should have #212121.  Do you only want the dropdown to have #212121 font when disabled?  Is this to be applied to every dropdown and input everywhere?
