### ISSUE TITLE
UI: Update the Contact Type section on Transactions

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#943]
User Story 
 
As Lead UX, I would like the contact type section to look like the wireframes

 Acceptance Criteria 

Update all border to be the following hexcode: #AEB0B5

Fix the border-radius for the Contact title
change from:
border-radius: 4px
change to: 
border-radius: 4px 0 0 4px;

Fix right side of contact type box
border-radius: 4px
change to: 
border-radius: 0 4px 4px 0;

Add a magnifying glass at the right side of the contact type text box:
![magnifying-glass.svg](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/23a303e8-7d1a-4905-a90e-71a4e345803e)

The MAGNIFYING GLASS icon should be 20px by 20px and color: #5B616B

Update the plus next to "Create a new contact"
The PLUS icon it should be 20px by 20px and color: #112E51 

Rollover state for contact selection should _only_ appear if there are options to change to another contact type.

 Assets

## Grey Loupe (Magnifying glass)
![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/55d45265-8e3f-40ef-88d8-4d4ed02fb5f2)

## Plus Icon
![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/1ff6d6e9-f94b-43a3-8286-9ed1cb0197fb)

## Down Arrow
![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/190151b6-7314-4363-aef8-bb94188f2f1b)

### QA Notes ### 
 
- [x] BA/Design Quality Checklist complete

Change from:
![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/65de67bb-3ebc-4419-8ad1-3c2cd62afcc6)

Change to:
![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/0315244d-39bb-4398-a082-0bd8d3539469)

_(Arrow only if applicable)_

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@mjtravers @toddlees @dheitzer @Elaine-Krauss-TCG

Please review this ticket and make sure all the info makes sense.

**Comment by toddlees** [comment]
The right side of the contact type might be more comprehensively solved by using a primeng button group to combine the inputs https://primeng.org/inputgroup

**Comment by MitchellTCG** [comment]
@toddlees @mjtravers 

I'm fine with you suggestion about a button Todd from the inputgroup. I can just work the CSS to look like my mocks

Will that work for yall and can we point this?

**Comment by GreggMoreland** [comment]
@MitchellTCG @toddlees @mjtravers Was this question ever answered? Can this ticket be moved/pointed?

**Comment by AureliaKhorsand** [comment]
@dheitzer added AC: "Rollover state for contact selection should only appear if there are options to change to another contact type."

**Comment by toddlees** [comment]
@MitchellTCG @dheitzer is the type dropdown supposed to be gray when enabled?

**Comment by mjtravers** [comment]
@dheitzer The down arrow is not showing up as a solid triangle. Here is a screenshot:


![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/a9edd992-e0e5-4e9c-b054-4c9c0c2259b8)

Sending back to In Progress.

**Comment by MitchellTCG** [comment]
can you make the border 2px thick

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Contact Type sections (with multiple selections) were updated.  Per @MitchellTCG discussion current implemented design passes.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/728ea366-8ddd-4f8f-888e-0ea097cebb0f)

QA Review Completed.   Moved to Stage Ready.
