### ISSUE TITLE
UI: Update ALL dropdown blocks

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#944]
As the UX Lead, I would like All dropdown blocks to be the same height as the other text entry fields

***Change from:***

  ![Screenshot 2023-03-26 at 9.29.40 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/eb5f91de-3520-4c57-b357-1b363054c30d](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/eb5f91de-3520-4c57-b357-1b363054c30d))

***Change to:***

  ![Screenshot 2023-03-26 at 9.29.18 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7c080e5a-3623-4f29-a525-dada52e8e103](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7c080e5a-3623-4f29-a525-dada52e8e103))

QA Note

_Ignore switching the dropdown carat_

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-832](https://fecgov.atlassian.net/browse/FECFILE-832)

**Comment by MitchellTCG** [comment]
@mjtravers @toddlees @dheitzer @Elaine-Krauss-TCG

Please review this ticket and make sure all the info makes sense.

**Comment by toddlees** [comment]
makes sense.  I'm assuming that to make them the same, you want the dropdown height to become the current other input height, rather than the other input height becoming the current dropdown height.

**Comment by Elaine-Krauss-TCG** [comment]
The dropdowns have a height of 28 pixels plus vertical padding.  The input fields have the same vertical padding, but their height is actually 24 pixels.  Changing just the height seems to have the effect we're looking for.

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/53bc823c-78f9-4844-9982-d000e5b66dc3)
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/7a0ebfa0-18fe-425f-ac29-943434a4b9d8)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by mjtravers** [comment]
Here is a comparison of calculated heights between a dropdown box and a text box on the transaction edit form. Both are basically 48px in height.![dropdown-height.jpg](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/ab4cb5ff-ac5f-4e3d-ab8f-1a17b05dd910)
![text-height.jpg](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/f8d68f0b-b867-46b4-a718-c6b0c4d30da2)

**Comment by WiseQA** [comment]
QA Review visual inspection review verified comparison of calculated heights between a dropdown box and a text box on the transaction edit form. Both are basically 48px in height with DEV

QA Review Completed.   Moved to Stage Ready.
