### ISSUE TITLE
Create Angular model for Schedule C

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#945]
Following the same pattern as was created for the Schedule A and Schedule B, create a Schedule C class to manage the data for a Schedule C record.

DEV Tasks:

*   Create a SchCTransaction class that extends the Transaction class
*   Create a ScheduleCTransactionGroups enum containing groupings for the "Add transacation" expand/collapse page
*   Create a ScheduleCTransactionsGroupsType type
*   Create a ScheduleCTransactionTypes enum containing the transaction unique identifiers
*   Create a ScheduleCTransactionTypeLabels LabelList containing the UI title for each transaction type
*   Update the ScheduleTransaction, TransactionTypes, and TransactionGroupTypes type definitions in the transactions.model.ts file

### QA Notes ###

There will be a unit test that can be reviewed verifying the correctness of the Schedule C model code. A screenshot can be provided.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-831](https://fecgov.atlassian.net/browse/FECFILE-831)

**Comment by mjtravers** [comment]
Screenshot of unit tests running successfully:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/1abde8e1-a12d-4096-9a8e-6318270fbfbc)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review of visual inspection of Unit Tests as provided above.

QA Review Completed.    Moved to Stage Ready.
