### ISSUE TITLE
Allow user to select Election Code and Election Year within a transaction

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#947]
Business Reason

As a user, I will be able to select from a list of Election code values and include an Election Year for my schedule A transaction on Form 3X so that I can categorize my receipts for bookkeeping purposes.

Acceptance Criteria

***Given*** the user is entering a transaction that requires Election Information (example: "Refund of Contribution to Other Political Committee", Schedule A). 

  ***Then*** they will have the option to select one Election Code from the dropdown under "Election Information"

  ***And*** the list will include the following in this order:

*   Primary (P)
*   General (G)
*   Convention (C)
*   Runoff (R)
*   Special (S)
*   Recount (E)

***And*** they will be required to enter an Election Year value (YYYY format)

  ***And*** If they select anything other than ‘Primary’ or ‘General’ then they will be required to enter a value in the Election Description text box (A/N 20).

***And*** upon saving, the Election Code/Year field in the specification will be a concatenation of the Election Code (X) and Year (YYYY) as "XYYYY", with the code mapping as follows:

*   Primary (P)
*   General (G)
*   Convention (C)
*   Runoff (R)
*   Special (S)
*   Recount (E)

![Screenshot 2023-03-29 at 10.46.31 AM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/083205df-a401-43b7-bdb8-4701faa959b5](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/083205df-a401-43b7-bdb8-4701faa959b5))

  ![Screenshot 2023-03-29 at 10.47.28 AM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/9a87eeb4-5189-4d59-8611-de6942f462af](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/9a87eeb4-5189-4d59-8611-de6942f462af))

### QA Notes ###
- Election code and Election Year are required. Election Description is only required if the Election Code is NOT Primary or General.
- Election Description should have "OPTIONAL IF PRIMARY OR GENERAL" in grey text next to the field name.

### DEV Notes ###
- The single digit code and year is what is captured and saved for .fec file for the "Election Code/Year" field in the specification. 
Example: P2022 - if code is P (Primary) and year is 2022

### Design ###
null

 See full ticket and images here: [FECFILE-829](https://fecgov.atlassian.net/browse/FECFILE-829)

**Comment by mjtravers** [comment]
Requests were made in CR for code changes. Sending back to In Progress.

**Comment by mjtravers** [comment]
Code suggestions made. Sending ticket back to CR.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified when selecting adding a "Receipt" - Refund of Contribution to Other Political Committee - the receipt is created and the Election Information data fields are displayed to include:   Election Type dropdown,  Election year, and ELECTION DESCRIPTION (OPTIONAL IF PRIMARY OR GENERAL)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e18b5d66-71de-4108-ad76-b452eb18a389)

Verified Election Type and Election Year are required fields.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/77bf80f8-5b5f-43e8-9a07-c958a26df504)

QA review verified Election Type dropdown is the Election Code (X) as denoted in AC.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f3c32609-7d5e-4ca0-8773-b6d82fe026fe)

@mjtravers @MitchellTCG returned to In-Progress for Election Code dropdown fix.   Should be the following - text bolded and (X) missing:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c34aacf9-c1fd-4b88-bd92-f553aa04e601)

**Comment by mjtravers** [comment]
Election Type dropdown labels have been corrected. Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
Drop down values for election type were bolded for name and not code. Passes CR and ready for QA.

**Comment by WiseQA** [comment]
QA review retesting Election Code and Election Year and Election Description.

Verified Election Type dropdown is name bold (e.g., Primary) Code (x) not bold (e.g., (P) per discussion and decision noted above.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dda002c7-611c-4e3f-85a0-6b61c2eaefd9)

Verified when selection Primary (P) from the Election Type dropdown the Election Year is required and Election Description is Optional.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6d9b484b-0848-40a4-af7e-3a74154524b1)

Verified Election Description is required if the Election Code is **NOT Primary or General**.   Select Convention (C) as example.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f4a6dc68-dcc2-4fa2-afb5-09f18aaa5c16)

QA Review Completed.   Moved to Stage Ready.
