### ISSUE TITLE
Verify tickets 890 and 892 have been commented out of Sprint 22 release

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#949]
User Story

As the COR (Paul), I would like tickets web-app 890 (Allow user to enter Individual Refund - Non-contribution Account) and web-app 892 (Allow user to enter Business/Labor Organization Refund - Non-contribution Account) not to appear in the Sprint 22 release to Stage and Production because there are Calculation issue with the code.

Acceptance Criteria

Please verify that the follow Schedule B's (DISBURSEMENTS) do not show up and are not clickable in the disbursement accordion list:

*   ***Individual Refund - Non-contribution Account***

       (under "Other expenditures) - Should be greyed out
*   ***Business/Labor Organization Refund - Non-contribution Account***

       (under "Other expenditures) - Should be greyed out

Note

890 and 892 will be reviewed and updated in the coming weeks. This is a stop-gap that the client is aware of and has sign-off on.

  — @MitchellTCG

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-828](https://fecgov.atlassian.net/browse/FECFILE-828)

**Comment by WiseQA** [comment]
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bacedd7a-eab2-455e-9cec-f4f45e632a13)

**Comment by WiseQA** [comment]
QA review verified Individual Refund - Non-contribution Account and Business/Labor Organization Refund - Non-contribution Account are not accessible and activated as selectable under the "Add Disbursement" Other Expenditures dropdown list.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/34d916ef-e164-44bd-b5e4-69c3d95bfc57)

QA Review Completed.  Moved to Stage Ready.
