### ISSUE TITLE
UI: Add column for Line Number in transaction lists within a report

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#950]
**Task:** Add a column to the transaction tables on the front-end to indicate the transaction line number. For example, an itemized Individual Receipt on Schedule A is Line 11(a)(i), or a Transfer is Line 12. 

 Acceptance Criteria

**Given** the user is on the "Transactions in this report" page,
**Then** they will see the transaction line numbers in the table
**And** the line numbers will be shown in the format of the DSP, such as 11(a)(i), 12(b), etc.

 Wireframe 

![1057 - Transactions in this report – Loan – 2.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/492ed3f7-abc9-4691-bd8d-07e4d296b5b6)

### QA Notes ### 
  DEV Notes
- This is unlike form type in that we strip out the "SA" or "SB", for example, and letters should be lower case and in parentheses. 

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg We can probably include this with #828, and have one ticket instead of two. Does that work for you both?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
Wires added and DEV NOTES updated

I'm fine with deleting this one but let's ask the devs first.

cc'd:
@mary @JonellaCulmer

**Comment by AureliaKhorsand** [comment]
Messaged Ryan via Slack on 5/17 to inquire if these should be capitalized or not. Waiting for response.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
I talked with @JonellaCulmer this afternoon. Please touch base with her before asking Ryan for input. 

The design was based on the paper form. 
Example attached:
![Screenshot 2023-05-17 at 5.24.56 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d364abd6-c7c8-4154-b898-6215305c9ee4)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG - I had already reached out - in any case, he agrees so we're all in agreement. We will match the formatting of the paper form for when the line numbers are user-facing. I will update ACs and move to ADTR.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified a column was created to identify the Line Number in the "Receipts" and "Distributions" transaction lists per UX design stated in ticket.

"Receipts" transactions showing line number column:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/94643419-f116-44db-8610-1410d8243517)

"Distributions" transactions showing line number column:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/99b3beb7-54b7-4028-b8ab-fa063a3a971f)

QA Review Completed.   Moved to Stage Ready.
