### ISSUE TITLE
UI: Update padding in footer across the entire site

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#953]
User Story 

  Acceptance Criteria

To achieve the 32px of space please use the CSS below.

Currently there are 5 pixels of around the entire footer around and then there are a 8 pixels of padding evenly distribute FEC logo, name, and address and the RAD Analyst text.

![Screenshot 2023-03-29 at 10.13.32 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/2931a649-ec9e-4b84-84ce-60cfd26e358a](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/2931a649-ec9e-4b84-84ce-60cfd26e358a))

***Please make the following change:***

  Change the padding for the area from Padding: 8px (currently it is .5rem which equals 8x)

  to

  padding: 8px 8px 8px 27px;

  (this 27px plus the other 5px will give the site 32px of space).

![Screenshot 2023-03-29 at 10.16.06 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/47e8da2f-2876-49a5-aaac-a737f7dde8bd](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/47e8da2f-2876-49a5-aaac-a737f7dde8bd))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
As the UX Design Lead, I would like the site to reflect the 32px of padding on the left side of the FEC logo, name, and address in the footer that exist in the wireframe, to create more whitespace and breathing room.

 See full ticket and images here: [FECFILE-825](https://fecgov.atlassian.net/browse/FECFILE-825)

**Comment by Elaine-Krauss-TCG** [comment]
CSS Updated accordingly
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/0ecf3591-3220-4e0f-bf48-ec94f5f6073e)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG does this include the Need help ? Contact us .   Ticket is written for footer only?   

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3727ae95-8ff1-4358-89ae-63124fd3ee16)

**Comment by MitchellTCG** [comment]
@Elaine-Krauss-TCG 
sorry for messing where the CSS

Please revert this line:
![Screenshot 2023-05-17 at 8.22.56 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a9faad8d-944a-499e-ab41-8b49d3fbbc81)
to:  padding: 8px

and change the following from (Padding:5):

![Screenshot 2023-05-17 at 8.25.24 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/e37aa418-229f-439a-b160-379242edc9a8)
![Screenshot 2023-05-17 at 8.24.17 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/882c3404-ce9b-481a-a64e-9a90eea5741a)

**Comment by MitchellTCG** [comment]
@Elaine-Krauss-TCG 
please make the above changes and send it back to @WiseQA when you are done

thx

**Comment by Elaine-Krauss-TCG** [comment]
The seal column has uniform 8px padding on each side
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/658fd1a4-463b-4e40-a6a1-bfa303e0b61e)

The upper and lower footer sections now have 27px padding on the left
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/9f338ad9-ae41-4b60-8118-88c5829c27be)
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/42758f18-b919-4b6a-948c-f9c6f4b64607)

**Comment by mjtravers** [comment]
Updates pass CR. Ready for QA on DEV

**Comment by WiseQA** [comment]
QA review verified footer updated per CSS and the  Need help ? Contact us position has been fixed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/80edb29f-f2fc-4c66-b3b1-fea94aeb918a)

QA Review Completed.   Moved to Stage Ready.
