### ISSUE TITLE
Allow user to view list of transactions on submitted report

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#964]
Business Reason 
 

As a user, I will be able to see a detailed list of transactions included on submitted reports so that I can have access to all my data even if the report has been submitted.

 Acceptance Criteria 
 

**Given** a report has been submitted to FEC,
**When** the user opens the report,
**Then** the left-hand navigation will have the option to "Review Transactions" (instead of Manage Transactions), 
**And** when the user clicks it, they will see a list of all the transactions in the submitted report
**And** they will be able to click on the transaction name or use the action kebab to "View" the transactions as read-only (continued in #830)

 Wireframe 

![964 - Allow user to view list of transactions on submitted report – 2.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7110adcb-e5e8-4622-84ed-c04522b4bd96)

### QA Notes ### 
  DEV Notes
- We do not expect the numbers to be frozen with this ticket. Submitted reports as "snapshots" of data will be accomplished in (ticket TBD).

### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
Transaction page changes compared to an in-progress report:
1. Read Only text under the transaction title
2. Grey out the Check box
3. Remove + Save & add more if there
4. instead of Cancel and Save - > Only have a Go back button

We will add the final wire to the top of the page. 

Please review

**Comment by mary-tcg** [comment]
@MitchellTCG @AureliaKhorsand Tentative wire for review ![964 - Joint Fundraising Transfer.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/3dbd07a7-0ce0-439a-82cf-0501f1faf49d)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand  please review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers @toddlees when I select View a transaction I am able to modify fields (e.g., date, amount, address) but not resave transaction.  

Transaction "Viewing"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b68575d3-25a5-4dc8-92b2-0dc017206785)

Same transaction fields are able to change, but cannot save.   If this is "Read-only" should we be able to modify fields even though can't save ?

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c3825173-cb6a-4bbf-9532-35f71a08ca95)

Ticket on-hold for clarification.

**Comment by WiseQA** [comment]
@mjtravers ticket to be kept on-hold until ticket #830 in QA bucket.   Will test both tickets #964 and #830 together to verify functionality.

**Comment by WiseQA** [comment]
QA review verified when selecting a "Submitted" report the "Review Transactions"  is displayed and selectable in the NAV bar.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/12d6d207-f8e6-44d8-a21d-c8b10e9d7423)

Select Review Transactions then select a Transaction for this report in the "Transactions in this report" table. under "Actions" and verify "View" is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/be553e9d-8f9c-4920-a363-332a7fb2d83d)

Select "View" the Transaction page is displayed for the transaction selected to view.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4634bac5-f672-4bc2-a88c-d5a55461dd71)

(NOTE:  UI design for color of button is known, and future ticket will be generated.)

QA Review Completed.   Moved to Stage Ready.
