### ISSUE TITLE
Consolidate Angular group A-M templates into one

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#974]
Although we need the logical code for the transaction group, we can safely merge the Angular component code into one component that will make management of the component code base easier. Currently, the only code that differentiates one component template group from another is the FormGroup fields declaration and the values for the entitly dropdown. The Schedule A and Schedule B versions of a group have been merged into one singular component template and the code can similarly merged across transaction type groups.

***DEV Notes***

It would be good to move the group logic out of the transaction type template and into classes (located in a shared/models/transaction-groups directory) that moved the FormControl and onInit() declarations out of the templates. These TransactionGroupA, TransactionGroupB, etc... classes would replace the TransactionType.componentGroupId with a e.g. TransactionType.transactionGroup = TransactionGroupA; declaration.

1\. The transaction-group-d.component.ts can be referred to as a model of how the transaction types can be managed in one component.

  2\. The html templates are already very similar and need to reviewed to make sure all HTML elements make it into the single composite HTML template file.

  3\. Unit tests will need to be merged as well.

***QA Notes***

  This is a strictly front end change that will pass QA mainly if unit tests and e2e tests pass successfully.

### QA Notes ###
**DEV Notes**

It would be good to move the group logic out of the transaction type template and into classes (located in a shared/models/transaction-groups directory) that moved the FormControl and onInit() declarations out of the templates. These TransactionGroupA, TransactionGroupB, etc... classes would replace the TransactionType.componentGroupId with a e.g. TransactionType.transactionGroup = TransactionGroupA; declaration.

1. The transaction-group-d.component.ts can be referred to as a model of how the transaction types can be managed in one component.
2. The html templates are already very similar and need to reviewed to make sure all HTML elements make it into the single composite HTML template file.
3. Unit tests will need to be merged as well.

**QA Notes**
This is a strictly front end change that will pass QA mainly if unit tests and e2e tests pass successfully.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-822](https://fecgov.atlassian.net/browse/FECFILE-822)

**Comment by mjtravers** [comment]
Some clarifications and comments from the CR are going to be implemented in the code. Sending back to In Progress.

**Comment by dheitzer** [comment]
Discussed changes with Matt and Gregg yesterday and pushed requested CR fixes to the PR.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
Screenshot of passing unit tests:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/2a58cf36-5d1a-4e21-91ab-0199bc0bd7fe)

**Comment by WiseQA** [comment]
QA review completed using DEV passing unit test.   No further testing on QA part that can confirm change.

QA review completed with DEV screenshot inspection ...  Moved to Stage Ready.
