### ISSUE TITLE
Clean up warning messages in front-end unit tests

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#977]
There are a large number of warning messages being displayed in the front-end unit test output:

  ![image.png]([https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/b6997b67-2791-432c-9f09-a6298c86bcc2](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/b6997b67-2791-432c-9f09-a6298c86bcc2))

There appear to be 2 types:

1\. NG303 is output when a component is not properly declared in the unit test

  2\. Using the disabled attribute in the HTML template when using Angular reactive forms

For the disabled attribute warning, the best solution could be creating an angular directive that can use the reactive forms but bundle the code to do it in one place, a newly created directive that can be added to the attribute of the HTML element using the disabled attribute.

***QA Notes***

  Update 5/1: After working through all the error and warning messages being displayed by the unit tests, it has been determined that a number of the blue warning messages are not relevant to our code functioning or being triggered by a necessity of a unit test itself. QA will depend then on getting a screenshot with warnings but with 100% successful test passage.

### QA Notes ###
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/b6997b67-2791-432c-9f09-a6298c86bcc2)

There appear to be 2 types:

1. NG303 is output when a component is not properly declared in the unit test
2. Using the disabled attribute in the HTML template when using Angular reactive forms

For the disabled attribute warning, the best solution could be creating an angular directive that can use the reactive forms but bundle the code to do it in one place, a newly created directive that can be added to the attribute of the HTML element using the disabled attribute.

**QA Notes**
Update 5/1: After working through all the error and warning messages being displayed by the unit tests, it has been determined that a number of the blue warning messages are not relevant to our code functioning or being triggered by a necessity of a unit test itself. QA will depend then on getting a screenshot with warnings but with 100% successful test passage.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-821](https://fecgov.atlassian.net/browse/FECFILE-821)

**Comment by Elaine-Krauss-TCG** [comment]
Cleaned up 147 errors and 3 warnings, comprising about 75% of the length of warnings/errors (see size of scrollbar) in the browser dev console when unit tests are run.

Of the remaining issues
 - 1 type of errors remain
    - 2 (NG04002) invalid route errors (these are likely the same error)
 - 1 type of warnings remain
    - 118 [disabled]="X" style warnings (the cure might be worse than the disease)



![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/3bb895e8-d6f2-4eb9-87ad-3c40e9ee933a)

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/9da7018c-5af9-42c4-9f8e-00a230fa7d25)

**Comment by mjtravers** [comment]
Screenshots for QA:

![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/a34bb773-2434-4788-8990-7f0f1e8a8196)

![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/44686e8b-f743-4e25-b32c-39c6f8959806)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review visual inspection with DEV per screenshot above.

QA Review Completed.   Moved to Stage Ready.
