### ISSUE TITLE
System to mark termination report in Form Type and Report Code

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#98]
Business Reason 
 

As a user, I will be able to create a Termination report for Form 3X so that I can submit my final report to FEC through FECfile Online.

 Acceptance Criteria 
 

**Given** the user is selecting a Form 3X report type and is either a Monthly or Quarterly filer,
**When** the user selects the report type of Termination and creates the report
**Then**:
- The Form Type field will be stored as F3XT 
- Report Code will be TER 

Dev Notes:
- Termination Report is already an option for selection on the Report Type selection screen.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
Now included in #135 as another report type. Closing as a duplicate.

**Comment by AureliaKhorsand** [comment]
BA Note: include form type and report code information in this ticket; can select larger coverage date.

Header row should indicate that it is a Termination Report (for example, F3XT).

Once a Termination report is filed, users should NOT be able to create new reports (but they can still amend them). We should potentially base this logic on Filing Frequency = T, which will be updated by FEC.

**Comment by WiseQA** [comment]
QA Review was completed by DEV team providing this outcome, verbally there is no visual inspection on this ticket by QA.   This ticket passes by the input by the DEV team, which isn't good QA practice.  However, as discussed e2e testing will be conducted on this ticket.

QA reviewed by DEV team and not QA actual inspection, by DEV team lead to proceed.  Ticket moved to Stage Ready.
