### ISSUE TITLE
System to prevent user from saving new contact with existing Committee or Candidate ID 

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#990]
Task: Prevent users from saving new contacts that share the same Committee or Candidate ID as an existing contact in Committee Account.

Acceptance Criteria

***Given*** that I am creating or editing a new contact in Contact Management or within a transaction,

  ***If*** the new committee or candidate contact I am trying to save matches the Committee ID or Candidate ID (respectively) of an existing contact in my Committee Account,

  ***Then*** I will be unable to save that new contact, and the system will indicate the reason.

Dev Notes

  Check on front _and_ back-end to guard against edge cases.

Wireframe

1.  FEC ID's must be unique.

       ![990 - Unique IDs.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/116ce995-0eda-4edc-b3bf-71fc91cf8527](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/116ce995-0eda-4edc-b3bf-71fc91cf8527))

### QA Notes ###
Note: This will be when creating and editing a contact in a transaction **and** in Contact Management.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-819](https://fecgov.atlassian.net/browse/FECFILE-819)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg can we get a warning message for the user for this ticket? Simple is fine - we just want to functionally prevent this from happening.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
I added wireframes to this ticket that correspond to Todd's suggested solution.

**Comment by mjtravers** [comment]
There are a couple of small requested changes from CR. Sending back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the Committee ID field displays the "FEC IDs must be unique" error when entering an existing Committee ID.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f25cb4d6-feff-4ebd-b476-92a4ae7b0aee)

QA review verified the Candidate ID field displays the "FEC IDs must be unique" error when entering an existing Candidate ID.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0f919bc9-f717-4290-a413-9028ad35e227)

QA Review Completed.   Moved to Stage Ready.
