### ISSUE TITLE
UI: Fix RED Background overlay

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#997]
User Story:

As a UX Lead, I would like the translucent Overlay behind the Create Report Modal to be Black as god intended.

Task:

*   [ ] Change the current red overlay background seen here:

      ***CURRENT CSS*** > maskbg: rgba(166, 27, 27, .4)

      ![Screenshot 2023-04-21 at 2.04.09 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f499e7a7-ae14-49fa-b6c1-26966459e65c](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f499e7a7-ae14-49fa-b6c1-26966459e65c))

CHANGE TO:

*   [ ] Change overlay to black EXAMPLE below:

      ***UPDATE CSS*** > maskbg: rgba(0, 0, 0, .4);

      ![Screenshot 2023-04-21 at 2.04.01 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d646429d-f9f4-4ce8-bd69-e18619709616](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d646429d-f9f4-4ce8-bd69-e18619709616))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-817](https://fecgov.atlassian.net/browse/FECFILE-817)

**Comment by Elaine-Krauss-TCG** [comment]
Fixed by changing one value in the stylesheets.  Verified on the Manage Reports page, the Manage Contacts page, and on transaction forms.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/03e7b6ed-7419-4c4d-aa62-6700163de72a)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified red background overlay has been changed to black EXAMPLE below:
UPDATE CSS > maskbg: rgba(0, 0, 0, .4); per UI direction.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1c06a8b9-acde-45f7-aeaf-70c3569e11ac)

QA Review Completed.   Moved to Stage Ready.
