### ISSUE TITLE
UI: Please update Font and Weight of Error Messages

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#998]
User Story 

As the UX Lead, I would like the error messages to match the styling of the wireframes so they are more legible for users with accessibility issues. 

 Issue 

Currently the error text is too light to see. It is currently 
Font: Times 
the width is just Times regular
EX.
![Screenshot 2023-04-21 at 2.10.37 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/958cdf5a-f6ba-41e6-bcf3-52a397982977)

Task 

Please update the CSS of the Error messaging so the font is Karla and the weight is bold.
- [x] font-family: karla;
- [x] font-size: 13px;
- [x] font-weight: bold;

 Wireframe 

![Screenshot 2023-04-21 at 2.17.51 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7cf58df8-8a46-4890-b4b6-f10c82c5a7e6)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG to update ticket with what pages have this validation text

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified error messages font and weight has been modified per the CSS the font is Karla and the weight is bold.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/04f26e16-5ebb-46bc-a016-801db3e19d42)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e373ad1b-cbda-4df3-aa98-77a7c29c9c70)

QA Review Completed.   Moved to Stage Ready.
