### ISSUE TITLE
UI: Update logo in upper left corner of pages without the bar nav bar - PART 2

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#999]
User Story

As a UX Lead, I would like the New FECFile Logo not to appear when there is a Left nav and i would like the Logo to take the user to the Dashboard when clicked.

Tasks

*   [x] When the user clicks the FECFile logo, the link will take the user to the Dashboard

       ex. [https://fecfile-web-app-dev.app.cloud.gov/dashboard](https://fecfile-web-app-dev.app.cloud.gov/dashboard)

*   [x] Whenever there the left nav is visible, the New FECFile should disappear.

Wireframe

#Without Left Nav 

  #

  ![Screenshot 2023-04-21 at 2.40.45 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/85eb478d-578a-410a-8347-f0dff1087199](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/85eb478d-578a-410a-8347-f0dff1087199))

1.  With Left Nav

       #

       ![Screenshot 2023-04-21 at 2.40.01 PM.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/25c21a00-adb0-4f1b-b198-82963621cf26](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/25c21a00-adb0-4f1b-b198-82963621cf26))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-815](https://fecgov.atlassian.net/browse/FECFILE-815)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA Review completed.   Verified new FECFile Logo does not to appear when there is a Left nav.   Click the new FECFile  Logo to take the user to the Dashboard when clicked.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b716e029-317d-4a37-ae9c-f6ce45452b5b)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ea3d70f1-01f5-4a82-b6ad-69853bab2486)

QA Review Completed.   Moved to Stage Ready.
